### ISSUE TITLE
Magic mode should use Object.observe() where possible

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1002]
Now that it's landed in Chrome stable, it would make sense to use `Object.observe()` over `Object.defineProperty()` to detect changes to data.

Advantages:

* It ought to be a good deal faster
* We don't need to muck about with the object, replacing data with get/set accessors
* We don't need to preemptively observe keys that may not be relevant (due to context ambiguities)
* We can probably ship stable support for Oo before Angular :-)

Disadvantages:

* It's more code (though hopefully not much), since we need both solutions until other browsers implement Oo.

On the final point, we could argue that the magic/array adaptors shouldn't be built-in, but should be shipped separately. That's a separate conversation though.

**Comment by dotnetCarpenter** [comment]
How about having `ractive.unobserve(keypath)`

**Comment by evs-chris** [comment]
> How about having ractive.unobserve(keypath)?

You should be able to use the return value to remove the observer with `cancel()`. See http://docs.ractivejs.org/latest/ractive-observe

**Comment by martypdx** [comment]
@dotnetCarpenter Also, see `{ defer: true }` on observe arguments for post-DOM firing of observers.

**Comment by dotnetCarpenter** [comment]
@evs-chris I missed that.
However setting properties on the ractive instance is observable but not in a meaningful way.
The code below always prints "setExplicitHeight is set to true"
```js
// set explicit height allow for animating the height
this.observe("setExplicitHeight", function(newValue) { this.info("observe setExplicitHeight");
  var yes = newValue || this.setExplicitHeight;
  var ch = this.changeHeight.bind(this);
  var observer; console.warn("setExplicitHeight is set to %s", yes)
  if(yes) {
    observer = this.observe("currentMoment", function() { this.info("observe currentMoment");
      // changeHeight after ractive has updated the DOM (racy)
      window.setTimeout(ch, 100);
    });
  } else {
    console.log("cancel currentMoment observer");
    observer.cancel();
  }
});
this.set("setExplicitHeight" ,false);
```
Setting *setExplicitHeight* on the data object however works. Too bad, kinda liked to have component properties on the component and only have template date/functions on the data object...

**Comment by dotnetCarpenter** [comment]
@martypdx Unfortunately, even with the defer option, it is still too early. Not sure why.
I'm measuring the height of a table with rows managed by Ractive and setting the height of a wrapper, which I have a css height transition for.
```
<div class="datepicker-table-wrapper">
  <table class="datepicker-table {{enableKeyNavigation ? selectionClass : ''}}">
```
```js
changeHeight: function() { this.info("changeHeight");
    var newHeight = $(this.find(".datepicker-table")).height();
    $(this.find(".datepicker-table-wrapper")).height(newHeight);
  }
...
// in this.observe("setExplicitHeight"
if(yes) {
  observer = this.observe("currentMoment", function() {
    // changeHeight after ractive has updated the DOM
    ch()
  }, { defer: true });
} else {
  observer.cancel();
}
```
I don't have a problem with using setTimeout though.

**Comment by dotnetCarpenter** [comment]
I've had all kinds of bugs in my component showing up after using `observer.cancel();`. It turns out that this cancel all observers on that path. Since I got a two-way binding setup automatically by Ractive and need that to stay there, I can't use the current cancel implementation.

I update a calendar whenever *currentMoment* changes.
```js
// calendarDays to display
, calendarDays: function() { this.info("calendarDays");
    //console.dir(arguments);
    var perfTiming = performance.now();
    var calendarDays = this.getCalendarDays(this.get("currentMoment"));
    console.log("Days took: ", performance.now() - perfTiming);
    return calendarDays;
    //return this.getCalendarDays(this.get("currentMoment"));
  }
```

**Comment by mefjuu** [comment]
What about stopping Object.observe support? https://mail.mozilla.org/pipermail/es-discuss/2015-November/044684.html

**Comment by Rich-Harris** [comment]
@mefjuu yep, we can strike that off our TODO list :-)

**Comment by arxpoetica** [comment]
FYI, I don't think the discussion is over...https://mail.mozilla.org/pipermail/es-discuss/2015-November/044691.html

**Comment by Rich-Harris** [comment]
If the discussion goes anywhere we could certainly reconsider it, but in the meantime it definitely seems like a low priority since the only engine that supports it is planning to kill it off. So I'll close this.

As for the other issue raised by @dotnetCarpenter (in February... :grimacing:), it looks like that's resolved in recent versions: http://jsfiddle.net/rich_harris/b718zw4b/

**Comment by dotnetCarpenter** [comment]
@Rich-Harris yep looks like it is solved. I hope I get a change to revisit my calendar code and open source it within the next few months. It's pretty entangled in a project with a NDA.
