### ISSUE TITLE
Non-existing path and Attempted to unrender a fragment that was not rendered

### ISSUE THREAD

**Issue by Thaylon** [ractivejs/ractive#1003]
Hi, Im preparing to do some semiheavy lifting with ractive and am currently scouring s.o. to get a feel for what awaits me.

I came across one issue that seems to be a bug. The combination of testing for the non-existance of a restricted reference while binding the same to the value of a select produces weird results.

http://jsfiddle.net/W3Lus/13/

Wont render at all and throw "Attempted to unrender a fragment that was not rendered".

http://jsfiddle.net/W3Lus/12/

Renders the select but then fails to render the "y".

I suppose binding the prior non-existing value to a select implicitly initializes it, so its understandable that it exists afterwards, but still quite counter-intuitive.

**Comment by esbhome** [comment]
I have the same problem. 
I use this **tamplate**: 
....
`{{#header:f}}
                <td class="wt_{{f}}">
                    <div class="sel-table">
                        <label>{{label}}</label>
                        {{#type}}
                        <**exchange-filter** params="{{data}}" param="{{cur}}" name="{{f}}" on-changed="filter_changed"/>
                        {{/}}
                    </div>
                </td>
                {{/}}`
**exchange-filter** is:
`<select class="form-control" value='{{param}}' on-change="changed" name="{{name}}">
    {{#params:k}}
    <option value="{{k}}">{{.}}</option>
    {{/}}
</select>`
and when I set data (this.set('header.col_name.data', {all: "all", s: "S", g: "G"}) I catch that exaption ( "Attempted to unrender a fragment that was not rendered" ) 
http://prntscr.com/alresk - in this screen we can see that in first time all ok (oninit event) but after data loaded and updated I have an error.

After some attempts to fix that I found this solution:
`this.set('header.col_name.data', false);
this.set('header.col_name.data', {all: "all", s: "S", g: "G"});`

**Comment by evs-chris** [comment]
@esbhome can you give us a working (well, failing) example as a fiddle or pen?

**Comment by esbhome** [comment]
Sorry, I don't know how I can show you only that part of my application... Because I am not sure that when I will do a simple version of my code I can repeat error. Maybe you can look to my app?

**Comment by esbhome** [comment]
http://jsfiddle.net/ont7prx1/44/
But I cannot repeat error on fiddle. On that link I created a simple version of my app. I don't know why dont work observe of orders var and I created update button (On my app that works fine). When hit del button fires event unrender and on content place rendered new Ractive object and after 4 sec replace back. On my app when 1 Ractive obj is rendered I hit to render another Ractive obj to content place and then come back and I have an error on my app, but on fiddle I have not.

**Comment by esbhome** [comment]
I found the interesting moment.
On console.log I see this sequence - http://prntscr.com/amlq7s, but when fire error in profile I see another sequence - http://prntscr.com/amlqm1. Function which fire error this - http://prntscr.com/amlqw1

**Comment by esbhome** [comment]
I found that works if I in event onunrender dont change my selects and after I came back they remain in the same state.

**Comment by esbhome** [comment]
Please help me with https://github.com/ractivejs/ractive/issues/2527

чт, 31 мар. 2016 г. в 2:02, Chris Reeves <notifications@github.com>:
