### ISSUE TITLE
Question: CSS animations for transitions?

### ISSUE THREAD

**Issue by rstacruz** [ractivejs/ractive#1008]
Is there a `transitions` adaptor out there today to perform transitions as basic CSS animations? It'd be nice to be able to do, say:

``` js
<div intro="animate:fadein">
```

...which will add the `fadein` class to the element and wait for the `animationend` event. I believe this is easily achievable, but I was wondering if there was already a plugin written for this.

**Comment by constantx** [comment]
@julianshapiro @Rich-Harris would love a velocity-power transition plugin as well :)

**Comment by constantx** [comment]
@cfenzo just checkout your `ractive-transitions-velocity`, look like it still has jQuery dependency, any plan to migrate?
