### ISSUE TITLE
Transitions never complete if nodes are removed from DOM prematurely

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1015]
This is a real edge case, but one I've encountered while rebuilding learn.ractivejs.org. When nodes that are undergoing an outro transition are removed from the DOM by some external force (e.g. an ancestor node has `node.innerHTML = ''` done to it), the CSS `transitionend` event is never fired. As a result, the outro is never considered to have completed, and other nodes fail to detach from the DOM.

Example: http://jsfiddle.net/rich_harris/j3KJ7/

**Comment by Madgvox** [comment]
I'm closing this since I feel like this will get solved when ~~browsers have decent mutation apis~~ hell freezes over.
