### ISSUE TITLE
Support multiple checkboxes

### ISSUE THREAD

**Issue by dodyg** [ractivejs/ractive#103]
This tutorial only shows support on a single textbox (http://learn.ractivejs.org/#!/two-way-binding/2)

How do you get/set values for multiple textboxes?

```
{{#FormData.Lookup.Targets}}
      <label class="checkbox"><input type="checkbox" name="target" value="{{Id}}"/>{{Name}}</label>                    
{{/FormData.Lookup.Targets}}

```

**Comment by esbhome** [comment]
Hi! Today that problem have again.
ractive-bootstrap.js we have .....<input name="{{name}}" type="radio" .......
and when I try use tag 'name' of input I have in HTML - <input name="{{name}}" type="radio"
Why? What can I do?
If I change template to this .... <input name_="{{name}}" type="radio" ....
as result I have in DOM - <input name_="foo" type="radio"
Please, halp me!

**Comment by evs-chris** [comment]
If you're trying to get the name attribute to show up in the actual DOM, you should be able to to add a twoway directive to the input e.g. `<input type="radio" name="{{name}}" twoway="false" ... />`. Ractive uses the `name` attribute with a single mustache as flag to set up a two-way binding by default. You could also disable two-way for the whole instance by passing `twoway: false` as on option when Ractive gets initialized.

**Comment by esbhome** [comment]
ohh YES! Thank you very much!!!

ср, 16 мар. 2016 г. в 4:27, Chris Reeves <notifications@github.com>:
