### ISSUE TITLE
Being tripped up by ractive's event handling

### ISSUE THREAD

**Issue by dantman** [ractivejs/ractive#1037]
I'm implementing 2 components with ractive.
A) A special type of button. This can optionally 'own' a menu that opens when the button is activated.
B) A popup navigation menu. This is 'owned' by a button, and positions itself relative to that owner when opened.

I've got this all implemented fine, up to the advanced handling of events on the button.

For normal actions a simple on-click='activate' handler is enough, but when a menu is owned there are a number of special behaviours needed.
A) On click/tap focus should stay on the button and the menu should open or close.
B) On keydown enter/space the same should happen, but when opened the first item should be focused.
C) On arrow{up,down} a closed menu should be opened (no closing this time) and the first item should be focused.
D) On escape the menu should be closed if open.

The problem lies with tying the two components together, :
A) on-click is not enough, I need keydown and I need to preventDefault/stopPropagation both, so I need to bind actual listeners rather than on-x attributes.
B) If I bind these events in my button's init I can't fire similar events to on-x (node, original, context, etc...) without hardcoding Ractive's behaviour littering my code with duplications of ractive internal code (and there's no way to insert something like a `this.fireFromEvent` into my extended ractive base type's prototype).
C) If I instead use events: to create a new on-active type of event I can fire normal on-x like events. But these have no context so they don't know if some of the menu activate behaviour should apply and I'd need a separate conditional on-x for the esc behaviour.

**Comment by Rich-Harris** [comment]
Will close this as it's been inactive a while - @dantman shout if you're still experiencing problems
