### ISSUE TITLE
Proxy events do not work in nested components

### ISSUE THREAD

**Issue by fcamarlinghi** [ractivejs/ractive#1043]
New to Ractive but already loving it, especially components! It seems though that proxy events are somewhat broken when it comes to nested components:

``` html
<mycontainer>
  <!-- Events won't work on the following: -->
  <mybutton label="Test button" on-myclick="buttonClick" ></mybutton>
</mycontainer>
```

You can see this behavior in action in this [fiddle](http://jsfiddle.net/e2x6S/3/). Am I missing something obvious or is it a bug?

**Comment by 14to9** [comment]
Hi guys, it seems that proxy events might have a bug when used in partials with explicit contexts, too?

When I fire a proxy event from within a partial referenced thusly:

```
{{ > partial { foo: "bar" } }}
```

The generated event has what appears to be a wholly corrupt keypath value (browser console output):

```
component: Object...
context: Object...
index: Object...
keypath: "${{foo:"bar"}}"
name: "myClickEvent"
node: a.test-button: MouseEvent
__proto__: Object...
```

Certainly not the string I was expecting for `keypath` ..

**Comment by martypdx** [comment]
@14to9 That's the expected result. The `context`, `index` and `keypath` are determined by the containing context in the template. This:

```
{{#each items}}
  {{ > partial { foo: "bar" } }}
{{/each}}
```

really is syntax sugar for:

```
{{#each items}}
  {{#with { foo: "bar" } }}
    {{ > partial }}
  {{/with}}
{{/each}}
```

So if you really want to pass `foo: "bar"` as part of the partial context, then also explicitly add the outer context keypath:

```
{{#each items}}
  {{ > partial { foo: "bar", item: this, keypath: @keypath } }}
{{/each}}
```

Then in your event you can access:

`this.event.context.keypath`

**Comment by 14to9** [comment]
@martypdx Thanks very much for the thoughtful and timely response.  :+1:

I hadn't seen the `@keypath` binding before, I'll dig into that too
