### ISSUE TITLE
Components and custom element container

### ISSUE THREAD

**Issue by matthewrobb** [ractivejs/ractive#1048]
I am trying to use Ractive Components but the custom element gets stripped out of the rendered dom.

If I include the element wrapper in the template then it's cyclic and broken.

Given template:
```
<my-widget>Foo</my-widget>
```
with a component template of:
```
<strong>{{>content}}</strong>
```
I would like the resulting dom to be:
```
<my-widget><strong>Foo</strong></my-widget>
```

I simply cannot see any documentation or existing issues covering what seems to me like a VERY common case?

**Comment by matthew-dean** [comment]
Does any of this discussion change now that Shadow DOM has been updated to a v1 spec that's now being implemented in browsers? - https://w3c.github.io/webcomponents/spec/shadow/

I think it's reasonable to assume that at *some point* in the future, writing <my-element></my-element> in a Ractive template would render <my-element></my-element> in the DOM, for better isolation of components and more consistency with the ideas of custom elements (and a lighter DOM being inserted / removed, no?). Or is performance still faster to insert an entire copy of the DOM fragment per component instance?

The other thing that would be nice with using actual custom elements is isolation of styles. Or, some other way to manage local styles with Ractive.

**Comment by Madgvox** [comment]
I feel like if/when we decide to discuss Shadow DOM, it's separate enough from this topic to stand as its own issue.
