### ISSUE TITLE
Link to external stylesheets from a component

### ISSUE THREAD

**Issue by KP** [ractivejs/ractive#1051]
The encapsulation of component-specific styles is awesome. Writing CSS directly in these components, however, is less than ideal (can't use CSSComb). It'd be great to be able to link to external stylesheets from inside a component and have those styles be encapsulated.

Was thinking an implementation like this:

``` html
<link rel='ractive' href='style.css'>
```

**Comment by evs-chris** [comment]
The ractive cli helper can parse components in much the same way as rcu, but aims to produce es modules rather than amd or commonjs modules thus punting loading to the user in a build step/runtime loader. It supports external scripts, partials, and stylesheets.
