### ISSUE TITLE
Support relative and absolute key paths in ractive.get / ractive.set

### ISSUE THREAD

**Issue by chanon** [ractivejs/ractive#1058]
As Ractive templates support relative and absolute key paths ( eg. `{{../path.to.key}}` ) it would be great if the `ractive.get` and `ractive.set` methods support it too.

The current work around is to pass in any data needed in computed properties / event handlers as template arguments from the parent. 

This works but:
- It pollutes the parent template when there is a lot of data needed.
- I'm running into performance problems in Firefox when each child component in a large list takes the same big data object as a template parameter.

Additionally, there is another inconsistency in data references in child component templates and `ractive.get` which is when isolated is false `{{ key.In.Parent }}` works but `ractive.get("key.In.Parent")` does not work.

Fixing these inconsistencies will also help make the usage of Ractive more consistent with less gotchas for newcomers.

BTW, I would actually prefer the latter case to be implemented first as it is more commonly required.

**Comment by nitriques** [comment]
Would it be overkill to offer this in templates as well ?

I have a case of

```html
{{#tags:i}}
	<div>{{value}}
		<button on-click="tagDelete: {{ i }}" type="button">X</button>
	</div>
{{/tags}}
<input on-newvalue="tagChanged" list="tags" value="" style="width:100%" />
<datalist id="tags">
	{{#tags.in.parent}}
		<option value="{{ value }}">{{ id }}</option>
	{{/tags.in.parent}}
</datalist>
```

But sadly, the only thing I can do right now is rename the 'tags' member in the parent...

**Comment by nitriques** [comment]
Note that handlebars does it via ../ (just like unix-paths)

> Nested handlebars paths can also include ../ segments, which evaluate their paths against a parent context.

**Comment by martypdx** [comment]
@nitriques Isn't that how it works in templates now?

**Comment by martypdx** [comment]
Or do you mean into the parent component?

**Comment by nitriques** [comment]
> @nitriques Isn't that how it works in templates now?

No, it does not works.

> Or do you mean into the parent component?

No I do not have any components involved. Just a regular template with nested objects as data.

```js
var ractive = new Ractive({
	debug: true,
	el: main,
	template: (function (template) {
		var t = template.html();
		template.remove();
		return t;
	})($('#template')),
	data: {
		    channels: [],
		    tags: []
		    selection: {
                        tags: [],
                        channels: []
                    },
        }
});
```

When the context is `selection`, I can't access the "siblings" values in the template.

**Comment by Madgvox** [comment]
Check out the 'ancestor references' section here: http://docs.ractivejs.org/latest/references.

You should be able to reference the parent `tags` by referring to it as `../tags` in your keypaths.

**Comment by nitriques** [comment]
Hum... like this ?

```html
<datalist id="tags">
    {{#../tags}}
        <option value="{{ value }}">{{ id }}</option>
    {{/../tags}}
</datalist>
``` 

Or should I explicitly use {{each}} on this to make it work ?

**Comment by martypdx** [comment]
Here's an example (http://jsfiddle.net/pw981otd/):

```html
    {{#child}}
    {{#tags:i}}
        <li>{{.}}
            <ul>
                {{#../../../tags}}
                <li>{{.}}
                {{/}}
    {{/}}
    {{/}}
```

```js
var ractive = new Ractive({
    el: 'main',
    template: '#template',
    data: {
        tags: [ 'one', 'two', 'three' ],
            child: {
                tags: [ 'red', 'blue', 'gree' ]
            },
        }
});
```

**Comment by nitriques** [comment]
Ooooohhhh. Nice! Thanks a lot !

**Comment by martypdx** [comment]
Tricky part is remembering the context of the thing you're iterating:

```
../  --> 'red' to child.tags
../  --> child.tags to child
../ --> child to root
tags --> root.tags
```

**Comment by nitriques** [comment]
Yeah totally. Thanks a lot for the clarification.

**Comment by nitriques** [comment]
I my case, I think it would be easier to use the restricted reference for the child tags and keep the names separated... it makes the code easier to reason about...
