### ISSUE TITLE
RactiveJS causes issues with ESRI Dojo JSAPI library.

### ISSUE THREAD

**Issue by donnyv** [ractivejs/ractive#1093]
For some reason adding RactiveJS with ESRI's Dojo JSAPI library causes an error in the JSAPI library.
Just adding these 2 script tags causes an error.

```
<script src="http://js.arcgis.com/3.10compact/"></script>
<script src='http://cdn.ractivejs.org/latest/ractive.js'></script>
```

ESRI's JSAPI home page.
https://developers.arcgis.com/javascript/

**Comment by dmfenton** [comment]
Here's a solution to a related problem with Angular https://github.com/Esri/angular-esri-map/issues/38#issuecomment-91439901
