### ISSUE TITLE
Add built-in identifiers inside Ractive templates

### ISSUE THREAD

**Issue by skyrpex** [ractivejs/ractive#1097]
Let's say I have this template:

``` html
<form on-submit="submit">
    <input type="text" value="{{ name }}" placeholder="Write your name...">
    <input type="text" value="{{ phone }}" placeholder="Write your phone...">
    <input type="text" value="{{ message }}" placeholder="Write a message...">
    <input type="submit" value="Submit">
</form>
```

Then, I would like to focus the message input everytime the form is submitted. Normally, I should use a CSS class or an ID. It would be awesome if Ractive had some built-in identifiers, so I don't have to pollute the final HTML with ID's or classes. An example:

``` html
<form on-submit="submit:message">
    <input type="text" value="{{ name }}" placeholder="Write your name...">
    <input type="text" value="{{ phone }}" placeholder="Write your phone...">
    <input rid="messageInput" type="text" value="{{ message }}" placeholder="Write a message...">
    <input type="submit" value="Submit">
</form>
```

``` javascript
Ractive.extend({
    template: template,
    init: function () {
        this.on('submit', function (event, message) {
            event.original.preventDefault();
            this.set('message', '');
            // Get element by ID
            this.elements.messageInput.focus();
        })
    }

```

The final rendered HTML shouldn't have the rid="messageInput" (that's the point I'm talking about). I need this because my template will have arbitrary input elements with arbitrary classes, which I won't have control at all.

Regards!

**Comment by papas-source** [comment]
any updates on this?

**Comment by evs-chris** [comment]
The decorator should work using the `onrender` or `oncomplete` events, so I'm going to close this :smile:
