### ISSUE TITLE
How to correctly and completely remove child components ?

### ISSUE THREAD

**Issue by batmandarkside** [ractivejs/ractive#1105]
Why when I call in FilterPanel.teardown() , the property at the data of child components remain live and more? 

When I create a new component FiltrPanel with the new model, I'm counting the old components are completely removed and will create new

I am sorry for my english.

     var FilterPanel = Ractive.extend({
                template: $templateCache.get('components/filter-panel/templ/panel.hbs.html'),
                append: true,
                data: {                  
                    filtersModel: null
                },

                partials: {

                },
                components: {
                    'IndicatorFilters': IndicatorFilters,

                    'FilterTime': FilterTime,
                    'FilterAirline': FilterAirline,
                    'FilterAirPort': FilterAirPort,
                    'FilterAviaLegs': FilterAviaLegs,

                    'FilterExtra': FilterExtra,
                    'FilterPrice': FilterPrice,
                    'FilterName': FilterName,
                    'FilterSlider': FilterSlider,
                    'FilterStars': FilterStars,
                    'FilterTaFactor': FilterTaFactor,
                    'FilterType': FilterType,
                    'FilterSort': FilterSort
                },

                init: function () {
                   
                    this.on({                        
                        teardown: function (evt) {
                            console.log('teardown FilterPanel');

                            // I did not have to do it hands
                            this.findAllComponents().forEach(function (child) {

                            })
                        }
                    })
              }
    });

**Comment by Madgvox** [comment]
I'm not really clear on what the possible "enhancement" is in this thread, so I'm closing it. Feel free to reopen and clarify what I'm missing.
