### ISSUE TITLE
Multiple checkboxes in a form

### ISSUE THREAD

**Issue by mweissen** [ractivejs/ractive#1113]
Sorry, I am here again after a week.

I could not find any way to use ractivejs with a form containing more than one checkbox.
It is possible to use the two-way-binding (box11, box12) **or** to get the checked values as get-argument, (box21, box22) but **not both**. 

<!doctype html>
<html>
<head></head>
<body>

	<script src='file:ractive.js'></script>
	<h2>Versuch 7d </h2>
	<div id="main"></div>
    
	<script id="template" type="text/ractive">
		
		<form action="#" method="get">			
			<input type="checkbox" value="box11"  name="{{box1}}"> Box11 checked="{{box11}}"<br> 
			<input type="checkbox" value="box12"  name="{{box1}}"> Box12 checked="{{box12}}"<br> <br>

			<input type="checkbox" value="box21"  name="box2"> Box21 <br> 
			<input type="checkbox" value="box22"  name="box2"> Box22 <br> <br>

			<input type="submit"><br> 
		</form>
		<br/>
		Box1: {{box1}} <br/>
	
	</script>

	<script>
		alert(window.location);
		var ractive = new Ractive({
			el: 'main',
			template: '#template',
			data: {
				box11: false,
				box12: false,
			}
		});
	</script>
	
</body>
</html>

Any ideas how to solve this problem?
Regards, Martin

**Comment by Madgvox** [comment]
I'm closing this as I am reasonably sure that this issue has been fixed.
