### ISSUE TITLE
Missing styles when rendering with toHTML()

### ISSUE THREAD

**Issue by PhilJ** [ractivejs/ractive#1127]
I would like to render an initial page (which consists of nested Ractive components) on the server with `toHTML()`. 

Loading the component with `ractive-load` and rendering works fine - however **the output of `toHTML()` lacks any css code** - both the styles of the root component as well the styles of the nested components are not present in the output.

This is fine for providing a server-rendered page with search crawlers, however this page would not work to pre-render Ractive views for users, since no styles would be present.

**What are my options to add the styles of all used components in the server-rendered output when using `toHTML()`?**

Including the styles via `<link rel="stylesheet" ..>` might be an option, but i'd like to avoid that, since this would mean that styles would no longer be present in the ractive component file. Furthermore the client would need to load all component stylesheets seperately.

The styles are present under the `.css` respectively `.components[COMPONENT_NAME].css` properties of the loaded component - so i could get and concat them from there. However the output of `toHTML()` also does not include the `data-rvcguid` properties in the markup to make use of Ractive's css scoping.

 Any ideas? Thanks for your support!

**Comment by ElliotChong** [comment]
I've been thinking through what it might take to get this working on the server-side... Would a possible interim solution be to expose a `toCSS()` method that is outputting the composed CSS? It would then be possible to use this in a server-only parent template that is rendering the `<html><head><body>` tags and encapsulating the "traditional" content / Ractive component.

The other caveat would be that `toHTML()` would also have to start attaching the `data-ractive-css` property, though I'm guessing that should be pretty doable.

@Rich-Harris @martypdx is this a route you guys would be interested in seeing a pull request for?

**Comment by Rich-Harris** [comment]
@ElliotChong sorry, I missed your comment - just turned up here because I'm experiencing the same problem! On my way I was thinking 'it'd probably make sense if we had a `toCSS()` method...

The wrinkle, of course, is that there needs to be some kind of mechanism to ensure that a) styles don't conflict (if you had HTML/CSS rendered by one process on the same page as HTML/CSS rendered by another, they might stomp each other's `data-ractive-css` IDs), and b) they sync up correctly at render time.

I'm not totally sure what the solution looks like, but keen for us to figure out what it is, and yes a pull request would be great!

**Comment by ElliotChong** [comment]
Did a quick implementation of `toCSS()` that exposes how Ractive is currently constructing the CSS string. This is useful right away if your CSS is written in an Object-oriented (aka: manually namespaced) fashion and works with `noCssTransform: true`.

https://github.com/ElliotChong/ractive/commit/6cf4e38030fee97d8b9913e9f3e321d2e086e31e

Re: syncing up at render time- the most straightforward approach might be to just throw out the `<style>` element rendered on the server and regenerate it once the client does it's render... It's unfortunately a manual implementation detail at that point, but just the process of implementing `toCSS()` on the serverside will probably have to be a bit manual in terms of specifying / creating a container for the content.

**Comment by Madgvox** [comment]
Progressive enhancement is coming with 0.8.

**Comment by MartinKolarik** [comment]
Reopening as it's still not possible to get CSS when rendering on server.

**Comment by fskreuz** [comment]
`ractive.toCSS` and `Ractive.getCSS` should now be available on edge https://github.com/ractivejs/ractive/pull/2362
