### ISSUE TITLE
Confusion about `get` method of Adaptors

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1178]
I haven't used adaptors much, and trying to put one together I ran into some confusion.

Calling `ractive.get('path.to.adapted')` doesn't return the result of the adaptor `get` function, but rather the original object. Are adaptors only "template-facing"?

See http://jsfiddle.net/ATAgH/13/ and check out console.

**Comment by zakj** [comment]
For what it's worth, this bit me as well; I would have expected `ractive.get` on an adapted property to return the wrapped value.

**Comment by evs-chris** [comment]
The answer is that anything that captures a keypath, like `get`, will return the unwrapped value. Anything that doesn't capture, like a template interpolator, gets the wrapped value. There is a get option in 0.9, unwrap, that when set to false allow you to get the wrapped value with `get`.
