### ISSUE TITLE
Observe keypath pattern recursively

### ISSUE THREAD

**Issue by lburgess** [ractivejs/ractive#1187]
When working with hierarchical data structures, it would be nice to be able to observe a pattern recursively - any thoughts on whether this would in fact be possible today? if not, how feasible would it be to implement?

Given a data structure such as:

```
{
    name: 'root',
    visible: true,
    children:  [
        {
              name: 'child',
              visible: true,
              children:  [
                  {
                      name: 'grandchild1',
                      visible: false,
                      children: [....]
                 },
                  {
                      name: 'grandchild2',
                      visible: false,
                      children: [....]
                 }
            ]
        }
    ]
}
```

I would like to observe when the visible property changes on any item within a 'children' array. 

Some initial ideas for a possible syntax: 
```
ractive.on('**children.*.visible', callback);
ractive.on('children.*.visible+', callback);
ractive.on('(children.*.visible)+', callback);
```

**Comment by Rich-Harris** [comment]
Will close this owing to the very high (complexity-involved-in-implementation : number-of-requests) ratio! @lburgess (or anyone else) let us know if the absence of this feature is particularly problematic
