### ISSUE TITLE
Adaptor wierdness and thrashing when used across component

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1198]
Here's an adaptor used inline in the same ractive instance: http://jsfiddle.net/tosjf79n/2/

Here's the same adaptor used on an object passed across component boundary:  http://jsfiddle.net/tosjf79n/5/. And pretty much same thing if the data is retrieved implicitly: http://jsfiddle.net/3m74my0r/2/

Looking at the console output, the first makes sense. But the second makes a reset call, and in addition a teardown and re-wrap, even though true is being returned from reset.

**Comment by Rich-Harris** [comment]
Looks like this is working a bit better now? The object is only wrapped once in all three examples, is that the expected behaviour?
