### ISSUE TITLE
Regression (0.5.6-7): data-foo="{{foo}} results in data-foo when foo is undefined.

### ISSUE THREAD

**Issue by dantman** [ractivejs/ractive#1211]
Ractive's behaviour for undefined attributes has changed between 0.5.5 and 0.5.6-7.

For the template snippet `<span data-foo="{{foo}}"></span>` when `foo` is undefined:
Ractive 0.5.5 will output: `<span></span>`
Ractive 0.5.7 will output: `<span data-foo></span>`

0.5.5 demo: http://jsbin.com/nagedanubece/3/
0.5.7 demo: http://jsbin.com/kodufizugiku/2/

**Comment by Rich-Harris** [comment]
Whoops, totally lost track of this issue. Looks like the consensus was that a non-boolean attribute with an `undefined` or `null` value should be removed from its node - anyone disagree, before I go away and implement that?

**Comment by Rich-Harris** [comment]
PR for this: #1818
