### ISSUE TITLE
Html entities encoding problem

### ISSUE THREAD

**Issue by bleuebuzz** [ractivejs/ractive#1221]
It could be impossible to output HTML entity without double encoding. Also, some encoded entities are decoded. It's hard to explain (encodinception) so I made a fiddle:
http://jsfiddle.net/cahnory/663aht7n/

I noticed that **hexEntityPattern** is `/&#x([0-9]+);?/g`, I think it should be `/&#x([a-f0-9]+);?/ig` but this does not fix the issue.

**Comment by ashok-softscripts** [comment]
Thank you so much...
