### ISSUE TITLE
Migration notes from v0.4 to v0.5?

### ISSUE THREAD

**Issue by binarykitchen** [ractivejs/ractive#1259]
Hello everyone

We are about to upgrade RactiveJS from `0.4.x` to `0.5.x` for our big project. Are there any migration notes what to do? Would be great because after reading the changelog on https://github.com/ractivejs/ractive/blob/dev/CHANGELOG.md we still do not know where to start.

Thanks!

**Comment by Rich-Harris** [comment]
Closing this issue as http://docs.ractivejs.org/latest/migrating exists, and will soon have notes for 0.6.x -> 0.7.x...
