### ISSUE TITLE
Demos do not work on Android 2.2

### ISSUE THREAD

**Issue by denmaradi** [ractivejs/ractive#1261]
These demos dont work (blank) on Android 2.2
1. [Comments Demo](http://examples.ractivejs.org/comments) not working.
2. [Typewriter Transition Demo](http://ractivejs.github.io/ractive-transitions-typewriter). Fade and Slide work good enough.
3. [Sortable Demo](http://ractivejs.github.io/Ractive-decorators-sortable/)

Thanks

**Comment by fskreuz** [comment]
@Rich-Harris Doing a quick cleanup run. Should this be closed? Froyo's at 0.2% https://developer.android.com/about/dashboards/index.html

**Comment by MartinKolarik** [comment]
Closing as I think 2.2 is old enough for this not being an issue.
