### ISSUE TITLE
Add ractive.set() for parent data

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1284]
#1228 added `get()`, but `set()` requires implicit parameter or inclusion in template. See http://jsfiddle.net/rhd92od0/1/

**Comment by Rich-Harris** [comment]
Can't quite make out what's going on here (the fiddle doesn't seem to work at all) - @martypdx is this still a live issue?

**Comment by martypdx** [comment]
The issue, if it is one, is that there is an asymmetry between able to get (and map) a parent path via `get` but not `set`. In this update fiddle, http://jsfiddle.net/rhd92od0/3/, if `widget1` is not explicitly passed the `user` parameter, it can't `set` it (at line 8 in the fiddle).

**Comment by Rich-Harris** [comment]
Ah, gotcha. I think this is probably one of those places where we have to accept that we can't work miracles, and that the cure (giving children control over their parents) would be worse than the disease (parents having to be explicit about what data they pass down, in cases like this one).

**Comment by martypdx** [comment]
Given that this was 6 months ago: a) I can't remember what my feeling was at the time, and b) having now dug deeply into this area of the code I agree that auto _set_ of data up in the parent like that would be trouble.
