### ISSUE TITLE
Invalid HTML is handled inconsistently

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1289]
In HTML, you can't have a `<div>` inside a `<p>`. The browser turns it into something you probably didn't want:

``` js
document.body.innerHTML = '<p><div></div></p>';
alert( document.body.innerHTML ); // '<p></p><div></div><p></p>'
```

Ractive does even worse - [it throws cryptic and inconsistent errors](http://jsfiddle.net/rich_harris/3n2swauj/), or renders the markup differently to how a browser would.

**Comment by evs-chris** [comment]
I don't think there's a decently performant (size/speed) way to handle this sort of thing in ractive, so for now I'm gonna go with "don't do that" 😄
