### ISSUE TITLE
getPotentialWildcardMatches performance with large keypaths

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1347]
From the [mailing list](https://groups.google.com/forum/#!topic/ractive-js/iFcCFEejCVc):

The following keypath leads to slow performance when inputting new values in an input box in combination with observers.

``` js
root.children.0.children.0.children.6.children.6.children.6.children.0.values.0.value
```

I'm trying to make treegrid component, using ractive, with the following tree like structure:

``` js
node: {
   children: [
       node: {},
       node: {
           children: [
                node: {}
           ]
       },
```

etc...

This leads to large keypaths, and slow performance due to the large starMap.

**Comment by evs-chris** [comment]
Star maps now only exist for event handler wildcard matching, so I think this can be safely closed.
