### ISSUE TITLE
#with aliasing isn't bidirectional

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#1353]
I'm not sure if this is something that can be addressed, but creating a new context with `{{#with { key: .some.path }}}<input value="{{.key.value}}" />{{/with}}` only updates from data to synthetic context and not from synthetic context to data. See http://jsfiddle.net/br7hy8hg/1/

If the value referenced in the `#with` happens to be an array or object, the data is updated in both places, but no change events are fired on the original keypaths, which means the view gets out of sync on the original keypaths.

**Comment by Madgvox** [comment]
Closing as this topic has been / is being explored in many other threads (as you can see above).
