### ISSUE TITLE
Something very strange happened - 0.6

### ISSUE THREAD

**Issue by smallhadroncollider** [ractivejs/ractive#1354]
After updating to 0.6 from 0.5 I got a "Something very strange happened error". Eventually tracked it down to one of my partials. Have recreated it: http://jsfiddle.net/smallhadroncollider/s1LLgofq/2/

Only seems to happen when the `<p>` is a `<p>` - if you change it to a `<div>` everything works.

**Comment by evs-chris** [comment]
It looks like this is now fixed in edge after @Rich-Harris's parser refactor and related error handling improvements.
