### ISSUE TITLE
reset() and update() methods duplicate template when there is a helper with array.prototype.sort() and data with an empty object

### ISSUE THREAD

**Issue by katio** [ractivejs/ractive#1359]
I have a problem with a large template and I think I finally could reproduce it in a small jsfiddle. I don't understand the following behaviour when Ractive.js reset() and update() methods duplicate the template when there is a helper with array.prototype.sort() and the data has an empty object like this:

    [
       {id : 4, name: "Ringo", username: "Star43"},
       {id : 2, name: "Paul", username: "Pmac44"},
       {id : 1, name: "John", username: "Jony41"},
       {id : 3, name: "George", username: "Harris44"},
       {}
    ]

This can be a bug but also a behaviour I just don't understand.

The helper is this:

       sort : function(arr){
           //return arr
           arr.sort(function(a, b){
               return a.id - b.id
           })
           return arr
       }
If I uncomment the first

//return arr
Then reset() and update() don't duplicate the template

This is the obligatory jsfiddle: http://jsfiddle.net/Katio/rfuzxwv8/

And the Stackoverflow question: http://stackoverflow.com/questions/26371101/why-ractive-js-reset-and-update-methods-duplicate-template-when-there-is-a-h

**Comment by Rich-Harris** [comment]
@katio sorry for the extremely long delay fixing this, and thanks for the very helpful test case. This was fixed in #1804.
