### ISSUE TITLE
Performance of unresolved implicit bindings with many components

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1362]
I ran into this on my current project, which was making heavy use of implicit bindings (i.e. where a component refers to data that exists in a parent context, and tries to create a parent <-> child binding as though the binding had been created explicitly as in `<widget foo='{{foo}}'/>`) - the performance gets terrible fairly quickly if you're not careful.

Happily, the workaround is straightforward - put more information into the system by creating those bindings explicitly, and Ractive has much less work to do.

But I'm going to leave these stress test JSFiddles here anyway, in case there's something smart we can do to make things more efficient in the absence of that information:

* [implicit bindings](http://jsfiddle.net/rich_harris/cuf3vr7r/) - takes about 15 seconds to initialise and render on the machine I'm on right now
* [explicit bindings](http://jsfiddle.net/rich_harris/bnj25bfg/) - comfortably under a second

If you have dev tools open when they run, you'll be able to see a profile. In the first case, that looks something like this - lots of repeated calls to `resolveRef`, triggered by `attemptKeypathResolution` which tries to figure out if references can be bound yet, which in turn are triggered by `runloop.end` (which happens each time a component renders).

(The yellow warning triangles by `Viewmodel$get` and `fireEventAs` indicate 'Not optimized: Optimized too many times' - not sure what the underlying cause of that is, but it would be good to figure it out since they're both very hot code paths.)

![screen shot 2014-10-15 at 12 11 33 pm](https://cloud.githubusercontent.com/assets/1162160/4648909/012187d6-5486-11e4-9a7f-3711f33d7f22.png)

**Comment by mkrn** [comment]
I need some help here 
Noticing in my grid the performance is really bad with a lot of components, even though they're isolated: true and pass quite a few variables explicitly 

I'm currently getting (profiling during large data ractive.set)  
3611.1 ms 24.94 %	6205.3 ms 42.85 %	resolveRef  is at the top 
Almost 100% of those are called by attemptKeypathResolution in runloop.end  by Ractive $set or $render

What are the general tips to bring it down? I also have quite a bit of computed in my components  which I may need to initialize in data?

Here's an example of component that repeats a lot 
```
  <formControl
    type="{{.type}}"
    settings="{{.}}"
    data="{{~/data}}"
    dataSources="{{~/dataSources}}"
    currentKeypath="data.{{multipleIndex+topRecordIndex}}"
    local="{{~/local}}"
    profile="{{~/profile}}"
    placement="grid"
    editablePre="{{~/state.inEditMode}}" />
```

![screen shot 2015-01-04 at 6 10 19 pm](https://cloud.githubusercontent.com/assets/1870075/5607729/06891e54-943d-11e4-8b73-4286c91838a1.png)


I think this is related, may point to other resolveRef issues,  in some grids cases i get up to 20+ s  so it's pretty bad,  hoping theres an easy fix or general tips to improve performance

**Comment by evs-chris** [comment]
I just checked this on edge and the two cases take roughly the same amount of time now (3s on my phone), though the explicit case needs a bit of twiddling due to changes in ambiguous resolution.
