### ISSUE TITLE
Adding attributes conditionally

### ISSUE THREAD

**Issue by DDKnoll** [ractivejs/ractive#137]
For a checkbox input, you provide an empty attribute, checked, if the checkbox is selected. I could do this with javascript, but it would be great if it worked with Ractive.

<input type="checkbox" value="checked" {{#truestatement}}checked{{/trustatement}} id="full" name="full"/>

This might be one of the only cases where this functionality is necessary, but it would be useful nonetheless.

**Comment by xorcus** [comment]
I want to render element ID only if an ID was supplied in the data model (copied from the supplied props object), and I go like this (can be executed in the mentioned tutorial):

template:
```
<p id="{{id}}">Hello world!</p>
```

code:
```
function create(props) {
  return new Ractive({
    template: template,
    data: {
      id: props.id
    }
  });
}
var props = {}; // the caller decides whether to supply an id or not
create(props).render(output);
```
The following is rendered: ```<p id="undefined">Hello world!</p>```, but I would like to have: ```<p>Hello world!</p>```

**Comment by Madgvox** [comment]
@xorcus You can accomplish that by wrapping the attribute with an if statement:

```html
<p {{#if id}}id="{{id}}"{{/if}}>Hello world!</p>
```

PS: You posted in a very, very old thread. It's better for organization and clarity for everyone if you create a new issue for your questions/concerns.
