### ISSUE TITLE
Multiple handlers on inline events? Is it possible?

### ISSUE THREAD

**Issue by arxpoetica** [ractivejs/ractive#1396]
Consider the following:

`<button on-click="save(.)" on-custom-click-event="track(.)">Save</button>`

It would be nice if I could not have to create a separate click event just to handle two separate function calls. Is this possible? Obviously the following doesn't work, but is their an equivalent?

`<button on-click="save(.);track(.)">Save</button>`

Is it possible to run multiple calls on events? Does this make sense?

**Comment by evs-chris** [comment]
This is now possible on edge with event expressions 😄
