### ISSUE TITLE
Nested elements with transitions: possible to not trigger all?

### ISSUE THREAD

**Issue by rxb** [ractivejs/ractive#1397]
Is it possible to remove a block from the document that uses a transition without also triggering all the transitions inside that block? For example:

```
  {{#if foo}}
    <div intro-outro="fade">
       Welcome to my cool section
       {{#if bar}}
         <div intro-outro="slide">
         Here is a single piece of that section
       </div>
       {{/if}}
    </div>
  {{/if}}

```

If `foo` becomes false, that entire block will be removed and trigger the outro, as expected. But as it fades, I can see the `bar` block transitioning away with its own slide outro at the same time. Ideally, only the outermost transition would happen. 

This example is overly simplified, but as as my project has become more complex, I've ended up with more and more of these situations -- like a list of things which can appear or disappear as a whole, with individual list items that can also appear and disappear on their own.

**Comment by Skyrpex** [comment]
I also find that the transitions should only apply to the root element being removed. I don't feel it makes sense...

The current behavior doesn't allow me to create a Collapse component in a clean way, for example.

**Comment by Madgvox** [comment]
Closing this as it falls under the umbrella of #1853, which is an ongoing (albeit hibernating) discussion.
