### ISSUE TITLE
CSS in components

### ISSUE THREAD

**Issue by victorwpbastos** [ractivejs/ractive#1412]
By now I'm using `style` attribute to customize my components. Is there a better way to handle with CSS in components?

**Comment by fabien** [comment]
@martypdx It appears that the end-of css-rule `;` will break the css parsing somehow. The following does not work, unless I remove the `;` in-between:

```javascript
var MyComponent = Ractive.extend({
    template: '<p class="large">hello world</p>',
    css: 'p { color: blue }; .large { font-size: 200% }'
})
```

**Comment by Madgvox** [comment]
@fabien That appears to be invalid css. The `;` doesn't go between blocks, it goes at the end of declarations. Removing the `;` from your snippet makes it valid css.

**Comment by fabien** [comment]
@Madgvox oops, you're right! - I guess my eyes were tricked in expecting it here (amongst the js) - I wasn't fully awake this morning ;)

**Comment by Madgvox** [comment]
@fabien No worries, we've all been there. :)
