### ISSUE TITLE
Data-bindings within expressions

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1421]
Edit: see below

**Comment by anywhichway** [comment]
I had a hard time following #1381 and am unsure of status or implications for my code. I am getting "Two-way binding does not work with expressions" and  Uncaught TypeError: Cannot read property 'split' of undefined using "latest" from the cdn. And, in some cases data does not propogate across template boundaries. Furthermore, I am not using expressions anywhere. If I use edge the problem goes way, but the code is slow as molasses. Things that updated sub-second before now take 3 to 5 seconds. Thoughts? Other bugs to review? File a new bug?

Also note, the two way error is truncating key names in its report, note the "t" missing below:

"Two-way binding does not work with expressions (`{object:model-productCalculator,property:"amazonFBANetProfit",options:model-productCalculator-class-properties-"amazonFBANetProfit"-}}.object.amazonFBANetProfi`)"

**Comment by dagnelies** [comment]
great, thanks
