### ISSUE TITLE
0.6.0 bug with .unshift and nested components

### ISSUE THREAD

**Issue by skeptic35** [ractivejs/ractive#1428]
I have an array that ist passed down from my main instance to a component and then on to another component, which finally uses the array values to display some other data in a certain order.
If I now use ```Ractive.unshift()``` to put an element at the front of the array, I get duplicated output for the last item, and the item that should be displayed at the front is missing (see http://jsfiddle.net/vpyssufk/1/).
If instead I use ```Array.unshift``` everything works as expected (see http://jsfiddle.net/vpyssufk).

P.S.: I was impressed by the improvement in rendering speed when I switched from 0.5.5 to 0.6.0. Great job guys!

**Comment by Rich-Harris** [comment]
Good news! It looks like this bug is fixed, for real this time. I suspect this is related to the more recent spate of unshift-related bugs, and @skeptic35 was just ahead of the curve as usual :)

Is it okay to close this issue? 0.7 is just around the corner

**Comment by skeptic35** [comment]
> Is it okay to close this issue? 0.7 is just around the corner

Sure thing. 
Looking forward to 0.7 :)
