### ISSUE TITLE
Transitions leaving elements in dom 

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1431]
I'm ending up with transition orphan elements in the DOM:

![image](https://cloud.githubusercontent.com/assets/478864/4854327/94de1dac-6090-11e4-9602-7c075244bc02.png)

The first does a cross-fade:

``` html
    {{#if detail}}
        <div intro-outro='fade' class='back-drop detail'></div>
    {{else}}
        <div intro-outro='fade' class='back-drop'></div>
    {{/if}}
```

The second a straight fade:

``` html
    {{#if detail}}
    <div intro-outro='fade' class='description'>{{description}}</div>
    {{/if}}
```

I suspect the data is such that `detail` is getting toggled back prior to completing

**Comment by evs-chris** [comment]
I'm gonna remove the bug part of this since any somewhat reproducible cases have been fixed. I'll swap it to enhancement for the reuse case.
