### ISSUE TITLE
bind to onload DOM event

### ISSUE THREAD

**Issue by constantx** [ractivejs/ractive#1440]
I have an object like this in the ractive template:
```
<object id="foobar" type="application/foobar.plugin" width="480" height="640">
    <param name="onload" value="pluginLoaded" />
</object>
```

Is it possible to bind to the `pluginLoaded` event inside a ractive component?

**Comment by RangerMauve** [comment]
Uhh, was there a solution to this? Or is it maybe working now?

**Comment by martypdx** [comment]
@RangerMauve Please let us know if you have an example of something NOT working.

My understanding is issue was with the `object` not firing load event, not about Ractive not being able to subscribe.

**Comment by RangerMauve** [comment]
Just tested it out and it seems to be OK. I think this issue can be safely closed for now.
