### ISSUE TITLE
Handlebars.SafeString in Ractive

### ISSUE THREAD

**Issue by victorwpbastos** [ractivejs/ractive#1446]
Is there something like `Handlebars.SafeString` in Ractive? I want to return HTML from a helper but I don't want to call it with tripple slashes.

**Comment by danjford** [comment]
I have a scenario which may need SafeString. I have some text which I want to shorten and use as a preview of the text in a blog. As such I have made an Expression which will limit the number of words and append an anchor tag which says read more. Clicking the anchor tag loads in the rest of the preview.

So returned from my original Expressions would be something like the following:

```
return shortenedPreview + ' <a href="javascript:void(0)" class="read-more" data-value="'+restOfPreview+'">Read More</a>';

```

In this scenario I would want the read more anchor tag to be parsed but not the original preview as it may contain things like videos and images. This can be done in handlebars by returning the following

```
return shortenedPreview + new Handlebars.SafeString(' <a href="javascript:void(0)" class="read-more" data-value="'+restOfPreview+'">Read More</a>');
```

**Comment by martypdx** [comment]
@danjford Structure your expression response and you can also avoid putting template in your expressions:

```js
return { shortened: shortenedPreview, rest: restOfPreview };
```

``` html
{{#with getPreview(preview) }}
    {{{ shortened }}}
    {{#if rest }}
    <a href="javascript:void(0)" class="read-more" data-value="{{rest}}">Read More</a>
    {{/if}}
{{/with}}
```

IMO a much nicer solution that string concatenation.

**Comment by danjford** [comment]
Thanks that was a lot better :+1:
