### ISSUE TITLE
Proxy event with event parameter can have uncaught TypeError

### ISSUE THREAD

**Issue by larryosborn** [ractivejs/ractive#1449]
If I take the example at the bottom of the [docs here](http://docs.ractivejs.org/latest/method-calls), and toggle the rendering of the node, an error occurs. (Uncaught TypeError: Cannot read property 'unbind' of null)

Here's a [fiddle](http://jsfiddle.net/limefest/044jzoLg/1/)

Removing the event parameter and using this.event in the handler works fine.

**Comment by Rich-Harris** [comment]
Closing this as fixed in edge...
