### ISSUE TITLE
Open discussion about "ractive widgets"

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1454]
Hi,

I'd like to discuss a bit about components and decorators. _But please take it with a grain of salt, Ractive is already great as it is and I'd prefer that @Rich-Harris @martypdx focus on making it bullet proof rather than working on some too ambitious extensions._

That being said, I think there is a great deal of potential for "components", but not exactly the way they are currently. The direction I'd love seeing it go is to make it easy to build a wrapper around existing js based widgets. That way, you could have "Ractive widgets" like `<graph ... /><datepicker .../><codemirror .../>...`. I know this has been in the air since quite some time, but as it is currently, it's fairly difficult to create such, or at least that's how I felt.

Currently, as far as I know, decorators are used to add functionality to "elements", like:
`Ractive.decorators['graph'] = function ( node, data ) {...}`
Used on a div like:
`<div decorator='graph:{{alldata}}'></div>`

Now, from a purely syntactical POV, it'd be much nicer if you have something like:

```
<graph x-label="..." y-label="..." values="..." />
```

So, you go around with a component ...but there the nasty stuff starts ...you can't put it directly in ~~init~~ onrender (tried it, didn't work but I forgot why), using intro and a transition didn't worked properly either.
So, in the end you can still combine both _component_ and _decorator_ like this:
`Ractive.components['graph'] = Ractive.extend({template: "<div decorator='graph:{{.}}'></div>"})`
`Ractive.decorators['graph'] = function ( node, data ) {...}`

But this is less than ideal for several reasons
- Components instanciate a template, so you don't drag along all usual html attributes like id, name, class, style, on*...
- you have to put everything in one `data` attribute
- it's not clear how the data-binding would propagate inside the widget

I think it'd be nice to have components/widgets "extending" a single DOM element (it can still fill it with any templated stuff) and keeping all attribues by default. This component would also have an init/teardown function in order to apply the adequate javascript. As well as get/set data in order to propagate the data binding inside such a "component/widget". 

```
Ractive.widgets['graph'] = Ractive.extend({
   base: "div", // inherits all attributes
   template: "The stuff here will not replace the element, it goes inside it. Like: {{message}} or {{>content}}", // optional
   init: function(node, data){...}, // optional
   getData: function(keypath) {...}, // optional
   setData: function(keypath, value) {...}, // optional
   teardown: function(node, data){...} // optional
})
```

This is just a rough example how I'd imagine it. Of course, this is a long shot between "imagining" something and all the work actually involved in realizing something like this, so take with a grain of salt. You already made a tremendous job guys!

**Comment by evs-chris** [comment]
There's a bit of sugar available now, and I think components have improved a bit since this issue was opened, so I'm gonna close this.
