### ISSUE TITLE
Component 2-way binding fail

### ISSUE THREAD

**Issue by svbatalov** [ractivejs/ractive#1495]
Hi.

Take a look at the following [fiddle](http://jsfiddle.net/v2pjttej/2/).

Clicking on the list items updates the value of the `<input>` but does not affects the `<Component>`. If I edit `<input>`, then  `<Component>` updates just fine. Not good..

Btw, what I'm trying to achieve is to edit the currently selected item in the list of items (not its copy, so that the upper list is updated dynamically). The indirect referencing I used looks odd and causes many problems such as this one. What is the Ractive-way to do this?

Thank you.

**Comment by Rich-Harris** [comment]
It looks as though it's okay to close this issue, is that correct? (fork of the original fiddle using edge build: http://jsfiddle.net/rich_harris/1tuqw1b9/)

**Comment by svbatalov** [comment]
Thanks! Closing.
