### ISSUE TITLE
Allow partials to be defined via an id selector like templates

### ISSUE THREAD

**Issue by akhoury** [ractivejs/ractive#1519]
is that a bug? I feel like the `options.partials.name` should behave like `options.template`

They kind of do, so declaring a template with DOM id, can be immediately used using that id,

``` html
  <script id="partial1" type="text/ractive">
    <h3>this is partial1</h3>
  </script>
```

``` html
{{> partial1 }} <!-- that works fine -->
```

But passing a specific id (or any other selector for that matter), just parses it as a string.

``` javascript
new Ractive({
  el: 'target',
  template: '#mytemplate',
  partials: {
    bar: '#partial1'
  }
});
```

``` html
{{> bar }}  <!-- this will just print the selector value, literally "#partial1" -->
```

I tried using `beforeInit` as outline in [this pseudo dynamic templating example](http://docs.ractivejs.org/latest/components#-a-name-dynamism-a-pseudo-dynamic-templating), still, same thing, so I am working around by calling the `querySelector` my self.

Demo: http://jsbin.com/yapocusodi/2/edit?html,js,output

**Comment by evs-chris** [comment]
With 0.8 you can create partials from data, and with edge (0.9), you can even yield to them, so I'm going to close this as the original cause for the issue can be addressed using inline partials like:

``` js
var r = new Ractive({
  el: '#sure',
  template: '{{> .pickedPartial}}',
  data: {
    pickedPartial: { template: 'yeah' }
  }
});

r.set('pickedPartial', { template: 'this will be parsed, so you can use {{refs}} and {{#sections}}...{{/}}' });

// you can also use pre-parsed templates, as any object that looks like { t: [ ] } will work
r.set('pickedPartial', Ractive.parse('this works too'));
```

**Comment by akhoury** [comment]
great thanks!
