### ISSUE TITLE
Errror on unrender and transitions

### ISSUE THREAD

**Issue by mkrn** [ractivejs/ractive#1529]
Uncaught TypeError: undefined is not a function
Element$unrender
(anonymous function)
Fragment$unrender
Section$update
flushChanges
runloop.end
Ractive$set

This is the exact location:
https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Element/prototype/unrender.js#L8

Started getting this error quite a few times, apparently may have to do with items disappearing while having transition..  Seems like this.transition is present  but not this.transition.complete... Adding `&& this.transition.complete`  to `if` leads to weird behavior (element does not remove fully)

Forgive me I cannot provide jsfiddle, but please let me know if it's a known problem.

**Comment by Rich-Harris** [comment]
Going to be optimistic and close this :)
