### ISSUE TITLE
Wrong impression about Ractive.js size

### ISSUE THREAD

**Issue by dcorb** [ractivejs/ractive#153]
the README.md drives you into the wrong impression about Ractive.js size.
Maybe it's time to update this paragraph, since Ractive.js sems that it has doubled its size in the last 4 months:

```
We've got frameworks like Ember.js and Angular.js [...]
A lot of the time, though, you don't need the functionality
of mega-frameworks, or the extra kilobytes (and learning curve) that go with them.
```

I didn't know before Ractive.js and I thought it was going to be a tiny library. The surprise came when I went to download it:

Size of minified ractive.js: 82 Kb
Size of minified angular.js: 78 Kb

Ember is certainly bigger (>200Kb) but most of the people is interested how it compares to Angular.js, or  even jQuery, because they are more familiar with their sizes.

**Comment by wires** [comment]
FWIW, as of today, Ractive is 164K *minimized*. Also the API surface area is increasing rapidly...

I would like to stress you to try to keep it a bit minimalistic. File size isn't everything, but together with the growing API this is a bit worrying. Otherwise enjoying the ease with which we can develop websites with this and would be sad if this grew into something too big (either bytes or semantics) to be comfortable.

Also to compare this with RiotJS (< 10K), which obviously does different things, but still...

:+1: for splitting up functionality into different modules and keeping API minimal

Hope this comment / 2 cents is useful! Cheers

**Comment by JonDum** [comment]
Just pulled down latest dev stuff. As of today it's actually 196k minimized (171k for runtime build).

Interestingly, Closure Compiler does a better job of compressing Ractive than Uglifyjs. 157kb minimized compared to the 196kb above. 

The thing is though, after gzip, it's only ~50kb, which is pretty manageable if you are keeping your overall request count low and concatenating it with the rest of your javascript.

I also ran plato over the source code if anyone is interested in looking that over https://jondum.github.io/ractive-anaylsis/

**Comment by evs-chris** [comment]
Slightly off-topic, but once some of the recent deprecations move to unsupported, a pretty big chunk of code can be stripped out. I don't remember the exact numbers, but between the parser and view code, I want to say it's somewhere north of 1000 lines. Also on the schedule is pulling the array and magic adaptors out into their own plugins, with the bonus that not having the array adaptor enabled by default gives a bit of a performance boost.

As to the API, it has grown a bit of late, but it has largely been in response to lacking ways to accomplish certain things without terrible hacks (or not at all), particularly for larger apps and integration with other frontend libraries and frameworks. _I_ think we've almost reached the sweet spot of feature completeness to call it done, or at least my list is almost completely done.

**Comment by kouts** [comment]
+1 @evs-chris , feature-wise I think Ractive js is complete.

**Comment by JonDum** [comment]
> Also on the schedule is pulling the array and magic adaptors out into their own plugins, with the bonus that not having the array adaptor enabled by default gives a bit of a performance boost.

So many +1s! 👍 👍 👍 

I turn off the array adaptor in every app because it can be very confusing and a source of bugs when you unintentionally start a runloop on what you thought was a modification to an immutable copy.

Same thing with magic adaptor. Shouldn't be in core. 👍

**Comment by ghost** [comment]
Glad to hear this is taken in consideration. Keep up the good work!
