### ISSUE TITLE
Don't modify the global object if AMD/CommonJS

### ISSUE THREAD

**Issue by skyrpex** [ractivejs/ractive#1547]
I'd like to know if there's a reason to expose Ractive to the global object even if we are bundling in an AMD or CommonJS environment. I find it more useful to not do so, like much libraries out there (jQuery, Backbone, store.js, etc.).

Thanks for this great library.

**Comment by Ghazgkull** [comment]
Googling for "ractive noconflict" brought me to this issue. I know it's > 6 months old at this point, but when I check out that fiddle, I just see an error in the console saying that Ractive.noConflict() doesn't exist. I don't see anything about this function in the API doc either, so I'm wondering if it was removed? If so, is there a replacement or recommendation for avoiding global Ractive conflicts?

**Comment by Madgvox** [comment]
Looks like in 0.6.0 and before, the `noConflict` function was included in the build process and got tacked onto the end of the generated file. After 0.7, the build process got revamped and it looks like this snippet was lost. So `noConflict` flew under the radar and straight outta ractive. Gonna have to fix that one!
