### ISSUE TITLE
Allow animation delays

### ISSUE THREAD

**Issue by emiltamas** [ractivejs/ractive#1552]
It would be great if we could specify an animation delay in the options of the `animate` function (similar to the `transition-delay` property from CSS). This way we can avoid using setTimeout just for achieving this.

``` javascript
    this.view.animate('something', val, {
               duration: 250, 
               delay: 100 //<----
       }
```

**Comment by evs-chris** [comment]
I think a composite transition is the best solution to this too, so I'm going to forward it to #987
