### ISSUE TITLE
Teardown promise not always resolved in edge <0.6.2?>

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#1553]
http://jsfiddle.net/sabob/5frek2qd/

The example above renders a Ractive and then immediately invokes a "rerender" function which consist of a teardown call and when the teardown promise fulfulls, renders the Ractive again. The "rerender" function is called twice in quick succession.

With Ractive Edge, the output in the browsers console is:
Teardown complete 1
Rerender complete 1

Interestingly the first call to ractive.teardown never fulfills it's promise. From my testing the call to Ractive.render inside the "rerender" function stops the other ractive.teardown request from completing?

With Ractive Latest, the output is a bit different:
 Teardown complete 1
Teardown complete 0

Here both teardown calls complete, although no rendering occurs.

This is fairly pedantic stuff and probably an abuse of the way Ractive is used in practice but there might be a valid issue at hand? Feel free to ignore though :)

**Comment by sabob** [comment]
Here[1] is my ignorant hack attempt to resolve this issue. This solves my issue where clients quickly navigate between menus and views are swapped out with animations but Ractive#unrender didn't fulfil the promise. Now the unrender promise is always fulfilled.

Unfortunately two tests fail so my approach is probably not correct.

Basically in  runloop.js I start tracking the fulfilPromise and in render.js all tracked promises are resolved before the dom is destroyed.

[1]: https://github.com/sabob/ractive/tree/gh-1553

**Comment by fskreuz** [comment]
@Rich-Harris Just doing some sweeping. Can this be closed now? Seeing that we're at 0.7.2 already.

**Comment by sabob** [comment]
Sure, you can close this. The problems still exists with 0.7.2, in that the teardown promise doesn't resolve when a second ractive renders to the same element before the first one completes. I've worked around this issue for now by not using Ractive's animation when switching views.

**Comment by Madgvox** [comment]
This issue will most likely be at least touched upon in the discussion on how to [improve the animation API](https://github.com/ractivejs/ractive/issues/1853#issuecomment-84223526). I'll close this for now.
