### ISSUE TITLE
question: re-render already rendered partials?

### ISSUE THREAD

**Issue by constantx** [ractivejs/ractive#1564]
on http://docs.ractivejs.org/latest/ractive-partials-instance

> However it is possible, should you need to, to add or replace these partials (obviously, doing so wouldn't affect partials that were already rendered)

and on http://docs.ractivejs.org/latest/partials
> Partials may be updated after they are rendered if they are held within a conditional section. They will be re-parsed each time they are re-rendered, if necessary, so string, pre-parsed, and function partials may be used.

so currently I have this:
```mustache
{{# snapshot }}
<div class="quicklook">
  <div class="quicklook-content">
    {{> POverviewItem }}
  </div>
</div>
{{/}}
```

and updating the partial for switching the `POverviewItem`:
```js
var resource = resources[type];
this.partials.POverviewItem = resource.partial;
this.set('snapshot', { foo: bar});
```

When snapshot change, it doesnt look like the new `POverviewItem` partial is re-rendered if it's already rendered (but render correctly if it's not already rendered).

Any hint on why it's not re-render as expected when I change the partial?

**Comment by constantx** [comment]
@Rich-Harris how about the case where we don't know the partial type yet till down the line?

http://jsfiddle.net/constantx/we74agcu/1/

**Comment by evs-chris** [comment]
I don't think I follow... What's the goal there?

Anyways, in edge, you can now use `resetPartial` to update all instances of a rendered partial as well. http://docs.ractivejs.org/edge/ractive-resetpartial

**Comment by constantx** [comment]
thanks @evs-chris. I’m running into issues where I’m trying to do this:
- component A has a dynamic partial string `{{> getForm(current) }}` with `current` is the name of different form
- that dynamic partial string resolved into a component for different form type (`<UserForm />`, `<AdminForm />`)
- the form is then rendered (take `<UserForm />` as an example
- then, when I updated a data key in `UserForm`, the view doesn’t update

Anyway, i looks like the example works fine albeit with the `Ractive.js: Could not find template for partial “POverviewItem”` in the console, so I’ll dig some more.
