### ISSUE TITLE
Keypath objects

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1579]
Something I've realised while doing #1578 is that we can get some modest (but definitely not meaningless) performance gains by treating keypaths as immutable objects rather than strings - rather than constantly doing things like [this](https://github.com/ractivejs/ractive/blob/864c183658b5e183675d5cf6ae5c1d057dc36c53/src/viewmodel/prototype/get.js#L71-L75)...

``` js
keys = keypath.split( '.' );
key = keys.pop();
parentKeypath = keys.join( '.' );

parentValue = viewmodel.get( parentKeypath );
```

...we can do this:

``` js
var keypathCache = {};

function getKeypath ( str ) {
  return keypathCache[ str ] || ( keypathCache[ str ] = new Keypath( str ) );
}

var Keypath = function ( str ) {
  var keys = str.split( '.' );

  this.str = str;

  if ( str[0] === '@' ) {
    this.isSpecial = true;
    this.value = decodeKeypath( str );
  }

  this.firstKey = keys[0];
  this.lastKey = keys.pop();

  this.parent = str === '' ? null : getKeypath( keys.join( '.' ) );
  this.isRoot = !str;
};

Keypath.prototype.toString = function () {
  return this.str;
};

/* later... */

key = keypath.lastKey;
parentValue = viewmodel.get( keypath.parent );
```

There's a bunch of places where keypaths get manipulated in this sort of way - getting and setting data, registering and unregistering dependants, resolving references and so on. I've tried it out in an isolated setting (retrieving data) and the gains are real. But I reckon it's better to do it as a separate issue rather than rolling it in with #1578, in case it turns out to have unforeseen consequences.

Another benefit: should go a long way towards fixing #1347.

**Comment by Ghostavio** [comment]
This broke IE8...

**Comment by Rich-Harris** [comment]
@Ghostavio can you elaborate? We made sure the test suite still passes in IE8 before release 0.7 (https://github.com/ractivejs/ractive/pull/1839)

**Comment by Ghostavio** [comment]
I get a `'this.str' is null or not an object` and nothing gets executed.

**Comment by Ghostavio** [comment]
And running IE9 on IE8 Compatibility Mode on Windows 7, I get `Unable to get value of the property 'split': object is null or undefined`, I guess this is coming from this line `var keys = str.split( '.' );`.

**Comment by Rich-Harris** [comment]
Afraid we're going to need more info than that - a simple test page runs fine for me in IE8 (regardless of document mode). At what stage does the error occur - while loading the library, or trying to call `new Ractive()`, or what?

Are you using the legacy build (e.g. http://cdn.ractivejs.org/latest/ractive-legacy.js)?

**Comment by Nemo64** [comment]
I can confirm: IE8 is broken since 0.7.0. But I have no showable example of this right now. I go back to 0.6.1 until i have to time to isolate the issue.

**Comment by Rich-Harris** [comment]
@Ghostavio @Nemo64 just so you know, it looks like the issue has been tracked down - see #1908 to track progress towards a fix
