### ISSUE TITLE
Mismatched template version! ...?

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1581]
Hi,

The full error is:
```
Mismatched template version! Please ensure you are using the latest version of Ractive.js in your build process as well as in your app
```
I encountered this error but I don't know the cause of it ...might someone shed some light on it? ...both with latest and edge.

**Comment by TehShrike** [comment]
aaaugh I spent an hour trying to figure out where a second version of Ractive could be coming from
