### ISSUE TITLE
Expression Functions and Computed Properties

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1583]
EDIT: TL;DR

Goals:

- allow computed properties keypaths like `foo.*.bar`
- provide current scope in the computed callback
- allow functions inside of `computed` or `expressions` (to avoid placing them in `data`)

``` javascript
computed: {
  'foo.*.bar': function(scope) {
     // cool, all "foo" items have a computed property "bar" 
     // and can access the data of the current foo!
  },
expressions: {
  pkg: {
    myFunction: function(arg) {
      // cool, an expression function to be used like this: {{ pkg.myFunction('abc') }}
      // That's a better place than in "data"! :)
    }
  }
}
```

----

Hi,

As you know, these are _relatively similar_. At least, they serve the same purpose. It's to compute something a little more fancy than trivial expressions.

However, they differ in some ways, which have their pros and cons. The cons are mainly:

**Expression functions**
- the functions are mixed with the data

_Call me old-fashioned but I like to separate my data and my processing functions ...especially in our AJAX world where raw json data tends to be the currency. It's rather annoying to "boost" your received json with additional functions just to render trivial expressions, and strip it away when saving._
- no getters, observers or setters

**Computed Properties**
- you cannot give them parameters

_which means you can't use it in lists of items!!!_
As shown even in the doc:

``` javascript
new Ractive({
  template: '{{#boxes}}{{area}}{{/}}',
  data: { boxes: [ { width: 20, height: 40 }, ...] },
  // there's no way to specify this for "each" box :(
  computed: { area: '${width} * ${height}' }
});
```

The question is: can we merge these in order to have the best of both worlds? Ideally, in a way that is compatible with the existing stuff.

**Option A**
Move expression functions out of `data` into a better place. You would still not have getters/observers/setters but in would already be a great step forward IMHO.

**Option B**
Be able to declare computed values for arbitrary keypathes _and_ provide the getter and setter a local scope object. Or at least a keypath. So that declaring properties would become:

``` javascript
computed: {
    'boxes.*.area': function(scopeOrKeypath) {
        // yeah, each box can have a computed area property!
    }
}
```

There are probably ways to make it nicer and more practical, but at least, it would enable to add properties to list items.

**Comment by ceremcem** [comment]
@dagnelies How about the recursive use-cases? For example, boxes might contain some other boxes and we might want to display the `width`, `height` and the `area` properties of the boxes in a tree-view, like so:

```js
...
data: {
  boxes: [
    {width: 10, height: 20, boxes: [
      {width: 5, height: 10, boxes: [
        {width: 2, height: 2}]
      }]
    },
    {width: 3, height: 23}
  ]
}
```

```html

{{#partial treeView}}
<ul>
  {{#each x}}
  <li>width: {{.width}}, height: {{.height}}, area: {{.area}}</li>
  {{#if .boxes}}
    <li>
      {{>treeView . as x}}
    </li>
  {{/if}}
  {{/each}}
</ul>
{{/partial}}

<h2>Boxes: </h2>
{{>treeView boxes as x}}
```

In this case 

```
'foo.*.bar': function(scope) {
     // cool, all "foo" items have a computed property "bar" 
     // and can access the data of the current foo!
  },
```
syntax will not seem to suffice. What do you think?

**Comment by ceremcem** [comment]
Moreover, think that our boxes in the above example is dynamic by their `height`s. So, we might set our boxes' `height`s by setting either their `height` directly or by the virtual `area` property: 

```html
{{#partial treeView}}
<ul>
  {{#each x}}
  <li>width: {{.width}}, height: <input value="{{.height}}" />, area: <input value="{{.area}}" /></li>
  {{#if .boxes}}
    <li>
      {{>treeView . as x}}
    </li>
  {{/if}}
  {{/each}}
</ul>
{{/partial}}

<h2>Boxes: </h2>
{{>treeView boxes as x}}
```

Where should we do the calculation? (I'm not sure if this bit is a part of this issue though)

**Comment by dagnelies** [comment]
I think this goes beyond the initial scope. The "new" computed properties as presented would cover structured data and lists. From a pragmatic standpoint, I think this covers the majority of use cases. For recursive stuff like you described, you could still deal with it using components instead of partials, like you do today.

Funnily enough, I find this 3 years old proposal still a very meaningful one.

**Comment by ceremcem** [comment]
> For recursive stuff like you described, you could still deal with it using components instead of partials, like you do today.

Correct. At this point I would only have to use the components for the recursive stuff and handle the rest with `foo.*.bar` syntax.

**Comment by dagnelies** [comment]
updated the original post to be more concise.

**Comment by ceremcem** [comment]
+1 for moving functions out of `data`. 

It seems as a very conscious decision and I'm circumventing this by defining event handlers and "data functions" in the same place, assigning them to `this.on()` and a `runHandler()` function to run these handlers as if they are normally defined in `data` block in my apps already.

**Comment by evs-chris** [comment]
While missing namespaces, ambiguous references (not prefixed) with a single key e.g. (`foo`) are now sought in the new `helpers` registry before looking at other contexts. There's also support for computations in nested keypaths using wildcards. See #3141 for more details, and as always, feedback welcome!
