### ISSUE TITLE
Alternate template syntax

### ISSUE THREAD

**Issue by mrmaxon** [ractivejs/ractive#1584]
Hey... for me personally the mustache syntax is very well readable and easy to write. 

However there are times when you want to implement with an alternate syntax. 

In my case I am having a project with twig style syntax for backend templates. I now want to add client side templating. My "perfect world idea" would be to have the exact same templates people use for the server work on the client but with the extra bit of data binding magic. 

I hope you get the idea. I know that ractive works in node, but changing the server side templating is not an option unfortunately.

Are there any plans for allowing an alternate syntax? What would be the cleanest way to change ractives mustache syntax?

**Comment by Rich-Harris** [comment]
I'll close this issue as part of today's triage as there aren't any current plans to support alternative template languages out of the box. There's still an interesting research project to be done to figure out how easy it would be to support other languages.
