### ISSUE TITLE
[Existing View].extend() causes data share across new View

### ISSUE THREAD

**Issue by ktiedt** [ractivejs/ractive#1593]
I have a 2 components that are similar, the 2nd just needs a few tweaks to make it unique... when I refactored our code to use View.extend() for the 2nd View... and overide/add methods as needed I get a weird data share...

View 2 sets some default values... View 1 does not.. but if I load View 2 then switch to View 1, the default value from View 2 pollutes View1...  I cant seem to find any way of preventing this?

**Comment by Rich-Harris** [comment]
Am just going through all open issues and triaging them - @ktiedt are you still experiencing buggy or unexpected behaviour? It definitely shouldn't be possible to that kind of pollution to happen, certainly not in the edge version. Let me know if we can close this, thanks

**Comment by ktiedt** [comment]
I worked around it as described, unfortunately I can't easily update to test the latest version, personally I would be fine with this being closed.

**Comment by martypdx** [comment]
Thx @ktiedt
