### ISSUE TITLE
broken links to ractive.js in docs

### ISSUE THREAD

**Issue by mainpart** [ractivejs/ractive#1607]
http://ractivejs.github.io/ractive-events-tap/

**Comment by Rich-Harris** [comment]
This is no doubt true for most if not all plugins. Since they'll most likely need to be updated for the 0.7 release, that'd be a good opportunity for us to fix them en masse. Thanks for the heads up @mainpart

**Comment by evs-chris** [comment]
Docs are due for an overhaul, but this particular issue is fixed, so I'mma close it.
