### ISSUE TITLE
Adding filter-style Expressions?

### ISSUE THREAD

**Issue by bestguy** [ractivejs/ractive#1609]
I'm looking to support Angular-style text filters for mustache expressions, for example this syntax:

    {{ someValue | capitalize | indent:2 }}
    {{ someDate | format:"M/d/YY" }}

which would correspond to these, respectively:

    indent(capitalize(someValue),2)
    format(someDate,"M/d/YY")
 
I have a function that can transform the filter syntax string into a normal expression string, but am unsure where I could extend or modify the Reactive codebase to add this preprocessor.

Any ideas or tips?

**Comment by Rich-Harris** [comment]
@bestguy not sure if you still need this functionality - the relevant logic isn't currently exposed, so there isn't any way you could monkey patch it. Changing that would require a fairly substantial refactor, I'm not sure if there's a particularly good route short of doing that I'm afraid.

**Comment by bestguy** [comment]
Thanks Rich - yeah after looking at it, I'm thinking it's too big a change as-is.  
Basically trying to smooth over changing our team from [Angular](https://docs.angularjs.org/guide/expression) and [Knockout Punches](http://mbest.github.io/knockout.punches/#text-filters) style expressions.   If there was a way it could be exposed easily would be very handy though.

**Comment by Madgvox** [comment]
I'm closing this as that "fairly substantial refactor" happened, and I feel further discussion around this topic would warrant a new thread.
