### ISSUE TITLE
foreach objects to generate form input

### ISSUE THREAD

**Issue by huip** [ractivejs/ractive#1611]
var obj = {joy: "why",peter: ''hello'}
  {{each: obj}}
        \<input name="{{@index}}" value="{{this}}" \>
  {{/each}}

this will render as  following

\<input name="{{@joy}}" value="why"\>
\<input name="{{@peter}}" value="hello"\>

what i want was following

\<input name="joy" value="why"\>
\<input name="peter" value="hello"\>

**Comment by Rich-Harris** [comment]
@fskreuz Yeah, that error isn't super helpful. Can't decide which of the following options I prefer:

1. Have a more specific error for `# each` etc (point out that it should be `#each`
2. Allow `# each`

History suggests being more permissive can cause unexpected problems, though it's hard to imagine what those might be in this case.

**Comment by fskreuz** [comment]
@Rich-Harris Not really sure. How does the library determine if `each` is a helper or a legit property called "each" (or some other name colliding with a helper)?

```
{{#each}} <!-- Are you helper? or are you property? -->
  {{.}}
{{/}}

<script>
component.exports = {
  data : {
    each : [1,2,3]
  }
}
</script>
```
