### ISSUE TITLE
Better docs for Ractive.parse()

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1616]
I'm trying to study how a component parser works (Ractiveify and rvc) and I can see that `Ractive.parse()` has other options other than `preserveWhitespace` and `sanitize`. As far as I have observed, there's `noStringify` and `interpolate` but I can't find any resources that explain what these do.

Can the docs reflect these other undocumented parameters?

**Comment by Rich-Harris** [comment]
Yes, these docs need to be improved - I've opened an issue on the docs repo (https://github.com/ractivejs/docs.ractivejs.org/issues/178) so I'll close this one
