### ISSUE TITLE
bug: firefox   checkbox  (火狐兼容性问题 关于 checkbox)

### ISSUE THREAD

**Issue by RyanSuen** [ractivejs/ractive#1618]
在火狐里面，checkbox 的值和我选择的结果是相反的。

In firefox,  one  checkbox(id="one")  was selected,  but    $("#one").prop("checked") === false;

not selected -> $("#one").prop("checked") === true

English  is  bad.

**Comment by Rich-Harris** [comment]
Will close this due to inactivity - @RyanSuen feel free to reply back if you're experiencing problems (preferably with a JSFiddle to illustrate :)

**Comment by jimmyye** [comment]
This is a fiddle to show this bug: http://jsfiddle.net/97r2m1w8/
Firefox and chrome behaved differently.

**Comment by mefjuu** [comment]
It's better to use on-change rather than on-click.

**Comment by jimmyye** [comment]
Thanks, `on-change` works.
