### ISSUE TITLE
on init, input type="range" value does not exceed 100 , even with hardcoded value > 100 and max > 100

### ISSUE THREAD

**Issue by akhoury** [ractivejs/ractive#1621]
Using Ractive 0.6.1 and __latest__

```javascript
new Ractive({
    el: '#target',
    template: '<input value="190" type="range" min="0" max="200" step="1" />',
    oncomplete: function() {
        console.log(this.find('input').value); // prints 100, should be 190
    }
});
```
Value is always at the middle range, `input.value` also reports the same __wrong__ mid value.
![screen shot 2015-01-08 at 8 47 06 pm](https://cloud.githubusercontent.com/assets/1398375/5674416/d5086d2e-9777-11e4-8e96-d675bf048de0.png)

See it in action
http://jsfiddle.net/8zofhx9h/4/

**Comment by akhoury** [comment]
further investigation, turns out it's not really at mid range, but rather the initial input range never exceeds 100.
![screen shot 2015-01-08 at 11 25 34 pm](https://cloud.githubusercontent.com/assets/1398375/5675512/d4279ab8-978d-11e4-9f1a-548ba378595f.png)

http://jsfiddle.net/8zofhx9h/5/

**Comment by martypdx** [comment]
The bug is that the attributes are order-sensitive. If you put the value last, it works:

```html
<input type="range" min="0" max="200" step="1" value="190"/>
```

**Comment by akhoury** [comment]
aahhh! thanks! will workaround it that way.

**Comment by Rich-Harris** [comment]
Thanks for flagging this @akhoury. Good sleuthing @martypdx. Fixed in edge

**Comment by bessfernandez** [comment]
Extra special thanks again to @akhoury and fixing @martypdx. This bug really gave me a migraine.
