### ISSUE TITLE
Manually triggering an 'event' on a binded element doesn't really work

### ISSUE THREAD

**Issue by akhoury** [ractivejs/ractive#1622]
for example, if I wrap an element via jquery, then `$node.trigger('change')`, that doesn't really trigger the change on the node, or at least, the ractive-brew callback does not fire, is this by design? 

Simple test case
http://jsfiddle.net/7y0jry4w/

#### Background, and what's the best approach?
When creating decorators from other libraries, say a jQuery plugin, for example, I am trying to create a colorpicker decorator, using [spectrum](http://bgrins.github.io/spectrum/), however, this is really a polyfill for browsers which do not support the `input type="color"`, so what the plugin does, is that it hides the original `input`, and then creates another `div` with the goodies in it, but I would still expect some sort of way to fire change events on the original node. However, when I do trigger 'change' (or really any other event), the listened-to event doesn't fire on the ractive instance. 

The decorator syntax is pretty simple, 
```html
<input on-change="onChange" value={{color}} type="text" decorator="spectrum" >
```

```javascript
var defaults = {
    hideAfterPaletteSelect: true,
    clickoutFiresChange: true
};
Ractive.decorators.colorpicker = function(node, params) {
    var $node = $(node);
    var onChange = function(color) {
        $node.val(color.toRgbString());
        // fake event, 
        // for some reason $node.trigger('change') does not really fire the relevant event on the ractive instance
        // so i manually fire it on the ractive instance
        // but I really don't want to do that
       this.fire(node._ractive.events.change.action, {name: node._ractive.events.change.action, node: node});
    }.bind(this);
    var onMove = onChange;
        
    var update = function(params) {
        defaults.change = onChange;
        defaults.move = onMove;
        $node.spectrum($.extend(true, {}, defaults, params));
    };

    update.apply(this, [params]);
   return {
       update: update,
       teardown: function() {
           $node.remove();
       }
    };
};
```

#### on an unrelated note:
Do you think a jQuery adaptor is a good idea? Something that normalizes all events to look like the jQuery events structure, all nodes to be jquery instances, etc...

**Comment by martypdx** [comment]
jQuery `trigger` appears to only trigger jQuery events. Doesn't work with `addEventListener`: http://jsfiddle.net/ahL3Lran/1/.

I would try and use `this` ractive instance in the decorator to get/set data and fire events rather than try and route the message through the DOM node.

**Comment by akhoury** [comment]
i see, ok great thanks.

**Comment by Rich-Harris** [comment]
In case it's helpful, I wrote a small library called [simulant](https://github.com/Rich-Harris/simulant) for situations like this - it's what the Ractive test suite uses to simulate user interaction.

**Comment by akhoury** [comment]
neat! thanks
