### ISSUE TITLE
Observers on objects 'gotcha'

### ISSUE THREAD

**Issue by paulie4** [ractivejs/ractive#1627]
As mentioned in the [docs](http://docs.ractivejs.org/latest/observers#a-gotcha-to-be-aware-of), the current Ractive.js Observer code doesn't really work with keypaths that point to objects instead of primitives. I think it would be useful to allow for a user to use an object keypath as long as (s)he is aware that it won't work with an object property change but only with a change to a fully new object.

I made a simple code change as a test, and if you are amenable to this idea, the [Observer.prototype](https://github.com/ractivejs/ractive/blob/dev/src/Ractive/prototype/observe/Observer.js#L14).init() function could allow for an `options.justCheckObjectIdentity`, and the equality check in the `Observer.prototype.setValue()` function could change from this:
`if ( !isEqual( value, this.value ) ) {`
to this:
`if ( this.justCheckObjectIdentity ? value !== this.value : !isEqual( value, this.value ) ) {`

After this code change is in place, then a change to a new object will have the `newObj` and `oldObj` parameters correctly pointing to the new and old objects, respectively, in the callback `function ( newObj, oldObj )`.

**Comment by martypdx** [comment]
> Observer code doesn't really work with keypaths that point to objects instead of primitives

I don't know that I agree with that. The issue is that objects being observed that have downstream value changes won't have the old downstream value on the `old` parameter. You can see that [here](http://jsfiddle.net/w5Lxb2tz/1/)

> a change to a new object will have the newObj and oldObj parameters correctly pointing to the new and old objects, respectively, in the callback function ( newObj, oldObj ).

This is already the case, as you can see [here](http://jsfiddle.net/ywdhy1fm/).

I agree that you sometimes want to ignore downstream changes. Usually I just do this:

```js
r.observe('foo', function(n, o, k){
    if(n===o) { return; }
    // only run this if object actually changed...
});
```

I suppose you could add an option for that. You could also try it out on your own by extending `observe`

**Comment by paulie4** [comment]
The main problem is that the observe callback is always called after any ractive.set() or ractive.update(), regardless if there was a change or not. As you said, I could add an if (n===o) return, but that seems like a lot of overhead for the Observe.update() then Observe callback function calls (even more if this.defer) that could easily be avoided with a new ``options.justCheckObjectIdentity`` (or similar naming).

I guess I could just extend Observe...

**Comment by paulie4** [comment]
As far as I can tell, there is no easy way to tell ractive.observe() to use a different Observer prototype function, so the only way I found to do it (which is quite ugly) is to override the setValue() function for an existing Observer instance:
```javascript
            ractive.viewmodel.deps.observers[keypath][0].setValue = function (value) {
				var this$0 = this;
				if ( value !== this.value ) {
					this.value = value;
					if ( this.defer && this.ready ) {
						runloop.scheduleTask( function() {
							return this$0.update();
						} );
					} else {
						this.update();
					}
				}
            };
```

It seems like you (and I'm sure other people) also want a way to observe changes to a new object. ``options.justCheckObjectIdentity`` seems like a  much nicer way to do it versus an ``if(n===o) { return; }`` in the callback function or the MUCH uglier and not safe in regards to upgrades override of ``setValue()``. For your reference, here's a little example of an Observer's update() being called over and over even though its keypath hasn't been touched at all (or even if nothing changes): http://jsfiddle.net/dnbpqn28/

**Comment by martypdx** [comment]
> As far as I can tell, there is no easy way to tell ractive.observe() to use a different Observer prototype function

Like so (see http://jsfiddle.net/aqpmw0qn/): 

```js
var observe = Ractive.prototype.observe;
Ractive.prototype.observe = function(keypath, fn, options){
    var identityOnly = options && options.justCheckObjectIdentity;
    
    observe.call(this, keypath, function(n, o){
        if(identityOnly && n===o) { return; }
        fn.apply(this, arguments);
    }, options);
}
```

> For your reference, here's a little example of an Observer's update() being called over and over even though its keypath hasn't been touched at all (or even if nothing changes): http://jsfiddle.net/dnbpqn28/

Hmm, it's actually the `ractive.update()` call that's causing the observers to fire. `update` without a keypath means update everything. If you limit it, it doesn't fire that observer http://jsfiddle.net/dnbpqn28/1/. But you could make a good case the observer shouldn't fire if the value doesn't change, but I'm not sure of the whole history of `ractive.update()`.

**Comment by paulie4** [comment]
Note: there's a bug in the different observe prototype function. observe() is supposed to return an object with a cancel method. Since it doesn't, observeOnce() causes an error, so just make sure to re-return the inner observe()'s return value.

**Comment by paulie4** [comment]
Also, observeOnce() will also need to be overwritten, since it only passes "init" and "defer" from the passed in options and just ignores the rest. It should be passing all the options to the inner call to observe(), and just set its init to false.

**Comment by evs-chris** [comment]
With the addition of strict observers and a few other bug fixes, it looks like this is taken care of.

**Comment by paulie4** [comment]
@evs-chris, I see that [dev/CHANGELOG.md](https://github.com/ractivejs/ractive/blob/dev/CHANGELOG.md) references the `strict: true` option to observe(), but it doesn't say exactly what it means to be "strict". Does it have the same meaning as the `justCheckObjectIdentity` option above?

**Comment by evs-chris** [comment]
That's correct, it only fires if `newval !== oldval`, so it doesn't fire on downstream property changes.
