### ISSUE TITLE
Ability to call functions exposed by components

### ISSUE THREAD

**Issue by blackgate** [ractivejs/ractive#1628]
It would be useful to call functions exposed by components, so we can do something like this:

```html
<my-component controller="{{myController}}"></my-component>

<button type="button" on-click="call('myController.action', arg1, arg2)">Action</button>

or

<button type="button" on-click="data.myController.action(arg1, arg2)">Action</button>
```

**Comment by Madgvox** [comment]
This could be a useful enhancement, although you can also implement a generic click handler to enable this functionality:

http://jsfiddle.net/s5uu1o03/2/

**Comment by blackgate** [comment]
Thanks for the suggestion, never thought of that.

**Comment by martypdx** [comment]
> It would be useful to call functions exposed by components

That works out of the box. But assuming you meant functions on data, @Madgvox has the right of it. You can also put a method on `Ractive.prototype` to enable across the board and get the method call syntax (I've also shown using the context as 'this' is you want to go that route):

```js
Ractive.prototype.call = function(fn, ...rest){
    fn.apply(this.event.context, rest);
}
```
```html
<button type="button" on-click="call(action, arg1, arg2)">Action</button>
```

**Comment by blackgate** [comment]
Thanks, that's what I ended up doing.
