### ISSUE TITLE
Publish edge on NPM

### ISSUE THREAD

**Issue by victorwpbastos** [ractivejs/ractive#1632]
The last version in NPM is full of bugs that were already fixed in edge!

**Comment by victorwpbastos** [comment]
#1430 is the most important in my case.

**Comment by evs-chris** [comment]
I don't think npm is really set up for ephemeral releases like edge. Would a git dependency work for you until the next release? I believe you could use
```
"ractive": "ractivejs/ractive#edge”
```

**Comment by Rich-Harris** [comment]
The git endpoint solution @evs-chris suggests is definitely the simplest. I've just tested, and this works:

```js
"dependencies": {
  "ractive": "ractivejs/ractive#build"
}
```

On each push to the `dev` branch, Travis builds and tests the library; if the tests pass, the build is pushed to the `build` branch.

Obviously that's a moving target - locking it down to a specific build would be a case of replacing `#build` with `#52eb21c`, taking a commit hash from [here](https://github.com/ractivejs/ractive/commits/build).

My understanding is that you *can* publish prerelease packages to npm with a tag other than `latest`...

```bash
npm publish --tag whatever
```

...but I don't think there are any benefits to doing that over just using the git endpoint. @victorwpbastos does that work for you? If so I'll close this issue

**Comment by kurdin** [comment]
#1672
