### ISSUE TITLE
Unable to use data.prop.shift() on provided object, when using magic flag

### ISSUE THREAD

**Issue by juliostanley** [ractivejs/ractive#1633]
I am getting the following error when attempting to perform a call to .shift on an array provided to ractive. Only occurs when creating an instance and using the magic flag set to true.

Cannot read property 'rebind' of undefined.

The error seems to have started at version 0.6.0

Please refer to the following snippet:
http://jsfiddle.net/Lbr0x3k7/1/

I am using Chrome 39

**Comment by MartinKolarik** [comment]
Seems to be [fixed in edge](http://jsfiddle.net/Lbr0x3k7/2/).

**Comment by juliostanley** [comment]
It does seem to be fixed in edge. Thank you.
