### ISSUE TITLE
Error in databound computed component variable

### ISSUE THREAD

**Issue by jugglinmike** [ractivejs/ractive#1635]
I'm guessing that's about as complex an issue title as you can get :P I'm trying to identify the problem myself, but hopefully this test case is reduced enough for someone on the Ractive team to make some sense of:

`layout.html`

```html
<ul>
{{#each people}}
  <select-name
    names="{{names}}"
    person="{{this}}"
    />
{{/each}}
</ul>
```

`select-name.html`

```html
<li>Select a name
  <select value="{{name}}">
    <option disabled selected>Name</option>

    {{#each names}}
    <option value="{{this}}">{{this}}</option>
    {{/each}}
  </select>
</li>
```

JavaScript:

```js
'use strict';
var Ractive = require('ractive/ractive.runtime');

var SelectName = Ractive.extend({
  template: require('./select-name.html'),
  computed: {
    name: {
      set: function(val) {
        this.set('_name', val);
      },
      get: function() {
        var newName = this.get('_name');
        var guess = this.get('guess');

        if (guess) {
          newName = 'Undisclosed';
        }

        return newName;
      }
    }
  }
});

var layout = new Ractive({
  el: document.body,
  template: require('./layout.html'),
  components: {
    'select-name': SelectName
  }
});

layout.set('names', ['Mark', 'Matt', 'Mike', 'Undisclosed']);
layout.set('people', [{}, { guess: true }, {}]);

var selected = document.querySelectorAll('option:checked');
var idx;

for (idx = 0; idx < selected.length; ++idx) {
  console.log(selected[idx].innerHTML);
}

console.log('Ractive.VERSION:', Ractive.VERSION);
```

Expected output:

    Name
    Undisclosed
    Name
    Ractive.VERSION: 0.6.1

Actual output:

    Name
    Undisclosed
    Mark
    Ractive.VERSION: 0.6.1

Also confirmed in the latest "edge" build.

**Comment by Madgvox** [comment]
```diff
<li>Select a name
  <select value="{{name}}">
--- <option disabled selected>Name</option>
+++ <option disabled='{{ _name !== undefined }}' selected>Name</option>
    {{#each names}}
    <option value="{{this}}">{{this}}</option>
    {{/each}}
  </select>
</li>
```

This fixes the behavior. Seems like changing one of the boxes to 'Undisclosed' somehow propagates to the select boxes that come after it and shunts the selection down to the first available option.

Doing this:

```diff
<li>Select a name
  <select value="{{name}}">
    <option disabled selected>Name</option>
    {{#each names}}
--- <option value="{{this}}">{{this}}</option>
+++ <option disabled value="{{this}}">{{this}}</option>
    {{/each}}
  </select>
</li>
```

Causes the third select to be blank, i.e. ractive couldn't pick a valid option so it picked none of them.

**Comment by jugglinmike** [comment]
@Madgvox Thanks! It's not pretty, but it's just what I need to move forward with my application for now :)

**Comment by Madgvox** [comment]
[The fiddle](http://jsfiddle.net/6qmtvqew/2/) seems to be working properly on 0.7.x, so I'm going to close this. If it pops again, feel free to reopen.

**Comment by jugglinmike** [comment]
Sounds good to me. Thanks for the help, and congrats on the release!
