### ISSUE TITLE
Missing "mouseenter" || "mouseleave" event plugin - Safari 5.1.7 , Win 7

### ISSUE THREAD

**Issue by parhelium** [ractivejs/ractive#1637]
Ractive started to behave incorrect with Safari 5.1.7 : it expects to install 'mouseenter' and 'mouseleave' event plugin.

That issue happens only to Safari 5.1.7 ( haven't checked older safari )
Other browsers work fine.

Ractive.legacy@0.6.1 
Browser : Safari 5.1.7
OS : Win 7 

Warnings : 
[object Object]Ractive.js: [object Object]Missing "mouseenter" event plugin. You may need to download a event via http://docs.ractivejs.org/latest/plugins#events
ractive-legacy.js:219[object Object]Ractive.js: [object Object]Missing "mouseleave" event plugin. You may need to download a event via http://docs.ractivejs.org/latest/plugins#events

**Comment by maxgalbu** [comment]
Isn't safari on windows discontinues?

**Comment by parhelium** [comment]
I think you are right, the last version was released on May 9, 2012.
However I still need to make sure my app is working on Safari 5.1.7...
Any ideas what to do ?

**Comment by Rich-Harris** [comment]
If you're having mouseenter problems I feel bad for you son, I've got 99 problems but Safari 5.1.7 on Windows ain't one. Can you use `node.contains()` on that version of Safari? If so you could use `mouseover` and `mouseout` events, and check that the event's `relatedTarget` isn't contained by the node in question: http://jsfiddle.net/rich_harris/ho7ostw8/

**Comment by Rich-Harris** [comment]
Alternatively, you could create a custom event definition, which Ractive will use instead of looking for the native DOM events: http://jsfiddle.net/rich_harris/hqgxbawc/

**Comment by parhelium** [comment]
Thanks @Rich-Harris, your first answer solves the issue.
