### ISSUE TITLE
Promise.all fails with non-promises

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1642]
The native `Promise.all(arr)` resolves as soon as all the *promises* in `arr` have resolved. Any non-promise members of `arr` are treated as resolved promises:

```js
var arr = [ Promise.resolve(1), 2 ];
Promise.all( arr ).then( function ( values ) {
  console.log( values ); // [ 1, 2 ]
});
```

Ractive's polyfill behaves differently, because it [assumes that everything is a promise](https://github.com/ractivejs/ractive/blob/dev/src/utils/Promise.js#L106), which causes errors in e.g. Safari.

An alternative to fixing this would be to depend on [es6-promise](https://github.com/jakearchibald/es6-promise), which is based on RSVP and therefore very fast (faster than native promises, I'm reliably informed). It's written in ES6 modules so wouldn't be too vexing to slot into our existing build process. The implementation is significantly larger than ours though.

**Comment by stefanpenner** [comment]
how big is yours?

**Comment by Rich-Harris** [comment]
It's a lean [214 lines](https://github.com/ractivejs/ractive/blob/dev/src/utils/Promise.js). Much of the difference can be explained by [this one](https://github.com/ractivejs/ractive/blob/dev/src/utils/Promise.js#L137) though - it's using a terribly inefficient `setTimeout` instead of using mutation observers etc. (It falls back to the native `Promise` if such a thing exists, so it's not quite as egregious as it sounds!) It probably has other performance pitfalls - if anyone can spot them it's you :-)

Could probably split the difference by having a separate browser build of es6-promise that ditched `process.nextTick()` and suchlike.

**Comment by stefanpenner** [comment]
@Rich-Harris maybe we can pair on it when we meetup.

**Comment by Rich-Harris** [comment]
sounds good
