### ISSUE TITLE
Events fire but data not yet changed

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1643]
Here's a simplified example: http://jsfiddle.net/b126tu8L/

```html
<script type="text/ractive" id="foo">
    <select on-change="foo" value="{{ rar }}">
        <option value="1">1</option>
        <option value="2">2</option>
    </select>
</script>
```

```js
new Ractive({
    template : '#foo',
    el : 'body',
    oninit : function(){
        this.on('foo',function(event){
            debugger;
        });
    }
});
```

The event fires *before any data is modified*. In this case, `this.data.rar` is still `1` after I have selected 2. I expect that on change, *the change has already happened*, `rar` should now be 2 by the time the event fired. I need to encapsulate the inner workings, like shadow DOM and only get the values via `data` or via values sent as attributes.

Thoughts?

**Comment by Madgvox** [comment]
Is there any reason you can't use an observer? They are essentially wrapped `on-change` events.

```js
this.observe('rar', function(n,o,k) {
  debugger;
});
```

**Comment by Madgvox** [comment]
Also here is a filed issue for the exact same thing. Looks like this is a known behavior: https://github.com/ractivejs/ractive/issues/1371

**Comment by fskreuz** [comment]
@Madgvox Sorry for the late reply. I'm not using two-way binding and observers (avoiding two-way magic at the moment). Also creating components like custom select boxes which can also work in non-two-way mode.
