### ISSUE TITLE
"d.dep.setValue is not a function" on nested components

### ISSUE THREAD

**Issue by anton-ryzhov** [ractivejs/ractive#1645]
I'm trying to use edge version and found some bug. I've prepared testcase as usual)

Bug appears after merge #1546 and looks related to #1542.

My case: http://jsfiddle.net/d4sgqma2/

All items are required to reproduce - `component1` inherits values from root object, `component2` rewrites context and uses function call and value is defined after first initialization.

Function itself isn't important — it fails with any one. http://jsfiddle.net/d4sgqma2/1/

```js
new Ractive({
    el: 'body',
    template: '<component1 />',

    components: {
        component1: Ractive.extend({
            template: '<component2 foo="{{ bar }}" />',
        }),

        component2: Ractive.extend({
            template: '{{ console.log(foo) }}',
        }),
    },
    
    onrender: function() {
        this.set('bar', 1);
    },
});
```

**Comment by anton-ryzhov** [comment]
http://jsfiddle.net/d4sgqma2/ doesn't work again with another one error.

```js
Error: Exposing privileged or cross-origin callable is prohibited 
this.node = document.createTextNode(this.value != undefined ? this.value : "");
```

in `Interpolator.prototype.render()`

**Comment by Rich-Harris** [comment]
What version of Firefox are you using? In FF36 I don't see anything like that. The `this.set('bar',{})` inside the `onrender` doesn't seem to do anything, which is odd (marking this as a bug), but that behaviour's consistent between Chrome and FF.

**Comment by evs-chris** [comment]
I'm not getting the error in Firefox from the beta channel. Do you have any extra security/privacy/content restrictions enabled?

It looks like the mapping isn't getting added properly, because adding `data: { bar: undefined }` makes the empty object log on `set`.

**Comment by anton-ryzhov** [comment]
It's 36.0.1, and seems there is no privacy extensions or something like that. I have some cases with this bug, I'll investigate it deeper and write details.

**Comment by anton-ryzhov** [comment]
Ok, I've found. This isn't associated with this ticket.
Firebugs `console.log` returns undefined-like but object, which can't be rendered by ractive. Chrome Devtools and Firefox built-in debugger returns native `undefined` and everything is ok.

Maybe I'll post new ticket if there is some issues inside ractive about this.

**Comment by anton-ryzhov** [comment]
Yes, this is firefox or firebug issue, nothing to fix in ractive
