### ISSUE TITLE
Using "event.original.ctrlKey" create null referance in RefResolvers when used in an on-click statement

### ISSUE THREAD

**Issue by petterek** [ractivejs/ractive#1650]
![image](https://cloud.githubusercontent.com/assets/181268/5838547/7f91ff20-a188-11e4-9347-7729bea33b2a.png)

The X is null. 

Seems CreateRefResolvers returns null, and adds this to the list of refResolvers.

    <th on-click="invoke(Sort, 'Originalname', event.original.ctrlKey)">Orginalname</th>

    Ractive.prototype.invoke = function (fn) {
            fn.apply(this, [].slice.call(arguments, 1));
        }

**Comment by petterek** [comment]
BTW the TH is inside a partial template

**Comment by Madgvox** [comment]
Can you create a jsFiddle for this bug? `event.original.ctrlKey` does not cause this error [by itself](http://jsfiddle.net/jeyfzypp/).

On a side note, you can simplify your `invoke` function greatly:

```js
Ractive.prototype.invoke = function (fn, ...args) {
    fn.apply(this, args);
}
```

**Comment by petterek** [comment]
First time the partial is rendered it's ok, but when the partial is rerended the error occure.. I will try to expand your fiddel

**Comment by petterek** [comment]
http://jsfiddle.net/jeyfzypp/6/

It works as expected if you remove the {{#if items}} cluse. 

seems some kind of 'double context' messes up the handlers.

**Comment by petterek** [comment]
And if there is some items in the array

**Comment by petterek** [comment]
![image](https://cloud.githubusercontent.com/assets/181268/5853501/a3fb1e4a-a224-11e4-8211-2ed59ab8a4fc.png)

This is where the null is set

**Comment by petterek** [comment]
my guess is that the native version of map adds the null to the array, where as some previouse versions of map (from _  or $?) excludes null's from the result array.

**Comment by petterek** [comment]
my guess is that the native version of map adds the null to the array, where as some previouse versions of map (from _  or $?) excludes null's from the result array.

**Comment by petterek** [comment]
handler.refResolvers = refs.map( function( ref, i ) {
					var match;
					// special case - the `event` object
					if ( match = eventPattern.exec( ref ) ) {
						handler.keypaths[ i ] = {
							eventObject: true,
							refinements: match[ 1 ] ? match[ 1 ].split( '.' ) : []
						};
						return null;
					}
					return createReferenceResolver( handler, ref, function( keypath ) {
						handler.resolve( i, keypath );
					} );
				} ).filter(function(e) { return e; });

**Comment by petterek** [comment]
The 'bug' dissaperd when I changed the code above.

**Comment by petterek** [comment]
I tried to use the http://cdn.ractivejs.org/edge/ractive.js instead, and that solved the issue..

**Comment by Madgvox** [comment]
Cool, I'm glad you were able to figure out the issue!
