### ISSUE TITLE
Data stops binding at a certain point

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive#1651]
I have the following structure:

filesTemplate:
```
<div class="scrollable tree">
	{{#root}}
		{{>file}}
	{{/root}}
</div>

<!-- {{>folder}} -->
<ul>
	{{#files}}
		{{>file}}
	{{else}}
		<li class="empty file"><span on-click="highlight" on-dblclick="select"><i></i><s>(empty)</s></span>
	{{/files}}
</ul>
<!-- {{/folder}} -->

<!-- {{>file}} -->
<li class="{{ type === 'folder' ? 'folder' : 'file' }} {{ ./open ? 'open' : '' }}"
	><span on-click="highlight" on-dblclick="select"><i on-click="open"></i><s>{{ name }}<s
	class="{{ c ? 'c' : ''}} {{ f ? 'f' : '' }}">{{ ext }}</s></s></span>
	{{# ./open }}
	{{# type === 'folder' }}
		{{>folder}}
	{{/ type === 'folder' }}
	{{ /open }}
</li>
<!-- {{/file}} -->
```
This is my setup:
```js
var ractive = new Ractive({
	el: document.getElementById('files')
	, template: filesTemplate
	, data: { root: currentDirectoryListing() }
});
```
And currentDirectoryListing returns an object like this:
```
{
  files: Array[4],
  name: "MyDir",
  open: true,
  path: "/yaddayadda/mydir",
  type: "folder",
}
```
Now, when a new directory is selected, there's obviously a new object, and I need to refresh. I WAS getting this to work with:
```
ractive.set('root', currentDirectoryListing());
```
Everything was working splendidly. However, at some point, something changed, and while the ractive will bind the first time, it will not bind to any data after that. It doesn't matter if I call update with a keypath to consider dirty, it doesn't matter if I call set and manually enter an object structure that should directly map to the template. It will display the root name, but not any other data. Any ideas what might cause that?

**Comment by martypdx** [comment]
Seems odd. You might try adding a console.log to your template to see what's going on when you set `root`:

```js
<div class="scrollable tree">
    {{console.log(root)}}
    {{#root}}
        {{>file}}
    {{/root}}
</div>
```

**Comment by Rich-Harris** [comment]
Yeah, it does seem odd - what version are you using? Any chance you could knock up a JSFiddle that reproduces the issue? Here's a template fiddle -> http://jsfiddle.net/rich_harris/va6jU/. Thanks

**Comment by matthew-dean** [comment]
Sorry guys, I seem to have solved the problem, and by now have forgotten how I solved it. I think possibly a function stopped returning the right node of the array, so I can't say for sure if it was a bug that I worked around, or a mistake of mine that I fixed, so to not waste your time, I will close.
