### ISSUE TITLE
Expanding data on component in onconstruct does not work

### ISSUE THREAD

**Issue by petterek** [ractivejs/ractive#1653]
If you try to add som data to a component in the onconstruct callback the properties on that object is not merged in to the object/viewmodel visible to template. 

    'use strict';
    (function (r,app) {
    r.components.actionmenu = r.extend({
        isolated: true,
        append: true,
        template: function() {
             return '<div>{{#ActiveElements}}<div on-click="invoke(Publish,.)">{{Name}}</div>{{/a}}</div> ';
        },

        onconstruct: function (init) {
            this.data = new ActionMenuModel(this,init.data.contextname, init.data.actions, init.data.id);
        },

        onrender: function() {
                
        }

    });
    
    function ActionMenuModel(ri,contextName, actions, id) {
        var self = this;

        this.SomeProperty = "HERE IS SOME TEXT"; //This property is not accessable in template 
        this.actions = actions;
        this.ActiveElements = [];
        this.AllElements = [];
        this.Elements =  actions;
        
        //ri.set("Publish", function (item) { alert(item.Name); }); //Cannot be done here as viewmodel is not set in ractive i think
        //this.Publish = function(item){ alert(item.Name)}; //It's not accessable in the rendering so its null in the invoke function

        app.Repo.GetContext(contextName).then( //returns a bunch of menu elements
            function(res) {
                self.AllElements = res;
                ri.set("Publish", function (item) { alert(item.Name); }); //Must be set here in stead.
                ri.set("ActiveElements",self.AllElements.filter(function(e) {
                    return self.Elements.find(
                        function(ae) {
                             return e.Name == ae.Name;
                        });
                }));
            });

    };

    })(Ractive,Core);

This might not be a bug, could be me missunderstaning something. 
To me it looks like ractive is using the attributes passed in as the data object when its rendering and not any data that you set on the ractive instance. 
Should you seperate the two "data objects" in some way?

**Comment by petterek** [comment]
onrender: function(init) {
            this.set(new ActionMenuModel(this, this.data.contextname, this.data.actions, this.data.id));
        }

**Comment by Madgvox** [comment]
Have you tried this?

```js
onconstruct: function (init) {
    init.data = new ActionMenuModel(this, init.data.contextname, init.data.actions, init.data.id);
},
```

**Comment by petterek** [comment]
That worked.. 

Thank you :+1:

**Comment by martypdx** [comment]
You could also use a function for the data option:

```js
data: function (data) {
    return new ActionMenuModel(this, data.contextname, data.actions, data.id);
},
```
