### ISSUE TITLE
automated profiling

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1655]
Filed under 'one day' - [this document](https://github.com/paulirish/automated-chrome-profiling#readme) has some handy hints on automated performance testing

**Comment by evs-chris** [comment]
The perf suite has a more comprehensive test along with config options to set up profiling in Chrome. So not as cool as using the debugging protocol to script it, but still fairly automated. There's not really a way to use it headless, as (stable) Chrome requires a graphical environment, which leaves out CI.

**Comment by ghost** [comment]
@evs-chris When https://github.com/ractivejs/ractive/pull/2848 is done, I plan to use the same Karma and Sauce Labs setup to do [karma-benchmark](https://github.com/JamieMason/karma-benchmark). I once added this goal to the PR but to just get the Karma and Sauce Labs setup out, I set it aside as a separate effort. 😄
