### ISSUE TITLE
Viewmodel not set on ractive instance for component.

### ISSUE THREAD

**Issue by petterek** [ractivejs/ractive#1659]
http://jsfiddle.net/qcqry2g9/1/

Fails on this line in ractive. 

![image](https://cloud.githubusercontent.com/assets/181268/5898517/7f8593cc-a550-11e4-9eeb-82eb1e69dfe2.png)

I tried to use the suggested "data as a function" but no luck.  Again might be me doing something horrible here.

If i do the 
     ri.set("VisibleElements", this.Elements)

in a promise it works the first time, understandable enough, because it's called after ractive is finished with its initializiation. My guess is that the viewmodel is attached to the instace to late. 

I have tested with both Stabel and Edge release.

**Comment by petterek** [comment]
![image](https://cloud.githubusercontent.com/assets/181268/5898693/43796d84-a552-11e4-8550-8e037b15f672.png)

Fails here

**Comment by Madgvox** [comment]
The viewmodel is undefined because you are calling `ri.set("VisibleElements", this.Elements)` before ractive has even built it. Try this instead:

```js
ri.data.VisibleElements = this.Elements;
```

**Comment by petterek** [comment]
I'm sorry to bother you guys, but this is my orignal code. 
![image](https://cloud.githubusercontent.com/assets/181268/5898822/af776a12-a553-11e4-9cf0-ffd161f8c0af.png)

And as i said this works fine, the first time its called. But when it tries to reconstruct the component, without a page reload, the promise is allready resolved and it fails. 

Any suggestion? 
Am I approching this the wrong way..

**Comment by guilhermeaiolfi** [comment]
Have you tried using the onrender method to set your data model?

```javascript
onrender: function () {
  this.set("data", new ActionMenuModel(this, "Test", [{Name:"1"},{Name:"2"},{Name:"3"}]));
}
```

**Comment by petterek** [comment]
![image](https://cloud.githubusercontent.com/assets/181268/5899089/259aa5da-a557-11e4-98b7-2c09e3a7edc6.png)

Changing to this does not help either, because it seem magic mode does not work in components

**Comment by petterek** [comment]
I have tried in the onrender callback as well. I belive it boiles down to me fetching the data async. 
I should probably fetch it sync instead, and it will solve my issue.

**Comment by guilhermeaiolfi** [comment]
Async shouldn't be the problem since I'm using it and it works just fine.

**Comment by Madgvox** [comment]
The crux of the issue is at some point you're attempting to call `set` before ractive has created the viewmodel. Can you explain what is wrong with using this code?

```js
function ActionMenuModel(ri,contextName, actions, item) {
        var self = this;
        this.Elements =  actions;
        ri.data.VisibleElements = this.Elements;
};
```

**Comment by petterek** [comment]
The code in the fiddel is somewhat simplefied.. 
Here is the complete code for the component

    'use strict';    
    (function (r,app) {

    r.components.actionmenu = r.extend({
        isolated: true,
        append: true,
        template: function() {
            return '<div>{{#ActiveElements}}<div on-click="actionselected:{{Name}},{{item}}">{{Name}}</div>{{/a}}</div>';
        },
        data: function(data) {
            return new ActionMenuModel(this, data.contextname, data.actions, data.item);
        },
        magic: true
    });
    
    function ActionMenuModel(ri,contextName, actions, item) {
        var self = this;
        this.item = item;
        this.actions = actions;
        this.ActiveElements = [];
        this.Elements =  actions;

        app.Repo.GetContext(contextName).then(
            function (res) {
                self.AllElements = res;
                //This works when the promise is not reolved. But when the promise is resolved and cached in the GetContext function, the 'then' function is called immidiatly and ractive is not finnished with its work.
                
                ri.set("ActiveElements",self.AllElements.filter(function(e) {return self.Elements.find(function(ae) {return e.Name == ae.Name;});}));
            });
    };

    })(Ractive,Core);

**Comment by Madgvox** [comment]
Thanks for the context.

I think this should work for you:

```js
'use strict';    
(function (r,app) {

r.components.actionmenu = r.extend({
    isolated: true,
    append: true,
    template: function() {
        return '<div>{{#ActiveElements}}<div on-click="actionselected:{{Name}},{{item}}">{{Name}}</div>{{/a}}</div>';
    },
    data: function(data) {
        return new ActionMenuModel(this, data.contextname, data.actions, data.item);
    },
    magic: true
});

function ActionMenuModel(ri,contextName, actions, item) {
    var self = this;
    this.item = item;
    this.actions = actions;
    this.ActiveElements = [];
    this.Elements =  actions;

    app.Repo.GetContext(contextName).then(
        function (res) {
            self.AllElements = res;
            //This works when the promise is not reolved. But when the promise is resolved and cached in the GetContext function, the 'then' function is called immidiatly and ractive is not finnished with its work.

            ri.data.ActiveElements = self.AllElements.filter(function(e) {return self.Elements.find(function(ae) {return e.Name == ae.Name;});}));
            if( ri.fragment.rendered ) ri.update();
        });
};

})(Ractive,Core);
```

**Comment by petterek** [comment]
Close :( 

![image](https://cloud.githubusercontent.com/assets/181268/5899564/151fad9e-a55d-11e4-8666-7450412f72d2.png)

**Comment by Madgvox** [comment]
Try `if (ri.fragment) ri.update();`

Or `if (ri.viewmodel) ri.update();`

**Comment by petterek** [comment]
if (ri.fragment && ri.fragment.rendered) ri.update();

This solved it..

**Comment by Madgvox** [comment]
That works as well.

**Comment by petterek** [comment]
Shouldn't magic mode picked up the cahnges?

**Comment by Madgvox** [comment]
Not necessarily, since I believe ractive does not listen to the data object itself, just its children. Don't quote me on that though, since I don't use magic mode myself. I find it to be kind of finicky, as you've discovered.

**Comment by petterek** [comment]
Thank you very much for your time :) 

@Madgvox
