### ISSUE TITLE
Dom event functions go to wrong ractive instance when using a content directive.

### ISSUE THREAD

**Issue by justspamjustin** [ractivejs/ractive#1661]
I'm trying to use the content directive in a component, the same way I would use transclusion in angularjs. However, the issue I'm running into is that when I put a dom event on an element that is in the content directive, it tries to call the method on the incorrect ractive instance (the one that has the {{>content}} in its template). Instead it should call the method on the ractive instance that is providing the content to the generic class.

To reproduce this issue:
1. Go to jsbin: http://jsbin.com/muqodoxoqi/1/edit?html,js,output
2. Open your console
3. Click on the first alert button (notice it works, because the button is outside of the content directive)
4. Click on the second alert button, it doesn't work and you get the following error: **Uncaught Error: Attempted to call a non-existent method**

Expected Behavior:
It should call the method on the ractive instance that is providing the content to the content directive. It should not call the method on the generic instance that has the content directive.

**Comment by martypdx** [comment]
Use `{{yield}}` instead of `{{>content}}`.

**Comment by justspamjustin** [comment]
Of course! Thanks. I apologize for the noob question. :)
