### ISSUE TITLE
Calling pop on a multi select bound value fails

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#1665]
In this fiddle:
http://jsfiddle.net/sabob/5fd8a3q7/
is a Select set to multiple values and bound to the "selectedValues" array property.

If no value of the Select is picked and pop() is called on the empty selectedValues array, Ractive throws an error:
uncaught TypeError: Cannot read property 'length' of null

Could be a bug?

**Comment by Madgvox** [comment]
```js

**Comment by Madgvox** [comment]
```js
switch(methodName) {
  /* ... */
  case "pop":
    if (array.length) {
      return [array.length - 1, 1];
    }
    return null;
  /* ... */
}
```
Internally, this switch is getting called. That `return null` is what's causing the error.

**Comment by MartinKolarik** [comment]
[This](https://github.com/ractivejs/ractive/blob/6e4f36a722b3254b5ad0264965c67c39b8f92e57/src/Ractive/static/adaptors/array/processWrapper.js#L11) should probably be replaced with [this](https://github.com/ractivejs/ractive/blob/e6f702823e7b309a5cd6fefe94be65bf4ad82414/src/Ractive/prototype/shared/makeArrayMethod.js#L23-27), but I'm not 100% sure as I haven't seen the codebase for a while.

**Comment by Rich-Harris** [comment]
Apologies for slow turnaround, now fixed. Thanks for the fixes - both would have worked (not returning `null`, and varying the update method used based on whether `newIndices` was generated), but combining them allowed a couple of lines of code to be deleted.
