### ISSUE TITLE
Combine precompiled templates

### ISSUE THREAD

**Issue by kurdin** [ractivejs/ractive#1667]
I could not find the way to combine all templates (with partials) in one file and serve this to application page. 

I have multiple templates in separate html file: 

templates_ractive/main.html
templates_ractive/accessError.html
templates_ractive/articles.html
templates_ractive/login_form.html
.. etc ...

I can compile them with :
```javascript 
gulp.task('ractive_templates', function() {
    return gulp.src('templates_ractive/*.html')
        .pipe(ractive({
          preserveWhitespace: true
        }))
        .pipe(gulp.dest('templates_ractive/compiled/'));
});    
```
each template will be a string saved in separate file and look something like this:

```json
{"v":1,"t":[{"t":7,"e":"script","a":{"id":"articles","type":"text/ractive"},"f":["\n  <h2>Articles</h2>\n",{"t":4,"n":52,"r":"pages.articles","f":["    <article>\n      <h3>",{"t":2,"r":"title"},"</h3>\n      <p>Posted by ",{"t":2,"r":"author"},"</p>\n      <p>",{"t":2,"r":"body"},"</p>\n    </article>\n"]},"  ",{"t":8,"r":"accessError"},"\n"]}]}
```

How can I merge them in one JavaScript file and include on application page with ``<script>`` tag or load with ajax? This is for production.

I don't want to use browserify and looks like I can use ``require`` only with main templates and not partials.

**Comment by martypdx** [comment]
Essentially you need to combine them into a single file, either assigning to global var or wrap as a module:

```js
var template = {
    name1: template1,
    name2: template2,
    name3: template3,
}
```

There's probably already be a pre-built project for this, I'm struggling to find the links - hopefully someone will jump in.

**Comment by maxgalbu** [comment]
You could use gulp-include:

Put this file in
```js
var templates = {
    main: //= include compiled/main.html,
    accessError: //= include compiled/accessError.html,
    articles: //= include compiled/articles.html
}
```

Then do this:
```js
gulp.task('ractive_include', ['ractive_templates'], function() {
    return gulp.src('templates_ractive/templates.js')
        .pipe(include())
        .pipe(gulp.dest('templates_ractive/compiled/'));
});

gulp.task('ractive_templates', function() {
    return gulp.src('templates_ractive/templates.js')
        .pipe(ractive({
          preserveWhitespace: true
        }))
        .pipe(gulp.dest('templates_ractive/compiled/'));
});    
```

Run `gulp ractive-include`, then include `templates_ractive/compiled/templates.js` in your html.

**Comment by kurdin** [comment]
> You could use gulp-include: Put this content in 'templates_ractive/template.js:

Well, this is not very flexible, you need to define all your template vs read list from files name in folder. I guess I can create my own gult task simular to include, where I can read all files in ``templates_ractive/compiled/`` folder and created single file ``templates_ractive/compiled/templates.js`` with content like this:

```JavaScript 
var template = {
    name1: template1,
    name2: template2,
    name3: template3,
}
```

**Comment by maxgalbu** [comment]
Please share your solution if you found a better one, I'm interested in it :)

**Comment by Rich-Harris** [comment]
At the Guardian we use [component files](https://github.com/ractivejs/component-spec) extensively and have a workflow around that (they get converted to ES6 modules, then bundled) - I can go into more detail if it's of interest.

But for this specific problem you could try [spelunk](https://github.com/rich-harris/spelunk). It takes the contents of a folder and generates a JSON object representing them all, where the filenames (minus extensions) become property names, and subfolders become nested objects.

So if you ran it on the `templates_ractive/compiled` folder, you'd get something like this:

```js
{
  "main": {"v":2,"t":/*...*/},
  "accessError": {"v":2,"t":/*...*/},
  "articles": {"v":2,"t":/*...*/},
  "login_form": {"v":2,"t":/*...*/}
}
```

You can then save it as a module, or whatever:

```js
spelunk( 'templates_ractive/compiled' ).then( function ( templates ) {
  fs.writeFile( 'templates.js', 'TEMPLATES = ' + JSON.stringify( templates ) );
});
```

**Comment by martypdx** [comment]
> you could try spelunk

@Rich-Harris you have the coolest modules. simplistic brilliance.

> At the Guardian we use component files extensively

I agree it doesn't take long to go from multi-template to components. I use @Rich-Harris's [gobble](https://github.com/gobblejs/gobble) along with [gobble-ractive](https://github.com/gobblejs/gobble-ractive) which make it embarssingly easy to turn components to modules.

**Comment by guilhermeaiolfi** [comment]
Components files are great. They need more publicity. I wasn't aware of their existence.

**Comment by kurdin** [comment]
@Rich-Harris currently I see that [spelunk](https://github.com/rich-harris/spelunk) converts file content into the strings then ractive will need to convert it back to object, not sure if this a good idea. 

I want to keep things simple, ``gulp`` is already been used so I don't think adding another task manager is necessary for me at least. [gobble](https://github.com/gobblejs/gobble) looks cool but I need to dig more into who to use ``components to modules`` approach. Maybe some other day. 

To anyone who want to use just gulp and build templates in real time then serve them to the client (browser) with regular ``<script>``` tag, here is what I come up with:

Folder for all ractive source templates is ``templates_ractive/``they have ```html``` extensions.

````console
#ls -la templates_ractive/
accessError.html	articles.html		index.html		login.html		login_form.html
main.html		photos.html
````
Make sure those files have ```HTML/Handlebars```code and you ***do not wrap*** their content into 
```<script id="accessError" type="text/ractive"> ... </script>``` .

in server.js or gulpfile.js
````javascript
var gulp = require('gulp'),
    path = require('path'),
    wrap = require("gulp-wrap"),
    declare = require('gulp-declare'),
    concat = require('gulp-concat'),
    ractive = require('gulp-ractive');

gulp.task('ractive_templates', function() {
    return gulp.src('templates_ractive/*.html')
        .pipe(ractive({
          preserveWhitespace: true
        }))
        .pipe(wrap('<%= contents %>', {imports: {path: path}}))
        .pipe(declare({
          namespace: 'Templates',
          noRedeclare: true // Avoid duplicate declarations
        }))
        .pipe(concat('templates_compiled.js'))
        .pipe(gulp.dest('./public/js/'));
});    

gulp.watch(['templates_ractive/*.html'], ['ractive_templates']);
````
On template file changes, code above will save compiled template into ``./public/js/templates_compiled.js`` file and it will look like this:

````javascript
this["Templates"] = this["Templates"] || {};
this["Templates"]["accessError"] = {"v":2,"t":[{"t":4,"n":50,"r":"accessError","f":["\n  ",{"t":7,"e":"div","a":{"class":"alert alert-error"},"t1":"fade","f":[{"t":2,"r":"accessError"}," You must ",{"t":7,"e":"a","a":{"href":"./login"},"f":["login"]}," to see content."]},"\n"]}]};
this["Templates"]["articles"] = {"v":2,"t":[{"t":7,"e":"h2","f":["Articles"]},"\n",{"t":4,"n":52,"r":"pages.articles","f":[{"t":7,"e":"article","f":["\n  ",{"t":7,"e":"h3","f":[{"t":2,"r":"title"}]},"\n  ",{"t":7,"e":"p","f":["Posted by ",{"t":2,"r":"author"}]},"\n  ",{"t":7,"e":"p","f":[{"t":2,"r":"body"}]},"\n"]},"\n"]},{"t":8,"r":"accessError"},"\n"]};
this["Templates"]["index"] = {"v":2,"t":[{"t":7,"e":"h1","f":["Welcome to Ractive Digest"]},"\n",{"t":7,"e":"p","f":["Here we got all sorts of content!"]},"\n"]};
....
`````

You can include this file with regular ``<script>`` tag before your ``app-ractive.js``
````html
<script src="/js/templates_compiled.js"></script>
````

in your ``app-ractive.js`` connect your Ractive app with compiled templates (main) and all partials like this:

````javascript
App = new Ractive({
    el: '#app',
    template: Templates.main,
    partials: Templates,
    data: Model,
    onrender: Actions
});
````

Hope this help to somebody!

**Comment by Rich-Harris** [comment]
@martypdx :-)

@guilhermeaiolfi yes, I find it a very convenient way to develop apps, especially if the UI is where the bulk of the code lives. Definitely need to bring the documentation and examples up to speed.

@kurdin thank you for the examples! Yep, not suggesting using gobble at the same time as gulp, they overlap. spelunk will treat JSON files as JSON and non-JSON as strings, so if you've already converted your `*.html` files to compiled templates, then they will stay as objects. But I've never tried it with gulp so have no idea how you'd rig it up - your solution looks pretty decent anyway.
