### ISSUE TITLE
Magic Mode Hides Properties Defined on objects Prototype

### ISSUE THREAD

**Issue by Xero314** [ractivejs/ractive#1669]
When using magic mode, any properties defined through Object.defineProperty on the prototype chain and not the object itself are incorrectly wrapped when magic mode is enabled.

The problem here is not so much that magic mode does not work in this case (which is an issue) but that it hides the actually property making it no longer accessible on the object (it creates a new local property and getter that does not use the underlying property, as if the property never existed)

This is caused by the use of Object.getOwnPropertyDescriptor with out traversing the prototype chain.

**Comment by timoxley** [comment]
Currently ractive adds getter/setter on the instance, but if you add the getter/setter on the prototype then writes will behave strangely, as they'd normally be applied to the instance. Needs to implement some kind of copy-on write functionality that has the getter lookup the value prototype until the setter on the instance is fired.

**Comment by evs-chris** [comment]
Punting to #2512
