### ISSUE TITLE
Magic mode calls to defined property lose context ("this" is incorrect)

### ISSUE THREAD

**Issue by Xero314** [ractivejs/ractive#1670]
When using magic mode an a defined property (getter/setter) method is wrapped the wrapped call has the window as the context (this).  

This is because the oldGet method is either not defined correctly or not called correctly.

This can be resolved by either:
oldGet = descriptor.get.bind(originalWrapper.value)
oldSet = descriptor.set.bind(originalWrapper.value)

Or

oldSet.call(this,v)
...
value = oldGet ? oldGet.call(this,) : v;

(I will make the change and put in a pull request when I find time, if no one gets to it first)

**Comment by Rich-Harris** [comment]
@Xero314 sorry for the slow response. Can you elaborate on what you mean? I haven't been able to reproduce it from the description (http://jsfiddle.net/rich_harris/1eshd4ne/) - if you could show what you mean in a JSFiddle that'd be ideal. Thanks
