### ISSUE TITLE
Converting/casting/formatting values with two-way binding

### ISSUE THREAD

**Issue by fabien** [ractivejs/ractive#1674]
It would be helpful if the inbound and outbound value could be specified separately, for example:

```
<select value="{{active}}" get="{{active ? 'y' : 'n'}}">
  <option value="y">Yes</option>
  <option value="n">No</option>
</select>

var ractive = new Ractive({
  template: ...,
  data: { active: true } // a boolean
});
```

The above can already be achieved using an additional `computed` property with both a `get` and a `set` function to handle the conversion. Perhaps this can be implemented in a more unified manner?

Likewise, it would be interesting to be able to handle input values and convert/cast them before actually updating the data (model), reminiscent of the initial issue at #488 - the `observe` solution works, but it doesn't exactly feel elegant. Perhaps this would work?

```
<input value="{{active}}" set="parseBoolean" />

var ractive = new Ractive({
  template: ...,
  data: { 
     active: true, 
     parseBoolean: function(value) {
        return value === 'y';
     }
   }
});
```

**Comment by martypdx** [comment]
> The above can already be achieved using an additional computed property with both a get and a set function to handle the conversion. Perhaps this can be implemented in a more unified manner?

Aren't computed properties the unified way?

```
<select value="{{yesno}}">
  <option value="y">Yes</option>
  <option value="n">No</option>
</select>

var ractive = new Ractive({
  template: ...,
  data: { active: true }, // a boolean
  computed: {
     yesno: {
       get: '${active} ? "y" : "n"',
       set: function(value){ this.set('active', value === 'y'); }
     }
  }
});

```

Are you looking for a pure template solution?

**Comment by fabien** [comment]
Thanks for the example - it's close to what I had (except for the getter as a string). 

However, I believe it does make sense to have `get` and `set` alongside `value` for two-way binding. 

What do you think?

**Comment by martypdx** [comment]
It occurred to me that with `edge` you have 90% of a solution (see http://jsfiddle.net/bdhrtqg3/):

```html
<select value='{{active ? "y" : "n"}}' twoway='false' 
        on-change='set("active", event.node.value === "y")'>
    <option value="y">Yes</option>
    <option value="n">No</option>
</select>

**Comment by fabien** [comment]
Thanks, that does work indeed. It doesn't exactly look elegant though. How would it look with `on-set`?

**Comment by matthew-dean** [comment]
Re: computed properties. Computed properties don't work very well when dealing with large arrays with "each" loops. In that case, you still want to be able to bind, say, the numeric result of a select element to a property of that member the array.

Observers also kind of work, but they're verbose, and they can get tricky when you have multiple fields that need the same conversion. It would be nice to be more declarative about how data should be handled, either in the HTML template, or by coercing against a schema in JS. (Probably the template is easier.)

**Comment by evs-chris** [comment]
You can actually use `{{true}}` as an option value, and the right thing will happen. For text inputs, handling the binding and formatting with a purpose-built decorator tends to be a better approach.
