### ISSUE TITLE
Preserve HTML comment tag on template processing for development env

### ISSUE THREAD

**Issue by kurdin** [ractivejs/ractive#1675]
It would be nice to have an option to keep HTML comment tags while compiling templates from Mustache, at least for development and remove it on production. It would help to identify templates and partial that has been used for final html rendering. 

let say I have html comments in my template's file:
````html
<!-- Template ./templates/index.html -->
<div class="tray">
  {{ > main_content }}
</div>
<!--/ Template ./templates/index.html -->
````
and another template file:
````html
<!-- Template ./templates/main_content.html -->
  <main class="tray__content">
    {{ i18n.t('hello', {name: user.name}) }}
    <p>Lang is: {{ lang }}</p>
  </main>
<!--/ Template ./templates/main_content.html -->
````
I want to keep those comments in final HTML rendered by ractive, so I can explore DOM with Dev Tools and see what templates/partial file has been used for generated HTML. 

For production, I would like to remove all comment tags.

**Comment by MartinKolarik** [comment]
There's a `stripComments` option: http://docs.ractivejs.org/latest/options#stripComments

**Comment by kurdin** [comment]
Sorry I could not find it in docs, I was looking in [Mustaches](http://docs.ractivejs.org/latest/mustaches) could you please add ``stripComments`` explanation in ``Comments`` section on http://docs.ractivejs.org/latest/mustaches

@MartinKolarik. Thank you very much!

**Comment by MartinKolarik** [comment]
`stripComments` only applies to HTML comments, not mustache comments.

**Comment by kurdin** [comment]
Yes, I understand this, but it would be nice have explanation something like this (taken from http://handlebarsjs.com/)

The comments will not be in the resulting output. If you'd like the comments to show up. Just use html comments, and they will be output.
````html
<div class="entry">
  {{! This comment will not be in the output }}
  <!-- This comment will be in the output -->
</div>
````

**Comment by MartinKolarik** [comment]
Ah, I see. Fair enough!
