### ISSUE TITLE
Templates inheritance

### ISSUE THREAD

**Issue by PaquitoSoft** [ractivejs/ractive#1679]
Hello,

First of all I'd like to say a big THANKS for your work. The more I use Ractive, the more I like it.

I'm evaluating Ractive for a new project (quite big) I'm facing. In my last project I was using dustjs (linkedin fork) for server side rendering and handlebars for client-side. 
This time, I would like to use a SPA approach and Ractive seems like a great tool. I need to be able to render server side for the first page view to be a quick as possible from the user's side and to help SEO.
Right now I have a mixture of dustjs and ractive mustache-like templates in my views because I need dustjs for template inheritance because I don't know how to do it with Ractive.

I need to have an application layout (I could have several layouts for different areas of the web) with some optional points of extensions.
Here is a (dustjs) example:
(File: /views/layouts/application.dust)
```html
<!DOCTYPE html> 
<html>
	<head>
		
		{! META tags section !}
		<meta charset="utf-8" />
		{+customMetaTags/}		
		
		<title>{docTitle|s}</title>
		
		{! STYLE tags section !}
		<link rel="stylesheet" href="/styles/common.css" />
		{+customStyles/}

		{! Some dynamic hreader links (canonicals) !}
		{+customHeadLinks/}	
		
	</head> 

	<body> 
		
		{! Content header !}
		{+contentHeader/}
		
		{! Main content section !}
		{+contentBody/}
		
		{! Main menu section !}
		{> "mobile/partials/layout/main-navigation-menu" /}

		{! Incluimos las dependencias JS de la aplicacion !}
		<script data-main="/js/main.js" src="/js/require.js"></script>

		{! Some pages need to include third-party scripts at the bottom of the page !}
		{+externalServicesScripts/}

	</body>
</html>
```

In the layout I have some sections which can be filled from the specific views. For instance, this could be the home page view:
(File: /views/home.dust)
```html
{> "layouts/application" /}

{<customMetaTags}
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui" >
{/customMetaTags}

{<customStyles}
	<link rel="stylesheet" href="/styles/home.css" />
{/customStyles}

{<contentBody}

	{! Landing main image !}
	<img src="/images/landing.jpg">
	
{/contentBody}
```

¿Is there any way I can get this working with Ractive?

Thanks.

**Comment by jbgutierrez** [comment]
Adding support to this seems feasible adding some middleware to your stack. Check out this example at https://github.com/jbgutierrez/ractive-server-side/commit/9ad00368e1bfaac1a73b45084f447aed4a2af55c#diff-1.

It will be nice to hear from the core team whether or not they are supporting this in a near future. Whatever they might decide, this framework is fantastic!

**Comment by martypdx** [comment]
Only in edge right now, but you can use named yields (see http://jsfiddle.net/r7x3ppb2/):

```html
<script id='page' type='text/ractive'>
    <header>
        {{yield header}}
    </header>
    <main>
        {{yield main}}
    </main>
    <footer>
        {{yield footer}}
    </footer>
</script>

<script id='example' type='text/ractive'>
    <page>
        {{#partial header}}
        I'm the header
        {{/partial}}
        
        {{#partial main}}
        I'm the body
        {{/partial}}
        
        {{#partial footer}}
        I'm the footer
        {{/partial}}
    </page>
</script>
```

**Comment by PaquitoSoft** [comment]
@jbgutierrez Thanks for the idea. That was my last bullet and I was evaluating an existing middleware to get it done in my project (https://github.com/mytharcher/mustlayout). The problem with this approach in that the template is parsed twice (first the middleware and then ractive).

@martypdx This seems the way to go and I will try it ASAP to check if it meets my needs. As the project I'm starting will go live in 3 or 4 months I would like to know if this functionality is scheduled to get in any new release soon. Do you have any idea about that?

Thank you both!

**Comment by PaquitoSoft** [comment]
@martypdx I can confirm named yields fulfills my requirement; thanks for your help. 
Any idea about when it's going to be available in a stable branch or in a new release?

**Comment by martypdx** [comment]
`0.7` has been lingering with an extended holiday hangover :) Definitely a bit longer than we usually like to go without a new release. I'm sure it's on @Rich-Harris' mind as well, probably a February todo.

**Comment by Rich-Harris** [comment]
What @martypdx said! I was actually trying to put together a demo for this issue the other day, but ran into #1680 and #1681 along the way. I'd love for us to get a new release out this month, and I don't think that's at all unrealistic (though it's not exactly a guarantee either!) Been road-testing it at work and we're seeing some decent performance boosts :-)

**Comment by PaquitoSoft** [comment]
Thank you, guys! I feel named yields and "Progressive enhancement / client-side rehydrate" (https://github.com/ractivejs/ractive/issues/395) will definitely move forward Ractive for server-side rendering.
