### ISSUE TITLE
IE8: Error while clicking "on" Ractive

### ISSUE THREAD

**Issue by kraftwer1** [ractivejs/ractive#1691]
I got this error when I click on ```<p>My template</p>```:

**Error: Object doesn't support this property or method**
_Line: 2776: if ( this.hasOwnProperty( i ) && this[ i ] === needle ) {_

```html
<!DOCTYPE html>
<html>
    <head>
        <script src="/ractive/ractive-legacy.js"></script> <!-- Version 0.6.1 -->
    </head>
    <body>
        <div id="comments1"></div>

        <script>
            new Ractive({
                el: "comments1",
                template: "<p>My template</p>"
            });
        </script>
    </body>
</html>
```

**Comment by dagnelies** [comment]
Works fine for me under IE8 with both
http://cdn.ractivejs.org/latest/ractive-legacy.js (0.6.1)
and
http://cdn.ractivejs.org/edge/ractive-legacy.js (0.7.0)

**Comment by kraftwer1** [comment]
Can you provide a little example? Or does my example work 1:1? Which doctype did you use?

**Comment by kraftwer1** [comment]
Did you turn on error warnings in IE8?

**Comment by dagnelies** [comment]
yes, 1:1 on my local machine

**Comment by kraftwer1** [comment]
What is IE8 emulation mode? You mean it's not a real IE8? Or do you mean something like compatibility view?

**Comment by dagnelies** [comment]
It's IE 11 set with emulation mode of IE 8 in the developer console. Usually, it catches all the old IE quircks.

**Comment by kraftwer1** [comment]
Oh, I see. Unfortunately, my customers have real IEs...

**Comment by dagnelies** [comment]
I'm still suprised it cannot be reproduced in emulation mode. Can you actually reproduce the bug with the same snippet you showed and http://cdn.ractivejs.org/latest/ractive-legacy.js ?

**Comment by kraftwer1** [comment]
Yes, and also with the edge version.

**Comment by dagnelies** [comment]
It works flawlessly for me. I'm curious if others can reproduce it. Perhaps it's related to some unusual settings/system/environment you have.

**Comment by kraftwer1** [comment]
@Rich-Harris can you?

**Comment by akhoury** [comment]
I cannot reproduce, using __real__ IE8, in neither Standard and Compatibility modes
https://jsfiddle.net/bentael/34k8had1/embedded/result/ (to view a jsfiddle in IE8 you must use full url)

Could this be related ? http://stackoverflow.com/a/8159434/493756

@kraftwer1 maybe you can add a log right before 
```javascript
 console.log(this.toString && this.toString()); // this way we would know if it's native or not
 if ( this.hasOwnProperty( i ) && this[ i ] === needle ) {
```

**Comment by Rich-Harris** [comment]
@kraftwer1 I don't have a machine with IE8 to hand (am downloading a VM from modern.ie but it's taking its sweet time). I assume the error refers to the fact that there's a missing `hasOwnProperty` method. Can you provide a stack trace? It's possible that Ractive itself isn't at fault, but rather that the `indexOf` polyfill it registers (the offending line is [here](https://github.com/ractivejs/ractive/blob/bc74ffeb728a8d328df9ebc9a3c33af9606484ed/ractive-legacy.js#L2776)) is causing problems with your app. (Related: @akhoury's suggestion that the legacy build be discontinued - #1636)

**Comment by kraftwer1** [comment]
I also used the one from modern.ie (and turned on error alerts). There was no stack trace, just this error. I had to solve the problem differently, so if you guys can't reproduce it, this issue can be closed.
