### ISSUE TITLE
component content not working

### ISSUE THREAD

**Issue by gefinity** [ractivejs/ractive#1693]
Apologies if I've misunderstood what ```>content``` is meant to do, but basically what I want to do is pass through the inner content from my component to the component's template: 

```
var Link = Ractive.extend({
    template: "<a href class={{class}}>{{>content}}</a>"
});

new Ractive({
    template: "<Link class='someClass'>What are you doing dave?</Link>",
    el: "body",
    components: {
        Link: Link
    }
});
```

expecting the below in the resulting DOM

```
<a href class='someClass'>What are you doing dave?</a>
```

The component renders and the class data is rendered of course but the <a/> tag is empty and the string content just appears underneath as a text node

Have I misunderstood ```>content``` completely? is there another way to do this?

http://jsfiddle.net/qjwdyt1w/

**Comment by dagnelies** [comment]
Hi,

`Link` is already an official HTML tag:
http://www.w3schools.com/tags/tag_link.asp

Yau cannot replace those. Just change the component name and it'll be all right:
http://jsfiddle.net/qjwdyt1w/2/

Cheers

**Comment by martypdx** [comment]
I think there's something else going on here.  It works with tags like `div`: http://jsfiddle.net/cy2bc6u9/.

If you look at the rendered output, it's putting the content after the tag:

```html
<body><a href="" class="someClass"></a>What are you doing dave?</body>
```

**Comment by martypdx** [comment]
Oh, the parser probably has special logic for `link` and other void tags: http://www.w3.org/html/wg/drafts/html/master/syntax.html#void-elements. So these can't be used as component tags, but non-void elements can be used.

**Comment by gefinity** [comment]
Thanks guys, makes since to me :-) Using a unique tag name works exactly as expected and seems like the right call.
Probably can close this now? unless you think the lib should give a warning/maybe throw?

**Comment by dagnelies** [comment]
+1 for giving a warning/error, it wouldn't harm

**Comment by Rich-Harris** [comment]
Agree, the parser should provide more useful feedback in this situation. Have opened #1714
