### ISSUE TITLE
Component observe being called twice for array data

### ISSUE THREAD

**Issue by vcatalano** [ractivejs/ractive#1695]
I ran into this issue recently while using components. It appears that the when using **observe** within the **oninit** callback of a component, the observe callback will be called twice. Inspecting the values of the callback shows the same exact values. Also, this doesn't occur when observing non-array values.

Here is a JSFiddle showing the problem: http://jsfiddle.net/b52tjdsc/.

Here is an example of the component's observe callback that is being fired twice whenever the **items** array is changed.

```javascript
var Component1 = Ractive.extend({
    template: '#component1',
    oninit : function() {
        // This observe callback is being fired twice!
        this.observe("items", function(newItem, oldItem, keypath) {
            console.log("New Item: " + newItem);
            console.log("Old Item: " + oldItem);
            console.log("Keypath: " + keypath);
        });
    }
});
```

**Comment by martypdx** [comment]
I noticed that this week too

**Comment by martypdx** [comment]
Turned out to be a more general issue with multiple change commands (like `merge` which queues up changes for each array index position as well as the array itself) that would queue up additional upstream notifications for keypaths that were already in the dependent queue.
