### ISSUE TITLE
Set default variables

### ISSUE THREAD

**Issue by arxpoetica** [ractivejs/ractive#1696]
For what it's worth, we did the following, and it's awesome:

```
Ractive = Ractive.extend({
	setDefault: function(key, value) {
		this.set(key, value);
	},
	// ...
});
```

The idea is that you can set default variables *after the fact*, after initializing the app. I think there are probably other methods for this, but having a simple function available like this is awesome.

**Comment by chen844033231** [comment]
its a good idea. but if i what to setDefault to app. i just need to:
```javascript
ractive = new Ractive({
    el:'',
    template:'',
    data:{
        key:value,
        key,value
    }
});
//or 
ractive = new Ractive({
    el:'',
    template:'',
    oninit:function() {
	//do something default,this will be fire when the instance is ready to be rendered.
   }
});
```
but its very interesting.i like it.

**Comment by arxpoetica** [comment]
The use case is if you need to set something, say, AFTER bootstrapping your app. Such as loading data after an AJAX call. Or just late in the game, for whatever reason.

**Comment by martypdx** [comment]
@arxpoetica I've stared at your snippet for awhile and not sure I get it. It's just an alias for `set` as `setDefault`? Or am I missing something?

**Comment by arxpoetica** [comment]
@martypdx it may not fit the Ractive convention (it's probably hackish), but it seems to work.

The idea here is that this is all done before instantiating any actual components, and therefore the data is available to *all* components as "defaults." I'm not sure if this is just a loophole in the code, or if it happens to be doing what it should. Ignore for the moment that `this.set(key, value);` is present. I could use AJAX to set some defaults in a similar way:

```
Ractive = Ractive.extend({
	data: {
		setSomeKey: function() {
			$.ajax('/some/url', function(someValue) {
				this.set(someKey, someValue);
			});
		}
	}
});
```

The main thing to note is that I'm extending Ractive before setting any components, and `setDefault` or this AJAX methodology will set default variables (global to all inherited components of the main Ractive app) asynchronously or after initializing and rendering any components.

Am I making any more sense?

**Comment by arxpoetica** [comment]
Another way to put this, one cannot set defaults on components that have already been initialized and rendered. (Or, at least, I don't know another way. :smile:)

**Comment by Madgvox** [comment]
What do you do if you attempt to access the variable before it's been 'defaulted'? Or are you building your application around that issue?

**Comment by arxpoetica** [comment]
That can certainly be an issue, but that can be an issue anyway. It all depends on how one first declares data.

The short answer is to just check if data exists:

```
if (!this.get('defaultVariable') ...

[or]

{{#if defaultVariable}}
...
{{/if}}
```

The longer answer is...one might be able to build around the absence of defaults, but it just seems easier to detect if/when they come into existence through some simple if/else checks.

**Comment by martypdx** [comment]
@arxpoetica I don't see how that works. It only sets the data on the instance. Unless you're changing a property of an object reference.

I usually use the view root, not the inheritance root, for global data. Unless it's static data that can be set before extend the components.

**Comment by arxpoetica** [comment]
I'm tellin' ya, it works! :stuck_out_tongue_winking_eye: 

Really, though, not trying to make an issue. I definitely want to do things the right way. This absolutely does seem to be working for our purposes, but since we're in a long term relationship with Ractive.js, I would like to understand the correct way to set globals. I'm not sure what `view root` means in this context. Do you have an example?

Again, concerned w/ setting *non* static data. This is data that is set (after extending and initializing components), manipulated, changed, deleted, etc.

Thanks!

**Comment by martypdx** [comment]
Not sure how you're using, what I mean is it is not shared across instances (even same type of component). See http://jsfiddle.net/p313srgg/1/.

This does share across all instances: http://jsfiddle.net/p313srgg/2/. __But__ it doesn't update all instances when you set from one: http://jsfiddle.net/p313srgg/3/.

By "view root", I mean the top level ractive instance (assuming you have one) that contains all the rest of the layout and components. Here's a pattern I like to use: http://jsfiddle.net/p313srgg/5/

But I learn from everyone else too, so maybe you're onto something I'm not realizing.

**Comment by Madgvox** [comment]
Yeah, I'm totally lost. These two fiddles operate identically, for example:
http://jsfiddle.net/p313srgg/6/
http://jsfiddle.net/p313srgg/7/

But I might be totally misinterpreting your use-case. Do you have a real-world example?

**Comment by arxpoetica** [comment]
Awesome thanks for the feedback, guys. I'll try and set something up today for comparison.

**Comment by Madgvox** [comment]
Hey, I'm going to close this issue since you haven't responded yet. If you're still interested in providing an example of the behavior you're describing feel free to reopen the issue any time. Thanks!
