### ISSUE TITLE
ractive.set can use funciton callback. and so on.

### ISSUE THREAD

**Issue by chen844033231** [ractivejs/ractive#1697]
like jquery.Ractive should be add function to set variable or so on like that.
```javascript
ractive.set( "name", function( oldName ) {
 //oldName value is the name. and i can do something use oldName . like name+'!';
return 'hello' + oldName + '!';
})
```
i think , that is awesome. is it?

**Comment by Madgvox** [comment]
You can actually do this using [computed properties](http://docs.ractivejs.org/latest/computed-properties).

Using your example:
```js
// ...
computed: {
  "name": {
    get: function() {
      return 'hello' + this.get( '_name' ) + '!';
    },
    set: function( value )
      this.set('_name', value);
    }
}
// ...
```

**Comment by chen844033231** [comment]
o , i see. that is ok. All Roads Lead to Romebut . i mean, if Ractive support function, it will be simple. i dont want to using computed to finish the simple ask.
```javascript
ractive.set('level',function() {
 if( ractive.get('level') == 'master' ) {
return 'master';
}else {
return 'general';
}

// if i use computed, logic is not clear.
// not just the set method. like event method on. off.and insert. and so on.
// the more importantly I want to according to the logic of the return value.
});
function masterHandler() {}
function generalHander() {}
//have two Event.
//if use 0.7.0 React. it may be like this:
if( ractive.get('level') == 'master' ) {
 ractive.on( 'levelClick', masterHandler );
}esle {
  ractive.on( 'levelClick', generalHandler );
}
//think about if support function, something will be happen.
```

**Comment by Madgvox** [comment]
I'm afraid I'm not following you. What you're describing seems like it's simple to implement either as a computed listener or as simple javascript logic outside of ractive.

This snippet:

```js
function masterHandler() {}
function generalHander() {}

if( ractive.get('level') == 'master' ) {
  ractive.on( 'levelClick', masterHandler );
} else {
  ractive.on( 'levelClick', generalHandler );
}
```
Is explicitly possible inside of ractive as of right now.

Additionally you would run into a conflict of interests in that you can already set a keypath to a function, and then call it in the template like so: `{{ myFunction() }}`. Defining special behavior for functions in `set()` would remove that functionality.

**Comment by martypdx** [comment]
You can also choose handlers in the template:

```html
{{#items:i}}
  <button on-click='{{level==="master"?"masterLevel":"generalLevel"}}:{{i}}'>Select</button>
{{/items}}
```

**Comment by Rich-Harris** [comment]
@chen844033231 Sorry, this is a wontfix - the `value` in `ractive.set(key, value)` can be any data type, including a function, so it would be impossible for Ractive to know what it was supposed to *do* with the function. Unless we're missing something it's already very easy to do what you need, so I'm going to close this issue
