### ISSUE TITLE
[feature-request] multiple Inheritance, Ractive.extend(A, B, C)?

### ISSUE THREAD

**Issue by akhoury** [ractivejs/ractive#1700]
You know if I had a common prototype which I want to extend to use for multiple components.
```
var Foo = Ractive.extend(protoA, protoB, protoC);
```

Right now I do this
```
var Foo = Ractive.extend($.extend(true, protoA, protoB, protoC));
```

**Comment by martypdx** [comment]
Easy enough, but fyi Ractive does some magic on a) combining registries, and b) wrapping overrides with `_super` so the two examples you gave are not strictly equivalent.

**Comment by akhoury** [comment]
ok - cool, thanks

**Comment by codler** [comment]
What are the difference with doing this? https://github.com/ractivejs/docs.ractivejs.org/issues/14 https://github.com/ractivejs/ractive/issues/364#issuecomment-32001114

    Ractive.extend(protoA).extend(protoB).extend(protoC)

**Comment by martypdx** [comment]
@codler This PR for this #1704 is just syntax sugar to avoid calling `.extend` successive times.

Current API as I understand it, is to take `options` or another extended instance. I wouldn't pass in a `.prototype` of anything.

Maybe your question is related to #1687?

**Comment by codler** [comment]
Okey so `Ractive.extend(protoA).extend(protoB).extend(protoC)` is same as `Ractive.extend(protoA, protoB, protoC)` now.

nope, my question was not related to #1687 :P

**Comment by martypdx** [comment]
> Okey so Ractive.extend(protoA).extend(protoB).extend(protoC) is same as Ractive.extend(protoA, protoB, protoC) now.

Yep, it was a [gratuitous opportunity](https://github.com/ractivejs/ractive/blob/dev/src/extend/_extend.js#L9-L15) to use ES6 arguments splats. :)

**Comment by akhoury** [comment]
`...options` nice
