### ISSUE TITLE
Cannot iterate object with keys that contain "."

### ISSUE THREAD

**Issue by andrey-buligin** [ractivejs/ractive#1701]
I found that context is empty object when looping through object that has keys containing "."
formFields: {
                'Joe': { email: 'joe@example.com'},
                'leaderboards.name': {
                    email: 'joe@example.com'
                }
}
In first iteration email is avalable but for "leaderboards.name" it will be empty.

**Comment by MartinKolarik** [comment]
See #396.

**Comment by andrey-buligin** [comment]
Thanks Martin
