### ISSUE TITLE
Doesn't build on windows using msysgit bash

### ISSUE THREAD

**Issue by dotnetCarpenter** [ractivejs/ractive#1706]
I tried to build Ractive on my win7 computer and ran into different issues which I will sum up here.
First, I was missing `jshint` globally, which is not mentioned in the [README.md] (../blob/dev/README.md).

After installing `jshint`, I had a path issue with gobble. Seems that the path is wrong on windows.
```shell
gobble: 03-esperantoBundle done in 1152ms
∙∙∙∙∙∙◦ 07-sorcery running...
gobble: 07-sorcery transformation failed

>>>
ENOENT, open 'c:\Users\dotnet\Projects\opensource\ractivejs\ractive\.gobble-build\03-esperantoBundle\c:\Users\dotnet\Projects\opensource\ractivejs\ractive\.gobble-build\02-6to5\1\config\02-6to5-template.js.map'
GobbleError
    at Object.<anonymous> (c:\Users\dotnet\Projects\opensource\ractivejs\ractive\node_modules\gobble\lib\utils\GobbleError.js:13:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\dotnet\Projects\opensource\ractivejs\ractive\node_modules\gobble\lib\nodes\Node.js:9:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
<<<
```
I can run `gobble` but not `gobble build tmp`. I bet that using [node `path.normalize`](http://nodejs.org/api/path.html#path_path_normalize_p) the right places will alleviate the issue. I just don't know `gobble` at all, so *can't* do it.

Obviously the test that are suppose to run on the output in `tmp/test/__nodetests/` will fail since the files are not there. Since `gobble` ran successfully, I can point the mocha test to the `gobble` folder.
```shell
# run node.js tests
echo "> running node.js-specific tests"
node_modules/.bin/mocha .gobble/17-merge/1/test/__nodetests/*.js --reporter progress
```
But then, in `basic.js` **'../../ractive'** is not found... In fact, I can't find anything simply called *ractive*, only *ractive.min.js*, *ractive-legacy.js* etc. `find . -name 'ractive*'`

The next step is minifying the .js files. I tried to alter the bash script a bit to `( cd .gobble` but got
```shell
Error: ENOENT, open 'c:\Users\dotnet\Projects\opensource\ractivejs\ractive\.gobble\*.min.js'
    at Error (native)
  fixed *.min.js sourcemap
```

At this point, I'm sure that I can't do much to successfully build Ractive on windows. But I hope this summery will help the person taking on the task of getting the build system to work on windows.
Until then...
I think prerequisites could be made more clear with a section:
### Prerequisites
You need
+ [OS X](https://www.apple.com/osx/) or [Linux](http://distrowatch.com/dwres.php?resource=major), **not** [msysgit bash](https://msysgit.github.io/)
+ [node](http://nodejs.org/)
+ [gobble](https://github.com/gobblejs/gobble) `npm i -g gobble-cli`
+ [jshint](http://jshint.com/) `npm i -g jshint`
+ [phantomjs](http://phantomjs.org/) `npm i -g phantomjs`

**Comment by Rich-Harris** [comment]
Thanks - reports like these are useful for non-Windows folk like me.

It says the [sorcery](https://github.com/Rich-Harris/sorcery) transformation failed - looks [like](https://github.com/Rich-Harris/sorcery/blob/master/src/Node.js#L146) [these](https://github.com/Rich-Harris/sorcery/blob/master/src/utils/getRelativePath.js#L4-L5) [lines](https://github.com/Rich-Harris/sorcery/blob/master/src/utils/getRelativePath.js#L19) may be at fault, should probably be using `path.sep` rather than `'/'`. Will fix that later when I get a chance.

You shouldn't need jshint and gobble installed globally IIRC - they're listed as devDependencies (I'm referring to the dev branch which is the default, by the way). You just need to run `npm run build` or `npm run serve` and it will use the local installations. I've just checked and it looks like it *is* expecting a global phantomjs installation, but that's easy to fix - another TODO.

Has anyone out there succeeded in building Ractive on Windows? @evs-chris, @MartinKolarik I seem to recall you may have some expertise in this matter...

* [ ] fix sorcery
* [ ] use local phantomjs installation

**Comment by martypdx** [comment]
> I've just checked and it looks like it is expecting a global phantomjs installation, but that's easy to fix - another TODO

I think that's taken care of with #1689

> You shouldn't need jshint and gobble installed globally IIRC - they're listed as devDependencies (I'm referring to the dev branch which is the default, by the way). You just need to run npm run build or npm run serve and it will use the local installations.

In my experience, cli tools don't get picked up on command line unless they're `-g`. If I'm right about this, it might be worthwhile to use a node module that invokes gobble.

**Comment by Rich-Harris** [comment]
> I think that's taken care of with #1689

Ah, thanks. I think the `test.sh` script needs to point to the local installation though: https://github.com/ractivejs/ractive/blob/dev/scripts/test.sh#L8-L11. Will push that fix momentarily. Same goes for gobble and jshint - they're installed locally but `build.sh` isn't pointing at the local installations! D'oh.

**Comment by martypdx** [comment]
They're in the `devDependencies`, but just to note: it won't work if someone has those installed globally and not locally.

**Comment by evs-chris** [comment]
I have the build running on win8 with msys up to running the phantom tests, but phantom is bailing with EINVAL when trying to pipe stdin from the bin wrapper to the actual exe.

**Comment by MartinKolarik** [comment]
It seems that the problem with sorcery isn't actually a problem with sorcery, but with esperanto, namely [this line](https://github.com/esperantojs/esperanto/blob/8a30a746facea90f6de91d3973b16b0dcb9568b0/src/utils/packageResult.js#L19). Changing `options.sourceMapFile[0] === '/'` to `/^(?:[A-Za-z]:)?[\\/]/.test( options.sourceMapFile )` fixes the problem.

**Comment by Rich-Harris** [comment]
@MartinKolarik Ah, okay, thanks. I fixed sorcery anyway (after a deeply tedious afternoon trying to get a Windows environment set up on this new laptop. I am genuinely baffled: how do Windows users get any work done?), and I'm trying to get esperanto building and testing now.

**Comment by Rich-Harris** [comment]
Ractive is now building on Windows (at least for me...) - after doing a `git pull` it's probably best to `rm -rf node_modules` (or whatever the Windows equivalent is) and do a fresh `npm install`, as there are one or two things that have been fixed further upstream.
