### ISSUE TITLE
sandbox not working, can't find Ractive.js

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1712]
Getting caught up on the changes the the dev environment. Sandbox doesn't appear to work anymore, failing with not being able to find `http://localhost:4567/src/Ractive.js `. Judging by the directory presented at `http://localhost:4567`, there doesn't appear to be a `src` folder.

**Comment by Rich-Harris** [comment]
Ah, yes - the `_base.html` file was updated but `sample/index.html` wasn't. Now fixed. Since overhauling the build process, the tests and sandbox folders are root-level along with the (built) library itself - no more messing around with AMD :)
