### ISSUE TITLE
Missing "click" event plugin when running over jsdom

### ISSUE THREAD

**Issue by akula1001** [ractivejs/ractive#1713]
I get the following error when running over jsdom. I have a simple template with an on-click directive.

`Missing "click" event plugin. You may need to download a event via http://docs.ractivejs.org/latest/plugins#events`

I solved the issue for myself by removing this return.
https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Element/EventHandler/prototype/listen.js#L33

Would it be all right to make this a warning instead and attempt to add the listener in any case?

**Comment by Rich-Harris** [comment]
Ah, interesting. Didn't know that about jsdom. I suppose there are two things we need to establish:

1. Is there any other way (cross-browser and jsdom) to determine whether an element supports a particular event?
2. Is there any potential harm from doing `node.addEventListener('lol', lolHandler)`, or are they simply ignored?

I don't know the answer to either of those questions off the top of my head.

Also, I'm interested to know more about your use case - is this for automated testing?

**Comment by akula1001** [comment]
For unit testing specifically. I want to load my component in isolation and use plain javascript to trigger actions on it. Much like these tests for React components.
http://facebook.github.io/jest/docs/tutorial-react.html#content

I don't know much about 1) but for 2) W3C does specify here that the method throw no exceptions.
http://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-Registration-interfaces

**Comment by Rich-Harris** [comment]
Closed via #1811 - Ractive detects whether it's running in JSDOM (via `navigator.appName`), and skips the warning etc if so. Would be grateful if you could try this out and confirm that it's actually fixed, thanks! http://cdn.ractivejs.org/edge/ractive.js
