### ISSUE TITLE
Investigate AppVeyor failures

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1716]
Have hooked Ractive up to AppVeyor (a bit like Travis for Windows) so that situations like #1706 don't arise again. For some reason, it's not working (even though it builds on Windows locally, at least for me in a VM), due to [this line](https://ci.appveyor.com/project/Rich-Harris/ractive/build/1.0.1/job/wpy4s3u2g6e2n6ni) (175):

![screen shot 2015-02-15 at 4 40 49 pm](https://cloud.githubusercontent.com/assets/1162160/6205122/75130ffa-b531-11e4-82ec-e80837d724b2.png)

Not sure why that's causing problems.

**Comment by Rich-Harris** [comment]
Any Windows folk have any insight into this? I've tried being more explicit about which test file to run, but Mocha is still giving the same error. It works fine for me locally...

https://ci.appveyor.com/project/Rich-Harris/ractive/build/1.0.51/job/i3vmyvjw5rn9jbej (line 173)

**Comment by codler** [comment]
What have you installed to run Bourne shell on windows? Do Appveyor have shell?

**Comment by codler** [comment]
@Rich-Harris  Could it be that you forgot to run `build.sh` script before running `test.sh` script?

**Comment by codler** [comment]
Im looking on [appveyor.yml](https://github.com/ractivejs/ractive/blob/dev/appveyor.yml) and the log and see it will only run `test.sh`. I compare it with [.travis.yml](https://github.com/ractivejs/ractive/blob/dev/.travis.yml) and see it will run `build.sh`. Looking closer inside `build.sh` I see `$MOD/gobble build tmp` runs before `test.sh`. I believe `$MOD/gobble build tmp` is missing in appveyor.yml

**Comment by Rich-Harris** [comment]
@codler oops, good spot! The test files don't exist until `npm run build` happens. I have updated the appveyor.yml file and have the appropriate headwear prepared for when it successfully builds. Thanks :)

![duncecap](https://cloud.githubusercontent.com/assets/1162160/6308002/86309de4-b90e-11e4-93fe-5c7a965026fc.jpg)

**Comment by evs-chris** [comment]
AppVeyor seems to be pretty happy these days...
