### ISSUE TITLE
.splice bug: Cannot read property 'unbind' of undefined

### ISSUE THREAD

**Issue by nitriques** [ractivejs/ractive#1718]
Usign both call style yeilds the same error: Uncaught TypeError: Cannot read property 'unbind' of undefined line 7283

```js
ractive.data.saves.splice(i, 1);
ractive.splice('saves', i, 1);
```

**Comment by Madgvox** [comment]
1) Have you checked that this bug occurs in edge? If you temporarily replace your ractive.js file with [this](http://cdn.ractivejs.org/edge/ractive.js), you can test if this this has not already been fixed.

2) If that doesn't work, try to reproduce the error in a [jsfiddle](http://jsfiddle.net). If you're unable, please post the context of where this error is occuring. Two abstracted lines is generally not sufficient enough to figure out what is going wrong.

**Comment by nitriques** [comment]
> 1) Have you checked that this bug occurs in edge?

Yes, both 0.6 and edge (0.6.1) are affected. Both minified version and un-minified.

> two abstracted lines is generally not sufficient enough to figure out what is going wrong.

Yeah I was in a hurry to go to bed yesterday, I'll post a quick fiddle ASAP. Thanks.

**Comment by nitriques** [comment]
OH sorry, I've tested latest, not edge. Will give a shot at edge ASAP.

**Comment by nitriques** [comment]
using edge yields the save problem. Coding a fiddle right now.

**Comment by nitriques** [comment]
There you go:

http://jsfiddle.net/nitriques/jvdfajse/

Line 16 is why it crashes. (removing it and everything works) So it seems to be a problem with magic mode.

**Comment by dagnelies** [comment]
Hi,

In my experience, the "magic mode" is a bit buggy. Here as well, there are some "magic" issues.

If you replace:
`ractive.data.saves = [];`
with
`ractive.set('saves', []);`
it actually works.

As illustrated here:
http://jsfiddle.net/jvdfajse/1/

...that said, it's definitely a "magic" bug.

**Comment by nitriques** [comment]
Well thanks for the explanation and the quick fix.

But magic mode is really the one thing why I chose ractive. Kind of sad about it now.

**Comment by dagnelies** [comment]
Yeah, I understand where you're coming from. From my experience, ractive is still great though, even without magic mode.
Here is another piece to inspire you:
http://jsfiddle.net/jvdfajse/4/

**Comment by nitriques** [comment]
Hum thanks a lot, but I do not understand the first part... Can you comment it please :smile: ?

**Comment by Madgvox** [comment]
It does appear to be a bug with magic mode of some kind, but this looks to be an actual bug:

http://jsfiddle.net/jvdfajse/5/

Reassigning `saves` is what's causing the errors to occur. If you swap out the comments it will break again.

**Comment by nitriques** [comment]
Yeah I understood that thanks! I was wondering about @dagnelies's fiddle.

**Comment by Madgvox** [comment]
Oops, haha! I totally missed @dagnelies original comment stating exactly what I did!
Here's a commented version of his fiddle: http://jsfiddle.net/jvdfajse/6/

That said, you can easily inline the splice operation in the template and not worry about that like I did here: http://jsfiddle.net/jvdfajse/5/

**Comment by nitriques** [comment]
Oooooh ! Really clever the remove as a default!!! :smile: Thanks!

**Comment by anywhichway** [comment]
I am getting the same error even when not trying to splice at the end of an array. Below is the stack trace if I execute somearray.splice(i,0). It appears to happen more frequently with very rapid user interaction deleting items. Putting a try/catch around the splice action will catch the error; however, the UI then gets into an illdefined state and stops behaving properly. I have been unable to create a simple jsfiddle at this point.

Uncaught TypeError: Cannot read property 'unbind' of undefined
ractive.js:7276 
rebindIfNecessaryractive.js:7263 
Section$shuffleractive.js:13842 
(anonymous function)ractive.js:13841 
Viewmodel$smartUpdateractive.js:12659 
viewmodel$get_arrayAdaptor_processWrapperractive.js:12691 
methodxcompare.html:70 (anonymous function)
xcompare.html:68 
addManufacturersxcompare.html:147 
deleteProductxcompare.html:1 onclick

**Comment by martypdx** [comment]
[Here is an updated fiddle](http://jsfiddle.net/jvdfajse/7/) with the changes necessitated by deprication of `ractive.data`.

@nitriques does that look good to you?

**Comment by nitriques** [comment]
LGTM !!
