### ISSUE TITLE
How to ... ? (complicated, see inside)

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1719]
Hi,

As usual, an example is better is than a long speech:

http://jsfiddle.net/63dqmwoc/2/

The question is: how do you keep the form data and the node data in sync?

And before you say to simply inline the input fields directly in the tree, I would like to point out this example is simplified. If you have more data and bigger forms, they have to be separate ...and having a `{{separate/chosen}}` attribute is quite handy.

I guess there are several ways to solve this but I'm not quite sure what would be most appropriate. I tried to store the keypath directly, a bit like a link to the right node, but I didn't know how to even access/reference it. Moreover, there are *two* keypaths, the one local to the component and the global one ...dunno if the latter one is available at all from within the component.

**Comment by Madgvox** [comment]
I'm afraid I'm unclear on what you mean by 'in sync'. What is the expected behavior of clicking on a node versus typing in the text box?

**Comment by dagnelies** [comment]
The desired behavior is that when editing the value in the text box, you also update the value in the tree.

**Comment by dagnelies** [comment]
http://jsfiddle.net/63dqmwoc/3/

...to my own suprise, interestingly enough, it looks like doing:
`set('keypath', somedata)`
actually makes a reference and not a copy! :/
Desired or not?

...this changes the issue completely. This actually becomes a bug that the component does not get updated properly ...tricky, tricky.

**Comment by dagnelies** [comment]
Kind of solved by:
```
 onrender: function() {
        this.observe('chosen.*', function(val) {
            this.update('root');
        })
    }
```
http://jsfiddle.net/63dqmwoc/4/

...but this really feels like a workaround patch placed over a bug.
