### ISSUE TITLE
Inconsistencies

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1720]
Hi,

http://jsfiddle.net/cnopeqw7/1/

The data gets updated for both `foo` and `bar`  but does not propagate into the view.

Before telling it's a problem of propagating the change in the view, there is a broader question:
*What is the expected behavior of*
`ractive.set('bar', ractive.get('foo'))`
*To make a "copy" of `foo` or a "reference" to `foo`?*

Currently, it considers it a reference and updating one's data updates the other's data as well. However, the view is not properly updated, probably because it has no notion of references. This can be circumvented by calling `update()` at the right places but it feels very hacky.

**Comment by simongfxu** [comment]
i consider this as a bug.

**Comment by evs-chris** [comment]
In this case, it's neither a copy nor a reference. Ractive is not tracking anything by object identity internally, so this is one of the places it can't keep track of changes for you. I've had a similar issue in the past, and I've been thinking about proposing an API for doing something like a symlink within the viewmodel. In my case, I have something like a master/detail list, where one object is focused and changes automatically with selection. I don't have any code yet, but this is roughly how it would work:

```html
{{#each items}}<li on-click="link(@keypath, 'current')">{{.name}}</li>{{/}}
{{#current}}
  <input value="{{.name}}" />
{{/}}
```

@dagnelies would that cover your use-case? I don't know if it would be reasonable to try to use object identity to try to manage this or some other object tracking automatically, especially with large data.

Under the covers, `link` would create a mapping that references the current viewmodel on both sides with only the keypath changing. The reciprocal `unlink` would remove the mapping, and `link`ing an existing mapping would overwrite it. Does that sound reasonable, or have I grossly underestimated what it would take to make this work?

**Comment by dagnelies** [comment]
@evs-chris I think your `link` proposal totally makes sense. It's clear and straightforward. I'd "+1" it ;)

Moreover, I'd go one step further and provide a way to either link or copy, rather than the current way which does "something" resulting in inconsistent view/data.

**Comment by evs-chris** [comment]
I looked into a `link`/`unlink` a little, and with the way mappings work right now, links would only be allowed as top-level keys e.g. `ractive.link('foo.bar', 'baz.bat')` would not be legal because the target has more than one level in the keypath. Working around that would get expensive, but just being able to link root level keys would be worth it for me. I'll put together an RFC PR and see what happens.

Something that @martypdx has brought up something intriguing for this particular discussion over on #1590 is `KeypathAlias`es, which would theoretically solve this problem much more easily. I think if the changes mentioned over there ever came to fruition, the API here would still be applicable - the limitations would just be relaxed.

**Comment by dagnelies** [comment]
Independent from the change it would be nice to mark this as bug because it causes discrepencies between model and view. To be solved either with:
- a warning
- copying the data
- propagating the change in the view

**Comment by evs-chris** [comment]
Just wanted to note that the PR for link/unlink no longer has the top-level target requirement after @martpdx's suggestion to just use `set` and `mark`. I can't think of a good way to intercept `ractive.set('foo', ractive.get('bar'))` without adding a bunch of overhead, but someone else may be able to.

**Comment by dagnelies** [comment]
@evs-chris Hi, could you please link the comment you're talking about?

**Comment by evs-chris** [comment]
I can't figure out how to link directly to an issue comment, so the suggestion was the seventh comment in #1722 and I responded in the last comment with details on the implementation.

**Comment by Madgvox** [comment]
Clicking on the timestamp of a comment gives you a permalink to the comment: https://github.com/ractivejs/ractive/pull/1722#issuecomment-74619136. I've had to figure that one out a couple of times because I found it then promptly forgot where it was again.

**Comment by Madgvox** [comment]
I'm closing this as #2172 has solved this use case. If someone feels like there is more to discuss regarding specifically the behavior outlined in the OP, feel free to reopen this thread.
