### ISSUE TITLE
Encapsulated CSS vanishes if a container element has an outro

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1725]
Pretty sure this is a regression http://jsfiddle.net/rich_harris/1qaL8q37/

**Comment by Rich-Harris** [comment]
New rule: rather than carefully trying to orchestrate the addition and removal of CSS as and when components enter and leave the page, I reckon it makes more sense if CSS is added to the page at the point of `Ractive.extend()`. At the cost of *occasionally* having a more complex CSSOM than is necessary, this means...

* way less state management (no listening for transition ends, etc)
* the CSSOM doesn't keep changing (theoretically better for performance, as it will avoid re-layouts in some situations
* easier debugging - you can inspect the encapsulated styles in the page, without them changing under your cursor
* easier debugging - non-encapsulated styles (`noCssTransform: true`) will do whatever damage they're capable of immediately, rather than surprising you when the component in question is rendered for the first time
* we can remove some code

Working up a PR now.

**Comment by martypdx** [comment]
> rather than carefully trying to orchestrate the addition and removal of CSS as and when components enter and leave the page, I reckon it makes more sense if CSS is added to the page at the point of Ractive.extend()

:+1:
