### ISSUE TITLE
Boolean attributes in components

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1727]
For regular elements, an attribute without a value is interpreted as 'true'. For components that's not the case - I'd argue that it should be http://jsfiddle.net/rich_harris/nk649buL/

**Comment by martypdx** [comment]
:+1:

**Comment by MartinKolarik** [comment]
Are we talking about boolean attributes (checked, readonly, ...), or all attributes without a value? A non-boolean attribute without a value is interpreted as an empty string for regular elements.

**Comment by martypdx** [comment]
My understanding is that this is would be limited to:
* component tags only
* missing values `<widget foo/>`, not empty values `<widget foo=''/>`

**Comment by Rich-Harris** [comment]
> component tags only

Yes. I suppose if you wanted to be precise about it, the component would have to declare which values were supposed to be boolean... though in practice I can't think of a situation where you'd want an empty component attribute to equal the empty string (@MartinKolarik unless I'm overlooking something?). At the moment I'm writing `<foo bar='true'/>` which I don't love.

**Comment by MartinKolarik** [comment]
>@MartinKolarik unless I'm overlooking something?

You probably aren't. It's a little counterintuitive that `<widget foo />` and `<widget foo="" />` don't mean the same thing, but I can live with that.
