### ISSUE TITLE
Feature request: Function on data object could return Promise.

### ISSUE THREAD

**Issue by petterek** [ractivejs/ractive#1735]
I belive it would be a nice feature if a ractive identified a promise as the result of a function on the data object, and rendered the data when the Promise is resolved. 

I have tried the promise plugin, but as I understand that only supports the hole data object to be a promise not a function on the object.

**Comment by Rich-Harris** [comment]
This actually works fine - you can use the promise wherever you like in your data object. Here's a (super crude, but functional) example using the [promise-alt adaptor](https://github.com/rstacruz/ractive-promise-alt) - you can even mix and match data types on the same keypath (e.g. `preview` is sometimes a promise, sometimes `null`): http://jsfiddle.net/rich_harris/752ksc1b/

**Comment by petterek** [comment]
hmm Thank you,  then it was just me missunderstanding the concept of promise in the template. 
I will invetigate this futher!
