### ISSUE TITLE
Multiple inline partials broken in edge?

### ISSUE THREAD

**Issue by aphitiel** [ractivejs/ractive#1736]
See this fiddle: http://jsfiddle.net/fsdy5na7/

In egde, the second partial is written to the template, and ractive.partials['partial2'] is an empty array.
Latest works as expected.

Edit: Traced it to commit 624f190787d50a7cd036db0ad758304936fa86ff

**Comment by aphitiel** [comment]
In src/parse/converters/readPartialDefinitionComment.js:
Looks like the var `closed` stayed true after the first partial. Moving the variable definition into function readPartialDefinitionComment *seems* to fix it.

**Comment by martypdx** [comment]
@aphitiel that seems correct to me. Do you want to submit PR with test case and fix?
