### ISSUE TITLE
Tutorial bug(?): Lesson 3 - Expressions - Copying code from left pane and putting into right panel does not execute properly

### ISSUE THREAD

**Issue by tangst** [ractivejs/ractive#1739]
I'm using Chrome 40 on Mac OS X Mavericks.

Steps to Reproduce:
1) Go to http://learn.ractivejs.org/expressions/1/
2) Select the "format(population)" code from the left pane with the mouse.  Paste it into the upper right pane in the appropriate place.
3) Select the "format" property code from the left pane with the mouse.  Paste it into the lower right pane in the appropriate place.
4) Put mouse focus in the lower right pane and hit Shift-Enter.  Code does not execute.  Output pane in the lower left does not update.

However...
When I copy the code with the mouse and paste it into TextWrangler (or some text-only editor), and then copy the code from that editor and paste it into the tutorial panes, the code does execute fine.  I noticed that the code to copy is not just plain text (there are span elements and such inside of it), so I think Chrome is not copying as plain text.  Maybe set up the code with just pre tags or implement a copy to clipboard function in these code snippets?  I'm not sure why this is happening.

**Comment by Madgvox** [comment]
Hmm... I can't reproduce this. Tried it on both FF 35 & Chrome 40 on Yosemite, not sure if the OSX version makes a difference. Copying text ignores most underlying styles*, so that shouldn't affect the output. Can you reproduce it consistently, even after restarting the browser? Does the same behavior occur on another browser?

**Comment by tangst** [comment]
Hello,
Hmm, I attempted to repeat the test after rebooting, and I can no longer reproduce this.  I tried this in Firefox and Chrome and another computer, and I couldn't reproduce this either.  It looks like my browser was unstable for some reason as I did have it open the entire day.

Sorry for the false alarm!
