### ISSUE TITLE
Tutorial Content Typo: Expressions Lesson 3.3 - HTML code snippet user is supposed to copy is not the same as HTML in template pane

### ISSUE THREAD

**Issue by tangst** [ractivejs/ractive#1744]
In the tutorial for Expressions (Lesson 3, Section 3), a user will read the following passage and HTML  code snippet:

"First, we want to show how much we're using of each colour. We'll use <div> elements with a percentage width corresponding to the amount. All the colour values are between 0 and 1, so we need to multiply by 100:

    <td>
    <div style='background-color: red;
       width: {{red*100}}%;'></div>
    </td>
"

The HTML code snippet above that the reader is supposed to copy over to the template pane on the right side has &lt;td&gt;&lt;/td&gt; tags, but the HTML in the template pane does not have these &lt;td&gt; tags and doesn't need them (i.e. Is the user expected to build out &lt;table&gt; and &lt;tr&gt;?).  What makes this situation potentially more confusing for the reader is that when the reader clicks on the "Fix Code" button, the correct code that is inserted into the the template pane doesn't have &lt;td&gt;  tags either.  The &lt;td&gt; tags should be removed from the passage or added to the "Fix Code" logic for consistency.

(Admittedly, this is a relatively minor problem, but I wanted to point this out to shore up the tutorial text for new Ractive.js readers.)

**Comment by Rich-Harris** [comment]
Thanks! I've updated the page http://learn.ractivejs.org/expressions/3/
