### ISSUE TITLE
Component reset() does not reset arrays

### ISSUE THREAD

**Issue by sixfeetover** [ractivejs/ractive#1745]
If you initialize a ractive component with array data, `reset()` will not change array values back to their initial state. In other words:

```javascript
var C = Ractive.extend({
  data: {ary: []}
});
c = new C();
c.push('ary', 5)
c.reset()
c.get('ary') // =>  [5]
```

See the console output from [this fiddle](http://jsfiddle.net/jfraser/jL3o3nn5/) for a slightly more detailed example. Note that other non-array properties DO reset as expected.

I noticed this when attempting to override an instance of a Ractive component in my app, where the new instance inherited the array data value from the previous instance. That behavior is also represented in the fiddle. I then tried to use `reset` as a band-aid, but that didn't work either. For now, I have solved it by setting my data in `oninit` rather than as a property of the component.

I am unclear if this is a bug, the expected behavior for arrays, or simply not the correct usage of `reset`.

**Comment by martypdx** [comment]
I was in the wrapper code yesterday, and I remember a test failed if the wrapper value was not recycled after teardown! I'll need to go back and have a look...

**Comment by Rich-Harris** [comment]
I was going to say that a good solution to this problem is to use a function for the component's `data` property, so that it gets created anew for each instance. There really isn't a good way to reset non-primitive values (i.e. arrays and objects) back to some 'initial' value if you've modified the array itself - one of the reasons [immutable data](https://github.com/facebook/immutable-js) is so appealing.

But it turns out that there's a bug somewhere - I [forked the fiddle](http://jsfiddle.net/rich_harris/d0zscp0r/), replacing the data object with a data function, and it's throwing an error. Marking this accordingly...

**Comment by Rich-Harris** [comment]
I've been looking at the [data configuration code](https://github.com/ractivejs/ractive/blob/dev/src/Ractive/config/custom/data.js) for a while now and I'm ashamed to say I'm struggling to understand it (and hence fix it). It seems we do different things depending on various factors - whether we're extending from a class that has default data, whether that default data is an object or a function, whether it's a POJO, and so on. 

I suppose this is our own fault for nobly trying to make everything Just Work, and I'm wondering how we might bring it under control. The alarming part is I wouldn't be able to explain how data gets inherited other than in non-exotic cases, which suggests either a) it's too complex or b) I'm too simple. Will have a bit of a poke and see what falls out.

**Comment by martypdx** [comment]
@Rich-Harris take a look at #1762 and my comments there if you haven't yet. IMO, things are rather simplified now, with the exception of the model return you mentioned.

**Comment by Rich-Harris** [comment]
@martypdx thanks, I wasn't aware of #1762. It definitely is simpler, though is it confusing that sometimes the child takes precedence and sometimes the parent does? Is there even a use case for *instantiating* with a data function?

There's some code in that module that doesn't appear to do anything - presumably leftover from before - so I'm slimming things down even further over on #1767.

**Comment by martypdx** [comment]
> It definitely is simpler, though is it confusing that sometimes the child takes precedence and sometimes the parent does? Is there even a use case for instantiating with a data function?

Was based on [this test](https://github.com/ractivejs/ractive/blob/dev/test/__tests/misc.js#L620-L654). Not sure when that test was introduced, but possibly recently?

**Comment by Rich-Harris** [comment]
Looks like the history got lost in a refactor! I can't remember the backstory to it

**Comment by sixfeetover** [comment]
Thanks!
