### ISSUE TITLE
Plugins aren't registering

### ISSUE THREAD

**Issue by aethant** [ractivejs/ractive#1750]
Working on a project, and it seems that plugins don't register when your ractive instance is outside of your html file. I had my core logic in ext.js, but keys, hover, etc wouldn't been seen by my code. I'd get the missing plugin message in my console. However, if I put them before my call to pull down core ractive, it gave me the usual warning about that.

Is this expected, or not, or is there a workaround I've yet to be aware of?

**Comment by Madgvox** [comment]
How are you registering the plugins?

**Comment by aethant** [comment]
Simply using <script> tags.

**Comment by martypdx** [comment]
Are plugins being loaded after Ractive?

**Comment by Madgvox** [comment]
Like @martypdx said, make sure your plugins are being loaded _after_ ractive and _before_ your code:

```html
<script src='http://cdn.ractivejs.org/latest/ractive.js'></script>
<!-- Plugins go here! -->
<script src='path/to/your/code.js'></script>
```

**Comment by aethant** [comment]
Of course. This is what I'm doing and they aren't registering.

My initial method was using gulp to concat core ractive, plugins, then my code. Even there, I was specifying order to ensure that ractive, etc was concatenated in the correct order.

**Comment by Madgvox** [comment]
Can you make sure that the plugins are actually running? i.e. that they successfully found the ractive instance and injected the plugin into the ractive object. Try adding a couple of `console.log` statements inside one of the plugins to make sure that they're actually being run.

```js
// ractive-events-hover.js
// ...
console.log( Ractive );
Ractive.events.hover = hover;
console.log( 'successfully attached' ); 
```

**Comment by aethant** [comment]
I've affixed a screenshot of my dev console. I put console.log messages around the line:
``` events = Ractive.events; 

in the ractive-keys plugin code. As you see in the screenshot, it says it can't find the plugin, then the console messages are displayed. If I load them before ractive core, I still get the typical error message. 

It seems there's something up with how it registers the plugin. Any ideas?

**Comment by aethant** [comment]
Hold on.. I realize I left out the Ractive in the console.log, that you suggested. Now, it seems to work. Any idea why this is?

![screen shot 2015-02-24 at 8 19 44 am](https://cloud.githubusercontent.com/assets/47235/6351034/ebce31f6-bbfd-11e4-8887-7acb6ca95fda.png)

**Comment by martypdx** [comment]
From your first screenshot, it's pretty clear the ractive instance in being instantiated _before_ the plugin loads are being called. Whereas in the second screenshot it's not necessarily clear. If including `console.log(Ractive)` fixed your issue, then my guess is somethings up with your module packaging.

**Comment by aethant** [comment]
Hrm, ok. Thanks. I'll need to investigate it some more.

**Comment by Madgvox** [comment]
In my experience, the few times in which a `console.log` has actually 'fixed' an issue was due to the log delaying code execution just slightly, which allowed whatever was missing to resolve. So it seems like there's definitely something wrong with the order of execution in your code, and the slight delay of `console.log` accidentally let the code run in the proper order. So I would definitely investigate to make sure that everything is running in the proper order. If gulp packaged the files improperly it could cause them to run not in the order you specified.

**Comment by Rich-Harris** [comment]
This definitely seems like a Gulp issue rather than a Ractive issue - @aethant is it okay to close this, or is there something we can to help get it fixed?

**Comment by aethant** [comment]
No go ahead and close it. I agree, I think it's a gulp issue. Thank you.
