### ISSUE TITLE
Unshifting an ractive array doesn't seem to work

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive#1751]
I've tried a few different ways to unshift arrays that Ractive data is pointing to, following: http://docs.ractivejs.org/latest/array-modification

However, using unshift() instead of push() results in this error:
```
Error: Attempted to remove a dependant that was no longer registered! This should not happen....
```

Is there an extra step I need to make or consideration when unshifting arrays?

**Comment by martypdx** [comment]
There's an open issue #1737 around unshift. Does that look similar?

**Comment by matthew-dean** [comment]
Hmm, could be. I tried both ractive.unshift() and using the unshift() method on the array in the data object. Either one produces the same result.

I'm using v0.6.1 by the way. The funny thing is that I seem to recall using unshift() on a ractive a while ago in this project, but it's likely that I updated Ractive since then.

**Comment by matthew-dean** [comment]
I'm also finding that shift() has the same problem. So any modification to the beginning of the array seems to be an issue. Since I'm trying to do a kind of "queue" list, I'm not sure now how to go about this. Just setting a root path with a new dataset?

**Comment by matthew-dean** [comment]
I was able to work around this with this brutal hack.

```js
// in custom create() function
var ractive = new Ractive({
	el: document.getElementById('messageBar')
	, template: template
	, data: { 
		messages: []
	}
});
// in add() function
this.messages.unshift(mObj);
if(this.messages.length > 3) {
	this.messages.pop();
}
this.ractive.set('messages', this.messages.slice());
```
It's hacktastic, but it works.

**Comment by martypdx** [comment]
Have you tried `merge`?:

```js
var copy = this.ractive.get('messages').slice();
copy.unshift(mObj);
this.ractive.merge('messages', copy);
```

**Comment by matthew-dean** [comment]
That seems like it could work, but only if you use the compare option, which has to JSON stringify all the objects and compare all strings. This doesn't seem ideal.

**Comment by martypdx** [comment]
With something like `mObj` isn't object reference equality sufficient?

**Comment by Rich-Harris** [comment]
@matthew-dean we've just fixed a couple of bugs related to this, could you see if your issue is fixed with http://cdn.ractivejs.org/edge/ractive.js please? Thanks

**Comment by evs-chris** [comment]
Please feel free to re-open if this is still an issue.
