### ISSUE TITLE
Setting value on ractive.observe doesn't update subcomponents

### ISSUE THREAD

**Issue by blackgate** [ractivejs/ractive#1752]
http://jsfiddle.net/br2m8muq/1/

If you try to change the first field in the jsfiddle, the others should be updated, however the one in the sub component "test-subcomp" isn't.

I also noted that if you add { defer: true } to the observer, it updates the subcomponent, but it doen't update the "test-comp" component.

**Comment by blackgate** [comment]
The workarround for now is wrapping the code with an setTimeout.

**Comment by dagnelies** [comment]
Apparently, this was fixed in "edge"
http://jsfiddle.net/br2m8muq/4/

**Comment by blackgate** [comment]
Ok, thank you.
Is there any way to use RactiveLoad with the edge version?

**Comment by dagnelies** [comment]
Simply use:
http://cdn.ractivejs.org/edge/ractive.js
instead of
http://cdn.ractivejs.org/latest/ractive.js

**Comment by blackgate** [comment]
I already tried that, but it doesn't work because of the "Mismatched template version" error:
http://plnkr.co/edit/c4VIfiGvaBElFqxfeBUH?p=preview

**Comment by martypdx** [comment]
@blackgate Monkey patch the template version check to right version (or delete out the check altogether)

**Comment by blackgate** [comment]
Ok, it worked, thank you. :+1:
