### ISSUE TITLE
Separating view data from functions, or a way to support "filters" on a ractive instance

### ISSUE THREAD

**Issue by fardog** [ractivejs/ractive#1753]
This is definitely a feature request, as I believe the way Ractive currently works is correct, but having functions and data share the same namespace is problematic, especially when using `instance.reset`. For example:

A Ractive instance (just as a very simple example):

```javascript
var instance = new Ractive({
  el: '#container',
  template: someTemplate,
  data: {
    percent: function(num, divisor) { return (num / divisor).toFixed(1) }
  }
})
```

Performing an `instance.reset({//some data})` will remove the `percent` function from the Ractive instance.

To understand why this model is important to us:

We have potentially many global filters in place for designers that work on our templates; these filters might format data, generate URLs, etc. However, we use Ractive as a view layer only; state is maintained elsewhere (not unlike [Facebook's Flux Architecture](https://facebook.github.io/flux/)) and we reset the Ractive views when state is updates.

Regardless of our workflow though, having data and functions share the same scope often adds to oddities, or having to "namespace" data. For example, if I had an object that I just needed to iterate through, it's natural to just set it in the root scope:

```javascript
var data = { "one": "One", "two": "Two" }
var instance = new Ractive({el: '#el', template: '#template', data: data})
```

And then iterate through it in my template:

```html
<ul>
{{#this:key}}
  <li>{{key}}: {{value}}</li>
{{/this}}
</ul>
```

However, if I had any default data, which would get merged in, suddenly iterating this way would be broken:

```javascript
Ractive.defaults.data = {something: function(val) { // something }}
```

In a larger system, using these defaults to provide global "filters" feels like the natural option, but is often rendered awkward by sharing the same namespace as data.

For what it's worth, we've worked around it by using a namespace for our filters, and then never using the root `data` object for anything aside from simple flags (such as `loading: false` or `noData: true`) and then namespacing everything else into objects that are children of data.

So I wanted to open this issue to discuss if there were any plans for separating functions/data, or if doing so is a sensible option.

My preference would be for a new property when instantiating Ractive, as such:

```javascript
var instance = new Ractive({
  filters: {
    percent: function() { // some function }
  },
  data: {
    //some data
  }
})
```

Similarly, `Ractive.defaults.filters` would be available, working in the same manner as `Ractive.defaults.data`, where any new instance would get these filters, so long as they didn't also define filters with the same name.

Let me know what you think about this proposal, and thanks for taking the time to read this wall of text!

**Comment by jarofghosts** [comment]
Similarly, a way to separate static context from dynamic would be great, and would actually solve the problem also.

Using `.set()` as a workaround here isn't exactly tenable either. For one we tend to prefer always dumping context as a whole into our view, but beyond that it becomes messy to manage such things, and again leads to namespacing the data which really only punts the mess into the template.

**Comment by martypdx** [comment]
> For what it's worth, we've worked around it by using a namespace for our filters, and then never using the root data object for anything aside from simple flags (such as loading: false or noData: true) and then namespacing everything else into objects that are children of data.

I don't think that's so much of a work around as how the system is currently designed. I tend to think of `data` as a registry of data objects of interest, much like components or any other plugin. The keys example becomes trivial from this perspective:

```js
Ractive.prototype.data = {
    something: function(val) {}
};

var items = { "one": "One", "two": "Two" };
var instance = new Ractive({
    el: document.body, 
    template: '#template', 
    data: {
       items: items
    }
});
```

Is it a conceptual gap or does this lead to other issues with the approach you want to take?

**Comment by martypdx** [comment]
@jarofghosts an example would be helpful :)

**Comment by jarofghosts** [comment]
```js
new Ractive({
  data: {somethingStatic: 'wee', somethingElseStatic: 4, state: {}}
})
```

then we use state as the dynamic bits. this means in the template we have

```html
{{#state}}
  ... template goes here ...
{{/state}}
```

and then we just abuse Ractive's context resolution to refer to global things in an outer scope.

it "works", but it ends up being pretty gross as you make more and more templates.

**Comment by martypdx** [comment]
@fardog Is it that you want the first key rollup behavior across two levels? The example I gave would leave all top-level keys to compete with one another, and you want to be specific about "filters" (or presumably some other arbitrary key - I wouldn't want to add DSL properties to core Ractive)?

```js
Ractive.prototype.data = {
    filters: {
        one: function(){},
        two: function(){}
    },
    fitzers: {
        blue: 'onion',
    }
};

var items = { "one": "One", "two": "Two" };
var instance = new Ractive({
    el: document.body, 
    template: '#template', 
    data: {
       items: items,
       filters: {
           one: function(){}, //redefined
           three: function(){}
       },
       fitzers: { red: 'carrot' }
    },
   'somehow-know-these-keys-are-special': [ 'filters', 'fitzers' ]
});
```

**Comment by fardog** [comment]
@martypdx That tends to be the issue; we end up having to create "reserved" namespaces that anyone working on the codebases need to remain aware of. Like "don't use the key `filters` or you'll overwrite the global filters".  Similarly, when dealing with partials, and passing context to those, if we're passing specific context to the partials via `{{>partialname { somdata: somethingElse } }}` this can get especially confusing.

**Comment by martypdx** [comment]
@jarofghosts I'm still not tracking 100% here. Part of the trouble is that `state` is recently (per ReactJS) used to refer to application state versus properties which refers to the data. So I think you're example may be inverted to that convention. 

Is the "static" part meaningful here? Or is it really the above the distinction?

There's been some discussion about introducing some form of division of state versus data. Literally in the options and by the use of `@` in the template:

```js
new Ractive({
  state: { editMode: true, somethingelse: 4 }
  data: { foo: { bar: 'qux' } }
})
```

Now it's cognitively clear in the template which is which:

```html
{{#foo}}
  <span contenteditable='{{@editMode}}'>{{bar}}</span>
{{/foo}}
```

I don't know if that's at all what you meant, let me know.

@fardog That would give you two separate buckets, but would you still need the rollup in the state bucket?

**Comment by jarofghosts** [comment]
@martypdx apologies for the confusion, but exactly what you have outlined there would work perfectly for me.

**Comment by jarofghosts** [comment]
is that discussion anywhere public? or is there some way that I can show support for it otherwise?

**Comment by martypdx** [comment]
@jarofghosts awhile back discussion at bottom of #570, but more recently I'm working on #1740 (serious WIP) that as a side effect would make it easy to add synthetic parts to to the model.

**Comment by fardog** [comment]
@martypdx I suppose my thought would be that state is maintained across partials, as well as when it's extended from `Ractive.default`, however I think the current behavior as you mentioned above is correct. A copy/paste:

```
Ractive.prototype.data = {
    filters: {
        one: function(){},
        two: function(){}
    },
    fitzers: {
        blue: 'onion',
    }
};

var items = { "one": "One", "two": "Two" };
var instance = new Ractive({
    el: document.body, 
    template: '#template', 
    data: {
       items: items,
       filters: {
           one: function(){}, //redefined
           three: function(){}
       },
       fitzers: { red: 'carrot' }
    },
   'somehow-know-these-keys-are-special': [ 'filters', 'fitzers' ]
});
```

The filter `one` being redefined is the correct behavior here. But in the example you gave @jarofghosts above, I would likely prefer to define our global filters on the state object (accessible as `{{@filters.somefilter()}}``; again preferring that this state follow into partials (so in a partial, no matter what its context was passed as, it would still have `@filters.somefilter()` available.

**Comment by Rich-Harris** [comment]
Just want to add #1612 to the list of relevant issues - it was closed, but I think it raises an important point about private state within a component, which is another part of this whole props/state/filters/helpers/whatever discussion.

For me the overriding concern is that a state/props/helpers distinction *shouldn't get in the way* - it should exist as an advanced feature for people who need it and know what to do with it. Understanding the distinction is one of the things people find hardest about learning React, for example, and it seems clear that you can actually build fairly sophisticated apps without ever actually *needing* that distinction.

@martypdx I'm looking forward to seeing what you cook up on #1740

**Comment by evs-chris** [comment]
There are a couple of additional ways to approach moving helpers out now, with `@global` and `@this.root`, so I'm going to close this. If we need to further address private state, I think it would be more appropriate in a new (or other existing) issue.
