### ISSUE TITLE
'Animation was not found'

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1755]
Via [this SO question](http://stackoverflow.com/questions/28769383/ractive-js-animation-was-not-found), I've realised that the 'Animation was not found' message (which was added for reasons that are lost in the mists of time) might cause developers to think they're doing something wrong, when (as far as I can tell) it's completely harmless. Should try and get to the bottom of a) exactly what causes it, and b) if there's anything that needs to happen as a result.

**Comment by TehShrike** [comment]
I ran into this when animating a timer, calling `animate` with a 1000ms transition inside of a `setInterval(fn, 1000)`.

I should be doing it a bit less dumb of a way anyway, but still, I'm not sure how much I should worry about this.

**Comment by evs-chris** [comment]
That string no longer exist in the code, so I'mma call this one resolved.
