### ISSUE TITLE
All objects and arrays in data: are copied to next component instance

### ISSUE THREAD

**Issue by vujovicigor** [ractivejs/ractive#1759]
All objects and arrays in data: are copied to next component instance,
even if you distroy data object onteardown
https://jsfiddle.net/wdhfhv7o/

Thanks for great work.

**Comment by evs-chris** [comment]
They're not copied, per se. They just live in the component and not on each instance, so they're shared. If you want instance specific data, you can use a data function:

```js
var shared = { foo: 1 };
var cmp = Ractive.extend({
  data: function() {
    return { fresh: true, arr: [], shared: shared };
  }
});

var inst = new cmp(); // will get a fresh new data object

inst.get('shared.foo'); // 1
inst.add('shared.foo'); // +1
inst.set('fresh', false);

var inst2 = new cmp();
inst2.get('shared.foo'); // 2
inst2.get('fresh'); // true
```

**Comment by martypdx** [comment]
see also http://docs.ractivejs.org/latest/advanced-configuration#copying-parent-data

**Comment by vujovicigor** [comment]
I see, thanks.
But if I use data function, initial data from parent wont work (<component param="{parentparam}}"/>)
http://jsfiddle.net/1t9eqqsr/

**Comment by martypdx** [comment]
@vujovicigor The syntax is latest is somewhat different than edge. You have to pass the data object through using `this._super`. see http://jsfiddle.net/mq6a87jf/.

Edge as the more intuitive syntax of rolling up the return value of data functions.

**Comment by Rich-Harris** [comment]
Is it okay to close this issue? Looks like ( data functions + edge ) = correct behaviour

**Comment by vujovicigor** [comment]
Not sure, 
last example not working in edge
and in latest version it return bad result in html output:

same var {{name}} have different value in
<cmp url="{{name}}" ></cmp> <input value="{{name}}"

**Comment by martypdx** [comment]
@vujovicigor the last fiddle you posted was using latest, not edge. updated to edge and it seems to be working: http://jsfiddle.net/1t9eqqsr/1/.  Could have missed something though, please clarify...

**Comment by vujovicigor** [comment]
Now is ok, 
 http://jsfiddle.net/mq6a87jf/ egde was throwing
TypeError: this._super is not a function
at line 35 ( this._super(data); ) 

Thank you
