### ISSUE TITLE
Resetting back to a predefined 'state'

### ISSUE THREAD

**Issue by aethant** [ractivejs/ractive#1760]
Hi, I'm continuing this from SO (http://stackoverflow.com/questions/28769383/ractive-js-animation-was-not-found) per @Rich-Harris suggestion.

Right now, I have a Ractive-based form that has a default 'state', which changes based on user input (if x, then this, etc.) When the user backs out programmatically, I'm using ractive.reset() to reset the data on the Ractive instance. However, as I currently understand it, I can set things for data to be reset to (for instance: .reset({foo:"bar"}) ). 

Is there a way for me to define a preset "default" state for data and revert to it. If not, is this something that would be feasible to add into Ractive? Or am I missing an obvious way to do this?

**Comment by LiorCohen** [comment]
You can deep-clone the state of `this.data` and store it in the instance:

    var foo = new Ractive({
        onconfig: function() {
            this._initialData = this.data;
        },
        restoreInitialData: function() {
            this.reset(this._initialData);
        },
        data: {...}
    });

    foo.restoreInitialData();

I haven't tested this code, but you should be able to get the general idea. You can change `onconfig` to `oninit` or another lifecycle event to better suit your needs.

**Comment by martypdx** [comment]
fyi in edge, form resets restore to inital state automatically: http://jsfiddle.net/u37pv0gb/

If your default data is coded in your component, you can also put it in a data function which will be called on reset:

```js
var View = Ractive.extend({
    data: function(){
        return {
            foo: 'foo',
            bar: 'bar'
        };
    }
})
var r = new View({
    el: document.body,
    template: '#template',
    data: {
        other: 'other'
    }
})

r.set('foo', 'changed')
r.set('bar', 'also changed')
r.reset({ other: 'something' });
```

However, the roll-up inheritance in edge appears to be broken for this use case :(  

It works in latest, but the syntax is somewhat different (see http://jsfiddle.net/usLkqgtm/):

```js
var View = Ractive.extend({
    data: function(d){
        d.foo = 'foo';
        d.bar = 'bar';
    }
})
var r = new View({
    el: document.body,
    template: '#template',
    data: {
        other: 'other'
    }
})

r.set('foo', 'changed')
r.set('bar', 'also changed')

r.reset({ other: 'whatever' });
```

**Comment by aethant** [comment]
Awesome. I'm at a conference right now, but I'm going to look into this deeper in a few days. Thanks much!

**Comment by martypdx** [comment]
@aethant, can you let us know if this is resolved for you?

**Comment by aethant** [comment]
Sorry for the delay... was getting something out the door. Yes, it seems to work for me. If issues arise, I'll report back. Thanks very much!
