### ISSUE TITLE
unregister: Cannot read property 'firstKey' of undefined

### ISSUE THREAD

**Issue by timoxley** [ractivejs/ractive#1768]
Using edge at time of writing 8be2caf.

I have not been able to create a minimal reproducible case for this, hence this bug report is a little vacuous, but I seem to be hitting errors when conditional components are added or removed from the tree.

My template has conditional display of some components based on the value of some radio inputs.

When toggling this value, Ractive gives me the following error:

```
 Uncaught TypeError: Cannot read property 'firstKey' of undefined
```

This is coming from the `if (mapping = this.mappings[keypath.firstKey]) {` line of:

```js
function Viewmodel$unregister(keypath, dependant) {
  	var group = arguments[2] === undefined ? "default" : arguments[2];

  	var mapping, deps, index;

  	if (dependant.isStatic) {
  		return;
  	}

  	if (mapping = this.mappings[keypath.firstKey]) {
  		return mapping.unregister(keypath, dependant, group);
  	}
…
```

The `keypath` is indeed undefined.

Following the stack trace, I see keypath is passed into unregister in `this.origin.unregister(this.map(keypath), dependant, group);` of:

```js
  	unregister: function (keypath, dependant, group) {
  		var deps = this.deps,
  		    i = deps.length;

  		while (i--) {
  			if (deps[i].dep === dependant) {
  				deps.splice(i, 1);
  				break;
  			}
  		}
  		this.origin.unregister(this.map(keypath), dependant, group);
  	}
```

In this scope, `keypath` is fine but `this.map(keypath)` produces `undefined`.

Please let me know what more information you need to debug this short of something reproducible as I can't seem to get it to break easily.

**Comment by martypdx** [comment]
Thanks for the sleuthing, I was able to repro in a test via: 

```js
var ractive = new Ractive({
	el: fixture,
	template: `<outer/>`,
	components: {
		outer: Ractive.extend({ template: `{{#show}}<inner foo="{{unresolved}}"/>{{/}}` }),
		inner: Ractive.extend({ template: `{{foo}}` })
	},
	data: {
		show: true
	}
});

ractive.set('show', false);
```

Then pretty easy fix to guard against unregistering unresolved mappings on components.
