### ISSUE TITLE
ractive.observe() options.init argument isn't working as designed

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#1769]
Hello! I use ractive.observe like this:

```javascript
ractive.observe('focus', function( newValue, oldValue, keypath ) {
   alert(oldValue);
}, {
  init: false, 
  defer: true
});
```

So, I expect that alert will never be fired if oldValue is undefined, but it's not true. Seems, it's can be a bug.

**Comment by evs-chris** [comment]
The init option only keeps the observer from firing until the first change. If the given keypath has no value and you assign it one after the observer is set up, it will be fired with the new value (as it *has* changed) and the old value of `undefined`. If that's not what you're expecting, can you put together a little more complete example? Maybe a [fiddle](http://jsfiddle.net)?

**Comment by PaulMaly** [comment]
Hm, but If the given keypath doesn't exist before? For example, I set variable in first time in oninit callback like this: this.set('focus', 0); and I expect that in this moment I'm not changing anything, so I believe, that observer won't firing, isn't it?

**Comment by martypdx** [comment]
@PaulMaly in your case, `0 !== undefined` so it counts as a change. You can put a guard in the observer:

```js
ractive.observe('focus', function( newValue, oldValue, keypath ) {
   if( typeof oldValue === 'undefined' ) { return; }
   alert(oldValue);
}, {
  init: false, 
  defer: true
});
```

Or, depending on your setup,  you could move your default value to an option that happens before the `oninit` (or just move your `set` before `init` if in same component:

```js
// logic-less
data: {
    focus: 0
}
// with logic, assuming this is a component:
data function() {
    if ( this.get('foo') ) {
        this.set('focus' 0);
    }
}
// with logic as part of onconfig:
onconfig: function() {
    if ( this.get('foo') ) {
        this.set('focus' 0);
    }
}
```

This has come up a few times now where people want to filter out `null` and `undefined` from observers. It needs some thought and discussion. I'll mark as enhancement, but it probably won't be till `0.8` or `0.9` - we're trying to get `0.7` out the door now :)

**Comment by PaulMaly** [comment]
Actually, now I missunderstand purpose of options.init argument. Really. I see only two cases I want to observe variable:
1) I want to know everything, when this variable first time appeared in my instance and when it's changed.
2) I want to know only difference beetween old and new value.

So, for me options.init=false handle second case and I'm a little bit upset that it don't. However, if it currently work as designed, so feel free to close this issue. Thanks for the answers and good luck!
