### ISSUE TITLE
Ractive Tutorial Lesson 10-2 Partials: Javascript error appears when deleting a line as instructed by tutorial

### ISSUE THREAD

**Issue by tangst** [ractivejs/ractive#1771]
In Lesson 10-2: Partials, the last line of the instructions state: "Add the partial to the template, and remove it (and the var item = ... bit) from the javascript code."

I go to the JavaScript panel and remove these lines from it, as per the instructions.

    var item = "<li class='{{ done ? \"done\" : \"pending\" }}'>" +
             "<input type='checkbox' checked='{{done}}'>" +
             "<span on-tap='edit'>" +
               "{{description}}" +

               "{{#if editing}}" +
                 "<input class='edit' " +
                        "value='{{description}}' " +
                        "on-blur='stop_editing'>" +
               "{{/if}}" +
             "</span>" +
             "<a class='button' on-tap='remove'>x</a>" +
           "</li>";

However, right after I delete the lines, the JavaScript panel highlights an error and prevents the panel from executing (i.e. I cannot do Shift + Enter).  Attached is a screenshot.  This error appears in both Firefox 36 and Chrome 41.0.22 on my Mac.  

After a little more messing around, the error triggers if I delete even one whitespace character from anywhere in the JavaScript panel.  It doesn't have to be the "var item" line. 

![screenshot](https://cloud.githubusercontent.com/assets/3941845/6508045/38edcdca-c324-11e4-9baa-404078b69504.png)

**Comment by martypdx** [comment]
Apparently that bit of code is just too clever for CodeMirror, and thus probably also too clever for a tutorial :)

Will change to:

```js
if( which === 13 ) { 
    fire({ node: node, original: event }); 
}
```

**Comment by martypdx** [comment]
fixed via https://github.com/ractivejs/learn.ractivejs.org/commit/4782e6400930835ac1cc6ecac33930253df24037 and
https://github.com/ractivejs/learn.ractivejs.org/commit/b388a9aa0bbba5f16b0914fba8f3d91038f5a729

**Comment by tangst** [comment]
Thanks!
