### ISSUE TITLE
A single space between two mustache sections is not rendered

### ISSUE THREAD

**Issue by mikemaccana** [ractivejs/ractive#1772]
This one's a little obscure, but came to light when using display table which has different whitespace handling than blocks or inline. [JSFiddle here](http://jsfiddle.net/ya4c07ue/2/). Eg:

    {{ firstName }} {{ lastName }}

outputs:

`"Joe"`, `"Blogs"` when seen by the inspector. It should output `"Joe"`,`" "`,`"Blogs"`

Adding a character outputs properly, eg:

    {{ firstName }} x{{ lastName }}

`"Joe"`, `" x"`, `"Blogs"` when seen by the inspector.

**Comment by martypdx** [comment]
I think you're fighting `display: table` here. Checkout this fiddle: http://jsfiddle.net/xnbqxxt1/.

All three nodes are there, same result as if I roll it by hand. Can you put the content into `display: table-cell`?

**Comment by mikemaccana** [comment]
You're right - sorry for wasting your time!
