### ISSUE TITLE
sourcemaps not loading

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1777]
I end up getting this a lot:

```





// Please wait a bit.
// Compiled script is not shown while source map is being loaded!
```

Also, breakpoints seems to come and go. Often I have to set the breakpoint in the [test].js, then go (re)set the breakpoint after bringing the module back up. Assuming I'm not getting the above non-source map.

**Comment by martypdx** [comment]
Ah, it seems to be related to LiveReload getting turned off.

**Comment by martypdx** [comment]
I'm not sure what's going on. Live Reload turns off initially (waiting for sourcemap?) and after test execution is back on. Turning off setting `sourceMap: false` in `gobblefile` doesn't work either :(

**Comment by evs-chris** [comment]
I noticed that there were a bunch of files missing on the source-mapped side a few days ago too. I haven't had enough spare time to check it out yet, but Firefox gives you the option to disable sourcemaps whilst debugging, which makes things a little less painful when they get mangled. It also has a pretty decent search facility built in for navigating about in the giant combined scripts (searches starting with a bang '!' will give you a jump list). Breakpoints seem much less ethereal too. You can set them in the sourcemapped source and they don't all disappear on reload. Chrome has a bad habit of only actually hitting the first breakpoint in the list when sourcemaps are involved.

I've also noticed that Firefox breaks waaay less violently if something goes wrong in a testcase. I've had Chrome completely lock up while running the test suite, but Firefox soldiers on and at least gives the option to kill the script without having to drop back to killing the process at the OS level. If only the debugger wasn't painfully slow.

**Comment by Rich-Harris** [comment]
Weird, I've never encountered an error like that. In any case it *might* have been fixed now (see https://github.com/ractivejs/ractive/issues/1774#issuecomment-78574455) - can you update gobble to 0.7.8 and see if this is still happening please?

**Comment by martypdx** [comment]
Okay, I did a big merge with latest, wiped out `node_modules

**Comment by martypdx** [comment]
Okay, I did a big merge with latest, wiped out `node_modules`, and a fresh `npm install` and everything is working great.

Along the way, I discovered chrome's blackboxing feature which is just awesome if you don't know about it:

![image](https://cloud.githubusercontent.com/assets/478864/6700534/9dd55c60-cccc-11e4-80bb-ab8b5ba45fd2.png)

Now I can use pause on exceptions without having to toggle it all the time.
