### ISSUE TITLE
Ractive Backbone Adaptor Example: Bad links to Backbone adaptor and wiki

### ISSUE THREAD

**Issue by tangst** [ractivejs/ractive#1782]
On this page: http://examples.ractivejs.org/backbone, two links are bad.

The link "Backbone adaptor" in this paragraph leads to a 404:

     In these situations, we use adaptors. Adaptors are small plugins that allow Ractive to communicate
     seamlessly with third-party model libraries. In the example above, we're using the Backbone adaptor.

The link "wiki" at the bottom of the page goes to a "create new page."  It doesn't look like the wiki is at that URL anymore.

    You'll find more information about adaptors, including how to create your own, on the wiki.

**Comment by Rich-Harris** [comment]
Thanks for spotting this - I've opened https://github.com/ractivejs/examples.ractivejs.org/issues/4, so I'll close this issue
