### ISSUE TITLE
ES6 destructuring & ractive.data

### ISSUE THREAD

**Issue by timoxley** [ractivejs/ractive#1783]
Now that ractive.data is deprecated, this a step backward for ractive ES6 friendliness, as one can no longer use destructuring to read and write data to the ractive instance. 

It also seems it's not possible to generate an object that can be destructured… I had high hopes for `ractive.get('')` but it seems to entirely ignore data passed in as properties on components:

```js
import Ractive from 'ractive'

const child = Ractive.extend({
  template: '<h1>{{name}}</h1>{{#items}}{{.}}<br />{{/items}}',
  data: {
    items: [1,2,3]
  },
  oncomplete: function() {
    let getName = this.get('name')
    let {name, items} = this.get('')
    console.log('name:', name)
    console.log('getName:', getName)
    console.log('items:', items)
    // Output:
    // name: undefined
    // getName: test
    // items: [1, 2, 3, _ractive: Object]
  }
})

new Ractive({
  el: document.body,
  template: '<child name="{{name}}"></child>',
  components: {child},
  data: {
    name: 'test'
  }
})
```

![image](https://cloud.githubusercontent.com/assets/43438/6573724/aab425f2-c758-11e4-986d-45a03f649e5c.png)

**Comment by Rich-Harris** [comment]
I can't find the issue right now, but the plan is to include mappings (which includes non-static component attributes like `name='{{name}}`) and computations in `this.get()` (or `this.get('')`, so this *would* work:

```js
let { name, items } = this.get();
```

You can still use destructuring to write data:

```js
this.set({ name, items });
```

**Comment by martypdx** [comment]
I've got a start for this on #1785. There are a couple of questions that need to be resolved:

* Should a root get from the template also be inclusive of computations and mappings? My incliniation is yes:

```html
{{JSON.stringify(.)}}
```

* Should non-computed property computations (expressions) be included? They are in the `computations` hash, but is that cool or confusing? (Leaning towards later):

```js
{
  "${JSON-stringify()}": "{\"foo\":\"foo\"}",
  "bar": "foobar",
  "foo": "foo"
}
```

**Comment by timoxley** [comment]
> Should a root get from the template also be inclusive of computations and mappings? 

Vanilla data is easiest to rationalise. Including "rendered" computations means you need to be aware of any dependencies in the computation, e.g. consider this computation:

```js
new Ractive({
  data: {
    users: [new ValidUser('alice'), new InvalidUser('bob')]
  },
  computed: {
    validUsers(): {
      return this.get('users').filter(isValidUser)
    }
  },
  oninit() {
    let { users, validUsers } = this.get();
    this.push('users', new ValidUser('kim'))
    console.log(validUsers.length) // 1
  }
}
```

Different story if computations are included as getters or functions.

> Should non-computed property computations (expressions) be included? 

No, seems like implementation detail and very tight coupling in the wrong direction.

**Comment by martypdx** [comment]
@timoxley good points. Why don't we start with just mappings for `0.7` and see where things go from there.

**Comment by Rich-Harris** [comment]
> Why don't we start with just mappings

:+1:

**Comment by timoxley** [comment]
Oh, hang on, where does data that's passed in via attributes end up?

**Comment by martypdx** [comment]
Those are the "mappings". We discovered a couple of issues we need to work through, see #1785.
