### ISSUE TITLE
Allow subsets of templates to be used as templates

### ISSUE THREAD

**Issue by Crisfole** [ractivejs/ractive#1786]
I'd like to use a node's content partial as a template in a decorator.  Here's [a gist with a good use-case](https://gist.github.com/Crisfole/19a5ea343fd152f2ba4e) for that in particular.

Right now, when I try to render a `tooltip` (from the above gist) I get two errors:

```
ractive.js:4501: Uncaught Error: Mismatched template version! Please ensure you are using the latest version of Ractive.js in your build process as well as in your app
```

and

```
ractive.js:9820: Uncaught TypeError: Cannot read property 'teardown' of undefined
```

I don't think I'm doing anything crazy; it seems like something that should be doable...

**Comment by martypdx** [comment]
The content partial is probably not fully formed to the [template spec](https://github.com/ractivejs/template-spec), or it's because you're using just the first element of the array, `template: r.partials.content[0]`. Try wrapping it like:

```js
{
  v: 2, /* Template spec version */
  t: r.partials.content
}
```

**Comment by Crisfole** [comment]
I tried using `r.partials.content` and it didn't work either.

I never tried manually setting the template version...doesn't seem like something I'd expect to have to do, I'll give it a whirl.

**Comment by martypdx** [comment]
@Crisfole [This] seems to work. 

Flagging as an enhancement to see we could either eliminate the need for the version in that case, or provide the version so it could be passed in rather than hard coded.

**Comment by evs-chris** [comment]
You can use fragment arrays from within templates with partials, so I'm going to go with "close enough" on this.
