### ISSUE TITLE
Mustache Template Inheritance

### ISSUE THREAD

**Issue by Aintaer** [ractivejs/ractive#1791]
Is the Mustache template inheritance syntax supported?
This is currently in discussion as a draft spec addition in https://github.com/mustache/spec/pull/75

There are conforming implementations in mustache.php, hogan, mustache.js and mustache.java so far and it seems like it would be a great addition for Ractive.

For example:

```
{{! base.mustache }}
<html>
  <body>{{$content}}Default content{{/content}}</body>
</html>
```

```
{{! page.mustache }}
{{< base }}
  {{$content}}My page{{/content}}
{{/ base }}
```

Rendering `page.mustache` with `base.mustache` as a partial would result in:

```
<html>
  <body>My page</body>
</html>
```

**Comment by martypdx** [comment]
We already have this with component `{{yield}}` and `{{>content}}`, so not sure what doing it at the mustache level would bring beyond spec conformity.

**Comment by Aintaer** [comment]
Spec conformity would be the goal, I think. What it would allow for us is to use the same mustache template in multiple contexts.

**Comment by Rich-Harris** [comment]
Thanks for linking to that thread @Aintaer, I had no idea about that discussion. As a general rule I think being backwards compatible with Mustache is a good thing, though I have to confess I'm a bit confused by the syntax they've chosen. It just seems totally bewildering to have `{{$thing}}` mean something totally different from one context to the next (especially seeing as `$thing` is a valid reference in its own right).

So while I do like the idea of spec conformity, I think it's worth being sure that this part of the spec is something that makes sense, given that as @martypdx says we can already do it (because we have components): http://jsfiddle.net/rich_harris/1cajfguo/

## Mustache (as per the proposed spec)

```html
{{! header.mustache }}
<head>
  <title>{{$title}}Default title{{/title}}</title>
</head>
```

```html
{{! base.mustache }}
<html>
  {{$header}}{{/header}}
  {{$content}}{{/content}}
</html>
```

```html
{{! mypage.mustache }}
{{<base}}
  {{$header}}
    {{<header}}
      {{$title}}My page title{{/title}}
    {{/header}}
  {{/header}}

  {{$content}}
    <h1>Hello world</h1>
  {{/content}}
{{/base}}
```

## Ractive

```html
{{! headerPartial}}
<head>
  <title>{{title || 'Default title'}}</title>
</head>
```

```html
{{! layout component template}}
<html>
  {{yield header}}
  {{yield content}}
</html>
```

```html
{{! main template }}
<Layout>
  {{#partial header}}
    {{>headerPartial { title: 'My page title' } }}
  {{/partial}}

  {{#partial content}}
    <h1>Hello world</h1>
  {{/partial}}
</Layout>
```

**Comment by Aintaer** [comment]
Right, I know Ractive can do it using special syntax a la `yield`, but our team relies on the disparate groups using various mustache renderers to cooperate using a single spec-standard syntax.

For now we are simply using variant partials to fulfill the same need, as that's supported across our teams. It would be fantastic to see the same syntax behave the same way no matter where we choose to render the template. :smile:

**Comment by martypdx** [comment]
It looks like it could be (mostly) solved as purely a parsing issue. Given that it doesn't seem like a done deal, it probably will sit a bit in terms of priority.

@Rich-Harris: Apart from implementing it, might give us logical reason to incorporate some of those other syntax delineators re #1748. Though why three separate things: `{{! this }}`, `{{$this}}`, and `{{<this}}{{/this}}` hasn't hit home with me yet.

**Comment by Aintaer** [comment]
@martypdx `{{! this }}` is just a mustache comment. `{{< this }}` As far as I understand, is like a "reverse partial", inside of which, `{{$ this }}` refers to a block to replace inside the reverse partial.

**Comment by martypdx** [comment]
> {{! this }} is just a mustache comment

@Aintaer ah right, I knew that now that you mention it.

**Comment by evs-chris** [comment]
It looks like the spec is still not complete, and it's nearly two years later, so I'm gonna close this for now.
