### ISSUE TITLE
AppVeyor === broken windows

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1807]
Can we remove AppVeyor from the github build until it builds successfully?

**Comment by Rich-Harris** [comment]
agree, it's annoying - I've commented out `npm run build` from `appveyor.yml` rather than removing the integration or (gasp!) actually fixing it, so that it's easier to reinstate when we eventually get round to it

**Comment by evs-chris** [comment]
I looked into this originally and was unable to reproduce it. I tried again just now and the first time I ran it, I got the same errors that appveyor does. Then the second run finished fine. I have now tried deleting all of the gobble/tmp/build folders and node modules and reinstalling and nothing seems to make it fail again.

So, I'm going to go with Windows === broken.

I'll try running the build twice in appveyor to see if it's magically ok the second time 'round there too.
