### ISSUE TITLE
Better error for partials

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1808]
Partials try and unrender when they don't exist, and can throw unhelpful `Uncaught TypeError: Cannot read property 'detach' of null` instead of warning that partial does not exist:

```js
var items = [];

var ractive = new Ractive({
    template: '{{#items}}{{>item}}{{/}}',
    el: 'main',
    data: {
        items: items
    }
});

items.unshift(1);
```

see http://jsfiddle.net/eku2p06y/4/

**Comment by Rich-Harris** [comment]
I reckon it's okay not to print an additional warning beyond the 'could not find template for "items"' one we've already got - better to just let this work as expected and not error. Fixed in #1808
