### ISSUE TITLE
What's wrong with several zeros? Parser error.

### ISSUE THREAD

**Issue by anton-ryzhov** [ractivejs/ractive#1819]
Simple minor bug, parser breaks on pretty inoffensive `00` literal.

http://jsfiddle.net/wnb470qp/
```js
new Ractive({
    el: 'body',
    template: '{{ true ? 11 : 00 }}',
});
```

```js
Uncaught ParseError: Expected closing delimiter '}}' after reference at line 1 character 8:
{{ true ? 11 : 00 }}
       ^----
```

**Comment by Rich-Harris** [comment]
Looks like it's time to update my [bullet-proof number regex](https://gist.github.com/Rich-Harris/7544330)... on it

**Comment by Rich-Harris** [comment]
fixed in edge, thanks
