### ISSUE TITLE
Inline partials discrepancy

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1824]
Came across this while updating the [template spec](https://github.com/ractivejs/template-spec): http://jsfiddle.net/rich_harris/eh4kqxd6/

Presumably, inline partials should be attached to their parent component, rather than all sharing the top level, and there shouldn't be a difference between parsed-at-instantiation versus pre-parsed.

Possibly a 0.7.1 fix

**Comment by evs-chris** [comment]
If you pass a Ractive instance to `parse` (`Ractive.parse(str, { ractive: myInstance })`), it will spit out a template object with the partials anchored to the right elements. It should definitely be possible to use `Ractive.defaults.components` though, and that isn't currently happening.

I think there is a better solution, though it adds a bit of expense to using partials, so it may not be worth it. That would be to just attach inline partials to the nearest element at parse time and then stick them to their components just before they are used. That way any pre-parsed template could be used with any set of components and the right thing should happen in each case.

**Comment by Rich-Harris** [comment]
I think that's the right approach (attaching to nearest element at parse time). Just tinkering a bit with that now
