### ISSUE TITLE
Ractive dies on wrong data (TypeError)

### ISSUE THREAD

**Issue by anton-ryzhov** [ractivejs/ractive#1825]
In lots of cases Ractive skips wrong data and continues to work. But it entirely dies if meet empty object as argument.

http://jsfiddle.net/4s76b4uw/
```js
new Ractive({
    el: 'body',
    
    template: '<hr class="{{ emptyObject }}" />',
    
    data: {
        emptyObject: Object.create(null),
    },
});
// TypeError: Cannot convert object to primitive value
```

**Comment by Madgvox** [comment]
That's interesting, since both `emptyObject: null`, and `emptyObject: {}` produce no error. It must be due to the fact that `Object.create(null)` has no `__proto__`.

**Comment by anton-ryzhov** [comment]
@Madgvox , yes, sure. It has no `__proto__` and can't access to `Object.toString()`.
I think `try…catch` block in the `Interpolator__toString` will help to to fix that.

**Comment by anton-ryzhov** [comment]
Same issue for `Interpolator__render`:
http://jsfiddle.net/4s76b4uw/1/

**Comment by martypdx** [comment]
@anton-ryzhov have PR for this. I think it covers the needed areas, but will leave open for a bit in case you find anywhere else.

**Comment by anton-ryzhov** [comment]
I've faced with this bug in two separate cases. With `Object.create()` and with Firebugs `console.log()` (see #1645).
Your PR covers first case `!value.toString === true`, but not second one — even accessing `value.toString` raises error.
I believe try-catch block will help in both cases in both Interpolator methods.

**Comment by martypdx** [comment]
> I believe try-catch block will help in both cases in both Interpolator methods.

try-catch prevents javascript optimization so don't want that in hot path of render/update code.

> Your PR covers first case !value.toString === true, but not second one — even accessing value.toString raises error.

Not sure I follow. What would be the test case that would make it fail?

**Comment by martypdx** [comment]
@anton-ryzhov I merged so you could try it out. Will leave open...

**Comment by anton-ryzhov** [comment]
Testcase: Firefox 36, Firebug 2.0.8, run in console
```js
foo = console.log('');
foo.toString
```
![screenshot from 2015-03-15 21 38 16](https://cloud.githubusercontent.com/assets/556933/6657402/ff96f1ce-cb5b-11e4-9b70-f66131d8c8aa.png)

**Comment by martypdx** [comment]
I'm leaning towards a wontfix on this, unless we can figure out a way to detect that type of object without the use of try/catch. I did a bit of digging on Firebug and this behavior, doesn't seem to be a lot to go on at this point.

You could patch console.log or make a wrapper function. I suppose we could create a predefined Ractive.log that could be used instead if this becomes a big issues.

**Comment by evs-chris** [comment]
Out of curiosity, what about `'toString' in value`?

**Comment by martypdx** [comment]
@evs-chris same error. The return value from firebug is some sort of native interop oject

**Comment by anton-ryzhov** [comment]
Ok, I accept your decision, performance is more important here.

**Comment by martypdx** [comment]
![image](https://cloud.githubusercontent.com/assets/478864/6657592/1e8138d6-cb0e-11e4-9ee1-105023d73bc6.png)

Here's the console.dir of the return, but can't seem to test for `__exposedProps__`

**Comment by anton-ryzhov** [comment]
Yes, `value.__exposedProps__ === undefined`.
Firebug guys made some strange thing.

**Comment by martypdx** [comment]
FWIW I asked on [SO](http://stackoverflow.com/questions/29065360/calling-tostring-on-firebug-console-log-return-value-throws).

**Comment by anton-ryzhov** [comment]
http://code.google.com/p/fbug/issues/list looks more suitable place to discuss it, isn't it?

**Comment by martypdx** [comment]
Looks like the SO question triggered a, [issue](https://code.google.com/p/fbug/issues/detail?id=7774) and subsequent [fix](https://github.com/firebug/firebug/commit/790572b5f5ce9fe218e1a779aebccb495de12d1c)!:

**Comment by anton-ryzhov** [comment]
Great. Should I close this issue?
