### ISSUE TITLE
Inline partial has gone missing

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#1838]
http://jsfiddle.net/xmk8kod1/

```js
var ractive = new Ractive({
    el: 'body',
    template: '<div>{{#partial foo}}foo{{/partial}}</div>{{>foo}}'
});
```

I haven't had a chance to dig into it yet, I just wanted to make sure it was noted.

**Comment by Rich-Harris** [comment]
This'll be related to #1824/#1835. Isn't that the desired behaviour though? If inline partials are 'scoped' to their components, then a partial that needs to be available throughout the template needs to be defined at the top level of the template: http://jsfiddle.net/rich_harris/cnffkqj0/

**Comment by evs-chris** [comment]
> Isn't that the desired behaviour though?

I'm not sure... it is a bit different from the previous behavior though, which allowed inline partials anywhere and bubbled them up to the nearest component. I'll defer to your judgement on the desired behavior.

For reference, I have a CMS-like thing that assembles parts of a page with their chunks of template that may include partials for recursive things. I think I can make it work without having the partials at arbitrary levels.

**Comment by martypdx** [comment]
> Isn't that the desired behaviour though?

It threw me at first, but makes sense. Does it means you can do:

<div>
  {{#partial foo}}one{{/partial}}
   <span>{{>foo}}</span>
</div>
<div>
  {{#partial foo}}twp{{/partial}}
   <span>{{>foo}}</span>
</div>

Needs to be document as _element_ scope right?

**Comment by Rich-Harris** [comment]
ooh, good question. Right now, those partials would just get lost in the ether because they're not top-level, and `<div>` turns out not to be a component. But we could absolutely store them on `Element` items, and use them in `getPartialTemplate.js`. That would actually be pretty neat

**Comment by martypdx** [comment]
I think you have to go all the way with this one. It doesn't make sense to say it "got lost" while still being component/instance scoped.

> That would actually be pretty neat

And in case we never understand the new mustache inheritance syntax, it would probably be swell to just do:

```html
{{#partial foo}}
Something happens {{>here}}
{{/partial}}

<div>
  {{#partial here}}one{{/partial}}
   <span>{{>foo}}</span>
</div>
<div>
  {{#partial here}}two{{/partial}}
   <span>{{>foo}}</span>
</div>
```

**Comment by evs-chris** [comment]
Oh, I like that.

**Comment by Rich-Harris** [comment]
> It doesn't make sense to say it "got lost"

Agree, this was an oversight on my part. That use case didn't occur to me. I *think* that the example above would just work if we implemented element-level scoping, because you wouldn't break out of the current scope and into the partial's scope. So yeah, that could solve some layout headaches in quite a nice way

**Comment by martypdx** [comment]
Think we can close this? @evs-chris reopen if I'm wrong about that...
