### ISSUE TITLE
Passing a `data` option with object and array properties to Ractive.extend() is discouraged as mutating them is likely to cause bugs.

### ISSUE THREAD

**Issue by Madgvox** [ractivejs/ractive#1840]
I recently switched over to edge in order to use the new component features in my app. This enabled debug mode for the first time for me, and I got a bunch of these messages. I've used `Ractive.extend()` + a plain data object heavily virtually since I started using ractive and I've never noticed any issues with this. Can I get a bit of clarification on what these possible bugs are, and what they're caused by?

**Comment by Rich-Harris** [comment]
It's basically the scenario described [here](https://github.com/ractivejs/ractive/issues/1803#issuecomment-78647781) - if you have multiple instances of a component that has array/object properties on its `data` object, there's a strong risk that an instance could mutate them causing everything to blow up in hard-to-debug ways:

```js
X = Ractive.extend({
  data: {
    answer: 42,     // fine
    emptyArray: [], // not fine, might not be empty for long
    obj: {}         // careful!
  }
});

r1 = new X();
r2 = new X();

r1.set( 'obj.foo', 'bar' );
r2.push( 'emptyArray', 'trololol' );

r2.get( 'obj.foo' ); // 'bar'
r1.get( 'emptyArray' ); // 'trololol'
```

**Comment by Madgvox** [comment]
Ahh, I see the issue. Thanks, might as well switch over to data functions then, if only to silence all those console messages. :+1:
