### ISSUE TITLE
Todo app at TodoMVC fails on double-click to edit

### ISSUE THREAD

**Issue by brandondrew** [ractivejs/ractive#1842]
At http://todomvc.com/examples/ractive/# I'm having repeated problems editing a task.  Sometimes double-clicking does nothing, and sometimes it makes all tasks editable, and sometimes it makes a subset editable.

**Comment by Rich-Harris** [comment]
Wow, I don't recognise that app at all! Looks like they changed a bunch of stuff. Also it's a ludicrously old version, we'll need to send them a PR with a working up-to-date version. Thanks for the heads up!

**Comment by martypdx** [comment]
I thought we fell off their list because we don't have a big model, action, control stack so we're not really an MVC. :)

**Comment by brandondrew** [comment]
I'm glad to have confirmation that the problem is with the app and not something with Ractive itself.  I've just discovered it and spent every spare moment for the last few days reading everything I can.  Over and over, with very few exceptions, as I understand a new aspect of Ractive I think to myself "wow... that's exactly how I would have designed it" (if I had both the brains and the time to do so, that is).

(I can post the lone exception I can think of as an issue if you're interested... depending on your tolerance threshold for such things--which could range from "we accept only bugs" to "we'd love to hear even the most certifiedly crazy ideas".)

**Comment by Rich-Harris** [comment]
The worst we can do is say 'that's certifiably crazy'... try us!

**Comment by brandondrew** [comment]
okay... I'm posting it... please consider it even though it would be a change away from what you're used to.

**Comment by brandondrew** [comment]
#1848

**Comment by evs-chris** [comment]
We're not on the list anymore, and the version in the example is 0.3.9 😱, so I'm gonna say this is probably safe to close.
