### ISSUE TITLE
observe & removed items

### ISSUE THREAD

**Issue by timoxley** [ractivejs/ractive#1843]
Using latest edge version of ractive:

```js
import Ractive from 'ractive'

Ractive.defaults.debug = true
const IntegerComponent = Ractive.extend({
  template: `
    <h2>Integer Value:{{value}}</h2>
  `,
  oninit() {
    this.observe('value', (newValue, oldValue, keypath) => {
      let value = parseInt(newValue, 10)
      if (isNaN(value)) value = 0
      this.set(keypath, value)
    })
  }
})

new Ractive({
  el: document.body,
  template: `
    {{#numbers:index}}
      <my-integer value="{{this}}"></my-integer>
      <button on-click="splice('numbers', index, 1)">Remove</button>
    {{/items}}
  `,
  components: {
    'my-integer': IntegerComponent
  },
  data: {
    numbers: [ 1, 2, 3 ]
  }
})

```

Playing with this leads to some interesting behaviour:

![ezgif-697455156](https://cloud.githubusercontent.com/assets/43438/6693218/598db314-cd0c-11e4-8e1c-b447b1676e29.gif)

This is due to the `this.observe('value'` code running asynchronously after the item has been removed from the array. The item is removed but the observe handler fires with `newValue` being `undefined` and subsequently updates the now removed `keypath`. This might be considered a user error, but it'd be nice if ractive could somehow avoid this issue as it took a long time to track down wtf was causing this as it didn't happen in ractive `0.6.1`. I don't think observers should fire for each property when objects are removed, or that should be an option like `{init: true}`.

If I did want to do this, how could I detect that the object is being removed? `undefined` isn't a good signal since perhaps that's a valid value.

Also would be good if ractive had some other way to enforce constraints on data, especially those going into components. See react has [this](https://facebook.github.io/react/docs/reusable-components.html) allowing you to specify optional/required properties, as well as enforcing datatypes.

**Comment by Rich-Harris** [comment]
Oof, this is kind of a perfect storm. Going to take a bit of unpacking. In the meantime I've put your example into a [fiddle](http://jsfiddle.net/rich_harris/as9jym5L/).

I have a hunch that @martypdx's work on #1740 is going to enable us to think through problems like this one with a bit more clarity.

Agree, a more idiomatic way of validating data would be good to have.

**Comment by martypdx** [comment]
For current state of Ractive, computed property setters tend to work better because they sit between the action and the data (see http://jsfiddle.net/as9jym5L/5/). 

```js
Ractive.components.Integer = Ractive.extend({
    template: '<h2>Integer Value:{{_value}}</h2>',
    computed: {
        _value: {
            get: '${value}',
            set: function(value){
                value = parseInt(value, 10);
                if (isNaN(value)) value = 0
                this.set('value', value);
            }
        } 
    }
})
```
Whereas observers that try to set their observed value end up in a bit of a mess.

See #1286 for my sad attempt and trying to monitor array changes and arrival at the conclusion we need an `observeArray`. :)

**Comment by evs-chris** [comment]
This is fixed in edge.
