### ISSUE TITLE
Gobble throwing 'build invalidated' errors when building on Windows

### ISSUE THREAD

**Issue by Madgvox** [ractivejs/ractive#1847]
When running `gobble build`, I get this:

```cmd
gobble: 02-babel done in 9753ms
gobble: 02-babel done in 9753ms
gobble: 02-babel done in 9753ms
gobble: 02-babel done in 9753ms
gobble: 02-babel done in 9753ms
gobble: 02-babel done in 9753ms
gobble: 03-esperantoBundle done in 768ms
gobble: 07-sorcery done in 541ms
gobble: 04-esperantoBundle done in 626ms
gobble: 08-sorcery done in 447ms
gobble: 05-esperantoBundle done in 583ms
gobble: 09-sorcery done in 387ms
gobble: 06-esperantoBundle done in 545ms
gobble: 10-sorcery done in 395ms
gobble: 24-merge done in 32ms
gobble: 11-moveTo done in 7ms
gobble: 11-moveTo done in 7ms
gobble: 12-merge done in 5ms
gobble: 12-merge done in 5ms
∙∙∙∙∙∙? 13-babel running...
gobble: build invalidated
>>>
Error
    at new GobbleError (C:\Users\Madgvox\Documents\ractive\node_modules\gobble\l
ib\utils\GobbleError.js:6:15)
    at C:\Users\Madgvox\Documents\ractive\node_modules\gobble\lib\nodes\Source.j
s:92:16
    at later [as _onTimeout] (C:\Users\Madgvox\Documents\ractive\node_modules\go
bble\node_modules\debounce\index.js:34:23)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
<<<


gobble: build invalidated
>>>
Error
    at new GobbleError (C:\Users\Madgvox\Documents\ractive\node_modules\gobble\l
ib\utils\GobbleError.js:6:15)
    at C:\Users\Madgvox\Documents\ractive\node_modules\gobble\lib\nodes\Source.j
s:92:16
    at later [as _onTimeout] (C:\Users\Madgvox\Documents\ractive\node_modules\go
bble\node_modules\debounce\index.js:34:23)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
<<<


gobble: build invalidated
>>>
Error
    at new GobbleError (C:\Users\Madgvox\Documents\ractive\node_modules\gobble\l
ib\utils\GobbleError.js:6:15)
    at C:\Users\Madgvox\Documents\ractive\node_modules\gobble\lib\nodes\Source.j
s:92:16
    at later [as _onTimeout] (C:\Users\Madgvox\Documents\ractive\node_modules\go
bble\node_modules\debounce\index.js:34:23)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
<<<
```

When running `gobble`, I get this:

```cmd
gobble: server listening on port 4567
gobble: livereload server running
gobble: 02-babel done in 6213ms
gobble: 03-esperantoBundle done in 732ms
gobble: 04-sorcery done in 539ms
gobble: 01-moveTo done in 3ms
gobble: 05-sorcery done in 3ms
gobble: 19-merge done in 5ms
gobble: 06-moveTo done in 7ms
gobble: 07-merge done in 5ms
gobble: build invalidated (3 files changed). restarting
gobble: build invalidated (6 files changed). restarting
```

And it stays like that forever. If I go to `localhost:4567` it just shows the 'gobbling' message.

I've tried doing a clean npm install, and completely resetting the repository through git. I'm going to try to do some more digging, but I'm not familiar with gobble so I'm not entirely sure what to look for.

**Comment by Madgvox** [comment]
Looks like this is probably the same issue as https://groups.google.com/forum/#!topic/ractive-js/5FPJUCzqLNg, so I'll close this.

**Comment by evs-chris** [comment]
That's the same issue that was killing the appveyor build. I got it to happen *once* on my machine, just after a fresh checkout and npm install. After it failed the first time, everything was OK. I came to the conclusion that something about watching windows filesystems is whacky. Is it repeatable for you? Running twice seems to be working for appveyor.

**Comment by Madgvox** [comment]
It's repeatable through restarts and reinstalls. I've yet to try completely nuking it, but that's my next step.

It's definitely something with the watcher. If I comment out the `test` section in the gobblefile it goes into an infinite loop just like in the link above.

**Comment by Madgvox** [comment]
I realized my node & npm versions were horribly out of date, but unfortunately bringing them up to date had no noticeable effect on the issue.

**Comment by Madgvox** [comment]
Alright, I've narrowed it down to exactly what is causing it to fail in the gobblefile:

The `lib.push( sandbox )` on line 88, and the babel transform starting on line 117. If I comment those two out, gobble successfully gets to 'build completed' and I can access the localhost properly. I still can't use it, since the sandbox isn't there and the tests attempt to run in es6, but it's progress.
