### ISSUE TITLE
feature request for improved consistency, elegance, and readability

### ISSUE THREAD

**Issue by brandondrew** [ractivejs/ractive#1848]
When I read Ractive code, I find that everything is easy to read and easy to understand.  This is very important to me, and I believe it is very valuable for my productivity.  (Not just mine&mdash;I believe it's valuable to everyone's productivity really, although lots of developers don't seem to realize this, and continue to use obscure or meaningless names for functions and variables and fields in the database). 

When I've worked with Angular I've always felt a little like vomiting in my mouth over all the little "ng-" turds littering my code.  Of course there's much to like about Angular, and I may still use it in the future as appropriate, but so many things attract me much more strongly to Ractive for any cases where I don't have a compelling reason to choose something else.

One reason I find Ractive code easy to understand is that it relies as much as possible on plain English words, rather than making up new and obscure conventions.  To specify a template I use the word... (drum roll, please!) "template"!  When I need to list partials I use... "partials".  When I want to refer to a source of data by variable name, or pass in data as a javascript object, I use... "data".  These are the most obvious and intuitive things possible.  At least if there's anything else comparable I can't think what it would be.  (I suppose you could use "layout" for the full-page template, and "templates" for partial templates, or something like that, but the Ractive way seems at least marginally clearer to my Rails-soaked thinking, and I'd be happy with either.)

When I want to do something on teardown, I use (no big surprise here) "onteardown" in my JavaScript.  The only thing I have to remember is that there is no underscore or camelCase or hyphen (the last of which would be impossible in the given context anyway).  That's not hard to remember, mainly because it's consistent (as far as I can see) throughout Ractive.  (Well, there's "on-teardown" as an attribute in templates and partials, but that's a different context and it makes sense to use a hyphen there to disambiguate between, for instance, "onclick" and "on-click".  So it's still logical and essentially consistent.)

These are just a few examples, but as far as I can see the pattern holds across all of Ractive.  Well... all except one thing.  The one notable exception that I have seen is "el".  I think it's pretty safe to assume that this is meant to stand for "element", but since it is abbreviated I have to remember that it is unlike everything else, and not to write out the whole word.  Moreover I have to remember that it's abbreviated in a particular way: not "elem" (as I've seen elsewhere), or "elm" or "elmnt" or any of the other myriad ways one might decide to abbreviate "element".  This is a problem with abbreviations.  We've got a (nearly!) standardized (or "standardised" on that side of the pond) spelling in the languages that are called "English", which means we have a wealth of shared conventions.  With only a smattering of exceptions, we all agree on how any given word is spelled.  But abbreviations are so often made up on the spot, and therefore require far more mental overhead to keep track of.  They're not quite as bad as random strings of arbitrary characters, but they're moving in that direction and away from the simplicity and ease-of-use of plain English words.

**Comment by MartinKolarik** [comment]
I'm not a fan of "simplifying" things only to save a few keystrokes, so :+1: for `element` from me.

**Comment by Rich-Harris** [comment]
It's funny, I was thinking similar thoughts last night. I'd be happy if we treated `el` and `element` as synonyms

**Comment by Rich-Harris** [comment]
This (along with many other issues) has been sidelined on the long road to 0.8 (on which we'll have more to report soon!) but I just wanted to make a note of @fskreuz suggested alternative, `target`, which I think  has some good things going for it.

**Comment by Madgvox** [comment]
I wasn't a huge fan of `target` when it was first suggested, but the more I think about it, the more I like it. It's a more general term than `element` and makes it more natural to be able to specify either a selector (`'#element'`) or an element (`myElem`). `element` seems slightly more like it just takes the element.

:+1: for `target`
