### ISSUE TITLE
Proporties added to array with bracket notation are ignored

### ISSUE THREAD

**Issue by Isinlor** [ractivejs/ractive#1852]
As in title. Here is a small demo: http://jsfiddle.net/mwo2jr49/

**Comment by martypdx** [comment]
Are you expecting iteration to combine array members and array properties? Or iterate the properties instead of the array members? Or just access the array property directly?

**Comment by Isinlor** [comment]
Intuitively it should combine them, but nothing in javascript is intuitive :) . I checked the mustache.js implementation: http://jsfiddle.net/cnn5xty9/ They are doing it in the same way as Ractive.js is now. And if I look at http://andrewdupont.net/2006/05/18/javascript-associative-arrays-considered-harmful/ , then I get to conclusion that maybe just the current behaviour should be documented.

**Comment by martypdx** [comment]
Yeah, array and hashmaps are mutually exclusive. You can still access the properties explicitly via `{{arr.one}}`.

**Comment by martypdx** [comment]
Also, you might consider using keypath expressions to unwind some of that complexity in those nested object hierarchies (if it works for your data):

```html
    {{#arr}}
        {{name}}
        <ul>
            {{# lists[list]}}<li>{{this}}</li>{{/list}}
        </ul>
    {{/}}
```

```js
var ractive = new Ractive({
	el:"container",
	template:"#template",
	data:{
        arr: [
            { name: 'one', list: 'listA' },
            { name: 'two', list: 'listB' },
            { name: 'three', list: 'listA' }
        ],
        lists: {
            listA: [1, 2, 3],
            listB: ['a', 'b', 'c']
        }
    }
});
```

see http://jsfiddle.net/npg3nf48/
