### ISSUE TITLE
Change {{#with obj}} to not render if obj is falsey

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1856]
@Rich-Harris brought this up in a comment [here](https://github.com/ractivejs/ractive/issues/1776#issuecomment-77954227) and I agree that `{{#with obj}}` should not render if `obj` is falsey.

**Comment by Madgvox** [comment]
Shouldn't it also have an `{{else}}

**Comment by martypdx** [comment]
It does already, added it last release. :) I

t's just kind of weird in that else works when falsey, but if you don't have an else block it runs the with with the empty object. Another reason to fix it up.

**Comment by Madgvox** [comment]
Oh, sweet! I totally missed that addition. Time to go edit some templates...

**Comment by ISNIT0** [comment]
https://github.com/ractivejs/ractive/pull/1984

**Comment by Madgvox** [comment]
This behavior still occurs in 0.8-edge: http://jsfiddle.net/jwk54ah9/

**Comment by skeptic35** [comment]
So... am I reading too much into this or does it mean the answer to #2024 should be "an empty object ist falsey"?

**Comment by MartinKolarik** [comment]
@skeptic35 yes, for explicit `{{#with object}}` it's now falsey. For `{{#object}}`, it's still truthy, but I think we should change that as well.

**Comment by dagnelies** [comment]
Damn, I'm always sooo late. I know it's long past, and I don't expect it to change, just wanted to add my grain of salt.

IMHO making `#with` work similar to `#if` was a step backwards. 

1) It broke all templates when upgrading from 07 to 0.8
2) It behaves now differently than handlebars, which is counter-intuitive to many
3) Before, a "conditional "with" could easily be achieved by combining "#if" and "#with". Now, chunks like:

```
{{#with just_let_the_user_fill_this_object}}
<div>
  Foo: <input value="{{.foo}}" />
  Bar: <input value="{{.bar}}" />
  More: <input value="{{.more}}" />
</div>
{{/with}}
```

Must always now be written more verbosely:

```
<div>
  Foo: <input value="{{just_let_the_user_fill_this_object.foo}}" />
  Bar: <input value="{{just_let_the_user_fill_this_object.bar}}" />
  More: <input value="{{just_let_the_user_fill_this_object.more}}" />
</div>
```

**Comment by evs-chris** [comment]
@dagnelies I'm right there with you. I was using something like that in a few places too, and I think an empty object not being used as context is actually a regression. I think it should still act like an `if` for _js_ falsey values, but empty arrays and objects are legitimate contexts. I shall put together a PR against 0.8 for any further discussion.

**Comment by paulocoghi** [comment]
> I think it should still act like an `if` for _js_ falsey values, but empty arrays and objects are legitimate contexts.

I totally agree, because I also had problems with this.
