### ISSUE TITLE
Select on first item in list not binding properly.

### ISSUE THREAD

**Issue by shayneoneill** [ractivejs/ractive#1858]
I'm having a slightly mysterious bug with a repeated form where only for the first item a select box isn't binding. 
```
  {{#items:i}}
   <div class="info-box {{#if (setting_type == 2)}}bg-teal-gradient{{ elseif (setting_type == 1) }}bg-red{{else}}bg-light-blue-gradient{{/if}}">
  ..stuff goes here..
    <select value='{{setting_type}}' style="color:#000" twoway="true">
                     {{#states}}
                    <option value='{{id}}'>{{name}}</option>
                     {{/states}}
                </select></small> {{setting_type}}
  ..more stuff goes here..
  </div>
  {{/items}}
```

It seems that when that select box is changed, it will reflect around the template and trigger the if/else clauses, but doesn't update the underlying model.items[i].setting_type. I should note all the other value in this form do update. Finally when I set  `ractive.observe(items.*.setting_type',typechange);` it triggers for all the other members of item, but not the first.

I honestly don't know how to work around this, and it feels like a bug of some sort.

**Comment by martypdx** [comment]
Could be an issue with the data property `setting_type` not existing on the item, and it's to a different level than you think 

Try changing all the the uses in the template to restricted references: `{{.setting_type}}`, `{{if (.setting_type ==2 }}`, etc.

Here's a fiddle I put together to test it out: http://jsfiddle.net/mnqbttxw/

**Comment by shayneoneill** [comment]
When I moved from selects to a radiobox check group the problem seemed to have resolved. I really do suspect the issue is somewhere in the <select> code.

**Comment by martypdx** [comment]
> I really do suspect the issue is somewhere in the select widget

Post a fiddle or test case and we'll take a look
