### ISSUE TITLE
Bower's Ractive is still at 0.6.1

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1859]
- Cleared bower cache
- Uninstalled Ractive from our deps
- Removed Ractive from our bower.json file
- `bower install ractive`

Still downloads v0.6.1. 

On the repo, I'm already seeing 0.7.1 on the package.json and the CDN version (on the homepage). But component.json still has 0.6.1 (and why is it still "component.json"?). Is this a Bower thing? Or is it Ractive?

While I could point our project to edge for now, it would be nice if they all methods were in sync.

**Comment by Madgvox** [comment]
@Rich-Harris Oops! It looks like 0.7.1 was never actually tagged, so bower never picked up on it.

**Comment by Rich-Harris** [comment]
Sorry, fixed now! Should really get round to automating releases... (they used to be but then we chucked out the old build process)

The `component.json` is for the benefit of the 4 or 5 people still using [component](http://component.github.io/)...
