### ISSUE TITLE
ractive.runtime throws ReferenceError

### ISSUE THREAD

**Issue by kui** [ractivejs/ractive#1860]
ractive.runtime.js seems not to work right on latest/edge versions:

* latest: http://jsfiddle.net/hc0bvzg4/1/
* edge: http://jsfiddle.net/pr0rkf9n/2/

In my console:

~~~~~~~~~~~~~~~~~~
Uncaught ReferenceError: parse is not defined
typeof Ractive: undefined
~~~~~~~~~~~~~~~~~~

**Comment by Rich-Harris** [comment]
Looks like this broke between 0.6.1 and 0.7.1 - will fix for 0.7.2. In the meantime the workaround would be to downgrade or use the non-runtime version - sorry!
