### ISSUE TITLE
Multiple params passing to event-proxy-handler doesn't work when using with strings

### ISSUE THREAD

**Issue by alexmakeev** [ractivejs/ractive#1862]
on-click="toggle:{{this}},1"  ---> toggle(this, 1)
on-click="toggle:{{this}},{{this}}"  ---> toggle(this, this)
on-click="toggle:{{this}},asdf"  ---> toggle("[Object], asdf")    Expected: toggle(this, "asdf")

**Comment by alexmakeev** [comment]
toggle-1:{{this}},{{"asdf"}} ---> toggle(this, "asdf")  Walk around

**Comment by alexmakeev** [comment]
Even:
on-click="toggle:tttt,asdf" ---> toggle("tttt,asdf") Expected: toggle("tttt", "asdf")

**Comment by dagnelies** [comment]
good opportunity to go forward with #1172...

**Comment by MartinKolarik** [comment]
I don't think this is a bug. If you use quotes for the strings, it works correctly:

```
on-click="toggle:{{this}},asdf" --> on-click="toggle: {{this}}, 'asdf'"
on-click="toggle:tttt,asdf" --> on-click="toggle: 'tttt', 'asdf'"
```

Ractive is just too forgiving, and if you don't use quotes, it thinks it's just one big string.
