### ISSUE TITLE
Wrapping jQueryUI in Ractive

### ISSUE THREAD

**Issue by gaelicmichael** [ractivejs/ractive#1863]
I have a large project that I am renovating. I originally used Knockout, but I prefer the architecture and style of Ractive. After reading the docs and looking at examples, I am unsure how to encapsulate jQueryUI widgets in Ractive components (that seems like the most appropriate mechanism) so that the code works properly and cleans up after itself. Namely, the following would need to be done:

(1) Provide a means of passing in a parameter used in constructing the component (i.e., an object that is going to be represented by the widget).
(2) Provide an initialization hook after Ractive had inserted elements into the DOM so that jQueryUI then has the chance to further modify it. This hook would need to pass the place in the DOM where the component has been built.
(3) Provide a detach hook, passing the node in the DOM as a parameter, so that jQueryUI can be called to deconstruct the widget before Ractive gets rid of the component.

It is entirely unclear to me how this would be done, and all of the examples are too trivial to handle such a case. I am writing an open source public platform, and would be glad to make my solutions public, should I get a hand in finding a solution.

Otherwise, I will just stick with knockout, which at least seems to provide the functionality I require.

Thank you in advance.

**Comment by fskreuz** [comment]
We're currently doing the same thing, except we use Bootstrap rather than jQuery UI. We're not doing all of it, as we see it as mere syntax sugar. An example would be a panel:

Plain HTML
```html
<div class="panel panel-success">
  <div class="panel-heading"><h3 class="panel-title">Hello World</h3></div>
  <div class="panel-body">The quick brown fox jumps over the lazy dog</div>
</div>
```

Ractive component
```html
<bs-panel context="success">
  <bs-panel-heading>Hello World</bs-panel-heading>tget
  <bs-panel-body>The quick brown fox jumps over the lazy dog</bs-panel-body>
</bs-panel>
```

bs-panel.html
```html
<div class="panel panel-{{ context }}">
  {{ yield }}
</div>
<script>
component.exports = {
  isolated: true,
  data: {
    context: 'default',
  }
};
</script>
```

You can imagine the same for the others. We use `{{ yield }}` so basically the components are just template wrappers. But you can opt to use content instead. We modelled the approach based on [react-bootstrap](https://react-bootstrap.github.io/components.html). 

To answer your questions, read up on the [component spec for authors](https://github.com/ractivejs/component-spec/blob/master/authors.md). This is what you see in the example. It's basically HTML+CSS+JS in one file *for that component*.

> Provide a means of passing in a parameter used in constructing the component (i.e., an object that is going to be represented by the widget).

Using the component spec, you use components like custom HTML elements. The attributes directly map to the `data` property in the exported object. In the case of the example, the constructor has a `context` of "default" by default. However, it's overridden by "success" in the component that uses it.

> Provide an initialization hook after Ractive had inserted elements into the DOM so that jQueryUI then has the chance to further modify it. This hook would need to pass the place in the DOM where the component has been built.

Ractive has [lifecycle hooks available](http://docs.ractivejs.org/latest/lifecycle-events) which you can declare in the component's exported object. Typically you'll be using `onrender` as you need the component to be mounted to the DOM before you run jQuery stuff.

> Provide a detach hook, passing the node in the DOM as a parameter, so that jQueryUI can be called to deconstruct the widget before Ractive gets rid of the component.

The lifecycle events also provide an `onteardown` which allows you to dismount all your mounted stuff before Ractive disposes of the component.

As for two-way binding, sometimes you can't do this "naturally" as most plugins mutate the DOM programmatically. To set data, you need observers to observe the data, and then set the value to the DOM using the plugin. To flush back data into the component, your plugin needs to have some event mechanism to tell you when it has updated, and use `Ractive.set` to set back the data.

**Comment by gaelicmichael** [comment]
Thanks for your suggestions. They were helpful, though I'm still having problems understanding how I would actually accomplish this in the code. I'm testing the feasibility of Ractive by attempting to implement the most complex widget I'll need, which is a jQueryUI nestable sorted list (implemented with https://github.com/ilikenwf/nestedSortable). This case is more complex than the Dialog example because I cannot assume that only one instance exists (I need to provide a distinct ID for each parent node). I want to be able to create the Component with a line like this within the Ractive area:

```
		<div id="ractive-output">
			<nested nestid="test-nester" array="legendHierarchy"></nested>
		</div>
```

This would assign the ID "test-nester" to the resulting DOM element and bind the array "legendHierarchy" to the Component.

I've managed to create this item via Ractive (without the complication of jQuery). I think that the top-most level of the Component's template would look like this:

```
<script id="nesting-outer" type='text/ractive'>
	<ol id="{{nestid}}" class="sortable">
		{{#each items:index1}}
			{{>nest1}}
		{{/each}}
	</ol>
</script>
```

It's not producing any output (including the debugging console.log output), so I'm clearly not understanding something. My code looks like this:
```
			// Create a component to wrap jQueryUI Nestable
		var NestComponent = Ractive.extend({
			template: '#nesting-outer',
			data: {
				items: [ ],			// the array represented
				nestid: 'default'	// the unique ID for this div
			},

				// Intercept render to insert and activate jQueryUI plugin
			onrender: function() {
				var thisID = '#'+this.get('nestid');
console.log("Attempting to create jQuery widget "+thisID);
				jQuery(this.find(thisID)).nestedSortable({
(... init options)
				});
			},

				// Intercept teardown to create jQueryUI component
			onteardown: function () {
console.log("Tear down");
			}
		});

		var ractive = new Ractive({
			el: 'ractive-output',
			components: {
				nested: NestComponent
			},
			data: { legendHierarchy: nestData }
		});
```

Thanks again in advance for your help.

**Comment by martypdx** [comment]
In the Bootstrap case, there's boilerplate markup to encapsulate into a
component but for many jQuery widgets that's not the case. So you might
consider making a decorator instead. Check out
http://prezent.github.io/ractive-decorators-select2/ for an example.

Basic pattern:

<!-- located on the node, so self-identifying. Data is passed in, and
update will be called on decorator if it changes.
<div decorator='jqueryWidget:theData'></div>

// decorator
Ractive.decorators.jqueryWidget = function ( node, data ) {

     var keypath = Ractive.getNodeInfo(node).keypath,
           ractive = this;

     var $widget = $(node).doYourWidgetThing({
          onchange: function(){
              this.updateModel(keypath);
          }
     });

     return {
          teardown: function(){
               $widget.destroy()
          }
          update: function(data){
              $widget.heresnewdata(data);
          }
     }
}

**Comment by martypdx** [comment]
[ typo: should be ractive.updateModel(keypath) inside change function ]

**Comment by martypdx** [comment]
In the Bootstrap case, there's boilerplate markup to encapsulate into a
component but for many jQuery widgets that's not the case. So you might
consider making a decorator instead. Check out
http://prezent.github.io/ractive-decorators-select2/ for an example.

Basic pattern:

```html
<!-- located on the node, so self-identifying. Data is passed in, and
update will be called on decorator if it changes. -->
<div decorator='jqueryWidget:theData'></div>
```

```js
// decorator
Ractive.decorators.jqueryWidget = function ( node, data ) {

     var keypath = Ractive.getNodeInfo(node).keypath,
         ractive = this;

     var $widget = $(node).doYourWidgetThing({
          onchange: function(){
              ractive.updateModel(keypath);
          }
     });

     return {
          teardown: function(){
               $widget.destroy()
          }
          update: function(data){
              $widget.heresnewdata(data);
          }
     }
}
```

**Comment by martypdx** [comment]
> I've managed to create this item with plain Ractive (without the complication of integrating it with jQuery).

:+1: 

> It's not producing any output (including the debugging console.log output), so I'm clearly not understanding something.

```
var ractive = new Ractive({
            el: 'ractive-output', 
            components: {
                nested: NestComponent
            },
            data: { legendHierarchy: nestData }
        });
```

`ractive-output` appears to be your template and your target el.  They need to be two separate things.

**Comment by gaelicmichael** [comment]
No, I don't think that's the problem. The template for the component is "nesting-outer" -- "ractive-output" is the DIV where the Ractive output will be sent.

**Comment by gaelicmichael** [comment]
Furthermore, I don't that the the decorator approach will work because the Component needs to insert a template that unwinds two nested array loops (which I implemented in my prior Ractive test with two further templates).  I don't see that decorators can function this way.

**Comment by Madgvox** [comment]
Is `ractive-output` an id or a class? If it's a class, you need to prefix it with a `.`.

**Comment by martypdx** [comment]
> No, I don't think that's the problem. The template for the component is "nesting-outer" -- "ractive-output" is the DIV where the Ractive output will be sent.

Okay, then in your example you've got the component directive in the output, so it's not in the template:

```html
        <div id="ractive-output">
            <!-- this should be in the template, not the target el -->
            <nested nestid="test-nester" items="{{legendHierarchy}}"></nested>
        </div>
```

**Comment by gaelicmichael** [comment]
Ah ha!  OMG, with that little fix, I think it may be working!!!  Wonderful!
