### ISSUE TITLE
Iteration over keys with dots fails

### ISSUE THREAD

**Issue by Crisfole** [ractivejs/ractive#1864]
See: https://jsfiddle.net/va6jU/96/

I realize it's a weird use case, but in my case I'm running a query over a bunch of databases, and the keys to the return val have dots in them (the url of the source database).

Took me a good long time to figure out what exactly the issue was...

**Comment by martypdx** [comment]
Yes, dots are not supported in data keys. :(  

I don't if testing every data key is feasible, but will look into it. Maybe just top level keys. We can certainly make it more prominent in the docs.

**Comment by Crisfole** [comment]
Better documentation would do the trick :) :+1:

**Comment by evs-chris** [comment]
Now that keypaths aren't just strings, does anyone feel any differently about escaping (`foo.bar\.baz`) or allowing things like `foo['bar.baz']` to become an intact keypath with a '.' in the second level?

**Comment by Madgvox** [comment]
Ooh, escaping is a surprisingly elegant solution for a messy problem. :+1:

**Comment by Rich-Harris** [comment]
Yeah, that seems much more feasible now. (Keys were escapable once, ages ago, but it caused all kinds of performance and code complexity problems that ought to be much less of an issue with how they're dealt with now.) Will probably have to be addressed after (or as part of) #1740

**Comment by TehShrike** [comment]
I would very much like this to be implemented.  I have an object of file names in my data object, and I tried `files["somefile.md"]` and expected it to work.

My use case is both static strings like above, and dynamic usage ala `files[filename]`

**Comment by evs-chris** [comment]
This is fixed in edge.

**Comment by Crisfole** [comment]
:clap:
