### ISSUE TITLE
Deferred observers firing before node removal

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1869]
Interesting case from @wpf500: http://jsfiddle.net/rpyw1c0y/

**Comment by martypdx** [comment]
Interesting. [In runloop](https://github.com/ractivejs/ractive/blob/dev/src/global/runloop.js#L34-L36) Observer fires at end of flushChanges, node is removed by transactionManager. Taking transitions out of the picture, it does seem logical that deferred observers should come last.

**Comment by martypdx** [comment]
Though it does raise an interesting distinction between observing the viewmodel vs observing the virtualDOM vs observing the DOM

**Comment by Rich-Harris** [comment]
Yeah. The whole point of deferred observers is precisely to be able to respond to changes to the real DOM, and the idea is that it should happen synchronously to avoid flicker etc. So to clarify, do we agree that the order should be

* data changes
* computed values etc update
* non-deferred observers fire
* virtual DOM updates
* nodes are changed and added. nodes without outros are removed
* deferred observers fire

*time passes*

* nodes with outros are removed

?

If you want to ensure that *all* nodes have been removed, transitions or not, and don't care about work happening in the same turn of the event loop then the promise returned from an update method is your friend.

**Comment by Madgvox** [comment]
This still occurs in 0.8-edge: http://jsfiddle.net/rpyw1c0y/1/
