### ISSUE TITLE
Dynamic insertion of Ractive elements wrapping jQueryUI

### ISSUE THREAD

**Issue by gaelicmichael** [ractivejs/ractive#1870]
I'm still trying to get my head around how Ractive works in complex, real-world scenarios. With some help from generous folks here, I've managed to get a couple of JQueryUI components to be constructed with Ractive templates, but I don't understand how such Ractive-wrapped components could be created and inserted dynamically.

For example, I've created a Dialog component that comes up when a webpage is opened (code given below). But how would I dynamically insert such a Ractive component dynamically so that it would only appear when a button was pressed?

```
<script id="ractive-example" type='text/ractive'>
	<div id="insert-point"></div>
	<dialog title="Test Title" subtitle="Test Subtitle">
		<p>This is my dialog content</p>
	</dialog>
</script>

<!-- Ractive Template for Dialog Component -->
<script id="dialog-r-template" type='text/ractive'>
    <div class="dialog-template" title="{{title}}">
        <h3 id="dialog-subtitle">{{subtitle}}</h3>
        {{>content}}
    </div> <!-- dialog -->
</script>

			// Create Ractive component to wrap jQueryUI Dialog
		var DialogComponent = Ractive.extend({
			template: '#dialog-r-template',
			data: {
					// set defaults
				title: '',
				subtitle: '',
				width: 350,
				height: 300
			},

				// Intercept render to insert and active jQueryUI plugin
			onrender: function() {
				var thisComponent = this.find('.dialog-template');
				var newModal = jQuery(thisComponent).dialog({
					width: this.get('width'),
					height: this.get('height'),
					modal : true,
					autoOpen: false,
					buttons: [
					{
						text: 'Cancel',
						click: function() {
							$(this).dialog('close');
						}
					},
					{
						text: 'Save',
							// How to intercept? ractive.on('clicked', function(ev) {
						click: function() {
						}
					}]
				});
				newModal.dialog('open');
			}, // onrender

				// Intercept teardown to create jQueryUI component
			onteardown: function () {
				var thisComponent = this.find('.dialog-template');
				jQuery(thisComponent).destroy();
			} // onteardown
		});

			/* Open Dialog -- doesn't work!! */
		jQuery('#open-dialog').click(function(evt) {
			jQuery('#insert-point').append('<dialog title="Test Title" subtitle="Test Subtitle"><p>This is my dialog content</p></dialog>');
		});
```

Again, I think that Ractive is great and deserves more attention. If I can figure this out and determine that it will serve my complex needs, I'll make my jQueryUI wrappers public.

**Comment by gaelicmichael** [comment]
And just to add -- I've also tried the following, with no success.
```
<script id="generate-nested" type='text/ractive'>
	<div id="insert-point">
		{{{insertdialog}}}
	</div>
</script>

	jQuery('#open-dialog').click(function(evt) {
		ractive.set('insertdialog', '<dialog title="Test Title" subtitle="Test Subtitle"><p>This is my dialog content</p></dialog>');
	});
```

**Comment by guilhermeaiolfi** [comment]
You could create a observer in a attribute like "hidden" and execute the jquery plugin function accordingly. And have functions like open() and hide() in your component to change this attribute.

```javascript
...
data: {
 hidden: true
},
onrender: function() {
   ...
   this.observe('hidden', function(hidden) {
      if (hidden) {
          jQuery(thisComponent).dialog('hide');
      } else {
          jQuery(thisComponent).dialog('open');
      }
   });
   ...
},
open: function() {
   this.set('hidden', false);
},
hide: function() {
   this.set('show', true);
}
...
```

**Comment by gaelicmichael** [comment]
I'm sorry, guilhermeaiolfi, but I don't like that solution -- it's too much of a hack. Isn't it possible to insert DOM elements that can be parsed and made live by Ractive, including Components?  There must be some mechanism, but I can't find the relevant documentation nor any example of this sort.

**Comment by guilhermeaiolfi** [comment]
But you can use your ractive instance as a component like so:
```javascript
var ractive = new Ractive({
  el: 'body',
  template: '#template',
  components: { jquery-ui-dialog: DialogComponent }
});
```
```html
<script id="template" type="text/ractive">
  <div>
    <jquery-ui-dialog hidden="true">
  </div>
</script>
```

**Comment by gaelicmichael** [comment]
I'll try a solution like that -- creating a new Ractive instance for a dynamically-created dialog.

**Comment by gaelicmichael** [comment]
Thanks!  Yes, creating a new Ractive instance and causing it to be inserted into a DIV of the current Ractive DOM space does indeed work. Thank you for your help. I will try to complete this complex case and offer a blog entry about it.

**Comment by martypdx** [comment]
I'm not super familiar with jQuery dialog, but here's an implementation with some ideas for you: http://jsfiddle.net/a2ef6zy7/

One of the great things about ractive is how it supports different styles and architecture.

**Comment by gaelicmichael** [comment]
Thanks, Marty, that's very helpful!  I've been struggling over the last couple of hours to get on-click to work in a dialog component (dynamically created within another Ractive context). Maybe this will help.

**Comment by guilhermeaiolfi** [comment]
Using @martypdx 's jsfiddle I adapted to use observers: http://jsfiddle.net/a2ef6zy7/3/

I like the idea to keep the state of the widget in the data model because you can bind your model to the state of the widget (as shown by clicking in the checkbox). Although, in ember, observers are a bit expensive CPU wise. I don't know about ractive.

**Comment by gaelicmichael** [comment]
I thought that I had this Ractive component wrapper for the jQueryUI dialog working, but I've just discovered that it is only working in the case that the OK button is pressed (not "Cancel"). Does anyone have any idea why this might be the case? When I press "Cancel" the outer DIV created by jQueryUI does indeed disappear, but the inside DIV remains in the DOM. The onteardown() function is indeed called in both cases. It doesn't matter whether I keep the call to .dialog("close"), or I remove it, the same problem happens.

```
var RJDialogComponent = Ractive.extend({
	template: '#dialog-r-template',
	data: function() {
		return {
			title: '',
			width: 350,
			height: 300
		}
	}, // data

		// Intercept render to insert and active jQueryUI plugin
	onrender: function() {
		var self = this;
		var thisComponent = this.find('*');
		self.modal = jQuery(thisComponent).dialog({
			width: self.get('width'),
			height: self.get('height'),
			modal : true,
			autoOpen: false,
			buttons: [
			{
				text: 'Cancel',
				click: function() {
// BUG!  Not working...
					self.modal.dialog('close');
					self.teardown();
				}
			},
			{
				text: 'Save',
				click: function() {
					self.fire('save');
				}
			}]
		});
		self.modal.dialog('open');
	}, // onrender

		// Intercept teardown so that jQueryUI component destroyed
	onteardown: function () {
		this.modal.dialog('destroy');
	} // onteardown
});
```

**Comment by gaelicmichael** [comment]
Update: If I make the Cancel code fire a message (like 'close') as Save does, and then listen for that 'close' message in the code that creates the modal, I can call teardown and it works properly. However, this is more complexity than should be necessary. The dialog Component ought to be able to deconstruct itself without relying the external code that creates it to do it.
