### ISSUE TITLE
Specified model not set on update

### ISSUE THREAD

**Issue by marcelboettcher** [ractivejs/ractive#1875]
Hey guys,

thanks for the great work!

I just struggled with a use case where I want to hand plain data objects into the components from the outside, but need some functionality on that data inside the components. So I essentially want to put my data into a model inside the ractive components.
After some research on adapters and decorators I found the [Advanced Configuration section](http://docs.ractivejs.org/latest/advanced-configuration) where you describe how to specify your own model. I have a computed property, which does the need the data wrapped into my model. That works in v0.6.1 initially, but not after I update the data from the outside. 

Code: 

```
Ractive.components['cod-image'] = Ractive.extend({
		isolated: true,
		template: cod.mustache.image,
		data: function(data) {
			data.image = new cod.Image(data.image);
			return data;
		},
		computed: {
			src: function() {
                               //this should but isn't an instance of cod.Image after update is called
				var image = this.get('image');  
				return image.getSrc();
			}
		}
	});
```

Is that expected behavior and I'm confusing some of your concepts?

Thanks a lot!
Marcel

**Comment by fskreuz** [comment]
Can you set up a minimal demo for this? I don't see anything wrong with the code itself unless... `update` flushes *down* changes. This means that your `image` could have been modified *before the call* by something else.

Try hooking up an observer to `image` in `oninit` and put a `debugger` statement inside the callback in order to trace the offending mutation.

**Comment by martypdx** [comment]
What do you mean by "update the image"?

**Comment by marcelboettcher** [comment]
thanks, that seems to be what I'm looking for. Just thought that 
```
Ractive.components['cod-image'] = Ractive.extend({
        data: function(data) {
            data.image = new cod.Image(data.image);
            return data;
        },
...
```
would be triggered on each update cycle as well.

Thanks a lot!

**Comment by Madgvox** [comment]
I'll close this issue as it seems to have been resolved. Please feel free to reopen it if you have any other issues.
