### ISSUE TITLE
Adaptors + computed properties = </3

### ISSUE THREAD

**Issue by suprMax** [ractivejs/ractive#1877]
Hi!

I have the following View:

````coffeescript
Ractive = require ('ractive')
require('ractive-adaptors-backbone')
UsersCollection = require('../models/users')


module.exports = class Home extends Ractive
  adapt: [ Ractive.adaptors.Backbone ]
  el: '#main'
  template: require('templates/pages/home')

  computed:
    secret: ->
      "#{@get('username')}:#{@get('password') or 'NULL'}" # fails to get second property

  onrender: ->
    @users = new UsersCollection()
    dfd = @users.fetch()

    dfd.done =>
      @set('list', @users.toJSON())

  handleClick: (item)->
    alert("Mein name ist #{item.name}")

  saveModel: ->
    console.warn JSON.stringify(@get())

  teardown: ->
    console.warn 'teardown of #home!'
    @users.destroy()
    delete @users
    super
````

It used to work fine without backbone adapter, when I was just doing `data: model.toJSON()`.

As soon as I updated that to use the adapter and passed `data: model` computed property stopped working.

I found out that if I call `@get` two times, the second call fails for some reason. A simple setTimeout(func, 0) solves this, but computed props need to return a value right away so it's not really helping.

Here's a stacktrace:

![screen shot 2015-03-26 at 2 51 51 pm](https://cloud.githubusercontent.com/assets/789031/6848868/a9baddbe-d3c7-11e4-8bb4-96d0290d9891.png)

Any ideas on how to fix? Or am I doing it the wrong way? Or maybe there's an alternative model that could be used instead of backbone one? Either solution would work for me!

**Comment by martypdx** [comment]
> `"#{@get('username')}:#{@get('password') or 'NULL'}"`

Can you post the javascript that transpiles to? As a string, would it transpile at all?

**Comment by martypdx** [comment]
Also, in vanilla js with a Ractive string computed, I assuming your trying to concat at string like `user:password`, you would write:

`secret: "( ${username} + ':' + ${password} ) || 'NULL' "`

**Comment by suprMax** [comment]
Sorry for coffeeinated source, here: `return this.get('username') + ":" + (this.get('password') || 'NULL');`

**Comment by martypdx** [comment]
But is it in a function or a string?

Both of these are valid computed props in Ractive:

```
computed: {
    secret: function(){
        return this.get('username') + ':' + this.get('password');
    }
}
```

```
computed: {
    secret: '${username} + ":" + ${password}'
    }
}
```   

See http://jsfiddle.net/9kk9pg3v/.  

Just trying to figure out if something with how the computed properties are being specified, or an issue interacting with the Backbone adaptor.

BTW - I think, but I'm not certain, that `this.get` on Backbone adaptor returns the underlying object, not the adapted object.

**Comment by suprMax** [comment]
@martypdx it's a function that returns a string. It was working fine before I introduced backbone adaptor, so I assume it's something related to how adapters work. 

Currently `this.get` works if I only request one item. For some reason it fails on multiple `get`s.

This would work:
````javascript
computed: {
    secret: function(){
        return this.get('username');
    }
}
````

Basically this raises and error:

````javascript
computed: {
    secret: function(){
        return this.get('username') + ':' + this.get('password');
    }
}
````

But this "works" (logs correct values)
````javascript
computed: {
    secret: function(){
        setTimeout(function(){ console.warn(this.get('username'), this.get('password')) }, 0);
        return 123;
    }
}
````

Also "password" is not defined on the model in the beginning, it might be related to that. E.g. `model.get('password') === undefined`.

**Comment by Madgvox** [comment]
The reason this thread was abandoned
