### ISSUE TITLE
Accessing objects keys doesn't work as expected

### ISSUE THREAD

**Issue by anton-ryzhov** [ractivejs/ractive#1878]
I've made a demo: http://jsfiddle.net/x4ehu6p9/

```js
new Ractive({
    el: 'body',
    template: '#main',
    data: {
        dict: {
            '': 'empty string',
            null: 'null value',
            undefined: 'undefinded value',
            false: 'false value',
            true: 'true value',
            
            'null': 'not null but "null"',
            'undefined': 'not undefined but "undefined"',
            'false': 'not false but "false"',
            'true': 'not true but "true"',
        },
    },
});
```

```html
<script id="main" type="text/ractive">
    
    {{ dict[''] }}, {{ dict[null] }}, {{ dict[undefined] }}, {{ dict[false] }}, {{ dict[true] }}
    <br />
    {{ dict.null }}, {{ dict.undefined }}, {{ dict.false }}, {{ dict.true }}

</script>
```

In this case it works fine for `foo.bar`. But not for `foo[bar]` — `dict[null]`, `dict[undefined]` returns nothing, `dict[false]`, `dict[true]` returns unexpected values.

And if we remove some values from dictionary, we'll have completely different result.

http://jsfiddle.net/x4ehu6p9/1/

Now `foo.bar` returns `foo['bar']` for some reason, `foo[bar]` is still broken, but in another way. `dict[null]`, `dict[undefined]` still returns nothing, but `"false"` becomes `false`. Very odd.

**Comment by mefjuu** [comment]
I've found similar problem with using stringified numbers as object key. The problem didn't occur in Ractive 0.6...

**Comment by anton-ryzhov** [comment]
@mefjuu we should separate JS and Ractive issues.

JS can't store integers as object keys, it forces it to string type. Compare with python:
```python
>>> a={1: 1, '1': '1'}
{'1': '1', 1: 1}
```

```js
> a={1: 1, '1': '1'}
{ '1': '1' }
> console.log(a[1])
1
> console.log(a['1'])
1
```

**Comment by martypdx** [comment]
Javascript coerces the key to a string value, and defining a key multiple times is valid without `'use strict';` (http://jsfiddle.net/x4ehu6p9/2/). So that's why the property values are changing in the two fiddles.

KeypathExpressions are a hybrid of valid javascript expressions and mustache resolvers. In this case they diverge from javascript in that `foo[null]` resolves (or rather doesn't resolve) to undefined. 

I don't know how useful it would be for Ractive to support having them resolve to "null" or "undefined". It seems like an edge case that you could just as well use {{foo["null"]}} or {{foo.null}}.

**Comment by anton-ryzhov** [comment]
Ok, that was my misunderstanding of this domain and dirty tests. Thank you for explanation.

But I've started this after faced with one bug. But I've made wrong conclusion about reasons.

Here is original case: http://jsfiddle.net/x4ehu6p9/3/
```js
'use strict';

new Ractive({
    el: 'body',
    template: '#main',
    data: {
        dict: {
            null: 'null value',
        },
    },
    components: {
        foo: Ractive.extend({
            template: '{{ bar }}',
        }),
    }
});
```
```html
<script id="main" type="text/ractive">
    <foo bar={{ dict[null] }} />    
</script>
```

It fails on `<foo bar={{ dict[null] }} />` but works fine `<foo bar={{ dict['null'] }} />` or `<foo bar={{ dict.null }} />`.

If you aren't supporting `dict[null]` syntax, ractive should inform about it somehow and shouldn't just fail with strange message.

**Comment by martypdx** [comment]
Ah, that's a bug for sure. The ReferenceExpression probably shouldn't call the resolved callback [here](https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/shared/Resolvers/ReferenceExpressionResolver/ReferenceExpressionResolver.js#L53) in this case.
