### ISSUE TITLE
Partial doesn't accept `.` keypath

### ISSUE THREAD

**Issue by Crisfole** [ractivejs/ractive#1880]
See reproduction here: https://jsfiddle.net/UG7Eq/12/

I get the following (well written, and self-explanatory) error:

    Expected a property name at line 3 character 17:
        <p>{{>test .}}</p>
                   ^----

**Comment by martypdx** [comment]
`{{>test this}}` works. Unless there's an expression parsing reason, I would think `.` should work as well.

**Comment by Crisfole** [comment]
Oh really? That's weird. Thanks for the workaround.

**Comment by Crisfole** [comment]
Here's an additional few tests that demonstrate the behavior that's working and that's not working.

https://github.com/Crisfole/ractive/tree/bug/1880

It also adds a tests for 'can a partial take a context?' which was missing from the tests I saw.

**Comment by Crisfole** [comment]
It looks like `readRefinements` is rejecting expressions that look like `.`.

**Comment by Crisfole** [comment]
I can't quite figure out why, but it looks like `readExpression` is trying to consume the `.` that's separated by a space from the initial expression. Is that because it's assuming that the `.` is an indexer?

**Comment by Crisfole** [comment]
So, yes, `readExpression` is assuming `.` is part of the name...apparently spaces are allowed in an expression. Is there any good reason for allowing spaces in expressions? Can you add a flag to disallow spaces in an expression (much like `relaxedNames`) that you could use in `readPartial`?

**Comment by Madgvox** [comment]
An `expression` in ractive is a very general term that includes things like `1 + 1`, `foo * bar( "baz" )`, and `foo.bar.baz[ qux ].do( "thing" )[ i ]`, so from a flexibility standpoint there are very good reasons to allow spaces in expressions.

**Comment by Crisfole** [comment]
Ah, I'd forgotten mathematical expressions. My guess, then, is that if this bug were to be fixed it'd need to be a breaking change to the "renderPartial" syntax. If the partial name can be an arbitrary expression that's not delimited by mustaches or parentheses then you'd have to write a specialized version of "readExpression" that allowed (and didn't consume) a trailing period. "readRefinement" would then work correctly.
