### ISSUE TITLE
Codemirror Plugin

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1881]
Hi,

I just wrote a little codemirror plugin for ractive:

http://dagnelies.github.io/ractive-codemirror/

...it's fairly basic, but hey, it works.

**Comment by Madgvox** [comment]
Cool! You can submit a PR over at https://github.com/ractivejs/docs.ractivejs.org/pulls to add it to the list.

**Comment by dagnelies** [comment]
done
