### ISSUE TITLE
The splice's Promise, where is data saved?

### ISSUE THREAD

**Issue by gaelicmichael** [ractivejs/ractive#1882]
I want to be able to have GUI buttons that move an item's position up and down an array of items. I realize that I need to use split with Promises, but I don't understand how this is to be done, and I can't see any examples of this.
```
		rApp.on('doLegendUp', function(event, index) {
			var myPromise = rApp.splice('theLegend', index, 1);
			myPromise.then(function() {
				rApp.splice('theLegend, index-1, 0, magicallySavedItem);
			});
		});
```
  Where does the magicallySavedItem come from?  Is this how to use the promise?

**Comment by martypdx** [comment]
Yep, it's the first argument of the promise.

```js
var r = new Ractive({
    data: {
        items: [ 'a', 'b', 'c' ]
    }
})

r.splice('items', 1, 2).then(function(spliced){
    console.log(spliced);
});
```

If you need to be synchronous, you can use the array methods:

```js
var spliced = r.get('items').splice(1, 2);
```

**Comment by gaelicmichael** [comment]
Well, that almost works. What is actually passed to the inline anonymous function (as the parameter spliced) is an array that contains the single element that was spliced. I see why this is done: any number of elements could have been removed via splice, and thus passed on.

Thanks for the help. Ractive is very impressive and powerful indeed. I intend to provide more code examples of this nature.

**Comment by martypdx** [comment]
Yes, it returns whatever the javascript array method returns. So `ractive.push('items', 'e').then(...)` would return the new length of the array for example.

But it's easy to refine semantics by creating prototype methods on Ractive:

```js
Ractive.prototype.remove = function(keypath, index){
    return this.splice(keypath, index, 1).then(function(result){
        return result[0];
    })
}

var r = new Ractive({
    data: {
        items: [ 'a', 'b', 'c' ]
    }
})

r.remove('items', 1).then(function(result){
    console.log(result); // 'b'
});
```
