### ISSUE TITLE
Need a better error when function undefined

### ISSUE THREAD

**Issue by Crisfole** [ractivejs/ractive#1883]
Right now the keypath is printed as `${undefined(parameters-my-1-first)}` (or something similar). In Debug mode I expect `undefined` to remember the original string (and probably the location, much like when you have a parse error).

**Comment by Madgvox** [comment]
Can you provide a test case?

**Comment by Crisfole** [comment]
Sure, is there an easy way to redirect the error console to someplace I can read from?

**Comment by Madgvox** [comment]
I'm just not 100% sure what you're referring to, since I can't directly reproduce what you're talking about: http://jsfiddle.net/k8fck0L7/.

In that fiddle, it displays the missing function name.

**Comment by Crisfole** [comment]
I already forget what the particular case was, it was happening like I described above...as soon as I spot it again I'll re-open with a better test case.  I think it may have been a function that was selected dynamically...

**Comment by Crisfole** [comment]
https://jsfiddle.net/k8fck0L7/1/

**Comment by Madgvox** [comment]
Related to https://github.com/ractivejs/ractive/issues/1879. Also throwing a TypeError in 0.8-edge.
