### ISSUE TITLE
a problem about set on undefined variable

### ISSUE THREAD

**Issue by simongfxu** [ractivejs/ractive#1884]
as i know, when update an item's property in an array, we'd like to code like this:

    app.set('items.' + index + '.checked', false)

when `index` is -1, `items` is undefined. we will create `items` as a object with a property `-1`, that is ok to me.

and then i update items to an array, and weird thing happened - i `lost` the first item in this array.

`lost` means we can get it in javascript code, but you cant see it in the view model.

my sample code is  here.[http://jsbin.com/fohepu/2/](http://jsbin.com/fohepu/2/)

**Comment by MartinKolarik** [comment]
Looks like this is fixed in edge.
