### ISSUE TITLE
A way to get data state in JSON format?

### ISSUE THREAD

**Issue by suprMax** [ractivejs/ractive#1886]
Hallo!

I'm trying to tie together Ractive with a Backbone Model.

Since the adaptor doesn't really work that well: https://github.com/ractivejs/ractive/issues/1877, I passed a JSON object to the Ractive instance instead (model.toJSON()). 

I have a form on the page that updates some data. I need to get that changed data back to set on a model and call model.save()

If I simply call `ractive.get()` it returns entire template context with additionally set properties, helpers and everything else. Is there a way to get simple JSON without all the clutter?

As if this moment I have to do the following:

```
data = {}
    for input in @$inputs
      data[input.name] = input.value

    @fire('submit', data)

```

That's a bit tedious to do all the time and kind-of defeats the purpose of having ractive in the first place...

**Comment by martypdx** [comment]
Use a key on the data object to isolate your model

```js
data: {
    myModel: json
}

ractive.get('myModel')

**Comment by suprMax** [comment]
But then I'll have to prefix everything in the view with `myModel.`

Oh :(

**Comment by martypdx** [comment]
> But then I'll have to prefix everything in the view with myModel.

```html
{{#with myModel}}

<!-- no prefixes needed here -->

{{/with}}
```

**Comment by suprMax** [comment]
legit! thanks @martypdx
