### ISSUE TITLE
CDN SSL issues

### ISSUE THREAD

**Issue by ahmadnassri** [ractivejs/ractive#1888]
attempting to use the Ractive CDN url, but its not SSL friendly ... 

> This server could not prove that it is cdn.ractivejs.org; its security certificate is from www.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

suggest using Cloudflare (as they provide both caching and free SSL) and putting it infront of the github (gh-pages) published files.

**Comment by Rich-Harris** [comment]
We did use Cloudflare until recently, and that was one of the reasons. I broke it when I redesigned [examples.ractivejs.org](http://examples.ractivejs.org/) as a node app instead of a static site, because it's now hosted on DigitalOcean, which meant that all of ractivejs.org had to use DO's nameservers instead of Cloudflare's.

There's almost certainly a way to put Cloudflare in front of the cdn subdomain while continuing to use DO's nameservers for the examples subdomain (and possibly all the others), but I haven't had time to figure that out (if anybody knows how to fix it, please help!)

In the meantime, if you need a production grade CDN with SSL support, I recommend cdnjs: http://cdnjs.com/libraries/ractive

**Comment by Nijikokun** [comment]
> In the meantime, if you need a production grade CDN with SSL support, I recommend cdnjs: http://cdnjs.com/libraries/ractive

This doesn't work properly for some unknown reason.

**Comment by Madgvox** [comment]
Which one were you using?

**Comment by ahmadnassri** [comment]
@Nijikokun doing a diff between the cdnjs one and cdn.ractivejs on, seems to be identical, so the problem is most likely somewhere else ... though somehow connected to the change ...

@Madgvox `0.5.8`

@Rich-Harris one way could be to keep the original domain on cloudflare, and use an alternative domain underneath (CNAME) for DO ... something along the lines of:

```
[CloudFlare](ractivejs.org)
  |
  +----> examples.ractivejs.org [CNAME] --> ractiveexamples.org [DO]
```

**Comment by Madgvox** [comment]
Oh, sorry @ahmadnassri, my question was referring to @Nijikokun's post. I should have made that more clear.

That said, your comment makes sense -- I doubt that @Nijikokun's issue is directly caused by an issue with the cdn file.

**Comment by ahmadnassri** [comment]
@Madgvox we actually work togethrer, the issue @nijikokun mentioned is the same I was referring to :)

**Comment by Madgvox** [comment]
Oh! Well. Never mind then.

**Comment by jimaek** [comment]
How about using [jsDelivr](https://github.com/jsdelivr/jsdelivr)? [More information](https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/)

* We support HTTPS + SPDY
* Great performance and uptime [Reporting](http://www.cedexis.com/reports/#?report=cdn_response_time&country=US&date=2015-07-04)
* Version aliasing and combination of files in a single HTTP request [Docs](https://github.com/jsdelivr/jsdelivr#version-aliasing)
* Public reporting on hits for each project is coming soon
* Auto-updating by out bot once you tag a new version in your repo

Example http://cdn.jsdelivr.net/ractive/0.7.3/ractive.min.js or http://cdn.jsdelivr.net/ractive/latest/ractive.min.js

For EDGE you could continue using cdn.ractivejs.org (or even better maybe rename it to edge.ractivejs.org to make it clear that its not production ready)

**Comment by MartinKolarik** [comment]
:+1: for using jsDelivr as the official CDN. It's rock-solid and requires no additional setup, plus the on the fly file combination is really awesome.

**Comment by evs-chris** [comment]
jsdelivr picks up production release, and unpkg picks up anything published to npm, so I'm calling this handled.
