### ISSUE TITLE
Option in select input losses selected attribute

### ISSUE THREAD

**Issue by Isinlor** [ractivejs/ractive#1891]
I have an select input on witch value I observe for changes to be able to save them. I have a problem when the only one option is available. That option is preselected by the browser without triggering change event. In that case user have no way to trigger change event and therefore value is not saved. I solved this problem by adding one selected and disabled option by default. Then user have to update input explicitly and I'm able to save it. Example in fiddle: http://jsfiddle.net/v0gkuokc/6/

The issue is that the option rendered by ractive.js losses selected attribute and because of that user once again have no way to trigger save.

**Comment by martypdx** [comment]
Took me a minute figure it out, but I think you're right. If the first item is explicitly marked as `selected` and there's no data binding value, it should select that one even if disabled.

**Comment by Madgvox** [comment]
The fiddle in OP works as of 0.8-edge.
