### ISSUE TITLE
Better error message when template is null

### ISSUE THREAD

**Issue by Skyrpex** [ractivejs/ractive#1893]
I've accidentally used a null template without noticing, and the error message was kinda criptic:

```
TypeError: Cannot read property 'v' of null
```

I've made [a fiddle](http://jsfiddle.net/tv25b9Lk/) just to see it in action.

IMO, it would be nice to have an specialized error message for falsy templates. What do you think?

**Comment by Madgvox** [comment]
Looks like ractive is looking for a version number (`v`) in the template without checking to make sure the template exists at all first.

**Comment by Skyrpex** [comment]
Exactly. Thank you for the pull request, @Madgvox
