### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1897]
Via the [mailing list](https://groups.google.com/forum/#!topic/ractive-js/Uf8Y0VEk2FI): the [mustache-security](https://code.google.com/p/mustache-security/) project does research into potential XSS vulnerabilities in various front end frameworks. [Here's the report for Ractive.](https://code.google.com/p/mustache-security/wiki/RactiveJS).

They use the following qualifiers:
- **{}SEC-A** Are template expressions executed without using eval or Function? (yes = pass)
- **{}SEC-B** Is the the execution scope well isolated or sand-boxed? (yes = pass)
- **{}SEC-C** Can only script elements serve as template containers? (yes = pass)
- **{}SEC-D** Does the framework allow, encourage or even enforce separation of code and content? (yes = pass)
- **{}SEC-E** Does the framework maintainer have a security response program? (yes = pass)
- **{}SEC-F** Does the Framework allow or encourage safe CSP rules to be used (yes = pass)

I'll address each in turn.
### {}SEC-A

Currently, expressions are parsed into a compact AST, but then 'flattened' to a string representation (e.g. `{{a+b}}` and `{{c  +  d}}` both get represented as `_0+_1`) which is turned into a function with `new Function(...)`. This is both fewer bytes to send down the wire (if templates are precompiled), and is most likely more performant than the alternative.

But the alternative (preserving the AST, and evaluating the expression without code generation) does exist. It might be worth doing some research into the performance implications (and seeing how much code it would take).
### {}SEC-B

Functions run in the global context, but only a [subset](https://github.com/ractivejs/ractive/blob/7b8d9bf7cff9201dae64a00817bbf8e5039296a9/src/parse/converters/expressions/primary/readReference.js#L9) of built-ins can be used within an expression. An attacker could do `window.Math = somethingNaughty` and we would have no protection. We could mitigate that _slightly_ by storing references to those globals when Ractive first executes, and somehow using those instead of the (potentially compromised) globals, but that's no protection against them being compromised _before_ Ractive loads.

Maybe we could have a `ractive-secure.js` version for the ultra-paranoid that included our own implementations of those globals, and banned the ones we can't implement ourselves.
### {}SEC-C

We get a fail for that in the report, though more recent versions of Ractive _do_ only allow script elements to contain templates.
### {}SEC-D

Personally I feel this is a misguided goal, and I'm not sure where you're supposed to draw the line between 'code' and 'content' in a declarative paradigm.
### {}SEC-E

~~Guilty as charged. We should perhaps offer some guidelines on README.md or CONTRIBUTING.md for people who want to report security vulnerabilities.~~

_guidelines for reporting security vulnerabilities now displayed in README and CONTRIBUTING files_
### {}SEC-F

As far as I know, it's only the use of `new Function` that prevents us from being CSP-compliant. See the section above on **{}SEC-A**.
---

Having said all that, I'm not totally clear on what the actual risks are here (beyond what you can already do via the console, since expressions are evaluated in the global scope) unless your template comes from an untrusted source (which would seem to fall under 'user error'). Can someone enlighten me?

**Comment by JoshuaWise** [comment]
I believe {}SEC-D refers to the vulnerabilities that exist if an attacker were to gain access to the HTML document *before* Ractive loads (they could add their own mustaches to retrieve otherwise-private data). However, because templates can be parsed on the server now (the test was done on Ractive 0.4.0), this vulnerability can be avoided.

**Comment by JoshuaWise** [comment]
`{}SEC-E` is obviously the most important, but fairly straightforward to solve.
Besides that one, `{}SEC-A` and `{}SEC-B` seem to be the only unavoidable faults. I believe that `{}SEC-B` could only ever pass if `{}SEC-A` passes, so that should be the first problem to look at. I'm fairly certain that Angular.js passes `{}SEC-A`, so you could look there for inspiration.

Take a look at [this](http://www.slideshare.net/x00mario/es6-en) to see why blacklist-based validation is effectively useless in terms of security on the web.

**Comment by evs-chris** [comment]
Security is not one the trades of which I consider myself a jack, but I'm with @Rich-Harris in that I don't really see how most of those aren't at least somewhat inherently necessary for this type of library.

Having written an interpreter or two (lisps in scala and c#, because any sufficiently complex program will contain an ad-hoc, slow, bug-ridden implementation of half of common lisp), I can say that it's probably more code weight than we would like. It's also not what I'd call "fast" for hot code paths.

According to the grid on the main page, Angular and Ember both pass B and fail A. I'm not sure exactly how they managed that, as my eyes tend to glaze over when I start trying to comprehend Angular code and I've never really visited Ember.

**Comment by Rich-Harris** [comment]
I raised #1900 in reference to E - I don't know if it amounts to a 'security response program' but it's something.

Ember passes B because it doesn't support logic in templates at all - instead there's a (slightly convoluted, IMHO) approach using 'helpers'. By coincidence a link to [this screencast](http://www.emberscreencasts.com/posts/24-handlebars-subexpressions) just landed in my inbox, showing how you'd do something like an equality check:

```html
{{#if (es-equal hatColor 'blue')}}
  "What a lovely hat!"
{{else}}
  "Have you no taste?"
{{/if}}
```

This works because you register a helper that supplies the logic:

```js
Handlebars.registerHelper( 'es-equal', function ( arg1, arg2 ) {
  return arg1 === arg2;
});
```

Now it seems to me that Ractive could do something similar to what I assume (without looking at the code) Angular does, which is to essentially register similar helpers for every possible JavaScript expression.

So if you had

```js
{{#if hatColor === blue}}
  ...
{{/if}}
```

you'd get an intermediate representation like this (this is what parsed expressions look like before they get 'flattened'):

```js
expression = {
  t: 36,
  s: "===",
  o: [
    {
      t: 30,
      n: "hatColor"
    },
    {
      t: 21,
      v: "blue"
    }
  ]
}
```

If we then call `evaluate(expression)`, Ractive finds the function for `t: 36 // s: ===` (however we choose to represent that), which looks something like this:

```js
// our version of the 'helper' above
function tripleEquals( node ) {
  return evaluate( node[0] ) === evaluate( node[1] );
}
```

The left hand side looks for the function for `t: 30`, which queries the viewmodel for the value of whatever `hatColor` resolves to, while the right hand side looks for the function for `t: 21`:

```js
function getLiteralValue ( node ) {
  return node.v;
}
```

So it seems to be that the hard work is already done - we could probably get there in ~100 lines, with no `eval` or `Function` in sight. Though I've been optimistic about this sort of thing before, and I hereby grant @evs-chris full 'I told you so' rights.

(Incidentally, I assume Ember fails A because Handlebars, in common with most string templating systems, uses code generation to compile template strings. Their next-gen HTMLBars system may be different in that regard - not sure.)

My belief then is that B falls under 'tricky but doable' and D falls under 'depends what you mean?', but all the others *should* be possible for us to pass.

**Comment by martypdx** [comment]
I'm going to totally profess my ignorance and admit I don't understand how `<div id="test">{{1..constructor.constructor("alert(1)")()}}</div>` is ending up in the template. Can someone explain the series of events by which a malicious third party is putting that into the mix?

That being said, if we're throwing around ideas to avoid using `eval` or `new Function()`, how about a security mode for the parser that generates a separate js file with all of the expression functions:

```
var safe = [
    "0": function(_0, _1) { return _0 === _1; },
    "1": function(_0, _1, _2) { return _0(_1, _2); }
]

expression = {
  t: 36,
  s: "0",
  o: [
    {
      t: 30,
      n: "hatColor"
    },
    {
      t: 21,
      v: "blue"
    }
  ]
}
```

**Comment by fskreuz** [comment]
How about putting in `Ractive.helpers` (ala Handlebars) to put in custom helpers, and migrate the existing helpers to this scheme. (just throwing in ideas).

**Comment by MartinKolarik** [comment]
>That being said, if we're throwing around ideas to avoid using eval or new Function(), how about a security mode for the parser that generates a separate js file with all of the expression functions

@martypdx Ha, I was just about to suggest that!

As for B, I think I'd be enough to let people specify a list of available globals.

I was also thinking about an option that would completely disallow any expressions in templates.

**Comment by Rich-Harris** [comment]
> Can someone explain the series of events by which a malicious third party is putting that into the mix?

A Chrome extension that rewrites the contents of `<script>` tags maybe? The part that confuses me is what extra powers an attacker hopes to gain by doing so - if they're capable of doing that then surely the app is already screwed.

I suppose if you were building an app that rendered templates supplied by other untrusted users, you could [end up in hot water](http://examples.ractivejs.org/7866bf15b8e3a7c4a0a0), particularly if you were careless enough to leave important stuff lying around in the global namespace (though that [won't stop a half-decent attacker](http://jsfiddle.net/rich_harris/33xgL6k0/)). 

> a separate js file with all of the expression functions

Each template would have its own set of helpers, which would need to get wired up somehow... and you'd presumably need to be able to generate a variety of different module formats to cover everyone's situation. Seems like it'd be hard to do without generating a lot of clutter and confusion. Even then, it wouldn't help in the case that parsing is done client-side (since dynamically generated script tags are forbidden by CSP). I reckon we should try doing it without any code generation first and see what the performance is like. Another benefit to the no-code-generation thing - presumably it'd be a lot easier to neuter attacks like the one above:

```js
function evaluate ( node ) {
  const evaluator = evaluators[ node.t ];
  const value = evaluator( node );

  if ( value === Function ) throw new Error( 'Nice try!' );
  return value;
}
```

> How about putting in `Ractive.helpers` (ala Handlebars) to put in custom helpers

Personally I'd prefer to avoid that - I think it's an unhappy developer experience, particularly when you're doing something trivial like making a list index one-based rather than zero-based, and it makes templates a lot harder to read. If we can solve the problem at a fundamental level then we won't have to inflict that on anyone.

> I was also thinking about an option that would completely disallow any expressions in templates.

That would actually be pretty straightforward to implement, and would eliminate pretty much the entire attack surface area. Suggested API...

```js
Ractive.parse( templateOfDubiousOrigin, {
  paranoid: true // :-)
});
```

**Comment by Madgvox** [comment]
`paranoid: true` :+1:

**Comment by MartinKolarik** [comment]
>Each template would have its own set of helpers, which would need to get wired up somehow... and you'd presumably need to be able to generate a variety of different module formats to cover everyone's situation

Now I realized that my idea was a little different from @martypdx's. I wanted to suggest returning an object that contains all functions. After that, you could use @marcello3d's [tosource](https://github.com/marcello3d/node-tosource) and treat it like any other preparsed template. Obviously, it would require preparsing all templates, but I think that's OK.

>Another benefit to the no-code-generation thing - presumably it'd be a lot easier to neuter attacks like the one above

That's probably true.

**Comment by MartinKolarik** [comment]
>Can someone explain the series of events by which a malicious third party is putting that into the mix?

Suppose an attacker can inject any HTML they like into your website (because there's a vulnerability in your app). You use CSP, which means they can't load scripts from other domains and inline scripts are ignored; there's basically no way for the attacker to execute malicious code.

However, if they can either change an existing template, or trick Ractive into using a fake template... See http://jsfiddle.net/e7d5tu1q/ for a super-simple example.

**Comment by guilhermeaiolfi** [comment]
I don't get it too. If the attacker can inject any HTML in your app, why would he use ractive templates to execute his code? Why wouldn't he just put the code he wants there?

**Comment by MartinKolarik** [comment]
@guilhermeaiolfi 

>You use CSP, which means they can't load scripts from other domains and inline scripts are ignored.

See http://en.wikipedia.org/wiki/Content_Security_Policy#Mode_of_operation

**Comment by martypdx** [comment]
> Now I realized that my idea was a little different from @martypdx's. I wanted to suggest returning an object that contains all functions. After that, you could use @marcello3d's tosource and treat it like any other preparsed template. Obviously, it would require preparsing all templates, but I think that's OK.

@MartinKolarik That's more or less what I was suggesting too. Now that I think about it, there's no reason not to put them in the template itself (I haven't seen anyone using them as JSON and not as object literals). 

I do like the current feature of sharing same structure compiled expressions, which is why I was seeing a list of functions and then a key inline in the templates:

```js
{
  v: 3, /* Template spec version */
  t: [  {
      t: 36,
      s: "f1",
      o: [
        {
          t: 30,
         n: "hatColor"
        },
        {
          t: 21,
          v: "blue"
        }
      ]
  }],
  p: {  /* Optional hash of partials */
    foo: [ /* items in the 'foo' partial */ ]
  },
  f: {
     f1: function(_0,_1){return _0===_1;},
     f2: function(){...}
  }
}

> I reckon we should try doing it without any code generation first and see what the performance is like. 

@Rich-Harris Well we already have the code to do the code generation in the current expressions. But  seems like the kind library you'd like to write and I know it will have a cool name. :)  

My guess is that the performance will be better than constructing a function. Whatever direction we take, we should considering moving as much into parsing as we can.

> How about putting in Ractive.helpers (ala Handlebars) to put in custom helpers, and migrate the existing helpers to this scheme. (just throwing in ideas).

Block helpers might be nice for hackability, but as a pre or post parse time feature, not the DOM-level ability that handlebars has (at least as I remembers it):

```html
<h1>My great template</h1>

{{#markdown}}
# {{tile}}
How about `{{subject}}`?
{{/markdown}}
```

**Comment by Rich-Harris** [comment]
I thought it'd be worth bringing some real numbers into the equation, since performance is one of the factors here: https://gist.github.com/Rich-Harris/f3d63e4ef4d6680d3052

To cut a long story short, a function created without `new Function(...)` runs about ~4.5x slower, in the example I've chosen (simple addition). Not ideal, but far from catastrophic, and certainly not bottleneck territory unless you're doing something rather inadvisable - at the very least, an acceptable fallback for people who don't want to precompile stuff for whatever reason.

> But seems like the kind library you'd like to write and I know it will have a cool name. :)

My train of thought: 'a library that evaluates things... evaluates... judges? Judges their value? Sounds biblical. St. Peter? He judges the value of people, that's kind of his thing. Hmm, I wonder if 'peter' is available.'

Alas, [peter is already taken](https://www.npmjs.com/package/peter). I miss the good old days when squatting meant buying cocacola.com and waiting to become rich.

Anyway, the AST format Ractive uses is totally bespoke, so it probably wouldn't have much utility as a separate thing!

**Comment by fskreuz** [comment]
Just throwing it in since someone opened up the issue about Chrome Apps and I thought it was an extreme edge case for one to use Ractive in a non-browser, non-server environment.

Ractive and rvc also doesn't run in FirefoxOS due to CSP (It's reasonable. You wouldn't want stray JS to run around the phone). CSP set on apps are [defined here](https://developer.mozilla.org/en-US/Apps/Build/Building_apps_for_Firefox_OS/CSP#Default_Policies) and the twist is that you can't make them less strict than they are. Ractive fails because of `new Function()` while rvc fails because it uses `eval` somewhere in the code.

**Comment by mikemaccana** [comment]
Following as I've just released https://www.npmjs.com/package/csp-by-api which includes a policy for ractive, currently using `unsafe-eval`.

**Comment by evs-chris** [comment]
We have csp compatibility by default in 0.8 for pre-parsed templates, so I'm going to call this as as close as we can get without turning into something else :smile:
