### ISSUE TITLE
build folder should have README

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1899]
otherwise [this](https://www.npmjs.com/package/ractive) happens:

![screen shot 2015-04-02 at 2 29 12 pm](https://cloud.githubusercontent.com/assets/1162160/6970638/b9e8ec4e-d944-11e4-9207-2ba1889c315c.png)

Doesn't necessarily have to be the same as the main README, since npm users (and others who just want the build) don't care about e.g. the 'developing and building' section

**Comment by evs-chris** [comment]
Took the easy path and copied the regular readme to build, but it is there henceforth :smile:
