### ISSUE TITLE
Slightly more detailed lifecycle event documentation requested

### ISSUE THREAD

**Issue by Crisfole** [ractivejs/ractive#1902]
Could the documentation be updated to include a little more detail on when the el is created/added, etc? For `init` through `teardown` it's very unclear to me when the document fragment is inserted into the DOM, when I can get an accurate measure of an element's size, etc.

For example: if I wanted to create a select2 component instead of a select2 decorator, when should I call `$.destroy` on the element? `teardown` or `unrender`? How about when can I safely attach, knowing that the size can be read by select2 for deciding width stuff? `render` or `complete`?

Just trying to get a better idea of how the lifecycle works.

**Comment by Madgvox** [comment]
Perhaps it's just that I've worked with lifecycle events a lot, but I'm not entirely sure where you're missing information. Most of the lifecycle events are tied to other function calls, such as the `insert` event and the `ractive.insert` function. For example, if you're confused as to what `unrender` does in comparison to `teardown`, check out the [unrender](docs.ractivejs.org/latest/ractive-unrender) and [teardown](http://docs.ractivejs.org/latest/ractive-teardown) docs, respectively.

To address your specific concerns, `render` is the event called when the fragment has been rendered i.e. inserted into the DOM. It's at this point when you can safely retrieve size measurements. `complete` is fired when all transitions finish animating. When components are removed from the DOM by ractive, they're torn down, so for a select2 component, your best bet is to put the `destroy` in the `teardown` event.
