### ISSUE TITLE
Disable two-way binding for subtree

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1903]
Would it make sense if disabling `twoway` for a parent component would also disable all descendants from doing two-way binding? Or disabling it for a parent would stop mutations only up to the parent and not beyond?

Take for instance this example: https://jsfiddle.net/gyt9s0d8/2/ Say `Child` was from another developer. I want to use his component on `Parent`, but I have two-way disabled for everything. So I'd expect that the data isn't two-way since I disabled it on `Parent` (and by encapsulation, I should not bother how `Child` was implemented). But then, I found out that `Child` is mutating the data because two-way isn't disabled on it. (throws notebook out the window) (flips table) (pulls hair)

So feature request, I was expecting disabling 2-way on my component would either

1. Disable two-way on the entire subtree. This means 2-way on any descendant component will cease to work starting with `Parent` downwards. This would probably break stuff.

2. Disable two-way *only up only the component with a `two-way:false`*. This could mean `Child` could still do two-way, `Parent` can still two-way, but if `Parent` is a component inside `Ancestor`, then the mutations only stop at `Parent`. Any data passed by `Ancestor` will not mutate as a result of two-way by `Parent` and below.

I'm not sure if it's feasible, I'm open to ideas. But it's shocking that one component very deep in the tree with 2-way enabled breaks the entire tree of components doing one-way. I already considered static delimiters, but I wanted to keep "one-way binding" where I set the data on the root component and changes trickle down the descendants.

**Comment by Madgvox** [comment]
You can for the most part achieve option 1 by setting `Ractive.defaults.twoway = false;`, unless the component in question explicitly sets it to true. As you said, this has a high potential for breaking things.

As for option two, I think it would be interesting to enable the ability to add an attribute on the component element itself that disabled two-way binding for data out of that component, just like an input.

```js
<component value='{{value}}' twoway='false'/>
```

**Comment by martypdx** [comment]
> I want to use his component on Parent, but I have two-way disabled for everything. So I'd expect that the data isn't two-way since I disabled it on Parent (and by encapsulation, I should not bother how Child was implemented). But then, I found out that Child is mutating the data because two-way isn't disabled on it. (throws notebook out the window) (flips table) (pulls hair)

IMO, you've got things backwards. It breaks encapsulation if the parent setting changes the component. That `Child` component was authored with the intention that ractive's two-way binding would be the mechanism by which data in the input controls would be propagated to the viewmodel. How do you know turning it off doesn't break the component?

**Comment by martypdx** [comment]
@fskreuz I don't mean to say your concern isn't valid, it's an important one if we're ever going to have a robust offering of community plugins.

In this case, it seems the concept of "how does a component leverage binding of it's owned elements" has been conflated with "how does a component communicate data updates to the view hierarchy in which it is participating" (Another confusing point are the two dimensions of hierarchy in Ractive: inheritance hierarchy, `Ractive.extend` and a parent/child view hierarchy.) 

Take this simple contrived example of a TitleEditor component:

```html
<input value='{{title}}'>
<input value='{{color}}'>
Preview: <span style='color: {{color}};'>{{title}}</span>
```

The preview should reflect "live" changes, but ideally the component should be usable both in a way that external propagation was live and delayed by event or some other trigger. And that goes beyond the blur of any single input.

I don't have any answers, just wanted to explain that I understand where you're coming from. But you've hit on a deeper issue than just controlling how `twoway` gets propagated.

**Comment by Madgvox** [comment]
@fskreuz I'm actually curious as to the use case you're looking at for this behavior. @martypdx brought up a couple of good points as to the nature of parent/child bindings, and while I believe there is a place for components that are only dictated to, and do not dictate, I'd like to know 1) what the reason is that you disabled two-way binding app-wide and 2) what kind of components you are expecting (i.e. if you don't want to enable two-way binding between parent/child, then the kind of components you're looking at are basically just components that you dictate settings to and that's it.)

**Comment by fskreuz** [comment]
@martypdx @Madgvox Ahh, sorry for the late reply (fell asleep) :D

A separate layer controls the data, separate from the components ("stores" in React speak). We're avoiding two-way binding for finer control of changes and avoid mutations where there shouldn't be (especially that layer).

Some of our components are built this way ("top-level component" in React speak), while some are built like HTML elements like custom inputs and textareas (where pressing keys updates its `value` immediately, etc.). It's the merging of the 2 kinds that's tricky.

The `Child` in our case is a two-way bound component by default (like `<input>`). We can avoid 2-way in `Parent` because the component is also designed with events + getters, similar to your normal input. So instead of feeding a value to the component and mutate that value, we can opt to do something similar to say `onkeyup + input.value` (or more specifically `on-keyup + componeng.get('value')`. 

This works for getting data off the component. Setting data to the component is another story as it is fed through attributes. This means that a value from `Parent` model is passed to `Child`, which means the model of `Parent` is now open for mutation by `Child`. The mutations don't go through the `event+getter` and instead directly mutate the data.

**Comment by Madgvox** [comment]
Would it be possible to pass a `temp` version of the data to components with an observer attached, so that data coming out of the component passes through the observer, and then you can sanitize the data and do what-have-you to it before saving the changes to the 'store'?

```html
<component value='{{temp.value}}' />
```

```js
ractive.observe( 'temp.value', function( n, o, k ) {
  this.set( 'value', n );
});
```

Additionally, you could set up a computed value for the data, which would act the same as your manually created getters and setters except data passing through components would also activate them.

```html
<component value='{{sanitizedValue}}' />
```

```js
var ractive = new Ractive({
  // ...
  computed: {
    sanitizedValue: {
      get: '${value}',
      set: function( value ) { /* whatever validation you need */ }
    }
  }
});
```

**Comment by fskreuz** [comment]
@Madgvox Interesting approach :D Will try that out.

**Comment by fskreuz** [comment]
@Madgvox It actually works \o/. But I'll keep this issue open as you guys might consider the feature. I'll also keep posted on how the approach holds up.

**Comment by Madgvox** [comment]
I'm going to close this for now as I consider the issue resolved. I doubt that there's a massive use case at this point for something like non-two-way components, especially since the existing methods seem to have worked out for you. Feel free to post any updates to this thread or reopen the issue if the problem resurfaces.

**Comment by fskreuz** [comment]
@Madgvox oki doki. Thanks! :D
