### ISSUE TITLE
merge() on Hashmaps

### ISSUE THREAD

**Issue by StritziK** [ractivejs/ractive#1907]
Please correct me if I'm wrong but I didn't find a good way to perform a merge of two hashmaps.
I have for example two hashmaps with different users:

``` javascript
Ractive.get('users') // returns something like { 'user_1': {...}, 'user_2': {...},  'user_3': {...} }
var newUsers = { 'user_4': {...}, 'user_5': {...},  'user_6': {...} };
```

It would be nice if there would be a support for:

``` javascript
Ractive.merge('users', newUsers, true)
```

-> http://jsfiddle.net/ayc8h9b0/
Currently with this approach nothing happens...
Is there an actual solution I am missing, except doing it with Ractive.set() and overwrite all Users which triggers rerendering of the whole userlist ...

**Comment by martypdx** [comment]
Not currently supported, through an interesting idea - there seems to be increasing requests for dealing with hashmaps.

The merge function _replaces_ the existing array with the new array while reusing any surviving members. In this case don't you want to append the keys as well as replace?

In any case, you can add your own function to `Ractive.prototype`, for example (see http://jsfiddle.net/zbanyr3p/):

```js
Ractive.prototype.mergeHash = function(keypath, hash){
    var obj = this.get(keypath), key;
    for(key in hash){
        if ( hash.hasOwnProperty(key) ) {
            obj[key] = hash[key];
        }
    }
    this.update(keypath);
};
```

> which triggers rerendering of the whole userlist

Take a look at the nodes in the example, Ractive reuses them. :)

**Comment by evs-chris** [comment]
`merge` on a hashmap is effectively a deep set, and that is now implemented in edge.
