### ISSUE TITLE
Update docs that currently use the depricated init option

### ISSUE THREAD

**Issue by webdesserts** [ractivejs/ractive#1917]
As mentioned [on stackflow](http://stackoverflow.com/questions/29596991/onrender-vs-init-in-ractive-js/29606409#29606409), I ran into a few parts of the docs that still used the old `init` option over the new `onrender` option. I did a quick search through the docs and the following pages. Most of these are directly related to components.

- [options](http://docs.ractivejs.org/latest/options) (under components)
- [partials](http://docs.ractivejs.org/latest/partials)
- [components](http://docs.ractivejs.org/latest/components)
- [Ractive.extend()](http://docs.ractivejs.org/latest/ractive-extend)

**Comment by Madgvox** [comment]
I've crossposted this to the [docs repo](https://github.com/ractivejs/docs.ractivejs.org/issues/204), so I'm going to close the issue here.
