### ISSUE TITLE
Checkbox is not set when event bubble is canceled.

### ISSUE THREAD

**Issue by donnyv** [ractivejs/ractive#1921]
I may be wrong but when you cancel an event bubble isn't it suppose to complete the current and then stop? The check box doesn't get rendered when you cancel the event bubble.

https://jsfiddle.net/DonnyV/0954hwwo/5/

**Comment by Madgvox** [comment]
In an event, returning false tells ractive to `stopPropagation` AND `preventDefault`. In the case of the checkbox, this prevents it from becoming checked. Placing `event.original.stopPropagation()` in the event instead of `return false` provides the behavior you're describing.

From the docs:

> Note that returning `false` has a dual purpose of both cancelling the view hierarchy event bubbling and cancelling the DOM Event if the event was DOM-based.

**Comment by donnyv** [comment]
I see...thanks!!!
