### ISSUE TITLE
Two-way false, set doesn't sync data with input

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1922]
http://jsbin.com/jabirokuvu/1/edit?html,js,output

Template
```
<script type="text/template" id="test">
    {{foo}}
    <input type="text" value="{{foo}}" on-keyup="test()" />
</script>
```

JS
```
var foo = new Ractive({
    twoway: false,
    el: 'body',
    append: true,
    template: '#test',
    data: {
        // This is blank to begin with
        foo: '',
    },
    test: function(){
      // Let's say we did validation, stripped invalid characters and got ourselves a blank.
      this.set('foo', '');

      // Oh, it won't be marked "dirty" because it's still blank. Let's update for force the UI.
      this.update();
      
      // The input still has the same value??? Not blank?? D:
    }
});
```

So let's say i have an input, that when the user inputs, passes through a validator in the data layer. The data layer then does some validation (like stripping of characters etc.) then returns the stripped value to the component.

Now, there will be times when the validation will just strip everything off leaving me with a blank string, and the component starts off with a blank string. Ractive seems to dismiss this as not dirty since it's blank to begin with and blank after, *but the input already has a value*. So I resort to force the UI with `update` but then, nothing happens.

Are there any workarounds or recommendations for this? I was expecting `set` to do refresh the UI or at least the input be in sync on every `set`.

**Comment by Madgvox** [comment]
I would manually reset the input field after updating the value:

```js
// ...
test: function () {
  this.set( 'foo', '' );
  this.event.node.value = this.get( 'foo' );
}
```

Another workaround would be to set foo to a placeholder and then immediately set it to your desired value, but that's a bit messy IMO:

```js
// ...
test: function () {
  this.set( 'foo', 'bar' );
  this.set( 'foo', '' );
}
```

**Comment by dagnelies** [comment]
While I agree that `this.set('foo', '')` shouldn't update of the field because the value is unchanged, I that `this.update()` being ineffective looks like a bug.

**Comment by Madgvox** [comment]
`this.update()` not doing anything isn't a bug because the ractive model wasn't changed. The text that is entered into the input when two-way is disabled is invisible to ractive. `this.update()` checks to see if any values in the data have changed since it last checked. No data values were changed, so no update. The only way for ractive to know that the value of the input does not equal the value of `foo` is if it's keeping track of it. For that, a two-way binding is required.
