### ISSUE TITLE
Wildcard observers are notified for each character in strings

### ISSUE THREAD

**Issue by frenchroasted** [ractivejs/ractive#1923]
If I create observers on a property, not knowing in advance what data type the value will be, I may create "propName.*" style observers. If propName ends up with a string value, every time this value changes, the notify observers process executes for each and every character in the string. If the string is large, this can be very performance intensive. In particular, I see the function "updateMatchingPatternObservers" being called with keypaths like propName[0], propName[1], etc., and the values of those keypaths are, for example, 'H', 'e', 'l', 'l', 'o'.

Perhaps the observer wildcard handler could be more picky about what data types are worth the application of an iterator (arrays and objects, for example, but not strings, numbers, etc.).

(Ractive version: 0.7.1)

**Comment by martypdx** [comment]
I think that makes sense.
