### ISSUE TITLE
sharing data between ractive instances

### ISSUE THREAD

**Issue by timoxley** [ractivejs/ractive#1925]
A pattern I used in ractive 0.6 would be to pass `this.data` to child components rendered inside a shadow root so they behave as if they were simply rendered inside the parent component.

This no longer works in ractive 0.7. Not sure what I can do short of manually setting up an observer for each property and binding the data myself.

Examples:
* Ractive 0.6: http://jsfiddle.net/uyju2h0b/2/
* Ractive 0.7: http://jsfiddle.net/0xwsco5o/1/

**Comment by arxpoetica** [comment]
@timoxley `this.data` is an anti-pattern, and is no longer exposed to Ractive instances. ([See the first item under “Breaking Changes” on `0.7.0`](https://github.com/ractivejs/ractive/blob/dev/CHANGELOG.md#070).) As it says in the change set,

> Use `ractive.get()` and `ractive.set()` rather than accessing data directly

As for passing data in this matter, Ractive has a built in `isolated` option on instantiation which defaults to `false`: http://docs.ractivejs.org/latest/options#isolated. This means any parent data is (by default) available to the child, unless the child has variables of the same name.

Why were you explicitly passing the data?

**Comment by Madgvox** [comment]
@timoxley As it has been over a month since you responded to this thread, I'm going to assume this issue has been resolved and mark it closed. If you have any more questions / concerns, feel free to reopen the issue at any time.
