### ISSUE TITLE
Force using a function as data, and change how reset works

### ISSUE THREAD

**Issue by Skyrpex** [ractivejs/ractive#1928]
I think it could be useful to force users to use a function as data (even when just creating a ractive instance) and use this function when calling reset.

```javascript
let x = Ractive({ data() { return { test: true } });
x.set("test", false);
// console.log(x.get("test")) == "false"
x.reset();
// console.log(x.get("test")) == "true"
```

What do you think about this?

**Comment by martypdx** [comment]
It works that way as a component:

```js
let X = Ractive.extend({ 
    data() { return { test: true } }
});

let x = new X();
x.set("test", false);
console.log(x.get("test")) //false

x.reset();
console.log(x.get("test")) //true
```

> force users to use a function as data

Doesn't seem compelling to require people to use functions.

I suppose we could make `reset` work in the instance case, would there be a downside be to that?

**Comment by Skyrpex** [comment]
I didn't noticed it works like that already. Sorry!

I'm testing this code (Ractive Latest):

```javascript
let X = Ractive.extend({
    data: { test: true }
});
let x = new X();

x.set("test", false);
x.reset();
console.log(x.get("test")); // true
```

which actually works. Does it keep a deep clone of the original data?

**Comment by martypdx** [comment]
The data is on the prototype:

```js
let X = Ractive.extend({
    data: { test: true }
});

console.log(X.prototype.data); // { test: true }

```

It reruns the data initialisation logic, using the supplied parameter to `reset([data])` in lieu of the initialization data.

```js
let X = Ractive.extend({
    data: { test: true }
});

var x = new X({ data: { foo: true } });
console.log( x.get() ); // { test: true, foo: true }

x.reset({ data: { bar: true } });
console.log( x.get() ); // { test: true, bar: true }

```

Bear in mind that (non-primitive) prototype data is shared, which is why this gives a console warning:

```js
let X = Ractive.extend({
    data: { foo: { bar: true } }
});

var x = new X();
var y = new X();
y.set( 'foo.bar', false );
console.log( x.get('foo.bar') ); // false !!!
```

Whereas this gives a unique copy to each instance:

```js
let X = Ractive.extend({
    data: function(){
        return { foo: { bar: true } };
    }
});

var x = new X();
var y = new X();
y.set( 'foo.bar', false );
console.log( x.get('foo.bar') ); // true
```

**Comment by Skyrpex** [comment]
Then it actually works they way I thought... that's great!

I close this. Thanks!

**Comment by martypdx** [comment]
> Then it actually works they way I thought... that's great!

nice to hear that's the case!
