### ISSUE TITLE
Bootstrap plugin preview

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1929]
Hi,

I just wanted to share this with you as a peek preview:

http://dagnelies.github.io/ractive-bootstrap/

My boss was kind enough to let me share some side products of my work, so here it goes. It's not yet finished, nor polished nor fully functional but it should give you an idea of what I'm working on and I hope you'll find it useful.

Granted, it has nothing to do with data-binding and is just style shortcuts ...but hey, I think it might come pretty handy for some people, given bootstrap's popularity. Once it's done, I'll make a nice plugin out of it, etc. However, you're still welcome to give early feedback or concerns.

Also, it would come in handy with #1535 , but I'll try to find a workaround for this in the meantime.

Cheers,
Arnaud

**Comment by fskreuz** [comment]
Having problems with CDN'ed resources and HTTPS.

**Comment by dagnelies** [comment]
@fskreuz I changed it to local links, is it all right now?

**Comment by fskreuz** [comment]
:+1:

**Comment by martypdx** [comment]
Nice!

**Comment by codler** [comment]
Very nice @dagnelies !

**Comment by Rich-Harris** [comment]
I like where this is going :+1:

**Comment by paulocoghi** [comment]
I have developed Ractive decorators for Bootstrap Select and Switch (but I need to do its docs). Are you interested in these decorators in this early stage, without documentation?

**Comment by dagnelies** [comment]
Glad you like it!

@paulocoghi this looks interesting. Of course it's welcome ...I'll just have to think wether I'd put it in the main repo or another "ractive-bootstrap-extras" repo. I'll come back to you once I get some more time on my hands.

**Comment by codler** [comment]
Here are also some components using some bootstrap https://github.com/codler/Ractive-UI written in TypeScript and using Ractive 0.5.5

**Comment by Madgvox** [comment]
@dagnelies I'm going to mark this closed as you've since had it added to the plugins section of the docs. Cool plugin all the same, though! :+1:

**Comment by dagnelies** [comment]
@Madgvox  Thanks

**Comment by Skyrpex** [comment]
@dagnelies The col component is too strict. You can't specify different columns for different sizes. I think it should be something like this:
```handlebars
<col xs=6" md="5"></col>
```

**Comment by dagnelies** [comment]
@Skyrpex ok, I'll take your point in account and make a new col. Feel free to post directly in the repository too.
