### ISSUE TITLE
`observe('*.*')` fails if function at top level

### ISSUE THREAD

**Issue by Crisfole** [ractivejs/ractive#1930]
It works fine w/ up-to-date Chrome, but for older versions of Chrome, Firefox, and IE11 the following fails: http://jsfiddle.net/va6jU/97/

Basically: if you use a function at the top level of `data` Ractive tries calling `Object.keys` on it, but functions aren't allowed to use Object.keys in the aforementioned browsers.

**Comment by Crisfole** [comment]
To make things worse, Ractive swallows the error, because it's during init, and it winds up being *very* hard to track down.

**Comment by Crisfole** [comment]
As a final note, I'm aware that I can avoid this by either namespacing the functions, or being more specific w/ my observe (which is how I fixed the issue), but the error should have a better error message and handling, *or* be fixed to work identically with all browsers.

**Comment by Rich-Harris** [comment]
Eek. I had no idea that `Object.keys` behaved like that in older browsers. Is that documented anywhere? The only sensible solution I can think of is having an internal `keys` helper that knows whether it's safe to defer to `Object.keys` or does the `for...in...hasOwnProperty` dance instead.

> Ractive swallows the error, because it's during init

Can you elaborate? It shouldn't be swallowing errors - e.g. if you deliberately throw an error inside `oninit` you get the expected result: http://jsfiddle.net/rich_harris/vqqp2385/

> but the error should have a better error message and handling, or be fixed to work identically with all browsers

The second of those, definitely. 

Something else I spotted - the `*.*` observer is being fired for each character of the string. I consider that a bug:

![screen shot 2015-04-20 at 2 06 38 pm](https://cloud.githubusercontent.com/assets/1162160/7237026/9ae2a8c8-e766-11e4-99de-219e8e1c4ede.png)

**Comment by Crisfole** [comment]
I was going to suggest you look at `_.keys` for inspiration, but from the look of it they (underscore and lodash) don't make the behavior consistent.

**Comment by Madgvox** [comment]
> Something else I spotted - the `*.*` observer is being fired for each character of the string. I consider that a bug:

Here's the issue post for that bug: https://github.com/ractivejs/ractive/issues/1923.

**Comment by Crisfole** [comment]
Documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys#notes

If I'm reading this correctly it's actually the "correct" way for ES5. ES6, however, coerces the argument to an object first.  Not fantastic either way.  With one you get a TypeError, with the other you get keys for strings and functions.

**Comment by Rich-Harris** [comment]
As far as I can tell this is now working in all browsers (and probably has been a while), so I'll close this. Shout if otherwise

**Comment by Crisfole** [comment]
:+1: I lost track of this request. Can't confirm because I no longer have access to the code that was triggering it.
