### ISSUE TITLE
Select value updated after blur (Firefox only)

### ISSUE THREAD

**Issue by Skyrpex** [ractivejs/ractive#1936]
Hello!

I noticed that a bound value to a select element is updated after the blur event (in Firefox; Chrome works fine).

I've [created a fiddle](http://jsfiddle.net/skyrpex/pz1dtxhn/) so you can test. Reproduced using Ractive Latest and Edge.

**Comment by Madgvox** [comment]
What version of firefox are you using? It's working perfectly well for me on 37.0.2.

**Comment by Skyrpex** [comment]
At this moment, I have Firefox v37.0.1 on Linux Mint 17.1.

Tomorrow I was using Ubuntu 14.10 (same Firefox version I suppose).

**Comment by Madgvox** [comment]
I'm using FF on OSX, so that's the only obvious distinction between our setups. I haven't heard of any FF weirdness that using Linux causes, but I'll do a bit of digging.

**Comment by Crisfole** [comment]
Just popped into my VM (Ubuntu, long time since I updated), it looks like FF 30 works OK.

**Comment by Skyrpex** [comment]
I've tested it using Firefox 37 Beta under Windows 7 too. It still doesn't update until I click out of the dropdown...

A more detailed description of the problem:
What I do is to focus the <select> input (clicking it, for example), and change its value using the keyboard arrows. In order for the <p> element to appear, I must focus-out (aka blur) the <select> input.

**Comment by Crisfole** [comment]
Ah, now I see that behavior in Windows, even. It depends, however, on how you select focus the element.  In Chrome if you focus the element and the dropdown opens and you arrow up and down nothing updates. If you focus it w/ tab and change it it *does* update as it changes.  In firefox that second behavior doesn't happen until you `Enter` or `Tab`.

**Comment by Crisfole** [comment]
Looks like Firefox is coded 'to-spec' for HTML, at least: http://stackoverflow.com/a/586969

I prefer the other verison, and it seems Ractive does as well.  You'd need to hook your selects' change events into keypress events, basically, to get that behavior.

**Comment by Madgvox** [comment]
You should have specified you were using arrow keys! I could have solved your problem immediately :D

Unless you absolutely must, I wouldn't modify the default behavior. It can create a break in expectations for the user.

**Comment by Skyrpex** [comment]
I'm sorry for the previously vague description :stuck_out_tongue: 

Thank you both for the valuable input. Looks like FF likes to be different from the other navigators!

I'll better leave it working as it is... I don't want to mess up anything.
