### ISSUE TITLE
"radio" inputs causes conflicts between components

### ISSUE THREAD

**Issue by blackgate** [ractivejs/ractive#1937]
The method described in http://docs.ractivejs.org/latest/two-way-binding#radios, causes conflicts between components, if they use the same name, as you can see in this jsfiddle:

http://jsfiddle.net/noy7o6u1/

**Comment by Madgvox** [comment]
Here's a solution to your problem. Wrapping the radio buttons in a form scopes them correctly: https://github.com/ractivejs/ractive/issues/1939#issuecomment-94998341

**Comment by blackgate** [comment]
Thanks. However this creates another problem for me, because i already have a form, and with that solution i need to create a nested form element which goes against the standards. From the w3c spec (http://www.w3.org/TR/2011/WD-html5-20110525/forms.html#the-form-element):

> Flow content, but with no form element descendants.

**Comment by Madgvox** [comment]
Hmm. That is a conundrum. It seems we can't just sweep this one under the rug. I'm going to mark this as an `enhancement`, and we'll see what we can come up with.

**Comment by blackgate** [comment]
One possible solution for this, is to define an initialization option to mark one component as an namespace container.

**Comment by martypdx** [comment]
What would work would be to use the component id and full keypath in constructing the token that goes into the `name` attribute. That way they would render as `name={{r-1.selected}}` and `name={{r-2.selected}}`, etc.

**Comment by Madgvox** [comment]
The issue with that is it then prevents you from sharing radio groups across components, which, while it's something @blackgate doesn't want to do, someone else might. We need a solution that works for both use cases.

**Comment by blackgate** [comment]
It still works if the radio inputs are bound to the same value as you can see with this plunkr:
http://plnkr.co/edit/6iM8RF8WKHwEi8blpeF7?p=preview
After all you don't need a name at all, as long as the binding emulates the radio behaviour.

**Comment by Madgvox** [comment]
My point is that with that change, what if I _want_ the behavior showcased in your original broken fiddle where the radio buttons are treated as a single group across component boundaries. Marking the `name` with the guid of the ractive prevents that from being possible.

**Comment by martypdx** [comment]
Oh right, got it.

**Comment by Madgvox** [comment]
The main issue I can see here is that the `name` field is pulling double duty. It's used to mark the radio button group but also to direct ractive what to bind to. The thing is, I can't think of a solution that isn't also incredibly ugly or awkward, or breaks the purpose of two-way binding. It'd have to be something that frees up the `name` field to be divvied up however you want, but doesn't confuse ractive as to how to bind everything together.

The double-use `name` field has the advantage of making it so you can't confuse the heck out of ractive by putting a bunch of radio buttons into one group but binding half of them to different values, but the disadvantage of ... well, exactly what @blackgate is running into, where you might get radio button groups grouping together in an undesired manner due to not being able to customize how the `name` field looks.

**Comment by Crisfole** [comment]
I'm trying to conceive of a **component** that I'd want to make that only had a portion of an array of radio buttons.  In my mind I should be able to stick a component on the page and have it be self-sufficient.

I suppose you could have a `<fancy-radio>` component that was just a thin veneer over a plain-jane radio button...but in that case you'd be able to achieve your goal by turning off `two-way`.

Would you be able to set `radio` up so it used a `:` to separate name and variable?

**Comment by martypdx** [comment]
@Crisfole I ended up at thinking some sort of declarative attribute modification too. Though was initially thinking two separate attributes.  I like the combination, though I'd put the modifier before and outside the mustache:

```html
<input type='radio' name="html-name:{{variableName}}" value='red'/>
```

I couldn't find it, but there's another gh issues out there where someone was posting the form directly and wanted to specify the name (something w/o  `{{mustaches}}`), so this would cover that case as well.

**Comment by Crisfole** [comment]
And I assume it'd be optional? (Skipping would maintain the current behavior?)

**Comment by blackgate** [comment]
@martypdx  I like the ideia. It solves all the possible scenarios i can think of.

**Comment by Madgvox** [comment]
I assume that would also apply to checkboxes?

**Comment by martypdx** [comment]
> And I assume it'd be optional? (Skipping would maintain the current behavior?)
> I assume that would also apply to checkboxes?

Sounds right to me.

**Comment by fabien** [comment]
> I couldn't find it, but there's another gh issues out there where someone was posting the form directly and wanted to specify the name (something w/o {{mustaches}}), so this would cover that case as well.

@martypdx I'm not sure, but perhaps you recall #1674 here?

**Comment by fabien** [comment]
Is this related? #1113

**Comment by Madgvox** [comment]
It appears that the fiddle in the OP works in 0.8-edge.
