### ISSUE TITLE
Radio button name field not executing expressions

### ISSUE THREAD

**Issue by Madgvox** [ractivejs/ractive#1939]
Found while researching #1937. If you inspect the checkboxes in [this fiddle](http://jsfiddle.net/5t9jc42o/), the name attribute is just `{{color}}`. It's never getting executed as a mustache.

Is this intended behavior? If so it's really weird. One of the things I love about ractive is the clean DOM it produces, so this is a strangely ugly way to deal with checkboxes.

**Comment by Madgvox** [comment]
It also prevents you from doing something like [this](http://jsfiddle.net/noy7o6u1/2/) in order to namespace your components' radio buttons.

**Comment by martypdx** [comment]
@Madgvox they need to been identically named so that they become a group. Using the keypath is a way to do that. But we could probably put whatever, maybe remove the `{{` `}}` from the reference.

> It also prevents you from doing something like this in order to namespace your components' radio buttons.

Use a form tag to scope the inputs: http://jsfiddle.net/noy7o6u1/3/

**Comment by Madgvox** [comment]
From the source, it looks like the `{{` `}}` are artificially added back in. Perhaps that's done so that there's no potential conflicts with non-ractive radio buttons? I dunno.

I'm going to close this, since the [related issue](https://github.com/ractivejs/ractive/issues/1937) has been resolved, and I don't have a real leg to stand on other than it's ugly to me, and I don't ever use radio buttons anyway :stuck_out_tongue:
