### ISSUE TITLE
Getting the instance's id

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1940]
The problem I have is that Bootstrap popover options don't allow a reference to an element as the container of the popover,  it [only accepts a selector](http://getbootstrap.com/javascript/#popovers-options) (and yes, it's a Bootstrap problem, but whatever). I was thinking of getting the ractive instance id (or some unique string identifier) of the component to scope down the selector. 

```
// This is possible because Ractive's `this.find` is scoped to the component
$(this.find('.elementToPoint)).popover({
  ...
  // However, this is a global selector search unless I scope the selector to this instance
  container: '[data-rvcguid=' + this.getInstanceId() + '] .targetContainerInsideComponent'
  ...
});
```

Ideas? or if not, feature request. :D

**Comment by Rich-Harris** [comment]
Unfortunate that Bootstrap does things that way. Selector-based programming is so 2013! 

There is one approach that you could use straightaway without it needing to be a new feature - overriding the `render` method:

```js
var render = Ractive.prototype.render;
Ractive.prototype.render = function () {
  var promise = render.apply( this, arguments );
  this.find( '*' ).setAttribute( 'data-ractiveid', this._guid );
  return promise;
}
```

Example here: http://jsfiddle.net/zj9j4g5m/ Note that it assumes templates have a single top-level element.

**Comment by fskreuz** [comment]
Ahh, this works fine. I usually wrap my components in a `<div>` anyway so they act like one element. :+1:

**Comment by wgrhstf** [comment]
Maybe I ran into the same problem, but I could not figure out how your approach could be adapted. I try to use Bootstrap popover in a partial with a button for downloading files:
```
const FilePartial = '<a href="#" data-toggle="popover" data-content="{{#files}}{{FileName}}'+
'<button type=\'button\' on-click=\'@this.download(FileName)\'>Download</button>{{/files}}"></a>';
```
but the function
```
download: function (FileName) {
            console.log(FileName)
        }
```
is never triggered. (the popover itself works fine)
Is that somehow related to the abovw problem?
