### ISSUE TITLE
[question] checkbox (or any element) should conditional wrap around attributes or attributes' values

### ISSUE THREAD

**Issue by akhoury** [ractivejs/ractive#1941]
Which is a better approach, in ractive-speak

```mustache
    <input on-change="flipOk" type="checkbox" {{#if ok}}checked="checked"{{/if}} /> 1 
    <input on-change="flipOk" type="checkbox" checked="{{#if ok}}checked{{/if}}" /> 2 
```

approach-1 seems buggy, is that expected? see example
http://jsfiddle.net/614xrnvk/10/

I feel like (1) needs a "change" event to be fired on when an attribute such as checked is programmatically added/removed, no?
Thanks

**Comment by Madgvox** [comment]
Ractive considers boolean attributes to be `true` if the expression is true, and `false` if the expression is not. so you can just do this:

```html
<input on-change="flipOk" type="checkbox" checked="{{ ok }}" />
```

**Comment by akhoury** [comment]
awesome notes and side notes, thanks @Madgvox

**Comment by Madgvox** [comment]
Has your issue been resolved? Do you have any other questions?

**Comment by akhoury** [comment]
yes, thanks
