### ISSUE TITLE
Incorrect behaviour when using array.splice()

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1943]
Via the [mailing list](https://groups.google.com/forum/#!topic/ractive-js/SyXXDwTFcrE), a weird splice bug: http://jsfiddle.net/rich_harris/re0yx58m/ Workaround appears to be to always use the second argument to `splice()`

**Comment by ISNIT0** [comment]
As far as I can tell, this bug is somewhere in the getNewIndices function: https://github.com/ractivejs/ractive/blob/dev/src/shared/getNewIndices.js

**Comment by ISNIT0** [comment]
Actually, maybe here: https://github.com/ractivejs/ractive/blob/dev/src/shared/getNewIndices.js#L78

**Comment by MartinKolarik** [comment]
@ISNIT0 indeed, the problem was in `getNewIndices`, but the JS default is `array.length - start` - remove all
