### ISSUE TITLE
Ractive in WordPress environment

### ISSUE THREAD

**Issue by gaelicmichael** [ractivejs/ractive#1944]
Does anyone have experience with developing WordPress plugins with Ractive? The JavaScript code I've developed with Ractive works on its own, but in the WP environment (I'm running WP 4.2 and Ractive 0.7.3) it seems to cause crashes -- are there conflicts around observing variables, or other issues?

**Comment by gaelicmichael** [comment]
For example, just the following code (triggered with a button press) causes a window to appear that asks if the user wants to stay on the page or leave, even though there is no page redirection in the code.
```
	rApp.on('copyCF', function() {
		rApp.set('theAttribute.cf', rApp.get('chosenCF'));
	});
```

**Comment by gaelicmichael** [comment]
Bizarrely enough, I've now narrowed it down to interference with validation in input fields. It looks like WordPress adds some custom JS code (or uses some additional library) to "enhance" validation. When  validation succeeds for all fields, it causes a crash when some Ractive operations are performed (!). That's as far as I've gotten thus far. I will post more info when I figure more out.

**Comment by RangerMauve** [comment]
It's probably because whatever form this is a part of is being submitted. You should call preventDefault() and stopPropagation() in your event listener. The popup is something provided by the browser, and it appears whenever you try to leave a page when there is stuff in an input.

**Comment by gaelicmichael** [comment]
Thank you!  Appending "return false;" to the end of all of my Ractive.on('button-message', …) functions has indeed solved some of the problems I was encountering! Still a couple of others, however, that may be related but haven't been fixed yet from this…

**Comment by martypdx** [comment]
@gaelicmichael Do you have a public endpoint we could look out to help diagnose errors?

**Comment by gaelicmichael** [comment]
Sorry, Marty, I don't yet -- I'm using Ractive to implement the backend (Dashboard) of a WordPress plugin, and it requires admin privileges at this point.

**Comment by gaelicmichael** [comment]
In case you want to see the code, though, I've created a GitHub repo for it at: https://github.com/Digital-Innovation-Lab/gig.

I now have the Dashboard for Attributes and Templates working… but not Records or Exhibits…

**Comment by gaelicmichael** [comment]
I think that the other bugs are my own -- just about got them squashed, I think. Thanks again for your generous assistance.

This Ractive-powered project will be Open Source, but there's not enough of it running yet to show off. It will happen and I will notify everyone when it does.
