### ISSUE TITLE
Components initialisation function

### ISSUE THREAD

**Issue by mmrosa** [ractivejs/ractive#1945]
I'm trying ractivejs components functionality and i would like to resolve the component that must be rendered based on the state of the ractive instance.

This scenario is exacly what is specified on [components advanced configuration](http://docs.ractivejs.org/latest/advanced-configuration#components), but for some reason on my [tests](https://jsfiddle.net/hcdabfp5/) the initialisation function is invoked without data argument.

So, we have 3 possible scenarios:
* I'm using this feature in a wrong way
* Bug in the documentation 
* Bug in the code

Can anyone check it, please?

**Comment by Madgvox** [comment]
Your setup looks good to me at first glance. The data object should definitely be getting passed into the function.

**Comment by mmrosa** [comment]
The method getComponents was updated on tag 0.7.1 and the code to bind the argument was removed. The point is if it was removed due to bug or new feature.

**Comment by Rich-Harris** [comment]
The docs are out of date, sorry! We'll fix it. As of 0.7, the `data` object is no longer passed into those functions (long story - basically it can't take account of data belonging to a parent component, or computed values, etc), and you have to use `this.get('foo')` instead of `data.foo`.

Also, the returned value should be a component constructor, rather than a string. Here's a working fork: http://jsfiddle.net/rich_harris/7pwud5q8/

**Comment by Rich-Harris** [comment]
I take back what I just said about having to return a constructor - you can use a string, if the component has been registered... http://jsfiddle.net/rich_harris/n9jrhffs/... d'oh

**Comment by mmrosa** [comment]
Ok, but if we are iterating an array it's possible to know the row that represents the component?

Example:

Template:
{{#each entry}}
  <dynamic data="{{.}}"/>
{{/each}}

Data object something like [ { componentType : "Button"}, { componentType : "Input"}]

And with the initialisation function to resolve the component that must be rendered using the component type property?

Thanks in advance

**Comment by Rich-Harris** [comment]
Easiest way to do what you describe is probably with components and dynamic partials: http://jsfiddle.net/rich_harris/7ok2hsL1/. Is that an option?

**Comment by mmrosa** [comment]
Well it's an alternative, anyway imho i think in a huge project we will lose the flexibility in terms of separation of concerns.

The usage of components it's really cool because we can have view logic and template together, encapsulating the logic of each one inside of each component will drive to a clean code easily testable and also reusable.

With this approach i think in a huge project we can end up with a mess for example to handle events.

My background is statically typed languages and eventually my point of view is too much oriented to this type of language.

Tell me from your justice, if i'm wrong or if you think this could be a new feature?

**Comment by martypdx** [comment]
@mmrosa here is a slightly modified version of @Rich-Harris' last example: http://jsfiddle.net/7ok2hsL1/2/. In this case we don't need to keep an intermediate list of mappings from partials to components, it can directly reference the needed the component. It uses a function to dynamic create a partial that is the component:

```js
Ractive.prototype.data = {
    getComponent: function(name){
        if (!!this.partials[name]) return name;
        this.partials[name] = '<' + name + '/>';
        return name;
    }
}
```

The issue with using the function return for a component (as in your original example) is that it is a one time initialization function return for that defined component, so it doesn't work for a list of components where you want a different one for each item in the array.

Dynamic partials on the other hand, give you a per-instance ability to change the implementation. It's on the list to expand that type of dynamism to components, but for now you need to go through a partial. Which does have the down side of requiring the parser at runtime.

That being said, you can use a pure component solution, but it is much better suited to lists that will not need to mutate, which in many cases works just fine. You just use an intermediate dynamic component (see http://jsfiddle.net/7ok2hsL1/4/):

```js
Ractive.components.dynamic = Ractive.extend({
    template: '<impl/>',
    components: {
        impl: function(){
            return this.components[this.get('type')]
        }
    }
});
```

**Comment by Rich-Harris** [comment]
start typing reply, see significantly more complete and helpful answer from @martypdx, ^h^h^h^h^h...

I'll just leave a reference to the dynamic components issue though, so we can find it (or this) later: https://github.com/ractivejs/ractive/issues/1678

**Comment by martypdx** [comment]
> start typing reply, see significantly more complete and helpful answer from @martypdx, ^h^h^h^h^h...

:)

Okay, since this thread is becoming complete (maybe we should use it for new docs :smile: ), here is an example of pure dynamic components solution including updating (see http://jsfiddle.net/7ok2hsL1/5/).  It works in this example, but in my experience it can be hard to get right as there are a number of edge cases issues you need to navigate.

**Comment by fabien** [comment]
+1 for adding this to the docs

**Comment by Rich-Harris** [comment]
I've [updated the docs](http://docs.ractivejs.org/latest/advanced-configuration)

**Comment by Madgvox** [comment]
Looks like this has been resolved! :tada: If you have any other problems, @mmrosa, please feel free to reopen this issue.
