### ISSUE TITLE
learn partials example: code is broken

### ISSUE THREAD

**Issue by fabien** [ractivejs/ractive#1946]
See: http://learn.ractivejs.org/partials/2 in `on('edit')`

```
Uncaught TypeError: Cannot read property 'i' of undefined

// reason: event.index is undefined
```

**Comment by Madgvox** [comment]
We have an issue opened [here](https://github.com/ractivejs/learn.ractivejs.org/issues/22), so I'm afraid I must close this one. Thanks for the catch regardless! :)
