### ISSUE TITLE
merge(keypath, object, 'id')

### ISSUE THREAD

**Issue by briancray** [ractivejs/ractive#1947]
Would be great to have the option to use an object instead of an array as the second parameter to `merge`. This is all assuming keypath points to a collection (array of objects vs primitives).

When using an object, two things change from `merge(keypath, [object], 'id')`:
1. It doesn't replace the whole array.
2. Appends or replaces the object in keypath.

I don't think this would lead to unexpected behavior--it felt pretty natural and I had to carefully read the documentation to realize that only arrays were allowed as second parameter.

**Comment by martypdx** [comment]
I can't follow from your description, can you show some data and how it would change.

**Comment by briancray** [comment]
Sure. Here's a contrived example.

```
data[keypath] = [
    { foo: 'bar', id: 1 },
    { foo: 'bar', id: 2 },
    { foo: 'bar', id: 3 }
]

// desired behavior
@merge(keypath, {foo: 'baz', id: 1}, 'id'); // change the first item
@merge(keypath, {foo: 'baz', id: 4}, 'id'); // add to list
```

**Comment by martypdx** [comment]
Ah, I see. Take a look at #753 for my initial confusion on merge and some discussion of adding options to the `set` method as well/instead of merge.

Your could try out your examples and see how the API goes for you:

```js
Ractive.prototype.arrayMerge(keypath, object, key){
    var found = this.get(keypath).findIndex(a => a[key] === object[key]);

    if(~found){
        this.push(keypath, object);
    }
    else {
        this.set(keypath + '.' + found, object);
    }
}
```

**Comment by briancray** [comment]
Yea I have something similar to do this already, was just hoping to use something built in. Are your suggestions on the imminent roadmap? I notice it was made a year ago :)

On a related note, it'd be also great to see `removeFromArray(keypath, {id: 1}, 'id')`

**Comment by martypdx** [comment]
> Are your suggestions on the imminent roadmap? I notice it was made a year ago :)

It hasn't come up that often. With the ease of adding one's own facade API calls, it's good to let things funnel to the core as people get some use out their own API's. PR's always considered :). I think with array handling, there's a set of improvements that could be added.

**Comment by evs-chris** [comment]
Based on #753 and #550, I think `merge` as it is now is going to turn into a deep set/extend and the functionality provided by merge will move to an option on `set`. After that happens, probably somewhere around 0.9 and 0.10, if this is still an issue not covered by the other two, we can reopen this one. So I'm going to close this for now.
