### ISSUE TITLE
Null in refResolvers causes errors on component teardown

### ISSUE THREAD

**Issue by RangerMauve** [ractivejs/ractive#1948]
Hello, I've  recently made a component for swipe-able pages and it seems that whenever it gets torn down, an uncaught error gets thrown and Ractive starts behaving strangely. I've narrowed it down to a [minimal example](http://requirebin.com/?gist=31db77359a0562285847) that gets it to break.

The error itself is:

```
Uncaught TypeError: Cannot read property 'unbind' of null
```

It occurs in [the unbind methodCaller](https://github.com/ractivejs/ractive/blob/722e6871363aff4e739b9c681348ae5f2acfa659/src/shared/methodCallers.js) when it gets called by the [unbind method in an Element's EventHandler](https://github.com/ractivejs/ractive/blob/dev/src/virtualdom/items/Element/EventHandler/prototype/unbind.js).

I'm not really sure what could cause it. I tried removing the inner `SPPage` components from the `SPContainer` component and used divs instead, in case it was related to nested components. But that didn't seem to be the case.

Would this maybe be an issue in the [ractive-touch](https://github.com/rstacruz/ractive-touch) library? Or might I be doing something wrong in the [ractive-swipe-pages](https://github.com/RangerMauve/ractive-swipe-pages) module?

**Comment by martypdx** [comment]
That's a know issue with `0.6.1` that has since been fixed. You're passing in `event` to an event handler method somewhere: 

`<element on-something='doSomething(event)'>`

And it returns a `null` referenceResolver reference.

You can access the event in the method via `this.event`, so try changing to that instead of passing it in and seeing if that works.

**Comment by RangerMauve** [comment]
Oh man, it seems so obvious now! Thank you!
