### ISSUE TITLE
Nested yields - aren't they supported?

### ISSUE THREAD

**Issue by gaelicmichael** [ractivejs/ractive#1949]
Ractive gives me the following error: "Error: A component template can only have one {{yield}} declaration at a time"

My components are wrappers for jQueryUI widgets (accordions and tabs) and there is only one yield statement in each of my component templates, but they end up getting nested because the GUI needs to have tabs within accordion panels.

Given that yields can be recursive, I don't understand why this is a problem. Is this a bug? Here's what my component templates look like and an extract from using them:

```

<!-- Ractive Template for jQueryUI Accordion Component -->
<script id="accordion-r-template" type='text/ractive'>
	<div class="jq-accordion-template">
		{{yield}}
	</div>
</script>

<!-- Ractive Template for jQueryUI Tabs Component -->
<script id="tabs-r-template" type='text/ractive'>
	<div class="jq-tabs-template">
		<ul>
		{{#each items:tIndex}}
			<li><a href="#{{prefix}}-{{vi}}-{{tIndex}}">{{tid}}</a></li>
		{{/each}}
		</ul>
		{{#each items:tIndex}}
			<div id="{{prefix}}-{{vi}}-{{tIndex}}">
				{{yield}}
			</div>
		{{/each}}
	</div>
</script>

	<accordion>
		<h3>Inspector Modal</h3>
		<div>
		...

		<tabs prefix="tmpt-vf-tab" items="{{iTemplates}}" vi="{{vIndex}}">
			Show content:
			{{#each c.cnt[tIndex]:cIndex}}
			...

```

**Comment by fskreuz** [comment]
As far as I remember, yep, this should be supported. We even use it as wrappers for our Bootstrap tabs, panels and modals. http://jsfiddle.net/2zwkxte6/1/

```html
<first-container>
    <second-container>
        <div class="content">Hello World</div>
        <div class="content">Foo Bar</div>
    </second-container>
    <second-container>
        <div class="content">Hello World</div>
        <div class="content">Foo Bar</div>
    </second-container>
</first-container>
```

**Comment by gaelicmichael** [comment]
The {{yield}} needs to generate the content for each panel's contents, so that the DOM ends up looking like this (from the jQueryUI website):

```
<div id="tabs">
  <ul>
    <li><a href="#fragment-1">One</a></li>
    <li><a href="#fragment-2">Two</a></li>
    <li><a href="#fragment-3">Three</a></li>
  </ul>
  <div id="fragment-1">
    Blah blah.
  </div>
  <div id="fragment-2">
    Blah blah.
  </div>
  <div id="fragment-3">
    Blah blah.
  </div>
</div>
```
I don't see where the error in my logic is. I can't have an outer loop outside of the Tabs template, because that would not produce the correct "double" structure (of <ul><li><a ..> followed by <div id...>).

**Comment by fskreuz** [comment]
@gaelicmichael Updated the examples:
- Yield: http://jsfiddle.net/2zwkxte6/3/
- Content: http://jsfiddle.net/2zwkxte6/5/

**Comment by gaelicmichael** [comment]
OK, so you got it to work by using "{{>content}" in the inner component. I copied that technique and now it renders the DOM... but I have to rewire the events. 

Thanks for your assistance!
