### ISSUE TITLE
Implementing Modals using Ractive

### ISSUE THREAD

**Issue by alexmakeev** [ractivejs/ractive#1953]
Using them with bootstrap, but want to make unlimited nested modals.

**Comment by alexmakeev** [comment]
The idea is to make a switchable DOM branches using a component like this:

<a class="btn btn-info btn-xs" on-click="toggle-modal-shown">Open Modal</a>
{{#if (is_modal_shown)}}
    <Modal />
{{/if}}

but the issue is: how to move newly shown Modal out of main DOM branch (cause nested modals will cause bad css things like being inside "overflow: hidden") without Ractive rendering and two-ways binding braking.

Thank for any effort.

**Comment by martypdx** [comment]
Here's a simple version of pattern I'm using. Assumes a `#popup-host` in the DOM where it can be  "above" the other stuff:

```html
<div id='popup''>
	{{#if ready}}
		<!-- content goes here, or: -->
        {{yield}}
	{{/if}}
</div>
```

```js
component.exports = {
	data: {
		ready: false,
	},
	close: function(){
		this.set('ready', false).then(function(){
			this.fire('close');
		}.bind(this));
	},
	onteardown: function(){
		if(this.host){
			this.host.innerHTML = '';
			this.host = void 0;
		}

	},
	onrender: function(){
		var host = this.host = document.getElementById('popup-host');
        host.appendChild(this.nodes.popup);
   		this.set('ready', true);
	}
}
```

**Comment by fskreuz** [comment]
The way we do it is we mount modals on `body` as a separate component and the main app as a component. To bridge them, we either use listeners or data stores (basically an event emitter that carries values).

```
// app.html

// listen for clicks that call this event
this.on('openModalOne', function(){
  // Basically just sets the flag for modalOne to true and emits a change event
  ExternalDataSource.openModalOne();
});
```

```
// modals.html

// Modals not nested, they're siblings so they don't clip each other
{{# isModalOneOpen }}<Modal />{{/}}
{{# isModalTwoOpen }}<Modal />{{/}}
{{# isModalThreeOpen }}<Modal />{{/}}

<script>
component.exports{
  data: {
    isModalOneOpen: false,
    isModalTwoOpen: false,
    isModalThreeOpen: false,
  },
  oninit: function(){
    // Listen to emitted changes and update modal states
    ExternalDataSource.listen(function(){
      // These are just getters for the flags in the emitter
      isModalOneOpen: ExternalDataSource.getModalOneState(),
      isModalTwoOpen: ExternalDataSource.getModalTwoState(),
      isModalThreeOpen: ExternalDataSource.getModalThreeState(),
    });
  }
}
</script>
```

```
// main.js

var App = require('rvc!path/to/app');
var Modals = require('rvc!path/to/modals');

new App({
  el: 'wherever your app mounts',
});

new Modals({
  // mount it to body so they're relative to the viewport and can fill the screen properly
  el: 'body',
  append: true,
});

```

**Comment by alexmakeev** [comment]
Thank you for variants!

**martypdx**, understood the idea, it's close to one I'm going to use. The only question is should it break the ractive rendering of modals sub-components and their two-ways binding? As I understand the ractive logic, I need make ractive to detach and reconnect the child to popup-host. Should it be implemented using http://docs.ractivejs.org/latest/ractive-insert ? It's very lack of documentation for this topic.

**fskreuz*, that's also good, but you see, I have no way to add new popups without modification of root ractive template. But I got the idea of using listeners to switch the modals, thank you for it.

**Comment by martypdx** [comment]
@alexmakeev I'm not sure if you're wanting to maintain the data bindings or not. The solution I outlined maintains the bindings. Here's the basic idea: http://jsfiddle.net/g39f563h/. As you edit in the popup notice the items stay in sync.

**Comment by alexmakeev** [comment]
@martypdx very thanks for jsfiddle! Haven't event think that native JS appendChild would preserve bindings. It really works.
