### ISSUE TITLE
"too much recursion" when I'm using adapt: [ 'Ractive' ] and update global data

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#1954]
Here is an example — http://jsfiddle.net/Inversion/fpopj4vq/ 
(Ractive.js  v0.7.3 + this adaptor: https://github.com/Rich-Harris/Ractive-plugins/blob/master/adaptors/Ractive.js)
Try to uncomment one of the commented lines at the bottom.

On the project I can also see `Error: Computed properties without setters are read-only. (This may change in a future version of Ractive!)` but cannot reproduce in the sample.

Workaround can be to have some separate Ractive object with all the global vars and do not mix it with any other data that can be updated.

Maybe there is some better way to have a global object and reflect its changes in all the linked Ractive objects (not using magic mode)?

Thank you!

**Comment by martypdx** [comment]
Can you just put the data on the root Ractive instance and spawn components under the that instance?

**Comment by Inversion-des** [comment]
I cannot get how to spawn components dynamically from the root Ractive instance.
Could you help me here: http://jsfiddle.net/Inversion/auyptc0s/

To be clear: I need to be able dynamically create dialog windows (not predefined windows in the root template) that can listen to some global settings changes.

**Comment by martypdx** [comment]
Use data to "create" the components: http://jsfiddle.net/auyptc0s/4/

**Comment by Madgvox** [comment]
@Inversion-des I'm going to assume this issue has been resolved and mark it closed. If you have any more questions or concerns, please feel free to reopen the issue at any time.
