### ISSUE TITLE
Viewmodel cache wtf?

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1955]
Caches would probably be gone due to https://github.com/ractivejs/ractive/pull/1740 but just wondering *when are viewmodel caches cached and updated*? Basically, the component is just this, pretty straightforward:

```
computed: {
  shouldNotificationOpen: function(){
    debugger; // 2
    var a = this.get('a');
    var b = this.get('b');
    var c = this.get('c');
    return a && (b || c);
  }
},
oninit: function(){
  ExternalData.listen(function(){
    debugger; //1
    this.set({
      a: ExternalData.getA(),
      b: ExternalData.getB(),
      c: ExternalData.getC(),
    });
    debugger; //3
  });
}
```

Updating the data with different values, it should be simple enough to reason out that the computed will run and will update its value (and re-render whatever uses it). Shown in the sample, the `debugger;`s will run in the said order. However...

In some cases, the second `debugger;` will not run at all. After hours of tracing through Ractive, it appears that doesn't run the computation because the value is somehow cached. The code will not run through here: https://github.com/ractivejs/ractive/blob/v0.6.1/ractive.js#L13490

So back to the question:

- What causes it to cache the value
- When does it cache a value
- When does it update the value
- What are workarounds to prevent it from being cached.

Knowing when these happen and why would put me in the right direction.

**Comment by martypdx** [comment]
Are you seeing it not rerun the computation function when it fact should rerun it based on changed data?

**Comment by fskreuz** [comment]
@martypdx Yup, the second `debugger` (the one in the computed value) doesn't run at all after `set`. It doesn't pass here https://github.com/ractivejs/ractive/blob/v0.6.1/ractive.js#L13490 but here instead https://github.com/ractivejs/ractive/blob/v0.6.1/ractive.js#L13505

**Comment by martypdx** [comment]
@fskreuz Here's a fiddle that emulates what it looks like you're trying to do: http://jsfiddle.net/os9uh73q/. Seems to work, but maybe I don't have the right combination of value changes. Can you try with same values as is happening in your case?

As to the broader question on caching, in current code it prevents unnecessary refetching of data, if nothing has changed. On a set operation, the cache will be cleared for that item plus any upstream, downstream and computational dependencies. Computations have an additional layer of checking input value changes explicitly before recalculating. There haven't been any known issues, so if you've found a bug we should correct.

> Caches would probably be gone due to #1740

Yes and no. I've used the same pattern of "marking" the data node graph as dirty when a change happens. Currently there is no explicit caching, I took it out to focus on the core functionality and to see where would be the best place to put it in. At this point I think it will be added back in for two reasons:

The first is that there is a cost in refetching the data value if the value is deeply nested, for example getting `dop` of `foo.bar.qux.dip.dop` requires walking accessors all the way down: `foo[bar][qux][dip][dop]`. It's only a small gain, but it may be more more significant when you consider adaptors. But probably the bigger reason is:

Know if a value has "really" changed and don't notify dependants if it hasn't. Imagine `foo` is `{ one: 'bar', two: 'qux' }` and gets set to `{ one: 'bop', two: 'qux' }`. `foo.two` hasn't changed but unless we know the prior value we can't make that determination.

Currently this comparison happens partially in the viewmodel via `cached` but primarily in the virtualDOM objects for the purpose of not making unnecessary DOM changes.  And maybe it should just stay there, but it may make sense to pull this comparison closer to the data and not send the notification out at all (though that would require changing the virtualDOM objects to pull the value whereas now it is pushed).

And if we get it to reliably not over-notify in the viewmodel, we could possibly eliminate the guard checking on computations.

**Comment by fskreuz** [comment]
Will just close this for now and investigate why it's happening. Most likely not a Ractive bug, but if it is... :trollface:
