### ISSUE TITLE
Supress Intro-Outro the first time?

### ISSUE THREAD

**Issue by Crisfole** [ractivejs/ractive#1957]
It seems to me there's a pretty normal use case where you have something displayed on-screen that you'd like to be able to transition out and back in again. (Say a menu, or help-text, or something).  When you apply `intro-outro` to that element it transitions in on-load as well which winds up being a very jarring visual experience.

Does Ractive have a way to handle this situation?

**Comment by Rich-Harris** [comment]
Yes:

```js
ractive = new Ractive({
  noIntro: true,
  /* other options */
});
```

See https://github.com/ractivejs/ractive/issues/1853 for some caveats though! (basically it doesn't apply to child components)

**Comment by Crisfole** [comment]
Awesome, I had misunderstood that config option.
