### ISSUE TITLE
Decorator Events

### ISSUE THREAD

**Issue by Crisfole** [ractivejs/ractive#1959]
I'm using the select2 decorator and having trouble attaching to the on-change event. (Works fine if I don't decorate, but looks terrible).

It looks like the decorator is swallowing the change event. I would give you a demo, but I can't figure out how to get jsFiddle to load the decorator code...

**Comment by Madgvox** [comment]
From a quick look at the select2 website, it looks like select2 completely takes over for the original select, so changing the input does not update what select option is marked `selected`, which means that a `change` event attached to the original select does not do anything. You'll have to fire that event manually.

**Comment by Crisfole** [comment]
Hm, I'm 90% certain that select2 posts the changes back to the original `select`. Because you can keep a reference to the select in js. Its `value` property stays in sync...But I'll poke around a bit.

**Comment by Crisfole** [comment]
@Madgvox So I've confirmed that the event isn't firing, although the original input is being changed (And classic html/javascript events work). The following works:

    <select multiple decorator='select2' value='{{whatever}}' onchange="alert('Trad. event fired')">
      <option>One</option>
      <option>Two</option>
    </select>

The following doesn't:

    <select multiple decorator='select2' value='{{whatever}}' on-change="methodOnRactive('Ractive event fired')">
      <option>One</option>
      <option>Two</option>
    </select>

**Comment by Crisfole** [comment]
Unfortunately the only decorator on an input is `select2` (and `chosen`, which is a fork of `select2` w/ `chosen` instead of `select2`). So demoing this will require a few extra steps...

**Comment by Crisfole** [comment]
So this is specific to the select2 decorator. I tried it with the toolbar demo decorator and it worked fine. I'll post ther.
