### ISSUE TITLE
Detect infinitely recursing partials?

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1960]
[This](http://stackoverflow.com/questions/30166473/recursive-partial-in-ractivejs-exceeding-call-stack/30167880#30167880) has caught me out once or twice before - partials that recurse infinitely because some expected property on the child is instead retrieved from the parent - which makes me wonder if there's a good way to detect those situations and handle the error in a friendlier way without wrapping everything in a try-catch. E.g. a particular partial template is marked 'active' while it's being initialised and deactivated straight away afterwards, and if an already-active partial template is seen, it means we're recursing, so we can slap on the try-catch brakes in case the recursion turns out to be infinite.

**Comment by Crisfole** [comment]
You *could* just set a maximum depth of recursion sufficiently high that a reasonable implementation wouldn't bump into it. (Nesting more than a few levels deep in a UI is a bad plan...). You could allow explicitly increasing the amount.

Although that solution doesn't really have the same elegance as most of the rest of Ractive's solutions.

**Comment by lluchs** [comment]
:+1:, just ran into the same issue.

@Crisfole: No, that doesn't work. The issue here is that due to the way references are resolved, you get infinite recursion.

**Comment by evs-chris** [comment]
@Rich-Harris i was thinking about this, and perhaps checking up the vdom tree for partials with the same template and context during render would be a sufficient indicator that there is an infinite recursion scenario unfolding?

**Comment by evs-chris** [comment]
We actively discourage ambiguity in the docs and any recommendations now, and there's not a non-cumbersome way to achieve this.
