### ISSUE TITLE
Support promises/async at a template level

### ISSUE THREAD

**Issue by paul-bjorkstrand** [ractivejs/ractive#1961]
I think it would be interesting if Ractive could support async data "natively". Since async is so gosh darned hard in the first place, I think using promises (meant to make async easier and palatable) would be the best way to make it useful in Ractive as well.

 I have not begun looking into it yet, but would like to dive into the Ractive source and see what it would take to make it happen. My straw man syntax would be something like

Given ```promise```, which is expected to hold the result of some async operation, we can retrieve the result using ```{{then}}``` and handle errors using ```{{catch}}```.
```
{{#async promise}}
  <span>Waiting for data...</span>
{{then:data}}
  {{#each data}}
    <span>name</span>
  {{/each}}
{{catch:error}}
  <span>Warning: {{error}} occurred</span>
{{/async}}
```
I used ```{{then}}``` and ```{{catch}}``` since it is the terminology used in ES6 promises. In lieu of using a specific loading block, I opted to use the space between ```{{#async}}``` and ```{{then}}```, as it seemed fitting. If you do not provide a variable name (such as the ```data``` in ```{{then:data}}```), the ```this``` or ```.``` variables would be used instead..

Any thoughts are welcome, and I appreciate your comments in advance.

**Comment by MartinKolarik** [comment]
You might want to check out [ractive-promise-alt](https://github.com/rstacruz/ractive-promise-alt). It seems to be doing exactly what you propose, but without need for any new syntax.

**Comment by paul-bjorkstrand** [comment]
@MartinKolarik, although I do see that the adapter has mostly what I want, I feel that this is something that shouldn't be left to 3rd party plugins/adapters. I think it would be a big win for Ractive, as a tool, to natively support (ES6 + polyfill) promises with straight forward syntax, and well known terminology. In my opinion, the syntax of [ractive-promise-alt](https://github.com/rstacruz/ractive-promise-alt) is a bit kludgy (no offense to @rstacruz, there really isn't any other way to make the adapter, and I am glad you made it!).

**Comment by MartinKolarik** [comment]
Although I'm a big fan of promises, I think this is exactly the kind of thing that should be left to 3rd party plugins.

As for the syntax, using standard sections and having `pending`, `result`, and `error` as a part of the `data` object allows you to trigger custom functions depending on the state of the promise. If we *did* decide to have this in core, I'd suggest using a very similar syntax:

```
{{#await user}}
    {{#pending}}
        Loading...
    {{/pending}}

    {{#result}}
        Hello, {{first}} {{last}}!
    {{/result}}

    {{#error}}
        An error occured: {{.}}
    {{/error}}
{{/user}}
```

**Comment by Rich-Harris** [comment]
I totally understand where you're coming from @paul-bjorkstrand, I'm also a heavy user of promises, and I've occasionally had the same thought. But @MartinKolarik is right - it's a siren song, and we'd be unwise to add it to the core library. Promises are first-class citizens in ES6, but so are Sets and Maps, and the W3C is [working on Streams](http://www.w3.org/TR/streams-api/) - in the future maybe we'll have some canonical form of Observables, and CSP channels, and immutable data... you could make the same argument for all of those, and the result would be a library that grew harder to learn and maintain over time.

The best way for Ractive to support all those things, and others than haven't been dreamt up yet, is to have a robust adaptor API and a set of well-supported plugins. (The adaptor API isn't perfect - it's something we need to revisit post-0.8, but it's good enough that @rstacruz was able to add really good promise support without changing a line of code in Ractive itself, and I think that's really cool!)

**Comment by paul-bjorkstrand** [comment]
Ok, I understand the reasoning, and also understand why @MartinKolarik prefers the section syntax (hello transitions). Thanks for the feedback, and the explanations!
