### ISSUE TITLE
Nested manual updates fail at component boundary

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#1963]
Demo: http://jsfiddle.net/rich_harris/nj7sax49/

I have a hunch that this might be fixed by #1740, but let's see...

**Comment by marcello3d** [comment]
It also fails within a component: http://jsfiddle.net/nj7sax49/1/

**Comment by martypdx** [comment]
Something more fundementally broken with input and update: http://jsfiddle.net/nj7sax49/2/.

@marcello3d assuming you closed inadvertently?

**Comment by martypdx** [comment]
No wait, should be `updateModel`, not `update`! - but still looks broken

**Comment by marcello3d** [comment]
Closed by accident, sorry!
