### ISSUE TITLE
Unshift breaks template conditionals

### ISSUE THREAD

**Issue by alchen** [ractivejs/ractive#1965]
I haven't spent a long time with either Ractive nor this problem yet, so any direction is much appreciated.

I have the following template with conditional partials:

```
{{#each items}}
  {{#if attr1}}
    {{> partial1}}
  {{else}}
    {{> partial2}}
  {{/if}}
{{/each}}
```

The partial calls an expression: `{{{ linkify(attr1) }}}`.

All is good until I do `unshift`. To reproduce the error,

```
var items =  [{
     attr1: 'foo',
     attr2: 'bar'
 }, {
     attr2: 'bar2'
 }, {
     attr1: 'foo1',
     attr2: 'bar'
 }];

// a delayed loop I used for debugging
var i = 0;
setInterval(function () {
  if (i < 3) ractive.unshift('items', items[i]);
  i = i + 1;
}, 1000);

```

I get error messages from Ractive.js saying `Failed to compute "$linkify(attr1...`, but `attr1` is never referenced unless it's `if` tested. If I just change `unshift` to `push` the problem goes away.

**Comment by fskreuz** [comment]
I would be nice if you set up a jsfiddle for this. I'm pretty sure the error comes with a few additional information. Chrome's dev tools can also break on caught errors, so you might want to check why that computation error happens.

**Comment by alchen** [comment]
Please see the following jsfiddle: http://jsfiddle.net/alchen/jh189yyy/2/

I also found out it is only a problem if I reference attributes of an object in an `expression`. E.g.

```
    bar: function (attr) {
        return attr.x + 'bar';
    }
```

**Comment by alchen** [comment]
I tried to dig into the code a little bit; This is the best I can tell:
  1. Ractive inserts first item, and calculates `${bar(items-0-attr1)}.
  2. Ractive inserts second item, and sees that items-0 has change and attempts to recalculate the same `${bar(items-0-attr1)}`, because it was there earlier.
  3. But the new `items-0` doesn't have an `attr1`, so it throws an error when recomputing the expression.

`Push` is probably unaffected because the index part of the key path doesn't change. The only clean fix I can think of is to introduce an internal counter and a map from the counter to index so we always known where the `x`th element is at.

**Comment by Madgvox** [comment]
We should really consider rewording this warning, because this is at least the third instance of this question in a little over a month.

@alchen Check out what I wrote in #1951.

> The program isn't actually breaking, the `failed to compute` error is simply a warning that ractive sends in debug mode. Like @martypdx said in the other thread [#1924], the message is harmless other than an annoying console log, and it will get cleaned up in 0.8 due to his work in #1740. For example, I set a new value to `pros` after four seconds, and there are no after-effects of the warning: http://jsfiddle.net/hLym2xcy/11/

**Comment by alchen** [comment]
@Madgvox ah, yes, I did realize things are still rendered perfectly; I was just thinking whether the expression should be called at all. Certainly nice knowing it will be taken care of in #1740. Thanks for the reply!
