### ISSUE TITLE
Two-way binding does not work when the name attribute is before the type attribute

### ISSUE THREAD

**Issue by such** [ractivejs/ractive#1968]
Hello,

As you can see in this [jsfiddle](http://jsfiddle.net/bxxoq5pc/1/), two-way binding does not work when the name attribute is before the "type=checkbox" attribute. If the two attributes are switched, the "Select red" button will work perfectly.

This issue hit me hard because my template is generated with haml that automatically reorders attributes alphabetically.

Attributes order is not supposed to matter in HTML so it should be fixed or at least made clear in the documentation!

Thanks!

**Comment by Madgvox** [comment]
I'm sorry, I'm not seeing any issue in your fiddle. It seems to be working perfectly as far as I can tell. The only thing I'm seeing is an 'ambiguous reference' warning, due to the attribute `selectedColors` not being previously defined.

**Comment by such** [comment]
When you click on the "Select Red" button, the red checkbox is supposed to be checked. It is not the case when the name attribute is before the type attribute.
If that's relevant I'm using the latest version of Chrome.

**Comment by Madgvox** [comment]
Ah, I see what you mean now. Yeah, that definitely shouldn't be happening.
