### ISSUE TITLE
Find a parent component

### ISSUE THREAD

**Issue by arxpoetica** [ractivejs/ractive#1969]
This is probably a stupid question, but I've searched far and wide w/out finding a simple answer.

Is there a way to `.findComponent` for parents? This function seems to only know children, and `findParent` and `findContainer` don't seem to be geared toward finding components.

**Comment by zenflow** [comment]
```js
var Child = Ractive.extend({});
var Parent = Ractive.extend({
  template: '<Child />', 
  components: {Child: Child}
});
var parent = new Parent;
var child = parent.findAllComponents()[0];
console.log(child.parent==parent);
// => true
```

**Comment by martypdx** [comment]
`findParent` and `findContainer` return components. Checkout the tests for usage:

https://github.com/ractivejs/ractive/blob/dev/test/__tests/init/initialisation.js#L474-L577

**Comment by arxpoetica** [comment]
Thx, @martypdx I just checked the changelogs and learnt this. The documentation isn't clear on that point—I'll go help it out. ;)

**Comment by arxpoetica** [comment]
See https://github.com/ractivejs/docs.ractivejs.org/pull/210 and https://github.com/ractivejs/docs.ractivejs.org/pull/211
