### ISSUE TITLE
An overview of how the internals of Ractive work

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1972]
Been doing some deep debugging on 0.6 lately due to some quirks I couldn't understand and have gotten a broad overview of how the internals work. However, it would be nice if the documentation had an overview of the internals, the workflow of different operations, etc. Something as broad like:

- https://facebook.github.io/react/docs/reconciliation.html
- https://ellislab.com/codeigniter/user-guide/overview/appflow.html
- http://calendar.perfplanet.com/2013/diff/
- http://blog.bguiz.com/post/57373805814/accessors-vs-dirty-checking-in-javascript-frameworks/

Primary concerns would be:

- General workflow of internals
- Get and set
- Computed
- Observers
- Initialization and teardown
- DOM and component management
- Data ownership
- How it differs from React (vdom)
- How it differs from Ember (binding)

This would make good documentation, contribution reference, a blog post perhaps (for promoting), implementation reference (for competing with other libraries). Beside, been meaning to tear apart the code but still couldn't understand how each module interacts with the others. Thoughts?

**Comment by martypdx** [comment]
I'm trying to finish up last few issues of #1740 and then would be great time to tackle those as it will be very fresh in my mind.

**Comment by dagnelies** [comment]
Just for tracking: same as #47
