### ISSUE TITLE
Nested <p> elements in templates cause an error on initialization

### ISSUE THREAD

**Issue by TehShrike** [ractivejs/ractive#1974]
JSFiddle: http://jsfiddle.net/p9fmhwnr/2/

- **Reproduction**: attempt to initialize a Ractive element with this template string: `'<p>This template has a <p>nested paragraph</p> element, which isn\'t <em>great</em> but probably shouldn\'t error</p>'`
- **Expected**: the Ractive object should successfully initialize
- **Observed**: an error is thrown with this message:
```
ParseError: Unexpected template content at line 1 character 112:
<p>This template has a <p>nested paragraph</p> element, which isn't <em>great</em> but probably shouldn't error</p>
                                                                                                               ^----
```

Is this expected behavior?  I couldn't find any reference to this sort of behavior in the documentation.

I'm coming all the way from Ractive 0.4, so I have no idea when this might have been introduced.

Is there any way to disable this strictness?  I have a wiki-type cms that allows users to embed the html from Markdown documents inside of other html-from-Markdown documents, so enforcing this sort of by-the-books properness isn't going to be very practical for me.

Reproduced with latest and edge.

**Comment by martypdx** [comment]
Nested `<p>` elements are not allowed per W3C spec, see [this SO questions](http://stackoverflow.com/questions/9852312/list-of-html5-elements-that-can-be-nested-inside-p-element).

If you don't need binding within that content (in other words it's pure html and template), You can work around be using inserting the content via triple stache (see http://jsfiddle.net/p9fmhwnr/4/):

```js
 data: {
            content: '<p>nested paragraph</p>'
        },
        template: '<p>This template has a {{{content}}} element, which isn\'t <em>great</em> but probably shouldn\'t error</p>'
```

which, if it's static you might just use:

```js
 data: {
            content: '<p>nested paragraph</p>'
        },
        template: '<p>This template has a [[[content]]] element, which isn\'t <em>great</em> but probably shouldn\'t error</p>'
```

**Comment by TehShrike** [comment]
So this is intended behavior?  Sadly, these nested documents can include Ractive expressions, so I guess I'll have to work out some way to clean them up.

**Comment by martypdx** [comment]
> So this is intended behavior?

Yes, it's specifically coded in the parser [here](https://github.com/ractivejs/ractive/blob/dev/src/parse/converters/readElement.js#L22-L37)

> so I guess I'll have to work out some way to clean them up.

Could you use `Ractive.parse` or a third-party library to validate the user input?

**Comment by TehShrike** [comment]
All of the html comes from parsing markdown documents into valid template html - the difficulty is that I'm embedding one of these documents into the other after turning them into html.

It believe it's only going to be an issue for me on the server-side, so I think I can work around it by calling `cheerio.parse(html).html()` to clean up the html before handing it to Ractive.

I'm sad about this change in Ractive, but it makes sense.  Thanks!

**Comment by fskreuz** [comment]
Chiming in. I had this example once where when the browser sees an invalid element inside a parent, the parent closes and starts with the once invalid element. https://jsfiddle.net/uqq5Lrq8/4/ It appears that, while the spec says invalid, the browser does seem to render but it won't render the way you expect it to.

**Comment by TehShrike** [comment]
Yeah, the browser tends to make them all siblings of each other, which is fine for my purposes.

**Comment by Madgvox** [comment]
Just my two cents, but I feel like `Unexpected template content` is an unnecessarily cryptic error. It certainly doesn't really seem to be caused by a spec violation. Perhaps something like `[parent] elements cannot contain [child] elements according to the HTML spec [here]`.

**Comment by fskreuz** [comment]
@Madgvox checklist item for https://github.com/ractivejs/ractive/pull/1915? :D

**Comment by Madgvox** [comment]
@fskreuz You read my mind :)
