### ISSUE TITLE
Observer enhancements RFC plus BREAKING CHANGES

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#1975]
In closing in on getting #1740 done, I made some enhancements and changes:
#### `observeArray()`

Since array modification semantics are now more fully baked into viewmodel notifications, I added `ractive.observeArray()` that reports detailed array modification information.

The test probably explains it best:

``` js
const ractive = new Ractive({
    data: { fruits: [ 'apple', 'orange', 'banana' ] },
    oninit: function(){
        this.observeArray( 'fruits', shuffle => {
            t.deepEqual( shuffle.inserted, [ 'pear' ] );
            t.deepEqual( shuffle.deleted, [ 'orange', 'banana' ] );
            t.deepEqual( shuffle.start, 1 );
            t.deepEqual( shuffle.deleteCount, 2 );
            t.deepEqual( shuffle.insertCount, 1 );
        });
    }
});

ractive.splice( 'fruits', 1, 2, 'pear' ); 
```

`pop`, `push`, `shift`, `unshift` get converted to their `splice` equivalent. (`sort` and `reverse` current count as full array value sets).

Because `observeArray` now exists, I (breaking) changed the behavior of pattern observers that use `observe` to not report on index shifts and removals from the array. Part of the motivation is to avoid the class of console warnings lke #1965 that happen when deleted array members fire notifications to their dependants.

But more constructively, it means that you can observe properties of array members without the extra noise:

``` js
const ractive = new Ractive({
    data: { fruits: [
        { name: 'apple' },
        { name: 'orange' },
        { name: 'banana' }
    ]},
    oninit: function(){
        this.observe( 'fruits.*.name', ( n, o, k, i ) => {
            console.log( n, i );
        }, { init: false } );
    }
});

ractive.unshift( 'fruits', { name: 'pear' } );
// "pear", 0
// no cascade of index shift observers
```

likewise:

``` js
const ractive = new Ractive({
    data: { fruits: [ 'apple', 'orange', 'banana' ] },
    oninit: function(){
        this.observe( 'fruits.*', ( n, o, k, i ) => {
            console.log( n, i );
        }, { init: false } );
    }
});

ractive.set( 'fruits', [ 'apple', 'mango', 'banana', 'pear' ] );
// "pear", 3
// "mango", 1
```
#### `strict: true`

Per issues like #1627, I added a `strict: true` option that will prevent the observer from firing if value has not strictly changed, essentially shielding the observer from downstream changes:

``` js
ractive = new Ractive({
    data: { config: { foo: 'bar' } }
});

ractive.observe( 'config', function ( n, o, keypath ) {
    observed++;
}, { init: false, strict: true } );

ractive.set( 'config.foo', 'baz' );
t.equal( observed, 0 );
ractive.set( 'config', { foo: 'baz' } );
t.equal( observed, 1 );
```

Feedback welcome...

**Comment by guilhermeaiolfi** [comment]
What happen if the observed keypath is a object and later on an array?

It would be OK for me to get in the same ```observe()``` different arguments depending on the observed target.

That's possible, right? What do you think?

**Comment by martypdx** [comment]
Yes, that doesn't change from current behavior:

```js
var ractive = new Ractive({
	data: { fruits: [ 'apple' , 'orange', 'banana' ] },
	oninit: function(){
		this.observe( 'fruits.*', function ( n, o, k, i ) {
			console.log( n, o, k, i );
		});
	}
});

ractive.push( 'fruits', 'pear' );
ractive.set( 'fruits', { pear: true, apple: true } );
// apple undefined fruits.0 0
// orange undefined fruits.1 1
// banana undefined fruits.2 2
// pear undefined fruits.3 3
// true undefined "fruits.pear" "pear"
// true undefined "fruits.apple" "apple"

```

**Comment by guilhermeaiolfi** [comment]
Do we ready need ```shuffle.insertCount``` and ```shuffle.deleteCount```? 

Wouldn't it be always the same as ```shuffle.inserted.length``` and ```shuffle.deleted.length```?
