### ISSUE TITLE
ractivejs Chinese web

### ISSUE THREAD

**Issue by blueforest** [ractivejs/ractive#1976]
HI,Rich-Harris！
I come from china,you can call me seven,I am a web engineer .I am experienced with Ractivejs  for long time.I am  interested by MVVM provided by it.Now I want to build a Chinese Web about Ractivejs,I would like to be an official authorized user of you, and I am looking forward to cooperate with you

**Comment by Madgvox** [comment]
I'm afraid there's no such thing as an 'authorized' user of Ractive. If you wish to use ractive, you may! It's completely free for anyone to use. :smile:

You can download the latest version [here](http://cdn.ractivejs.org/latest/ractive.js), if you haven't already.
