### ISSUE TITLE
"Mapping does not have keypath, cannot set value."

### ISSUE THREAD

**Issue by bestguy** [ractivejs/ractive#1977]
Seeing an error using 0.7.3 that worked fine with 0.6.1.
I'm calling an ajax api which returns an array, then setting an existing property with the array value.  This triggers an error:

"Uncaught Error: Mapping does not have keypath, cannot set value. Please raise an issue at https://github.com/ractivejs/ractive/issues - thanks!"

This is using the ES6 syntax:

    module.exports = Ractive.extend({
      data() {
        return {
          people: []
        }
      },
      oninit() {
        xhttp({ url: '/api/people' })
          .then(people => {
            this.set('people', people);
          });
      }
    });

The error originates from ractive.js:14331

  	setValue: function (value) {
  		if (!this.keypath) {
  			throw new Error("Mapping does not have keypath, cannot set value. Please raise an issue at https://github.com/ractivejs/ractive/issues - thanks!");
  		}

  		this.origin.set(this.keypath, value);
  	},

when the error occurs, `this` is:

    Mapping {
	deps: Array[0],
	keypath: undefined,
	local: Viewmodel
	localKey: Keypath,
	origin: Viewmodel,
	unresolved: Array[0]
    }

I'm also using https://github.com/MartinKolarik/ractive-route, which could be part of the cause, but I'd like to understand what circumstances "Mapping does not have keypath, cannot set value" would get called.   Also would like to confirm I'm not missing anything obvious like "don't set an array in oninit", etc (as a fake example).

**Comment by martypdx** [comment]
Are you using the `Ractive.extend` as a component for which you are also passing in a people data key? Like:

`<component people='{{people}}'/>`

**Comment by bestguy** [comment]
Not exactly, using in ractive-route like so:

    var router = new Router({
      el: '#main',
      basePath: '/app' // TODO just use basepath always? Avoids SS coupling
    });
    router.addRoute('/people', require('./people/People'));
    ...

and it instantiates the component for you

**Comment by martypdx** [comment]
Having trouble reproducing in isolation: http://jsfiddle.net/uzt480dx/. Not sure how the router instantiates the components.

**Comment by bestguy** [comment]
Thanks, will take a look and see if I can repro there.

**Comment by MartinKolarik** [comment]
I haven't tested ractive-route with v0.7.x yet. Let me see if I can find source of the problem.

**Comment by MartinKolarik** [comment]
@martypdx 
>Not sure how the router instantiates the components.

Basically just calling `new Component()`.

@bestguy 
I couldn't reproduce this error. Mappings are used to map data between the main Ractive instance (initialized by ractive-route) and inline components used in the template, so the source of the problem is probably somewhere else. If you can create a jsfiddle or a small repo demonstrating this, it would be very useful.

**Comment by bestguy** [comment]
Thanks for the help, will try and reduce this down to a shareable example, will close if not able to reproduce.

**Comment by bestguy** [comment]
Also to clarify, this problem first appeared when I switched to using an async call (xhttp Promises) to set the `people` array, and only seems to be an issue with array - setting a string, etc seems fine.

**Comment by martypdx** [comment]
@bestguy what is the value of localKey? is it `people` or something else?

```js
Mapping {
deps: Array[0],
keypath: undefined,
local: Viewmodel
localKey: Keypath, // what is localKey.str?
origin: Viewmodel,
unresolved: Array[0]
}

**Comment by bestguy** [comment]
localKey: Keypath
      firstKey: "child"
      isPattern: false
      isRoot: false
      lastKey: "child"
      str: "child"
      parent: Keypath
        firstKey: ""
        isPattern: false
        isRoot: true
        lastKey: ""
        parent: null
        str: ""

**Comment by bestguy** [comment]
I can't reproduce this after reducing an example this down to Ractive, ractive-route, xhttp and simplifying the template, so must be some other issue or dependency.   Will close this and try to identify root cause.   Thanks for help, will reopen if need be.

**Comment by bestguy** [comment]
Seems to be a problem when I use a custom component when rendering each person in the array - not sure what I did wrong with it, but thanks for help narrowing issue.
