### ISSUE TITLE
0.7.3 Pattern observers not working in components for values mapped to parent data model

### ISSUE THREAD

**Issue by frenchroasted** [ractivejs/ractive#1978]
After upgrading from 0.6.x to 0.7.x, I noticed some differences in my app. I've boiled it down to a difference between observing someArray.* in 0.6.x and 0.7.x. I've made a couple of jsFiddles to illustrate the difference. The fiddles are the same except for the included ractive library, but they exhibit different behavior.

[Ractive 0.6.1 example](http://jsfiddle.net/frenchroasted/x9tunmd6/)
[Ractive 0.7.3 example](http://jsfiddle.net/frenchroasted/vn984r2L/)

In 0.7.3, the only observer that triggers is the statically-defined one (e.g. myArray.0.propName). The wildcard observer does not execute (e.g. myArray.*.propName). I didn't get very far in my debugging due to the complexity of the keypath/dep/mapping code, but I know the observers in my app are being defined and I can see the mappings back to the original data model. However, the observer execution just never happens.

For what it's worth, I also evaluated with "Edge" using jsFiddle's "Frameworks and Extensions" built-in, and Edge shows the same behavior as 0.7.3.

**Comment by frenchroasted** [comment]
I played with the jsFiddles a bit more and found that the pattern observers are equally blind to changes in objects, so it's not limited to array observation. I found "obj.*.a" was a working observer in 0.6.1, but it did not recognize changes to the object in 0.7.3.

**Comment by martypdx** [comment]
Thanks for the fiddles! Looks like it's related to data over the component boundary.

**Comment by frenchroasted** [comment]
You're right, my original title could have been more clear and accurate. I just updated the issue label. My temporary workaround is to iterate through indices/properties and set static observers on each, but that solution is... how to put it? Less observant than the pattern syntax. It may not catch all the different kinds of modifications on the object that I might care about. Given all the other fixes and improvements since 0.6.x, it seems a shame to revert to that older version because of this.

**Comment by Madgvox** [comment]
Here is another repro found by @dagnelies from #1988:

>  Hi,

> Here is the fiddle with `observe("*", ...)`:

> http://jsfiddle.net/mku42tuy/

> And here is the fiddle with `observe("value", ...)`:

> http://jsfiddle.net/mku42tuy/2/

> it results in the same for both latest and edge.

**Comment by dagnelies** [comment]
Just as a comment, I tried to debug/investigate it a little but failed miserably. Understanding even the basics of how it's working is quite tough.

So far, it appears that in `Viewmodel$applyChanges()`: `deps.observers` exist in one case, with the static observer, and that it does not exist when using the `*` wildcard pattern.

**Comment by dagnelies** [comment]
Further investigation and trying to understand what's going on.

In Viewmodel$applyChanges()  https://github.com/ractivejs/ractive/blob/db7a5d61730ad72857ae355597838b3d77f5bc28/src/viewmodel/prototype/applyChanges.js

Following happens:
1. When "value" observers are added to the root, it's present in `deps.observers`.
2. When "pattern*" observers are added to the root, it's present in `deps.patternObservers`.

The 1. happens for components too, but 2. seems to be missing/broken.

**Comment by dagnelies** [comment]
this illustrates the issue even better:

http://jsfiddle.net/mku42tuy/3/

The `observe("*")` doesn't work for keypaths resolving to parent instances, while `observe("value")` does.

**Comment by blackgate** [comment]
Same issue with pattern observers on arrays:
http://jsfiddle.net/np5ch3ot/

On 0.8 edge pushing to an array doesn't seem to work.

**Comment by Madgvox** [comment]
@blackgate The original bug has been fixed in 0.8, so your bug is distinct from that one and belongs in its own issue. I'm marking this closed, and I'll move your bug to a new thread.

**Comment by martypdx** [comment]
Fixed via #2296

**Comment by dylanbaxter** [comment]
Howdy gurus, maintainers and lurkers. I think I've run into this very same issue, on the latest version. Here's a fiddle demonstrating: https://jsfiddle.net/92ces3dc/
Help!
