### ISSUE TITLE
Get event value altered

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#1979]
Hi,  I have attached an event on multiple select elements like this:
```
<select value="{{offer_id}}" on-change="send_data">
<select value="{{product_id}}" on-change="send_data">
```

How to get which value changed inside the event?
```
	ractive.on('*.send_data', function(event){
              // How to know which select of all selects changed? eg. offer_id or product_id
	});
```

**Comment by Madgvox** [comment]
The simplest method would be to pass your own id into the event:

```html
<select value="{{offer_id}}" on-change="send_data:offer_id">...</select>
<select value="{{product_id}}" on-change="send_data:product_id">...</select>
```

```js
ractive.on( 'send_data', function( e, id ) {
  console.log( id ); // "offer_id" or "product_id"
});
```
---

If you really want to get exactly the keypath value, you can drill into the ractive binding, something I seriously **DO NOT** recommend you do. It's incredibly dirty, and much more likely to break in unexpected ways. You are also unable to customize the id you send to the function if you wanted to.

```html
<select value="{{offer_id}}" on-change="send_data">...</select>
<select value="{{product_id}}" on-change="send_data">...</select>
```

```js
ractive.on( 'send_data', function( e ) {
  console.log( e.node._ractive.binding.keypath.lastKey ); // "offer_id" or "product_id"
});
```

---

You could also wrap all your select keypaths in a container object, e.g. `selects`, and then setup an observer:

```html
{{#with selects}}
  <select value="{{.offer_id}}">...</select>
  <select value="{{.product_id}}">...</select>
{{/with}}
```

```js
ractive.observe( 'selects.*', function( newValue, oldValue, keypath ) {
  console.log( keypath ); // "selects.offer_id" or "selects.product_id"
  console.log( keypath.split( '.' )[1] ); // "offer_id" or "product_id"
});
```

You also have easy access to the value of the changed select with `newValue` using this method.

**Comment by fskreuz** [comment]
```html
<select value="{{offer_id}}" on-change="send_data">
<select value="{{product_id}}" on-change="send_data">
```

In my opinion, *you already know* which one changed in that you know that in the data, it's `offer_id` and `product_id`. All you need to do is hook up separate observers for each:

```
this.observe('offer_id', function(){/* offer_id changed */});
this.observe('product_id', function(){/* product_id changed */});
```

You can hook these 2 to call a third function to do your final task.

**Comment by Madgvox** [comment]
Very true, depending on what you're doing with the values, it may be more beneficial to split up the fields into separate observers. However, if you're doing very similar things with each of the fields, or if the number/type of fields is dynamic, it could be DRYer to use an event-delegation approach. If the fields are always static, it's probably more clear to split up each of the fields like @fskreuz suggests.

**Comment by kouts** [comment]
Thanks! I followed Madgvox's suggestion, passing my id on the event, but fskreuz's idea is also good, it's nice to have options.

**Comment by Madgvox** [comment]
Glad it worked for you! I'm going to assume your issue is resolved and close this thread. If you have any more questions or concerns feel free to reopen it at any time.

**Comment by fskreuz** [comment]
:+1:
