### ISSUE TITLE
event.index is undefined on custom proxy events

### ISSUE THREAD

**Issue by bensinober** [ractivejs/ractive#1982]
When using ractive-events-keys.js and probably any other custom proxy events, the event.index object is left undefined.

I've left a small jsfiddle to show the issue:
http://jsfiddle.net/u1fh11fd/

**Comment by ISNIT0** [comment]
@bensinober Do you mean like this? 
http://jsfiddle.net/u1fh11fd/1/

**Comment by bensinober** [comment]
Actually, that's a workaround, but will not work e.g. in nested templates.
I believe event.index should be an object containing all active indexes, at least it works this way for on-click.

I've demonstrated this with a nested fiddle here: http://jsfiddle.net/h25aytwk/
using on-click proxy event, you can see that event.index object holds both outer and inner index, whereas keypath only gives current path.

Using on-enter will leave event.index undefined, which is the bug I've submitted a pull request for.
Benjamin

**Comment by heavyk** [comment]
this is fixed in edge.

**Comment by Madgvox** [comment]
:+1:
