### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by markisus** [ractivejs/ractive#1985]
The link to download the plugin is broken here: http://ractivejs.github.io/ractive-transitions-slide/

It points to https://raw.github.com/ractivejs/ractive-transitions-slide/master/ractive-transitions-slide.js which is currently 404

**Comment by zenflow** [comment]
That would be an issue with in the ractive-transitions-slide repo. I've logged this issue there ractivejs/ractive-transitions-slide#9.

**Comment by Madgvox** [comment]
Thank you very much @zenflow! I'm going to close this issue as it's been moved.
