### ISSUE TITLE
Functions shouldn't get re-evaluated on outro

### ISSUE THREAD

**Issue by markisus** [ractivejs/ractive#1986]
Fiddle: http://jsfiddle.net/rdgs7rv2/3/

I have a list with some strings inside of it. I want Ractive to turn each string into an image through a function called get_url.

The relevant part of the template looks like 
```
 {{#game.cards}}
        <img intro-outro="slideh" src="{{get_url(.)}}" width="100em" height="100em">
    {{/cards}}
````

When the list is emptied, the images should slide out. But somehow the get_url function is getting called again with an empty argument after the list is emptied and the images are replaced with a default image (in this case a bee instead of a chair).

I'm pretty sure this is not the desired behavior, is it?

**Comment by zenflow** [comment]
I also noticed this behavior and found it undesirable.

For the record, this behavior occurs with nodes being removed, even without the outro directive. In the above fiddle, try removing the intro-outro attribute and adding a call to `console.log` or `alert` inside the `get_url` function. You will see that `get_url` is called 4 times (once for each image) immediately before the images are removed.

For my own purposes I used a work around, which is sufficient, but I do think changing it to only compute/render within *existing* nodes (including nodes being "intro"d, but not nodes being "outro"d or simply removed) would be an improvement, although I currently have no idea how hard this would be to implement.

Agree? Disagree?

**Comment by Madgvox** [comment]
If I'm understanding the changes from #1740 correctly, this issue should become fixed with 0.8. The new logic is a lot more choosy about when to attempt to evaluate a keypath, which helps improve performance, but should also prevent `get_url` from being evaluated again unnecessarily.

**Comment by heavyk** [comment]
this is fixed in edge.

updated the fiddle.
http://jsfiddle.net/9sy4upj8/

**Comment by Madgvox** [comment]
Fantastic! I will close the issue.
