### ISSUE TITLE
Backbone adaptor example has gone

### ISSUE THREAD

**Issue by marcosscriven** [ractivejs/ractive#1987]
There's a dead link here:http://docs.ractivejs.org/latest/using-ractive-with-backbone

If I could find it I'd offer a little PR for the docs, but wondering if it's just been removed entirely?

**Comment by Rich-Harris** [comment]
I'm afraid it's been removed! examples.ractivejs.org was updated a while back to supported dynamically loaded examples from gist.github.com, but a side-effect of that was that static files (such as the .json file used in the Backbone example) can no longer be imported - so we need to cobble together a different example. It's up there on the TODO list - in the meantime I've updated that docs page to reduce the confusion. Thanks for the prod

**Comment by Madgvox** [comment]
As this is a [pending issue](https://github.com/ractivejs/docs.ractivejs.org/issues/220) in the docs repo, I'm going to close the issue here.
