### ISSUE TITLE
Isolated works inconsistently in v0.7.3

### ISSUE THREAD

**Issue by arxpoetica** [ractivejs/ractive#1989]
I'm finding I need to explicitly find the parent or root, i.e., `this.root.set('etc')`, where in 0.6 I could do `this.set('etc')` and it would chunnel up to the surface until it found the correct parent component and variable.

It's not always behaving consistently now, and sometimes doesn't find the parent data.

(This is all relevant to `isolated: true`, or, in other words, the default.)

**Update: I meant `isolated: false` is the default.**

**Comment by martypdx** [comment]
I'm pretty sure `isolated: false` is the default. You should be able to `set` _as long as the data in the parent has been referenced (used) by the template, a `.get()`, or `.observe()`. 

If that's not the case, can you please provide an example?

**Comment by arxpoetica** [comment]
Sorry, you are correct, I *meant* `isolated: false` as the default.

As for the reference, is this documented somewhere? That seems like a big gotcha. What if I have some data stored in the parent, but have yet to use it anywhere.

Example scenario. (I'm completely inventing this. If we need to dig further, I can provide a real scenario.) Parent layout has `loaded` data variable, where several children need to know about it. `loaded` is set to `false` in the data initially (no `.set` or `.whatever`, it's just the default data assignment in the component).

```
var Component = Ractive.extend({
	data: function() {
		return {
			loaded: false
		};
	},
	...
});
```

Lets say all the children need to know the parent data is started as `false`. So each child component might do `this.get('loaded')` to check state.

You're suggesting that if nothing explicit has been done w/ the data in the parent _yet_ that the children won't know about the `loaded` variable? Or am I not following your description?

**Comment by evs-chris** [comment]
Way late here, but yes, the children won't know about `loaded` unless something explicit has been done.
1. the child has `loaded` mapped in e.g. `<child loaded="{{loaded}}" />`
2. the child has a reference to `loaded` in the template, which will cause an implicit mapping to grow
3. in 0.8 or later, the child has a context method force a resolution, essentially the same as 2 without template, by doing something like `child.getNodeInfo('*').get('loaded')`, which will also grow an implicit mapping
4. in 0.9 or later, the child can link to `loaded` at init using `this.link( 'loaded', 'loaded', { ractive: this.parent })`, which is effectively a mapping too

**Comment by arxpoetica** [comment]
Thx. I'm used to the behavior now
