### ISSUE TITLE
JSFiddle demo in documentation is broken

### ISSUE THREAD

**Issue by ISNIT0** [ractivejs/ractive#1991]
Getting the following error at the JSFiddle referenced by the transition documentation page:
"Uncaught ParseError: Cannot use reserved event names (change, reset, teardown, update, construct, config, init, render, unrender, detach, insert) at line 2 character 24:
    <button on-click='insert'>Insert item</button>"

Proposed fix:
Change event names.
http://jsfiddle.net/Hf2ea/24/

http://jsfiddle.net/rich_harris/Hf2ea/
http://docs.ractivejs.org/latest/writing-transition-plugins

**Comment by fskreuz** [comment]
@ISNIT0 probably best filed in the docs repo: https://github.com/ractivejs/docs.ractivejs.org/issues

**Comment by Madgvox** [comment]
As @fskreuz pointed out, this is more suited for the docs repo, so I'm going to crosspost this issue over there, and close this one. Thanks!
