### ISSUE TITLE
How to make Ractive to not auto instantiate

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#1993]
Ractive auto instantiates by default, is there anyway to make e.g:
```
var ractive = new Ractive({
      el: '#container',
      template: '#template',
      data: { name: 'world' }
});

ractive.init();
```

**Comment by Isinlor** [comment]
Hmm... Won't this work just fine ;) ?
```
var initRactive = function() {
    return new Ractive({
          el: '#container',
          template: '#template',
          data: { name: 'world' }
    });
};

var ractive = initRactive();
```

**Comment by fskreuz** [comment]
You can create the constructor first, then create an instance:
```js
var WorldRactive= Ractive.extend({
      el: '#container',
      template: '#template',
      data: { name: 'world' }
});

new WorldRactive();
```

**Comment by Rich-Harris** [comment]
Also, if by 'auto-instantiate' you mean that it renders to the specified `el` immediately, you can defer that:

```js
var ractive = new Ractive({
  template: '#template',
  data: { name: 'world' }
});

// some time goes by...
ractive.render( '#container' );

// bonus - ractive.render returns a promise that resolves when any
// intro transitions have completed, so you can do this sort of thing
ractive.render( '#container' ).then( function () {
  ractive.set( 'ready', true );
});
```

Demo here: http://jsfiddle.net/rich_harris/sfL875Lu/

**Comment by kouts** [comment]
Thanks all for your help, I think Isinlor's suggestion is the one that works for me.

**Comment by guilhermeaiolfi** [comment]
oh, I didn't know that we could use ```render``` for that. Nice.

**Comment by Worthaboutapig** [comment]
Yeah, I've wondered about this a while. The suggested behaviour of 'new Ractive()' (making it render on object instantiation) has massive side-effects, in fact the whole point is its side-effects, which is *really* bad practice for a constructor; even if it is convenient (I'll stop this long sentence now).

**Comment by evs-chris** [comment]
It is a _little_ side effecty, but if you don't supply a target or unparsed template, there is very little that happens beyond construction and a hook or two firing. Template parsing for non-trivial templates probably accounts for most of the non-render construction time.
