### ISSUE TITLE
enhancement request: putting expressions/functions outside `data` 

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1996]
Hi,

This is a humble request / vote to put expression functions outside `data` in the long term.

There are several reasons for this:
- functions are not data, they are functions, why are they here in the first place?
- I think it is a fairly common scenario that people use REST APIs to get/set the whole data at once. However, currently, this would blow up the helper functions. Sending the whole wouldn't work either, because the helper functions are mixed with the data.
- Combine this with potential adaptators which load/save your data automatically and the functions would be in the way too.

...this is of course not dramatic, simply putting the data in a specific place does the trick, but i still think keeping only data in `data` would be nicer.

So where would I put the functions? Ideally, I'd put them anywhere in the root, or in a predefined place like `functions` or `expr`, whatever.

**Comment by fskreuz** [comment]
I remember this one before, and I resorted to using computed props. There was also an example of helper functions in `Ractive.defaults` to patch in libs into components. Might help you with the globals issue too.

Here's the related issue: https://github.com/ractivejs/ractive/issues/956

**Comment by Rich-Harris** [comment]
Yeah, it has come up once or twice (gawd, more than a thousand? Get ready to party like it's #1999) - I can understand where you're coming from @dagnelies. It *is* something that you can do by adding helper functions to the prototype, but it could be more intuitive. I don't think it'll make it into 0.8 (want to limit the scope of that release), but consider it on the radar.

**Comment by evs-chris** [comment]
I just wanted to toss in my two cents that I'd like to keep the ability to have functions in the data intact because it can be pretty handy to swap out functionality (sorting, side-effecting - for shame, I know -, etc) from the viewmodel. I have been planning to experiment with something more akin to filters from other template systems, where the filter fn that lives outside the data is called with the Ractive instance as the context and the data as the first param, to see how that plays out.

**Comment by evs-chris** [comment]
I think with access to `@this`, `@this.root`, and `@shared`, there are a few reasonable places to put functions, so I'm going to close this.

**Comment by dagnelies** [comment]
out of curiosity, what's `@shared`?

**Comment by evs-chris** [comment]
It's like `@global` but only for ractive instances, so it's not subject to outside interference.

**Comment by dagnelies** [comment]
thanks for the info. Btw, good work.

**Comment by kouts** [comment]
So how to use this? something like `Ractive.shared.myfunc = function(){ ...` ?

**Comment by evs-chris** [comment]
@kouts, no it's only reachable in a ractive-observable way: `ractive.set('@shared.myfunc', function() {...})`. All ractive instances can read and write to the same `@shared` keypaths, and all ractive instances will receive updates as `@shared` keypaths that they reference change.

UPDATE: not sure how, but I typoed `set` as `get`
