### ISSUE TITLE
Feature request: @global

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#1997]
Hi,

Simple request: a new `@global` token to reference the global scope. Can also be seen as an alternative to #1996.

Sometimes, you don't want to add more and more stuff to ractive, or just use a lib out of the box.

For example, you could have lines like:
```
<p>{{@global.moment(isoDate).format('MMMM Do YYYY, h:mm:ss a')}}</p>
```
To see the given date using momentjs. This would be kind of handy.
This could also be usable for both expressions and method calls.

It would also be backward compatible with the existing stuff.

**Comment by Rich-Harris** [comment]
Finally merged this! http://jsfiddle.net/rich_harris/zpf48Lnu/

**Comment by dagnelies** [comment]
great great great! I'm looking forward to test this out! thanks again!
