### ISSUE TITLE
Retrieving the raw text between component tags

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#1998]
```html
<my-component>The quick brown {{foo}} jumps over the lazy {{bar}}</my-component>
```

How does one get the raw text `The quick brown {{foo}} jumps over the lazy {{bar}}` (with `{{foo}}` and `{{bar}}` not yet resolved, still in mustache form) from within the constructor of `my-component`? Something like:

```
oninit: function(){
  var rawContent = this.something;
}
```

I was planning on doing something creative with it. I have tried looking at `ractive.yield.template` and `ractive.partials.content` (which are identical) and they are already parsed (already in object form). Anything else I could look into? Possibly a `toHtml` or `toString`?

**Comment by Madgvox** [comment]
You can escape a mustache by prepending it with a backslash:

```html
<my-component>The quick brown \{{foo}} jumps over the lazy \{{bar}}</my-component>
```

This will prevent it from being executed by ractive. Depending on the complexity of what you're trying to do, you may then be able to extract the string literal from `ractive.partials.content` or `ractive.yield.template`.

**Comment by martypdx** [comment]
It's parsed when the outer template is parsed, so it's already a done deal.

**Comment by Rich-Harris** [comment]
I've occasionally wondered if it'd make sense to have a `stringify` function that was the counterpart to `parse`. Not in the core library, but as a separate thing. Some information gets lost (e.g. single versus double quotes, custom delimiters, whitespace and comments unless you set the appropriate options), but not much. There was never a compelling use case though... @fskreuz what's your scenario?

**Comment by fskreuz** [comment]
@Madgvox Yup, tried that, as well as using custom delimiters to avoid the parse, But I wanted it to feel more natural because the scenario is...

@Rich-Harris I'm building a i18n component

The idea was to harvest the text between the open and close tags of the component, and provide the dynamic data as `data`. The component is hooked up to a data source which determines the locale of the current user and fetches the appropriate translation texts. The component can then query the data source for the translated text, interpolate the data and render.

As to why I want to preserve the mustache - If in case the component fails to translate for whatever reason (translation doesn't exist, failed to fetch translations, missing data etc.), the component can either fall back to `{{yield}}` or interpolate again on the raw string manually.

**Comment by fskreuz** [comment]
@Rich-Harris the idea of `stringify` also sounds good, a counterpart of `parse`. Prior to this issue, I was also looking if `parse` allowed interpolation like `Mustache.render` - it doesn't.

So to add to that, maybe a `Ractive.compile` or `Ractive.render` (static functions) that allows creation of HTML using Ractive's rendering mechanism and mustache syntax but without creating an instance (skip all the process of binding, event handlers and all).

**Comment by evs-chris** [comment]
I have a wacky CMS system that builds pages that use Ractive using Ractive. I use separate delimiters for each of the two rounds of parsing, so the mustaches come out ok. What gets weird is when you start looking for your directives, event handlers, entities, and other bits and bobs like `<` in expressions in the output. I don't know if it would help the i18n case much, but having a stringier complement to `toHTML` would be lovely.

**Comment by fskreuz** [comment]
At the moment, got around it by skipping over parsed content from `partials.content` and just getting the strings:

```
function getTextFromContent(content){
  return content.reduce(function(text, potentiallyText){
    return typeof potentiallyText === 'string' ? text + potentiallyText : text;
  }, '');
}
```

And appear like so:
```
<translate>Hello <span>foo</span> world!</translate>

<span>Hello  world!</span>
```

**Comment by fskreuz** [comment]
Will close this one as I have ended up using the partials workaround. Will open a formal issue for stringify.
