### ISSUE TITLE
Replacing attributes with bindings

### ISSUE THREAD

**Issue by Kikimora** [ractivejs/ractive#2000]
I have an image like this
    
    <img src="/images/ajax-loader.gif"
             {{#submitting}}class="visible"{{/submitting}}
             {{^submitting}}class="hidden"{{/submitting}} />

Then following happens
1. submitting is false, img get class='hidden' correctly
2. I change submitting to true, img class change accordingly to class='visible' and I can see spinner.
3. submitting change to false again - entire class attribute disappear instead of change to class='hidden'

I found a workaround which is to keep attribute and only change it value. Like below.

    <img src="/images/ajax-loader.gif"
             class='{{#if submitting}}visible{{else}}hidden{{/if}}'
             />

For a newbie in Ractive like me this is confusing, at least there should be an exception or error message.

Thanks

**Comment by fskreuz** [comment]
Can we have a demo? What version of Ractive? Any errors on the console?

I tried replicating it using a div instead and toggling the way you did seems to work: http://jsfiddle.net/k15ck2yr/

**Comment by Kikimora** [comment]
Thanks for quick response. I was not able to reproduce this problem with your JSFiddle and in my source code. You can close this issue as invalid and I should go and get some sleep. 

PS: shame on me, issue number #2000 should be better than that :)

**Comment by Skyrpex** [comment]
I agree that it could throw a warning at compile time at least (not sure if it already does...)

**Comment by Madgvox** [comment]
No warning should be thrown, since the behavior described is supported by ractive.

**Comment by Skyrpex** [comment]
Oh, sorry about that then.

**Comment by Madgvox** [comment]
No problem, it's what I'm here for. :)
