### ISSUE TITLE
Bind context to ractive methods

### ISSUE THREAD

**Issue by atomiomi** [ractivejs/ractive#2002]
Hi! I have a lot of places in my code where method of some ractive instance should be passed as callback. 

For example:
```js
new Ractive({
    complete: function () {
        $(window).on('resize', this.onResize) // <--- here it is
    },
    data: {
        message: 'hello'
    },
    onResize: function () {
        console.log(this.get('message'))
    }
})
```

But the problem is that the context will be global object. Of course, I can bind context but by this approach method should be defined in `oninit`. But callbacks are wrapped when I use `this.on` to handle events and I like this behavior: http://jsfiddle.net/pvtabau9/. How can I bind context but define it method as normal?

**Comment by Madgvox** [comment]
You can bind a function to a context using the [`bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) method, so your example would become:

```js
new Ractive({
    complete: function () {
        $(window).on('resize', this.onResize.bind(this)) // <--- here it is
    },
    data: {
        message: 'hello'
    },
    onResize: function () {
        console.log(this.get('message'))
    }
})
```

**Comment by martypdx** [comment]
What @Madgvox said plus es6 fat arrows can be handy though not much shorter:

```js
$(window).on('resize', () => this.onResize() );
```

Some libraries (not jquery though) offer a this argument:

```js
library.on('resize', this.onResize, this);
```

__However__: sometimes end of ractive instance means end of browser window, but remember that you should remove handers unless you know the scope and lifecycle of the event emitter. 

This gets a bit messy in the amount of tracking that has to be done:

```js
new Ractive({
    complete: function () {
        $(window).on('resize', this.resizeHandler = this.onResize.bind(this) );
    },
    data: {
        message: 'hello'
    },
    onResize: function () {
        console.log(this.get('message'))
    }
    onteardown: function(){
       $(window).off('resize', this.resizeHandler);
   }
})
```

**Comment by Madgvox** [comment]
Yep, I was going to follow up to my previous post that if you need to support a browser older than IE9, you can also do this:

```js
var self = this;
$(window).on('resize', function() {
  self.onResize();
});
```

Which is basically the long form of @martypdx's example:

```js
$(window).on('resize', () => this.onResize() );
```

**Comment by martypdx** [comment]
The nice thing about using the Ractive event infrastructure is a) it puts the declaration in the template on the element where it's used, b) you get contextual binding, c) you can directly call instance methods if you want, d) it gets cleaned up as part of the instance lifecycle. 

I wonder if it would be useful to offer logic `document` and `window` element in the template:

```
<@window on-resize='resize()'/>
<@document on-mousemove='{{#dragging}}drag{{/}}'/>
```

**Comment by Madgvox** [comment]
That's an interesting idea, but I think it's kind of weird for a template to reach outside of itself. The more I think about it the more I like it though. :+1:

**Comment by fskreuz** [comment]
@atomiomi Event handlers are at the mercy of their callers. In the case of `this.on` and `this.observe`, the context is the instance because their handlers are at the mercy of Ractive. In this case of `$(window).on('resize', this.onResize.bind(this))`, jQuery holds control. A developer would easily say "Ahh, I expect `window`." - changing that expectation might lead to confusion.

I'm not saying it's impossible (the instance's handlers could be bound to the instance beforehand), but I think it's all about not making any surprises - which Ractive has been quite good at recently.

@martypdx Might be handy to put in a few more "environment"-related ones, especially those very handy ones. Posted this issue, building up from your idea. https://github.com/ractivejs/ractive/issues/2003

**Comment by atomiomi** [comment]
Thanks guys! I like your environment "components" idea. Now there is need to bind context, save reference to this handler and unsubscribe in `teardown` but all this things ractive do for local events. 

But for me it will be more convenient if in addition to your idea it is possible to attach handlers to global events as to component events:
```js
var ractive = new Ractive({
    oncomplete: function () {
        this.on('window.resize', this.resizeHandler())
    },
    data: {
        message: 'hello'
    },
    resizeHandler: function () {
        console.log(this.get('message'))
    }
})
```

**Comment by Skyrpex** [comment]
I just wanted to mention that you can also use [$.proxy](https://api.jquery.com/jQuery.proxy/).

**Comment by Rich-Harris** [comment]
Will close this as auto-binding is generally a Bad Idea, and it's easy to solve using fat arrows or `bind`
