### ISSUE TITLE
Initialisation options link does not work in Components | Docs

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2007]
In http://docs.ractivejs.org/latest/components#init the "initialisation options" link does not work (points to http://docs.ractivejs.org/latest/initialisation-options)

**Comment by fskreuz** [comment]
I think this is best posted in the docs repo.

**Comment by Madgvox** [comment]
@kouts I've crossposted this to the [docs repo](https://github.com/ractivejs/docs.ractivejs.org/issues/217), so I'm going to close the issue here. Thanks for the find! And thanks for the tip-off @fskreuz.
