### ISSUE TITLE
Ractive + Placeholder.js in IE < 10

### ISSUE THREAD

**Issue by paul-bjorkstrand** [ractivejs/ractive#2009]
Seems that we have a little bit of a collision when using both of these together. The problem is that Placeholder.js, when the field is empty, then the field is blurred, it will change the value of the field. This causes Ractive to fire observers due to the value change. Currently, I am just grabbing the placeholder value, and comparing it to newValue to skip the observer actions (and treating the placeholder value as empty/null).

Is there a more idiomatic way to solve the problem (perhaps a decorator or something)? Has anyone else run into this problem and/or have workarounds or a solution?

**Comment by fskreuz** [comment]
What I normally do in these situations where a plugin collides with Ractive functionality is to just create a component with the said functionality with just Ractive as much as possible.

What you can do is build a component that accepts `value` and `placeholder` as data, and internally has 2 inputs, one on top of the other. When the top one (the one you interact with) is blank, print the `placeholder` on the one underneath it. You can proxy the needed events from the input off the component manually.

Something like... this: http://jsfiddle.net/fb17mmsn/1/

**Comment by Madgvox** [comment]
Hey @paul-bjorkstrand, it's been awhile since you responded to this thread, so I'm going to mark the issue resolved. If this is not the case, please do not hesitate to reopen it at any time.
