### ISSUE TITLE
Textarea doesn't apply computed value while typing

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2011]
### Problem

When the computed property updates from input, it does set the data, but it doesn't re-render the text in the textarea unless the textarea is blurred. But it's not lazy. [Here's a very crude example](http://jsfiddle.net/6pvw6zss/3/).

Steps:
- Type "The quick brown {{fox}}" into the textarea.

Expected:
- Internal should show "The quick brown {{fox}}"
- Expected should show "The quick brown something"
- *Textbox* should show "The quick brown something" (replaces "{{fox}}" after typing the last `}`)

Actual:
- Internal shows "The quick brown {{fox}}"
- Expected shows "The quick brown something"
- Textbox shows "The quick brown {{fox}}"
    - Remove focus from the textarea, only then does the textbox update.

### Context

I have this component which accepts strings wrapped in `{{ }}`. When it meets one of these strings, it reverts the text it removes the `{{ }}`, but now styled with some CSS trickery. In the internal data, however, the string keeps the `{{ }}`, while a textarea presents the version without `{{ }}`. For instance:

- Text typed by user: `The quick brown {{fox}}`
- Value after typing the last `}`: `The quick brown fox*`
- Internal representation: `The quick brown {{fox}}`

Data can either be user input or provided via `value` property, so either can be the "source of truth". The `*` in the value above is a zero-width whitespace used to map existing styled text into their internal repesentation. That way, whenever Ractive cycles through, the component it doesn't revert the internal into plain text.

**Comment by martypdx** [comment]
If you explicitly set the `textarea.value` it seems to work: http://jsfiddle.net/6pvw6zss/4/.

Not sure computed vs observer matters, was just messing around to get a work around. Probably something in how textarea is being set...

**Comment by fskreuz** [comment]
@martypdx Yep, tried the following last night after the post:

- Hooking up observers for 2 props and modify each other (thinking it was a computed prop issue), still the same.
- Tried firing `update()` manually on the above, still the same.

However, if I run a timer that constantly alters the value while typing, it does seem to update the computed. http://jsfiddle.net/6pvw6zss/5/ Probably caused by how ractive does its set-compute-render routine?

**Comment by dagnelies** [comment]
btw, your original example gets updated once you move the focus away from the textarea ...just not while you're typing ...which would trigger a lot of other questions like: where should the cursor jump, etc.

**Comment by fskreuz** [comment]
Confirming that it's still happening in 0.8 version.

**Comment by Rich-Harris** [comment]
Looks like this is fixed now via #2199 – reopen if not

**Comment by fskreuz** [comment]
I wrote the intro right, but my steps to reproduce were wrong :facepalm: Sorry for that. Updated the description. Still "broken" on edge (wondering if it's broken, or it's just how Ractive works).

**Comment by Rich-Harris** [comment]
How do you mean broken? It won't update a focused input/textarea, if that's what you mean... just because that's a dreadful user experience (where does the cursor go on update?)

**Comment by fskreuz** [comment]
> How do you mean broken?

When I type `The {{fox}}`, after the last `}`, `{{fox}}` in the textbox should be transformed into `something` ([as sampled in the "Expected From Textarea" below it](http://jsfiddle.net/6pvw6zss/3/)). However, it doesn't. Only if I remove focus from the textarea does it change.

> where does the cursor go on update

I guess just after `something`, since the cursor was just after the text that transformed.

But again, if it's how Ractive works, I'm ok leaving this as a wontfix. :D

**Comment by Rich-Harris** [comment]
> if it's how Ractive works

yep. Manipulating an input under the cursor is a UX fail in the vast majority of cases – probably better to handle unusual cases like this one manually.
