### ISSUE TITLE
Use JSCS to enforce style guidelines

### ISSUE THREAD

**Issue by mrjoelkemp** [ractivejs/ractive#2015]
Any interest in using [JSCS](http://jscs.info/) to fail PRs that violate the styleguide?

This would likely have to wait until after 0.8 to avoid major code conflicts when fixing the existing style violations.

Happy to submit a PR when ready.

**Comment by Rich-Harris** [comment]
Yep, am +1 on this. We actually had a brief discussion on it some time ago (https://github.com/ractivejs/ractive/pull/666 - number of the beast) but we eventually decided we weren't ready. Would be good to revisit post-0.8, especially now that JSCS has some new features we probably need.

**Comment by mrjoelkemp** [comment]
Yeah, we have growing es6 support now and the [idiomatic preset](https://github.com/jscs-dev/node-jscs/pull/1069) is close to being merged (your interest will give us a nudge to finally get the blocker on that resolved). 

Plus, [autofix](https://github.com/jscs-dev/node-jscs/blob/master/OVERVIEW.md#--fix--x) (support for all rules is growing) can avoid a bit of the manual fixing necessary to bring JSCS to an established project.

Looking forward to it.

**Comment by evs-chris** [comment]
We now have eslint enforcing some styling. There are still a few rules that don't fit nicely, but we make work them in yet.
