### ISSUE TITLE
Accessing outer context's {{this}}? Ancestor references to {{this}} -- no {{../this}}?

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2017]
So i've got a pretty complicated thingy-ma-bob here with multiple loops within loops iterating over different data structures.

````
            <tbody>
                {{#rows:i}}
                <tr>
                    {{#_columns:j}}
                            ....
                                <ul class='popup'>
                                    {{#each types}}
                                        <li on-click='setType(i*page, ../this, this)' 
                                            class='{{ highlights[i*page]["type"] == this ? "active" : "" }}'>
                                            {{this}}
                                        </li>
                                    {{/each}}
                                </ul>
                            </td>
                            {{/if}}
                        {{/if}}
                    {{/}}
                </tr>
                {{/}}
            </tbody>
```

Here is where I need to get a reference to the parent context:

` <li on-click='setType(i*page, ../this, this)'`

My issue is that {{../this}} doesn't appear to work. It's always undefined.

Is there any other way of getting the outer context's scope?

**Comment by dagnelies** [comment]
Apparently, there is no way to reference the parent context itself, just properties relative to it, so it's kind of missing.

In the meantime, here is a workaround by using the keypath directly:
http://jsfiddle.net/cL4qnnoe/

**Comment by JonDum** [comment]
@dagnelies Thanks for the workaround! Pretty hacky, but it works.

**Comment by JonDum** [comment]
Actually... Not sure if I should have closed — maybe {{../this}} is a feature that should be in? Feel free to re-close if the lack of {{../this}} is intentional.

**Comment by dagnelies** [comment]
I personally think it should even simply be `..`

**Comment by evs-chris** [comment]
I think `..` is pretty important for relative keypaths and that it'd be hard to overload. I also feel like there should be a way to traverse the context stack. The first things that come to mind are in-template aliasing and special refs. There's probably an easy way to use some @martypdx magic to accomplish one or both in 0.8 or 0.9.

**Comment by evs-chris** [comment]
This is now possible in edge with aliasing: `{{#each array as outer}}{{#each outer as str}}<button on-click="foo(outer)">{{str}}</button>{{/each}}{{/each}}`. I think that's probably better than the confusion that usually surrounds ancestor traversal in iterations. I'm going to close this, but feel free to re-open if aliasing doesn't work for your use case.
