### ISSUE TITLE
Ancestor reference not resolving correctly

### ISSUE THREAD

**Issue by TehShrike** [ractivejs/ractive#2018]
Based on the [References](http://docs.ractivejs.org/latest/references) doc page, I would expect to be able to reference a parent's properties in an expression using something like this: `{{../name}}`

Testing with latest and edge versions, I can't seem to refer to properties of ancestors in this way.  The expressions always produce empty.

Duplication in this pastebin: http://jsfiddle.net/pxr6L387/1/

**Comment by evs-chris** [comment]
List keypaths are slightly different. You basically need an extra `..`, because you have to account for the part of the path with indices.

**Comment by TehShrike** [comment]
Huh - I see that `{{../../name}}` works, but I can't quite understand why - could you give me an example to help me grasp the object I'm actually referencing with the `../` in the example above?

**Comment by evs-chris** [comment]
```html
{{#each outer:i}}
  kp: 'outer.${i}'
  {{#each inner:ii}}
     kp: 'outer.${i}.inner.${ii}'
  {{/each}}
{{/each}}
```
So if you're at the inner `kp`, doing `..` once, gets you to `outer.${i}.inner`, which is the inner list. Adding a second `..` gets you to the place you really want to be `outer.${i}`.

It's a little confusing... I confused myself once or twice while writing this. Does that make it clearer?

**Comment by TehShrike** [comment]
I think so - it seems like my mistake was thinking of the tree in terms of the nested expressions, as opposed to the keypath required to uniquely identify the objects (which needs to include the array indexes).
