### ISSUE TITLE
is an empty object truthy or falsy?

### ISSUE THREAD

**Issue by skeptic35** [ractivejs/ractive#2024]
The answer seems to be "both", at least that's what this fiddle suggests: http://jsfiddle.net/z9uywar0/
One might argue wether ```{}``` should be considered truthy or falsy in that context but I fail to see how it can be both. Or maybe I just completely misunderstood the meaning of ```{{#value}}``` vs. ```{{^value}}```.  That's entirely possible...

**Comment by martypdx** [comment]
Change the test to `{{#if value}}` and you'll get results more like what you probably expect.

`{{#value}}` is implicit so in the case of an object, it gets treated as an `{{#each value}}` hash iteration, but in the case of `{{^value}}` is negation of `if`.

The only disagreement with js is `{{#if []}}` -> `[] is falsy (javascript disagrees)` which is an intention ractivism, though you could argue that `{{#each []}}` should be adequate for utlilizing array.  - and is what you get with `{{# []}}`

**Comment by skeptic35** [comment]
> Change the test to ```{{#if value}}``` and you'll get results more like what you probably expect.

I'm aware of that but that wasn't the point ;)

And I'm afraid I also have to disagree on ```{{#value}}``` being the same as ```{{#each value}}``` in case of an object (see http://jsfiddle.net/z9uywar0/2/). Imho ```{{#value:index}}``` would be the same as ```{{#each value}}```.
I don't have a problem with ractive treating things differently than javascript. In case of ```[]``` I think the "ractivism" (nice word) is more intuitive. So why not treat an empty object ```{}``` the same way as an empty array? I find it rather irritating that an empty object, as opposed to any other data type, is valid both for ```{{#value}}``` and ```{{^value}}```.

**Comment by Madgvox** [comment]
Would not be surprised if #1856 related.

**Comment by MartinKolarik** [comment]
@martypdx it seems that `{{#value}}` behaves like `{{#with value}}`, not `{{#each value}}`, so it should be probably changed to match the new `{{#with value}}` behavior.

**Comment by martypdx** [comment]
@MartinKolarik yep, that makes sense. What's the new behavior again?

**Comment by MartinKolarik** [comment]
@martypdx `{{#with obj}}` behaves the same way whether there's an `{{else}}` section or not - an empty object is always falsey.
