### ISSUE TITLE
HTML5 input range causes error

### ISSUE THREAD

**Issue by MCBotha-GiPLE** [ractivejs/ractive#2025]
This:
```<input type="range" min="20" max="80">80</input>```

Causes error:

```ParseError: Unexpected template content at line 19 character 45:
<input type="range" min="20" max="80">80</input>```

**Comment by Madgvox** [comment]
The input element [is empty](http://www.w3schools.com/tags/tag_input.asp). It cannot have child elements inside it. To set the value of an input field, use the `value` attribute instead:

```js
<input type="range" min="20" max="80" value="80"/>
```

**Comment by Madgvox** [comment]
Hey @MCBotha-GiPLE, since it's been awhile since you've responded to the thread, I'm going to mark this issue resolved. If this is not the case, please do not hesitate to reopen the issue at any time.

**Comment by MCBotha-GiPLE** [comment]
Apologies for not responding. Yes, it was a mistake in my side.
