### ISSUE TITLE
recursive components keypaths empty

### ISSUE THREAD

**Issue by felixhummel** [ractivejs/ractive#2026]
Hi,

I took an [example](http://jsfiddle.net/rich_harris/LDk5N/) that @Rich-Harris put together for [recursive components](https://groups.google.com/forum/#!topic/ractive-js/jGtCt3QDhqU) and began to adapt.

[Here's mine](http://jsfiddle.net/felixhummel/LDk5N/15/)

Changes I made:
- Replace `a` with `button`
- Add `on-click` handler and `*.debug` listener

Steps Taken:
- click "README.txt"

Expected:
- `keypath` is `"root.files.2.files.0.filename"`

Actual:
- `keypath` is `""`

Notes:
`ractive.get('root.files.2.files.0.filename')` returns `README.txt` as expected.
The same goes for all other buttons. Keypath is always "".

**Comment by defnull** [comment]
I ran into the same problem.

**Comment by ISNIT0** [comment]
That looks like the component's keypaths aren't flowing through components.

**Comment by TehShrike** [comment]
I just ran into this issue as well.  I'm trying to figure out how to have components emit events to a parent who will later change specific properties at the component's keypath.

**Comment by martypdx** [comment]
You can use `this.event.component` in the parent to get access to the component and then you don't have to worry about full path, just the local component path:

`this.event.component.set( 'filename', 'Foo' );`

**Comment by TehShrike** [comment]
I can use that as a hack to get around the issue, but I really want to know the keypath that the component is at.  This is roughly my use case: http://jsfiddle.net/fa04LLhe/2/

**Comment by martypdx** [comment]
> but I really want to know the keypath that the component is at

Right, you want `e.component.component.parentFragment.context.str` (see http://jsfiddle.net/fa04LLhe/4/), but in a supported API :)

**Comment by tmilker** [comment]
So what's the point of the proxy event's keypath if it doesn't ever get filled out?  This is kinda killing me with adding drag and drop support.

Best solution I can come up with is embedding the indexes of the containers and contained items as attributes and manually building a keypath to splice them around for dragging an item from one container to another.
