### ISSUE TITLE
Elements in `if` and `else` blocks visible at the same time

### ISSUE THREAD

**Issue by MartinKolarik** [ractivejs/ractive#2027]
See [this demo](http://jsfiddle.net/gc230cj9/) and click the button twice. Text nodes are removed immediately, but it seems that elements are waiting for the transition (which really has nothing to do with the if/else block) to complete.

**Comment by YRathod** [comment]
Not able to reproduce with test html page but able to reproduce on jsFiddle only.

**Comment by evs-chris** [comment]
Fixed in edge 😃
