### ISSUE TITLE
Getting Invalid Argument error when using ractive.set in ie11

### ISSUE THREAD

**Issue by mleeper** [ractivejs/ractive#2031]
I have a nested dropdown component and when I try to modify the data of any of the items in the dropdown I get an Invalid Argument error.  

Here is a sample data structure
```json
{
  "id": "menu1",
  "items": [
      {
          "name": "Item1",
          "id": "item1"
       },
      {
          "name": "Item2",
          "id": "item2"
       },
      {
          "name": "Item3",
          "id": "item3"
       }
  ]
}
```

I'm calling set inside of an event, when an menu item is clicked.

```js
function myClickEvent(event){
   this.set(event.keypath + ".active");  
}
```

Here is screenshot of the error in ie11.  
<img width="1297" alt="ie11debugger" src="https://cloud.githubusercontent.com/assets/4120952/8579250/58046ab0-2568-11e5-86c1-2c16d0c678a4.png">

<img width="1295" alt="ie11console" src="https://cloud.githubusercontent.com/assets/4120952/8579262/64185960-2568-11e5-8b04-ffb6bde61b8d.png">

The code works everywhere except internet explorer.  Any ideas on how I can fix this issue?  Thanks!

**Comment by evs-chris** [comment]
Can you put up a [fiddle](http://jsfiddle.net) to make it a little easier to track through?

**Comment by Madgvox** [comment]
Hey @mleeper, I've edited your comment just to make your code samples a little clearer.

As @evs-chris said, I think we need a bit more context for this problem. Can you create a test case in jsFiddle, or if not, provide some of the relevant template/ractive code?
