### ISSUE TITLE
no two-way binding with triple curlies?

### ISSUE THREAD

**Issue by jmellicker** [ractivejs/ractive#2033]
In this fiddle:
http://jsfiddle.net/ejruypwc/

if you type in the top textarea, there is the normal two way binding, but not in the bottom one.

Is this the intended behavior with triple curlies?

(Sorry if this should have gone on SO or elsewhere)

**Comment by Madgvox** [comment]
Here is perfectly fine, @jmellicker. :)

I'm not entirely sure why you would require two-way binding with triple mustaches, since input elements cannot render DOM elements and therefore have no need for escaped HTML.

**Comment by Rich-Harris** [comment]
Yep, this is intentional! I'm going to slap a 'better error' on here, since we print a warning in other invalid two-way binding situations.

**Comment by jmellicker** [comment]
Thanks!

**Comment by Madgvox** [comment]
In revisiting this issue, I discovered a strange behavior in 0.8-edge using the fiddle in OP (http://jsfiddle.net/ejruypwc/). If you type in the top double mustache textarea, the bottom triple mustache textarea gets updated on the first change, and then none afterwards.

**Comment by evs-chris** [comment]
The issues from @Madgvox last comment is fixed in edge, so I'm going to bump this back to better error.
