### ISSUE TITLE
Does Ractive have information about all instances on the page

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2035]
Was wondering if the Ractive global knows/has a reference of all the instances being created on the page. Or, if I take this question in another angle, how do I get hold of all the instances being created on the page without 1) resorting to monkey-patching the Ractive API and 2) without altering the load order/methodology of any files on the page.

**Comment by JonDum** [comment]
If you need to keep track of all the instances, it might be better to have a single large ractive instance that contains multiple [Components](http://docs.ractivejs.org/latest/components) (which are really just additional instances that ractive manages for you). Then you can use `.findAllComponents("type")` to get a reference to these components.
