### ISSUE TITLE
partial disappearing on unrender-rerender

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#2041]
Haven't had a chance to investigate this, but [this SO question](http://stackoverflow.com/questions/31437735/ractive-teardown-re-render-with-partials-doesnt-re-render-partials) seems to have found a bug with partials: http://jsfiddle.net/rbwtmxjn/. May already be fixed in #2022...

**Comment by evs-chris** [comment]
This is indeed working on edge.
