### ISSUE TITLE
Values not getting passed to component.

### ISSUE THREAD

**Issue by john-charles** [ractivejs/ractive#2042]
At takes a bit to exercise this bug, but doing anything like the following fiddle will reproduce the issue.
http://jsfiddle.net/johncharles/mwy1z4ok/6/

Basically values from the outer scope which get passed to a components `my-attr="{{myAttr}}"` don't always get passed. As I said simpler uses than the one above seem to work fine.

**Comment by evs-chris** [comment]
If you use camel casing on the binding, it works. (currentTab instead of current-tab)

**Comment by john-charles** [comment]
Thanks for the reply. I see it does. Casing is not explicitly called out in the documentation; however, passing camel case in the template is not the norm for component libraries. Both CanJS and Angular, I have not checked others, automatically convert `some-dashed-attr-name` to `someDashedAttrName`. Perhaps this should be called out more explicitly in the documentation.
