### ISSUE TITLE
Add support for Custom Element typeExtensions

### ISSUE THREAD

**Issue by paulie4** [ractivejs/ractive#2043]
The draft spec on Web Components Custom Elements (http://w3c.github.io/webcomponents/spec/custom/#extensions-to-document-interface-to-instantiate) describes a new HTML and DOM API enhancement that allows for a custom element to extend a native element. For example, you could extend the `<img>` element to add a caption feature to it. This new feature has worked for a while in standard Chrome/Chromium.

On the Javascript-side, they added an argument to document.createElement() to pass the typeExtension. They also added a special DOM node attribute, named "is", whose value is the typeExtension that's been registered in Javascript.

For example:
```
<img is="img-ext" src="http://lorempixel.com/400/200/nature" caption="This is my custom caption!" />
```
The typeExtension here is named "img-ext".  The JSFiddle link below shows this working (please run in Chrome/Chromium).  It also shows the same extended tag NOT working correctly when created by Ractive, since Ractive doesn't know about the special "is" attribute nor the new typeExtension argument to document.createElement().
http://jsfiddle.net/3c2pfhgL/1/

**Comment by Rich-Harris** [comment]
Closing – #2044 has been ported to the current dev branch and will be included in 0.8
