### ISSUE TITLE
Function.prototype.bind, PhantomJS and computed properties

### ISSUE THREAD

**Issue by nicolas-t** [ractivejs/ractive#2045]
Hey, me again :3

First, sorry for the unclear title, I still don't understand that much of the issue...  
   
I have a ractive view (I use backbone-adaptor) with computed properties

``` coffeescript
App.ViewRactive.DropoverTag = App.ViewRactive.extend
    tpl: '#dropover-tag-tpl'
    adapt: [ 'Backbone' ]

    computed:
        myProp:
            get: ->
                return @get('something')

            set: (myProp) ->
                @set('something')
                return myProp
```

When I instanciate it in my code it works well.
  
But when I instaciate it in the context of a unit test like this : 
``` coffeescript
        view = new App.ViewRactive.DropoverTag(
            el: $('#wrapper')
        )
```

I get this error : 
```
TypeError: 'undefined' is not a function (evaluating 'fn.bind(context)')
    at getComputationSignatures__bind (/vendor/ractive.js:15236)
    at getComputationSignature (/vendor/ractive.js:15206)
    at getComputationSignatures (/vendor/ractive.js:15185)
    at initialiseRactiveInstance (/vendor/ractive.js:15276)
    at /vendor/ractive.js:16778
    at dropover-tag-test.js:48:0 <- dropover-tag-test.coffee:43:12
```

If I "stub" my computed properties it works well : 
``` coffeescript
view = new App.ViewRactive.DropoverTag(
    el: $('#wrapper')
    computed:
        myProp:
            get: ->
                return 'a'

            set: (tagsIds) ->
                return 'b'
)
```

Any hint ?

thanks :)
  
  edit : yup, it's coffeescript, I can "translate" to js if you prefer.

**Comment by nicolas-t** [comment]
Ok, I think I got it, phantomJS run a javascript version that doesn't have Function.prototype.bind.
  
I'll try a polyfill and keep you updated.

**Comment by nicolas-t** [comment]
Yup, that was it.
Fixed with MDN polyfill : 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill

NIcolas

**Comment by Madgvox** [comment]
Ractive actually has a polyfill for bind implemented, but it is only included in the package if you're using the IE8 legacy mode. It would be great if we could detect phantomjs somehow and activate the polyfill for that.
