### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by basickarl** [ractivejs/ractive#2053]
I find it hard to believe that the specifications as to which browsers this supports is not listed on the front page. If it does exist somewhere it needs to be pointed out more clearly.

**Comment by Madgvox** [comment]
You're right, I swear there was a page with browser support details but I can't find it on a quick peruse through the website. As it stands, Ractive is supported on all major browsers and IE back to IE8, although IE8 requires the ractive-legacy version.

**Comment by MartinKolarik** [comment]
It's [at the bottom of README](https://github.com/ractivejs/ractive#browser-support).

**Comment by basickarl** [comment]
Martin I assume you did not read the bottom of the readme, it states one browser and nothing about which platform either. I'll give you an example; Chrome on Linux for example is stated as Chromium. Chrome on Android is also exists also.

**Comment by MartinKolarik** [comment]
"Tested successfully in IE8+ and all modern browsers." sounds pretty clear to me.

**Comment by basickarl** [comment]
No, the word "modern" is not very clear. "Modern" can imply modern when it was written, how long ago was it written? Was it written a year ago or yesterday? How long does "modern" stretch back in time? 

https://www.mozilla.org/en-US/firefox/releases/

What is modern in that list I have linked? Everyone is not running the latest browser version jfyi. The word modern is a good selling point for users to read more deeply about a product, it is a lazy word when used in a specification.

**Comment by basickarl** [comment]
I assume the product has been tested in various browsers and versions. I guess noone could of been bothered to create a file or update the readme once it was tested in said specific browser with said specific version.

**Comment by MartinKolarik** [comment]
I don't know if @Rich-Harris does some testing in older Firefox/Chrome/etc. versions before making releases, but since we support IE8, I think it's safe to assume that it'll work in Firefox 20 (probably even much older).

If you need to be sure that Ractive works in specific browser version, running the tests takes a couple of seconds...

There's an open issue somewhere about using Open Sauce for testing, so once we get that set up, the definition of "modern browser" can be made more specific.

**Comment by MartinKolarik** [comment]
Btw, there's also `testling` section in `package.json`, but I'm not sure if it's still relevant.

**Comment by martypdx** [comment]
> I assume the product has been tested in various browsers and versions. I guess noone could of been bothered to create a file or update the readme once it was tested in said specific browser with said specific version

@basickarl: We do our best. It is an open community and help is always appreciated.

**Comment by Rich-Harris** [comment]
> there's also `testling` section in package.json, but I'm not sure if it's still relevant

Yeah, that's pretty old, along with other stuff in `package.json`. Should probably have a spring clean before 0.8.

@basickarl we do our level best to help everyone out in the time we're able to devote to this project, but this is an independent volunteer-run effort. We're all pretty easy-going but no-one deserves to have snark thrown at them. Please consider your tone when posting.
