### ISSUE TITLE
feature request: ractive.sort

### ISSUE THREAD

**Issue by jmellicker** [ractivejs/ractive#2056]
Ractive is awesome for presenting lists. Lists often want to be sorted.

Therefore:

**Ractive.sort(keypath, type, direction)**

- keypaths can have wildcards *
- type = alpha, numeric
- direction = asc, desc

Arguments for feature:

1. You can make funny comments like "Working on getting this feature sorted" or "Sorting through this issue"

2. Large benefit/cost ratio (apparently the internet has not yet figured out a good way to sort objects)

3. React.js never saw it coming

**Comment by fskreuz** [comment]
It's nothing a computed property can't do :)

**Comment by jmellicker** [comment]
Understood. A plugin would be great. Not sure if it's cool to offer a bounty for something like this, but if it is, I do.

**Comment by fskreuz** [comment]
@jmellicker [You can always create a pull request](https://github.com/ractivejs/ractive/blob/master/CONTRIBUTING.md#pull-requests). :D

> If in doubt, submit the request - a PR that needs tweaking is infinitely more valuable than a request that wasn't made because you were worrying about meeting these requirements.

**Comment by ISNIT0** [comment]
http://jsbin.com/hugitaf/4/edit?js,output

**Comment by jmellicker** [comment]
awesome! Thanks @ISNIT0 !
