### ISSUE TITLE
if else with components?

### ISSUE THREAD

**Issue by bryansray** [ractivejs/ractive#2057]
I don't appear to be able to wrap an if/else around components without getting a

  Uncaught ParseError: Expected closing delimiter '}}' after reference at line 4 character 8:
    {{ else }}
       ^----

JSFiddle: http://jsfiddle.net/bryanray/xptenpk1/1/

Am I missing something here?

**Comment by martypdx** [comment]
Components are not void elements, you need to include the trailing solidus `/` if you don't want to write them as two separate tags:

```handlebars
{{ #if user }}
    <Comp1/>
    {{ else }}
    <Comp2/>
    {{ /if }}
```

see http://jsfiddle.net/xptenpk1/2/

**Comment by bryansray** [comment]
Wow. I feel really silly now. Thanks a ton, @martypdx
