### ISSUE TITLE
Size chart. 

### ISSUE THREAD

**Issue by xavierin** [ractivejs/ractive#2058]
Link: http://www.amazon.in/Raymond-Mens-Business-Shirt-8907115750856/dp/B00REI851W/ref=sr_1_1?s=apparel&ie=UTF8&qid=1438573520&sr=1-1&keywords=raymonds+shirts+for+men+XL
Size shows  X-Large 
However Size chart does not mention any information related to Small, Medium, XL and XXL. Customers are finding difficult to choose the size. Please research the issue and do the needful.

**Comment by martypdx** [comment]
@xavierin sorry, but need some more context to help with this issue. Is there a template or some code you can reference or show to enable us to do the needful?

**Comment by fskreuz** [comment]
It would be better if part of the code was placed here for future reference. Otherwise, if that link went dead, the whole thread would be useless.

**Comment by ISNIT0** [comment]
What's the policy on closing old 'clutter' issues?
