### ISSUE TITLE
is it possible to get component attributes?

### ISSUE THREAD

**Issue by simongfxu** [ractivejs/ractive#2059]
i have not seen it in any official document, so may be it is a feature request?

```html
<widget x="1" y="2" />
```

widget.js

```js
var widget = Ractive.extend({
    oninit: function() {
        var options = this.getAttributes()
    }
})
```

 this options in `widget.js` only get x and y without Ractive.defaults.data or any other external settings

**Comment by Madgvox** [comment]
All data attributes passed to components are set at the root level, so you can use `this.get()` to retrieve the root data object. Is there a scenario where you need a catch-all, instead of referring to the attributes as needed (i.e. `this.get('x')` or `this.get('y')`)?

**Comment by simongfxu** [comment]
@Madgvox 
I have made a component which has many complicated settings:

```html
<panel x="1" y="2" z="3">
    <!-- child compoennt -->
    <child ref="item" m="1" ... />
    <child ref="chart" n="2" ... />
</panel>
```

now the data object in `panel` will be

```js
{
    x: 1,
    y: 2,
    z: 3,
    item: {
        m: 1
        // any other attributes
    },
    chart: {
        n:2
        // any other attributes
    }
}
```

so the `child` component need to get all the attributes to set on the parent component

**Comment by fskreuz** [comment]
> so the child component need to get all the attributes to set on the parent component

There's 2 ways to do it:

In one end, you can use the [`{{>content}}`](http://docs.ractivejs.org/latest/components#content) mustache. This one follows closer to your description of "need to get all the attributes to set on the parent component"

Assuming you have that data in the containing component, you can pass them to `<panel>` via attributes. They get accessed by the inner HTML via the attribute names you used on `<panel>`. Will rename a few properties for clarity:

```html
<panel a="{{ x }}" b="{{ y }}" c="{{ z }}" stuff="{{ item }}" graph="{{ chart }}">
    <child ref="item" m="{{ a }}" ... />
    <child ref="chart" n="{{ b }}" ... />
    <!-- also access item as stuff, and chart as graph -->
</panel>
```

Inside `<panel>`'s definition, it should have the `{{>content}}` mustache where you want the inner HTML in `<panel>` to be positioned:

```html
<div class="panel">
  <header>...</header>
  <div>{{>content}}</div>
  <footer>...</footer>
</div>
```

---

The other way is to use `{{yield}}`. It's the same as `{{>content}}` except the data to be accessed by the inner HTML of `<panel>` doesn't need to be passed through `<panel>`. It can directly access the data from outside `<panel>`

```html
<panel>
    <child ref="item" m="{{ x }}" ... />
    <child ref="chart" n="{{ y }}" ... />
    <!-- can also access items and chart here -->
</panel>
```

Inside `<panel>`'s definition:

```html
<div class="panel">
  <header>...</header>
  <div>{{yield}}</div>
  <footer>...</footer>
</div>
```

**Comment by martypdx** [comment]
@simongfxu perhaps what you are asking is how to pass a set of values. If so, a keypath expression may be what you're looking for:

```html
<panel x="1" y="2" z="3">
    <!-- child compoennt -->
    <child ref="item" attributes="this['item']" ... />
    <child ref="chart" attributes="this['chart']" ... />
</panel>
```

**Comment by simongfxu** [comment]
@fskreuz @martypdx 
Thanks for your answers.
But I think i have not expressed my intention correctly.

My really intention is to let the attributes to be more flat.
**And keep these attributes in template file not in js file (more friendly to i18n and maintenance).**
So I assigned some attributes to the child component and reassemble them in some time.(not a good way indeed)

Why i did in this way becasue we can not set complicated attributes directly.

Just consider the `panel` has an attibute named `tabs`, and the format is an Array like this:

```js
var tabs = [
    {
        label: 'tab1',
        value: 'value1',
        ajaxUrl: '...',
        ajaxParams: {some other object},
        formatters:[some array]
    },
   ....
]
```

Attribute like `tabs` is complicated and we have only one way to do it: 

```html
<pane tab="{{tabs}}" />
```

But I do not think this is a good way:
> * not easy to see the whole settings, need to switch to js file
> * more work to do in js file if we need i18n
> * inflate the js file

so if wen can set attributes in this way:

```html
<panel
    tabs.0.label="tab1"  tabs.0.value="val1"  
    tabs.0.ajaxUrl="/abc" ...  />
```

would it be better?

**Comment by fskreuz** [comment]
@simongfxu 

> And keep these attributes in template file not in js file

By this,  you mean you want to hard-code the values in the template instead of using JS for it. No problem, but you still need a second component (`<tab>`) to make it more verbose. Either yields or content will work in this case.

```html
<!-- General look -->
<panel>
  <tab label="label1" value="value1" ajaxUrl="ajaxUrl1" />
  <tab label="label2" value="value2" ajaxUrl="ajaxUrl2" />
  <tab label="label3" value="value3" ajaxUrl="ajaxUrl3" />
</panel>

<!-- In panel component -->
<div class="panel">{{ yield }}</div>

<!-- In tabs component -->
<div class="tab">
  <div class="label">{{ label }}</label>
  <div class="content">{{ value }}</label>
</div>

```



Anyways, regarding dotted attribute support, there's an ongoing thread about its support https://github.com/ractivejs/ractive/issues/2060

**Comment by simongfxu** [comment]
@fskreuz 
Thank you very much! I do not know you guys are discussing it, really good.
:+1:

**Comment by Madgvox** [comment]
Ha, I actually opened that issue because of the experimentation I did with your issue! :smile:
