### ISSUE TITLE
Allow dots in component attributes to set non-root data

### ISSUE THREAD

**Issue by Madgvox** [ractivejs/ractive#2060]
As of now, dots in component attribute names (i.e. `<component foo.bar="foobar"/>`) are completely ignored. The value `"foobar"` is set on the key `foo`. The `.bar` part is completely dropped. Here's a working example: http://jsfiddle.net/c4ut7uc4/

According to a quick look at the [HTML spec](https://html.spec.whatwg.org/multipage/syntax.html#before-attribute-name-state), as far as I can tell dots in attribute names are completely allowed (The more you know!~). So an attribute name with a dot in it should either set `foo.bar` in the component to `"foobar"`, or it should set `"foo.bar"` to `"foobar"` in the root of the component, which can potentially cause its own issues due to a key name having a dot in it.

Or we could just scrap the HTML spec and throw an error. Either way I think leaving it the way it is is a totally unexpected behavior. Thoughts?

**Comment by ISNIT0** [comment]
I think we need to either stick to the HTML spec completely, or chuck it
out of the window completely. Half-way houses are really confusing.

I personally don't think it's worth having yet another spec (for Ractive
users to learn).

https://xkcd.com/927/

**Comment by Madgvox** [comment]
I agree completely, and I was originally thinking that throwing an error was the way to go until I took a look at the spec and realized that dots are allowed in attribute names.

Ractive's parser is already built pretty much to spec, this is just a weird edge case where attribute names are corresponding directly to keypaths.

**Comment by martypdx** [comment]
Setting aside other issues, is there a case where it would useful to allow this? Doesn't seem like it, but my thinking is sometimes limited :)

**Comment by Madgvox** [comment]
That's basically what I'm wondering. There has never been an issue AFAIK where someone wants to set a non-root keypath through component attributes. I guess my original question wasn't as focused as I intended. I meant to basically say, the current setup can lead to unexpected behavior, what action is reasonable to take to resolve the issue? 

After thinking more on it, the solution I'm leaning towards right now is to throw an error, as the argument can be made that attributes on components are not and should be treated as regular HTML attributes, and supporting multi-level keypaths on component attributes is essentially a non-issue from my perspective.

The only solution I feel is improper is to leave the behavior as-is.

**Comment by bryansray** [comment]
Would it be viable to support the HTML5 spec (with dot notation) and proviate a warning message in debug mode -- similar to the data: {} warning message that is provided?

**Comment by fskreuz** [comment]
I'm for supporting the spec of allowing dots. The problem is how does one access them especially in mustaches (`{{ }}`) and `get()`. It has been an issue on the following too:

- https://github.com/ractivejs/ractive/issues/1967
- https://github.com/ractivejs/ractive/issues/1864
- https://github.com/ractivejs/ractive/issues/744

**Comment by evs-chris** [comment]
FWIW, I think the most obvious behavior for `<Component foo.bar="{{baz}}" bippy.boppy.boop="10" />` to be (in component context) `this.get('foo.bar')` fetch the mapping `baz` and `this.get('bippy.boppy.boop') === '10'`.

**Comment by fskreuz** [comment]
@evs-chris sounds good to me. +1

**Comment by martypdx** [comment]
@evs-chris Other than two-way binding, it doesn't seem that `foo.bar="{{baz}}"` would be any different than `foo='{{ { bar: baz } }}'`.  Again, 2way caveat aside, why would we want two ways to do same thing?

**Comment by evs-chris** [comment]
@martypdx Fair enough. I was just going with the principle of least surprise(ing to me). It also feels a bit more natural and, for the lazy among us :raising_hand:, is fewer characters to type and less noisy to parse.

**Comment by evs-chris** [comment]
Turns out this was already possible in 0.9 (and probably 0.8), but there was a bug in the linking code that would make it effectively ignore all of the props in the keypath except the _last_ one.
