### ISSUE TITLE
How can I set partial parameter with only knowing its DOMNode?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2062]
Hi, 

I want to set a partial's parameter with only knowing its DOMNode which I find with jQuery. I can get the data, but I can not set: 

```js
setStatusLeds = function(){
  return $('.status-led').each(function(){
    var jqElem, pinName, actor, ractiveNode, ractiveData;
    jqElem = $(this);
    console.log(jqElem);
    ractiveNode = Ractive.getNodeInfo(jqElem.get(0));
    ractiveData = app.get(ractiveNode['keypath']);
    ractiveData['state'] = false;
    ractiveNode['ractive'].set(ractiveData);
    ractiveNode['ractive'].updateModel();
    return console.log("view.get: ", ractiveNode['ractive']);
  });
};
```

**Comment by fskreuz** [comment]
You might want to add a little more than that code, and perhaps a jsfiddle or something.

**Comment by ceremcem** [comment]
Here is the jsfiddle code: http://jsfiddle.net/nqk2nb03/3/ 

I expect (want to get) the following output: 
>this is the test partial for bar

**Comment by martypdx** [comment]
You can't set an expression, but you can set a value that the expression is dependent on. 

Where are the values coming from and how would you determine which value goes to which partial?

**Comment by ceremcem** [comment]
Here values are set by the `actor` object, which gets its data from a socket.io socket, and changes are sent via this `actor` object. 

A working example is here: 

```ls
set-switch-buttons = !->
  $ '.toggle-switch' .each !->
    elem = $ this
    elem-dom = elem.0
    pin-id = elem.prop 'value'
    actor = SwitchActor pin-id

    # make it work without toggle-switch
    # visualisation
    elem.change ->
      actor.send-event this.checked
    actor.add-listener (msg) ->
      elem.prop 'checked', msg.val
```

```html 
        {{#partial io_switch}}
          <input class="toggle-switch" type="checkbox" value={{.pin}} />
        {{/partial}}
```

I include a specific class name to the partial's first child (top level DOM object inside that partial) and use jQuery to iterate over them. 

What do you mean by saying "you can set a value that the expression is dependent on"?

**Comment by ceremcem** [comment]
Works as I expected: http://jsfiddle.net/nqk2nb03/4/

**Comment by ceremcem** [comment]
This is current behaviour with intended result: http://jsfiddle.net/nqk2nb03/13/

Following fiddle demonstrates our use case where we copy and paste the same partial with the same parameters but expect the [same results with the previous fiddle](http://jsfiddle.net/nqk2nb03/13/) : http://jsfiddle.net/nqk2nb03/14/

If we edit `createExpressionKeypath()` function as follows, we achieve what we want: 
```
  var keypath_id = 0; 

  function createExpressionKeypath(uniqueString) {
  	// Sanitize by removing any periods or square brackets. Otherwise
  	// we can't split the keypath into keys!
  	// Remove asterisks too, since they mess with pattern observers
        var i = uniqueString.replace(/[\.\[\]]/g, "-").replace(/\*/, "#MUL#")
        i = i.replace(/}$/, ", keypath____id: " + String(keypath_id) + "}" );
        i = i.replace(/{,/, "{"); 
        console.log("unique string: ", i); 
        keypath_id += 1; 
  	return getKeypath("${" + i + "}");
  }

```

Would it be possible to achieve the same result without editing Ractive.js?

**Comment by ceremcem** [comment]
@Madgvox Why is this issue closed? Both [setting different keypaths](http://jsfiddle.net/nqk2nb03/13/) and [setting same keypaths](http://jsfiddle.net/nqk2nb03/14) work in the same way? 

To make it short: Ractive widgets uses keypaths as id's for widgets (partial usages). In my case, every hardcoded widget may have different source, so every widget should be treated as it has different id from any other.

**Comment by Madgvox** [comment]
Oh, my apologies! I misread your last post and assumed that you solved your issue. I think I understand where you're coming from now.

**Comment by ceremcem** [comment]
No problem.

**Comment by Rich-Harris** [comment]
Hanging properties like `my_id` off a computed value is colouring a *little* outside the lines...

When you have a partial like this...

```html
{{>test-partial {name: 'foo'}}}
```

...Ractive internally changes it to this:

```html
{{#with {name: 'foo'}}}
  {{>test-partial}}
{{/with}}
```

The `name: foo` part could be any expression – and rather than recalculate its value each time it appears (for all Ractive knows it could be an expensive computation repeated thousands of times), Ractive recognises that it's the same each time and reuses the value. So you're adding different values of `my_id` to the same object.

The correct solution is probably to use components, since each component has its own context and can therefore set private props like `my_id` without interfering with anything else: http://jsfiddle.net/rich_harris/p11vyv0n/

**Comment by ceremcem** [comment]
Thank you for the explanation. As we build a relatively big [system with a partial module](https://github.com/ceremcem/aktos-website/tree/master/app/partials), I want to ask you if there would be a performance difference between component mechanism and [the patched version of ractive.js by me](https://github.com/ractivejs/ractive/issues/2062#issuecomment-139078828) before converting all partials to components.

**Comment by martypdx** [comment]
@ceremcem as it currently stands, components will take longer than partials. But really depends on how many instances, what quantity are you talking about?

Other option is include a property with a unique identifier in the "with" partial:

```
{{>test-partial {name: 'foo', id: getId() } }}
```

**Comment by ceremcem** [comment]
my patch does almost the same thing, under the hood. In our current point, a trivial system includes 41 partials and 120 usages. Our target applications might require about 100 partials and 300-500 usages.
