### ISSUE TITLE
textarea value attribute not w3c compliant

### ISSUE THREAD

**Issue by lazylester** [ractivejs/ractive#2063]
AFAICT (ref http://www.w3.org/TR/html-markup/textarea.html) 'value' is not a permitted attribute for a textarea tag. Perhaps many backends would render it anyway, however Rails will not, with good justification (w3c compliance). I know better than to try to submit a PR for Rails ActionView to introduce a non-compliant attribute!

This creates a problem with Ractive binding on textarea elements, which apparently requires a value attribute to be present, when served from a Rails backend.

One solution (if you agree that it's a problem) might be to allow binding to the contents of the tag, like this: `<textarea id='something'>{{text_contents}}</textarea>`. In order to be a non-breaking change, the value attribute will still need to be used, so a precedence needs to be defined to handle the case that both are present.

**Comment by evs-chris** [comment]
Out of curiosity, are you serving your template in a `<script>` tag? Typically frameworks don't care what you put in there, and they usually work out better for templates because the tags (components) and attrs don't get lower-cased.

**Comment by lazylester** [comment]
Yes, I have the templates inside <script type='text/ractive'/> tags.
And even inside these script tags, Rails view helpers for form elements are available and are properly rendered. Besides all the usual Rails form goodness, it means I can use Rails i18n translations and easily populate json initialization data.
I even go one step further, and my templates are written in HAML.
My views have so little HTML that I often forget how to write it!

**Comment by Rich-Harris** [comment]
Fixed in edge thanks to @evs-chris, closing
