### ISSUE TITLE
View got strange when call `instance.set('')` error

### ISSUE THREAD

**Issue by magicdawn** [ractivejs/ractive#2064]
when call `ract_instance.set('')` , we got an error `Uncaught TypeError: Cannot read property 'str' of null`

Then, other Ractive instance behaves unmormal, such as a `{{#each}}` loop whill not clear previous items, but append items to the iteration.

```html
{{#each list}}
    <div>{{ this }}</div>
{{/each}}
``` 

when list = [1,2]
```
<div>1</div>
<div>2</div>
```

when list = [1,3]
```
<div>1</div>
<div>2</div>
<div>1</div>
<div>3</div>
```

And a instance named a caused a error , other instance will be affected, That's the point.

**Comment by magicdawn** [comment]
BTW , I'm using v0.7.3

**Comment by fskreuz** [comment]
Shouldn't `{ this }` be `{{ this }}`?

**Comment by magicdawn** [comment]
@fskreuz yeah

**Comment by fskreuz** [comment]
Seems to work fine on the latest version: http://jsfiddle.net/6vack1zb/

Must be somewhere else in the code. Can you post the stack trace/console log as well as any related code? Better yet, try to reproduce the problem in a jsfiddle.

**Comment by magicdawn** [comment]
I can't replay the `do not clear previous item`, but I can show you that http://jsfiddle.net/6vack1zb/1/

a `set('')` error, will affect other instance

**Comment by fskreuz** [comment]
Oh, I see. So you're trying to clear the first instance.

`set` requires 2 arguments, the key and value. You're doing `set('')` which is throwing the error. This causes the code after that to not run, which is normal after a thrown error. Plus, `set` cannot be used this way.

If you want to clear the first instance's values such that you'll only see 1 and 3 from the second instance, you have several options:

- [`set('list', [])`](http://jsfiddle.net/6vack1zb/2/) - replace `list` with an empty array
- [`splice('list', 0, ract1.get('list').length)`](http://jsfiddle.net/6vack1zb/3/) - splices the array, removing all.
- [`reset()`](http://jsfiddle.net/6vack1zb/4/) - wipes everything in `data` for the instance.

**Comment by magicdawn** [comment]
Yeah. I just call the `instance.set('')` by accident. (I call `set(arg)` and expect the arg to be an object, but it's actually a empty string), so go next. Everything behaves strange.

I though an error caused by a special instance should not affect other instance. This shuld be considered as a bug.

**Comment by fskreuz** [comment]
It's not really a special case. It's just how JS works. Code never proceeds when it throws an error. http://jsfiddle.net/mu01Lj0k/ 

I believe it is more beneficial to the developer that Ractive to actually throw errors on erroneous API calls. If Ractive didn't throw that error and just absorbed it, your app would continue sending down a blank string instead of an object to `set` and wouldn't even know it happened until it's too late. :)
