### ISSUE TITLE
get('array-of-objects').splice(x,y) removes to much from the dom.

### ISSUE THREAD

**Issue by defnull** [ractivejs/ractive#2065]
This is the fiddle:
https://jsfiddle.net/ztzqdop6/22/

Removing any but the last element of an array (via `Array.splice()`) results in broken DOM. When iterating over an Array in a template, not only the missing item is removed but also parts of the following item.

**Comment by MartinKolarik** [comment]
Link for a fiddle without MIME type issues: http://jsfiddle.net/ztzqdop6/23/

Looks that `splice` works correctly, but the implicit `{{value}}` mapping doesn't update. Works correctly with explicit mapping or without component.

@defnull you can use `<Item value={{value}}/>` until it's fixed.

**Comment by evs-chris** [comment]
This is now fixed in edge.
