### ISSUE TITLE
Safari Only error - Requested keys of a value that is not an object

### ISSUE THREAD

**Issue by alsze** [ractivejs/ractive#2068]
Hi,

Been getting the following error only in safari:
"Requested keys of a value that is not an object"

It is on the expand function on line:
keys = value ? Object.keys(value) : null;

It errors on calling ractive.splice or ractive.push

Exact same code on chrome and firefox is fine

**Comment by Madgvox** [comment]
Do you have a repro in jsfiddle? Just calling `splice()` or `push()` doesn't error by itself.

**Comment by alsze** [comment]
I havent been able to replicate it in jsfiddle with a cut down version of my code but it is definitely erroring in my full code. I basically have an ontap that does a splice to delete an item.

I had to do a more specific test of value so it wont error

typeof value === "object" && value !== null

**Comment by Madgvox** [comment]
What are the values of `keys` that error out?

**Comment by alsze** [comment]
i have value = numbers ie 1, 2, 3 that gives the error in safari only
although typeof value === "object" is false in all browsers. a value of 0
or undefined is ok in safari

**Comment by Madgvox** [comment]
I'm afraid I'm lost. Is this code:

```js
keys = value ? Object.keys(value) : null;
```

in your code or Ractive's code?

**Comment by alsze** [comment]
hi yes,

the Object.keys(value) errors out in safari on numeric values. Not sure
why. I managed to get around it by testing whether it is an object or not
for now.

Havent been able to replicate it using a cut down version of my code. I
will going to slowly add back in code until it errors to find out exactly
what is causing it

Al

**Comment by fskreuz** [comment]
It's not Ractive's fault though. It's `Object.keys`'s fault. It's a breaking behavior between ES5 and ES6. [ES5 returns a TypeError](http://www.ecma-international.org/ecma-262/5.1/#sec-15.2.3.14) when the argument isn't an object, which appears to be what Safari is doing. [In ES6, it coerces the argument into an object and operates on it.](http://www.ecma-international.org/ecma-262/6.0/#sec-object.keys).

**Comment by alsze** [comment]
Ah right that makes sense. In which case shouldnt ractive check for this
before calling object.keys for compatibility?

**Comment by fskreuz** [comment]
I have never encountered such error in my endeavors. Plus, even if `Object.keys` did throw up unexpectedly, we wouldn't know why?

Would you mind putting the stack trace of the error here as well as the values you used when calling `splice` or `push`? How are you calling them? Where are you calling them (lifecycle event? computed property? etc.)
