### ISSUE TITLE
Policy for closing old and stagnated issues?

### ISSUE THREAD

**Issue by ISNIT0** [ractivejs/ractive#2070]
As with any Open Source Project, there will end up being random issues which are going nowhere, but are still clogging up the issues list e.g.
https://github.com/ractivejs/ractive/issues/2058

What are the RactiveJS Org's policies on closing these issues (and what counts as a dead issue).

**Comment by Rich-Harris** [comment]
Ha! Obvious spam like #2058 should just be closed in my view. We should probably go through old issues periodically and close any that have the `pending-clarification` label and no follow-up. As for feature requests that we sort-of-decided-against-but-not-explicitly, I suppose we just need to reach a proper decision.

Anyway, in the spirit of being more proactive about closing issues that don't require further action, I'll close this :) Happy to continue the discussion if anyone has any strong feelings about an official policy etc.
