### ISSUE TITLE
How to get path to the variable inside template to pass it to event processor?

### ISSUE THREAD

**Issue by alexmakeev** [ractivejs/ractive#2072]
Dear colleagues,
I need to process **remove_reminder** action for one of multiple **client.invitation** instances (depending on button pressed) without ractive desynchronization. I don't want to use **event.keypath**, cause it is not a good solution for neighbour issues (for example I want to trigger **remove_reminder** on other (not self) element.

Template
```
{{# multiple instances...}}
    <btn on-click="remove_reminder:{{ client.invitation }}">Remove Reminder</btn>
{{/}}
```
JS
```
oninit: function(){
    var self = this;    
    self.on({
      remove_reminder: function(event, invitation){
        invitation.reminder = null; // How should I use here self.set() ? No keypath available
      }
    })
```

#### I suppose there is (should be) something like that:
```
{{# multiple instances...}}
    <btn on-click="remove_reminder:{{ get_keypath(client.invitation) }}">Remove Reminder</btn>
{{/}}
```
JS
```
oninit: function(){
    var self = this;    
    self.on({
      remove_reminder: function(event, invitation_path){
        self.set(invitation_path + ".reminder", null); // now it is Ok
      }
    })
```

#### Does such helper exist?

PS: more over, **event.keypath** has a strange value of:
```
${{client_person_role:USER-broker_account-enrollments_roles-0-enrollment-client_persons_roles-0}}
```
and is not applicable at all. Probably the strange value is because I use *Mustache* alias **client_person_role**. Is that value format correct?

**Comment by Madgvox** [comment]
You can use `ractive.update()` to resync the data model with ractive:

```js
oninit: function(){
    var self = this;    
    self.on({
        remove_reminder: function(event, invitation){
            invitation.reminder = null;
            this.update();
        }
    });
}
```

**Comment by alexmakeev** [comment]
Yes, but it is not accurate, i.e. it invalidates the whole **this** template part.
The helper **get_keypath** could solve the issue, but have no idea how it could be implemented.

**Comment by evs-chris** [comment]
How about the `@keypath` special ref?

```html
<button on-click="remove:{{@keypath}}">Remove</button>
```

If you're inside an iterative section, the first param will be the keypath up to the index of the current item.

**Comment by evs-chris** [comment]
...and you can also pull the keypath from the event object for proxy (non-method) events. I always forget about that.

**Comment by alexmakeev** [comment]
Very near, but **@keypath** doesn't properly work inside alias blocks, it returns the value of:
```
${{client_person_role:USER-broker_account-enrollments_roles-0-enrollment-client_persons_roles-0}}
```

**Comment by evs-chris** [comment]
Ah... sorry, I missed the PS. If you're inside an expression context, as you would be with a `{{#with {...} }}` section, there's currently no really good way to keep the real context in scope that I'm aware of. You can get the base of it by manually passing it along e.g. `{{#with { ..., keypath: @keypath } }}`, but you'll have to  keep last bits built up manually if there are any.

`{{#each foos}}{{#with { bar: ., keypath: @keypath } }}{{#each .bars:i}}...<button on-click="doseomthing:{{keypath + '..bars.' + i}}">Yep</button>...{{/each}}{{/with}}{{/each}}` is very contrived, but hopefully useful.

Once #2022 gets merged in, I plan to revisit aliasing like #1722 as well as an aliasing directive that is more limited than with but keeps the links intact. It also may be possible to make `with` work in a bi-directional way after #2022, but I haven't looked at it too hard yet.

**Comment by alexmakeev** [comment]
@evs-chris, thank you for detailed answer, hope we could see something for such cases further!
Will use the ```{{#with { ..., keypath: @keypath } }}``` approach

**Comment by alexmakeev** [comment]
### Solution implementation
For thous, who are looking the solution for complex @keypath being processed correctly.
My solution uses a small parser that converts strange "${{...}}" keypath value into ordinal one. The only requirement is to place **", kp=@keypath"** to the end of alias (with) Mustache statement. Sorry for the complicated code (tried to make comments).

Parser function:
```javascript
var parse_keypath = function(kp){
  var re = /\$\{\{([-"\w:,]*)}}/; // The most inner ${{...}} block reg-exp
  var m;
  var substitutions = {};
  while ((m = re.exec(kp)) !== null) {
    var m_key = getRandomStr(5);
    if (kp.indexOf(m_key)!=-1) continue;
    substitutions[m_key] = {};  // Each ${{...}} block is being substituted by temporary unique str key
    kp = kp.replace("${{" + m[1] + "}}", m_key);
    var re2 = /([\w]*):([-"\w]*)/g; // Key-value reg-exp
    var m2;
    function get_substituted_value(value){
      value = value.replace(/-/g, ".").replace(/"/g, "");
      var value_parts = value.split(".");
      if (substitutions.hasOwnProperty(value_parts[0])){
        var new_root="";
        if (value_parts.length>1 && substitutions[value_parts[0]].hasOwnProperty(value_parts[1])){
          new_root = substitutions[value_parts[0]][value_parts[1]];
          value_parts.shift(); // Removing substitution
          value_parts.shift(); // Removing substitution key
        }else{ // the case of empty value_parts tail
          if (!substitutions[value_parts[0]].hasOwnProperty("kp")){
            console.error("Please, add \', kp=@keypath\' to the end of alias (with) Mustache statement.")
          }
          new_root = substitutions[value_parts[0]]["kp"];
          value_parts.shift(); // Removing substitution
        }
        value_parts.unshift(new_root);
        value = value_parts.join(".");
      }
      return value;
    }
    while ((m2 = re2.exec(m[1])) !== null) {
      var value = m2[2];
      substitutions[m_key][m2[1]] = get_substituted_value(value);
    }
  }
  var ret = get_substituted_value(kp);

  return ret;
};
```

Then use it at some Ractive helper:
```javascript
  onconstruct: function(options){
    var self = this;
    if (!options.data) options.data = {};
    options.data.ract_path = function(kp, additional_path){
      if (!kp){
        console.error("Please, pass @keypath to ract_path helper");
      }
      if (additional_path){
        kp += "." + additional_path;
      }
      return parse_keypath(kp);
    };
  },
```

Usage:
```
{{#USER.broker_account.enrollments_roles:i}}
  {{# { client_person_role: this.client_persons_roles.0, kp: @keypath} }}
    {{ ract_path(@keypath) }}
    {{ ract_path(@keypath, "client_person_role.invitation") }}
  {{/}}
{{/}}
```

Output:
```
USER.broker_account.enrollments_roles.0.enrollment
USER.broker_account.enrollments_roles.0.enrollment.client_persons_roles.0.invitation
USER.broker_account.enrollments_roles.1.enrollment
USER.broker_account.enrollments_roles.1.enrollment.client_persons_roles.0.invitation
```
