### ISSUE TITLE
How to profile user code, I spent 5000+ ms in `ract.set()`

### ISSUE THREAD

**Issue by magicdawn** [ractivejs/ractive#2073]
As I say, I have code like

![image](https://cloud.githubusercontent.com/assets/4067115/9349590/c28eabf6-467a-11e5-8477-40cb9cfdcb9a.png)

And that `set` step took 5000+ms at first, oh my god!
And I thought maybe i can profile, but i failed, it's all ractive.js inner call...
![image](https://cloud.githubusercontent.com/assets/4067115/9349784/2f51cc26-467d-11e5-8ede-a4a4678b42c0.png)

After my blind fix, I reduce the `set` time to 1500+ ms

my code look like
```
new Ractive({
    data: {
        list: []
    },
    computed: {
        filteredList: function(){
            // get the list, filter it
        },
        sortedList: function(){
            // get the filteredList & sort it
        }
    }
})

// and use `sortedList` in the template
```

I said `blind fix` above, I guess that some code maybe cause performance problem, and I fix it.
How to profile only user code

**Comment by LeJared** [comment]
Why don't you just put the ```console.profil``` right in the function you want to profil, e.g. in your ```filteredList``` and ```sortedList``` functions?

**Comment by fskreuz** [comment]
I think the Tree (Top Down) view would better display the profile. It shows function calls in sequence as you go deep into the tree. That way, you can easily see which call went for a stroll in a chain of calls.. Additionally, you could also use the flame chart, which works the same way but in the form of a chart.

Also use [blackboxing](https://developer.chrome.com/devtools/docs/blackboxing) in Chrome dev tools. That way, you can hide Ractive from stack traces and elsewhere, giving more focus on your code. This is really handy especially when you have deep component structures.

Also, you didn't show your filter and sort code but I'll take a shot in the dark. Computed properties get called very often. I'm not sure exactly when, but it's the most active site in a component. You might want to minimize the stuff done inside them.

**Comment by Rich-Harris** [comment]
I should just clarify one point: the effects of `ractive.set(...)` are actually synchronous, i.e. you should add `console.profile` and `console.time` commands like so:

```js
console.profile('modal-table');
modalRact.set('list', res.body.data);
console.profileEnd('modal-table');
```

The promise that gets returned fulfils when any transitions that happen as a result of the data changing (e.g. some rows slide in or out) have completed – this makes it easy to chain UI animations together, but you can ignore the `.then(...)` method if you're not doing that.

If you get a chance to try out the current development build I'd love to find out if it improves performance! You can find it here: http://cdn.ractivejs.org/edge/ractive.js Thanks :grinning:

**Comment by magicdawn** [comment]
Thanks. All.

> Computed properties get called very often. I'm not sure exactly when exactly they reevalueate ... You might want to minimize the stuff done inside them or optimize it so it doesn't eat up cycles and memory that much.

I got pretty complicated business logic here, and computed property really helps me originize the code.
And this make it hard to profile. 

@Rich-Harris nice job :+1:
