### ISSUE TITLE
How do we use parent variables in loop?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2074]
I want the following code show "connected" in all lines: 

```
        {{#partial switch-list}}
          <p> before loop: {{ .connected? 'connected...': 'disconnected...' }}</p>
          {{#my_list}}
            <p> looping: {{ .connected? 'connected...': 'disconnected...' }}</p>
          {{/my_list}}
        {{/partial}}
  ```

Usage: 
```
  {{>switch-list {my_list: ["hello", "world"], connected: true}}}
```

Displays: 
```
before loop: connected...
looping: disconnected...
looping: disconnected...
```

Here is the [JSFiddle page](http://jsfiddle.net/fvxmxh03/1/)

How can I use parent variable in loops?

**Comment by Madgvox** [comment]
You just need to go up a level:

```
{{#partial switch-list}}
  <p> before loop: {{ .connected? 'connected...': 'disconnected...' }}</p>
  {{#my_list}}
    <p> looping: {{ ../connected? 'connected...': 'disconnected...' }}</p>
  {{/my_list}}
{{/partial}}

**Comment by ceremcem** [comment]
Not working. Would you mind editing the JSFiddle page: http://jsfiddle.net/fvxmxh03/1/

**Comment by fskreuz** [comment]
As long as you don't have a property of the same name in the current scope, Ractive's natural "scope climbing" will work. Since `my_list` doesn't contain objects which have a property of `connected`, Ractive will look for it in the ancestor objects, until it can't find any on `data`.

[This should work just fine](http://jsfiddle.net/fvxmxh03/2/):

```
{{#partial switch-list}}
  <p> before loop: {{ connected? 'connected...': 'disconnected...' }}</p>
    {{#my_list}}
      <p> looping: {{ connected? 'connected...': 'disconnected...' }}</p>
    {{/my_list}}
{{/partial}}
```

**Comment by ceremcem** [comment]
Thank you!

**Comment by evs-chris** [comment]
For the ancestor reference, you actually need two steps, since the first refers explicitly to the list object. So `../length` is the list length and `../../connected` is `connected` on the list's parent.

**Comment by Madgvox** [comment]
Yeah, @evs-chris is right. I haven't used Ractive in awhile, I forget things like this :confounded:
