### ISSUE TITLE
Add support for computed promises

### ISSUE THREAD

**Issue by stiff** [ractivejs/ractive#2075]
Since ractive already uses promises as a part of its API, it seems logical to make a little step further: if a computed property returns a Promise, wait for it's resolution. For example:

``` coffee
computed:
  user: -> Q.xhr.get('/api/users', {id: this.get('user_id')})
```

in template: `{{user.name}}` currently will always output empty string since promise doesn't have a name.

Thanks in advance!

**Comment by Rich-Harris** [comment]
It's slightly tricky, because it's very likely that you need to show something (e.g. a loading indicator) while the promise is pending, and you need to handle error states as well. The [ractive-promise-alt](https://github.com/rstacruz/ractive-promise-alt) adaptor allows you to do that.

So in theory it should just be a case of rigging up that adaptor, and returning a promise from the computed property, but [I just tried that](http://jsfiddle.net/rich_harris/934thc6m/) and it causes an error. Marking this as a bug!

You can workaround it like so – it's not quite as elegant, but it works basically the same way: http://jsfiddle.net/rich_harris/xp67ng5z/

**Comment by stiff** [comment]
I think if you want to use progress tracking, loading indicators and other advanced stuff, then you should install plugin for that. But if you want a primitive operation with data types that are already returned by Ractive, I think you should be able to do that.

I tried both ractive-promise and ractive-promise-alt and they both attempt to write into the computed field.

**Comment by martypdx** [comment]
I don't know that we want computed properties to stray into the realm of asynchronous constructs. My gut says they need to remain synchronous and complete within the same update cycle as the values they depend upon.

Fetching an asynch value is best left to an observe and/or adaptor. The syntax is very similar:

```js
oninit () {
    this.observe( 'user_id', id => {
        this.set( 'user', Q.xhr.get( '/api/users', { id } ) );
    });
}
```

If we get around to implementing the `options` level observers syntax would be even closer:

```js
observe: {
    user_id ( id ) { 
        this.set( 'user', Q.xhr.get( '/api/users', { id } ) );
    );
}
```

**Comment by stiff** [comment]
Well, that's true — proper tracking of the dependencies in async calls is very very tricky.

The point that writing code declaratively rather than messing up with random `.set()`s is a much more viable way in a large project. But if you don't think it's worth the effort, feel free to close this issue, because naive implementation may easily lead to confusion.

**Comment by Rich-Harris** [comment]
Thanks for understanding. I think we should leave this issue open anyway to see if we can figure out a way to let adaptors play better with computed properties.

**Comment by heavyk** [comment]
when I was reading #2130, an idea occurred to me. both of you could actually use async with computed properties like this:

http://jsfiddle.net/a64ct27n/

imo, just ditch the promise idea altogether. I have used that promise-alt plugin, and tbh, it's a bit of a pain in the ass (not the plugin, the nature of promises). if you need to amend your resolved promise in any way (infinite scroller or modifications, all kinds of weird bugs popped in for me when modifying `mypromise.result` (I think it had to do with the gc). now I use a pattern which does the same thing in async. I might have a go at using this pattern actually. seems solid.

cheers

**Comment by evs-chris** [comment]
Punting to #2512
