### ISSUE TITLE
layout control

### ISSUE THREAD

**Issue by arisAlexis** [ractivejs/ractive#2076]
Hi, former marionette user here but I like the simplicity.
Whats the best practise on how to know which views are open at a point in time and performing either model updates on them or tearing down?
For example I would like to use socket.io to get real time updates and notify the view instances about new data to render but I need a reference to them from the dispatcher. 
I could do it manually just wandering if people here can sugget something. I am also worried about stale views/memory leaks.

Thanks

**Comment by fskreuz** [comment]
You could create a "top-level component" that accepts the data. In that component, you include other components, which serve as your views. Then that top-level component distributes the data according to the components that need it. You can use conditionals to know which component appears when.

**app.html** 
```mustache
{{#if channelList }}<channel-list channels="{{channels}}"/> {{/if}}
{{#if chatView }}<chat-view user="{{userId}}" otherPerson="{{otherPerson}}"/>{{/if}}
```

**Comment by arisAlexis** [comment]
Ok nice example. 
In another example if I use the router to destroy a view and render another one in its place how would I obtain a reference to that? Havinf an app.mainView.childview object?

**Comment by fskreuz** [comment]
Depends on how you do your render and destroy, which would be nice if you put an example here too.

**Comment by arisAlexis** [comment]
I havent coded anything yet. If I attach a new ractive instance in the same dom element will the previous one get destroyed/unrendered automatically?

**Comment by martypdx** [comment]
Generally using a higher-level component makes most of these tasks easier because you're "updating the data" rather than trying to find and manipulate views.

> If I attach a new ractive instance in the same dom element will the previous one get destroyed/unrendered automatically

Yes, Ractive will teardown existing instance rendered to a DOM node.

You can also use `Ractive.getNodeInfo(node)` to get access to the ractive instance associated with a DOM node

**Comment by fskreuz** [comment]
@arisAlexis Here's an example of routing and dynamic data in Ractive. Post is long though, so I'll just reference it: http://stackoverflow.com/a/31334842/575527

Essentially, that "top-level component" becomes your router/dispatcher in that it is responsible for who renders when, and who renders what.

**Comment by arisAlexis** [comment]
Thanks all for answers. As my project is a big and I need to run auth checks before routing etc I will go with page.js and write a blog post afterwards :)

**Comment by jmellicker** [comment]
By the way @arisAlexis, we are using page.js with Ractive and check auth in the * route, then the components observe that data when it arrives and configure themselves appropriately. It's working great. If I can be of any help, let me know!
