### ISSUE TITLE
where can we find the roadmap ?

### ISSUE THREAD

**Issue by bang88** [ractivejs/ractive#2077]
The next version of Ractive we have wait a long time,can we have a timeline ,thanks

**Comment by Rich-Harris** [comment]
I'm afraid we adhere to the John Carmack 'when it's done' philosophy of release cycles around here, much as we try to be a bit more disciplined. The good news is that the big chunk of work standing in the way of the next version (0.8) has been merged, so now it's a case of fixing any major bugs and tidying up the build a bit. Next couple of weeks hopefully, depending on how things go!
