### ISSUE TITLE
List sort doesn't work with magic mode

### ISSUE THREAD

**Issue by Ghazgkull** [ractivejs/ractive#2078]
The [Indirect Dependencies](docs.ractivejs.org/latest/dependants#indirect-dependencies) documentation shows an example of using a template with a sorted list. In the example, when you change the value of the sort property, the template get re-rendered. Happy day.

But it looks like this same simple example doesn't work using magic mode? I put together a quick fiddle which demonstrates the problem. At the very end, I change the name of a list item using plain Javascript, but the list doesn't get re-sorted. If I make the same change using ractive.set(...), it works.

https://jsfiddle.net/Ghazgkull/e92s4t5x/5/

Is this expected behavior? Is there any kind of workaround other than not using magic mode?

**Comment by martypdx** [comment]
> Is this expected behavior? 

don't think so

> Is there any kind of workaround other than not using magic mode?

adding `ractive.update( 'sort' )` updates the sort, so maybe do something like:

```js
ractive.observe( 'list.*.name', function() {
	ractive.update( 'sort' );
});
```

see https://jsfiddle.net/e92s4t5x/6/

**Comment by evs-chris** [comment]
Punting to #2512
