### ISSUE TITLE
Refer to multiple variables in a single keypath

### ISSUE THREAD

**Issue by Kricket** [ractivejs/ractive#2081]
See stackoverflow question here: http://stackoverflow.com/questions/32253618/reference-a-variable-index-in-an-array-keypath

Essentially: suppose I have
```javascript
var x = new Ractive({
  data: {
    arr: ['a', 'b', 'c'],
    currentIdx: 0
  }
})
```
I'd like to be able to access `arr[currentIdx]` with a single keypath, e.g. `x.get('arr[currentIdx]')`. Is there any way to do this, or would it be possible to add it?

**Comment by Madgvox** [comment]
`x.get()` does not parse expressions, it simply returns the contents of a keypath. What you want is this:

```js
x.get( 'arr[' + this.get( 'currentIdx' ) + ']' );
// or more compact
x.get( 'arr.' + this.get( 'currentIdx' ) );
```

**Comment by martypdx** [comment]
Beyond what @Madgvox said about `ractive.get`, in the template you _can_ just directly write:

`{{ arr[currentIdx] }}`. 

You can also create a computed property:

```js
computed: {
    current: '${arr}[$[currentIdx}]''
}
```

and then refer to it via `x.get('current')`.

```js
var x = new Ractive({
  el: 'body',
  template: '{{ arr[currentIdx] }} {{ current }} {{ log }}',
  computed: {
  	current: '${arr}[ ${currentIdx} ]'
  },
  data: {
    arr: ['a', 'b', 'c'],
    currentIdx: 0
  }
})

x.set( 'log', x.get( 'current' ) );
```

**Comment by Kricket** [comment]
Ahh, good idea about the computed property; I hadn't thought of that.

Still, would it be too far out of scope to suggest adding this sort of thing to keypaths? Maybe something to change the syntax a little, like `x.get('arr[@currentIdx]')`. The computed property is a good idea, but it seems a bit like overkill to create a new one every time I want to make a one-shot get() a little more concise.

**Comment by martypdx** [comment]
With ES6 you can just write: ``` x.get(`arr.${currentIdx}`) ```. 

So given these minor inconveniences are being addressed in js proper, I don't know how pressing it would be to include this in Ractive. But, PR's always considered :)

**Comment by Rich-Harris** [comment]
Or you could hack the prototype! Demo: http://jsfiddle.net/vx4v0ep0/

```js
var get = Ractive.prototype.get;
var computedProp = /\[(\w+)\]/g;

Ractive.prototype.get = function ( keypath ) {
  var ractive = this;
  keypath = keypath.replace( computedProp, function ( match, sub ) {
    return '.' + ractive.get( sub );
  });
    
  return get.call( ractive, keypath );
};
```

**Comment by martypdx** [comment]
> hack the prototype

:+1:

**Comment by Kricket** [comment]
Concerning ES6: that would still require 2 get() calls, wouldn't it?

Would it be difficult to hook get() into the mustache parser? Because unless I'm mistaken, it is possible to do `{{arr[currentIdx]}}` in the template...

**Comment by martypdx** [comment]
> Concerning ES6: that would still require 2 get() calls, wouldn't it?

It's always going to be two get calls: 1) get the current index, 2) get array member at that index.

> Would it be difficult to hook get() into the mustache parser? Because unless I'm mistaken, it is possible to do {{arr[currentIdx]}} in the template...

The mustache parser creates JSON which at runtime gets turned into three things: References for the two items mentioned above (index and array) plus a third keypath expression to manage the dependency updates and to execute the combinatorial get.

IMO, sticking with vanilla keypath expressions in API calls maintains a level of sanity. I expect confusion levels would rise if we supported full expression syntax in api gets.

Adding methods to `Ractive.prototype` is _highly encouraged_ and seems like the way to go on this one.

**Comment by Madgvox** [comment]
Just to add my two cents, I've never really run into any issues with the single-keypath nature of `get()` in my own app. The whole point of expressions in templates is to leverage the power of javascript in a template, so moving the responsibility of executing an expression to ractive inside your javascript is essentially moving your javascript to text so that it can be parsed and executed as javascript.

**Comment by Kricket** [comment]
Highly encouraged, eh? I must be too used to java...
Thanks for all your suggestions.
