### ISSUE TITLE
no this.parent in onconstruct of component in 0.8.0

### ISSUE THREAD

**Issue by skeptic35** [ractivejs/ractive#2091]
Tried to run our application with the edge version (as I am really looking forward to it's release :) ). 
Alas I didn't get very far. I have a widget that produces a menu and that is used both as a component and 'standalone' and I need to be able to tell these two cases apart. Therefor I check for ```this.parent``` in ```onconstruct```.  But in 0.8.0 ```this.parent``` always seems to be ```null```, at least in ```onconstruct```. See here: 
http://jsfiddle.net/muqxqbrv/ (edge)
http://jsfiddle.net/muqxqbrv/1/ (latest)

**Comment by Rich-Harris** [comment]
Fixed in edge thanks to @YRathod
