### ISSUE TITLE
Ractive error when a component was torn down that had a `'self.root.observe()'`. (v0.7.3)

### ISSUE THREAD

**Issue by jmellicker** [ractivejs/ractive#2093]
We saw this error when a component that had a `'self.root.observe()'` was torn down:

![image](https://cloud.githubusercontent.com/assets/8551583/9588659/56b0f5ac-4fde-11e5-9bcf-eb70b700573f.png)

The issue was solved when we manually canceled all root observers (`.cancel()`) before the component was removed.

Is it possible that listeners to data in the root (or other components) are not torn down when a component is?

Thanks for any insight!

**Comment by Rich-Harris** [comment]
Was the error happening when the observer was called after the component had been removed?
Observers are (or at least should be!) cancelled when the instance being observed is torn down, but it sounds like in this case the root instance was still there but the child wasn't. Any chance you could reproduce the bug in a [fiddle](http://jsfiddle.net/rich_harris/va6jU/)? Thanks

**Comment by jmellicker** [comment]
So sorry I missed these questions.

Yes, the error happened when the observer was called after the component had been removed.

No, I tried to recreate this in a fiddle but couldn't, must be dependent, or perhaps caused by, our specific codebase structure.

Since we have a solution, I'm closing, thanks!
