### ISSUE TITLE
Ractive.js <@version@> in debug mode

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2094]
While checking out this issue https://github.com/ractivejs/ractive/issues/2092, I notice that the version number isn't being shown properly. It appears as 

    Ractive.js <@version@> in debug mode

http://jsfiddle.net/wax27gr9/

**Comment by ISNIT0** [comment]
I believe the problem is due to windows using the 'backslash' character instead of the slash character. I will quickly create a pull request.

**Comment by martypdx** [comment]
Happening on OSX too

**Comment by ISNIT0** [comment]
@martypdx Oh right, that's odd. My change got it working on Windows, I figured it was just the different direction of slashes.

**Comment by NikhilVerma** [comment]
The fix for it is here: https://github.com/ractivejs/ractive/pull/2106

But right now the build is failing for some reason, it works on my Mac

**Comment by Rich-Harris** [comment]
This was happening because the `transform` functions [specified in the build definition](https://github.com/ractivejs/ractive/blob/dev/gobblefile.js#L23-L29) weren't actually getting used – same cause as #2105. Now fixed
