### ISSUE TITLE
Why ractive variables don't work with some html elements? 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2099]
Hi, 

As [this JSFiddle shows](http://jsfiddle.net/nqk2nb03/11/), `<p>` tag works as expected but `<textarea>` tag fails for a reason. 

Why is that?

**Comment by martypdx** [comment]
For two way binding on `textarea` [use the `value` attribute](http://docs.ractivejs.org/latest/two-way-binding#-textarea-elements), not the text content:

```html
 <textarea class="my-class" value='{{.name}}'></textarea>
```

A two-way interpolated text area value (`<textarea class="my-class">some words {{.name}}</textarea>`) doesn't really make sense, but maybe you could explain the use case?

**Comment by ceremcem** [comment]
In fact, it was intended for one way data flow and "some words" are written for only debugging purposes. Otherwise, (if we intend to use it as two way data binding) it would be confusing also. For example if we define: 

```
<textarea class="my-class">some words {{ .name }} {{ .some_other_variable }}</textarea>
```
and then edit the area and write "foo bar baz", what would be the `name` and `some_other_variable` contents? 

Anyway, thanks for the explanation. I updated my code.

**Comment by Rich-Harris** [comment]
Actually this seems like a bug – the textarea probably *should* update like other elements if it's not subject to two-way binding. I'll re-open this

**Comment by Rich-Harris** [comment]
#2199 changed the result of the above fiddle, but there's still something weird going on – the first textarea doesn't update. Haven't investigated yet

**Comment by evs-chris** [comment]
I'm reasonably sure it's got something to do with binding to a non-direct-model object (`{{>test-partial { name: 'foo' } }}`), which I've yet to look at since the Model changes. That's still unsupported for two-way binding, isn't it?

**Comment by evs-chris** [comment]
Found it. The empty fragment left over after moving the interpolator to the value attribute was overwriting the content.

**Comment by ceremcem** [comment]
:+1:
