### ISSUE TITLE
Ractive merge doesn't keep untouched values

### ISSUE THREAD

**Issue by linde12** [ractivejs/ractive#2100]
Hello!

I'm not quite sure if this is classified as a bug, but at least it's an issue(or, well, it's bothersome)

When i use Ractive.merge to merge existing object the untouched objects(those who weren't discovered by the compare) are all removed from the array.

See this quick fiddle where i use numbers instead of objects.

http://jsfiddle.net/wsk6ofg4/1/

As of now i have to manually do Ractive.get, compare my elements and update the ones which have changed and then merge/set them. I just thought it was obvious that `merge` would leave the other elements alone like `_.extend` or similar. Maybe some clarification on the docs would suffice? Is this the expected behavior?

**Comment by linde12** [comment]
Here is another sample with objects http://jsfiddle.net/wsk6ofg4/2/

**Comment by martypdx** [comment]
You're not alone, here was my first stumble over `merge`: https://github.com/ractivejs/ractive/issues/753

Basically, as @MartinKolarik explained very well on first comment, the data you supply as the second argument __is__ the complete new data that is being set. 

The value of merge is that if the "comparison" returns true, _the associated DOM nodes for that item in the section are reused_.

**Comment by linde12** [comment]
Ah, thanks for your quick reply! I see, so it has been brought up before!

I'm not against it doing what it does, but i don't fancy the name. I think many people will be misled by it!

But now i know, thanks a lot!

**Comment by JonDum** [comment]
Maybe now is a good time for @Rich-Harris's suggested syntax in #753? Close this and redirect convo to there?
