### ISSUE TITLE
TypeError: this.iterations is undefined

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2101]
On edge (0.8.0)

`TypeError: this.iterations is undefined ractive.js:6279:0`

Running into the above error, which happens due to a call to update(), but I'm having trouble distilling it down into a small repro.

Before the Exception, in a call to `RepeatedFragment.prototype.bind`, the call `var value = context.get();` returns undefined, so the checks isArray and isObject are passed, leaving `this.iterations` unset.

Hoping someone might be able to take a look for anything obviously amiss. Otherwise, I will continue to try to create a small fiddle to reproduce.

**Comment by Rich-Harris** [comment]
Going to be optimistic and close this, as it should have been fixed by #2120. @woodlandhunter shout if that's not the case!
