### ISSUE TITLE
[BUG] Runtime builds aren't runtime builds

### ISSUE THREAD

**Issue by NikhilVerma** [ractivejs/ractive#2105]
Runtime builds now include the parser: http://cdn.ractivejs.org/edge/ractive.runtime.js

This should not happen, this is not why runtime builds were created.

**Comment by NikhilVerma** [comment]
@Rich-Harris Fixed here: https://github.com/ractivejs/ractive/pull/2106

**Comment by Rich-Harris** [comment]
Well, this is odd – my local runtime build didn't include `Ractive.parse`. So I cleared out my `node_modules` folder and reinstalled everything, and now I get the same result. I must have `npm link`ed something. Unfortunately #2106 isn't the right fix – bundling pre-transpiled code results in a lot of unnecessary duplication in this case. Will look into it

**Comment by Rich-Harris** [comment]
This is now fixed
