### ISSUE TITLE
Mappings initialised incorrectly in 0.8

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#2108]
Works in latest, fails in edge: http://jsfiddle.net/rich_harris/923yetf5/

**Comment by evs-chris** [comment]
Looks like maybe the mapping is hitting the root and not the intermediate component? Scoping in the list template seems to work around: http://jsfiddle.net/923yetf5/1/

**Comment by Rich-Harris** [comment]
Yeah. Looks like [this](https://github.com/ractivejs/ractive/blob/dev/src/view/resolvers/resolveAmbiguousReference.js#L11) is the offending line – it's jumping straight to parent mappings, rather than testing local contexts first. Working on a fix...

**Comment by Rich-Harris** [comment]
Well, #2109 fixes it, it seems. If in doubt, just delete a bunch of code

**Comment by evs-chris** [comment]
> If in doubt, just delete a bunch of code

Quote of the day

**Comment by martypdx** [comment]
And it was ugly code to boot :grin:

**Comment by JonDum** [comment]
> If in doubt, just delete a bunch of code

LOL
