### ISSUE TITLE
Custom a lightweight version.

### ISSUE THREAD

**Issue by unbug** [ractivejs/ractive#2129]
How can I build a lightweight version?Ractivejs is too big for me.I don't see any of this in the docs,do I missing something?I actually just need the Templates(and extend)  parts.All the events,animations,data-binding are not necessary.

**Comment by Madgvox** [comment]
As of now, there is no lightweight version of ractive exists nor plans for one, as ractive was never meant to just be a template renderer and the different services of ractive ( events, data-binding, etc. ) are pretty integral to the way templates are rendered. If all you need is a templating engine, perhaps something like [handlebars](http://handlebarsjs.com/) may be a better fit for you.

**Comment by unbug** [comment]
Fair enough,total agree with what you stand for. I am start digging

**Comment by unbug** [comment]
Do you mind to take look of this question?[How do write a Virtual DOM base javascript template engine?](http://stackoverflow.com/questions/32423206/how-do-write-a-virtual-dom-base-javascript-template-engine)

**Comment by Rich-Harris** [comment]
Looks like the SO question has been downvoted – I recommend reading [How do I ask a good question?](http://stackoverflow.com/help/how-to-ask) to avoid that happening again.

Short answer: ask concise, specific questions. Your question is ludicrously broad! It's like asking 'how would I reimplement jQuery?' If you're interested in DOM diffing, start by reading source code – lots of source code. React, Mithril, virtual-dom, Cito, etc. (Ractive doesn't use a diffing mechanism.)

A custom build generator is something we might offer in future. I'd like to be able to exclude certain methods from some builds, or the Promise polyfill, or various other things. It's not on the immediate radar though so I'll close this. In the meantime, remember that Ractive (which weighs about as much as a small thumbnail jpeg) can save you thousands of lines of application code and will give you more time to spend optimising your app once you've built it!

**Comment by unbug** [comment]
@Rich-Harris You made your point,especially the  “thumbnail jpeg” part. I'll keep digging.Thanks a lot.
