### ISSUE TITLE
Event for when an element has been rendered

### ISSUE THREAD

**Issue by binarykitchen** [ractivejs/ractive#213]
Hi folks

I am looking for an event which is fired then the element has been rendered. For example a video I am getting from the server and is rendered via Ractive. And when rendered, then I want to listen to the play button ... so here is the code:

``` html
{{# video }}
        video(poster="{{video.image}}", preload="auto", controls="controls")
            source(src="{{video.mp4}}", type="video/mp4")
            source(src="{{video.webm}}", type="video/webm")
        {{^ hidePlayButton }}
        button.play(on-tap="play") Play
        {{/ hidePlayButton }}
{{/ video }}
```

and

``` js
    var VideoView = Ractive.extend({
        el:         'main',
        template:   template(),

        data:       {
            video: null
        },

        init: function() {
            this.on('play',       this.play);
            this.observe('video', this.videoChanged);
        },

        videoChanged: function(newVideo) {
            if (newVideo) {
                // caching it so that I do not have to query for it again
                this.video = this.el.querySelector('video');
            }
        },

        play: function() {
            this.set('hidePlayButton', true);
            this.video.play();
        }
    });
```

problem is this error I'm getting:

```
Uncaught TypeError: Cannot call method 'play' of null 
```

when I am setting the video after an Ajax query with:

``` js
videoView.set('video', video);
```

video is not null, yet I am having this error. Weird.

I guess the observer is called before the video is rendered in the DOM. Either the observer should wait until it is in the DOM or we need a new event.

What do you reckon?

**Comment by JonDum** [comment]
@Rich-Harris My goodness, you think of everything. Thank you for the defer: true. Exactly what I needed right now.

**Comment by rstacruz** [comment]
as an aside, `this.on('play', this.play);` is probably not necessary anymore.. `on-tap="play"` should trigger play() just fine.

**Comment by rstacruz** [comment]
and `this.video = this.el.querySelector('video');` can also be written as `this.nodes.video` if you put an `id="video"` on the video element :)

**Comment by Rich-Harris** [comment]
...though I was wondering if we should deprecate `this.nodes.xyz` since it relies on IDs which are essentially globals. (It was introduced before `this.find()`.)

@JonDum 

> My goodness, you think of everything

we try :)

**Comment by martypdx** [comment]
> ...though I was wondering if we should deprecate this.nodes.xyz since it relies on IDs which are essentially globals. (It was introduced before this.find().)

For people moving from `$('#specialElement')` having `this.nodes.specialElement` is very helpful. 

Since IDs are sometimes not actually globally, componentizing and `node.xyz` is handy.

**Comment by derozn** [comment]
+1
