### ISSUE TITLE
Make ractivejs accept promises

### ISSUE THREAD

**Issue by wenerme** [ractivejs/ractive#2130]
I use computed to load data, but most of time the load is async, computed can not accept promises.Other ractivejs function-able properties  also have no idea about promises(e.g. data).So why not make ractivejs have aware of promises, I thinks this is a big advance.

**Comment by Madgvox** [comment]
There's a very recent thread open about this very subject [here](https://github.com/ractivejs/ractive/issues/2075), so I'm going to close this thread. We would gladly welcome your input over there, and I also invite you to read @martypdx's [thoughts on the matter](https://github.com/ractivejs/ractive/issues/2075#issuecomment-136058829) as it stands now.

As it stands however, there exists an [adaptor](https://github.com/rstacruz/ractive-promise-alt) for this very thing, so see if that fulfills your needs.
