### ISSUE TITLE
{{#each}} iteration includes undefined first time computed array is changed 

### ISSUE THREAD

**Issue by waynebaylor** [ractivejs/ractive#2134]
Test: http://jsfiddle.net/pzyzcpf0/2/

I'm running into this with 0.7.3, but after writing the test I noticed it passes with edge version. Just thought I'd document it here anyway.

In the test if you change the check() function to use console.log() you can see that "undefined" is logged 3 times, once for each item of the array that is filtered out. It only happens the first time the computed array changes; subsequent changes behave as expected. Open the dev console and check out http://jsfiddle.net/v4r2x2d4/1/

**Comment by Madgvox** [comment]
Since it's appeared to be fixed in 0.8, my suggestion would be to upgrade ASAP :smile:.

I'm going to close this thread as `wontfix`, but as you said, it's good to have this bug documented nonetheless.
