### ISSUE TITLE
How can I detect isRendered or isDetached ?

### ISSUE THREAD

**Issue by wenerme** [ractivejs/ractive#2135]
From this [question](http://stackoverflow.com/questions/32443021/).

I use pagejs to mantain page state with ractive, it turns out the render state and detach state is very hard to deal with.I can not just render or unrender or detach, but there is no way to detect the state, some time a ractive is not render or unrender.

Or is there other way to do this ? Any guide to use ractive work with single web app ?

**Comment by wenerme** [comment]
![image](https://cloud.githubusercontent.com/assets/1777211/9725710/19f48852-561b-11e5-9e39-e55eb6c96b13.png)

```
        if (app.r.fragment.rendered) {
            app.r.insert('#content');
          } else {
            try {
              app.r.render('#content').then(()=> app.r.insert('#content'));
            } catch (e) {
              console.warn('Render failed', e);
              app.r.insert('#content');
            }
          }
```

**Comment by Madgvox** [comment]
You don't need to render _then_ insert. `render()` automatically inserts the ractive into the DOM. I've used this exact function in my own app:

```js
function insertRactive( ractive, node ) {
  if( ractive.fragment.rendered ) ractive.insert( node );
  else ractive.render( node );
}
