### ISSUE TITLE
Crash when non existing keypath inside decorator (0.8)

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2138]
Check the fiddle:
http://jsfiddle.net/58hsp2bs/2/

{{objects.construction_type}} is non existent and Ractive fails.
This only happens if {{objects.construction_type}} is bound to the value of the select element.

**Comment by Madgvox** [comment]
I'm not seeing the error happen in your fiddle on my computer. It appears to be functioning correctly as far as I can tell.

**Comment by kouts** [comment]
Sorry, wrong fiddle, I' ve updated the first post with the correct one.

**Comment by Madgvox** [comment]
No worries!

**Comment by kouts** [comment]
I' ve updated the fiddle (http://jsfiddle.net/58hsp2bs/3/), it is now easier to understand what's wrong.
Just uncomment the "objects" node in data to make it work again.
