### ISSUE TITLE
Crash when trying to render empty select option (0.8)

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2139]
Ractive (0.8) crashes when trying to render empty select option:
```
<select><option></option></select>
```
see this  fiddle:
http://jsfiddle.net/qpr9obxy/4/

**Comment by heavyk** [comment]
are you saying it should display a warning? do nothing?
obviously, if you need a value for the option.

**Comment by heavyk** [comment]
you mean replicate 0.7's empty ... ah, ok

I mean, this is the programmer's oversight more than anything... because, even if you have `<option>{{notExists}}</option>`, it won't crash. however, it could lead to confusion for the newbies, I guess.

this is a super easy fix. I'll do it now.

**Comment by kouts** [comment]
In 0.73, an empty select is drawn as it should (http://jsfiddle.net/70aedasc/), I think the same behavior is expected.
