### ISSUE TITLE
using update('some.key') changes not reflected (object updated outside of set())

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2141]
See the attached fiddle. On Edge, click on "Click me" and the change is not reflected. On latest, the change is reflected.

http://jsfiddle.net/y270cxxb/

(I know usually you would use `set()` for this, which works, but in my application I'm updating many objects in a loop and then doing an update() call once.)

I can work around it by using `update('some')` instead of `update('some.key')` but since the behavior is changed I thought it was worth checking into whether this was now expected.

**Comment by evs-chris** [comment]
It looks like the issue on edge is that `sub` is an ambiguous reference. Changing the reference to `.sub` to remove the ambiguity causes the "Click me" to work. I think the unresolved process should handle this case from `update`.
