### ISSUE TITLE
I could not find a link to download minified version in your homepage.

### ISSUE THREAD

**Issue by alexserver** [ractivejs/ractive#2143]
Hi there, I was looking for a simple way to download ractive minified version without downloading the repo and running `npm run build`. I was expecting a min version link, but only found the non minified version throught your CDN: `http://cdn.ractivejs.org/latest/ractive.js`.
Doing some research in internet I came upon this page which has all versions for your builds:
[http://spmjs.io/package/ractive](http://spmjs.io/package/ractive)
Which is awesome, but I think you still should have these links in your web home page for those who are not in touch with node.js

**Comment by Madgvox** [comment]
Here is the minified file: http://cdn.ractivejs.org/latest/ractive.min.js

I do agree that there should be a clear description of all the different available builds somewhere on the website, though!

**Comment by Madgvox** [comment]
I've created an issue at the ractivejs.org repo, so I'm going to close this issue.
