### ISSUE TITLE
Can partials be imported declaratively?

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive#2144]
Is there any support for a Twig-like syntax like:

```html
{{ import "partial.html" as mypartial }}

<div>
  {{>mypartial}}
</div>
```
I'd like Ractive-based pages to get setup via JS without any additional configuration for that page, but it seems the only current way to reference partials is to add it explicitly on the JS side to the partials property.

Or, alternatively, is there another way to import partials ad-hoc without much extra configuration?

**Comment by martypdx** [comment]
If you're looking to dynamically specify the partial, you can use a reference and the partial will resolve to that reference:

```js
new Ractive({
    el: 'main',
    template: '{{>foo}}',
    data: { foo: 'one' },
    partials: {
        one: '<span>one</span>',
        two: '<div>two</div>'
    }
});
```

If your looking to dynamically load files, take a look at [this blog post] from Behance on a partial loading plugin.

**Comment by heavyk** [comment]
wow thanks @martypdx that actually helps a lot! I googled the article.

relevant links:

https://github.com/behance/ractive-partials
http://behancetech.net/2015/08/06/ractive-partials/

**Comment by mrjoelkemp** [comment]
Can this be closed? Is ractive-partials a workaround or is the suggested syntax a wontfix?

**Comment by Madgvox** [comment]
I think at this point dynamically loaded partials are the way to go.

**Comment by matthew-dean** [comment]
Okay, I'll find a different solution.
