### ISSUE TITLE
Feature request: more lines output for errors

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive#2146]
Hi, I've run into this a number or times so I'd thought I'd bring it up.

I currently have a parsing error that looks like this:

```
Uncaught ParseError: Unexpected closing tag at line 164 character 25:
                        </label>
                        ^----
```
However Ractive counts lines, whether it's by counting from the start of the inline template, or somehow using the position in the HTML doc, the line # never amounts to something meaningful / matching to my template.

Rather than focus on the line number issue (although getting insight on that would be nice too), what would help me is if the error output included more than just one line. I have LOTS of </label> closing tags in this particular template, so I end up visually inspecting all of them to try to find a parsing error.

If, however, the error output simply included more than one line, like two lines preceding the error, I would probably be able to find that easily in my code.

This has actually come up a lot for me, where I get an error, but the error information doesn't actually provide anything I can use to find the source of the problem. Is a little more verbosity possible?

**Comment by matthew-dean** [comment]
I was able to figure out after some mathing that the line of the actual error was the position of the template in the HTML doc + the line of the error. Which makes sense, I suppose, but I still think having more lines would still help, since the math may not always be that simple, depending on how the template is imported.

**Comment by Rich-Harris** [comment]
Agree, this is particularly confusing in the templates-in-script-tags case. Perhaps we should have special treatment for those:

```
Uncaught ParseError: Unexpected closing tag at line 164 (relative to
<script id='template' type='text/html'>) character 25:
                        </label>
                        ^----
```

A couple of lines of padding either side wouldn't hurt either.
