### ISSUE TITLE
Splice behaves unexpectedly

### ISSUE THREAD

**Issue by ISNIT0** [ractivejs/ractive#2147]
Seems splice is over-writing values which shouldn't be touched.

http://jsbin.com/talequ/8/edit?html,js,output
http://jsfiddle.net/va6jU/106/

You see that 'push' behaves as expected, but when you start splicing, values are changed, re-ordered and overwritten.

Try pushing once, the splicing once.

You will see the push adds a value to the end of the list,
then the splice changes the last item (a push) to a value of splice,
then moves the last item (formerly a push, now a splice) to the beginning,
adds a splice at the beginning.

(I know that is a bit convoluted).

If you click splice multiple times, the original 'test' values are over-written.

If you click splice until all 'test's are gone, then click push a few times, then splice again, the 'test's return.

**Comment by ISNIT0** [comment]
I believe the problem is in viewmodel.smartUpdate, not in the makeArrayMethod/getNewIndices functions.

**Comment by heavyk** [comment]
I tried fixing this here https://github.com/ractivejs/ractive/pull/2137

it is however way over my head... what happens is, in the update cycle it marks the wrong ones for deletion, and sometimes it will delete more than once. to fix this, it looks like that code needs to either be rewritten or refactored in a way which doesn't have the possibility to delete the same fragment more than once.

it is possible to get "attempted to remove fragment which was already removed" errors with splice too.

**Comment by ISNIT0** [comment]
I'm glad it wasn't just me that couldn't fix it :p I have been working on
it on and off all day.

**Comment by heavyk** [comment]
I spent a whole day on it too. I understand the update cycle a lot better now.

right now things are done in two stages, where the old indexes are saved, and then compared to the new indexes.

what I propose, is to keep track of the fragments on some sort of unique id (an integer is fine) which doesn't change ever for each fragment (new ones get new ids). that way, indices don't need to be passed around at all... only one object which stores id<->index mapping would be needed.

if I suddenly see it clear, I'll have a go at it. cheers

**Comment by martypdx** [comment]
@ISNIT0 I'm probably not doing the steps right, but seems to work for `edge`. 

`ractive.splice( 'list', 0, 0, item )` is equivelent to `ractive.unshift( 'list', item )`, so when I click <kbd>splice</kbd> it adds one to the front and <kbd>push</kbd> it adds to the end.

Is that not what's expected or am I missing something?

**Comment by heavyk** [comment]
@martypdx I have illustrated the problem better here:
http://jsfiddle.net/fLcnvxfc/

**Comment by martypdx** [comment]
Thanks @heavyk!

**Comment by heavyk** [comment]
I've updated the fiddle to be more complete.

http://jsfiddle.net/yo754sv7/

you will notice a few things about it:
if the length doesn't change, it works
if the array is fresh and a null is spliced in, it works
usually splicing the last element out works

also dude, I've got to ask, how did you do the pushbutton effect on the ```splice``` and ```push``` words?
I've tried a whole bunch of combinations but couldn't figure it out

**Comment by martypdx** [comment]
It also has to be components in the repeated fragment 

> also dude, I've got to ask, how did you do the pushbutton effect on the splice and push words?

`<kbd>button<\kbd>`   <kbd>button<\kbd>

**Comment by heavyk** [comment]
yeah that's true. it does work fine without a component.
that must be where the problem is.
so, I think I'm beginning to formulate the solution in head.
I'll have another go at it soon.

**Comment by martypdx** [comment]
I played with it this morning by not calling `this.mark()` on `Model#shuffle` and instead updating `this.childByKey`. It fixed the immediate problems but created a whole set of failures in other tests and specifically in splice tests when ref is bound to specific index like `{{foo.2}}`

**Comment by heavyk** [comment]
I did the same thing, disabling mark ... encountered the same results too :)

after playing with it a while, I think the solution is to give each fragment a unique id and then just update that lookup table. when the fragment is no longer found in the lookup table it could be deleted. that will simplify the run loop a whole bunch because then they wouldn't need to be marked and stuff - they could be looked up / updated until the end of the runloop. it would also optimize the shuffle function when multiple moves occur sometimes. (I hope I'm explaining it ok)

it's kindof a big task, which is why I haven't started yet, but I'd really like to begin soon.

though, since it only happens with components, it could be happening in the bind/rebind bit... know what I mean?
