### ISSUE TITLE
Adjacent components, only the first is rendered

### ISSUE THREAD

**Issue by lazylester** [ractivejs/ractive#2151]
HTML:
```
<div id='container'/>

<script id="bandz_template">
    <h3>Bandz</h3>
    <beatles>
    <stones>
</script>
```
javascript:
```javascript
Beatles = Ractive.extend({
    template : "{{#beatles}}<p>{{name}}</p>{{/beatles}}"
})

Stones = Ractive.extend({
    template : "{{#stones}}<p>{{name}}</p>{{/stones}}"
})


new Ractive({
  el : "container",
  template : '#bandz_template',
  data : {stones : [{name : "mick"},{name : "keith"}], beatles : [{name: "ringo"},{name:"george"}]},
  components :{
    beatles : Beatles,
    stones : Stones
  }
})
```
(this is on jsfiddle at http://jsfiddle.net/fdf9cdxe/)

In the top-level template there is a \<beatles\> component followed by a \<stones\> component. However if you look at the jsfiddle, only the first is rendered. As an experiment, on jsfiddle, reverse the two components so it's \<stones\> followed by \<beatles\>. Then only the \<stones\> component is rendered.

The only way to get them both on the page seems to be to encapsulate each of them in an html element, e.g. div.

**Comment by martypdx** [comment]
You need to close your component tags:

```
<beatles/>
<stones/>
```

http://jsfiddle.net/fdf9cdxe/2/

**Comment by Rich-Harris** [comment]
Have raised #2154, which adds an error if the end of the template is reached with missing end tags.
