### ISSUE TITLE
No way to use custom easing functions

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2152]
I noticed today when trying to use a custom easing function with `animateStyle` that there's no way to use a custom easing function since it defaults to CSS animations instead of JS animations. 

http://jsfiddle.net/jondum/betc10qo/

Notice that the `easings.elastic` isn't being used.

**Comment by Rich-Harris** [comment]
Hmm... I *thought* transitions fell back to JS timer-based animations if a non-CSS easing function was specified. Clearly I haven't looked at that part of the codebase for a while. Truth is there's a lot of stuff that needs to be fixed around transitions, it's one of the oldest and clunkiest bits of the library – one thing I'd definitely like to do is allow arbitrary easing functions with CSS keyframes (i.e. you 'prebake' the style for each frame of the animation, then let it run off the main thread).

In the meantime, I suppose the only workaround would be to do the transition without using `animateStyle`.

**Comment by sarendipitee** [comment]
@evs-chris Huzzah! I owe you like 100 beers.

**Comment by evs-chris** [comment]
Finally got round to looking at transitions hard enough to figure out what was going on here 😄. The simple fix is basically to force js transition if the css timing function doesn't stick.
