### ISSUE TITLE
setting a global delimiter

### ISSUE THREAD

**Issue by hyusetiawan** [ractivejs/ractive#2153]
Per docs, we can set the delimiters by passing delimiters: [ '[[' , ']]'] but passing it on every ractive component is a hassle, is there a way to globally change it, just the way Mustache does it?
```
Mustache.tags = ['[[', ']]'];
```

**Comment by Madgvox** [comment]
`Ractive.defaults.deliminiters = [ '[[', ']]' ];`

**Comment by hyusetiawan** [comment]
@Madgvox thanks!
`Ractive.defaults.delimiters = [ '[[', ']]' ];`

works! I did not see that in the docs, must have missed it

**Comment by Madgvox** [comment]
No problem!

For future reference: http://docs.ractivejs.org/latest/ractive-defaults

**Comment by rolldone** [comment]
Hi, Im working on webpack, and have to change the delimiters. But why is not working?
