### ISSUE TITLE
RFC: disallow ractive.animate(map)

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#2155]
While doing some recent heavy [linting](https://github.com/ractivejs/ractive/tree/more-linting) of the codebase (ESLint is great, by the way!) I got massively sidetracked by the `ractive.animate(...)` code, which is under-tested and over-complex.

One thing that became painfully obvious after adding some new tests – it doesn't make sense to be able to animate a map of keypaths simultaneously, because you can't then cancel a subset of those keypaths:

```js
ractive.animate({ foo: 1, bar: 2 }, {
  duration: 1000,
  step: stepCallback
});

// less than 1000 milliseconds later...
ractive.animate( 'foo', 3, {...});
```

(Because a keypath can't be the subject of two simultaneous animations, the first is supposed to be cancelled.)

What happens to the original animation in this case? Does the `step` callback continue to be called, but with the `foo` converging on 3 rather than 1? If there was a `complete` callback (or a promise `.then()` handler), what would it *mean* when that was called, given that the original animation didn't really complete? (1000ms might have elapsed, but the original target was never met, and `foo` – and `bar`, if another animation started – might still be animating.) It turns out you quickly fall down a bit of a rabbit hole.

On top of that the code to make it all happen is slightly ridiculous. Therefore I propose that we **only allow `ractive.animate(...)` to be called with a single keypath** at a time. It's simpler, more flexible, less ambiguous, and doesn't prevent anyone from doing anything they're currently doing (though they might have to add e.g. a single line of code).

Any objections?

**Comment by JonDum** [comment]
That sounds good to me. I lean towards keeping `animate` as simple as possible. Animations can get super crazy complicated and others have already spent the time working on these edge cases (TweenLite/TimelineLite, Velocity, et al). 

Ractive should keep it simple for quick ease of use, then someone who needs way more complex animations can provide their own animation engine.

**Comment by Rich-Harris** [comment]
I've opened a PR that implements this change: #2156

**Comment by martypdx** [comment]
:+1: 

Interestingly, just yesterday I thought we had a case where the map api would be nice. We were animating a dragged item back in bounds (the object wasn't a pojo so we couldn't just animate whole position). But even in that case we _needed_ two lines because the animations were independent:

```js
if ( top < 0 ) {
	this.animate( 'position.top', -origin.top/cardview.height, options );
}

if ( left < 0 ) {
	this.animate( 'position.left', -origin.left/cardview.width, options );
}
```
