### ISSUE TITLE
Section rendered after set() updates section key to false-y value

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2157]
http://jsfiddle.net/tfj7uvsa/

It renders correctly when data is set to `{obj: false}`on initialization.
(It also happens for `{}`, `[]`, and `undefined` in place of `false`)

**Comment by NikhilVerma** [comment]
This seems very similar to #2178

**Comment by Rich-Harris** [comment]
Fixed in edge by @evs-chris
