### ISSUE TITLE
Simulate document ready

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2158]
Here is the situation: I have a "main" ractive that is my "page".
The page hosts various components that are displayed or hidden depending on some variables.
The thing is the if I instantiate some jquery plugins (e.g tooltips) inside main page's "oncomplete" function, the components that are not displayed at the time do not pickup the jquery plugins functionality.
I know this is expected, because the components do not exist in DOM before they get rendered.

I tried setting up an observer on a "page_step" variable, so that every time "page_step" variable changes, I am able to instantiate the jquery plugins, but the observer fires before the ractive finishes rendering the page.

I feel I'm missing something obvious here, if someone has any idea please enlighten me!
Thanks.

**Comment by heavyk** [comment]
put the observer in the `oncomplete` function

**Comment by martypdx** [comment]
@kouts example would be helpful

**Comment by kouts** [comment]
Thanks @heavyk that solved it!
