### ISSUE TITLE
`npm run build` doesn't work

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#2159]
since getting latest it looks like the animation tests won't run via headless:

```sh
Tests completed in 5390 milliseconds. 2290 assertions of 2294 passed, 4 failed.
methods/animate.js: ractive.animate() returns a promise that resolves when the animation completes (#1047) (1, 0, 1)
methods/animate.js: all animations are updated in a single batch (1, 0, 1)
methods/animate.js: animations cancel existing animations on the same keypath (1, 0, 1)
methods/animate.js: set operations cancel existing animations on the same keypath (1, 0, 1)
```

**Comment by martypdx** [comment]
Looks like #2156 never passed Travis, although showing different error reason.

**Comment by Rich-Harris** [comment]
Damn. `npm run build` is currently failing if you have an up-to-date version of Rollup, due to https://github.com/rollup/rollup/issues/132, hence the Travis failures, which is also why I didn't catch those PhantomJS failures

**Comment by martypdx** [comment]
FWIW this one fails sporadically in the qunit tests:

![image](https://cloud.githubusercontent.com/assets/478864/10077498/586f2f48-6295-11e5-9a24-971fe2f340ef.png)

**Comment by Rich-Harris** [comment]
I've downgraded Rollup pending a fix, and got those other tests working in PhantomJS (it was a Promise thing – forgot to bring the polyfill). Travis is green again
