### ISSUE TITLE
Components loading order

### ISSUE THREAD

**Issue by nicolas-t** [ractivejs/ractive#2161]
Hi :)

I have 3 components, lets say `BlogPost`, `AuthorAvatar`, and `PostTitle`, like this : 
(in fact they are in several files, and concatenated in alphabetical order)

```coffeescript
App.ViewRactive.AuthorAvatar = App.ViewRactive.extend
    template: "whatever"
    isolated: true

Ractive.components.AuthorAvatar = App.ViewRactive.AuthorAvatar

App.ViewRactive.BlogPost = App.ViewRactive.extend
    template: "<authorAvatar /> <postTitle/>"
    isolated: true
    components:
        authorAvatar : App.ViewRactive.AuthorAvatar 
        postTitle:  App.ViewRactive.PostTitle

Ractive.components.BlogPost = App.ViewRactive.BlogPost

App.ViewRactive.PostTitle = App.ViewRactive.extend
    template: "whatever"
    isolated: true

Ractive.components.PostTitle = App.ViewRactive.PostTitle

```

As you can see `BlogPost` is a parent for `PostTitle` (defined after) and `AuthorAvatar` (defined before)

I'm returned this error : 
`Uncaught TypeError: Cannot read property '_Parent' of undefined`
Is it Because `PostTitle ` is "loaded" after its parent `BlogPost` ?

I have created a JSFiddle showing the issue : https://jsfiddle.net/nbvurmdq/2/

What am I doing wrong ? are there any good practice regarding components declaration ? 

Thanks !

**Comment by fskreuz** [comment]
It's because [`BlogPost` requires both](http://jsfiddle.net/nbvurmdq/3/). You need them both defined, otherwise, `postTitle ` in `BlogPost` is undefined.

> are there any good practice regarding components declaration ?

You can use [existing loaders](https://github.com/ractivejs/component-spec/#available-loaders). They piggyback on existing module systems. Choose one that fits your app. If you're not using a module system, it's time you start using one. :P

> concatenated in alphabetical order

Why? What concat tool do you use? Do you use Meteor by any chance (iirc, they also did alphabetical concat)?

**Comment by woodlandhunter** [comment]
I'll second what @fskreuz is saying re: existing loaders. I recently reviewed most of the loaders and settled on webpack & [ractive-loader](https://github.com/rstacruz/ractive-loader). It handles components and partials.

**Comment by nicolas-t** [comment]
Thanks !

Here is what I did , with browserify: 

'parent' component : 
```coffeescript
App.ViewRactive.BlogPost = App.ViewRactive.extend
    template: "<authorAvatar /> <postTitle/>"
    isolated: true
    components:
        authorAvatar :  require('./author-avatar')
        postTitle:   require('./post-title')

Ractive.components.BlogPost = App.ViewRactive.BlogPost

```
'child' component : 
```coffeescript
PostTitle = App.ViewRactive.extend
    template: "whatever"
    isolated: true

Ractive.components.PostTitle = PostTitle 
module.exports = PostTitle

```

@fskreuz Concatenated in alphabetical order, because that's how my gulpfile works :D
