### ISSUE TITLE
Two-way binding only works within a single instance of component

### ISSUE THREAD

**Issue by owanturist** [ractivejs/ractive#2163]
Two-way data binding correctly only works within a single instance, not across component boundaries ([live demo](http://jsbin.com/qepupayego/1)).

Question from [stackoverflow](http://stackoverflow.com/questions/32755097/two-way-binding-doesnt-work-inside-ractive-components).

**Comment by Madgvox** [comment]
I feel like this has been addressed, but I can't remember where. I'm going to mark it as a bug since it also occurs in edge, but if this issue actually _has_ been addressed and is intended behavior, feel free to remove that. :)

**Comment by lazylester** [comment]
Since Rich Harris referenced this bug in response to my stackoverflow question, I'll link it here, for your reference: http://stackoverflow.com/questions/32891814/unexpected-behaviour-of-ractive-component-with-checkbox
