### ISSUE TITLE
0.8 Fragment inside partial does not get updated when inside {{else}}

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2165]
http://jsfiddle.net/jondum/s4vL0mes/

Had this happen to me in a thing I'm working on and I reduced it down to the minimum. Works in 0.7.3.

**Comment by dagnelies** [comment]
Hi,

Are you sure the example is all right?

I see no light bulbs, just following messages in the console:

```
Ractive.js 0.8.0-edge in debug mode, more...
ractive.js:178 Ractive.js: Could not find template for partial 'lightbulb'

log.js:37Ractive.js 0.7.3 in debug mode, more...
log.js:69 Ractive.js: <comp> Could not find template for partial "icon"
```

**Comment by JonDum** [comment]
@dagnelies *Argh* thanks for noticing that. I really hate jsfiddle, it didn't properly save everything. I updated it. 

Also, the issue is that the `status` property on `things` does change (`ractive.findAllComponents()[0].get('status')` when you toggle the checkmark, but the SVG doesn't update. It works fine if it's not within the `{{else}}` statement. Kind of a major issue I thought.

**Comment by evs-chris** [comment]
This is now fixed in edge.
