### ISSUE TITLE
UUIDs as partial names sometimes fails

### ISSUE THREAD

**Issue by ArtskydJ** [ractivejs/ractive#2171]
I am getting this error:
```
Uncaught ParseError: Expected closing delimiter '}}' at line 1 character [number]:
```

Script to replicate error:
```js
var uuid = require('random-uuid-v4')
var Ractive = require('ractive')
Ractive.DEBUG = false

for (var i = 0; i <10; i++) {
	var id = uuid()

	var template = '{{>' + id + '}}'
	var partials = {}
	partials[id] = 'hello'

	try {
		Ractive({
			template: template,
			partials: partials
		})
		console.log(template + '\nok\n')
	} catch (err) {
		console.log(err.stack.split('\n').slice(1, 3).join('\n') + '\n')
	}
}
```
output:
```
{{>ca285c71-1e35-457a-863b-bd6257c9f0f9}}
ok

{{>47862c27-5268-4183-9c19-890f56836737}}
                       ^----

{{>0b0ff746-8fac-4b3c-840f-d7e2694df4ea}}
             ^----

{{>080777e2-3297-4f85-a47a-bb3071454eb4}}
ok

{{>cfb4d277-e273-4ded-a344-e998c1ed4ba7}}
ok

{{>66377dd6-03ef-424b-a08a-dcb7fbabc379}}
              ^----

{{>971418e7-1fb6-4338-b0e3-d3e9afc98224}}
ok

{{>68b9c929-4a47-4052-91b2-d623b587eae4}}
             ^----

{{>bb1acbb9-30d9-42ee-b20e-324a2fbafeb8}}
ok

{{>f47788c3-65d0-4c5b-aa56-5c153400ceea}}
ok
```
There's a pattern; partial names starting with a letter always work, names starting with a number sometimes work.

If I change line 6 to `var id = '_' + uuid()`, then it always works.

Replicated in node and chrome.

**Comment by Madgvox** [comment]
I would hazard a guess that for some of those, you're confusing the parser into thinking it's a math expression due to the numbers and `-` signs, and it's dying because it isn't actually. I don't think there's an easy way to fix that on our side, but prefixing the UUID with an underscore seems like an easy workaround to me.

**Comment by evs-chris** [comment]
The issues is that the partial name starts with a number, and that isn't a valid js identifier.

You can also quote the partial name to avoid it trying to parse out expressions where it shouldn't. For instance, where `{{>47862c27-5268-4183-9c19-890f56836737}}` throws an error, `{{>'47862c27-5268-4183-9c19-890f56836737'}}` is fine. I vaguely remember a discussion about further relaxing partial expressions, but I don't remember where it landed.

**Comment by Madgvox** [comment]
@evs-chris I was thinking the same thing, except that some of the names that start with a number don't break.

**Comment by martypdx** [comment]
The ones that work are a valid number ala scientific notation in the first position: 080777e2, so they trigger as a valid expression to calc the ref name.

**Comment by ArtskydJ** [comment]
@evs-chris Thanks for the quoting trick, I didn't know about that.

I feel like this might be an unreasonable expectation, so I'll close the issue.

Thanks everyone!
