### ISSUE TITLE
Feature request: template-level variables

### ISSUE THREAD

**Issue by xandrmoro** [ractivejs/ractive#2175]
Hi there,

Is it possible to have something like template-level local variable?
I mean something like this:
```
{{ #each array:i }}
  {{ #using a = some_func(i) }}  // any expression possible
    {{ #if a != 0 }}
      <some_component id={{a}}/>
    {{ #else }}
      <another_component id={{a}}/>
    {{ /if }}
  {{ /using}}
{{ /each }}
```
One can have such behavior right now with some boilerplate js, but this feature will be pretty much useful.

**Comment by Madgvox** [comment]
You can indeed do this!

```html
{{ #each array:i }}
  {{ #with { a: some_func(i) } }}
    {{ #if a != 0 }}
      <some_component id={{a}}/>
    {{ #else }}
      <another_component id={{a}}/>
    {{ /if }}
  {{ /with }}
{{ /each }}

**Comment by xandrmoro** [comment]
Oh my. I've tried lots of variants, but the simplest way never came to my mind. Thank you!

**Comment by heavyk** [comment]
that's true. I've never seen `#with` sections explored in the documentation (I'm using memory here). I only knew of them cause of comments here.

**Comment by Madgvox** [comment]
@heavyk They are explained briefly in the [mustaches](http://docs.ractivejs.org/latest/mustaches) documentation, but I agree that it's a bit sparse. I could've sword that there was some kind of `{{#with a as b}}` syntax, but for the life of me I can't find any reference to it anywhere.

**Comment by evs-chris** [comment]
@Madgvox there was a [comment](https://github.com/ractivejs/ractive/issues/1834#issuecomment-81708780) in #1834 a while back that proposed that syntax. That's one of the things on my short list to look at after 0.8.
