### ISSUE TITLE
"Strict mode" brainstorm

### ISSUE THREAD

**Issue by thomsbg** [ractivejs/ractive#2183]
### Context

This is some riffing on discussions already happening on other issues, particularly #1753, #1996, and #2166.

I use Ractive to develop a single-page-app with ~50 different components, which I precompile and bundle together using webpack and `ractive-component-loader`.
### Feels

When developing a large application using Ractive components, I've found it useful to document component files to describe which data is expected to be supplied via attributes vs data that is handled internally. Rather than do this with code comments, I'd love if the code itself could express its intention.

Much like the distinction between `props` and `state` in react, I'd love to somehow distinguish between external data supplied to a component vs data managed internally. I know this may be a breaking change, and a controversial one at that, but I feel it's worth some discussion.

My goal with all of this is to make Ractive code more explicit in how it's intended to function, which makes it easier to review and revisit down the road. I really appreciate the roots of Ractive as a tool for getting things done against deadlines, but it is also useful for larger applications that must be maintained and iterated on. Adding some opt-in features to clarify larger codebases would be a great win!
### Proposal

Use the `@` character to indicate references that must be resolved using _attributes_. Mustaches and calls to `get()`, etc using a keypath prefixed with `@` must resolve their reference using only component-bindings, and nothing else. For example:

```
// outer-component.html
<link rel="ractive" href="./inner-component.html" />
<inner-component a="from attribute">

// inner-component.html
Attribute: {{@a}}
Data: {{a}}

<script>
component.exports = {
  data: {
    a: 'from data'
  }
}
</script>
```

The above should output:

```
Attribute: from attribute
Data: from data
```

I like the `@` character for this purpose, because "at" reminds me of "attribute". Unfortunately, `@` is already used for three special references: `@keypath`, `@index`, and `@key`. That doesn't quite seem like a deal-breaker me.

This proposal could be implemented in a backwards-compatible way, in which `{{normal}}` references continue to use the existing resolution mechanism, with `{{@attribute}}` references using only component-bindings for resolution. Perhaps there could be a per-component "strict mode" option to opt-in to make `{{normal}}` references ignore component-bindings, i.e. `Ractive.defaults.strict = true`.

Additionally (though maybe going overboard here): similar to separating component bindings from internal data, it may be useful to also have a special syntax to reference computed properties, like `{{=computed}}` (borrowing the `=expression` syntax from spreadsheet applications).

**Comment by fskreuz** [comment]
> Much like the distinction between props and state in react, I'd love to somehow distinguish between external data supplied to a component vs data managed internally. I know this may be a breaking change, and a controversial one at that, but I feel it's worth some discussion.

I've ran across this too when a co-developer asked me how do I differentiate data passed in via attributes from internal component config. I managed to get away by either prefixing internal attributes with `_`. It's pseudo-privates essentially.

The nice part of Ractive is that it *doesn't* have this distinction. Avoids all that "props vs state" discussions, when to use it, how to use it. Data is just... data regardless of where it came from or what its intended use is. It makes it "easy to reason about" when you just have one source of data defined in one way.

There's already that discussion of component context https://github.com/ractivejs/ractive/issues/2166 where another level is proposed during resolution of a template value. I wonder if we need another level of resolution here.

And wouldn't it be more confusing that `a`, given some special doodad, can easily spin off and mean something else? It's comparable to Angular's directives where, given `=`, `&`, `@`, it could spell the difference if the data can two-way bind, what context the function runs, how the function handler should look like, should I just be passing a reference or a string expression. etc. etc.

Been venturing out to other frameworks, and nothing comes close to Ractive's "no frills" simplicity when it comes to dealing with templates and data.

My 2c. Bow.

**Comment by thomsbg** [comment]
> It makes it "easy to reason about" when you just have one source of data defined in one way.

But we don't have just one source of data defined in one way. Computed data and inter-component bindings and other data are all different beasts.

> There's already that discussion of component context #2166 where another level is proposed during resolution of a template value. I wonder if we need another level of resolution here.

That discussion is what made me pull the trigger on writing up this PR. I would rather not adding another (invisible) level of resolution. The invisible/silent merging of disparate data sources is elegant and reads well for small apps. I am not proposing that ractive moves away from that. Instead, I'm brainstorming having some way to opt-in to a "strict mode". This would allow Ractive to be used for both the initial prototype of a larger project, and the subsequent iterations.

> And wouldn't it be more confusing that a, given some special doodad, can easily spin off and mean something else? It's comparable to Angular's directives...

I haven't used Angular, but I can empathize with the bad first-reaction upon seeing what seems like unnecessary syntax / symbols. Perhaps there is a better alternative.

What if there was some different way to specify which bindings to expect or require (and their types) when used as a child component?

```html
// hello.html
Hello, {{name}}!

<script>
component.exports = {
  attributes: {
    name: String // indicates that a string is required
  }
};
</script>
```

Attempting to use the component without passing a `name` attribute (`<hello>`) would throw an error, as would be passing a non-string value for name (`<hello name="{{42}}">`).

Thinking back on the "strict mode" idea (`Ractive.defaults.strict = true`), there are other useful things that this could enable. A couple of ideas (not married to any of either):

- Throwing an error or warning when a reference cannot be resolved (instead of just returning `undefined`).
- Forcing the use of `../` to traverse parent contexts, rather than doing this implicitly and automatically.

Again, I just want to reinforce that I think you should continue to be able to use Ractive in the way it is used today, taking the "no frills" approach to combining templates and data. Seeing something that "just works" without weird syntax is what makes Ractive special. It's certainly what drew me in.

However, this doesn't preclude the ability to opt-in to a stricter subset of features or mode of operation that helps you to not shoot yourself in the foot with typos, shadowed variables, etc. Allowing Ractive to grow and adapt to applications and teams of different sizes can only make it stronger.

**Comment by evs-chris** [comment]
Attributes and ambiguity warnings are now options on edge, and there's also a PR open to remove unresolved references.
