### ISSUE TITLE
Using @index while not in section fails

### ISSUE THREAD

**Issue by JustMikle** [ractivejs/ractive#2184]
Check out: http://jsfiddle.net/qsunhoL1/

```
<script id='template' type='text/ractive'>
    <input type="text" data-index="{{@index}}">
</script>
```

Throws `Uncaught TypeError: Cannot read property 'indexModels' of undefined`

Catched it after update to v0.8.0-edge from v0.7.3

**Comment by Madgvox** [comment]
Does `@index` have any use outside of iterative sections? This almost feels more like a `better error` situation. I'm going to milestone it, but I'll leave the tag off for now.

**Comment by JustMikle** [comment]
If it comes from code design (and not a bug) than it is really better to fail fast.

@index outside of section have use only for my wrapper over Ractive. So I will just make it a bit smarter.  Thank you for quick response!

**Comment by JonDum** [comment]
@JustMikle I thought you were referring to @index not working if it was in a separate template called as  partial like this http://jsfiddle.net/jondum/fxuhax5k/, but that works fine so I don't see the bug here. Of course @index won't work if it's the current context isn't iterating over something, am I missing something?

**Comment by evs-chris** [comment]
References, in the wrong place or not, shouldn't cause exceptions from within the bowels of Ractive. I don't really even feel like a warning is necessary, since it _is_ technically just `undefined`.

**Comment by martypdx** [comment]
@evs-chris :+1: 

Though an argument could be made it should return `0` :grinning:

**Comment by JonDum** [comment]
@evs-chris Ah ok, so it should just output undefined without throwing an error. Gotcha. Good find then, @JustMikle!
