### ISSUE TITLE
Partials being overwritten by data properties

### ISSUE THREAD

**Issue by TehShrike** [ractivejs/ractive#2185]
Ran into a couple weird issues with partials.

Reproducible with latest and edge.

- if your template references a partial that doesn't exist, say like `{{>butts}}`, and data object has a property `butts`, calling `ractive.resetPartial('butts', 'some totes legit template')` will not cause the partial to get reset.
- if your template references a partial that doesn't exist, like `{{>butts}}`, but your data object has a property `butts` whose value **is a string that happens to be the name of a partial**, that OTHER partial will be displayed in the place where `{{>butts}}` exists in the template.  Like the first bullet point, `resetPartial` will be unable to change the partial.

You can test the first case here: http://jsfiddle.net/ddzg0uvw/4/

You can test the second case here: http://jsfiddle.net/ddzg0uvw/3/

I have no idea how much of this behavior, if any, is desired - I certainly didn't expect any of it.

/cc @ArtskydJ

**Comment by Madgvox** [comment]
That certainly seems like unintended behavior to me.
