### ISSUE TITLE
Conditional attribute with `on-` method call events don't work

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2188]
Is this supposed to work? :)
    
```html  
<button
{{#if thing}}
on-click='set("animal", "dog")'
{{else}}
on-click='foo("cat")'
{{/if}}>Click #1</button> 
```
----
This way doesn't work either
```html
<button
on-click='{{#if thing}}set("animal", "dog") {{else}} foo() {{/if}}'
>Click #2</button> 
```
----
Nor does this. Ractive evaluates it like a normal expression and tries to insert the result instead of calling the method, but I kind of expected that already, just wanted to try it.
```html
<button
on-click='{{thing ? set("animal", "dog") : foo() }}'
>Click #3</button> 
```
----
http://plnkr.co/edit/aaAqQC?p=preview

**Comment by Madgvox** [comment]
At the very least No.2 should be working. I know you're able to add or remove attributes as in No.1, but I guess it doesn't extend to events.

**Comment by heavyk** [comment]
why not just do:

```html
<button on-click="click">Click me</button>
```

```js
onconfig () {
  this.on('click', (event) => {
    if (this.get('thing')) this.set('animal', 'dog')
    else this.foo('cat')
  })
}
```

**Comment by JonDum** [comment]
@heavyk Of course that's an option still, and I've used that many many times. This was more of a question of whether this is working as intended or not.

Also there's so many times where I would rather have it declarative then switch to imperative event handlers. As a real world example, in one of my apps there are multiple supported `languages` that may or may not be available and I need to have a button open a modal if there are multiple languages or call a method on the prototype of ractive instance if there's only a single `language` available. In this specific scenario it's a lot cleaner for me to write:

```html
on-click="{{#if languages.length > 0}} set("modal", "newProgramModal") {{else}} reset() {{/if}}"
```
If it was anymore complicated than that I would switch to a proxy event, but it's annoying making a bunch of `this.on('')`'s all over the place when I already have the methods I need on the prototype.

**Comment by evs-chris** [comment]
See #1270 and #1496.

I have a way to do it, but it's not exactly ideal. I can port #1496 to edge if the masterminds of Ractive think it'll do, but I still haven't cobbled together a fragment based approach to avoid the double parse.

**Comment by JonDum** [comment]
@evs-chris Ah, that answers my question. Would you prefer I leave this open or close and direct conversation to #1496?

**Comment by martypdx** [comment]
@JonDum This is on the TODO list. It's something we need to upgrade to new syntax for events, decorators and transitions.

What currently works for events is only the `:` style handler declarations and you put it around the handler name:

```html
<button on-click='{{#if thing}}bar{{else}}foo{{/if}}: {{animal}}, {{dog}}'>Click #3</button> 
```

You can do same thing for decorators and transitions, but they only get evaluated and render time and will not update.

The current conditional attributes only include raw element attributes and don't process for events, decorators and transitions.

Where we want to end up is "real" ractive fragments like you tried. It would also enable attribute partials, though we'd probably have to come up with semantics for no element. So glimpse of the future might look like:

```html
{{#partial coolstuff}}
< as-tooltip='{ title }' fade-in-out {{#if editable}}on-tap='set( "foo", bar)'{{/if}} >
{{/partial}}

<button {{>coolstuff}}>click me</button>
<label {{>coolstuff}} on-mouseover='doThis()'>fizz buzz</label>
```

**Comment by martypdx** [comment]
@evs-chris for me the implementation of attribute fragments seems straightforward, but not sure where to start on the parsing to get it to process the sections for attributes, decorators, etc.

**Comment by heavyk** [comment]
gotcha. I didn't actually know that was a thing that could be done.

@martypdx - woah that future look is quite impressive! omg that would be soo cool.

**Comment by evs-chris** [comment]
@martypdx that future syntax looks like an interesting start. I'd say that there would have to be a special kind of partial block to handle it though, as an element-less element would be pretty tricky to parse out. Something like `{{#partial< coolstuff}}attrs="and" {{#consditions}}and whatnot{{/}}{{/partial}}` would make it easy to say that 'this partial may only be used in an an attr context'. Although, I don't know how that would work with instance partials. Perhaps a partial pragma that set a flag on the parsed partial and threw the parser into attr mode? `{{!attrs}} foo="{{bar}}" {{#if baz}}on-click="do('something', cool)"{{/if}}`.

**Comment by martypdx** [comment]
I'm changing this to a post `0.8` enhancement as it is the ractive behavior that has existed for some time.

Definitely want to address, I don't think it should keep `0.8` from going out...

**Comment by evs-chris** [comment]
Fixed in edge :smile:
