### ISSUE TITLE
How to set app.data in mustaches?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2190]
Can we set a ractive variable, say `my_data` in mustaches, so that we can use the same variable elsewhere in the document? For example: 

```
<p>something's index is {{ my_data }} </p> 

{{#each something:i}}
{{ my_data = i }}
{{/each}}
```

**Comment by Madgvox** [comment]
What is your use case? In that example `my_data` would either always be equal to the length of the array - 1, or 0, depending on the execution order, so I don't really see the need to define a variable to it in the template. You can alias variables or define new ones in a context using the `{{with}}` block and an object:

```html
{{#with { foo: 'bar' } }}
  {{ foo }}
{{/with}}
```

**Comment by ceremcem** [comment]
After a bit thinking, it's useless in my case, so I'm closing this issue. However, the `{{#with}}` block does not help either: http://jsfiddle.net/q8vcbey2/2

**Comment by Madgvox** [comment]
@ceremcem it seems like you're looking for something more along the lines of linking keypaths, which @evs-chris has been working on [here](https://github.com/ractivejs/ractive/pull/2172).

**Comment by ceremcem** [comment]
Yes, it seems so. I may watch that progress.
