### ISSUE TITLE
Improper detection of context chain in #resolveAmbiguousReference

### ISSUE THREAD

**Issue by NikhilVerma** [ractivejs/ractive#2191]
Example: http://jsbin.com/xafadaxolu/1/edit?html,js,output

So if a fragment is not a root it's not marked that it has a context chain. And then if that is followed by a context which has a prototype property. It doesn't work.

![image](https://cloud.githubusercontent.com/assets/87832/10309559/dd4349f6-6c5a-11e5-89ae-968bb0141c56.png)

My solution is to patch Model.prototype.has() but perhaps there is a better way?

```javascript
	has ( key ) {
		const value = this.get();
		if ( !value ) {
			return false;
		}

		var hasProperty = hasProp.call( value, key );
		if ( hasProperty ) {
			return true;
		}

		// We climb up the constructor chain to find if one of them contains the key
		var constructor = value.constructor;
		while ( constructor !== Function && constructor !== Array && constructor !== Object) {
			if ( hasProp.call( constructor.prototype, key ) ) {
				return true;
			}

			constructor = constructor.constructor;
		}

		return false;
	}
```

See PR: #2192

**Comment by fskreuz** [comment]
Best if you open this one as a PR. Then everyone can review it, and see your progress in the form of successive commits.

**Comment by NikhilVerma** [comment]
@fskreuz done!
