### ISSUE TITLE
Ractive js not working on iOS 9 Safari - iPad & iPhone

### ISSUE THREAD

**Issue by evromalarkey** [ractivejs/ractive#2193]
Hello,

I found a critical bug with ractive js on iOS 9 Safari. The problem is that the page can't be loaded and keeps refreshing until Safari get message "A problem repeatedly occurred on page"

Try some of the examples on http://examples.ractivejs.org/, some of them have problems with loading,
eg.: http://examples.ractivejs.org/illustration

This problem occurs on heavy load applications with lot of code in template. Our application has 1110 rows in template and it fails to load it. But if we limit it on 300 it works.

Any help is appreciated, I spent some time on debuging this and it's only happening on iOS 9 devices. On iOS 8 devices it's working, but the loading is extremely long.

**Comment by MartinKolarik** [comment]
Indeed, the example page doesn't load in Safari, and if opened in Chrome, it crashes the whole browser.

**Comment by evs-chris** [comment]
I have no Apple things with which to test (:\), but from googling around a bit, it looks like pages that use lots of memory are known to crash iOS Safari, especially on older devices with less memory. If you add in pagination does it keep it from crashing?

**Comment by evromalarkey** [comment]
well pagination is kind of out of question for our aplication. Anyway we tested this on iPhone 4S and iPad mini with iOS9 and there was the problem. But on old iPhone 4 and old iPad with older iOS it worked, but the loading was longer.

**Comment by fskreuz** [comment]
Was waiting for someone else to suspect iOS9. Throwing this info for what it's worth. Maybe iOS9 has messed up timing or something. Angular (I believe we use 1.2.x) also has problems with iOS9, where apps end up in an infinite digest cycle before Angular bails out. This may also be the case with Ractive, as indicated by the repeated errors and long load times.

**Comment by skeptic35** [comment]
Sorry, can't hold it back: Not running on iOS9 Safari is imho entirely forgivable ;)

**Comment by evs-chris** [comment]
I just ran into this with a co-worker's iThing. It works just fine in iOS8, but some heavier pages just completely bail on iOS9. It gives some error about the page failed to run multiple times so it's giving up. Let me just pull up the handy mobile developer console oh wait that's not a thing that would be totally useful.

**Comment by heavyk** [comment]
you have to connect over cable to get the console on your MacbookPro

**Comment by JonDum** [comment]
>you have to connect over cable to get the console on your MacbookPro
and only on safari lol

**Comment by Rich-Harris** [comment]
Some breadcrumbs via Twitter: Angular's problem was apparently related to the use of window.location.hash, and they worked around it like so: https://gist.github.com/IgorMinar/863acd413e3925bf282c. I haven't had a chance to look into whether something similar would fix this issue (it seems that it only affects real devices, and not the iOS simulator, which will make debugging lots of fun), but it's a starting point...

**Comment by evs-chris** [comment]
I did some tracking on this in my app today using alerts peppered through Ractive's init (ugh) and it looks like it's going to lunch somewhere during the initial parse of the template in 0.7.3. My captive test device had to go home for the day, but I'll try to track it down within the parser tomorrow.

**Comment by evs-chris** [comment]
I have now tracked this down to iOS 9 Safari not being able to parse giant-ish templates. For instance, I had one with a ton (~30) of partials in it that was a total of ~1400 lines. Splitting them out into their own individual script tags made the problem go away. I suspect it's got something to do with increased OS resource usage and/or a change in how substrings are handled, since the parser substrings a lot.

**Comment by martypdx** [comment]
@evs-chris just to be clear, it's not rendering. If you pre-parse the template then it works?

**Comment by evs-chris** [comment]
Correct. It's just parsing that kills it. Parsing the same amount of template in smaller chunks works fine. While I didn't try it specifically here, I use equally large or larger templates pre-parsed elsewhere, and they work as well.

**Comment by evs-chris** [comment]
I hacked the parser to avoid substrings (see the `substr` branch), and it does indeed work on iOS9 devices. Unfortunately it also increases the parse time by an order of magnitude. If anyone else would like to hack on that branch, please feel free to do so. I'm inclined to say close this as cant-fix, since it's not our bug. Do we have a known issues spot in the docs somewhere?

**Comment by evs-chris** [comment]
I just re-read the original post, and it seems in my various alert shotgunnings and head-to-desk interactions I forgot about the part of this issue that involved rendering a large number of rows. I haven't run into that part of this issue yet, but the most I've had to render at a time so far has been ~150 items.

@evromalarkey by rows in the template, do you mean items in an array that are being used in an `{{#each}}`? Can you give me a failing example to work with that doesn't involve the parsing issue? Also, edge seems to be considerably less resource intensive than 0.7.3. Have you tried your code on edge yet? edge seems to have stabilized to the point that I'm not longer finding bugs from my various apps, for whatever that's worth.

**Comment by ceremcem** [comment]
So do we have a workaround by preparsing? How could we preparse?

**Comment by martypdx** [comment]
@ceremcem It means instead of passing in `<p>Hello World</p>` you run `Ractive.parse('<p>Hello World</p>') at build time. Implementation details are specific to your build/delivery process.

**Comment by ceremcem** [comment]
@martypdx  I didn't follow the documentation. OK, I understand we get an object, like

```
[{"t":7,"e":"div","a":{"class":"gallery"},"f":[{"t":4,"r":"items","i":"i","f":[" ",{"t":7,"e":"figure","a":{"intro":"staggered"},"f":[{"t":7,"e":"img","a":{"class":"thumbnail","src":["assets/images/",{"t":2,"r":"id","p":4},".jpg"]}}," ",{"t":7,"e":"figcaption","f":[{"t":2,"x":{"r":["i"],"s":"❖0+1"},"p":4},": ",{"t":2,"r":"description","p":4}]}],"v":{"tap":"select"}}," "],"p":1}]}]
```
Can you have a chance to give steps to implement this by hand? For example, I can run `console.log(Ractive.parse(THE CONTENT))`,  get this result to the console, copy and paste into a javascript file and assign it to a variable. What do I need after that?

**Comment by JonDum** [comment]
Use a module system @ceremcem . 
[ractive-loader](https://www.npmjs.com/package/ractive-loader) makes it dead easy to use templates and have them parsed automatically. [rvc](https://github.com/ractivejs/rvc) can do this too I think. There's a bunch. Since you're just calling `Ractive.parse()` it's real easy to add that into a build system so you don't have to copy and paste like that. If you need a full example, I keep up to date a little boilerplate for myself and coworkers as a starting point https://github.com/JonDum/Web-Boilerplate for new projects.

**Comment by ceremcem** [comment]
@JonDum  I'm convinced that I need to try switching to webpack, but I need a very quick workaround today. Now I'm splitting the single page web application into different html files (it works). [Our project](https://github.com/ceremcem/aktos-scada) uses brunch.io, so I don't know how to benefit from ractive-loader. `rvc` seems to be a little bit complex to me at this time. Isn't there any simple manual way?

**Comment by MartinKolarik** [comment]
@ceremcem 

>Isn't there any simple manual way?

As @JonDum pointed out, you just need to pass the output of `Ractive.parse()` to `new Ractive()`
```js
new Ractive({ template: /* output of Ractive.parse() goes here */ });
```

**Comment by martypdx** [comment]
@ceremcem:

```js
var fs = require( 'fs' );
var path = require( 'path' );
var Ractive = require( 'ractive' );

// this assumes getting your templates from a directory
var dir = './templates';
var templates = {};

fs.readdirSync( dir ).forEach( function( file ){
	var name = path.basename( file, '.html' ); //assuming templates are .html
	var filePath = path.join( dir, file );
	var unparsed = fs.readFileSync( filePath ).toString();
	templates[ name ] = Ractive.parse( unparsed );
});

var js = 'var templates = ' + JSON.stringify( templates /*, true, 2*/ ) + ';'
fs.writeFileSync( 'templates.js', js );
```

Then if you include that file via `<script src='templates.js'></script>` you can access:

```
new Ractive({
    template: templates.foo  //name of template file
});

**Comment by ceremcem** [comment]
@martypdx Thank you for Node.js sample. I was working on a client side version of this code since @JonDum edited his post and pointed out the way to go but I didn't make the client-side file download thing worked. Then [I edited your sample script](https://github.com/ceremcem/aktos-scada/blob/fix-ios9-ractive/preparse.js) accordingly and it worked out. Tomorrow I'll find an iPhone-5 and test it. Thank you both.

**Comment by martypdx** [comment]
@ceremcem :+1:

**Comment by ceremcem** [comment]
Yess! Now it works on iOS9, on desktop browsers and Android 4/5 phones; **but** the weird result is that it stopped working on iPhone 4S (iOS7), older Android devices, new Android tablets. Why preparsing might cause any trouble?

**Comment by martypdx** [comment]
@ceremcem when I first loaded the page into chrome it didn't work and had a "couldn't load module /" error. On refresh it worked. Could it be a timing issue with how your loading modules that shows up on some devices? Just a wild guess...

**Comment by ceremcem** [comment]
@martypdx I don't know if it is a timing issue or not, but I started to try another ways, starting from your original suggestion: I dropped usage of  `require`, loaded the preparsed object externally as you mentioned earlier. As far as I can test, it works on Safari and Chrome on iPhone4S, on Iceweasel on Linux desktop, on Chrome and Dolphin on Galaxy S4 (which was not working before). I'll check if it works on iOS9 devices as soon as I can. Thank you again and again and again :)

**Comment by jmellicker** [comment]
We had the "A problem repeatedly occurred on page" problem in iOS Safari with a project that loaded about 34 components up front using Ractive.load.

We solved this by creating a structure where each page route loaded only the needed components (anywhere from 1 to 9). The app works great on iOS now, we haven't seen that error since.

**Comment by zendar** [comment]
We also solved our problems with io9 by pre-parsing the template. It isn't an optimal solution, but it works. :-)

**Comment by evromalarkey** [comment]
I just get chance to look into this problem again on my project and I can confirm that preparsing indeed fix this issue! Thanks to everyone

**Comment by Madgvox** [comment]
Fantastic! :+1: I'll close this issue then as a solution has been found.

**Comment by keith5000** [comment]
I disagree that this issue should be closed. The problem still exists in Ractive. Preparsing is just a workaround and will not work for everybody.

**Comment by evs-chris** [comment]
To be fair, the problem exists in Safari. I actually made a branch that didn't substring for every parser op, and it did work on Safari on iOS. It also slowed down parsing so much that it took roughly 135x longer.

Preparsing isn't the only solution though, as you can also split large templates into multiple partials and Safari will chug right on through it. The arbitrary limit that worked for my app was ~100 lines of template.

**Comment by keith5000** [comment]
Does Apple have any plans to fix this in Safari? (Or is the bug in Webkit since Chrome on iOS also has this bug?)

**Comment by evs-chris** [comment]
I've no idea what Apple plans to do, or even if they have a bug they are tracking for this. I'm not an Apple user or developer, so i don't think I could report or even inquire. Improvements in their js engine should eventually resolve the issue, since it looks like a memory leak/resource exhaustion bug introduced by their last round of performance enhancements for Safari.

There is only Safari on iOS wrapped in different guises, so yes, this affects all browsers on iDevices. In fact, Chrome on iOS dies horribly when it encounters this bug.

**Comment by keith5000** [comment]
That's very discouraging. Considering iOS 9 has been out for several months now with several updates thus far without addressing the memory leak, I have to guess that doing so is not high on Apple's list of priorities. If Ractive can't work around this problem then it is a very limited solution. I recently (pre-iOS 9) rolled out a large web application using Ractive and now I'm in the unfortunate position of having to completely rewrite it to work around the iOS 9 bug. Based on the Ractive team's reluctance to address this issue, I have to consider dropping Ractive and use something else that can scale.

At the very least, I suggest that you state the iOS 9 limitation somewhere in the documentation.

**Comment by MartinKolarik** [comment]
@keith5000 you *can* work around this problem by pre-parsing the template, which is recommended when running in production anyway.

**Comment by ceremcem** [comment]
We are on our way to switch to webpack, as recommended before. So, as no
one look at the html source code, who cares if we preparsed or not. That
seems an appropriate solution to me. By the way, doesn't preparsing give us
a faster application? If so, I may thank Apple for introducing such a bug
which make me meet with the preparsing option.

2016-01-13 16:37 GMT+02:00 Martin Kolárik <notifications@github.com>:

**Comment by fskreuz** [comment]
> By the way, doesn't preparsing give us a faster application?

Yes. Avoids having Ractive do parsing on runtime, the part that chokes an iDevice.

> If so, I may thank Apple for introducing such a bug which make me meet with the preparsing option.

We can all thank Apple and this bug for reminding us to deploy optimized code to production, and uncovering Ractive users who target constrained systems (*cough* iOS *cough*).

If only we had iOS devices handy to test these things... (sorry, Android user here)

**Comment by martypdx** [comment]
I'm, going to reopen this issue, as I suspect it will be easier to find for devs searching gh issues if we keep it open. 

Priority is low because it's high effort and there's a clear work-around that's "best practices" anyway. 

But for the developer, it *is* a bug regardless of whether it is in Ractive or iOS Safari.

**Comment by martypdx** [comment]
> rolled out a large web application using Ractive and now I'm in the unfortunate position of having to completely rewrite it

@keith5000 how do you currently write and deliver your app? Are the templates `script` tags in the `html` page(s)?

**Comment by evs-chris** [comment]
I was also going to add a known issues page to the docs and link to it on the welcome page.

**Comment by djp9803** [comment]
<frustrated> I am using templates in script tags within html pages (bottle templates).  I love ractive, but as others have asked, is there no SIMPLE way to parse the templates without having to learn npm, grunt, gulp and other tools first? I don't use any of those tools or "build" my application.  Even a method to get the parsed templates (as @ceremcem commented) to cut and paste would be helpful.  Thanks. </frustrated>

**Comment by ceremcem** [comment]
@djp9803 Doesn't [the nodejs script](https://github.com/ractivejs/ractive/issues/2193#issuecomment-158227609) work for you?

**Comment by djp9803** [comment]
@ceremcem  Yes, sort of.  It is including a lot of things that are not part of the actual template, but I think I can just cut/paste the appropriate section.  Thanks.

**Comment by ceremcem** [comment]
@evs-chris closing this bug causes false sense that "Ractivejs has solved this problem". Would you consider leaving it open?

**Comment by evs-chris** [comment]
Ractive _can't_ solve this problem, though. There's a warning about large-ish templates in the docs that suggests using pre-parsed templates if you have them and support safari on ios, and I was trying to clean up some of our giant backlog of issues that are handled to the extent that we can.

In the absence of a fix for safari on ios dying with a bunch of substringing, you can work around the safari bug by splitting large-ish templates into smaller `<script>` partials if you can't pre-parse templates. If you _can_ pre-parse templates, that's even better, as it's faster.

I did another test with the parser replacing substrings with regexes adjusted to start at the correct position with `lastIndex` twiddling. It is still _abysmally_ slow.

Given all of that, should this still be left open?

**Comment by ghost** [comment]
This _could_ be left open, but then... who's still on iOS 9? I'm under the assumption that iDevices get updated regularly and iOS 10 has been out for quite a while now. There might be little need to look into this unless it still happens on iOS 10.

<sub>Disclaimer: Android user here.</sub>

**Comment by ceremcem** [comment]
For those who use Browserify and want to preparse the templates continuously (in `.html` or `.pug`/`.jade` format) may use [this browserify transform](https://github.com/aktos-io/Scada.js/blob/master/src/lib/aea/ractive-preparserify.ls).

Enable this transform [in your Gulp file](https://github.com/aktos-io/Scada.js/blob/5b9f2af49d1ced5e70fca716b167ae7e584ac397/gulpfile.ls#L132) and then: 

Replace `template: '#my-template'` with
    * `template: RACTIVE_PREPARSE('my-template.pug')` if file contains only template code
    * `template: RACTIVE_PREPARSE('my-template.pug', '#some-template-id')` if file contains multiple template codes
# Example:

You may take a look at [the components](https://github.com/aktos-io/Scada.js/tree/master/src/client/components) used in [Scada.js](https://github.com/aktos-io/scada.js) for more examples. Briefly: 

In the main ractive instance:
```
ractive = new Ractive do
    el: '#main-output'
    template: RACTIVE_PREPARSE('base.pug')
```

In a component file:
```
Ractive.components.checkbox = Ractive.extend do
    template: RACTIVE_PREPARSE('index.pug')
    isolated: yes 
```

# TODO 

Since altering a template file does not change its appropriate `.js` file, using `cache` with `browserify` fails to update while in continuous build mode. Till [this problem is resolved](http://stackoverflow.com/questions/40958076/how-to-tell-browserify-cache-that-one-file-depends-another-file) we need to disable browserify caching.

**Comment by ceremcem** [comment]
I don't want to put the clock back for this issue, but probably the same problem bite me again. Page is not displayed on specifically IPhone 5 models. I'm preparsing the templates, there is nothing left for the browser to do. The only resort I could think of is sending components one after another, after page loaded and `new Ractive` completed. I don't know how to make this happen though. 

Is there any advice to follow?

**Comment by ghost** [comment]
@ceremcem If it's "5" and not "5S", we might need to know the OS and Safari version. I _think_ Apple skipped updates on those devices so it might not have the latest and greatest stuff (I might be wrong. it's probably iOS 11 news I read). Stack trace would be nice too. 😄

**Comment by evs-chris** [comment]
Are you _sure_ there's nothing else being parsed on the phone? You could try using the runtime-only build, connecting with developer tools (is that a thing for ios safari?), and seeing if anything blows up. I haven't seen any problems that weren't related to big parsing on phones as yet.

**Comment by evs-chris** [comment]
One thing that just occurred to me - have you recently moved to 0.9? Safari on an iphone 5 may be old enough that it requires polyfills, which are in v0.9-dev but require including the polyfills file for 0.9.0-0.9.2. I'm going to be cutting 0.9.3 soon(tm), so that will fix it if it's a polyfill issue.

**Comment by ceremcem** [comment]
@fskreuz  I don't have an Iphone either, so let me grab someone's

@evs-chris I'm pretty sure there is nothing left (except [some little components](https://github.com/aktos-io/scada.js/blob/e7d2ed2789edb54c453692be4c15a01aa72b378b/components/io-pushbutton/index.ls#L4-L18). Would they hurt? ). Again, I need to grab someone's IPhone 5 first. (Would it be reliable to redirect the `console` into some `div` in the page so that I could ask users copy and paste the console output to me?)

Yes, I'm using 0.9.2 currently. Days ago [I added ` "babel-polyfill": "^6.23.0"`](https://github.com/aktos-io/scada.js/tree/e7d2ed2789edb54c453692be4c15a01aa72b378b/vendor/000.babel) into my builds so that the application can be viewed on my old Android phone (which was crashing because `Object.assign is not a function`). Wouldn't it suffice already?

**Comment by evs-chris** [comment]
I _think_ the babel polyfills should cover it. If there's no other good way to debug, then yes, loading up a div or pre and a console proxy that just dumps into it is probably as close as you're going to get to debugging. I don't know how reliable that will be, but it should at least give you console messages that might hint at what's happening. If you can wrap your main ractive instantiation in a try catch with a console log on error, that would probably help too (may even get a stacktrace).

As far as architecture with lightening the main bundle, the only thing I've seen that does that in a reasonably easy way is webpack. I haven't poked at browserify too much, but there may be a way to do code-splitting there too. I'm slowly working on an example app and architecture that will be integrated into the playground as a sort of app template - kinda like svelte's repl.

**Comment by ceremcem** [comment]
Here is my progress so far: 

I redirected console to a `pre` and got the following output on Iphone5s: 

```
You're running Ractive 0.9.3 in debug mode - messages will be printed to the console to help you fix problems and optimise your application.

To disable debug mode, add this line at the start of your app:
  Ractive.DEBUG = false;

To disable debug mode when your app is minified, add this snippet:
  Ractive.DEBUG = /unminified/.test(function(){/unminified/});

Get help and support:
  http://docs.ractivejs.org
  http://stackoverflow.com/questions/tagged/ractivejs
  http://groups.google.com/forum/#!forum/ractive-js
  http://twitter.com/ractivejs

Found a bug? Raise an issue:
  https://github.com/ractivejs/ractive/issues


Error in new Ractive: 
page loaded. data length: 
2157276
Error in new Ractive:
```

The "Error in new Ractive:" part is produced by the following code: 

```
try {
  ractive = new Ractive({
    el: '#main-output',
    template: RACTIVE_PREPARSE('app.pug'),
     ....
}
catch (e$) {
  e = e$;
  console.log("Error in new Ractive: ", e);
}
```

I don't know what I'm doing wrong but I can not get the stack trace. 

Working on it.

**Comment by ghost** [comment]
Oooh! A Jade preparser? 😄

**Comment by ceremcem** [comment]
...here is the stack trace: 

```js
Error in new Ractive: 
{
  "message": "QuotaExceededError: DOM Exception 22",
  "stack": "setItem@[native code]\nset@https://aktos.io/scada/:63:21587\nhttps://aktos.io/scada/:3:6647\nn@https://aktos.io/scada/js/vendor.js:5:13922\ndispatch@https://aktos.io/scada/js/vendor.js:8:2369\nvl@https://aktos.io/scada/js/vendor.js:8:2072\nxt@https://aktos.io/scada/js/vendor.js:5:14866\nhttps://aktos.io/scada/js/vendor.js:5:14040\nforEach@[native code]\nhttps://aktos.io/scada/js/vendor.js:5:14006\nforEach@[native code]\nwt@https://aktos.io/scada/js/vendor.js:5:13809\noninit@https://aktos.io/scada/:3:6614\nfire@https://aktos.io/scada/js/vendor.js:7:27080\nnr@https://aktos.io/scada/js/vendor.js:6:27904\nnr@https://aktos.io/scada/js/vendor.js:6:27920\nend@https://aktos.io/scada/js/vendor.js:11:12898\nir@https://aktos.io/scada/js/vendor.js:6:28276\nDr@https://aktos.io/scada/js/vendor.js:7:2812\nhttps://aktos.io/scada/:65:6168\ni@https://aktos.io/scada/:1:258\ne@https://aktos.io/scada/:1:422\nglobal code@https://aktos.io/scada/:1:438\nappendChild@[native code]\nn@https://aktos.io/scada/js/vendor.js:2:826\nglobalEval@https://aktos.io/scada/js/vendor.js:2:15220\ntext script@https://aktos.io/scada/js/vendor.js:4:18109\nee@https://aktos.io/scada/js/vendor.js:2:12870\ni@https://aktos.io/scada/js/vendor.js:4:12185\nhttps://aktos.io/scada/js/vendor.js:4:17379",
  "code": 22,
  "name": "QuotaExceededError",
  "line": 63,
  "column": 21587,
  "sourceURL": "https://aktos.io/scada/"
}
page loaded. data length: 
2157276
Error in new Ractive: 
{
  "message": "QuotaExceededError: DOM Exception 22",
  "stack": "setItem@[native code]\nset@https://aktos.io/scada/:63:21587\nhttps://aktos.io/scada/:3:6647\nn@https://aktos.io/scada/js/vendor.js:5:13922\ndispatch@https://aktos.io/scada/js/vendor.js:8:2369\nvl@https://aktos.io/scada/js/vendor.js:8:2072\nxt@https://aktos.io/scada/js/vendor.js:5:14866\nhttps://aktos.io/scada/js/vendor.js:5:14040\nforEach@[native code]\nhttps://aktos.io/scada/js/vendor.js:5:14006\nforEach@[native code]\nwt@https://aktos.io/scada/js/vendor.js:5:13809\noninit@https://aktos.io/scada/:3:6614\nfire@https://aktos.io/scada/js/vendor.js:7:27080\nnr@https://aktos.io/scada/js/vendor.js:6:27904\nnr@https://aktos.io/scada/js/vendor.js:6:27920\nend@https://aktos.io/scada/js/vendor.js:11:12898\nir@https://aktos.io/scada/js/vendor.js:6:28276\nDr@https://aktos.io/scada/js/vendor.js:7:2812\nhttps://aktos.io/scada/:65:6168\ni@https://aktos.io/scada/:1:258\ne@https://aktos.io/scada/:1:422\nglobal code@https://aktos.io/scada/:1:438\nappendChild@[native code]\naddScript@https://aktos.io/scada/:64:65\nsuccess@https://aktos.io/scada/:75:21\nc@https://aktos.io/scada/js/vendor.js:3:8007\nfireWith@https://aktos.io/scada/js/vendor.js:3:8780\ni@https://aktos.io/scada/js/vendor.js:4:12512\nhttps://aktos.io/scada/js/vendor.js:4:17379",
  "code": 22,
  "name": "QuotaExceededError",
  "line": 63,
  "column": 21587,
  "sourceURL": "https://aktos.io/scada/"
}
```

**Comment by ceremcem** [comment]
@fskreuz Yess :))

**Comment by evs-chris** [comment]
Oh my. Is there any way you can run against a non-minified vendor.js? I can pick ractive code out of other libs, but unmangling minified code will take quite some time.

What comes out of `RACTIVE_PREPARSE('app.pug')`? Is it a string or an object?

**Comment by evs-chris** [comment]
Though, a quick google of the error seems to indicate that it's related to `localStorage`. Is there some chain of events happening whereby your app is writing to `localStorage` during init?

**Comment by ceremcem** [comment]
@evs-chris  I was working on error output of non-minified version but as you mentioned the `localStorage`, let me explain: Yes, there is a [piece of code](https://github.com/aktos-io/scada.js/blob/34f0b822905ded9b75642e5d0ce30339957ba07c/src/lib/aea/browser-storage.ls#L1-L12) that tries to read session token from `localStorage` and tries to login to the server with that token. Let me disable it.

**Comment by ceremcem** [comment]
Okay, wrapping `setItem` with `try/catch` solved the problem. Now the application is correctly displayed on IPhone5s. I'll find a workaround for the `localStorage`, it's really not a problem at all. 


Thank you @evs-chris !!!
