### ISSUE TITLE
{{{triple}}} doesn't work inside textarea

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#2197]
There's no particular reason why a triple *should* work inside a textarea, but the error message that results isn't particularly helpful: http://jsfiddle.net/rich_harris/ut7qzn2u/

Related: we might consider treating `<textarea>{{foo}}</textarea>` the same as `<textarea value='{{foo}}'/>` – in particular it probably makes a bit more sense in the context of a readonly textarea.

Via [this SO question](http://stackoverflow.com/questions/32989662/ractivejs-data-binding-textarea-causes-cannot-call-removechild-with-null).

**Comment by mikemaccana** [comment]
In this case it's shell code inside a text area, which would contain e.g. greater than & less than chars. The thought process here was 'we generated the shell code, so we trust it: don't turn `<` into `&lt;`, and use `{{{ }}}`. Does that make sense?

**Comment by Rich-Harris** [comment]
Yep – this is fixed in edge now thanks to @evs-chris

**Comment by mikemaccana** [comment]
🎉@evs-chris🎉
