### ISSUE TITLE
Using .set with an object can trigger inconsistant observers

### ISSUE THREAD

**Issue by ngasull** [ractivejs/ractive#2200]
_Ractive lastest & edge_

When `.set`ting a new object of properties, Ractive seem to process each of them one at time. I would expect setting all of them at the same time.

Consider this example: http://jsfiddle.net/bd29n0w6/ _(result in the console)_

The parent view contains two children that are displayed conditionally like a navigation routing point. When I navigate to another view, I want to set the view name **and** the parameters at the same time the parent router.

What happens is that `ChildA` receives `ChildB`'s params before `currentView` is evaluated.

Am I doing anything wrong? Is this a bug?

Thank you for the support!

_Even though I couldn't find any similar issue already open, if there is, please close this one, thanks!_

**Comment by JonDum** [comment]
I've also noticed the same thing when items implicitly depend on each other. Yet to find a way to set the correct resolution order other than having a crap ton of error checking and some try catches. :|

**Comment by evs-chris** [comment]
`set` with an object has always been a shortcut for calling `set` multiple times. So as it stands, it's not really a bug.

I suppose the question is should `set` with an object defer dependant notification untill after the model has been set for each key. It looks like that would be possible, but from a cursory glance, it wouldn't be pretty.

**Comment by heavyk** [comment]
@evs-chris , yes I actually thought it was an optimization until I ran into this as well. in the end, I just use multiple sets... though, it would be nice to have the set object defer the notifications, definitely. we could simplify some code that way.

**Comment by ngasull** [comment]
@evs-chris fair enough, thanks for the info. It would be a great enhancement to be able to set multiple data at the same time though, both in terms of performance (avoid double runloop / DOM update) and consistency I would say.

Any chance we have it on a future release?

**Comment by martypdx** [comment]
> set with an object has always been a shortcut for calling set multiple times

> It would be a great enhancement to be able to set multiple data at the same time though, both in terms of performance (avoid double runloop / DOM update) and consistency I would say

Actually a hash object `set` _is_ different than calling set multiple times. It [only calls `runloop.end()` once ](https://github.com/ractivejs/ractive/blob/dev/src/Ractive/prototype/set.js#L24). This means that while dependents are _notified_ on each set, DOM updates are only processed once at the end after all the sets have been made.

Given that observers are notified prior to DOM changes being made, it makes sense that the code example, as written, behaves as it does. What isn't as clearly defined is what should happen if the observe is passed `{ defer: true }` which means it should be called after the DOM updated. Currently it behaves identically - you could argue it shouldn't.

In any case, swapping out sections like this does tend to be more difficult than it seems it should. And it can be more difficult if you have transitions defined. 

How I would manage this case (and given that the details matter, it may be different for your "real" use-case) is to clear the data that drives the section, then set the new data. Without transitions that would mean (see http://jsfiddle.net/bd29n0w6/3/):

```js
parent.set({ currentView: '',  params: null });
parent.set({ currentView,  params });
```

With transitions something more like (http://jsfiddle.net/bd29n0w6/4/):

```js
parent.set({ currentView: '',  params: null }).then( () => {
	parent.set({ currentView,  params });
});                                               
```

**Comment by ngasull** [comment]
@martypdx Interesting. Using an empty view seems to be a good workaround to change `params` without giving any intermediary to the views and I will use it for my navigation stuff. Thanks for details & advices!

**Comment by evs-chris** [comment]
If you use deferred observers, it looks like the issue is resolved: http://jsfiddle.net/bd29n0w6/5/
