### ISSUE TITLE
"itemscope" boolean attribute is not added to the DOM element

### ISSUE THREAD

**Issue by wmcmurray** [ractivejs/ractive#2201]
While trying to add an `itemscope` attribute to an element, I noticed that no matter what I do, It is never added to the DOM element in the rendered template...

I've tried :
`<div itemscope></div>`
`<div itemscope=""></div>`
`<div itemscope="itemscope"></div>`
`<div itemscope="true"></div>`

...and It never worked. Am I missing something ?

[Code exemple here](http://jsfiddle.net/jpm4w8e2/1/)

**Comment by martypdx** [comment]
What's happening is that it passes the `booleanAttribute` test [here](https://github.com/ractivejs/ractive/blob/dev/src/view/items/element/Attribute.js#L89), but earlier when it [tests the node](https://github.com/ractivejs/ractive/blob/dev/src/view/items/element/Attribute.js#L83) for that property it doesn't exist.

So when it goes to set it [here](https://github.com/ractivejs/ractive/blob/dev/src/view/items/element/attribute/getUpdateDelegate.js#L186) it's setting an undefined property.

I don't know if the answer is to correctly set the `propertyName` on the node, or use `setAttribute` instead.

**Comment by wmcmurray** [comment]
Thanx for the investigation ! I am not familiar with Ractive codebase but I just made a test and realized that setting the property `itemScope` to a DOM element dosen't set it's attribute automatically, could it be the problem ?

```
var test1 = document.createElement('div');
console.log('itemscope - before : ', test1.itemscope, test1.attributes);
test1.itemscope = true;
console.log('itemscope - after : ', test1.itemscope, test1.attributes);

var test2 = document.createElement('input');
console.log('required - before : ', test2.required, test2.attributes);
test2.required = true;
console.log('required - after : ', test2.required, test2.attributes);
```

Which prints :

```
itemscope - before :  undefined, {}
itemscope - after :  true, {}
required - before :  false, {}
required - after :  true, {0: required}
```

So the attribute is set using the more "regular" property `required`, and it is not with more "obscure" properties... There is probably other properties like this, I just don't know exactly how they are called :open_mouth:
