### ISSUE TITLE
Wrong transition.node when setting

### ISSUE THREAD

**Issue by nicolas-t** [ractivejs/ractive#2203]
Hi, 

I came across something that looks like a bug (but that's probably not one)

I have an array of 3 elements 

```
ractive.get('items') // ['A', 'B', 'C']
```

and I set to 2 elements : 

```
ractive.set('items', ['B', 'C'])
```

Outro transition is called because one element has been removed from the dom
But transition.node is not the one i expected.
See this jsfiddle : 
http://jsfiddle.net/t87hL1ny/2/ (open the console to get the point)

Of course If I use shift instead of set it works : `ractive.shift('items')`

**Comment by nicolas-t** [comment]
Oops, I think I found it, i need to use merge instead \o/

**Comment by evs-chris** [comment]
Up until 0.8, it was not possible to merge an array with itself, so it probably would have thrown an error. I'm going to transfer this to the backbone adaptor repo.
