### ISSUE TITLE
Value not rendered in expected position after set()

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2204]
See the attached fiddle. After two seconds setTimeout will `set()` different data and you can see the position of the key/value which should be first change from the first div to second.

http://jsfiddle.net/osobb0mv/

(Sorry... the example template is a little more convoluted than I'd prefer.. I believe it could be pared down but i was hitting some other *possible* bug when attempting to do just that.)

**Comment by Rich-Harris** [comment]
These bugs are always fun to solve... have [whittled it down a bit further](http://jsfiddle.net/rich_harris/7pce7jyd/). Taking a look now

**Comment by Rich-Harris** [comment]
Am admitting defeat for the moment – have put up a failing test in #2205

**Comment by evs-chris** [comment]
@woodlandhunter looks like your fiddle is now working as expected. Did you corner that other potential bug?

**Comment by woodlandhunter** [comment]
@evs-chris Thanks for your efforts and the quick fix. I opened #2214 for the other problem.
