### ISSUE TITLE
Method call events in partial passed through a component via {{> content}} do not work

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2206]
http://plnkr.co/edit/3k04BCLDUSnkihFs8uDs?p=preview

main template:
```
        <Foo>
            <button on-click="doStuff()">doStuff()</button>
        </Foo>
```
inside Foo's template
```
      <div class='Foo' things='{{things}}'>
         {{> content}}
      </div>
```
js:
```
        Foo = Ractive.extend({
          template: '#comp'
        })

        app = new Ractive({
            el: '#container',
            template: '#template',
            
            components: {
              Foo: Foo
            },
            
            doStuff: function() {
              
              // where's ma alert, ma?
              alert('doStuff()');
                
            }
        });
```

Results in `Uncaught Error: Attempted to call a non-existent method ("doStuff")` when clicking the button.
Looks like the method call is looking on the component instead of the parent?

**Comment by evs-chris** [comment]
Yes, the `content` partial lives in the context of the component. You should be able to use `{{yield}}` to get what you're looking for.

**Comment by JonDum** [comment]
`{{yield}}` isn't what I want though :(

I made a pagination component that I'm going to open source. It works like this:

```
<paginator items='{{things}}'>
    <div class='thing'>
        {{.}}
    </div>
</paginator>
```

Where whatever is inside the `<paginator>` tag is what gets looped over inside the component. So I want the user to be able to do whatever they would normally in an `{{#each}}` but instantly get pagination. If I do `{{yield}}` instead, it doesn't even work. It creates an infinite loop and throws a maximum call stack exceeded error.

**Comment by evs-chris** [comment]
Ah, that's an unfortunate situation. I've had the same problem in the past, but I side-stepped the issue by mangling the content partial that was passed in to do what I wanted. _I_ don't know of any way to work around it without getting hacky, but someone else may. I think there's an outstanding issue on something like this, but it didn't jump out at me when I looked.

**Comment by fskreuz** [comment]
If you go with `{{yield}}`, you could [pull out the looping outside](http://jsfiddle.net/gvhec2se/), reducing your component into a wrapper for styling. This way, the inner HTML's context is the parent and you have direct access to `doStuff`.

```
<paginator>
  {{# things }}
    <button on-click="doStuff()">{{.}}</button>
  {{/}}
</paginator>
```

If you go with the `{{> content}}` route, you can [pass in the handler as part of the child data](http://jsfiddle.net/ea4k3797/). Then manually wire it up inside your paginator. The only drawback is that you manually wire up the events, names should be known beforehand, and (gasp) putting functions in data.

```
<paginator doStuffInside="{{ doStuff }}" thingsInside="{{ things }}">
  <button on-click="doStuffInside()">{{.}}</button>
</paginator>
```

**Comment by JonDum** [comment]
I totally forgot to add a fiddle in my main post before. http://plnkr.co/edit/3k04BCLDUSnkihFs8uDs?p=preview

@fskreuz Ahhh so I knew about the distinction between `{{yield}}` and `{{> content}}` but I got it backwards in my head.

I think your solution will work, but it's definitely not as clean as the syntax I currently for the [paginator](https://github.com/JonDum/ractive-paginator):

What I have now (and doesn't work)
```
<paginator items='{{things}}'>
    <div class='thing' on-click='doSomething()'>
        {{.}}
    </div>
</paginator>
```

What you'd have to do every time to make events work.

```
<paginator items='{{things}}'>
    {{# _items}}  //gross underscore to separate the entire array from the current page array
    <div class='thing' on-click='doSomething()'>
        {{.}}
    </div>
   {{/}}
</paginator>
```

---


Also, I'm a little surprised that ractive won't walk up the ancestor chain like it does for data to find that method if it doesn't exist on the child component.

**Comment by fskreuz** [comment]
> Also, I'm a little surprised that ractive won't walk up the ancestor chain like it does for data to find that method if it doesn't exist on the child component.

@JonDum Oh wait, I forgot about bubbling! You *can* listen to events from the inside.

http://jsfiddle.net/80oatqas/

```
<div id="container"></div>

<script type="text/template" id="paginator">
  <div class='foo'>
    {{# thingsInside }}
      {{> content}}
    {{/}}
  </div>
</script>

<script type="text/template" id="app">
  <paginator thingsInside="{{ things }}">
    <button on-click="doStuffInside">{{.}}</button>
  </paginator>
</script>
```

```
var Paginator = Ractive.extend({
  template: '#paginator',
});

var app = new Ractive({
  el: '#container',
  template: '#app',
  components: {
    paginator: Paginator
  },
  data: {
    things: [3,4,5]
  },
  oninit: function(){
    this.on('paginator.doStuffInside', function(){
      alert('from the inside'); 
    });
  }
});
```

**Comment by heavyk** [comment]
@fskreuz that's a really clever way of using `{{yield}}` !!! great stuff

**Comment by martypdx** [comment]
Would it help to have separate `paginator` and `page` components?

```html
<paginator>
    {{#each items}}
    <page>
        <div class='thing' on-click='doSomething()'>
            {{.}}
        </div>
    </page>
    {{/each}}
</paginator>
```

**Comment by Rich-Harris** [comment]
Would loosening the restriction on `{{yield}}` help? I seem to recall feeling quite strongly at one point that it *shouldn't* be possible to have more than one `{{yield}}` or `{{yield foo}}` in a template (but that rendering the equivalent partial repeatedly was totes legit), but for the life of me I can't remember why.

I got myself all turned around the other day over a very similar issue – I was trying to build an infinite scroll thingy (forget cache invalidation and naming things – this is the real hard problem in computer science). `{{#each visibleItems}}{{yield item}}{{/each}}` would have made my life a lot easier.

**Comment by fskreuz** [comment]
I think it was because `{{ yield }}` was supposed to be already constructed before it was handed down to the component, while `{{> content }}` is merely a special partial (hence the `>`) that was handed down to the component before constructing. So looping yield would mean looping the preconstructed DOM rather than whatever we wanted it to loop through inside the component.

Just throwing in what I know. [It was one of my questions before](https://github.com/ractivejs/ractive/issues/1748) that pretty much made me understand how they work.

**Comment by martypdx** [comment]
I think the challenge is coming up with an api that makes sense and dealing with the inverted nature of the an iterative context yielding back up to a parent context. Ideally the component wouldn't have to directly "know" about the data being iterated and the api could merely indicate within the component that a yielding iteration was happening and the calling instance could provide the actual iterative mechanism.

**Comment by JonDum** [comment]
> You can listen to events from the inside.

@fskreuz Nice! That works. Except the keypath will be wrong :(. In the case of my paginator, it will always be `_items . <index of item on current page> ` instead of the real index of the source data array. I'm sure that will trip someone up, but no better solutions right now.

> {{#each visibleItems}}{{yield item}}{{/each}} would have made my life a lot easier.
@Rich-Harris Giving the `{{yield}}` a context would be pretty cool. How would that work? If the `{{yield}}` has its own context, it prefers any events/data on that one, but then tests the parent context for a match before failing?

@martypdx summed it very nicely. Writing components, I need to be able to control that distinction.
