### ISSUE TITLE
Template section not rendered when new key is added to data

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2214]
See fiddle. There's no output when the `baz` key is added with `set()`, but it works as expected if `data` is initialized with the `baz` key.

http://jsfiddle.net/ozghcocL/

I also discovered that it works if you change each `baz` in the `{{#if ...}}` to `~/baz`

**Comment by dagnelies** [comment]
what a big bad bug! definitely a show-stopper :/

I really do hope ractive 0.8 will be more stable

**Comment by martypdx** [comment]
Actually there is a `0.8` BREAKING CHANGE along with bug happening here. 

Default resolution for ambiguous reference is now context, not root of the component. So `baz` resolves to each item of `fields`, which is not the same as `ractive.set( 'baz', [1,2,3])`.

Still an issue with second half of if/else not showing up...

**Comment by Rich-Harris** [comment]
> Default resolution for ambiguous reference is now context

That only applies if there's a forced resolution though (i.e. two-way binding), right? Shouldn't be a breaking change in this scenario

**Comment by martypdx** [comment]
> That only applies if there's a forced resolution though (i.e. two-way binding), right? Shouldn't be a breaking change in this scenario

Ah, true. My mistake.
