### ISSUE TITLE
Decorators raise element events? (post 0.8)

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#2217]
Something that always seemed dirty to me in decorators was mucking about with the ractive instance directly from within the decorator. 

You end up doing things like passing keypaths into the decorator or creating coupling by hardcoding them or names to methods or events to be handled on the ractive instance. (see [this group question](https://groups.google.com/forum/#!topic/ractive-js/yKi5YXKDubo), or [this SO](http://stackoverflow.com/questions/33041695/create-jquery-dialog-ractivejs-decorator) for recent examples).

It occurred to me what would make more sense is to allow the decorator to fire element events that could then be mapped back to the ractive instance in the template:

``` html
<div as-dialog='{ show: showDialog }' on-close='set( "showDialog", false )'>...</div>

<div as-someDecorator on-update='doSometihng( event.value )'>...</div>

<div as-sortable='{ allowDrop: true }' 
     on-drag='set( "position", { x: event.x, y: event.y } )' 
     on-drop='move( ...arguments )'>...</div>
```

(Quick note: I'm using the proposed new decorator syntax in these examples that moves the decorator name out into the attribute name with the prefix `as-` and uses implied bindings in the attribute value, so `decorator='tooltip:{{content}}'` becomes `as-tooltip='content'` or more property `as-tooltip='{ content }'` as would be the "recommended", but not required, object literal options syntax. Parameterless decorators can use the value-less attribute syntax like `as-sortable`).

It would require a change to the decorator interface in order to have access to a `fire` method, or perhaps it could be a ractive method accessible on the existing `node` parameter. And I think access to `ractive` would still be supported for those that prefer direct communication between the decorator and the ractive instance.

Details aside, I just wanted to float this out there to see if others were looking for a better bridge between decorators and the template.

**Comment by JonDum** [comment]
If I'm not mistaken, aren't you already passed the instance in the decorator constructor, so you can call `instance.fire()`?

Secondly, I also like the attribute name for decorators. How would it work with multiple decorators? The order they appear on the tag is the order they're called? Also, what's the `as` prefix in `as-someDecorator`. Is that a personal namespace you use, or a suggestion to have all decorators start with that? 

Personally, I would go with no prefix at all:

`<div tooltip='{{someTooltip}}'></div>`

There's still have to be an entry in the `decorators` object that matches the attribute name for the decorator to be added.

**Comment by martypdx** [comment]
> If I'm not mistaken, aren't you already passed the instance in the decorator constructor, so you can call instance.fire()?

`this` in the decorator refers to the ractive instance, so you can raise ractive events (which is what I currently do as it gives the best decoupling). I was just looking to keep the decorator scoped to the element and raise what would be the equivalent of a custom event plugin event.

I suppose I could try this out via [`dispatchEvent`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) and see how this goes as a general pattern. 

It could be that overly-ambitious decorators are really wannabe components. So for now, I'll try that out. :)


> Secondly, I also like the attribute name for decorators. How would it work with multiple decorators? 

It solves the multiple decorator problem as the attributes would be unique: `as-tooltop as-sortable`

> The order they appear on the tag is the order they're called? 

Probably, makes sense.

> Also, what's the as prefix in as-someDecorator. Is that a personal namespace you use, or a suggestion to have all decorators start with that? Personally, I would go with no prefix at all:

It would be __the__ prefix for decorators. Two reasons: 1) avoid conflicts with other html attributes, 2) consistency in matching the syntax pattern for event plugins: `on-[event]`, `as-[decorator]`

**Comment by JonDum** [comment]
> It would be the prefix for decorators. Two reasons: 1) avoid conflicts with other html attributes, 2) consistency in matching the syntax pattern for event plugins: on-[event], as-[decorator]

Is it an acronym for something or is it to be read like [as](http://www.merriam-webster.com/dictionary/as)? Not quite grokking it yet. Read as the word "as" it reminds me of ye olde type casting a la `foo = bar as String` hehe

**Comment by martypdx** [comment]
> Is it an acronym for something or is it to be read like as?

:+1: 

as: 
> preposition
> 1. used to refer to the function or character that someone or something has.

like a costume, "I'm going _as_ Captain Jack Sparrow to the halloween party"

decorator pattern:
> a design pattern that allows behavior to be added to an individual object, either statically or dynamically, without affecting the behavior of other objects from the same class.

**Comment by evs-chris** [comment]
Context objects (event and getNodeInfo) can now `raise` events on edge.
