### ISSUE TITLE
Any way to observe node change

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2220]
I have an issue similar to this stackoverflow question http://stackoverflow.com/questions/28559626/how-do-i-know-when-components-dom-is-updated-and-finished-transitions-in-ractiv

I need to destroy and reinit a jquery plugin (namely jquery datatatables) based on some data changes.

Is there a way to accomplish this, I can set up a data observer but this fires before the DOM gets rendered.

**Comment by Madgvox** [comment]
You can defer an observer to fire after the DOM is rendered by passing in `defer: true` to the options.

http://docs.ractivejs.org/latest/ractive-observe

**Comment by JonDum** [comment]
@kouts You may also want to take a look at [ractive-datatable](https://github.com/JonDum/ractive-datatable)

**Comment by kouts** [comment]
Thank you @Madgvox !
If you were close I would definitely buy you a :beer:  for that :smile: 
What an understated feature by the way. There should be an example on both "Observers" and "ractive.observe()" docs pages, about this.
