### ISSUE TITLE
reset() method not resets data attributes

### ISSUE THREAD

**Issue by gam6itko** [ractivejs/ractive#2223]
Here an example.
http://jsfiddle.net/z6c6n69d/1/

**Comment by martypdx** [comment]
Ractive is keeping the data attributes up to data, see http://jsfiddle.net/yg4wfp29/ or inspect the elements in the dom.

jQuery is probably loosing track of the hash between element id and its data object.

**Comment by gam6itko** [comment]
it's worth mentioning in documentation

**Comment by Madgvox** [comment]
As ractive does not require jquery as a dependency it has no way of keeping track of what jquery data has been set on an element.
