### ISSUE TITLE
Regression bug: data inside component differs from the view

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2225]
Hi,

here is one more bug (working with latest, but broken in edge):

http://jsfiddle.net/eq75y264/6/

This is another case where the model/data drifts apart from the view. What's inside the component always appear to be wrong/unchanged, even when calling `update()`.

**Comment by fskreuz** [comment]
Looks like `active` is set for the component, but not reflected in template.

**Comment by evs-chris** [comment]
It looks like this is fixed in edge now. @dagnelies can you confirm?

**Comment by evs-chris** [comment]
It looks like this boils down to the same issue as most of the other outstanding observer issues: triggering a runloop from an observer where some fragments are already marked dirty in the outer runloop causes things to get skipped. I'm not really sure what the best solution to this is at this point. I don't think it will be as simple as always adding the fragments to the batch on bubble regardless of their dirty state. I have an idea to try out when I get some more time, but I'm afraid it may be too ugly.

**Comment by evs-chris** [comment]
If #2239 is correct, then the fix was a lot simpler than I thought it would be.

**Comment by dagnelies** [comment]
great, thanks
