### ISSUE TITLE
Support for LiveScript (and other languages) in templates?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2226]
[LiveScript](http://livescript.net) is a functional language that's compiled into Javascript with a compiler that is written in Javascript (like Coffee Script). 

LiveScript has a lot of way to get the code shorter and readable. If we have an option to use LiveScript code in Ractive templates, it would be much easier to get the work done and the codebase would be consistent across templates and other javascript\* codes for LiveScript users. 

I had an attempt to get the code compiled into Javascript before evaluating in Ractive, but I had no success. If it's easy for you, I'm asking for LiveScript support. Else, I'll try again to get it done whenever I could.

**Comment by fskreuz** [comment]
This is a task for a pre-processor or a loader, not Ractive. There is [Ractiveify](https://github.com/norcalli/ractiveify) that allows you to hook in a compiler. It's sort of [do one thing and do it well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well).

**Comment by ceremcem** [comment]
Thanks for the answer. I'm already using brunch.io in [my project](https://github.com/ceremcem/aktos-website). All scripts precompiled to javascript before publishing. This is already done by brunch.io. 

The closest solution seems ractiveify, but it seems that it has another perspective. I meant the following: 

```
{{#each [.. for messages when /monkey/i isnt ..]}}
    <p style="background-color: {{ \cat in .foo ? \red : \green }}">hello .bar</p>
{{/each}}
``` 

Here `[.. for messages when /monkey/i isnt ..]` is a code in LiveScript which compiles to 
```
var i$, x$, ref$, len$;
for (i$ = 0, len$ = (ref$ = messages).length; i$ < len$; ++i$) {
  x$ = ref$[i$];
  if (!/monkey/i.test(x$)) {
    x$;
  }
}
```

If I'm not wrong, this is done in ractive.js in runtime, for the first time. I just searched for `eval(` and `parse` but found nothing. 

If you encourage to precompile them into javascript before serving, then I'll take that option as a start point.

**Comment by fskreuz** [comment]
Yeah, I think that's not possible. However...

You can use a [computed property](http://docs.ractivejs.org/latest/computed-properties) for the `{{# each }}`. For the ternary, you can offload that logic to a data function. Since both are now in the script realm, you can easily write the script portion in another language, and have a tool or loader to compile it.

```
{{#each notMonkey }}
    <p style="background-color: {{ isIn(foo, 'cat') }}">hello .bar</p>
{{/each}}

// You can write this in another language
component.exports = {
  ...
  data: {
    isIn: function(array, string){ ... }
  },
  computed: {
    notMonkey: function(){
      return this.get('animals').filter(function(animal){
        return isNot('monkey', animal);
      });
    }
  }
  ...
}
```

**Comment by JonDum** [comment]
This is actually super easy with webpack since it allows you to chain loaders together.

it would just be `require('livescript!ractive!myTemplate.html')` which would take your livescript, convert it into normal javascript, then load up the ractive-loader to precompile that into a ractive template. 

You'd then make an alias in your loader webpack.config.js to reduce that down to just `require('templates/myTemplate')` so you don't have to type `livescript!ractive!...html` every time.

**Comment by Rich-Harris** [comment]
In theory this could be done if we had a hook that allowed custom expression pre-processors to convert LiveScript et al into JavaScript at parse time. The tricky part is that you don't really have a way of knowing where the expression *ends* – the JavaScript parser keeps going until it creates a fully formed expression, then expects to find `}}` (or whatever custom delimiter you're using). But most compilers want the input to be complete – you can't just throw whatever's left or your template at the LiveScript compiler and expect to get back the compiled JS plus whatever came after it. So you have to figure out a way to isolate the expression without using the parser, which is basically impossible (you could get 95% of the way there with regular expressions, but the last 5% makes life rather difficult).

The alternative would be to allow the expression parsing logic to be replaced completely, but I think that's fairly impractical. So I'm afraid this is probably a wontfix.

In the absence of a robust 'official' mechanism for doing this, your best bet, if you're intent on using LiveScript inside templates, is probably to hack together a template preprocessor of your own:

```js
template = template.replace( regexThatIsBrittleButBasicallyWorks, ( match, code ) => {
  if ( !isLiveScriptExpression( match ) ) return;
  return match.replace( code, transpileLiveScript( code ) );
});
```

Incidentally,

> If I'm not wrong, this is done in ractive.js in runtime, for the first time. I just searched for `eval(` and `parse` but found nothing. 

Almost. `Ractive.parse` contains a full JavaScript expression parser, which extracts references and flattens them back to strings, [like so](http://jsfiddle.net/21d01zut/). When the expression is rendered, a function is created with `new Function()`, and we just keep calling that function with the value of those references each time they change. `new Function()` is basically the same as `eval`, except much, *much* faster if you call the code repeatedly. The expression parsing code [lives here](https://github.com/ractivejs/ractive/blob/dev/src/parse/converters/readExpression.js) and [here](https://github.com/ractivejs/ractive/blob/dev/src/parse/utils/flattenExpression.js), and the functions are created [here](https://github.com/ractivejs/ractive/blob/dev/src/shared/createFunction.js).

**Comment by evs-chris** [comment]
I think a separate parser that outputs ractive-compatible template would be the only workable solution, so I'm going to close this, as that seems better suited to a separate project.
