### ISSUE TITLE
cant use {{elseif}}

### ISSUE THREAD

**Issue by yuu2lee4** [ractivejs/ractive#2227]
big bug!

**Comment by JonDum** [comment]
@yuu2lee4 Can you please provide a jsfiddle or alternative that reproduces this bug?

**Comment by fskreuz** [comment]
Please include the version of Ractive as well as plugins/loaders used.

**Comment by yuu2lee4** [comment]
@jondum @fskreuz  i have replaced the lastest version  and  this bug maybe solved
