### ISSUE TITLE
Strange server-side rendering.

### ISSUE THREAD

**Issue by dangreen** [ractivejs/ractive#2230]
Rendering on server-side doesn't fill value to `name` attribute of input element.

```html
<input placeholder="{{data.text.value}}" data-name="{{data.text.value}}" name="{{data.text.value}}">
```
result:
```html
<input placeholder="Name" data-name="Name" name="{{data.text.value}}">
```

**Comment by MartinKolarik** [comment]
We should probably add ` && this.element.getAttribute('type') === 'radio'` [here](https://github.com/ractivejs/ractive/blob/d775f3b51fe6b8c05ac27783012b61d2f0226ed1/src/view/items/element/Attribute.js#L112).
