### ISSUE TITLE
question about the fate of the 'change' event in Ractive 0.8-edge

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2231]
Hi.  We're using an [experimental Ractive to Ractive adaptor](https://github.com/rstacruz/ractive-ractive) which apparently conforms to [documentation on adaptors.](http://docs.ractivejs.org/latest/writing-adaptor-plugins)

Ractive 0.8-edge seems to be en route to deprecating the ractive.on('change') event, which the Ractive to Ractive adaptor uses to learn about changes in the referred-to Ractive object.

Hints about deprecation of the 'change' event in [Ractive 0.8-edge:](http://cdn.ractivejs.org/edge/ractive.js)

```javascript
// TODO deprecate this
this.changes = {};
```

and

```javascript
  		// TODO deprecate this. It's annoying and serves no useful function
  		var ractive = fragment.ractive;
  		changeHook.fire(ractive, ractive.viewmodel.changes);
  		ractive.viewmodel.changes = {};
```

Is the 'change' event going away?  If so, is there a recommended replacement for it? 

And a related question: will adaptors be supported in Ractive 0.8-edge?  Using the documented interface, or a new interface?

**Comment by Madgvox** [comment]
Ractive 0.8 is slated to have _minimal_ breaking changes, so included in that is the change event and adaptor support. Anyone else is feel free to chime in if I'm wrong. :)
