### ISSUE TITLE
Isolated stops {{> content}} / {{yield}} from updating, but still renders initially.

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2235]
http://plnkr.co/edit/BgRbvFwwiG4KTPpt3Wqg?p=preview

Is this intended? Ran into this scenario today where I need `isolated` set to true to avoid an infinite loop, but it stops it's `{{> content}}` from updating. I was under the impression that `isolated` stops the component from accessing its parent's properties, not including its own `{{> content}}` it gets from its parent. 

I thought that maybe `{{> content}}` was dependent on `foo` from its parent in this scenario, but the same thing happens with `{{yield}}` and, annoyingly, I can't use `{{yield}}` more than once. Any thoughts?

**Comment by Madgvox** [comment]
Wow, this is an old one.

**Comment by evs-chris** [comment]
I believe that this is indeed intentional. The only way to get data into an isolated component is using API methods (`set` and friends) or passing bindings. If you pass a `foo` binding into the component, it works as intended. A `{{>content}}` partial is effectively the same as setting the partial manually on the component. It has no inherent tie to the component's context.

**Comment by martypdx** [comment]
What @evs-chris said. You can add `<comp foo='{{foo}}'>` and it works.

> but the same thing happens with {{yield}} 

That looks like a bug for sure: http://plnkr.co/edit/ANGXdw1ZuyZo0TXOnuf6?p=preview

> and, annoyingly, I can't use {{yield}} more than once. Any thoughts?

See above link on getting multiple yields (though not iterative yields)

**Comment by JonDum** [comment]
@evs-chris ok that makes sense to me. In this case then, I need to use `{{yield}}`, but it still doesn't work: http://plnkr.co/edit/NPOV3IoF2qHnFg9O189F?p=preview :(

**Comment by JonDum** [comment]
Does edge from the cdn have dd9eaf8f14a7ea8b in it? Not seeing any of the plnkr's working.

**Comment by evs-chris** [comment]
It is, and a simplified case works. I'll look into the plunkrs some more...

**Comment by evs-chris** [comment]
@JonDum the other side of this issue is fixed now :grinning:

The plunkrs were sort of working, the 'Foo is true' was just being added to the wrong element.

**Comment by JonDum** [comment]
Hell yea! Now that's sexy!! Where is your gittip chris??
