### ISSUE TITLE
Bug (?) in two-way binding across partials

### ISSUE THREAD

**Issue by TehShrike** [ractivejs/ractive#2238]
fiddle: http://jsfiddle.net/ddzg0uvw/6/

Steps: 
1. open the console
2. type something into the first edit
3. type something into the second edit

Expected behavior: after typing in either edit, changes should be reflected in the other one, and the change should log to the console

Observed behavior: when you type into the second edit, the change shows up immediately in the console and in the first edit.  But when you type into the first edit, the one where the input is contained in a partial, the changes don't show up in the console or in the second edit.

**Comment by evs-chris** [comment]
I believe this is the same as #1353. Basically, you're creating an out-of-model object in the context passed to the partial. Ractive doesn't know how to connect that `.value` is actually an alias to `object.value1`. For one potential solution, see #2209.

**Comment by Madgvox** [comment]
Closing this and pointing discussion towards https://github.com/ractivejs/ractive/issues/1834 and https://github.com/ractivejs/ractive/pull/2209.
