### ISSUE TITLE
staticDelimiter option does not work

### ISSUE THREAD

**Issue by ArtskydJ** [ractivejs/ractive#2240]
```js
new Ractive({
    // these work:
    delimiters: [ 'a', 'b' ], 
    tripleDelimiters: [ 'c', 'd' ],

    // these do not work:
    staticDelimiters: [ 'e', 'f' ],
    staticTripleDelimiters: [ 'g', 'h' ]
})
```

http://jsfiddle.net/rej2mgwr/4/

**Comment by moo3** [comment]
This is marked closed, was this released? I couldn't get custom values staticDelimiters to work in 0.7.3.

http://codepen.io/anon/pen/XXpQMZ?editors=100

```
var r = Ractive({
	template: '<h1>Hello {{type}} [@name@]</h1>',
	el: 'body',
	staticDelimiters: ["[@", "@]"],
	data: {
		type: 'planet',
		name: 'Earth'
	}
});
//expected result: Hello planet Earth
//current result: Hello planet [@name@]
```

Am I doing it right?!

**Comment by ArtskydJ** [comment]
It is fixed in edge, which is not released on npm yet, but should be in the 0.8.0 release.

**Comment by ArtskydJ** [comment]
You can work around this issue by adding `{{{=[@ @]=}}}` to the beginning of your templates. (See [fiddle](https://jsfiddle.net/v3fdfuxz/1/).)

**Comment by moo3** [comment]
That's interesting. Thanks. Workaround seems to help for now.

**Comment by ArtskydJ** [comment]
I messed up the workaround. It should be `[[=[@ @]=]]`. This replaces `[[` and `]]` with `[@` and `@]`, respectively.

The previous "workaround" actually replaced the triple delimiters, not the static delimiters.
