### ISSUE TITLE
item.getValue is not a function

### ISSUE THREAD

**Issue by jhiver** [ractivejs/ractive#2242]
Hi there, I'm currently trying to upgrade a 50+ screen single page javascript app which was running on ractive 0.6 to the latest ractive library on NPM 0.7.3. On one of the screens of the application (a multi-step wizard), I get *item.getValue is not a function* error on the JS console log.

This seems to happen when changing steps in the wizard, i.e. going from step1 to step2, which is defined in the template like so:

  {{{#step === 1}}}
    ... step1 html ...
  {{{/end}}}
  {{{#step === 2}}}
    ... step2 html ...
  {{{/end}}}

I searched for the following in my local node_modules directory

    value = item.getValue();

And replaced it with:

    if (item.getValue && typeof(item.getValue) === 'function') {
        value = item.getValue();
    }
    else {
        console.log('unexpected error', item);
        value = null;
    }

That kind of seems to make  the problem go away but the thing is, I don't understand why it fixes it, which is kinda bad... FYI here is what the "item" object looks like on the console. Any ideas of what's happening?

<img width="543" alt="item" src="https://cloud.githubusercontent.com/assets/4971072/10697397/9b0fb956-79a3-11e5-94c9-04467bae4db9.png">

**Comment by fskreuz** [comment]
Would you mind posting relevant components? It's hard to tell what's in play here. Additionally, any reason why you're using triple mustache on sections (`{{{#step === 1}}}`)?

**Comment by jhiver** [comment]
Triple mustache is a typo here, I checked and I'm using normal mustaches. I'll try to isolate the bug and let you know.

**Comment by jhiver** [comment]
Looks like it's due to a broken template. Ractive doesn't throw errors when parsing the broken bit below; but behaves funny afterwards (look inside <option>)

    {{#loaded}}
     {{#step === 1}}
      <h3>STEP ONE</h3>
      <div>
       <button id="mbnPortBtn" class="btn btn-primary" on-tap="submitStep1Port"  style="margin-bottom:1em">Go to step 2</button>
      </div>
     {{/end}}
     {{#step === 2}}
      <h3>STEP</h3>
      <div class="panel panel-default" style="border:0px">
       <div class="panel-heading" style="border:1px solid" id="ddd">
        <b>Step 2. Confirm current provider</b>
       </div>
       <div class="panel-body">
        {{^isPortable}}
          <select value="{{numberLCP}}">
           <option>
            <selected>
             <disabled>select LCP
           </option>
          </select>
        {{/isPortable}}
       </div>
     {{/end}}
    {{/loaded}}

**Comment by Rich-Harris** [comment]
It looks like this is 'fixed' in edge: http://jsfiddle.net/219oqq6a/ (0.7 equivalent – http://jsfiddle.net/jnyutujc/), insofar as it renders and more or less behaves. I think we should probably throw an error if an option contains elements though, since if it happens it's almost certainly unintentional. (Though I suppose it should be a render time error rather than a parse error, since someone might call their component `<option>`...)
