### ISSUE TITLE
http://examples.ractivejs.org/illustration text falls outside label 

### ISSUE THREAD

**Issue by kaihendry** [ractivejs/ractive#2244]
Text falls outside label on Google Chrome	48.0.2541.0

<img src=http://s.natalian.org/2015-10-27/1445911611_1918x1058.png>

It's fine in Firefox.

**Comment by heavyk** [comment]
works fine in chrome canary (48.0.2541.0). maybe it was a bug...
<img width="1143" alt="screen shot 2015-10-27 at 04 22 47" src="https://cloud.githubusercontent.com/assets/1226324/10748643/9eb8c248-7c62-11e5-8f8f-f62075a1a9b9.png">

**Comment by kaihendry** [comment]
Odd, feel free to close as invalid. My platform in Archlinux.

**Comment by Rich-Harris** [comment]
Looks like the problem is with the font – perhaps we should use a web font rather than a system font so that we have some control over how much space the label takes up. I've reopened this on the examples repo
