### ISSUE TITLE
Ability to parse (compile) Ractive template at build time with data?

### ISSUE THREAD

**Issue by moo3** [ractivejs/ractive#2245]
I'm looking to create static HTML created out of a Ractive template whose data I can provide at build time. Is this even feasible? I'm aware of the Ractive.parse() method but if only it can also accept a data property which could be used to update the mustache templates. 

Example:
**content.html**
```html
<h1>Hi {{username}}</h1>
<h3>List of {{type}}</h3><br>
{{#each items}}
  {{@key}}: {{this}}
{{/each}}
```
**Build time task**
```javascript
var list = {
 type: 'fruits',
 items: [{apple: 'red'}, {pear: 'green'}];
}

//fetch template from content.html
var template;

//parse template with data
var parsed = Ractive.parse(template, options, list);

//...returns a parsed equivalent of this HTML, applies any provided data
<h1>Hi {{username}}</h1>
<h1>List of type fruits</h1><br>
apple: red
pear: green
```

**Comment by fskreuz** [comment]
You could just create an instance, feed the data to that instance, then use [`ractive.toHTML()`](http://docs.ractivejs.org/latest/ractive-tohtml) to render into HTML the current state of the instance.

```
var instance = new Ractive({
  template: '...',
  // stuff... you can put data here or set it later.
});

instance.set({/* the data you want to appear */});

var html = instance.toHTML();
```

**Comment by moo3** [comment]
Thanks and true this did work for simpler templates. But fails when I have decorators. Any way to exempt from looking for decorators/plugins?

**Comment by fskreuz** [comment]
You can simply just import the decorators too, assuming you have the decorators in a module format that's easily importable. Otherwise, if it's safe to do so, you can simply just stub them with ones that do nothing.

```js
// You can import and add in the decorators
var myFruitsList = new Ractive({
  /* the stuff above */
  decorators: {
    /* declare all decorators */
  }
});

// or you can stub out the decorators with ones that do nothing
Ractive.decorators.NAME_OF_DECORATOR = function(){ return { teardown : function(){} }; }
```

**Comment by martypdx** [comment]
I just noticed a bug in edge that Ractive does not warn or error on missing decorator.

**Comment by Madgvox** [comment]
Created a thread for that bug: #2246

**Comment by Rich-Harris** [comment]
That's odd – decorators should be ignored when you're creating an instance in Node, because they're only created when an element is rendered, and nothing gets rendered in Node. Or have I misunderstood the problem?

**Comment by moo3** [comment]
Thanks @fskreuz. That solves my problem.

**Comment by moo3** [comment]
@fskreuz I am looking for another clarification related to the initial question. Is there a way for the template variables that were not substituted to be left alone? 

For this content.html template
```
<h1>Hi {{username}}</h1>
<h3>List of {{type}}</h3><br>
{{#each items}}
  {{@key}}: {{this}}
{{/each}}
```

and data
```
var list = {
 type: 'fruits',
 items: [{apple: 'red'}, {pear: 'green'}];
}
````

is there a way to get the return as shown below (notice the **{{username}}** is not substituted)
```
//...returns a parsed equivalent of this HTML, applies any provided data
<h1>Hi {{username}}</h1>
<h1>List of type fruits</h1><br>
apple: red
pear: green
```

I have a business case that deals with unsubstituted keys. Please let me know if Ractive provides a way to leave the keys for those data is not available.

**Comment by martypdx** [comment]
@moo3 How about something [like this](http://jsfiddle.net/hz4jb1o5/):

```js
const insertReference = {
  filter: function (object, keypath, ractive) {
    return object === undefined;
  },
  wrap: function (ractive, object, keypath, prefixer) {
    const key = keypath.split('.')[0];
    return {
      teardown() {},
        get() {
          return `{{${key}}}`;
        },
        set() {},
        reset() {}
    }
  }
};

var r = new Ractive({
  el: document.body,
  template: `
      <h1>Hi {{username}}</h1>
      <h3>List of {{type}}</h3>
      <br> 
      {{#each items:fruit}}
          	<li>{{#each this as color:fruit}}{{fruit}}:{{color}}{{/each}} 
      {{/each}}
  `,
  data: {
    type: 'fruits',
    items: [{
      apple: 'red'
    }, {
      pear: 'green'
    }]
  },
  adapt: [insertReference]
});
```

**Comment by moo3** [comment]
@martypdx thanks but it solves just a few of the actual use-cases, partially. I need the key remain untouched means if the original key was unescaped `{{{key}}}` then the code suggested above is going to return `{{key}}`, I see no way to figure out escaped vs unescaped keys. 

Also, the suggested code does not seem to handle the following data for the same template.
```
var list = {
 type: 'fruits'
}
```

Since `items` is not found in data I'd expect Ractive to return that part of the template untouched but I get empty instead of this.
```
<h1>Hi {{username}}</h1>
<h1>List of type fruits</h1><br>
{{#each items}}
  {{@key}}: {{this}}
{{/each}}
```

**Comment by martypdx** [comment]
Yeah, you're pretty far outside the lines of Ractive at this point.

Given the need for block support, you're probably looking at some post-processing of the rendered output based on the template.

Maybe put in a sentinel value like `%MISSING%` using the adaptor above, the run through the [template](https://github.com/ractivejs/template-spec) and the output looking for those values and using the template to write out the unrendered content.
