### ISSUE TITLE
Object.keys not available in template

### ISSUE THREAD

**Issue by heavyk** [ractivejs/ractive#2247]
I had something like this in my template:

```
{{#if Object.keys(panels).indexOf(active) !== -1 }} ... {{/if}}
```

and it didn't work. turns out I can't use `Object.keys` in the template. no big deal cause I made it a computed value, but was that intentional?

http://jsfiddle.net/fs6fxwt9/

**Comment by fskreuz** [comment]
The mustaches only evaluate a subset of JS expressions, not sure what comprises that subset though. It doesn't seem to work in older versions (0.4, 0.6), so it may never have been possible.

**Comment by heavyk** [comment]
yeah, I don't think it ever has either. I assumed all primitives were available, cause I've used `Array.isArray` before. just, today I ran into this one. like I said, not a big deal :)

if you're gonna add it, perhaps `String` may be valid as well. potentially, `String.fromCharCode` or `String.fromCodePoint` (I dunno for translators or something, lol)... who knows

**Comment by Rich-Harris** [comment]
Yeah, I can't see a good reason not to include all the types (Object, String, Number, Boolean etc) since Array is already there (I think it was included because `{{#each Array(10) :i}}...{{/each}}` is a good way to repeat a section ten times)
