### ISSUE TITLE
jquery .click() does not work in {{#if}} block

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2251]
`click me 2` works but `click me` does not work: http://jsfiddle.net/nqk2nb03/20/

**Comment by heavyk** [comment]
that's because the dom component for #my-link-1 doesn't exist yet. if you move your jquery to be inside of the complete block it works fine:

http://jsfiddle.net/1kok0wrd/

**Comment by fskreuz** [comment]
The DOM for the component has not rendered yet. In fact, you should not rely on the idea that the DOM is created during instantiation of a component. The operations are potentially asynchronous.

@heavyk mentioned that you can attach them using the `complete` event. 

However, you can dump jQuery and [use Ractive's own DOM event handler mechanism instead](http://jsfiddle.net/nqk2nb03/23/). There's 2 ways to do it: [event directives](http://docs.ractivejs.org/latest/event-directives) and [method calls](http://docs.ractivejs.org/latest/method-calls) (looks like inline scripts).

```mustache
<div id="container"></div>
<script type="text/ractive" id="app">
    <a href="#" on-click="action2()">click me 2</a>
   {{#if myTest}}
    <p>myTest data is: {{ myTest }} <a href="#" on-click="action1()">click me</a></p>
   {{else}}
    <p>myTest is empty</p>
   {{/if}}
</script>
```

```js
app = new Ractive({
    template: '#app',
    el: 'container',
    action1: function () {
        alert('link 1 clicked');
    },
    action2: function () {
        alert('link 2 clicked');
    }
});

app.on('complete', function () {
    app.set('myTest', 'aaa');

    setTimeout(function () {
        app.set('myTest', null);
    }, 10000);
});
```

**Comment by heavyk** [comment]
in addition to what @fskreuz said, I forgot to mention that if you do add your listeners on oncomplete you will need to remember to remove those event handlers on onteardown as well or you will create leaks.

however a bonus to using ractive event directives is, you will not need to worry about cleaning up your handlers. they get cleaned up for you when ractive removes the dom

**Comment by ceremcem** [comment]
Ok, sorry for the fiddle. I built a mechanizm to get every action done in `complete` function, but I forgot to write it in the fiddle. 

So, these jquery functions should be called after DOM is completed, which is inside `complete` block; right? Am I missing something again: http://jsfiddle.net/nqk2nb03/25/

**Comment by heavyk** [comment]
you shouldn't be using jquery. use event directives like @fskreuz demonstrates

**Comment by heavyk** [comment]
and the reason why your fiddle doesn't work is because my-link-1 doesn't exist yet (cause of the if-statement). you would need to set myTest before trying to bind to the events.

http://jsfiddle.net/t100qcko/

**Comment by ceremcem** [comment]
Setting the data is out of my hands, because it's actually for `{{#if loggedIn}} click to logout {{else}} click to login {{/if}}` usage, so data is set whenever user wants to login.

Here is my workaround to use jQuery: http://jsfiddle.net/nqk2nb03/27/  Isn't it possible to implement in an efficient way?

I think I'll end up using proxy events anyway, but this is a limitation.
