### ISSUE TITLE
Transitions: expected behavior or bug?

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive#2252]
I haven't used transitions much, and I'm just starting to integrate them. My expectation with transitions is that they are designed to transition / animating between two states. So, if, without transitions, I have an element that adds to DOM, removes from DOM, then my assumption is that adding an intro/outro transition would
1. Intro: Add element to DOM at animation start position. Animate to final position of intro.
2. Outro: Animate element to final position of outro, then remove from DOM.

However, the final critical piece, removing from DOM, never happens. That is, without a transition, the element disappears. With a transition, it animates, but leaves the element in the DOM, which, in my case, just leaves an empty hole.

Is this as designed? It's unexpected behavior for me, and seems like a bug, but I'm wondering if I missed something.

**Comment by Madgvox** [comment]
When an outro completes, the relevent node is removed from the DOM. My best guess is that the transition is never calling the `complete` function on the object that gets passed into the transition function. If it doesn't call complete, then Ractive doesn't know if the transition is over yet, so it will keep the element in the DOM for as long as necessary.

Here's an example of a _working_ transition: http://jsfiddle.net/ag7r6yro/

As you can see, the node is removed from the DOM upon completion of the outro.

**Comment by matthew-dean** [comment]
The transition I'm using in this case is ractive-transitions-fly.js, so I'm not sure why that would be.

**Comment by Madgvox** [comment]
The most likely explanation is that something is causing the promise to never fire inside [ractive-transitions-fly.js](https://github.com/ractivejs/ractive-transitions-fly/blob/master/src/ractive-transitions-fly.js) for you. I would try intercepting the promise inside your local copy and confirming that `t.complete` is actually firing properly.

```js
// this
t.animateStyle( target, params ).then( t.complete );
// becomes this
t.animateStyle( target, params ).then( function() {
  console.log( "Transition complete" );
  t.complete();
});
```

**Comment by evs-chris** [comment]
There's now a safety net on transitions that forces them to complete.
