### ISSUE TITLE
Fired events lose arguments at parent handler

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2253]
When firing from child component, handler on parent fires but doesn't receive the arguments. Same applies to `fire` when done via method call.

Further testing shows that it only loses arguments outside the component. Listening inside the same component works fine. Narrowed it down to reproxying arguments logic for component method calls. Not sure how to proceed from here.

Works on 0.7 (parent handler receives arguments), breaks on 0.8 (parent handler receives blank arguments): http://jsfiddle.net/r9zmsz89/2/

```js
var ChildComponent = Ractive.extend({
    template: '<button type="button" on-click="foo()">Click me!!!</button>',
    oninit: function () {
        this.on('far', function () {
            console.log('on child', arguments); // ['foo', 'bar']
        });
    },
    foo: function () {
        this.fire('far', 'foo', 'bar');
    }
});

var ParentComponent = Ractive.extend({
    template: '<child-component on-far="boo" />',
    components: {
    	'child-component': ChildComponent
    },
    oninit: function () {
        this.on('boo', function () {
            console.log('on parent', arguments); // []
        });
    }
});

new ParentComponent({
    el: 'body',
    append: true
});
```

**Comment by martypdx** [comment]
This was (some-what) intentional, see #2095, for two reasons:

1. Using arguments at component boundary requires explicit inclusion.
2. I didn't put the work in to handle argument passing for event handler syntax.

However, given the lack of 2, and the pre-existing behavior, maybe the thing to do is include all the arguments on a proxy event re-fire.

**Comment by martypdx** [comment]
BTW - You can get your example to work by doing: `<child-component on-far="fire('boo', $1, $2)" />`

**Comment by fskreuz** [comment]
Yeah, tried to "fix" that last night when it broke the tests related to that issue, and then remembered. Was waiting for your input whether this is really a bug (since I've been using it this way for quite some time) or is this a breaking change, and should be a docs update thing instead.

**Comment by martypdx** [comment]
@fskreuz I've got it fixed just implicitly tacking on existing args for event re-fire. 

Looking into one other case I thought of which is including `...arguments` but not as sole argument, `on-foo='someMethod("bar", ...arguments)'`

**Comment by fskreuz** [comment]
Now that I've used the `$1, $2, ...` and `...arguments` syntax, it makes more sense. The `$1, $2, ...` allows for repositioning of args, while `...arguments` just allows everything in. However, tacking in everything at the end feels confusing. Was thinking more like the following:

```
// Event style. bar gets everything from foo, like the old behavior. Captured by `on`.
on-foo="bar"

// Explicit, method call. Define what gets passed in. Reposition, additions, rest possible.
on-foo="bar('baz', $2, $1', ...arguments)"
on-foo="bar: 'baz', $2, $1, ...arguments" // Quite confusing. Looks like an event.

// Explicitly saying we don't want to pass anything to method.
on-foo="bar()"

// Explicitly saying we just want to pass everything.
on-foo="bar(...arguments)"
```

**Comment by martypdx** [comment]
per #2257:

* using `...arguments` as a spread operator _must_ be last argument (just like normal es6) of method call or will throw parse error
* use of `...arguments`, `$N`, and `arguments[n]` is _NOT_ supported in proxy events per intent to deprecate the expanded parameter syntax that uses `:`.

**Comment by heavyk** [comment]
> using ...arguments as a spread operator must be last argument (just like normal es6) of method call or will throw parse error

you sure about that? I dunno about arguments, but I've been playing with the spread operator in the new node-5.0.0 and they can be mixed...

```
> var a = [1,2]
undefined
> var b = [7,8]
undefined
> b.push(...a, 3, 4)
6
> b
[ 7, 8, 1, 2, 3, 4 ]
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator#A_better_apply

**Comment by martypdx** [comment]
@heavyk Fair enough :D

**Comment by Rich-Harris** [comment]
> using ...arguments as a spread operator must be last argument (just like normal es6)

I thought that too until @heavyk's example – I think we were both thinking of rest parameters, which *do* have to go at the end
