### ISSUE TITLE
Events whose names contain spaces are not catchable

### ISSUE THREAD

**Issue by TehShrike** [ractivejs/ractive#2258]
I tried emitting an event with spaces in its name, like you do, and found that it was impossible to catch that event: http://jsfiddle.net/ddzg0uvw/9/

If I remove the spaces from the event name (replacing `custom event` with `customevent`) then the events are catchable as expected.

**Comment by Madgvox** [comment]
I'm marking this as `wontfix` because spaces are not allowed in event names so as to let you subscribe to multiple events with one handler: http://docs.ractivejs.org/latest/publish-subscribe#multiple-events-to-one-handler

**Comment by TehShrike** [comment]
aah, I'd been looking for some explanation on the [publish-subscribe](http://docs.ractivejs.org/latest/publish-subscribe) doc page.  Maybe there could be a mention there?

**Comment by Madgvox** [comment]
It probably could be a bit more obvious in the docs.
