### ISSUE TITLE
`if` based on data from attribute is not working as expected

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#2261]
**Starting point:**
http://jsfiddle.net/gigasoft/1aq35u6p/1/

**Step to reproduce**
Upon page load, click "Help"

**Expected result**
"Help" section is displayed.
"Content" section gets hidden.

**Actual result**
"Help" section is not displayed, even though `tab` selection is modified.
It looks like the property `active` changes, but the shorthand if `{{active ? 'active' : ''}}` is not re-computed.

--
Example is broken on Edge, works fine on 0.7.

**Comment by fskreuz** [comment]
Yup, appears to be that expression. [A workaround is to use sections (and be mustache-y)](http://jsfiddle.net/1aq35u6p/2/)

```
{{# active }} active {{/}}
```

**Comment by Rich-Harris** [comment]
Thanks for the test case – have whittled it down and created a branch for it (#2262). Will take a look this pm if no-one beats me to it

**Comment by Rich-Harris** [comment]
Turned out to be a pleasingly simple fix

**Comment by martypdx** [comment]
:grin:
