### ISSUE TITLE
Binding/unbinding at runtime

### ISSUE THREAD

**Issue by arxpoetica** [ractivejs/ractive#2266]
Sorry if this has been asked elsewhere, but I couldn't find an answer.

I am interested in learning if Ractive allows (dynamic) bindings at runtime. Consider the following:

```html
<!-- {{sharedVariable}} -->
<componentOne componentOneVariable="{{sharedVariable}}"></componentOne>
<componentTwo componentTwoVariable="{{sharedVariable}}"></componentTwo>
```

^ This binding is explicit, and doesn't change during the duration of the application. However, what if one wants to selectively bind or unbind values based on some criteria? Is such a thing possible via Javascript?

```html
<!-- {{sharedVariable}} (note the absence of binding) -->
<componentOne></componentOne>
<componentTwo></componentTwo>
```

```js
var ComponentOne = Ractive.extend({
	template: '#ComponentOne',
	oninit: function() {
		// do some binding here?
	}
});
```

**Comment by fskreuz** [comment]
Not aware if this is possible with Ractive at the moment. But first thing that comes into mind is computed properties with added logic to check whether or not they should change the value they're computing from.

```
var Component = Ractive.extend({
  computed: {
    someVariableValue: {
      get: function(){
        return shouldChange ? someChangedValue : notChanged;
      },
      set: function(someChangedValue){
        this.set('someData', shouldChange ? someChangedValue : notChanged;
      }
    }
  }
});
```

**Comment by arxpoetica** [comment]
Thanks for the info. Still not hitting what I hope for; your idea still has an explicit binding set in the DOM. This is a good idea if you know that you'll have a single variable that might change at will. Interesting idea. But leaving this open if anyone else knows otherwise. Possible to have a runtime binding? @martypdx? @Rich-Harris? @anyone? :)

**Comment by martypdx** [comment]
@arxpoetica TBH not really understanding what you're trying to accomplish. What is the trigger that would cause "rebinding"? Where are the multiple values to which you would bind coming from? Inside or outside the component?

However, I think the new `link` functionality would do what you want. You can selectively map (and thereby bind) one keypath to another (haven't used this much, so may not be 100% accurate):

```
var ComponentOne = Ractive.extend({
    template: '#ComponentOne',
    data: {
        internalVar: null
    },
    oninit: function() {
        this.link( 'internalVar', 'sharedVariable' );

        this.on( 'switcheroo', () => {
                this.link( 'internvalVar', 'otherSharedVariable' );
        });
    }
});
```

**Comment by arxpoetica** [comment]
I b'lieve `link` is precisely what I'm looking for. I also went to try it out—are you sure it's not the PR, and rather a CSRF prob?

![image](https://cloud.githubusercontent.com/assets/111424/11076082/cf729cbe-87c6-11e5-9da4-b6354f8e9aad.png)

When I use [this alternative CDN link](https://cdnjs.cloudflare.com/ajax/libs/ractive/0.7.3/ractive-legacy.js), I get the following instead:

![image](https://cloud.githubusercontent.com/assets/111424/11076104/f637237e-87c6-11e5-8d10-7158282fc246.png)

In any case, looking forward to trying out `link`. Any idea on when that might get merged?

**Comment by martypdx** [comment]
> Any idea on when that might get merged?

@evs-chris Iis there stuff to do or are you waiting for feedback?

**Comment by evs-chris** [comment]
@martypdx it's done pending review/feedback to make sure I didn't lose any marbles :smile:

**Comment by evs-chris** [comment]
@arxpoetica link/unlink has been merged into edge. Give it a try and let me know if it works for you. I'm going to close this for now, but feel free to re-open it if link doesn't suite.

**Comment by arxpoetica** [comment]
Awesome! :+1:
