### ISSUE TITLE
Concatenating two or more arrays results in duplicate DOM nodes rendered.

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2267]
Indexes are getting rendered multiple times when they shouldn't be. 

http://plnkr.co/edit/hrJyefxS964OxUkF21pz?p=preview

Click the first button, then the second. Each subsequent click adds duplicate keypaths getting rendered, but `app.get(vars)` returns a normal array as expected. (`app.get('vars').forEach(v => console.log(v))`)

I'm iterating over a computed var that returns two other arrays concatenated together. Doesn't seem to matter whether one is concat'd to the other, or if they're concated to a new, clean array.

```
            computed: {
                vars: function() {
                    
                    var things = this.get('things');
                    var stuff = this.get('stuff');
                    
                    
                    // return things.concat(stuff); 
                    
                     return [].concat(things).concat(stuff); //still broken

                },
            },
```

**Comment by JonDum** [comment]
Narrowed it down to something weird happening in `RepeatedFragment.prototype.update()`

```
  		if (this.pendingNewIndices) {
  			this.updatePostShuffle();
  			return;
  		}
```

As soon as `updatePostShuffle()` runs, the extra node gets added. Investigating further.

**Comment by JonDum** [comment]
It looks like `postUpdateShuffle()` isn't taking into account that there's already rendered nodes, but this might be a problem with shuffle getting confused due to the `._ractive` added on the arrays.

Turning off `modifyArrays` seems to fix it completely....

**Comment by evs-chris** [comment]
@JonDum thanks for the pointers! This is now fixed in edge.

**Comment by JonDum** [comment]
Chris, you beautiful, beautiful human you.
