### ISSUE TITLE
{{#each expression}} doesn't update correctly

### ISSUE THREAD

**Issue by MartinKolarik** [ractivejs/ractive#2269]
See http://jsfiddle.net/va6jU/110/ and click splice.

The problem is that `newIndices` array received by `RepeatedFragment#shuffle()` doesn't account for the fact there's an expression in `{{#each}}` section. In this case, the actual number of rendered fragments is 1 less than `items.length`, so when we get [here](https://github.com/ractivejs/ractive/blob/0155d0eb3b6797c8b74b4b58b1b648aa891fa9b8/src/view/RepeatedFragment.js#L360), we try to unrender a non-existing fragment.

**Comment by gaelicmichael** [comment]
I believe I'm encountering this problem too. The error I'm getting is:
TypeError: context is undefined
if (isArray(context.get())) {
ractive.js (line 6634, col 1)

**Comment by evs-chris** [comment]
@gaelicmichael the original fiddle works in edge now... are you still getting an error?

**Comment by gaelicmichael** [comment]
Yes -- I just updated to v0.8.0-edge (Sun Nov 15 2015 21:44:30) and I get the same error:
TypeError: context is undefined
if (isArray(context.get())) {
ractive.js (line 6634, col 1)

Note that I was not getting this error in my code when I was using 0.7.3.

**Comment by evs-chris** [comment]
I've looked through all of the ways I can think of to arrive at that line with an undefined context and I got nothing. How are you emptying and reloading the array? Also is there an observer that is also modifying the array that is not also deferred?

**Comment by gaelicmichael** [comment]
File is: https://github.com/Digital-Innovation-Lab/prospect/blob/master/js/edit-record.js

Array is cleared on line 395
The fillRecordFromTemplate() function fills it.

What do you mean by "deferred"?  Do I need to wait for a promise to refill it?  Example and/or documentation?

**Comment by evs-chris** [comment]
That helps a lot. Thanks!

Ractive can keep observers from firing until the DOM modifications from the current runloop (single set, update, toggle, etc) are complete, which tends to step around issues where a value is modified more than once in a runloop by observers. `ractive.observe('somepath', v => ..., { defer: true })`

**Comment by gaelicmichael** [comment]
Your comment is not clear to me. Are you telling me that my code has a problem with the way that it is using Ractive? If so, I need clearer directions to documentation or example that will fix the problem.

**Comment by gaelicmichael** [comment]
Let me also point out that the variable I am observing is NOT the array that is being changed.

**Comment by evs-chris** [comment]
Your code should continue to work as written for 0.8. I was just trying to gather enough context to hunt down the regression. I only mentioned deferred observers to help me narrow down where to look.

Sorry, I should have noted that. To be clear, any existing code written against 0.7.3 should continue to work with 0.8 except for very specific intentional breaking changes, of which this is NOT a case.

I should be able to track down the issue based on the project you linked. Thanks!

**Comment by gaelicmichael** [comment]
IN case it's of any use, the template file used with this JS file is at:
https://github.com/Digital-Innovation-Lab/prospect/blob/master/php/scripts/english-us/edit-record.txt

**Comment by gaelicmichael** [comment]
@evs-chris FYI, I've just tried with the version from today (Tue Nov 17) at 07:25:22.  I really love Ractive -- it's my JS data-binding/templating library of choice -- but this issue has been holding up the release of the software I've been developing.

**Comment by evs-chris** [comment]
@gaelicmichael I'm having trouble reducing this to a testable case. Do you have your project accessible on a development server somewhere? Either way, shoot me an email (or hangout) if you have some time that you can allot to trying a few test builds.

**Comment by gaelicmichael** [comment]
@evs-chris can you please email me directly at msnewton@unc.edu

**Comment by evs-chris** [comment]
Closing this in favor of the PR(s).
