### ISSUE TITLE
Select binding enhance test failures in firefox

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#2273]
The enhance binding tests for selects fail in Firefox because when the selected attribute is removed from the selected second option, the value of the select reverts to the first option. Then when the select binds, it sets its value and option state according to the new non-selected state. This seems to only affect Firefox. So my question is, should we a) work around the issue for Firefox, b) say that if the data doesn't match the occupant DOM state then ignore the DOM and go with data (make everything else act like Firefox for these two tests), or c) just disable the tests for Firefox and call it a browser specific corner case?

There's also a decorator teardown test that fails when the whole suite is run, but it doesn't fail when just the decorator module or the single test is run. I suppose that's a browser timing issue, so I'll go with it's safe to ignore.

**Comment by evs-chris** [comment]
Just noting that apparently Chrome 50 is changing to match the FF behavior, so this is an issue there too if #2369 doesn't land.

**Comment by sabob** [comment]
My vote is that #2369 should land for 0.8. Lot's of good things in there. Not sure what the risks (read new bugs) are with #2369? What do others think?
