### ISSUE TITLE
Invalid behavior of components in loop.

### ISSUE THREAD

**Issue by dangreen** [ractivejs/ractive#2275]
http://jsfiddle.net/zckx1pdb/3/

**Comment by heavyk** [comment]
unless I'm missing something, this works on edge

**Comment by dangreen** [comment]
In my app I use 0.7.3. When I use edge version I catch many errors, edge version is stable?

**Comment by heavyk** [comment]
unfortunately, it's not really all that stable. I too have bugs that are fixed on 0.8, but I still can't can't use it cause there are a bunch of other things broken.

have you tried working around it? that's what I've done, anyway.

**Comment by martypdx** [comment]
Work arounds:

* Use the array methods instead of api method (http://jsfiddle.net/zckx1pdb/4/):

```
_insert() {
        var items = this.parent.get("data"),
            index = items.indexOf(this.get("data"));
        items.splice( index + 1, 0,  { instances: 0 } );
} 
```

* Raise event and let parent do the add (http://jsfiddle.net/zckx1pdb/5/):

```
<button {{#if data.instances > 1}}style="color: red"{{/if}} on-click="inserted:{{data}}">Insert After</button>
```

```
var SubComponent = Ractive.extend({
	template: "#sub",
    components: { TestComponent },
    oninit() {
        this.on('*.inserted', function(item){
            var items = this.get("data"),
			    index = items.indexOf(item);
        
		    this.parent.splice("data", index + 1, 0, { instances: 0 });
        });    
    }
});
```

(note you could pass the index in as well and avoid the `indexOf` call)

**Comment by evs-chris** [comment]
0.8 isn't quite stable yet, but it hopefully will be soon. If you can try your app against edge and report any bugs you see, it would help tremendously!

**Comment by dangreen** [comment]
Thanks to all! Special to @martypdx!
