### ISSUE TITLE
Computations and setting keypaths

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#2276]
While testing some of my larger and harrier apps with edge, I came an odd scenario where edge and 0.7.3 are very different. I don't know if I was relying on undefined behavior in latest to accomplish this, but it feels like it should still work in edge.

I have a list of items that can be filtered, so my template has something like `{{#each helper.filteredItems()}} <button on-click="toggle(@keypath + '.foo')">Show</button>{{#if .foo}}... hidden initially ...{{/if}}{{/each}}`. `.foo` is initially not set and the button is meant to toggle it to `true`, and it does in latest. Should I still be able to do this or some approximation in edge?

I feel like maybe `set` shouldn't be allowed but that there should be a way to set foo on the event context and then trigger an update for `@foo().0.foo` and the like. Also, it seems that computations don't participate in the unresolved handling process right now, so even if I force the set on `@foo().0.foo`, the section doesn't show.

**Comment by JonDum** [comment]
> Should I still be able to do this or some approximation in edge?
Absoutely yea. The fact that it works at all is what makes ractive so freaking cool.

> Also, it seems that computations don't participate in the unresolved handling process right now, so event if I force the set on @foo().0.foo, the section doesn't show.

Sounds like another buggy boo for 0.8. We're getting so close I can smell it!

**Comment by evs-chris** [comment]
Search fail on my part... this is already in discussion in #2123.
