### ISSUE TITLE
{{#each}} inside {{#if}} does not work correctly on edge

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2277]
Check this fiddle: http://jsfiddle.net/oddf24yp/6/
When you remove all items in the list it should only display "The list is empty".
It seems that the last item is left on DOM.

This works as expected in 0.73

**Comment by Madgvox** [comment]
As a workaround for now, using an `else` with the `each` block directly still works:

```html
{{#each list}}
  {{text}}<a href="javascript:;" on-click="remove_me">x</a><br />
{{else}}
  <p>The list is empty</p>
{{/each}}
```

**Comment by kouts** [comment]
Thanks @Madgvox , I'm building an app prototype using 0.73 and from time to time I test it with 0.8, great way to discover things like these.

**Comment by evs-chris** [comment]
@kouts thanks for the report!
