### ISSUE TITLE
Observe fails when inside decorator (0.8)

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2278]
Here is the fiddle: http://jsfiddle.net/r8gx1858/24/
So what this decorator does is that it takes a config object like this:
```
{
    disabled: false,
    required: false,
    hidden: false
}
```
and applies these properties to a form element inside a div (select, input, button etc).
To see a working example check this fiddle: http://jsfiddle.net/35rLq5Lr/1/
It is the same example as above but with 0.7.3 instead of edge.
Select Italy or Belgium from the dropdown list to see a second dropdown appear, based on field properties set.

**Comment by evs-chris** [comment]
@kouts thanks for the report!
