### ISSUE TITLE
0.8 edge sets textbox value as "undefined"

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive#2279]
In short, here is the template:
```
<input type="text" value="{{ root.searchText }}" />
```
```searchText``` is not always present as a property on the object. In the past, this would always render the value as blank. With latest 0.8, it sets the value as "undefined" (see attached pic). However, it doesn't do this the first time, only when subsequently using ```ractive.set()``` on an object does the "undefined" text appear.

<img width="274" alt="screen shot 2015-11-15 at 2 06 48 pm" src="https://cloud.githubusercontent.com/assets/414752/11171345/9cfd63ce-8ba2-11e5-9499-a775c2506fed.png">

**Comment by Madgvox** [comment]
Put together a quick jsfiddle: http://jsfiddle.net/fzwgh6zg/

**Comment by matthew-dean** [comment]
Thanks @Madgvox!
