### ISSUE TITLE
"with" context added to keypath in edge

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive#2281]
Simplified example: I have a template like:

``` html
        {{#each ~/top.sources}}

            {{# { files: ., category: @key, top: top } }}

                <ul>
                {{#if .files}}
                    {{#.files:i}}
                        {{#if i == 0}}
                            <li style="height: 23px"><h1>{{ category }}</h1></li>
                        {{/if}}

                        {{>file}}
                    {{/}}
                {{/if}}
                </ul>

            {{/}}

        {{/each}}
{{#partial file}}
<li on-click="doSomething />blah</li>
{{/partial}}
```

In 0.7.3, the keypath passed to the on-click event was something like: "`top.sources.0.files.0.stuff`"
In edge, it's "`@{files:top\.sources\.less,category:less,top:less}.files.0`".

The latter is pretty useless to me and now breaks this (simplified for example) code:

``` js
ractive.set(event.keypath + '.open', !ractive.get(event.keypath + '.open') );
```

So, bug, yes?

**Comment by Madgvox** [comment]
Hmm... in testing this, it looks like the 'weird' keypath has everything to do with the aliasing from `{{# { files: ., category: @key, top: top } }}` and not at all based on changes introduced by 0.8.

Here you can see that in latest, when you access the keypath from an aliased block, it will show the alias in the keypath, even in 0.7.3: http://jsfiddle.net/f869exzw/1/

The only difference between 0.7.3 and 0.8 is a slightly more compact syntax for the aliased keypaths: http://jsfiddle.net/f869exzw/2/

I'm going to mark it as an enhancement instead, maybe there's some way to simplify 1:1 aliases into 'real' keypaths?

**Comment by martypdx** [comment]
The issue is that in `0.7` setting against a keypath that represented an expression would actually find the expression and apply the change to the output of that expression. `0.8` no longer support setting children of expressions (but does allow with aliasing instead). Let me see if I can mock that up...

**Comment by martypdx** [comment]
Okay, found an issue in iteration aliasing, but basic concept is that you could just write:

```
 {{#each ~/top.sources as files:category}}

{{/each}}
```

**Comment by matthew-dean** [comment]
Well, maybe this is two issues. The second is that, if this is a valid keypath, then setting it and concatenating a "sub" keypath should still work. But here, it didn't. So, even if the keypath is different, it seems that it's not accepted in ```ractive.set()```.

**Comment by matthew-dean** [comment]
@martypdx I was going to report your code had an error, and then I searched here for that error, which led me back where, whereupon I realized that you were actually saying it doesn't currently work, but that's how you would currently write it.

Is there a different kind of workaround that currently works in edge?

**Comment by Madgvox** [comment]
Since the complete keypath is still in there, just kind of broken up, you could parse `{files:top\.sources\.less,category:less,top:less}` into an object of strings (or otherwise separate the alias from the keypath), then replace `files` in `.files.0` with `parsedObject[ 'files' ]` making the keypath `top.sources.less.0`. It's a kludge for sure, but it should work.

**Comment by martypdx** [comment]
Is the data structure recursive?

**Comment by matthew-dean** [comment]
Good point about object parsing. What did you mean separate the alias from the keypath?

**Comment by Madgvox** [comment]
The docs could certainly use a spring cleaning. If it's not already on the roadmap, I'm going to be campaigning for it once 0.8 is released.

In your example, the keypath that was returned was `@{files:top\.sources\.less,category:less,top:less}.files.0`. In this instance, 'alias' refers to the `@{stuff}` portion of the keypath. In your template, you're _aliasing_ the keypath `top.sources.less` to the variable `files`. So in order to retrieve the original keypath back, you just have to undo the process, by replacing `files` in `files.0` (the non-aliased part of the keypath) with `top.sources.less` to get the full keypath `top.sources.less.0`.

**Comment by Rich-Harris** [comment]
> The docs could certainly use a spring cleaning. If it's not already on the roadmap, I'm going to be campaigning for it once 0.8 is released.

God yes. I was poking around the various sites recently (after I managed to screw up a bunch of DNS settings and decided to migrate everything to Surge), and the docs repo made me wince. Well, a lot of them did, but especially the docs. I reckon we should have everything on a single page, so that searching for 'Aliasing' would just be a Cmd-F away.

**Comment by Madgvox** [comment]
An actual docs search bar wouldn't hurt either.

**Comment by martypdx** [comment]
@matthew-dean The end of the `{{#with expression}}` hack (see http://jsfiddle.net/x0e1y1xy/):

```handlebars
    {{#each ~/top.sources as files:category}}
    <ul>
        {{#each files as file:i}}
            {{#if i == 0}}
            <li style="height: 23px">
                <h2>{{ category }}</h2>
            </li>
            {{/if}}
            {{>file file}}
        {{/each}}
    </ul>
    {{/each}}

    {{#partial file}}
    <li on-click="doSomething()">{{type}} - {{name}} - {{@keypath}}</li>
    {{/partial}}
```

**Comment by matthew-dean** [comment]
Am I understanding from your example that this new keypath behavior is here to stay? Or is it a bug? Currently there are few templates the current behavior doesn't break for me.

**Comment by matthew-dean** [comment]
For example, I'm noticing that in edge, two-way-binding doesn't work inside of aliased sections. It will display the correct value, but it won't update the object. Should that be filed as a separate bug?

**Comment by martypdx** [comment]
> I'm noticing that in edge, two-way-binding doesn't work inside of aliased sections (but works in 0.7.3). It will display the correct value, but it won't update the object. 

Correct, should be a console message saying you can't update children properties of expressions

> Should that be filed as a separate bug? 

Not a bug

> Is this #2123?

Yes, that issue and the commits/PR it references have the details

>  (I doubt it since I'm not using a computed value.)

Not true, both of these blocks use expressions (expression == computed property):

```handlebars
{{# { compiler: .compiler, fileOptions: this.options } }}
{{#each getSettings(compiler).options }}
```

**Comment by martypdx** [comment]
BTW: This is the issue that arises with allowing the update of child properties of expressions:

```handlebars
{{foo}}

{{#with { bar: foo } }}
    <!-- won't update foo used above -->
    <input value='{{bar}}'>
{{/with}}
```

**Comment by martypdx** [comment]
OMG, I just realised @evs-chris put in comma-seperated aliases:

```html
{{#with foo as bar, qux as obj }}
    <input value='{{bar}}'>
    {{obj.name}}
{{/with}}
```

:grin:

**Comment by matthew-dean** [comment]
Okay, hold on a second....

I'm calling computed properties what Ractive calls them: http://docs.ractivejs.org/latest/computed-properties. That is not what I'm doing.

The value binding to the form fields are _not_ the result of an expression. They are references to a particular path in my data, so the object reference may be computed, but it doesn't compute a value based on that data. All I'm doing here is naming those object path references. 

This expression:
```hbs
{{#each getSettings(compiler).options }}
```
... is just to get the proper labels and keys that will be used to reference the data. I don't see what the value is of creating the breaking change of walling off references to parent data. In fact, this example:
```
{{foo}}

{{#with { bar: foo } }}
    <!-- won't update foo used above -->
    <input value='{{bar}}'>
{{/with}}
```
I'm not sure what you meant to illustrate here, because it doesn't explain the change. An author could just as easily write the same mistake as:
```
{{foo}}
    <input value='{{foo}}'>
```
Computing keypaths to my data using expressions I use all the time in my templates, and in my cases, for two-way binding, so the previous 0.7.3 behavior is something I'm constantly relying on. And, based on your other syntax examples, it still wouldn't help me, since you say any reference inside of ```{{#each getSettings(compiler).options }}``` would not bind to fields at all. Please reconsider this.

**Comment by martypdx** [comment]
> I don't see what the value is of creating the breaking change of walling off references to parent data. In fact, this example:
> 
> {{foo}}
> 
> {{#with { bar: foo } }}
>     
>     <input value='{{bar}}'>
> {{/with}}
> I'm not sure what you meant to illustrate here, because it doesn't explain the change. An author could just as easily write the same mistake as:
> 
> {{foo}}
>     <input value='{{foo}}'>

The later is different because the binding is consistent. Once you use an expression, the updates within the block don't propagate outside the block, try changing the inputs in [this 0.7 example](http://jsfiddle.net/Lgq61w6s/).

> since you say any reference inside of {{#each getSettings(compiler).options }} would not bind to fields at all.

No, just the child properties of expressions.

> This expression:
> 
> {{#each getSettings(compiler).options }}
> ... is just to get the proper labels and keys that will be used to reference the data.

Right, so that wouldn't be an issue. The only issue in your example is the first block, which you would write as:

```handlebars
{{#with .compiler as compiler, this.options as fileOptions }}
{{#each getSettings(compiler).options }}
    ...
{{/each}}
{{/with}}
```

Here's a slimmed down fiddle of your example showing the updates happening in 0.8: http://jsfiddle.net/qyn675cz/

**Comment by matthew-dean** [comment]
@martypdx Oh. I got confused because earlier you said that ```{{#each getSettings(compiler).options }}``` was an expression.

As far as the ```#with``` block, maybe I'm still not getting it. Isn't it just different syntax to write the same thing?

Isn't ```{{#with { bar: foo, red: green } }}``` kinda the same as ```{{#with foo as bar, green as red }}```? Maybe the difference is more obvious if you know the Ractive internals, but to me, it's just a syntax difference. The only reason I could see for treating them differently is that the latter doesn't allow computed values e.g. ```{{#with { bar: foo + 1} }}``` makes no sense as ```{{#with (foo + 1) as bar }}``` (I guess). Although a computed value seems detectable.

So with those similarities, it seems strange that the existing syntax has a breaking change to a new behavior, and a new syntax replaces the old behavior which was just broken.  o_O

**Comment by martypdx** [comment]
> I got confused because earlier you said that {{#each getSettings(compiler).options }} was an expression

Well it is, but you're not trying to update any of its properties :)

> That is, isn't {{#with { bar: foo, red: green } }} kinda the same as {{#with foo as bar, green as red }}?  ... The only reason I could see for treating them differently is that the latter doesn't allow computed values e.g. {{#with { bar: foo + 1} }} makes no sense as {{#with (foo + 1) as bar }}

That's basically it, We've been getting fairly regular issues with people using the expression object literal syntax and then wondering why the updates aren't propagating outside of the block. We talked about trying to "reverse engineer" but that felt hacky and you'd could end up with half-baked stuff like `{ foo: bar, qux: bizz(buzz) }`. 

So instead we separated aliasing into it's own construct believing that's what people were really doing anyway, so now it's more obvious and avoids the triple `}` pile up.

**Comment by martypdx** [comment]
And it doesn't look like I've mentioned it in this thread, but the one type of "expression" that is fully bindable is the keypath expression: `{{ foo[bar] }}`

**Comment by martypdx** [comment]
@evs-chris Is the double `x` intentional for aliases?

```html
{{#with 3 * 2 + 10 as num}}{{num}}{{/with}}
```

```json
{
  "n": "num",
  "x": {
    "x": {
      "r": [],
      "s": "3*2+10"
    }
  }
}
```

**Comment by evs-chris** [comment]
No. I didn't modify any of the existing parsers, so I suspect it's an artifact of what the reference or expression parser expects.
