### ISSUE TITLE
Babel transpilation issue on block aliases

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#2282]
Looking into #2281, it looks like babel is changing [these lines](https://github.com/ractivejs/ractive/blob/dev/src/view/RepeatedFragment.js#L107-L109):

```
if ( this.owner.template.z ) {
    fragment.aliases = { [this.owner.template.z[0].n]: model };
}
```

into [this](https://github.com/ractivejs/ractive/blob/build/ractive.js#L6560-L6562):

```
if (this.owner.template.z) {
    fragment.aliases = defineProperty({}, this.owner.template.z[0].n, model);
}
```

(which fails because it should be `{ value: model }`).

However, if I use the babel online cli for:

```
var foo = { bar: 'bar' }
var o = { [foo.bar]: 12 };
```

It generates a babel defined `_defineProperty`:

```
function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

var foo = { bar: 'bar' };
var o = _defineProperty({}, foo.bar, 12);
```

Maybe conflict with babel somehow, HOWEVER probably better to skip babel on this one and just do:

```
const aliases = {};
aliases[this.owner.template.z[0].n] = model;
fragment.aliases = aliases };
```

(Note there are multiple occurrences in that file)

**Comment by evs-chris** [comment]
@martypdx I couldn't figure out why, but the iterative aliasing tests were running fine in Chrome and refused to run in phantom. Swapping out the computed properties makes all of the tests work in phantom too. It also fixes the #2264 failure. I shall henceforth be more wary of newer ES features.
