### ISSUE TITLE
ractive.observe should always be async

### ISSUE THREAD

**Issue by saiichihashimoto** [ractivejs/ractive#2285]
I've run into the case of needing to run the callback in ```ractive.observe``` on init and on changes, but there's a chance that the callback will cancel the observer itself. This fails in cases where the canceling happens in the init. A trivial example:
```javascript
console.log('output 1');
var observer = ractive.observe('property', function() {
    // some code
    console.log('output 3');
    if (somethingtrue) {    // if this happens to be true on init...
        observer.cancel();  // ...this throws a TypeError
    }
    // some more code
}, { defer: true, init: true });
console.log('output 2');
```

This will throw a ```TypeError: Cannot read property 'cancel' of undefined```. The callback is being called **before** ```ractive.observe``` can return the object to set to ```observer```, so the ```observer.cancel``` call is being called on an undefined value. I can't rely on ```observer``` existing within the callback. The ideal flow would end up outputing:
```
output 1
output 2
output 3
```

but instead it outputs:
```
output 1
output 3
output 2
```

If there were more code after the ```output 2```, I can't be sure if the observer has already run once yet.

In @isaacs's [blog post about async apis](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony), the problem is explained pretty well:

> If you have an API which takes a callback,
and sometimes that callback is called immediately,
and other times that callback is called at some point in the future,
then you will render any code using this API impossible to reason about, and cause the release of Zalgo.

The only true work around (that I can think of) would look like:
```javascript
// some code
if (somethingtrue) {
    var observer = ractive.observe('property', function() {
        // some code (same code as above)
        if (somethingtrue) {
            observer.cancel();
        }
        // some more code (same code as below)
    }, { defer: true, init: true });
}
// some more code
```

Though there's obviously some way to not write the same code twice (defining the before and after code in separate function, for example), this is the sort of thing that having ```ractive.observe``` running on init by default should prevent, afaik.

**Comment by fskreuz** [comment]
Observer callbacks, by default, execute immediately when created. To prevent it from firing during creation, [`observe` accepts a config object as second argument where you can set `init` to `false`](http://docs.ractivejs.org/latest/ractive-observe).

**Comment by saiichihashimoto** [comment]
That doesn't deal with the issue completely. If we did want the callback to run initially but there was a condition that could cancel the observer, that wouldn't be possible as is.

i.e.
```javascript
var observer = ractive.observe('property', function(some_value) {
    // maybe do some stuff
    if (some_value === 'DONE_OBSERVING') {
        observer.cancel(); // This throws a TypeError if it happens the first time
    }
    // maybe do some other stuff
});
```

**Comment by fskreuz** [comment]
Well, your first post didn't include your use case, so we are left guessing what you are really doing. Would you mind putting a sample use case on the first post?

**Comment by martypdx** [comment]
> In @isaacs's blog post about async apis, the problem is explained pretty well

This doesn't apply to this api because `ractive.observe` is an event emitter, not an asynchronous api. (For the later case, promises work, for event emitters promises don't work).

Furthermore, `ractive.observe` without `{ init: false }` (and without `{ defer: true }`( should _always_ fire immediately and synchronously. Please post an example if you are seeing this behavior.

**Comment by saiichihashimoto** [comment]
I updated my initial post, hopefully it adds clarity.

I tried using the options ```{ init: true, defer: true }``` but this did nothing different. Is that not what @martypdx meant?

I suppose a use case is that the observer can be cancelled based on the value its observing. If I'm approaching this incorrectly, what is the expected way of:

1. Running the same code for initialization and value changes AND
2. having a condition where the observer can be cancelled within the callback (or in the case of init... not being setup up to begin with?)

Or is this a use case that Ractive is not designed to handle?

**Comment by saiichihashimoto** [comment]
I was under the assumption that a large part of ractive was asynchronous, i.e. doing an ```ractive.set``` would affect the dom later in the event loop. I see that I am wrong. Closing issue.

**Comment by martypdx** [comment]
> I tried using the options { init: true, defer: true } but this did nothing different. Is that not what @martypdx meant?

`init: true` is the default, setting it to false prevents initial firing, but I don't think that's what you want (see http://docs.ractivejs.org/latest/ractive-observe for info on options).

For your use case, I think you need to just guard against an initial value:

```js

if ( ractive.get('property') !== 'DONE_OBSERVING' ) {
    var observer = ractive.observe('property', function(some_value) {
        if (some_value === 'DONE_OBSERVING') {
            observer.cancel();
        }
        // maybe do some other stuff
    });
}

```

You could even wrap that in a prototype method:

```js
Ractive.prototype.observeUntil = function ( keypath, cancel, handler, options ) {
    if ( cancel( this.get(keypath) ) ) return;
    var observer = this.observe(keypath, function(n, o, k){
        if ( condition(n) ) return observer.cancel();
        handler.call( this, n, o, k );
    }, options);
}
```
