### ISSUE TITLE
question on adaptors

### ISSUE THREAD

**Issue by telekosmos** [ractivejs/ractive#2288]
Hi
At the [http://docs.ractivejs.org/latest/writing-adaptor-plugins](http://docs.ractivejs.org/latest/writing-adaptor-plugins), the documentation on `adaptor.set(...)` says:

```
// The `set()` method is called when you do `ractive.set()`, if the keypath
// is _downstream_ of the wrapped object. (...)
```

Trying to come up with a custom adaptor, I can have, let's say

```
//...
data: function() {
   return {
      state: adaptorState;
  }
}
```

Then:
- if I do `ractive.set('state.list', newItem)` then this gets filtered by adaptor
- if I do `ractive.set('state.list[itemId]', newVal)`, `ractive.data` does not get updated but this `set` is filtered by adaptor, then `ractive.data` can get updated from adaptor.
- if I do `ractive.set('state.list.itemId, newVal)`, `ractive.data` does get updated but it is not filtered by adaptor. So, `set` method in adaptor is not run.

Did I misunderstand the documentation regarding the downstream concept or is there any limit on the downstream level? 

Cheers!!

**Comment by Rich-Harris** [comment]
Actually I think this might be a case of bad documentation – the `set()` method is only called when you set a property directly on the adapted object. We should probably clarify exactly what the rules are regarding downstream changes on adaptors and enforce them with tests – I suspect we might need to change [this method](https://github.com/ractivejs/ractive/blob/b8f7e37eed61692a08d7bf572a73aa0a2cbf496e/src/model/Model.js#L191-L196) such that adaptors are created for new branches.

Could you spell out what you're trying to do and what the expected results are please? Would help with coming up with a sensible test. Thanks

**Comment by evs-chris** [comment]
Gonna move this over to #2512.
