### ISSUE TITLE
Tutorial color theme for the love of god

### ISSUE THREAD

**Issue by gigmig** [ractivejs/ractive#2289]
I know it's a childish request but..
Please can you put dark color theme on the tutorial, http://learn.ractivejs.org/event-proxies/1
I understand the design is sleek but I want to gauge my eyes out and im on step 4. 
https://41.media.tumblr.com/22d01faa8f5d7614c4513dd7f6857248/tumblr_mm13nbkGCO1qka8bio1_400.jpg
I might have crappy display, but i checked it on a decent dell display in the office and the colors are still subtle especially in the <> in the html. Most of the colors are not visible (on the pro tips and the top menu) on most of the displays in the office (except on the dell one), nor the highlights of the text or html/js editor.
Monokai would be nice. Or Dracula or whatever just not the current one. Or if it needs to be the light one make it a bit more readable. The tutorail is great, but maimed by the color theme.. Thanks

**Comment by bryansray** [comment]
https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en

Best bet is to probably use a Chrome Plugin to do it yourself.

**Comment by gigmig** [comment]
Yea I thought of Stylish, the problem is that we inherited a project with ractive and other technologies, with very tight deadline and i discarded the idea of creating styles for the tutorial..I needed to go through it fast. This is more of a suggestion for some other guys that will be in similar situation. Thanks.

**Comment by gigmig** [comment]
Just got home and yep, the design of the ractive website/tutorial doesn't look what you think it looks to the majority. :)

**Comment by Madgvox** [comment]
An overhaul of the docs is coming down the line. With that, we'll certainly take a look at the tutorials as well.

**Comment by gigmig** [comment]
Thanks for the response guys.

**Comment by Rich-Harris** [comment]
> the design of the ractive website/tutorial doesn't look what you think it looks to the majority

eek, thanks for the heads up! I'll close this in favour of https://github.com/ractivejs/learn.ractivejs.org/issues/26
