### ISSUE TITLE
Can't place some utf symbols in the template

### ISSUE THREAD

**Issue by tovarishStepanov** [ractivejs/ractive#2291]
For example &#128527; (&#128527); looks like ?, however &#9824; (&#9824) displays properly;

**Comment by fskreuz** [comment]
[Definitely something funny going on here](http://jsfiddle.net/h163v7gu/1/). Went to check if this was a bug or wasn't really supported. The funny thing is [it works on v0.4](http://jsfiddle.net/h163v7gu/2/). It broke v0.5 onwards, including edge.

```js
var instance = new Ractive({
    el: document.body,
    append: true,
    template: '<div>Hello &#128527; World &#9824; People</div>',
});

console.log(Ractive.parse('Hello &#128527; World &#9824; People'));
// {"v":3,"t":["Hello � World ♠ People"]}
console.log(instance.toHTML());
// <div>Hello � World ♠ People</div>
```
