### ISSUE TITLE
multiple copies of Ractive on a single page causes CSS scoping errors...

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#2292]
...because each copy keeps its own `data-ractive-css` tally

**Comment by fskreuz** [comment]
> multiple copies of Ractive on a single page

Is there a use case for having multiple versions of Ractive on one page? Or is this for the new versions to gracefully catch accidentally putting in 2 copies on the page?

**Comment by gaelicmichael** [comment]
Sorry for the naive question, but does this refer to creating a new instance of Ractive? If so, this needs to be supported -- I have an instance of Ractive running to manage the GUI but create another instance to control a dialog box, for example.

**Comment by Rich-Harris** [comment]
> Is there a use case for having multiple versions of Ractive on one page?

Sort of... my day job often involves creating interactive widgets for [pages like this](http://www.theguardian.com/us-news/2015/dec/01/the-county-kern-county-deadliest-police-killings) – the widgets need to be developed and tested separately, but they all need to live on the same page. Cruel experience has taught us the folly of attempting to load shared libraries from a CDN or vendor bundle – everything is async, we don't control the page itself, we use different AMD loaders in different environments (web vs app etc), mucking around with the loader config causes all sorts of hairy problems that you *don't* want to debug on a deadline, we need fully reproducible builds, etc, etc. If we had more time we could solve some of these issues but the simplest and most reliable solution is simply to bundle each app up separately. 

> does this refer to creating a new instance of Ractive?

No, this is purely about 

```js
<script src='my-bundled-ractive-app.js'></script>
<script src='my-other-bundled-ractive-app.js'></script>
```

– you can have as many top-level instances as you like, and CSS scoping will work as expected.

**Comment by fskreuz** [comment]
CSS from multiple Ractives should now be covered https://github.com/ractivejs/ractive/pull/2362
