### ISSUE TITLE
Scoped CSS pseudo-elements fails

### ISSUE THREAD

**Issue by KP** [ractivejs/ractive#2294]
In components, some CSS pseudo-elements do not work properly. For instance, `test-class::after` does not work while `.test-two:after` does work. In the case of `-webkit-slider-runnable-track` neither `.input-one:-webkit-slider-runnable-track` or `.input-two::-webkit-slider-runnable-track` work.

See here:

http://jsfiddle.net/veg1vwow/3/

**Comment by MartinKolarik** [comment]
[Fixed](http://jsfiddle.net/veg1vwow/3/). Thanks for reporting!

**Comment by KP** [comment]
Thanks Martin for fixing this so quickly!
