### ISSUE TITLE
Keypaths wrong for mapped data

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#2297]
Both `@keypath` and observer `keypath` report source data keypath, not component keypath. See http://jsfiddle.net/dt55zpmL/.

**Comment by evs-chris** [comment]
Shall I add the observer case to #2264?

**Comment by martypdx** [comment]
@evs-chris forgot about that PR, looks like that would do it. :+1: 

Have some follow-up questions I'll post on #2264

**Comment by martypdx** [comment]
@evs-chris I already have the test in next push to #2296
