### ISSUE TITLE
Two-way binding doesn't work straightforwardly inside partials

### ISSUE THREAD

**Issue by wmcmurray** [ractivejs/ractive#2298]
I've seen a lot of issues about two-way bindings inside partials but none exactly like what I'm trying to achieve *(I believe)* :

In this [simplified fiddle](http://jsfiddle.net/1mtz3ey3/1/), I've made a partial used to display a `<select>` with options. When I change the value of this generated `<select>`, the value in the context above **doesn't get updated** while the other way around works (changing the value in the context above **changes** the value in the generated `<select>`).

At this point, I would think that the partials are like an other context without bindings outside of it **BUT** the variable printed in the partial **doesn't** seems to follow the value of the `<select>`. Isn't that stange ?

I understand that I could do this to solve the issue:

```
{{#with food as value}}
    {{> select}}
{{/with}}
```

...but it feels strange to me.

I expect partials to be **self-contained** (devoid of external aliases to make them work) and able to bind **straightforwardly** with their parent context.

Dunno if it's easy to implement but...

![](http://www.quickmeme.com/img/46/46b35216e5fc5bc36b9b718384ee8f0b80311fc74feda5fb1b850a1b977bbf49.jpg)

Thank you :)

**Comment by hstonge** [comment]
+1

**Comment by martypdx** [comment]
Yes, I agree this should work because `{{>partial [context] }}` gets normalized to `{{#with [context[}}{{>partial}}{{/with}}`, so we just overlooked the new alias case of `context as alias`.

BTW - you can also pass a context that you use as `this` in the partial, see http://jsfiddle.net/fx5ayh1k/:

```handlebars
   {{#partial select}}
    <select value="{{this}}">
      <option value="cookie">Cookie</option>
      <option value="cake">Cake</option>
      <option value="pasta">Pasta</option>
      <option value="pizza">Pizza</option>
    </select>
    <p>The value inside partial : <span class="right">{{this}}</span></p>
   {{/partial}}


   {{>select food }}

**Comment by wmcmurray** [comment]
Ohhh well done ! :+1: 

I haven't tested this case because I wanted to add more functionalities to my partial.
ex: adding an empty option `<option value="">-</option>` at the begining like so:

`{{>select {value: food, empty: true}}}`

...resulting in a new bug discovery :smile:

**Comment by evs-chris** [comment]
I have a PR for adding the aliasing shortcut to partials too - see #2299. That should allow `{{>select food as value, true as empty}}`. Aliases don't kill binding for normal paths like manual object creation for context does, but you can still do the latter with aliasing e.g. `{{>select food as value, { empty: true, extras: [ 'bar', 'baz' ] } as options } }}` and have one way access to `options.empty` and `options.extras` and two way access to value in the select partial.

**Comment by wmcmurray** [comment]
:point_up: cool stuff ! This way you give the choice to the developer if he wants two way bindings or not, but it's less straightforward than just passing variables with bindings that always works under the hood.

**Comment by evs-chris** [comment]
Completely unrelated, but I wanted to say somewhere that I miss the old jsfiddle... there's no handy Ractive {Edge,Latest} dropdown anymore... :cry:

**Comment by wmcmurray** [comment]
Ahahah I had the exact same reaction this morning

**Comment by martypdx** [comment]
It's still there under the settings in the upper right of the javascript panel.

**Comment by martypdx** [comment]
(Though it's still not alphabetical :frowning: )

**Comment by evs-chris** [comment]
Ah! I always forget about the panel options... also a step down in discoverability in my humble and accurate opinion. Thanks for pointing that out!

**Comment by Madgvox** [comment]
They go through all the trouble to update the look but `Ctrl+/` still puts HTML comments in the Javascript box. >.>

**Comment by wmcmurray** [comment]
https://github.com/jsfiddle/jsfiddle-issues/issues :wink:

**Comment by Rich-Harris** [comment]
Closing this now that it's fixed
