### ISSUE TITLE
30 - 50 sec component load times on older mobile devices using Ractive in Cordova

### ISSUE THREAD

**Issue by dwolner** [ractivejs/ractive#2300]
Hey guys!

We’re using Ractive for mobile development with Cordova and one of our bigger apps has more components than usual (around 15). On some older devices, Ractive.load() is taking 30 - 50 secs to compile components on app launch:

iPhone 4: 52 s
iPhone 4s: 40 s
iPhone 5c: 31 s
iPhone 5: 30 s
iPad Mini 1st gen: 30 s
iPad Mini 2nd gen: 12 s
iPhone 5s: 10 s 
iPhone 5s: 9 s
iPhone 6: 8 s
iPhone 6s: 6 s

This has got to be just the difference in their cpu power, and it seems like if we precompile Ractive components and templates this might speed up loading? If so, maybe use Gobble?

Another option would be loading and parsing only what’s needed for the first view, then loading and parsing things in the background, based on user actions, in a sort of “just in time” approach.

Any ideas welcome, also, we would be happy to pay your hourly consulting rate if you can help us solve this issue. Thanks!

**Comment by MartinKolarik** [comment]
Parsing should be a lot faster in edge, so you might want to try the edge build (not sure if it's stable enough though). But in any case, pre-parsing all your templates can still save some time and there's no reason not to make it a part of your build process.

**Comment by JonDum** [comment]
Those seem *extremely* long. `6s` load time on iPhone 6s is still crazy high. I have a feeling you're doing something odd. Would you mind sharing your benchmark and/or code?

**Comment by dwolner** [comment]
Without getting into the actual code, our startup process is this:

OnDeviceReady we:
1. pull relevant info out of the cache and setup a ractive data obj
2. setup the file system including checking what data the user already has
3. Ractive.load()
4. .then(function() {
5. var r = new Ractive({ ......
6. ractive.oninit then shows the first "scene"

I put diagnostic events in between each process (each 'step' above), and the largest (and sometimes the only noticeable) chunk of load time was between Ractive.load() and right before new Ractive. As the devices got older and slower, then time went up in correlation with the processing power of the device.

**Comment by JonDum** [comment]
If I'm not mistaken, Ractive.load() goes out to the network to grab the templates as well. Are you sure you're not also hitting network latency here in your measurements?

**Comment by martypdx** [comment]
Hey @dwolner - I put together a [simple-ractive-bundling](https://github.com/martypdx/simple-ractive-bundling) repo that uses gobble and rollup for bundling components.

I designed it specifically for dropping into projects that use Ractive.load and traditional global `<script>` tag inclusions of libraries.

**Comment by dwolner** [comment]
Oh awesome! Thanks Marty!
@JonDum all of our components are local on the device

**Comment by fskreuz** [comment]
Loading templates on the fly is slow. That's because the process involves loading the scripts you need, then load the templates for those components from disk, parsing the templates, then building Ractive instances. The first 3 can be prevented by a build phase, by pre-parsing and bunding everything. That way, your app will load from just a few bundled up files rather than several files.

**Comment by jmellicker** [comment]
Just wanted to update this issue– @martypdx set up a [Gobble](https://github.com/gobblejs/gobble) script for us to pre-compile all components to Ractive's native objects (as well as other build optimizations)... so far it looks like app load times have been reduced 80% - 90%, we're doing a complete suite of tests on old devices and will update.

**Comment by jmellicker** [comment]
Speed increase of elapsed time from appReady => ready for user input: **200x** by using Marty's Gobble script and pre-compiling components and partials.

On iPhone 4, total launch time went from 52 sec => 10 sec
iPad Mini 1, 30 sec => 10 sec
iPhone 6s, 6 sec => 1 sec

Thanks @martypdx and everyone!

**Comment by JonDum** [comment]
As a follow up to this, maybe we need a big disclaimer on ractive-load's readme that strongly recommends precompiling load critical templates and using the loader for additional post-load templates.

**Comment by paulocoghi** [comment]
@martypdx Congratulations, again! You are incredible!
