### ISSUE TITLE
Returning false from method calls not working

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2301]
According to the docs[1], returning false from method calls should cancel the original event: event.original.stopPropagation and event.original.preventDefault.

See this fiddle:
http://fiddle.jshell.net/sabob/wzm2msre/8/

Clicking the link and returning false from the method should stop propagating up to the parent div, however the div is still receiving the event.

This is in edge and latest.

Kind regards

Bob

[1]: http://docs.ractivejs.org/latest/method-calls

**Comment by martypdx** [comment]
Thanks for flagging this. I noticed it too, but forgot to create an issue.

**Comment by martypdx** [comment]
Ah, works for events but not method calls. PR inbound...
