### ISSUE TITLE
Bug when mixing strings and objects in proxy event arguments

### ISSUE THREAD

**Issue by TehShrike** [ractivejs/ractive#2303]
Fiddle: http://jsfiddle.net/1xnzn7qg/

In the template: `<button on-click="event-name:someString,{{objectOnScope}}">click meh</button>`

In the code:
```
r.on('event-name', function(event, str, hopefullyTheObject) {
  console.log(str, hopefullyTheObject)
})
```

Expected: `str` should be the string `someString` and `hopefullyTheObject` should be the object `{ thing: 'one', subthing: 'hello' }`.

Observed: when the event fires, `str` is the string `someString,[object Object]` and `hopefullyTheObject` is undefined.

Reproduced in edge (0.8) and latest.

If I change the template to `<button on-click="event-name:{{'someString'}},{{objectOnScope}}">click meh</button>` then the two arguments are correct.

**Comment by Rich-Harris** [comment]
Yeah, this is exactly the sort of confusion we can eliminate with #1172. It's easy to workaround – you just need to quote the string: http://jsfiddle.net/8hp2pc0w/

```html
<button on-click="event-name:'someString',{{objectOnScope}}">click meh</button>
```

**Comment by Rich-Harris** [comment]
Btw, re

> I can't replace this with function calls without changing my paradigm around quite a bit

...with method call syntax you'd get the exact same behaviour with

```html
<button on-click="event-name:'someString',{{objectOnScope}}">click meh</button>
```

(The `event` object has been removed from the event handler arguments, but you can use `event` in the method call arguments if nec.) Demo here: http://jsfiddle.net/d140n63j/ Does that alleviate your concerns at all?

**Comment by TehShrike** [comment]
It definitely does.  I'd somehow missed making the connection that I could call `fire` from within templates like that.

**Comment by TehShrike** [comment]
Man, I somehow even missed the `fire` example in the "Option 1: deprecate" section of that other issue!

**Comment by TehShrike** [comment]
It seems like the `bug`+`won-fix` labels would be more appropriate - the docs seem to imply that my use case should work (un-quoted strings are used as proxy event arguments in the docs).

But in light of the probable deprecation of proxy events, I would be surprised if it was worth the trouble of fixing.

**Comment by Rich-Harris** [comment]
Yeah, the docs are ambiguous because it doesn't have an example of a string argument. But I think you're right, this is a wontfix. Will close
