### ISSUE TITLE
0.8 (legacy) is not working in IE8

### ISSUE THREAD

**Issue by michaljerabek** [ractivejs/ractive#2309]
Hi. I don't have a real IE8, but in emulation mode in IE11 (Windows 10) Ractive 0.8 is not working, because it's trying to use `Object.create` (line 23).

**Comment by neersighted** [comment]
This should be solvable with `es5-sham` as a temporary workaround...

**Comment by neersighted** [comment]
With `es5-sham`, this fails for another reason... The `defineProperty` wrapper test the sham'd `Object.defineProperty` and determines that it is fully supported, and thus tries to apply magic setters and getters; which causes the same to throw and error. I'm not sure of a way around this at the moment... Maybe `Object.create` should be added to the legacy file, or maybe we need a way to force the gimped `defineProperty`.

**Comment by martypdx** [comment]
@michaljerabek are you using `ractive-legacy.js`?

**Comment by michaljerabek** [comment]
@martypdx Yes.
