### ISSUE TITLE
Ractive 0.8 Two-Way binding failing.

### ISSUE THREAD

**Issue by ISNIT0** [ractivejs/ractive#2314]
A few times now, I have tried updating a project to Ractive 0.8 as an experiment, but I keep ketting two-way binding errors which I never got previously.

Is there a breaking change I'm missing or would it be worth my investigating?

![image](https://cloud.githubusercontent.com/assets/5173131/11653962/ed76f03c-9d99-11e5-8c27-93e3f5e00522.png)

**Comment by martypdx** [comment]
> Is there a breaking change

Yes, you can't two way bind to child properties of expressions. Instead of:

```
{{#with { Model: Model.TopLevelSections.0, context: context, listPosition: 0 } }}
```

use: 

```
{{#with Model.TopLevelSections.0 as Model, 0 as listPosition }}
```

For the other case, it depends on what the implementation of `getColumns` is, but probably want to use a keypath expression instead: `{{#each columns[name] }}`

**Comment by ISNIT0** [comment]
Okay, Thanks a lot!

**Comment by Rich-Harris** [comment]
0.8 is more vigilant about stuff like this – 0.7 would either ignore potential issues, or behave incorrectly. Usually the message will give instructions on how to fix it. It looks like we're ok to close this issue, shout if otherwise

**Comment by guilhermeaiolfi** [comment]
It seems that most problems are regarding ```twoway="false"```. What if you have two properties in a component and I want the twoway to be applied  for one binding and not the other (to fix those errors)? Shouldn't the option be set somehow by binding and not by component/element? Other frameworks have this flexibility, it could be a helper/function like so:

```html
<Component foo="{{foo}}" bar="{{copy bar}}" /> // reverse of {{mut bar}} from ember
<Component foo="{{foo}}" bar="{{copy(bar)}}" /> // a function would be OK too
```

Or maybe a different delimiter. But it needs to be per element/component.

**Comment by guilhermeaiolfi** [comment]
I went after how vue does it: http://vuejs.org/guide/components.html#Prop_Binding_Types :
```html
<!-- default, one-way-down binding -->
<child :msg="parentMsg"></child>

<!-- explicit two-way binding -->
<child :msg.sync="parentMsg"></child>

<!-- explicit one-time binding -->
<child :msg.once="parentMsg"></child>
```

You can still set validation and settings for your properties like so:

```javascript
Vue.component('example', {
  props: {
    // basic type check (`null` means accept any type)
    propA: Number,
    // a required string
    propB: {
      type: String,
      required: true
    },
    // a number with default value
    propC: {
      type: Number,
      default: 100
    },
    // object/array defaults should be returned from a
    // factory function
    propD: {
      type: Object,
      default: function () {
        return { msg: 'hello' }
      }
    },
    // indicate this prop expects a two-way binding. will
    // raise a warning if binding type does not match.
    propE: {
      twoWay: true
    },
    // custom validator function
    propF: {
      validator: function (value) {
        return value > 10
      }
    },
    // coerce function (new in 1.0.12)
    // cast the value before setting it on the component
    propG: {
      coerce: function (val) {
        return val + '' // cast the value to string
      }
    }
  }
})
```
See ```propE``` definition. That would be a nice addition. What do you think?
