### ISSUE TITLE
Template is renderd in wrong order.

### ISSUE THREAD

**Issue by petterek** [ractivejs/ractive#2315]
This is a really strange bug a found while using the edge version.

    {{#Data}}
        {{#AllItems}}
        <div>
            {{Id}} - <input value='{{Name}}' on-change='invoke(Data.NameChanged,this)'>
            <br /> Use text value <input type='checkbox' checked='{{UseTextValue}}' on-change='invoke(Data.UseTextValueChanged,this)'>
            <br />User can edit <input type='checkbox' checked='{{UserCanEdit}}' on-change='invoke(Data.UserCanEditChanged,this)'>
            <br />
        </div>
        {{/AllItems}}

        {{#Changes}}
        <h3>
            {{name}}
        </h3>
        {{/Changes}}

        {{#if Data.AllItems.length && Data.Changes.length}}<input type='button' value='Save' on-click='invoke(SaveChanges)' />{{/if}}

        {{#Changes}}

        <h1>
            {{name}}
        </h1>
        {{/Changes}}
    {{/Data}}

image when rendering with latest..
![image](https://cloud.githubusercontent.com/assets/181268/11685803/1f012162-9e7c-11e5-9f1b-174380da011f.png)

When renderd in Edge
![image](https://cloud.githubusercontent.com/assets/181268/11685846/7281c6a2-9e7c-11e5-835c-2fc2ed1ded79.png)

The Changes array is changed when I change the text in any textbox or check any of the radios

The template is precompiled using ractify in gulp.

**Comment by fskreuz** [comment]
Before I mark this as a bug, can you provide a demo (jsFiddle would be fine) and also put the demo code in here as well? It's for historical purposes.

**Comment by petterek** [comment]
I shall see what i can do. 
The built template is the same for both versions, but it could be there is some issues with the version of the template.

**Comment by petterek** [comment]
You are right, this boils down to the compiling of the template some how. When I use a string as the template instead of the precompiled one(wich is a v3 template) is works correctly.

**Comment by petterek** [comment]
Maybe you should warn about compiled templates in some way. I will close this for now..

**Comment by fskreuz** [comment]
Ractive actually throws an error if the template mismatches the one expected by the parser. [In this case](http://jsfiddle.net/q96p6tLw/), the latest expects v3, but I changed the `v` to 2 so it throws an error. So I'm not sure what's happening with your template. Might be worth investigating if ractify uses an updated version of Ractive or rcu (the toolkit from which loaders are created from).

```js
new Ractive({
  el: 'body',
  append: true,
  template: {"v":2,"t":[{"t":7,"e":"div","f":["test"]}]}
});
```

**Comment by petterek** [comment]
{"v":3,"t":["﻿",{"t":4,"f":[" ",{"t":4,"f":[{"t":7,"e":"div","f":[{"t":2,"r":"Id"}," - ",{"t":7,"e":"input","a":{"value":[{"t":2,"r":"Name"}]},"v":{"change":{"m":"invoke","a":{"r":["Data.NameChanged","."],"s":"[_0,_1]"}}}},{"t":7,"e":"br"}," Use text value ",{"t":7,"e":"input","a":{"type":"checkbox","checked":[{"t":2,"r":"UseTextValue"}]},"v":{"change":{"m":"invoke","a":{"r":["Data.UseTextValueChanged","."],"s":"[_0,_1]"}}}},{"t":7,"e":"br"},"User can edit ",{"t":7,"e":"input","a":{"type":"checkbox","checked":[{"t":2,"r":"UserCanEdit"}]},"v":{"change":{"m":"invoke","a":{"r":["Data.UserCanEditChanged","."],"s":"[_0,_1]"}}}},{"t":7,"e":"br"}]}],"r":"AllItems"}," ",{"t":4,"f":[{"t":7,"e":"h3","f":[{"t":2,"r":"name"}]}],"r":"Changes"}," ",{"t":4,"f":[{"t":7,"e":"input","a":{"type":"button","value":"Save"},"v":{"click":{"m":"invoke","a":{"r":["SaveChanges"],"s":"[_0]"}}}}],"n":50,"x":{"r":["Data.AllItems.length","Data.Changes.length"],"s":"_0&&_1"}}," ",{"t":4,"f":[{"t":7,"e":"h1","f":[{"t":2,"r":"name"}]}],"r":"Changes"}],"r":"Data"}]}

Don't know if this gives any value but this is how the comiled template look like

**Comment by fskreuz** [comment]
Can you provide sample data too?

**Comment by petterek** [comment]
[{"Name":"Sats","OwnerTypeId":2,"UserCanEdit":false,"UseTextValue":false,"Id":24,"$type$":"2dadfec3-9b33-3906-ac5d-187f299c4570"},{"Name":"Personer","UseTextValue":false,"UserCanEdit":false,"OwnerTypeId":2,"Id":14,"$type$":"2dadfec3-9b33-3906-ac5d-187f299c4570"},{"UseTextValue":false,"Name":"Selgernummer","OwnerTypeId":2,"UserCanEdit":false,"Id":20,"$type$":"2dadfec3-9b33-3906-ac5d-187f299c4570"},{"Id":15,"Name":"IQ","UseTextValue":false,"UserCanEdit":false,"OwnerTypeId":2,"$type$":"2dadfec3-9b33-3906-ac5d-187f299c4570"},{"Name":"T-shirt","OwnerTypeId":2,"UseTextValue":false,"UserCanEdit":false,"Id":16,"$type$":"2dadfec3-9b33-3906-ac5d-187f299c4570"},{"Id":21,"UseTextValue":false,"Name":"test","UserCanEdit":false,"OwnerTypeId":2,"$type$":"2dadfec3-9b33-3906-ac5d-187f299c4570"},{"UseTextValue":false,"Name":"Allergies","Id":22,"UserCanEdit":false,"OwnerTypeId":2,"$type$":"2dadfec3-9b33-3906-ac5d-187f299c4570"}]

**Comment by petterek** [comment]
The Data prefix in the template is because, the data is attached to a another object, before it is sent to ractive
