### ISSUE TITLE
Ractive 0.8 - Change in data, results in component misplacement on DOM

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2317]
Check out this fiddle:
http://jsfiddle.net/6b9jkphv/22/

when the data changes, it causes "test-toolbar" component to be placed underneath the text.
Press buttons "Go to 2" -> "Go to result", or just start pressing the buttons randomly and eventually you will encounter it!

**Comment by evs-chris** [comment]
Now that Travis is finally done, the fiddle now works as expected. Thanks for the report!
