### ISSUE TITLE
empty number inputs empty values returns nothing in get

### ISSUE THREAD

**Issue by AlexandreBernard** [ractivejs/ractive#2318]
We have a number input : 

```
<input type="number" value="{{bid}}" />
```

initial data is : 

```
{ bid: null }
```

when doing ra.get() we get no bid anymore until we add a value to the field.

I guess we would expect null to be returned and the key to be present in data

**Comment by fskreuz** [comment]
What version of Ractive are you using? Are you using tools with it? Build step? Loader?

Because on [latest (0.7.x)](http://jsfiddle.net/baynovwx/1/) and [edge (0.8.x)](http://jsfiddle.net/baynovwx/2/), they work as expected.

**Comment by AlexandreBernard** [comment]
i'm using 0.7.3 but you're right, it returns undefined and i was fooled by the request inspector: it's jQuery ajax that removes undefined values and ractive works the way it is supposed to

if i may add my opinion on this topic, i would expect a null value rather than undefined for a number input. at least null translates into json contrary to undefined

you probably can close this issue
