### ISSUE TITLE
updateCss fails in IE8

### ISSUE THREAD

**Issue by zapodot** [ractivejs/ractive#2320]
Unfortunately, we have some users that is still tied into IE8. With ractive-legacy (0.7.3) the "updateCss" function fails with the following error:

![image](https://cloud.githubusercontent.com/assets/551569/11776398/08e891c0-a247-11e5-8a21-ca62ac27a68b.png)

The line in question is:

```javascript
     node.appendChild(document.createTextNode(content)); // ractive-legacy-0.7.3.js line 12655
```

**Comment by fskreuz** [comment]
Given that `createTextNode` is supported by modern browsers, it only leaves `appendChild` faulty which only happens when `node` isn't what you'd expect it to be.

Can you provide a simple demo (jsFiddle or other) that reproduces the issue?

**Comment by zapodot** [comment]
Thank you for your feedback Joseph!

I will try to reproduce the error.

Sondre
