### ISSUE TITLE
Feature request: image/resource preloading

### ISSUE THREAD

**Issue by matthew-dean** [ractivejs/ractive#2322]
After migrating a wizard from a number of "hidden" panels to a Ractive-based wizard, I noticed that one of the side-effects is that, because Ractive doesn't insert ```<img />``` tags into the DOM, then none of those images are pre-loaded, whereas a hidden panel will still request images. Would it be possible for Ractive to preload image assets (and maybe any CSS / JS tags) in the template by default, so that showing / hiding Ractive panels has the appearance of being instantaneous?

**Comment by martypdx** [comment]
Seems too broad to include globally in the core.  You can roll your own pretty easy:
```js
new Ractive({
    template: `
        <div style='display:none'>
            {{#each src in images}}<img src='{{src}}'>{{/each}}
        </div>
        <!-- rest of template -->
    `,
    onrender(){
        this.set( 'images', this.find('img').map( img => img.src ) );
    }
});
```

**Comment by JonDum** [comment]
Agreed with Marty. You already have full control of how assets are
loaded/preloaded.

**Comment by fskreuz** [comment]
You can still use your hidden-panels approach with Ractive. Instead of using sections to conditionally render components, make them conditionally put a CSS class that makes the step visible instead.

```js
var WizardComponent = Ractive.extend({
  template: `
    <div class="wizard">
      <div class="step {{# step === 1 }}step--visible{{/}}><Component1 /></div>
      <div class="step {{# step === 2}}step--visible{{/}}><Component2 /></div>
      <div class="step {{# step === 3 }}step--visible{{/}}><Component3 /></div>
  `,
  css: `
    .step { display: none }
    .step--visible { display: block }
  `,
  data: {
    step: 1
  }
});
```

`display` is just a simplification. You can use a lot of CSS trickery, especially with `transition`.

**Comment by Rich-Harris** [comment]
I'm inclined to agree that developers should be in control of preloading strategies – too many ways we could end up making unnecessary requests (even to bad URLs) otherwise. Will close this as wontfix.
