### ISSUE TITLE
`{{ foo[0].bar() }}` is a parse error

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#2325]
Via [this SO question](http://stackoverflow.com/questions/34442726/ractivejs-parse-error) – looks like you can't call methods of references with computed properties:

```js
// these both fail
Ractive.parse( '{{foo[0].bar()}}' );
Ractive.parse( '{{foo[0].bar.baz()}}' );
```

Demo: http://jsfiddle.net/shLgn4cv/

**Comment by MartinKolarik** [comment]
Only happens with numbers, these work:
```js
Ractive.parse( '{{foo["0"].bar()}}' );
Ractive.parse( '{{foo[bar + 1].bar.baz()}}' );
```
http://jsfiddle.net/shLgn4cv/1/
