### ISSUE TITLE
Leading and trailing &nbsp; entity not rendered in conditional

### ISSUE THREAD

**Issue by waynebaylor** [ractivejs/ractive#2327]
Leading and trailing `&nbsp;` entities on their own line are not rendered in conditional mustaches. If there is other content on the line with the entity then it is rendered correctly.

Test case (uses edge, but also broken in 0.7.3):
http://jsfiddle.net/ve4y4Lmr/1/

**Comment by martypdx** [comment]
Thanks for the test case!
