### ISSUE TITLE
fails to compute attribute derived from component selection

### ISSUE THREAD

**Issue by lazylester** [ractivejs/ractive#2328]
ref: this jsfiddle https://jsfiddle.net/cmgjz9z4/1/

Previously posted on StackOverflow (http://stackoverflow.com/questions/34385694/fails-to-compute-attribute-derived-from-components-collection), where a respondent suggested this might be a bug. So re-posted here.

given the following coffeescript:
````
Member = Ractive.extend
  template : "<p>{{name}} {{age}}</p>"
  computed :
    age : ->
      parseInt(@get('age_in_days')/365)

new Ractive
  el : "#family"
  template : "{{#members}}<member name='{{name}}' age_in_days='{{age_in_days}}'/>{{/members}}{{youngest}}"
  components :
    member : Member
  data:
    members : [
      {name : 'Fred', age_in_days: 8000},
      {name : 'Barney', age_in_days: 10000},
      {name : 'Wilma', age_in_days: 7000}
      ]
  computed :
    all_ages : ->
      _(@findAllComponents('member')).map (member)->
        member.get('age')
    youngest : ->
      _(@get('all_ages')).min()
````

An error is thrown ("TypeError: Cannot read property 'findAllComponents' of undefined") from deep within the Ractive code. And the computed attributes "all_ages" and "youngest" are not computed or rendered.
I believe this to be a legitimate scenario consistent with the docs. So I'm assuming that the error is the symptom of a bug.

**Comment by martypdx** [comment]
Computed properties are as part of data initialization which happens _prior_ to virtual dom creation or rendering, so there are no components to find.

There's not really a great way in Ractive to use a computed property in a component as a data generator. 

You could delay the getting of the components using something like this: https://jsfiddle.net/cmgjz9z4/3/

**Comment by lazylester** [comment]
Ah, I see, that clarifies a lot of issues I've had with computed properties. Thanks Marty!
