### ISSUE TITLE
Add more control over the data lookup process in components

### ISSUE THREAD

**Issue by wmcmurray** [ractivejs/ractive#2332]
I would like to have a way of limiting the deepness of the search for data outside a component. I know there is an [`isolated` param](http://docs.ractivejs.org/latest/options#isolated) that prevent the lookup outside the component, but what I want is to tell my component he can look outside **but** not farther than one level of deepness.

**My use case :**
I have a blog article page. At the bottom of the page, I have a listing of related articles displayed in a grid. Each items of this grid is a component displayed in a loop :

```
{{#each relatedArticles}}
    <articleBox></articleBox>
{{/each}}
```

If one of those related articles doesn't have an `image` property by exemple, the component will use the image of the current article in the page. To prevent this I could set the `isolated` param to `true`, but I'll have to update my code like this :

```
{{#each relatedArticles}}
    <articleBox image={{image}} title={{title}} content={{content}}></articleBox>
{{/each}}
```

etc. Using my component now become annoying because I have to define every attributes, every time, everywhere.

**Brainstorm :**

Maybe there is an other way of solving this beside a "maxDeepness" param, like a special mustache syntax stopping the context lookup process ?

```
{{#isolated}}
    {{#each relatedArticles}}
        <articleBox></articleBox>
    {{/each}}
{{/isolated}}
```

Could be useful in more situations.

**Comment by evs-chris** [comment]
Usually with isolation, you're only really interested in the one (or so) thing, so you just pass in the main object e.g. `{{#each relatedArticles}}<articleBox article="{{.}}" />{{/each}}`. Then your component can be isolated and just use `{{article.title}}`, `{{article.content}}`, etc.

For something slightly cleaner, how about #2174? Then you could do `{{#each relatedArticles}}<articleBox this="{{.}}" />{{/each}}` along with isolation. Then everything in your component template would be `{{.title}}`, `{{.content}}`, etc. You can also leave them ambiguous (`{{title}}`) if you like.

**Comment by wmcmurray** [comment]
I wanted to avoid your first exemple because (in my opinion) it's annoying and add a little bit of dirt in my components.

But your PR do what I want and I like it !! :wink: The only downside is that it can't isolate a whole part of an app like `{{#isolated}}...{{/isolated}}` would do... But I never needed that anyway and I can't think of a situation that couldn't be solved otherwise...

...I was thinking of a page where you want all of it's content to be isolated from the global layout of the website, but in that case I would probably just do a page component that is isolated.

**Comment by martypdx** [comment]
Can you move the `isolated: true` to the parent component? If that's the intended boundary, wouldn't that make more sense?

**Comment by dagnelies** [comment]
> If one of those related articles doesn't have an image property by exemple, the component will use the image of the current article in the page. To prevent this I could set the isolated param to true, but I'll have to update my code like this...

Isn't it sufficient to just use `{{.image}}` instead of `{{image}}` in your component/partial? ...that way, it'll only look at the "image" property at this level.

**Comment by fskreuz** [comment]
If I get what this is all about, the OP wants selective isolation? Here's some ideas:

[Why not rename `image` to something specific](https://jsfiddle.net/y46fssyh/1/)? That way, when it doesn't exist lower down the data, it won't look for `image` in the ancestor (or vice versa). That way, it doesn't require your component to be isolated on purpose.

```js
var ArticleBox = Ractive.extend({
	template: `
  	<div class="article-box">
  		<h1>{{title}}</h1>
    	<div>{{image}}</div>
    	<div>{{content}}</div>
    </div>
  `,
  css: `
  	.article-box{
    	margin: 1rem;
    }
  `
});
var ArticleList = Ractive.extend({
	data() {
  	return {
      headerImage: 'parent image',
      relatedArticles: [{
        title: 'article with image 1',
        image: 'child image 1',
        content: 'sample content 1'
      },{
        title: 'article without image 2',
        content: 'sample content 2'
      },{
        title: 'article with image 3',
        image: 'child image 3',
        content: 'sample content 3'
      }]
    }
  },
	template: `
  	{{# relatedArticles }}
  	  	<ArticleBox />
    {{/}}
  `,
  components: {
  	ArticleBox
  },
});

new ArticleList({el:'body'});
```

Now if you do have a recursive structure, where the parent is the same structure as the child (think a folder/file tree), then what you could do is to [create a component that contains the same data as the child, but with blanks](https://jsfiddle.net/y46fssyh/3/). Technically, we're making the resolver collide with an intermediate component on purpose instead of going up the parent. 

In the following example, the semantics are almost the same as the proposal. I just put it outside the loop, to avoid Ractive creating the isolator component for each item. The resolver will collide with it either way.

```js
var ArticleBox = Ractive.extend({
	template: `
  	<div class="article-box">
  		<h1>{{title}}</h1>
    	<div>{{image}}</div>
    	<div>{{content}}</div>
    </div>
  `,
  css: `
  	.article-box{
    	margin: 1rem;
    }
  `
});

var ArticleIsolator = Ractive.extend({
  data(){
  	return {
      title: '',
      image: '',
      content: ''
    } 
  },
  template: `
  	{{> content }}
  `
})

var ArticleList = Ractive.extend({
	data() {
  	return {
      image: 'parent image',
      relatedArticles: [{
        title: 'article with image 1',
        image: 'child image 1',
        content: 'sample content 1'
      },{
        title: 'article without image 2',
        content: 'sample content 2'
      },{
        title: 'article with image 3',
        image: 'child image 3',
        content: 'sample content 3'
      }]
    }
  },
	template: `
    {{image}}
    <ArticleIsolator>
      {{# relatedArticles }}
          <ArticleBox />
      {{/}}
    </ArticleIsolator>
  `,
  components: {
  	ArticleBox,
    ArticleIsolator
  },
});

new ArticleList({el:'body'});
```

**Comment by wmcmurray** [comment]
@martypdx The parent component in my case is my page component, which contains my current article AND the list of related articles, so isolating the page component wont fix the conflict between the current article and the related articles.

@dagnelies Oh ! If using `{{.image}}` in partials doesn't behave the same way as in components, maybe that's an **inconsistency problem that should be fixed ?** :warning: 

@fskreuz I could rename my properties but the current article and the related articles properties are based on the same article model. If would be confusing to rename those properties to fix isolation problems.

But I like your `ArticleIsolator` idea ! I would just rename it to be more reusable like this :

```javascript
var Isolator = Ractive.extend({
  isolated: true,
  template: `{{> content }}`
});

Ractive.components.isolator = Isolator
```

And then use it like this :

```html
<isolator relatedArticles={{relatedArticles}}>
    {{#each relatedArticles}}
        <articleBox></articleBox>
    {{/each}}
</isolator>
```

Which ends up being what @martypdx suggested :wink: ,
which invalidate the need for an `#isolated` syntax,
which do what I want ! :+1:

**Comment by evs-chris** [comment]
It looks like this found a reasonably satisfactory resolution, so I'm going to close it.
