### ISSUE TITLE
on components, 'set' works but 'reset' does not

### ISSUE THREAD

**Issue by lazylester** [ractivejs/ractive#2334]
(ref this jsfiddle https://jsfiddle.net/239f5op9/)
same behaviour with 0.7.3 and 0.8

``` javascript
Widget = Ractive.extend({})

var ractive = new Ractive({ 
    template: "{{#colors}}<widget color='{{color}}' />{{/colors}}",
    data: { colors: [{color:'red'}]} ,
    components : {widget : Widget}
})

function logData(){
    console.log(JSON.stringify(ractive.findComponent('widget').get()))
}

logData()
// {"color":"red"} as expected

ractive.findComponent('widget').reset({color:'chartreuse'})

logData()
// {"color":"red"} why did reset have no effect?

ractive.findComponent('widget').set({color:'indigo'})

logData()
// {"color":"indigo"} set works as hoped
```

**Comment by fskreuz** [comment]
Not entirely sure what's going on, but here's a head start. Something to do with `values` and `mappings` being different. The reset did happen, but somehow, `get` reads from `mappings`.

![image](https://cloud.githubusercontent.com/assets/1582932/12190435/7d6ade88-b596-11e5-92e6-e7668250ae55.png)

**Comment by martypdx** [comment]
It's not a bug, it's the expected behavior. Data passed into components always trumps default data.

Using `reset` is like starting over on  data initialization. So 

```js
ractive.findComponent('widget').reset({color:'chartreuse'})
```

is the the same as running:

```js
Widget = Ractive.extend({
    data: {
        color: 'chartreuse'
    }
});

var ractive = new Ractive({ 
    template: "{{#colors}}<widget color='{{color}}' />{{/colors}}",
    data: { colors: [{color:'red'}]} ,
    components : {widget : Widget}
})
```

In which case the color would be `red`, not `chartreuse`.

**Comment by fskreuz** [comment]
Ahh. I see. I was also under the impression that `reset` was like erase + `set`. Maybe better docs tag I guess?

**Comment by lazylester** [comment]
thank you both. Yes, docs tag seems appropriate.

**Comment by lazylester** [comment]
Thought about this some more...
Surely the data passed as an argument to the `reset` method constitutes "passed-in" data, and should therefore override the default data?
Yes, data is passed-in to the component both from the parent and also the reset, but does it really make sense to ignore the data passed-in with the reset? Intended behaviour perhaps, but expected? Not so much.

**Comment by martypdx** [comment]
> Surely the data passed as an argument to the reset method constitutes "passed-in" data, and should therefore override the default data?

No, then how would it be any different than `set`?

> does it really make sense to ignore the data passed-in with the reset?

Yes, because `reset` "resets" data initialization, that's what it does.

> Intended behaviour perhaps, but expected? Not so much.

What did you expect `reset` to do that's _different than `set`_?

**Comment by lazylester** [comment]
My expectation was based on the docs:
````javascript
ractive = new Ractive({
  // ...,
  data: { foo: 1 }
});

ractive.set({ bar: 2 });
console.log( ractive.get() ); // { foo: 1, bar: 2 }

ractive.reset({ bar: 2 });
console.log( ractive.get() ); // { bar: 2 }
````
So I understood that `reset` would configure the component variables exactly as the passed-in arguments (= "resets data initialization" as you said), whereas `set` would merge the passed-in arguments with any pre-existing values, with passed-in args overwriting. As @fskreuz mentioned, the docs suggest that reset is like 'erase'+`set`, isn't that what you mean when you say that it resets data initialization?
Clearly the behaviour is what you intended, and I'm just not understanding it.
Thanks for your contributions to ractive, Marty.
Les

**Comment by martypdx** [comment]
Ah, now I follow how you got to that conclusion, thanks for bringing it up. I've tagged this issue in a new docs issue, so should be easy to use this thread to write better docs for `reset`

**Comment by heavyk** [comment]
I had the same misconception as @lazylester too. it introduced some weird bugs until I figured out what was going on.
