### ISSUE TITLE
Isolated no longer isolated in 0.8?

### ISSUE THREAD

**Issue by skeptic35** [ractivejs/ractive#2335]
Either a breaking change or a bug. The following code produces no console output in 0.7.3 but does so in 0.8:
```javascript
var fComponent = Ractive.extend({
  "isolated": true,
  "oninit": function()
  {
    if (true === this.get("model.not_mine"))
    {
      console.log("model.not_mine is true");
    }
  }
});

new Ractive({
  "template": "<c-test />",
  "el": "#main",
  "components": {"c-test": fComponent},
  "data": function()
  {
    return {
      "model": {"not_mine": true}
    };
  }
});
```

P.S. I would have created a jsfiddle but for some reason I can't chose RactiveJS edge as a library there anymore.

**Comment by skeptic35** [comment]
Fiddles for convenience - no idea why this didn't work earlier:
0.8 edge: https://jsfiddle.net/03gyenjs
0.7.3: https://jsfiddle.net/03gyenjs/1/

**Comment by evs-chris** [comment]
Whoops! Fixed. Thanks for the report.

**Comment by skeptic35** [comment]
Great - Thanks!
