### ISSUE TITLE
Using proxies to implement magic mode.

### ISSUE THREAD

**Issue by petterek** [ractivejs/ractive#2337]
http://www.sitepoint.com/preparing-ecmascript-6-proxies/

As of now, my understanding is that if you use magicMode ratctive transforms the fields of an object into properties, and add the 'databinding callbacks' inside the properies.  

Would it be more appropriate to do this with proxies instead? Seems less intrucive than current solution? Just a thougt..

Proxies is not widley supported yet so probably a future feature :)

**Comment by martypdx** [comment]
I think proxies and wrappers are better direction than hacking the props of the supplied object. But the main issues is the disconnect between the supplied object and the wrapped object.

If I have:

```js
var myObject = getMyObject();

new Ractive({
    data: { obj: myObject },
    oninit () {
        // how do I get my proxied object so I can write:
        myObject.foo = 'bar'

        // It won't work with current code if I write:
        this.obj = this.get('obj')
        // because ractive currently returns the "real" object from API methods, not the adaptor.
    }
});
```

Magic mode currently uses the adaptor interface, but it's really different in that it's a way to proxy object calls to the ractive api so it knows about the changes. Versus something like the backbone adaptor that sits between the data and ractive's understanding of the model.

So we need a good api way of getting to the proxied object. Perhaps it's as simple as:

```js

this.obj =  ractive.proxy('obj') // now I have an on demand proxy!

```

**Comment by petterek** [comment]
What if we 'prepare' our object for ractive by doing something like this? 

    var myObject = Ractive.databindingProxy(myData);

    new Ractive({
        data: myObject 
    });

Then you have to take an active decision to op-in for 'magic-mode', this will also probably be easier to implement even without the support of proxies in ES7 or whenever it will appeare in browsers. 
In principal proxies could be used to support a wide aspect of functionality, so it might be an idea to offer a range of proxies doing different things. 
Just a top of my head example... 

    var myObject = Ractive.Proxy.twoWay(Ractive.Proxy.logCalls(Ractive.Proxy.timing(myData)));

    new Ractive({
        data: myObject 
    });

**Comment by martypdx** [comment]
@petterek Only issue is child objects, but that could be part of the Proxy options (probably default true).

**Comment by petterek** [comment]
yes, and also sub arrays might cuse issues. Could probably wrap push,pop,slice,splice e.q.

**Comment by petterek** [comment]
What is your "basic" idea for implementing this @evs-chris 
Just interesting.. 
Should it be some kind of
` var wrapped = new MagicProxie(myObj)`

then we could enumerate over the fields in the myObj, and wrap it with the ractive.get , ractive.set 

Should be doable for one level objects, but could be more job for complex objects.

**Comment by evs-chris** [comment]
Figuring out #2512 should make handling nested objects less painful. I'm thinking that perhaps the promise returned from `set` should effectively return the result of `get` with the same keypath(s). A plain `r.set('foo', foo /* will be magicked */); foo = r.get('foo');` would also work. Either way, you would need to get the proxied object back from your ractive instance for further use so that changes are observable. Further, to avoid bizarro issues with the same object being used in multiple keypaths/across instances, the proxified magic adaptor should probably detect that the object is already wrapped and simply set up a cross-instance `link` instead of allowing it to exist pseudo-independently in two or more places.

**Comment by evs-chris** [comment]
Punting to #2512
