### ISSUE TITLE
Teardown invoked before transition finishes

### ISSUE THREAD

**Issue by pqvst** [ractivejs/ractive#2339]
I recently started using transitions. I have an element which contains a component. However, I noticed that teardown on the component occurs before the transition finishes (which doesn't look very good).

```
<div intro-outro="slide">
    <Component />
</div>
```

https://twitter.com/pqvst/status/686502421032472576

**Comment by fskreuz** [comment]
You might want to post a reproducible demo so everyone can inspect what's happening.

**Comment by pqvst** [comment]
@fskreuz Sure thing.

Github repo:
https://github.com/pqvst/ractive-transition-teardown-bug

Live demo:
https://rawgit.com/pqvst/ractive-transition-teardown-bug/master/demo.html

**Comment by martypdx** [comment]
Confirmed in both `0.7.3` and `edge`.

Seems like a bug, any disagreement?

**Comment by evs-chris** [comment]
Ehhhh. I don't think it's a bug so much as maybe a missing lifecycle event. Perhaps there should be a `torndown`?

The most convenient way I see to resolve this situation is to expose the current batch promise on runloop (`promise() { return (batch || {}).promise || Promise.resolve(true); }`) and then fire the hook off of `runloop.promise().then(() => youGetTheIdea())`. Does that sound reasonable?

**Comment by pqvst** [comment]
What about adding an event called ``destroy`` rather than ``torndown``, so that ``teardown`` is invoked as the teardown process begins (i.e. before any transitions complete), and ``destroy`` is invoked just before the component is actually removed from the DOM? I feel that such an event is missing in any case.

    teardown -> transition begins -> transition ends -> destroy -> removed from DOM
