### ISSUE TITLE
If defineProperty exists, setters and getters are used

### ISSUE THREAD

**Issue by neersighted** [ractivejs/ractive#2343]
If a `object.defineProperty` method exists, and succeeds on an object, Ractive assumes that setters and getters are supported and attempts to use them. Polyfills such as [IE8](https://github.com/WebReflection/ie8) provide this method, but throw an error when attempting to use setters and getters. The case where Object.defineProperty supports objects but not setters and getters should be handled.

**Comment by Madgvox** [comment]
The Ractive-legacy version provides its own polyfills. Would it be possible to use those instead?

**Comment by neersighted** [comment]
I am using Ractive-legacy, however, it falls back to native if they exist (or are set by a prior polyfill). I have to load ractive-legacy before polyfills to work around this. It works at the moment, but it would be great if the underlying cause could be fixed (maybe just fall back to legacy if getters/setters are not supported)?

**Comment by evs-chris** [comment]
The detection now checks for getter and setter support before deciding whether or not properties are fully supported.
