### ISSUE TITLE
return false to cancel events in method calls not working.

### ISSUE THREAD

**Issue by magicdawn** [ractivejs/ractive#2346]
Here is the document shows: http://docs.ractivejs.org/latest/method-calls

> Cancelling events
As with proxy events, you can cancel a DOM event by returning false from your event handler. Ractive will then call preventDefault() and stopPropagation() on the original DOM event. You can also call any methods on the original event by having it passed to your handler or accessing it using this.event.original.

It's saying case like https://jsfiddle.net/2eqqee1t/1/
If I `return false` in `handleClick`, Ractive will help us to `preventDefault` & `stopPropagation`, but it's not working in the jsfiddle case: click on `#btn` will alert-btn & alert-document

I know I have other way like `this.event.original.stopPropagation`, but the document & the real behavior get users confused.

**Comment by Madgvox** [comment]
This does appear to be a bug in 0.7.3, however in 0.8-edge it looks like this behavior [has been fixed](http://jsfiddle.net/2eqqee1t/2/), so I'm going to close this. Since 0.7 isn't really being updated anymore, please use the workaround until 0.8 is released. Thanks!
