### ISSUE TITLE
Decorators of same type being initiated before the old one is torn down

### ISSUE THREAD

**Issue by EduardJS** [ractivejs/ractive#2350]
Ok, so what happens is that I have a decorator using `owlCarousel`, on two different templates ( a user's profile and my own settings tab ).

When switching from a `user's profile` to my `settings tab` the decorator in my settings gets initiated but then immediately `torn down` since the `teardown` method from the `decorator` in the `user's profile` is being triggered after and not before it so I end up with the `owlCarousel` from the settings which I just rendered being destroyed rather than having to destroy the one in the user's profile tab.

![image](https://cloud.githubusercontent.com/assets/7712869/12448303/67a2c668-bf75-11e5-9240-bfa9ba2a565f.png)

Update: I'm changing the views by changing the value of a `view` variable which is a dynamic partial. I guess that's what's causing the problem, since I'm only having:

```html
<div class="wrapper">{{ > view }}</div>
```

And then:

```javascript
renderView: function( e, template ) {
    content.set( 'view', templates )
}
```

Made a `SSCCE` here [https://jsfiddle.net/05sq8o2k/6/](https://jsfiddle.net/05sq8o2k/6/)

Make sure to tap `load unsafe scripts` if you get the warning because `ractivejs` cdn does not support `https` as far as I can see so jsfiddle kind of disagrees with it now.

**Comment by sabob** [comment]
Hi Eduard,

This seems fixed in the next version of Ractive. Update your fiddle to use: https://cdn.ractivejs.org/edge/ractive.min.js

Kind regards

Bob

**Comment by EduardJS** [comment]
Thanks !
