### ISSUE TITLE
Edge version multiplying elements

### ISSUE THREAD

**Issue by EduardJS** [ractivejs/ractive#2352]
https://jsfiddle.net/d8svxcd1/5/

Make sure to run unsafe scripts as edge version is not delivered via https. Hit disable / enable multiple times and form will multiply.

**Comment by fskreuz** [comment]
Simplified case:

```js
new Ractive({
  el: 'body',
  data: {
    form: true
  },
  template: `
    <button type="button" on-click="toggle('form')">{{ form ? 'disable' : 'enable' }}</button>
    {{# form }}
      <form on-submit="SubmitSomething">
        <input type="text" value="{{input}}" />
        <input type="submit" value="submit" />
      </form>
    {{/}}
  `,
});
```
 
Ok on latest: http://jsfiddle.net/d8svxcd1/9/
Breaks on edge: http://jsfiddle.net/d8svxcd1/8/
