### ISSUE TITLE
Question: computed values within array

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2355]
Hi,

I got somewhat of a silly question, but I thought I'd ask nonetheless.

**Intro**

Currently, my web page displays a list like this:

| User   | Stuff                              | 
| --------|-------------------------------|
| UserA | computed infos from A | 
| UserB | computed infos from B | 
| UserC | computed infos from C | 

Where the left part is ``{{.username}}`` and the right part is a function computing something based on the user's data, like ``{{getInfos(.)}}``.

**The "annoyance"**

In order to work, this `getInfos` is a function at the root of `data`. Since I'm also regularly fetching and sending this same `data` remotely, I always have to "remove" or "add" this `getInfos` function to the data. Which is kind of annoying.

I guess there is no way to move this `getInfos` into `computed` properties, right? I mean, it would require either an argument, or be able to map a keypath within an array. Which is, as far as I know, not possible. Right?

The other possibility is to move every data item into a `real_data` prefix for example. It's OK, yet it doesn't feel as comfortable.

**The question**

Just in case I missed it: do you have a more comfortable way to compute something based on the data without altering the `data` object itself?

*Extra note: moving it in a component isn't practical either because it also requires data outside the user itself.*

**Comment by dagnelies** [comment]
Hmmm ...this is kind of a dupe of #1583. Feel free to close it or enlighten me.

**Comment by Madgvox** [comment]
I don't understand the view that having the fetched data not in the root feels uncomfortable. For me, having all my data at the root is what's uncomfortable! You lose the ability to have non data related attributes in your `data`, unless you do the weird object shuffle you're referring to in your post.

**Comment by evs-chris** [comment]
I typically use `Ractive.defaults.data` for stuff that needs to be available everywhere like filters. That combined with putting the data you're setting as a child of the root will leave `ractive.set(`${newDataKey}`, newData)` to not touch the filters and friends. The filters are also available in components or anywhere a new Ractive instance is created.

I've also had similar situations where I mod the data as part of the encapsulated fetching process, though if you're also sending the whole thing (`ractive.get()`) out later I suppose that does probably do more harm than good.

@martypdx's state PR #2345 looks like it would make the `@ractive` stuff accessible enough to cover this case nicely too.

**Comment by evs-chris** [comment]
Looking at it, you could move `getInfos` to a computed property that just returns the function. If your transport back uses JSON, then the function would be stripped out automatically.

```js
new Ractive({
  el: '#somewhere',
  template: '... getInfos(...) ...', // should pull the fn from computed and call it
  data: { to: 'be replaced later' },
  computed: {
    getInfos(arrrrg) { return  do.stuffWith(arrrrg) }
  },
  shipData() {
    send(JSON.stringify(this.get()));
   }
});
```

**Comment by martypdx** [comment]
> I guess there is no way to move this getInfos into computed properties, right? I mean, it would require either an argument, or be able to map a keypath within an array. Which is, as far as I know, not possible. Right?

At some point, it would be nice to add stuff like:

```js
new Ractive({
    data: { users: users },
    computed: {
        'users.*.isAdmin' ( context ) {
            const otherStuff = this.get( 'otherStuff' );
            return context.foo && otherStuff.bar;
        }
    }
});
```

> I typically use Ractive.defaults.data for stuff that needs to be available everywhere like filters.

I also use `Ractive.prototype` (same as `Ractive.defaults`) for ubiquitous functions and read-only data. Just be aware if you need to sync the data, it needs to go on the root instance, not the prototype.

While as a library, we want to make using `data` as a single object doable, it is also meant to support a registry/hash model across top-level keys and if you have multiple data "domains" it necessitates doing this.

However, as @evs-chris mentioned, I've got a PR to allow treating things like functions as "state" separate from "data". In your case (as best I can tell), it would like like:

```js
new Ractive({
    template: `{{.username}} {{@getInfo(.)}}`,
    data: user,
    getInfo () {
        //return "info"
    }
});
```

**Comment by dagnelies** [comment]
Many thanks for all your tips, as usual, great support! Especially for you @evs-chris, great tips, I'll do exactly that. Thanks.
