### ISSUE TITLE
Wildcard observers not working in components, AGAIN?

### ISSUE THREAD

**Issue by dylanbaxter** [ractivejs/ractive#2357]
Hi folks,
This issue seems to keep cropping up:
- 0.7.3 Pattern observers not working in components for values mapped to parent data model #1978
- Observers not working on child components with data passed from parent (see fiddle) #2233
- fix root \* pattern observers on mapped data (#1978) #2296

Maybe its fixed and I'm just doing something wrong. Any help would be most appreciated!
JSFiddle: https://jsfiddle.net/92ces3dc/1/

Thank you all for your hard work and valuable assistance!
Dylan

**Comment by martypdx** [comment]
@dylanbaxter from your fiddle it looks like your using `latest` which is `0.7.3`. PR #2296 was made against `0.8` edge.

I was able to fork and use `http` on this fiddle: http://jsfiddle.net/zwweapmt/. Let me know if that works for you.

**Comment by martypdx** [comment]
btw - we also added a `strict: true` option that prevents firing observers on strict equality. So given this code in your example:

```js
   		// This observer is always triggered
		'groups': function (newValue, oldValue, keypath)
```

you could have it __not__ trigger if `newValue === oldValue` by passing in `, { init: false, strict: true }` in the options.

**Comment by Madgvox** [comment]
Oops, I forgot to check the version of ractive on the fiddle :disappointed:.

**Comment by martypdx** [comment]
@dylanbaxter looks likes this works with edge, can you confirm?

**Comment by dylanbaxter** [comment]
Hey folks,
Shame on me, I didn't know there was such a thing as "edge". I simply used what I thought was the most stable version available (and shown in the docs). Frustrated at another failed foray into whiz-bang JS frameworks, I handed the project off to someone who could bring themselves to subvert most of the Ractive magic and use plain 'ole event handlers and manual DOM updates. It felt really dirty but they needed the app working in production ASAP and I was holding up the show. Sorry, I cannot confirm this without digging up some old commits and bad memories.
Best of luck, and thank you again for all of your hard work and assistance!

**Comment by fskreuz** [comment]
> I didn't know there was such a thing as "edge"

"latest"/"stable" is 0.7 (which is what you see on the site). "edge" is well... the bleeding edge, and is always the name for the upcoming release when it's not yet released. Every new merged PR affects edge. So while it may get the bugs fixed, it may cause other parts to fail. Your mileage may vary.

> I handed the project off to someone who could bring themselves to subvert most of the Ractive magic and use plain 'ole event handlers and manual DOM updates.

You might also want to share with us how you use Ractive. That way, we gain insight on what paradigm you use it with so we can accommodate. :+1: 

> Best of luck, and thank you again for all of your hard work and assistance!

Bug reports are always welcome. In fact, help in any form is always welcome. :smile:

**Comment by mertemin** [comment]
I am experiencing similar issues with pattern observers. See the following examples:
Example with 0.8.0-edge: [http://jsfiddle.net/0mdjdq4u/5/](http://jsfiddle.net/0mdjdq4u/5/)
Example with 0.7.3: [http://jsfiddle.net/0mdjdq4u/6/](http://jsfiddle.net/0mdjdq4u/6/)

**Comment by evs-chris** [comment]
I can see where it would definitely be useful to get the object as it existed before the change. Does an option to deep clone from an observer sound reasonable e.g. `ractive.observe('someKey', { clone: true })`? I also like `deep` and `cloneDeep` (lodash) as option names, but `clone` seems to fit best.

Something else I deal with pretty often is checking to see if a value has actually changed from its initial state - to see if it's dirty and thus needs to be saved to a backing store. I was thinking that beeing able to freeze an observer would be pretty handy, such that it would always emit its frozen (cloned) value as the old value. I would propose:
```js
ractive.set('key', { foo: 'yep' });
const observer = ractive.observe('someKey', (...) => ..., { freeze: true }); // observer has a frozen old value of { foo: 'yep' }
ractive.set('key', { foo: 'nope' }); // old value handed to observer is cloned { foo: 'yep' }
ractive.set('key', { foo: 'maybe' }); // old value is still cloned { foo: 'yep' }
observer.freeze(); // cloned value becomes { foo: 'maybe' }
ractive.set('key', { foo: 'yep' }); // old value is freshly cloned { foo: 'maybe' }
observer.reset(); // equivalent to ractive.set('key', { foo: 'maybe' });
observer.unfreeze(); // revert to tracking changes as before
```
This could be applied to pattern observers as well.

**Comment by martypdx** [comment]
@evs-chris that seems pretty complicated. What would the api needed to _support_ doing that from user land? Couldn't you do the same thing observing the props rather than the parent object:

```js
var initialProps = Object.create(null);

this.observe('key.*', ( val, old, keypath, property ) => {
    var initialVal = initialProps[property];

    if (!initialVal || shouldFreeze() ) {
        initialProps[property] = val;
        return;
    }

    if ( shouldReset() ) {
        this.set( `key.${property}`, initialProps[property] );
    } 

    // ...
});
```

BTW - If anyone missed it, `0.8` added a `{ strict: true }` option so that you can write:

```js
this.observer( 'obj', obj => {
    // ...
}, { strict: true } );
```

And it will *only* fire when `obj is actually set, not prop changes.

The other easy option I've been meaning to PR is a `{ empty: false }` to prevent observers firing when value is `null` or `undefined`. It would turn boilerplate like:

```js
this.observer( 'obj', obj => {
    if ( !obj ) return;
    // ...
} );
```

into:

```js
this.observer( 'obj', obj => {
    // ...
}, { empty: false } );
```

**Comment by evs-chris** [comment]
Gonna forward this to the newer #2833
