### ISSUE TITLE
Debug information should be more clear

### ISSUE THREAD

**Issue by kolipka** [ractivejs/ractive#2358]
I am trying to use Ractive to create bit more advanced app than todo to learn about web development. I try to make component and receive following error:

```
TypeError: Argument 1 of Node.appendChild is not an object.
Fragment$render/<()
 main.js:15933
forEach()
 self-hosted:211
Fragment$render()
 main.js:15932
Element$render()
 main.js:12370
Fragment$render()
 main.js:15928
Ractive$render()
 main.js:3392
Component$render()
 main.js:15615
Fragment$render()
 main.js:15928
Element$render()
 main.js:12370
Fragment$render/<()
 main.js:15933
forEach()
 self-hosted:211
Fragment$render()
 main.js:15932
Element$render()
 main.js:12370
Fragment$render/<()
 main.js:15933
forEach()
 self-hosted:211
Fragment$render()
 main.js:15932
Ractive$render()
 main.js:3392
initialiseRactiveInstance()
 main.js:15203
Ractive()
 main.js:16680
<anonimowa>
 main.js:103
__webpack_require__()
 main.js:20
<anonimowa>
 main.js:40
```

The cause is simple: I put function with name "render" instead of "onrender'. This actually happens a lot, I do something wrong and receive something that does not help at all. Would be nice to have it more descriptive. Thanks :)

**Comment by fskreuz** [comment]
Can you include the related code to reproduce the issue? That way, we know the context of the error.

**Comment by kolipka** [comment]
Here you go. Just change render to onrender and it will work.

	const template = `<div><b>Toolbox</b><br/>
	<canvas class="wave-canvas"/> <div>...scroller...</div></div>`;

	const Waveform = Ractive.extend({
	  isolated: true,
	  template,
	  oninit() {
	  },
	  render() {
	  },
	  data: {
		lblPlay: 'Play'
	  }
	});
