### ISSUE TITLE
Dynamically create parent -> children relationship between two components

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#2361]
In Ractive we can do something like this.

App’s template:

```
<h1>My app</h1><SubComponent/>
```

And generally have `SubComponent`’s template access data from `App`.

However, as far as I know, there is no way to have the same behaviour without mentioning `SubComponent` in the template.

Something like the following*

```
const App = new Ractive({el: ‘#myapp’, …………});
const SubComponent = Ractive.extend({ append: true, ………… });
const example = new SubComponent()
example.render(App.el)
```

but, with `example`’s template being able to access `App`’s data, maybe also giving `App` the chance to find it by using `App.findComponent()`.

What I’m trying to do, is having unpredictable (= I can’t include them inside templates by default) nested components.
## 

*I know that it can't possibly work like this, but hopefully you'll get the idea
## 

I originally created this as a [question on StackOverflow](http://stackoverflow.com/questions/35009565/adding-components-to-existing-ractive-instance), but it probably makes more sense to discuss about it here, because from what I understand, this feature is currently not implemented in Ractive.

**Comment by giovannipiller** [comment]
The following is a workaround to my original problem. I'm leaving it here as it might help other people.

You can include a component dynamically (= without knowing its name beforehand) by using [a solution like this](http://stackoverflow.com/questions/31075341/how-to-create-ractives-subcomponents-dynamically-and-change-them-programmatical).

Not the same as setting up a relationship between two standalone instances together, but it's close enough for my needs.

**Comment by martypdx** [comment]
@giovannipiller I've had success moving components after they have been rendered, for example a popup component. Considering you want the strong binding relationship between parent/child, but don't seem to want the component to live in-line, would that be a helpful solution?

Or was it just about dynamically specifying _which_ component to render and the dom "space" is well known in relation to the parent?

**Comment by kenvunz** [comment]
@martypdx, if you don't mind, are you able to share your workaround?

**Comment by evs-chris** [comment]
In the 0.9 alphas, there is support for embedding foreign instances at an anchor point.
