### ISSUE TITLE
Component CSS only defined when using extend

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2365]
```js
new Ractive({
  el: 'body',
  append: true,
  template: `
  	<div>Red Hello World</div>
  `,
  css: `
  	div{
    	color: red
    }
  `
});

let BlueComponent = Ractive.extend({
  el: 'body',
  append: true,
  template: `
  	<div>Blue Hello World</div>
  `,
  css: `
  	div{
    	color: blue
    }
  `
});

new BlueComponent();
```

Came across [this](https://jsfiddle.net/4Lz9f0L0/) while doing [`toCSS` work](https://github.com/ractivejs/ractive/pull/2362). In the above, the first component is instantiated directly from Ractive and should show up red. The other one is instantiated with a component definition and should show up as blue. However, only the blue one gains color.

Is this intended behavior? Does the `css` property only apply to extending and not directly creating instances?

**Comment by martypdx** [comment]
> Is this intended behavior? Does the css property only apply to extending and not directly creating instances?

Currently that would be the case.

**Comment by fskreuz** [comment]
Hmm... might be nice to document which options work where. To the docs!

**Comment by martypdx** [comment]
Until there's a demand, I think we should just limit to `extend` and include in the docs.

Right now you can do a one-liner and add to a component to get root:

```js
const MyRactive = Ractive.extend( { css: 'li { color: blue; }' } );
```

We probably _should_ give a warning if `css` is included as an option to tell people what to do instead.

**Comment by fskreuz** [comment]
There should now be a warning when `css` is used on an instance configuration https://github.com/ractivejs/ractive/pull/2362. Docs pending at https://github.com/ractivejs/docs.ractivejs.org/issues/246

**Comment by sabob** [comment]
Just stumbled upon this. Do we know why css prop doesn't work on instances? Would be useful to have.

**Comment by ghost** [comment]
Ahh, I can explain this (just haven't got to it like... forever 😄 ). Long story short, the generated CSS is currently just generated on a per-component level. 

There's actually no reason we couldn't go per-instance. There's just no one looking for the feature 😄 . Per-component CSS is sufficient in most cases since normally, you don't generate hundreds of unique instances with unique CSS each, just a hundred instances of a few dozen components.

I'm open to implementing it. It's just that does anyone actually need it? 😁

**Comment by sabob** [comment]
Not sure if there are implications with per-instance css. One can do a workaround by extending before instantiating:

```
import css from 'view.css';
let Comp= Ractive.extend({css: css});
let comp = new Comp();
```

I guess it's just surprising it doesn't work per instance, like 'template'.

**Comment by sabob** [comment]
Can we reopen this issue if css should be supported per instance?

**Comment by ghost** [comment]
I think a separate issue would be better. This one is more like verification of the existing functionality.
