### ISSUE TITLE
Unrender a component included in an instance's template

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#2368]
Components inserted in the page using `Component.render(...)` can be unrendered via `.unrender()`.
The same is not true for components rendered through a template.
See my fiddle for a working example.

https://jsfiddle.net/gigasoft/1aq35u6p/3/

Is this intentional?
## 

Same behaviour on edge and latest.

**Comment by Madgvox** [comment]
Yes, this is intentional as far as I'm aware. The difference being that in one instance, `Component` is a root ractive instance, and in the other it's a child of another instance. Only a root instance ractive can use the dom manipulation functions, since a ractive that is the child of another ractive is controlled by the template itself, not the dom (probably another footnote to add to the docs). In other words, the component inserted into the page via `render` isn't really a component, just another root ractive instance.

It's probably worth pointing out that if you render a ractive and then insert another ractive into that ractive using `render`, you can later `unrender` the second ractive, unlike a component.

**Comment by giovannipiller** [comment]
I see. So there's no way to teardown/unrender a child component, unless I remove it from the template with something like:

    {{#if showComponent}}<Component/>{{/if}}

While I understand the motivation behind this, it is a bit confusing 😊

It makes it a little harder to code components that can be used both as Ractive instances _and_ child components.

Thanks for the reply!

**Comment by giovannipiller** [comment]
It might be worth noting that `.unrender()` will trigger transitions wether the component will unrender or not: https://jsfiddle.net/gigasoft/g83pt4mt/1/

This made it quite difficult to catch this behaviour in my code (component faded away, but was actually still alive).

**Comment by Madgvox** [comment]
It is worth noting! I would call that a bug.

**Comment by skeptic35** [comment]
> I see. So there's no way to teardown/unrender a child component, unless I remove it from the template

```teardown()``` actually seems to work even on child components. But I'm not quite sure if manually tearing down child components has any unpleasent effects on the parent.

**Comment by martypdx** [comment]
> It makes it a little harder to code components that can be used both as Ractive instances and child components.

@giovannipiller: Can you explain why?

> teardown() actually seems to work even on child components. But I'm not quite sure if manually tearing down child components has any unpleasent effects on the parent.

FWIW I recall it was intentionally fixed to work awhile back under the presumption that if you called it, you knew what you where doing and could manage the consequences.

**Comment by giovannipiller** [comment]
> Can you explain why?

For example, a message component with a dismiss button (as in http://jsfiddle.net/gigasoft/g83pt4mt/1/).

The dismiss interaction (=removing the component from the DOM) makes sense to be coded right within the Ractive.extend(...), as opposed to having a separate `{{#if showMessage}}<Message>...</Message>{{/if}}` when included as component.

Of course, if we're allowed to teardown any component, then this is not an issue.

**Comment by martypdx** [comment]
So, I can think of two approaches you could take. I don't think there's an issue with using teardown, but the issue would be keeping parent (if there is one) in sync. (I've added a conditional display to highlight the issue of the parent being "in-sync" with the actual state of the component)

You could always teardown in the component, but sync up the parent by subscribing to the `teardown` (see http://jsfiddle.net/g83pt4mt/2/):

```html
{{#if show}}
    <component from="app's template" on-teardown='set("show", false)'/>
{{/if}}
```

Seems a bit "mystical" that the parent would know to do that, but maybe within your own app that's not an issue.

Other approach is to test within the component if it is the root, and handle teardown if it is (see http://jsfiddle.net/g83pt4mt/3/):

```js
    onrender: function () {
        if ( this === this.root ) {
            this.on( 'close', _ => this.teardown(), false );
        }
    },
```

And now there is more logical `close` event to catch in the parent:

```html
{{#if show}}
    <component from="app's template" on-close='set("show", false)'/>
{{/if}}
```

**Comment by giovannipiller** [comment]
Thanks for the tips!
