### ISSUE TITLE
How to find parent component node or root node from decorator

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2373]
Is there any way i can get the parent component node (if exists) or the parent root node, from within a decorator?

**Comment by kouts** [comment]
ok, I found this solution but I don't now if it's the correct way to do it:
``
    // If it is located inside a component
    if(element._ractive.proxy.decorator.root.component){
        // Get component root node
        var node = this.root.findComponent(element._ractive.proxy.decorator.root.component.name).find('*');
    }else{
        // Else get ractive root node
        var node = element._ractive.root.el;
    }
``

**Comment by Madgvox** [comment]
You're probably looking for [Ractive.getNodeInfo()](http://docs.ractivejs.org/latest/ractive-getnodeinfo).

**Comment by kouts** [comment]
Aaah missed that! I saw it now, thanks for that.

**Comment by martypdx** [comment]
@kouts inside the decorator function `this` refers to the current ractive instance:

```js
function myDecorator( node ) {
    this // ractive
}
```

**Comment by kouts** [comment]
Thanks @martypdx , so how do I find out if my decorator is inside a component or a root instance?
Currently I'm doing this:
```
function myDecorator( element) {
    var ractive_node = Ractive.getNodeInfo(element).ractive;
    var node = ractive_node.parent ? ractive_node.find('*') : ractive_node.el;
}
```

**Comment by kouts** [comment]
Ok found it,
```
var node = this.parent ? this.find('*') : this.el;
```
Thanks @Madgvox and @martypdx

**Comment by martypdx** [comment]
You can also use `this === this.root`. 

Just FYI that `this.el` is the containing element to which the root instance was appended, whereas `this.find('*')` returns the first element within the template of the instance.

**Comment by kouts** [comment]
> Just FYI that this.el is the containing element to which the root instance was appended, whereas this.find('*') returns the first element within the template of the instance. 

Yes, I'm looking for the containing element in case the instance is the root instance.
