### ISSUE TITLE
creating a new Ractive on top of the same #el keeps data object

### ISSUE THREAD

**Issue by arisAlexis** [ractivejs/ractive#2374]
I am not sure if this is a bug or feature since I am using ractive with a router and quite unorthodoxically.

What I do is create a new Ractive.extend object on an element and then create a new same instance of this class on the same element. The outcome is that the data object is not cleared (shouldn't it happen somewhere in teardown?) even though I have `data: {}`  in the class properties.

**Comment by evs-chris** [comment]
When you use extend with an object literal, that object is shared with all instances of your extension. If you want non-shared data, you can use a function, which will return a different data instance for each instance of your extension e.g. `data: function() { return {}; }`.

**Comment by arisAlexis** [comment]
great thanks!
