### ISSUE TITLE
Memory leak questions

### ISSUE THREAD

**Issue by fgan** [ractivejs/ractive#2377]
My team uses Ractive as our UI library, and have extended it quite a bit for our own purposes. We've recently noticed that we are leaking memory related to Ractive - perhaps related to our additions to it - and we're not sure where to start looking. Does anyone have thoughts on what a good place to start would be?

**Comment by fskreuz** [comment]
A good start would be to get a profile of your running code. Dev tools would be your greatest friend, especially Chrome's https://developer.chrome.com/devtools/docs/javascript-memory-profiling.

Also, try out the 0.8 (edge) branch. It's packed full with optimizations.

**Comment by heavyk** [comment]
for us, we had the following:

1. external event sources whch we needed to unsubscribe from onteardown (`emitter.off(this.alistener)`)
2. if you're listening or observing something in a parent component you'll need to remove that onteardown also
3. if you use external client libraries to make effects or something, remember to clean them too. they can maintain references to deleted dom nodes without you even knowing it.

use the chrome debugger and look at memory allocations. to use it effectively, make a set of tests which do something then it cleans up. look at what's left in memory after cleanup and you'll see where your memory leaks are.

**Comment by dagnelies** [comment]
My 2 cents: try to isolate it by means of small examples
