### ISSUE TITLE
DOM duplication with component in {{#each}} block and unshift

### ISSUE THREAD

**Issue by jast** [ractivejs/ractive#2381]
Prepending an item to a list that is rendered as a bunch of inline components seems to get an offset wrong somewhere: with each new unshift, one more item from the tail of the list stops being rendered, and instead, you get two, then three, ... copies of the first item (the one you just unshifted).

Minimum demo: https://jsfiddle.net/h2Lufo38/3/

Everything works fine if you append instead (using push).

PS. Tested with 0.7.3 (broken), dev branch 9766109ca (works)

**Comment by fskreuz** [comment]
Fixed on edge http://jsfiddle.net/h2Lufo38/4/

**Comment by dagnelies** [comment]
Funnily enough, it works with `<Breaky bar="{{.bar}}" />`

https://jsfiddle.net/h2Lufo38/6/

**Comment by ISNIT0** [comment]
I believe this is pretty similar:
https://github.com/ractivejs/ractive/issues/2147
