### ISSUE TITLE
computed partial expressions using a this reference and a context do not resolve the partial

### ISSUE THREAD

**Issue by smoldaner** [ractivejs/ractive#2383]
Using a partial expression ``{{>this.computedProperty this.partialContext}}`` does not resolve the partial. Instead a ``Could not find template for partial 'undefined'`` is logged. Tested with 0.7.3 and edge. 

See [Fiddle](http://jsfiddle.net/qs80wqhy/9/) for an example

**Comment by evs-chris** [comment]
This is actually not technically a bug since `{{>partial context}}` is a shortcut for `{{#with context}}{{>partial}}{{/with}}`. If `context` is undefined, then using `this.someName` as the partial name will always yield `undefined`, as `context.someName` is undefined. Does that make sense?

**Comment by smoldaner** [comment]
Ok, if a partial with context is an alias for ``{{#with context}}{{>partial}}{{/with}}``, then that's the point. In my case the context is not undefined, but it's clear that is doesn't have the ``partial`` property!
