### ISSUE TITLE
Strange behaviour when passing context to partials

### ISSUE THREAD

**Issue by sleewoo** [ractivejs/ractive#2384]
Such a scenario:

- having a partial that using a variable to set value for `name` attribute

```html
<input type="radio" name="{{v}}">
```

- `v` is passed like this

```html
{{> p {v: 'v'} }}
```

- the result is 

```html
<input type="radio" name="{{${{v:"v"}}.v}}" value="on">
```

- however, if using whatever after `{{v}}` it works as expected:

```html
<input type="radio" name="{{v}}-whatever">
```

renders to this:

```html
<input type="radio" name="v-whatever" value="on">
```

Here is the proof: https://jsfiddle.net/v4xd228z/1/

Thanks.

**Comment by evs-chris** [comment]
Using `name="{{v}}"` creates a two way binding for the radio. If you're just trying to set the name attribute for the radio, try also using `twoway="false"` in the input e.g. `<input type="radio" name="{{v}}" twoway="false" />`.

**Comment by sleewoo** [comment]
seems no issues with another attributes, just with `name`.

```html
<input type="radio" whatever="{{v}}">
```

renders ok to:

```html
<input type="radio" whatever="v" value="on">
```

https://jsfiddle.net/v4xd228z/2/

**Comment by sleewoo** [comment]
oh, got it, thank you, adding to my TIL :)
