### ISSUE TITLE
Render and update sub views in ractive

### ISSUE THREAD

**Issue by apachemaven** [ractivejs/ractive#2385]
http://getbootstrap.com/examples/dashboard/

Take the above for example, when I click the menu in the left panel, the content(sub view) in the right should be changed, but I am not sure how to make it.

page.html:

```
<div class="container-fluid">
    <div class="row body">
        <div class="col-md-3 ui-sidebar">
            <ul class="nav nav-pills nav-stacked nav-sidebar">
                <li><a href="feature/list">Feature</a></li>
            </ul>
        </div>
        <div class="col-md-9 ui-content">
        </div>
    </div>
</div>

```

```
View = function (element) {
    this.element=element;
}
View.prototype = {
    init: function () {
        this.ractive && this.ractive.teardown();
        this.ractive = new Ractive({
            template: require("./page.html"),
            el: this.element,
            data: store.getState()
        });
    },
    handleChange: function () {
        this.ractive.update(store.getState());

        var active = store.activeComponent; //say it is user_list, now how can I update the `ui-content`
    }
};
```

**Comment by JonDum** [comment]
Can you please provide a live fiddle or example?

I don't see any handlebars expressions in your template at all... so ractive is just going to render the html and be done. There's nothing to do or change in that template.

Also, I don't think `ractive.update()` does what you think it does. http://docs.ractivejs.org/latest/ractive-update

I would maybe also take a look at the ractive tutorial to learn how to add interactive / dynamic bits to your templates. http://learn.ractivejs.org/hello-world/1/

**Comment by apachemaven** [comment]
The above template is not the full template(so you can not find the expressions).

For the `ractive.update` I know it is used to update the data(the expressions) rather than the template which is the point.

When using backbone, I may use this:

```
var subView=new SubView();
this.$el.find(".ui-content").html(subView.render().el);
```

I want to know if this is possible in ractive?

**Comment by woodlandhunter** [comment]
It sounds a like he wants a sidebar that has items which when clicked will change a dynamic content area. It could include routing, history, etc. or could be as simple as just an `{{#if ..}}` block dispatching components from a main template.

@apachemaven 
I believe your suggested approach of manually rendering an instance and then setting it in the target would not be recommended.

Hopefully someone can point you to a simple example.

**Comment by evs-chris** [comment]
0.9 (alpha) has child instance management where the children can be anchored in the parent or external. This is old, so I'm going to close it. Feel free to reopen :smile:
