### ISSUE TITLE
Nested components event capturing

### ISSUE THREAD

**Issue by kenvunz** [ractivejs/ractive#2388]
Say if i have 3 level deep nested components `grandparent -> parent -> son`

Is there any way to do a `grandparent.fire("event")` that will trickle down to `son` component?

Cheers
Ken

**Comment by fskreuz** [comment]
Bubbling is supported (son -> grandparent) but capturing isn't afaik. Can you give us your use case? We may be able to give you alternatives.

**Comment by martypdx** [comment]
For ancestor to descendant communication I usually use data modification to trigger the change, or find the child and invoke a method: `this.findComponent('child-component').someMethod(); `

**Comment by heavyk** [comment]
in our code, we solved this by using namespaced event emitters (think pub/sub) and routing our events through that. don't forget to unsub on teardown though.

**Comment by kenvunz** [comment]
@fskreuz for me it's for letting a page notifying its children (and grandchildren) when it has finished its transition effect, so they can start going crazy with all intensive rendering / data fetching processing after that but not before. This deferring trick definitely keeps the animation a lot smoother I found.

Currently, I have a pub/sub event system (as mentioned by @heavyk ) to get around it, but it feels somewhat less elegant than a simple `page.fire('transitionComplete');`

What do you guys think? Is it worth it to implementing to the core?

**Comment by martypdx** [comment]
For that specific use-case, what you're tracking is app state. What I've done is have a root instance "global" data item called `user` and then various components can use the `user.action` property to both register actions when they happen and observe or use in the template the `user.action` property.

Fundamentally, there's not much difference between pub/sub and observing data. 

One downside is that I've been using non-isolated components and would prefer to switch to isolated components, which makes the "global state" approach less appealing. This is one of the reasons I'm keen to get `@` state semantics #2345 into ractive. That way I could access something like `@@user.action` anywhere in my app.

**Comment by sabob** [comment]
Maybe you could use global lifecycle events?

Ractive.globals.oncomplete = function() {
    // Here you know a ractive completed it's transitions 
}

or even
Maybe Ractive.globals.onrender = function() {
    // Here you know a ractive is attached to dom, but transitions not started
}

One issue here is that the lifecycle events doesn't pass any arguments, so you don't know "which" ractive instance the event pertains to.

**Comment by evs-chris** [comment]
This came up on SO recently, and I think the proposed solution is actually better than sticking event capture on Ractive. Basically, you want a component to listen to events that originate from somewhere up the hierarchy, and you already have easy access to installing listeners at those levels (parent, root). So during component init, you can use `this.root.on` or `this.parent.on` to listen to your desired event, say 'event'. Then when the parent or, in the case of root and starred event listeners, anywhere between the component and root fires the 'event' event, the component listener will also fire. Keep a reference to the listener that's set up during component init so that it can be cancelled when the component is removed. Here's what it looks like:

```js
var cmp = Ractive.extend({
  onrender() {
    this.listener = this.root.on('*.event', doSomething);
  },
  onunrender() {
    this.listener.cancel();
  },
  ...
});

var r = new Ractive({
  template: 'with cmp somewhere...',
  ...
});

r.fire('event'); // this will trigger cmp event listener, in this case doSomething
r.findComponent('somethingInTheMiddle').fire('event'); // this will too, because it bubbles to root as
// a namespaced event, which is caught by the starred listener
```
