### ISSUE TITLE
Is RactiveJS still alive?

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#2389]
I want to start a new project based on RactiveJS, but I found that releases was stuck in April 2015. And even 0.7.x version is not encouraging me. 

Do you have a plans when 1.0 version will be released? Thanks!

**Comment by ISNIT0** [comment]
Typically, a good way to see how active a project is, would be the graph page on GitHub: https://github.com/ractivejs/ractive/graphs/contributors

The 'latest commit' metric at the top of the code page is pretty good too:
![image](https://cloud.githubusercontent.com/assets/5173131/13181906/2b35b518-d727-11e5-99ad-74d265626987.png)

Yet another metric would be 'Milestones', the next of which is 0.8: https://github.com/ractivejs/ractive/milestones/0.8

I would say there is pretty constant activity in the development of Ractive, plus there are an increasing number of companies using it to drive their businesses :)

Hope that helps!

**Comment by fskreuz** [comment]
> Is RactiveJS still alive?

Yep, alive and kicking. You can always watch the repo and see all the goofy conversations happening over at the Issues and Pull Requests section.

---

> but I found that releases was stuck in April 2015

Everyone's trying to get 0.8 out of the door, with community approval of course. Same goes for documentation. Feel free to jump into the action. No one will be left unheard. :smile: 

---

> Do you have a plans when 1.0 version will be released?

meanwhile in Ractive...

> I'm afraid we adhere to the John Carmack 'when it's done' philosophy of release cycles...
> @Rich-Harris , https://github.com/ractivejs/ractive/issues/2077#issuecomment-136003028
>
> when asked for a release date on a new title, Carmack will usually reply that the game will be released "when it's done."
> https://en.wikipedia.org/wiki/John_Carmack#Personal_life_and_philosophy

**Comment by PaulMaly** [comment]
Thanks guys, you calmed me. In Russia, where I from, Ractive is not so popular like React or Angular, but for me it is a favorite library for now. I'm preparing toolbox to develop isomorphic web application based on Ractive and NodeJS. So, I want to be sure, that Ractive has the future. Good luck!
