### ISSUE TITLE
Request: put version header in minified scripts

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2390]
Hi,

currently, `ractive.min.js` and most other plugins don't write anything in the minified versions. It'd be nice to write at least the version though.

**Comment by heavyk** [comment]
this is quite easy to do in your gobblefile. do you need help to know how?

**Comment by martypdx** [comment]
fyi - you can get version at runtime via `Ractive.VERSION`, so as a workaround you can search the file for `VERSION:`

**Comment by dagnelies** [comment]
well, sure, you can do all that. Yet, I think it wouldn't harm to put a `/* ractive.js v... */` in ractive's minified scripts and the various plugins as well.

**Comment by heavyk** [comment]
make a PR to the build scripht :)

**Comment by evs-chris** [comment]
There is now a version header for minified edge builds.

**Comment by dagnelies** [comment]
Cool, thanks, I'll close it now.
