### ISSUE TITLE
Hmmm... how do I do...

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2391]
Hi,

...please bear with me, it's quite long and contrived.

the issue is related to a tiny plugin of mine:
http://dagnelies.github.io/ractive-array/

it's really a silly tiny plugin but I use it all the time all over the place.

It's used as generic shortcuts in lists, like a down arrow to move an item down:
`<img {{#if list_isLast(@keypath)}}class="disabled"{{/if}} src="img/down.png" on-click="list_down(@keypath)" />`

...replacing a vanilla version like:
`<img {{#if some-custom-function(@index)}} class="disabled"{{/if}} src="img/down.png" on-click="some-custom-function(@index)" />`

This mostly avoids the need of requiring to write a custom function each time to swap specific items. 

I simply imported the `list_down` through `Ractive.defaults` and it still works without a fuss.

The `list_isLast` is a bit more tricky. It's an expression, so it should belong to `data`. However, since I wanted to avoid polluting my "holy" data, I followed a recommendation in one of my previous tickets. I put it in a computed variable returning a function:

```
Ractive.defaults.computed.list_isLast = function() {
	return function(keypath) { 
		var ki = this.list_splitKeypath(keypath)
		var len = this.get(ki.keypath + '.length')
		return (ki.index === len - 1)
	}
}
```

now this is pretty crazy right? ...but it works, at least in 0.7. However, after upgrading to 0.8 (because of other issues), this crazy construct broke. (It wasn't able to find the `list_splitKeypath` it depends upon). It's broken and I have no idea on how to fix it for 0.8.

This all might seem like overkill, however, I still have no better idea of how to find a generic way to identify a "last item" in an array. If you have a more elegant *generic* way to solve this, or a better way to place/call that function, you're welcome.

PS: and if you want to experiment around, just download the example above in the repo.

**Comment by evs-chris** [comment]
This doesn't help with the plugin, but I typically just use `../length == @index + 1` to detect the last element. It's reasonably concise, even if it's boilerplate-y.

Have you tried `get`ing the keypath function in the computation?

**Comment by dagnelies** [comment]
@evs-chris how to do that?

**Comment by evs-chris** [comment]
Sorry, was at lunch on my phone. Looking at it again, is this a case of the missing function context?

```js
Ractive.defaults.computed.list_isLast = function() {
    var self = this;
    return function(keypath) { 
        var ki = self.list_splitKeypath(keypath)
        var len = this.get(ki.keypath + '.length')
        return (ki.index === len - 1)
    }
}
```

As for the length comparison, that's in definite stable territory, so you shouldn't have to worry about it :smile:.

There is an alternate approach for 0.8, which is using the new special reference `@ractive` (warning: there are some suggestions that it might change to `@this` before 0.8 is out) that gives you access to your Ractive instance in the template. So you can add your helpers in a designated spot on your instance either directly or in a designated area and call them from there.

```js
var ractive = new Ractive({
  el: ...,
  template: `<ul>{{#each someList}}<li>...
    <button {{#if @ractive.list.isFirst(../, .)}}disabled{{/if}} on-click="...">Up</button>
    <button {{#if @ractive.list.isLast(../, .)}}disabled{{/if}} on-click="...">Down</button>
  {{/each}}</ul>`,
  data: {
    someList: [ 1, 2, 3 ]
  },
  list: {
    isFirst(list, item) { return list.indexOf(item) === 0; },
    isLast(list, item) { return list.indexOf(item) === list.length - 1; }
  }
});
```

You could also namespace with the name instead of an object e.g. add `list_isLast` to your Ractive instance and access it with `@ractive.list_isLast(...)`.

**Comment by martypdx** [comment]
> list: {
>     isFirst(list, item) { return list.indexOf(item) === 0; },
>     isLast(list, item) { return list.indexOf(item) === list.length - 1; }
>   }

Okay, nitpicking here, but you already have the index in the template so pass that in and don't turn an `O(1)` into a `O(n) by doing an `indexOf`!

**Comment by evs-chris** [comment]
For example only... don't actually use this code. :smile:

**Comment by dagnelies** [comment]
Well, I'll still revert to `../length == @index + 1`. It's more concise and straightforward than `@ractive.list.isLast(@keypath)`. It's just a pity that I have to edit so much of my existing code.
