### ISSUE TITLE
Recursive looping on firstNode of fragment with nested if blocks

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2395]
Hi,

I encountered a bug, which I couldn't isolate so far. I'm posting it nevertheless to keep track of it. I'll perhaps be able to track it down when I have more time... or perhaps some of you already have an idea. Following snippet on edge causes a timeout (probably because of an endless loop):

```
{{#each mylist.users}}
	{{#if !~/users.filter || .displayName.indexOf(~/users.filter) >= 0 }}
		{{#if !~/users.showSelected || .selected}}
			...
		{{/if}}
	{{/if}}
{{/each}}
```
Funnily enough, inverting the two `if`s makes it run seamlessly again.

The recursive loop is connected to:
```
findNextNode@ractive.js:6877:1
firstNode@ractive.js:13486:12
findNextNode@ractive.js:6879:18
findNextNode@ractive.js:13441:12
firstNode@ractive.js:13486:12
firstNode@ractive.js:7212:29
firstNode@ractive.js:13480:13
findNextNode@ractive.js:6879:18
...
```

**Comment by dagnelies** [comment]
Never mind, errors happen independently of the `if` order. Apparently when more results have to be rendered.

**Comment by fskreuz** [comment]
I assume this is edge?

**Comment by dagnelies** [comment]
yes, edge

**Comment by evs-chris** [comment]
@dagnelies I think I can see where infinite recursion might occur and blow the stack, but I can't seem to reproduce it. Can you give me a little more context from the template e.g. what surrounds the iterative section and the contents of the iterations?

**Comment by dagnelies** [comment]
@evs-chris the content doesn't appear to play a role. Even with solely `...` it blows up. Sadly, I wasn't able either to reproduce it in a simple example. I'm currently also quite busy at work right now, but I'll come back later to it. Just give me some time.

**Comment by dagnelies** [comment]
Ok, I've lastly nailed it down better. One reason why I couldn't reproduce it with a small example is because it was not an endless loop. It rather appears to require exponential time to resolve.

Here is the fiddle:
http://jsfiddle.net/ey0LxzL0/

"Instructions":
- check/uncheck the "show only selected" box, everything is fine
- change the `addUsers(20)` into `addUsers(25)` and do the same, it'll take quite a while
- change to `addUsers(30)` and the browser dies

**Comment by evs-chris** [comment]
Thanks for the example! I think I've got it sorted. It's a case of trying to find the first node calling find next node on the parent that called first node and yo-yoing about. I'll have a PR for review shortly: http://jsfiddle.net/ey0LxzL0/1/

**Comment by dagnelies** [comment]
you saved my day, thanks!
