### ISSUE TITLE
[0.8] - getNodeInfo is not returning the keypath

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2396]
I'm probably doing something wrong but here goes:

```xml
<div id="container"></div>

<script id="my_template" type="text/ractive">
  <div>
    <label>Input element</label>
    <input type="text" value="{{text_value}}" decorator="my_decorator" />
  </div>
</script>
```

```js
Ractive.decorators.my_decorator = function(node, props) {
  console.log(node);
  var node_info = Ractive.getNodeInfo(node);
  console.log(node_info);
  return {
    teardown: function() {}
  };
};


var ractive = new Ractive({
  el: '#container',
  template: '#my_template',
  data: {
    text_value: 'Sample text'
  }
});

```

In this fiddle http://jsfiddle.net/wwx3gj1e/2/ I'm trying to get the keypath from the DOM node (an input text element), but I get an empty object (check console).
Am I using getNodeInfo in the wrong way or is this a bug?

**Comment by evs-chris** [comment]
No, you're using it correctly. It's just that there's no context at that point in the template. Context is only provided by non-`if` sections i.e. plain section mustaches, `each ` sections, and `with ` sections. Your context there is effectively the root model.

**Comment by kouts** [comment]
Thanks @evs-chris , so is there any way to get the keypath associated with the DOM element.
In this fiddle's case it would be: text_value

**Comment by evs-chris** [comment]
Ah, so you want the binding keypath. Unfortunately there's no official API for that, but as of #2376, I've been thinking about proposing a utility method to resolve keypaths relative to an element. I updated your fiddle with an incomplete version that supports getting a binding keypath as well as any element's keypath. Will that work for you?

It's missing the path resolution part because I'd have to copy private chunks of Ractive to get it to work at this point. Do you think this would be a reasonable addition to Ractive to sit next to `Ractive.getNodeInfo`?

**Comment by martypdx** [comment]
> I tried wrapping it into a "values" section but I get "values" as the keypath.

Wrap the input in a `with` block and change the ref to `this` or `.`:

```html
{{#with text_value}}<input type="text" value="{{this}}" decorator="my_decorator"/>{{/with}}
```

**Comment by evs-chris** [comment]
... or you could do what that, though it is a bit noisy. I'm determined that _someone_ else needs to resolve keypaths relative to an element :laughing:

Completely forgot to link to the updated fiddle: http://jsfiddle.net/wwx3gj1e/4/

**Comment by martypdx** [comment]
@evs-chris But how do you know what an element is?

```html
<div class="{{foo}}">{{bar}}{{quex}}</div>
```

Or is this only an `input[value]` thing?

**Comment by martypdx** [comment]
@kouts Out of curiosity, what is it you want to do with the context keypath inside the decorator?

**Comment by evs-chris** [comment]
An element has its natural context `<node>._ractive.context` and you could also have a binding on form elements that you may want to retrieve. So by binding, I mean `twoway` binding, or an element that represents a window into the data for user interaction (forms, contenteditable, etc).

I could see using the binding keypath for validation, among other things, in a decorator without having to pass it directly to the decorator.

**Comment by martypdx** [comment]
Gotcha, but given the ambiguity of applying it to _any_ element - what if we added a `.bound` prop that had `{ context, keypath }` to the return of `getNodeInfo`? That way the specific ractive element implementations can add in the values (or not) as appropriate.

**Comment by kouts** [comment]
> @kouts Out of curiosity, what is it you want to do with the context keypath inside the decorator?

I have a decorator which adds a calendar on an input text element and I want to get the value of that input.

**Comment by fskreuz** [comment]
@kouts Decorators are more of "patching up the DOM", while components are "custom elements". What you appear to need is some sort of custom input element. Consider using a component instead. It's not really that different from a decorator from a code perspective, but packs more power.

```js
const CalendarComponent = Ractive.extend({
  template: `<input value="{{ date }}">`,
  data(){
    return { date: `...` }
  },
  onrender(){
    this.find('input').datepicker();
  },
  onteardown(){
    $(this.find('input')).remove();
  }
});
```

**Comment by kouts** [comment]
@fskreuz , I'll try and do that thanks.

**Comment by kouts** [comment]
> Do you think this would be a reasonable addition to Ractive to sit next to Ractive.getNodeInfo
@evs-chris yes I think it would be useful.

**Comment by kouts** [comment]
@evs-chris I had a chance trying getKeypath and it is great for what I'm trying to achieve.
Is there a more "stable" version of this function?
I get info.binding is undefined on some fields (are these fields that are not "bind" to any keypath?)
Thanks!

**Comment by evs-chris** [comment]
@kouts that should only happen if you use it with a non-form element or a non-twoway-bound form element. Also, I'd need to update that to work with current edge, but I have another proposal to make that looks like it would be better. I'm almost through my pile of day job work, so I should be able to get that in after some bug fixes.

**Comment by kouts** [comment]
I had an non-twoway-bound form element so that's why I was getting the error.

**Comment by evs-chris** [comment]
Node info objects now have helpers for, among other things, getting binding info off of inputs.
