### ISSUE TITLE
Dynamically updated element class blows away classes added by a decorator

### ISSUE THREAD

**Issue by Ghazgkull** [ractivejs/ractive#2404]
If you have an element in a template with classes that are conditionally added based on bound data, Ractive will blow away any classes on that element which were added by decorators if/when the data changes.

Here's a working example that demonstrates the issue:
http://codepen.io/Ghazgkull/pen/EKYVxd

**Comment by martypdx** [comment]
Looks like a variation of #1262. Basically the text fragment that corresponds to the dynamic attribute value doesn't know anything about value modifications happening elsewhere.

Probably mostly an issue for `class` and `style`. The solution may require adding style and class value parsing, or maintaining a before/after comparison.

**Comment by evs-chris** [comment]
Classes and styles are no longer trampled in edge.

**Comment by Ghazgkull** [comment]
Woo!
