### ISSUE TITLE
Data-binding on method call broken

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2410]
Works on latest (0.7): http://jsfiddle.net/zh1mu8eL/3/
Broken on edge (0.8): http://jsfiddle.net/zh1mu8eL/1/

```xml
<script id="t" type="t">
  <input value="{{val}}" />
  {{val}}
  <btn onclick="alert('{{val}}')">What?</btn>
</script>
```

```js
Ractive.components['btn'] = Ractive.extend({
	template: "<button onclick='{{onclick}}'>{{yield}}</button>"
});

var r = new Ractive({
	el: 'body',
	template: '#t'
});
```

**Comment by guilhermeaiolfi** [comment]
I wasn't aware that was possible in 0.7. Good to know.

**Comment by dagnelies** [comment]
well, components *cannot* have `on-click`, so as far as I know, it's the only way it can be done

**Comment by fskreuz** [comment]
> well, components cannot have on-click, so as far as I know, it's the only way it can be done

Actually, you can. `on-click` can simply be [a custom "click" event emitted by the component](http://jsfiddle.net/tgrexae5/).

```js
const Child = Ractive.extend({
  template: `
    <button on-click="fire('click')">Click Me!</button>
  `
});

const Parent = Ractive.extend({
  template: `
    <Child on-click="clickHandler" />
  `,
  components: { Child },
  oninit(){
    this.on('clickHandler', function(){
      alert('Hi!')
    });
  }
});

new Parent({
  el: 'body'
});
```

As far as I know, it's *component event method calls* that [were not supported in 0.7](http://jsfiddle.net/tgrexae5/1/) and was [introduced in 0.8](http://jsfiddle.net/tgrexae5/2/).

```js
const Child = Ractive.extend({
  template: `
    <button on-click="fire('click')">Click Me!</button>
  `
});

const Parent = Ractive.extend({
  template: `
    <Child on-click="clickHandler()" />
  `,
  components: { Child },
  clickHandler(){
  	alert('hi');
  }
});

new Parent({
  el: 'body'
});
```
