### ISSUE TITLE
Dear Ractive...

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2411]
Hi,

this is just a message for you, dear staff, to open my thoughts about Ractive.

**The Great**

- the library is simple and intuitive (most of it at least)
- it doesn't get in your way and plays well with other libs
- your support is top notch, really amazing guys!
- it's fairly flexible and you can push it pretty far
- debug messages are most of the time rather helpful

**The hmmm...**

- there are some quirks which are not obvious / unintuitive
    - `{{ func(a) }}` calls a function in data scope
    - `on-click="func(a)"` calls a function in ractive scope
    - `onclick="func({{a}})"` is still the most intuitive for most people (*)
    - you can provide whole objects in `on-click` but only primitives in `onclick`
    - ...
- components require quite a bit of know-how
- plugins are poorly presented

(\*) *and is still especially handy because you can't put an `on-click` on a component, but you can forward the `onclick`*

**The Ugly**

...just one here, but a BIG one: ***stability, stability, stability!!!***

Honestly, this is what kills me every time. Ractive offers you great productivity at first, and you build things in no time. However, it all backfires afterwards because there *will be* some kind of bug. For every hour I spent making something, I probably spent three time as much tracking down strange bugs around and working around them. Often I report them, but sometimes I'm just not able to identify the reason. The frustrating thing as well is that these bugs tend not to be present in small toy examples but appear once richer constructs are in place. It's so dramatic that my pages use different versions of ractive, because each have different sets of bugs, and that I'm each time afraid of updates. So please please please, take my plead to focus on simplifying stuff and making it more robust.

Thanks for your attention (and the great job you're doing here!)

**Comment by fskreuz** [comment]
> there are some quirks which are not obvious / unintuitive
- `{{ func(a) }}` calls a function in data scope
- `on-click="func(a)"` calls a function in ractive scope
- `onclick="func({{a}})"` is still the most intuitive for most people (`*`)
- you can provide whole objects in on-click but only primitives in onclick

That's actually an [ongoing discussion](https://github.com/ractivejs/ractive/pull/2386) for a huge PR (I see you there too :smile:). I believe we should come to a conclusion on that PR fast and merge it. Then we can get feedback again. Huge lingering PRs are subject to conflicts and bugs.

> - components require quite a bit of know-how

Can I get more detail from this? I just run with the idea that I'm creating custom elements (but maybe that's just me).

We're holding off on the docs until 0.8 is done. There's so many changes in 0.8. We're trying to track them in the [docs repo](https://github.com/ractivejs/docs.ractivejs.org). Everyone uses Ractive a bit differently (Some use models while some POJOs. Some use two-way binding while some use Flux. Some use component files while some use vanillla JS ) so it's really easy to miss some Ractive intricacies. If you happen to see one, feel free to jump in.

> - plugins are poorly presented

There's the [mono-repo discussion](https://github.com/ractivejs/ractive/issues/2271) where plugins should be housed in one repo for unified testing, building and tracking. I'm starting to lean on the mono-repo idea lately given that we're breaking a lot of them recently.

> ...just one here, but a BIG one: stability, stability, stability!!!

It's a sub-1.0 project, it happens (reminds me of Meteor back in 0.6). :smile: It's also an ongoing process of hitting the balance between familiarity, performance and features. So things are bound to change until everyone agrees with something that's good for everyone. 

> Thanks for your attention (and the great job you're doing here!)

What are you talking about? You're a regular here. :smile: Again, everyone's opinion is always welcome. No one will be unheard. :smile:

**Comment by dagnelies** [comment]
Oh, the thanks was solely for politeness. I'll respond to most points on a later date when my personal work load is smaller if you don't mind.

As for the:

> ...just one here, but a BIG one: stability, stability, stability!!!

I think the word *stability* could have been better chosen. I don't mind the changes, that's ok. It's part of a library to evolve and sometimes changes have to be made.

What I meant with stability is more the bugginess. I spend way too much time debugging and hitting road blocks, and  I would trade less features for less bugs any time of the day!

**Comment by martypdx** [comment]
> What I meant with stability is more the bugginess. I spend way too much time debugging and hitting road blocks, and I would trade less features for less bugs any time of the day!

What version of Ractive? `0.8`? `0.7`? both?

**Comment by dagnelies** [comment]
kind of both to be honest. It's a usual step form me to test it with both and pick the one where the page seems working best. For example, in latest, I had bugs with arrays and transitions (fading plugin).

**Comment by dagnelies** [comment]
Hi,

I guess you got my point now with 10 reported bugs so far (3 for latest, 7 for edge) 

I sometimes have the feeling that I'm sitting on a gold pot about to explode. A gold pot because you can do lots of cool things, but about to explode because its increasing complexity lead to *a lot* of bugs. ...and I think what I report is probably just the tip of the iceberg. That's why I asked to humbly avoid any unnecessary complexity, and to favor simplicity/stability over additional features before it gets out of hands

**Comment by heavyk** [comment]
why don't you try to fix some of the bugs?

**Comment by fskreuz** [comment]
![10fuue](https://cloud.githubusercontent.com/assets/1582932/13587267/fc826114-e494-11e5-917e-a86aff479c38.jpg)

@heavyk That would be easy if everyone knew how the internals work. Unfortunately, only a few people know it by heart. Even I have barelyscratched the surface. There have been rounds of questions about it, but so far, nobody has come up with a definitive guide.

- https://github.com/ractivejs/ractive/issues/1972
- https://github.com/ractivejs/docs.ractivejs.org/issues/47
- https://github.com/ractivejs/ractive/issues/2363

And even the [docs repo is swamped with issues](https://github.com/ractivejs/docs.ractivejs.org/issues). So yeah, no one can easily fix without knowing how it works first. We might end up breaking it even further, and we still have a 0.8 to ship :wink:

**Comment by dagnelies** [comment]
@heavyk Indeed, easier said than done. Without properly understanding the internals, which is pretty complex, you might do more harm than good in trying to "just fix some bugs". It might accidentally blow up in ten other places, without you even noticing, simply because you didn't know or didn't understand properly some stuff. I see this in the workplace every day, by young hackers doing some quick and dirty fixes, and then calling the senior experts months later because everything blew up and they don't understand why. The "one hour fix" causes then "many days of debugging and proper fixing".

**Comment by heavyk** [comment]
all of my life, instead of fixating on what others can do to fix a problem or what they can do to make my situation better, I tend to like the challenge of finding my own solution. contribute it back and it'll get improved on eventually. sure, there are others that already have the necessary skills, but isn't the challenge of trying to learn it kinda fun?

**Comment by dagnelies** [comment]
@heavyk Hi, it's not really a question of challenge or fun. It's the risk of causing more harm than good due to a shallow understanding of the codebase. And a bad patch is indeed worse than no patch at all. Lastly, it's also very time consuming, and you simply don't always have that luxury.

I think in the meantime the staff got my point, to focus on stability and keeping complexity under control. It's time to close it.

**Comment by sabob** [comment]
> I think in the meantime the staff got my point

I'm pretty sure there is no "staff". There is no commercial company involved, nobody is paid. It's all voluntary work.

Wrt PRs, I think open source projects always encourage PRs, even if it is just to add a test case to cover the issue.

**Comment by dagnelies** [comment]
By staff I meant mostly @Rich-Harris @martypdx @evs-chris. I know it's not company backed, etc. However they still represent "the staff" for me. :wink:

**Comment by heavyk** [comment]
yeah, I think @sabob has a good point. if you make PRs with the test case already built, that severely reduces time. when I made PRs a while back that's how I started anyway. good idea. I just discovered a broken bit today in my code, so I will follow my own advice (hehe). also I guess, some of the other fiddles can also be translated too. actually, this gives me a good idea: the new programmers that I hire, I'll set them to translate the fiddles into tests (and try and reduce them) to see their skill levels. oh man, what a great idea; I'll see what I can do.

**Comment by fskreuz** [comment]
> if you make PRs with the test case already built, that severely reduces time.

For a funny video about "guard-rail programming", [see this video](http://www.infoq.com/presentations/Simple-Made-Easy) and jump to 15:30-17:15. Highly recommend. :+1: 

> also I guess, some of the other fiddles can also be translated too.

It's also advised that reproductions of bugs be written in the issue and not just in jsfiddle. It's for historical purposes, and if we lose any of those services, we have history. If only Github had templated issues *(sigh)*.

> the new programmers that I hire, I'll set them to translate the fiddles into tests

Send them our way. We're always in need of hands. :smile:

**Comment by heavyk** [comment]
> If only Github had templated issues (sigh).

they do now! both issue and PR templates. they go in the `.github` folder. have a look at the nodejs one here: https://github.com/nodejs/node/tree/master/.github

**Comment by heavyk** [comment]
btw, that's a great video! LOL absolutely hilarious. gonna watch the whole thing now :+1:
