### ISSUE TITLE
Decorator teardown too many items when moving items in array

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2412]
I'm looking at getting this sortable plugin running in 0.8:
https://github.com/ractivejs/Ractive-decorators-sortable

Most things are working now, but edge and 0.7.3 behave a bit different wrt decorators when removing and adding items in an array.

I'm trying to isolate the differences between edge and 0.7.3.

In this fiddle:
http://jsfiddle.net/sabob/11zqqamh/

is a decorator that immediately removes the first item in the array, using ractive.splice.

In the console is shown that the teardown method is never called for the removed item.

In 0.7.3, the teardown is called.

I won't call this a bug, as I'm removing the item while ractive is busy building the dom, so this change from 0.7.3 might be intentional?

The real issue I'm having though is in this fiddle:
http://jsfiddle.net/sabob/m0c00da8/

Here is a "move" button that moves an item from index 0 to index 1, using splice.

The console output in edge is:

TEARDOWN  Bob        // This is good, Bob was removed at this point
Removed item Bob      // All good
TEARDOWN  Steve     // Why is Steve's decorator torn down?
Init decorator for:  Bob // This is good, Bob's decorator is setup again since we readded Bob to array

Also Steve's decorator is not setup again.

The console output in 0.7.3 is:

TEARDOWN  Bob         // This is good, Bob was removed at this point
Removed item Bob      // Callback from splice to say item removed from array
Init decorator for:  Bob // This is good, Bob's decorator is setup again since we readded Bob to array

**Comment by sabob** [comment]
#2378 fixes the multiple teardowns I've seen in this fiddle: http://jsfiddle.net/sabob/m0c00da8/
I should be able to get the sortable decorator working for 0.8 now.

There is still this different behavior between edge an 0.7.3 though:
http://jsfiddle.net/sabob/11zqqamh/

Would that cause upgrade problems?

Otherwise we can close this issue.

**Comment by evs-chris** [comment]
Now _that_ is an interesting case... a decorator that causes its host element to be torn down as it is set up. I suppose we should add a check after the decorator is set up to see if the element has been unrendered to halt the process and tear down any set up decorators?

**Comment by evs-chris** [comment]
Or perhaps decorator creation should be moved to a `setImmediate` equivalent so that it doesn't muck around with the init process?

**Comment by martypdx** [comment]
> Or perhaps decorator creation should be moved to a setImmediate equivalent so that it doesn't muck around with the init process?

No, I think most of the time decorators should decorate synchronously...

**Comment by evs-chris** [comment]
I'm looking at twiddling about transitions to see if I can resolve some of the outstanding issues and ran across something interesting - the transition manager no longer has a decorator queue. It seems like decorator teardown should still be called for nodes that detach so that they have a chance to clean up any external stuff they may be doing. Am I right in thinking that elements being destroyed should have their decorator added to the runloop batch to be torn down after transitions are complete?
