### ISSUE TITLE
bug in latest: change not propagated in component's observer

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2413]
Hi,

one more bug. It worked once in latest, but not anymore, but still works in edge.
I'm a bit tired to post the details, but it can be seen fairly easily in this plugin:

http://dagnelies.github.io/ractive-codemirror/

(it's using edge right now)

If you download the "`gh-pages`" and switch to latest, you'll see it break. The observer doesn't get notified anymore.

When I get more time, I'll build a simpler example.

**Comment by woodlandhunter** [comment]
Are maintenance releases even happening for the 0.7.x branch?

**Comment by dagnelies** [comment]
dunno ...good question. I don't know exactly how it's meant to be.

**Comment by heavyk** [comment]
I don't believe so. I think the next release is 0.8

I still use 0.7.3 it in some projects, but all new stuff 'is 0.8

you should make the switch  soon. it is better in so many ways
