### ISSUE TITLE
Animations delay removing parent element

### ISSUE THREAD

**Issue by ADantes** [ractivejs/ractive#2414]
If any of an element's children contain transitions, that element isn't removed until those transitions complete.  It feels like it would be more in line with expected behaviour to just remove the element immediately and ignore any child transitions.

http://jsfiddle.net/reLcn1dz/2/

In the above example:
- switch between "Tab One" and "Tab Two" and back to "Tab One"
- Observe that the transition happens instantaneously
- Check the checkbox and wait for intro transition to complete
- Switch to "Tab Two"
- Observe that both #tab-1 and #tab-2 are present and visible while the outro transition plays.

(In my specific use case, having both of these visible breaks my page layout)

**Comment by martypdx** [comment]
Issue is that sometimes you _do_ want the parent to wait for the children. So it's a matter of an api that can work for various situations.

With current edge you can do something like:

`intro-outro="slide:{{ tab !== 'One' ? { duration: 0 } : {} }}"` 

to prevent the transition.  See http://jsfiddle.net/reLcn1dz/3/, I changed your example a bit so you could see the individual item transition on add.

Once #2369 is merged, you will be able to write conditional transitions using:

 `{{#if tab === 'One'}}intro-outro="slide"{{/if}}"`

**Comment by ADantes** [comment]
I don't think this is a practical solution, once you start dealing with component hierarchies. It did, however, lead me down a few paths I like better.

Approach #1: "none" transition that ends immediately, hiding the element
http://jsfiddle.net/reLcn1dz/4/
(This still subjects you to https://github.com/ractivejs/ractive/issues/2027 however, since the animation time hasn't changed)

Approach #2: Disable animations during a component's teardown step
http://jsfiddle.net/hsLyomb6/
(This is probably the better solution, although is slightly inconvenient since disabling transitions does not cascade down to child components)

I still am of the opinion this is a bug, possibly a side effect of https://github.com/ractivejs/ractive/issues/2027.

**Comment by evs-chris** [comment]
What if the transitions got notified of whether or not they were the root element being transitioned? Then each transition site could choose to transition before letting the parent go or not.
