### ISSUE TITLE
Component intro transitions regression on Edge

### ISSUE THREAD

**Issue by ADantes** [ractivejs/ractive#2415]
Intro transitions are correctly animated on initial load.  However, if a component is rendered later, its intro transitions are not animated.

0.7.3: http://jsfiddle.net/29fLzj6g/1/
Edge: http://jsfiddle.net/29fLzj6g/
* Click "Tab One" and observe the differences between the two versions

**Comment by evs-chris** [comment]
Just wanted to note that I'm looking into it and, potentially, a way to resolve the issues with transitions holding up non-transitioning elements.

**Comment by evs-chris** [comment]
Fixed :smile:
