### ISSUE TITLE
[Enhancement] Allow use of the observable implementation outside of a Ractive View

### ISSUE THREAD

**Issue by halfnelson** [ractivejs/ractive#2416]
I was interested by Mobx (formerly mobservable) and it seems that ractive does this already, except that it only does it for ractive instances which want a template etc. It would be great to be able to use a viewless ractive instance to maintain a reactive data object without tying it to the DOM

**Comment by martypdx** [comment]
> except that it only does it for ractive instances which want a template etc. It would be great to be able to use a viewless ractive instance to maintain a reactive data object without tying it to the DOM

I think what you want already exists, see http://jsfiddle.net/Lt2jL6ck/;

```js
var r = new Ractive({
    data: {
        qux: {
            one: 'foo'
        }
    }
});

r.observe( 'qux.one', val => {
	alert( val );
}, { init: false});

r.set( 'qux.one', 'bar' );
```

**Comment by halfnelson** [comment]
Awesome. Sorry for wasting your time.
