### ISSUE TITLE
Transitions tutorials in learn.ractivejs.org are not rendering

### ISSUE THREAD

**Issue by dlucero23** [ractivejs/ractive#2419]
Hey guys, I'm on the [Transitions section](http://learn.ractivejs.org/transitions/1), and I cannot seem to get the `intro`/`outro` transitions to render.  Also when I run after using 'fix code' button it does not render then either.

Obviously, I don't think that this is intentional, and I am sure the transitions work great in projects.  I have checked for similar issues through Google search, in Github, and I have read the short Transitions [documentation article](http://docs.ractivejs.org/latest/transitions). Before I play with it on my system, I wanted to let you know that I was not able to get it to work in your tutorial section.

BTW, I love RactiveJS so far.  I can't believe how simple and easy to use it is, and I can immediately see how this is going to help moving forward.  Let me know if I can do anything else.

**Comment by fskreuz** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1582932/13395250/9f197c80-debb-11e5-84af-79ba74ea976e.gif)

It seems to work fine. Can you check the console for errors? Or better, post a screen cap? I use [LICEcap](http://www.cockos.com/licecap/) to capture.

**Comment by dlucero23** [comment]
Hi there, it appears that it is working now. not sure what happened.  Maybe my chrome browser crapped out.  Thanks for looking at it for me.
