### ISSUE TITLE
bug: observers observe too much and not enough

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2420]
Hi,

Thanks for all your effort. 

Here is an update of the fiddle last time:
http://jsfiddle.net/ey0LxzL0/2/

As you can see, there are *two* problems:
- the observers for *ALL* items are triggered, instead of just the one that changed
- the "old" value is simply wrong

One more day, one more bug, sorry about that :/

**Comment by evs-chris** [comment]
I think I may be missing something here, but it looks like the observer is behaving as intended. It is being asked to watch `list.users.*` which includes 0-19 in this case. When the observer is created, it is not passed `{ init: false }` to keep it from firing on setup, so it checks all of its matching paths against the previous value (`undefined`) and fires for each instance that has changed (all of them went from undefined to an object).

**Comment by dagnelies** [comment]
sure, just set a checkbox on/off, you'll see

**Comment by evs-chris** [comment]
Aha! I was missing something :smile:... looking into it.

**Comment by martypdx** [comment]
@evs-chris it doesn't appear that the PatternObserve call to the model for child values does any discrimination based on whether the child model is actually dirty or not.

**Comment by evs-chris** [comment]
I think this is now covered.

The old values will be the same as the new because they are the same values (object identity) and ractive doesn't do any defensive cloning.

**Comment by dagnelies** [comment]
Uh ...still misleading to see identical old/new values. What a pity, but I can live with that. I just remember that in the past I did extra checks that new != old because there was another bug leading to the observers triggered too often. Ideally, it'd be nice to see the "correct" old value.

**Comment by evs-chris** [comment]
There's some ongoing discussion about that facet of observers in #2357.
