### ISSUE TITLE
if section loops if data is not found in select

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2424]
Hi,

here is another impressive bug:

http://jsfiddle.net/xc2o8y08/24/

It's probably related to #2423 but I'm not sure. Something is seriously broken there.

...anyway, I wish you a good Weekend.

**Comment by dagnelies** [comment]
Apparently, this occurs when a value is mistakenly not in the select options.

Here the simplified fiddle:
http://jsfiddle.net/xc2o8y08/25/

**Comment by fskreuz** [comment]
Works on latest (0.7): http://jsfiddle.net/xc2o8y08/27/
Breaks on edge (0.8): http://jsfiddle.net/xc2o8y08/26/

```js
Ractive.components['comp'] = Ractive.extend({
  template: `
  	<div>{{yield}}</div>
  `
})

var ractive = new Ractive({
  el: 'body',
  template: `
    {{#if .condition}}
      <b>I'm not even in an #each block, WTF?!</b>
      {{#each .foo}}
        <comp>
          <select class="form-control" value="{{.bar}}">
            <option></option>
            <option>a</option>
            <option>b</option>
            <option>c</option>
          </select>
        </comp>
      {{/each}}
    {{/if}}
  `,
  data: {}
})

ractive.set({
  condition: true,
  foo: [{
    bar: 'd'
  }, {
    bar: 'e'
  }, {
    bar: 'f'
  }]
})
```

**Comment by guilhermeaiolfi** [comment]
@dagnelies should be in the QA team :)
I would like to thank you for finding those bugs and taking the time to report them

**Comment by dagnelies** [comment]
@guilhermeaiolfi I hope not ;) ...it's just that I used it heavily in a project, so bugs pop up like if it was a honey pot

I was able to track this one and #2423 to:

https://github.com/ractivejs/ractive/blob/dev/src/view/items/element/specials/Select.js

I wouldn't say it's the *source* of the bug, it's more what triggers it ...I think ...but as I say, I find it hard to understand the sources enough.

```
        Select.prototype.sync = function sync() {
  		...
  		if (selectValue !== undefined) {
  			...
  			if (!optionWasSelected && !isMultiple) {
  				...
  				if (this.binding) {
  					// this.binding.forceUpdate(); // commenting this does not trigger bug #2424
  				}
  			}
  		}
  		...
  		else if (this.binding) {
  				// this.binding.forceUpdate(); // commenting this does not trigger bug #2423
  			}
  	};
```

...however, commenting these out would very likely trigger some other undesired behavior. Like not setting a variable. Additionally, a warning would also be appropriate here in the bound variable in not present in the select's options.

**Comment by dagnelies** [comment]
thanks!
