### ISSUE TITLE
0.8 - Correct way to unrender - set new data - and the render again

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2426]
Currently I'm using this method to destroy an Ractive root instance, set new data then render it again:
```
Ractive.prototype.setPageData = function(data){
    var self = this;
    self.unrender().then(function(){
        self.set(data).then(function(){
            self.render();
        });
    });
}
``` 
Using just  ```set()``` would not work in my case because there may be some jQuery plugins that must be reinitialized.

Is there any other / better way to do it?

**Comment by fskreuz** [comment]
> Is there any other / better way to do it?

You can look for the component using [`findComponent`](http://docs.ractivejs.org/latest/ractive-findcomponent)/[`findAllComponents`](http://docs.ractivejs.org/latest/ractive-findallcomponents) and call [`teardown`](http://docs.ractivejs.org/latest/ractive-teardown) to destroy it. You can then create a new instance and use [`insert`](http://docs.ractivejs.org/latest/ractive-insert) to put it back.

**Comment by dagnelies** [comment]
Perhaps the clean approach would also be to move the jquery part in a ractive component that initializes/destroys it properly/automatically. What's the jquery plugin if I may ask?

**Comment by kouts** [comment]
The instance I'm trying to destroy and reset data is the root instance not a component(s) inside it.
This is the only way it worked for me so I'm guessing there is no other way to do it.
