### ISSUE TITLE
edge bug: infinite observer loop

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2429]
Hi,

I'll indeed soon take the job as "QA" guy :wink: (also called the party pooper)

until I'm able to isolate this into a simple example, here's the "endless" stack trace:

```
resetPartial (ractive.js:13788)
<my observer callback>
dispatch (ractive.js:14192)
Observer (ractive.js:14179)
createObserver (ractive.js:14151)
(anonymous function) (ractive.js:14116)
observe (ractive.js:14115)
<my component oninit() setting an observer>
call (ractive.js:286)
fire (ractive.js:292)
fire (ractive.js:12271)
end (ractive.js:12301)
initialise (ractive.js:12713)
bind (ractive.js:12967)
_bind (ractive.js:1145)
bind (ractive.js:13400)
bind (ractive.js:7691)
_bind (ractive.js:1145)
bind (ractive.js:13400)
bind (ractive.js:10660)
_bind (ractive.js:1145)
bind (ractive.js:13400)
initialise (ractive.js:12710)
bind (ractive.js:12967)
_bind (ractive.js:1145)
bind (ractive.js:13400)
bind (ractive.js:7691)
_bind (ractive.js:1145)
bind (ractive.js:13400)
bind (ractive.js:10660)
_bind (ractive.js:1145)
bind (ractive.js:13400)
initialise (ractive.js:12710)
bind (ractive.js:12967)
_bind (ractive.js:1145)
bind (ractive.js:13400)
update (ractive.js:7409)
_update (ractive.js:1185)
update (ractive.js:13676)
update (ractive.js:10936)
_update (ractive.js:1185)
update (ractive.js:13676)
update (ractive.js:10936)
_update (ractive.js:1185)
update (ractive.js:13676)
flushChanges (ractive.js:826)
runloop.end (ractive.js:760)

resetPartial (ractive.js:13788)
<my observer callback>
dispatch (ractive.js:14192)
Observer (ractive.js:14179)
createObserver (ractive.js:14151)
(anonymous function) (ractive.js:14116)
observe (ractive.js:14115)
<my component oninit() setting an observer>
...
```
(works on latest)

From what I can understand in this stack trace, it appears that resetting the partial in the component re-creates the component itself, which doesn't make any sense.

**Comment by fskreuz** [comment]
Not sure if this is possible (but I believe so), try enabling the sourcemaps when taking the stack traces. That way, they point to the raw files line numbers instead of the compiled line numbers, and it's easier to look for in the files rather than scrape through the compiled version.

**Comment by dagnelies** [comment]
...the question is: how do I do that exactly? (enabling the source maps)

The thing is, I don't have the usual stack trace in the console, I only get "Uncaught RangeError: Maximum call stack size exceeded". The stacktrace I provided is obtained by setting a breakpoint in the debugger, can it be sourcemapped there as well?

**Comment by dagnelies** [comment]
As a workaround, I placed the observer in `oncomplete` instead of `oninit` as advised in the docs. That way, it appears to be working fine. I wasn't able to reproduce it in a small example yet.

**Comment by fskreuz** [comment]
In Chrome, open dev tools and press `F1`. Under the **Sources** section there should be a **Enable JavaScript source maps** checkbox. Check that, close and reopen dev tools (sometimes, restart Chrome), and your line numbers should now point to the original files.

As for stack size exceeded, tell Chrome to pause when it happens. In dev tools, under **Sources** tab, there should be a big **pause button** on the right pane. Click to enable, then re-run your script. Sometimes Ractive will handle errors. Enable **Pause on Caught Exceptions** checkbox which you can check to pause for managed errors.

**Comment by dagnelies** [comment]
Hi, apparently it was already enabled and I used "http://cdn.ractivejs.org/latest/ractive.js". It's rather annoying I wasn't able to reproduce it, but I have it in my source control, so I can come back to it later.

**Comment by dagnelies** [comment]
closing it since I wasn't able to reproduce it in an example
