### ISSUE TITLE
Summary of observe/onchange related bugs

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2430]
This seems to be a tough recurring topic, especially lately.

This ticket serves as a summary on related open bugs.

- #2429 : edge bug: infinite observer loop
- #2420 : observers observe too much and not enough
- #2413 : change not propagated in component's observer
- #2357 : Wildcard observers not working in components, AGAIN?
- #2200 : Using .set with an object can trigger inconsistant observers
- #2142 : Observers don't respect initially ambiguous implicit mappings
- #2090 : Ractive 0.8.0-edge onchange bug
- #1990 : `onchange` triggered for root instance but not for components
- #1926 : ractive.observe '*' in 0.7 only fires once… when child component is rendered inside Shadow DOM

**Comment by fskreuz** [comment]
Probably a new label would do in this case. Creating one in a bit and tagging those.

**Comment by fskreuz** [comment]
Added a new "observers" label for easy filtering in the search. I'll close this one. Thanks for the help. :+1:
