### ISSUE TITLE
Observing {{yield}} ?

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2434]
From inside a component, how can I know when any fragments/keypaths get updated inside its `{{yield}}`?

```html
    Name: <input value='{{name}}'/>
    <hr>
    <comp>
    	{{name}}
    </comp>
```

Test case with all the ways I tried:  http://jsfiddle.net/tgb3owdk/

**Comment by martypdx** [comment]
Yes, there's no way to do that.  You need to either pass the relevant data to the component:

```handlebars
    Name: <input value='{{name}}'/>
    <hr>
    <comp name='{{name}}'>
        {{name}}
    </comp>
```

or observe in the parent and notify the component when it changes:

```js
this.observe( 'name', _ => {
    this.findComponent( 'comp' ).contentsChanged();
});
```

**Comment by JonDum** [comment]
Dang. I'll have to completely rethink how `ractive-select` works then. I wanted to keep the API working just like a normal `<select>`:
```html
            <select>
                {{#fruit}}
                    <option>{{this}}</option>
                {{/}}
                {{#otherstuff}}
                    <option>{{this}}</option>
                {{/}}
            </select>
```

So I have no idea what keypaths to observe on from within `ractive-select`, not to mention yielded fragments don't actually set any keypaths.

I may have to just not use any of the ractive internals and use a `MutationObserver` to watch for DOM changes to trigger a redraw :|

**Comment by fskreuz** [comment]
Another way to do it would be to [use `{{> content}}`](http://jsfiddle.net/tgb3owdk/2/). The only difference is that the scope of the data in the inner HTML is now the component's, not the parents. So you will have to pass in the data. No funky JS required. :wink: 

```js
var comp = Ractive.extend({
	isolated: true,
	template: `
  	{{>content}}
  `,
  oninit() {
    this.observe('*', c => {
      console.log('* obs: ', arguments);
    });
  }
});

new Ractive({
  el: 'body',
  template: `
  	Name: <input value='{{name}}'/>
    <hr>
    <comp value="{{name}}">
    	{{value}}
    </comp>
  `,
  components: {
  	comp
  },
  data: {
    name: 'world'
  }
});
```

**Comment by JonDum** [comment]
Thanks for the suggestions guys. I ended up just doing the MutationObserver on a hidden "real" `<select>` and updating the fake dropdown when the options in the hidden select change.

@fskreuz I kinda already have that supported in `ractive-select`. You can pass in an `items='{{adf}}'` if you already have an array and it will make the `<options>` for you. This was for people who already have existing `<select>` elements so they could drop in `ractive-select` with no additional work.
