### ISSUE TITLE
Outro animations in components don't apply on the correct element

### ISSUE THREAD

**Issue by ADantes** [ractivejs/ractive#2435]
Rendered directly: http://jsfiddle.net/0dn4qqw1/1/
This does exactly what I want.  Click on a row and you can smoothly see it collapse.

Rendered as a component in another view: http://jsfiddle.net/0dn4qqw1/2/
This does not.  You can see Ractive reorder the DOM, placing the row it is about to delete at the bottom.  Only after that does it remove the row. Since that row is at the bottom of the list now, the animation is visually disconnected from the action the user performed and it overall looks pretty jumpy.

**Comment by evs-chris** [comment]
Fixed in edge, though I'm not entirely sure when :smile:
