### ISSUE TITLE
Calling Set function for an empty Keypath string results in a vague error message

### ISSUE THREAD

**Issue by SherifRefaat** [ractivejs/ractive#2436]
Hi, 

If you do so
`this.set('', {});`

it will result in the following error:

> Uncaught TypeError: Cannot read property 'str' of null(…)

I don't mean that it should not generate error. But rather, it should say that the keypath string provided is empty string or so.

Thanks.

**Comment by evs-chris** [comment]
As of 0.8, this is no longer the case :smile:
