### ISSUE TITLE
Clean way to know if instance has been torn down?

### ISSUE THREAD

**Issue by aharpervc** [ractivejs/ractive#2437]
Is there an in-built way to know when `teardown` has been run on a ractive instance, from inside that instance?

I have a situation where methods could be called asynchronously even after the component has unloaded. I could track my own property easily enough, like `this._has_been_torn_down` or something, but I was wondering if ractive altered it's own state in a predictable way so this could be one fewer thing to manage. Using Ractive 0.4.0.

Here's a vastly simplified sample:

```
Comp = Ractive.extend({
  // ... etc logic

  myThing: function() {
    FunctionThatReturnsPromise()
      .then(function() {
        this.doMoreStuff();
      });
  },

  doMoreStuff: function() {
    // STUFF THAT SHOULD NOT RUN IF TEARDOWN HAS BEEN CALLED
  },

  unload: function() {
    // etc custom unload logic
    this.teardown();
  },
});

// etc

var c = Comp.new();

// etc
```

**Comment by martypdx** [comment]
You can use `onteardown`. See [docs](http://docs.ractivejs.org/latest/lifecycle-events) for more info.

**Comment by fskreuz** [comment]
I think 0.4.x was the time before lifecycle events were standardized. It should be just the `teardown` property. http://docs.ractivejs.org/0.4.0/events

**Comment by aharpervc** [comment]
Is `teardown` a property? I see that it is a method, and an event name to listen for, but I don't see how I could do something like `if (this.teardown){ return; }`.

**Comment by martypdx** [comment]
In `0.4` you need to add `this._super();` inside the `teardown` because you're actually overriding the base teardown method.

**Comment by martypdx** [comment]
> the question is if it already exist

No, there's no `this.torndown`

**Comment by fskreuz** [comment]
> Is teardown a property?

It's a (reserved? @martypdx) configuration property that accepts a function which is run when the component instance is being torn down.

> I have a situation where methods could be called asynchronously even after the component has unloaded.

If your operations can be aborted (ie. jQuery AJAX), then you can abort them in a `teardown`.

If not, or if you need to check after the first callback after the teardown responds, you can always [check if the component instance is still in the DOM](https://jsfiddle.net/qxmg6qyw/). A torn-down component will already have been detached by then.

I believe there's something much simpler for the later versions, but the following should work for APIs that existed way back.

```js
var Component = Ractive.extend({
  template: `<div>test</div>`,
  onrender: function(){
    console.log('render', this.find('*').parentNode);
  },
  onteardown: function(){
  	console.log('teardown', this.find('*').parentNode);
  }
});

var ractive = new Component({
	el: 'body'
});

ractive.teardown();
```

**Comment by aharpervc** [comment]
At least in 0.4.0 `teardown` is a method. As in my simplified example, I am calling it manually in my custom component's `unload` method, rather than hooking up an `onteardown` event and then putting my special cleanup in there.

Unfortunately standard promises do not allow for cancellation, or otherwise I would simply collect all the promises internally and cancel them in my `unload`. Hence now needing some kind of guard property to avoid extra work after teardown.

@fskreuz it looks like `this.find("*")` returns undefined after teardown, so that would be a satisfactory guard, thank you.

**Comment by evs-chris** [comment]
There is a `this.torndown` now, apparently :smile:

**Comment by aharpervc** [comment]
Sweet, thanks for coming back on this and letting me know
