### ISSUE TITLE
Ractive 0.8 - events not working inside sections

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2441]
Check this fiddle: http://jsfiddle.net/df0huenp/2/
How can I make ```set``` and ```toggle``` to work?
I noticed that when I pass the context explicitly to the set event 
```on-click="set('object.capacity', '65')"```
then it works as expected...

**Comment by evs-chris** [comment]
The `set` isn't connected to the template in any way, so it doesn't know the context. You can use `@keypath

**Comment by evs-chris** [comment]
Sorry, backtick - tab and R-shift - enter proximity strikes again.

Also... github now has reactions for comments?

**Comment by kouts** [comment]
Ahhh so it's 
```on-click="set(@keypath+'.capacity', '65')"```
and
```on-click="toggle(@keypath+'.active')"```
thansk @evs-chris
