### ISSUE TITLE
Is Ractive has some set of Ractive re-usable components?

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#2443]
Many other libraries and frameworks, which practice components-based approach, has a set of components build on this framework/library (for example Polymer has https://elements.polymer-project.org/). Is Ractive has something like that?

**Comment by dagnelies** [comment]
Some, but not that much:

http://docs.ractivejs.org/latest/plugins

Among them:

http://dagnelies.github.io/ractive-bootstrap/
http://dagnelies.github.io/ractive-codemirror/
https://github.com/JonDum/ractive-datatable

**Comment by PaulMaly** [comment]
Yep, it's really not much.. What do you think, whether is  necessary for Ractive has some kind of components kit?

**Comment by dagnelies** [comment]
well, everyone is welcome to contribute

**Comment by fskreuz** [comment]
> Is Ractive has something like that?

There's @dagnelies's kit. Not much, but it's a start. We're always open to contributions. If you happen to build one, you can ping us and have it linked in the website.

> What do you think, whether is necessary for Ractive has some kind of components kit?

I have played with the idea before, and the problems I encountered are:

- The components are either too trivial or too small. Take for instance building buttons. Do you really need to create a full-blown instance of Ractive for a button where a simple `<button>` could have worked? It can affect performance, [especially in big trees](https://github.com/ractivejs/ractive/issues/1905).

- Pre-built components only satisfy generic use cases. The idea reminds me of [PrimeFaces](http://www.primefaces.org/). They're handy, but there's always that requirement that needs that custom something. You start of hacking the prebuilt but end up building a new beast from scratch.

- Chasing dependencies. For instance, @dagnelies appears to use Bootstrap 3. However, Bootstrap 4 is almost ready and contains a lot of changes. This would mean updating his kit, which would take time.

- Lastly, Ractive is (always) in flux. There's a lot of movement lately, and breakage is always a concern. There's also [a discussion about mono-repos](https://github.com/ractivejs/ractive/issues/2271) for unified build and testing. Maybe you can pitch in your ideas there as well.

I'm not saying it's a bad idea (I totally dig the Bootstrap kit). Ractive is flexible enough for you to do these things, but there are factors that should be considered when going forward.

**Comment by PaulMaly** [comment]
I'm not sure that I think about something like "how to dig Bootstrap kit and dig in to Ractive", but more about "design (template, dependencies, etc.) free" components, which more about component business logic and customization, properties and events. And also about composition of several components. Of course, not just a regular button, but maybe button extended by some useful features. ))) 

For components design you can just use any CSS framework, like Bootstrap or Fundation, or your own stylesheets. For UI-component JS you can just use some JQuery plugins wrapped in decorator. It's doesn't matter. Each complex component need to have internal business logic and external api to interact (properties, events, methods, etc.) with it. 

For example, let's get Polymer Tabs component available [here](https://elements.polymer-project.org/elements/paper-tabs?view=demo:demo/index.html&active=paper-tabs) . As you can  see, that it's not just a nice UI, but a few cool features, like built-in scrolling and keyboard focus changing.

Hope, now you've got what I mean. )))

**Comment by dagnelies** [comment]
The question is: what do you need?

As you said, there are already plenty of frameworks, widgets and other libs. This ranges from the trivial toggle to the very complex code editor, data-tree-grid, whatever. IMHO opinion, it's not worth to reinvent/rewrite everything from scratch. What *is* important is that it's easy enough to data-bind them with ractive. That's all. Wrap them. Done.

I just made the bootsrap plugin because they are shortcuts I frequently use. As for the tabs, you'll see the plugin has some too ...but most importantly, they have data-binding, which is the important part that polymer lacks altogether. It's comparing apples and oranges.

That said, there are IMHO a few shortcomings regarding ractive components, but this is another topic.

**Comment by JonDum** [comment]
> Yep, it's really not much..

:(

https://github.com/JonDum/ractive-select
https://github.com/JonDum/ractive-multiselect
https://github.com/JonDum/ractive-colorpicker
https://github.com/JonDum/ractive-autosize-input
https://github.com/JonDum/ractive-stepper
https://github.com/JonDum/ractive-datatable
https://github.com/JonDum/ractive-tooltip
https://github.com/JonDum/ractive-paginator

**Comment by PaulMaly** [comment]
Better, but not too much))) Anyway, that's what I'm talking about at first look. Maybe you need to publish these components on Ractive's website? Or make your own website with Ractive components presentation?

**Comment by sabob** [comment]
Since this thread mentioned polymer I thought I'd ask. Has anyone integrated ractive with polymer components? Is it even possible?

Is web component compatible with native ones eg. will ractive two-way binding work on say, paper_input?

**Comment by evs-chris** [comment]
Gonna punt to #2763
