### ISSUE TITLE
Edge bugggg, observers again, data-binding too

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2444]
As usual, here is the fiddle:

http://jsfiddle.net/xc2o8y08/48/

Basically, the `only here if name exists: ...` should only appear when the `name` exists. When typing a couple of letters and removing them, you'll see that *both* the data-binding is badly broken and the observers too.

**Comment by evs-chris** [comment]
Fixed :smile:

**Comment by dagnelies** [comment]
wow, three bugs at once, not bad :wink:
