### ISSUE TITLE
Transition processParams returns empty object when invoked without a default object

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2446]
According to docs, processParams accepts an optional defaults:
http://docs.ractivejs.org/0.3.9/transitions

Given the template:
```
template: '<p intro="foo:{duration: 1000}"></p>',
```
this test should work:
```
transitions: {
    foo ( transition, params ) {
        t.equal( params.duration, 1000 );

        params = transition.processParams( params );
        t.equal( params.duration, 1000 );
```           

it fails at the second assertion because processParams calls Object.extend which returns an empty object if the a defaults isn't provided. In the test above, params is empty after calling transition.processParams.

Should be easy fix, I'll do a PR tomorrow.

**Comment by martypdx** [comment]
As a workaround, you can use:

```handlebars
<p intro="foo:{{ {duration: 1000} }}"></p>
```

**Comment by martypdx** [comment]
TBH, things like this are why we want to lose the "`: {{ mustache }}" call syntax :)
