### ISSUE TITLE
Log unresolved/missing bindings in debug mode

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2450]
Hi,

I think it's a common usecase that at some point some data format changes (think of json provided by a service) ...however, you might not have noticed that somewhere on your page a data-binding broke because of this. As a comfort / safety measure, it would be nice to simply log the unresolved bindings.

...this is neither vital not urgent, but would be handy in the long term. (either by default or through a flag)

**Comment by evs-chris** [comment]
There's now a flag in 0.9 builds to warn about ambiguous references that should catch stuff like this (`warnAboutAmbiguity`).
