### ISSUE TITLE
'this' reference not updating in edge

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2454]
In this fiddle:

http://jsfiddle.net/sabob/y8sg7cad/

is an array of items, each with a delete action that deletes that item from the array.

In the template, the current item is passed to the delete action (through the 'this' reference) and printed to the console.

This works as expected, deleting the 1st item prints "item Bob", delete again prints "item John" etc.

However, conditionally showing the delete button in a mustache's "else" part doesn't work correctly.  As shown in the fiddle, deleting the first items works fine, console prints "Item Bob". However deleting the second item prints "false" instead of "Item John".

Things do work correctly if the delete button is moved to the "then" part of the mustache (and set the disabled props to true in the data object).

This works in 0.7.3.

**Comment by sabob** [comment]
The following change fixed it for me loxcally:

Change this line: https://github.com/ractivejs/ractive/blob/11d24eb453d7ad38328eb5fb252b533639566a6f/src/view/items/Section.js#L81

to:
```
this.fragment.rebind( this.sectionType === SECTION_IF || this.sectionType === SECTION_UNLESS ? null : this.model );
```

So SECTION_IF and SECTION_UNLESS rebind to null instead of "this.model". In the fiddle above "this.model" refers to the "disabled" property which value is "false".

**Comment by evs-chris** [comment]
Yep, SECTION_IF and SECTION_UNLESS shouldn't contribute context, but it looks like the unless got overlooked. Nice hunting! If you don't want to do a PR, I'll catch it in a while.
