### ISSUE TITLE
How easy would it be to port react component to ractive?

### ISSUE THREAD

**Issue by brucou** [ractivejs/ractive#2456]
Building on this issue : https://github.com/ractivejs/ractive/issues/2443, I would like to know how easy it would be to port react components to ractive? It would really help a lot to have a nice library of reusable components. I am sure the guardian is using some slick components they built over the years of publishing infographics or am I wrong and they do custom work each time? 

Anyways, if it is not too hard to port, I would not mind porting some.

**Comment by fskreuz** [comment]
> I am sure the guardian is using some slick components they built over the years of publishing infographics or am I wrong and they do custom work each time?

From what I see @Rich-Harris posts on Twitter from time to time, they look pretty custom every time. They may have a stash of internally reused components.

> I would like to know how easy it would be to port react components to ractive?

Pretty easy, almost too easy even. Both frameworks almost have the same lifecycle events. The only difference I see is that in React, markup can be inlined with logic while in Ractive, markup and data is explicitly separate. Also, two-way binding is by default enabled, but you can disable it. Isolation is disabled by default, but you can also enable it.

Taking [a component example in the React documentation](https://facebook.github.io/react/docs/tutorial.html#reactive-state).

```jsx
// tutorial13.js
var CommentBox = React.createClass({
  getInitialState: function() {
    return {data: []};
  },
  componentDidMount: function() {
    $.ajax({
      url: this.props.url,
      dataType: 'json',
      cache: false,
      success: function(data) {
        this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
  render: function() {
    return (
      <div className="commentBox">
        <h1>Comments</h1>
        <CommentList data={this.state.data} />
        <CommentForm />
      </div>
    );
  }
});
```

The equivalent Ractive would be something like the following:

```js
var CommentBox = Ractive.extend({
  twoway: false,
  isolated: true,
  data(){
    return {
      data: []
    }
  },
  onrender(){
    $.ajax({
      url: this.get('url'),
      dataType: 'json',
      cache: false,
      success: data => this.set('data', data),
      error: (xhr, status, err) => console.error(this.get('url'), status, err.toString())
    });
  },
  template: `
    <div class="commentBox">
      <h1>Comments</h1>
      <CommentList data="{{ data }}" />
      <CommentForm />
    </div>
  `
});
```

**Comment by brucou** [comment]
Great! I will experiment. Closing this for now.
