### ISSUE TITLE
ractive rxjs adaptor

### ISSUE THREAD

**Issue by brucou** [ractivejs/ractive#2457]
This is some kind of a feature request. It would be a great to have a Rxjs adaptor for ractive (I am trying to integrate ractive with cyclejs which is based on rxjs). There is one (cf. http://ractivejs.github.io/ractive-adaptors-rxjs/) but it says : `This (work-in-progress, broken) adaptor allows you to use RxJS observables within your Ractive templates.`.

Sample code is here : 

```
<button class='up'>up</button>
<button class='down'>down</button>

<p>Counter: {{counter$}}</p>
```

I am quite knowledgeable about rxjs, so I could help writint that adaptor. I see three issues that maybe are causing the problem : 
- updating the view when a new value appears on the stream
- lifecycle : unsubscribe/resubscribe when the values pushed by the stream are no longer on screen, or  dealing with the case when a stream has completed
- update of stream : this is a case when the stream itself changes (not the values it pushes), so it would be necessary to unsubscribe from the former stream value, and subscribe to the new one

I am open to working on that with somebody knowledgeable about ractive rendering, diffing and updating process. Adding the functionality would be an immense addition to ractive as it would bridge the gap to frp and open the nice ractive component api to it (so far componentization in the frame of frp is a pain you know where).

**Comment by Rich-Harris** [comment]
Hi @brucou – would love for there to be decent Rx integration. The adaptor API is a bit wonky (something we'll probably be revisit in future) but it *should* be possible to do all those things. For example, if an observable is wrapped by the adaptor, the wrapper's `teardown` method should be called when it's no longer needed, providing an opportunity to dispose of the subscription.

I've just updated ractive-adaptors-rxjs to follow the plugin conventions we've more recently adopted (e.g. not depending directly upon `ractive` and `rx`), and to use the Rx 4 API: https://github.com/ractivejs/ractive-adaptors-rxjs/. It's basic but it seems to work: http://jsfiddle.net/gpsm5157/

There are definitely lots of things I personally don't understand about Rx (e.g. if you have a stream with an existing value, and you do `ractive.set('stream', myStream)`, how to make `{{stream}}` reflect the current value before there's a new one?), so I'd definitely love to get your input. Would be more than happy to give you admin access to that repo if you'd like? Probably best if we have a single project to lessen confusion. Thanks!

**Comment by brucou** [comment]
Hi @Rich-Harris. This definitely sounds great. I was not able though to run the `jsfiddle` (`Uncaught Error: Missing "null" adaptor plugin.`). But I will play with it directly in my code anyways. I eyed through the code, I think it was the `teardown` method who was causing error, because of the `dispose` method call. I suppose it should be fine now. I will test and let you know.

Answering your questions:

- The stream does not necessary have a current value yet. It could be a good addition (similar to how the [ractive-promise-alt adaptor](https://github.com/rstacruz/ractive-promise-alt) works) to add a default value.
- You can get the current value of a stream (if it exists) with `withLatestFrom` operator. 

The code could be changed (untested) into something like :
```
this.subscriber = Rx.Observable.merge(
    Rx.Observable.return({}).withLatestFrom(observable, function (_, currentValue) {
        update_keypath(keypath)(currentValue);
    }),
    observable)
    .subscribe(update_keypath(keypath));

function update_keypath(keypath) {
    return function (value) {
        if (self.updating) return;

        self._value = value;

        self.updating = true;
        ractive.set(keypath, value);
        self.updating = false;
    }
}
```

**Comment by brucou** [comment]
Also I have nothing against admin access, and single project, but I am not really experienced with pushing code on github, so as long it is made in such a way that I can't break anything, I am up for it.

**Comment by brucou** [comment]
Well, I was unable to make it work in my application. The filter seems not to recognize the observable type. Turns out the object passed do not have a `subscribe` method (?). And as a result, my computer blocks so I can't really test further unfortunately.

**Comment by evs-chris** [comment]
#2512 is the adaptor rework issue targeting 0.10. it sounds like this would be doable after that, so I'm going to forward this there.
