### ISSUE TITLE
Can the template attribute of ractive instances be modified?

### ISSUE THREAD

**Issue by brucou** [ractivejs/ractive#2458]
It will be an easy question. I checked the documentation in all versions of ractive, and it turns out that the template property in ractive configuration options is fixed (can be pre-parsed but still fixed). My question is whether ractive would loose some of its properties (performance?) by allowing the user to change the template on the fly.

**Comment by dagnelies** [comment]
As far as I know, you can't change the template.

But what you can do is reset a partial at runtime ...which is, in the end, almost the same. However, from my experience, doing so is currently a bit unstable sometimes and lead to difficult to isolate bugs like #2452

**Comment by fskreuz** [comment]
Instead of dynamically changing the template, you can predefine the template and just let Ractive flip it over using data.

```js
var Component = Ractive.extend({
  template: `
    {{#if condition }}
      <div>...</div>
    {{else}}
      <span>...</span>
    {{/if}}
  `
});
```

Most of the time I do this, I end up writing too much code inside the blocks (and the component in general) that I splinter them off to their own components.

**Comment by brucou** [comment]
Allright, thanks for the tips. Yeah, dynamic insertion of component is full of traps (potential side-effects with respect to scoping, etc.). My use case is routing. I might end up diffing 'manually'. I detail it here in case you can give some advice on the best way to proceed :  

- T1 : the url `cp1/cp2/cp3?param_key=param_value` leads to the following template `<Component1/><Component2/><Component3 param_key = param_value/>`
- T2 : the url changes to `cp1/cp2/cp3?another_param_key=another_param_value` leads to the following template `<Component1/><Component2/><Component3 another_param_key=another_param_value />`. That behaviour I understood could be achieve by using the regular `data` property, and writing the template as `<Component1/><Component2/><Component3 {{another_param_key}}={{another_param_value}}/>`
- T3 : the url changes to `cp2/cp4`.  So the template would become `<Component2/><Component4/>` And of course ideally ractive would understand that it needs to delete/disable/destroy `cp1` and `cp3` and instantiate `cp4`. 

I strongly suspect that there is no way to implement such behaviour in ractive. I want to confirm my suspicions, and know if you know of any easy workaround. As I said, I could put something in between the router and the ractive engine to do the Component-level diffing. Component-level diffing is not such an easy task, but it is better than recreating the whole component hierarchy anew.

**Comment by fskreuz** [comment]
> I strongly suspect that there is no way to implement such behaviour in ractive.

Routers aren't an out-of-the-box thing for Ractive, but is relatively easy to build one using components. I even built my own based on Page.js. 

All you need to do is build a Router component that listens to url changes. When the url matches the current route, you show the contents. Otherwise, you hide it. Removing or hiding depends on stuff like if you want to transition or just plainly detach.

I believe the following is an example of how I did mine. Not the actual thing, but the idea is there.

```js
export default Ractive.extend({
  data: {
    route: ''
  },
  template: `
    {{# routeMatches }}{{ yield }}{{/}}
  `,
  oninit(){
    // Register this.get('route') to Page.js
    // Hook on to the entry and exit handler to toggle routeMatches
  }
});
```

Usage would be as easy as:

```js
import Route from 'path/to/route.js';
import AboutPage from 'path/to/about.js';
import HomePage from 'path/to/home.js';

export default Ractive.extend({
  template: `
    <Route route="/"><HomePage /></Route>
    <Route route="/about"><AboutPage /></Route>
  `,
  components: {
    Route,
    AboutPage,
    HomePage
  }
});

**Comment by martypdx** [comment]
Here's a dynamic component you can toggle via component name of a data property:

```js
Ractive.components.view = Ractive.extend({
    template: '<component/>',
    components: {
        component: function() {
            return this.get('name');
        }
    },
    oninit: function(){
        this.observe('name', function(){
            this.reset();
        }, { init: false});
    }
});
```

and use like:

```html
<view name="{{page}}"/>
```

see http://jsfiddle.net/s7k219s0/

**Comment by dagnelies** [comment]
@brucou Hi, this sounds fairly abstract. Could you make a more concrete example? ...perhaps the right way is completely different/simpler.

**Comment by brucou** [comment]
@fskreuz : I like the hack. One disadvantage I can see is that you then need to pass all those present and future components in that template, which might result in loading a large file. For small application, it should not be much of a problem though. And it is quite simple to get one's head around it. Performance after all is parsed should also be very similar I guess.

@martypdx Very neat as well. Is that what is described [here](http://docs.ractivejs.org/latest/advanced-configuration) under the `component` section? I read it but did not imagined it could be used like that. That would definitely be useful in a number of cases but I would worry that it would not be flexible enough to cover the routing problem in general.

@dagnelies To give you more context. I am looking to use ractivejs with cyclejs/rxjs. It gives an easy path to components that does not exist so far with cyclejs and its performance remains quite good and not so far from VDOM (can't put my hand on the performance comparison now). So one important thing to that endeavour is routing.

Routing basically is matching an url with a set of (component, component state). The component part of the tuple is usually derived from a lookup table. The component state is generally derived from the url, usually from the param section of that url.

An example of lookup table : 

```
"/" : HomePage
"/about": AboutPage
"/:user": UserComponent
```

An example of component state passed through url:
`http:www.website.com/username?show=address, fullname&avatar=small`

This url in conjunction with the routing lookup table should produce the following template:

<HomePage/>
<UserComponent username=`username` show='address,fullname' avatar='small' />

Changes to the url should result automatically to the corresponding changes in the template, leading ideally to an optimized rendering (not rerendering the unchanged part of the template)

**Comment by fskreuz** [comment]
> One disadvantage I can see is that you then need to pass all those present and future components in that template, which might result in loading a large file.

For production use, it's advised to [write in component files and use loaders](https://github.com/ractivejs/component-spec). Some loaders allow pre-compilation. When templates are precompiled, they're converted into a lightweight AST version of the template instead of the full markup.

**Comment by dagnelies** [comment]
@brucou ...just as a tip :wink: 

![not_smart](http://www.azquotes.com/picture-quotes/quote-debugging-is-twice-as-hard-as-writing-the-code-in-the-first-place-therefore-if-you-write-brian-kernighan-66-91-06.jpg)

If you use several libraries, especially complex ones, and you or one of the libs has a bug or the something in one library produces a side-effect in another ...which will surely occur at some point ...you'll spend a very happy time debugging

**Comment by brucou** [comment]
@dagnelies thanks for the tip. At the same time, I will tell you that debugging makes you a smarter programmer. And the experience of others does not replace yours. So we'll see. But are you saying that ractive is buggy? Because Rxjs is very extensively tested, and I haven't had a bug with it in two years (precisely because I spent extensive time debugging in the beginning), and cyclejs core is ridiculously small, so the most complex library here is ractive. Should I not use ractive because it is too complex? What are the ractive features which are more risky to use?

**Comment by dagnelies** [comment]
Well, it's up to you. As a rule of thumb, I'd say that `latest` is relatively stable, while `edge` is in flux and more unstable. Please also note that ractive was never meant for routing. I think that "hot" template replacement is indeed one of the areas where you *might* encounter bugs.

**Comment by brucou** [comment]
@fskreuz : have you used this router often? Did you encounter bugs that I should be aware of? Or any traps to be avoided?

@dagnelies If I find a bug, I'll make sure to report it here. That can only help improve ractive. I know it is not intended as a router but it is not about intents, it is about specs. So if I can do a half-decent router with the documented specs, then I can. And that would be a testament of the quality of the thoughtfulness of ractive design. If I can't, then I'll try something else, no worries, I can always combine rxjs/cyclejs with react to take advantage from react components, there is already a library doing that. It is just that I have a preference for Ractive.

**Comment by fskreuz** [comment]
@brucou Using this way of routing? Yes. If you're looking for a reusable version of it, I have none. It's just a wrapper to Page.js, one that's fairly easy to remember and write.

As for traps, Page.js does need to be initialized by calling `Page.start()` once _after all routes have been registered_. I normally put a dummy parent component that calls it in its `oncomplete` handler.

The app markup looks like:

```xml
<!-- This component calls Page.start() -->
<Router> 
  <!-- These components handle the route matching and toggling of components -->
  <Route path="/"><Home /></Route> 
  <Route path="/about"><About /></Route>
</Router>
```

**Comment by brucou** [comment]
@fskreuz I know about page.js but I already wrote my own router, so no problem. Alright thanks. Thanks everybody for all the insights, I am closing this for now.
