### ISSUE TITLE
Bug: Changing data for select breaks binding for object values

### ISSUE THREAD

**Issue by ADantes** [ractivejs/ractive#2460]
http://jsfiddle.net/sr1vxpzo/
1) Change value in select.
2) Observe that the correct object is displayed
3) Click "More" button
4) Change value in select
5) Observe that all values in select now just yields the string "[object Object]"

**Comment by kouts** [comment]
I' don't think you can set the option value to ```{{this}}```
Change it it to id instead: http://jsfiddle.net/sr1vxpzo/2/

**Comment by guilhermeaiolfi** [comment]
It works in edge. It replaces the selection because although the selected object looks the same, it's not. http://jsfiddle.net/sr1vxpzo/3/

**Comment by ADantes** [comment]
Yep, Edge acts exactly the way I would expect.

**Comment by fskreuz** [comment]
Feel free to close if fixed on edge.
