### ISSUE TITLE
Computations survive the destruction of the components that own them

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#2461]
Normally this isn't observable, but in certain cases involving reference expressions the computation continues to update after the component that owns it has been destroyed: http://jsfiddle.net/6xnLt2jy/1/. (The fact that reference expressions involving computations – e.g. `{{foo[bar]}}` where `foo` is computed – cause the computation to be re-evaluated as their containing sections are being destroyed is probably the more important bug, since a dormant computation is presumably harmless, though to be honest having been out of this codebase a while I'm not certain)

**Comment by evs-chris** [comment]
Would overloading `mark` on `ExpressionProxy` and `ComputationChild` to not actually force an update when `mark`ing (just set a dirty flag) work? Just mark the deps and children and let the actual change check happen as the deps ask for the value... that would effectively defer the `retrieve` that triggers the issue until after the section is removed, which would avoid the pull on the model from the interpolator. I think. :confounded:

**Comment by Rich-Harris** [comment]
I had a similar thought, and tried adding a `mark` method to `ReferenceExpressionProxy` (which is the offender here, rather than `ExpressionProxy`, though perhaps both behave similarly), and immediately got *more* test failures, so shelved that line of enquiry for the time being. But it seems likely that the proper solution lies in that direction. Going to have a prod and see what's behind the new failures.

Curiously, `ExpressionProxy.prototype.mark` looks like this...

```js
mark () {
  this.handleChange();
}
```

...whereas `ReferenceExpressionProxy.prototype.handleChange` looks like this:

```js
handleChange () {
  this.mark();
}
```

Pretty sure I wrote both. Can anyone explain to me what I was *trying* to write? Nothing more humbling than being completely stumped by your own code

**Comment by evs-chris** [comment]
I didn't have much time to poke, but, while almost certainly incomplete, this passes the tests:

```diff
diff --git a/src/view/resolvers/ReferenceExpressionProxy.js b/src/view/resolvers/ReferenceExpressionProxy.js
index 6523251..744875a 100644
--- a/src/view/resolvers/ReferenceExpressionProxy.js
+++ b/src/view/resolvers/ReferenceExpressionProxy.js
@@ -3,7 +3,7 @@ import { REFERENCE } from '../../config/types';
 import ExpressionProxy from './ExpressionProxy';
 import resolveReference from './resolveReference';
 import resolve from './resolve';
-import { unbind } from '../../shared/methodCallers';
+import { handleChange, mark, unbind } from '../../shared/methodCallers';
 import { removeFromArray } from '../../utils/array';
 import { isEqual } from '../../utils/is';
 import { escapeKey } from '../../shared/keypaths';
@@ -142,11 +142,27 @@ export default class ReferenceExpressionProxy extends Model {
        }
 
        get () {
-               return this.model ? this.model.get() : undefined;
+               const value = this.model ? this.model.get() : undefined;
+               if ( this.dirty ) {
+                       this.dirty = false;
+
+                       if ( !isEqual( value, this.value ) ) {
+                               this.value = value;
+
+                               this.children.forEach( mark );
+
+                               this.deps.forEach( handleChange );
+                               this.clearUnresolveds();
+                       }
+                       this.value = value;
+               }
+               return value;
        }
 
        // indirect two-way bindings
        getValue () {
+               if ( this.dirty ) this.get();
+
                let i = this.bindings.length;
                while ( i-- ) {
                        const value = this.bindings[i].getValue();
@@ -176,6 +192,12 @@ export default class ReferenceExpressionProxy extends Model {
                return this.childByKey[ key ];
        }
 +       mark () {
+               this.dirty = true;
+               this.children.forEach( mark );
+               this.deps.forEach( handleChange );
+       }
+
        retrieve () {
                return this.get();
        }
```

As to what you were _trying_ to do, I'm not sure, but I can say that if your brain works anything like mine, you probably got twisted up in the model/dep (which looks like template) combo that is a `Proxy`.

**Comment by guilhermeaiolfi** [comment]
Any chance to write an overview of how the classes are connected and what are they meant to do?

So people like me that would like to understand how the internals works can get the big picture before getting into the code.

Nothing fancy. Just a sentece or two for each important class. That would help a lot.

**Comment by evs-chris** [comment]
I have a branch with some readme mds added in a few places in src. I should probably finish those up and PR them...

**Comment by Rich-Harris** [comment]
> I didn't have much time to poke, but, while almost certainly incomplete, this passes the tests:

Nice – I'd made some progress (which I forgot to check in before leaving the office, d'oh) which among other things involved making `ReferenceExpressionChild` lazy in the same way as `ReferenceExpressionProxy` is supposed to be, but I didn't manage to get all the tests passing (couple of two-way binding cases acting up) so I'll take a look at that tomorrow when I'm back in. Also there were a couple of failures in the `enhance.js` tests, but I think they're unrelated/pre-existing.

Readmes alongside source sounds great, some stuff doesn't really work as a comment. And being away from the code from a while brings home how steep the learning curve is.

**Comment by JonDum** [comment]
>I have a branch with some readme mds added in a few places in src. I should probably finish those up and PR them...

Honestly... I think the src files are the best place for that. There are tiny comments here and there, but I'm constantly baffled by things in the source. I would really love to see some larger comment blocks explaining the idea and purpose of various classes. Ractive really needs other people working on the core stuff than you and sometimes Rich/Marty. Helping us other devs understand the scary internals would go miles in that regard.

**Comment by Rich-Harris** [comment]
> Ractive really needs other people working on the core stuff than you and sometimes Rich/Marty.

True dat. And my natural instinct is to agree that inline comments are generally the best place to document what code does, but I do think @evs-chris's idea has a lot of merit:

* Explanatory code comments would live alongside things like `// Exit early if no adaptors`, `// TODO remove this legacy nonsense`, `// massive temporary hack to enable array adaptor` and so on (to pick three from `Model.js` – so there's a bit of mode-switching involved in reading them
* A README file serves a directory rather than an individual file, which is arguably more useful in terms of providing familiarity with the structure of the codebase
* We can add links (including to other READMEs), headers, asides, formatted code blocks (HTML as well as JS) – much more readable, especially if we're using GitHub itself to read them
* It's more obvious which areas of the codebase aren't well documented – it's the directories that don't yet have a README
* The act of producing and maintaining the READMEs is likely to expose weaknesses in our thinking that code can easily mask

In any case, I think we all have the same goal – strengthening the library's future by making it easier for people to contribute

**Comment by JonDum** [comment]
100% with you. Some READMEs with some of your guys's high level thoughts and ideas would go a super long way.
