### ISSUE TITLE
<select value="{{foo.0.bar.0}}"> + ractive.set == Big Bad Bug

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2467]
Hi,

One more edge bug:

http://jsfiddle.net/xc2o8y08/65/

...a nasty one this time since the ractive data-binding breaks on the whole page as a consequence

**Comment by evs-chris** [comment]
Array wrapper strikes again... if you aren't using modified arrays (you use `ractiveInstance.splice(keypath, idx, ...)` instead of `array.splice(idx, ...)`), you can use `modifyArrays: false` as a config parameter to work around for now.

**Comment by dagnelies** [comment]
Just as a note: it breaks in the `select` but works fine in an `input`

**Comment by dagnelies** [comment]
thanks @evs-chris
