### ISSUE TITLE
Aliasing both key and value in iteration blocks

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2475]
Wondering if possible (or makes sense) to support in ractive, for instance:

```
var teams = {'Mavericks': ['Dirk', 'JJ'], 'Spurs': ['Tim', 'Cedric']}
{{#each teams:team,players}}
```

Maybe it could be used for lists too:

```
{{#each players:i,player}}
```

When you have more than one iteration block the template can become littered with `this` and `.` and it's not as clear as I'd like.

**Comment by MartinKolarik** [comment]
It's currently possible using an additional `{{#with}}` block, but this might be a good addition.

```html
{{#each players:i}}
  {{#with this as player}}
    {{i}}: {{player}}<br>
  {{/with}}
{{/each}}
```

**Comment by evs-chris** [comment]
Good news! While still undocumented (working on it :smile:), this is supported on edge via aliasing:

`{{#each teams as players:team}}`
`{{#each players as player}}`

Also, if the `:` syntax is a bit much, you can still use `{{@key}}` and `{{@index}}`.

**Comment by MartinKolarik** [comment]
Ah, so it *does* work! I thought aliasing might work with `{{#each}}` too, but used wrong syntax :smile:

**Comment by woodlandhunter** [comment]
Great... I'm on edge so I can use now.

I set up a fiddle to check it out [here](http://jsfiddle.net/k24qm45k/).

is the `as` aliasing documented anywhere?

**Comment by guilhermeaiolfi** [comment]
Nice one. v0.8 is going to be so good If it's ever released.

Thanks.

By the way, what is holding an alpha/beta version back? so it could get any visibility outside github.
