### ISSUE TITLE
memory issues with ractive edge

### ISSUE THREAD

**Issue by fgan** [ractivejs/ractive#2477]
Hello,

I was testing component construction with ractive edge, and I noticed that memory utilization goes up as I load/reload the same data. Here is the fiddle: http://jsfiddle.net/ax61fysj/. When I alternate between the "load data" and "load blank" buttons, I see the JS heap increase from Chrome dev tools.

**Comment by dagnelies** [comment]
Hi,
I can confirm this. In latest, after a while (clicking many times on load data / load blank), the dom nodes seem to be garbage collected. In edge, they appear to be kept in memory forever. Using the chrome "timeline/memory" is pretty handy to see this.

**Comment by lupesko** [comment]
+1
What is the plan for the next release?

**Comment by fskreuz** [comment]
@fgan Yup. Definitely seeing it.

![screen shot 2016-03-31 at 8 07 07 am](https://cloud.githubusercontent.com/assets/1582932/14175247/bfa397f0-f717-11e5-8805-371dac55b4a1.png)

@lupesko [This PR](https://github.com/ractivejs/ractive/pull/2022)(and everything referencing it) sums up what 0.8 is going to be.

**Comment by JonDum** [comment]
I can't believe the legendary "0.8 is tree-lined" post was 8 months ago...

**Comment by lupesko** [comment]
@fskreuz - lots of folks are eager to get 0.8 - when can we expect it?

**Comment by fskreuz** [comment]
> I'm afraid we adhere to the John Carmack 'when it's done' philosophy of release cycles...
> @Rich-Harris , https://github.com/ractivejs/ractive/issues/2077#issuecomment-136003028
>
> when asked for a release date on a new title, Carmack will usually reply that the game will be released "when it's done."
> https://en.wikipedia.org/wiki/John_Carmack#Personal_life_and_philosophy

I'm probably going to post this somewhere in the README. This question is getting famous. :smile:

**Comment by MartinKolarik** [comment]
As to when it's going to "be done", there's about 20 open issues that need to be resolved (mostly regressions).
