### ISSUE TITLE
Unexpected newlines before and after interpolated value in Ractive.js v0.8.0-edge

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2485]
**Description of the bug:**:
Edge is adding unexpected newlines where 0.7.3 did not.  I've linked to an example run two ways (with 0.7.3 and with Edge) to show the change in behavior.

**Versions affected:**
	Ractive.js v0.8.0-edge
	Sat Apr 02 2016 22:38:06 GMT+0000 (UTC) - commit 9b0c45d6fce87b096196d37a489feb00fee63411

**Platforms affected:**
Chrome Version 49.0.2623.110 m on Windows 10
also on MS Edge and IE11 on Windows 10

**Reproduction:**
RactiveJS 0.7.3 (no unexpected newlines in style section of template)
http://jsfiddle.net/5n85mkds/

![ractivejs-0 7 3-style](https://cloud.githubusercontent.com/assets/2102919/14230400/682ac68e-f923-11e5-81bd-33923906fe9e.png)

RactiveJS Edge (unexpected newlines after ```font-size:``` and the interpolated value for ```{{size}}``` (= **36**) in the style section of the template)
http://jsfiddle.net/8h8a3y94/

![ractivejs-edge-style](https://cloud.githubusercontent.com/assets/2102919/14230384/572d4b46-f922-11e5-84a7-0daeb29d7a87.png)

**Code:**
HTML
```HTML
<main></main>
```

JavaScript
```JavaScript
var ractive = new Ractive({
    el: 'main',
    template: '<style>p {color: red; font-size: {{size}}px;}</style>   <p>hello</p>',
    data: {
        size: 36
    }
});
```

**Comment by evs-chris** [comment]
It looks like Ractive isn't actually adding newlines. I'm guessing since each text segment and interpolator gets its own DOM node, the various inspectors show them on separate lines.

Is this causing issues somewhere? I don't think it would, but if it is, we can add a special element handler for style tags that sets innerHTML/cssText/whatever when rendering instead of just letting the normal element render process handle it.

**Comment by Jeff17Robbins** [comment]
I have a much more complex case where it might be causing an issue.  Something changed from 0.7.3 to edge and this is what I first noticed as a difference in generated DOM.  I will keep investigating.  

How easy would is it to add a special element handler?

Also, is it "unusual" to have sequential Text nodes like that, rather than coalescing the text content into one node?

**Comment by Jeff17Robbins** [comment]
In RactiveJS 0.7.3, the ```<style>``` element in the test has one child text node.
In Ractive.js v0.8.0-edge, the ```<style>``` element has three child text nodes.

My issue title is wrong, as @evs-chris already stated; the apparent newlines are due to Chrome's inspector showing each text node on its own line.

It appears that Ractive.js v0.8.0-edge has a finer-grained approach to text interpolators than RactiveJS 0.7.3.  I doubt this change is the source of my actual problem.
