### ISSUE TITLE
#with badly broken in edge!

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2489]
Hi,

the `#with` is badly broken in edge:

http://jsfiddle.net/xc2o8y08/68/

**Comment by MartinKolarik** [comment]
That's an intended breaking change. See #1856.

**Comment by dagnelies** [comment]
Ok, thanks, I miss a lot of things.

Updated doc. https://github.com/ractivejs/docs.ractivejs.org/pull/252
