### ISSUE TITLE
Ractive Edge Template Doesn't Notice New Data Type

### ISSUE THREAD

**Issue by paulie4** [ractivejs/ractive#2490]
**Description of the bug:**
If a Ractive instance starts out with no data for a keypath that is iterated over in the template, it seems like it is caching the assumption that it will be an array instead of an object.

**Versions affected:**
Ractive.js v0.8.0-edge
	Sat Apr 02 2016 22:38:06 GMT+0000 (UTC) - commit 9b0c45d6fce87b096196d37a489feb00fee63411

**Reproduction:**
http://jsfiddle.net/9sLs4h3n/

**Code:**
```html
<div id="container"></div>
<script id="template" type="text/ractive">
  {{#each heap:key}}
  <div>{{key}}</div>
  {{/each}}
</script>
```

```javascript
ractive = new Ractive({
  el: 'container',
  template: '#template',
  data: {
/*    heap: {
      key1: {
        a: 'optiona',
        b: 'optionb'
      },
      key2: {
        a: 'optiona',
        b: 'optionb'
      },
      key3: {
        c: 'optionc'
      }
    }*/
  }
});
ractive.set('heap', {
  key1: {
    a: 'optiona',
    b: 'optionb'
  },
  key2: {
    a: 'optiona',
    b: 'optionb'
  },
  key3: {
    c: 'optionc'
  }
});
```

Expected results:
```
key1
key2
key3
```

Actual results:
```
0
1
2
```

**Comment by MartinKolarik** [comment]
Fixed - thanks for reporting.
