### ISSUE TITLE
Ractive.js v0.8.0-edge observe *.* problem

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2503]
**Description of the bug:**
`observe('* *.*', ...)` works in Ractive.js v0.7.3 but doesn't in Ractive.js v0.8.0-edge

**Versions affected:**
Ractive.js v0.8.0-edge

**Platforms affected:**

**Reproduction:**
Ractive.js v0.7.3 (works)
http://jsfiddle.net/bhpamt0s/

![r 7 3 wildcards](https://cloud.githubusercontent.com/assets/2102919/14359838/6a3a6ec4-fcc1-11e5-88aa-f5256f245a64.png)

Ractive.js v0.8.0-edge (doesn't)
http://jsfiddle.net/xsrmz3bx/

![r 8 0 wildcard](https://cloud.githubusercontent.com/assets/2102919/14359847/79130938-fcc1-11e5-82b7-c796e30af83f.png)

**Code:**
HTML
```html
<div id="container"></div>
<script id="template" type="text/ractive">
    <div>{{counter}}</div>
    <ul>
    {{#list}}<li>{{.}}</li>{{/list}}
    </ul>
</script>
```

JavaScript
```javascript
ractive = new Ractive({
    el: 'container',
    template: '#template',
    data: {counter: 0, list:['a', 'b', 'c']}
});

var obs = ractive.observe('* *.*', function(newValue, oldValue, key) {
    console.log(key, newValue);
});

ractive.add('counter');
```

**Comment by evs-chris** [comment]
Fixed. Thanks for the report!
