### ISSUE TITLE
Component event bubbling only works 1 level deep

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2504]
**Description of the bug:**

With nested components inside components inside components, the bubbling and redirection of events stops at one level up.

**Versions affected:**

0.7.3, edge

**Platforms affected:**

Chrome 49

**Reproduction:**

http://jsfiddle.net/jondum/gkm3xptj/

**Code:**

``` html
  <bar on-select='log'></bar>
```

``` js
/*

    <main>
        <bar>
            <foo></foo> <-- sends "select" event on click
        </bar> <-- listens for "select", fires "log"
    </main> <-- listens for "log"

*/

var foo = Ractive.extend({
  template: `<div on-click='test'>Click me</div>`,
  oninit() {
    this.on('test', e => {
        this.fire('select', 'hi');
    });
  }
})

var bar = Ractive.extend({
  template: `<foo></foo>`,
  components: {
    foo: foo
  },
})

var ractive = new Ractive({
  el: 'main',
  template: '#template',
  components: {
    bar:bar 
  },
  oninit() {
    this.on('log', function() {
            alert('it worked'); // should be sending alerts, but isn't
    })
  }
});
```

**Comment by guilhermeaiolfi** [comment]
Shouldn't you be firing the ```log``` event instead of ```select```?

That way it works.

**Comment by JonDum** [comment]
No, I don't have control of what the innermost component fires (`foo` here).

This is how I imagine it should work:

1. `foo`, which is inside `bar`, fires a `select`
2. `select` bubbles to `bar` (not working?)
3. In the root scope, listen for a `select` on `bar` and call/fire `log` when it gets it (like a redirect/proxy of sorts)

Am I totally off in this thinking?

**Comment by guilhermeaiolfi** [comment]
I don't see where ```bar``` is listen or firing anything. For me ```bar``` is not doing what you say it's doing. So, the only thing that is bubbling is ```select``` and you listen for ```log```. So I wouldn't expect it to work like you want.

**Comment by fskreuz** [comment]
`bar` doesn't seem to "re-fire" the event so `main` gets nothing.

There was a discussion about this before. It was something about namespacing bubbled events by component name. Not sure where that was or if it was ever implemented, but I'm pretty sure @martypdx was on that thread.

**Comment by martypdx** [comment]
Generally speaking, events are bubbled outside of (non-isolated) components with the event name modified via prefix of the tag name defined in the parent component. Without any template defined handlers, you can catch `foo.select` anywhere above `foo` in the view heirarchy. See http://jsfiddle.net/j2m34x6e/

Event handlers on component directives have some special behaviors. They cancel the component event from bubbling (which will happen on any return of `false` as well). They also can use the component prefixed event names, which is required in this case because `foo` is raising the event, not `bar`:

```html
<bar on-foo.select='log'></bar>
```

And the new event is being fired from the component that is "hosting" the above code, so the handler inside which is at the same level should not be prefixed (you could use `'log *.log' if you wanted to catch either):

```js
    this.on('log', function(n,o,k) {
    	console.log(arguments)
    });
```

See http://jsfiddle.net/mufoukg9/

Most of this is in the docs [here](http://docs.ractivejs.org/latest/event-bubbling)

**Comment by JonDum** [comment]
@martypdx Are there technical reasons for the namespaced bubbling? I've read that doc page at least a dozen times over the years and I had assumed (incorrectly) that the namespaced event was optional if you were trying to be specific on which event to listen to.

The way it is now is very limiting: your event listener's have to be aware of whether or not a component is firing it, and account for that in the name, making them not easily portable. :(

**Comment by martypdx** [comment]
@JonDum I guess I have the opposite viewpoint that namespacing events _helps_ manage events in view hierarchies and not having them would be event spam hell.

> your event listener's have to be aware of whether or not a component is firing it, and account for that in the name, making them not easily portable

A component knows at a bare minimum whether or not it is catching events raised by itself or a child component. In my mind the events raised are part of the api of a component, and given that the host of a component determines the namespace, there's a consistency within that component:

```html
<div><some-component/></div>
```

```js
this.on( 'some-component.select', (e, index) => {
    this.set( 'selected', index );
} );
```

I also think robust support for component template events in `0.8` makes things much easier:

```html
<div><some-component on-select="set('selected', $2)"/></div>
```

**Comment by evs-chris** [comment]
I think #2566 is an acceptable solution to this, so I'm going to punt it over there. Feel free to re-open if it's not :smile:
