### ISSUE TITLE
Issue building on windows (with bash)

### ISSUE THREAD

**Issue by ISNIT0** [ractivejs/ractive#2507]
**Description of the bug:**
When trying to build Ractive (dev branch) with `npm run build` on my windows machine (for work), I get the following error:
![image](https://cloud.githubusercontent.com/assets/5173131/14422921/fcc850f0-ffd0-11e5-86e5-f6fb47f2d185.png)

I have previously built Ractive a few times with the same setup (perhaps a minor version of npm/node different). I started going through the script file (removing \r characters that should be \n characters), but my bash foo is lacking when it comes to finding syntax errors in this stuff:
![image](https://cloud.githubusercontent.com/assets/5173131/14423047/b3393660-ffd1-11e5-9dd5-1313f5a959ae.png)

I'm assuming the \r characters are from a merge tool when @martypdx did his 'super merge' :) because it seems similar areas that were modified in those commits are breaking for me:
https://github.com/ractivejs/ractive/commits/dev/scripts/build.sh
https://github.com/ractivejs/ractive/commit/c8a4fb22292e3718b0dd4be53cd8c6ceff82c2f0#diff-5

Any thoughts on how to proceed? I'm happy to look into this further, but if anyone knows what the problem might be already, it would save some time :+1: 

**Versions affected:**
Bash (4.3.42):
![image](https://cloud.githubusercontent.com/assets/5173131/14422899/e776945a-ffd0-11e5-9345-779dd561b730.png)

Windows 10 (10.0.10586):
![image](https://cloud.githubusercontent.com/assets/5173131/14422952/1deaf184-ffd1-11e5-993b-ade4b6459315.png)

Node and NPM:
![image](https://cloud.githubusercontent.com/assets/5173131/14422977/4f839b10-ffd1-11e5-9916-551ea1754666.png)

**Platforms affected:**
See above

**Reproduction:**
See above

**Code:**
N/A

**Comment by sabob** [comment]
I'm using [git bash](https://git-scm.com/downloads) on Windows 10 to build. Maybe you can give it a try.

**Comment by ISNIT0** [comment]
@sabob That seems to be working, Not sure what the difference between my normal bash and 'git bash' is!

**Comment by dagnelies** [comment]
It's frequent that git tools have a setting to automatically convert `\n` in `\n\r` on checkout and back on checkin. Probably it did just that, thereby breaking the `sh` scripts for your tools. And probably the git bash is able to cope with the line endings nevertheless.

**Comment by sabob** [comment]
Interestingly, once I ran the ractive build once in git bash, I can also run it in cmd, so git bash probably converts the line endings?

**Comment by fskreuz** [comment]
iirc, [Git for Windows](https://git-for-windows.github.io/) (the one with an orange icon) is configured to handle line ending sorcery for you by default. I think the related setting is [`git config --global core.autocrlf true`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace).

Might also be worth mentioning which "bash" you are referring to, as the Windows will get its own Bash soon.
