### ISSUE TITLE
Ractive error: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

### ISSUE THREAD

**Issue by jwenger100** [ractivejs/ractive#2509]
Description: I am working with an app with Ractive.js.  I am running into an issue with the on-blur event throwing an exception when I am trying to transition between views. I get the exception "Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?" from the detach.js code in Ractive where it is trying to call parentNode.removeChild( node );  The following scenario results in this behavior.  I have a decorator on my text box components, which have an on-blur event.  I clean up the event handlers in the teardown of the decorator.  The scenario occurs when I am in either text box, type something in, and press 'Enter' on the keyboard.  I receive the error when the ractive.teardown() is being executed in conjunction with the decorator's blur event handler, which causes a promise chain to fail in my application (I have excluded this piece of complexity from my jsfiddle example as it is not needed to reproduce the error).  The interesting part is that it all works fine, until I am trying to do a ractive.set() in my decorator's blur event handler.  It seems to be some sort of relationship between ractive.set and the ractive teardown of the view/component executing in parellel. As soon as I remove the ractive.set from the blur handler, everything works fine.  Also, it only seems to happen if my input is defined as a component (subview).  If put all the markup into the main control, it seems to work. 

I am wondering if there is a different pattern I can use in my application to avoid this scenario, or if a check is needed in Ractive to ensure this error won't happen.

Version of Ractive effected: 0.7.3

Platform effected: Mac OSX: 10.10.5 
                             Chrome: 48.0.2564.103
1. Run the application
2. Enter any value into either textbox
3. Press 'Enter' on the keyboard
4. Observe the exception in the debugger console

https://jsfiddle.net/jwenger100/dh9c4qL3/1/

Full code:  [Ractivejs_codeSample.txt](https://github.com/ractivejs/ractive/files/213804/Ractivejs_codeSample.txt)

```
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.js'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/ractive/0.7.3/ractive.js'></script>

  <div id='container'></div>
```

``` javascript
  var inputValidation = function ( node, content ) {
  var handlers, eventName,
      $node = $(node),
      $inputNode = $node.find('input');

  handlers = {
    blur: function () {
        ractive.set('myProp', '');
        console.log('called ractset');
    }
  };

  // Add event handlers to the node
  for ( eventName in handlers ) {
    if ( handlers.hasOwnProperty( eventName ) ) {
      $inputNode.on( eventName, handlers[ eventName ] );
    }
  }

  return {
    teardown: function () {
        for ( eventName in handlers ) {
          if ( handlers.hasOwnProperty( eventName ) ) {
            console.log('removing ' + eventName + ' event handler!');
            $inputNode.off( eventName, handlers[ eventName ] );
          }
        }
    }
  };
};

var outerTemplate = '<div><div><div><form id="myform" method="POST" action="javascript: console.log(\'posted!\');" ><p>Hello, {{name}}!</p><myInput id="userNameField" /><myInput id="passwordField" /><input type="submit" value="destroy view"/></form></div></div></div>';
var innerTemplate = '<div decorator="inputValidation"><input id="{{id}}"></div>';
var myRactive = Ractive.extend({
    template: innerTemplate,
    'onconstruct': function( component ){
        if(component.el === '#container') { return; }
        component.decorators = { 'inputValidation':inputValidation};
        }
});

var ractive = new myRactive({
      el: '#container',

      template: outerTemplate,

      components: {
          myInput : myRactive
      },

      data: { name: 'world' }

    });

    var mySubmit = function(){
        ractive.teardown();
        return false;
    };
    $('#myform').submit(function(){
        mySubmit();
    });
```

**Comment by fskreuz** [comment]
Kindly fix the formatting of your report :smile:

**Comment by jwenger100** [comment]
@fskreuz I think the formatting should be better now :)

**Comment by evs-chris** [comment]
I think there was a race condition in 0.7 teardown, but I couldn't quite track it down. I can confirm that the fiddle works with 0.8.3, though :smile:
