### ISSUE TITLE
Ractive removes wrong class from element

### ISSUE THREAD

**Issue by woodlandhunter** [ractivejs/ractive#2510]
**Description of the bug:**
Ractive removes wrong class from element (when the class is altered before ractive gets a chance to update).

Broken in #2453.

The problem occurs around [here](https://github.com/ractivejs/ractive/blob/dev/src/view/items/element/attribute/getUpdateDelegate.js#L236). The `value` array  contains the class to be removed, but the `attr` array does not, so `attr.splice(-1, 1)` happens, removing a class that should not be.

It looks like this could happen in other places too (e.g styles).

(I know it's a bit shaky to modify the DOM from underneath ractive, but I am using a UI lib which modifies the classes on it's own.)

**Versions affected:**
Ractive.js v0.8.0-edge
Mon Apr 11 2016 19:30:36 GMT+0000 (UTC) - commit 4a5b7cd4b74fa1ba240781aba5b86a3292bee644

**Reproduction:**
http://jsfiddle.net/k80ngnyk/

(Watch the classes in inspector)

**Comment by evs-chris** [comment]
Oops :smile:. Thanks for the report!

**Comment by evs-chris** [comment]
Also, this isn't really an issue for inline styles because they are not a list and thus not spliced. If you modify an inline style outside of ractive and ractive goes to remove the style, it will still remove the external change for _that_ property. No other properties should get stepped on though.

**Comment by martypdx** [comment]
@evs-chris side note: the `class-className` and `style-styleName` directives currently follow the interpolation style, whereas all of the other `foo-bar` directives assume the content is already a mustache expression.

Styles are mostly interpolated, like the example I gave. Classes will be boolean expressions but require `{{ ... }}`. I was trying this example out with `class-red="active==='one'"` and then realized it need to be `class-red="{{active==='one'}}"`

We could argue either way, just need to make sure docs updated to give correct guidance.

**Comment by evs-chris** [comment]
@martypdx I hadn't thought of it from that perspective. I definitely think that `style-whatever` should use mustaches. Would it be more confusing to have style- and class- be different or to require the mustache for class- too? I was equating it to `checked="{{foo}}"` and `value="{{whatever}}"` in my head.

I don't think it would be too much trouble to add class- to the parser. What's the consensus?

**Comment by martypdx** [comment]
@evs-chris IDK! 

Let's stick with how it is and make sure to document it.

**Comment by JonDum** [comment]
@evs-chris @martypdx keep it all mustache expression for consistency!

**Comment by evs-chris** [comment]
Sounds like a plan http://docs.ractivejs.org/edge/elements
