### ISSUE TITLE
Breaking change of adaptor behaviour in edge

### ISSUE THREAD

**Issue by skeptic35** [ractivejs/ractive#2513]
I noticed a change in adaptor behaviour that makes it impossible for me to switch to edge.
Provided I have a Backbone model as ```model``` property of my ractive ```data``` and I use the Backbone adaptor. Then I do ```this.get("model")```.
In 0.7.3 that would return the original, unwrapped, unadapted Backbone model, complete with it's own ```get``` and ```set``` methods and what have you.
In edge I only get the model's attributes.
This has rather catastrophic effects on my application, especially in cases where the model is passed on to components, which then receive a POJO instead of a Backbone model.

Question is: Is that a problem of the adaptor or a problem of Ractive or - heaven forbid - an intentional breaking change?

**Comment by fskreuz** [comment]
We're aware of this one. See discussion about adaptors https://github.com/ractivejs/ractive/issues/2512 :smile:

**Comment by skeptic35** [comment]
Sorry to be bothering you again (and that after almost two months have passed...) but I don't quite see how the adaptor discussion is an answer to my question or how this issue is a duplicate to ... well I don't know what it's supposed to be a duplicate of.
Might very well just be me being to dumb but anyway...
Thing is: I'd really love to use Ractive edge and I still can't, because the Backbone adaptor is breaking my Backbone models. And I fail to see another ticket adressing that issue and I also fail to see a solution for it.

**Comment by skeptic35** [comment]
Just downloaded the latest edge version and I have the very same problem again: Wrapped models that are passed down to components are "destroyed", i. e. the component receives a POJO instead of a Backbone Model.

**Comment by evs-chris** [comment]
@skeptic35 oops, I missed a test case, so it slipped back in. It should be good now.

**Comment by skeptic35** [comment]
Yup - good now :)
