### ISSUE TITLE
Question: How to make global events

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2514]
Hi, how can I have events that are global across Ractive instances?
As a workaround I have a function:
```
Ractive.prototype.globalEvents = function(){
  this.on('*.go go', function(event, options){
        this.doNavigation(options);
  });
  this.on('*.send_data', function(event, field, value){
        console.log(event);
        console.log(field);
        console.log(value);
 });
}
```
and then I run this function oninit of every Ractive instance.
```
oninit: function(){
       this.globalEvents();
}
```
I'm sure there must be a better way.

**Comment by heavyk** [comment]
`require('eventemitter3')` or `require('events')` then just use it as normal. if you want keyspaces or wildcards, instead of using the standard EE's you can use Ractive itself as one:

```js
let g = Ractive.globalEvents = new Ractive
g.on('*.lala.*', (msg) => { console.log(msg) })
g.fire('caca.lala.lama', 'weeeee!')
...
```

**Comment by kouts** [comment]
I'm using ES5, so is there essentially a place to register all these events as is for example "Ractive.defaults.data" for helper functions?

**Comment by fskreuz** [comment]
If this data you are passing is simply actions, you can pull in _any_ event emitter library and use that. If you have jQuery, you can use `.on()` and `.trigger()` for this. You can use `document` as the rendezvous point for attaching handlers and firing listeners. Just make sure you namespace the events. Attach the listener during `oninit` or later lifecycle events, while fire the events at will.

```js
$(document).on('someEvent.ractive', handler);
$(document).trigger('someEvent.ractive', data);
```

If this data is state, consider wrapping these instances in a parent component and put the data up there. Then have the data passed down to the instances and let two-way binding to the rest of the heavy lifting.

```js
var ChildComponent1 = Ractive.extend({
  template: `<div class="child1">{{ data }}</div>`
});

var ChildComponent2 = Ractive.extend({
  template: `<div class="child1">{{ data }}</div>`
});

var ParentComponent = Ractive.extend({
  template: `
    <ChildComponent1 data="sharedData" />
    <ChildComponent2 data="sharedData" />
  `,
  data: {
    sharedData: 'Hi! I am shared!'
  },
  components: {
    ChildComponent1,
    ChildComponent2
  }
});

var app = new ParentComponent({ el: '#somewhere' });

```

**Comment by martypdx** [comment]
@kouts - If you have a single app view hierarchy, you can just put the handler in the top level component:

```js
var app = new Ractive({
    oninit () {
         this.on('*.go go', (event, options) => {
             this.doNavigation(options);
         });

         this.on('*.send_data', (event, field, value) => {
             console.log(event);
             console.log(field);
             console.log(value);
         });
    } 
});
```

If you __don't__ have a single view hierarchy, then take a look at [this comment](https://github.com/ractivejs/ractive/issues/2512#issuecomment-210006241) because I think you have the same underlying need - it would enable you to create arbitrary view hierarchies _without_ requiring template tags in parent components and thus leverage Ractive's built-in event bubbling for component events.

**Comment by kouts** [comment]
@martypdx  you re right, I don't have a single app view hierarchy. I just need a way so that all my Ractive instances share some events so that I' don't have to do it oninit of every instance.

**Comment by martypdx** [comment]
@kouts Outside of adding new Ractive functionality as I proposed, you could still go with a global events obj like @heavyk suggests. 

Otherwise, you could simplify your existing code in several ways:

Use the prototype lifecycle events to register global events. You could use `oninit`, though it is common event handler so if you override in component, you'll need to call `this._super()`. Other option is to use much less common `onconfig` event:

```js
    Ractive.prototype.globalEvents = function(){
      this.on('*.go go', function(event, options){
            this.doNavigation(options);
      });
      this.on('*.send_data', function(event, field, value){
            console.log(event);
            console.log(field);
            console.log(value);
     });
    }

    Ractive.prototype.onconfig = function () {
         this.on('*.go go', (event, options) => {
             this.doNavigation(options);
         });

         this.on('*.send_data', (event, field, value) => {
             console.log(event);
             console.log(field);
             console.log(value);
         });
    } 
```

However, it looks like in your case you could just use a prototype _method_ and skip events altogether:

```js
     Ractive.prototype.go = function(options){
            // now you don't really need a separate method as signatures are identical!
            this.doNavigation(options);
      });

      // I've removed event, you can add it back it if needed
      Ractive.prototype.send = function(field, value){
            console.log(field);
            console.log(value);
     });

    // now in any template you can do:
    // <button on-click="go({ page: 'home' })">Home</button>

    // and in any component you can do:
    this.go({ page: home });
```

**Comment by kouts** [comment]
Thanks @martypdx , does the prototype method work with the "fire" method?
So that I can do e.g ```fire('go', event, options)```

**Comment by martypdx** [comment]
> does the prototype method work with the "fire" method?

If I understand you correctly, I think the answer is yes, the `fire` method is also on the prototype:

```js
Ractive.prototype.someMethod = function(){
    this.fire('someEvent', 'foo');
}
```

> I'm trying to use the fire method so that I can be "compliant" with the new syntax suggested in #1172

Method events are still first class citizens, it's just the old event proxy syntax `on-whatever="someEvent:{{someRef}}"` that needs to be rewritten as `on-whatever="fire( 'someEvent', event, someRef )"`.

It seemed in your example using the event infrastructure doesn't buy you much beyond using a method call that is handled globally via the same prototype method on all instances.
