### ISSUE TITLE
change event in Ractive.js v0.8.0-edge -- discussion

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2529]
@Rich-Harris, three different comments in Ractive.js v0.8.0-edge src suggest that the `change` event is to be deprecated. 

version:    

```
Ractive.js v0.8.0-edge
    Fri Apr 22 2016 20:17:22 GMT+0000 (UTC) - commit af9dbf1e958a4c03827bafe0f70295c9a738733a
```

These are the 3 comments and related code:

https://github.com/ractivejs/ractive/blob/dev/src/global/runloop.js#L102

``` javascript
        // TODO deprecate this. It's annoying and serves no useful function
        const ractive = fragment.ractive;
        changeHook.fire( ractive, ractive.viewmodel.changes );
        ractive.viewmodel.changes = {};
        removeFromArray( ractives, ractive );
```

https://github.com/ractivejs/ractive/blob/dev/src/model/Model.js#L147

``` javascript
        // TODO deprecate this nonsense
        this.registerChange( this.getKeypath(), value );
```

https://github.com/ractivejs/ractive/blob/dev/src/model/RootModel.js#L16

``` javascript
        // TODO deprecate this
        this.changes = {};
```

Meanwhile, @evs-chris  has been doing non-trivial work to make the `change` event work in Ractive.js v0.8.0-edge.  

My interest in the `change` event is that we are currently using https://github.com/rstacruz/ractive-ractive (written by @rstacruz inspired by one of your examples, I think) with Ractive.js v0.7.3 and it works great.  

This adaptor relies on the `change` event.  This adaptor still doesn't work 100% correctly in Ractive.js v0.8.0-edge, but I bet we can get there.  It will take some more work.  I'm happy to continue working on it (mostly generating test scenarios -- as soon as I create a reproducible bug, it seems that @evs-chris  knocks it down, hence my confidence that we can get there!)

However, if the intent of the "deprecate" comments is that the `change` event is going to be deprecated, it would be great to understand the reasons and/or the suggested replacement for it.   

For example, I thought that maybe `ractive.observe('*')` would be a potential alternative to keeping up with all the changes, but have a concern about the loss of batching behavior -- a lot of changes get delivered atomically as a lot of .observe() callbacks instead of in one single `change` event callback -- which seems like a step backwards in efficiency?  So I am not confident that `ractive.observe('*')` is a true replacement for `ractive.on('change')`.

Also, @martypdx has suggested a possible alternative to using adaptors for Ractive instance to Ractive instance binding, by instead using a not-yet-existent `ractive.addChild()` function  that sounds like "same great taste at half the calories"!  It sounds intriguing.  Issue #2512 has some more discussion on this idea.  I don't know if that alternative requires a working `change` event` or relies on some other (internal?) feature to keep different Ractive instances in sync.

Summary: I am worried about the "deprecate" comments and want to make sure we're on the same page regarding the fate of the `change` event, hence this discussion issue.

**Comment by martypdx** [comment]
fyi, my problem with `change` is that:

1. Logically it does the same thing as `observe`. Why do we need both?
2. `change` "happens" on every change. That means creating the object with keys and values and running it up the component view stack and to look for event subscribers (yes `change` bubbles like any other event). You can't opt out, you always pay the cost of running the change event every time the data changes.

**Comment by Jeff17Robbins** [comment]
In response to @martypdx's point 1: `Logically it does the same thing as observe. Why do we need both?`

I agree that `observe` is logically _similar_ to `change`.    But both its semantics and its performance seem markedly different.  Below are two illustrations using 	Ractive.js v0.8.0-edge
	Mon Apr 25 2016 19:30:36 GMT+0000 (UTC) - commit 67b5b224e7fc6e9dd27470c12607b6fe3beea978

Here's a jsfiddle using `change`:  http://jsfiddle.net/2o7qnx14/
console output:
```
VM83 ractive.js:427 Ractive.js 0.8.0-edge in debug mode, more...
2016-04-25 15:54:42.454 VM84:57 before Object {i1: 1, i2: 2, i3: 3, i4: 4, i5: 5…}
2016-04-25 15:54:42.512 VM84:65 change: 1092.357ms
2016-04-25 15:54:42.700 VM84:67 Object {i1: 1, i2: 2, i3: 3, i4: 4, i5: 5…}
```
Here's a jsfiddle using `observe`:  http://jsfiddle.net/twg2bepj/
console output:
```
2016-04-25 16:02:34.424 ractive.js:427 Ractive.js 0.8.0-edge in debug mode, more...
2016-04-25 16:02:35.395 VM176:57 before i1 1
2016-04-25 16:02:36.329 VM176:65 observe: 1902.693ms
2016-04-25 16:02:36.505 VM176:67 Object {i1: 1, i2: 2, i3: 3, i4: 4, i5: 5…}
```

differences seen in the console output:

1. The line ```2016-04-25 16:02:35.395 VM176:57 before i1 1``` is puzzling to me.   I don't understand why I only get one value delivered to my `observe` callback.  I would have thought that setting up an `observe` prior to setting the Ractive instance's `data` would have yielded all the data once I called `set()`.  This might be an edge bug?

2. And then there's the matter of the lack of batching in `observe` -- note that the `observe` callbacks that finally do receive all the data take nearly twice as long to execute than the **single** callback that the `change` event delivers.  Even if this performance gap could be closed, the semantics of **many** callbacks vs a **single** callback are clearly different.

**Comment by Jeff17Robbins** [comment]
In response to @martypdx's point 2: `change "happens" on every change. That means creating the object with keys and values and running it up the component view stack to look for event subscribers (change bubbles like any other event, admittedly this is an issue with all lifecycle events). You can't opt out, you always pay the cost of running the change event every time the data changes.`

We aren't using Ractive components.  We're using individual Ractive instances, and keeping each instance in its own [web component](http://webcomponents.org/).  I don't know if that is relevant to this point about overhead, but thought it important to point out.

If we could leverage the model work using the mooted `addChild()` API, all the better.  Our need is to have multiple `views` subscribe (bind) to multiple `stores`.  The only reason I raised the `change` event topic for discussion is due to the fact that the [Ractive-Ractive adaptor](https://github.com/rstacruz/ractive-ractive) is currently implemented with the `change` event, and it does not work in Ractive.js v0.8.0-edge.  

(BTW, @evs-chris's fix for the `change` event in Ractive.js v0.8.0-edge seems to be working, but the  Ractive-Ractive adaptor still isn't working, either due to `update()` behavior differences or `adaptor` differences, or both.)

So...I'm not overly attached to the `change` event.  If `observe()` ought to be used, that makes good sense. (We'll just have to make sure it really does what is intended.  And perhaps come up with a way for it to send a whole batch of observations, instead of each keypath individually called back?)  

But whether `change` or `observe`, we need some way for a set of disparate Ractive instances ("views") to somehow share a piece of their models' with a "store", so that our JSON feed can update the "store" (via `update`? or `set`? or some internal magic via `addChild`?) and the disparate Ractive views get updated in a timely and efficient manner.

**Comment by Jeff17Robbins** [comment]
here is a simple, working example of the Ractive-Ractive adaptor in Ractive.js v0.8.0-edge showing a "store" and two "views".  It uses the `change` event.

http://jsfiddle.net/rexo4tkb/

This example is simpler than our app's real use case, which involves more nested objects and arrays in the store.  Something is going wrong with those more nested cases (arrays?), perhaps involving the array adaptor in Ractive.js v0.8.0-edge and how `update()` interacts with adaptors?  That's pure guesswork -- still trying to create a reproduction of the problem to share here!

It would be great to see an equivalent example using a different technique.

**Comment by evs-chris** [comment]
FWIW I think enhancing observers to cover any missed corners would be the best way forward. Between that and having a good API for managing child components, I think change could go away.

**Comment by Jeff17Robbins** [comment]
I'm on board.  To make the switchover, I see a couple of obvious topics: A) bugs and B) semantics.

A)
I am confident we can fix the remaining bugs in Ractive.js v0.8.0-edge's `observe()`.  

I know of at least 2 bugs:
 
1. the odd `observe()` behavior shown in http://jsfiddle.net/twg2bepj/ and mentioned above.

2. A "wraparound" bug I am working on a simple reproduction of.  The bug seems to involve a call to `set()` from inside an `observe()` callback wrapping around internally to calling back the `observe()`.

B)
But there's also the difference in semantics between `change` and `observe`:  namely `change` gives me all the changes in one callback, whereas `observe` gives me each keypath change as a separate callback.  

Can we enhance `observe()` to give it that batching capability as an option?  As shown above, `observe()` can be a lot more expensive than `change` if you have a lot of changes to process.
```2016-04-25 15:54:42.512 VM84:65 change: 1092.357ms```
```2016-04-25 16:02:36.329 VM176:65 observe: 1902.693ms```

Or are my numbers not taking into account the cost for `change` of accumulating `viewmodel.changes` during a processing cycle?  Even so, it seems a shame to give up an API that offers a less chatty way of getting handed all the changes.

**Comment by dagnelies** [comment]
Hi,

...just to add my two cents, I also "preferred" the `onchange` event.

Aside from this, why `change` and `observe` have been implemented with totally different logic is still a mystery to me. :confused: 

My gut feeling tells me that "under the hood" everything should trigger the `onchange` event. Then, observers would simply be a tiny layer on top of it, filtering and dispatching these to the appropriate observer listeners. That way, it would be simple, homogenous and robust.

Don't take me wrong, but there were so many things broken so often in the past regarding observers and onchange, that I think something might be seriously flawed with them. A central place collecting change events and dispatching them seems simpler and more robust to me.

**Comment by dagnelies** [comment]
Hi,

I just noticed too that observers are _REALLY_ slow.

Here is a small example of a dataset virtual scroll of mine:
http://dagnelies.github.io/ractive-dataset/big.html
Adding 10k rows takes around 40ms here. It's almost instantaneous.

Just by adding observers:
http://dagnelies.github.io/ractive-dataset/big_observers.html
...makes it utterly slow. Adding the same number of rows would take about 20 seconds.
I had to reduce it to "only" 1k rows in the link.

Wouldn't making `onchange` work and using it to dispatch the event would make it more robust, more intuitive and faster.

...and please don't ask me the measures of this in edge, because half of it is broken as usual:
http://dagnelies.github.io/ractive-dataset/big_edge.html

Ok, by now it works, here are the observers version (which is very slow):
http://dagnelies.github.io/ractive-dataset/big_edge_o.html

**Comment by evs-chris** [comment]
Recursive observers are now available on edge, and the change event plumbing has been removed. I'll leave a batching mode to a new issue if the need ever arises.
