### ISSUE TITLE
Update changelog?

### ISSUE THREAD

**Issue by TehShrike** [ractivejs/ractive#2530]
0.7 hasn't been updated in a long time, and it sounds like a good number of people are using 0.8 via edge/Github.

I'm considering doing the same, but I can't find a better changelog than looking through a massive commit/pull request list.

## Request

Could the changelog be updated to reflect all the changes that would presumably eventually be added before 0.8 is published?

I would like to at least mentally prepare to make the move, and would rather not have to click on [every closed pull request](https://github.com/ractivejs/ractive/issues?q=milestone%3A0.8+is%3Aclosed).

## Suggestion

In the few projects of my own where I maintain changelogs, I've been adding notes to the changelog under the presumable next version at the time of merging the changes, which makes it much easier to cut new releases.  I can publish when appropriate without having to retroactively build a big changelog entry.

Would that reduce publish friction for Ractive?

## Possible side discussion point

If Ractive 0.8 is the current "version in use" by the heaviest Ractive users, should it just be released as is?  Any open bugs could be released later under patch releases, and any features currently tagged for 0.8 could be bumped to 0.9, and all the current 0.9 milestone issues could move to 0.10.

I know there's usually some trepidation around large projects bumping versions, but if all the major contributors have moved on from 0.7, leaving the year-old version on npm seems a bit awkward.

### Possible side-side discussion

Versioning would be easier if 1.0.0 was out and breaking/feature/patch version numbers were all on the table.  Ractive seems pretty stable overall - unless there's some pie-in-the-sky plan to magically become even-more-stable eventually, why not take the leap past 0.x?

**Comment by TehShrike** [comment]
Sorry to the Ractive issue followers who get updates by email - I accidentally submitted this issue before I'd finished typing it.  Why haven't I learned to just write everything in my editor and paste into the browser at the last second? 😿

**Comment by evs-chris** [comment]
If you switch to edge on the docs site, the migration guide has a major- and breaking-changes list.

As to releasing 0.8, I agree that it would be good to get away from 0.7 being what everyone gets by default. Unfortunately cutting a release is a non-trivial thing and there are a few bugs that need to be addressed before that point. We're getting closer though, as I don't think there are any *super* serious bugs that don't have a potential fix pending.

**Comment by TehShrike** [comment]
What all is involved in publishing a release?  I'm guessing there are steps not in the release scripts, but I don't know where to figure out what they are.

Another question while I'm asking "how does it work" questions: what's the release plan for patching bugs in released versions without releasing other code in `dev`?  Check out the commit of the last patch [release](https://github.com/ractivejs/ractive/releases) on that version number, fix it in a branch, publish from that branch, and then merge that branch into the `dev` branch and delete the patch branch?

**Comment by TehShrike** [comment]
Oh, and thanks for pointing me at the [edge migration guide](http://docs.ractivejs.org/edge/migrating), that looks quite useful.  It does point back to the changelog file though! :-)

**Comment by evs-chris** [comment]
Well, the PR for 0.7 should give you an idea of what needs to happen before a release #1784. The IE stuff in particular needs to be addressed. I know @MartinKolarik has already braved a good bit of that particular dungeon. See also #1253 - I think only Rich can publish to npm.

I think tags and branches would be the way to go to handle bug fixes for older releases going forward. Unfortunately the early changes in 0.8 are just too big to keep anywhere close to in sync with master. Changes going forward should be less drastic. An alpha/beta/RC cycle for majors would be nice, but I don't know if that would be feasible time-wise.

I think we're getting pretty close to being able to have a 1.0 release, meaning nothing super huge should happen, like the more-or-less complete rewrite in 0.8 by @martypdx and @Rich-Harris. I'm sure there will still be plenty of semver major bumps left after 1.0. I would guess there's a 0.9 and probably a 0.10 between here and there though. Ultimately it's up to the bdfl.

**Comment by evs-chris** [comment]
0.8.0 is out and 0.8.1 will be out shortly with some bug fixes. The changelog is updated, so I'm gonna close this :smile:
