### ISSUE TITLE
spacing in key bug

### ISSUE THREAD

**Issue by yishenggudou** [ractivejs/ractive#2533]
As we know, in Mustache wen can iterate an object like this:

users object data:
```
{
    users: {
      'Joe': { email: 'joe@example.com' },
      'Jane': { email: 'jane@example.com' },
      'Mary': { email: 'mary@example.com' }
    }
  }
}
```
We can iterate over the users object with the following:
```
<ul>
  {{#users:name}}
    <li>{{name}}: {{email}}</li>
  {{/users}}
</ul>
```
to create:
```
<ul>
  <li>Joe: joe@example.com</li>
  <li>Jane: jane@example.com</li>
  <li>Mary: mary@example.com</li>
</ul>
```
However, I found that when there is a blank in the key, then the object iteration does not work any more.
users object data with blanks in the key
```
{
    users: {
      'Joe Lee': { email: 'joe@example.com' },
      'Jane Lau': { email: 'jane@example.com' },
      'Mary Hoo': { email: 'mary@example.com' }
    }
  }
}
```
I can only get the user's name (like 'Joe Lee'), but the value 'email' is disappear. like:
```
<ul>
  <li>Joe Lee: </li>
  <li>Jane Lau: </li>
  <li>Mary Hoo: </li>
</ul>
```

**Comment by fskreuz** [comment]
Please specify what version of Ractive, what browser you're using, as well as a reproduction. All seems well here: https://jsfiddle.net/5jh8vzcu/

**Comment by yishenggudou** [comment]
`0.7.3` @fskreuz

**Comment by fskreuz** [comment]
Closing. Seems to work on both 0.7 and 0.8.
