### ISSUE TITLE
textarea two way binding

### ISSUE THREAD

**Issue by sharmam1** [ractivejs/ractive#2534]
I am trying two way binding with textarea and it's working fine, but when i embed ckeditor to it
it's not binding, i think it's only binding when there is an event like change happening to textarea, in case of ckeditor as change is not happening directly to textarea, as it copies values to textarea(i guess no event in this case) i am new to ractive,<br/> is there any other way of doing it?: i am using v0.4.0.

**Comment by fskreuz** [comment]
As far as my CKEditor knowledge goes, it replaces the textarea into a wysiwyg that has a toolbar that lives in the host, and a "textarea" that's actually a contenteditable element inside an iframe.

In scenarios like this where Ractive has no direct access to the DOM, have to interface with an API or when some plugin alters the DOM in a way that it loses bindings with Ractive, you'll need to interface with the widget's API to get and set data.

```js

// CKEditor Ractive wrapper
var RactiveCKEditor = Ractive.extend({
  data: {
    value: ''
  },
  template: `
    <textarea></textarea>
  `,
  onrender(){

    // Initialize CKEditor onto the textarea. Reference to the DOM <textarea> in the template can be
    // retrieved using `this.find('textarea')`
    var CKEditorInstance = ...

    // Observe `value` and send the data to the CKEditor instance
    this.observe('value', value => {
      CKEditorInstance.setData(value);
    });

    // Listen to CKEditor for data changes and set the value on the Ractive instance
    CKEditorInstance.on('change', () => {
      this.set('value', CKEditorInstance.getData());
    });
  }
});

// Creating an instance:
new RactiveCKEditor({
  el: '#app',
  data: { value: 'test' }
});

// Use as a component
new Ractive({
  el: '#app',
  template: `
    <RactiveCKEditor value="test" />
  `,
  components: { RactiveCKEditor },
});

```

**Comment by waynebaylor** [comment]
Here's an example that's worked for me in the past:

```html
<textarea class="form-control" id="description" name="description" value="{{{markdown(path.description)}}}"></textarea>
```

```js
var CKEDITOR = require("CKEDITOR");

component.exports = {
	isolated: true,
	
	data: function() {
		return {
			path: null,
			editor: null,
			...
		};
	},
	
	onrender: function() {
		// setup stuff.
		this.observeOnce("path", function() {
			// create the description editor.
			this.set("editor", CKEDITOR.replace("description", ckeditorConfig));	
		}, {init: false, defer: true}); // defer=true so dom is ready for ckeditor

		// click save button.
		this.on("save-details", function(event) {
			var postData = JSON.stringify({
				description: this.get("editor").getData()
			});

			// do ajax
		};

		...
	}
};	
```

**Comment by sharmam1** [comment]
Thanks @fskreuz @waynebaylor, my question is,
is there a way to achieve Two way binding in textarea without actually changing textarea value manually (in my case i will change in ckeditor and copy the value to textarea) ? or **Two way bindingz** occurs only change event of actual element(in my case textarea).

**Comment by fskreuz** [comment]
@sharmam1 Short answer is no.

Ractive has no integrations with CKEditor nor does CKEditor have integrations with Ractive.  CKEditor isn't aware that Ractive has bound an element to data and may do destructive changes to the DOM that may break the original data binding. In the same way, Ractive isn't aware how CKEditor manipulates the DOM. CKEditor may be updating the textarea, but Ractive may not know about it.

The only party that is aware that both libraries exist on the page *is the developer*. This means you're responsible for making both libraries aware of each other. This means making the logic that integrates the two, which in Ractive's case, is a custom component.
