### ISSUE TITLE
Lazy attribute on inputs cannot be dynamic

### ISSUE THREAD

**Issue by ISNIT0** [ractivejs/ractive#2535]
**Reproduction:**
0.7.3:
http://jsbin.com/yirapomeru/7/edit?html,js,output
Here the attribute is ignored if it's a ractive value

0.8:
http://jsbin.com/yirapomeru/5/edit?html,js,output
Here, the value of the attribute when the input is respected, but changes do not take effect.

**Code:**
`<input type='text' value='{{foo}}' lazy='{{lazy}}' />`

**Comment by evs-chris** [comment]
Fixed in edge :smile:
