### ISSUE TITLE
Class attributes aren't reflected in the ractive.toHTML() output.

### ISSUE THREAD

**Issue by mpowell-atomic** [ractivejs/ractive#2537]
**Description of the bug:**
Class attributes aren't reflected in the ractive.toHTML() output.

When I set a class dynamically in the template e.g. `class-test="{{hasTest}}"` I expected `class="test"` to show up in the toHTML() output but instead it just passes through the original class-test stuff. Is this a known issue? Thanks!

**Versions affected:**
Ractive.js v0.8.0-edge

**Platforms affected:**
All

**Reproduction:**
http://jsfiddle.net/v9L6xc9c/

**Code:**
```
<script type="text/template" id="template">
    <div class-test="{{hasTest}}">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </div>
    <h4>HTML Source:</h4>
    <div>
    	{{source}}
    </div>
</script>

<script>
new Ractive({
	el: 'body',
	template: '#template',
  data: function(){
    return {
      hasTest: true
    };
  },
  onrender: function(){
     this.set('source', this.toHTML());
  }
});
</script>
```

**Comment by martypdx** [comment]
Class-specific attributes are a shiny new thing and we probably just forgot the `.toHTML()` case.

**Comment by mpowell-atomic** [comment]
no worries. just noticed it this morning. cheers.

**Comment by mpowell-atomic** [comment]
And it also looks like the style-specific attributes are also missed by toHTML,

**Comment by martypdx** [comment]
> And it also looks like the style-specific attributes are also missed by toHTML.

Thanks! Good call on checking those too...

**Comment by pidgpowell** [comment]
Thanks for fixing this!
