### ISSUE TITLE
Selective content partial

### ISSUE THREAD

**Issue by linde12** [ractivejs/ractive#2539]
Hello! I'm trying to make a Flyer-component which in turn uses the Ractive fly plugin. What i'd do with React is something like this:
```
<Flyer>
  <Fly>Page1</Fly>
  <Fly>Page2</Fly>
  <Fly>Page3</Fly>
</Flyer>
```
and depending on which `Fly` is "active" i'd only show that `Fly` from `this.props.children` in the `Flyer` component. However in Ractive we've got the `{{>content}}` partial which shows all the passed content. What i want is to only show some of the passed content(e.g. one page at a time)

E.g. when pressing on a link that says "Page 1" i want the `Flyer` to only yield the first(Page 1) `Fly`
**Versions affected:**
0.7.3

This probably isn't a bug and maybe there's a solution to it but from the docs alone i couldn't figure this one out! Is there a way to just extract a part of the content partial?

**Comment by martypdx** [comment]
You can use named partials (see https://jsfiddle.net/kho3s3jd/):

```handlebars
<Flyer active='{{active}}'>
  {{#partial page1}}
  <Fly>Page1</Fly>
  {{/partial}}

  {{#partial page2}}
  <Fly>Page2</Fly>
  {{/partial}}

  {{#partial page3}}
  <Fly>Page3</Fly>
  {{/partial}}
</Flyer>
```

And access them directly:

```handlebars
{{#if active === 'page1'}}
	{{>page1}}
{{/if}}
{{#if active === 'page2'}}
	{{>page2}}
{{/if}}
{{#if active === 'page3'}}
	{{>page3}}
{{/if}}
```

This works with both `{{>name_of_partial}}` partial passing and "yielded" (runs in parent context) partials: `{{yield name_of_partial}}`

If you're looking for something more dynamic, I'd use a [dynamic component](http://stackoverflow.com/questions/31075341/how-to-create-ractives-subcomponents-dynamically-and-change-them-programmatical/31080919#31080919).

**Comment by linde12** [comment]
Hmm... Well, because of the named partials i guess it's possible with some workarounds. So although this might work but it will be extra code for the developer that is using of the component. I don't necessarily want to name the components, just be able to have an array of elements that were passed as children to my component so that i can loop through them and display the correct index depending on which page/fly the user navigated to.

I'll put some more psuedo-code of what i want to do. As a user i want to specify pages in the flyer like this:
```
<Flyer>
  <Fly>Page 1 that flies in when navigated to</Fly>
  <Fly>Page 2 that flies in when navigated to</Fly>
</Flyer>
```

In Flyer.js i would listen to when the selected index changes(aka user navigated to another page/fly):
```
onIndexChange: function (idx)  {
  // Set the current fly to the child with the navigated index...
  // However AFAIK there is no "this.children" concept
  this.set('currentFly',  this.children[idx]);
}
```
and in Flyer.html:
```
{{each children:i}}
  <div intro="fly" outro="fly">
    <currentFly />
  </div>
{{/each}}
```

Is there any clean way to solve something like this or do i have to force the users of the component to write named partials for each fly?

Thanks for your quick response @martypdx

**Comment by MartinKolarik** [comment]
I think this is the closest you can get to what you described:

```html
<!-- Fly template -->
{{#if visible}}
    <div intro="fly" outro="fly">
        {{>content}}
    </div>
{{/if}}`
```

```html
<!-- Flayer template -->
{{>content}}
```

```js
// Flayer
this.observe('active', (active) => {
    this.findAllComponents('Fly').filter((page) => {
        return page.parent === this;
    }).forEach((page, index) => {
        page.set('visible', index == active);
    });
});
```

Demo here:https://jsfiddle.net/dd84skdf/1/

**Comment by linde12** [comment]
@MartinKolarik This is exactly what i wanted and your assumption about the Fly component being defined by me is also correct. Hooray! :+1: 

Thanks a lot. It's kind of difficult to figure out how to do after using React but this snippet made it easy to understand how to do something similar in Ractive!

**Comment by MartinKolarik** [comment]
>@MartinKolarik This is exactly what i wanted and your assumption about the Fly component being defined by me is also correct. Hooray! :+1:

Good to hear that!
