### ISSUE TITLE
How to write isomorphic code with Ractive?

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#2540]
Hello again!

I try to use Ractive in my isomorphic project demo. Could someone tell me the best way to do it? 

I know about toHTML() method of instance, it helps me to send prepared HTML back to the browser if synchronous http-request is coming. But how to asign all Ractive's handlers and bindings back to that static HTML on client side? Is it possible at all?

**Comment by MartinKolarik** [comment]
>But how to asign all Ractive's handlers and bindings back to that static HTML on client side? Is it possible at all?

You need to use `new Ractive()` exactly as you would without server-side rendering. Ractive up to v0.7.3 will simply re-render everything (so not much benefit in rendering server-side). Starting with v0.8.0 (current edge), it supports DOM diffing, so it should use the existing elements and only add the bindings/handlers/etc.

**Comment by fskreuz** [comment]
The general discussion can be found here https://github.com/ractivejs/ractive/issues/395 and the related PR over here https://github.com/ractivejs/ractive/pull/2196.

**Comment by PaulMaly** [comment]
> (so not much benefit in rendering server-side)
Benefit is that js-disabled clients can handle this HTML using  browser default maner. What will have a positively affect on UX and SEO. That's the purpose of isomorphic applications, I think, not only performance increasing.
  
Thanks a lot, I'll try this feature and leave a comments here if you don't mind.
