### ISSUE TITLE
0.8 Question, how to get index of filtered items

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2543]
In this fiddle http://jsfiddle.net/szfmzw21/9/ you ll see a list of filtered items.
is there a way to get the index of the filtered item rather than the index of the original array?
For example when you filter by 'Name 1' I would like the second item to have an index of 1 not 3.
How to do this?

**Comment by dagnelies** [comment]
I think the only/best way to do it would be to add your index directly in options data beforehand

**Comment by MartinKolarik** [comment]
If you don't use twoway binding inside the loop, the best way is to filter the options directly inside the `{{#each}}` block:

```js
{{#each options.filter(filter_by_name(object.filter_by)): i}}
    <li>{{i}} - {{name}}</li>
{{/each}}
```

http://jsfiddle.net/szfmzw21/10/

**Comment by evs-chris** [comment]
The latest 0.9 alpha has experimental support for binding against expressions, so I'd say that's the best answer now.
