### ISSUE TITLE
Suggestion: track-by in <select />

### ISSUE THREAD

**Issue by guilhermeaiolfi** [ractivejs/ractive#2545]
Hi,

I was wondering how everybody does what seems to be a pretty common use case when using the select element in ractive: 
### Use Case

You have your model loaded from the server and want to show it AND edit it, something that looks like:

``` javascript
{
  name: 'Record #1',
  owner: {
     id: 1
     name: 'User Name'
  }
}
```

You bring the name of the user because you may be listing tons of records and you don't want to go back to the server and get the user name one by one, so it came with it.

But you want to edit this object occasionally and so you create a form to have:

``` html
<select value="{{owner.id}}">
   {{#each users}}
       <option value="{{id}}">{{name}}</option>
   {{/each}}
</select>
```

By this time you'll change the user ID but not its name. To change its name you'll need to go over the `users` array and look for the one that has the new `owner.id`. You can do that with a computed property to automate a little bit, but if you have a deeply nested model you'll have to manually go over your data and sync everything.
### Suggestion

So, I was thinking about it and thought that maybe if we were able to tell the select to compare by some of the object properties instead of the whole object we could set the object directly into the model, like:

``` html
<select value="{{owner}}" track-by="id">
   {{#each users}}
       <option value="{{this}}">{{name}}</option>
   {{/each}}
</select>
```

This would be doing some things:
- it wouldn't set the object into the option, it would use the `track-by` property, get the `id` of `{{this}}` and set it in the `<option>` element AND keep a reference for `{{this}}` somewhere else.
- when `{{owner}}` changes, it will go over the options and look by the option that has `option.id` to compare. 
- Same thing goes for the other way: when the selected option changes it gets the `{{this}}` object of the selected option and sets it in the `{{owner}}`.

It doesn't need to change the current behavior. The change would be for when there is a `track-by` in the select element.

What do you think?

**Comment by MartinKolarik** [comment]
Just a note that if we end up implementing this, it should probably work with `radio` and `checkbox` inputs as well.

**Comment by fskreuz** [comment]
Sounds like a good idea, reminds me of Angular 1.x and all the goofy expressions it has for selects and repeats. Just not convinced with `track-by` tho. I have a gut feeling there's a better way to express this than another unofficial property.

Side note: We should start putting these properties like `ractive-*`. I'm losing track of what Ractive has with all the new changes (esp. transitions).

**Comment by martypdx** [comment]
@guilhermeaiolfi I don't understand your use case. Can you provide example of what you mean by:

> By this time you'll change the user ID but not its name. To change its name you'll need to go over the users array and look for the one that has the new owner.id. You can do that with a computed property to automate a little bit, but if you have a deeply nested model you'll have to manually go over your data and sync everything.

**Comment by guilhermeaiolfi** [comment]
@martypdx since you can't get the whole object selected, you have to chose one of its properties that are either an integer or a string. To bring the selected object (not just one property) back to your model (in case you want to show its name, for example) you have to loop all the list and see which one the user selected: http://jsfiddle.net/FarWn/93/

@fskreuz Maybe just "r-" then:
```
<select r-compare="id">
```
It could also accept a function for more complex cases.

**Comment by fskreuz** [comment]
I think I got it simplified... https://jsfiddle.net/h53zhnwp/

```js
new Ractive({
  el: 'body',
	template: `
  	<div>
      <label>ID:</label>
      <span>{{ owner.id }}</span>
    </div>
  	<div>
      <label>Name:</label>
      <span>{{ owner.name }}</span>
    </div>
    <div>
    	<select value="{{ owner.id }}">
      	{{# names }}
          <option value="{{ id }}">{{ name }}</option>
        {{/}}
        </select>
    </div>
  `,
  data: {
  	owner: {
    	id: 0,
      name: 'foo'
    },
    names: [{
    	id: 0,
      name: 'foo'
    },{
    	id: 1,
      name: 'bar'
    },{
    	id: 2,
      name: 'baz'
    }]
  }
})
```

**Comment by evs-chris** [comment]
Why not use the whole object? https://jsfiddle.net/8pkhzwch/ Though I may be missing something...

Unless you're actually trying submit the html form the good old-fashioned way, which has been an issue in the past. In that case, I'd suggest that we add a way to set the HTML value separately from the bound value.

**Comment by guilhermeaiolfi** [comment]
@evs-chris that's still won't work because the object returned from the server is not the same in the list. That's because we need to find something unique to compare them.

No. I'm not trying to submit the form the old way. 

> I'd suggest that we add a way to set the HTML value separately from the bound value.

I don't think that would be enough because the thing I said about the objects not being the same (object in the list vs object from the server).

**Comment by martypdx** [comment]
> the object returned from the server is not the same in the list

Ah yes, that problem I recognize, thx

**Comment by evs-chris** [comment]
Ah! Gotcha. So the issue is that you swap out the list and it no longer matches the selected value. In that case, I'd say that providing a comparator function for the binding would be the most flexible thing to do.

**Comment by guilhermeaiolfi** [comment]
@evs-chris not sure that's the same case, but they are bound to the same problem: comparing objects is too limiting, they can have the exactly same data and a simple comparison will say they are different. It doesn't matter how my app end up having two different objects but if the developer says they are the same, ractive should respect that. 

> I'd say that providing a comparator function for the binding would be the most flexible thing to do.

That's was what I thought, but since that's so common (to compare objects using one of its properties) maybe it should accept strings too that tell ractive which property is unique in those objects.

**Comment by evs-chris** [comment]
Shooting from the hip - how about moving binding flags to a second interpolator e.g. `<select value="{{owner}}{{ { lazy: true, comparator: some.fn.reference } }}">...`. That would allow coalescing the special attributes into a construct right next to what they affect. I'm not wild about wave of braces, but it's not something that would pop up often, I'd guess.

As an alternative, how about directives like the new class and style handlers e.g. `<select value="{{owner}}" value-comparator="{{some.fn.references}}">...`?

Also, there's no reason the comparator couldn't go all lodash and accept a string as a comparator and just use it for property access.

> It doesn't matter how my app end up having two different objects but if the developer says they are the same, ractive should respect that.

But you are modifying the list and having the value get out of sync (reset to nothing), right? Just to be clear, the owner value would still get swapped out, it would just be to the new matching value from the options list, right?

**Comment by guilhermeaiolfi** [comment]
> But you are modifying the list and having the value get out of sync (reset to nothing), right? Just to be clear, the owner value would still get swapped out, it would just be to the new matching value from the options list, right?

Yes, but I guess there is two scenarios here: 

1) using an object to select an item in the list. In that case it doesn't need to change the list. Just need to find the right item to select.
2) selecting an item in the list. In that case you swap out the owner value and set one object from the list.

Your jsfiddle shows that the second case can be done already. The first can't.

I don't know if you (core team) want to start go that path, but maybe something like vue is doing using the attribute name for express some options: 

```html
<select value.comparator(id)="{{value}}" />
```

**Comment by guilhermeaiolfi** [comment]
So, I tried to implement it and for strings it was easy to do it. But now I want it to accept ```{{@this.comparator}}``` but I can't figure it out how to turn that into a reference to a function. Can someone give any pointers?

**Comment by guilhermeaiolfi** [comment]
Although that would be trickier for 'multiple', another interesting approach would be accepting something like:

```html
<select value="{{ owner }}">
  {{# names }}
       <option value="{{ . }}" {{#if this.id == owner.id}} selected="selected" {{/if}}>{{ name }}</option>
  {{/}}
</select>
```
