### ISSUE TITLE
Ractive 0.8.0-edge templating stops re-rendering after overriding data properties

### ISSUE THREAD

**Issue by linde12** [ractivejs/ractive#2548]
**Description of the bug:**
Overriding `data` properties(properties returned from data function) via `this.set()` causes Ractive to re-render once and then completely(??) stop re-rendering any templates. This only seems to happen in the setup i've got on the fiddle(maybe something with `yield`)
**Versions affected:**
0.8.0-edge
**Reproduction:**
1. Go to http://jsfiddle.net/0u4rr1cx/1/
2. Open console
3. Click 0
4. Click 1
5. Click 2
6. Click cancel, 0 or 2
7. Observe that the page does not change however the console.logs still state that the observer was called and that everything was updated correctly.

**Comment by evs-chris** [comment]
It looks like this is fixed... @linde12, can you confirm?

**Comment by linde12** [comment]
Sorry for the late reply! I can confirm that this now works!
