### ISSUE TITLE
Dots don't work in keys while looping v0.7.3

### ISSUE THREAD

**Issue by linde12** [ractivejs/ractive#2549]
**Description of the bug:**
Having dots in your object keys in the templates cause weird behaviour. If this is expected behaviour i think this is something that should be underlined in the docs. Just spent all day, on the bridge of insanity, trying to reproduce and figure out what was wrong. What confused me even more is that it works in 0.8.0-edge
**Versions affected:**
0.7.3, works fine in 0.8.0-edge
**Reproduction:**
See http://jsfiddle.net/0eg38b38/1/

**Comment by guilhermeaiolfi** [comment]
Yes, it's not been too long since edge supports dots in keys.

**Comment by MartinKolarik** [comment]
This was reported several times before, and is expected in versions up to v0.7.3. We added support for dots in keypaths in edge/v0.8.0.

**Comment by linde12** [comment]
Not sure why this was closed. Imo this is a breaking change and should be underlined in the docs of 0.8.0

**Comment by MartinKolarik** [comment]
Not sure how this is a breaking change. It didn't work before; it works now. Also, 0.8.0 hasn't been released yet.

**Comment by linde12** [comment]
It's a breaking changes because there might be code depending on the old behavior. The behavior has been changed from the old behavior. It doesn't matter if it "didn't work before" because someone somewhere might depend on that behavior.

I'm aware that 0.8.0 isn't released yet but for when it is i think it would be appreciated if this was properly documented.

**Comment by fskreuz** [comment]
> Having dots in your object keys in the templates cause weird behaviour. If this is expected behaviour i think this is something that should be underlined in the docs

It's a bug, not expected behavior. It was only fixed in 0.8/edge and is unreleased. There are several closed threads that are related to this.

> What confused me even more is that it works in 0.8.0-edge

And that's the expected behavior. 😉

**Comment by linde12** [comment]
@fskreuz 

> I am not sure how code could depend on it if it actually breaks it. The only workaround for it was to avoid dots on keypaths which shouldn't be breaking when moving to 0.8.

It doesn't break, it just doesn't work as i(and i assume many others)expected. See the following fiddle:

http://jsfiddle.net/3vh6hLpy/

Anyway a bug or not, the fix has caused the behavior to change from previous versions and i think it should be documented. Something that addresses that this was a bug in versions before 0.8 and because of that it's behavior has changed.

Maybe it's just me, but i believe others may find it helpful as well.
