### ISSUE TITLE
Progressive enhancement fails to remove redundant class names

### ISSUE THREAD

**Issue by monoblaine** [ractivejs/ractive#2551]
**Description of the bug:**

The "enhancement" phase fails to remove class names that shouldn't be in the final dom.

```html
<div class="someCls someCls--variant">foo</div>
```

Based on the example I have provided, the html above should have turned into the one below after ractive had done its job:

```html
<div class="someCls">foo</div>
```

I suspect there's something wrong in function [`updateClassName`](https://github.com/ractivejs/ractive/blob/96f593b59316029485d39293115425f2ae305294/src/view/items/element/attribute/getUpdateDelegate.js#L222).

Here is the transpiled code (Debugging the example I've given, the comments at the end of the lines are the runtime values):

```js
function updateClassName () {
    var value = readClass( safeToStringValue( this.getValue() ) ); // value = ["someCls"]
    var attr = readClass( this.node.className ); // attr = ["someCls", "someCls--variant"]
    var prev = this.previous || []; // prev = []

    var i = 0;
    while ( i < value.length ) {
        if ( !~attr.indexOf( value[i] ) ) attr.push( value[i] );
        i++;
    }

    // remove now-missing classes
    i = prev.length;
    while ( i-- ) {
        if ( !~value.indexOf( prev[i] ) ) {
            var idx = attr.indexOf( prev[i] );
            if ( ~idx ) attr.splice( idx, 1 );
        }
    }

    this.node.className = attr.join( ' ' );

    this.previous = value;
}
```

Here, we're making sure all the elements in `value` gets pushed into `attr`, but we're not checking for the opposite case: "Remove elements from `attr` that are not present in `value`." Am I missing something?

***

And one last thing:

```js
this.node.className = attr.join( ' ' );
```

We're always updating the value of `className` attribute even if it is already the same (fires attribute modification events in Chrome Dev Tools). Shouldn't we do something like this instead?:

```js
var newValue = attr.join(' ');

if (newValue !== this.node.className) {
    this.node.className = newValue;
}
```

**Versions affected:**

v0.8.0-edge

**Platforms affected:**

All

**Reproduction:**

http://jsfiddle.net/monoblaine/jtvbdrop/2/

**Code:**

```html
<div id="foo"><div class="someCls someCls--variant">foo</div></div>

<script type="text/template" id="template"><div class="someCls">foo</div></script>
```

```js
setTimeout(function () {
    new Ractive({
        el: 'foo',
        template: '#template',
        enhance: true
    });
}, 200);
```

**Comment by woodlandhunter** [comment]
Seems like this has potential to get tangled up with #2510. (I'm using a UI lib which modifies the class name outside ractive... )

**Comment by monoblaine** [comment]
> Here, we're making sure all the elements in `value` gets pushed into `attr`, but we're not checking for the opposite case: "Remove elements from `attr` that are not present in `value`."

This is incorrect. I don't know why I said this. We're actually trying to check for the opposite case, but we're blocked by `prev` because it's initialized as an empty array.

@woodlandhunter I understand the potential problem here. (Yes it took a week) I think all I need is a change in [this](https://github.com/ractivejs/ractive/blob/96f593b59316029485d39293115425f2ae305294/src/view/items/element/attribute/getUpdateDelegate.js#L225) line:

From
```js
const prev = this.previous || [];
```

To
```js
const prev = this.previous || attr.slice(0);
```

Because the first time `updateClassName` is called, `this.previous` is undefined which leads to an empty array being used instead of the existing list of classes. If we use a copy of `attr` instead of an empty array, my problem gets fixed. I don't think this will cause any trouble regarding your case. (Tried `npm run build`, no problems) What do you think?.

**Comment by woodlandhunter** [comment]
I'll test it out and report back

**Comment by woodlandhunter** [comment]
Forgot to comment here but I did test the fiddle I posted in #2510 and it worked.
