### ISSUE TITLE
Function passed as property has "Window" as its scope

### ISSUE THREAD

**Issue by guilhermeaiolfi** [ractivejs/ractive#2552]
**Description of the bug:**
When a function is passed as a reference to a component, its scope changes. Probably should be considered in #2386. Using ```onEvent="{{ractive.func.bind(@ractive)" works. But I think that should be the default behavior.

**Versions affected:**
0.8-edge

**Code:**
http://jsfiddle.net/e897yuyo/

**Comment by martypdx** [comment]
I'm confused because your example isn't using events, it's just passing a function as a component property and invoking it.

**Comment by guilhermeaiolfi** [comment]
onEvent is a reference to how those properies are named: onChange, onSearch, onSelected. I need to pass it as a reference and not invoke it right away. It is not bound to a event in particular. The jsfiddle was just to illustrate. I'm doing much more logic with onEvent.

**Comment by martypdx** [comment]
Oh, you mean this: http://jsfiddle.net/cqpe1pcb/

Top-level functions should be bound, we're just missing those passed as component props.

**Comment by guilhermeaiolfi** [comment]
Exaclty. Thanks. I think it's pretty nice to pass functions as props. Very powerful and flexible. I'm starting to explore that now with 0.8. 

That's another point to '@this' become just 'this' because it would be more align to how JavaScript looks like without Ractive. But that discussion is over, I think.

**Comment by evs-chris** [comment]
Functions that are children of a root keypath will now lazily bind to the ractive instance non-destructively in edge.
