### ISSUE TITLE
Data-binding broken in edge

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2554]
Hi,

Just take a look at my plugin:

http://dagnelies.github.io/ractive-dataset/dataset.html
http://dagnelies.github.io/ractive-dataset/dataset_edge.html

no error messages, no warnigs, nothing. It just doesn't work anymore on edge. Any clue?

**Comment by evs-chris** [comment]
If you're precompiling templates, event expressions are not compatible with 0.7 and earlier edge templates.

**Comment by dagnelies** [comment]
Hi Chris,

I don't use precompiled templates, so that shouldn't be a problem. I've also adapated some method events to use "@this".

I'm surprised you haven't seen any binding breakage. None of the input fields in:
http://dagnelies.github.io/ractive-dataset/dataset_edge.html
...have any effect.

Whereas with latest, everything works:
http://dagnelies.github.io/ractive-dataset/dataset.html

**Comment by evs-chris** [comment]
I've tracked the remaining piece of this issue back to an problem with fragments getting stuck in a dirty state. Manually adding the main instance fragment to a runloop flush magically kicks everything into a working state. I may be able to track that down, but in case I can't get it now, I wanted to leave a note for future evs-chris so he can.

**Comment by guilhermeaiolfi** [comment]
Nice and Interesting library, @dagnelies. Very flexible too :)
