### ISSUE TITLE
Returning "false" in an event handler does not stop the event if "@this.fire" is used

### ISSUE THREAD

**Issue by monoblaine** [ractivejs/ractive#2556]
**Description of the bug:**

Returning "false" in an event handler does not stop the event if `@this.fire` is used.

The old school method works:

```html
<a on-click="foo"></a>
```

But the new one does not work:

```html
<a on-click="@this.fire('foo')"></a>
```

I tried to debug it, sort of found the reason, but I don't know how to fix it. Here is what I've found ([Fiddle here](http://jsfiddle.net/monoblaine/hf68w350/1/)):

1. When we click on the link, in the DOM event handler, `directive.fire` is called [here](https://github.com/ractivejs/ractive/blob/6ff7104a6bbc47f7a918a2e890f36a51534f5f4e/src/view/items/element/ElementEvents.js#L25).
2. In method [`fire`](https://github.com/ractivejs/ractive/blob/eb6c7d5670878bf483e50383556451a636060ff6/src/view/items/shared/EventDirective.js#L108) of `EventDirective`, [`if ( this.fn )`](https://github.com/ractivejs/ractive/blob/eb6c7d5670878bf483e50383556451a636060ff6/src/view/items/shared/EventDirective.js#L120) is true because we're not using the old school method.
3. [Here](https://github.com/ractivejs/ractive/blob/eb6c7d5670878bf483e50383556451a636060ff6/src/view/items/shared/EventDirective.js#L150), our event handler is kinda called:
    
    ```js
    var result = this.fn.apply( ractive, values ).pop();
    ```
4. Then this (auto-generated):
    
    ```js
    (function(
    /**/) {
    return function (_0){return([_0.fire("foo")]);};
    })
    ```
5. Then [this](https://github.com/ractivejs/ractive/blob/6ff7104a6bbc47f7a918a2e890f36a51534f5f4e/src/Ractive/prototype/fire.js#L4):
    
    ```js
    fireEvent( this, eventName, { args: args });
    ```
6. In [`fireEvent`](https://github.com/ractivejs/ractive/blob/6ff7104a6bbc47f7a918a2e890f36a51534f5f4e/src/events/fireEvent.js#L6), `if ( !options.event )` is true so a weird object named "event" is added to "options" object.
7. [`fireEventAs` is called](https://github.com/ractivejs/ractive/blob/6ff7104a6bbc47f7a918a2e890f36a51534f5f4e/src/events/fireEvent.js#L21).
8. [`notifySubscribers` is called](https://github.com/ractivejs/ractive/blob/6ff7104a6bbc47f7a918a2e890f36a51534f5f4e/src/events/fireEvent.js#L63).
9. [Here](https://github.com/ractivejs/ractive/blob/6ff7104a6bbc47f7a918a2e890f36a51534f5f4e/src/events/fireEvent.js#L80), Neither `preventDefault` nor `stopPropagation` could be called, because `!event._noArg` is false:
    
    ```js
    if ( event && !event._noArg && stopEvent && ( originalEvent = event.original ) ) {
        originalEvent.preventDefault && originalEvent.preventDefault();
        originalEvent.stopPropagation && originalEvent.stopPropagation();
    }
    ```
10. We go back to where we were in step 3:
    
    ```js
    var result = this.fn.apply( ractive, values ).pop();
    ```
    
    Here, the value of result is always `undefined`, because neither [`fireEvent`](https://github.com/ractivejs/ractive/blob/6ff7104a6bbc47f7a918a2e890f36a51534f5f4e/src/events/fireEvent.js#L6) nor any of the subsequent methods return a value.
11. The value of `result` is `undefined`, so we can't get in to this [if](https://github.com/ractivejs/ractive/blob/eb6c7d5670878bf483e50383556451a636060ff6/src/view/items/shared/EventDirective.js#L154):
    
    ```js
    if ( result === false && ( original = event.original ) ) {
        original.preventDefault && original.preventDefault();
        original.stopPropagation && original.stopPropagation();
    }
    ```

**Versions affected:**

v0.8.0-edge

**Reproduction:**

http://jsfiddle.net/monoblaine/hf68w350/1/

**Code:**

Template:

```html
<script type="text/template" id="template">
    <p><a href="javascript:alert('You\'re not supposed to see me!')" on-click="@this.fire('foo')">Click me</a></p>
    <p><em>(You shouldn't see any alerts after clicks)</em></p>
</script>
```

JavaScript:

```js
new Ractive({
    el: 'body',
    template: '#template',
    oninit: function () {
        this.on('foo', function () {
            return false;
        });
    }
});
```

**Comment by martypdx** [comment]
@monoblaine - 

Issue here arises because the `fire` method on the ractive api is considered a synthetic event in that it doesn't (necessarily) correspond to a dom event. For example just calling `this.fire( 'foo' )` from within the ractive instance means _there is no dom event object_ (hence `_noArg == true`) on which to call `.preventDefault` or `.stopPropagation`.

So basically we need to come up with a way to bridge things.

In the meantime, if you need a horribly hacky, but working, work around:
1) set `this.event._noArgs = false` in the event handler
2) use the comma operator in the template to return false: `on-click="@this.fire('foo'), false"`
