### ISSUE TITLE
Electron library?

### ISSUE THREAD

**Issue by gaelicmichael** [ractivejs/ractive#2557]
I'm beginning to experiment with Electron and I would really love to continue to use Ractive (rather than React or Angular) when developing apps -- are there are plans (or current libraries) that enable the use of Ractive in this environment?

**Comment by MartinKolarik** [comment]
>that enable the use of Ractive in this environment

I don't see any reason why Ractive wouldn't work with Electron.

**Comment by gaelicmichael** [comment]
Do you know of any example apps that use Ractive on Electron?  I haven't found one yet.

The issue is how to get the Ractive instance into the scope of the renderer process and the "DOM" -- there is no longer any global DOM.

I'm just starting to explore the system so the basic may elude me.

**Comment by MartinKolarik** [comment]
I don't - I was experimenting with NW.js a while back, but not electron.

>The issue is how to get the Ractive instance into the scope of the renderer process and the "DOM" -- there is no longer any global DOM.

My guess (after reading their docs for 1 minute, so might be wrong) is that you need to create a Ractive instance inside the rendered process, not the main process.

**Comment by gaelicmichael** [comment]
Ah ha, yes, your guess is confirmed!  I just got a very simple test to work.  For those who may be interested:

index.html:
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
	    <title>Prospect Workbench</title>
	</head>
	<body>
		<h1>Your Project</h1>
		<div id="ractive-container"></div>
	</body>

	<script id='ractive-outer' type='text/ractive'>
		<p>{{greeting}}, {{recipient}}!</p>
	</script>

	<script>
		require('./renderer.js');
	</script>
</html>

renderer.js:

const Ractive = require('ractive');

var rApp = new Ractive({
	el: '#ractive-container',
	template: '#ractive-outer',
	data: { greeting: 'Hello', recipient: 'world' }
});
