### ISSUE TITLE
Fade plugin link to source is broken

### ISSUE THREAD

**Issue by donnyv** [ractivejs/ractive#2559]
Fade plugin link to source is broken  
https://raw.githubusercontent.com/ractivejs/ractive-transitions-fade/master/dist/ractive-transitions-fade.js

**Comment by fskreuz** [comment]
If this is a docs issue, [the docs repo](https://github.com/ractivejs/docs.ractivejs.org) is a better place for this.

**Comment by donnyv** [comment]
My bad

**Comment by JonDum** [comment]
Close?
