### ISSUE TITLE
Break attributes xmlns:xlink, xlink:href in browser

### ISSUE THREAD

**Issue by kachurun** [ractivejs/ractive#2560]
**Description of the bug:**
Hello, i'm used ractive for display list of SVG icons with `use` tag, like this:

```
<svg width="40" height="40" style="vertical-align:middle; fill:{{item.ico.color}};" viewBox="0 0 52 52">
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="{{item.ico.url}}#icon"></use>
</svg>
```  

then svg4everybody polyfill converts `use` tag to SVG content, but now i've got error with it because  Ractivejs compile my template to this:
```
<svg width="40" height="40" style="vertical-align:middle; fill:#242424;" viewBox="0 0 52 52">
        <use xlink="http://www.w3.org/1999/xlink" href="/_s/images/svg/line/1.svg#icon"></use>
</svg>
```
its turned attributes:
`xmlns:xlink`-> `xlink`  
`xlink:href` -> `href`  

p.s. I have no problem with compile template with node.js (or browser with use .toHTML() method)

**Versions affected:**
0.8-edge  

**Platforms affected:**
Any browser, not node.js or .toHTML() method  

**Reproduction:**
http://jsfiddle.net/fs07b7zL/

**Comment by evs-chris** [comment]
I'm not seeing quite this issue on Chrome 52. Locally, I get an erroneous xlink attribute, but I'm not seeing the href without the xlink namespace on it. I have a fix for the extra attribute, but I'm not sure why the fiddle should behave differently than a local test. Changing the name of the namespace to foo e.g. `xmlns:foo="..."` and using `foo:href` seems to work around the issue in the fiddle.

I have very little experience with namespaces, but I believe ractive will actually supply xlink for you, so you don't have to include the xmlns:xlink bit. But again, I have no idea why it's not behaving in the fiddle.

**Comment by evs-chris** [comment]
I _think_ this is ok, or at least I've successfully used xlinked use tags in an inline svg in ractive. Please re-open if this is still an issue.
