### ISSUE TITLE
*.eventname does not fire in own namespace

### ISSUE THREAD

**Issue by lnryan** [ractivejs/ractive#2566]
Hiya,

I searched but did not find this bug. Apologies if i simply didn't search well enough. I'm newish to searching git issues.

**Description of the bug:**
I find the above mentioned behavior counter intuitive. I would not expect to have to separately register an event for when it fires in its own container and when it fires in a subordinate container.
eg `ractive.on('myevent *.myevent')`, which is what i'm finding.More exactly, since `this` and `.` can generally be used in ractive, I would expect `this.`/`{emptystring}.` to be among the valid prefixes covered by *.

I would rather expect to use a special notation to indicate i'm _only_ interested in it firing in the current container or _only_ interested in subordinate container firings. 

Perhaps `*.myevent` could be distinguished from a more specifically child only notation? 

**Versions affected:**
0.7

**Platforms affected:**
Chrome

**Reproduction:**
_this is exactly how i found this. Obviously, switching around which lifecycle event it's in may have nothing to do with this_
1. Define an `oncomplete` method for a ractive template. 
2. In `oncomplete` add an event with `this.on('*.myevent',function(event){ alert('I fired!'); });`
3. In your template add a button `<button on-click="myevent">Pick Me!</button>`
4. Create a component and include it in your template `<mycomponent />`
5. In the template add a button `<button on-click='myevent'>No, Pick Me!</button>`
6. When you view this, the button within the component will fire the event, but the one within the original template will not.

**Code:**
See steps to reproduce

**Comment by evs-chris** [comment]
I think it seems reasonable that `this.on('*.foo')` should fire on `this.fire('foo')` too. @martypdx?

**Comment by heavyk** [comment]
I dunno, but personally I do not thing it should be so... I always saw the `.` like a namespace separator... so, `this.fire('clicked')` shouldn't fire for `this.on('*.clicked')` unless it was `this.fire('foo.clicked')` cause I would want these to be different:
 - `<button on-click="clicked">...</button>`
 - `<button on-click="button1.clicked">...</button>`

not sure exactly, but I may have to change some code if this were to change.

**Comment by guilhermeaiolfi** [comment]
I think it's a valid change. If you consider ```clicked``` as ```this.clicked``` (```this``` as namespace), you would expect ```*.clicked``` to be fired.
