### ISSUE TITLE
Mismatched template version (expected 4, got 3)

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2570]
When upgrading from 0.8 edge v0.8.0-edge-ed9564e3f95e9befe619b92ed35e3a46375164f7 to
v0.8.0-edge-cb5bcd919339cf2b70d9a27a89752094b83a5359
I get: Error: Mismatched template version (expected 4, got 3) Please ensure you are using the latest version of Ractive.js in your build process as well as in your app

I don't use any module bundler or build process just plain old js script tags.
Any ideas why this might be happening?

**Comment by fskreuz** [comment]
This happens when the parser's output has been changed but the tools aren't updated to expect these changes. Which tools are you using specifically?

**Comment by kouts** [comment]
@fskreuz  sorry for my ignorance but what exactly do you mean by "tools"?

**Comment by fskreuz** [comment]
Bundlers, build tools, loaders. Anything that runs on top of Ractive, particularly one that uses the output of `Ractive.parse`. I did miss the part where you said you didn't use a bundler or build tool.

I am not 100% sure if this could happen with Ractive alone but I might be wrong.

**Comment by evs-chris** [comment]
Yes, this will not happen with ractive alone. You probably have a component compiler/bundler that is using 0.7.3 asit's the last published version on npm. The API hasn't changed, so you can switch out the ractive script in node_modules for the bundler safely.

**Comment by pidgpowell** [comment]
Yeah, i am having this issue with rcu which is a dependency of ractive-component-loader for webpack. What is a quick solution for this?

**Comment by fskreuz** [comment]
A safe bet would be to roll back to 0.7.3, or if you prefer edge, the revision just before the template version was changed to 4. Ractive is in a state of flux right now, but I'm pretty sure the tools aren't up to speed with the latest changes.

**Comment by evs-chris** [comment]
If you're comfortable with the command line, you can find . -name ractive.js; cd to any matches in node_modules; rm ractive.js; wget http://cdn.ractivejs.org/edge/ractive.js

Since the API is compatible, anything using ractive for parsing should carry on with the new version.

**Comment by mpowell-atomic** [comment]
I am all in on the edge version and it has been great (with minor updates needed along the way) but this is a big breaking update. I was previously referencing the edge build in my package.json file:

 "ractive": "git+https://github.com/ractivejs/ractive.git#edge",

but if I specify a specific hash it install the src, not the built version. How do I reference a build of a specific commit? Thanks and apologies for my dumbness!

**Comment by mpowell-atomic** [comment]
This is an example error:
```
Module build failed: Error: Mismatched template version (expected 3, got 4)! Please ensure you are using the latest version of Ractive.js in your build process as well as in your app
    at Object.parse (/Users/Shared/Rh/swat/laravel/node_modules/rcu/dist/rcu.umd.js:546:10)
    at Object.module.exports (/Users/Shared/Rh/swat/laravel/node_modules/ractive-component-loader/index.js:11:24)
```

**Comment by mpowell-atomic** [comment]
Ah sorry, I have to be on the build branch to get, uh builds! Duh.

**Comment by MartinKolarik** [comment]
It's because of the [hardcoded](https://github.com/ractivejs/rcu/blob/9724172e90f167ccd90b41b00a39c3e7c85cc980/src/parse.js#L20) template version in rcu. I'm not sure if there's a good reason for that check.

**Comment by mpowell-atomic** [comment]
Yeah i commented out the template check in rcu and the builds seemed fine...

**Comment by evs-chris** [comment]
Hmmm. I've not used rcu before, but it looks like it's pulling in external files from script and link tags using ractive as a parser. Unfortunately, conditional attribute support breaks the expectation that rcu has about how attributes are stored on element nodes. It shouldn't be too difficult to support multiple versions of the template spec, but it will take me a bit to get round to it. I think if all of your scripts and styles are embedded it will be work as expected for now (after removing the hard-coded check).

**Comment by mpowell-atomic** [comment]
Cheers. rcu is used by a few of ractive component & template loaders so it would be nice if this could be addressed sooner than later plus @Rich-Harris is the developer of rcu so it would seem like this could be resolved relatively easily. The ractive component loader for webpack has, for better or for worse, a loose rcu dependency: "rcu": "0.x" so it would pick up any change to rcu.

**Comment by Rich-Harris** [comment]
> How do I reference a build of a specific commit?

This is a bit convoluted, but it works – essentially you need to replace `edge` with a specific commit from the `build` branch:

* Go to [the build branch](https://github.com/ractivejs/ractive/tree/build)
* Click on the latest commit (right hand side of blue bar, just beneath the green 'clone or download' button)
* Grab the commit hash from the URL
* `npm i -S ractivejs/ractive#f4c16f93d2cd81f55ac838dfb9e34db0740ed124 # current latest`

There's probably a more streamlined way of doing the same thing...

@MartinKolarik 

> It's because of the hardcoded template version in rcu. I'm not sure if there's a good reason for that check.

If we didn't check at build time, wouldn't we just run into the same error at run time?

**Comment by Rich-Harris** [comment]
Actually, thinking a bit further – given most people's workflows it's unlikely you'd be using one version of Ractive in your build process and another in the browser. Hmm... guess we could just remove the check. Vote 👍  or 👎  using emoji reactions! (:+1: === 'remove the check')

**Comment by MartinKolarik** [comment]
@Rich-Harris not always - if you used a different version during parse time, then yes. Currently, you simply can't use edge, because rcu expects template version to be 3 and it's 4 in edge - but if you also use edge in production, that's fine and rcu shouldn't care.

**Comment by MartinKolarik** [comment]
I think the only concern is that the template format might change in a way that rcu stops working (since it needs to be able to read some attributes) and needs to be updated.

**Comment by martypdx** [comment]
Would it be enough if rcu stored the version of Ractive used to parse the template? Then the runtime would compare against that?

**Comment by Rich-Harris** [comment]
@martypdx Yeah, I like that idea. I guess the original thinking was that you might parse a template with something other than Ractive itself, but I haven't really seen much appetite for custom parsers recently. Any thoughts on how we can smoothly migrate in that direction?

**Comment by evs-chris** [comment]
Wouldn't the existing template version tag handle that? That would just leave breaking changes to the bits of template format that rcu actually cares about that would require an update to rcu anyways.

**Comment by martypdx** [comment]
@evs-chris good point, sounds like two separate things:
* Is rcu compatible with the template being produced by Ractive.parse (i.e. `TEMPLATE_VERSION`)?
* Is a particular parsed template compatible with the runtime being used to run that template (I don't think there's a currently a check for this)?

Given that `rcu` may, or may not, need to be updated with any particular Ractive release, it seems to me that the only way to handle this is to maintain an rcu `edge` that is introduced when Ractive `edge` as a breaking template spec change.

**Comment by mpowell-atomic** [comment]
Hi! Is there any resolution here yet? I see rcu got updated but not tagged as a new version or an updated edge version. Thanks!

**Comment by heavyk** [comment]
you should be initializing rcu with the ractive version you are using.. to solve this exact problem:

```js
var rcu = require('rcu')
rcu.init(require('ractive'))
```

**Comment by mpowell-atomic** [comment]
@heavyk: I am not manually invoking rcu. It's part of a [webpack component loader](https://github.com/thomsbg/ractive-component-loader/blob/master/index.js) that depends on rcu and that does exactly what you wrote. There is only one version of ractive in my node_modules directory. I don't see how this solves my problem, unless I am missing something. Thanks!

**Comment by Rich-Harris** [comment]
@mpowell-atomic I've just published a version to npm – you can install it with `npm install rcu@edge`

**Comment by dagnelies** [comment]
FYI, one of the source of the message is following outdated dependency:
https://github.com/ractivejs/ractive-load
