### ISSUE TITLE
0.8 - Observers return an object rather than a value changed

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2572]
On 0.8 edge, observers instead of returning only the value changed, they return an object
with a key and a value.

For example:
```
ractive.observe('somevar.myvar', function(newValue, oldValue, keypath){
   console.log(newValue);
});
```
Let's say that somevar.myvar changed from true to false then newValue gives you:
 Object { myvar=false}

**Comment by evs-chris** [comment]
I was trying to reproduce this for a test, but I haven't been able to come up with something that doesn't hand the values directly to the callback. Is there some more context to the observer, like some mappings or extra keypaths?

**Comment by JonDum** [comment]
Let me be Chris's translator for a moment.... 

Where's the fiddle, @kouts?

**Comment by kouts** [comment]
Here is the fiddle: http://jsfiddle.net/3fmz9ctc/8/
Open console and press the "Set to true" button.

**Comment by kouts** [comment]
I'm glad it helped!
