### ISSUE TITLE
on-click event does not work in <input .... disabled/>

### ISSUE THREAD

**Issue by tugrulkukul** [ractivejs/ractive#2577]
**Description of the bug:**
on-click event does not work in `<input .... disabled/>`

**Versions affected:**
0.7.3

**Platforms affected:**
linux/firefox

**Reproduction:**

**Code:**

Procedure included: https://jsfiddle.net/fxn2avg5/2/

**Comment by fskreuz** [comment]
Not sure if this is a bug. It appears to be correct behavior https://jsfiddle.net/a3fj6e7f/1/

**Comment by ceremcem** [comment]
A workaround is using `<div contenteditable="true" value="{{yourVariable}}"></div>` as inputs: https://jsfiddle.net/fxn2avg5/8/

**Comment by ceremcem** [comment]
FYI: This is an example how you can control "enable" or "disable" the `<div contenteditable ...`: https://jsfiddle.net/fxn2avg5/11/

**Comment by tugrulkukul** [comment]
Using `<div contenteditable ... ></div>` inplaces of `<input ...>` element suffices, thank you.
