### ISSUE TITLE
Private events does not work in components 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2579]
**Description of the bug:**

Events are triggered in main ractive template, but not in component definition: https://jsfiddle.net/s34o9u7j/1/

**Comment by evs-chris** [comment]
Unfortunately, we don't yet support an events hash for components. This works though: https://jsfiddle.net/s34o9u7j/2/

**Comment by ceremcem** [comment]
Well, there is no difference for me to define whether inside `oninit: ` or `on: ` keys :) This is more than enough, thank you :+1:
