### ISSUE TITLE
Component is not updated if js variable is set by another component

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2581]
**Description of the bug:**

Procedure is included: https://jsfiddle.net/js3ak747/7/

**Comment by martypdx** [comment]
`aa` is a primitive value (a string), so it gets _copied_ when you assign it to `myData` and `myData2`. That's just how javascript works. Ractive allows you to pass primitives into components and keeps them in sync, but it is fully in control of the data mapped between parent and child component.  

If `aa` were a reference and you modified one of it's properties, that would work (see https://jsfiddle.net/martypdx/9Lx1z39m/). 

Though if you assign the same object to two references (`myData` and `myData2`), Ractive still won't know that those ref to the same thing (unless you explicit tell it via `ractive.update`). Is there a reason you could use the same data twice like in your example?

**Comment by ceremcem** [comment]
OK, I remembered the same `string` issue in Python as you told. I'm still happy to use object or list, as in this fiddle: https://jsfiddle.net/9Lx1z39m/1/

We are creating a component library with Ractive (like jquery-ui's) and I want to be sure that the component will update its view as its javascript data is changed by anyone. 

Possible scenario: Think of two distinct components. One is a datatable, listing contents and allows editing a list of objects, other is a pie-chart that visualizes and permits editing a datatable in another format. 

my data contains: `hobby-name`, `where-i-learnt`, `how-much-do-i-like`
I should pass whole data to my  `<datatable ...>`
I should pass only `hobby-name` and `how-much-do-i-like` columns` to `<pie-chart ...>`. 
So `<pie-chart />` and `<datatable />` should use two distinct `ractive.data` as they accept different number of columns. 

A really pseudo code-ish  example for this purpose is as follows: https://jsfiddle.net/9Lx1z39m/2/

**Comment by evs-chris** [comment]
Way late, but ractive doesn't track separate references to the same data unless you `link` it. Links are available starting in 0.8.

With your fiddle, ractive doesn't know the myData[1] and myCheckbox are the same object. It sounds like having an observer keep the two sides in sync would be your best bet, since the data doesn't exactly line up on either side.

https://jsfiddle.net/9Lx1z39m/4/
