### ISSUE TITLE
Ractive events doesn't work on components

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2586]
**Description of the bug:**

I would expect ractive components behave just like any other native elements, but it seems ractive events are not working on components: https://jsfiddle.net/ceremcem/25e5wnv2/1/

## Edit

It doesn't work with `oninit: this.on...` binding either: https://jsfiddle.net/ceremcem/25e5wnv2/2/

**Comment by ceremcem** [comment]
Same problem occurs with Ractive-v0.8.8: https://jsfiddle.net/ceremcem/25e5wnv2/5/ . 

The ["Components currently only support simple events - you cannot include arguments. Sorry!"]( https://github.com/ractivejs/ractive/issues/1684) error is vanished, but Same problem occurs with Ractive-v0.8.8: https://jsfiddle.net/ceremcem/25e5wnv2/5/ .

**Comment by fskreuz** [comment]
I am not sure if native DOM events automatically convert to custom events and delegate up as component events. As far as I know, native DOM events and custom events are two different things. I may be wrong though. Thoughts @martypdx @evs-chris ?

However, I do know that you can [re-fire the DOM event as a custom event of `my-widget`](https://jsfiddle.net/25e5wnv2/8/). In this case, we fire a custom `customclick` from a DOM `on-click`.

```html
<div id="main-output"></div>
<script id="main-template" type="text/ractive">
  <p><span on-click="myRactiveEvent">Native element, Click me, it works</span></p>
  
<p><my-widget on-customclick="myRactiveEvent" text="Click me, doesn't work..." /></p>
</script>

<script id="my-widget" type="text/ractive">
<p on-click="fire('customclick')">{{text}}</p>
</script>
```

```js
MyWidget = Ractive.extend({
	template: "#my-widget"
})

ractive = new Ractive({
  el: "#main-output", 
  template: "#main-template",
  data: {
    hello: "world"
  }, 
  components: {
  	"my-widget": MyWidget
  }
})

ractive.on({
  myRactiveEvent: function(){
    alert("hello world!"); 
  }
})
```

**Comment by martypdx** [comment]
> I am not sure if native DOM events automatically convert to custom events and delegate up as component events. As far as I know, native DOM events and custom events are two different things. I may be wrong though. Thoughts @martypdx @evs-chris ?

Correct, component events are from the ractive instance, element events are DOM events or custom events. Given that you might have multiple top-level elements and that you might want to selectively expose which elements raise the click event, it seemed something best left in user land.

**Comment by ceremcem** [comment]
Thank you guys, custom events solved that issue! The explanation is clear enough... Do we have this distinction in documentation or should I add this example in there?
