### ISSUE TITLE
How can I get the contents of {{>content}} partial programmatically?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2592]
How can I use contents of  `{{>content}}` partial in Javascript side of a component? Here is the fiddle: https://jsfiddle.net/ceremcem/2aLeu75n/2/

**Comment by evs-chris** [comment]
`{{>content}}` is a partial template, so it's an array of template bits. Text nodes happen to come through as a string though, so `this.partials.content == ['World!']`. Anything more complex will get a bit confusing, but if you just want HTML out the other end, you could render it in a new throw-away Ractive instance e.g. `(new Ractive({ template: { v: 4, t: this.partials.content } })).toString()`.

**Comment by ceremcem** [comment]
Thank you!
