### ISSUE TITLE
Question 0.8 - get(root)BindingPath

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2593]
In this fiddle http://jsfiddle.net/d2w9zy28/9/ I'm using getBindingPath inside a decorator to
get the bound element's keypath.
When I'm inside a component I want to get the "absolute" keypath, (the root keypath if you will),
is this possible?

**Comment by evs-chris** [comment]
Sure, just pass in the instance to which you wish the path to be relative. So for your main instance, which we'll call `r`, `Ractive.getNodeInfo(someInputNode).getBindingPath(r)`. Note that if the data actually belongs to a child component, and is thus not reachable from the root instance, the returned path will _not_ lead to the data. The path has to actually be mapped.

I'm working on docs, I promise :smile:

**Comment by kouts** [comment]
Thanks @evs-chris , I tried passing the instance but I still get the keypath inside the component.
http://jsfiddle.net/d2w9zy28/12/

**Comment by evs-chris** [comment]
It looks like maybe there's a typo in that fiddle... if you change the component mapping to `<some-component checkedval="{{some.nested.value}}" />` rather than `<some-component checked="{{some.nested.value}}" />`, it looks like it works as intended?

**Comment by kouts** [comment]
Yes that was it! Thanks.
