### ISSUE TITLE
Drop IE8 for 0.8? Anyone still have to support it?

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#2597]
__Please vote__: use the thumb's up reaction on this comment to vote to drop IE8 support, and thumb's down to try to keep it.

I had a nice long rant about trying to debug IE8, but I'll spare you. 😄 You probably already know there's just no reasonable way to debug stuff on IE8. Also, @MartinKolarik bravely tried _actual_ IE8 in a VM and found that _emulated_ IE8 is actually more well-behaved. 😢

The first error in the test suite, in aliasing because the alphabet, is caused by `bind` being called on `Alias`, but the function that actually executes is `bind` on Transition. Obviously `Transition.bind` is going to fail when called on an `Alias`, but I have been unsuccessful in determining how that is happening at all. My only guess was that the `Transition.bind` was somehow becoming positionally global, but it has other `bind`s defined before and after. The prototypes also have references to the correct methods. 😖

All of my clients dropped IE8 early last year, and as of early this year, have also dropped IE9. I don't think maintaining IE9 support will be too cumbersome at this point; not so with IE8. Anyone else?

**Comment by fskreuz** [comment]
Minimum IE at our place is IE9.

**Comment by heavyk** [comment]
@fskreuz yep. IE8 is sooo 2006.

**Comment by mpowell-atomic** [comment]
At the very large corporation that I do some contract work for (using Ractive, of course), they upgraded everyone to IE11 earlier this year.

**Comment by JonDum** [comment]
Yea seriously don't waste any of those precious brain clock ticks of yours on IE8

**Comment by kouts** [comment]
IE8 not needed here too

**Comment by skeptic35** [comment]
Good riddance

**Comment by aharpervc** [comment]
IE10 is an acceptable minimum. Don't need to be concerned with versions older than that.

**Comment by tomekmarchi** [comment]
I would drop all of IE NP switch the focus to Edge.

**Comment by dagnelies** [comment]
A few related tidbits:
https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support
https://support.microsoft.com/en-us/lifecycle?p1=15672
...so I think it's safe to drop it.

**Comment by MrStonedOne** [comment]
Ugh, 

We use ractive in an embedded IE view for a game that still sees some windows xp users. Because microsoft won't release ie9 to windows xp, we are forced to support ie8

**Comment by fskreuz** [comment]
@MrStonedOne Oh cool! What game is this?

Anyways, correct me if I'm wrong, but the things that are polyfilled out of the box for older browsers are mostly ES5 APIs like array methods (see `legacy.js` for more). This can easily be resolved by polyfills like [es5-shim](https://github.com/es-shims/es5-shim) and others.

**Comment by aharpervc** [comment]
There is also always the option of not upgrading your version of ractive, and continuing to develop your app on an older version until you decide to not support IE8 any more.

**Comment by MrStonedOne** [comment]
>@MrStonedOne Oh cool! What game is this?
https://github.com/tgstation/tgstation/tree/master/tgui This one. (game is in parent folder) We have an entire subsystem for this, (its not our only interface, they all use ie embedded windows, some things use simple html interfaces, but most player side interfaces use tgui (based on ractive) (admin tools are all hard coded html for speed reasons))

As for the rest of what you all suggested, I have no idea, I don't actually understand newage web dev well enough, Just that we need to move to ractive8 once it's stable for the massive speed boost (I've tested it, and it does seem to load much much much quicker), but now we might have to drop xp support to do so.
