### ISSUE TITLE
Edge problem with IF statement in main template

### ISSUE THREAD

**Issue by enneid** [ractivejs/ractive#2598]
**Description of the bug:**
Follow template will gives parser error. If this code will be in partial this problem doesn't exists. Problem doesn't exists on 0.7
**Versions affected:**
Ractive 0.8 edge
**Platforms affected:**

**Reproduction:**

**Code:**
 `{{#if AppData}}
        Hide miniatures
    {{else}}
        Show miniatures
        {{/if}}`

**Comment by martypdx** [comment]
@enneid works in [this fiddle](http://jsfiddle.net/h84vskfw/). What is error are you seeing?

**Comment by enneid** [comment]
ok, my fault there was stupid legacy code, which breakes ealier code
