### ISSUE TITLE
Merge detaches and reattaches elements regardless of position - or how to sort efficiently

### ISSUE THREAD

**Issue by michaljerabek** [ractivejs/ractive#2599]
After a few recent changes half (ok, not that much) of my app stopped working. Now i'm trying to make it work again...

My first issue:

Earlier, when I had template like this:

```
<ul>
    {{#each array}}
        <li>{{.something}}</li>
    {{/each}}
</ul>
```

...then manually changed the order of (html) elements and then removed an item from the array, the order of elements remained unchanged. Now, after removing/adding an item, elements are reordered according to the array. Is this intended (and necessary) change?

**Comment by evs-chris** [comment]
It's not exactly intentional, but it was part of a bug fix. Ractive assumes it has full control over the DOM, and for now, takes the easiest approach of just re-attaching in the new correct order everything when a list section shuffles. There may be an optimization that would not re-attach all of the nodes when it detects a splice, push, pop, shift, or unshift. Note that even with that, re-arranging the DOM and then inserting a new (Ractive-controlled) element will cause the element to be attached where Ractive things it should, which may cause issues.

**Comment by michaljerabek** [comment]
Thanks. That's not good. 

I understand that inserting a new item with `splice` can cause issues, but shouldn't the other functions work correctly? (Everything I need is `push`, which had worked fine.)

**Comment by guilhermeaiolfi** [comment]
But do you really need to change the html yourself? It's usually better to change the order in your array and let ractive reflect the changes. Otherwise your DOM won't be in sync with your data and keep state in the DOM is a bad idea.

**Comment by michaljerabek** [comment]
It's drag-and-drop feature for sorting things. And it's not a simple list, but a list of very complex sections of a page containing many - also sortable - components. Of course I've tried to change the data in the array (after sorting is done), but everything failed in certain cases. The second thing is, that I don't want to re-render everything.

**Comment by martypdx** [comment]
> Of course I've tried to change the data in the array (after sorting is done)

Drag-and-drop is tough to do reactively if for no other reason than having to roll your own versus using an already built DOM sort library. Key part is you don't sort the DOM nodes, you sort the array on the fly as the user is dragging.

However, I haven't tried this with `0.8`. @evs-chris I'm hearing that on any splice operation, all the nodes get detached and reattached? That may cause havoc on something like a drag and drop ui done reactively. But maybe not if the browser is smart enough to leave them alone if it happens in the same event loop.

**Comment by evs-chris** [comment]
Yes, somewhere in 0.8 we started using a docfrag for shuffling. I'm bout to do a PR that just moves DOM around directly if the shuffle is splice compatible i.e. not a merge.

**Comment by michaljerabek** [comment]
>  Key part is you don't sort the DOM nodes, you sort the array on the fly as the user is dragging.

I know, but it is not working well and wasn't working well even before, because Ractive rerenders all elements after the dragged one. (Version 0.3.9 used in the ractive-sortable example does not do that.)

**Comment by martypdx** [comment]
> I know, but it is not working well and wasn't working well even before

Not sure what you mean:
* Are you saying that doing drag-and-drop in a reactive style doesn't work? 
* Or are you saying that manually sorting nodes and then appending doesn't work?

For the later, [0.7.3](http://jsfiddle.net/martypdx/ydu5qha5/) does as you describe but [0.8](http://jsfiddle.net/martypdx/sdkjow4m/) is reordering, though @evs-chris just pushed some changes that likely have not been propagating to cdn edge yet, so we can see if that works.

As to the former, having created an extensive drag and drop with 0.7.3, across multiple containers all synced real time across browsers with firebase, I can say it works fine. Not simple, but very functional.

>  because Ractive rerenders all elements after the dragged one.

In 0.7.3 this isn't the case. If I understand @evs-chris PR it would also not be the case for 0.8

**Comment by michaljerabek** [comment]
I didn't say it does not work, but half a year ago 0.8 rerendered everything after the position, where an item was inserted (into array). And that's not good if one of those items contains an iframe with Google Map.

**Comment by evs-chris** [comment]
Is edge as of now working for you?

**Comment by michaljerabek** [comment]
It's better, although it's still moving elements, wherever it wants to. But I have a different solution, but there is bug (possibly more then one). See [#2601](https://github.com/ractivejs/ractive/issues/2601).

**Comment by michaljerabek** [comment]
I have a question. If I want to reorder an array ("of components"), there are basically three options:

##### `set`
```javascript
var array = this.get("array").slice();
array.splice(0, 0, array.splice(2, 1)[0]);
this.set("array", array);
```
good: no element is re-rendered
good: no component is torn down
bad: content of elements is changed
##### `merge`
```javascript
var array = this.get("array").slice();
array.splice(0, 0, array.splice(2, 1)[0]);
this.merge("array", array);
```
good: no component is torn down
good: content of elements is not changed
bad: all elements are re-rendered
##### `splice`
```javascript
var array = this.get("array");
this.splice("array", 0, 0, array.splice(2, 1)[0]);
```
good: content of elements is not changed
bad: one component is torn down and replaced
bad: one element is removed and replaced

Obviously, I want the good stuff and none of the bad stuff. Would it be possible?

Thanks.

**Comment by JonDum** [comment]
I too would like to know that. 

Ideally all of those methods should do the same thing since you aren't doing anything that should break `===` checks, right?

**Comment by evs-chris** [comment]
I think `merge` is the best bet. I think it can be addressed, but out of curiosity, why is having the elements detached and re-attached a bad thing if you're no longer manually sorting?

**Comment by michaljerabek** [comment]
I'm actually still sorting elements manually*, but `merge` doesn't have problem with that. (It moves the element at the same position, so it does not matter. ...I think.)

The problem with re-attaching everything is that it re-renders (in my case) the whole page and this can mean more than a thousand elements and iframe with Google Map.

The second problem is that CSS Animations are triggered again.

By the way, the reasons why I don't like `splice` either are:

1. It causes problems with transitions. (New element is created.)
2. It tears down the component, which leads to two issues: 

- A component may be complex and the recreating process may take some time.
- You may have a reference somewhere to that component and if you don't know, this has happened or even don't know it works this way (which is not intuitive at all), you can get into trouble. (And by the way, ractive.org says: "Optimised for your sanity". ;))

*For sorting I'm using [touch-dnd](https://github.com/rkusa/touch-dnd).
