### ISSUE TITLE
Cannot escape static mustaches

### ISSUE THREAD

**Issue by mathCactus** [ractivejs/ractive#2603]
Cannot escape static mustaches.

To recreate try parsing '\\[[foo bar]]'

I think this should be available like it is for standard mustaches.

Many thanks.

**Comment by evs-chris** [comment]
I think I'm missing something? http://jsfiddle.net/br63j23d/1/

**Comment by evs-chris** [comment]
I'm thinking maybe this was meant to be `Ractive.parse('\\[[foo.bar]]')` where the js string escape was throwing in the monkey wrench (`'\[' === '['`) so I'm going to close this. If that's not it, please feel free to reopen.
