### ISSUE TITLE
error in commented rendering statement

### ISSUE THREAD

**Issue by enneid** [ractivejs/ractive#2606]
**Description of the bug:**
Could you give me a clue what may be problem with above partial. I've got some commented rendering statement, however it gives error: 

> Expected a JavaScript expression at line 6 character 38:
>                 {{#IsStaticLayer}}{{!>staticlayercontrol}}{{/IsStaticLayer}}
>                                      ^----

This error doesn't impact rendering, however, it is irritating at debugging

**Versions affected:**
edge

**Platforms affected:**

**Reproduction:**

**Code:**

```
    {{#Viewport}}
    {{#Spreads}}
        {{#Pages:idx}}
            {{#Elements}}
                {{#IsStaticLayer}}{{!>staticlayercontrol}}{{/IsStaticLayer}}
                {{#IsTextFrame}}{{!>textareacontrol}}{{/IsTextFrame}}
                {{#IsImageFrame}}{{>imagelayercontrol}}{{/IsImageFrame}}
            {{/Elements}}
        {{/}}
    {{/Spreads}}
    {{/Viewport}}
```

**Comment by fskreuz** [comment]
I'm not up to date with the recent developments. I know `{{> }}` are partials, but not sure what `{{!> }}` is.

**Comment by JonDum** [comment]
@fskreuz Comments :) 

http://docs.ractivejs.org/latest/mustaches#comments

**Comment by evs-chris** [comment]
This is apparently by design, as there are tests that ensure that comments have the lowest priority among the various mustache parsers. I don't think mustache comments were designed to remove bits of template, which I find weird, but ¯_(ツ)_/¯.
