### ISSUE TITLE
Bug: Teardown method is not called in decorators and events

### ISSUE THREAD

**Issue by michaljerabek** [ractivejs/ractive#2608]
**Description of the bug:**
`teardown` method is not called if the decorated element is inside another element.

http://jsfiddle.net/m82cgo0d/2/

EDIT: The same problem with events:

http://jsfiddle.net/m82cgo0d/3/

**Versions affected:**
0.8 - edge

**Platforms affected:**
Any browser

**Comment by michaljerabek** [comment]
This still doesn't work if a decorator is inside a component: http://jsfiddle.net/m82cgo0d/5/

**Comment by evs-chris** [comment]
Oops. Missed the component case. That facet is now fixed and has test coverage. Thanks!

**Comment by michaljerabek** [comment]
Better but not enough. :)

If the decorator is inside `{{#if}}{{/if}}`, it still doesn't work.

http://jsfiddle.net/m82cgo0d/6/

**Comment by evs-chris** [comment]
Conditional and iterative sections and partials. I _think_ that should have everything covered. :smile:
