### ISSUE TITLE
Bug: Styles are not removed after transition is done

### ISSUE THREAD

**Issue by michaljerabek** [ractivejs/ractive#2609]
**Description of the bug:**
Styles are not removed after transition is done, if the transition is added in the form of `-in-out` or `intro-outro`.

**Versions affected:**
edge

**Platforms affected:**
Any browser

**Reproduction:**
http://jsfiddle.net/c0whp4za/

**Comment by fskreuz** [comment]
Marking this as pending clarification. Not sure if this is intended behavior potentially because of the fact that the latter 2 have outros. Coincidence? Maybe. 😄
