### ISSUE TITLE
onInit method of a component is called many times 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2610]
**Description of the bug:**

According to [this](http://stackoverflow.com/a/29606409/1952991) explanation, `onInit()` method should be called only once whether it is rendered or re-rendered. 

Here is the fiddle that demonstrates it is called everytime it rendered: https://jsfiddle.net/ceremcem/ruv3nw8u/1/

**Versions affected:**

Stable, Edge

**Comment by evs-chris** [comment]
This is actually correct behavior. When a component is in a section that gets removed, it gets torn down completely. You can manually un-render and re-render the component, and oninit will not be called multiple times.

There was some discussion about keeping components intact if they go out with a conditional, and then re-rendering if the conditional comes back. I don't think any version of Ractive has done that though.

**Comment by ceremcem** [comment]
Thank you. So I should use something like `jQuery.hide()` instead of `{{#if ... }} ... {{/if}}`?

**Comment by evs-chris** [comment]
If you just want to show/hide something on the page, you can just use an inline style attribute e.g. `<div style-display="{{ condition ? '' : 'none' }}">...</div>` or `<div style="{{#unless condition}}display: none;{{/unless}}">...</div>`. You can't use inline styles on components, but you can on a wrapping element or on the top-level elements of the component.
