### ISSUE TITLE
How to get real element when render (true question how to make reference?)

### ISSUE THREAD

**Issue by acterhd** [ractivejs/ractive#2611]
Hello. In vue.js possible make v-ref for future getting element when template mounted. How to do same with ractive? How to make reference, and get element by this reference, when render event fired?

**Comment by woodlandhunter** [comment]
If I understand you correctly you ca use `componentInstance.find('*')` to get the root element for a component

http://docs.ractivejs.org/latest/ractive-find

**Comment by fskreuz** [comment]
You can use the [`ractive.find`](http://docs.ractivejs.org/latest/ractive-find) and [`ractive.findAll`](http://docs.ractivejs.org/latest/ractive-findall). The former acts like `document.querySelector` while the latter acts like `document.querySelectorAll`. However, they're all scoped within the component.

Also, to ensure the elements exist and are on the DOM, only call this on lifecycle events that happen from `onrender` onwards.

**Comment by woodlandhunter** [comment]
@fskreuz the docs say `onrender fires just before each time the component is rendered.` so I was a little unsure on whether the element would be available at this point.

**Comment by fskreuz** [comment]
@woodlandhunter That's odd. That sounds like `oninit`.

Here's the list of events http://docs.ractivejs.org/latest/lifecycle-events

**Comment by woodlandhunter** [comment]
Here's the page where that remark is found: http://docs.ractivejs.org/edge/components

**Comment by fskreuz** [comment]
Looks like a docs bug! 👍

**Comment by evs-chris** [comment]
The render event does fire right after the DOM is set up and before any transitions complete. Nodes _should_ be available in `onrender`.

**Comment by acterhd** [comment]
I had some expirence in vue, so I know that I can get DOM element when rendered. I in experimental way ran webgl.

**Comment by evs-chris** [comment]
You can also set up a decorator to track nodes as they pop in and out of existence.
