### ISSUE TITLE
each not working in ractive js

### ISSUE THREAD

**Issue by bhador1936** [ractivejs/ractive#2613]
Why ractive.js each not working on object array?

This is my js code :

```
var template  = "<table> \
    {{#each x.education}} \ 
        <tr> \
            <td>{{a}}</td> \
            <td>{{b}}</td> \
        </tr> \
    {{/each}} \
</table> \
{{y}}";

var data = {
    x: {
        education : [
            {a:1    ,b:'c'},
            {a:4    ,b:'ec'},
            {a:15   ,b:'cr'},
            {a:1    ,b:'ct'}
        ]
    },
    y: '123145'
};

var ractive = new Ractive({
    el: '#dataContainer',
    template: template ,
    data: data
}); 

```
And this is my HTML code:

`<div id="dataContainer"> </div>`

Response the displayed :‌

`123145`

**Comment by fskreuz** [comment]
There seems to be an error in your JS https://jsfiddle.net/5k133swL/1/. Please check the console.

On the other hand, everything is perfectly fine https://jsfiddle.net/5k133swL/
