### ISSUE TITLE
error in the tutorial 

### ISSUE THREAD

**Issue by dylan-shao** [ractivejs/ractive#2617]
**Description of the bug:**
there is a function error in the tutorial : http://learn.ractivejs.org/expressions/1 , which the 'format' function for the third 'case num>1000' is wrong, suppose the 'population = 2000', it will output '2,0'.
**Versions affected:**

**Platforms affected:**

**Reproduction:**

**Code:**
error: 'if ( num > 1000 ) return ( Math.floor( num / 1000 ) ) + ',' + ( num % 1000 );'

The correct should be: 'if ( num >= 1000 ) return ( Math.floor( num / 1000 ) ) + ',' + ( String.prototype.slice.call(num,-3) );'

**Comment by fskreuz** [comment]
I think this is better reported over at https://github.com/ractivejs/learn.ractivejs.org/issues

**Comment by dylan-shao** [comment]
you are right
