### ISSUE TITLE
0.8 edge possible error in ReferenceResolver.prototype.unbind

### ISSUE THREAD

**Issue by skeptic35** [ractivejs/ractive#2619]
Actually not so much a bug report but rather a note or a question or something. You'll work it out... ;). 

This [fiddle](http://jsfiddle.net/skeptic35/9b9qvwaz/) here is the closest I got to reproducing my "problem" (you'll have to open the console). Only difference being that in my setup I did not get the ambiguity warning even though running in debug mode. I found actually two ways to prevent this error from occuring:
1. Initialising the data
2. Moving the ```observe()``` call from ```onconfig``` to ```oncomplete```
My point is: It is obviously possible to build setups where the ```ReferenceResolver.prototype.unbind``` does not have a ```fragment``` property. What I don't know is if the method should be more forgiveable about that or if the missing ```fragment``` property is a sign of the setup being so fundamentally wrong that Ractive should throw an error here (preferably one that is helpful in resolving the problem ;) )

**Comment by evs-chris** [comment]
Interesting... I think that initially ambiguous observers should be able to be set up without a fragment present. The first solution that springs to mind is to fake a fragment when setting up resolvers from an observer if there isn't a fragment available. Anyone else?
