### ISSUE TITLE
Publish 0.8.0-edge to npm?

### ISSUE THREAD

**Issue by van-nguyen** [ractivejs/ractive#2620]
Can this be done? Please :)

**Comment by giovannipiller** [comment]
I don't believe that 0.8 is ready to be published.

However, you can npm anyway via terminal using its tag:
`npm install https://github.com/ractivejs/ractive.git#edge --save`

Better yet, you can use the URL of a specific commit hash.

**Comment by fskreuz** [comment]
Just for clarification, this was brought up before and the reason was because of npm https://github.com/ractivejs/ractive/issues/2326

In the end, the workaround is still to use a direct github reference.
