### ISSUE TITLE
each wont work inside the table 

### ISSUE THREAD

**Issue by NikosEfthias** [ractivejs/ractive#2624]
**Description of the bug:**
each wont work inside the table 
**Versions affected:**
0.7.3
**Platforms affected:**
linux
**Reproduction:**
```html
		<div id="place">
			<table >
				<tr>
					<th>#</th>
					<th>date</th>
					<th>amount</th>
				</tr>
				{{#each elems:index}}
				<tr>
					<td>{{index}}</td>
					<td>{{date}}</td>
					<td>{{transaction.amount}}</td>
				</tr>
				{{/each}}
			</table>
		</div>
```
**Code:**
```js
		<script>const $ = elem=>document.querySelector(elem)</script>
		<script>
	let transactionTable=new Ractive({
		el:$("#place"),
		template:$("#place").innerHTML,
			data: {
				elems:[]
}})
```
the template doesnt work each block is ignored and the properties are inherited from the global scope

**Comment by evs-chris** [comment]
The issue is that you're using innerHTML, which, with a table, eats any disallowed markup, including the each mustache. If you use a script or template tag or a string literal, you should get the whole template intact.

**Comment by NikosEfthias** [comment]
wow i didnt know that thank you :)
