### ISSUE TITLE
Conditional transition attribute

### ISSUE THREAD

**Issue by mefjuu** [ractivejs/ractive#2625]
**Description of the bug:** According to "edge" docs: 

> The intro, outro, and intro-outro directives have been deprecated and replaced by named and suffixed directives ${name}[-in][-out] e.g. fade-in-out. Arguments passed to these directives should no longer be wrapped in mustaches, as they are parsed as an array. Dynamism for transitions can be achieved with attribute sections.

we have a new transition syntax. However conditional `transitionname-in-out` attribute doesn't work.

**Versions affected:** 0.8-edge

**Code:** `<div class="dialog__box" {{#if effect}}scale-in="{duration: 200}"{{/if}}>`

**Comment by evs-chris** [comment]
I'm having trouble reproducing this. Does it work with the old-style syntax? Could you put together a fiddle?
