### ISSUE TITLE
Ractive size check

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2626]
## History of Ractive's size

```
# 0.4.0
387K ractive-legacy.js
138K ractive-legacy.min.js
313K ractive-legacy.runtime.js
112K ractive-legacy.runtime.min.js
377K ractive.js
134K ractive.min.js
303K ractive.runtime.js
107K ractive.runtime.min.js

# 0.5.8
435K ractive-legacy.js
157K ractive-legacy.min.js
397K ractive-legacy.runtime.js
144K ractive-legacy.runtime.min.js
421K ractive.js
152K ractive.min.js
383K ractive.runtime.js
139K ractive.runtime.min.js

# 0.6.1
446K ractive-legacy.js
162K ractive-legacy.min.js
409K ractive-legacy.runtime.js
150K ractive-legacy.runtime.min.js
432K ractive.js
157K ractive.min.js
396K ractive.runtime.js
145K ractive.runtime.min.js

# 0.7.3
426K ractive-legacy.js
167K ractive-legacy.min.js
365K ractive-legacy.runtime.js
146K ractive-legacy.runtime.min.js
413K ractive.js
162K ractive.min.js
352K ractive.runtime.js
141K ractive.runtime.min.js

# 0.8.7
466K ractive-legacy.js
213K ractive-legacy.min.js
400K ractive-legacy.runtime.js
188K ractive-legacy.runtime.min.js
453K ractive.js
208K ractive.min.js
387K ractive.runtime.js
183K ractive.runtime.min.js

# Dev
443K ractive.js
208K ractive.min.js
442K ractive.mjs
381K ractive.runtime.js
184K ractive.runtime.min.js
381K ractive.runtime.mjs
```
## Checklist of removable things

Currently exploring the code and found that these can either be shimmed/polyfilled or unnecessary.

- [x] ES5 Shims
- [x] `Promise` shim
- [x] `requestAnimation` polyfill
- [x] `getComputedStyle` polyfill
- [ ] Logging messages
- [ ] Deprecations
- [ ] Remove legacy code (see TODOs inside source code).
- [ ] Moving out lesser needed features as extensions
- [ ] (more to come)

---

It started with https://github.com/ractivejs/ractive/issues/153#issuecomment-235226752 which was an eye opener. But was Ractive really that small? So I looked at the `perf` directory which handily had a collection of the older versions and surprisingly, Ractive wasn't _that_ small to begin with (see below for full list from 0.4 to 0.8-edge). Buuut! Suggestions on how to trim the size is welcome.

## Comparison

I wouldn't compare Ractive to Ember or Angular. Their size justifies their features. I would rather compare Ractive to the likes of vue, riot, inferno and react, small component frameworks with a sprinkle of features.

### vue

```
267K vue.js
76K vue.min.js
```

From their install page, it looks like [warnings are stripped off](https://vuejs.org/guide/installation.html), which makes sense. Strings, particularly verbose ones, can't easily be compressed. Ractive has built-in debug mode in Ractive which might account for a bulk of that. Removing it from a production build will make debugging harder though.

### riot

```
92K riot+compiler.js
31K riot+compiler.min.js
72K riot.js
21K riot.min.js
```

Correct me if I'm wrong, but the last time I took a peek into riot's source, if offloads much of its operations to modern APIs. I think it uses actual custom elements so it might not be old-browser friendly.

### inferno

```
4.4K inferno-component.min.js
5.0K inferno-create-class.min.js
2.7K inferno-create-element.min.js
20K inferno-dom.min.js
7.8K inferno.js
3.5K inferno.min.js
8.8K inferno-router.min.js
3.8K inferno-server.min.js
```

I don't know the story of inferno other than that it's a "Ractive under React's clothing". But it appears that it has modularized its offerings. Assuming that the `infero.min.js` is the core package and everything else is an addon, adding them up, they're still 48.2K in total. Not sure if Ractive benefits from this manner of packaging.

### react

```
1.2K react-dom.js
 709 react-dom.min.js
1.2K react-dom-server.js
 728 react-dom-server.min.js
687K react.js
146K react.min.js
764K react-with-addons.js
157K react-with-addons.min.js
```

Looks like React's in the same league in terms of minified size. I can't say for sure why, I haven't been in their code. But their code compresses pretty good. It's either they use a good compressor, or or their code compresses good, or their development build just contains a lot of comments.

### Yox

```
106K yox.js
41.7K yox.min.js
```

A newly submitted entry. Seems to have roots from Vue.

**Comment by tomekmarchi** [comment]
What I have noticed is that many built in methods aren't wrapped in functions/cached or are used when a smaller & faster alternative is available. A quick example off the top of my head is the use of .forEach. One could easily have a simple forEach function that uses a for loop instead or at the very least acts as a wrapper. When time comes to minify it the function name will be drastically smaller plus may be a bit faster than typical forEach. This can be applied to a variety of built in methods and many JS utility libraries make use of it. Food for thought.

**Comment by MartinKolarik** [comment]
Using a custom function for `forEach` and other methods makes sense if it's because of performance, but doesn't really help with file size - the only size that matters is size after compression (which, btw, is what we should be comparing here) and that size is very similar in both cases. Sometimes even lower when **don't** try to optimize it by hand.

**Comment by tomekmarchi** [comment]
@MartinKolarik wasn't considering Gzip was looking it as stands. In that case which ever ends with less text and reasonable performance I'm all for. For me the above works so I stuck with it. Good looks.

**Comment by tomekmarchi** [comment]
@MartinKolarik ran tests today it is actually less after Gzip compression when using the slowest method. Using Keka the gain was 7,416KB vs 7,482. There is a performance and min gain to be had there alone. By much i would say it depends on the size of the project and the frequency of the functions used. I used a side project Acid (noted before) of mine as the test case. Either way performance and min gain results with my originally suggested method depending on project.

None the less there are some adaptors that were mentioned are to be gutted and moved as an extra option like magic mode and array adaptors those alone will be a huge plus.

**Comment by evs-chris** [comment]
I have a few changes that, in addition to resolving some chewy bugs, also cut several hundred loc out. I'm down to a handful of failing tests, but I'm still not positive that they'll pan out. They're fairly major changes in a few regards, though nowhere near as far ranging as the tree-lined model PRs,  and even if/when I get the tests passing they'll need a fairly thorough review.

Between that, deprecations going unsupported (another few hundred loc), and splitting out adaptors, Ractive should be able to lose a bit of weight for 0.9. There's also a fair chance that IE 8 won't be supported at some point in the near future, which would cut a bit of legacy stuff. Overall, I'd say there's a decent chance to get back below 400k for the unminified "legacy" build.

**Comment by tomekmarchi** [comment]
Looking through the source today and noticed on edge there is still a fallback for promises. With that being said are there plans to remove these bastardizations?

**Comment by fskreuz** [comment]
A checklist of these would be nice. I am not familiar with most of the inner workings, except the very explicit `legacy.js` file.

**Comment by trueadm** [comment]
@fskreuz Someone flagged this topic up on Inferno's Slack to me. I just wanted to point out that, in relation to the original post, you wouldn't combine all the Inferno packages. You can get by with `inferno.min.js` and `inferno-dom.min.js` – which is around 23.5kb min (7kb gzip). Inferno splits everything so it can remove bloat from core that developers don't want to use. 

Wouldn't this approach benefit Ractive's file size too? Or is that hard to do given how the codebase was written?

**Comment by fskreuz** [comment]
@trueadm There were discussions somewhere here about pulling out several built-ins into separate packages. Most of the code is still beyond me, although the more I get into it, the more I think Ractive was built "batteries included".

@evs-chris @MartinKolarik or @martypdx might have some more insight on this.

**Comment by tomekmarchi** [comment]
@fskreuz Thanks to your recent pull we should re-post the latest stats for the size check. let's continue working towards getting this thing down to a min.

**Comment by ghost** [comment]
Updated the sizes. A good 10k was removed with the recent PR, but didn't affect minified sizes that much.

Need. Moar. Exercise! 😄

**Comment by musicode** [comment]
https://www.npmjs.com/package/yox   Inspired by reactive.js

**Comment by ghost** [comment]
Currently doing some experiments with @evs-chris 's [hoist-props](https://github.com/evs-chris/hoist-props). Brought down 208K to 176K with nothing more than just adding it in the transform sequence.

Also doing a bunch of gobblefile tweaking to simplify build. Still waiting on a Buble fix though, specifically [this commit](https://gitlab.com/Rich-Harris/buble/commit/ddbc9c2bdd58ab0b1bef87e5a551a1e3bfc6213d). Ractive is plagued with imports having the same name as class methods. Hopefully @Rich-Harris will publish it soon. 😄

**Comment by MrSorcus** [comment]
```
laptop% du -sh ractive.min.js 
216K    ractive.min.js
```
Sad. Why ractive has big size? Legacy? Features? Backward compatibility?

**Comment by evs-chris** [comment]
Mostly features, all batteries included, and a very classy (as in made of classes, which don't minify particularly well) code base 😄.

We're shooting for < 200k (hopefully around 180k) minified for 1.0, which will be coming up next. On the plus side, transfer size is only ~60k gzipped. If you don't need runtime parsing, you can use the runtime-only build that is ~185k, which will hopefully be around ~150k for 1.0.

**Comment by MrSorcus** [comment]
Mmm...
```
laptop% du -sh vue.js 
252K    vue.js
```
It's a development version... Not minified... And vue is a `The Progressive JavaScript Framework`. Framework. Not a library, like a Ractive... But has smaller size.
What about custom builder, like a https://modernizr.com/download?setclasses

**Comment by kouts** [comment]
@MrSorcus I think Vue.js is a library pretty much like Ractive and not a complete framework, extended functionality comes as plugins e.g routing AFAIK.
The ```The Progressive JavaScript Framework``` is just a "pitchy" statement :smile:
Other than that I agree on the size comment, people often decide on the library they will use just
looking at the size.
