### ISSUE TITLE
Question: Are observers declared inside oninit or oncomplete destroyed on teardown?

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2627]
I usually set up observes inside the oninit or oncomplete instance methods.
Something like
```
        oncomplete: function(){
            this.observe('myvar', function (newValue, oldValue, keypath){
                if(newValue == true){
                   // do something here
                }else{
                   // do something else here
                }
            }, {
                defer: true
            });
        }
```
Are these destroyed automatically when the instance is torn down or do I have to manually cancel them inside the instance's teardown method?

**Comment by evs-chris** [comment]
They _should_ cancel when the instance is torn down. If they aren't, that would definitely be a bug.

**Comment by kouts** [comment]
Ok, so I don't need to normally cancel them, thanks @evs-chris .
