### ISSUE TITLE
Dynamic name attribute not evaluated for radio buttons

### ISSUE THREAD

**Issue by tw3** [ractivejs/ractive#2630]
Can someone please explain why the "name" attribute for my radio button does not get evaluated?

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<h1>Ractive test</h1>

<div id="container"></div>

<script id="template" type="text/ractive">
	 <p>Hello, {{name}}!</p>
	 <p>Radio: <input type="radio" class="radio-inline" name="{{fieldName}}" data-name="{{fieldName}}"/></p>
</script>

<script src="http://cdn.ractivejs.org/latest/ractive.min.js"></script>

<script>
var ractive = new Ractive({
	el: "#container",
	template: "#template",
	data: {
		fieldName: "foobar",
		name: "world"
	}
});
</script>
</body>
</html>
```

When I inspect the resulting HTML I see:

`<input type="radio" class="radio-inline" data-name="foobar" name="{{fieldName}}" value="on">`

This affects the latest version of ractive.

I see this in all IE, Firefox, and Chrome.

**Comment by tw3** [comment]
I see a similar bug reported for #1939 and a workaround was to avoid using a name attribute but instead wrap radio groups in separate form tags.  This does not seem like a good solution.

**Comment by tw3** [comment]
Invalid??

**Comment by MartinKolarik** [comment]
This is expected behavior because [Ractive uses the name attribute for two-way binding](http://docs.ractivejs.org/latest/two-way-binding#radios). If you don't want two-way binding for this the input, you can add attribute `twoway=false` and it'll render the name.

**Comment by tw3** [comment]
This seems strange because when I hard code the name attribute two-way binding seems to still work fine.

**Comment by tw3** [comment]
So the only way to create radio groups with dynamic names is to either turn off two-way binding or wrap them in separate <form> tags?

**Comment by MartinKolarik** [comment]
You mean two-way binding works with something like `<input name="myName">`? I don't see how that would be possible.

**Comment by MartinKolarik** [comment]
@tw3 what problem are you trying to solve? If you submit the form the normal way, you don't need two-way binding. If you use JS to submit it, name of the inputs doesn't really matter.

**Comment by evs-chris** [comment]
Two-way binding on radios (and checkboxes) is only available on the name and checked attributes. Setting `<input type="radio" name="{{someVar}}" twoway="false" value="whatever" />` where you don't want `someVar` to be tied to the value `"whatever"` won't affect anything else on the form. If you're trying to submit plain HTTP forms and have bindings too, you'll probably have to resort to wiring the binding side with events.

**Comment by tw3** [comment]
@MartinKolarik Thanks for your quick responses, I really appreciate your help.  My bigger issue is that I will be using ractive to generate dynamic forms, and sometimes these forms will have multiple radio groups.

My true logic looks more like:
```
<form>
{{#each formFieldArray}}
	{{# {fieldData: this}}}
		{{#each fieldData.radioOptions}}
			<input type="radio" id="{{this.radioId}}" name="{{fieldData.id}}" data-name="{{fieldData.id}}" {{#if this.bChecked}}checked="on"{{/if}}>
			<label for="{{this.radioId}}">{{this.valueLabel}}</label>
		{{/each}}
	{{/}}
{{/each}}
</form>
```

...where the input formFieldArray might look like this:

```
[{
	"id": "colors",
	"name": "Colors",
	"type": "radioGroup",
	"radioOptions": [{
		"radioId": "red",
		"type": "radio",
		"valueLabel": "Red",
		"bChecked": true
	 }, {
		"radioId": "blue",
		"type": "radio",
		"valueLabel": "blue",
		"bChecked": false
	 }
	]
},{
	"id": "animals",
	"name": "Animals",
	"type": "radioGroup",
	"radioOptions": [{
		"radioId": "horse",
		"type": "radio",
		"valueLabel": "Horse",
		"bChecked": false
	 }, {
		"radioId": "cow",
		"type": "radio",
		"valueLabel": "Cow",
		"bChecked": true
	 }
	]
}]
```

So if there is a way I can accomplish the radio groups with data binding but without wrapping the radio groups in separate form tags that would be great.  Otherwise I will probably turn off the two-way data binding and resort to jQuery code to grab the value during form submission.

**Comment by evs-chris** [comment]
Unless I've missed something, you only need one-way binding, so you can just throw a `twoway="false"` on your radio inputs and all will be well. Plain old one-way binding just renders something from your data into the DOM. Two-way binding takes that a step further and allows the DOM to also update the data when the user changes something e.g. checks a radio button or changes a text input. I don't see where you're using that in this case.

**Comment by MartinKolarik** [comment]
@evs-chris it seems @tw3 is using AJAX to submit the form, so two-way binding can be useful to "collect" the data.

@tw3 if you can't use multiple `<form>` elements, you'll need to turn off the two-way binding. However, you can "re-enable" it very easily by using method calls. Here's a simple example: https://jsfiddle.net/k18su33m/

**Comment by tw3** [comment]
@MartinKolarik that's correct I am using AJAX to submit the form and plan to use two-way binding to collect the form data.  Thanks for the pointers, I really appreciate the help.

**Comment by martypdx** [comment]
@tw3: Have you tried using keypaths? I modified @MartinKolarik's example and seems to work fine: https://jsfiddle.net/efu7xf6o/
