### ISSUE TITLE
Animations not firing/are too dogmatic and cause elements to be hidden on 0.8

### ISSUE THREAD

**Issue by ISNIT0** [ractivejs/ractive#2632]
**Description of the bug:**
When transitions are run, they set a height (and other properties) pixel value, even when it doesn't need to be set. This means that if data is loaded after the animation is fired, the parent's height is still set low.

I guess there are a few things that could be done:

* Figure out why 0.7.3 doesn't do this
* Add a method that can be called to re-run transitions (maybe it could be run automatically on data change)
* If the element is relatively positioned, default height and width to auto, rather than a pixel value

**Versions affected:**
0.8

**Reproduction:**
[Repro](http://jsbin.com/cazeros/edit?html,css,js,output)

**Comment by evs-chris** [comment]
I think the leftover values are related to changes to how styles are handled. We no longer wholesale overwrite the style attribute when binding styles, so Ractive can now get along with other libraries and decorators that change styles. I think we can add a step that records initial values when transitioning individual properties and allow the transition to reset everything once it is complete. See also #2609 

I don't see any transitions in the linked repro?

**Comment by ISNIT0** [comment]
Sorry, looks like I put the wrong link in:
[http://jsbin.com/cazeros/5/edit?html,js,output](http://jsbin.com/cazeros/5/edit?html,js,output)

You're probably right about that issue.

**Comment by evs-chris** [comment]
Looks like #2647 took care of this too.
