### ISSUE TITLE
Observers don't fire with conditional attrs on components

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2636]
**Description of the bug:**

Observers don't fire with conditional attributes on components.

**Versions affected:**

Edge/0.8

**Platforms affected:**
Chrome OS X 10.9

**Reproduction:**
http://jsfiddle.net/n2jzd5uv/1/
**Code:**

```js
const Foo = Ractive.extend({
    template: "#foo",
    oninit: function () {
		const self = this;
		self.observe('bar', foo => {
			self.push('log', 'bar changed');
		}, {init: false})
    }
});

var app = new Ractive({
  el: "#app",
  template: "#main",
  components: {
    Foo 
  },
  data: {
	  baz: ''
  },
});
```
```html

Main:

<input type='text' value='{{~/baz}}'/>

Foo: <Foo {{#if ~/baz}} bar='{{~/baz}}' {{/if}}></Foo>


Foo:
<pre>
	{{#log}}
		{{.}}
	{{/}}
</pre>
```

**Comment by evs-chris** [comment]
I have a branch (linky-stuff) where I've been working on issues like this, and with some minor adjustments, it now covers this as well. It's a pretty big chunk of changes addressing tough corner-casey  things, and it may not pan out. If you have a bit of spare time, give it a try. I'll open a PR against that branch soon™ explaining what all it does to get some review, feedback, and testing.

**Comment by JonDum** [comment]
Here's a fiddle with latest linky-stuff instead of edge http://jsfiddle.net/n42m91j4/

Seems to work now! I'm also trying out linky-stuff on some medium sized projects and will comment on that PR if I find anything.
