### ISSUE TITLE
Radio abandon two-way binding when switch repeatedly

### ISSUE THREAD

**Issue by babywhale** [ractivejs/ractive#2638]
**Description of the bug:**
as the title
**Versions affected:**
edge
**Platforms affected:**

**Reproduction:**

**Code:**
[http://jsfiddle.net/kg6na484/25/](http://jsfiddle.net/kg6na484/25/)

**Comment by fskreuz** [comment]
No Edge at the moment. Will test when I get to one. Your voice has been heard. 😄
