### ISSUE TITLE
Errors when using functions that return partial and two way binding

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2641]
**Description of the bug:**

When using a function that directly returns a parsed template and that template has a fragment with two way binding, bad things happen.

`Uncaught TypeError: Cannot read property 'fragments' of undefined` or an infinite loop.

Linky-stuff branch does not fix.

**Versions affected:**
Edge, Edge (linky-stuff)

**Platforms affected:**
Chrome, OS X 10.9

**Reproduction:**
http://jsfiddle.net/3dbpLo0q/2/

**Code:**
```html
modal: {{~/modal}},

<br/> ---- <br/>

{{! this one works fine}}
{{!> bar}}

{{! this one breaks}}
{{> modalPartialFor(modal) this}}
```
```js

const foo = Ractive.extend({
		template: `
		<span>Hi I am foo (comp)</span>. 
		
		<!-- Any element/component with two way binding here
		causes a crash/infinite loop -->
		<input type='checkbox' checked='{{.enabled}}'/>
		`
});
	
const bar = Ractive.parse(`Hi I am bar (partial)! 
	<br/>
	<foo></foo> 
`);

window.app = new Ractive({
  el: "#app",
  template: "#main",
  
  modals: {
  	bar
  },
  
  partials: {
  	bar
  },
  
  components: {
  	foo
  },
  
  data: {
  
	modal: 'bar',
  
	modalPartialFor(modal) {
		modal = modal.type || modal;
		return this.modals[modal] || this.partials[modal];
	},

  },

});
```

**Comment by evs-chris** [comment]
I'm glad someone else found dynamic literal partials useful :smile:

**Comment by JonDum** [comment]
Nice fix! And Yes I use them a lot for organizing partials! I have so many on some projects that I run into naming collisions.

**Comment by mikemaccana** [comment]
What version of ractive did the fix ship in? Thanks!

**Comment by evs-chris** [comment]
Looks like it landed just before the 0.8.0 release, so anything north of that should be good.

**Comment by mikemaccana** [comment]
That's weird, I'm getting in in 0.8.5:

    order.js:79016 Uncaught (in promise) TypeError: Cannot read property 'fragments' of undefined
        at Object.addFragment (order.js:79016)
        at Fragment.bubble (order.js:94207)
        at Section.bubble (order.js:86683)
        at Fragment.bubble (order.js:94210)
        at Section.bubble (order.js:86683)
        at Fragment.bubble (order.js:94210)
        at Element.bubble (order.js:86683)
        at Fragment.bubble (order.js:94210)
        at Element.bubble (order.js:86683)
        at Fragment.bubble (order.js:94210)

Checking version:

    yarn list v1.1.0
    └─ ractive@0.8.5
    Done in 1.23s.

**Comment by evs-chris** [comment]
That sounds like a change that's somehow happening outside of a runloop. There have been a couple of issues that have popped up where something triggers an invalidation from an unexpected place in the last year. If you have a sampling of template and a trigger (event, changed binding, etc), I can poke at it a bit.

**Comment by mikemaccana** [comment]
Hrm got in and found a particular module that was using HTML data values in `{{ }}` which seems to trigger this. Sounds like I was Doing It Wrong, but was creating an embed code for users from an ES6 string template. Have stopped doing that and it looks like this error has gone away. So yeah please leave closed!
