### ISSUE TITLE
Tuturial does not work on mobile device

### ISSUE THREAD

**Issue by Aeliot-Tm** [ractivejs/ractive#2649]
I tied to use tutorial (http://learn.ractivejs.org/hello-world/1/) on my mobile (samsung j7, browser: Chrome)
It does not work.

**Comment by evs-chris** [comment]
It's a bit painful to use on mobile, because code editing, but it works ok-ish in Chrome on my Nexus 6p. The navigation doesn't seem to want to click, but tap-hold works to navigate. Can you be more specific about what doesn't work?

**Comment by seriouz** [comment]
It is working for me in Chrome, too. But the site is definitely made for desktop browsers and not mobile or respsonsive!
