### ISSUE TITLE
Question: Way to tell if observable changed programmatically

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2651]
Is there a way to tell if an observable keypath was changed programmatically or by user input?

**Comment by dagnelies** [comment]
Not that I am aware of. I would advise either:
- putting the listeners directly on the input fields
- or use a flag variable before changing it programmatically

**Comment by evs-chris** [comment]
No, as far as Ractive is concerned all changes are the same. There may be a way to have the binding say that it's firing an update and then make that available through a context method, but there's no inherent "source" built in to the change propagation.

**Comment by fskreuz** [comment]
Not a direct answer to the question but if you have control of your integrations, you can wire up your plugin's events to call Ractive methods.

```js
const Input = Ractive.extend({
  template: '<input type="text" on-change="ractiveTriggered()">',
  onrender(){
    const input = jQuery(this.find('input')).plugin();

    // make the pluginTriggered Ractive method the callback of your plugin's on-change.
    input.plugin('onchange', this.pluginTriggered.bind(this));
  },
  ractiveTriggered(){ /* wired using Ractive's on-change */ },
  pluginTriggered(){ /* wired to the plugin's events */ },

});
```
