### ISSUE TITLE
Abstract widget with special content 

### ISSUE THREAD

**Issue by agronomhidden** [ractivejs/ractive#2652]
**Description of the bug:**

**Versions affected:**

**Platforms affected:**

**Reproduction:**

**Code:**

Hello!

I`m trying to write Abstract widget with self template with section "content", that must be abble to render partial template passed from root template.

Popup component:
```javascript 
var Popup = Ractive.extend({
    template: '#popup',
});
```
popup template:

```html
<script id='popup' type='text/ractive'>
	<div class="popup_wrapper" >{{>content}}</div>
</script>
```

main template:
```html
<script id='template' type='text/ractive'>
    <div class="checked-link">
		<span on-click="loc-check">{{#if open}}close{{else}}open{{/if}}</span>
		<div class="location_wrap" >
			<popup position='top'>
		</div>
		{{#partial content}}
			<div class="content">Specific content</div>
		{{/partial}}
	</div>
</script>
```
main script:
```javascript
var ractive = new Ractive({
    el: 'location',
    template: '#template',
    data: { open: false, locations: null },
    components: {
	popup: Popup
    }
    });
ractive.on('loc-check', function(e) {
    ractive.toggle('open');
});
```
It doesn't work. So is it posible to define partial (like: {{#partial}}...{{/partial}}) into the main template and then use it as "content" inside some widget (for example popup)?

**Comment by evs-chris** [comment]
Components can only get to inline partials from their parent if the parent includes them in their content. The content partial is also a special case that includes all of the content:

```html
<popup some="attributes">
  This is the content partial that is rendered with {{>content}}.
  {{#partial foo}}This is the foo partial that is rendered with {{>foo}}{{/partial}}
</popup>
```

You can pass as many named partials in a component's content as you like.

**Comment by agronomhidden** [comment]
Oh, thanks, evs-chris! It works right!
