### ISSUE TITLE
What is the best way to send a message to a component from another component?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2653]
Currently we can make different component's instances communicate over a var `new Ractive`'s `data.someVariable`. But what is the most convenient way to communicate between two ractive component instances? 

My specific problem starts here: I created a button that displays some icons (rotating wheel, warning sign, success sign, etc...) in order to give user about button click results. 

Button triggers some other event in surrounding ractive component (maybe another component, maybe the main instance). 

```
<ack-button on-buttonclick="myEvent" value="{{ someValue }}" /> 
```

`myEvent` should accept this value as well as an event argument, which I could send message back to this specific `ack-button` instance: 

```
function myEvent(event, value){
  ...
  event.instance.set("state", "error"); 
}
```

What should I pass as this `event` in order to use in the other component's instance as shown?

**Comment by martypdx** [comment]
You're think you're looking for `event.component.set("state", "error");`

**Comment by ceremcem** [comment]
Hmm. Should I pass caller's `this` object to the called function?

in the caller component 
```
this.on('myclick: function(val){
  ...
  fire('buttonclick', val, {component: this})
}
```

use it in the template: 

```
<ack-button on-buttonclick="myMainHandler" value="{{ someDynamicValue }}" ></ack-button>
```

in the handler event: 
```
ractive.on(
  myMainHandler: function(val, event){
    alert("got message: " + val);
    event.component.set("state", val);
  });
```

This setup works as expected. Is this the right usage?

**Comment by martypdx** [comment]
Depends on whether you are using `0.7` or `edge`. In edge [you can just do](http://jsfiddle.net/yuc3pzby/):

```js
this.on( 'myEvent', () => {
    this.event.component.set('value', 'bar');
});
```

I think with `0.7` you need to let it bubble from the component and not intercept.

**Comment by ceremcem** [comment]
Thank you, I think [I got it](https://github.com/aktos-io/aktos-scada2/blob/52ed084174c064512cb06ecee161e67f71a293c6/src/client/components/ack-button/index.ls#L33).
