### ISSUE TITLE
Events from component always cancelled when a handler is defined in parent

### ISSUE THREAD

**Issue by aphitiel** [ractivejs/ractive#2655]
**Versions affected:** 0.7.3 and edge

**Code:** http://jsfiddle.net/quvap3u9/

In the fiddle there are several elements containing a link. The link should lead to "/", clicking the element surrounding the link should fire some event.

This works as expected in the template (C). Once I make a component out of it and try to attach a handler in the parent, the event always gets cancelled (A). Not attaching the handler lets the event pass (B).

Is this by design or am I doing something stupid/wrong?

**Comment by martypdx** [comment]
I don't think you posted link for latest fiddle. I don't see any attached handlers. Did you mean http://jsfiddle.net/quvap3u9/1/?

But what you might be referring to is that if you use a component event handler to "recast" an event, it stops propagating the original event. So this line:

```html
<Comp on-compClick="test" />
```

stops the `compClick` event from bubbling and raises a `test` event instead

**Comment by aphitiel** [comment]
Sorry, messed up that link and possibly misunderstood the docs. Many thanks for your explanation!

So in cases like this I would attach a handler on each link and call stopPropagation() like in this updated fiddle http://jsfiddle.net/quvap3u9/3/ ? I can live with that, but it somehow feels dirty...

Or can this recasting behaviour be questioned? As I understand, ractive-events won't bubble out of the component unless explicitly requested. But DOM-events do, unless there is a component event handler defined. So from a practical POV component event handler means propagationStopped/defaultPrevented?

**Comment by martypdx** [comment]
> ractive-events won't bubble out of the component unless explicitly requested

No, they bubble out of the component like DOM events. You don't need to manually propagate, but you do need to use the qualified name outside the component. 

I think what your asking though, is how to stop the DOM event, but allow the component event to propagate? So, yes you could (within the originating component) call `event.preventDefault` to stop the `a` navigation. Or, you can `return false` in handler (even bubbled) and it will also call`preventDefault` and `stopPropagation` for you.

I guess questions is, what behavior _are_ you looking for in your specific situation?

**Comment by aphitiel** [comment]
> No, they bubble out of the component like DOM events. You don't need to manually propagate, but you do need to use the qualified name outside the component.

Oh yes, of course, that's another possibility. Not as pretty but works. Can we blame it on the heat that I didn't think of that?

> I think what your asking though, is how to stop the DOM event, but allow the component event to propagate?

The other way around: I wanted the DOM event to propagate, and found it strange that ractive *only* cancels the DOM event when a component event handler ```<Comp on-compClick="test" />``` is defined - the DOM event propagates unhindered when the event is handled with ```ractive.on('Comp.compClick',...```.

In my case I (think I) need the parent to handle clicks on certain elements in a component. These elements can contain links which I would like the browser to handle. 

But as I said I now understand that the component event handler recasts the event (without corresponding DOM event?) and can live with that. So if the DOM event cancellation is intended, I apologise for the time wasted.
