### ISSUE TITLE
Question: can I read back original keypath from a link in Edge?

### ISSUE THREAD

**Issue by drgnorq** [ractivejs/ractive#2657]
In Edge you can create an alias of a key path using link().

`myRactiveApp.link('document.nodes.7.subnodes', 'selectedNodes');`

In some event handler I need to know the original keypath that was assigned to 'selectedNodes'.

I think there is no direct access to myRactiveApp._links, that seems to be the place where defined links are stored. Is there some way to read back the original keypath (`document.nodes.7.subnodes`) or do I have to store it myself in a separate variable?

**Comment by evs-chris** [comment]
There's currently no API to determine link targets, so yes, you'd have to
keep track of that separately unless you want to muck about in Ractive's
internals.

Also, as of a few weeks ago, links are no longer stored in _links.
