### ISSUE TITLE
edge: Array linked to component via attribute: Rendering breaks after splice

### ISSUE THREAD

**Issue by aphitiel** [ractivejs/ractive#2659]
**Description of the bug:** Component gets array via ```<List list={{parentList}} />```. Once this array is spliced from inside the component, changes aren't rendered anymore. It seems the model is still Ok.

**Versions affected:** edge

**Reproduction:** http://jsfiddle.net/anqjzwu5/1/ Works if you comment out the splice in line 13.

**Comment by evs-chris** [comment]
Thanks for the report!

**Comment by aphitiel** [comment]
Thank YOU for the fast fix! \o/
