### ISSUE TITLE
edge: After unshift, event.resolve returns wrong keypath for array in array 

### ISSUE THREAD

**Issue by aphitiel** [ractivejs/ractive#2660]
**Description of the bug:** Rendering an array of arrays with event-emitters in subitems. After unshifting, 
event.resolve on later items returns a keypath with a too low index for the top items. event.toggle changes the wrong item. @keypath is ok.

**Versions affected:** edge

**Reproduction:** http://jsfiddle.net/2oo5hb29/1/

**Comment by evs-chris** [comment]
Thanks!

Out of curiosity, are you checking an existing app against edge?

**Comment by aphitiel** [comment]
Amazing, that did it!

Yeah, after finding http://docs.ractivejs.org/edge/migrating I just had to. Absolutely loving it so far! Sadly I'm not quite ready to publish yet...

**Comment by aharpervc** [comment]
That migrating doc is great... please make sure the directions for coming from 0.4.0 are up to date when edge turns in to 0.8.0 (which should probably be 1.0 at this point 😆 )
