### ISSUE TITLE
Collection sorting with two way binding inside (computed properties)

### ISSUE THREAD

**Issue by mefjuu** [ractivejs/ractive#2662]
**Versions affected:** 0.7.3, 0.8

**Code:** https://jsfiddle.net/ykz3241o/1/

Hello, I have a collection of objects with 2-way binding inside. The collection should be presented as a list sorted by its item's property (no need of doing array 'real' sort). 
I'm confused how it can be done in the right, efficient way?

**Comment by fskreuz** [comment]
It looks like sorting in this case is just presentational, and doesn't need to affect the original data. This is a job for [computed properties](http://docs.ractivejs.org/latest/computed-properties).

https://jsfiddle.net/ykz3241o/2/

```
var Component = Ractive.extend({
  template: `
    {{#each sortedLayers }}
      <div>
        <input type="text" value="{{.label}}">
        <input type="number" value="{{.zIndex}}">
        label: {{.label}}
        zIndex: {{.zIndex}}
      </div>
    {{/each}}
  `,
  data: {
  	layers: null
  },
  computed: {
    sortedLayers: function() {
      return this.get('layers').slice().sort((layer1, layer2) => layer2.zIndex - layer1.zIndex);
    }
  },
  onrender: function() {
    this.set('layers.0.label', 'Layer A after binding test')
  }
});


new Component({
  el: 'body',
  data: {
    layers: [{
      zIndex: 3,
      label: "Layer A"
    }, {
      zIndex: 4,
      label: "Layer B"
    }]
  }
});
```

A good way to know what properties are computed is when you can compute that data from original data. Think... functions, like `area = width x height` or `speed = distance / time` or in this case `sortedData = sort(originalData)`.

**Comment by mefjuu** [comment]
@fskreuz I've already tried the computed properties. Thanks for your effort, but as you can see in the fiddle you've posted - changing `zIndex` input doesn't re-sort the array...

**Comment by fskreuz** [comment]
Ahh, I see now.

I am not sure if this is a bug, although it might be. The way I understand how Ractive works is that it only recomputes when the dependents change. In this case, the section indirectly depends on the array, whether via computed function or the data function. However, when you interact with the form, it's not mutating the array, but the property of one of the elements in the array.

Running out of ideas at the moment. Hmmm...

**Comment by martypdx** [comment]
@fskreuz, @mefjuu: It works if you set the right field, `zIndex`, not `label`: https://jsfiddle.net/ykz3241o/6/

**Comment by mefjuu** [comment]
@martypdx Changing `<input type="number" value="{{.zIndex}}">` still doesn't affect on `sortedLayers`.

I think there could be `layers.*.zIndex` observer, but we need then some kind of forcing `sortedLayers` _recompution_.

**Comment by mefjuu** [comment]
I've found that computed properties can be updated via `update('computedKp')` (https://github.com/ractivejs/ractive/issues/651) so I updated the fiddle with a following observer: 
`this.observe('layers.*.zIndex', function(){...});`

https://jsfiddle.net/ykz3241o/7/

But it doesn't see updated zIndex by input editing.

**Comment by mefjuu** [comment]
Any ideas on it? I'm stuck with this problem and would be thankful for a concept.

**Comment by evs-chris** [comment]
This is a bit weird because the binding is not in the `layers` keypath due to the computation, so it's not easy to get an observer on the `zIndex` properties. The easy way out for 0.7.3 is to add an `update('layers')` when the zindex input changes: https://jsfiddle.net/ykz3241o/9/.

Edge is a little more difficult because bindings aren't allowed on computed paths, so you could do something more like:  http://jsfiddle.net/kg6na484/31/. Unfortunately that doesn't quite work in 0.7.3 due to a bug with bindings that cause their element to be ripped out from under them.

**Comment by mefjuu** [comment]
@evs-chris 

> Edge is a little more difficult because bindings aren't allowed on computed paths, so you could do something more like: http://jsfiddle.net/kg6na484/31/.

Note that original (not sorted) array's items observer (`layers.*`) doesn't work http://jsfiddle.net/kg6na484/33/ unfortunately.

**Comment by evs-chris** [comment]
It _looks_ like 0.8 has resolved most of the binding funkiness. 0.9 also has experimental support for binding and/or observing in computed (expression) keypaths, which should cover the other half of this issue, so I'm going to close it. Feel free to re-open if there's more to it.

**Comment by mefjuu** [comment]
@evs-chris Which functionality from v0.9 do you mean? Could you give more light on it?

**Comment by evs-chris** [comment]
0.9 has a flag that allows binding inside an expression context (`{{#with foo()}}<input value="{{.name}}" />{{/with}}`) called `syncComputedChildren`. It's an init flag, so `new Ractive({ ..., syncComputedChildren: true, ... })`. At this point, the changelog and source PRs are the best place to look for new info. I'm still working on docs.

While the `syncComputedChildren` flag should cover this case, you can also `observe` within an expression context (`{{#with foo()}}<div />{{/with}}`) using `ractive.getNodeInfo('div').observe('.name', v => ...)`.
