### ISSUE TITLE
How to use `debugger` statement in components 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2663]
**Description of the bug:**

How can we use `debugger` statement in components' Javascripts? 

**Versions affected:**

0.7.3

**Comment by martypdx** [comment]
Is `debugger;` not working for you?

**Comment by fskreuz** [comment]
Can you elaborate on your setup? There might be setups out there that could make debugging a bit more tricky (like the RequireJS setup that transforms the component file into a function created by `new Function` and debugger is the only way to pause code on VM-run code).

**Comment by ceremcem** [comment]
@fskreuz I'm [using browserify](https://github.com/aktos-io/aktos-scada2/blob/79fc63e52303c49f212a7125a1461f847888f154/gulpfile.ls#L153-L166) to compile my Livescript codes (both [application](https://github.com/aktos-io/aktos-scada2/tree/79fc63e52303c49f212a7125a1461f847888f154/apps/aktos/webapps/showcase) and [framework components'](https://github.com/aktos-io/aktos-scada2/tree/4a149b1738aaa12ac26eef17d58fbd6ffa330c90/src/client/components) codes) into Javascript. 

@martypdx  `debugger` statement works in my application codes, but not in components.

**Comment by fskreuz** [comment]
@ceremcem oooh, a compiler? Check if the output still has the `debugger;` statement. It might have been stripped somewhere in the tooling.

**Comment by ceremcem** [comment]
GRRRR!!! I'm sorry, I don't know how and why, but it works now and I can not reproduce this bug...

**Comment by ceremcem** [comment]
Well! I found the reason! 

If I place `debugger` statement right **after** an exception, then `debugger` statement does not work **and (but)** there is no error thrown in console or somewhere. That was why I thought that the `debugger` statement didn't work.

**Comment by evs-chris** [comment]
The 'break on all exceptions' setting is awesome :smile:

**Comment by fskreuz** [comment]
@evs-chris You'll snag a few dozen jQuery errors along the way before reaching the actual error. 😄

**Comment by evs-chris** [comment]
Oh jeez. I haven't had many encounters with jquery in the last few years. Can you blackbox it to skip all of that foolishness?

**Comment by ceremcem** [comment]
@fskreuz is right, when I click "Pause on caught exceptions" button, it stops everywhere, including [prelude-ls](http://www.preludels.com/): 
![screenshot_2016-09-23_09-37-25](https://cloud.githubusercontent.com/assets/6639874/18778186/d522051e-817b-11e6-885d-c242c135acf2.png)

**Comment by martypdx** [comment]
@ceremcem: It's in the settings on chrome. Put in matching string or regex and it should skip breaking in that library:

![image](https://cloud.githubusercontent.com/assets/478864/18786312/19248cc0-8152-11e6-97b0-64440c6690ab.png)
