### ISSUE TITLE
Idea: option to use CDATA sections or comments to split up adjacent text nodes in toHTML for enhance

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#2664]
HTML merges adjacent text nodes, which is problematic for progressive enhancement where adjacent VDOM nodes may end up being rendered as text. CDATA sections are not rendered, but they are still part of the document~~, unlike comments~~. There could be an option for `toHTML()` to output CDATA nodes next to non-element VDOM nodes that would allow the enhancement process to acquire individual text nodes instead of grabbing the first (and only) one and leaving the remainder of the textual VDOM nodes to insert additional text nodes.

Perhaps a similar solution could be applied to triples where a special CDATA content could be used as a marker for all of the nodes that should belong to the triple.

**Comment by martypdx** [comment]
>  still part of the document, unlike comments

Comments _are_ accessible via `childNodes` of parent element. But maybe you're referring to something else?

**Comment by evs-chris** [comment]
Huh. So they are. I'm not sure where I got that.

**Comment by MartinKolarik** [comment]
Wouldn't it be better to simply treat `Hello {{name}}!` like one text node instead of three? This idea came up before and I think I even started with the implementation back then but didn't finish it.

**Comment by evs-chris** [comment]
I also started trying to implement something like that, but I gave up when trying to figure out how to handle things like `foo{{#if bar}}<span>yep</span>{{/if}}bar` where nodes would need to split and rejoin.

**Comment by MartinKolarik** [comment]
Hmm that indeed looks problematic. I guess using comments would be easier.
