### ISSUE TITLE
each loop doesn't work with keys which includes "." character

### ISSUE THREAD

**Issue by sultanDMTR** [ractivejs/ractive#2665]
**Description of the bug:**
each loop doesnt work with key which has "." character in it in newest version of ractive but works with ractive 0.3.7
**Versions affected:**
http://cdn.ractivejs.org/latest/ractive.min.js //Ractive.js v0.7.3
http://cdnjs.cloudflare.com/ajax/libs/ractive.js/0.3.7/ractive.min.js
**Platforms affected:**
google chrome
**Reproduction:**
   http://jsfiddle.net/FarWn/113/  is working with key which has "." character in
   http://jsfiddle.net/FarWn/112/ isnt working

**Comment by MartinKolarik** [comment]
See #2549.
