### ISSUE TITLE
Up-to-date TypeScript definition?

### ISSUE THREAD

**Issue by seriouz** [ractivejs/ractive#2666]
Does anyone have a TypeScript definition for the latest ractive sources?
Besides: I suggest to make an official TypeScript definition file: Because in the current times more and more developers are switching over to TypeScript in their projects.

**Comment by MartinKolarik** [comment]
There is one, although it probably isn't fully up-to-date: https://github.com/codler/Ractive-TypeScript-Definition

You're welcome to improve it and send a PR either to @codler or to this repo.

**Comment by dandeven** [comment]
I made one for the version 0.7.3 here: https://github.com/dandeven/ractivejs.d.ts

**Comment by seriouz** [comment]
Perfect! I already found your definition and i'm using it now! 👍 
@dandeven You could create a pull request on ractivejs, so that your awesome definition file could go official?

**Comment by dandeven** [comment]
Sure @seriouz ... I'm happy to help.
Here it is: https://github.com/ractivejs/ractive/pull/2671

**Comment by seriouz** [comment]
@Dandeven thank your very much! Good work!

**Comment by dandeven** [comment]
This issue can be closed now. Typings can be found here: https://github.com/ractivejs/ractive/tree/dev/typings

**Comment by codler** [comment]
@MartinKolarik Actually [it](https://github.com/codler/Ractive-TypeScript-Definition) is up to date. Ractive API haven't changed.
