### ISSUE TITLE
0.8 Edge: Observers not firing correctly inside decorators

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2668]
Observers inside decorators are not firing correctly.
This [fiddle](http://jsfiddle.net/yvhhp2n6/) uses the latest edge, you can press the buttons and see that some values are not formatted correctly (you can press the buttons more than once to make it more obvious).
This [fiddle](http://jsfiddle.net/mqmzny8s/2/) uses the v0.8.0-edge-c0fd077dcbf14872da9f3a84dbc07a6b599e2118 commit which updates correctly.

**Comment by evs-chris** [comment]
The fiddle mostly works now, but note that formatting values while typing in a non-lazy bound field is not recommended.

**Comment by kouts** [comment]
thanks @evs-chris , I will try it using the "lazy" attribute.
