### ISSUE TITLE
How to read erb (rails) variables inside a ractive template

### ISSUE THREAD

**Issue by nkrasnogor** [ractivejs/ractive#2670]
**Description of the bug:**

Full disclosure: I am new to ractive and rails.

I am trying to use a rails variable (current_user.username) within a ractive template but have been unsuccessful.

Is there a simple way to: a) read the value of a rails variable (in my case associated with an Active Record) within the template part of a ractive component template and b) do so within the same *.html.erb file?

Any help or advice will be welcomed.

**Comment by fskreuz** [comment]
Not familiar to rails either. A little code on how the variable is normally put onto a page with rails could help.

If this is a matter of giving Ractive a value that's provided server-side during page load without an additional data call, printing a single global object with all that data would be the simplest approach. You can then pass it to your Ractive instance.

I normally do this in PHP:

```php
<!-- somewhere in head -->
<script>
  <?php if($some_data_structure_with_data): ?>
    window.AppData = <?php print json_encode($some_data_structure_with_data); ?>;
  <?php endif; ?>
</script>
```

Then in your top-level instance:

```js
var ractive = new Ractive({
  data: {
    username: AppData.currentUser.Username
  },
  ...
});
```

Another approach is to load the data in an AJAX call.

**Comment by nkrasnogor** [comment]
@fskreuz, 

Many thanks for your kind help. 

As I needed to dynamically change (not only in the first load) the value of a Ractive component I opted to follow the second approach you suggested (thanks) that needed to be  suplemented with the use of the  [gem gon](https://github.com/gazay/gon) as to more easily access rails variables in javascript. 

So all in all, it seems that to read a server side erb (rails) variable inside a client side ractive template one need to:

1.  install the gem gon in the Gemfile

2.  in the top level application.html.erb add "<%= include_gon(watch: true) %>" just after the `<title></title>` tag in the head section so gon functionality is available

3.  within a relevant controller (for the view one needs to dynamically render) use gon to 
     pass the variable values. For example (could be simplified):
      `@thispageuser = current_user`
      `gon.thispageuser = @thispageuser`

4.  and then specify that the ractive will update the variable in question via an Ajax call back
     function. For example:

        `var ractive = new Ractive({
          el: '#Rcontainer',
          template: '#Rtemplate',
          // Here, we're passing in some initial-default data
          data: { 
                  Rname:' '
                }
        });
        
        $.get('features', function(txt) {
        resetName(gon.thispageuser.name);
        });
            
        function resetName(txt)
        {
            ractive.set('Rname', txt);
        }   
`

**Comment by woodlandhunter** [comment]
I'm not sure if you example is just incomplete or I'm missing something but you're making an AJAX call with $.get(...) but never using the reply? You just use the gon global var embedded into the html.

Looking at the gem it appears the basic usage just helps you accomplish @fskreuz first suggestion. To use the more advanced form correctly with `watch` it looks like you have to call `gon.watch` from javascript.

**Comment by nkrasnogor** [comment]
@woodlandhunter  you are correct the example is partial as the AJAX response is used indirectly via the ractive.
