### ISSUE TITLE
White-space in #partial syntax

### ISSUE THREAD

**Issue by p3k** [ractivejs/ractive#2673]
**Description of the bug:**

I want to use white-space after and before the curly Mustache braces, and while it generally is not a problem with variables like `{{ foo }}`, blocks like `{{ #bar }}` and sections like `{{ #foobar }}` I am getting an error trying with partials like `{{ #partial barfoo }}`:

```
ractive-legacy.js:4107 Uncaught ParseError: Partial definitions can only be at the top level of the template, or immediately inside components at line 22 character 2:
{{ #partial barfoo }}
```

**Versions affected:**

At least 0.7.3 and edge.

**Platforms affected:**

Chromium Version 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Reproduction:**

http://jsfiddle.net/rL3a8znh/2/

**Code:**

```html
<script type="text/template" id="template">
  {{ #partial barfoo }}
	<h1>Hello World</h1>
  {{ /partial }}
  {{ >barfoo }}
</script>
```

```javascript
new Ractive({
	el: 'body',
	template: '#template'
});
```

**Comment by evs-chris** [comment]
This is now fixed in edge. Thanks for the report!
