### ISSUE TITLE
observing variable is not working for deeply nested objects in ractive 0.8.0 edge

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2675]
http://jsfiddle.net/3uc0g182/1/

**Comment by fskreuz** [comment]
Strange... It's not working in 0.7 either http://jsfiddle.net/3uc0g182/2/

**Comment by ceremcem** [comment]
Nope, it **works** with 0.7: http://jsfiddle.net/3uc0g182/3/

**Comment by ceremcem** [comment]
@evs-chris how can we get it from CDN?

**Comment by evs-chris** [comment]
After a pull request is merged, travis has to do his thing again, which will update the cdn. It looks like he just finished and the fiddle is working now. Thanks for the report!

**Comment by ceremcem** [comment]
You guys, you are awesome! :+1:
