### ISSUE TITLE
Component updates are problematic if we use `{{#if}}` in attributes

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2678]
**Description of the bug:**

If we use `{{#if}} ... {{/if}}` in a component instance's attributes, Ractive is not updating the component value for the first change, but updates correctly for the rest. 

**Versions affected:**

Ractive.js v0.8.0-edge
	Wed Oct 05 2016 18:21:35 GMT+0000 (UTC) - commit d05727dd2a7eda8206e65fa5441ff9de0bba937e

**Reproduction:**

Works well: http://jsfiddle.net/fz500nLj/7
Pay attantion that the `span` is not updated for the **first** change: http://jsfiddle.net/fz500nLj/5/

**Comment by evs-chris** [comment]
Fixed. Thanks for the report!

**Comment by ceremcem** [comment]
You welcome!
