### ISSUE TITLE
Bug: x.update is not a function

### ISSUE THREAD

**Issue by van-nguyen** [ractivejs/ractive#2679]
**Description of the bug:**
Recently I have updated to 0.8.0 from master branch, when I run Ractive on server-side it crashes when initialising Ractive with a template.

```
.../node_modules/ractive/ractive.runtime.js:2077
function update$1$1             ( x ) { x.update(); }
                                          ^

TypeError: x.update is not a function
    at update$1$1 (.../node_modules/ractive/ractive.runtime.js:2077:43)
    at Array.forEach (native)
    at Fragment.update$1 [as update] (.../node_modules/ractive/ractive.runtime.js:13801:15)
    at Fragment.bind$1 [as bind] (.../node_modules/ractive/ractive.runtime.js:13512:25)
    at initialise (.../node_modules/ractive/ractive.runtime.js:8093:6)
    at new Ractive (.../node_modules/ractive/ractive.runtime.js:14263:2)
...
```

**Versions affected:**
0.8.0

**Platforms affected:**
Mac OS, Linux etc.

**Reproduction:**
https://plnkr.co/edit/O9xGZLe3Z4X6w4BEyW1a

**Code:**
```javascript
const layout = new Ractive({template: '...'});
```

For the template, I have tried both the raw markup and also preparsed template, but they both give the same error.

**Comment by fskreuz** [comment]
A simple reproduction would be helpful.

**Comment by van-nguyen** [comment]
@fskreuz No worries, here's a quick plunker: https://plnkr.co/edit/O9xGZLe3Z4X6w4BEyW1a

**Comment by evs-chris** [comment]
The issue is with the doctype vdom class, which we apparently don't have fully covered in the test suite. A workaround would be the render the doctype outside of Ractive if you can.

**Comment by van-nguyen** [comment]
@evs-chris Wow who would have thought, thanks it's working now! 👍

**Comment by evs-chris** [comment]
Turns out a twoway binding was triggering an immediate update on the fragment, of which the doctype is a child, and there was no update to call on the doctype. This is now fixed in edge. Thanks for the report!
