### ISSUE TITLE
0.8 - Dependent lists do not update on data change

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2680]
This is a really strange one that unfortunately I cannot reproduce.
This is the [fiddle](http://jsfiddle.net/u4yxkvxe/12/) that I have tried to reproduce the issue.
- Change the first dropdown and select the L3 value.
- Change the first dropdown and select the empty value
- Change the first dropdown into the L3 value again then the second dropdown does not get updated.

This works correctly for me with commit v0.8.0-edge-c0fd077dcbf14872da9f3a84dbc07a6b599e2118
Please bear in mind that the fiddle posted above works, I couldn't reproduce it as hard as I've tried.

**Comment by kouts** [comment]
Ok I've managed to reproduce it!
Check this fiddle: [http://jsfiddle.net/e9wwtqz1/2/](http://jsfiddle.net/e9wwtqz1/2/)
When you select Object type  "Vehicle" it should hide the second dropdown.

This works as expected with 0.73 and commit v0.8.0-edge-c0fd077dcbf14872da9f3a84dbc07a6b599e2118

Thanks.

**Comment by evs-chris** [comment]
Another case of the expression proxy adding and removing itself from the model that it is updating and causing the forEach to skip some array members. This is now fixed in edge. Thanks for the report!
