### ISSUE TITLE
Observers with multiple wildcards seem to be firing even though data has not been changed there

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#2682]
**Description of the bug:**

Hi there,
in my attached example, observer will fire from 2 to 3 times, randomly, rather than just once.
The additional 1-2 fires are triggered by a `this.set(...)` on a location different from the one being watched.

I tried to extrapolate this simple example from my application, where a similar setup triggers an extremely frightening **"Maximum call stack size"** :(
Note: in my app there are many `this.set('blocks.${something}.data.${somethingelse}')` happening one after the other.

Hopefully, that's caused by the same bug.

0.7.3 is running just fine, and as far as I can remember it used to run ok on 0.8-edge up to a few months ago, though other issues prevented my upgrade.

**Versions affected:**
0.8

**Reproduction:**
See fiddle: http://jsfiddle.net/gigasoft/u20q621r/

(btw, thanks for the release guys 👍 ❤️)

**Comment by evs-chris** [comment]
Hmmm... it seems my test case wasn't quite good enough as the fiddle actually fails harder now. I'll poke it some more.

**Comment by evs-chris** [comment]
Errr... it helps to actually check the fiddle with the changes just made :smile:, so nevermind. I shall publish this as 0.8.1-build-2.

**Comment by giovannipiller** [comment]
I can confirm that this indeed solved my issues.
No more "Maximum call stack size"!! 🎉
