### ISSUE TITLE
Ractive 0.8.0 breaking change with attribute interpolation

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2686]
**Description of the bug:**
Ractive 0.7.3 doesn't show attributes with undefined attribute values.  Ractive 0.8.0 does.  Our app relies on Ractive 0.7.3 behavior, which, arguably, seemed correct. 

**Versions affected:**
0.8.0

**Platforms affected:**
Tested on Chrome Version 54.0.2840.59 m  on Windows 10 OS

**Reproduction:**
 0.7.3
https://jsfiddle.net/9r8qsv6r/

shows

`<div><textarea></textarea></div>`

 0.8.0
https://jsfiddle.net/3g2Lwzyd/

shows

`<div data-attr=""><textarea></textarea></div>`

[note that Ractive 0.8.0 creates an empty data-attr attribute, which is arguably wrong if, for example, it were a boolean attribute.  Absence of a boolean attribute is how you indicate it is false.  Presence of it indicates it is true.  But in this example, the mustached attribute value `{{foo.bar}}` evaluates to `undefined`, which presumably is falsey.]

**Code:**

**HTML**

```
<script` id='template' type='text/ractive'>
<div data-attr="{{foo.bar}}">
<textarea>
</textarea>
</div>
</script>

<div id='host'>
</div>
```

**JavaScript**

```
var r = new Ractive({el: '#host', template: '#template'});

var textarea = document.querySelector('textarea');
textarea.textContent = document.querySelector('#host').innerHTML;
```

**Comment by fskreuz** [comment]
It's breaking behavior, but not sure if it's a bug. `data-attr` is just another data attribute and not a boolean attribute. When `innerHTML` is done, it returns the attribute regardless if empty or not.

It's consistent with native behavior as well. https://jsfiddle.net/ev0vmqsh/2/
HTML:
```
<div id="foo">
  <div data-something="">Hello World</div>
  <input type="checkbox" checked="">
  <input type="checkbox" checked>
  <input type="checkbox">
</div>
```
JS:
```
alert(document.getElementById('foo').innerHTML);
```
Result:
```
<div data-something="">Hello World</div>
  <input type="checkbox" checked="">
  <input type="checkbox" checked="">
  <input type="checkbox">
```

**Comment by Jeff17Robbins** [comment]
Thank you for the explanation, and the quick fix!  

To reinforce my learning:  there are special boolean attributes (e.g. "required" or "disabled") and these behave as expected in Ractive 0.8.0.  

All other attributes are strings, and so no matter what their value is, it will end up as a string (possible empty for things like `undefined` and `null`.)

So this breaking change in Ractive 0.8.0 is actually a "break" for the better!
