### ISSUE TITLE
Whitespace in observe keypath causes whole model to be observed

### ISSUE THREAD

**Issue by richbenwell** [ractivejs/ractive#2690]
**Description of the bug:**
If an observe keypath has preceding or trailing whitespace then the the whole model is observed in addition to the keypath(s) specified. 

Probably not a common issue, but it does cause unexpected behaviour.

**Versions affected:**
0.8 and 0.8.1-build-2 
No issue on 0.7.3

**Platforms affected:**
n/a (tested on Chrome 53)

**Reproduction:**

http://jsfiddle.net/sgq3myjL/

**Code:**

Example:

`this.observe('aProperty ', handler)`

**Comment by evs-chris** [comment]
This is now fixed in edge. Thanks for the report!

**Comment by richbenwell** [comment]
Thanks for the fast turnaround. Awesome!

Just starting initial work on porting a large app built with Ractive 0.7.3 (see https://demo.squaredup.com). Will report other issues as we find them...

Great job with Ractive 0.8. Look forward to using it and hopefully contributing to 0.9!
