### ISSUE TITLE
Should we still support Node < 4?

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2692]
Today, I meticulously updated dependencies to avoid updating modules that break the build due to various reasons (*cough* **gobble** *cough* **rollup** *cough*). But then I hit another snag. The latest ESLint [does not support Node < 4](http://eslint.org/docs/user-guide/migrating-to-3.0.0). This makes me wonder...

Should we still support Node < 4?

**Comment by MartinKolarik** [comment]
For development or using Ractive in general? For development, I think it's completely fine not to support it. I know that also means we won't be able to run tests on those old versions, but we don't really use any node specific functions and as long as Ractive runs on v6, it should run on v0.10 too.

**Comment by evs-chris** [comment]
I'm :+1: for dropping everything older than 4. That would also reduce the chances that phantom decides to hang during ci and cause a run to need to be kicked off again.

**Comment by codler** [comment]
We can drop support for node < 4

**Comment by evs-chris** [comment]
Goodbye old node. :smile:
