### ISSUE TITLE
unexpected observe callback in Ractive 0.8.0

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2693]
**Description of the bug:**
A data viewmodel with two fields:  `fieldA` and `fieldB`.  Setting `fieldA` causes an `observe(...)` on `fieldB` to callback unexpectedly on Ractive 0.8.0 (it doesn't on Ractive 0.7.3.)

**NOTE**: this problem seems to involve interaction between a user-written adaptor (provided in the jsfiddle links below) and Ractive's built-in "modifyArrays" adaptor.

The problem seems to be the result of this function in Ractive 0.8.0:

```
function update$3 ( ractive, model ) {
	if ( model.parent && model.parent.wrapper ) return update$3( ractive, model.parent );
```

In the reproduction on jsfiddle, the user-written adaptor does this:

```
parent.update(keypath + '.' + key);
```

which is the same as 

```
storeB.update('StoreA.fieldA');
```

I didn't expect this call to `.update(...)` to cause a callback on an `.observe('StoreA.fieldB')`, but `update$3`, because of the presence of `model.parent.wrapper`, recursively calls `update$3`, but this time on the parent `StoreA` in its entirety.  Then, somehow due to the modifyArrays adaptor, this causes the `.observe('StoreA.fieldB')` to callback.

This is a regression from 0.7.3, and also seems like incorrect behavior.

**Versions affected:**
Ractive 0.8.0

**Platforms affected:**
Windows 10 Chrome Version 54.0.2840.59 m

**Reproduction:**
Ractive 0.7.3 https://jsfiddle.net/8455fddf/
textarea remains blank (because the observe callback does not get called)

Ractive 0.8.0 https://jsfiddle.net/t84t0ppk/
textarea gets value from callback, showing unexpected callback for keypath `fieldB`

**Code:**
HTML
```
<textarea style="width: 500px; height: 50px;"></textarea>
```

JavaScript

adaptor
```
(function() {
  var Adaptor = Ractive.adaptors.Ractive = {
    filter: filter,
    wrap: wrap
  };

  function filter(child, keypath, parent) {
    if (!(child instanceof Ractive))
      return false;
    if (parent &&
      parent._ractiveWraps &&
      parent._ractiveWraps[keypath])
      return false;
    return true;
  }

  function wrap(parent, child, keypath, prefixer) {
    setup();

    return {
      get: get,
      teardown: teardown,
      deactivateOnDetach: true,
    };

    function setup() {
      markAsWrapped();
      child.on('change', onChange);
    }

    function teardown() {
      delete parent._ractiveWraps[keypath];
      child.off('change', onChange);
    }

    function onChange(updates) {
      each(updates, function(value, key) {
        if (key) {
          console.log('adaptor regular update', keypath, key, value);
          parent.update(keypath + '.' + key);
        } else { // e.g. child.reset(newData)
          console.log('adaptor no key update', keypath, key, value);
          parent.update(keypath);
        }
      });
    }

    function get() {
      console.log('adaptor in get')
      return child.get();
    }

    function markAsWrapped() {
      if (!parent._ractiveWraps) parent._ractiveWraps = {};
      parent._ractiveWraps[keypath] = child;
    }
  }

  function each(obj, fn) {
    for (var key in obj) {
      if (obj.hasOwnProperty(key)) fn(obj[key], key);
    }
  }
}());
```

code using the adaptor and the modifyArrays adaptor
```
var storeA = new Ractive({
  modifyArrays: true,
  adapt: ['Ractive']
});
window.StoreA = storeA;
storeA.set({
  fieldA: false,
  fieldB: ["some string"]
})

var storeB = new Ractive({
  modifyArrays: true,
  adapt: ['Ractive']
});
window.StoreB = storeB;
storeB.set('StoreA', storeA);

var output = document.querySelector('textarea');
storeB.observe('StoreA.fieldB', function(n, o, k) {
  console.log('in observe of StoreA.fieldB with', 'new value =', n, 'old value =', o, 'keypath =', k);
  output.value = 'observe("StoreA.fieldB") callback with new value = ' + n + ' old value = ' + o + ' keypath = ' + k
}, {
  init: false
});

storeA.set('fieldA', true);
```

**Comment by evs-chris** [comment]
Eeesh. The adaptor API is begging to be updated to handle various cases in a more sane manner. I'm thinking that basically having a pluggable Model API is the ultimate answer, so that the adaptor can decide, among many other things, how to handle deep access. I think that would be pretty awesome for firebase and similar graph-y structures.

It looks like you're using the ractive-ractive adaptor, so I'd love to get your input on #2674, which includes `parent.link('', 'some.path.to.child', { ractive: child })`, or at least I think it does... linking the root may or may not work, but it should. That would put all of `child`s viewmodel at `parent.get('some.path.to.child')` where any sets on either side propagate correctly because the actual models handle it and then forward the notification back through the links.

I'm hoping to get 0.9 out within a reasonable (< 2 mo.) amount of time with the major goals of getting the code slimmed down a bit and a decent API for managing components.

**Comment by evs-chris** [comment]
Confirmed that this particular adaptor bug isn't happening any more: https://jsfiddle.net/t84t0ppk/1/

Thanks for the report!

**Comment by Jeff17Robbins** [comment]
Thank you for the blazingly fast fix!
