### ISSUE TITLE
[solved] Order of dynamic components is not maintained (experimental feature)

### ISSUE THREAD

**Issue by paulocoghi** [ractivejs/ractive#2695]
**Description of the bug:**
Using [dynamic components](http://stackoverflow.com/questions/31075341/how-to-create-ractives-subcomponents-dynamically-and-change-them-programmatical) (experimental) worked perfectly since Jun 2015, but now the component's order is lost when changing one of them.

_(We had already solved the problem since our first experiments, and I removed the fix by mistake. The solution is to wrap each dynamic component into a div. Please, see the second comment for easy details.)_

Considering this template:

```html
<dynamic name='{{header}}'/>
<dynamic name='{{content}}'/>
<dynamic name='{{footer}}'/>
```

When I change `content` value to point to another component name, the respective component (sitting in the middle) falls down this way:

```html
<!-- Before component change -->
Header

Content 1

Footer
```

```html
<!-- After component change -->
Header

Footer

Content 2
```

**Versions affected:**
Latest (0.8.0)
Edge (0.8.1-edge)
Strangely the old stable too (0.7.3)*

*Used for more than a year without this issue in [altiva/altiva](https://github.com/Altiva/altiva)

**Platforms affected:**
Tested in Chrome and Firefox, but only in linux

**Reproduction:**
Latest (0.8.0) : http://jsfiddle.net/8fsxxg04/
Edge (0.8.1-edge) : http://jsfiddle.net/gf03hxh1/1/

Old-stable (0.7.3) : http://jsfiddle.net/tu1d32ur/1/ (just for reference)

**Code:**

**[Html]**
```html
<script id='template' type='text/ractive'>
   
    <button on-click="goto_content_2()"><b>Go to content 2</b></button>
    <button on-click="goto_content_1()">Go to content 1</button>
    
    <dynamic name='{{header}}'/>
    
    <dynamic name='{{content}}'/>
    
    <dynamic name='{{footer}}'/>
       
</script>
```

**[Javascript]**
```javascript
Ractive.components.header = Ractive.extend({ template: '<p class="header">Header</p>' });
Ractive.components.content1 = Ractive.extend({ template: '<p class="content">Content 1</p>' });
Ractive.components.content2 = Ractive.extend({ template: '<p class="content">Content 2</p>' });
Ractive.components.footer = Ractive.extend({ template: '<p class="header">Footer</p>' });

Ractive.components.dynamic = Ractive.extend({
    template: '<component/>',
    components: {
        component: function() {
            return this.get('name');
        }
    },
    oninit: function(){
        this.observe('name', function(){
            this.reset();
        }, { init: false});
    }
});


var r = new Ractive({
    el: document.body,
    template: '#template',
    data: {
        header: 'header',
        content: 'content1',
        footer: 'footer',
    },

		goto_content_1: function() {
    		this.set( 'content', 'content1' )
    },

		goto_content_2: function() {
    		this.set( 'content', 'content2' )
    }
});
```

**Comment by paulocoghi** [comment]
Problem solved: wrap each dynamic component in a div.

```html
<script id='template' type='text/ractive'>

    <button on-click="goto_content_2()"><b>Go to content 2</b></button>
    <button on-click="goto_content_1()">Go to content 1</button>

    <div><dynamic name='{{header}}'/></div>

    <div><dynamic name='{{content}}'/></div>

    <div><dynamic name='{{footer}}'/></div>

</script>
```

**Comment by evs-chris** [comment]
This was a bug, as a component should always be able to find the correct anchor so as not to get out of order. Wrapping in a div is a workaround because the element can properly find its render anchor. This is now fixed in edge. Thanks for the report!

**Comment by paulocoghi** [comment]
@evs-chris A thousand thanks!
