### ISSUE TITLE
0.8.1 Edge - too much recursion

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2699]
Here is the fiddle: [http://jsfiddle.net/rn6e9Lr0/16/](http://jsfiddle.net/rn6e9Lr0/16/)
Open the console and press the "Update" button.
I think that there is something related with {{yield}} but I'm not sure.

This works as expected with 0.8.0-edge-c0fd077dcbf14872da9f3a84dbc07a6b599e2118
([http://jsfiddle.net/g3L56tjf/1/](http://jsfiddle.net/g3L56tjf/1/))

Seems that something changed after that build.

**Comment by evs-chris** [comment]
This was an issue related to linking linked arrays and then shuffling from the link. I added some guards to keep nested links from triggering shuffles on themselves while they shuffle, and it looks as though that's got it fixed. Thanks for the report!

**Comment by evs-chris** [comment]
Also, I published 0.8.1-build-5 with this change :smile:
