### ISSUE TITLE
Fire render complete event after observer

### ISSUE THREAD

**Issue by seriouz** [ractivejs/ractive#2702]
Is there a way to fire a render complete event after an observer fired and the ui changed?

I think i could use the "complete" event but how do i know which observer fired?

**Comment by fskreuz** [comment]
[Observers](http://docs.ractivejs.org/latest/ractive-observe) accept a third argument, and object, that configures observer execution. The `defer` boolean option configures when the observer runs. 

- When `false` (default), the observer before the DOM is updated.
- When `true`, the observer runs after the DOM updated.

So it would look like:

```js
this.observe('path.to.observed.data', function(newValue, oldValue){
  // code to run
}, {
  defer: true
});
```

**Comment by seriouz** [comment]
Thanks! Its working with `defer: true`
