### ISSUE TITLE
Tutorials and examples not in sync with latest release of Ractive.js

### ISSUE THREAD

**Issue by zuck** [ractivejs/ractive#2703]
## Description:
Tutorials and examples are not in sync with the latest available _Ractive.js_ release.

These should be kept in sync to the very last release and, in case, provide previous versions for older releases (like for example _Django_ project does with its docs).

An important issue is that, at the moment, the tutorials explain deprecated features or _modus-operandi_, generating confusion to new adopters (e.g. _proxy events_).

## Versions affected:
**0.8.0**, at the moment.

## Platforms affected:
All

## Reproduction:
Just visit http://learn.ractivejs.org/ and open the dev console in Chrome. The Ractive.js version is stuck on 0.7.3 instead of 0.8.0.

**Comment by fskreuz** [comment]
Yep, we're aware of this. We're also undermanned at the moment (you can see @evs-chris hard at work on almost everything! 🤓 ).

Pull requests to any of the Ractive projects, including docs, are very much welcomed. 😄 

> If in doubt, submit the PR. A PR that needs tweaking is infinitely more valuable than a request that wasn't made because you were worrying about meeting these requirements.

More details on how to submit contributions in [CONTRIBUTING.md](https://github.com/ractivejs/ractive/blob/dev/.github/CONTRIBUTING.md)
