### ISSUE TITLE
Render ractive components in HTML

### ISSUE THREAD

**Issue by chenxsan** [ractivejs/ractive#2707]
As far as I know, I could use components inside template like:

```
<script type='text/ractive' id='template'>
  <component id=1/>
  <component id=2/>
</script>
```

What if i want to use them right inside HTML:

```
<body>
  <h1>A show for ractive components</h1>
  <component id=1/>
  <component id=2/>
</body>
```
In this way, I can render the components with their initial states right in the server side, and let ractive.js take control then in the front end.

But as @Rich-Harris suggested in [this issue](https://github.com/ractivejs/ractive/issues/299#issuecomment-30055156), browser would mess the innerHTML with custom component. So it won't work.

I made a demo [here](http://jsbin.com/qosuma/edit?html,js,console,output), any way to work around this problem?

**Comment by evs-chris** [comment]
I think you're looking for progressive enhancement, where the html, including components, is rendered server-side and then absorbed by Ractive without being completely rerendered? If so, as long as your component definitions are in place everywhere Ractive renders, you can pass it `enhance: true` and it will try to reuse the existing DOM to the extent that it can.

**Comment by chenxsan** [comment]
Yes, that's what I am looking for. But I found it's because of a problem I made.

My component in my example was written as:

```
    <my-vote type=1 />
    <my-vote type=-1 />
```
And I got the `innerHTML` as:

```
"
    <my-vote type=\"1\">
    <my-vote type=\"-1\">
  </my-vote></my-vote>"
```

I changed them to:

```
<my-vote type=1></my-vote>
 <my-vote type=-1></my-vote>
```
Now it works like a charm.
