### ISSUE TITLE
[question] Adding multiple properties to a data's object without multiple updates

### ISSUE THREAD

**Issue by paulocoghi** [ractivejs/ractive#2708]
**Description**
How to add multiple properties to an object (not an array, but a real object) inside "data", e.g. 100 additional properties, without causing 100 updates, but only one.

Or, how to temporarily disable updates for a specific keypath.

**Example ( with fiddle https://jsfiddle.net/t8nf9jmx/ )**

```javascript
var app = new Ractive({

    data: {
        users: {
            'rich-harris': { name: 'Rich Harris' },
            'evs-chris'  : { name: 'Chris Reeves' }
        }
    }
    
})
```

The automatic update below is awesome, but I would like to disable it temporarily
```javascript
// Here we have only 'rich-harris' and 'evs-chris'
var users = app.get( 'users' )

// This will update app.data.users, without using app.set(), which is awesome!
// But how can I disable updates temporarily?
users[ 'martypdx' ] = { name: 'Marty Nelson' }

// This will output users including 'martypdx'
console.log( app.get( 'users' ) )
```

to avoid multiple updates when adding large additional data.

---

**Why I am not using arrays? (in order to use `modifyArrays: false`)**

I need to be able to find data by its original key value, not by a inconstant array position.

Using array would force me to create an additional table to store the pair "key -> array_position" and operations like `splice` changes the array, making my index-table inconsistent and forcing a new re-index operation.

In the other hand, removing an item from my "object-with-objects" doesn't affect access to remaining data.

---

**Why not clone `users` object and, after all additions, use `app.set( 'users', new_users )`**

Although there are **[really fast](https://jsperf.com/cloning-an-object/143)** ways to clone, there is nothing better than not clone at all.

Instead of doing more work just to stop Ractive updates, tell Ractive to do less work seems interesting.

**Comment by fskreuz** [comment]
Construct an object to house your 100 properties then use [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) to update the `users` object.

```
Object.assign(app.get( 'users' ), {
  // an object with your 100 properties
});
```

**Comment by paulocoghi** [comment]
@fskreuz Excellent!

Your alternative is even better, because we don't need to stop Ractive and, at the same time, propagate just one update.

Awesome!

**Comment by paulocoghi** [comment]
It was in front of us all the time in `ractive.set( map )` mode.

```javascript
var app = new Ractive({

    data: {
        users: {
            'rich-harris': { name: 'Rich Harris' },
            'evs-chris'  : { name: 'Chris Reeves' }
        }
    }

})

var additional = {}

additional[ 'users.martypdx' ] = { name: 'Marty Nelson' }

additional[ 'users.fskreuz' ] = { name: 'Joseph Descalzota' }

app.set( additional )

// This will output users including 'martypdx' and 'fskreuz'
console.log( app.get( 'users' ) )
```

No cloning and no assigning :)
