### ISSUE TITLE
ractive.toHTML does not output scoping IDs

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2709]
## Description:

`ractive.toHTML` does not output scoping IDs that are applied on the actual DOM. It's not a bug, but an unforseen use case brought by `ractive.toCSS`.

Note that rehydration is not done on the client side. The use case is for rendering server-side. It _might_ work (in theory) if the DOM was rehydrated on the client-side, generating new IDs and reconstructing the CSS without help from a server-side `ractive.toCSS` output.
## Versions affected:

0.8, because `ractive.toCSS` is present since 0.8.
## Platforms affected:

All, but in particular Node.js since you need `ractive.toHTML` and `ractive.toCSS` together to do server-side rendering.
## Reproduction:

Expected `ractive.toHTML` output:

``` html
<div data-ractive-css="{d2f165eb-8661-7420-7af8-fc8fb14ee44c}">
    <div class="component-with-css">Hello World!</div>
    <h4>actual HTML</h4> <textarea class="actual-html"></textarea>
    <h4>toHTML</h4> <textarea class="component-html"></textarea>
    <h4>toCSS</h4> <textarea class="component-css"></textarea>
</div>
```

Actual `ractive.toHTML` output (note missing `data-ractive-css` on enclosing `<div>`):

``` html
<div>
    <div class="component-with-css">Hello World!</div>
    <h4>actual HTML</h4> <textarea class="actual-html"></textarea>
    <h4>toHTML</h4> <textarea class="component-html"></textarea>
    <h4>toCSS</h4> <textarea class="component-css"></textarea>
</div>
```

Relevant `ractive.toCSS` output.

``` css
/* Ractive.js component styles */
/* {d2f165eb-8661-7420-7af8-fc8fb14ee44c} */

.component-with-css[data-ractive-css~="{d2f165eb-8661-7420-7af8-fc8fb14ee44c}"],
[data-ractive-css~="{d2f165eb-8661-7420-7af8-fc8fb14ee44c}"] .component-with-css {
    color: red;
}
```
## Code:

https://jsfiddle.net/7pm3vy5s/3/

``` js
const ComponentWithCSS = Ractive.extend({
  template: `
    <div>
      <div class="component-with-css">
        Hello World!
      </div>
      <h4>actual HTML</h4>
      <textarea class="actual-html"></textarea>
      <h4>toHTML</h4>
      <textarea class="component-html"></textarea>
      <h4>toCSS</h4>
      <textarea class="component-css"></textarea>
    </div>
  `,
  css: `
    .component-with-css{
        color: red;
    }
  `,
  onrender(){
    this.find('.actual-html').value = document.body.innerHTML;
    this.find('.component-html').value = this.toHTML();
    this.find('.component-css').value = this.toCSS();
  }
});

new ComponentWithCSS({ el: 'body' });
```
## Potential problems:
- Scoping IDs are randomly generated internally. Additional logic needed on rehydration to detect the presence of server-generated scoping IDs.

**Comment by evs-chris** [comment]
Thinking about the rehydration issue in terms of progressive enhancement, a component will be the same no matter what it is named, and it would certainly help to be able to have a reproducible id to identify the same component no matter where or when it was loaded. Perhaps we should allow components to have an `id` specified that is used in place of the randomly generated id when present?

Then during `toHTML`, if there was a provided id, include the attribute, but if it was randomly generated, it probably won't do much good when the next (foreign) load will get a new id. So only components with css and a provided id would add the attribute to their top-level elements. Unless I've misunderstood the process, which is a definite possibility :smile:.

**Comment by fskreuz** [comment]
Haven't thought about the progressive enhancement side that much yet. But for a pure server-side rendering perspective, the HTML needs to be ID'ed to match up with the ID'ed CSS. 😄

The IDs are generated per component definition, not per instance. Assuming Ractive can figure out which component definition to use for a certain chunk of DOM as part of progressive enhancement, wondering if it can also use an ID when present in or generate one client-side if none was provided.

Totally new to this isomorphic JS thing 😁

**Comment by evs-chris** [comment]
As it turns out, `Ractive.extend({ cssId: 'my-component' })` lets you set the css id used by the component.
