### ISSUE TITLE
Support, version lifecycles, and the road ahead

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#2713]
With the >1 year that elapsed while 0.8 was cooking fresh in my memory, I've been thinking about how to handle new releases and maintenance on old releases.

@Rich-Harris has granted me the power to publish to npm, and since we're recommending unpkg as a target for linking, I can cut releases relatively easily. I didn't even completely break anything when I cut 0.8.1. I'm going to try push out patch-level releases as often as necessary, and at least every 6 weeks if there are commits made. I still need to get publish access for some of the supporting tools, like rcu, so that I can keep them compatible as major versions are published.

Quick aside: I consider `0.8.0` to be a major version, where `0.8.1` would be a patch or minor version - either way with non-(intentionally :smile:)-breaking changes. I know pre-1.0 releases are pretty much the wild west of semver.

For major releases leading up to 1.0, I have a list of things I'd like to get done for about 3 more milestones moving forward. Of course, anyone else is welcome to add to that list. Most of my list for 0.9 is pretty much all already in PR form. The last big thing I want to try to tackle, assuming someone else doesn't get to it first, is a revamp of the transition handling using keyframes where available and straight functions everywhere else - probably for around 0.11. Since there are a few pretty big things on some of the majors, I'd like to introduce them as experimental in one major and then stabilize them in the following major. Once 0.9 is out, I'm going to try to focus on docs a little more. I'm hoping to merge the tutorial site and the docs site into one thing where the docs start out with a light intro tutorial and ease into the docs. The docs should have ample examples that can pop over into the tutorial editor with click so that they can be played with. I'd also really like to get shareable urls that include the code a la http://buble.surge.sh, so that reproducing issues is even easier. Once all of the list items are checked off and stabilized, I'd like to cut 1.0.

That brings me around to support. 0.7 and 0.8 were vastly different, so it was virtually impossible to maintain 0.7 in a sane manner with the manpower available. I don't think we'll have any more major overhauls like that for the foreseeable future, but just in case, I'd like to propose a 2 version maintenance plan where when a major release is cut, it is moved to its own branch where any bug fixes and minor updates are applied to it and released from there. The last two major versions would then get fixes whenever possible, so 0.8 would be actively maintained until 0.10 lands. That will also hopefully make deprecation cycles less painful for people with larger projects.

Does all of that sound reasonable?

**Comment by evs-chris** [comment]
Also, I opened this issue now because I'd like to move 0.8 into a branch. Then edge/dev can move to 0.9, and I can start merging stuff before it gets painfully conflicted :smile:.

I also think I can get travis set up to publish all of the successful main builds to npm as tagged alpha-style releases, but it will take a bit of fiddling, especially to figure out how to handle the major branches. The http://cdn.ractivejs.org site doesn't have https support, and maintaining that is a bigger headache than anyone can take on right now. 0.8 will probably be the last version on the cdn.

**Comment by fskreuz** [comment]
Sounds good to me.

I've been (directionlessly) playing with the docs lately and actually having Ractive render it (hence the recent activity in docs as well as the CSS and node questions). It's a good opportunity to test out SSR and progressive enhancement there. Wondering if there's some to do list somewhere for the docs, aside from the issue tracker. I'm probably the one with the least exposure to the code, but I can write docs. 😄

**Comment by mefjuu** [comment]
@evs-chris It's great to hear that project isn't dead and there is (I mean you?) a developer who maintain it actively. In a few last months I was considering switching to Vue or even React because of long time since Ractive v.0.7.3 was released, as well as after @Rich-Harris disappearance.

BTW. Ractive has still the easiest templates/API, but what differs it from e.g. mentioned libraries is relatively small (or silent?) community. Thus an availability of reusable components/other extensions is not too high...
As far as I remember @Rich-Harris started a discussion about some official plugin repository some time ago.

**Comment by fskreuz** [comment]
@mefjuu Here it is. https://github.com/ractivejs/ractive/issues/2271 although I'm torn between being for it and being against it. There is also [a plugin repo](https://github.com/ractivejs/ractive-plugins), but not sure how far behind it is compared to its repo counterparts.

And the community is small and/or silent. I see new faces every now and then asking questions and filing issues that don't appear beginner-y. 😄

**Comment by evs-chris** [comment]
I think Vue has some pretty good things going for it. They have really nice docs, but I'm hoping to one-up them with our docs redo :smile:. I also _really_ don't like the `v-if`, `v-for`, `v-bind`, etc. We _do_ need to put some ui components together in a central repo. There are a fair number of third party components out there, but discoverability is an issue.

**Comment by evs-chris** [comment]
I made the executive decision to go ahead and move 0.8 maintenance into the new `0.8` branch. `dev` is now `0.9.0`. The changelog has been updated, and I've pushed out 0.9.0-build-1 (tagged as `next`) for experimentation. Some of the features are flagged as experimental, as outlined above, so, please, feedback welcome!

I'm working on docs, but if you have any questions about new features before I get them ready, feel free to ask here or in the feature PR.

https://unpkg.com/ractive@next
https://unpkg.com/ractive@0.9.0-build-1

**Comment by JonDum** [comment]
@evs-chris Speaking of doc, I don't see much activity over on the docs repo. Is a redesign happening? Where?

Is there some way I can help? I'm actually more of a designer than programmer and if it gets Ractive more attention, it's definitely in my best interest to commit time to giving Ractive's public front a face lift.

**Comment by JosipHaboic** [comment]
Please do docs if possible with https://readthedocs.org so i can download nice PDF :)

**Comment by paulocoghi** [comment]
@evs-chris @JonDum I am also interested in help with the site.

Are you interested in translation to a multi-language site? I can help with design and translations of all content (site, docs, learn, etc)

**Comment by MartinKolarik** [comment]
@paulocoghi I think we should focus on creating great docs in one language first, before translating to other languages.

Help with design/coding/writing documentation/examples would be definitely welcome. We should probably discuss this in more detail since @evs-chris is suggesting some major changes.

**Comment by paulocoghi** [comment]
> Help with design/coding/writing documentation/examples would be definitely welcome.

I'm in, specially with design.

**Comment by fskreuz** [comment]
> There are a fair number of third party components out there, but discoverability is an issue.

@evs-chris Just did an npm and bower search for "ractive" and a bunch of them came up. 

---

Was doing research on mono repos. The idea of a single point of build and publish is great. Still not sure how to handle development workflow, publishing, how it affects direct npm dependency references to a git repo (which I happen to use in certain cases), contribution etc. etc. 

Also experimenting with Ractive server-side rendering and progressive enhancement to generate the docs. Didn't get that far, but it's a great way to try out features on our own resources.

My 2c.

**Comment by evs-chris** [comment]
> Is a redesign happening? Where?

Yep... on my machine :grinning:. I'm still working on getting the skeleton in place. I'm not far along enough to be sure that everything will pan out. I'm using some features in 0.9, which is why I wanted to go ahead and move 0.8 to maintenance. Once I get to a workable spot, I'll put up a repo.

It's also not just a site redesign. The actual docs are a big part of it. Ractive has changed enough in the last two years that the docs are mangled into something barely readable in places (mostly my fault - I'm a lousy writer). The current docs feel like they're half technical spec and half narrative, which makes for poor reading for learning purposes.

My plan is to use a js router and a static page generator that creates suitable pages to use `enhance`. Once loaded, all of the docs, which will also be pre-assembled from a tree of human read/writable files into a JSON blob, will be loaded into the app. In the doc blob will be the tutorial with executable examples covering all of the major features with start/end version tags so you can pick a version and only see relevant info. The usual API docs will be there too for quick reference. Everything should be easily searchable.

> so i can download nice PDF

I don't think we can use that particular site, but there's probably no reason we couldn't stick the non-interactive parts of the docs into a pdf.

> Are you interested in a multi-language site?

Sure! But I'm afraid I'm absolutely no help there. I can barely write in my native 'Murican.

> It's more of a maintenance problem

It is. I suppose that's a problem with about 80% of npm too :smile:. I think getting an official component repo with an easy way to get community contributions would help. Getting a good stable API would also help, and I think we're getting a lot closer.

**Comment by paulocoghi** [comment]
> My plan is to use a js router

From my experience, [visionmedia/page.js](https://github.com/visionmedia/page.js) is very solid and **human** _(although slightly abandoned)_.

I have also improved it to properly [handle SVG links](https://github.com/visionmedia/page.js/pull/394).

While they don't merge, the temporary fork SVG-ready [is here](https://github.com/Altiva/page.js).

**Comment by matthew-dean** [comment]
I think it's been said here, but I would have expected 0.8.0 to at least be 1.0 (major version change) because of "Templates parsed with previous versions of Ractive are no longer compatible."

**Comment by dagnelies** [comment]
Like usual, I'd put my grain of salt. :wink: 

I like it like it is now. The latest release maintained, and the "edge" build preparing the next version. It's a fair system.

While the development of the next release is going on, I'd appreciate:
1. that existing bugs in the latest release are fixed
2. that the upcoming version is compatible with the current one, but with "deprecation warnings" where appropriate
3. when you make a breaking change, write it somewhere where you can't miss it! Even in the script itself. If in debug mode (by default), a console log entry like: `For a list of breaking changes, see http://...` 

The problem is that these points are only modestly pulled through. I'm always afraid of making an update because, I'm pretty sure that:
- my templates will break
- I'll be hunting strange bugs/behaviors/incompatibility 
- things might break at unexpected places that I won't notice
- the plugin dependencies I use will likely be broken too

As I moved from "0.7 latest" to "0.8 edge" because there were bugs in 0.7. I exchanged the couple of ractive bugs for a whole new batch of these. During more than a month, I submitted a few bugs per week! And some, I could still not isolate, but had to work around. I'm now "afraid" of updates.

That's why it is also difficult to make an ecosystem around it, because the flux of change is pretty high. You can be pretty darn sure that most plugins made for 0.7 won't work properly for 0.8 and vice-versa. Even Ractive's own plugins are mostly outdated. They could need some love. Take a look, each one has several PRs.

---

I'm also pretty sure that the "components" part could boost the ecosystem mostly. But here also I'd make it differently. Mainly that components are based on a single HTML element that can inherit attributes provided to the component. But that's a whole other topic. Perhaps making the plugins page a bit more visible would already help.

**Comment by mefjuu** [comment]
BTW @evs-chris. every day I see another issues being closed. Keep up the good work! A reduction from ~160 to 120 is a great result :)

**Comment by evs-chris** [comment]
So, variously:
1. Travis is now handily publishing builds any time a supported branch (0.8 and dev for now) gets new commits. This theoretically includes stables releases as well, so when 0.8.5 is pushed to the 0.8 branch, travis should handle publishing it. Any commits with a package version of `X.Y.Z-edge` will also have `vX.Y-dev` tagged, so you can track unreleased 0.8 updates by using `v0.8-dev`.
2. I would very much like for a 1.0.0 to land, but per semver, 0.x releases are a a free-for-all as far as stability is concerned, and I don't think the API is stable enough to leave that territory yet. Call it my internal compromise between semver and sentimental versioning. 0.9 is also killing off the backlogged deprecations, which I definitely want to happen before 1.0. FWIW, 0.10 may be 1.0, but that's not just up to me. That's also about the time I anticipate being to a usable point with my docs do-over project.
3. I don't foresee and major _architectural_ changes coming down the pipe. The major updates we have left are dealing with stuff mostly already in 0.9, an adaptor redesign, and a transitions redesign. Since none of those _directly_ affect core functionality, it shouldn't be too much trouble to keep bugs squashed across two stable versions and a development branch.
4. As a side-effect of that last point, there should be no major new bugginess introduced moving forward. 0.7 -> 0.8 was a major set of changes that has (and continues to) exposed a bunch of corner cases that the test suite didn't have covered. Bugs should mostly be limited to new features (though hopefully there will be none there either).
5. Dealing with deprecations is also one of the reasons I want to keep two stable versions maintained at once. Quite a few things were deprecated in 0.8, and everything deprecated has been removed in 0.9. Keeping 0.8 actively maintained means that there should be no immediate pressure to jump to 0.9 when it comes out and have to rewrite large chunks of template.

**Comment by paulocoghi** [comment]
@evs-chris Congratulations again and again!

Just a novice (and maybe obvious) question: the bugfixes done in 0.8.x are also ported to 0.9.x?

**Comment by evs-chris** [comment]
> the bugfixes done in 0.8.x are also ported to 0.9.x?

That's correct. Thus far that has just been a `git cherry-pick $revno`, from one branch or the other, followed by a quick test run and push.
