### ISSUE TITLE
Can we remove component.json?

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/ractive#2718]
## Description:
Doing a cleanup run when I noticed `component.json` whose version is stuck at `0.7.1`. It's either the file needs updating, or removal if we don't use this `component.json` anymore.

I'm not very familiar what this file is for (I'm probably not old enough to know :P ), so your opinion matters. :)

**Comment by evs-chris** [comment]
...yeah, it looks like that one died out: https://github.com/componentjs/component

It probably didn't help that TJ bailed on node shortly after that started picking up. Oddly enough, my first contribution to Ractive was to fix the component manifest :smile:

It was a neat project back in the wild west days of everyone making their own whacky frontend build tool/repo/packager/toaster and npm would go offline for hours at a time. Ah, nostalgia.
