### ISSUE TITLE
toHTML does not render class-* and style-*

### ISSUE THREAD

**Issue by shirotech** [ractivejs/ractive#2727]
## Description:

When rendering on server-side .toHtml does not compute the class-\* or style-\* attributes and leave them in their raw state. Client-side rendering is fine though.
## Versions affected:

0.8.2
## Platforms affected:

Maybe all
## Reproduction:

https://plnkr.co/edit/2wU2B1A98W6S6panm6iX?p=preview
## **Code:**

Expected

``` html
<div class="test" style="font-weight: bold;">Test</div>
```

Actual

``` html
<div class-test="true" style-font-weight="bold">Test</div>
```

Have to use {{#if}} and {{#unless}} wrapper as workaround for now.. not ideal as they are messy and inconvenient to use.

Hope this can be resolved in next release, thanks! :)

Edit: I tried with defining a valid "el", seems to work but what can "el" be from server as there is no document?

**Comment by van-nguyen** [comment]
Have to use {{#if}} and {{#unless}} wrapper as workaround for now.. not ideal as they are messy and inconvenient to use.
