### ISSUE TITLE
Event names no longer support dashes

### ISSUE THREAD

**Issue by WaltzingPenguin** [ractivejs/ractive#2730]
## Description:
Inside templates, events handlers that are bound to an event name with dashes no longer trigger.

## Versions affected:
0.8.x

## Reproduction:

I expect to see both "COMPONENT" and "VIEW" logged to console.  This only happens for 0.7.3.  For 0.8.2, it only logs "COMPONENT".

0.7.3: https://jsfiddle.net/6zx12ufu/
0.8.2: https://jsfiddle.net/Le3fhgo8/1/

### HTML

    <script id="component" type="ractive/template">
      <button on-click="event-with-dash">Click Me!</button>
    </script>

    <script id="template" type="ractive/template">
      <p>
        <Component on-event-with-dash="event-with-dash" />
      </p>
    </script>

    <main></main>

### JS

    var Component = Ractive.extend({
      oninit: function() {
        this.on("event-with-dash", function() {
          console.log("COMPONENT");
        })
      },
      template: "#component"
    });

    new Ractive({
      components: {
        Component: Component
      },
      el: "main",
      oninit: function() {
        this.on("event-with-dash", function() {
          console.log("VIEW");
        });
      },
      template: "#template"
    });

**Comment by evs-chris** [comment]
This is odd. According to the docs, `on-event-with-dash` should subscribe to three events: `event`, `with`, and `dash` - see http://docs.ractivejs.org/0.6/event-directives. I went back to the 0.6 docs just to make sure it wasn't a documentation screw up.

Is the issue that only _DOM_ events should allow `-` separators for multiple events? So component events should _not_ split on `-` when listening to events? If that's the case, it's an easy fix.

**Comment by WaltzingPenguin** [comment]
Having different rules for DOM events and component events would be confusing.  This does look like it goes in the category of "things that worked but really shouldn't have".

Can we have better error messaging around this?  If event names shouldn't contain dashes, it would be nice to get an error when attempting to bind to an event like that.

**Comment by evs-chris** [comment]
I agree that having different meanings in different contexts that look the same is not a good idea. That's probably why I assumed that component events should behave like DOM events and accidentally introduced the breakage in the first place :disappointed:

I'm not sure that there's a good way to warn in this particular scenario, unless we warn when you `ractive.fire('some-dashy-event')`. That seems like a legitimate use of the API, though.

**Comment by ghost** [comment]
Multiple events with a dash looks strange. I still prefer regular HTML style events, one each even when pointing to the same handler. Less magic to think about. Break for 0.9?

However... [DOM event names](https://developer.mozilla.org/en-US/docs/Web/Events) are usually alphabetic, single-word, lower-case or title-case. It's probably what this feature is depending on. But I haven't read the HTML spec, I may be wrong.

**Comment by evs-chris** [comment]
I have no particularly strong feelings one way or the other, but I will say that `<div on-mouseenter-mouseover-touchstart="@this.doSomeFunkyThing(that, 'has', [args])">` is quite a bit more convenient than the long form. I have used that a time or two.

**Comment by WaltzingPenguin** [comment]
> I'm not sure that there's a good way to warn in this particular scenario, unless we warn when you `ractive.fire('some-dashy-event')`.

Yes, I think the framework should.  If this won't work:

```
<button on-some-dashy-event="@this.doThings()">Click</button>
```

then it would be helpful if `this.on("some-dashy-event", this.doThings)` and `this.trigger("some-dashy-event")` also did not work.  That enforces the same naming conventions for all events, regardless of individual usage.
