### ISSUE TITLE
"Cannot read property 'original' of undefined" in EventDirective.prototype.fire

### ISSUE THREAD

**Issue by aphitiel** [ractivejs/ractive#2731]
## Description:
There's a component with a button which, when clicked, does some stuff in the component-context, then notifies the parent using ractve.fire.

If the handler in parent returns false and the compont does not pass the event-object in ```ractive.fire```, the error ```Uncaught TypeError: Cannot read property 'original' of undefined``` is thrown in EventDirective.prototype.fire.

Not sure if this is a bug or a nicer error message should be implemented. Anyway this is not urgent for me, since there's an obvious workaround.

## Reproduction:
https://jsfiddle.net/dpqexp4b/ - please compare CrashyComponent with GoodComponent

PS: I can't thank you enough for the latest releases and plans for the future. So I wont;) \o/

**Comment by evs-chris** [comment]
Thanks for the report! The fix will go out with 0.8.4.
