### ISSUE TITLE
Decorator teardown function not called in certain circumstances

### ISSUE THREAD

**Issue by trvrm** [ractivejs/ractive#2735]
## Description:

If I use a decorator within a `div` AND within a `with` section, the `teardown()` function never gets called.

## Versions affected:
Ractive 0.8.3
## Platforms affected:
Chrome

## Reproduction:

I've created the smallest possible reproduction I can at

http://codepen.io/trvrm/pen/pyOeyR?editors=1010

## **Code:**

```html

{{#with 1 as v}}
  <span as-decorator id="span1" >Span 1</span>  
{{/with}}
<div> 
  {{#with 1 as v}}
    <span as-decorator id="span2" >Span 2</span>  
    <!-- THIS decorator doesn't get teardown() -->
  {{/with}}
  <span as-decorator id="span3" >Span 3</span>  
</div>
```

**Comment by evs-chris** [comment]
The fix for this will go out with 0.8.4 when it's ready. Thanks for the report!
