### ISSUE TITLE
`yield` evaluates after `onrender`

### ISSUE THREAD

**Issue by WaltzingPenguin** [ractivejs/ractive#2743]
## Description:
In 0.7.3, HTML provided by yields are present when `onrender` triggers.  As of 0.8.0, the yield HTML is inserted after `onrender` and doesn't seem to have any matching lifecycle event.

## Versions affected:
0.8.2

## Reproduction:

0.7.3: https://jsfiddle.net/67qczjh3/
0.8.2: https://jsfiddle.net/9s2mjc12/3/

### JS

    var Component = Ractive.extend({
      onrender: function() {
        console.assert(this.findAll("option").length === 2);
      },
      template: "#component"
    });

    new Ractive({
      components: {
        Component: Component
      },
      el: "main",
      template: "#template"
    });

### HTML

    <script id="component" type="ractive/template">
      <select>
        {{yield}}
      </select>
    </script>

    <script id="template" type="ractive/template">
      <Component>
        <option>A</option>
        <option>B</option>
      </Component>
    </script>

    <main></main>

**Comment by evs-chris** [comment]
Turns out yielder's findAll was only calling find. The fix will go out in 0.8.4 soon. Thanks for the report!
