### ISSUE TITLE
Could the Computed Properties Compact Syntax be improved?

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2748]
## Description:
The syntax of Ractive is getting very clean and regular.  The Compact Syntax for Computeds looks increasingly lonely as something irregular to learn. 

As an enhancement idea, could the Compact Syntax for computeds be upgraded to support an "expression", more like how Event Methods are now event expressions?

As an example, could 
```
  computed: {
    area: '${width} * ${height}'
  }
```

be changed to

```
  computed: {
    area: 'width * height'
  }
```

I know that this analogy isn't 100%, but, in spirit, a template can do this (from [doc](http://docs.ractivejs.org/edge/method-calls)):

```
{{#each items :i}}
  <button on-click='@this.select(this,i)'>select this item</button>
{{/each}}
```

I'm thinking that if Ractive can "know" that `i` is part of the evaluation context, so too it could know in the case of a Computed that `width` and `height` are part of the data context, without recourse to the special `${...}` markers.

## Versions affected:
edge

## Platforms affected:
all

## Reproduction:
N/A

## **Code:**
N/A

**Comment by evs-chris** [comment]
That's probably a reasonable thing to do, especially if it saves space on some special-cased parsing. It would also make template strings tiny bit less confusing when they eventually make it in to the parser :smile:

**Comment by dagnelies** [comment]
+1 from me. The `${...}` always seemed out of place to me.

And as usual, first only a warning ;)

-----

Besides of this, I'd like to point out a design flaw in computed variables: they are "lonely".
Let's say you have a list of boxes: 
```js
data: {
   boxes:[ {width: 1, height: 2}, ...]
}
```
In this case, computed variables become useless.

Extending it to keypaths would be rather nice in the future:
```js
data: {
   boxes:[ {width: 1, height: 2}, ...]
},
computed: {
  'boxes.*.area': 'width * height * @index' // (scope would be 'boxes.*')
}
```
...but that would be a whole other topic, where care should be taken that it does not clash with observers and components. IMHO this would be a very low priority feature though.

**Comment by aharpervc** [comment]
What about mustache (or mustache-lite) syntax, the same way you would in a template?

**Comment by dagnelies** [comment]
@aharpervc  I had this thought too. However, there is subtlety in it:

You should write `{{weight * height}}` to be a valid expression. Because something like `{{weight}} * {{height}}` would result in the *text* `"1 * 2"` instead. ...I think this would confuse a lot people. Think about it. And if you think it should act like the second expression, then you'd handle it differently than inside templates, which is even more confusing.

Therefore, I vote against the mustache syntax here, just its content. If you want to use mustache style stuff, better use a partial directly!

**Comment by evs-chris** [comment]
Yeah, as it stands computation strings are kind of a strange beast. Here's what happens: `${width} * ${height}` has a regex applied to convert the string to `var __ractive = this; return (__ractive.get("width") * __ractive.get("height"))`, and then that string gets stuffed into a new function as the body. You _could_ end up with a very broken computation if you tried to do something like `"the area is ${width * height}"`, which on the surface seems like it would be reasonable. It would definitely make more sense to me to treat the string as if it were already in an interpolator (an expression), so `width * height` would become `var _0 = this.get("width"), _1 = this.get("height"); return (_0 * _1);`.

After a year or two of pondering off and on, I _still_ haven't come up with a consistently good way to have computed properties available at any keypath.

**Comment by evs-chris** [comment]
#3141 is now cherry-picked into edge.
