### ISSUE TITLE
Would you like to join us on JavaScript Jabber?

### ISSUE THREAD

**Issue by coolaj86** [ractivejs/ractive#2749]
How'd you like to join us on JavaScript Jabber?

I'm always interested to hear about tools that are actually written in JavaScript (as opposed to TypeScript, Elm, JSX, blah, blah, boring) and this looks so simple and useful I'd love to have you on the show to talk about it.

I haven't tried it out yet, is it true that it's strict-mode and CSP compliant without a compiler? https://github.com/ractivejs/ractive/pull/2287 That would freaking rock my world! (I was just about to start using vue.js and immediately ran into the CSP and ES5.1 violations... made me so sad)

It's nearly impossible to find secure JavaScript these days that Just Works in the browser without 10 million dependencies and commandline tools.

cc/ @cmaxw

**Comment by evs-chris** [comment]
I know @martypdx and @Rich-Harris have done Ractive talks before.

Unfortunately you can't really do (no-eval) CSP compliant templating without some sort of pre-parsing to function-ify the expressions in the template, unless you build in a JS interpreter, which would probably be its own security issue :smile:. If you stick to straight references, Ractive can be eval-less without pre-parsing, but it's a bit hard to do anything meaningful with just references. The parser that converts templates with expressions is built in though, so it's just a `Ractive.parse(...)` away.

I'm not entirely sure about the strict violations. The Ractive source is ES6, which is strict by default, but I don't know if the transpiler either validates that or does any transformation that would have violations.

Ractive tries to be batteries-included, so there are no deps currently, even for polyfills. We're seriously considering dropping the polyfills, as they tend to introduce their own issues, but as long as you're on a modern-ish browser, there won't be any deps.

**Comment by cmaxw** [comment]
Gonna chime in here. You can email me (chuck@devchat.tv) if you'd like to come on the show.

**Comment by evs-chris** [comment]
You may want to ping [@Rich_Harris](https://twitter.com/Rich_Harris) on twitter, as I think he may have some very interesting developments to talk about, though not necessarily about Ractive, in the next week or two.
