### ISSUE TITLE
Update docs: Writing decorator plugins

### ISSUE THREAD

**Issue by andreujuanc** [ractivejs/ractive#2750]
This page explain decorators using edge new naming convention: 
http://docs.ractivejs.org/latest/decorators but this one is not: http://docs.ractivejs.org/latest/writing-decorator-plugins

**Comment by ghost** [comment]
Thank you for the report. Currently overhauling the docs at https://github.com/ractivejs/ractive/pull/2747. 👍

**Comment by andreujuanc** [comment]
@fskreuz no prob, ill open a second issue, since I went to the docs because of a little thing I'm trying to do, and maybe found some weird behaviour on ExpressionParser.
