### ISSUE TITLE
ExpressionParser and directives

### ISSUE THREAD

**Issue by andreujuanc** [ractivejs/ractive#2751]
Writing a small directive, I came across something that I don't know if can be simplify, this is my scenario:

Implemented like: `as-test="{something:1}"`. Works fine, but i found that this directive was going to be very simple most of the time. 

When I tried `as-test="1"` I coudn't get the parameter data. More or less the way it was done before edge.

So, basically two things:

1. Is this incorrect?  `as-test="1"`
2. When checking some other simple parameter values i found that if I pass  as-test="#"` I get: 

> Cannot read property 't' of undefined.

Reproduced like this:  flattenExpression(  new ExpressionParser( ("[#]") ).result[0] )
This one on the other side works fine: `flattenExpression(  new ExpressionParser( ("[1]") ).result[0] )`

Version 0.8.1
Method: processDirective
Line: 63357 and 63358. 
Extra data: right after "TODO clean this up, it's shocking" xD

Cheers

**Comment by evs-chris** [comment]
1. Yep that's correct. The second arg to the decorator function will be `1`: https://jsfiddle.net/kq6xyct1/
2. This is improved in the upcoming 0.9 release that's currently in alpha. Basically, in 0.8 the whole attribute is read, wrapped in `[ ]`s, and fed to an expression parser manually. With 0.9, the main parser knows that `as-test` is a directive and starts parsing an expression directly, so you get a better error message: https://jsfiddle.net/ge01xktg/1/

> Extra data: right after "TODO clean this up, it's shocking" xD

...yeah. :laughing:

**Comment by andreujuanc** [comment]
Sorry, I should have closed this!
