### ISSUE TITLE
ractive cdn down

### ISSUE THREAD

**Issue by jhanifen** [ractivejs/ractive#2752]
Looks like ractive http://cdn.ractivejs.org/ domain was not renewed

**Comment by Jeff17Robbins** [comment]
Also, the main site http://www.ractivejs.org/ returns `404`.

**Comment by sarendipitee** [comment]
Yeeeeep expires today: 
`Registry Expiry Date: 2016-11-07T08:40:16Z`

Kinda bullshit that Google's nameservers kills it completely the second it expires.

@Rich-Harris I'm assuming you own the `ractivejs.org` domain? 

I wouldn't mind pitching in to keep the domain up. Or maybe we should take this opportunity to switch to something "cooler" like `http://ractivejs.rocks/` lol

**Comment by paulocoghi** [comment]
An opportunity to use [js.org](url) free domain name service for opensource JS projects and get: `ractive.js.org`
- it's **just a dot of difference** from the current domain
- 100% free
- official / well received by the community
- and will never expire.

## 

@jhanifen : it's interesting to change the title to something like "ractivejs.org domain expired".

**Comment by sarendipitee** [comment]
I really like the js.org idea. It mimics our current domain and is really just a mirror to github's gh-pages so we still have full control over the site and docs.

Setup appears to be very simple too. We add a file `CNAME` in the root of `gh-pages`, then submit a PR adding our domain to [here](https://github.com/js-org/dns.js.org/blob/master/cnames_active.js).

**Comment by ghost** [comment]
Except we need to adjust how everything is built. Most of Ractive's pages (home page, docs, learn, etc.) are built on Travis and pushed to Surge. And they all live in separate repos. 😱

**Comment by Rich-Harris** [comment]
<img width="433" alt="screen shot 2016-11-07 at 5 48 28 pm" src="https://cloud.githubusercontent.com/assets/1162160/20079395/76a0f3be-a512-11e6-8d2b-49b9838f07b8.png">

> This domain is being restored

...I guess that means it'll fix itself? 😬 

Sorry about dropping the ball here – I've been 100% tied up with 9-5 work (or 8-11 work, to give it its proper title...) leading into the US election (our results app will be putting Ractive 0.8.4 through its paces!) and completely missed the email telling me it was up for renewal.

If it doesn't restore by itself, I'll be able to take a look later in the week

**Comment by sarendipitee** [comment]
@Rich-Harris Thanks Rich, we all understand. 

It's back up now.

That takes the pressure off us to come up with an alternative solution asap now 👍 

(and fixes everyone's websites that uses the cdn url :O)

**Comment by evs-chris** [comment]
FWIW, with https becoming basically required, we recommend using jsdelivr, the cloudflare js cdn, or unpkg for all your linking needs. :smile:
