### ISSUE TITLE
How to use layouts in Ractive or convert them to partials?

### ISSUE THREAD

**Issue by interphx** [ractivejs/ractive#2753]
I have been using [handlebars-layouts](https://www.npmjs.com/package/handlebars-layouts) in my project and recently decided to migrate it to Ractive to keep server-side and client-side templates in same language.
My templates look roughly like this:

    // base.html
    <!doctype html>
    <html>
        <head>
            <title>{{#block 'title'}}{{/block}}</title>
            ...
        </head>
        <body data-body-attr="{{#block bodyAttrValue}}{{/block}}">
            <div id="panel">
            ...Some common text...
            {{#block 'panel'}}{{/block}}
            </div>
        </body>
    </html>

    // page.html
    {{#extend 'base'}}
        {{#content 'title'}}Some Page{{/content}}
        {{#content 'bodyAttrValue'}}someValue{{/content}}
        {{#content 'panel'}}Panel data{{/content}}
    {{/extend}}

Is there an alternative to layouts for ractive.js? Or what is the right way to convert this kind of templates to partials? Note that this affects only the final rendered template, not logic, so there is probably no need for ractive components.

**Comment by evs-chris** [comment]
If you're using a traditional request-response model for your site, where each major navigation is going to re-render from the base down, I'd recommend against using ractive as the primary parser unless you have good caching or relatively non-demanding traffic. Ractive is probably an order of magnitude slower than something like handlebars or lodash templates.

If you're going SPA-style where you render the initial page and let ractive take over from there in cooperation with a client routing lib, there is a text-only mode for the parser that lets you use it more like a traditional mustache renderer. You could then build your layout using partials to handle the layout. I've used something like this pretty successfully.

``` js
const baseFile, pageFile; // read the files as strings somewhere
const base = Ractive.parse(baseFile, { textOnlyMode: true });
base.partials = Ractive.parse(pageFile, { textOnlyMode: true }).p; // assign the partials from the page to the base file
return new Ractive({ template: base }).toText();
```

``` html
<!-- base -->
<html>
    <head>
        <title>{{>title}}</title>
        ...
    </head>
    <body data-body-attr="{{>bodyAttrValue}}">
        <div id="panel">
        ...Some common text...
        {{>panel}}
        </div>
    </body>
</html>
```

``` html
<!-- page -->
{{#partial title}}Some Page{{/partial}}
{{#partial bodyAttrValue}}someValue{{/partial}}
{{partial panel}}Panel data{{/partial}}
```

`textOnlyMode` skips pretty much everything but sections and interpolators, so you don't have to worry about ractive eating directives on elements, like `value` and `on-click`. I typically set templates that are going to be handled server-side to use `[[ ]]` and `[[[ ]]]` as the mustaches so they stand out a bit more. I almost never use static mustaches in my templates.

**Comment by ghost** [comment]
If you're looking for something _exactly_ like handlebars-layouts, Ractive doesn't do that. Ractive is more of a "top-down" composition-style system where a component defines what it contains, rather than the component define where it's positioned in the parent template.

@evs-chris would this be a good use case for anchors? i.e. page loads, route matches, picks out components to use for page, instantiates the base page with anchors and the child components, sticks child components to base page, dumps data in, `ractive.toHTML()` and you got a page? I'm probably missing some steps, but that's the general idea. 😄

**Comment by evs-chris** [comment]
Layouts are pretty much the main use-case for anchors. They don't support progressive enhancement yet, so that could be a problem. I should probably fix that :smile:
