### ISSUE TITLE
Issue with setting default value for selects when combined with `yield`

### ISSUE THREAD

**Issue by WaltzingPenguin** [ractivejs/ractive#2754]
## Description:
Starting with 0.8.0, selects no longer set their correct default value if all options are supplied via a yield block.

## Reproduction:

0.7.3: https://jsfiddle.net/nuct64hg/
0.8.4: https://jsfiddle.net/g0n714eb/

### JS

    var Component = Ractive.extend({
      template: "#component"
    });

    var view = new Ractive({
      components: {
        Component: Component
      },
      el: "main",
      template: "#template"
    });

    console.assert(view.get("foo") === "A");
    console.assert(view.get("bar") === "One");

### HTML

    <script id="component" type="ractive/template">
      <select value="{{value}}">
        {{yield}}
      </select>
    </script>

    <script id="template" type="ractive/template">
      <Component value="{{foo}}">
        <option>A</option>
        <option>B</option>
      </Component>

      <select value="{{bar}}">
        <option>One</option>
        <option>Two</option>
      </select>
    </script>

    <main></main>

**Comment by evs-chris** [comment]
The fix for this will go out with 0.8.5. Thanks for the report!
