### ISSUE TITLE
Get node from a keypath

### ISSUE THREAD

**Issue by sarendipitee** [ractivejs/ractive#2755]
Say I have a simple recursive partial like this:

```
{{#partial thing}}
  <div class='thing'>
	{{.name}}

	{{# .things}}
		{{> thing}}
	{{/}}
        
  </div>
{{/partial}}

{{# ~/things}}
	{{> thing}}
{{/}}
```

Is there anyway I can get a specific node out of the fragment by giving it a keypath?

For example `this.fragment.items[0].giveNodePlease("1.things.3.things.2")`?

Does that make sense?

**Comment by sarendipitee** [comment]
Without resorting to IDs or something hacky 👍

**Comment by evs-chris** [comment]
> Without resorting to IDs or something hacky 

Nope :laughing: 

> Is there anyway I can get a specific node

``` js
// this is so tightly bound to your template structure that it's cyanotic
this.viewmodel.joinAll(Ractive.splitKeypath('things.1.things.3.things.2')).deps.filter(d => d.fragment).map(d => d.fragment.items[0].node);
// it may blow up terribly depending on your actual template
```

Now, if you don't mind being a bit decorative, in the template on the nodes you're looking for:

``` html
<div as-tracked>...</div>
```

``` js
Ractive.decorators.tracked = function(node) {
  if (!this.nodes) this.nodes = {};
  const ractive = this;
  const path = this.getNodeInfo(node)].resolve();
  this.node[path] = node;
  return {
    teardown() { delete ractive.nodes[path]; }
  };
};
```

With that, `this.nodes['things.1.things.3.things.2']` will give you the `div` that's decorated `as-tracked`.

You could get fancy with that and have different registries by name for each keypath, passing the registry name as an argument. `<div as-tracked="{ name: 'divs' }"><hr as-tracked="{ name: 'lines' }" /></div>`.

**Comment by sarendipitee** [comment]
You sexy beast you. I would not have thought of using a decorator and `getNodeInfo()` to store it in `nodes`. 

Also...

> Now, if you don't mind being a bit _decorative_,

I lol'd.

**Comment by sarendipitee** [comment]
Just in case anyone ever sees this...

Fixed some typos in Chris's code, so copy/paste away.

``` js
    decorators: {
        tracked: function(node) {
            const instance = this;

            if (!instance.nodes)
                instance.nodes = {};

            const path = instance.getNodeInfo(node).resolve();

            instance.nodes[path] = node;

            return {
                teardown() {
                    delete instance.nodes[path];
                }
            };
        }
    },
```
