### ISSUE TITLE
Input attributes order does matter for proper 2-way binding

### ISSUE THREAD

**Issue by mefjuu** [ractivejs/ractive#2756]
## Description: 
2-way binding on radio input groups doesn't work properly when `type="radio"` attribute isn't the first one.

## Versions affected: 
0.7.3

## Reproduction: 
It works: http://jsfiddle.net/dg8Kd/2/ and it doesn't http://jsfiddle.net/dg8Kd/3/

## **Code:** 
`<input type="radio" name="{{.value}}" value="1"/>` works, `<input name="{{.value}}" type="radio" value="1"/>` doesn't

**Comment by MartinKolarik** [comment]
This should be fixed in v0.8 (#1968).

**Comment by fskreuz** [comment]
Both demos appear to be working for me in 0.7.3

- https://jsfiddle.net/dg8Kd/4/
- https://jsfiddle.net/dg8Kd/5/

**Comment by ghost** [comment]
Fixed on the latest release 0.8.4
- https://jsfiddle.net/dg8Kd/6/
- https://jsfiddle.net/dg8Kd/7/

**Comment by evs-chris** [comment]
Since it's fixed in latest and there's a reasonable workaround, I'm going to go ahead and close this.
