### ISSUE TITLE
Experimental resolveInstanceMembers feature doesn't bind instance

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2757]
## Description:
Experimental `resolveInstanceMembers`  feature doesn't bind Ractive instance as context of function.  But the [CHANGELOG.md](https://github.com/ractivejs/ractive/blob/134a166661d7a174d285390a4f845f559287190b/CHANGELOG.md)  says on-click="set('foo', 'bar')" should work.

## Versions affected:
https://unpkg.com/ractive@0.9.0-build-3

## Platforms affected:
Windows 10 Chrome 54.0.2840.71 m

## Reproduction:
https://jsfiddle.net/336v65tr/

## **Code:**

HTML
```
<script src="https://unpkg.com/ractive@0.9.0-build-3"></script>
<div id='host'></div>
```

JavaScript
```
var view = new Ractive({
  el: '#host',
  template: '<button on-click=\'set("foo", "bar")\'>Click me</button>',
});
```

Click the button; crash in the console because the `ractive` argument to `gather(...)` is `undefined`.

**Comment by evs-chris** [comment]
Well, dang. I completely forgot to add tests for that. This is now fixed and published as 0.9.0-build-4. Thanks for the report!

**Comment by Jeff17Robbins** [comment]
There's still a difference between 0.7.3 and 0.9.0-build-4.

Two examples below, same code under 0.7.3 and 0.9.0-build-4 respectively.  Each example has two buttons.  The first button's `on-click` works the same under both versions.  The event handler has the expected `this`.  

But the second button works differently.  Under 0.7.3, the instance method has the Ractive instance as its `this`.  Under 0.9.0-build-4, the instance method has `window` as its `this`.

https://jsfiddle.net/jg51h2L6/    // 0.7.3

https://jsfiddle.net/qfpL88h3/  // 0.9.0-build-4

**Comment by evs-chris** [comment]
Yes, that's just a side effect of the way ractive handles binding of functions. It only binds if there's a `this` reference in the function. If you add a reference to `this` in somewhere in the function body, it behaves as expected: https://jsfiddle.net/qfpL88h3/1/

**Comment by Jeff17Robbins** [comment]
I see.  Still, it is a breaking change from 0.7.3, isn't it?  It should be noted in the changelog.
