### ISSUE TITLE
UI kits alternatives

### ISSUE THREAD

**Issue by andreujuanc** [ractivejs/ractive#2763]
Guys,

I have no idea what to give up first, if ractive (and use other projects just because of lack of UI kits), or give up react, (because it's just a mess, setting up babel, compilers, precompilers, post compilers, compiler's compilers, etc)

So I decided to try to start a project for ractive, based on components. I need great UI design, but dont want to use jquery and really like material design principles.

Couldn't find anything worth it out there, so the idea is to build components based on [Material-UI](http://www.material-ui.com/#/components/app-bar) for React but using RactiveJS.

Before writing this, I even tried to implement react into my new project. But it's so ugly and complicated. I REALLY want to use ractive but I was no able to find any solid UI kit.

Maybe this should have been better posted on stackoverflow, but I think here will find people already using ractive on production and might get something out of this.

**GOAL**: Implement Material-UI components for Ractive without using JQuery (I could have just used materialized and jquery for example)

I chose Material-UI because it's components are really solid, and there is almost anything you would need to build a project.

Things I already tried but failed, or required more work than implementing UI from zero:

- [PhononJS](phonon.quarkdev.com)+Ractive: Works fine, but some components have problems when rendered dynamically
- [Material Design Lite](getmdl.io): Started to look good, but got problems when "upgrading the dom" and they even confirmed that the project was not intended to use in dynamic environments.

It would be amazing if I get some positive feedback and maybe form a small team to do this on any way, since the idea of "forking" material-ui it's just an idea, I'm totally open to new ones.

Thanks, and sorry for long post.

**Comment by ghost** [comment]
Having gone over the components documentation yesterday, I'd say it's entirely possible. The only problem we have when doing these sort of things is the lack of momentum, especially when you have to keep up with the times and have frameworks outpace you every time.

In related news, there have been attempts to integrate Ractive with other UI libraries. The one I remember is @dagnelies 's [Ractive-Bootstrap](https://github.com/dagnelies/ractive-bootstrap/). Maybe you could get in touch with him on this adventure.

For me, this is a 👍 Don't forget to share the site and github repo. @evs-chris or whoever holds the Twitter account could possibly promote it in a snap. 😄

**Comment by mefjuu** [comment]
@andreujuanc Having the same need as you, some weeks ago I investigated "porting" Material Design Lite into Ractive components world.
As for updating DOM, take a look at MDL v2 (`master` branch) - they introduced quite clean way to integrate JS-based MD components with DOM-oriented view libraries. There are examples for some popular libs included - e.g. https://github.com/google/material-design-lite/tree/master/examples/vue/src/v-mdl-drawer.

Unfortunately, version 2 is still in progress and not all MD components are rewritten yet.

**Comment by evs-chris** [comment]
I'm definitely :+1: to an "official" ui library. I think it would help tremendously to have some common components, decorators, events, etc that were available in a conveniently bundle-able way. Most of the components I run across a need for exist in some form in the community (or are super simple to make), but I think a material design collection would be awesome.

**Comment by andreujuanc** [comment]
Thanks for such nice replies.

@fskreuz I totally agree with you, and it was the first problem i thought of. But I have already 2 or 3 weeks searching around for options. I checked almost all "view" js frameworks and their respective UI kits. I literally have more than 100 folders in a folder called TempAndTesting. I think in 3 weeks I could have already something running  by now :(  I checked vue, and their options, and digging around all the Chinese docs I found that there is no solid alternative, but a bunch of small (but good) pieces to build the UI, but that lacks the uniformity that an UI should have.  

I will totally poke him and see if he can at least point the project in the right direction (or maybe get him involved, muahaha).

@mefjuu I also checked v2, but since it's not quite released yet, i dont know if it's a good idea or not, maybe it's the best shot we have, at least the easiest, since it's design for that. But i still havent checked the entire project and it's ambitions and scope.  But yes, it's an option for sure.

@evs-chris exactly! it's not much about the component's behavior, but more about design. And material for me is the way to go for enterprise apps, they just look good enough without being all flashy.

From this convo i see that we have those two options, port Material-UI or wrap around MDLv2.

Now i will do small research, to see how both implementations will look like. Because wrapping can be sometimes "ugly", and who knows how sexy the final code for a React port will be.

What do you think?

Thanks again guys!!!

**Comment by andreujuanc** [comment]
**SMALL UPDATE**: I really liked it, but seems like material-ui for react cant be elegantly ported, since they (i didn't know) hardcode the styles on each component. Which maybe "nice", but make too hard to implement different styles/themes. And also more stuff to port and keep the project up to date.

Last option is to do it via MDLv2. OR of course, read all design guides and do it our way.

MDL V2 Due by May 13, 2021 => https://github.com/google/material-design-lite/milestones

I'm going to build a small code pen with it, and see how it looks.

Thoughts?

**Question:**  Should we keep these stuff in this issue? or you want to move it somewhere else?

**Comment by ghost** [comment]
What I normally do with Ractive components with regards to theming is to not bake in the CSS into the component at all. Although we have the `css` option, but I avoid it due to high specificity (at least a class and a data prop) which makes it tricky to override.

Instead, I use [BEM](https://en.bem.info/methodology/) to give a predictable name to the elements as well as have very low-specificity, easily overridable selectors. I'd have two global stylesheets, one is for a wireframe-y rendering (structure, no colors and specifics) and another for the actual theme, the same way Bootstrap 3 does it. The first CSS file is required, the other can be swapped out depending on the theme.

``` js
const MyMaterialComponent = Ractive.extend({
  template: `
    <div class="my-material-component">
      <div class="my-material-component__something">
        <div class="my-material-component__something-else my-material-component__something-else--modifier">...</div>
      </div>
    </div>
  `
});
```

``` scss
// base.css, all base definitions
.my-material-component{}
.my-material-component__something{}
.my-material-component__something-else{}
.my-material-component__something-else--modifier{}

// theme.css, overrides the above where needed
.my-material-component__something{}
.my-material-component__something-else--modifier{}
```

> Should we keep these stuff in this issue? or you want to move it somewhere else?

If you have a separate repo, sure you can move. Just make sure everyone's informed. 😄

**Comment by andreujuanc** [comment]
True, me too, but now I think we should stick to whatever "base" project's nomenclature they chose.

Otherwise this project would require a complete rewrite, which I would love, but probably we wont have time for.

Right now, I'm evaluating MDL v2,.
I also found this: https://www.muicss.com , looks fine. I will keep you guys posted.

Any ideas are fully accepted (and needed)

Will create repo as soon as decide what project we will base the components from.

**Comment by mefjuu** [comment]
+1 for BEM
+1 for keeping styles externally in *.css file 

MDL v2 has well considered architecture (but looks too overcomplicated somewhere) that allows to easily customize theme, including _dark theme_ (which v1 is lacking of).
I will check MUICSS...

**Comment by andreujuanc** [comment]
**UPDATE**: Google's MDLv2 is going to take too long probably (i accept suggestions on how to implement it), and they don't have any docs (yet) on how to implement everything, and source code lacks any comment whatsoever.  I dont want to go and start guessing or asking around for something they haven't event release, if they ever do. 

Still gonna keep trying on MDL, @mefjuu  if you like MUICSS let me know, maybe try a small component on codepen if you have the time.

**Comment by andreujuanc** [comment]
Jesus, i have this internal fights with myself, about MDL, do it from scratch or try MUICSS xD

EDIT: Almost got codepen demo for Google MDL.  Maybe too much for a simple checkbox, but maybe will be worth it for other components. 

EDIT 2: MDL does not have lots of useful components for now. It looks really promising, but I cant say it's the way to go. Last option is going to be to port [MaterializeCss](http://materializecss.com/getting-started.html) And since i'ts just JQuery, we can just use it and port component by compoinent until get rid of jquery completely.  Opinions?

**Comment by dagnelies** [comment]
A bit off topic, but for simple UI wrappers, I'd be nice to have something like #1535 implemented in the future.

**Comment by andreujuanc** [comment]
@dagnelies nice issue, i will comment there something I was thinking before.

**Comment by paulocoghi** [comment]
+1 for MaterializeCss

**Comment by andreujuanc** [comment]
Everyone is welcome here:
https://github.com/andreujuanc/Ractive-Materialize

@paulocoghi  🎱 

@mefjuu Checked MUICSS?

@fskreuz Gonna stick with materialize for now. Maybe some day if we gonna start our own UI project, we will use BEM for that, for sure.
