### ISSUE TITLE
Link to jsfiddle returns 404 (.github/ISSUE_TEMPLATE.md)

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#2767]
Hi there,
the URL to jsfiddle in `.github/ISSUE_TEMPLATE.md` is currently broken.

https://jsfiddle.net/evschris/exc00vup/ (404)

p.s.
Ractive 0.8.5 is incredibly fast and awesome! Thank you guys 😊
I'm trying to finally complete the porting of the SPA I've been working on, and so far it seems way more stable than any previous release.

**Comment by evs-chris** [comment]
Fixed, thanks!
