### ISSUE TITLE
`noIntro` counterpart for outro transitions (`noOutro` ?)

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#2770]
## Description:
I think it'd make sense to have a `noIntro` counterpart for outro transitions (`noOutro` ?).
I'm running into many situations in which transitions are only important while the component is on-screen.

What do you think?

## Disable transitions from template:
As a side note: is it possible to conditionally disable specific transitions from templates?

On 0.7.x I used to do something like `<div intro="{{shouldTransition ? 'fade' : ''}}">`, but that currently throws a warning on 0.8 (`Missing "" transition plugin`). Any better way to do it?

Not sure if it's even doable in 0.8's `...-in-out` syntax, doesn't seem like it.
ex. `<div fade-in="{{shouldTransition}}">` ?

**Comment by evs-chris** [comment]
For the `noOutro` side, I think having transitions that can be configured _not_ to run if there is already a parent element transitioning is the answer (#2414).

For conditional transitions in 0.8, the recommended way is `<div {{#if shouldTransition}}fade-in{{/if}}>`. You can also use a plain section for slightly more brevity `<div {{#shouldTransition}}fade-in{{/}}>`.

**Comment by giovannipiller** [comment]
> For the noOutro side, I think having transitions that can be configured not to run if there is already a parent element transitioning is the answer

I still think that `noOutro` would cover a different use-case though.

---

### Component1
```
...
{{#unless hide}}
   <div fade-in-out>...something...</div>
{{/unless}}
...
```

### Component2
```
<section>something else</section>
```

### Page 
Data has `activeComponent: 1`.
```
{{#if activeComponent === 1}}
  <Component1/>
{{/if}}

{{#if activeComponent === 2}}
  <Component2/>
{{/if}}
```
---

Executing `Page.set('activeComponent', 2);` will result in both components temporarily being displayed in the page.
This because `<Component1/>`'s internal transitions will have to be completed before its node gets removed.

`noOutro` seems like a logical counterpart to `noIntro`, and would solve these cases where there's no parent transition involved.

**Comment by evs-chris** [comment]
Ah, that makes sense. I've added a `noOutro` flag to #2773, which disables outros for a component that is unrendering. The inheritance mirrors that of `noIntro` in that if there's an unrendering parent that has `noOutro` explicitly set, components belonging to it that are unrendering and have no explicit setting will use that of the parent.

**Comment by giovannipiller** [comment]
Is this planned for 0.9, or there's a chance for it to land in a 0.8.x?

Just asking because I'm trying to remove all the deprecated bits from my code, and this is one of the few remaining (`<div intro="{{shouldTransition ? 'fade' : ''}}">`).

**Comment by evs-chris** [comment]
It's planned for 0.9, which has almost all of its bits in place to start a release cycle (alpha). There are still one or two pending PRs and a few issues that need to be resolved.
