### ISSUE TITLE
Compound keypath not working with sort function

### ISSUE THREAD

**Issue by speasley** [ractivejs/ractive#2771]
## Description: Sorting with a simple keypath (eg. 'name') works as expected; however, when trying to sort with a compound keypath (eg. 'name.first') sorting does not occur and no errors are thrown.

I've tried using name['first'], ractive.get('name.first') and ractive.get('name["first"]') but they (silently) kill the sort feature.

## Versions affected:
0.8.1

## Platforms affected:
macOS 10.12.1
• Chrome 54.0.2840.71 (64-bit)
• Firefox 32.0
• Safari 10.0.1

## **Code:**
HTML:
<script src="//unpkg.com/ractive"></script>

<script type="text/html" id="template">
	<table class='superheroes'>
  <tr>
    <th>#</th>
    <th>Superhero name</th>

    <th>Real name</th>

    <th>Superpower</th>
  </tr>

  {{#each sort( superheroes, sortColumn ) :num}}
    <tr>
      <td>{{ num + 1 }}</td>
      <td><a href='{{info}}'>{{name}}</a></td>
      <td>{{realname.first}} {{realname.last}}</td>
      <td>{{power}}</td>
    </tr>
  {{/each}}
</table>
</script>
<div id="main"></div>

JS:
var xmen = [
  { name: 'Nightcrawler', realname: {last:'Wagner',first:'Kurt'},     power: 'Teleportation',    info: 'http://www.superherodb.com/Nightcrawler/10-107/' },
  { name: 'Cyclops',      realname: {last:'Summers',first:'Scott'},   power: 'Optic blast',      info: 'http://www.superherodb.com/Cyclops/10-50/' },
  { name: 'Rogue',        realname: {last:'Marie',first:'Anna'},      power: 'Absorbing powers', info: 'http://www.superherodb.com/Rogue/10-831/' },
  { name: 'Wolverine',    realname: {last:'Howlett',first:'James'},   power: 'Regeneration',     info: 'http://www.superherodb.com/Wolverine/10-161/' }
];
const r = window.r = new Ractive({
	el: '#main',
  template: '#template',
  data: {
    superheroes: xmen,
    sort: function ( array, column ) {
      array = array.slice(); // clone, so we don't modify the underlying data

      return array.sort( function ( a, b ) {
        return a[ column ] < b[ column ] ? -1 : 1;
      });
    },
    sortColumn: 'realname.first'
  }
});

**Comment by speasley** [comment]
I have some deprecations to catch up on before this is looked at. I apologize for opening it prematurely.

**Comment by speasley** [comment]
Deprecations addressed. Issue ready for review. Thanks.

**Comment by evs-chris** [comment]
I think you may be getting lodash in your vanilla JS :smile:. JS property access doesn't deal with dotted keypaths, so if you switch to a function that returns the sort value, it works as expected: https://jsfiddle.net/kmf7f9L5/4/

**Comment by speasley** [comment]
Ahh, thank you.

Would the same logic not apply for setting the sort value dynamically? This fails, where column equals 'realname.first':

`r.set('sortColumn', function(i) {
  return i.column;
});`

**Comment by evs-chris** [comment]
That has the same problem as the original - JS doesn't handle `.` in properties, so `foo['bar.baz'] gets the`bar.baz`property on`foo`rather than the`baz`property on the`bar`property of`foo`. Ractive does have a helper that makes this slightly easier than having to handle corner cases on splitting up keypaths yourself:`Ractive.splitKeypath('some.dotted.path')`which`=== ['some','dotted','path']`. From there you can use array reduce to read each successive property starting from the root value with`pathArray.reduce( (a,c) => a && a[c], startPoint)`. Here's an updated fiddle that does just that: https://jsfiddle.net/kmf7f9L5/5/

**Comment by speasley** [comment]
That is a great solution and very helpful. Thank you.
