### ISSUE TITLE
ractive.findComponent() seems to fail when certain data values are enabled.

### ISSUE THREAD

**Issue by mikemaccana** [ractivejs/ractive#2774]
I'm using ractive 0.8.5

I have a ractive with a number of sub components.

If I comment out:

    data: {
      // Yes exactly this below
      currentStep: 1
      // Yes just this single line above 
    }

Then `this.findComponent('progressBar');` returns a component.

If I leave in that line, `this.findComponent('progressBar');` returns `undefined`

The progressBar component is incredibly boring:

    var fs = require("fs"),
      Ractive = require("ractive"),
      progressBarTemplate = fs.readFileSync(__dirname + "/progress-bar.mustache", "utf8");

    var progressBar = Ractive.extend({
    	isolated: false,
    	template: progressBarTemplate,
    	data: {}
    });

    module.exports = progressBar;

**Comment by evs-chris** [comment]
I think I need a little more info to reproduce the issue. I think the progress bar and main templates would do it. Here's the fiddle I was checking against, if you want to just add it there and update it: https://jsfiddle.net/evschris/whh067hp/

**Comment by mikemaccana** [comment]
Ack, trying to play with a few things here. The current progressbar template is `<p>Test</p>`.

**I can change `currentStep: 1` to `currentStep: 'banana'` and the `this.findComponent('progressBar');` works.**

I'll keep playing here and see if I can get a working jsfiddle.

**Comment by mikemaccana** [comment]
OK got it:

The parent template was conditionally including the child, eg the progress bar was only shown after step 1.

Fixed with:
    - {{# currentStep !== 1 }}
    -     \<progressBar />
    - {{ / }} 
    + \<progressBar />

And editing the progressBar template to only show something if `currentStep !== 1`.

**Comment by mikemaccana** [comment]
Wonder if it could be worth mentioning in the docs that conditionally including components is bad? This was totally user error but it seemed reasonable at the time.

**Comment by evs-chris** [comment]
It's not necessarily _bad_, as it can be quite handy for SPAs that swap out views as part of navigation, but it probably wouldn't hurt to add a note to the docs to point out that `findComponent` and friends only work with currently rendered things.
