### ISSUE TITLE
Underdocumented sweet decorator feature: update

### ISSUE THREAD

**Issue by TehShrike** [ractivejs/ractive#2777]
Documentation issue: I was wondering how to handle changes to dynamic decorator arguments, but couldn't find any way to do `observe` type stuff.

Eventually I found #429 and learned I could return an `update` function along with my decorator's `teardown` function!

After learning that, I noticed the reference to "the update method of the decorator" on http://docs.ractivejs.org/latest/decorators, but I think this feature really needs to be documented on http://docs.ractivejs.org/latest/writing-decorator-plugins .

Almost related: I'm loving decorators in 0.8, the `as-whatever` syntax is gloooorious

Thanks ❤️ 👍

**Comment by ghost** [comment]
Noticed that when I was running through the docs. As far as I know, the behavior is that if the arguments to the decorator update, two things can happen:

- If the decorator does not return an `update`, the decorator function gets re-run.
- If the decorator does return an `update`, that will run instead of the decorator function.

I think @evs-chris is working on the docs right now so hang tight. 😄

**Comment by TehShrike** [comment]
In my case, `reset` was getting called, and was changing the values that the argument dependend on.

My testing led me to believe that in that case the decorator was not getting re-run when that reset happened, though I didn't test that thoroughly.

At the very least, `destroy` was never getting called.  If the decorator was getting re-run without calling `destroy`, that would be bad, because I would have been leaking event listeners.

**Comment by ghost** [comment]
I think you mean `teardown` 😄

**Comment by TehShrike** [comment]
oh yup I do!  `teardown` was not being called.  I'll make a fiddle to see if I can repro that.

**Comment by TehShrike** [comment]
I set up a fiddle to reproduce, and confirmed what you said.  On `reset`:

- when there **is** an `update` function, it is called
- when there is **no** `update` function, `teardown` is called and then the decorator is re-run

There must have been an issue in the non-`update` version of my code.

**Comment by evs-chris** [comment]
Yep, I'm working on the docs, but it wouldn't hurt to update the current ones, as my docs project is a bit ambitious and might take a while to get off the ground. :smile:

**Comment by ghost** [comment]
Updated the docs. I only found `update` mentioned in the 0.8 Decorators page. Not entirely sure how far back it was supported.

**Comment by TehShrike** [comment]
The new docs look great!  Thanks @fskreuz!
