### ISSUE TITLE
CSS wrongfully transformed (attributes selector: start-with, contains)

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#2778]
## Description:
CSS transformation breaks for attributes matches like `[xyz*="abc"]`  and `[xyz^="abc"]`.
In my tests `[xyz$="abc"]` transformed properly.

## Versions affected:
0.8.5

## **Code:**
If you have this CSS: 
```
.note-rule-text a[href^="https://"]::after {
  content: "MyTest";
}
```

It will be transformed to something like:
```
.note-rule-text  a[href^="https[data-ractive-css~="{1c5477da-53ba-62ab-3012-9f1508e61a39}"]://"]::after, .note-rule-text  [data-ractive-css~="{1c5477da-53ba-62ab-3012-9f1508e61a39}"] a[href^="https://"]::after, .note-rule-text[data-ractive-css~="{1c5477da-53ba-62ab-3012-9f1508e61a39}"]  a[href^="https://"]::after, [data-ractive-css~="{1c5477da-53ba-62ab-3012-9f1508e61a39}"] .note-rule-text  a[href^="https://"]::after {
  content: "MyTest";
}
```

Which won't work in browser (see `a[href^="https[data-ractive-css~="{1c5477da-53ba-62ab-3012-9f1508e61a39}"]://"]::after`).

**Comment by MartinKolarik** [comment]
It's because of the colon in attribute value. Using `a[href^="https"]` should work for now. I believe the current implementation fails with many edge cases like this - will try to write a better parser for css selectors when I have some time.
