### ISSUE TITLE
Question: Get default data from root

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2779]
Hello all, I want to ask if this is a valid thing to do: [http://jsfiddle.net/uehkvw4o/3/](http://jsfiddle.net/uehkvw4o/3/)
i.e: use data from the parent (or root) as the default for a component.
Is this ok?
```
data: function () {
        return {
            thevalue: this.root.get('myvalue')
        };
    }
```

**Comment by evs-chris** [comment]
That's a perfectly valid thing to do, as long as you're aware that the two values will not be synced. You'll also want to avoid copying objects and arrays like that unless you are doing a deep clone or slice.

**Comment by ghost** [comment]
Though valid, this approach breaks encapsulation and causes tight coupling. The component now 1) expects an ancestor exists or knows about an ancestor and 2) expects the ancestor to have a `myvalue` key.

I would suggest keeping default values to the component themselves.

**Comment by evs-chris** [comment]
Also, what @fskreuz said. My answer assumes you're already in a tight coupling situation where the child component is acting as a private member of the root. You'd definitely not want to do this with a generic component.

**Comment by kouts** [comment]
Thanks @fskreuz and @evs-chris , is there any way to keep them in sync or is this something that it can only be achieved by explicitly passing the data to the component? i.e.
```
<testcomponent thevalue="{{myvalue}}" />
```

**Comment by kouts** [comment]
Will [ractive.link()](http://docs.ractivejs.org/edge/ractive-link) help with this, or am I completely off? :confused:

**Comment by evs-chris** [comment]
Passing the data to the component (mapping) will work, as will `link`. Both do the same thing behind the scenes. using links and mappings _will_ keep the data in sync, because it's the same data, so you can map or link objects and arrays across instances and everything will update appropriately as changes happen.

Note that cross instance linking is only available on edge (0.9) right now.

**Comment by ghost** [comment]
Still, given the sample code, it's a strange use case to have an ancestor define defaults for a descendant (or in this case, the descendant asking an ancestor what it should default to). @kouts if you don't mind, can we see the rest of the code or at least what this component does? Feels like it's a use case I haven't come across before.

**Comment by kouts** [comment]
There is a component that uses "hardcoded" keypaths that now must be changed to getting data from outside but if this is not the case then fallback to defaults which they are always present in the root instance. Unfortunately the nature of the development environment does not allow me to update all places this component is used so I figured this as a solution.
It might not be a good idea, but I will try the link feature to see if this works in my case.
