### ISSUE TITLE
input value is not updated when printing

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2781]
http://jsfiddle.net/kv7xwpfk/4/

**Comment by ghost** [comment]
Not sure if this is a bug or a browser quirk. I'm seeing the same behavior without Ractive. (I'm on Chrome) https://jsfiddle.net/kv7xwpfk/5/

**Comment by evs-chris** [comment]
Yeah, I'm pretty sure there's nothing we can do about this, as ractive is only responding to input events and not actually changing anything in the input.

**Comment by ceremcem** [comment]
@fskreuz Oh, yeah... It's same without Ractive... I suspected that if Ractive's virtual DOM might cause this behaviour but there seems no such problem. 

PS: sorry, I should test without Ractive first :(
