### ISSUE TITLE
Transitions broken in 0.9?

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2785]
## Description:

Running through old issues, I came across https://github.com/ractivejs/ractive/issues/2152. The custom easing issue is still unresolved and tried working on it, but what's more interesting is that:

- Transitions work in 0.8: https://jsfiddle.net/betc10qo/2/
- Transitions break in 0.9: https://jsfiddle.net/betc10qo/3/

I'm not aware of any changes to transitions or its syntax, and nothing appears to be in the changelog so I'll just put this here just in case this is a real bug.

## Versions affected:

0.9

## Platforms affected:

Only tried on Opera and Edge, but Chrome and Firefox should also be affected regardless.

**Comment by evs-chris** [comment]
It's a known breaking change :smile:. 0.8 introduced `${name}-in-out` syntax with cleaner parsing and deprecated `intro-outro` syntax. 0.9 just removed all of the deprecations: https://jsfiddle.net/betc10qo/4/

**Comment by ghost** [comment]
Oooh. I was looking at the wrong version in the changelog. Thanks.
