### ISSUE TITLE
Merging rcu into Ractive's bin (or vice versa)

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2786]
## Description:

Probably self-explanatory but I'll explain anyways. We have Ractive's bin (which at the moment contains `parse`). Then we have rcu which is a module that contains utility functions for pre-parsing stuff. We have utils in two places!

So I was wondering, to avoid multiple tools:

- The bin go over to rcu, drop Ractive bin (make rcu be both importable and as a bin).
- Bring rcu to Ractive's bin, drop rcu (ractive bin with more functions, not sure about importability).
- Bring rcu to Ractive's bin, and have rcu (the module) be a thin wrapper for the bin functionality.

Any thoughts?

**Comment by evs-chris** [comment]
I was thinking about this too, and I'm very conflicted. On one hand, having a bunch of different ways to do the same things is certainty suboptimal. On the other hand, especially for the precompilation case, it makes a ton of sense to have that as a built-in. That seems to be one of the biggest issues people run into, given that iOS browsers like to die horribly when parsing large templates.

Right now, I'm leaning toward adding a simplified component builder into the bin script and just leaving rcu to more tool oriented build processes. I don't think it would take much at all to convert a component definition into an es module, and it eliminates a bunch of complexity if you drop source maps and AMD/CommonJS support.

For 0.9, it's all flagged experimental anyways, so we can play with it a bit to see what works out best.

**Comment by dagnelies** [comment]
I've never used *rcu* directly, so I'll leave it up to your expertise.

I just now that following plugin:
https://github.com/ractivejs/ractive-load
has both a dependency on ractive and on rcu. Sadly, it's broken and unmaintained.

**Comment by ghost** [comment]
I'll close out this one since rcu is a totally different monster, primarily because it's meant to be embedded in other tools, as opposed to being a build-time dependency.

While it is possible to merge everything (nothing is impossible 😉 ) and make Ractive bin more robust, it makes the Ractive package a bit more complicated with dependencies and all.
