### ISSUE TITLE
Adaptor not called for '2nd level' properties

### ISSUE THREAD

**Issue by benbeaumont** [ractivejs/ractive#2788]
## Description:

I am trying to use an adaptor on an object whose data is effectively:
```
{ name: 'abc',
  dimensions: {
    height: 123,
    width: 123,
  }}
```

When I put these properties in the mustache I can see the adaptor 'set' method being called for the {{name}} property.

However, I do not see the adaptor 'set' method called for {{dimensions.height}} nor {{dimensions.width}}

## Reproduction:
I've made this up in a fiddle: http://jsfiddle.net/benbeaumont/ATAgH/30/
  - you will see some input boxes
  - the calls to the adator 'set' method are logged (in purple)
  - note that changing the width/height does not cause a new purple message while changing the name does

## Versions affected:
Tried with latest (currently v0.8.1)

**Comment by ghost** [comment]
I'm seeing the same behavior in 0.6.1, 0.7.3 and 0.8.5 which suggests that this might not be a bug but a use case that adaptors wasn't designed for. But I'm not that sure as I personally don't use adaptors that much. I'll let others chime in.

Should it be a known limitation, at least we need it to warn or be documented somewhere. :)

**Comment by evs-chris** [comment]
Yes, as originally designed and implemented, adaptors support only the value and its immediate children. There's a planned redesign on adaptors for 0.10 that aims to address this and a few other limitations with adaptors. The next adaptor API is still open for discussion, so I'm going to punt this over to the existing issue: #2512
