### ISSUE TITLE
The adaptor example isn't working - via Twitter

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#2789]
A quick look through didn't surface the issue. Here's the repro: http://jsfiddle.net/ATAgH/28/

**Comment by ghost** [comment]
You used `adaptors` instead of `adapt` :P https://jsfiddle.net/ATAgH/32/

**Comment by evs-chris** [comment]
Nice! I was looking on my phone and completely missed that. I thought it was a docs bug, but it looks like it's just a case of slightly confusing options.

**Comment by ghost** [comment]
Yep. That got me once before while going through adaptor docs.

And you're working on a fone? So hardcore! 🙇

**Comment by jasny** [comment]
@evs-chris Could you update the docs to link to the fixed jsfiddle on http://docs.ractivejs.org/0.8/writing-adaptor-plugins ?

**Comment by evs-chris** [comment]
@jasny done! I didn't even see the link on the first look though :smile: That was a very out of date fiddle.
