### ISSUE TITLE
0.8.5: inline style with !important does not get rendered to browser

### ISSUE THREAD

**Issue by mpowell-atomic** [ractivejs/ractive#2794]
## Description:
A template that has an inline style with !important (e.g. style="display: inline !important") when rendered to the browser doesn't have the attribute at all. If I remove the !important, it does get rendered. It does, however, appear when using this.toHTML().

## Versions affected:
0.8.5 (update: and 0.9)

## Reproduction:
0.8.5: https://jsfiddle.net/jgawe4cq/

Works in 0.7.3:
https://jsfiddle.net/85a5o443/

## Code:
```javascript
new Ractive({
  el: 'body',
  template: `
  <div class="test">
    <div style="display: inline !important;">
      LEFT 
    </div>
    <div style="display: inline !important;">
      RIGHT 
    </div>
  </div>

  <div>Ractive 0.8.5</div>
  <p>toHTML() output:</p>
  <code>{{debug}}</code>`,
  onrender: function(){
  	this.set('debug', this.toHTML());
  }
});
```

**Comment by evs-chris** [comment]
Hmmm. I had never seen an `!important` on an inline style until now. It looks like we can probably fix it (http://stackoverflow.com/questions/7917608/im-unable-to-inject-a-style-with-an-important-rule), but it may add a bit of overhead to processing style elements. Out of curiosity, are you trying to defeat an `!important` in a stylesheet?

This is caused by 0.8 adding support for _not_ clobbering the style attribute when updating it. Instead, it parses the rules in the attribute body, keeps track of what it is changing, and applies them using the property on the DOM node.

**Comment by ghost** [comment]
It _is_ strange to have `!important` on inline styles. :D

While it appears to be a bug, may I suggest you reconsider how the CSS is done. Usage of `!important` is a warning sign signaling that your CSS is fighting for power. 😄

**Comment by mpowell-atomic** [comment]
:-) In this particular case, the app is one used for creating html email newsletters so ```!important``` is essential to the working of html emails. sadly. Believe me, I wish I wasn't working with html email...

**Comment by mpowell-atomic** [comment]
how much of an overhead? could it be optional maybe? it's super important to this app working. i realise it is an edge case maybe but it'd be nice if the html that is in the templates is rendered as is. thanks!

**Comment by evs-chris** [comment]
Well I've learned a few new things I didn't know about CSS today :smile:. I can't seem to find a definitive answer on what _other_ values are allowed for priority. It seems that `important` is the only string mentioned anywhere that my google-fu has turned up. Does anyone know of any other allowed priorities? `!unimportant`? `!normalDammit`? `!whyGodWhy`?

As to overhead, an extra string replace and compare per style key, so not huge, but not nothing.

_Edit:_ eh, change string compare to string length compare, as that works just as well.

**Comment by mpowell-atomic** [comment]
yeah, i feel like there might be but i can't find any either.

**Comment by ghost** [comment]
Ractive has [`Ractive.getCSS()`](http://docs.ractivejs.org/latest/ractive-getcss) and [`ractive.toCSS()`](http://docs.ractivejs.org/latest/ractive-tocss). You can simply write CSS like normal in the component definitions (unsupported on single instances at the moment), then you can use either method to grab the CSS. Then render the grabbed CSS after everything you want to override.

The following assumes that your CSS is fixed (no dynamic values, bindings or whatever), thus we can move it out of the template and into the `css` property. Also assumes you have control over the rendering of that HTML. https://jsfiddle.net/jgawe4cq/1/

```js
const Component = Ractive.extend({
  template: `
  <div class="test">
    <div class="test__left">
      LEFT 
    </div>
    <div class="test__right">
      RIGHT 
    </div>
  </div>
  `,
  css: `
    .test{}
    .test__left{ display: inline !important; }
    .test__right{ display: inline !important; }
  `
});

const ractive = new Component({
	el: 'body'
});

console.log(Ractive.getCSS()); // Gets all CSS known to Ractive
console.log(ractive.toCSS()); // Gets CSS of the instance only
```

**Comment by mpowell-atomic** [comment]
Interesting but I cannot do that. HTML email depends almost entirely on inline styles on the elements because of the way email clients render/mangle the emails and the !important in particular is used to override the mail client styles.

**Comment by ghost** [comment]
Hahaha. I clearly have no experience in HTML emails. Well, I tried. 😄 

#TodayILearned

**Comment by evs-chris** [comment]
The fix for this shipping on edge now and will be shipped to 0.8-dev shortly thereafter. It will also go out with 0.8.6 when it gets cut.

**Comment by mpowell-atomic** [comment]
Amazing! Thank you! Any very approximate ETA for a 0.8.6 release so I can communicate with the project managers?

**Comment by evs-chris** [comment]
I suppose it's been three weeks with no _reproducible_ errors other than this reported, so I'll go ahead and push 0.8.6 about two minutes ago :wink:.
