### ISSUE TITLE
0.8.6: inline styles that have a dash in them e.g. background-color are ignored

### ISSUE THREAD

**Issue by mpowell-atomic** [ractivejs/ractive#2796]
## Description:
Hi. Apologies! I found another inline style issue... A template with inline styles that have dashes in them, e.g. background-style, font-weight, etc are not rendered to the DOM but are output when toHTML() is used.
## Versions affected:
0.8.x, 0.9

## Reproduction:
0.8.6 - no background-color is rendered:
https://jsfiddle.net/d1em01kt/

0.7.3 - correct rendering:
https://jsfiddle.net/n9rvkahd/

## Code:
```javascript
new Ractive({
  el: 'body',
  template: '<span style="background-color: red;">background color should be red</span>',
  onrender: function(){
    console.log(this.toHTML());
  }
});
```

**Comment by evs-chris** [comment]
Neat! I didn't know `setProperty` uses actual css names. That'll let us ease up on the processing applied to properties during updates (camelization).

**Comment by evs-chris** [comment]
I've pushed out 0.8.7 with the fix. Hopefully there are no more #TIL experiences lurking around the corner :laughing:

**Comment by mpowell-atomic** [comment]
Ha. Gosh, thank you for your work on Ractive and keeping it alive! It's working nicely in my html email abomination app now. This fix is good. Yeah, I hope, for your sake, to not find anything else. 

Also, today I learned what #TIL means.

**Comment by evs-chris** [comment]
On the plus side, the test suite is getting more and more comprehensive :grinning:

**Comment by evs-chris** [comment]
Also, thanks for the bug reports! It's not great that there are bugs, but it's always great when bug reports have good descriptions and nice, easy-to-follow reproductions.
