### ISSUE TITLE
File input's value binding doesn't work

### ISSUE THREAD

**Issue by orangecoloured** [ractivejs/ractive#2797]
## Description:
The binding with the file input's value doesn't work. After choosing a file the bound Ractive object is not updated.

## Versions affected:
0.8.1

## Platforms affected:
Firefox, Chrome, Ubuntu

## Reproduction:
Here's a couple of fiddles to demonstrate the issue:
https://jsfiddle.net/RCKT/b55hfLsw/3/ - 0.8.1 doesn't work
https://jsfiddle.net/RCKT/2outv20a/4/ - 0.7.3 works

## Code:
```html
<div id='container'></div>
<script id='template' type='text/ractive'>
	<input id="file" type="file" value="{{fileInputValue}}" on-change="checkFiles" />
    <p>{{fileInputValue}}</p>
    <p>{{files}}</p>
</script>
```
```javascript
var ractive = new Ractive({
    el: '#container',
    template: '#template',
    data: {
        fileInputValue: null,
        files: null
    }
});

ractive.on('checkFiles', function (event) {
    var input = document.getElementById('file');
    this.set('files', input.files);
});
```

**Comment by evs-chris** [comment]
I think this was fixed in 0.8.4, but it looks like it missed the changelog. https://jsfiddle.net/b55hfLsw/4/

**Comment by orangecoloured** [comment]
@evs-chris Thanks!

I'm using the one from cdn.ractivejs.
It would be nice to have this fix in there.

**Comment by ghost** [comment]
@orangecoloured Ahh. The one in cdn.ractivejs.org is 0.8.1, and not updated. Use https://unpkg.com/ractive instead.

**Comment by orangecoloured** [comment]
@fskreuz Ok. Thanks for the info!
