### ISSUE TITLE
Why is uglify not part of gobble's production run

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2804]
## Description:

Just as the title says. Why is it not part of the production run in gobble?

I'm playing with the gobblefile and was just curious why some parts of the build are in the gobble file while the others are in the build script. Wondering if I should be aware of anything before plowing in and moving things around.

**Comment by evs-chris** [comment]
I think it's mostly a legacy thing. This is actually one of the things on my todo list, but you're certainly welcome to knock it out 😁
