### ISSUE TITLE
0.8.7 - Setting array item at specific index doesn't update expression

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2806]
Check this fiddle [http://jsfiddle.net/kqp6c96q/3/](http://jsfiddle.net/kqp6c96q/3/)
Setting an item on the list array doesn't update the expression.
You have to manually call update (uncomment line 12 in js) in order to  update the expression.

**Comment by ghost** [comment]
Doesn't appear to work on 0.7.3 as well https://jsfiddle.net/kqp6c96q/4/

**Comment by evs-chris** [comment]
This is now fixed in 0.8-dev and edge, and will be published when 0.8.8 is released. Thanks for the report!
