### ISSUE TITLE
Unloading DOM events before they exist?

### ISSUE THREAD

**Issue by holmosapien** [ractivejs/ractive#2814]
## Description:

I am in the process of upgrading our web application from Ractive 0.6.1 to 0.8.8, and I've run into an interesting issue in a few places.

We regularly kick off the loading of data from APIs in onrender(), and show the appropriate state in the template via state variables.  See attached JS and template for minimal example.

We're running into a situation where, if we immediately in onrender() change a state that causes portions of the template with on-click events to be removed from the DOM, Ractive crashes with the following error:

```
Uncaught TypeError: Cannot read property 'removeEventListener' of null
    at DOMEvent.unlisten (/build/vendor.core.bundle.js?v201612311342:40438:14)
    at /build/vendor.core.bundle.js?v201612311342:40610:51
    at Array.forEach (native)
    at EventDirective.destroyed (/build/vendor.core.bundle.js?v201612311342:40610:16)
    at /build/vendor.core.bundle.js?v201612311342:42358:56
    at Array.forEach (native)
    at Element.destroyed /build/vendor.core.bundle.js?v201612311342:42358:21)
    at Element.detach (/build/vendor.core.bundle.js?v201612311342:42364:32)
    at detachImmediate (/build/vendor.core.bundle.js?v201612311342:30259:14)
    at TransitionManager.ready (/build/vendor.core.bundle.js?v201612311342:30188:4)
```

There are a number of workarounds, like setting the initial state such that we don't have to immediately flip it or moving the loading to oninit(), but in some cases we really do need to begin the initialisation in onrender() once certain DOM elements are available to us.

Checking for `this.node` before calling `this.node.removeEventListener()` within `DOMEvent` does of course prevent the crash, however I am not familiar enough with the Ractive internals to know whether that hides some even worse problem later.

## Versions affected:

0.8.8

## Platforms affected:

Chrome 55.0.2883.87

## Code:

```
var RactiveTest = Ractive.extend({
    'template' : require('../../tp/ractive/test.tp.html'),
    'el'       : '#ractiveElement',

    'components' : {
    },

    'data' : function() {
        return {
            'loading' : false,
        };
    },

    'oninit' : function() {
    },

    'onrender' : function() {
        this.loadSomething();

        this.on('onDoSomething', function() {
            console.log('I am doing something.');

            this.loadSomething();

            return false;
        });
    },

    'loadSomething' : function() {

        // Indicate we're loading some data.  Unset the flag when the loading is done.

        this.set('loading', true);
        this.set('loading', false);
    }
});
```

```
{{ #if loading }}
    <h4>LOADING</h4>
{{ else }}
    <a href="#" on-click="onDoSomething">
       <h4> NO LONGER LOADING</h4>
    </a>
{{ /if loading }}
```

**Comment by evs-chris** [comment]
I wasn't able to get a test reproduction for this, but the code in 0.8 was a little different than that in edge. I've added a check in 0.8 to make sure that a handler is actually installed before trying to remove one, so it now matches what edge does and _should_ prevent an exception due to missing node (because the handler gets created while attaching an event listener to the node).

This change is published as v0.8-dev if you want to try it out. The vRelease-dev builds only get bug fixes applied, so it should be a stable target. Thanks for the report!
