### ISSUE TITLE
Conditional transitions in 0.8.x

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#2815]
Hi, I'm just migrating my app from Ractive 0.7 to 0.8 and got some questions on transitions.

How do you make transitions execute conditionally in Ractive 0.8.x?

In 0.7.3 you could do this: 
`<div intro-outro="{{useAnimation ? 'fade' : ''}}:150">Hello World</div>`
Which was kind of hacky but it worked.

In 0.8.x we have new transitions syntax and I can't figure out how to put that transition into a condition.
I've built a demo here: https://jsfiddle.net/lejared/qsxgL7bz/1/
This: `<div {{#if animate}}fade-in-out="1000"{{/if}}>Hello World</div>` won't work.

In my app The whole purpose on that is to prevent the element from being animated if the parent element was removed from the DOM, but still be animated if the element itself is removed/added.

BTW: Documentation on how to build decorators is outdated, as it still uses old `decorator="tooltip"`-syntax.
http://docs.ractivejs.org/latest/writing-decorator-plugins

**Comment by evs-chris** [comment]
This is a bug caused by the transition trying to get a reference to its target node from the wrong place. It shouldn't be too hard to track down. Thanks for the test case!

**Comment by evs-chris** [comment]
This is now fixed in v0.8-dev (0.8.9-build-3) and on edge. It will go out with 0.8.9, which will probably happen in a few hours. Thanks for the report!

**Comment by LeJared** [comment]
Wow, that was quite fast! Thanks!
