### ISSUE TITLE
Uncaught Error: ReferenceExpressionChild retrieving mismatched models?

### ISSUE THREAD

**Issue by sarendipitee** [ractivejs/ractive#2817]
## Description:

It seems like ReferenceExpressionChild is messing up when the model changes from `true` to an object and back.

```
Uncaught TypeError: Cannot use 'in' operator to search for 'baz' in true
    at ReferenceExpressionChild.retrieve
    at ReferenceExpressionChild.mark$1 [as mark]
```

## Versions affected:

0.8.2+

## Platforms affected:

Chrome 55+

## Reproduction:

https://jsfiddle.net/feo2xhbs/

## Code:

This may be overly complex because I pulled it from the app it was happening in, but the key here is the `<thing {{#if .foo.baz}}zap='{{.foo.baz}}'{{else}}zap='{{ ~/someComputed ? 10 : 5 }}'{{/if}}></thing>`

Even if I wrap the `{{#if .foo.baz}}` in an `isObject(.foo) && isNumber(.foo.baz)` it still throws the error.

```
Thing = Ractive.extend({
	template: `<em>(Thing zap={{.zap}})</em>`,
});

app = new Ractive({
	el: 'app',
	data: {
		items: [
			{ name: 'Item 1', foo: null },
			{ name: 'Item 2', foo: { baz: 10 } },
			{ name: 'Item 3', foo: true },
		 ],
		selectedItemIndex: 0,
	},
	template: `
		{{#each items}}
			<button on-click='set("selectedItemIndex", @index)'>Select {{.name}}</button>
		{{/each}}

		<hr>

		{{#with items[selectedItemIndex]}}
			{{> item}}
		{{/with}}
  `,
	computed: {
		noName() {
			return this.get('items').length > 0;
		}
	},
	partials: {
		item: `
			<div class='item'>
				{{.name}}
				<thing {{#if .foo.baz}}zap='{{.foo.baz}}'{{else}}zap='{{ ~/someComputed ? 10 : 5 }}'{{/if}}></thing>
			</div>
		`,
	},
	components: {
		thing: Thing,
	}
});
```

**Comment by evs-chris** [comment]
This is now fixed in edge and 0.8-dev, and it's been released along with the transition fixes in 0.8.9. Thanks!

**Comment by sarendipitee** [comment]
@evs-chris You're awesome Chris! Really simple fix. I wish I wasn't so afraid little changes like that would have cascading effects because I don't see the whole picture!

**Comment by evs-chris** [comment]
The test suite _mostly_ keeps me from freaking out about little things like this :grinning:
