### ISSUE TITLE
Passing a data attribute to a transition cause a Type Error when set data to null after transition is complete

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#2818]
Greetings,
above all thanks for creating this library.

## Description:
It seems that passing a object data to a transition using new syntax and then removing the object after transition will generate a `TypeError: x.handleChange is not a function`.

The transition is a simple version of the one that is currently present in the app and has some timeouts but I think this is not related to the issue.

NOTE: This issue is not present using old transition syntax.

## Versions affected:
0.8.x

## Reproduction:
1. Click on animate button!
2. Check console.

new syntax (doesn't work) -> https://jsfiddle.net/swkz9n7n/16/
previous syntax (works)  -> https://jsfiddle.net/swkz9n7n/17/

## Code:

HTML
```html
  <h1>Hello {{who}}!</h1>
  <button on-click="@this.fire('animate')">Animate!</button>
  
  {{#if _myBlock}}
  	<p customTransition-in="{ someData: _myBlock }">{{_myBlock.text}}</p>
  {{/if}}
```

JAVASCRIPT
```javascript
function customTransition(t, params) {
  var DEFAULTS = {
    delay: 0,
    duration: 300,
    easing: 'linear'
  };

  var targetOpacity;

  params = t.processParams(params, DEFAULTS);

  if (t.isIntro) {
    targetOpacity = t.getStyle('opacity');
    t.setStyle('opacity', 0);
  } else {
    targetOpacity = 0;
  }

  setTimeout(() => {
    t.animateStyle('opacity', targetOpacity, params)
    setTimeout(() => {
      t.complete(true)
    }, 2000);
  });
}

const r = window.r = new Ractive({
  el: '#main',
  template: '#template',
  transitions: {
    customTransition,
  },
  data: {
    _myBlock: null,
    who: 'World',
  },

  oninit() {
    this.on('animate', () => {
      // reset another animation if is in progress
      this.set({ _myBlock: null}).then(() => {
        this.set({ _myBlock: { text: 'greetings' } }).then(() => {
          this.set({ _myBlock: null});
        });
      });
    });
  },
});
```

**Comment by evs-chris** [comment]
This was already fixed on edge and is now fixed in v0.8-dev. Thanks for the report!
