### ISSUE TITLE
Result of Ractive.getNodeInfo() for invalid nodes

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#2819]
If you call `Ractive.getNodeInfo()` with a dom node, which does not belong to any Ractive instance or simply isn't part of the DOM anymore, Ractive.getNodeInfo() returns an empty object.

I find this a bit unpleasant. I think, it should either return `null` / `undefined`, so you can simply check for it, or  it should still return a helper object with all it's helper methods attached and have them return sane values like empty string for `info.resolve()` or `null` for `info.ractive`.

Right now i first have to check if `info.resolve` is present before calling it, as it might not.

**Comment by evs-chris** [comment]
Yeah, that sounds like a more friendly API, and the prior behavior was undefined, so I wouldn't really consider this to be breaking. v0.8-dev and edge will now return undefined for non-Ractive or falsey nodes.

**Comment by Jeff17Robbins** [comment]
@paulie4  and I are currently relying on the undefined behavior of 0.7.3, and have a number of spots in our code that look like this

```var r = Ractive.getNodeInfo(node).ractive;```

Which, for a non-ractivated node, would conveniently set `r` to `undefined`, but now throws an error.  I see @LeJared 's point, as to why the old behavior is unpleasant for some use-cases.

**Comment by LeJared** [comment]
I get your point, but your example `Ractive.getNodeInfo(node).ractive;` is the only one, where this would still work. If you had relied on `Ractive.getNodeInfo(node).keypath;` in 0.7.3 this would crash now anyways, since `Ractive.getNodeInfo(node).resolve().keypath;` on the new info-object is not defined in either way.

**Comment by Jeff17Robbins** [comment]
It was a convenient way for us to initialize a variable with a node's Ractive instance, if it had one.

**Comment by LeJared** [comment]
I'm sorry for inconvenience. Maybe this might help:

extend Ractive with own `getNodeInstance` Method like this
```JS
Ractive.getNodeInstance = function (node) {
	var info = this.getNodeInfo(node);
	return info && info.ractive;
}
``` 
To make the call even more convenient:
```JS
var r = Ractive.getNodeInstance(node);
```

**Comment by Jeff17Robbins** [comment]
Nice suggestion -- thanks!
