### ISSUE TITLE
Ractive 0.8 Transitions  -  set transition name dynamically 

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#2820]
## Description:
In Ractive 0.7.x transition syntax the name can be set dynamically. 
In Ractive 0.8.x using moustache syntax for transition name inside an `if` cause a `Parse error`.

Refer to following fiddles.

## Versions affected:
0.8.x

## Reproduction:
New Syntax https://jsfiddle.net/swkz9n7n/19/
1. Run fiddle!
2. Check console.

Previous syntax https://jsfiddle.net/swkz9n7n/18/
## Code:
HTML
```html
<h1>Hello {{who}}!</h1>
  
<button on-click="@this.toggle('show')">Show element!</button>
  
{{#if show}}
  {{console.info('transition', transition)}}
    <p {{#if !!transition}}{{transition}}-in{{/if}}">Hi there!</p>
{{/if}}
```

JAVASCRIPT
```javascript
function fade(t, params) {
  var targetOpacity;

  var DEFAULTS = {
    delay: 0,
    duration: 300,
    easing: 'linear'
  };

  params = t.processParams(params, DEFAULTS);

  if (t.isIntro) {
    targetOpacity = t.getStyle('opacity');
    t.setStyle('opacity', 0);
  } else {
    targetOpacity = 0;
  }

  t.animateStyle('opacity', targetOpacity, params).then(t.complete);
}


const r = window.r = new Ractive({
  el: '#main',
  template: '#template',
  transitions: {
    fade,
  },
  data: {
    who: 'World',
    transition: 'fade',
    show: false
  }
});
```

**Comment by evs-chris** [comment]
This is actually a known breaking change. There's no dynamic name support on directives yet, but you can still get the same effect with a wrapper transition that delegates to the named transition on the fly.

**Comment by evs-chris** [comment]
I think the best solution to this is probably a composite transition that would allow names to be changed and multiple transitions to be run in parallel and/or in sequence, so I'm going to point this issue to #987
