### ISSUE TITLE
Rendered unresolved component name case different on Edge.

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2821]
## Description:

This test passes on every other browser I have (IE11, Opera and therefore Chrome, Phantom) but blows up in edge. It appears that there's confusion about the case of a component name when it's unresolved. Edge renders an unresolved `<Foo/>` as `<Foo></Foo>` while other browsers do `<foo></foo>`.

Not sure which one is correct though. The component's name, as used on the template, is `<Foo/>` so it might make sense that the HTML be `<Foo></Foo>`. However, I am not an expert when it comes to HTML spec and behavior. It might be correct to lowercase element names, as HTML is a case-insensitive language.

## Versions affected:

The test has been there since March 2016. Potentially 0.8 and newer only.

## Platforms affected:

Edge

## Reproduction:

![untitled](https://cloud.githubusercontent.com/assets/1582932/21747467/984d6896-d535-11e6-9433-0de51ef95b60.png)

## Code:

```js
	test( 'Components not found in view hierarchy when isolated is true', t => {
		const Foo = Ractive.extend({
			template: 'foo'
		});

		const Bar = Ractive.extend({
			template: '<Foo/>',
			isolated: true
		});

		new Ractive({
			el: fixture,
			template: '<Bar/>',
			components: { Foo, Bar }
		});

		t.equal( fixture.innerHTML, '<foo></foo>' );
	});
```

**Comment by evs-chris** [comment]
Looks like according to the html5 spec, element names should be lowercased. It kinda depends on the document mode though, so if edge is in XHTML mode or something like that, that would explain the difference.

**Comment by MartinKolarik** [comment]
@evs-chris I think the spec says names should be lowercase, but doesn't say what should browsers do if they are not.

**Comment by evs-chris** [comment]
@MartinKolarik Ah. I was reading https://www.w3.org/TR/html5/syntax.html#syntax-tag-name as saying that the resulting element should have an all-lowercase name. Would it hurt to go ahead and `toLowerCase()` when creating the element?

**Comment by MartinKolarik** [comment]
Custom elements are defined here: https://www.w3.org/TR/custom-elements/#valid-custom-element-name

>Would it hurt to go ahead and toLowerCase() when creating the element?

I think that's the right thing to do.
