### ISSUE TITLE
Which UI lib for Ractive?

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2823]
Hi,

I've got a little time on my hands, and thought about making a wrapper around some web widgets library.
What I had in mind are "rich widgets" like datagrids, trees, tabs, datepickers...

Instead of reinventing the wheel, I'd like to wrap some existing library. The difficulty is choosing one of the many libs available. There are many candidates, without clear winner.

---

These are the ones I investigated:

- dhtmlx: is a "write the UI in JS" framework, doesn't integrate well inside other HTML.
- dojo/dijit: I found it difficult to get into
- easyui: declarative API makes it probably easy to integrate. Nicely customizable. Not on par feature wise with other libs (no keyboard navigation...)
- jquery ui: it's a possibility, but you'd have to deal with a lot of separate plugins since the core is tiny
- jqwidgets: lots of widgets, very nice docs. API slightly complex IMHO regarding remote data handling, drag-drop and other things.
- kendo UI: the "open source" core lacks everything, commercial licenses are expensive.
- primeui: I think not everything is documented and more could be taken out of it ...but it's hard to say.
- vaadin: not even a tree in the standard components?!
- wijmo: not even a tree in the standard components?!
- webix: is a "write the UI in JS" framework, doesn't integrate well inside other HTML.

---

As a conclusion, I'd pick one of:

- easyui
- jqwidgets
- primeUI

EasyUI the easiest to "port" and customize. JQWidgets has most features/documention, and primeUI has a nice license (apache). Each is also JQuery UI based and looks a bit dated.

---

**Do you have any preference as to which IU lib you'd really like to see "ported" to ractive?** (mentionned or not)

**Comment by ghost** [comment]
Currently playing with [Metro UI CSS](http://metroui.org.ua/) with React. That would be a nice one to port that over to Ractive. Bootstrap and friends are too mainstream. :D

**Comment by sarendipitee** [comment]
Yea there isn't really any good options. Using non-ractive components loses out on all the benefits of ractive. That's why I started making my own and open sourcing them. I think the best bet would be to start standardizing on these a bit and pull them all into a website registry where you can find examples and docs.

Maybe as part of the upcoming docs revamp?

**Comment by andreujuanc** [comment]
@dagnelies I'm currently slowly building something here:
https://github.com/andreujuanc/Ractive-Materialize

It's just a wrapper/initializer for now , because of time. But  soon I want to natively write the jquery to Ractive components. 

I agree with @JonDum

**Comment by dagnelies** [comment]
By the way, happy new year to everyone!

I'm aware of all these initiatives and would like to push it a bit further. In particular "rich" widgets (like a tree with drag&drop, key navigation, ajax lazy loading, multiselect...). This differs from the usual css frameworks.

Regarding the quote "Using non-ractive components loses out on all the benefits of ractive", I don't see why. As a user, I just care to write `<tree data-url="api/some/URL" lazy="true" drag-drop="true" />` ...and whether there is a "native" component behind it or wrapped from another lib, I don't care.

**Comment by andreujuanc** [comment]
@dagnelies That's exactly the way I see things. Rich widgets are hard to make, not because of code, but everyone has different requirements. 

And also happy new year!!.

**Comment by ghost** [comment]
> Rich widgets are hard to make, not because of code, but everyone has different requirements.

Using componentized rich widgets isn't that far from the idea of using third-party tools anyways. You're essentially trading flexibility for convenience. As long as everyone comes to a conclusion on what does what, I think it should be fine. You can always fall back to vanilla Ractive should you want more flexibility. And if it's open-source, you can always hack and submit a PR. 👍

**Comment by woodlandhunter** [comment]
I'll add this one to the list: http://semantic-ui.com/

The standard version is using jquery, but there's an official react version too which may be a better starting point.

http://react.semantic-ui.com/introduction

**Comment by dagnelies** [comment]
I'll put this on hold for now and keep you informed.
