### ISSUE TITLE
Inject script/template with the model

### ISSUE THREAD

**Issue by seriouz** [ractivejs/ractive#2832]
How can i inject a `<script>`-tag via the model?
My ractive template looks like this:

```html
<script id="htmlTemplate" type="text/ractive">
    {{{html}}}
</script>
```

The model:

```html
{ "html": "<div>one</div><script type=\"text/ractive\" id=\"injected\"><h1>NICE</h1></script>"}
```

Resulting in an error `SyntaxError: unterminated string literal`

**Comment by evs-chris** [comment]
You've got to escape the double quotes in the string.

Out of curiosity, what are you trying to accomplish with that?

**Comment by seriouz** [comment]
Sorry, i forgot the quotes only here on github. I builded a spa with ractive. Now i have a very special page which is only visible to admins and they will visit it rarely. This special page is injected with json into the `htmlTemplate` from above. Now the tricky part: I want to use ractive (custom ractive instance) on this page. Build the gui, use it for the tables, data binding and event binding.

**Comment by dagnelies** [comment]
> Resulting in an error SyntaxError: unterminated string literal

Like @evs-chris said, this is merely a syntax error in your script.

I'd avoid injecting scripts in the template. By looking at your snippet, it looks like you are trying to render a `<script type="text/ractive">...` inside a ractive template itself. This doesn't seem to make any sense to me.

**Comment by seriouz** [comment]
Consider the following:

We have this template:

```html
<script id="htmlTemplate" type="text/ractive">
    {{{html}}}
</script>
```

This model is working:

```html
{"html": "<div>one</div>"}
```

And this model does not work:

```html
{"html": "<div>one</div><script></script>"}
```

**Comment by dagnelies** [comment]
You should not put scripts inside templates.

**Comment by ghost** [comment]
So Ractive isn't like jQuery where it pops in your HTML and executes any JS found inside the markup (although it might do it as a side-effect).

What you appear to be doing is taking a traditional page (markup with data and script) and loading it with Ractive. You might want to consider creating a component with that similar markup and script, and have your data source represent your data in plain objects. When that data is present, render the component and have it access that data.

```js


const ComponentThatWasHtml = Ractive.extend({
  template: `
    <!-- Template from the HTML. It's a template, that gets filled in with data. -->
    <!-- By default, an instance has full visibility of its parent's data. -->
  `,
  onrender(){
    // Script from that HTML. This will run when an instance of this component is rendered.
  }
});

const ParentComponent = Ractive.extend({
  components: { ComponentThatWasHtml },
  template: `
    <!-- When dataThatWasInHTML is present, render the component. -->
    {{#if dataThatWasInHTML }}<ComponentThatWasHtml />{{/}}
  `,
  data: {
    dataThatWasInHTML: null
  },
  onrender(){
    // Do whatever that loads that data
  }
});
```

**Comment by evs-chris** [comment]
Just wanted to note that you can `resetTemplate` to rerender with whatever template you like, `resetPartial` to swap out partials on the fly (necessary if they're renedered), and simply set a new partial to a string or pre-rendered template e.g. `ractive.partials.foo = "... whatever HTML/Ractive that you want ..."` _before_ a `{{>foo}}` is rendered to achieve dynamic templating.

If you want to template directly from data, you can `{{> { template: ~/template } }}` and `ractive.set('template', "... whatever HTML/Ractive that you want ...")`. Any further updates to `template` will be parsed and rendered into the partial. You can also render pre-parsed templates from data with `{{> ~/template}}` and `ractive.set('template', Ractive.parse('...'))`.

**Comment by evs-chris** [comment]
Also, I _just_ noticed that you're tying to render a script inside another script, which is not possible. The contents of script tags don't get parsed as HTML, so the inner tag will never show up in the DOM.

**Comment by seriouz** [comment]
Thank you all for your help! @evs-chris I'll have a closer look into your comment the next days (Because as you said: parse a script-tag to script-tag is not possible).
