### ISSUE TITLE
Question: "in place" initial template?

### ISSUE THREAD

**Issue by dankoster** [ractivejs/ractive#2834]
Just a quick question here: Is there currently support for using the contents of the target element as the initial template? I want to be able to do this: 

```
const r = window.r = new Ractive({
	el: '#main',
	template: '#main',
	data: { who: 'World' }
});

<div id="main">
	<h1>Hello {{who}}!</h1>
</div>
```

instead of this:
```
const r = window.r = new Ractive({
	el: '#main',
	template: '#template',
	data: { who: 'World' }
});

<script type="text/html" id="template">
	<h1>Hello {{who}}!</h1>
</script>

<div id="main"></div>
```

**Comment by evs-chris** [comment]
There used to be, but there is no longer because of some of the somewhat surprising things that happen to the content of non-script tags when they are parsed. For instance, you have to be careful with component names, as they will be automatically lowercased. You also lose the ability to have mustaches in your attributes. HTML is a little more unpredictable with things like `<div />` too.

Progressive enhancement support will allow you to render into an element that is already populated with normal HTML, and it will reuse as much of the existing DOM as it can. You didn't state why you wanted to use the content as a template, but usually when that question is asked it's to try to avoid the empty main element or render/flash-to-empty/render on load, which is where progressive enhancement helps.

**Comment by dankoster** [comment]
Hey, thanks for the response! I'm mostly just messing around, but you're exactly right. I want to avoid the empty main element AND the render/flash/render. Sounds like progressive enhancement is the way to go. I found [this](https://github.com/ractivejs/ractive/issues/395#issuecomment-149769020) and the docs [here](http://docs.ractivejs.org/0.8/options#enhance). 

So, I tried this obvious hack ([fiddle](http://jsfiddle.net/geh0kobu/1/)):

```
<div id="main">
	<h1>Hello {{who}}!</h1>
</div>

var template = document.getElementById('main');
var ractive = new Ractive({
	el: 'main',
	template: template.innerHTML,
	enhance: true,
	data: { who : 'world' }
});
```

And that kind-of gets me what I wanted, but there are also obvious drawbacks. So that leads to the [next obvious hack](http://jsfiddle.net/1ru3dbqm/1/)... Am I missing built-in support for just straight-up replacing the current template with a new one?

EDIT: I realize, I'm not really using enhance in these examples... just poking around and figuring out what's possible. :)   I'll definitely be using it more like this: http://jsfiddle.net/rich_harris/kxpdgo89/

**Comment by evs-chris** [comment]
You can use `resetTemplate`, but that will probably cause a flash too. There is also a `resetPartial` that avoids the necessity for a conditional wrapping the partial, but again, may cause flashing. Further, if you want to store your partials somewhere data accessible, you can actually change them with a plain `set` using inline partials `{{> { template: some.data.path.to.string } }}` or `{{> some.path.to.parsed.template }}`.

**Comment by dankoster** [comment]
Cool!  Thanks for the help! I'm using Ractive a bit in [Electron](http://electron.atom.io/). I'll letcha know if I come up with anything cool or weird. I'm not so concerned about a flash, but having the template in-place instead of loading it into an empty element was desirable to some co-workers.

Here's kind-of where I ended up in my futzing around: http://jsfiddle.net/u6h37va9/


```
<div id="main">
  <h1>Hello?</h1>
  <button disabled='{{disabled}}' on-click='loadTemplate("#newTemplate")'>Change Template</button>
</div>

<script type="text/html" id="newTemplate">
  <h1>Hello {{who}}!</h1>
  <button disabled='{{disabled}}' on-click='test("ME", true)'>It's ME!</button>
</script>
```

```
setTimeout( () => {
  var template = document.getElementById('main');
  
  var ractive = new Ractive({
    el: 'main',
    template: template.innerHTML,
    enhance: true,
    loadTemplate: function(template) {
      this.resetTemplate(template); 
    },
    test: function(who, disabled){
      this.set('who', who); 
      this.set('disabled', disabled);
    },
    data: { 
      who : 'world',
      disabled : false
    }
  });
}, 2000 );
```
