### ISSUE TITLE
How do we add default methods for components?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2840]
How do we add default method for components so we can use like `this.set`? For example, I want to separate `myfunc` into a library file and make `mycomp` still work: 

```ls
myfunc = (x) ->  
  foo = this.get \foo 
  return x * foo 

```

```ls
mycomp = Ractive.extend do 
  oninit: -> 
    if (this.myfunc 5) is 4
      this.set \bar, \baz
  data: 
    foo: 3
```

**Comment by ghost** [comment]
Destructuring or for older editions, `Object.assign`?

```js
const MyFuncMixin = {
  myFunc(){ ... } // Mixin will have to assume context (this) is a ractive instance.
};

const MyComponent = Ractive.extend({
  ...MyFuncMixin,
  oninit(){ ... }
  data(){ ... }
});

// or

const MyComponent = Ractive.extend(Object.assign({}, MyFuncMixin, {
  oninit(){ ... }
  data(){ ... }
}));
```

**Comment by ceremcem** [comment]
One more thing: Is there any default way to make this assignment valid for all `Ractive.extend` usages?

**Comment by ghost** [comment]
Looks like [`Ractive.defaults`](http://docs.ractivejs.org/latest/ractive-defaults) is what you're looking for. Not sure if it merges everything, haven't been into that part of the code for a while.

**Comment by evs-chris** [comment]
Yes, `defaults` is the base prototype for all ractive instances. Also, each component is a constructor that has a prototype, so you can add methods outside of extends by adding to `Component.prototype`, where Component is the constructor returned from extends.

**Comment by ceremcem** [comment]
Thank you, `defaults` has solved this problem ([here](https://github.com/aktos-io/scada.js/blob/6994d8796cf4250ef0d0bb3c8bae253ea322a6e0/vendor/000.ractive-npm/ractive-npm.ls#L3-L6)).
