### ISSUE TITLE
Cannot fire an event on a component from event handler located in parent component

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#2842]
## Description:
In < 0.8.x ractive version if a component subscribe on a sub component event, in event handler you can access the component instance using `event.component`.
In 0.8.x implementation a lot of component method are present inside the event itself but not the `fire` function.

I can perform wanted operations inside a data function and retrieve it via `get` but I just wonder if this is the expected behaviour.

## Versions affected:
0.8.x

## Reproduction:
https://jsfiddle.net/95mom81p/4/

## Code:
HTML
```html
<script type="text/html" id="template">
  <h1>Hello {{who}}!</h1>
  <p>
    Click me!
  </p>
  
  <MyComponent/>
</script>

<script type="text/html" id="MyComponent">
  <button on-click="@this.fire('customEvent', event, who)">
    @this.fire
  </button>
  
  <button on-click="customEvent:{{who}}">
    Proxy events
  </button>
</script>

<div id="main"></div>
```

JAVASCRIPT
```javascript
const MyComponent = Ractive.extend({
  template: '#MyComponent',

  data() {
    return {
      myComponent: true,
    }
  }
});

console.info('MyComponent', MyComponent);

const r = window.r = new Ractive({
  el: '#main',
  template: '#template',

  components: {
    MyComponent,
  },

  data: {
    who: 'World'
  },
  oninit() {
    this.on('*.customEvent', (event, param) => {
      console.info(event, param);
      console.info('event.get', event.get(), '\nevent.component', event.component, '\nevent.fire', event.fire, '\n--------');
    });
  },
});
```

**Comment by marcalexiei** [comment]
Another concern. If I have a event listener like:
`this.on('customEvent componentName.customEvent ', (event) => { ... })` at the moment I'm not able to find a way to get component name inside the event handler. 

Using old proxy events, `e.component.component.name` will return the name of the component.

**Comment by ghost** [comment]
Proxy events were deprecated (warning showing in console) because of the strange syntax. Handlers now support (sort of a superset of) expressions, which look like inline JavaScript, for familiarity.

Another is that the event object has been updated to return [`Info`](http://docs.ractivejs.org/latest/instance-getnodeinfo) objects that contain helpers that operate in the context of the node involved in the event. I believe the equivalent to `event.component` is now `event.ractive.component`.

**Comment by marcalexiei** [comment]
Ok, thank you for the clarification.
