### ISSUE TITLE
Understanding "twoway: false" behaviour

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2847]
## Description:

A component with intended usage  (but unintended behaviour) is here: http://jsfiddle.net/kv7xwpfk/7/

Correct behaviour of this component is here: http://jsfiddle.net/uhqchsdc/

How can I make this component be used as intended and behave as intended? 

## Versions affected:

0.8.10

**Comment by ghost** [comment]
When `twoway` is `true`, changes on bound elements mutate the key. When `twoway` is `false`, changes on bound elements are ignored. https://jsfiddle.net/3zbxhk1b/1/

```js

Ractive.components.myInput = Ractive.extend({
  isolated: true,
  template: `
    <h1>myInput: isolated:true</h1>
    <p>Same as test. Since twoway:true, the input can update the model.</p>
  	<div>myInput value (ractive x, test a): <input value="{{value}}" /></div>
  `,
  data: function() {
    value: 'test1'
  }
});

Ractive.components.test = Ractive.extend({
  isolated: true,
  twoway: false,
  template: `
    <h1>test: twoway:false, isolated:true</h1>
    <p>Simply put, it's like ignoring onchange</p>
    <p>Changes to a and b via the input will NOT update the data model thus not re-render anything.</p>
    <p>However, directly updating the data model directly (like via ractive.set) will update and re-render everything</p>
    <div>a (ractive x): {{a}}  <input value="{{a}}"></div>
    <div>b (ractive y): {{b}}  <input value="{{b}}"></div>
    <button on-click="myHandler">Update outside variables!</button>	
    <hr>
		<myInput value="{{a}}"></myInput>
  `,
  oninit: function() {
    this.on({
      myHandler: function() {
        this.set('a', 5); // get value of "a"
        this.set('b', 6); // get value of "b"
        alert("updated x and y!");
      }
    });
  }
});

var ractive = new Ractive({
  el: 'body',
  template: `
  	<h1>ractive: default</h1>
    <p>Changing x and y via input will update the data model, and all downstream bindings</p>
		<div>x: {{x}} <input value="{{x}}"></div>
		<div>y: {{y}} <input value="{{y}}"></div>
    <hr>
		<test a="{{x}}" b="{{y}}"></test>
	`,
  data: {
    x: 11,
    y: 12
  }
});

```

In a bit of a rush atm. Will follow up in a bit. But that's the general idea.

**Comment by ceremcem** [comment]
@fskreuz Thank you. I'm more clear about `twoway` behaviour now. I was thinking `twoway: false` is something we can use to perform a MITM attack between variable assignments (updates), but obviously it's not.

**Comment by evs-chris** [comment]
If you want to get between an input and the setting of its value in either direction, the best way is with a decorator written to do binding. A decorator can be written such that it can consider multiple keypaths when updating the input.

**Comment by ceremcem** [comment]
A-ha! :)
