### ISSUE TITLE
Transition's t.isOutro

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#2852]
## Description:
I believe that we should have a `isOutro` property to be checked during transitions.

It used to be that simply checking `!t.isIntro` was fine, but since 0.8 we can manually trigger transitions using `ractive.transition(transition, node, options)`, thus adding a third case.

```
if (t.isIntro) {
  // intro
} else if (t.isOutro) {
  // outro
} else {
  // ractive.transition(..)
}
```

In the meantime, you can technically check for outros with `t.isIntro === false`, but it's not that intuitive.

```
if (t.isIntro === true) {
  // intro
} else if (t.isIntro === false) {
  // outro
} else {
  // ractive.transition(..)
}
```
## Versions affected:
0.8 and above

**Comment by evs-chris** [comment]
That makes a lot of sense and is a tiny change, so it's in edge now.
