### ISSUE TITLE
[insert site generator here] for consolidated documentation

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2857]
## Description:

Proposal to use [Gitbook](https://www.npmjs.com/package/gitbook) (self-built and self-hosted, not the [hosted version](https://www.gitbook.com/)) to build documentation. If I remember correctly, it's what Redux and friends use. Compared to Read The Docs, it looks cleaner and modern but it loses some important things RTD has like auto ToC generation and versioning.

Thoughts?

**Comment by dagnelies** [comment]
Dunno ...the most important part of ractive's homepage is the tutorial. In would be a pity to loose that and I don't know if it can be integrated in a gitbook. Can it? If not, it'd split the site and the docs, here again I don't know if it's worth it. How is it actually done currently? Is it complicated/difficult to update the docs? (are we actually solving a problem or creating one? 😉  ...I've no idea, just throwing my first thoughts. I remember I corrected a detail on a page long ago and found it fairly intuitive/straightforward to do so. But it was just a detail, some other tasks might be more problematic. Dunno.

**Comment by ghost** [comment]
A sign that the site needs improvement is how recent contributors only contribute typo corrections, but *never an undocumented feature*. `Ractive.DEBUG` (the static one) is a good candidate. It appears in the console every time you use it, but it's *never mentioned anywhere in the site*. If the docs was so easy to contribute to, one can easily make content for that - but no one did, ever.

At the moment:

- The blog is unmaintained, the last post being 3 years ago.
- The example site is text for the most part and probably outdated.
- The main site is just the front page and the 60-second setup.
- The whole site is built with 5 different repos (site, blog, examples, learn, docs)
- They're all built custom and differently.
- And nobody is actively maintaining it (we only update when we remember or someone reminds)

The larger goal I'm trying to grab *is to consolidate the site* and make it (and everything else) contributor friendly. 

- Gitbook solves the build problem by using a dedicated site generator tool that Just Works™ and not care about how it's built *at all*. 
- Consolidating everything means everything is coherent and in one place. It also takes less effort since there's only a few places to take care.

Gitbook is just some random tool I just pitched in. It could be anything really (RTD was a good one, just fugly by default). And I'm not even talking about plugins just yet. That's another story for another time. 😄

**Comment by sarendipitee** [comment]
I'm of the opinion that whomever is willing to put the work in gets to decide how to do it.

All the points @fskreuz made are totally valid and are probably a big part in why Ractive is an unpopular as it is. I'd say go for whatever you think is best and get feedback from us where you need it, if you need it.

**Comment by dagnelies** [comment]
> I'm of the opinion that whomever is willing to put the work in gets to decide how to do it.

...I wholeheartedly agree with that. I think Ractive stands on the shoulders of a handful of people like @evs-chris and you @fskreuz, who are contributing a lot. I doubt it would affect how others contribute. They'd just fix typos and add a couple of lines here and there. However, if it makes *your* life easier, please go ahead and do it.

> All the points @fskreuz made are totally valid and are probably a big part in why Ractive is an unpopular as it is.

IMHO, it has nothing to do with such "technicalities". I think Ractive stays in the background because it's relatively unknown. Plain and simple. It lacks of press coverage and being shown in conferences.

**Comment by paulocoghi** [comment]
Looking specifically at the documentation problem, Gitbook is interesting.

My concern is with http://learn.ractivejs.org and I understand that this is another story as well.

**Comment by ghost** [comment]
Welp, just hit a snag on Gitbook. Apparently [it uses Nunjucks](https://toolchain.gitbook.com/templating/) which has special meaning for `{{ }}`. It could be escaped, but we wouldn't want to be doing `{% raw %}` just about everywhere we use `{{ }}`.

There goes Gitbook 💣 💥  (looks for another tool that gobbles up plain markdown).

---

> My concern is with http://learn.ractivejs.org
> @paulocoghi 

@evs-chris has special plans for that one in the near future.

> it has nothing to do with such "technicalities"
> @dagnelies 

You can get people to know Ractive from a technical point of view. Lowering barriers is one, simplifying the API, making it easy to contribute, having a fully automated workflow, a perfect test coverage, quick turnarounds.

We lack marketing, but we don't really need to have it. Let devs that have good experience using  Ractive spread the word about it. 😄

**Comment by evs-chris** [comment]
I would _like_ to get everything consolidated into one site with interactive demos to go with each docs section. Realistically though, that's a lot of work, and I really suck at docs and narrative. I think it would be great to get all of the docs together and coherent in one place with maybe an option to frame in a Ractive-specific version of jsfiddle-like-thing that we could use for demos and bug reproductions later on. For the most important and immediate part of that, gitbook looks like it would work fairly well. It certainly wouldn't hurt to have ebook/pdf versions of the docs.

Further along those lines, I think we should switch to gh pages for hosting and see if we can switch the domain to ractive.js.org so that we aren't putting all of the hosting/maintenance/site burden on one person (currently @Rich-Harris).

As far as the docs themselves, I'd like to see a landing page with links to a hello world, faqs, migration, a longer walkthrough tutorial of the major concepts, api docs, and plugins. The format of the _docs_ site isn't awful, but the rest of the ractivejs.org properties are way out of date and largely beyond our control at this point.

**Comment by evs-chris** [comment]
@fskreuz it looks like Nunjucks supports swapping out tags, though I don't know if gitbook exposes that functionality as a cursory search didn't yield anything. The current docs use markdown + handlebars, which means we're escaping all of the Ractive code that goes in the docs now. It would be a pretty decent improvement to the current process _not_ to have to do that.

**Comment by ghost** [comment]
> Realistically though, that's a lot of work

Much of the developer-important parts (API, plugins list, integrations) I already cleaned up in the [`rtd` branch](https://github.com/fskreuz/ractive/tree/rtd/docs). I haven't gone through the concepts pages though (named "Under The Hood" in the branch). Shouldn't be that hard to clean up although it's still a lot of pages.

> see if we can switch the domain to ractive.js.org

Was thinking about doing the js.org thing after this one flies. But then, when I looked at Inferno and Vue, both are doing the `${frameworkName}js.org` approach. Since we already have `ractivejs.org`, might as well keep it? 😄 

> The current docs use markdown + handlebars, which means we're escaping all of the Ractive code that goes in the docs now. It would be a pretty decent improvement to the current process not to have to do that.

Yep. The goal is to just write plain Markdown so anyone who knows how to write Markdown can simply jump in without having to worry about weird things.

**Comment by evs-chris** [comment]
Does rtd have a self-hosted option, or is it pretty much a requirement to use readthedocs.org? That was the one of the more attractive things about gitbook - you can self-host.

Switching to ractive.js.org and gh-pages would mean that _everything_ ractive is available on github, which would definitely make maintenance much simpler. I still haven't figured out exactly how ractivejs.org gets published. The link to the cdn really needs to be changed 😆

**Comment by ghost** [comment]
> Does rtd have a self-hosted option

It does, but [requires a lot of Python sorcery](https://docs.readthedocs.io/en/latest/install.html) since it's more than just a static site generator. It's only a "generator" when you use the shared version since they do the build and hosting for you. 😄 

> I still haven't figured out exactly how ractivejs.org gets published.

Appears to use gobble, [builds on travis](https://travis-ci.org/ractivejs/ractivejs.org), but the [`travis.yml` installs and runs Grunt](https://github.com/ractivejs/ractivejs.org/blob/master/.travis.yml) and blows up. Looks like it uses gh-pages tho. 😄

**Comment by paulocoghi** [comment]
Another possible solution: **Grav**
https://learn.getgrav.org/

**Comment by ghost** [comment]
[I just took mkdocs for a spin](http://fskreuz.github.io/ractive/Index/), the thing that runs under the hood of Read The Docs version I made earlier. Not too bad. 

**Pros:**
- Plain markdown-to-site generator.
- Built-in gh-pages deploy tool.
- Built-in search.
- Write in pure markdown.
- Easily integrated into main repo (under `/docs` directory).

**Cons**
- Lacks a good docs theme (although Cinder works fine).
- No versioning.
- Python (will require tweaking of Travis)
- Menu is fixed, not relative. Bad for traversing versions.
- Side-bar is only for in-page heading navigation.

**Comment by ghost** [comment]
Went ahead and:
- Created an org site https://github.com/ractivejs/ractivejs.github.io
    - Org projects become subpages of the org domain.
- Created a PR for `ractive.js.org` https://github.com/js-org/dns.js.org/pull/1053

I'll slowly move over contents from the main site, docs, examples, and within the source into this repo. Then we can decomission those repos and domains so that everything is in one place and the entire workflow is in Github. We won't have to poke @Rich-Harris for domain problems anymore. :smile: 

Feel free to contribute, everything's done in vanilla markdown now.

---

Plugins, prepare yourselves. You're next. :smiling_imp:

**Comment by sarendipitee** [comment]
Do we have a look and feel in mind? I wouldn't mind playing around with some look and feels this weekend if no one has made any headway in that department

**Comment by evs-chris** [comment]
I don't... @fskreuz? I personally think we could use a good redesign, perhaps from the logo up. My designer buddies have forbidden me from trying to be aesthetical (box shadows and rounded corners are not primary design elements, I'm told 😁), so I'd say go nuts.

**Comment by ghost** [comment]
I have no design preferences other than very legible text and easy-to-find pages. So yes, go nuts. :smile:

**Comment by paulocoghi** [comment]
I really enjoy [Laravel's and Lumen's documentation](https://lumen.laravel.com/docs/master) design.

Clean, legible, easy-to-find pages.. **and beautiful**.

**Comment by ghost** [comment]
Closing this issue since... https://ractive.js.org/ is up! 🎉 

The original sites will still be up until everything is polished. The docs structure should be in good enough condition for everyone to start sending in PRs for typos and general writeups.

---

@paulocoghi kinda reminds me of [Ember's docs]( http://emberjs.com/api/) but the text is very small and light tho. [Inferno's docs](https://infernojs.org/docs/guides/installation) is more or less in the same scheme, but with larger text and more white.
