### ISSUE TITLE
Ractive "REPL"

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2861]
## Description:

I'll just throw the idea out there so it won't be lost:

- Looks like [CodePen](https://codepen.io/pen/) (Collapsible HTML, CSS, JS, and output panels).
- Has a console panel like [JSBin](https://codepen.io/pen/).
- Shareable without back-end persistence (like [Buble](http://buble.surge.sh/), [Rollup](http://rollupjs.org/), [Babel](https://babeljs.io/repl/))
- Switch between Ractive versions care of [unpkg](https://unpkg.com/).
- Pretty much like the [learn site](http://learn.ractivejs.org/) but not bound to that functionality.
    - It could be the other way around, the learn site uses this tool.
- Gives an IDE feel, full screen-ish and not 4 small panels.

**Comment by evs-chris** [comment]
https://ractive.js.org/playground/#N4IgFiBcoM5Q2iA9EgrgOwA4GsDmA6AYwHsBbJAJwENCAXASwDcBTAAWYBNdmQBdAXwA0IWlBAAeDkwAE9DgF4AOiFJV66ZQD5xSKY02L04mIQr1MtabQCemZkpHMAHrSRhapADbLZC5bUxvEAMNWnEwACZNAAlmT09iQWlgYAB3MGJ+fgBCHUiQnRMzC00QYThIEFT1DmJU-AppeWl0ZlTpACUaBhYACmBDRVpaKgpuWkhpAHIAYlV1KcFB4eZSQKpaZknZgM9F5Y4NqkmB0KH04m2AdWIKTw4p5f5DfgBKMpBCMQAjYg5rZLLABmxHQtAAtECqKR6J5rJMYFR0DBwTBmGYgQBuF6DdCRQGhTYucFUTz0XDoSaEZhg9HY9D8ED8IA

I'mma call this one done enough 😄.
