### ISSUE TITLE
typo in doc for attachChild(), and clarification question

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2863]
## Description:
http://docs.ractivejs.org/edge/ractive-attachchild has a typo:

> When a child is attached targeting an anchor, only anchors that belong directly to the parent are considered as hosts. However, **and** element or component queries on the parent instance

The word `and`, bolded by me, is probably meant to be `any`.

Also, it may just be me, but I can't really tell what this function does in the case of two independent Ractive instances where one is "attached" to the other with this function.  What actually happens once I do that?  

This sentence says what it does, but it is too compressed for me to know the implications:

> When a child is attached to a parent, the child's parent property is updated in an observable way, so any references to @this.parent in the child will be notified of the change.

Does that mean that **only** `@this.parent` is useful in the child's template, or does it mean also that the template can refer to any of the parent's model properties, e.g. `@this.parent.foo`?  

Sorry in advance if that was meant to be obvious!

## Versions affected:
Edge

**Comment by ghost** [comment]
See https://github.com/ractivejs/ractive/issues/2864#issuecomment-278208457

**Comment by Jeff17Robbins** [comment]
I can't even find `.attachChild()` over on the new site.  Not sure what I  am supposed to do now.

**Comment by evs-chris** [comment]
The docs in both places are very much a work in progress, but ractive.js.org will be taking over, so please file any omissions or issues you come across over there. We'll probably get the bulk of the missing stuff soon, but I'm an awful typist so there's bound to be plenty of stuff to fix in whatever docs I write 😁

**Comment by Jeff17Robbins** [comment]
While I wouldn't dare produce any fresh material (because I'm not confident
I understand it all!), I really enjoy editing.  So...if you have any
material you want me to edit, let me know an efficient way for me to do
so.  I tend to spot typos pretty easily.

**Comment by ghost** [comment]
Well, you're in luck! The whole of https://github.com/ractivejs/ractivejs.github.io is open for proof-reading, editing and whatever can make it better! PRs are highly encouraged. 😄

**Comment by Jeff17Robbins** [comment]
ok, don't yell at me, but I don't know how to do a "PR".  Assuming I can
master the workflow, happy to take a pass at the documentation.

**Comment by evs-chris** [comment]
PRs are actually pretty easy to do. The basics are:
1. fork the repo
2. clone your fork to your local machine
3. make changes, commit, and push to your fork
4. go to your fork on github and there will be a button above the file list to create a PR
5. fill in the details and click submit
6. ???
7. Profit!

**Comment by Jeff17Robbins** [comment]
Sounds feasible, thanks.  What software do I need on my Windows  10 machine to make this happen?

**Comment by ghost** [comment]
You'll only need:
- [Git for Windows](https://git-scm.com/download/win)
- An editor with EditorConfig and Markdown plugins. I recommend [VS Code](https://code.visualstudio.com/). 
    - You can configure VS Code's terminal to use the Bash that comes with Git for Windows.

VS Code has a built-in Markdown preview (`Ctrl + K, V`) to view the rendered document, which should be sufficient since the documentation is entirely in Markdown. Optionally, if you want to run the full site locally, install Python, pip and virtualenv. Refer to their respective docs for their installation.

**Comment by Jeff17Robbins** [comment]
Thanks!  Snowed-in today in Boston, so a perfect time to try this out.

**Comment by evs-chris** [comment]
For the second question about the parent ref, yes, it is updated and you can use it in references as if it were a component.
