### ISSUE TITLE
http://docs.ractivejs.org/edge/ractive-set still mentions the "change" event

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2864]
## Description:
http://docs.ractivejs.org/edge/ractive-set
> A change event will be fired with keypath and value as arguments (or map, if you set multiple options at once).

This might be a nice spot for a pointer to `.observe()` as the replacement for the `change` event.  Also, the doc for `.observe()` needs updating with the `links` option, and the new recursive pattern `**`.

## Versions affected:
Edge

**Comment by ghost** [comment]
The docs are currently being moved to a new site https://ractive.js.org/. The repo is also separate as well, at https://github.com/ractivejs/ractivejs.github.io. Might want to file this issue on that repo if it still exists there.

**Comment by Jeff17Robbins** [comment]
It is still an issue over there on the new site.  Also, the "Instance methods" left-hand vertical menu isn't scrollable for me, so it was hard to get down to `.set()`...I scrolled down through the right-hand content to reach it.

**Comment by kouts** [comment]
+1 @Jeff17Robbins  I confirm that left menu at https://ractive.js.org/ is not scrolling when its height exceeds screen height.

**Comment by evs-chris** [comment]
The left-hand menu should now scroll when necessary.
