### ISSUE TITLE
0.8.10 - Ractive.getNodeInfo returns undefined on root element

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2865]
I'm trying to get an Ractive instance from another instance only by knowing it's element id.
I tried Ractive.getNodeInfo but it returns undefined.
I'm probably missing something very obvious here, here is the fiddle:
http://jsfiddle.net/qgrszcg2/8/

**Comment by ghost** [comment]
Not sure if it's a bug. `#my_test` is not part of the Ractive instance. It's merely where the instance was placed. So Ractive isn't aware about it.

In [this demo](https://jsfiddle.net/qgrszcg2/10/), I included a span which is part of the Ractive template, and used `Ractive.getNodeInfo` on that.

**Comment by kouts** [comment]
Yes @fskreuz I think that you are right, so is there any way to get the Ractive instance only by knowing
the element that Ractive was placed?
I noticed now there is an ```__ractive_instances__``` array inside the element, maybe the first item on this array is always the instance, but can I rely on that?

**Comment by ghost** [comment]
If you're pretty sure an element contains an instance, then querying the children of the element should be a viable solution. However, you still need to wrap it in an element, since text nodes don't really provide anything. https://jsfiddle.net/qgrszcg2/13/

**Comment by kouts** [comment]
Thanks @fskreuz , the instance will only contain ractive components inside so I can't do that but it's nice to know.

**Comment by evs-chris** [comment]
If there's more than one ractive instance, you can't really get the node info from it. As long as you don't use `append: true` when targeting that element, then there will only be one instance. `__ractive_instances__` is not going to change, but it's also not public API. #2868 will add an official path for getting a context from a host node.

**Comment by kouts** [comment]
Thanks @evs-chris,  will this propagate to 0.8.10 also?

**Comment by evs-chris** [comment]
Most likely not because the node info objects in 0.8 require an element where that PR makes a bunch of changes to get them to the point that they don't.
