### ISSUE TITLE
Ractive re-using different components? Or, stopping unnecessary observer calls.

### ISSUE THREAD

**Issue by sarendipitee** [ractivejs/ractive#2867]
## Description:

In a somewhat complicated scenario (actually a simplified version of the app I'm [currently working on](https://demo.novo.cloud)), components are still calling observers as they are being torn down. Or, they're not being torn down? 

When switching between the dashboards with the buttons, all of the `foo` components get switched out with `bar` components. In the process, each foo's observer for `value` gets called. This is strange to me, because these components should be on the way out. Why call the observer?

This is a problem because the `value` observer in `foo` and `bar` components simulates an observer in my app that does a huge amount of work and network calls when the component loads, so it's really not ideal that the observer gets called when the components gets torn down. 

## Versions affected:

0.9.10

## Platforms affected:
Chrome 55
## Reproduction:

https://jsfiddle.net/zx19h4sf/

## Code:

```js

const foo = Ractive.extend({
  template: `foo: value={{value}}`,
  oninit() {
     this.observe('value', value => {
        console.log('foo value changed');
     })
  },
  teardown() {
      _super();
  		console.log('foo teardown');
  }
})

const bar = Ractive.extend({
  template: `bar: value={{value}}`,
  oninit() {
     this.observe('value', value => {
        console.log('bar value changed');
     })
  },
  teardown() {
      _super();
  		console.log('bar teardown');
  }
})

new Ractive({
  el: 'app',
  data: {
    active: 0,
    cardPartialFor(type) {
        return this.cards[type];
    },
    dashboards: [
    	{
       cards: [
         {type: 'foo', value: 1},
         {type: 'foo', value: 2},
         {type: 'foo', value: 3},
       ]
      },
      {
       cards: [
         {type: 'bar', value: 7},
         {type: 'bar', value: 8},
         {type: 'bar', value: 9},
       ]
      }
    ]
  },
  components: {
    foo, bar
  },
  template: `
    Active Dashboard: {{active}} —
    Show {{#dashboards}}
    <button on-click='set("active", @index)'>dashboard {{@index}}</button>
    {{/}}
    <hr/>
    {{#with dashboards[active]}}
      {{#.cards}}
          {{> card}}
       {{/}}
   {{/with}}
  `,
  cards: {
    foo: Ractive.parse(`<foo value='{{.value}}'></foo>`),
    bar: Ractive.parse(`<bar value='{{.value}}'></bar>`),
  },
  partials: {
  		card: `
      <div class='card'>
          {{> cardPartialFor(.type) this}}
      </div>
      `,
  },

})


```

**Comment by evs-chris** [comment]
This is one of those chicken-and-egg scenarios that exists because the context (and therefore value) of the component is changing and subsequently causing the component to unrender. Observers happen before vdom updates by default, so the observer sees the value change along with the context and fires. Then the component gets notified that its services are no longer necessary and it gets torn down along with its observers.

To avoid firing observers that are dependent on vdom like that, you can flag them as deferred e.g. `this.observe('...', () => ..., { defer: true })`. There's also `{ init: false }` to keep them from immediately firing when they are subscribed. https://jsfiddle.net/zx19h4sf/1/

**Comment by sarendipitee** [comment]
Oh ok awesome. I wouldn't have thought deferring it like that would work since in my mind the observer should already have been canceled, but I can see how that works now. Thanks!
