### ISSUE TITLE
ractivejs.org is down (503 Service Unavailable)

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2879]
Hi,

I guess you're working on it guys ...just wanted to let you know in case you didn't.

Next time, it'd be nice to place a page "Under construction / we're updating" or something like this  ;)

**Comment by evs-chris** [comment]
Actually we're not 😄, The hosting for ractivejs.org has been flaky lately, so we're working on transitioning to github pages and js.org hosting at ractive.js.org.

**Comment by dagnelies** [comment]
how is hosted actually?

**Comment by evs-chris** [comment]
I'm not _entirely_ sure, which is one of the reasons we're working on the transition, but I think parts of it are on one of Rich's droplets and other parts on surge.sh.

**Comment by dagnelies** [comment]
technology is indeed complicated and diversified ...even for hosting. I hope @Rich-Harris, that you can help out a little here to shed some light.

**Comment by evs-chris** [comment]
It appears to be back, so I'm going to close this. The goal is to have the switch to ractive.js.org ready for 0.9 release, which should be happening pretty soon - hopefully within a few weeks.
