### ISSUE TITLE
Which of the deploy scripts are currently in use

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2881]
## Description:

So I found 3 scripts related to deployment:

- `deploy-edge-to-cdn.sh`
- `release.sh`
- `travis-deploy.sh`

Of the 3, only `travis-deploy.sh` is called by Travis. What are the other 2 for? Can they be removed if `travis-deploy.sh` already does everything? I'm not super-confident in my bash-reading skills, so I though I'd ask.

**Comment by evs-chris** [comment]
`deploy-edge-to-cdn.sh` is the original (for me) Travis script that targeted `cdn.ractivejs.org`. `release.sh` is what I wrote to make deployment easier when I started releasing 0.8 patches, then used to get the process for automated publishing sorted out, and finally what `travis-deploy.sh` is based on. The Travis deployment script seems to be stable enough that the others can safely go. You could leave `release.sh` sitting around as `manual-release.sh` if you wanted to in case Travis ever decides to be entirely uncooperative.

**Comment by ghost** [comment]
Are we still using `cdn.ractivejs.org` or can we drop that since we're on unpkg?

**Comment by evs-chris** [comment]
Yes, I think the cdn was last updated around 0.8.1. I tried to get ractivejs.org updated to show unpkg rather than the cdn, but you see how well that went 😄.
