### ISSUE TITLE
Question: Ractive in ReactNative Environment

### ISSUE THREAD

**Issue by copongcopong** [ractivejs/ractive#2886]
I attempted to use Ractive (via npm) in a ReactNative project attempting to just use its observable and data handing features, however it didn't work out of the box like it should for a node.js environment;

Is there a way for me to create a version of Ractive that is vdom free,  just using https://github.com/ractivejs/ractive/tree/dev/src/model

I know this a bit silly but I've been accustomed with how Ractive handles observable data and I can't help it! :)

**Comment by ghost** [comment]
> it didn't work out of the box like it should for a node.js environment

Ractive should (in theory) work in Node.js. However, it's not its primary use case so this feature is pretty much overlooked (as seen by the number of Node.js tests present compared to browser tests).

I'm also not sure what you mean by "vdom free" and just using models. If you can share to us how you use Ractive, we might look into this use case. A sample app or demo would suffice.

**Comment by copongcopong** [comment]
@fskreuz vdom-free, for me with by the how ractive handle the "data" attribute on initialization and all data-related functionality, such as .observe .set .get

ReactNative is a different environment with Node.js it could be that it is emulating the `window` global object, where in Ractive tries to check; 

The ReactNative error was `Can't find variable document` at line 97

```
var doc = win ? document : null;
```

**Comment by evs-chris** [comment]
Ractive definitely works in a plain node environment, as that's how server-side rendering is accomplished. If you manually change the `doc` assignment from `var doc = win ? document : null` to `var doc = win ? win.document : null` does it still break?

**Comment by copongcopong** [comment]
I think forcing `var win = null` will do the trick for Ractive to think that it is a Node environment;

**Comment by copongcopong** [comment]
yup, from my tests, forcing `win = null` did the trick;

**Comment by copongcopong** [comment]
Here is what I found out going through this experiment:

ReactNative appears to be emulating a `window` global object, making Ractive browser-environment detection to be triggered.

Possible Fix: Have a "real" non-browser environment of Ractive (without `window` object detection) like `Ractive = require('ractive-node');`

 OR 

simply ignore this since It is only I who is using it in an environment (ReactNative) that is really not designed to be in :)

**Comment by evs-chris** [comment]
Does this build work? [ractive.js.txt](https://github.com/ractivejs/ractive/files/789238/ractive.js.txt)

**Comment by copongcopong** [comment]
@evs-chris nope, that build didn't work;
