### ISSUE TITLE
"Cannot set read-only computed value" exception if a computed property returns undefined

### ISSUE THREAD

**Issue by smoldaner** [ractivejs/ractive#2888]
## Description:
If a computed value returns undefined, ractive tries to update the computed value. 

## Versions affected:
0.8.11 and edge

## Platforms affected:
All

## Reproduction:

To reproduce, use the code below or this fiddle: https://jsfiddle.net/w3yk7j93/1/

### HTML

    <script type="text/html" id="template">
        <propertyValidation valid="{{cvalid}}" />
    </script>
    
    <div id="main"></div>

### JS
	var propertyValidation = Ractive.extend({
		lazy: true,
		template: "{{>content}}",
		data: function () {
			return {
				valid: true
			}
		}
	});

	var r = window.r = new Ractive({
		el: '#main',
		template: '#template',
		components: {propertyValidation: propertyValidation},
		data: {prop: {}},
		computed: {
			cvalid: function () {
				return undefined;
			}
		}
	});

**Comment by ghost** [comment]
Hello! Please add the necessary information in this issue (code, steps to reproduce, etc.), not just the jsfiddle. Should jsfiddle go down, this thread won't be. 😄

**Comment by smoldaner** [comment]
Missing information added

**Comment by evs-chris** [comment]
This was an issue with the mapping init logic not checking for a readonly source model. It has been fixed in edge and v0.8-dev and will go out with 0.8.12 when it is cut. Thanks for the report!
