### ISSUE TITLE
Template parsing breaks if section starts with closing html tag

### ISSUE THREAD

**Issue by Djemo** [ractivejs/ractive#2891]
## Code:

```
{{#surround}}
<p>From here</p>
<div class='surrounded'>
{{/surround}}
<p>You can't surround us!</p>
{{#surround}}
</div>
<p>to here!</p>
{{/surround}}
```

**Comment by paulocoghi** [comment]
Every code inside a section must be valid. This is not possible.

**Comment by Djemo** [comment]
@paulocoghi Is there any other way to get what I need in this case. To be specific I'm trying to envelop or not part of my template code depending on variable, like 'surround' in example.

**Comment by ghost** [comment]
Ahh, this. Unfortunately this is not possible in Ractive. Ractive is not concatenating template strings like you would in Mustache. It parses the template to a tree and your template would look like this to the parser:

```xml
<surround>
  <p>From here</p>
  <div class='surrounded'></div>
</surround>
<p>You can't surround us!</p>
<surround>
  </div> <!-- A wild div closer has appeared -->
  <p>to here!</p>
</surround>
```

What you could do is to put the content in a partial, and conditionally render with and without the enclosure.

```xml
{{#partial surroundedContent}}
  <p>You can't surround us!</p>
{{/partial}}

{{#if surround}}
  <p>From here</p>
  <div class="surrounded">
    {{> surroundedContent }}
  </div>
  <p>to here!</p>
{{else}}
  {{> surroundedContent}}
{{/if}}
```

**Comment by Djemo** [comment]
@fskreuz Yup, did exactly that. Didn't hurt too much either.
