### ISSUE TITLE
"Using a non-POJO as the root object may work, but is discouraged”

### ISSUE THREAD

**Issue by clarkd** [ractivejs/ractive#2892]
We're looking at using Typescript along with Ractive to help bring more structure to our codebase. 

Ideally we'd want to use a strongly-typed Typescript object for the data but Ractive throws a warning:

> If supplied, options.data should be a plain JavaScript object - using a non-POJO as the root object may work, but is discouraged”

Why is this discouraged?

**Comment by ghost** [comment]
Ractive only knows about objects and arrays - this pretty much sums it up. It isn't aware about the intricacies of your non-POJO object like accessors, private/pseudo-private members, language-specific features etc.. It _may_ work if Ractive can add, read, modify or remove properties/values to it like a POJO.

For non-POJO objects, we recommend reading about [Adaptors](https://ractive.js.org/Extend/Adaptors/). It's essentially a translation layer between Ractive and your non-POJO object so you can take advantage of your non-POJO features.

**Comment by evs-chris** [comment]
Ractive treats the root object as a dictionary, and at certain times may 'reset' it in a way that can blow up if it isn't a pojo. You can set any of the data below the root object as custom classes and you will probably not have any issues unless there are read-only props that get set out other things like that.

It's also not possible to have an adapted root object for many of the same reasons that custom classes are strongly discouraged as root data.
