### ISSUE TITLE
Child components will update parent data

### ISSUE THREAD

**Issue by nemtsov** [ractivejs/ractive#2897]
## Description:

A child component setting data with the same name as the parent will also update parent's data.

## Versions affected:

`0.7.3`

## Reproduction:

```html
<div id='container'></div>
```

```js
const SubComponent = Ractive.extend({
  template: `{{progress}}`,
  data() {
    return {
      progress: 0
    };
  },
  oncomplete() {
    this.set('progress', 100);
  }
});

const ractive = new Ractive({
  el: '#container',
  template: `
    <div>PARENT: {{progress}}</div>
    <div>CHILD: <SubComponent progress={{progress}}></SubComponent></div>
  `,
  components: {
    SubComponent
  },
  data: {
    progress: 0
  }
});
```

Output:
```text
PARENT: 100
CHILD: 100
```

**Comment by ghost** [comment]
Unless I'm missing something, this is intended behavior.

- You have `progress` on the parent.
- You have `progress` on the child.
- `progress` on the parent is mapped to `progress` on the child when you did:

    ```
    <SubComponent progress={{progress}}></SubComponent>
    ```
Therefore any changes to either parent or child will reflect on the other and any other mappings using either.

To clarify what's really going on, [I'll rename the child data](https://jsfiddle.net/7zhmkcad/).

```
const SubComponent = Ractive.extend({
  template: `{{value}}`,
  data() {
    return {
      value: 0
    };
  },
  oncomplete() {
    this.set('value', 100);
  }
});

const ractive = new Ractive({
  el: 'body',
  template: `
    <div>PARENT: {{progress}}</div>
    <div>CHILD: <SubComponent value={{progress}}></SubComponent></div>
  `,
  components: {
    SubComponent
  },
  data: {
    progress: 0
  }
});
```

The only time it works is [if you remove the mapping](https://jsfiddle.net/0g4cbuan/). That way, `progress` of the parent has no connection to the `progress` of the child:

```
const SubComponent = Ractive.extend({
  template: `{{progress}}`,
  data() {
    return {
      progress: 0
    };
  },
  oncomplete() {
    this.set('progress', 100);
  }
});

const ractive = new Ractive({
  el: 'body',
  template: `
    <div>PARENT: {{progress}}</div>
    <div>CHILD: <SubComponent></SubComponent></div>
  `,
  components: {
    SubComponent
  },
  data: {
    progress: 0
  }
});
```

**Comment by evs-chris** [comment]
Since there's currently no good way to just pass data in to a component without creating a mapping, perhaps we should lean on a static interpolator to handle that e.g. `<component nonMapped=[[some.path]] mapped={{other.path}} />`. Does that sound reasonable?

Right now, interpolators are not checked for the static flag when doing mapping, which seems like a bug to me.

**Comment by dagnelies** [comment]
IMHO it's perfectly fine like it is. A two-way mapping looks ideal to me, and I've never seen use cases where it's undesired. ...there are also workarounds, like copying the variable during component initialization. Adding non-mapped bindings appear to me like an unnecessary source of complexity.

**Comment by paulocoghi** [comment]
I totally agree with @dagnelies
