### ISSUE TITLE
ractive.animate() optional complete callback only passed one argument

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2900]
## Description:
`ractive.animate()` optional `complete` callback only passed one argument (apparently the destination value), but the documentation says `...to be called when the animation completes, with the same argument signature as `step` (i.e. t is 1, and value is the destination value)`
## Versions affected:
https://unpkg.com/ractive@edge
## Platforms affected:
Windows 10 Chrome Version 56.0.2924.87
## Reproduction:
https://jsfiddle.net/po1bg8yg/

## Code:
`HTML`
```
<script src="https://unpkg.com/ractive@edge"></script>
<script id="template" type="text/ractive">
  <span id="sprite" style="left: {{left}}px">
  hi
  </span>
</script>

<div id="container">
</div>
```

`CSS`
```
#sprite {
  background-color: green;
  color: white;
  font-size: 24px;
  position: relative;
}
```
`JavaScript`
```
var r = new Ractive({
  el: '#container',
  template: '#template',
  data: {
    left: 0
  }
});

r.animate('left', 400, {
  duration: 2000,
  step: function(t, v) {
    console.log('step', t, v);
  },
  complete: function(t, v) {
    console.log('complete', t, v);
  }
});
```

**Comment by evs-chris** [comment]
I'd say the docs are wrong in this case. It doesn't make much sense to me to send a time code `1` indicating that stepping is complete for a function that only fires on complete. I _do_ think that the promise returned by animate should resolve with the final value rather than `undefined`, though.
