### ISSUE TITLE
Question: how can sub component templates inherit from base component templates?

### ISSUE THREAD

**Issue by arxpoetica** [ractivejs/ractive#2907]
Question: how can sub component templates inherit from base component templates?

Is it possible to create sub templates for sub components? I don't know if this is possible, but sometimes when I use `.extend(...)` to make a sub component, I want to inherit the parent template, and add to it for another `extend` down the line. Oh the web we weave, but imagine a sub-sub-component that inherits two templates.

I realize this is what partials and dependency injection are for, but I can't seem to get that to work the way I'm imagining it. Maybe the docs just aren't clear enough?

Here's an example of what I'm trying to do that doesn't actually work: https://jsfiddle.net/langbert/msqfsqg8/

Note the line in the jsfiddle that says "uncomment this"

Relevant code from the fiddle:

```html
<script type="text/html" id="Layout">
	<div class="container">
    <BaseComponent></BaseComponent>
    <SubComponent></SubComponent>
  </div>
</script>
<script type="text/html" id="BaseComponent">
	<h1>I am the {{which}} component.</h1> 
</script>
<script type="text/html" id="SubComponent">
	...this would inherit from BaseComponent and add it's own stuff somehow? {{yield}}? {{>partial}}?
</script>
<div id="main"></div>
```

```js
Ractive.components.BaseComponent = Ractive.extend({
	template: '#BaseComponent',
	data: function() { return { which: 'base' } },
})
Ractive.components.SubComponent = Ractive.components.BaseComponent.extend({
	// template: '#SubComponent', // <<<<<< uncomment this line...it doesn't inherit anything, it just overrides :( sad face
	data: function() { return { which: 'sub' } },
})
new Ractive({
	el: '#main',
  template: '#Layout',
})
```

**Comment by evs-chris** [comment]
The only option I can think of that's available right now would be to leave extension points in the super template as partials. https://jsfiddle.net/msqfsqg8/3/ I still usually end up with copy-pasta though, for the sake of simplicity.

We could probably set up template functions such that they could reference their super template in some way, like perhaps to set it up as a partial e.g.

```js
Ractive.extend({
  template(super?) {
    this.partials.super = super?.template;
    return 'wrapped around {{>super}} my super template';
  }
});
```

**Comment by ghost** [comment]
This is more of an architectural problem than a feature problem. I've been down this road once before, the "I want a base modal component which I can subclass to modal subcomponents which looks the same but a bit different". Wasn't long before I dumped the idea.

> ...this would inherit from BaseComponent and add it's own stuff somehow? {{yield}}? {{>partial}}?

The "somehow" was where I was stuck. How do you _extend_ templates? And how do you do it without making the entire architecture brittle, where changing the base component doesn't break the subcomponents? Can this be done without inheritance to begin with.

In fact, it can be done with composition, something components do really nicely. Just break down the features you want into smaller, more generic components that can be shared. [Here's a minimal example of how I eventually did it](https://jsfiddle.net/thc5w04j/1/).


```
// Smaller, common parts of the modal
Ractive.components.ModalHeader = Ractive.extend({
  template: `
    <div class="modal__header">{{ title }}</div>
  `,
    data: () => ({
    title: ''
  })
});

Ractive.components.ModalContent = Ractive.extend({
  template: `
    <div class="modal__content">{{ content }}</div>
  `,
    data: () => ({
    content: ''
  })
});

Ractive.components.ModalFooter = Ractive.extend({
  template: `
    <div class="modal__footer">
      <button type="button" on-click="okclicked">OK</button>
    </div>
  `
});

// The modals

const ModalA = Ractive.extend({
  template: `
    <div class="modal">
      <ModalHeader title="Hello World!" />
      <ModalContent content="Lorem ipsum dolor sit amet, consectetur adipiscing elit." />
    </div>
  `
});

const ModalB = Ractive.extend({
  template: `
    <div class="modal">
      <ModalHeader title="Foo Bar Baz" />
      <ModalContent content="The quick brown fox jumps over the lazy dog" />
      <ModalFooter on-okclicked="@this.okHandler()" />
    </div>
  `,
  okHandler(){
    alert('ok was clicked')
  }
});

// Instances

new ModalA({ el: 'body', append: true });
new ModalB({ el: 'body', append: true });
```

**Comment by ghost** [comment]
There's also [named yields](https://ractive.js.org/Extend/Components/#yield). [This situation](https://github.com/ractivejs/ractive/issues/1317) was exactly one of the reasons why I requested the feature (thanks to @evs-chris for implementation 👍 ).

Your component could position named yields on the template. This would allow instances to define what goes into those positions in the same way how other templating languages define overridable blocks (Django does `{% block %} {% endblock %}`).

[Taken straight from the docs:](https://ractive.js.org/Extend/Components/#yield)

```
Ractive.components.ChildComponent = Ractive.extend({
  template: `
    <div class="child-component">
      {{ yield }}
      {{ yield italicYield }}
      {{ yield boldYield }}
    </div>
  `
});

const ractive = new Ractive({
  el: 'body',
  data: {
    message: 'Hello World!'
  },
  template: `
    <div class="ractive">
      <ChildComponent message="Lorem Ipsum">
        {{#partial italicYield }}<em>{{message}}</em>{{/}}
        {{#partial boldYield }}<strong>{{message}}</strong>{{/}}
        {{message}}
      </ChildComponent>
    </div>
  `
});
```

**Comment by arxpoetica** [comment]
So I'd tried using partials from one child to a parent, and wasn't having luck, but I think I figured out what I was doing wrong, so that will probably work for what I need. Thanks!
