### ISSUE TITLE
avoid observer notification for specific cases (question)

### ISSUE THREAD

**Issue by dakairus** [ractivejs/ractive#2908]
Version: 0.7.x
Description: I'm looking for a way when I use Ractive.set('keypath', value) to avoid the notification to observers for specific situation:
Example: 
- var1 change, because of a user change
- observer catch change and perform ajax http call to save
- save succeed, but the save event in backend add more information to var1 (backend validation rules and calculations)
- update var1 with the server response for save event
- because this update will go to step1 and cause a infinite loop.

**Comment by ghost** [comment]
It depends on how you're setting the data and how you're observing the keypath. A demo of the situation would be nice to have. 😉 

Anyways, by default, observers will fire for changes under an object even if you didn't change the object itself. In 0.8, [`ractive.observe`](https://ractive.js.org/API/Instance%20Methods/#ractiveobserve) accepts a `strict` option which changes how it determines when the handler fires. Set it to `true` and the observer will not fire if the object whose properties were modified is still the same object.

For 0.7, I would suggest making the observer pattern more specific, avoiding the use of a pattern that listens to everything.

---

<small>The new docs site is under development. Formatting issues exist at the moment.</small>

**Comment by evs-chris** [comment]
For 0.7, the easiest thing to do is add a lock variable to the scope containing the callbacks for the observer and server update. The when the server is updating the data, set the lock and only fire the data to the server from the observer if the lock is not set.

With 0.9, you can silence and resume observers, and there is also a hook to allow a deep comparison.

**Comment by dakairus** [comment]
Thanks, for your response guys. I handled the situation referencing the observer to a variable and cancelling the observer when I needed. Here a little example for anyone using Ractive 0.7 and need to sort this.
```
function observerFunction(newVal, oldVal, node) {
console.log('do something on observe');
}
var observer = component.observe('someVariable', observerFunction);
```

Then during the server transaction:

```
$.get('some/url', function(err, data, response) {
observer.cancel();
component.set('someVariable', data.someVariable);
observer = component.observe('someVariable', observerFunction);
})
