### ISSUE TITLE
Rename or remove Blog link from site

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2909]
Hi all,

I think the Blog might hurt Ractive' reputation a bit.  When I navigate to a new framework with a Blog link I generally go there and if entries are a couple of years old I assume the project is either mature or inactive. In Ractive' case it is still under active development so I think the wrong message might be sent out.  And devs do not tend to think in terms of mature, but rather dead or irrelevant ;-)

Suggestions:
1. remove the link completely, but there is some useful info there
2. remove the dates from the entries
3. change the link description from Blog to Articles (still removing the dates)

**Comment by ghost** [comment]
The docs site is [currently being reworked](https://ractive.js.org/) (Argh! Typos and formatting errors abound!) to consolidate all documentation. Part of that would be removing the blog, or at least merge those posts into documentation as part of a framework comparison section. 😄 

The site is split across repos at the moment, so to do this on the existing setup will need a bit of hunting. We'll get to it when we can. 😄

**Comment by sabob** [comment]
Thanks, wasn't aware of the site revamp.
Just quick feedback to whomever is working on it: There are many improvements to the current site, eg better highlighting of example snippets, and moving concepts into menus.

I'm not sure I like the way the docs have been split up. I prefer all the docs in one place like the old site with a sidebar to link to all the material. Easy to search for what I'm looking for. With the new menu layout I have to "know" where to go in order to find what I'm looking for or navigate around the menus to get to all the docos.

But that gripe aside good work on the new site!

**Comment by ghost** [comment]
To compensate for that, there's now a search functionality (should be on the navbar somewhere). 😄

**Comment by ghost** [comment]
Closing. Refer to the docs issue referencing this thread for future tracking. 😄
