### ISSUE TITLE
Setting data in component in code.

### ISSUE THREAD

**Issue by Worthaboutapig** [ractivejs/ractive#2910]
## Description:
How do I set the (non-trivial) `data` of a component in code?  In order to create the component, I extend `Ractive`, however, with any actual 'real' object, I get a warning 
`Passing a `data` option with object and array properties to Ractive.extend() is discouraged, as mutating them is likely to cause bugs. Consider using a data function instead`.

Firstly, this message appears when the data is wrapped as a function (see fiddle), so there seems to be a bug there.

Secondly, my use-case is a self-contained component with data set once.  I don't want to access data from a parent, I want the component to set its own data.  How do I do this without acquiring the above warning?

## Versions affected:
v0.8.11

## Platforms affected:
Any

## Reproduction:
https://jsfiddle.net/worthaboutapig/7d3z2gfb/

**Comment by ghost** [comment]
The warning comes from your `Car1` component. Its `data` isn't wrapped around a function. [Wrapping it](https://jsfiddle.net/5uvozw7v/) would remove the warning.

[The reason behind this warning](https://ractive.js.org/API/Initialization%20Options/#data) is that object literals as `data` tells Ractive to attach the data on the prototype (a form of data sharing, like vanilla JS prototypes) while functions as `data` tells Ractive to call that function and whatever it returns, assign it to the instance (data on a per-instance basis).

If you can do ES6, arrow functions are a neat way to remove the verbosity of function data.

```
const Component = Ractive.extend({
  // Regular data:
  data: {
    message: 'Hello World!'
  },

  // Function as data
  data: function(){
    return {
      message: 'Hello World!'
    }
  },

  // Arrow function as data
  data: () => ({
    message: 'Hello World!'
  });
});
```
