### ISSUE TITLE
Travis not able to publish

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2911]
## Description:

Not sure what happened here. Just [merging this PR](https://github.com/ractivejs/ractive/pull/2901) like normal when this happened. The PR didn't change any of the `secure` things tho.

## Versions affected:

dev

## Reproduction:

https://travis-ci.org/ractivejs/ractive/builds/209964279

## Code:

```
publishing as unstable edge build to npm...
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.10.0/bin/node" "/home/travis/.nvm/versions/node/v6.10.0/bin/npm" "publish" "--tag" "v0.9-dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

**Comment by ghost** [comment]
Took a shot in the dark and added `NPM_TOKEN` to Travis, to no avail. 

Found [an older build](https://travis-ci.org/ractivejs/ractive/builds/175270447) that had encountered this error, and [a follow-up build](https://travis-ci.org/ractivejs/ractive/jobs/175271197) that made it work or at least got past the auth error. The fix appears to be adding an encrypted variable, but I don't know what it contains.

Thoughts @evs-chris ?

**Comment by evs-chris** [comment]
So it turns out that running npm with auth via an npm script was the issue. I'd _guess_ that npm strips out the auth env variables to prevent accidental leakage when you use run-script. Seems to be ok now though.

**Comment by ghost** [comment]
🤦‍♂️ A big "today I learned" moment for me. 😄  Thanks for the fix.
