### ISSUE TITLE
Ractive.isInstance

### ISSUE THREAD

**Issue by rockerest** [ractivejs/ractive#2914]
## Description:

In some cases, it's useful to be able to determine if a variable contains a Ractive instance.  
In these situations, it's not possible to _simply_ *and* _functionally_ test the value without indirect smoke tests against the current public API *or* using the pseudo-OO `instanceof` operator.  

It would be nice to provide another static method on the Ractive library that will officially determine whether a value is an instance of Ractive or not in a way that fits the functional programming paradigm (which is ostensibly "supported" by Ractive's ability to construct without the `new` operator).

Ideally, this method would check a (new) property of the instance (extended from the parent chain) that declares explicitly that it is an instance. However, another option may be digging into the base constructor and reading the `name`/`VERSION` properties. However, this is again just smoke testing and hoping for the best.

I'd be happy to create and submit a PR for this if this is something that would be desirable to have in the Ractive library.

## Versions affected:

All, as far as I know.

## Platforms affected:

All, as far as I know.

## Reproduction:

https://jsfiddle.net/rockerest/Lw5ygoc7/1/

## Code:

```
Ractive.DEBUG = false;

var myinstance = new Ractive( {} );

console.log( myinstance instanceof Ractive ); // true, but undesirable syntax
console.log( typeof myinstance ); // object
console.log( myinstance.toString() ); // [object Object]
console.log( Ractive.isPrototypeOf( myinstance ) ); // false
// console.log( Ractive.isInstance( myinstance ) ); // TypeError: Ractive.isInstance is not a function
// console.log( Ractive.isRactive( myinstance ) ); // TypeError: Ractive.isRactive is not a function

```

**Comment by ghost** [comment]
It wouldn't hurt to have this function. A PR is very welcome too. 😄

**Comment by rockerest** [comment]
I'm going to take a deeper look into the codebase soon, but I wanted to see if you / other contributors had any preference on the method of checking.

I'll probably just default to a simple `maybeRactive instanceof Ractive` internally, unless that doesn't fit the internal style (despite mentioning the explicit property above, I think `instanceof` is probably more effective long-term).  

Other concerns would be making sure this is robust into the future (I think it should be?).

Let me know your thoughts or preferences. I won't get to work on this until probably next week.

**Comment by MartinKolarik** [comment]
This is a good chance to also add `Ractive[Symbol.toStringTag] = 'Ractive'` if Symbols are available and check for that in `Ractive.isInstance()` (again, only in addition to instanceof, if Symbols are available). Instanceof checks don't work in every case and debugging problems this causes is usually very painful.

**Comment by ghost** [comment]
I think `instanceof` has quirks when identifying objects from different frames (i.e. `Ractive` from host, object from frame or vice versa).

**Comment by MartinKolarik** [comment]
@fskreuz exactly.

**Comment by rockerest** [comment]
I'd also like to add a test for a Component. I suspect this should not be within `isInstance` or if it is, the method should be named something like `isRactive`.

The only test I've discovered for a Component (that doesn't construct the component, which seems really inadvisable) is this:

```
function isRactiveComponent( maybeComponent ){
    var isFunc = typeof maybeComponent == "function";
    var isComponent = isFunc ? Ractive.prototype == maybeComponent.prototype.__proto__ : false;

    return isComponent;
}
```

I'd like to hear thoughts on also testing for a Ractive component, whether it would also be useful, the best way to do so (better than the above, I hope), and where that might be placed in the Ractive library if it's deemed useful.

**Comment by evs-chris** [comment]
We're already leaning on `instanceof` in [the extend code](https://github.com/ractivejs/ractive/blob/dev/src/extend/_extend.js), so perhaps `extend` should add another static method `isInstance(target) { return target instanceof Target /* && maybe include Ractive.isInstance too? */; }` to the constructor when it sets it up. I don't know that there's a good way to throw a symbol check for components too, but I think the `Ractive.isInstance` method _should_ do that when possible. That _should_ net:

```js
const Cmp1 = Ractive.extend();
const Cmp2 = Cmp1.extend();
const Other = Ractive.extend();

const cmp = new Cmp2();

Cmp1.isInstance(cmp) === true;
Cmp2.isInstance(cmp) === true;
Ractive.isInstance(cmp) === true;
Other.isInstance(cmp) === false;
Ractive.isInstance({}) === false;
```

**Comment by rockerest** [comment]
Just wanted to leave an update here:

I've been extremely busy in the day job, so I haven't had a chance to work on this.
It's still on my radar, but I can't promise timely results right now.

**Comment by ghost** [comment]
> I've been extremely busy in the day job

Take your time. No rush 😄
