### ISSUE TITLE
Moving observers, events and methods to its own hash

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2926]
I think I've requested something similar before but I'd like everyone's idea on this:

```js
const MyComponent({
  ...otherInitOptions,
  observers: {
    'foo.bar.baz': function(){ ... }
  },
  events: {
    'namespace.event': function(){ ... }
  },
  props: {
    anInstanceProp: true
  },
  // Alternatively, similar to data, with built-in auto-merge:
  props: props => ({
    anInstanceProp: true
  }),
  methods: {
    'myMethod': function(){ ... }
  }
});
```

Motivation:

1. Explicitly define props and methods of the instance. I find it hard on first glance when looking at a component definition which of the properties are legit config or were added by another dev. It would be nice if everything on the initialization object to be just initialization options.

2. Future-proofing the addition of new initialization options (as if we don't have enough 😄 ) 

    > Extra properties passed as options that are not initialization options are added as properties or methods of the instance.

    This would inevitably cause collisions when adding new initialization options, particularly ones that are very generically named. Again, all in the name of just having config on the init options.

3. It would be nice to add observers and handlers without having to write all the `oninit` boilerplate.

    ```js
    const Component = Ractive.extend({
      // sooo boilerplate-y
      oninit: function(){
        this.observe('foo.bar.baz', function(n, o){ ... });
        this.observe('foo.bar.qux', function(n, o){ ... });
        this.on('event1', function(e){ ... });
        this.on('event2', function(e){ ... });
      },
      // less fluff
      observers: {
        foo.bar.baz: function(n, v){...},
        foo.bar.qux: function(n, v){...}
      },
      events: {
        event1: function(e){ ... },
        event2: function(e){ ... }
      }
    });
    ```

4. Props would pave the way for separation of props and state. Not sure how the syntax would be like on the template, but I'd imagine on the API

    ```js
    const Component = Ractive.extend({
      data: () => ({ defaultData: true }),
      props: () => ({ defaultProp: true })
    });

    const ractive = Component({
      data: () => ({ defaultData: false }),
      props: () => ({ defaultProp: false })
    });
    ```

I think backwards compat for `on` and `observe` will remain since they're both instance methods anyways (still accessible from anywhere that has the instance as context), but I'm leaning towards removing the "merge non-config to instance" bit.

Thoughts?

**Comment by evs-chris** [comment]
I think being explicit about adding members wouldn't be a bad idea, but I think I'd prefer to keep properties and methods together (since methods are just function properties?). There's also #2006 for the same thing but static rather than instance methods. It doesn't really bother me to have to add static methods after extending the component, though.

Are you counting the existing `on` and `observe` init hashes in 0.9 for events and observers?

One thing I've thought could be useful to add to those would be a way to make listening on the root instance easier. For instance, if your component wanted to listen to all `xhr.loading`/`xhr.done` events, it could subscribe to the that event on the root instance at init. Having support for that sort of thing would automatically tear down the listener with the component rather than requiring an init and destruct/render and unrender set of listeners. That may be a little too special-cased though.

**Comment by ghost** [comment]
> Are you counting the existing on and observe init hashes in 0.9 for events and observers?

Nope. Was just putting out the idea for feedback. It's more of an organization/aesthetics thing, no immediate need. If it comes with extra perks (faster code, better process), even better. 😄

**Comment by dagnelies** [comment]
Just reading it now. Simply put: 👍 😉 

> Are you counting the existing on and observe init hashes in 0.9 for events and observers?

What are you reffering to?

**Comment by evs-chris** [comment]
> What are you reffering to?

As of 0.9, you can subscribe events and observers with a hash as init options:

```js
new Ractive({
  on: {
    someevent(ctx) { ... },
    other() { ... }
  },
  observe: {
    'some.path.to.observe'(v) { ... }
  }
});
```

There are some more options regarding how to set up the listeners and observers - see the changelog for more details. You can also subscribe any lifecycle events that take place after `construct`, and both hashes are additive if you use `Ractive.extend`.

**Comment by dagnelies** [comment]
Oh, great! So it's already there, nice. :)
