### ISSUE TITLE
Is there a Slack channel or anything?

### ISSUE THREAD

**Issue by Worthaboutapig** [ractivejs/ractive#2927]
## Description:
A/A.  Where does one chat, or just ask questions and what not, without raising a bunch of 'issues' which are more likely issues I have, rather than the ractive code has ;)

**Comment by evs-chris** [comment]
Twitter is more or less it, but it's not so great for detailed conversations. I've created a slack channel at ractivejs.slack.com to see how that works out. There's also a gitter, but it seems harder to monitor.

**Comment by Worthaboutapig** [comment]
Thanks... how do I get an invite? :)

**Comment by evs-chris** [comment]
I suppose send an email to my username without the hyphen at gmail and I can add you. I've not used slack before, so it's a bit experimental. @fskreuz can I make you an admin as well?

**Comment by Worthaboutapig** [comment]
Done.

**Comment by kouts** [comment]
@evs-chris  I sent for invite too :)

**Comment by evs-chris** [comment]
To be clear, at gmail, I'm evschris 😃. It seems that any member can invite others by default, which seems reasonable.

Just gonna ping a few more ractive regulars off the top of my head in case they're interested @JonDum @aharpervc @dagnelies @Jeff17Robbins @andreujuanc @brakmic @TehShrike

**Comment by Worthaboutapig** [comment]
That's where I sent it. :)

When it's set up, perhaps it can be added onto the homepage markdown asap, so other people will know it's there in future after this is closed.

**Comment by Jeff17Robbins** [comment]
@paulie4  might be interested (and hopefully will explain to me what I need to do?!  😃)

**Comment by dagnelies** [comment]
What about this:

https://gitter.im/

I think it's quite neat for github based communities.

**Comment by Worthaboutapig** [comment]
@dagnelies Whatever has a consensus, I don't mind... there's millions of these chat things.

**Comment by andreujuanc** [comment]
I can see people already googlin' "slack vs gitter" xD

**Comment by evs-chris** [comment]
I was probably doing something wrong, but my issue with gitter was lack of notifications. So far, slack seems to be quite good at making monitoring easy.

**Comment by ghost** [comment]
I recommend asking questions on Github tho. That way, it's sort of "written in stone" and anyone stumbling across the same problem can just ask Github or [insert your favorite search engine] and be pointed back to the same issue.

For lengthy discussions or casual talk, a chat room wouldn't be that bad.

---

> can I make you an admin as well?

@evs-chris yep.

**Comment by paulocoghi** [comment]
+1 for Gitter : https://gitter.im/ractivejs/ractive

Its notifications have worked perfectly for me.

**Comment by evs-chris** [comment]
So it turns out that I hadn't actually managed to "join" the Ractive gitter 🤣. Since its barrier to entry is much lower, I think I'll point a chat link to the gitter, but I'll still watch the slack channel for those who prefer it.
