### ISSUE TITLE
I am puzzled about references in a loop

### ISSUE THREAD

**Issue by dodyg** [ractivejs/ractive#2928]
## Description:
I am forced to use root reference for comments and I don't understand why. There are no ```comments``` property inside the loop.

```
    $.when(getTBS, getComments).done(function (data1, data2) {
        const plan: Payloads.Single<Payloads.TechnicalBasePlan> = data1[0]
        const comments: Payloads.Many<Payloads.DocumentComment[]> = data2[0]

        const tbs = new Plan({
            el: '#technical_base_plan',
            oncomplete: function () {
                C.loadingIndicator('hide')
            }
        })

        tbs.set('plan', plan.item)
        tbs.set('comments', [1,2])

    })

var Plan = Ractive.extend(
    {
        oninit: function () {
            const self = this
        },
        template: `
    {{#each plan.sections as section}}
        <Section section={{section}} financialMetrics={{plan.financialMetrics}} projectId={{plan.projectId}} comments={{~/comments}} />
    {{/each}}
`,
        components: {
            Section: Section
        }
    })
```
## Versions affected:
0.8.3

**Comment by ghost** [comment]
We'll need a bit more context and a demo. [From what I understand](https://jsfiddle.net/dmnx0cL1/), the root reference shouldn't be necessary.

```js
const Component = Ractive.extend({
  data: () => ({
    obj1: {
      arr1: []
    },
    arr2: []
  }),
  template: `
    {{#each obj1.arr1 as arr}}
      <div>{{message}}</div>
      <div>{{ JSON.stringify(arr2) }}</div>
    {{/each}}
  `
});

const App = Ractive({
  components: { Component },
  el: 'body',
  data: () => ({
    obj1: {
      arr1: [
      	{ message: 'Hello' },
        { message: 'World' }
      ]
    },
    arr2: ['foo', 'bar', 'baz']
  }),
  template: `
    <Component obj1="{{ obj1 }}" arr2="{{ arr2 }}" />
  `
});

```

**Comment by dodyg** [comment]
https://jsfiddle.net/wvowx98d/1/ 

If you remove the root reference at arr2, it will fail to work.

**Comment by evs-chris** [comment]
It looks like the issue is that the component has an `arr2`, which means that each component gets its own empty value at its local `~/arr2` keypath. When you create the mapping for `arr2` on each component, you're effectively symlinking the a new `arr2` over each component's local keypath to point to the one on the `App` instance. Is `arr2` supposed to live on the `App` or the `Component`?

Slightly re-arranged, the mapping isn't necessary for non-isolated components: https://jsfiddle.net/wvowx98d/1/

**Comment by dodyg** [comment]
Does every single value to be used inside a component needs to be initialized on `oninit` ?

In many cases I just create a component and perform `com.set('key', value)` without setting default value for 'key' inside `oninit`.

**Comment by paulocoghi** [comment]
> Does every single value to be used inside a component needs to be initialized on `oninit` ?

No, it doesn't.

**Comment by ghost** [comment]
> Does every single value to be used inside a component needs to be initialized on `oninit` ?

It's not required. Also, if you _do_ want to set default values for your component attributes, you can set them using the `data` initialization option. You don't need to set it manually in `oninit`.

```js
const Component = Ractive.extend({
  // Defaults
  data: {
    foo: 'Hello',
    bar: 'World!'
  },
  template: `
    {{foo}} {{bar}}
  `
});

// Renders "Hello Alice!"
Ractive({
  components: { Component },
  template: `
    <!-- set value for foo -->
    <Component bar="Alice!"/>
  `
});
```

**Comment by dodyg** [comment]
Then I don't understand why in my sample ```comment``` has to be rooted.

**Comment by evs-chris** [comment]
If the component isn't isolated, which they are by default as of 0.9, then mappings may get made if you don't have data initialized at init. Basically, when mappings and non-isolated components are involved, you need to initialize data that you _don't_ want to get mapped.
