### ISSUE TITLE
One more lil' plugin ;)

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2931]
Hi,

since the main site was on the move how it is hosted/edited, I wasn't sure it was the right place, but I added a lil plugin here:

https://github.com/ractivejs/docs.ractivejs.org/pull/279

Is it still the right way to update the docs?

**Comment by ghost** [comment]
We're moving the docs over to https://ractive.js.org/ soon. The repo can be found at https://github.com/ractivejs/ractivejs.github.io . It's now hosted on Github Pages and uses a js.org subdomain.

This page is where it should be at https://ractive.js.org/integrations/plugins/ which should be on this file https://github.com/ractivejs/ractivejs.github.io/blob/dev/docs/integrations/plugins.md.

**Comment by ghost** [comment]
Should be available in https://ractive.js.org/integrations/plugins/ momentarily. 👍
