### ISSUE TITLE
@global binding not updated on ractive.update

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2932]
## Description:

While writing an example for `@global` two-way binding, I notice that changing the global outside of Ractive and calling `ractive.update()`, the instance isn't updated to the new value.

I might be blind staring at the screen all day or just using it wrong. Wouldn't hurt to ask for another pair of eyes to take a look. 🤓 

## Reproduction:

https://ractive.js.org/playground/#N4IgFiBcoE5QdgVwDbIL4BoQBcogDwDOAxjAJYAO2ABITMQLwA6422FhkA9F4vBQGsA5gDpiAewC2XGAENi2MgDcApiwB8+LiXJV1ILITwB3MvAAm44yMkrChWUJXUG1AOQAJFanHUA6uIwyOYAhG5M8BEASvKKqgAUwBFM2N6Q7gBG4uYAnm4YydiyFBQqFunYMIgqBZFsKpIUyLKp6QAGhSn4ZhSINNg5pcw4KgAe2CzUSrLI1cPAwNQAAkLI4hkzNnYOTtRoaBqd2PgZfdji8NQDQyynbBeTFwC0xMhkxALDS9hgZIQiayEURUADMVDAysQVPEAJQaAAy4iE1AhYIh8ChUxm1S0d3O8HURxOZwuV0GKmGeIeIGoz1e70+LG+v3+gIA4msNshYQikdRVusZljZipcSSCUSqZdrhTbuLHvAXm8Pl8fn8RIQVNgAGLicQAIVkMENAC8eSB1ABhMCyeC7c7UFggvXUDYwV2yE2TcxkCEKZA5MX3CV1LpSsk3EBShVKhmqlkiRAUcwtaFwi2W5UCK6+JMp1JB-GE0MTEv4cTIYspavHN5WrOOkCI5Go8GQ5zTEWTW3mahrcTZlpXMDOCTwQgV0VcOtHLp1zMMxvN-mcoWd6rdix9vWD-oj6hjifIKczktzshWm125w-Zw9PrC6rUHsolSlIeEVIcagARmfW4AJi0U8a3PetFxYa1bXtXw3GdXw3Q9E03GoH0-WwAMWGAi9Z1rC9gXfGhPzfQhf3-XsAPI6h4HERRMR+D8vzI4xZFImiaFkFiIVpEFh2cNCVAUA8rycbCqwmCT8HnBtIIbB081TLDpxws88PUAiVEYkiyJfSiX3Y94bxtGgsh+Wgv1Io1nBo4xny4k8VJrLQK3EtpahSQFgTRdtYSSEtD0nAEkXiNV-icbB4jcFZV2QLZ7EcFQ3BhOE6kwQp2Ri3yjgC48gqEeJTAsKw4p2FQYQAbkKNK6k1HU9UNY1PSyktCssaxbHi3ZXCdF1EI2L0QCqiI0AqkA0CAA

## Code:

```js
window.message = 'Hello World!'

Ractive({
  el: 'body',
  append: true,
  template: `
    <input type="text" value="{{ @global.message }}">
    <button type="button" on-click="@this.logReference()">Log reference value</button>
    <button type="button" on-click="@this.logGlobal()">Log global value</button>
    <button type="button" on-click="@this.setFooBarBaz()">Change to "foo bar baz" directly</button>
    <button type="button" on-click="@this.update()">Click to update</button>
    
    <ol>
      <li>Click "Log reference value" and look at the console</li>
      <li>Click "Log global value" and look at the console</li>
      <li>Change the input value and repeat steps 1 and 2</li>
      <li>Click "Change to 'foo bar baz' directly"</li>
      <li>Repeat steps 1 and 2 and notice that step 1 was not aware of the direct change</li>
      <li>Click "Click to update"</li>
      <li>Repeat steps 1 and 2 and notice that both steps are now aware</li>
    </ol>
  `,
  logReference(){
    console.log(this.get('@global.message'))
  },
  logGlobal(){
    console.log(window.message);
  },
  setFooBarBaz(){
    window.message = "foo bar baz"
  }
});
```

**Comment by ghost** [comment]
So it looks like only a blank `ractive.update()` doesn't work. But specifying the keypath does.

**Comment by evs-chris** [comment]
That actually seems like _mostly_ reasonable behavior to me. I wouldn't really expect any old `update` to touch `@global` and `@shared` refs in other instances. If it needs to be changed, we'll just need to update `update` to include those special keypaths. I lean towards requiring explicit updates (`ractive.update('@global')`), though, because the next logical step is `@this`, and that's another can of worms.

**Comment by ghost** [comment]
If it's expected behavior, it's ok by me. I'll just update `ractive.update` to make note of that. 👍
