### ISSUE TITLE
Replace 'isArray' polyfill with Array.isArray()

### ISSUE THREAD

**Issue by Worthaboutapig** [ractivejs/ractive#2934]
## Description:
Currently we have this:

    var toString = Object.prototype.toString;
    // thanks, http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/
    function isArray ( thing ) {
      return toString.call( thing ) === '[object Array]';
    }

However, is there a reason the native `Array.isArray()` isn't used?  It would appear that other features (e.g. `Object.keys`) are used which appear in the same spec and are supported after `Object.keys` (at least according to MDN (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/keys#Specifications vs. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray)

I wonder, as Array.isArray has been the correct way for a while, and the toString() hack is prone to problems.  Basically I have an array (as defined by Array.isArray() and created from var `array = [];`, which Ractive doesn't think is an array, because, for some reason, the toString() is iterating the toString on each item in the array and returning the toString() on that... I don't know why this is happening, it's not on another array, which should be being created in an identical way.  Hopefully I can find out what's causing a different toString() results.. but the point stands. Is there a reason not to use `Array.isArray()`?

## Versions affected:
v0.8.11 (and presumably all others)

## Platforms affected:
All

**Comment by ghost** [comment]
Are you referring to https://github.com/ractivejs/ractive/blob/0.8/src/utils/is.js#L5? If so, [that's already gone in the dev branch](https://github.com/ractivejs/ractive/blob/dev/src/utils/is.js) (the upcoming 0.9). The core library will be using native APIs where possible. A separate [polyfill file](https://github.com/ractivejs/ractive/blob/dev/src/polyfills.js) is made available for legacy browser support.

> because, for some reason, the toString() is iterating the toString on each item in the array and returning the toString() on that

Better check if any of your other libraries is mutating `Array.prototype.toString()`. To do that on Chrome, simply put `Array.prototype.toString` (or that specific array's `toString` if not globally, i.e. `thatarray.toString`). If the output isn't `function slice() { [native code] }`, right click on the output and select "Show function definition". It should lead you to the code that changed `toString`.

I'm certain to a degree Ractive isn't responsible for this. If it is, it's a bug. :)

**Comment by Worthaboutapig** [comment]
That looks like it, yes, I was looking at the released code for v0.8.11.  Ok, it's going, that's great :)

I didn't think it was Ractive's code, :) I could see there was something wrong in mine, and I've tracked it down to setting the prototype to Array.prototype, which then screws up the prototype for all arrays...  I'm quite fortunate here that it showed up with the `toString()` test; otherwise who knows how long until I'd notice this bug!
