### ISSUE TITLE
Documentation should be cleaned up

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2936]
We should make the documentation complete: 

- [ ] Links should match with each other: CDN addresses differ between pages
- [ ] Every item should contain an interactive example (jsfiddle or inline)
- [ ] Every concept (like plugins) should contain a full and up-to-date example (plugin template is 2 years old)

I prefer Ractive above other UI libraries because any johnny-come-lately may adopt an on-going project in no time. He or she only has to know Javascript and HTML and a couple of hours to look into documentation to get up and running because Mustache is very clear to understand. 

But if documentation is not good, then all these benefits vanish. 

It's been 3 years I'm using Ractive, but I have never been able to use a plugin, or transition, animation. Same reason.

**Comment by ghost** [comment]
Yep, we're on it. https://ractive.js.org/ And it will go out with 0.9.

With regard to your items:

- The CDN links there are updated.
- Under Extend, each type of plugin should have a very minimal structure which one can start with. Might need a bit of polish but should suffice.
- @evs-chris also created [playground](https://ractive.js.org/playground/). Sort of a jsbin for Ractive that can also be embedded in the docs (see page source on how they're embedded).

Of the 3, I think interactive examples for each would be the big one. Also, [feel free to contribute](https://github.com/ractivejs/ractivejs.github.io) to the docs or spot errors. I stare at the screen all day, I might miss a few typos here and there. 😄

**Comment by ghost** [comment]
I'll just close this one. Stuff is tracked at https://github.com/ractivejs/ractivejs.github.io/issues/29
