### ISSUE TITLE
Question: Add method(s) to main ractive instance and not components

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2940]
If I want to add a method to all Ractive instances I'm using
```
Ractive.prototype.myMethod= function(){
    return 'Something';
}
```
But what if I wanted to add this method only to "main" Ractive instances (i.e not components)?
How can I achieve this?

I have many methods in my components that are not needed but they exist there because I've added them to the prototype. I'm thinking that there may be a performance penalty or is this negligible?

**Comment by ghost** [comment]
Ractive uses prototypal inheritance as the mode of inheritance, regular prototype rules apply. So if you add it to the `Ractive` prototype, it gets inherited by all who stem from that prototype.

What you could do is create a separate constructor that nobody is inheriting, attach your custom stuff there, and  use that constructor in place of `Ractive`. Anything on the config object that's not an initialization option becomes properties of the instance.

```js
const CustomConstructor = Ractive.extend({ /* custom stuff */ });

// Just so you know, Ractive.defaults (or constructor.defaults) is an alias for the constructor prototype
// https://github.com/ractivejs/ractive/blob/dev/src/Ractive.js#L37
CustomConstructor.defaults = { /* custom stuff */ };

new CustomConstructor({ ... });
```

Alternatively, you can just mix your custom stuff on initialization. Again, anything on the config object that's not an initialization option becomes properties of the instance.

```js
const CustomStuffMixin = { /* stuff */ }

new Ractive(Object.assign({
  el: '...',
  template: '...'
}, CustomStuffMixin));

// If you are able to do object spread
new Ractive({
  ...CustomStuffMixin,
  el: '...',
  template: '...'
});
```

**Comment by kouts** [comment]
The only option I have right now is to add the method to the main Ractive instance upon initialization.
This way it will only propagate to the main Ractive instance and not to components.
The other part of the question is: Do I have a performance impact if I'm adding methods to the prototype even if they are not used.

**Comment by ghost** [comment]
Nope. There shouldn't be.
