### ISSUE TITLE
getNodeInfo() retrieves wrong keypath after Ractive.splice()

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#2941]
## Description:
`getNodeInfo()` returns the wrong keypath after moving an object in my data structure from one specific point to another using `Ractive.splice()`. 

## Versions affected:
0.8.10 - 0.8.13-edge
not affected: 0.8.9 and earlier versions

## Reproduction:
http://jsfiddle.net/lejared/jmov2t55/9/

In the demo the object with id "a10" is removed from it's array with splice and than inserted in the parent's object's array right before "a4" when the button is pressed.

After this operation `getNodeInfo()` returns the wrong keypath for node "a11".

This bug only happens if I move an object from inside of "a5" right before "a5". Works fine if item is moved after "a5".

**Comment by evs-chris** [comment]
This is now fixed in v0.8-dev and edge and will go out with 0.8.13 when it is cut. Thanks for the report!
