### ISSUE TITLE
class-* attributes toggling not working as per the documentation (0.9.x)

### ISSUE THREAD

**Issue by mpowell-atomic** [ractivejs/ractive#2946]
Hi. I've noticed this when I've been testing my apps on 0.9x recently. Thanks!

## Description:
class-* attributes toggling not working as per the documentation here:
[https://ractive.js.org/api/attributes/#class-](https://ractive.js.org/api/attributes/#class-)

I get this error in the browser console:
```ParseError: Expected matching quote '"' at line 1 character 17: <div class-foo="{{ isFoo }}">Adds "foo" if isFoo</div>```

## Versions affected:
@edge (0.9.0-build-123 and other earlier 0.9.x builds)

## Reproduction:
[Example code on Ractive Playgrounds](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiAIYAOT9AfAQPQmlsg4BneJ07kwuXEwGQRMBgGNcZBADoAVgJUB7GCk7Ni+iTGIAjAK64EAzgGJ5AGwYCBAWloA7Tx4QB3cgBKCkqkCAAUwJ60Egy6CLiQ5ADktsxMSVhRuEgMuAyJkV640cQCAGJaWom4MOYIWdhZVgC2TE5WiUlEZOSOzm4AZpV0IMDAlOWV5BgY7ACCSEgC5PRDWvSUAxMVWlw8bEmeGACUANz8IPLwPOSF0fJaDjqJMMinR1EeKmu3WQ9PMESKFeCA87w8GEwQA)

## Code:
```js
new Ractive({
  target: '#app',
  data: {
    isFoo: true
  },
  template: '<div class-foo="{{ isFoo }}">Adds "foo" if isFoo</div>'
});

**Comment by ghost** [comment]
It looks like `class-*` values _are_ evaluated as expressions. Removing the `{{ }}` works. The tests [appear to support that claim](https://github.com/ractivejs/ractive/blob/dev/tests/helpers/samples/render.js#L1328). Either this is a code bug (and the `{{ }}` stays) or a documentation bbug (and the `{{ }}`) goes away.

**Comment by evs-chris** [comment]
It's a docs bug. This was caused by applying some consistency to the last weird parts of mustaches. Basically, if it's a string (style directive, interpolator) or in a string context, it requires mustaches. If it's a value or expression (event directive, decorator, class directive boolean, expression in a block, etc) it's already in expression context and doesn't require mustaches.

**Comment by ghost** [comment]
Changes will be up momentarily.

**Comment by mpowell-atomic** [comment]
Thanks! Yeah, i figured out what I needed to update but then the docs confused me! :-) Just wanted to make sure which one was correct. Glad it's updated now. Thanks again.
