### ISSUE TITLE
minor bug in .update()

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2948]
## Description:
Ractive edge (0.9+) `.update()` has a new, optional `options` object arg.  But the code for the new option expects there will be an initial `keypath` argument, which is not required.  Crash results if you pass solely the `options` object to `.update()`
## Versions affected:
0.9+
## Reproduction:
https://jsfiddle.net/2whue794/
## Code:
```html
<script src='https://unpkg.com/ractive@0.9.0-build-123'></script>

<div id="container"></div>

<script id="template" type="text/template">
  {{#val}}
  value: {{k1}}
  {{/}}
</script>

```
```javascript
var r = new Ractive({
  target: "#container",
  template: "#template"
});

var cache = {val: {k1: 17}};
r.reset(cache);

cache.val.k1 = 5;

r.update(); // works

r.update({force: true}); // crashes

```

**Comment by evs-chris** [comment]
This is now fixed on edge. Thanks for the report!
