### ISSUE TITLE
Build Ractive on Windows 

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2951]
## Description:

Ractive's build experience on Windows (at least Windows 10) seems to have improved over the years. Following the Contributing.md page, I can do most of the npm commands in package.json without downloading the dependencies on that page such as, a "real shell" and Python.

Then the page notes the command: 

> npm run build:local

 which depends on a real script environment for Windows. 

However, as far as I can tell, the two most important commands for hacking Ractive is:

>npm run dev:browser

 for development (is this the command  everyone uses to hack on Ractive? It runs the tests at location:4567/tests) and

> npm run bundle:release

 for a release.

Both ran without any issue or external dependencies.

Perhaps contributing.md should put less emphasis on the external dependencies which raises the barrier to entry. It seems unnecessary for the primary use cases which is dev and build.

Instead we can highlight the above mentioned commands to develop and build Ractive.

On the other hand, it is quite possible I could be missing something.

## Versions affected:
edge

## Platforms affected:
Windows 10

**Comment by ghost** [comment]
> On the other hand, it is quite possible I could be missing something.

Some of the dependencies use [gyp](https://github.com/nodejs/node-gyp), which requires external native compilers to be present to work (gyp does not come with them). If you have Visual Studio (Win) or XCode (OSX), these compilers are installed along with the IDE. However, not all devs use these IDEs so these tools may not be present. When dependencies that require gyp compile without these tools, they emit very cryptic errors. You'll wonder why you have C errors in a JS project.

So it's important to highlight these dependencies up front. We just might need to reword "might require" to something like "You may not need it. But if it spews errors, you probably need it."

**Comment by evs-chris** [comment]
At one point, one of our dev dependencies required a native module to be built and installed for file watches. That's where the python and native build tools requirements came from. If that's no longer the case, those can certainly be removed.

Perhaps a TL;DR at the top of the file would be helpful?

```sh
# In an sh environment, run these commands to get started:
git clone https://github.com/ractivejs/ractive.git
cd ractive
npm install
npm run dev:browser
```

**Comment by ghost** [comment]
Here's the link to [gyp's installation requirements](https://github.com/nodejs/node-gyp#installation). There was one point in time that their readme was outdated. Took some trial-and-error phase to get it to work on my setup which I wouldn't want to do again. 😄

**Comment by sabob** [comment]
@fskreuz Yes, gyp used to be the issue on Windows. Where is it currently used in the Ractive build process?

@evs-chris We can also add

> #to build a distribution run
> npm run bundle:release
> #The .build folder contains the different Ractive distributions

**Comment by ghost** [comment]
I think gobble used to have a dependency on something that used gyp. Just tried redownloading dependencies and it doesn't appear to be there anymore. If this is the case, we can remove it. 👍

**Comment by ghost** [comment]
I have update CONTRIBUTING.md to highlight the unavailability of the `build:*` and `release:*` shorthand scripts when using Windows Command Prompt because they use shell scripts and that the `build:*` ones is just comprised of a bunch of CLI commands that don't need a real shell.

Also remove the additional softwares section. Looks like Gobble got rid of the gyp dependency and xvfb is probably something advanced enough a developer needing it should already know they need it.

Hopefully the wording is clear, otherwise I'm open to improvements.

**Comment by MartinKolarik** [comment]
If anyone is interested in making all scripts fully portable, [ShellJS](http://documentup.com/shelljs/shelljs) is an excellent tool for that.
