### ISSUE TITLE
Conditional  class-* attribute throws error when used on SVG elements

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#2955]
## Description:
Conditional class-* attribute throws error when used on SVG elements

## Versions affected:
0.8.12

## Reproduction:
https://jsfiddle.net/lejared/4oqxjvnk/1/

## code
` <rect x="0" y="0" width="100" height="100" class-red="{{active}}" />`
results in _TypeError: str.split is not a function_

**Comment by ghost** [comment]
Today I learned: SVGs have special objects as values for animateable attributes. Bug happens because Ractive expects a string but SVG returns this object.

https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString

**Comment by evs-chris** [comment]
Eeesh. That's not very pretty, but it's now patched around in v0.8-dev and edge. The fix will go out with 0.8.13 when it's cut.

Thanks for the report!
