### ISSUE TITLE
Component anchor tag format

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2957]
## Description:
I don't normally use components but started looking at attachChild and friends (awesome feature btw).

I had a hickup with the <#anchor/> tag in that the component would not render until I figured out that there must be a space before the closing tag:

<#myComp/> #works

<#myComp /> #doesn't work if space before closing tag "/>"

Ractive tests for attachChild also adds a space before closing.

Would this be considered a bug?

## Versions affected:
edge

**Comment by sabob** [comment]
Fiddle is [here](https://jsfiddle.net/sabob/mygdmrzv/). Didn't notice at first but closing without a space throws a parse error. Check in console.

**Comment by evs-chris** [comment]
Anchors allow relaxed names like partials, only they _shouldn't_ allow `/` like partials. It's fixed now. Thanks!
