### ISSUE TITLE
Component atachChild insertAt:0 not working if another component is already present

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2958]
## Description:

instance.AttachChild("components", {insertAt: 0}) only works for the first component. Subsequent insertsAt calls behave similar to "append:true".

In attachChild.js#33 is this line:
const idx = options.prepend ? 0 : options.insertAt || list.length;

If there is already a component present, this line at runtime looks like:
const idx = undefined ? 0 : 0 || 1;
idx == 1 #true

This part is the problem: "0 || 1". The 0, which is the insertAt value, evaluates to false in JS.

We can replace the ternary operator with an "if" to fix the issue.

On a related note, would a option {replace: true} make sense for attachChild? It will probably act as an alias for insertAt: 0. Perhaps just me, but replace as a default option, instead of append. feels like the more common use case? 

## Versions affected:
edge

**Comment by ghost** [comment]
Can we have a demo for debugging purposes?

**Comment by sabob** [comment]
Fiddle is [here](https://jsfiddle.net/sabob/4kLbxmbt/2/)

**Comment by sabob** [comment]
Can we use the playground instead of jsfiddle for demos? 
https://ractive.js.org/playground/

**Comment by evs-chris** [comment]
That's what it's there for :smile:

**Comment by evs-chris** [comment]
There is a `prepend: true` that worked even before this was fixed. I'm not sure which case is more common, because I only have two so far - one of each.

**Comment by sabob** [comment]
I'm curious about how append/prepend should work, since only one of the components can be rendered at a time correct? So we can attach a number of components to an anchor, but I fail to see what happens next. Do we detach a child so that the next one can render? Or is this simply infrastructure for future use cases?

**Comment by evs-chris** [comment]
You can actually specify the same anchor name more than once e.g. `<#anchor/><#anchor/>` or put them in an each `{{#each list}}<#anchor/>{{/each}}`. Instances are rendered in their corresponding anchor by index. There's a builtin list of children so that you can generate anchors for each attached child by name: `{{#each @.children.byName.anchor}}<#anchor/>{{/each}}`, where ractive keeps the list updated in an observable way.

**Comment by sabob** [comment]
Oh right, multiple anchors... got it :)
{replace: true} wouldn't make sense then.
