### ISSUE TITLE
Cannot read property 'deferredObservers' of undefined

### ISSUE THREAD

**Issue by Minstel** [ractivejs/ractive#2960]
## Description:
Error is thrown in a pretty strange case that is shown in a fiddle, when assigning second observer.
## Versions affected:
at least 0.9.0-build-117 and upper
## Platforms affected:
Chrome 57.0.2987.133
## Reproduction:
https://jsfiddle.net/h0vzjpeb/4/
## Code:
```
var RactiveCustom = Ractive.extend({
    oninit: function() {
        this.observe('*', function() {
            this.set('foo', 'Here');
        }, {defer: true});
        
        this.observe('*', function() {}, {defer: true});
    },
});

var ractive = new RactiveCustom({
  	el: '#output',
  	template: "foo_expr: {{ foo_expr }}, foo: {{ foo }}",
  	data: {foo: ''},
  	computed: {
    	'foo_expr': '${foo}'
 	}
});
```

**Comment by evs-chris** [comment]
This is a case of init happening outside of a normal runloop, which observers expect to be in place when they're firing. It should no longer error on edge, but there might be some cause to use a `setTimeout` for deferred observers that fire outside of a runloop. Let me know if something further needs to be done.

Thanks for the report!
