### ISSUE TITLE
"keypath cannot be linked to itself" test should not happen with options.ractive

### ISSUE THREAD

**Issue by paulie4** [ractivejs/ractive#2962]
## Description:
The [link() function](https://github.com/ractivejs/ractive/blob/dev/src/Ractive/prototype/link.js) has an error check for "A keypath cannot be linked to itself," but it should not perform this check if options.ractive is passed in, since even though here === there, it's a different data model.

## Versions affected:
Ractive 0.9

## Platforms affected:
All

## Reproduction:
https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSANCAzlA2iCALoC+WukIAbgIYwAE2ALgPYwL0C89AdggO70ASjQDGTAJZUEACmAAdHvKZIaTGpHoKlTZQGsEATwAOasJoDktADYXFykopIBKANz2etBlQkCuvPxFxKVltZQRrSyQpCwx7JiYEAFtjazUESwMTM39gYCzTJjASEjseF0UfAQA6awkePRkLArNY+majQrA24BgxSWlNZjYEF3ceURYebBZrBFqWFCaWoq42qv5qtCZlztbnN0wQJngAHmiqAD5TgHoLy5ASIA

## Code:
I think the fix should be to change the error logic to be like this (maybe with some line breaks):
```
	if ( !options.ractive && ( here === there || (there + '.').indexOf( here + '.' ) === 0 || (here + '.').indexOf( there + '.' ) === 0 ) ) {
		throw new Error( 'A keypath cannot be linked to itself.' );
	}
```

**Comment by evs-chris** [comment]
Instead of checking the keypath strings, edge will now actually walk the model tree to see if either resolved model is a parent of the other. That should still keep cross instance cycles from forming.

Thanks for the report!
