### ISSUE TITLE
Polyfills failing in IE

### ISSUE THREAD

**Issue by Minstel** [ractivejs/ractive#2964]
## Description:
`polyfills.js` contains lots of lines, where strings are constructed using backquotes, for ex: 
```
if (typeof callback !== 'function')
    throw new TypeError(`${callback} is not a function`);
```

They cause an error in IE 11, 10 and less, because backquotes are not supported in these browsers. Maybe even in greater IE's, because I see on MDN page that IE completely does not support backquotes.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
## Versions affected:
0.9.0 - all builds
## Platforms affected:
IE <= 11

**Comment by ghost** [comment]
[The polyfills are transpiled](https://github.com/ractivejs/ractive/blob/dev/gobblefile.js#L38) (they stem off the `src` node which is transpiled ahead). And the published versions of both [minified](https://unpkg.com/ractive@0.9.0-build-133/polyfills.min.js) and [unminified](https://unpkg.com/ractive@0.9.0-build-133/polyfills.js) polyfills have no trace of backticks.

Which file are you referring to? Can we see?

**Comment by evs-chris** [comment]
Confirmed the published polyfills only have backticks in comments, so I'mma call this one ok :smile:
