### ISSUE TITLE
managed vs unmanaged components have inconsistent two way binding

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2966]
## Description:
In this isolated [managed component example](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiALYCGxAdvQHy0y3u7e8CAehKkuPdhIIBnAMYxiAB1yUa9RUxgJW-EOVwBPRQjp4EAD1xCwuBgBtOA1gAVN23JHLBgxmNID2rAB0rEwMCBgYTgRsigCuKqRMdnEm3r4BwaHhkULivNGyYMR2SOTZaT4IfoEhYREYeU7RQnIKyvmSgm1KKlSmRSVI9PpGJvS4FlY29o5SAEYwTRIAwsWlnt4VkdGxCeRJKZXbjZ3CPR0gONLwdggqg6Xk1OTkAEpMsrhkCEFT2kgABTAAq4SYMRR2JiTTz0ADEj2GIF4GAAlABuAqsO4qDRaHTPcoIADu70+31ICGBoIQdlhIDhzDY9CwoPBkOhCHpcLx7hZoKQ0KYmwygU25Xq9IAUv4wOxMNhQbJ-BDAu5pJtEZ5EVFWGjMaxMEA), there is two way binding in the parent and child to "parent.name". Editing the input box in the parent syncs data in the child and vice versa.

In this isolated [unmanaged component example](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiALYCGxAdvQHy0y3u7e8CAehKkuPdhIIBnAMYxiAB1yUa9RUxgJW-EOVwBPRQjp4EAD1xCwuBgBtOA1gAVN23JHLBgxmNID2rAB0rEwMCBgYTgRsigCuKqRMdnEm3r4BwaHhkULivNEAxOSyYMR2SOTZaT4IfoEhYREYeU7RQnIKyvmSgp1KKlSmpeVI9PpGJvS4FlY29o5SAEYwrRIAwmUVnt7VkdGxCeRJKTV7LT3C-d0gONLwdggqIxXk1FUIAO7kAEpMsrgyAgABTAAq4GYMRR2JgzTz0QovMYgXgYACUAG4CqxHioNFodG8Pt8-gCgaDwQg7PCQIVmGx6FhwZDobCEDTCvj3IzwUhYUwdhlAjsqk0aQApfxgdiYbDgoRCWT+KGBdzSHZIzxIqKsdFY9isLk6IKw3D-MCbUbApFYLxmmBoDzkehI+jozBAA0) the parent two way binding affects the child bindings, but changes in the child binding doesn't affect the parent.

Changing child to isolated:false has same behavior.
Is this expected or a bug?

## Versions affected:
edge

**Comment by evs-chris** [comment]
That was a weird one. Until anchors and attached children, elements would never get bound, unbound, and bound again, so the element binding wasn't also bound during element bind. Yeah.

This should be fixed as soon as travis does his thing. Thanks!
