### ISSUE TITLE
Sortable decorator issue in Firefox

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#2967]
## Description:
I have ported [Ractive Sortable](https://ractive.js.org/Ractive-decorators-sortable/) to Edge.  The original demo works in Chrome and Firefox.

The port also works in Chrome and IE Edge, but Firefox shows a bug when dragging the 1st item to the 2nd position. Instead of the two items swapping, the first item jumps to 3rd.

To show the problem more clearly I lookup the context for the dragged item (&lt;li&gt;) then resolve the keypath and log it out.

As the item is dragged from 1st to 2nd position, Chrome logs:
```
keypath = list.0
keypath = list.1
keypath =list.1
 ```

Firefox logs:
```
keypath = list.0
keypath = list.1
keypath =list.2 
```

Not sure if the issue is with Ractive.getContext() or if the drag event in Firefox provides the incorrect draggable item (&lt;li&gt;).

But it does work in the original demo. Perhaps there was Firefox specific code in 0.7.3?

[Example of the port can be seen here](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gG4CGMABLgPYwAuRARgDYIAiCAxlUdVaQLykAKAGYBXAHZtqASwpjBpFAwp0iDLKSFFJVAJ6kAlKWAAdGMbGnzx6gHIRuBOWowpkmwG5LFsxeoB6P1IAYQoAW1DZUgApAGVBKQA6BATSOhgKAHcHFyEdQwQxAil0sVCC6i9rKSF5ah0ABwQKGoikESZSAEJefjsxJAQhKTFkG1IAMnHSVvbkhAAPeqpqXAmpusbm0hgEAEcRYsce3tEJaVkxwxMfa2tNbRgdAW29g53nmxgtaQIES4NPDdqBhKkCAqQAIIAWWYAH5KtQEAwHKRqrUGk0agMhiM+D1SDZTpIZGIxpNSNjhskiKEkAYjAjrJSRgIANoEr7E35jAC66nu3EeAIRIJuYMCaUy2QUShUDARSJRaOeACVvlJfvTrlYKtQBbpVerNfpATrRVYgYrHNrfNZqGB0hlSCMnQBRGDpGAfELtOliCjUDTDOlqrkITqkACSgdC9kDdEcSiIAzpCaEVEc9scoZ+CAAtAMOF9Bbg85QaPQOvUGCIUMNLqbfObvOYMM8NpjSBlg5kuvi+szRqRYV2e07IKR7VJcPzxMTIoaw1rQTq7CjcM5XLZGwjiGRy7RGAgsIznEbj6fKCIYGwEABpBANLhgE9A6xXm8ICEeog6V8698KGvW9I36BZ-1tagkC+FANxIagAAkiH6JgYAg24oJg8oEBgJCUJw9DdR2CJfgAFRINBqCCBgiFwGdT3qHZfjEahWE0dpqEI6wcM9KEEDoog0B3IED0rI4NDnc45Gef0BmXN9qFk5JoMElAxL4ScYBEBBhIAxSKAGBJkyQV1mOoAAZadERGL0CRU2DaBoGx1HsuCaDwpBUP5VQURNU8lKMpATLMyyNwKHCPns7CYGciksJYnCPK8jQfMcPyFIC4zTPKULrIiuyYKYIhuXUYiKDIiiEComi6O85E0p3XVMqC7KWNy8LbJsaCKHqWKyoqmBKOo2iZxS+rhTFPTwRGW8BKFbhSEYhAzNIZCpFCLgSS7MAcMcFAwAoDdSCRBAyhYl5qGvMRcFPcEFqkFZBAoBgkEMA6yn8gzqRakKrI6yKYPKnDYqWsy2KIDi6t83TIJ2S6YDkG0MLtBASCQTIxAnIkpMEK5TwwgL+oQVqLL+myAcEtzbBcmCqaSgixuh-Gmq+hIiZJ9ryYKwTotiqKEtw5DPIZzRxvSvSCdZ9nfrCrmusK1GSpeEiEHIwaquG2rGYa5nrEJ06gY5sn8vlnq+oNgahpq0bRaZhTJcM6WcuNzr7KBmL1FB8pwch7WJol4FTwwRrg5XXxRKPBJHKtkaNNN+po6qjww+4j0qD4gS0Dj0idvIZZ1MLThBVIWQGD0DIqAAa1Wbt7WOpgzse+0uFIIsdlwJZ+knChVp-PQylCBMYFwZPJt8VzHMQoXUI07GtueZbynkiWFPBV1mAAcVdU891b2REXmQN+BzDVkiG-eFmodswGnAx1Bq1iA1AgZ5kawDgPvR96mfDSOASw+2b8Wer8AQU5cDi0grdQI5kISkVdDEUiUDd5-wPkfUgJ9fgJEogAOS+qBdM19b76HvrRR+1Bn4LDfv4PwH5bwPifHXfgKDL4JErl-Z8VDdbUMnDfVYhdiw8FLuXKuNcHpgF7l8fup0h64E6KeB+zAn5gXmBpWhn8GFgASA-Ch8wADyQgPgJAbPjBSypSAKKUS-PE-A8wAEZl6QOoPaR0zoEBujTrZHi6d+K4B5v7SCzZLxAU-N+SRqjgl0PYfaBIuARB0A3LZAADCQjcijyHKP8RhNROiNIAGpnhqPod-aJsT4mbjECgZ4Fj0lWNyaQexhgIGnjMdObBRBsEFIiQgHJjSGT2ycQ6XsLpSDuk9AvDxGdfFZyabqQJClF4sQSEgLgRBSJfGukIHCMSqrMBWR8dMFBYrOG0gCUg4IChiT4TBOsFTURyAAGL3JSCgHuQwUDXgQCnXU4I2EIHqKtF4mydgSEzD3LM6Dzx3LgiCnhLcbAYxHjw2+yzaCrS7mA+up1yink5LmX+F8AG4tPmzCgAYQ4wyZPFREgt8JkH4HPBceMFK70TtQIpz4UlkJ0eoVloTfw8sqjU8CEj+V5w-hS75gR15bx3iQPe-80EYLPhrAlV8kWrBmbcVe0DYHwMQdq5BqqNJKqwVVXBAx8EUEIRqiV1hwSRhqBkRwCTfzIDuQtSgZRZCOCtDYVY1KXCCj-KtOgyxmk1GeMwwl54SUBj7PwIlxo+kBzhldKhgTdRQJGZvbeClWXssYfK1BgDKAMBAWApp2rSAwLgQgqBhSoniKYaq1hjbOEKT-qW5IShKnGBAPZV0At6YwAnPmxtkA+2kDqWOjR+gvl2sCBi-hXBBFiDLl2ERo464kDCQPGRciFLVJyfwGdxTNHaOUfowxxix4YTMUejJxxSB2IccjAZLjhmjKoOM3iPi-GasDre3UvK+4aVPc+GJcSEnPGSeY0haSelUNZceqd7ZBUFs0aUhJwxKlwdSZYhYU76n0krVNQIaInWfEcAMVQOGt3iKIBSaoQKl47tFfQMNpiI2TkFXyvQ3R+BqL46+zNzgqppqDvO7haIHp+p4c6mkjhgzCuMnFHqrLW7W3k3IDjNBw21EFce-E2SMlMoDmAhIbBra5UCkgTpFZI6ss1ja5mqaEbpqk2xvQCaY2UU6R-YTpHILgiJmKz8Gh0ihBFToHFMaO4MFcAgfzIS+7qBMy-dQDSo47TEMISSJIBAnUbuA5Nji1EaUxcV1kiSeScIqP0u6ucNPKZUbff0TpwXlZawkHrzN0uEZPYZ5RtrJWrSCmF28qQtCV27tFu5rinRKDYJtWQrm4vVkS8l28fG0tdO5aQWD5WAMYBmaHIDRM1YxzorPfLjLSsYQs1ZkaNmib2cPEwKOgrnOZOBBKr2LEfYMDQQy6Sx0VpXDB+UBI-3WKDAhkDgQJpSBnYtDqE1y6SwxPzkecJDmmASrc3ICO+Ow4naC+CEI4RIixHiEkFIkosg4WqHkY6hRiiyEbl4MxHYtgzA6AJgk4hBxIDJFMPncxFjLBK0jag4ukiS5oKsQT2OmCsCLCumAjY5mo5bGIRN4lhlKoEDLjCSIJxdQNs5ZmiJQjVi4Agc3ABiAYEQ8w27t4iK3-SUVEAnCb0TCWNwTlZFw6wwBnSKfN-cw46Z5ixVIAnxPSfXCyHN0MHYseAD6AA2AALPMPP0OKljGwKH6g4exCR4JEEQZZR49J4b6iP+5u2C14QDn-Phf6jF4T6X-pGEK9V5sDEIgmgXD18b4nlPmMCS+LH1IDvBfc9F5QGMZHXFRNh4j2Uc3ujGhfAn5PhP0-zc9RwkQRfXee+9432+wfO+CRQiIIfA6pJ1BH+P83gkG0X+yEv8v7vVfdfMve-B3AkUCalEYQMV0RYJQHYD2JvVPAkKQBAWxRJf-FfNfXvLhHkZmDNawE7dwEAHAageAAAHiQA1FRCQF4D7RdwoD7QAD4yC-BKCCBGCw4yDcA2AXAE5qDeALdXd3caJPdJwMQBDUE-B9cbAOCFIKCqCns6IBCmAhBbBZCA4yCwAAAmRgtZPQHYKgAYFwW5B6U6XAHrBIFg7Q9QxxMg9oTTEaAQgwmAIw9SBnbIEeGwt9MPYAR3QPYEfAzfagMghLVaUsYnRwLwoIjCLg7+MQRg4AYASvMoDADAFgjuZCKI7w4IvwBLLI0TRI3IqyVI5mFg9ofIlgtgrwuQtghwpQz4KQfaNQ0o6wiwh6aYYoT0VYCGbgDaaQZbBgMuKwnQ0o+wxQ3AAQ9wnCTwrhRIvw4owIt9EIqQfI7I2IzIxI5IhAVI9IuI1Y0TFgvI2Y4AIojcEo-pMohgCo1gjUKI9IngqQBOGw4gkANgeALRQYTiUgNmRosAQMf3awbsJAe0CcAAVkSQAFI6shAkxqAJwVDqA6s8wnU6BK4Ho8xQ15gywpAAAvHDCcUNFwnCDEigV+ZmPMCIHEkkrE3AXE-E1IQw4kzEurTE7EvEipAkxkmAakjzIDawD41Q+7UTb+IKekxJepU6A7A7XknXDCH4pooUjCEUygjkqU8U8U2xU6GU3XOUqY4eRU3UfwssOoJgCcf0EYOrZUsUurDaQaYYCcRJbU08BIPU1YUIgE6gJYWkqSCcHYEQ0+S04yMUhIUEyUxJEMsMiMqLLQhIAADi1OZhUDYErhQHSCFzzA4DgInEdwQFzJtIontLVIOwSC0LDLqwSxGDzB2l+LhPqRZOm1TKAn6AdJLMlPBIhOdAoDzB2EaC4HrOTMbPTNpJxLAJ6J7ljMhJZK5InFsXqBUVLSkDpBzLzMTK5O7OTCkHsBbNLNCCRJRLROoGpLZPpMJKMJ5PJMpKPOHJPLXOZNXJpLpNVNPKZNJKdIUkAS5PUndOZjYGvHLAnGRIQFRPRNTPoDq1-OHioAAsvNAroHAr-KgoUC+DgsTIbLTP6AzOekQuXJ0kkz5OoASyWXSATkFQNOsGfJHXqTnIpFoh2jpEGjoAEC0MSWSWYuSTQMSQA3IrQqbKQF9JQEYq0Nz1YuEqwDYq4uoCTJTPQqQDzHWh5jNO9S6HWiWArBYnAqwsorPGum-mBURLwtlN1BdMdA8PIDiLIr1H3jZLANsQSFzwTIUgwEwCAA)

## Versions affected:
0.9 and 0.8

**Comment by evs-chris** [comment]
I think there may be an issue with the events in firefox because if you rub the first li on the second one a little bit, it will jump in there correctly. To my knowledge, there's no firefox-specific code anywhere. IE-specific (meh), all over the place, but firefox is usually pretty good about not being awful 😄.

I'll poke at it a bit more and see if I can get anything to shake out.

**Comment by evs-chris** [comment]
[Here you go](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gG4CGMABLgPYwAuRARgDYIAiCAxlUdVaQLykAKAGYBXAHZtqASwpjBpFAwp0iDLKSFFJVAJ6kAlKWAAdGMbGnzx6gHIRuBOWowpkmwG5LFsxeoB6P1IAYQoAW1DZUgApAGVBKQA6BATSOhgKAHcHFyEdQwQxAil0sVCC6i9rKSF5ah0ABwQKGoikESZSAEJefjsxJAQhKTFkG1IAMnHSVvbkhAAPeqpqXAmpusbm0hgEAEcRYsce3tEJaVkxwxMfa2tNbRgdAW29g53nmxgtaQIES4NPDdqBhKkCAqQAIIAWWYAH5KtQEAwHKRqrUGk0agMhiM+D1SDZTpIZGIxpNSNjhskiKEkAYjAjrJSRgIANoEr7E35jAC66nu3EeAIRIJuYMCaUy2QUShUDARSJRaOeACVvlJfvTrlYKtQBbpVerNfpATrRVYgYrHNrfNZqGB0hlSCMnQBRGDpGAfELtOliCjUDTDOlqrkITqkACSgdC9kDdEcSiIAzpCaEVEc9scoZ+CAAtAMOF9Bbg85QaPQOvUGCIUMNLqbfObvOYMM8NpjSBlg5kuvi+szRqRYV2e07IKR7VJcPzxMTIoaw1rQTq7CjcM5XLZGwjiGRy7RGAgsIyVjA2CegUyvigNyRqAAJIj9JgwS8669ENBiREwJ8vhA31PHYIl+AAVEg0GoIIGCIXAZ1Peodl+H9WE0dpqHfW1f09KEEHgr8EB3IED0rI4NDnc45Gef0BmXK9qFo5IkBvFAyL4ScYBEIiV2wpiEmTJBXRQ6gABlp0REYvQJFivzvGgbHUWTb1oGh-yQV9+VUFETVPfjBOE8pxI3ApAI+ZTykAxSKRvSy-2fDTAK05FHF0hj9KQISROMySzJkm8mCIbl1BAihwMghBoNg+DnJ0nddQ8ryjIk0zpJsFiKHqazQvCmAoJguCZw0bTXOIj9-ECEY2Hw3ASD0bhSCQhARNIZ8pFCLgSS7MBAMcFAwAoDdSCRBAyh-F5qBEGAxFwU9wQaqQVkECgGCQQwBrKPSKAGATPMMn8fNS8ybzCqz1CakS0KIDDYtK3jbmcSKprkG0HrtBASCQTIxAnIkqMEK5Twe-icoQfaxJSqTjrk1TbCUm95MfBzNOKlzhQY4HtuSUHwcOqH-MIn8zpswnf3UlHNDRtzysxnace8yG-PSgKPuCl5QIQCC8sigqYtRuKgYSrGEnp5KTPx5nMuy0bTq5-LoqKymBYxoW6Zl35ccZtLlNOmBrIu8orpu-m7pV5sHoweLLfulZljIhJVPlwqOMl+pHcijwbcA3CasIl2wJ68g7aPCl2E4QVSFkBg9AyKgAGtVm7e1hqYMalvtLhSCLHZcCWfpJwoVqPSIPQylCBMYFwT2xR1ZTEfJwCOL+rrnma8p6PKvcs9kRF5kDfgcw1ZJ8p7hZqHbMBp3R8rcHPDiOCJvv4tuBj5sn1ZC3Dngo5j+PE8WsAi6+UvRor3BOlPZUughYudASacb+P54F976gEigj4EgSPx-kMQGVftI6Z0CA3QeioK3MBMA8IETQNPbC5sGJtx-AkJAXAiBgS+DNIQgEEgOGoMwNBHx0wUGss4biAJSDggKGRDerFhgoBFGVXwFkib2QAmQfgzcFzDRav-TuJBQ5DQHkaYePNR59wnlPam2FTxILfqg2gGDny4GwTAFB6R6iuiENgyQLt-QjGrhacq4JIw1AyI4Dcx9kCoh-IXSgZRZCOCtDYVYOFFq6HUPQZYl8ajPAGBuEWIiRYUADH2fgs82CBLDME0JfCZGPUmtNZewIbZVF8dfW+99cCPxLn4-Cb8P4Ei-j-ekf8GQAIdL2F0pB3SeggT7GBptyoIOMYENE5jPiOAGKoeho5k5EApNUVR7cSDH08XQbxDEr7+IKZFT+39-jdHCeed+cyikLNKeUmmCTnrJJadhLuETIxIHmBxCJqzx4EgAALBgWJcJS+TjmnP4DMi5Hwbn9DuXAt6DEpy4ASGwBWPldpIGeKRI8DsIpRWdtIh6ciUFoKUVgnBGVNHaPYP3AkHNDEtmwuCXA3YABehKOhZiPiXVq+dEQMAYNsERBdSAiHqAohAp4u6jIpcsyJhSbDFIbKeDld9c4MFcAgPJG4nnqAAAyeMycK0VYLzyStIAARgMKyKVPJvm6nOUyll8ySmwt1HNQIMzUSuMDtUiJp4IkcRmVbJh1hQZyx5grJulEW5xIen8gFQKJIi3VmKoOFYIXu2hfBbV1sa6+ANqhQY10GCYq4dRHh7cripuQbG-B8aMICBNKQKNRjfCD1+CgsOxYqD-PBR0cJwcmCOp2dNYNh5628QwPoWFPhwQhHCJEWI8QkgpElFkQC1Q8jDUKMUWQacvBXw7FsGYHQlkEnEIOJAZIpiLrmIsZYuAvXUC3UkHdNBVi1pDUwVgRYuBUEbPs3inJcwcWqSWsVr1jXUonOlGWilBaIlCNWLgCBP0AGIBgRDzH+gDiIf0qwUUQCcb63rUBFRuCcrJBYPWAM6GkQGCQADFDjpnmNZUgpGyPkdcLIT9QwdhEYAPoADYAAs8xmMJHqGIFAYxsAYd1FhsQOHP1BEqWUEj5HxOogXp+tgImECMZY2xjjXHSM8ZVph7DZRP0xCIJoFwYmJNkcoz9AktVdNSHk6xpj7HONjALVhJD6mBOaYJAAeUaF8fTBnSNGc-ZlQCRALOKZs2R1T2zHOCYJFCIgfcBqknUF57zUmsXRftLIQLVmlPcfs++8LzmbCRlYSMQMrpFhKB2HrdQPmCRSAQCqqV6XrPKZC7xnkgtza6nbe4EAOBqDwAADxIA1KiJAvBjAgDAxQMbAA+PrfhBsECm7xPruA2AuDdsN3gX7wOQdgtBycGJNuvz8A+oeNhFsMQG0NwFhVNtMCELYc72y+tgAAExTYwXoHYVABguE46iP9-yv6zde49+JfX2hZwVptr7MAfvsWHdkKuoOHPUGAMAYDKHgTtZR31kVrVSzVscMjnL77lv1GfFNtHTmEAYAwLN3OFPePWFmyK4nSG0d+Ex7TwWs32hs+oLN+byOLvzchzdz4Uh+oPZ5yDr+98YzFE9Ksa63AOrSDYKoaOwO3s84h9d+Cm2EeASR7xtHGOJLc7U7qXHUh+c44Z2ISnwBqe0-p+Tx3TOBec9t6b4A3uNyW6e34Pnp5BcamJ-T1bUg3ag+6yANg8AEh3cwqQEWkuwCBkQ7qbsSB7QTgAKxSoAKTJLuEmagE5k+l+oHmcxdA46LTzBM+YZYpCEvoROCZsPAJN4oPMaveYIiEt7y33AbeO+pG+z35v1fm+t-b5xzvU+YAj72akt+yetnxPJ55CfUrVWjVIPvqVa-o0PTT1LrfSGd+DcX0f+-++VWjVP0W8-RvK5X-fZjssdQmATn0TxCrDfnvtXh1HlMMBOCfqeHerqAkO-qsHjlntYEsGPlRBODsLtkPNXsAXflKgkPnofngQQaEEfvgYfi9gkAABzP6CwqBsBxwoDpCrp5gcBlYTjAYICcGgGQQQEP6kEvaEHV4iojB5g9Tp4V6qqz5aAMFMH9CQEJACEkGF5F7OgUB5g7CNBcBSH0GMEUDMFj6Eq4Yq6FyUHF6z7L4Tgqr1CnKUAip0gcFcG0HL7qHJhSD2DyGKED514N415z4GET5d4-ar6CyD4UDD5+Hj536BHT597mGj6REoBL7d4r4z7QHr4BrL7sSIGCxsBTTlgTi14ID16N6MH0DV65GVxUAFFD55ilF0DlF5FVEKBfD1G0HSG6HMGsFNEOGAHNLr4irqKZRhqf4PTREwCWHWEUhwQ9R0h5R0ACAvZSoyqLEyp1ZSpGqjHtGyFIDoEoDzEvZMbLGHFYArEbG6h0EyF6H9B5jtSET-6OJdDtRLAVg-jlErRNHODKLk47CvFpFn6wHwHkDu4jG6jpg-jz64YqoJBMY0EMQYCYBAA). There was some weird hackiness in the `dragenter` handler that was confusing firefox a little bit. I modernized everything a bit and it seems to be much happier now.

**Comment by sabob** [comment]
Thanks for your effort @evs-chris.
