### ISSUE TITLE
Update TypeScript definitions

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2969]
## Description:

With the latest wave of API changes, removals, and additions for 0.9, the TypeScript definition needs updating. But I'm no TS expert. I know how to use types but that's about it.

## Versions affected:

0.8.x, 0.9.x

**Comment by jmkgreen** [comment]
Will this allow for custom methods - right now I'm told neither Ractive.extend nor Ractive.static allow for custom methods which I think is utterly wrong.

**Comment by ghost** [comment]
I'm not sure what you mean by "custom methods". Do you mean component/instance methods? Also, what's `Ractive.static`?

**Comment by jmkgreen** [comment]
In the original site documentation (good as of yesterday I think - the web site is now completely updated) it was referenced as "Custom Methods". I can't actually find this in the new web site.

Regarding `Ractive.static`, see `node_modules/ractive/typings/ractive.d.ts:476` which I acquired via `npm install ractive` per the web site instructions. It states: `declare var Ractive: Ractive.Static;`

Incidentally I have just noticed that the top of that typescript definition file starts:
```javascript
// Type definitions for Ractive 0.7.1
// Project: http://ractivejs.org
// Definitions by: Han Lin Yap <http://yap.nu>
// Definitions: https://github.com/codler/Ractive-TypeScript-Definition
// Version: 0.7.1-1+2015-03-21
```

This despite me having just installed `ractive@0.8.14`

**Comment by ghost** [comment]
Maybe @codler can chime in 😄

**Comment by codler** [comment]
Im abit outdated whats new in 0.9, but in TypeScript you cant define "custom methods" on interface, so you will need to extend the interface together with your custom methods in a new interface in your project.

Small example how to use https://github.com/codler/Ractive-TypeScript-Definition/blob/master/RactiveTypeScriptDefinition/ractive-tests.ts

**Comment by ghost** [comment]
Closing. Was recently updated in the following commits.

- https://github.com/ractivejs/ractive/commit/233b2fa30548c0c48490b4fe3a76ca4e253ecf84#diff-07a22cd5add1e2ae986fbc5e3ede858e
- https://github.com/ractivejs/ractive/commit/250f0e9ae9555767ba127fe912209c4cbabed4b9#diff-07a22cd5add1e2ae986fbc5e3ede858e
- https://github.com/ractivejs/ractive/commit/02e099e2e510af764346d67991114cfa474607b4#diff-07a22cd5add1e2ae986fbc5e3ede858e
- https://github.com/ractivejs/ractive/commit/893a99c4debe7b5edd0c3df15286a371b2abfd93#diff-07a22cd5add1e2ae986fbc5e3ede858e
