### ISSUE TITLE
Continue pushing for Bower?

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#2970]
Bower's putting this huge sign on [their website](https://bower.io/) now:

> ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!

I don't take this as "dead" like most people believe. I take it "feature complete" and nothing more to add. However, I'll just ask out of curiosity if we should still consider pushing for Bower. 

- Thumbs up if yes, continue pushing builds to Github for the sake of Bower.
- Thumbs down if no, and just go with npm.

And feel free to add in your reactions. This is not for immediate action, just an inquiry.

**Comment by MartinKolarik** [comment]
👍 not for the sake of Bower (I've never used it), but because GitHub releases are the simplest way to download the dist files, if you need them for any reason.

**Comment by evs-chris** [comment]
Gonna close this as keep pushing release to github, but not for bower 😄
