### ISSUE TITLE
FR for 0.9.x - Warn on transitions running as JS.

### ISSUE THREAD

**Issue by andreujuanc** [ractivejs/ractive#2974]
I just read this from ChangeLog:

> easing functions that can't be run using CSS transitions will now cause the transition to be run as JS (#2152)

It'd be nice to inform on console warning that the easing transition is running as JS. Might help a bit :)

 Cheers!

**Comment by evs-chris** [comment]
That would only apply to easings that you specify as JS e.g. `new Ractive(template: '<div slide-in={ easing: 'elastiBounce' } />', { easings: { elastiBounce() { ... } } })`, which before that change would end up just using the default css easing (linear, I believe).

**Comment by andreujuanc** [comment]
So then it's more like, _easing functions written has JS will be run as such_ right?

**Comment by evs-chris** [comment]
That's it exactly 👍
