### ISSUE TITLE
Removing an item from a list of checkboxes unchecks the next item

### ISSUE THREAD

**Issue by fallenrayne** [ractivejs/ractive#2976]
## Description:
Weird title, I know, but it is a bit of a weird issue. So we have a list of checkboxes. The list is dynamic and populated by an async API. When a checkbox is unchecked, it is removed from the list and then we update the view model with the new list. When we do that update, the item gets removed correctly, but the next checkbox in the list becomes unchecked, even though it should still be checked. The DOM element has the "checked" attribute, the view model has the data that says it should be checked, but then if you inspect the DOM and look at the "checked" property of the Node, it says checked === false.

Now, I've found a way around it but I am not fully happy with the work around. I found that if you clear out the list first and then populate the list with the data, then it will render correctly. I've reproduced the bug on a basic level in the JSFiddle link below. Try clicking on a checkbox in the middle of the list. The workaround is putting another line in updateSources that does ```this.set('inputSources', []);``` first.

Thanks in advance for your help.

## Versions affected:
0.8.14

## Platforms affected:
Latest Chrome

## Reproduction:
https://jsfiddle.net/03mu07e5/3/

## Code:
```javascript
var sources = [{
    key: 1,
    checked: true
},{
    key: 2,
    checked: true
},{
    key: 3,
    checked: true
},{
    key: 4,
    checked: true
}];

function getSources () {
  return sources;
}

new Ractive({
    template:`
        <ul>
            {{#each inputSources:i}}
                <li>{{>checkbox checked as checked, i as index}}Source {{key}}</li>
            {{/each}}
        </ul>
        
        {{#partial checkbox}}
            <input type="checkbox" on-change="@this.removeSource(index)" {{#checked}}checked{{/checked}} />
        {{/partial}}
    `,
    el: '#app',
    data: () => {
        inputSources: []
    },
    
    oninit: function () {
        this.updateSources();
    },
    
    updateSources: function () {
        this.set('inputSources', getSources());
    },
    
    removeSource: function (index) {
        sources.splice(index, 1);
        this.updateSources();
    }
});
```

**Comment by ghost** [comment]
So...Ractive treats the `checked` attribute in a special way. Instead of being a presence attribute which is how it works in regular HTML, Ractive actually checks its value.

https://ractive.js.org/concepts/data-binding/#checkboxes

```
checked="{{ checked }}"
```

With that, your code works fine 

https://jsfiddle.net/Lc6v10n7/

**Comment by fallenrayne** [comment]
Awesome, thanks for the help. I recall seeing Rich talk about that issue but I missed the solution to it. Appreciate it.
