### ISSUE TITLE
ractive.el vs ractive.target

### ISSUE THREAD

**Issue by Jeff17Robbins** [ractivejs/ractive#2977]
## Description:
"target" seems to be preferred to "el" in the object literal to Initialize a Ractive instance.  But is there a .target property on the created Ractive instance, or only a .el property?  If only a .el property, this feels unbalanced.

**Comment by evs-chris** [comment]
It would make sense to have a `target` property to match the init option. Out of curiosity, what do you use `ractive.el` for?

**Comment by Jeff17Robbins** [comment]
We are burying a ractive instance inside a custom element.  Sometimes we
need access to the element for its properties and attributes.
