### ISSUE TITLE
[question] how to tear down event listeners but _not_ DOM?

### ISSUE THREAD

**Issue by wearhere** [ractivejs/ractive#2978]
I'm trying to use Ractive to render a dashboard like this:

<img width="605" alt="screen shot 2017-05-26 at 6 55 53 pm" src="https://cloud.githubusercontent.com/assets/110000/26517023/121a339e-4245-11e7-9505-70a863520046.png">

When I click between folders in the sidebar, I would ideally re-render the entire dashboard view (for simplicity) while reusing as much of the DOM as possible (for performance and also to implement double-clicking on a folder name to edit it—if I re-render and don't reuse the list item, then the double-click event won't be received.)

I feel like this should be possible using psuedocode like:

```js
const ractiveInstance;
function renderFolder(folderId) {
  if (ractiveInstance) ractiveInstance.teardown();
  ractiveInstance = new Ractive({
    el: /* some container element */,
    enhance: true, // to reuse DOM elements
    template: /* some html, where each folder list item has the class '.js-folder-name' */
    data: /* a Backbone model created from the folder Id */
  });
}

$(document).on('click', '.js-folder-name', (e) => {
  renderFolder($(e.target).data('folderId'));
});
```

I call `teardown` before re-rendering the ractive instance because the Ractive instance is bound to a Backbone model using [the Backbone adaptor](https://github.com/ractivejs/ractive-adaptors-backbone) and I assume I should tear down those event listeners. But then this removes the DOM and no DOM is reused!

How can I just tear down event listeners but not the DOM?

Btw I suppose one way of doing this would be to have one global Ractive instance that never gets torn down, I just swap out folder models within its data context, but for purposes of structuring my code I would prefer not to do that.

**Comment by evs-chris** [comment]
That looks like a master-detail sort of scenario, which is one of the primary use cases for `link`s, though it looks like you could get away with just `set`ing the data. Any reason not to skip the teardown on the component and just set data in the existing component if available?

**Comment by evs-chris** [comment]
Sorry, on my phone so I missed the backbone teardown part. You shouldn't have to worry about that because any time adapted data is replaced/removed, the existing adaptor is torn down as part of the change propagation process.

**Comment by wearhere** [comment]
Cool thanks for the response @evs-chris, good to know that the Backbone adaptor will be automatically torn down.

I think I will need to take your suggestion to replace data on the existing component, but to address why I said

> Btw I suppose one way of doing this would be to have one global Ractive instance that never gets torn down, I just swap out folder models within its data context, but for purposes of structuring my code I would prefer not to do that.

for anyone in the future that finds this issue (and why I think the notion of tearing down event listeners while keeping the DOM was misguided):

--------------

Contrary to the original example, my folder dashboard component does not directly handle clicks on the folder names (by re-rendering). Instead the folder names are actually links that cause in-app navigation:

```hbs
<li data-id="{{_id}}" class="js-folder-name">
  <a href="/dashboard/templates/folder/{{_id}}">
</li>
```

and (in a parent component of the folder dashboard):

```js
// Part of a Backbone event delegation hash, so binding omitted
'click a[href]': function(e) {
  if (/* link is in-app */) {
    e.preventDefault();
    Router.navigate(e.target.href);
  }
}
```

The router responds by calling `remove` i.e. teardown on the top-level dashboard component and mounting a new dashboard component in its place, rather than trying to reuse the existing component (partly because it's built to be agnostic as to the exact type of the dashboard, there are several different types the user could navigate between).

So this is why I wanted to be able to reuse the existing _DOM_ rather than the existing component. **But**, making the existing component leave its DOM behind when it's torn down seems weird in retrospect—we'd only want it to do that when navigating between dashboards of the same type, otherwise we would want to clean up the HTML (since it'd be of a different structure and not reusable in that case).

So if I'd need to introspect on the dashboard type anyway, I should just do it how you suggest with swapping data on the instance rather than trying to figure out how to tear down while keeping the DOM.

Thanks!
