### ISSUE TITLE
polyfill.js direct link

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2979]
In https://ractive.js.org/get-started/support/ it states that there is a polyfill js file
for older browsers but there is not a link for this file for someone to download.

Is there a direct link for this file?

**Comment by ghost** [comment]
It comes with the package if you use Bower or npm. It's also a sibling to the rest of the library files so replacing `ractive(.min).js` on whatever CDN you're on to `polyfills(.min).js` should just work.

But then I should just put a direct link to ~jsDelivr~ unpkg (jsDelivr doesn't have 0.9 yet) on that page just in case. 👍 Thanks for the report, will update in a bit.

**Comment by ghost** [comment]
Changes should be up in a bit. 👍

**Comment by MartinKolarik** [comment]
jsDelivr sure does have 0.9

**Comment by MartinKolarik** [comment]
@jsdelivrbot npm ractive

**Comment by ghost** [comment]
I only see 0.8.12 and older on the site tho 🤔

**Comment by MartinKolarik** [comment]
Yeah the site doesn't support the new backend yet. This is up to date listing: https://cdn.jsdelivr.net/npm/ractive/

**Comment by ghost** [comment]
Oooh, nice. I'll replace then. 👍

**Comment by MartinKolarik** [comment]
We could also use this link and call it the legacy build, since some people might be used to that: https://cdn.jsdelivr.net/combine/npm/ractive/ractive.min.js,npm/ractive/polyfills.min.js

**Comment by ghost** [comment]
Changes will be up momentarily. Thanks for the info @MartinKolarik 🎉
