### ISSUE TITLE
Ractive.fire() passes unexpected parameter

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2980]
## Description:

According to [changelog](https://github.com/ractivejs/ractive/blob/dev/CHANGELOG.md#090), there is no breaking changes on `Ractive.fire()` so it should take the event name as the first parameter and pass its additional parameters to the function it calls; but it doesn't behave as expected as it passes an object as `{name: "myEventName"}`. Rest of parameters are missing. 

## Versions affected:

0.9

## Reproduction:

http://jsfiddle.net/ceremcem/waqzjjj2/2/

**Comment by ghost** [comment]
I remember there was a discussion that both custom and DOM event handlers would get an "event object" as first argument. Any arguments after that would be the arguments passed in.

_(looks for thread)_

**Comment by ghost** [comment]
Here we go: https://github.com/ractivejs/ractive/issues/2810

If this isn't found in the docs, feel free to open an issue or pull request at https://github.com/ractivejs/ractivejs.github.io. 😄

**Comment by ceremcem** [comment]
Thank you @fskreuz . The fixed version of the example is like so: http://jsfiddle.net/ceremcem/waqzjjj2/3/

**Comment by ceremcem** [comment]
I found the entry in the "Breaking Changes" when I wanted to edit the `Changelog.md`: 

>The first argument to the callback supplied to ractive.on will be a context object regardless of whether or not the event originated as a DOM event. This means that all event listeners share the same base callback signature. Any additional arguments to fire will follow the context argument.

My bad, sorry.
