### ISSUE TITLE
0.9 - ractive.get() options

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2981]
In 0.8 ractive.get() included an options object (https://github.com/ractivejs/ractivejs.github.io/blob/dev/legacy/0.8/ractive.get().md)
Is this still the case with 0.9? I don't see a mention of it in the new docs.
In 0.8 ractive.get() would return a deep POJO clone of the data whilst ractive.get(keypath)
would return a shallow copy.

**Comment by evs-chris** [comment]
The options are still available, they just got missed in the transition. I'll get them added to the 0.9 docs in a bit.
