### ISSUE TITLE
0.9 - method string parameters do not replace &amp; with &

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2982]
I don't now if this is bug but it isn't documented in changelog so I thought it deserves a mention
in case this is something "deeper".

In 0.8, if you passed a string parameter that included ```&amp;``` directly to a method, it would automatically convert ```&amp;``` to & - http://jsfiddle.net/sohv6qgb/4/
In 0.9, ```&amp;``` stays as is. - http://jsfiddle.net/2Ly88nvg/1/

**Comment by evs-chris** [comment]
That's interesting... and a side effect of cleaning out the legacy parsing for attributes that parse in an expression context. Prior to 0.9, attributes where read into a string and then parsed with a special handler. Now they just use the normal expression parser inline, which is considerably more resilient. Should string literals in those contexts automatically have their entities decoded? I feel like they probably should, but I'll play with it a bit to see what happens with different forms of template.

**Comment by ghost** [comment]
I have this strange feeling that they should stay as is (as `&amp;`). Making it auto-convert gives the impression that Ractive handles auto-decoding where it shouldn't. It would be strange in JS if functions suddenly decode urls for you. 😉

**Comment by evs-chris** [comment]
Yep, I was thinking about it in the wrong context. If we allowed templates outside of script tags, it would be a problem. I think the 0.9 behavior is correct. I'll add a note to the changelog breaking changes.

**Comment by kouts** [comment]
That sums it up then, thank you @evs-chris !
