### ISSUE TITLE
An array push does not trigger the pattern observer like the documentation describes

### ISSUE THREAD

**Issue by stephenir** [ractivejs/ractive#2984]
## Description:

The documentation (https://ractive.js.org/concepts/data-binding/#observers) has the following in the pattern observer example:

people.push({name: 'Jason Brown'});
//newValue will equal 3, and the keypath will be people.length

But the observer does not fire when pushing to the array.

## Versions affected:

https://cdnjs.cloudflare.com/ajax/libs/ractive/1.0.0-build-2/ractive.js

## Platforms affected:

Tested on Chrome

## Reproduction:

http://jsfiddle.net/tGGv9/10/

## Code:

(Code from documentation)

var ractive = new Ractive({
  el: myContainer,
  template: myTemplate,
  data: {
    people: [
      {name: 'Rich Harris'},
      {name: 'Marty Nelson'}
    ]
  }
});

ractive.observe('people.*', function(newValue, oldValue, keypath) {

});

var people = ractive.get('people');
people.push({name: 'Jason Brown'});
//newValue will equal 3, and the keypath will be people.length

ractive.set('people.3', {name: 'Jack Black'});
//newValue will be {name: 'Jack Black'} and the keypath will be people.3

ractive.set('people.3.isACelebrity', true);
//newValue will be {name: 'Jack Black', isACelebrity: true} and the keypath will be people.3

ractive.set('people.0.info.isCreator', true);
//newValue will be the object for index 0 and the keypath will be people.0

**Comment by ghost** [comment]
That portion of the documentation is outdated. Just started revising that area yesterday. 😄 

[This branch](https://github.com/ractivejs/ractivejs.github.io/tree/data-binding-update) contains a work in progress that covers [that portion already](https://github.com/ractivejs/ractivejs.github.io/blob/data-binding-update/docs/concepts/data-binding.md).

**Comment by stephenir** [comment]
Thanks for clarifying. I'm still having an issue when pushing an item that doesn't have a value set where that value corresponds to an `<input>` value.

Please check -

http://jsfiddle.net/tGGv9/11/

**Comment by ghost** [comment]
Interesting. This does look like a bug. We'll get back to you with a fix soon. 😄

**Comment by evs-chris** [comment]
Yep, there was a bug with pattern observers and shuffling that happened to coincide with additional changes (in this case, the binding creates an `id` on the pushed object). On the plus side, the fix was actually to remove some code 😄. This should be out on edge and 0.9-dev as soon as travis does his thing, and it will go out with 0.9.1 when it gets cut.

Thanks for the report!
