### ISSUE TITLE
Embedding ractive code in html pages

### ISSUE THREAD

**Issue by davidmoshal** [ractivejs/ractive#299]
Hi, am wondering if it's possible to embed Ractive code inside an html template.
e.g:

```
 <script>
    function get (el, items) {
       new Ractive:({
          el:el,
          template: this,
          data: items
       })
</script>

<div>
   {{#items}}
      <div>{{ name }}</div>
   {{/items}}
</div>
```

ie: the ractive code is embedded in an html page, which contains the template, so that all of the code can be in one place?

**Comment by davidmoshal** [comment]
Hi @Rich-Harris I've been playing with Vue.js recently, seem really similar to this idea we bounced around in 2014. 

In fact one of the examples above looks just like a .vue file !
Seems to work pretty nicely.

Dave Moshal

**Comment by Rich-Harris** [comment]
Yep! A lot of Vue's ideas are heavily influenced by Ractive, including this one – we've been using [single-file components](https://github.com/ractivejs/component-spec) since long before .vue files existed. We just never did a good job of advertising it 😁

**Comment by davidmoshal** [comment]
We should have! 

Vue.js is the second most starred front-end framework on Github (after AngularJS).

Dave
