### ISSUE TITLE
0.9 - events in 0.9 

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2990]
Here's a fiddle in the playground displaying the use of ```fire``` inside the templates.
https://goo.gl/BQKtak

I understand that the first way (Test event button) is now deprecated and one must use 
the third way (Test @context button) in order to achieve the same functionality.
I also tried passing the @event property but I only get a ```Object { name: "test_event" }```

I'm using the ```on-click="@this.fire('something', event)"``` method throughout my app and I now
have to replace this syntax both in HTML and JS sides, should I be using some other way?
Is it an anti pattern to use ```@this.fire``` inside the templates?

**Comment by evs-chris** [comment]
That's an interaction with the other event change - `on` callbacks _always_ get a context object as their [second arg](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANoC6AvngMbwB0MA9gO4AEwAtkjAOYCWAdgLQAjOihR1WkAIwAGAA4APANykAOr1qNIgtADM6MNDiYaGkJDvQwWFOr3R3IKkE8VMAJtwyzkAT0hMUJEEENCZXChCOLREwZVx8eAA3DiYYJAoUbkTQgF4mXjRmACV0zOyACmA1JiY0BH8AcgBiVh8AfXQsBpxqgLRWb1Q0Rpb2zpQO-sH0bt63VCR-Kt4alRQ1NfINsV4+bhR-HQBXXgzuW3KASmW1tZQwT2oLhvG2tGy7bqZj08yL97QdiMSGu21uKBsvAwdBC1AQdE45QBQKYIMUYJQpEu6N44Puj2er0h6HkKC+PzOF2JaFJwNBuPWjMh0Nh8MR1NpqOxGKxOM2al58WwkBAAB4PIkmNw3DknK1JlgnAA+UUAeglSo2vFFGAoMG4shQAR8sjQspAJJQqvQA2Q6CcUplcrGmAmNumaGVanFWSYESQGAw5voDC9DNFgiOolsxtN5sj0dxICYtn4EW4FAA1uaAAL4jDUHTcAzlF6ut4fMlGZEoS7KgAqrtqlbVCZ2mu16qyHZ9kv9geDjDDawjUZ2sbNTjbtgdqfTWdz+cLxbQpdeNa+OZrdZASsbWCYW5bqunvB7XcSPYlfuQA6cIeHKFHiYn8bHM+Tc4QGezTjzDwLIsSzLLA2g5KtD3Anc9ybHNwNbd8z29C9z11fVDSVEBSCAA). If `fire` detects that its second arg is not a context, it will insert a context and bump the rest of the args one spot.

`@this.fire` in templates is definitely not an anti-pattern. There are two shorthands for proxying events like that though:
* If you have no args: `<button on-click="something">`
* If you have args: `<button on-click="['something', arg1, arg2]">` - there's nothing really special going on there syntactically, it's just special handling at runtime by the event directive class when it detects a single array with a string as the first param - it just does a `fire` with the current event context injected for you.

I personally quite like to use proxied events for some things, and usually go so far as to use unquoted attrs for them `<button on-click=['something', arg1, arg2]>`. Some people/teams don't like shorthands or strangish template constructs, though.

**Comment by ghost** [comment]
> Some people/teams don't like shorthands or strangish template constructs, though.

✋ 😄

**Comment by kouts** [comment]
Ah I missed the part > it will insert a context and bump the rest of the args one spot
It's a little confusing though, maybe because I was used to the old behavior :smile:
