### ISSUE TITLE
0.9, edge - TypeError: cyclic object value

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#2994]
In 0.9 and edge I'm getting a ```TypeError: cyclic object value```
when I'm copying the data object like this e.g ```JSON.parse(JSON.stringify(this.get()))```

This didn't happen in 0.8 so something must have changed in 0.9 and up when you call ```this.get()``` right?

I'll try to pinpoint when this happens in order to create a fiddle displaying the problem.

I'm using the piece of code bellow to remedy this for now in order to be able to further test 0.9 

```js
            var seen = [];
            return JSON.parse(JSON.stringify(obj, function(key, val){
                if (val != null && typeof val == "object") {
                    if (seen.indexOf(val) >= 0) {
                        return;
                    }
                    seen.push(val);
                }
                return val;
            }));
```
This uses the replacer function of  JSON.stringify to exclude already serialized objects (https://stackoverflow.com/questions/9382167/serializing-object-that-contains-cyclic-object-value).

**Comment by evs-chris** [comment]
Hmmmm. Does skipping the virtual props help? `ractive.get({ virtual: false })`

I don't _think_ there're any differences between 0.8 and 0.9 in that regard.

**Comment by evs-chris** [comment]
@kouts can you change your stringifier to log out which key/value is cyclic?

```js
            var seen = [];
            return JSON.parse(JSON.stringify(obj, function(key, val){
                if (val != null && typeof val == "object") {
                    if (seen.indexOf(val) >= 0) {
                        console.log('found a cycle at ', key, val);
                        return;
                    }
                    seen.push(val);
                }
                return val;
            }));
```

**Comment by kouts** [comment]
Ok I managed to pinpoint when this happens.
It happens when I have another Ractive instance which is appended to the ```<body>```
This also affects 0.8, so I'll try to make a fiddle as soon as I can.

**Comment by kouts** [comment]
I'm closing this for now since I cannot reproduce this.
