### ISSUE TITLE
Styles are transitioned incorrectly

### ISSUE THREAD

**Issue by monoblaine** [ractivejs/ractive#2998]
## Description:

Something in recent commits (b231022 maybe?) broke the slide plugin. Various styles (margin, border, padding, etc.) get weird final values when the transition end.

The [slide plugin](https://ractive.js.org/ractive-transitions-slide/) animates the following props:

```js
props = [
  'height',
  'borderTopWidth',
  'borderBottomWidth',
  'paddingTop',
  'paddingBottom',
  'marginTop',
  'marginBottom'
];
```

It looks like (sorry didn't have the time to debug thoroughly) ractive's changing all the values in this list to eg. `34px` although it's supposed to change only the height property.

## Versions affected:

[1.0.0-build-11](https://cdnjs.com/libraries/ractive/1.0.0-build-11)

```
v1.0.0-edge
Build: e3ed3d46324f42200e78d274465996bd6be4c42a
```

## Reproduction:

https://jsfiddle.net/monoblaine/7bbwhkq8/

## Code:

```html
<script type="text/ractive" id="template">
  <div class="container">
    <p><button class="btn btn-default" type="button" on-click="@.push('items', @.get('items').length + 1)">Add item</button></p>
    
    {{#if items.length === 0}}
      <div class="alert alert-warning" slide-in-out>Nothing here!</div>
    {{else}}
      <ul>
        {{#each items}}
          <li slide-in-out>
            Item {{.}}
            <button class="btn btn-danger" type="button" on-click="@.splice('items', @index, 1)">Remove</button>
          </li>
        {{/each}}
      </ul>
    {{/if}}
  </div>
</script>
```

```js
new Ractive({
  el: document.body,
  template: '#template',
  noIntro: true,
  data: {
    items: []
  }
});
```

```css
p {
  margin-top: 1em;
}

.alert,
ul {
  margin: 0;
}
```

**Comment by monoblaine** [comment]
Hold on! I think I've found something 🕵️ 

Flashback to my initial post:

> ```js
> props = [
>   'height',
>   'borderTopWidth',
>   'borderBottomWidth',
>   'paddingTop',
>   'paddingBottom',
>   'marginTop',
>   'marginBottom'
> ];
> ```

I did some debugging and something seems odd [here](https://github.com/ractivejs/ractive/blame/b231022216a99677f8b517e29435141160ce1db8/src/view/items/element/transitions/createTransitions.js#L173):

```js
interpolator = interpolate( parseFloat( originalValue ), parseFloat( to[ prop ] ) ) || ( () => to[ prop ] );
```

* This line is executed within a while loop.
* This loop is iterated for each property name in `props` in reverse order.
* Until we get to the first element (which is `height`) the variable `interpolator` gets `( () => to[ prop ] )`

So that function expression is improperly using the `prop` variable. Because the value of `prop` will always be the first element in `props`, which is `height`. That's why the transition is applied as eg. 0px to 34px for all style properties.

IMHO the following change would fix that:

```diff
- interpolator = interpolate( parseFloat( originalValue ), parseFloat( to[ prop ] ) ) || ( () => to[ prop ] );
+ interpolator = interpolate( parseFloat( originalValue ), parseFloat( to[ prop ] ) ) || ( ( _prop ) => () => to[ _prop ] )( prop );
```

**Comment by evs-chris** [comment]
Yep, I think that's part of it. I _think_ that code shouldn't be run at all for those props though, as they a) aren't changing, and b) should be CSS transitionable.

**Comment by monoblaine** [comment]
@evs-chris I might have the answer to *a*:

[Here](https://github.com/ractivejs/ractive/blob/dev/src/view/items/element/Transition.js#L87):

```js
// we need to know if we're actually changing anything
if ( current != to[ prop ] ) { // use != instead of !==, so we can compare strings with numbers
...
```

We're comparing `"0px"` with `0`.

**Comment by ghost** [comment]
Not sure if "0px" would be equal to 0. 😉 

The problem might be because there's units involved, causing one value to be a string. Normalizing everything to numbers may be a better solution. jQuery does that for most of its CSS-related operations.

**Comment by evs-chris** [comment]
There were a couple of different overlapping issues going on there, but I think I've got them all sorted. @monoblaine let me know if something is still amiss. I'll cherrypick this back to 0.8 along with the other transition fix after it's had a bit more time on edge (by the end of the week).
