### ISSUE TITLE
How to use ractive.set without firing ractive.observe? 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2999]
## Description:

I need to update a variable of a component, so I use `this.set("myvalue", 5)`, but this triggers `this.observe('myvalue', function(_new){})` also, which leads an endless loop (because of my handler I just passed to `this.observe()`). 

That's why I need to update a variable without triggering `this.observe()`. Is this possible? 
## Versions affected:

0.9.0

**Comment by ghost** [comment]
Is the observer setting some value that is indirectly affecting `myvalue`? Or am I missing something?

~Also, @evs-chris wasn't there a temporary "silence" feature added recently?~ ~Nope, it was for `ractive.on`, not observers.~ I guess I didn't read the changelog correctly. There is an observer silencer.

> - Event listener handles returned from ractive.on( ... ) now have methods to silence and resume the listener. The existing cancel() method now has siblings isSilenced(), silence(), and resume(). When a listener is silenced, it will not call its callback.
> - Like event listeners, observer listener handles also have methods to silence and resume the listener. While an observer is silenced, it will still track state changes internally, meaning the old value on the next call after being resumed will be the last value it observed, including those observed while it was silenced. It simply won't fire its callback while it is silenced.

**Comment by evs-chris** [comment]
You can use a strict observer if you `===` comparisons are ok for the observer. Otherwise, you can silence the observer while you're setting and resume it afterwards.

**Comment by ceremcem** [comment]
@fskreuz yes. When a value is got from `the network source`, it is `.set()` to the component variable. If the component's variable is changed within webapp, it is sent to `the network source`. As the newly received value causes re-send of the exact same value, it causes an infinite loop. 

@evs-chris I didn't understand how to use "a strict observer". Is it somewhere in the documentation?

**Comment by evs-chris** [comment]
It's an option. See https://ractive.js.org/api/instance-methods/#ractiveobserve

**Comment by ceremcem** [comment]
Unfortunately `{strict: true}` has no effect in my case. I had solved the problem by "silencing" the observer: 

```ls
        __ = this 
        silenced = no 
        @observe \testValue, (_new) ->
            if silenced 
                silenced := no 
                return 
            log.log "sending #{_new}"
            actor.send-val _new

        actor.receive = (msg) ->
            silenced := yes 
            __.set \testValue, msg.payload.IoMessage.val
```

**Comment by ceremcem** [comment]
It looks a bit dirty. I wish we had `ractive.set('keypath', value[, {fireObserver: false}])` option.

**Comment by evs-chris** [comment]
@ceremcem silencing is actually built in to observers in 0.9, though it looks like I missed that part in the API docs.

```ls
        __ = this
        handle = @observe \testValue, (_new) ->
            handle.silence
            log.log "sending #{_new}"
            actor.send-val _new
            handle.resume

        actor.receive = (msg) -> 
            __.set \testValue, msg.payload.IoMessage.val
```

_I think_. I haven't played with livescript in quite some time. You may also have to adjust it a bit if the `actor` is asynchronous.

**Comment by ceremcem** [comment]
Following code works as expected: 

```ls
        handle = @observe \testValue, (_new) ~>
            log.log "sending #{_new}"
            actor.send-val _new

        actor.receive = (msg) ~>
            handle.silence!
            @set \testValue, msg.payload.IoMessage.val
            handle.resume!
```

Looks quite nicer. Thank you!
