### ISSUE TITLE
Question: component data availability in lifecycle

### ISSUE THREAD

**Issue by dodyg** [ractivejs/ractive#3004]
I am using version 0.8.14

I have the following component declaration
```
<Concurrence aclId={{acl.id}} common={{common}} initial={{initialConcurrences}} concurrence={{acl.concurrence}} comments={{comments}} decisionAuthorities={{decisionAuthorities}} />
```

At which component lifecycle will these data be available?

I tried at ```onrender``` and ```oncomplete``` but the data are not available, e.g.:

```
   onrender: function () {
            const self = this
            alert(self.get('aclId'));
```

will alert ```undefined```.

My goal is to setup ```select2``` jquery plugin in my dropdown e.g 
```
 onrender: function () {
            const self = this
            const globalPsfa: any = $('#concurrence_global_psfa');
            globalPsfa.select2(concurrenceSelect2Option());
            globalPsfa.val(["102"]).trigger('change');
}
```

however none of the passed data to the component are available at the lifecycles I tried.

**Comment by dodyg** [comment]
Never mind. I use this.observe instead.

**Comment by ghost** [comment]
Data is available as early as `onconfig`. Lifecycle events after that (i.e. `oninit`, `onrender` and `oncomplete`) should already have access to that data. [See example](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4BjAewDssACAYVIFsAHCtclKgXioCUliUAlgDc0AOjQAPdOQAmACmAAdcopQzUSSFWBV6GAOZaA5Ear5lq9E2TotAAwspVwYHv04cju3kcUB5ARQ5AEolFScUMkpSBDEEUn05FDABDFF9NCCjNyNg4MdPchxggG4Lcl5+YTQFRzQEYwAjUhkATyMfcKRGRlYZLRQYAFc0TtUyJhY2DC0dOknyVnZzcPUUTW0qADNSUmMACXr4vCoAdVIYBBkAQlMVyzRrVDR7R1UAHnnmRbZdAw5FCAXDtSB5AVQAPQAPi8ymKuCAA). Having them `undefined` tells me that whatever is supplying the data has not supplied it yet (which isn't mentioned in the OP).
