### ISSUE TITLE
Object.assign issue on Android (Cordova app)

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#3008]
Hi, guys!

Bad news, "Ractive is not defined" exception on some Android devices (seems where webview is not Chrome-based) in Cordova app. Quick investigation showed that the problem in Object.assign usage. (legacy variant, extendObj() function, works fine) Seems, that on iOS (Safari-based webview) it won't work too.

I guess it's designed to use some polyfill for that? It's a little bit strange, because of Object.assign is a very common thing in Ractive. Though if it's "design intent", we can skip it.

Thx!

**Comment by ghost** [comment]
As of 0.9, polyfills were moved out of the core and into a separate polyfill file. https://ractive.js.org/get-started/support/#legacy-browsers

**Comment by PaulMaly** [comment]
Hi @fskreuz ! Yep, I know! But for my opinion mobile Safari is not "legacy browser" it's severe reality ))))

**Comment by ghost** [comment]
Can you provide us with which version of Ractive you're using, the version of the platforms being tested, and a stack trace for both platforms? And if possible, reproducible code?

**Comment by PaulMaly** [comment]
Unfortunately, I can't provide details, because I've already handled this problem and moved further. I caught this exception on emulator under 5.0 Android's version. Ractive version was latest (0.9.1). I'm sure that "Ractive is not defined" happened because of Object.assign(). 

Potential problems in iOS is my assumption based on this browser support info: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by evs-chris** [comment]
Just wanted to note that _any_ flavor of internet explorer requires the polyfills to be loaded, because we no longer supply a Promise polyfill in core either. If you're supporting anything other than evergreens, you probably want to throw the polyfills in before ractive if you don't already have a set of polyfills in place.

**Comment by evs-chris** [comment]
The polyfills have been pared down to minimum and are included in the main ractive build again.
