### ISSUE TITLE
Decorator not rendered as part of toHTML() result

### ISSUE THREAD

**Issue by dirksen** [ractivejs/ractive#3009]
## Description:
When calling ractive.toHTML(), the output does not include decorator output, even though the decorator is rendered in the browser.

## Versions affected:
edge

## Platforms affected:
all browser/server side

## Reproduction:
http://jsfiddle.net/v8axk1oe/7/

## Code:
```
<div id='container'></div>

<script id="template1" type="x-template">
  <h1 as-foo></h1>
</script>

<script>
window.ractive = new Ractive({
  el: 'container',
  template: '#template1',
  decorators: {
    foo: function(node) {
      node.innerHTML = 'YAY';
      return {
        teardown: function() {},
      }
    },
  }
});
console.log(ractive.toHTML()) // prints <h1></h1> on console
</script>
```

**Comment by evs-chris** [comment]
A decorator is a function that takes a DOM node and returns a handle to tear itself down and optionally update itself. `toHTML` takes the vDOM template and renders it to a string, so there are no DOM nodes ever created. If you need to render decorators server-side, your best bet is to bring your own DOM, like jsdom.

We could possibly add an optional mode for decorators that would allow them to mess with the string output for the element. Something like:

```js
Ractive.decorators.foo = function(node, args) {
  node.innerHTML = 'YAY';
  return { teardown() {}; }
};

Ractive.decorators.foo.toHTML = function(string, args) {
  // do something with string?
};
```

**Comment by dirksen** [comment]
Thanks for the response. I'd like to give jsdom a try, but found no example. Could you provide one?

**Comment by evs-chris** [comment]
I've not used it personally, but it looks like you could just do something like this:

```js
const jsdom = require('jsdom');
const doc = new jsdom().window.document;
const div = doc.createElement('div');
new Ractive({
  template: '...',
  target: div
});

console.log(div.innerHTML);
```
