### ISSUE TITLE
{{#each}} not updated with ractive.set(keypath, arr, {shuffle:'prop'})

### ISSUE THREAD

**Issue by paulie4** [ractivejs/ractive#3010]
## Description:
Although ractive.set(keypath, arr, {shuffle:'prop'}) does correctly reorder the DOM elements in an {{#each}} section, it does not update any of the other values in it.

## Versions affected:
Ractive 0.9+

## Reproduction:
[Ractive playground example](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQBRADyQFsAHBNAAgHsAze4YAYjSQGMwcc9AG5IEAV0z0AdoxT0A5mhQoAllPn0x1ACao02+itYYwY5swRqNI8ZkgAdKQB4ARjAB8rj46faVQzwB6PwCQAgx4HkYpLHoYegBeaTQAd3oAJV5VITQACmB7GEd6Evo0BEh6AHIQqrxC4tL0GmR0SoADBqlS0vYuXjB6JBgYARVtSvZxgTxpKjRJ4Cl5gS93dkDuPgEunpK13b3hmAA6AEYT5coGJPZj88uVnAOi7r2Xxp7XMWVopikALQ8Sw8ADWCXsIAAAigwCoMCcMEpclVjnV6ABtYDjSAAFlmVwWVSkqVxVXwbBxZwJ80gxNSZ3Js2xEwArDgALrMkxmCxE8bkgCUkPcPPMdHoLgAntUBU5Ai4fihou5Dj1YfC4mhGDBtGgYBh6LCGAARADyAFkynRrlIUIbFXJtIxJDI5FpdOghlIZTYJIa1EawAx7KH7H0tvxnm5Va89vQPm8vo7ld1okCQeDITC4QiPXoUWjhSB3Bq8zoC6iRlVBfKUyq1aVna7ZPQUjrQYn4133vW04DgSowRDoWWTvn0IWRg9CTWRWOJ3kq6cLrPawqlQ243tm4a3W2Oz3k95t8nN-2M0Os6Pc4jkcuZ-N0Tn4SdFCgpyvHtca8XS7ekQ-B9VyfAlUgANVEdc+1jT4mxdPdW3bGBOxjRt9jQ09Sm+X4L0HYdswXCtJ2XdFgGYHUeAWI0YAkHA-yIz0lzRZkKJgKjKhQWi0Houtz1gpN4JbORkNQk84Iw8TBIw89-kvAib1fRdP0fH9WMo6iuLohjb2U4DvzQMi2I4mjtL43CBPjMtDENY1-gQGUNXUINUAPFCMCPbDMIk+gACkAGUzQAOURLirCMKVcmOQVFgC4LQpgcLmEi6Kdiw9p6iwz0kEmY5KgxdDKQmehqTma5KiqFRmkZfBCpZSoACYaXK2Vmgapk6pxegAGZmuoyrmm6jqsJKer6HxMr+qqtBKDJWqRqKypWT6irpsoVlhsaDl5sceiAG5cCAA)

## Code:
HTML:
```html
Example of {{#each}} values not getting updated if shuffling values:
<br><br>
<div></div>
```

JavaScript:
```javascript
const r = new Ractive({
    el: 'div',
    template: `
      {{#each arr}}id: {{id}}, name: {{name}}<br>{{/each}}
      <br>
      arr.1.name = {{arr.1.name}}<br>
      <br>
      <button on-click="@this.set('arr', [{id:4, name:'new4'}, {id:1, name:'new1'}, {id:5}], {shuffle:'id'})">shuffle by 'id'</button>
      this reorders the DOM elements but does not update any values in the \\{{#each}}<br>
      <br>
      <button on-click="@this.update('arr')">this.update('arr')</button>
      does not work<br>
      <br>
      <button on-click="@this.update('arr.1.name')">this.update('arr.1.name')</button>
      does not work<br>
      <br>
      <button on-click="@this.set('arr.1.name', @this.get('arr.1.name'))">this.set('arr.1.name', newVal)</button>
      does not work<br>
      <br>
      <button on-click="@this.update('arr', {force: true})">this.update('arr', {force: true})</button>
      does not work<br>
      <br>
      <button on-click="@this.update('arr.1.name', {force: true})">this.update('arr.1.name', {force: true})</button>
      this is the only thing that works<br>
      <br>
      JSON.stringify(arr): {{JSON.stringify(arr)}}
    `,
    data: {arr: [
      {id: 1, name: 'item1'},
      {id: 2, name: 'item2'},
      {id: 3, name: 'item3'},
      {id: 4, name: 'item4'},
      {id: 5, name: 'item5'},
  ]},
});
```

**Comment by evs-chris** [comment]
Edge (and 0.9.2 when it's cut) will now assume that `set(..., {shuffle: true})` is not safe, meaning it will also invalidate any view associated with the target keypath. Before this, it was treated as a specialized splice operation.

Thanks for the report!

**Comment by paulie4** [comment]
Thank you for the super-fast turnaround!
