### ISSUE TITLE
on-click event called twice

### ISSUE THREAD

**Issue by danielhoey** [ractivejs/ractive#3012]
## Description:
Clicking an element once causes the click event to be called twice. Seems to be related to rendering another on-click element as a result of the first event.

## Versions affected:
0.9.1, edge

## Platforms affected:
Tested on Firefox and Chrome on Linux

## Reproduction:
See this jsfiddle: https://jsfiddle.net/yb3erzda/1/
Click the "add item (buggy)" button twice, the second click will add 2 items (should just add 1 item)

## Code:
  
    <div id="ractive_container">
    </div>

    <script id="template" type="text/ractive">
      
      <div>
        {{#each items}}
          <button on-click="something">X</button>
        {{/each}}
        <button on-click="@.push('items', '')">add item</button>
      </div>
      
      
      {{#each items}}
        <button on-click="something">X</button>
      {{/each}}
      <button on-click="@.push('items', '')">add item</button>
    </script>

    <script type="text/javascript">
      new Ractive({el: '#ractive_container', template: '#template', data: {items: []}});
    </script>

**Comment by evs-chris** [comment]
There was a bug with delegation and elements that happen to be children of a delegation target but not subject to delegation themselves. This should be fixed on edge and will go out with 0.9.2 when it is cut.

Thanks for the report!
