### ISSUE TITLE
Please put back the access to Ractive Versions on the Website

### ISSUE THREAD

**Issue by lnryan** [ractivejs/ractive#3013]
## Description:
Until recently, the Ractive.js website allowed navigation between versions. This seems to have disappeared with the switch to this new top-navigation style menu, which by the way, makes it really hard to find things. 

Having the versions available was very helpful in identifying differences in features and functionality and in being able to rollback if a breaking change (to our own development) was introduced. 

So please consider putting it - or _some basic versioning information_ back. Thanks.

## Versions affected:
all of them.

**Comment by evs-chris** [comment]
We're still working on getting multiple versions of the docs available in a more usable way, but until we get that figured out, the legacy docs are available at https://ractive.js.org/v0.x/0.8/get-started

**Comment by ghost** [comment]
Closing in favor of https://github.com/ractivejs/ractivejs.github.io/issues/54
