### ISSUE TITLE
How to register/define a function globally

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3016]
## Description:

I need to define `myfunction` in a component's javascript file as if I would define as: 

```ls
# main ractive instance 
ractive = new Ractive {
    ...
    data: 
        myfunction: (arg1, arg2) -> 
             return arg1 or arg2
}
```

How can I define the same function in a component file in order to use it globally? 

I tried the following: 
```ls 
# mycomponent.ls 

Ractive.defaults.data.myfunction = (arg1, arg2) -> 
    return arg1 or arg2
```
but it is not working (and I'm not sure if it would).

**Comment by kouts** [comment]
```Ractive.defaults.data``` should work, but I don't know what it takes
to declare ```Ractive.defaults.data.myfunction``` inside a component,
I usually specify such global methods in a separate file before Ractive even inits.
E.g
```
(function(){
    var helpers = Ractive.defaults.data;
    helpers.myfunc1 = function(){
        return 'foo';
    }
    helpers.myfunc2 = function(){
        return 'bar';
    }
}());

var ractive = new Ractive({
   // options here
});
```

**Comment by ghost** [comment]
Yep, I would split this off to a separate file and load it in the entry point (which would load it ahead) since it's technically a dependency of the app and not just the component. Otherwise, it wouldn't be global to begin with.

Alternatively, you can just augment your component's data on definition with `Object.assign`. But you'll have to do this for every component that needs that function.

```js
const mixins = {
  myFunc: ...
}

Ractive.extend({
  data: Object.assign({
    // data
  }, mixins);
})
```

**Comment by ceremcem** [comment]
@kouts I did the exact same thing and `mycomponent.ls` had the following contents: 

```ls

# mycomponent.ls 

Ractive.defaults.data.myfunction = (arg1, arg2) -> 
    return arg1 or arg2

Ractive.component['my-component'] = Ractive.extends do 
    template: ...
    ...
```
Which seems the same thing as you recommended. 

But, the weird thing is that I tried again and it worked o_O 
Now `myfunction` can be used globally but defined in the component's file. Thank you. 

@fskreuz Yes, this function is a dependency of the app but only if this component is included in the application. 

To be specific, it's a `login-button` component. If the developer prefers to include the `login-button` component in his application, then a `checkPermissionsFor()` function is registered globally to be used in the application.
