### ISSUE TITLE
animate broken when magic is true

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#3018]
## Description:
Instead of smooth change, values updated by steps when you click :(

## Versions affected:
0.8.14
works fine with 0.7.3, and 0.9.1

## Platforms affected:
Chrome on Win

## Reproduction:
http://jsfiddle.net/Inversion/e8tjb4e8/
if you comment line with magic:true — works fine

**Comment by ghost** [comment]
Magic was disabled in 0.8 and removed completely in 0.9 due to [various reasons](https://github.com/ractivejs/ractive/pull/2885). Still a bug in 0.8 nonetheless. Since you're using `ractive.animate()`, you can just remove `magic` unless the demo only represents the bug and `magic` is needed in the actual app.

**Comment by Inversion-des** [comment]
>Magic was disabled in 0.8  

Not it is not. Works fine in 0.8.14

>… magic is needed in the actual app

Actually I found this problem in a real app trying to migrate to 0.8. 
And I cannot just remove magic — see this my [sample case](https://stackoverflow.com/questions/44759630/how-to-handle-global-config-without-magic-mode).

**Comment by ghost** [comment]
Ahh, what I meant was deprecated, not disabled. Running a `ractive.update()` after setting the data should do the trick.

**Comment by evs-chris** [comment]
In the case described in that SO question, you would want to use a cross-instance [link](//ractive.js.org/api/#ractivelink), or possibly [`@shared`](//ractive.js.org/api/#shared) data. I'll poke at the magic adaptor in the 0.8 case and see if I can figure out what's happening to it.

**Comment by Inversion-des** [comment]
>cross-instance link

I can see that arguments are strings there, so how can I link some external data for Ractive instance?

>or possibly `@shared` data

As I understand it's a template special variable. I do not know how to access it without using any Ractive instance.
I also tried to use `@global.conf` but it is not updated when I change `window.conf` :(

>I'll poke at the magic adaptor in the 0.8

I will appreciate it. Currently it is the critical issue for migrating from 0.7

**Comment by evs-chris** [comment]
I should note that these two solutions are for 0.9:

### linking
You can set up a root/storage instance for linking e.g.
```js
const storage = new Ractive({ data: { conf } });
const instance1 = new Ractive({ ... });
instance1.link('conf', 'conf', { ractive: storage });
```

With that, any changes to the `storage` instance `conf` will automatically show up across any links.

### shared
`@shared` can be accessed from API methods e.g. `ractive.set('@shared.conf.whatever', 42)`, so you just need to reference `@shared.conf` wherever it's needed and use a ractive instance to update it externall where appropriate.

### global
If you need to stay 0.8 friendly, you can use `@global.conf`, but you either need to use ractive to update it e.g. `ractive.set('@global.conf.whatever', 42)` or tell ractive that it has updated e.g. `conf.whatever = 42; ractive.update('@global.conf')`.

**Comment by Inversion-des** [comment]
>instance1.link('conf', 'conf', { ractive: storage });

There third argument is not covered in docs

This linking for each instance is quite cumbersome compared to conf:conf

In all these ways it is better to have dedicated storage Ractive instance for updating data, and linking needed if you want to use `conf` instead of `@shared.conf`.

So I can see it is possible, but needs some changes for conf and some inheritance to hide linking…
I will really miss the magic mode…

Related question.
I also used magic to have more clear code when working with model (I saw such in Vue.js). 
I used `@d = @viewmodel.value` to be able to do for example:
`@d.val = '('+@d.val + ')'`
Instead of
`@set('val', '(' + @get('val') + ')')`
And I really like it.

Now do we have any chance for something like this without magic mode?

**Comment by evs-chris** [comment]
Magic mode could come back as a plugin using the code that was removed in 0.9 - if you don't mind the bugs and corner cases that are associated with it. There's also a proxy-based implementation over in #3002.

**Comment by evs-chris** [comment]
v0.8-dev _should_ have working `animate` with `magic: true`. It will go out with 0.8.15 when it is cut. Thanks for the report!

**Comment by Inversion-des** [comment]
Works for me. Thank you!
