### ISSUE TITLE
Can we replace a default tag with our custom component?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3022]
## Description:

I need to change all behavior of `<a></a>` tag. That's why, I made the following component: 

```ls
Ractive.components.a = Ractive.extend do 
    template = '<a href="{{href}}" class="{{class}}" style="{{style}}">{{yield}}</a>'
```

which caused a stackoverflow because Ractive tried to replace `a` tag recursively. That's why, I tried a workaround: 
```ls
Ractive.components.a = Ractive.extend do 
    template = '<span href="{{href}}" class="{{class}}" style="{{style}}">{{yield}}</span>'
```
obviously with a few lines of CSS to make it look like an anchor. 

## Problem 

That worked fine so far, but it doesn't play well with 3rd party libraries (SemanticUI in this case) because their CSS looks for `a` tag, not a `span` tag to decorate.
Which makes me return to the beginning. I need to replace the default tag, but not in a recursive manner. 

Is there any way to do this?

## Versions affected:

0.9.1

**Comment by kouts** [comment]
Can't you just name your component ```mya``` or something and make it render a real ```<a href ... ``` ?

**Comment by ceremcem** [comment]
Current workaround is just like that and it doesn't hurt much. But as I had to rewrite all my anchors (in the menus, in the pages, in everywhere), it sounded like a good idea to replace a default tag with my custom component

## Rationale

I'm building an application, [ScadaJS](https://github.com/aktos-io/scada.js), much like AngularJS, but specialized for building SCADA systems. One of the main goals was making user learn only a few things to get up and running (as Ractive also cares about). What I meant is that a user will only have to learn basic Mustache syntax and that's it. Adding anything to remember makes things look uglier. (Which is one of the exact reasons I prefer Ractive over Vue or the others)


## Conclusion 

If it is expensive from the point of view of performance or development efforts, this issue could be closed. 

If it sounds like a goood idea, I love to hear the way.

**Comment by evs-chris** [comment]
As of 0.9, this is indeed possible. You just have to [block the component from trying to use itself](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR4gCGeAGMA9gDssNJDQY0ASkgkpqaAHRoAHuhlkAFMCYymKdAFsADsnSQaAchKKwMNADNmIAMS8CBQyANY0wMAAnhRoCGQ4OAJIPM545pbSdrJoMigYTsAKTl5ICBhoNDjmOACUANzpMtJyKAq2tko0MmgA7qrqmlRopulWbJwoTs5+KONcqaM29qhoU248SEk8NOsAjFsLFiiZttm5+eEKldU1uEA) by setting any component names as which it might appear to `false`.

__Edit:__ derped the example.

**Comment by ceremcem** [comment]
Thank you! Things look way better now!

**Comment by ceremcem** [comment]
(Fixed [the example](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR4gCGeACUkAYxTU0AOmkB7ALYAHZQDs0WlBgVIaDGlNnyFaAB7otZABTAmWpinQbk6SDQDkJI2AwaABmzCAAxLwIFFoA1jTAwACeFGgIZDg4Akg8PnjOrioa2rr63sA0SN7BSAgYaDQ4zjgAlADcBVoqWliV6urGNDoA7qYyclRojgVubJwo3j7hKHNceTPu6p5oi-48SNk8NHsAjIc+zS24QA))

**Comment by ceremcem** [comment]
How can we re-fire any Ractive event? For example, original node: 

```
<a on-click="doMyStuff">hello</a>
```
When we replaced the original node with our custom component, the `on-click=...` stuff is lost. 

For example, when we clicked `aaa` link, `hello` event is fired in [this example](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR4gCGeACUkAYxTU0AOmkB7ALYAHZQDs0WlBgVIkNBjSmz5CtAA90WsgApgTLUxToNydJBoByEsZgMGgAZswgAMS8CBRaANY0wMAAnhRoCGQ4OAJIPL54Lm4qGtq6+j7ANEg+IUgIGGg0OC44AJQA3IVaKlpYVerqJjQ6AO5mMnJUaE6F7mycKD6+ESjzXPmzHupeaEsBNNoAtNIx0nHhYOkIyrxGRjk8NPtHJxRn4SiXwbwARn8PG1cKG0sQoixoIQArt05NoaA5WolZm5PhQDNoZkC3NjwFcblAIdCLBiAPpoKZ6VrOLHcWk9DDKBCKa7sBwsS4Ia40cllOgYCEUYJkACELA6yNp+AlOM+aG+BKhMIopJ5lOp2NpRW0DKZChZbMIX0aqpQfIFQtFIHFNLcUppbVmzS0bVwQA). How can we make the same thing [in this example](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR4gCGeACUkAYxTU0AOmkB7ALYAHZQDs0WlBgVIaDGlNnyFaAB7otZABTAmWpinQbk6SDQDkJI2AwaABmzCAAxLwIFFoA1jTAwACeFGgIZDg4Akg8PnjOrioa2rr63sA0SN7BSAgYaDQ4zjgAlADcBVoqWliV6urGNDoA7qYyclRojgVubJwo3j7hKHNceTPu6p5oi-402gC00tHSsWFgaQjKvEi3SNk8NHuHxxSnYSgXQbwARn8P6xcKG0MQoCxowQArl05NoaPYWgkZq5PhQDNppkDXNjwJdrlAIdDzBiAPpoSZ6FpOLHcWndDDKBCKK7sewsC4IK40cmlOgYCEUIJkACELHayNp+AlOM+aG+BKhMIopJ5lOp2NphW0DKZChZbMIXwaqpQfIFQtFIHFNNcUpprRmTS0rVwQA)?

**Comment by ghost** [comment]
Ractive doesn't immediately listen to template events. So what happens is that nobody is listening to the real `<a>`. What you could do is [fire a proxy `click` to the real `<a>`](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR4gCGeACUkAYxTU0AOmkB7ALYAHZQDs0WlBgVIaDGlNnyFaAB7otZABTAmWpinQbk6SDQDkJI2AwaABmzCAAxCw02gC00ggU0gDWYfGJSbwJWkk0wMAAnhRoCGQ4OAJIPD54zq4qGtq6+t7ANEjewUgIGGg0OM44AJQA3LVaKlpYberqxjQ6AO6mMnJUaI61bmycKN4+4SjbXNWb7uqeaHv+0VpxCclhYMUIyrxI70gVPDTXsWkPLBQTyCvAARuCvicXChtBQtBRdjRggBXcZybQ0eyDXKbVxAigGbQbaGuUngZ6vKBI1HmIkAfTQaz0gycJO47ImGGUCEUL3Y9m2yNUTQwg1x7Lq2i5PIUfPsLCeCBeNEZTToGCRFCCZAAhCwRuLXPhDdxCMC0CwOjT0Vp7AymSgWSbJZNubzlPzAeaVQ71ZrtXqQAa2Uaamyhpt+lohrggA) and listen to the `proxy` click on the enclosing component.

```
Ractive.components.a = Ractive.extend({
	template: '<a href="#" on-click="click">link {{yield}}</a>',
	components: { a: false }
});

const app = new Ractive({
	target: '#target',
	template: '<a on-click="hello">aaaa</a> <a on-click="there">bbb</a>',
	oninit: function () {
		this.on({
			"hello": function(_event){
				console.log(arguments)
				console.log("hello event is fired!");
			},
			"there": function(_event){
				console.log("there event is fired!");
			},
		})
	}
})
```
You'll have to do this for every possible event tho, as far as I'm aware of.

**Comment by evs-chris** [comment]
You can pass through plain attributes, but event handlers stick at the component level, so I'd just reproxy any events you expect to use [like this](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR4gCGeACUkAYxTU0AOmkB7ALYAHZQDs0WlBgVIaDGlNnyFaAB7otZABTAmWpinQbk6SDQDkJI2AwaABmzCAAxCw0wMAAnhRoCGQ01igwSAC0qGkUAEYArugYODg02hnSCBTSANZhldU1vFVaNdFxCUklAkg8PnjOrtkweYWY3gDaALoDLigqGtq6+t7ANEjewUgIGGg0OM44AJQA3INaKlpY6+rqxjQ6AO6mMnJUaI6DbmycKN4+4RQPy4-S+7nUnjQ-38ZS0FSqtTCYESCGUUTkKAQaDCGDUXDAFC07F4SFJSB6PBoMPKDURLBQyKCvFyLIpoLm2lWX1cyIQqM2+Qucm09gA+mh3nojk45q5XJdcViFKj2PYWLzUSlJSg6BgaMEKEEyABCFinbkofAWhloIICoUUEXi7XSi3y7SKxQqtWERl7CXLXX6w1oE1ms6yy1fA5aY4nXBAA). You can do some template twiddling if you want to just grab events that are attached to the component.

**Comment by ghost** [comment]
<s>We need to document that `extra-attributes`. :P</s> omg I'm blind. 😂

**Comment by evs-chris** [comment]
It [_kinda_](https://ractive.js.org/api/#attributes) is 😁

**Comment by evs-chris** [comment]
Question: _should_ events be considered along with normal attributes? Other directives, like `class-` are, but they also aren't directives at the template level - they're more runtime directives. As it stands, events, decorators, and transitions wouldn't be considered for `extra-attributes`. Of course, transitions and decorators aren't valid on a component.

**Comment by ceremcem** [comment]
@fskreuz Thank you, actually your example let me achieve [the main goal](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR4gCGeACUkAYxTU0AOmkB7ALYAHZQDs0WlBgVIaDGlNnyFaAB7otZABTAmWpinQbk6SDQDkJI2AwaABmzCAAxCw02gC00ggU0gDWYfGJSbwJWkk0wMAAnhRoCGQ4OAJIPD54zq7aFFoUKN7BAK5a5tr2AJROLtxuYBQGXX2u4yhpyS3tnVo9YwMTSAhoMCj2LChDGHS722g0ALIAkgAqRzQARvk0Khrauig0-jws3bVLKDifrjgf-Xwn3umh0egw3mANCQLRWGEOPy0-wA3LUOtosND1OpjDQdAB3UwyORUNCOT4oNicZq+cKUjhcaoUtAeVBobx+IyxKYpFhgYoIZS8JAipAVHgvLlaOIJZJhA5BXhXZXipn9eqNGltDpybQ0Hq5X6DYYKUZG8bgAVCqA0bVzewAfTQpL0vXNAxUWgwylWCkF7HsVNaqieGABEwmnu9vv9m0tCEFNGdTz2tooQTIAEJ3qj+hMgXmloR+YqbXbdfMnS6UG7C5GMT7FLGtiXDsm9Kngum0Fmc+6C-nw99nP9cEA).
