### ISSUE TITLE
Strange issue with "sortable" as component parameter

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3023]
I detected a small issue with the `{{>extra-attributes}}` mapping. Basically, if an attribute is called `sortable`, its valuesimply disappears during the mapping.

---

Template: `<fancy class="foo" sortable="disappeared" other="true">hmmm</fancy>`

Component: `<div><p {{>extra-attributes}}>{{yield}}</p></div>`

Result: `<div><p class="foo" sortable="" other="true">hmmm</p></div>`

---

Snippet:

https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutAZkXYkAngAIAvKOLlqdBAA8yXJAApgAHXbqyS1gBsiSyKIDkAHiTUAfGZajgwKwrIwiAWkMuKAIwCuS3AwMKwdhCgQ9JCCzAHoWGxjLKisTLE1tTxgffwRcY2BRJiIWAEE9PWMXXwRRbHSyDkZ9BCNRPl8hSg4VAEp7eu0qIhhRJIlRMjAKXj4KdlUTJJMegG4BskZ2XAY9Oj0GFBUk2gYcmAAJABUAWQAZVfqMTQwHrXYhkZHJTgB3KVJKDQ1PUIsYTN4GEhhKl6roWAZWuYBEIxCQDLhcOJ1CA+AwGNjRNsYGQiN5dliQJZcMUWAhhsgCQxJggYBSqghsVYwEwebFkSIUs9ViAcGR4JggA

**Comment by dagnelies** [comment]
Ok, I found the issue, it's because the "sortable" attribute is defined in "booleanAttributes".

See:

https://github.com/ractivejs/ractive/search?q=booleanAttributes+&type=Code&utf8=%E2%9C%93

Basically, if an attribute is in this list, its value will be stripped ...which makes sense for normal DOM nodes. 

However, it leads to surprises as we see for components.

More globally, perhaps we should not strip them at all since other scripts might read/use such attributes on normal DOM nodes. ...So, what do you think, should we add one more flag, or just drop the value stripping?

**Comment by evs-chris** [comment]
Hmmmm... does anyone know if leaving the attribute value is detrimental when supplied for boolean attributes? I imagine that most people wouldn't supply a value if it's not required. It looks like this particular attribute only applies to `table` elements, so it seems extra odd to strip it off of _all_ elements.

**Comment by dagnelies** [comment]
I think it is made so that things like `disabled="{{value}}"` become `disabled` when true and removed when false instead of `disabled="false"`.

I don't know if leaving the value in attributes instead of removing it completely can have any impact in some cases or not. Usually, it does not make a difference ...but who knows, we're dealing with multiple elements / attributes / browsers here.
