### ISSUE TITLE
Support css on a per-instance level

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#3024]
## Description:

From https://github.com/ractivejs/ractive/issues/2365.

**Comment by evs-chris** [comment]
I don't imagine it would hurt anything. It would just require getting a css id and not bailing if the instance isn't a component. It might get weird to try to supply css on an instance of a component, though, so that would need to be tested. PR anyone? 😀

**Comment by ghost** [comment]
I can probably play with this one since I've been there... once. 😛 

re: CSS on instance vs CSS on component, I would think the instance one overrides the component one completely. Not sure how it is with templates, but the behavior should probably be the same.

**Comment by evs-chris** [comment]
In the context of plugins, it starts to make more sense to allow easy use of ractive's managed style container. For root-level styles, looks like more the case for this, there's now an experimental `Ractive.addStyle(id: string, css: function|string)` that allows you to add css text and/or functions to managed style tag.

Any functions you add will be based on data at the `Ractive` level, so only `Ractive.styleSet(...)` will cause a style update for functions added via `Ractive.addStyle`.
