### ISSUE TITLE
Promise error on IE 11

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3026]
Hi,

Currently, ractive latest/edge breaks on IE 11 due to missing `Promise` object.

https://caniuse.com/#search=Promise

Probably introduced through #2801

I'm amazed this did not pop up earlier. 😲

**Comment by kouts** [comment]
Yes, you can solve this by adding the polyfill file and after loading Ractive insert
```Ractive.Promise = Promise;```

My opinion though is to support at least IE11 without polyfills, just my 2c.

**Comment by ghost** [comment]
0.9 doesn't ship with a legacy build (one with built-in polyfills). Instead, it ships the polyfills on a separate file. Load it before Ractive for legacy browser support. Otherwise, if you only intend to support newer browsers or already have another polyfill in place (i.e. ES5 shim, ES6 shim, etc.), you can just use Ractive as is.

If plugins rely on `Ractive.Promise` (which was also removed), you can just stick the global promise (polyfilled or not) to as `Ractive.Promise` as @kouts mentioned.

**Comment by dagnelies** [comment]
Considering IE 11 to be "legacy" is a bit harsh, don't you think?

**Comment by ghost** [comment]
I just like to call IE legacy 😛 

But IE has [ceased feature development](https://en.wikipedia.org/wiki/Internet_Explorer#End_of_life). Pinning a library to a browser that's half-dead would only make it hard to move forward. IE11 is 99% ES5 compliant and for ES6, it will only need 3 APIs polyfilled - which isn't that bad really.

Technically, the polyfill + Ractive = legacy build, sort of. The only difference is that the polyfills are moved out of the library and into a separate file. It also makes it easy to use another polyfill. I'm not a fan of packaging own polyfills when other polyfills are better tested.

**Comment by sabob** [comment]
I think the argument is if everyone is going to include polyfill.js anyway to support IE11, then maybe Ractive should just include it by default? Batteries is included...

**Comment by MartinKolarik** [comment]
I have to agree with @sabob on this. IE 11 should be supported by default.

**Comment by dagnelies** [comment]
Me too, I don't care about IE <= 10, but IE 11 is still widespread and should be supported for a couple of years IMHO.

In debug mode, a check could be performed when starting and mention something like "Error: this legacy browser is not supported, please use polyfills at `<some-url>`.

**Comment by evs-chris** [comment]
This should now be fixed on edge, and will also be addressed for 0.9.3 when it is cut.
