### ISSUE TITLE
Transitions: TypeError: invalid 'in' operand params[0]

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#3029]
## Description:
I'm migrating my web-app from 0.8.14 to 0.9.2 right now. 

I've encountered a strange bug regarding transitions. This template code `<div fade-in-out="300">Test</div>` throws an error in Ractive `TypeError: invalid 'in' operand params[0]` on line 14947 in method  `Transition.prototype.shouldFire` where it performs this check:  `if ( params && params[0] && 'nested' in params[0] ) {`

While debugging it I see that the value of `params[0]` is `300` (type number) when passing the above check, but it is expected to be an object.

When I use the following template code instead `<div fade-in-out="{duration:300}">Test</div>` everything works fine.

## Versions affected:
0.9.2

## Platforms affected:
Chrome 59, Firefox 54

## Reproduction:
~~Unfortunately I've not been able to produce a minimal test case so far. It always works in those minimal cases. I've not found the exact trigger of this problem.~~

**UPDATE**
Reduced test case: https://jsfiddle.net/lejared/0zatne42/2/
I've found that `Transition.prototype.shouldFire` won't be called at all if the transitioned node is not nested within another node.

**Comment by ghost** [comment]
Notes: Code appears to assume long-hand notation when transition args are allowed string or numeric inputs.

Also, relevant PR https://github.com/ractivejs/ractive/pull/2773
