### ISSUE TITLE
Manually fired events don't seem to be able to extend Event's context

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#3033]
## Description:

From [the docs](https://ractive.js.org/api/#ractivefire):
> [context] (context|object): A context object to reuse for the event or an object with properties to assign to a new context object. **If you need to pass arguments but don't need to provide context, pass an empty object ({}) before the additional arguments.**

However, extending event's context doesn't seem to work.
See example below.

## Versions affected:
0.9.2

## Platforms affected:
reproduced on Chrome & Safari (macOS)

## Reproduction:
https://jsfiddle.net/4ervr8kv/3/

```javascript
const r = window.r = new Ractive({
  el: '#main',
  template: '#template',
  data: {
  },

  oninit() {
    this.on('myEvent', (...args) => {
      console.info(`Number of arguments: ${args.length}`, args);
    });

    // this.on('myEvent'...) should have its context extended by { wontExtendContext: 'this will be argument 1' }, no other argument.
    // will actually have a sort-of clear Context, and an additional argument: { wontExtendContext: 'this will be argument 1' }
    // SHOULD RESULT IN 1 ARGUMENT, currently 2
    this.fire('myEvent', { wontExtendContext: 'this will be argument 1' });

    // this.on('myEvent'...) should have its context extended by {} and an additional argument
    // will actually have a sort-of clear Context, and 2 additional arguments: {}, { someData: 'something' }
    // SHOULD RESULT IN 2 ARGUMENTS, currently 3
    this.fire('myEvent', {}, { someData: 'something' });
  }
});
```

**Comment by ghost** [comment]
Looks like this is the related PR https://github.com/ractivejs/ractive/pull/2868 . I'm not familiar of this functionality though.

**Comment by marcalexiei** [comment]
After some debugging I think I have find the problem on [fire.js file](https://github.com/ractivejs/ractive/blob/0.9/src/Ractive/prototype/fire.js#L6)
There is a match only on Context class and not on plain JS object:
`if ( args[0] instanceof Context ) {`

Probably this is the source of the issue.

I hope this can help 🙂
