### ISSUE TITLE
Event call two times

### ISSUE THREAD

**Issue by renattonl** [ractivejs/ractive#3036]
## Description:
When I click on the TR of the table it calls twice the event. Why does this happen?. When I remove the parent DIV it works fine. Also when I remove the Button it works fine.

## Versions affected:
0.9.2

## Platforms affected:
reproduced on Chrome (window 10)

## Reproduction:
https://jsfiddle.net/bbyr541y/

**Comment by kouts** [comment]
The jsfiddle that you posted does not work, I've corrected it here: https://jsfiddle.net/bbyr541y/2/
and the event seems to fire only once.

**Comment by renattonl** [comment]
@kouts  The event I am referring to is the TR of the TABLE. Review it please.

**Comment by kouts** [comment]
Ahh ok, I see it now, you're right, seems like a delegation bug but even adding ```delegate = false``` didn't fix it .

**Comment by renattonl** [comment]
Even testing with version 0.9.1 gave me an infinite event.

**Comment by renattonl** [comment]
@evs-chris Am I doing something wrong or is it a bug? . My published code is an excerpt from my project

**Comment by kouts** [comment]
It seems that it's a bug, I could only make it to work by removing the ```on-click="@this.addCurso(item)"``` directive from the button inside the first ```{{#each```

**Comment by ghost** [comment]
Yup, looks like a delegation bug. Wrapping the first `{{#each }}` with a `<div>` eliminates the issue, probably because the handler is attached to that div and not the common ancestor div.

**Comment by renattonl** [comment]
@fskreuz  I understand, then I just have to wrap the EACH inside a div. I hope it is arranged in the next version, thanks.

**Comment by evs-chris** [comment]
Yep, the bug surfaces when an element contains iterative sections as both immediate and grandchild or farther descendants. The delegate listener is installed on both nodes when that happens, so both listeners get triggered. I'm working on a fix.
