### ISSUE TITLE
Array polyfills are incorrectly enumerable

### ISSUE THREAD

**Issue by paulie4** [ractivejs/ractive#3038]
## Description:
The array*.js polyfills in https://github.com/ractivejs/ractive/tree/dev/src/polyfills are all added directly to Array.prototype without using Object.defineProperty(), which makes them enumerable. That makes `for (var idx in arr)` include the polyfilled properties, when it shouldn't.

Since we dropped support for IE8 and under (see https://github.com/ractivejs/ractive/issues/2597), we can safely use Object.defineProperty() to add the properties so they are not enumerable.

## Versions affected:
All

## Platforms affected:
IE9, IE10, IE11, and any other browser that uses the polyfills.

## Reproduction:
```
var arr = [];
for (var idx in arr)
    console.log(idx);
```

**Comment by evs-chris** [comment]
I fixed array.find in edge because that is the only array polyfill required for IE10+ (I think). When I publish 0.9.3, it will include the changes that include the promise, array.find, and object.assign polyfills in the default build.

I'll get 'round to the rest of the polyfills, but if anyone wants an easy intro PR... 😄.

**Comment by evs-chris** [comment]
I've added the `node.contains` polyfill to the default build and verified that IE10+ pass the test suite sans polyfill. There are still some `if (window...`s and direct assignments to prototypes that need to be addressed in the polyfills.

**Comment by paulie4** [comment]
I checked MDN and also tested on Node.js, and all of these exist in IE9+ and in Node.js, so we can probably remove the polyfills, since we don't support anything less than IE9:
- Array.isArray
- Date.now
- Object.create
- Object.defineProperties
- Object.defineProperty
- Object.freeze
- Object.keys
- addEventListener (it's not in Node.js, but I doubt we need it there. MDN says IE9 supports it, but they do show [a few caveats](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener))
- Array.prototype.every
- Array.prototype.filter
- Array.prototype.forEach
- Array.prototype.indexOf
- Array.prototype.map
- Array.prototype.reduce
- Function.prototype.bind
- getComputedStyle (it's not in Node.js, but I doubt we need it there)
- Node.prototype.contains (it's not in Node.js, but I doubt we need it there)
- String.prototype.trim

Actually, I just checked, and only IE11 supports `const`, so many of the polyfills won't work on IE9 or IE11, since a lot of them use `const`. Of course, some sites (like [this one](https://www.xfive.co/blog/stop-supporting-ie10-ie9-ie8/)), say we're doing a disservice by continuing to support older browsers...

**Comment by evs-chris** [comment]
Cool. If those are _only_ for IE8, there's really no hope of compatibility again - we're using getters and setters in too many places (read: more than 0). I don't know what the aging firefox, safari, and phone browser landscape looks like, though. _Hopefully_ there is ES5 everywhere.

Regarding use of `const`, the polyfills are also transpiled 😁.

**Comment by paulie4** [comment]
Ah, they're transpiled, gotcha.

Oh, I see you needed Node.contains. [MDN says](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) it works on IE5+, but then they say, "Internet Explorer only supports contains() for elements," so we would need the polyfill if you want to try a contains test on any type of Node, not just an HTMLElement.
