### ISSUE TITLE
child component index not updated

### ISSUE THREAD

**Issue by sabob** [ractivejs/ractive#3042]
## Description:
In this [playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDwC2AhgJYB2AfAPYDWBA9KZVQDoUcEDOAxjGQAOuAARkkAXjYhBJGAgq5pI3AE9BCKXgQAPXIxgleuMgDcE09p064CuEgCMANgitslN98GABiGDQB3bkgyDAwOd0jbXjAyJyQRfwCJb1xY7jCxCiRdFOBQjEY3JVxvRjCImyZ7Z1dKpj4BYTcKHn4hUXEtGLikZTUNLVxdfUNjMwsQFrsYYrskKm8kgDoKEiIEMOqFiNtcBYIHAFdcXBoKEXOAWl4nMl46LQABZfkiGnMAJUCACkTArBZHI6EQASksnwQ73M2ys1Vm9UYjQ6VBAOG48Bcoh68REEhEnyMJnMyxGCiQP2Au2GREEThIw0gIgA5D4cUhmVhdrs3h8EN8An9-gFAZRgWCRFTPCVeOduDQXMsnDQUD9pGLdFkROzINJRdldIDmcLIJzheDpe40mRuMsAGZkeQ-Zm8r6BM1A3SggDc3Nw2G5FAwPsqWJEsnkijxIgoCACBKJE0pfoQTiZzJYFE5fppdIZCHTPgjClw2ct0qQDJITKlUXcSWCIgA2n6osAY+sCyzuMNzMaA5aSu21ht0wArGhgLMiAd1ocd0cskjZeQBftcwdeBdd5ncZdIVTr1vzkc70jZQ8zjdz9wAXT9s5lNFp5xLjdrJXcOu1sXiD9bQYWhwxaKMs5zOuyrxQnyApmnaRwUOM4HargOj6uKoKSsesoUPKirKqq6oGiClDhnIJa6mino6CGg7Wra3B0vcCDOg2ZoamhIgAIy0VEwaYEAA) is a parent with a child component. Parent renders a table and child renders the rows. parent maps the 'row' and 'index' to the child. 

The child has a remove button that fires an event to the parent, passing along the index of the row to remove. The parent then removes the actual row from the data.

However the index is not adjusted when rows are removed, so the next remove operation removes the wrong row.

To produce, remove the first row, then try the last row, which isn't removed.

## Versions affected:
edge

**Comment by sabob** [comment]
Ok, this shouldn't actually work as I thought. Otherwise mapped data will be changed.

To pass index, one should rather use @index!

**Comment by evs-chris** [comment]
I think this is a legit bug. Splicing the parent should update the index mapping on the children regardless of the source of the splice.

**Comment by evs-chris** [comment]
Yep, index models had a shuffle bug, which will be fixed on edge as soon as travis does his thing. Thanks for the report!
