### ISSUE TITLE
unknown cause bug

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3043]
Hi,

I tried to update the ractive lib in one of my apps and it broke (worked in 0.8, broke in 0.9/1.0). I can't really pin point it though, it simply fails to initialize correctly.

The exception is: `TypeError: can't assign to properties of (new Boolean(false)): not an object`

From: https://github.com/ractivejs/ractive/blob/cb384af6e034fa9c933f126db1f6e02013adcb5b/src/view/items/element/binding/Binding.js#L13

And the stack trace is quite long but here is the summary:

```
Binding
GenericBinding
createTwowayBinding
recreateTwowayBinding
...
resetPartial(...)
```

And the resetPartial is applied on a component.

I wasn't able to understand what goes wrong so far. Any hints welcome.

**Comment by ghost** [comment]
~Shot in the dark, `twoway` is by default `false` on 0.9. Try doing `Ractive.defaults.twoway = true` at the beginning of the app to see if this fixes that.~

**Comment by dagnelies** [comment]
no kidding?!? 😲 😲 😲 ...why has it been disabled by default? (seems like very useful to me and what's intuitively expected).

Btw, I tried it but sadly without effect. Nice try ;)

**Comment by ghost** [comment]
oh wait. `twoway`... no. I meant `isolated` became `true` by default.

Mondays :facepalm:

**Comment by dagnelies** [comment]
Indeed, I checked that, it's not the cause ...I still have no idea what's going on. It's the typical effect that small examples work but once you reach a certain complexity, some probably minor bug makes the whole blow up.

But thanks to the comment, I found another place which was missing that fact.

**Comment by evs-chris** [comment]
@dagnelies what type of element and binding? (`element.name` and `name` in the stack frame when you pause on all exceptions in chrome)

I'm poking around it now, but nothing has jumped out so far.

**Comment by sarendipitee** [comment]
Definitely gonna need a working example/recreation fiddle I think.

**Comment by dagnelies** [comment]
@evs-chris The element is an "Input" field, and the binding is on the "value".

@JonDum That would be nice indeed, I wasn't able to reproduce it in a small example yet. I'm still fishing in the dark as to what might be the cause.

**Comment by dagnelies** [comment]
if I understand right, interpolators are used for some kind of animations, which I don't use whatsoever.

Somehow, the attribute "value" has an interpolator `false` which results into an exception later on because `false` is not expected. On the other hand, the attributes with an interpolator `null` seem to be fine ...I think.

**Comment by dagnelies** [comment]
...I'm getting closer ...give me some more time

**Comment by dagnelies** [comment]
Ok, found it! 🎉 

What caused the exception is a harmless loooking `<input value="{{prefix}}/{{suffix}}" disabled />`.
This broke, quite simply.

However, if you put this in a small example by itself, it works just fine. I still don't know what combination of stuff caused it to throw the exception. Replacing it by `<input value="{{prefix + '/' + suffix}}" disabled />` worked ...now I'm running in another problem of unresolved bindings. ;)

**Comment by dagnelies** [comment]
If you don't see any objections, I'm going to close this as it's unlikely I'll ever discover why this fragment caused the exceptions whereas it works as standalone. There is a bug lurking around, but without reproducability it's problematic. At some point the interpolator is wrongly set, that's all I can say.

**Comment by evs-chris** [comment]
There are two interpolators in ractive: algorithmic number interpolators for animation (1 -> 5) and view string interpolators for putting strings in the midst of other strings (`hello, {{name}}!`).

Bindings require a single (view) interpolator, so that the binding can map back to exactly one model. There was a bit of weird logic in the binding selector code that may have allowed a binding through, but the attribute code that puts the interpolator in place on the attribute was correct, which left the interpolator `false`. This should now be fixed in edge, should anyone happen to cause an attempt to recreate a binding on an attribute with more than one interpolator.

**Comment by dagnelies** [comment]
thanks 👍

**Comment by dagnelies** [comment]
I'll test it tomorrow as well, to see if it solves the *"real case"* too.

**Comment by dagnelies** [comment]
I confirm it, no more exceptions thrown. 👍
