### ISSUE TITLE
Ractive.link w/ "ractive" option has #each problems

### ISSUE THREAD

**Issue by paulie4** [ractivejs/ractive#3045]
## Description:
If a Ractive instance is created with an `{{#each}}` with `Store[storePropName]`, then after the ractive.link() is called to hookup the Store, the `{{#each}}` is not updated. In addition to that, when the Store's values are updated, the `{{#each}}` values are not updated correctly.

## Versions affected:
Ractive 0.9.2+ (possibly caused by changes for https://github.com/ractivejs/ractive/issues/3010)

## Platforms affected:
All

## Reproduction:
I have this doing a console.log() with expected and actual values: [spectacularly long playground link](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgHwED0JFAOjHQHYg4DO8AEgCoCyAMgGEA9gBtRCAMa5iwpgDoADjGG5VAT0UJ5MZAFdJCAAQBeIwEEYMAIbqlKtbk3bdSAwgbMAZnqbTZTEaiwigA8ooycgBq1qJ6CGwAFGxgokgARggAlEbAnkx0uJJybLhGpLFspkZIwpJ6ALYITLjyAI7xMOoAyggS0sIwiQDkbH1SuMNZ8pJgxGm6Cq7uiT5+kUyJurgVolhGwhFZwEbbejCB27tGANQHEfK78QDcRthGw1PP+YXFTGxibTBFAjQ4bKpPBJGFLCPRpIyZIx0EDDW7Q1IZYx3YbIhF6MrWXRIlFo3ZVbHIr75DA-Rh+EplMEBNgARmqAG0frhgExrE1IMSmXIWcj9pCBciRZgsFyeXyEBKQEKmAAmUXlWLxRVq6Wy3n8wURAIAZnV4uJpt1dIAut86fk-qUjNYkEhcKJwhtqnKDcjlUYAHIIADuZs1CuJTBDyIwduYDoZ93BKo5LrdHqNcmtMzkkmsuESytZWTjBTpjrKpUGxjMUeDRgAStZ-KQEIk8vbcEh89YBR347hCkWBUWWTLOzS6RgS7TmBXTtU643mzJW+2ubhCWhcALhrRhuOB7gEA1FKJ8xGAAZcwoEMb9XDkG9lIyv4DAADECGbYCM3TUujslWugAAoqIoAbytaGCTgOhSvghCEEP6MjuggJjIu++oIDBuKQhhIDvpCuEgOQWHyjB1DKk+nbwQh75UN+sy4bRuDUPeEw0XBbHpDAXEFIOPH4mogRyAAtJIojEJIADWBFqCgKASJ6zKJFkyLkIIUmyUYai6SESnGEW1DpMJcjkJeh4Cd2m59s+wEIGBhyQQawxFgez4KYZKklGpuTPoUVBUEY3BzFUtRQkwqhGF4YjBPWuBgMYABicQAB5GIo+bHhc+ymWUehsMQTAoDFgy6QkMglQFMheEYyQAdo26gpm-xTKYJhmEWKo5P2AmFANuAOfIYwFm5rVsAeSbMiyM6sYNwI+UwMRxAkIwsiqxpUvNuAYEYfRjP5O2FMNo0teCU3dXN3ELSES0rfESTDHWG1bdd-WCbBH1fYUX3TqW+QwPIUlMDJIxTcM-7VlNwA2C2EYOf9s7-AguDcMQTSwgWaz+HIal9YUi2tQ9a3DK920DkFFWnuex5GMQbBMMMZSZMVpV6IoNnIM6Xg5acwPFWDOQAkYUbc3psUwIYulJacfTCC6XJA2doyNU5EHyhD1hsEgXgUwJyuoyMDnqy5CAQ+573vAArAADLbJaYEAA)

**Comment by evs-chris** [comment]
This is actually 3 issues, and I think I have a fix for each.

1. Linking to root data `''` or `'~/'` isn't working.
2. Rebinding (shuffle or relink) of a reference expression does nothing.
3. Reference expression children overwrite their internal value whilst invalidating it, which makes them erroneously think they're not dirty. (strangest sentence I've written in a while)

I'll distill a test cases for each of those later this evening, and assuming everything stays green, will push them out to edge.

**Comment by paulie4** [comment]
When you say, "Linking to root data `''` or `'~/'` isn't working," I assume you only mean when a View's template is using a variable to reference a Store's property, since the &lt;select&gt; &lt;option&gt;s do load properly if I use `Store.options` directly instead of `Store[storePropName]`, see:
[slightly shorter playground](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgHwED0JFAOjHQHYg4DO8AEgCoCyAMgGEA9gBtRCAMa5iwpgDoADjGG5VAT0UJ5MZAFdJCAAQBeIwEEYMAIbqlKtbk3bdSAwgbMAZnqbTZTEaiwigA8ooycgBq1qJ6CGwAFGxgokgARggAlEbAnkx0uJJybLhGpLFspkZIwpJ6ALYITLjyAI7xMOoAyggS0sIwiQDkbH1SuMNZ8pJgxGm6Cq7uiT5+kUyJurgVolhGwhFZwEbbejCB27tGANQHEfK78QDcRthGw1PP+YXFTGxibTBFAjQ4bKpPBJGFLCPRpIyZIx0EDDW7Q1IZYx3YbIhF6MrWXRIlFo3ZVbHIr75DA-Rh+EplMEBNgARmqAG0frhgExrE1IMSmXIWcj9pCBciRZgsFyeXyEBKQEKmAAmUXlWLxRVq6Wy3n8wURAIAZnV4uJpt1dIAut86fk-qVoWoiWYmAgAO5GABK1n8pAQiTy9twSGsuGsAuDzEKhWVbAF8ZZMpDNLpGCydpjdMdZRg1XdXt9-sD0YKuAjMDQuAFw1owxTMYrCAailE4YVRgABlzCgQxv1cORe2UjGPgMAAMQIP1gIzdF3aeMYNNNwpjjcbgjKowyXASEzIif6hAr3GQw8gCeQs8gcjH+Ur6jK4ch9cbidUGezM9v3DUAcJnILtGyYDMswKOkYHkURiCYABrEYGw+BdBgQZDgBsEsBVKNDwNpZgxlwbhiCaWFcFWXx-DkRJji5YFwg2GI4gSEYWRVY0qXTfYAFYAAY+MzTAgA)

**Comment by evs-chris** [comment]
"isn't working" is a bit strong. If the target instance happens to be a component, it could do strange and interesting things, which is what threw me to begin with.
