### ISSUE TITLE
0.9.2 - Disabled buttons fire events in IE

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3046]
## Description: Disabled buttons fire events in IE while they shouldn't.
It seems that it has something to do that they are inside a loop.

## Reproduction: 

[behold the ginormous link](https://ractive.js.org/playground/#N4IgFiBcoE5QdgVwDbIDQgM5QNrgC74AOmkA9GQMYAm8AdAFabUCmyAlgG4x3wv5l4RALZkYAQ0r4uLAAIAGOgE468skQD2yAJ4AzdqkyNsGMIRLkyiIQGsA5nUobREqTIXK6AJjGTpnFjphdnomEABdAF8MfCgQAB5qLgACdmoAXgAdEGFtAH18Fkx8bIA+eLIkzlLM+Fr4zEoYdiJ8ZPxtIhYskEKADwFC4SJkcULs1Izs3IKi-Fnh0fGQGrr8RJTKUcxMHpgNAHcy2syS9dGAIzZSgGEOShtkjXh2sBZkpMxxC+QWamSLohCM9MMlEJgQnZkgBJACiFUu13iFxgyTIqxOZ2AwAAxCxJGBksgNJw8qwiHQAGoAQQAStDqQA5G6RSKY04c9ZVZJbcQ7HrCP7scQAWl+ujaBwAbMc1pzOcigfhnh92F8fn92p1utlAcC6iAnvARVt2A8ejgAOSFYp5FgBeD4S3hWXys4KsAAFh52120wu8jK2P6+FZFS9GPdUYqeuV8EjboqVQT+GxZHxlDArMxSa4qwqjWarVKIAw2EgIE44lRrn873SyT4B2StL8MgAFMBaslkmxIMlLTiZjanWhu+0WIsxix+4Ph3MFiNp5axy8PmNxP2u2vTsTSeSt+POTT6Uybv2cEeo8AQ7OQwBGS3RK+cm8sAZ39-4LxP1c9t1vh+A4hgAzL+L5YrewFfp6T4QS6O6hpiz5rM8h5yoQC72iwjr9ro1huM87YsAAlNubriL8MD4O2loABLsAAhJaJEANzskhJRrGy8CRGxICREAA)

**Comment by evs-chris** [comment]
This is an unfortunate side effect of event delegation. The `button` isn't firing an event, but the `h4` is. If you disable delegation on the containing `div.row`, then events capture/bubble as normal and the button stops the propagation (I'd guess in the capture phase). So which of these is the best solution?:

1. add code the looks for disabled elements between the current target and the source of the event to skip events that shouldn't fire? (click, any others?)
2. note that nested elements in disabled elements can still trigger events when delegation is enabled and recommend disabling delegation on the parent element?
3. sames as 2, but make the event handler conditional with the same condition as the disabled attr?

I don't think 1 would be particularly difficult, but I'm not sure what events should be stopped by a disabled attr. I'll look into it this weekend, so until then, you can throw a `no-delegation` attr on the element that contains the `{{#each}}` or turn off delegation at the instance or global levels and it will use normal DOM event propagation.

**Comment by kouts** [comment]
Strange thing is this is happening in IE and Chrome and not in Firefox. So even if the firing event is the "correct" behavior, one should expect to behave the same across platforms.
Due to the event delegation, that 0.9.x introduced, I realize that one cannot expect an application that was working ok in 0.8.x to continue to work in 0.9.x just by following the [migration instructions](https://ractive.js.org/support/#migrating-from-previous-versions) 
I think that it should be noted clearly in the migration docs that this breaks BC.

For now I have disabled the event in js side by checking if node is disabled, 
I really liked how things worked in 0.8.x without thinking where should I add ```no-delegation``` attrs etc
How other UI libraries are handling this? Do they have automatic event delegation like Ractive 0.9.x or don't they have automatic event delegation at all?

**Comment by evs-chris** [comment]
You _can_ disable delegation entirely with `Ractive.defaults.delegate = false` if you happen to fall into the handful of corner cases in which delegation breaks down. I've added that to the migration docs now. If you're not dealing with large-ish/nested (>100 items) iterations, then delegation isn't providing much benefit for you anyway.

From what I've seen, most other libs only do manual delegation for benchmark purposes.

`resolveInstanceMembers` has turned out to be a bit of a footgun. Should `delegate` switch off by default for 1.0 too, leaving it for those who need it for performance reasons to find and enable it? Since it technically doesn't change functionality (except for corner cases), it could be disabled by default in 0.9.3. Thoughts? @fskreuz

**Comment by kouts** [comment]
Thanks @evs-chris,  I know it is possible to disable delegation globally with ```Ractive.defaults.delegate = false```but I have left it true on purpose in order to discover where it breaks.
I have situations with large tables in which it works fine, haven't done any benchmarks though so I' cant
say if it's really faster.
Maybe consider defaulting delegate to false and have a mechanism to enable it per section if needed.

**Comment by evs-chris** [comment]
There's not a whole lot that can be done about firefox handling events from within a disabled element a little differently than any of the other browsers, which will cause different behaviors regardless of delegation state. This particular case should be fixed on edge now though, as the delegate handler will check for disabled intermediate elements for uievents before delegating. I'm planning to cut 0.9.3 in the next few days after I cherrypick a few fixes from edge. Thanks for the report!

**Comment by kouts** [comment]
Thanks for your efforts @evs-chris
