### ISSUE TITLE
Looks like some problem with cached values

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#3047]
## Description:
http://jsfiddle.net/Inversion/m1vz3evb/
In this sample if you click on some `<li>` item once (flag will be switched), 
then click on 'clear flags', and then click on same li-item again — flag will not be changed.

While debugged I found that Ractive returns here because values are equal:
```
Model.prototype.applyValue = function applyValue ( value ) {
    if ( isEqual( value, this.value ) ) return;
```

I tried to call `this.get() `— it returns different value then `this.value`.

I expected that `@update 'list'` will reset any cached values after direct object changes.

## Versions affected:
0.8.14
no such problem in 0.9.2

## Platforms affected:
Chrome on Win

**Comment by evs-chris** [comment]
This is technically off-label use, as 0.8 doesn't support modifying children of computed values (#2123). If you're using `list` anywhere other than `sorted(list)`, then changes to the `sorted(list)` model will not propagate to anything using `list` directly. That said, fixing this was just a matter of adding a value cache and using the already-available dirty flag on computed child models. You can use `v0.8-dev` until 0.8.15 is cut.

**Comment by Inversion-des** [comment]
Thank you again for another fix!
By the way I finally decided to get rid of using magic:true. Will use one of the proposed solutions for global config storage.
