### ISSUE TITLE
How do we simulate a mouse click on components?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3048]
## Description:

I need to trigger a click event for a component when a certain event occurs but I don't know how to do that. `this.findComponent('myComponent').fire('click')` is not working, of course. 

jQuery's `.trigger('click')` is not working either. 

## Versions affected:

0.9.2

## Reproduction 

Here is the [minimal example](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdEAewFcUAHTlgPhIB6SlT5MAdiS58AwmDQBjANY0FrcRlYI0NdTS5IA5joSskZPDQDuO8WjRkaKVtZgV0NFvICeTt4eMYBwBCFl1xfSMTMwsaACt2LBoECiUdLzQEUyd5INCQOgxVFOUHADohaRACDHgAJSQFFGo0MrUAWy51NHEUDDKfGgYaBqaWsrQAD3RxMgAKYAkmFHRO5HRIGgADJZRlkgAjTmcI9QBaBRKlZnA0bzCsb20bg9YYMjQYTYBGLkmaTQpRxBMj8YDAbwUTJkHA4IRHFbqMTiZbLLZ4XbqIKzT6bABm7HEY3UcwAlIsUXsVmAKP0SRTUVSAOQ+Jn4wnE8RkhlUxlqDRaVqmQxzDK+FD+QIhFik3aMnBylA4WWUhWUiTKiR2KwjRrNKhoBa7FBIGDGFCbJkAYg43E4TIxlNWXHWaE2WxIPj48iyLhQuTQwSEXvRmPE2I+XxoBKJzRJ5MV7V8w39tLKeIosxkrE63V6cxZdyZpIA3J51Sgk+mKEEC5cKMpiyXdmrlbggA) of the case. I need to fire the button click event on page load.

**Comment by ceremcem** [comment]
Finding the answer right after asking online... I needed to define what to do on `component.click` action. [This works as described](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdEAewFcUAHTlgPhIB6SlT5MAdiS58AwmDQBjANY0FrcRlYI0NdTS5IA5joSskZPDQDuO8WjRkaKVtZgV0NFvICeTt4eMYBwBCFl1xfSMTMwsaACt2LBoECiUdLzQEUyd5INCQOgxVFOUHADohaRACDHgAJSQFFGo0MrUAWy51NHEUDDKAM1YXBhoGppaytAAPdHEyAApgCSYUdE7kdEgaAHJVkgAjTmcI9QBaBRKlZhB270uKZTCsb20bg9YYMjQYbYBGLjTGiaFKOIJkfjAYDeCiZMg4HBCI5rdR8HZ4FYnILzH7bAbscQTdQLACUy3Eq1WKDAFH6xPJlJQqzuD2UeIJRPEpIZTN5VJp-QGFCCCx2rKUOxJmMZOGlKBwUop8okCok42aVFaHS6dl6-R8NFG6smMzmix56y4mzQ2wABnKSEMXOdxTcfM8UK80O9Pt9fjQAUCQfQaODIdDYQh4YjBE6xErVraMUr1Ni-ezCc1iWS5dTaWV6XLVjsfDsM5zuUXeWoNFpWqZDAsMr4UP5AiEWIrGatZQn5V3eXnBRR5jJWJ1ur1RU7JYNhWhReLJQBuTG9yniVXiOxWMaNDULi1IGDGFDbHYAYg43E46MxlutdpIPj48iyLmpPzQwSEL6TmNTHp0xofFMwobMeWZXxRiHOdR3HHUehQUVSxJZdPD7O45xFMUrhXNcVRJXAgA)

**Comment by kouts** [comment]
Is this what you want?
[XL link here](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdEAewFcUAHTlgPhIB6SlT5MAdiS58AwmDQBjANY0FrcRlYI0NdTS5IA5joSskZPDQDuO8WjRkaKVtZgV0NFvICeTt4eMYBwBCFl1xfSMTMwsaACt2LBoECiUdLzQEUyd5INCQOgxVFOUHADohaRACDHgAJSQFFGo0MrUAWy51NHEUDDKfGgYaBqaWsrQAD3RxMgAKYAkmFHRO5HRIGgADJZRlkgAjTmcI9QBaBRKlZnA0bzCsb20bg9YYMjQYTYBGLkmaTQpRxBMj8YDAbwUTJkHA4IRHFbqMTiZbLLZ4XbqIKzT6bABm7HEY3UcwAlIsUXsVmAKP0SRTUVSAOQ+Jn4wnE8RkhlUxlIbQwFBzDK+FD+QIhFik3aMnAylA4aWUuWUiSKiR2KwjRrNKhoBa7FBIGDGFCbJkAYg43E4TIxlNWXHWaE2WxIPj48iyLhQuTQwSEHvRmKJrDWaA2NAJROaJPJ8vavmGvtpZTxFFmMjDXTsvTmLLuTNJAG5PKqUIm0xQgvnWSXdirFbggA)

**Comment by ceremcem** [comment]
That was much more clean :+1:
