### ISSUE TITLE
Observer on parent property set using 'observe' keyword not firing until property is rendered in template

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3053]
## Description:
If a non isolated component observe some data on parent component and the observer is set using `observe` option the callback is called only once with `undefined`as both new and old value.

## Workarounds:
1. set the observer using `this.observe` in the `oninit` callback: https://jsfiddle.net/weqtrdyj/
2. print the property inside the component: https://jsfiddle.net/nro4djy2/

## Versions affected:
- 0.9.x
- edge

## Platforms affected:
All

## Reproduction:
- https://jsfiddle.net/d9q0eb6o/

**HTML**
```html
<script type="text/html" id="template">
  <p>route.entry: {{route.entry}}</p>
  <MyComp/>
</script>

<div id="main"></div>
```

**Javascript**
```javascript
Ractive.components.MyComp = Ractive.extend({
  template: 'Component:<br><!--{{JSON.stringify(route)}}-->',

  isolated: false,

  observe: {
    'route.entry': function(...args) {
      console.info('route.entry observer', args)
    },

    'route': function(...args) {
      console.info('route observer', args)
    },
  },

  oninit() {
    console.info('init')
  }
});

const r = window.r = new Ractive({
  el: '#main',
  template: '#template',
  data: {
    route: {},
  }
});

setInterval(() => {
  console.info('set interval');
  r.set({ route: { entry: Math.random() } });
}, 1500)
```

**Comment by ghost** [comment]
So in summary:

- Expected: Observers observe regardless of other conditions.
- Actual:
    - Observers set using the `observe` initialization option only observe if its dependency is rendered.
    - Only happens with non-isolated components.
    - Observers set using `ractive.observe` remain unaffected.
    - Isolated components with mapping unaffected.

**Comment by evs-chris** [comment]
The observers from the hash were being set up before the fragment, which means that they couldn't find their parent instance. I've moved hash observers to just after the init event so that that is no longer a problem. Thanks for the report!
