### ISSUE TITLE
Transition animates wrong node after any filtering

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#3063]
## Description:
I saw something about it: "0.9 has support for bindings in computed contexts" but I have wrong behavior.

Here is a minimal sample where filter just returns items. 
Direct list works correctly, filtered — no (notice highlighted item):
http://jsfiddle.net/Inversion/44qao09g/1/

`syncComputedChildren: true` doesn't help also.

## Versions affected:
all: 0.6 - 0.9.3

## Platforms affected:
tested on Win

**Comment by evs-chris** [comment]
Bindings are supported, but shuffling doesn't propagate from a computation source into the computation result. Ractive has no way of knowing that `tt(items)` is producing an array that is related to `items`, so all it can do when `items` changes (even in a shuffling way) is to completely replace (not shuffle) the result of a new evaluation of `tt(items)`.

There is an open issue on adding a way for ractive to correlate things like this over in #2947.

**Comment by ghost** [comment]
Closing in favor of #2947
