### ISSUE TITLE
Should renders guard against `NaN`?

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#3064]
## Description:

You're deep into your app, writing one computation after the other. But then you select that one odd option and your computation blows up. Ractive renders `NaN`... but should it?

`undefined` and `null` don't render as "undefined" or "null", they render nothing. Computeds that blow up get caught gracefully. Should `NaN` get the same treatment and gracefully render nothing as well?

**Comment by evs-chris** [comment]
That seems pretty reasonable for interpolators. If you actually _want_ `NaN` to be output, it's not difficult to achieve. That seems like it would be more the special case, and preventing it by default would reduce some of the fodder for thedailywtf.
