### ISSUE TITLE
Performance problem with images with inline base64 data

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3066]
## Description:

I'm using multiple `div`s where only one of them is visible at a time. Each `div` is holding an image. Pseudocode is something like: 

```html 
<tab index="1" /> 
<tab index="2" /> 
<tab index="3" />

<div style="{{#if theIndex !== 1}}display: none{{/if}}">
    <img src="data:image/png;base64,...." />
</div>
<div style="{{#if theIndex !== 2}}display: none{{/if}}">
    <img src="data:image/png;base64,...." />
</div>
<div style="{{#if theIndex !== 3}}display: none{{/if}}">
    <img src="data:image/png;base64,...." />
</div>
```

Images are displayed correctly upon each `tab` button press, but when I use a large image (400 kB?) it takes seconds to switch to the target `div`. CPU hits %100 while switching. 

Is it something expected? Shouldn't I use inline data for images? 

Or is it something unexpected and I should provide a reproduction code?

## Versions affected:

0.9.3

**Comment by evs-chris** [comment]
400k is pretty huge for an attribute like that. I haven't ever tried it, but does plain DOM do any better? I'll poke at it when I get a little free time.

I would expect the best thing to do with that sort of thing would be to create a blob url and shuffle that in and out of the img src.

**Comment by ceremcem** [comment]
[`window.URL.createObjectURL()`](https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications#Example_Using_object_URLs_to_display_images) is what I was looking for. Thanks @evs-chris !
