### ISSUE TITLE
Is there an easy way to get the keypath of a component's event?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3067]
# Orig: Is there an easy way to get the keypath of an event source?

## Description:

Consider the following template: 

```html 
<ul>
{{#each curr.myArray:i}}
    <li on-click="['aHandler', i]">{{.foo}}</li>
{{/each}}
</ul>
```

```js
...
on: {
    'aHandler': function(ctx, i){
        curr = this.get('curr');
        item = curr.myArray[i];
        item.foo = "hello!";
        this.set('curr', curr);
    }
}
```

When `x` is clicked an action is taken by taken `i` into account in order to calculate `curr.myArray[i]`.

Is there an easy way to get the clicked keypath, like `"curr.myArray.3"` ?
 
This would be handy when we have a button in a deeply nested document, for example, which will add or remove an item to the array. 

## Versions affected:

0.9.3

**Comment by ghost** [comment]
I think that would be [`context.resolve()`](https://ractive.js.org/api/#contextresolve) without args.

**Comment by evs-chris** [comment]
Yep, that's what `context` is made for. You can event store a ref to the context and use it to modify the array with `context.push('../', { newItem })`.

**Comment by ceremcem** [comment]
@fskreuz  I tried to use `context.resolve()` like [this](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdEAewFcUAHTlgPhIB6SlT5MAdhJIYAxjApcUNFAE8uaZoTQAPFIJhIZKamhZ1GLCuJ4p+EpihLsEYybZTBgAYjSGwNGXYYGAA6AFsVAEFgnBx7dxIEClcHVMcMLiRxGlZxAFoZJJkAa00kAAkssgQ0GH5CihKaMLQAQhpIGk8QgDNWVlihDKyUhMEk0YdPQV8ZMFj4oWcxW3EhuQUUPhACDHhxNAB3GgAlQ2MqNAAKYHi0BE6Aci8Obk5HvHj0MK5kdCevFYbB94rloPEHBUqjUYJ0euxxEYKLkrkZtABKW5uNIUb4ABVQ-gYARQ2hCMEwrAQlyu6IA3BD3Li0GEaMSUGAKBgQgBzNAoK7MsIEjn0xkOIW9fpsmgsMD3BCsVpmADUdHxhIZ2PcHK5IQw-MFGo5eHVLLF2ribnw8TIqCQ4O1gWCnSxaQcEWisJoAG1xe5gDbtWlA59gwGre73ABdRmRlBWnDo3BAA), but it resolves to `""` in my actual application. 

Let me dig in further.

**Comment by ceremcem** [comment]
I'm defining the handlers in a separate file and pass them to the component via an attribute. At this point, `context.resolve()` resolves to `""`

Does it make any sense or should I provide a full working example?

**Comment by evs-chris** [comment]
That's really weird because the context shouldn't be affected by where it's being passed. Can you provide a working example?

**Comment by ceremcem** [comment]
It _is_ really weird because [in this example](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdEAewFcUAHTlgPhIB6SlT5MAdhJIYAxjApcUNFAE8uaZoTQAPFIJhIZKamhZ1GLCuJ4p+EpihIBbFQFoZrJ11bi04pTLsMDCawMCBwTg4dpJKNPEk7AhisfFpaWEAxGiGYDQRMAB0LgCCkdGp6WkkCBQpDlWNNNJcSOI0Pu61MgDWmkgAEm1kCGgw-DLdPTROaACENJA0YYUAZqysUUIYreL1cY1CtftNy8CCOTJgUfYHzYJJYraSlQmPt6dZl3kFxSplMBuryqNTqH1O1R2bQ64i6FF6mm0EymVgA5sowBQMDQAO6sGA9bEeYJoIwIFSLM5rDZbQRQvbgw6CY6MqphC65IENaoPZIOeyxIQudyeby+fwpbZyBQoPggAgYeAAJUMxioaEKHi8Pj8KAwAG0AOTCrVi3WGgC6NAYNBVRhMhR06HEZAAFMBbugvMh0EtDWE+B5-Lqooa8LcfFYKCglqt2OJ7T5XQBKD2xBxkNCrJBJFBDF2jGDYm1p-m2FDaWPxxPiV1GbSp25lsvRtBOAAKqDyNvrhRgmFYCHVKYA3E3yy2vdaMVjCqi0ChXa2O13k2P0xPy8vqaxpywUJjsXiCRg5mYANR0L2dg-r5ubg+zjALpfXrt4K9ttfjhwVMt-8tM2zXN8xGMYMEKQZhkLadHwg+dF0NApDWTP4wGg8DINAws73LODCiTICcwQPMMKLb8N1uCocGTAUoILMZpzjBNjCTetG1iZcb27fIKz7AchzQUdbmXWDDznF8uNXXDt3WXcbRYMA0AQBBWDPEAaEvKTb09cTn0XbSwA-ZcKL-cRfBxW1VRMd1bmUv1Mg4bhODDT02y4H00AcqwbFc2IyFQJBoHHAollLTdSmCJZ9R-ctgHwWKHHi8NKLigD7wtFL7xcdCGKLYLUoceiwJgJZisLWL0pQADqOTXAgA) it works as you expected. I'm going to close this issue until I find the root of the problem.

**Comment by ceremcem** [comment]
Okay, here is a reproduction: [link](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdEAewFcUAHTlgPhIB6SlT5MAdhJIYAxjApcUNFAE8uaZoTQAPFIJhIZKamhZ1GLCuJ4p+EpihIBbFQFoZrJ11bi04pTLsMDCawMCBwTg4dpJKNPEk7AhisfFpaWEAxGiGYDQRMAB0LgCCkdGp6WkkCBQpDlWNNCRIrTQ+ri4ytTIA1pra-N0UfVYA5spgFBg0ZKyYNOKsSgDurDC9NAAUAEac+WBofZNo+T4YrAhoAJQ0kDRhhQBmrKxRQq1I9XGNQrXfTQewEEORkYCi9h+zUESTEtliQhc7k83l8-m+kOcbg8Xh8fgCQRCLDCBQhIAB1VhkMBWVBeQKxRUZRgEMqv3+1MB1QwXCQ4na4ncPX6LEG5OGo3EExQUxmaw2Mw8wSOKAQKjuQOer3egh5fIpv0EHLZVTCINyrIa1RhyQcmMESJxqPxKSEsnkij4IAIGHgACVDMYqGhCk68f4MIVPjQGDQA0YTIUdOhxGQtsBIegvMh0PcAOTSXn8joSkUgLrC-hhFQUNAIMg6vXiPh5yESHDXezieNBkNhtEoDAAbTzjpR4ZQeYAujG44HE8m-GmM7Es1wc2h82E+B5-Pionm8JCfNA27YUNp7k92OIEz4tkZtNcV3bz6-dxcroUEKwxls89oNBgHyZBXDANAwDekaFIUebXAA3Ger4OBQWYAAqoHksaPoUMCYJcwZbAhSFvsYWazjK0yFGMaAoFsqFoE4GEysRsTIeeDFOFqrCziwlFyusvQYAAhGYADUdDoZhiFsaRDj8YUGC0fRUkyngkmMax7EVK+FQdl2vgrHOCaES+6AIPmmQcNwnCHpmjHrqgm40HmmRWDYdmxGQqBIKeskFPcZmvqUwT3EOJEOMA+ARSgUVHrJr5RTFU5njpKB6dcuBAA)

Root of the problem seems proxying the events.

**Comment by evs-chris** [comment]
Here's what's up: the event is firing _outside_ of the yield, which means that its scope is the component root, whereas _inside_ the yield with the interpolator is the surrounding scope - the iteration.

There's nothing built into ractive right now to address this particular issue, but there _is_ a way around it if you're willing to go a bit lower level with your component. Basically, at `construct`, you can arrange to have a mapping automatically generated that pulls the scope surrounding the component into the component as a key (say `scope` e.g. `~/scope` in the component template). Then you can wrap the `span` in a `with` that makes it the context for the event e.g. `{{#with scope}}<span ...>...</span>{{/with}}`.

I've tried to come up with a good way to achieve that with friendly helpers, but it hasn't played out any better than just doing it manually thus far. The `this` mapping from #2166 would get part of the way there, but you'd still have to specify it on the component, which is unfortunate. Perhaps an option on the component to make automatic mappings would help and get rid of the need to [mangle the template surrounding the component](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiAPYCuuADi-QHwED0JpnWgDthBAM4BjGMVa5yuAJ6sEdPAgAeuHjACGE3GQT1KNesSHtcXYbVwEAtgoC0EhvdYMhCIXIlMYMKrAwH4BGBjWInLkMQRMADaCUTEpKcEAxAh6YOShMAB0jgCCYRHJqSkE8cRJthX15AQ6zeSeLtUSANaq6lwSHZ3mKPJgxGLkSAwI40IMcgDuDDCd5AAUAEYsuWAIXSMIuZ5iDPEIAJTkkOTB+QBmDAzhvM06tdH1vNVvDdfAPFkSMDhGzvRo8BKCKxRXiOFxuDxeHxvEEOZyudyeby+fyBejBPLAkDfSoQkE-DIAnJ5QoKEowYHlD5fMk-SpiVg6IStITtYhdHp9AZDEZjciLZbjVwBXa4eIKS6-O4PJ48dmc4kfHjMxkVYL-bIMuqVcGJWwoniw9EIrFJXiSaSyTggHBieAAJT0BlICHyVsxPjE+Re5Go5A9+kM+Q0uG8SFWwBBMfc8R0MauAHIMvNiLgcpIGMonmquW1+nzuvQy10uMEFMQEPEkCri5w9dnc+F01gQZ4rgmorZXEIxLgYEx9KsLsByDweCLxmAdONcAxyOsDuZDsPR+O5OuJDomGIDqmt7diCgsPtyPYdKxWENxjoYCf4i+dEhKFzWCmJEYB1YuBDiOuTuCG86+vC-q4AA3DOc4vrcCAvkIf7yKuuYHH6iJyDmCD2FuuA6OYwq5qK5gjpyf4gmaBi3GsACEEjuBcL64P4QhwbOuScumci3kIKCnNezAxjA8j4T+qYHPc4m3vej6UPRsxyDohwYjhNGAcBchsPE4HMaw+RJlJMZ3Fxc6YeQty6Cg9hYuQz66PKsnXthDkmSmMZaYORyqbgo7jKGhnGZJXk+gRAD8oFGZ50mFPkYgdAgk4KgA2gAuhZhysPKVmpoFjkBDo8rHGKWGcuQYg6Ehco3pyQkblCtGDu4oXJtJ4H9i1gEIFcIVxWZCBXtxri5W5UE4eQQg6PZPmAbcVx6SNc5jXlOzWbZ9k+PNti4P1bWDT6uArTl60HKQkwEYoyi7bg9hXAVMDjNxYjzHeX6tP4rTzFyT1PsVCjzRg8HXmIi7xPEDDzGd5CsC+3oBtZLD+AcKFIMh4wMPRVlHZtbhrggwrwwgTgCY1SC7QBtije+MaOdNCAw-JD6Cdy15HfN-35Ow4Pxnd+3kAAjAAzKdObpk+f0BdImzedTgFCBm+bKF2oMzfZn4q-+PW2It5BpdO3Gcp+VlDjGPiUFLX5iR4XlLIqhqAT1gsAEzdgrtEwBm+TpndGAZRgZwwXdd3cbMMOYS+VvkAgtxIRG3p1WpXgw097Nm5NDmS2NKh4sA+SEn7AFlLYZRBzYQjhl6PruQGaXppaWc+OmGXgdXkbRrG-NREdGbBJw5tYp2Hu2L21xaeoVy3EwqEGJ4qxD5oZzdc7WhzmI5hofMCDptHGjKBGbNqS+Tjwww6gKFe8yjICN5ZMOYPMDAaFLwsxCQ4TYowJ4l7lXDCR9KZx8NGfG10NrHH8GhWYGN5o6VyLgdQ4EyKBjQLgAAwp4GMmhF5YOjPkGB5wQ4K30OoRKCBcCrHTEqBgas+KjHGOKToYgGLkHTOQAA1AgshL5jjxG9JOYO81w5zAOLmU8wDsFyE6AgJQqYqSLkEtMCYCBlBCBIGzTwT8oEbm3FRA4+5DzHlaDjDaLMhjCLnAoZgPEuRMKKswdRIxTzrHlEeYUAADAAAj-OYHJcweKUuQaxTBuR1QPjKbkBxThJxMYzEcwoliWPIB40h+ReEnAEdQtWKCebPixGcQJK5yAZP4QcG+H80YIG9M9UiZi7ysxQOMdcuAd7eHIDsaOJs4b5MtqsLeVAsQ6EhlfFJPiHhsHkYE8iICYAzRGWMt+6TpiZJStkq8Xjcm+NwIUs4WlS64HLnskQQhU5hk9IYHutgGwZnSKJSwXZExhWkrc8wDzR64CQKmHQ0AtJ5D7PNYoAQrhpTusAbAYKIWe1wOC+aGV9kgiOZgIAA).

At the very least, I think I could come up with something that would remove the need to do your own shallow copying, but you'd still probably have to come up with your own template bits. That's not too bad if you _know_ that you have the parser available, as it's just a `Ractive.parse('<dummy bind-scope="." />').t[0].m` away for getting an array of attributes for this case. Being able to force the parser into attribute-parsing-mode would help a bit more, as then you could `Ractive.parse('bind-scope="."').t` for your attributes array. Creating the literal template bits will always be faster, though not necessarily as future-proof.

**Comment by ceremcem** [comment]
I  appreciate the workaround, which will let me move forward when I badly need the functionality (this time I just copied and pasted the component contents into the target place).

Do you think this case is very specific so we should implement the workaround when we need?

**Comment by evs-chris** [comment]
This would definitely be in corner-case territory. There are some other related cases though, so I've added experimental support for a shortcut version in edge - see #3070.

**Comment by ceremcem** [comment]
As a workaround, `@keypath` could be passed as an argument to the handler: [Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutR-AAgC8A4uWp0EADzJckACmAAddkrKzWAGyKzIAgAYq1agDwAjAK7qOAjgFoSmiiQDWQpSAD6j5y48A+YGAATwoETSQMDBMAektrdn8BIzJ9LBSOaBS1bydXPQAzC3ZxDnlyKQBKZVUyYzIChgZhAWBcZgQ9AHISIk0SC21ZJAEqPosEAQp2XAokScZWDi4yLoxsuoam+j7NM1IXFqKSyjKEGBhqjfrGGYZNOk0GFHku85gGGAEYBDILGE4IzMwQEYCI7CQDxgkC6WAE70qAG5rmR1rV6mQwBReAUKD9Xj5XLCBI0GEiNmi1GiMJUVJwAO6iUiUGiKFLhboAYgYVhYVlhKQ0LCGnUMtSCnIQpDAJKakAoURSJhY-g2Jn4RFs7AceTcHgA2l0wOEnsSAAIuBDBFg6MAAXQC8TINiCCuiMQ1STGmgmeiCtG9E0VtViKpSQRiUpIYGDajSGXYWXRmJNDEKxVK7HKZCkcMt1ttV2Talu7QetCeLy6+ZtmOJNcLyOL6ixvFwv3kDcxAgA1AIugHxghiV0fmWaCNbrIZN1ewIu2Byc2KjtNHsDq92M13p9aHuukv6pTUelakgdEQ-RtSXp9cBsK0H-e7XDrrVqZUQDgyPATEhqFMSDuCAPJkHydQgP4sT-lQ-iYEAA)

If we could get the `@keypath` with an attribute (like `<aaa outside-keypath="{{@keypath}}" ...`), whole problem might be solved appropriately by #3070 

### Edit 

Workaround applied to original example [here](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdEAewFcUAHTlgPhIB6SlT5MAdhJIYAxjApcUNFAE8uaZoTQAPFIJhIZKamhZ1GLCuJ4p+EpihIBbFQFoZrJ11bi04pTLsMDCawMCBwTg4dpJKNPEk7AhisfFpaWEAxGiGYDQRMAB0LgCCkdGp6WkkCBQpDlWNNCRIrTQ+ri4ytTIA1poA2gDk2kN4NAACvWhqqGAAuvzdFH1WAObKYBQYNGSsmDTirEoA7qwwvTQAFABGnPlgaH2baPk+GKwIaACUNJA0YUKADNWKwokJWkh6nFGkJatCmgDgIIcjIwFF7DDmoIkmJbLEhC53J5vL5-NDMc43B4vD4-AEgiEWGEChiQAjqrjMYisqi8gViioyjAMZVYfDuYjqhguEhxO1xO4ev0WNolsr1pttjQzhcdh5gk8UAgVH8kcDQeDBDK5RzYYIJWKqmEUblRQ1qjjkg5KYIiTTSfSUkJZPJFHwQAQMPAAEqGYxUNCFAN0-wYQqQmgMGhxowmQo6dDiMhXYCY9BeZDof4AA2ksvlHWWfU0XWV-DCKgoaAQZCtNvEfBrEhw33s4lzCaTKbJKAww39JNTKCG8yzOfj+cLfhLZdiFa4VbQ-yGYT4Hn89KiY0xPmgmJ9KG0-yB7HEeZ8VyM2nG01mKDAb490fECUAvD4vkKBBWDWK4RhoMA5TIL4YBoGA3wwf4-1lADIDGGhsLmb4AG4H1sciHAA7ZCgwNAUCuQiAJoABqGghgtVh8MYwDSNiR8Kn4kcx0kcRfBODc80TUtMR7E9Mg4bhOBvfc0ErVBjzYzIrBsZSHDIVAkHvPiwMZf5gIolBSmCf4BjIx9gHwOzyIcvAnIcBy3JQRZjIElAKlHXAgA).

**Comment by evs-chris** [comment]
So technically, you could achieve this by snagging the event directives off of the outer component template, throw them into a partial, and yield them, but that's probably not a reasonable expectation for not-a-maintainer devs to get into. So, on my list for a while has been to allow context traversal in a finer grained way than per-element since contexts don't necessarily require an intervening element (`{{#with foo}}how do you get this context{{#with .bar}}<span>from here?</span>{{/with}}{{/with}}`). You can pass `@context` objects out of the template, but there's no external access.

As of edge, there's now a `getParent( crossComponentBoundary )` method on contexts, and there is a check in the event directive code to allow reuse of a context by setting `refire` to a truthy value, allowing this:

```js
const aaa = Ractive.extend({
  template: `<span on-click="_click">{{yield}}</span>`,
  on: {
    _click(ctx) {
      const c = ctx.getParent(true); // event will be fired with parent context object
      // would probably be a good idea to copy in original event, etc from source ctx
      c.refire = true;
      this.fire('click', c);
    }
  }
});
```

**Comment by ceremcem** [comment]
[Awesome!](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiAPYCuuADi-QHwED0JpnWgDthBAM4BjGMVa5yuAJ6sEdPAgAeuHjACGE3GQT1KNesSHtcXYbVwEAtgoC0EhvdYMhCIXIlMYMKrAwH4BGBjWInLkMQRMADaCUTEpKcEAxAh6YOShMAB0jgCCYRHJqSkE8cRJthX15AQ6zeSeLtUSANaq6lwSHZ3mKPJgxGLkSAwI40IMcgDuDDCd5AAUAEYsuWAIXSMIuZ5iDPEIAJTkkOTB+QBmDAzhvM06tdH1vNVvDdfAPFkSMDhGzvRo8BKCKxRXiOFxuDxeHxvEEOZyudyeby+fyBejBPLAkDfSoQkE-DIAnJ5QoKEowYHlD5fMk-SpiVg6IStITtYhdHp9AZDEZjciLZbjVwBXa4eIKS6-O4PJ48dmc4kfHjMxkVYL-bIMuqVcGJWwoniw9EIrFJXiSaSyTggHBieCuIRiOQvcjUcgAJT0BlICHyGlw3iQq2Awhi4fc8R04auAANxByuW1+nzuvQAPpZrpcYIKYgIeJIFVqoScZNYGPcq7RrkpfMDVb6dQXJv1d2e3I+3K4dT5NC4AAKOhgWNWuBgTHOAG5yDweOQEMGfGLiPF4uR1gdbsQp0gt7gchyp5v3eHNK11gArGX11IrsXMcvkVgwBjrHTrOV7gcOjkCgDwnlQWTyAwhysPK5itNIKDmDou7rliWBrrgEjkLc372OQxz+BIBwds+KQSPkU6HlOA6zvOC5kbGoxiHcR4IKsADkBadBxGESGcDHNjEZTCcIGACTYQgBvohj5FamI+GIADaHGWvCCm4BxAC6A7SUGIZhhGUYgnGrAJkm5AccEnDXli4S8SCnjQCCZpDlctxMEIMmeO2Q4YZ0CBKImYBnE2rnhVhRwnCG8QMCgnHqOQYCckgpwwOQc4elcAVBWekC8YOw5Tsc8TBqsZwSVEEW2GeYz5GICC4L5RXTCcZUXAA1JZSoMAVHaUa1pXsRVgkRWUrllOJklePM-qBoYxlRGWVwcekzBsCwDlRKZ5kICt6TmJYW22EgiY6M5VVYTijYuVYuDFAEVxKbdrnANgL13W9daXa9413a5Wm3X9k1nJgQA)
