### ISSUE TITLE
Performance issues with rendering content by Ractive

### ISSUE THREAD

**Issue by ctomczyk** [ractivejs/ractive#3068]
## Description:

Rendering thousands of HTML elements causing performance issues and due of that the browser is getting frozen.

## Versions affected:

0.9.3

## Platforms affected:

* macOS Sierra, 10.12.6 (16G29)
* Chrome 60.0.3112.113 (Official Build) (64-bit)

## Reproduction:

1. Go to [http://sokolka.pl/](http://sokolka.pl/). This site is an example that contains quite a lot of HTML code.
2. Open developer console.
3. Use code snippet from [ASLint](https://www.aslint.org/usage/) page in the developer console.
4. Observe the results of rendering content.

I've used JavaScript Profiler from Chrome and seems that `Element.prototype.render` is causing performance issues. This is because there are thousands of HTML nodes to be rendered by Ractive and in that particular case that might be expected.

<img width="1648" alt="performance" src="https://user-images.githubusercontent.com/3242483/29819218-fca15d06-8cbf-11e7-8d9b-d666b69da6ee.png">

However, it's probably worth to investigate a bit more to see if there is a room for an optimisation.

**Comment by ghost** [comment]
Yep, that's a ton of renders there. Is the tool open-source? I didn't see a GitHub link, I must be blind if it is open 😎 . Maybe we can poke some holes into the implementation.

![screen shot 2017-08-29 at 8 21 26 am](https://user-images.githubusercontent.com/1582932/29820612-1615c880-8c93-11e7-9518-237cf3927a34.png)

Common practices you could do to avoid excessive renders:

- If possible, use partials over components, particularly when all you need is a template. 
- Lessen element usage.
- Avoid unnecessary render/unrender. For instance, pre-render then show/hide.

I haven't looked into detail what's causing the excessive rendering, just a scrape on the surface. I too run an MBP and I'm seeing the same issue. Even the profiler is lagging because of the size of the call tree.

**Comment by ctomczyk** [comment]
The tool is not open source. At least, not at the moment ;-) However, here is what follows:

1. The Ractive instance is initialised:

        ractive = new Ractive({
            append: true,
            data: data,
            el: '#asContainer',
            magic: true,
            template: template
        });

2. The all data is gathered and appended to the model **once**.
3. The container where it is rendered has set `display: none` initially to avoid reflow/repaint multiple times and once the data is added to the model the container gets `display: block`:

        function pushCachedResultsToModel() {
            ractive.set('messages', cacheResults.messages);
            ractive.set('visibleContainer', true);
        }

4. The template is only one:

<div id="asResults" class="asResults">

    <div class="asOptions">

        <h3 class="visuallyhidden">Options</h3>

        <label for="slTrackActiveElementOption">Active</label>
        <input type="checkbox" on-change="setLiveTrackingActiveElementOption" id="slTrackActiveElementOption" name="slTrackActiveElement" value="" aria-label="Show element details that has focus" />

        <label for="slActivateFocusOutline">Focus</label>
        <input type="checkbox" on-change="activateLiveFocusOutline" id="slActivateFocusOutline" name="slActivateFocusOutline" value="" />

        <label for="slOptionAction" class="visuallyhidden">High Contrast</label>
        <select id="slOptionAction" name="slOptionAction" value="{{selectedOption}}">
            <option selected="selected" disabled="disabled" value="selectOption">Select option</option>
            {{#highContrastOptions}}
            <option value="{{ value }}">High Contrast Mode - {{ label }}</option>
            {{/highContrastOptions}}
            <option value="getKeyboardNavigationMap">Keyboard Navigation Map</option>
            <option value="getReport">Report</option>
        </select>

        <button class="button action" on-click="slOptionAction" id="slOptionAction">Ok</button>
        <button class="button action" on-click="slRefreshAction" id="slRefreshAction">Refresh</button>

        <div aria-live="polite" role="status" class="slActiveElement {{ visibleActiveElementDetails ? '' : 'hide' }}">
            <label for="slActiveElementString" class="visuallyhidden">Active element:</label>
            <textarea rows="2" placeholder="Current active element" readonly="readonly" value="{{activeElement}}" id="slActiveElementString"></textarea>
        </div>

    </div>

    <div class="asReport" on-click="@this.toggleSection(event)">

        <h3><a href="#as-results-container" data-action="toggleVisibility" data-toggle-container="as-results-container" aria-haspopup="true" aria-expanded="{{ visibleContainer ? 'true' : 'false' }}">Results</a></h3>

        <div id="as-results-container" class="{{ visibleContainer ? '' : 'hide' }}">

            {{#each messages:i}}

            <h4><a href="#as-{{@key}}" class="as-{{@key}}" data-action="toggleVisibility" data-toggle-container="as-{{@key}}" aria-haspopup="false" aria-expanded="false">{{@key}} <strong>{{this.total}}</strong> <span class="visuallyhidden">items</span></a></h4>

            <div id="as-{{@key}}" class="hide">

                {{#each this.results:i}}

                <h5><a href="#{{@key}}" data-action="toggleVisibility" data-toggle-container="{{@key}}" aria-haspopup="true" aria-expanded="false">{{@key}}<span class="visuallyhidden">, </span><strong>{{this.length}}</strong> <span class="visuallyhidden">items</span>{{#this.typeId}}<span class="visuallyhidden">, reference </span><em>{{this.typeId}}</em>&nbsp;{{/./typeId}}</a></h5>

                <div id="{{@key}}" class="hide">

                    <ol>
                        {{#each this}}
                        <li class="as-{{this.type}}">

                            {{{message}}}

                            <ul>
                                <li>
                                    <strong>Impact:</strong> {{impact}}
                                </li>

                                <li>
                                    <strong>Rule id:</strong> {{ruleId}}
                                </li>

                                {{#if xpath}}

                                <li>
                                    <label for="element_nodesString_{{id}}" class="visuallyhidden">Element string</label>
                                    <textarea id="element_nodesString_{{id}}" rows="3" readonly="readonly">{{nodesString}}</textarea>

                                    <button class="btn action" title="Copy element HTML string" data-clipboard-text="{{nodesString}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" baseProfile="tiny" x="0px" y="0px" width="24px" height="24px" viewBox="0 0 24 24" xml:space="preserve">
                                            <title>Copy element HTML string</title>
                                            <g>
                                                <path d="M15.979,7.62H1.021c-0.221,0-0.4,0.18-0.4,0.4v14.959c0,0.221,0.179,0.4,0.4,0.4h14.959c0.221,0,0.4-0.18,0.4-0.4V8.021   C16.379,7.8,16.2,7.62,15.979,7.62z M15.58,22.579H1.42V8.421H15.58V22.579z"></path>
                                                <path d="M22.979,0.62H8.021c-0.221,0-0.4,0.18-0.4,0.4v4.959c0,0.221,0.179,0.4,0.4,0.4s0.4-0.18,0.4-0.4V1.421H22.58v14.158   h-4.559c-0.221,0-0.4,0.18-0.4,0.4s0.179,0.4,0.4,0.4h4.959c0.221,0,0.4-0.18,0.4-0.4V1.021C23.379,0.8,23.2,0.62,22.979,0.62z"></path>
                                            </g>
                                        </svg>
                                    </button>
                                </li>

                                <li>
                                    <label for="{{id}}_xpath" class="visuallyhidden">XPath string</label>
                                    <textarea readonly="readonly" rows="3" id="{{id}}_xpath">{{xpath}}</textarea>

                                    <button class="btn action" title="Copy XPath string" data-clipboard-text="{{xpath}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" baseProfile="tiny" x="0px" y="0px" width="24px" height="24px" viewBox="0 0 24 24" xml:space="preserve">
                                            <title>Copy XPath string</title>
                                            <g>
                                                <path d="M15.979,7.62H1.021c-0.221,0-0.4,0.18-0.4,0.4v14.959c0,0.221,0.179,0.4,0.4,0.4h14.959c0.221,0,0.4-0.18,0.4-0.4V8.021   C16.379,7.8,16.2,7.62,15.979,7.62z M15.58,22.579H1.42V8.421H15.58V22.579z"></path>
                                                <path d="M22.979,0.62H8.021c-0.221,0-0.4,0.18-0.4,0.4v4.959c0,0.221,0.179,0.4,0.4,0.4s0.4-0.18,0.4-0.4V1.421H22.58v14.158   h-4.559c-0.221,0-0.4,0.18-0.4,0.4s0.179,0.4,0.4,0.4h4.959c0.221,0,0.4-0.18,0.4-0.4V1.021C23.379,0.8,23.2,0.62,22.979,0.62z"></path>
                                            </g>
                                        </svg>
                                    </button>

                                    <button class="btn action" on-click="['highlight', @keypath] " title="Highlight elements">
                                        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" x="0px" y="0px" width="24px" height="24px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
                                            <title>Highlight elements</title>
                                            <path d="M24,11.323h-2.88c-0.344-4.499-3.952-8.092-8.455-8.419V0h-1.409v2.909C6.787,3.272,3.224,6.852,2.88,11.323H0v1.409h2.88  c0.344,4.472,3.906,8.051,8.374,8.415V24h1.409v-2.85c4.503-0.325,8.11-3.917,8.457-8.418H24V11.323L24,11.323z M12.665,19.741  v-2.784h-1.409v2.781c-3.692-0.355-6.631-3.311-6.967-7.007h2.753v-1.409H4.289c0.335-3.696,3.275-6.651,6.967-7.006v2.726h1.409  V4.313c3.728,0.32,6.708,3.286,7.046,7.01h-2.753v1.409h2.753C19.373,16.457,16.392,19.422,12.665,19.741z" />
                                        </svg>
                                    </button>
                                </li>

                                {{/if}} {{#if ~/externalReport}}
                                <li>
                                    <strong>Reports to:</strong> {{#each ~/externalReport}}
                                    <button class="button action" value="{{id}},{{this}}" on-click="exportProblemToExtension">{{this}}</button>
                                    {{/each}}
                                </li>
                                {{/if}}
                            </ul>

                            <hr aria-hidden="true" />
                        </li>
                        {{/each}}

                    </ol>

                    {{#if this.links.length}}
                    <div>
                        <h6>Related Techniques and Resources<q class="visuallyhidden"> to {{title}}</q></h6>
                        <ol>
                            {{#each this.links:a}}
                            <li><a href="{{url}}" target="_blank">{{content}}</a></li>
                            {{/each}}
                        </ol>
                    </div>
                    {{/if}}
                </div>

                {{/each}}

            </div>

            {{/each}}

        </div>

    </div>
</div>

**Comment by evs-chris** [comment]
I've been through Element.render a couple of times before trying to narrow down bottlenecks, and have made a few minor adjustments from those rounds of profiling. I have one more idea that might help a little - to add a map for static attributes to element templates so that they don't have to go through the same slightly convoluted render process as dynamic (bound, in conditional, etc) attributes. The bulk of attributes seem to fall strictly in the "just-a-string" category, which _should_ benefit somewhat from being able to just iterate the map and call `setAttribute` on the element right after it's created.

Anyways, it looks like that's not the source of most of your problem. If you switch to conditional sections for controlling visibility, you won't be rendering the _entire_ tree of invisible DOM nodes all at once, which should drop your render time down to something much more reasonable. Is there a particular reason you're using classes to hide closed tree nodes rather than something like `{{#if .open}}` or even `{{#if ~/openNodes[@keypath]}}`? If it's accessibility, I get that, but surely there's some sort of signifier that "activating this element will result in more information", because I'd imagine that a giant wall of lists would be pretty well inaccessible too. (I am in no way an accessibility expert or even novice, so I really have no idea, just reaching for a solution to overlarge render times)

**Comment by ctomczyk** [comment]
> and have made a few minor adjustments from those rounds of profiling.

From the code I see you can also consider to extract function from every `forEach` so it will not be recreated every loop.

> Is there a particular reason you're using classes to hide closed tree nodes rather than something like {{#if .open}} or even {{#if ~/openNodes[@keypath]}}?

I use classes because I want to separate content from presentation and by that also the code is better maintainable. Anyway, if strongly required then I can use inline styles too ;-)

> If you switch to conditional sections for controlling visibility, you won't be rendering the entire tree of invisible DOM nodes all at once, which should drop your render time down to something much more reasonable.

Hm, hiding container:

`<div id="as-results-container" class="{{ visibleContainer ? '' : 'hide' }}">`

before adding data to the Ractive model speeds up the whole process significantly, but seems there is bottleneck on the script side.

What do you mean by:

> If you switch to conditional sections for controlling visibility

CSS class `hide` contains `display: none`. Do you think about something else?

I've been looking in Ractive for something like lazy rendering so the particular content could be rendered when required, but I couldn't find anything like that.

> [...] something like {{#if .open}} or even {{#if ~/openNodes[@keypath]}}

Hm, where and how this could be implemented?

**Comment by evs-chris** [comment]
@ctomczyk sorry, I got swamped and forgot to respond to this...

> I use classes because I want to separate content from presentation and by that also the code is better maintainable. Anyway, if strongly required then I can use inline styles too ;-)

Oh, absolutely use classes for targeting styles. I was referring to using `display: none` for hiding vs actually adding and removing DOM based on some state. If the default state is hidden, then it's effectively lazy, as it won't be rendered until something triggers the section to be rendered.

[Here's an example](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4BjAewDssACGKgXivLQHcqAlJYlASwDc0AFMAA65YSnQBbAA7J0kKgHIAxFNmo0ivKPEokMAOZoUClXsPGtOlABNUSBSLEpxMUqRNUn4nygylJNEdrX3EbNDRZAE9HRkx0GwUUGABXNCp8EJds6VQwBQBtLNCURRQwVCtnEvFFCoxFYuyAXSbM6uzefW5SFIxgjt8AI24-AZrs0gAzceyJuz1Cpomy0iqJksUhzW1Buf3FGDRycKObRr2S1svsnGWUO73H33bfXPL+r2eH3fFkLAA0mgogJ3mAAJReGjGFIwcjsTg8fgAOgwslGQKiYNBeXByOkpGkAnBAG4Mr8JKQDAYEGgAAp5HHlSHAKjlbgYZEoKk0wQcLh8NDIgBWpG45ExGAEijBDTwVDB4NJGVEOHBIAI2EgIAAPBhiDBuNIUGysWg6MIQOgAB4oAD0YBQkgQlqo3BsFqtaBkcjQloAfNZgMB-aNvRgaO4Ho8dXb9YbjYGxOQ9QajSaUGbPTb7Y7na73Z6w5IMAHrDqUggk+Jg8o0JwwFRkThvuIdQhuNX9sGAALI-4oTECHsAa2BipbkCate4U1N0jQ0yb9DoDEUpCGwrQXEULfuOqGKUp8IoAFpiB3iCPPX3udTaQzysOx1jcQGZ3OAH522UFUfjvJmhbMgEGQaQMDQYM0AQCCWzQa1chOYM7VnFtY0PY8uxKD8qG-X9-1fcogJwYNQykDAW2Q1DW2yKCYLQPcbmDZsaJrYAUKmRjfFjDsu2Q+tiDALiUFjSsk1jeN02rFMbD4N0PUtcwjBcEB-VjWTeH9XAgA) of a tree viewer that waits for user interaction to render past the first level. Check it out in devtools element view as you toggle the levels to see what I mean about `display: none` vs adding/removing DOM on demand.

**Comment by ctomczyk** [comment]
@evs-chris  Yes, I think **adding/removing HTML elements on demand is the solution**. It's better than adding all elements to the DOM as some of the parts even may not be used at all. When I'll be able I'll change the way of rendering the results and then this should significantly impact on the performance in case of having huge amount of data.

I think there can still be done some optimisations in Ractive itself, but that's now a different story. Shall I close this issue?

**Comment by ghost** [comment]
You can leave this open for future reference.

**Comment by evs-chris** [comment]
While still not the _best_ at handling tons of DOM to render, ractive has improved a bit more since version 0.10 - to the point that it's less than 50% worse than hand-coded js, which I think is not too bad. So I'm going to close this, but feel free to reopen or create a new issue if performance issues crop up again.

**Comment by ctomczyk** [comment]
It's a bit better now. Let's see how it'll go in the future. Thanks.
