### ISSUE TITLE
Toggling attributes that have same name via {{#If}}...{{else}}...{{/if}} is broken on 0.9.x

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#3071]
## Description:
`hasSomething = true`
`<p {{#if hasSomething}}anything="really"{{else}}anything="else"{{/if}}>`

Toggling `hasSomething` multiple times, will have the attribute `anything` disappear when it is true.

Goes like this:

1. `<p anything="really">` - hasSomething === true
2. `<p anything="else">` - hasSomething === false
3. `<p>` - hasSomething === true **(should be like 1.)**
4. `<p anything="else">` - hasSomething === false
5. `<p>` - hasSomething === true **(should be like 1.)**
6. ....

#### Why do we use it
We use this kind of code to set the `tabindex` and focus an element, when necessary.

Kinda like this (`as-focused` is a decorator that focuses the node):
`<a {{#if focusedIndex === index}}tabindex="0" as-focused{{else}}tabindex="-1"{{/if}}`

## Versions affected:
0.9.x

0.8.x works as expected

## Platforms affected:
Tested on Chrome and Safari.

## Reproduction:
Fiddle: https://jsfiddle.net/1cpofgvk/1/

### Javascript
```javascript
const r = window.r = new Ractive({
	el: '#main',
  template: '#template',
  data: {
  	hasSomething: true,
  },
});
```

### Template
```html
<p {{#if hasSomething}}anything="really"{{else}}anything="else"{{/if}}>Should toggle between red background and bold text.</p>
<button on-click="@this.toggle('hasSomething')">Toggle</button> a few times, and you'll see that the attribute [anything="really"] will never reappear.<br>
The paragraph will either be have the [anything="else"] attribute, or none at all.
```

**Comment by evs-chris** [comment]
Should be fixed in edge, once travis does his thing, and will go out with 0.9.4. Thanks for the report!
