### ISSUE TITLE
How do we set/get keypaths which include a  dot in its keyname?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3072]
## Description:

How can we get/set keypaths which include a dot, eg. [set `img.'a.jpg'.url`](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiAPYCuuADi-QHwED0JpnEDgDO8AHYIA7uQBKAQwDGuMggAUwWmNq5ccmGlyRyAcgDEzNi2NZN23AgC2rADZz7RgAa3cBVp3JMMM7kDABm5PRyAHQAVqwo9JTCRgQARpzAwJQOKADaxtFxKMYAulGBwRgYvOnkqpLEzsGpCOQKYHJiaEiUYuQADFEArOTCCAoMYkjCAJS8ft4eNlq4kzAIUwgwRqFMYkrEk6oz5Bor2gD6F+TU5LhgxMIA3BHnuGO4ACrEDggWqrt9sojjMztpwbgJJIAKpBG4RcAIACeKJRAEI0fQnt4ITjcNofih4VcogZVMZCcYZti3toJmJhAxnAgos4GChVPRCUZ6FhsihqXiCTl8oV4qVynDblDYc4abjcCSPuTKXzCdTXkLcDweOQwAxpEgGORJK0jXcwK1hHJfhbiF1eiEJORnPaEDzadqeEqELgVTkorlIrF4vQyhVrOQZUFBVo3thyEN+v0Zt5sN4kG45EYwfjlDkc1qCiHioXPdoKjyQDxWG4wDxVjwxQkQFqMHj2ytO+CxBgZpggA)  for `{img: {'a.jpg': {url: '/path/to/image'}}}`?

**Comment by giovannipiller** [comment]
From mobile, excuse my formatting.

You should take a look at Ractive.escapeKey: https://ractive.js.org/api/#ractiveescapekey

You should also be able to access a known property like this:

img.a\.jpg.url

**Comment by giovannipiller** [comment]
Hmm github changed my code.
Basically, you should escape \ all the extra dots.

Like this, hopefully:
img.a\\.jpg.url

**Comment by ceremcem** [comment]
A-ha! It's double backslash: [like that](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiAPYCuuADi-QHwED0JpnEDgDO8AHYIA7uQBKAQwDGuMggAUwWmNq5ccmGlyRyAcgDEzNi2NZN23AgC2rADZz7RgAa3cBVp3JMMM7kDABm5PRyAHQAVqwo9JTCRgQARpzAwJQOKADaxtFxKMYAulGBwRgYvOnkqpLEzsGpCOQKYHJiaEiUYuQADFEArOTCCAoMYkjCAJS8ft4eNlq4kzAIUwgwRqFMYkrEk6oz5Bor2gD6F+TU5LhgxMIA3BHnuGO4ACrEDggWqrt9sojjMztpwbgJJIAKpBG4RcAIACeKJRAEI0fQnt4ITjcJcLlEPqpjD8UFE5LQqbRYvFykFrOQobDnDNsVo3thyEN+v0Zt5sN4kG45EYwfjlDkxXjtAVacVpW8IRUjPQeKw3GAeKseIV4vQZbgMHjjStTeCxBgZpggA)
