### ISSUE TITLE
How do we create numeric keyed objects with ractive.set?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3074]
## Description:

[Following code](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7tCANpKQDkAYgD2AV1oAHSYKyduPALZTelHgIAGC2gB4pMBAD5gwAFIBlAPIA5AHS5aMegRT0AZgE8WYPr1EAlBgYugD0BsY6mvJctKIELvS0Au7iBHT08SwBHLGKYPS4Dgi0LOzgfqJ2tL6GdgCM5VikAKwBANw62DpI6pQCudzcvrz+AzpDtDUIhgMYE7TzsUsYASA4tPC6SEyk9EgAvOUS0pLlRmE7jEaYQA): 

```js
new Ractive({
	el: '#output',
	template: `
	<pre>{{JSON.stringify(hello)}}</pre>
	`,
	oninit: function(){
		this.set("hello.there.1", 5);
	},
	data: {
		hello: {
			there: {}
		}
	}
})
```
Produces the following output: 

```js
{"there":{"1":5}}
```

Which is somewhat expected. 

[But removing `data`](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7tCANpKQDkAYgD2AV1oAHSYKyduPALZTelHgIAGC2gB4pMBAD5gwAFIBlAPIA5AHS5aMegRT0AZgE8WYPr1EAlBgYugD0BsY6mvJctKIELvS0Au7iBHT08SwBHLGKYPS4Dgi0LOzgfqJ2tL6GdgCM5VikAKwBANw6GJwYASA4tPC6SEyk9EgAvOUS0pLlRmEjjEaYQA) (thus creating the object dynamically): 

```js
new Ractive({
	el: '#output',
	template: `
	<pre>{{JSON.stringify(hello)}}</pre>
	`,
	oninit: function(){
		this.set("hello.there.1", 5);
	}
})
```

Produces the following output: 

```js 
{"there":[null,5]}
```

So the question is: 

How do we make a distinction between creating a numeric keyed object and an array while creating a data object dynamically with `ractive.set`? 

## Versions affected:

1.0

**Comment by ceremcem** [comment]
# Proposal 

If there is no such distinction yet, I would like to use a backslash for that purpose, like so:

```js
this.set("hello.there.\\1", 5);  // => {"there":{"1":5}}
this.set("hello.there.1", 5);  // => {"there":[null,5]}
```

---
> Note to self: [This](https://github.com/ractivejs/ractive/blob/76e49bd6ba0ef982dd8e7fd9e3e89adf779a29f8/src/model/Model.js#L158) is the responsible line.

**Comment by evs-chris** [comment]
Yep. That's one of those things that tends to be what you're after until it's not. We _could_ throw some escaping or some other indicator in the keypath, or even add another set option that specifies that numeric branches should be objects, but how about [`this.set('hello.there', { 1: 5 }, { deep: true })`](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7tCANpKQDkAYgD2AV1oAHSYKyduPALZTelHgIAGC2gB4pMBAD5gwAFIBlAPIA5AHS5aMegRT0AZgE8WYPr1EAlBgYugD0BsY6+oYm5tb2js6uHt6itL4wQSHhMTqa8ly0SOqUAhyF3GkZZaTpLigCANoAuqQYOtg6ogQu9LQC7uIEdPTdLAHl3Ipg9LgOCLQs7OB+onbpCIbLWKTApACMAgCsbTt7SAgIUgJO4ghtAQDcOtOz84uCVZvrM65yu6QjgIAEzA04Ai5XG4wO4PZ6FdoEDABEA4WjwXRIJikehIAC8ywk0kkyyMYSxjCMmCAA) as a workaround for the edge case? The deep set means that existing structures will be used rather than overwritten. More escapes are pretty unpleasant in the code.

As another alternative, what if branching only created an array with `0`? Is it common to want to create a sparse array like that?

**Comment by ceremcem** [comment]
Hmm. I've never used `{deep: true}` option. Maybe that's the right solution here. 

The reason for this question is related to #3072, as the [solution was using `Ractive.escapeKey()`](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiAPYCuuADi-QHwED0JpnEDgDO8AHYIA7uQBKAQwDGuMggAUwWmNq5ccmGlyRyAcgDEzNi2NZN23AgC2rADZz7RgAa3cBAEYtcBjFyIIBaBWdiBQBrOhBhBFwABTcwLgio6PJA8gTcbLAEciYYZ15-HSDObwJWGAROYGAAKQBlAHkAOQA6YVwYYjEUYgAzAE9VYgcUAEoMDF46hu8PGy1AsSMNde08lNwwIxGmMSViINUZ8m3tW9wR4mcEMTkHIupyejlugCtWFHo3juB2Iwl6iVUximKG6xgA1LJFMpSAhughhAo5KwEABpBATB5PF5vK5w4zdErOayfPBgNw8UE8CSSHiU+gzADcQNwGG8vLEGBmmCAA) to set a keypath that includes a dot. 

That's the code I use in production in order to set [CouchDB document attachments](https://pouchdb.com/guides/attachments.html#how-attachments-are-stored) when a user uploads a file by file input:

```js
db.put({
  _id: 'mydoc',
  _attachments: {
    'myattachment.txt': {
      content_type: 'text/plain',
      data: 'aGVsbG8gd29ybGQ='
    }
  }
});
```

Code worked well so far because every image has a dot or string in its name, but [what if user tries to upload a file with a name of `12345`, for the **first time**](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiAPYCuuADi-QHwED0JpnEDgDO8AHYIA7uQBKAQwDGuMggAUwWmNq5ccmGlyRyAcgDEzNi2NZN23AgC2rADZz7RgAa3cBAEYtcBjFyIIBaBWdiBQBrOhBhBFwABTcwLgio6PJA8gTcbLAEciYYZ15-HSDObwJWGAROYGAAKQBlAHkAOQA6YVwYYjEUYgAzAE9VYgcUAEoMDF46hu8PGy1AsSMNde08lNwwIxGmMSViINUZ8m3tW9wR4mcEMTkHIupyegBGACZ6bzuB2Iwl6iVUximKG6xgA1LJFMpSAhughhAo5KwEABpBATB5PF5vK4w4zdErOayfPBgNw8YE8CSSHjk+gzADcANwGG83LEGBmmCAA)? That would be definitely an invalid CouchDB document attachment structure. Obviously I need to change the code before someone hits this problem. 

> In fact that's [not hard to add `if (typeof this.get('img') !== 'object'){ this.set('img', {}); }`](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiAPYCuuADi-QHwED0JpnEDgDO8AGbEANggB2AQwC2CctXIBGAEy0ZMhAHdyAJTkBjXGQQAKYNtq5ccmGlyRyAcgDEzNizdZb9ggKrJJyuAiuAAYBBABGLLgMMuRJALQmksQmANZ0IMIIuAAKYWBcGVnZ5InkTCEMckjkugAeuOQS0rzx9kmcMawwCJzAwABSAMoA8gByAHTCuDDEMijEYgCelsQKKACUGBi8g8MBkf4ydkmuNpe4dgXFpa5iTDJmxEmWe+S3dv-mMTkSy4DasBAMIG4MDEYRzZyWNw7FBuH4AQmoqjcDFiACsEGZUX97iS7NDYQtCojkX5fhg9gBuAIAjDMknkuGPam7OZuADURlM5lICDmCGEJjk4IA0ggtp1ZIoED8+W45kwYJJafRoWEeLCeLo9DwNZJ6Iy2XYFfIlHy+Uy7nZWXdnfTMEA) to set the `_attachments` with a `{}` beforehand. 

I thought, if I need to use `Ractive.escapeKey(name)`, then I have a case I might have a dot in the `name`. So the `name` has to be definitely a `String`. So `escapeKey()` should place a mark which will point out whatever it tries to escape is a string. Is there anything defined in Ractive to point that a keypath portion is `String`? Not yet. So we should have an escape sequence for that. 

That was the rationale. I may use `{deep: true}` in my case. This issue might be closed if the `escapeKey()` matter is not a big deal.

**Comment by evs-chris** [comment]
Gonna punt on this one until the issue comes up again :smile:
