### ISSUE TITLE
.set() assigns wrong value for specific keypaths

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3075]
## Reproduction:

Code is [here](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiAPYCuuADi-QHwED0JpnEDgDO8AHYIA7uQBKAQwDGuMggAUwWmNq5ccmGlyRyAcgDEzNi2NZN23AgC2rADZz7RgAYFWMBJ2DAAFIAygDyAHIAdMK4MMRiKMQAZgCeqsQOKACUGBi8Pn4eNlq4DGLxxIbkSUxiSsRlqlkaJXZgxMLRCLiqxhkokQCMCIORTDDO1uT0uGBuPB08EpI84870WQDctrgYmhhZmEA). 

Expected output: 

```
{"1e1":{"url":"that/is/new/url"}}
```
Current output: 

```
[]
```

The problem is `1e1` portion in the keypath. Changing it to something other than a number representation produces expected output, [like this](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOiAPYCuuADi-QHwED0JpnEDgDO8AHYIA7uQBKAQwDGuMggAUwWmNq5ccmGlyRyAcgDEzNi2NZN23AgC2rADZz7RgAYFWMBJ2DAAFIAygDyAHIAdMK4MMRiKMQAZgCeqsQOKACUGBi8Pn4eNlq4DGLxxIbkSUxiSsRlqlkaJXZgxMLRCLiqxhkokQCMcoORTDDO1uT0uGBuPB08EpI84870WQDctrgYmhhZmEA).

## Versions affected:

1.0

## TODO

Add this case into [the tests](https://github.com/ractivejs/ractive/blob/dev/tests/browser/methods/set.js).

**Comment by evs-chris** [comment]
I think it's definitely weird to use non-integer numbers for branching a keypath. It looks like anything where `isNaN(thing) === false` will cause branching as an array, but I think that's probably not usually what's intended. Going back to #3074, perhaps we should require branching as an array to use `0` rather than just any old number? I would _think_ that a sparse array would be a fairly special case, and it wouldn't be unreasonable to require it to be set up in the data before access.

**Comment by ceremcem** [comment]
# Edit: 

Expected output was: 

```js
[null,null,null,null,null,null,null,null,null,null,{"url":"that/is/new/url"}]
```

as `1e1` is actually an integer which equals to `10`, so `'img.1e1.url'` is equal to `'img.10.url'`. 

It's `1e1` instead of `10`, because it might be generated by a code that outputs number `10` as `1e1` which is perfectly legal.

**Comment by evs-chris** [comment]
That's interesting... so what's happening is the array is getting a `1e1` property because the property set code doesn't convert the key to a number for arrays. That furthers my conviction that at the very least only integers should cause array branching.

**Comment by ceremcem** [comment]
As far as I could poked around, there is no way to return an integer from a function (or calculation) in this format. So this is really an edge case.
