### ISSUE TITLE
Ractive.joinKeys not constructing keypath correctly. 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3076]
## Versions affected:

1.0

## Reproduction:

[Playground :arrow_right: ](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gLYCeACgIYAuYABALzUDkAZgPYsB0ARmTF2QF4MA3AB0AdrjrUASmQDGFAJYA3BO1wAHADaKKAaQRENlMAApi5KgEpRYmFNkKVagFYtFYg0VyncN8XIsEixaalosKKYMxMZU1ADuZLiQjFjUFib+YoHBoezhkQyaOhQUyNSmPDBkRFYpDGl+tjm4IWERUTAIALRuHsj1aTBZikwVGXEAhLT0w8DiIhQtbewIMDAsMFETNIqSYiwU1C0UMACuCuWB6wgKWkTUnA+OSqrsfZ6GPlYMWRjiIBwFHgAB4kCpqIokLQRCAWGcKBoEbCAHwggD04OUKMwQA)

**Comment by MartinKolarik** [comment]
`Ractive.joinKeys()` doesn't take an array of strings, but multiple individual string arguments. [Fixed code.](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gLYCeACgIYAuYABALzUDkAZgPYsB0ARmTF2QF4MA3AB0AdrjrUASmQDGFAJYA3BO1wAHADaKKAaQRENlMAApi5KgEpRYmFNkKVagFYtFYg0Vyn2f3DbiciwSLFpqWiwopgzExlTUAO5kuJCMWNQWJoFiwaHh7JHRDJo6FBTI1KY8MGREVmkMGQG2ebhhEVExMAgAtG4eyI0ZMDmKTFVZCQCEtPSjwOIiFG0d7AgwMCwwMVM0ipJiLBTUbRQwAK4KlcGbCApaRNScT45KquwDnoY+Vgw5GHEIBwFHgAB4kCpqIokLQRCAWBcKBokfCAHxggD0kOUaMwQA)

**Comment by ceremcem** [comment]
Upps, yes, and the documentation says the same :( Sorry. 

As `Ractive.splitKeypath` returns an array, I guessed `Ractive.joinKeys` will do the reverse, just 
 like `Array.join` does.
