### ISSUE TITLE
Special reference $n only works for primitive values

### ISSUE THREAD

**Issue by BartVanBeurden** [ractivejs/ractive#3079]
## Description: 

When handling events, the special `$n` reference only works for primitive values (numbers, strings).

`this.fire('change', 123)` works as expected.
`this.fire('change', { something: 123 })` does not work as expected.  
`this.fire('change', null)` even throws an exception.

## Versions affected:

0.9.3; 1.0.0-edge (tested on ractivejs.org playground)

## Platforms affected:

Firefox, Chrome (others untested)

## Reproduction:

https://jsfiddle.net/jqp5v1tq/2/

```html
<script type="text/html" id="template">
  <TestComponent value="{{ valuePrimitive }}" on-change="@this.handleChange($1)">Click Primitive</TestComponent>
  <TestComponent value="{{ valueObject }}" on-change="@this.handleChange($1)">Click Object</TestComponent>
  <TestComponent value="{{ valueNull }}" on-change="@this.handleChange($1)">Click Null</TestComponent>
</script>
```

```javascript
const TestComponent = Ractive.extend({
  template: '<button on-click="@this.doClick()">{{ yield }}</button>',
  data() {
  	return {
    	value: null
    }
  },
  doClick() {
    const value = this.get("value");
    console.log("fire change", value);
    this.fire("change", value);
  }
});

const r = window.r = new Ractive({
  el: '#main',
  template: '#template',
  components: { TestComponent },
  data() {
    return {
      valuePrimitive: 123,
      valueObject: { something: 123 },
      valueNull: null
    }
  },
  handleChange(value) {
    console.log("handle change", value);
  }
});
```

Button 1 fires a "change" event with $1 = a number. The handler receives the number
Button 2 fires a "change" event with $1 = an object. The handler receives 'undefined'
Button 3 fires a "change" event with $1 = null. Throws TypeError at `Ractive$fire`

**Comment by evs-chris** [comment]
The signature for `fire` changed with 0.9, which is in the changelog, but it looks like we missed it for the migration notes. If the first argument to `fire` is an object or context, it is used as the context for the listeners. https://jsfiddle.net/jqp5v1tq/3/

I'll update the migration notes.

**Comment by BartVanBeurden** [comment]
Thanks.

The documentation on `ractive.fire` does mention the context, I must have missed it because I only looked at the docs on `$n`.
