### ISSUE TITLE
How can we create a hook for "onteardown" event?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3080]
## Description:

How can we register multiple functions to `onteardown` life cycle event? Registering a function with 

* [`this.onteardown = myfunction`](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gDoB2ASgIYDGALgJYBuCAdBQPYC2ADi0QkVbozJCABAF5h5avSYIAHlV5IAFMGIEqCzgBsyCyMIAGaquoA8AIwCuG7gD5gwAJ40EWpBgymA9FZtFbxgZYwsbcMIoIMPoAZpZEUtxKAJSqROrqrES4LFpMWiwoSgDkbI7CFDq4uMI0WVRk8Qg11bU0tGRaNABeyEVJANzG6lRgNALcCmQwSCwA7kRiwrHxtIkpQyZUmdm5jPmFJWUVZFU1dQ0UTWPCANY0WrlIfRsYxq9EGElqRDyzEpS0BgqYyufRFADELGsHGsRSwxk0HB0ekMG1MtRhVGEVEcHAQogIIAoYAQFBu5hYskJ5RJZOQBJADlwYDmHmpXgCaU2DnBNGiwmZrPe6SopiEZFsJIeLG84s5IocXj5bK5QWMSF0ZH0qRFgtm+ioMEsCDexE+IBwVHgpiQ9BqSFERShVExRVs3ltdFsmCAA) works, 
* [`Ractive.extend(onteardown: function(){ ... })`](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gDoB2ASgIYDGALgJYBuCAdBQPYC2ADi0QkVbozJCABAF5h5avSYIAHlV5IAFMGIEqCzgBsyCyMIAGaquoA8AIwCuG7gD5gwAJ40EWpBgymA9FZtFbxgZYwsbcMIoIMPoAZpZEUtxKAJSqROrqrES4LFpMWiwoSgDkbI7CFDq4uMI0WVRk8Qg11bU0tGRaNABeyEVJANzG2KF8CGQwSCwA7kQxcQlEyanpVJnZuYz5hUWMu3u7ZEhIbTTcHcK4VJbR0X2DaVQYxBhJakQ8UxKUtAwqxq76IoAYhY1g41iKWGMmg4Oj0hmMZlq4Kowiojg4CFEBBAFDACAoAGtzCxZDjyviichsSAHLgwNMPOSvAEHuoHECaNELgypky2VRTEIyLZ8Vp8t5hayVg4vFz+eogsYkLoyPpliZ+Lz9FQYJYEENnkkQDgqPBTMc6DUkKIiqCqCiirZvJbbJggA) also works (as normal) 
* but [putting them together](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gDoB2ASgIYDGALgJYBuCAdBQPYC2ADi0QkVbozJCABAF5h5avSYIAHlV5IAFMGIEqCzgBsyCyMIAGaquoA8AIwCuG7gD5gwAJ40EWpBgymA9FZtFbxgZYwsbcMIoIMPoAZpZEUtxKAJSqROrqrES4LFpMWiwoSgDkbI7CFDq4uMI0WVRk8Qg11bU0tGRaNABeyEVJANzG6lRgNALcCmQwSCwA7kRiwrHxtIkpQyZUmdm5jPmFJWUVZFU1dQ0UTWPCANY0WrlIfRsYxtihfAhTM-MxcQlEZKpdJbbg7PIFYqMaEw6FkJBINo0bgdYS4KiWaLRPqDNJUV5EDBJNREHizCSUWgMFTGVz6IoAYhY1g41iKWGMmg4Oj0hg2plqrKowiojg4CFEBBAFDACAoN3MLFkUvKsvlyElIAcuDAcw8Kq8ATx6gcDJo0TRutm+uNVFMQjItllDxY3gdRpBDi85pt6iCxiQujI+mBmx1c30VBglgQb2IRJAOCo8FMiLoNSQoiKzKoQqKtm8adsmCAA) does not work.

**Comment by evs-chris** [comment]
All of the lifecycle events can be subscribed as [regular old event listeners](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutR-AAgC8A4uWp0EADzJckACmAAddkrKzWAGyKzIAgAYq1agDwAjAK7qOAPmDAAnhQSakGDCYD0l6+xtGyfSwBAI4YOQQYPQAzC3ZxDnkASmVVMjVGdlwGTTpNBhR5AHImBwESbVxcAQossiJ4hBrq2opKIk0KAC9kIqSAbgC1T08BMjBIhCLqjk0yjiaijlkiGCQGAHd2IoEWGAYWSLIHYOyBBvnxyOrOZDGGATMm8JQLbRgBBBpuAVwLM1wQ3UYAovGWCFW6y2wgEsXilESKSBGQ42VytHyhRKZQqRCqNTqDRITVBAgA1hRNLkkH0gRgAthQuw9KljOoIWtNuxkgJWel+Zk0XkCsVaGLxWKiEgkG0KBwOr8yBZotE+oM0mp6WktRgkkZ2JwNqJSJQaIoAi49EUAMQMKwsKxFLABDQsbS6AxAky1B1kMYOQ5CJQgEgTEhkswMKTB8phsnIIMgey4MCbdwxzz+DVkezWijRX6pjbp7MmfhEGwTKkMLzlrNs+yefMltRBAJIHREFlAlObPRkGAWBAMlS6kA4MjwEwyqg1JBCJb2x02LwzmyYIA), which means you can listen on namespaced bubbling too:

```js
Ractive.extend({
  on: {
    teardown() { console.log('tearing down'); }
  }
});

// and/or

instance.on('teardown', () => console.log('also tearing down'));
```

**Comment by ceremcem** [comment]
Thank you, [that was all I needed](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutR-AAgC8A4uWp0EADzJckACmAAddkrKzWAGyKzIAgAYq1agDwAjAK7qOAPmDAAnhQSakGDCYD0l6+xtGyfSwBAI4YOQQYPQAzC3ZxDnkASmVVMjVGdlwGTTpNBhR5AHImBwESbVxcAQossiJ4hBrq2opKIk0KAC9kIqSAbgC1T08BMjBIhCLqjk0yjiaijlkiGCQGAHd2IoEWGAYWSLIHYOyBBvnxyOrOZDGGATMm8JQLbRgBBBpuAVwLM1wQ3UYAovESqWM6XUCFW6y2MTiCXYyQhUMhmWyuVo+UKRQA1ATCQTSuVKi06g0SE1QQIANYUTS5JB9IFqDBAjBJALYULcGFrTbsBHxSiJJICVEZDiYvIFYq0BWKhVEJBINoUDgdX5kCzRaJ9QZpdnsTlGdicDaiUiUGiKAIuPRFADEDCsLCsRSwAQ0LG0ugMQJMtXdZDGDkOQiUIBIExItLMDCkUfKsdpyEjIHsuDAm3cyc8-jSansToo0V+OY2eaLZBM-CINgmjIYXnrhch9k8ZeraiCASQOiIeklPErejIMAsCG5Kk5IBwZHgJjVVBqSCESzdHpsXhXNkwQA).
