### ISSUE TITLE
Observers set up using `{ handler() { .... } }` won't always fire

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#3081]
## Description:
Observers' handlers set up using ["options-friendly" object](https://ractive.js.org/api/#observe) won't always fire on change.

Still working on a reproducible fiddle, as it happened on a complex side of my application.

I was observing a passed computed property (from parent component, passed via attribute, `isolated: true`), using an observer set up via `{ handler() { .... } }`. Sometimes, it wouldn't fire.

Simply switching to a plain function, rather than the object with `handler`, fixed the issue.

## Versions affected:
1.0.0-build-64

## Platforms affected:
Chrome

## Code (I'm still working on reproducible fiddle):

Observers written like this, sometimes **fail** to trigger:
```javascript
Ractive.extend({
  // ...

  observe: {
    myKey: {
      handler() { /* won't always trigger */ }
    }
  }

  // ...
});
```

While observers set up like this, seem to always **work properly**:

```javascript
Ractive.extend({
  // ...

  observe: {
    myKey() { /* always works as expected */ }
  }

  // ...
});
```

Are observers handled differently based on how they're set up?

**Comment by evs-chris** [comment]
The code that handles subscribing from `on` and `observe` keys is [here](https://github.com/ractivejs/ractive/blob/dev/src/Ractive/helpers/subscribe.js#L8-L12), and there should be no difference between using a handler in a object vs using a function. What options are you passing in the config version?

**Comment by giovannipiller** [comment]
> What options are you passing in the config version?

No option, just a plain object with the handler.

**Comment by giovannipiller** [comment]
On Monday I'll try some debuggers here: https://github.com/ractivejs/ractive/blob/dev/src/Ractive/prototype/observe/Observer.js

I think I'll start from `handleChange` and see where things go.

**Comment by giovannipiller** [comment]
..ok, hopefully I'll debug it next week :)

**Comment by giovannipiller** [comment]
Finally reduced to a simple fiddle (Ractive edge, tested on build 64 & 67): https://jsfiddle.net/7ojwab76/3/

Looks like it wasn't a problem on **0.9.3**: https://jsfiddle.net/7ojwab76/2/

```javascript
// child component
const MyComponent = Ractive.extend({
  template: `<button on-click="@this.add('proxiedCounter')">Change data: {{proxiedCounter}}</button>`,

  isolated: true,

  observe: {
    proxiedCounter: {
      handler() {
        // will never fire when interacting with the button
        console.info('fired handler');
      },
    },
  },

  oninit() {
    this.observe('proxiedCounter', () => {
      console.info('fired observe');
    });
  },

});

// root component
const r = window.r = new Ractive({
  el: '#main',

  template: `
  <article>
  	Open the console and click the button.<br><br>
    <strong>Two observers should fire each time</strong>, but only the one set up via this.observe(...) does.<br><br>
    {{#if show}}
	    <MyComponent proxiedCounter="{{counter}}"/>
    {{/if}}
  </article>
  `,

  components: { MyComponent },

  data: {
    show: true,
    counter: 0,
  },

  onrender() {
    // without this code, everything works as expected
    this.toggle('show').then(() => {
      this.toggle('show'); // final state => true
    });
  }
});
```

**Comment by evs-chris** [comment]
Ah! The config object was getting a fragment set on the first run, which caused further init to resolve in the wrong context. The fix was simply to use the config object as a prototype on an empty object to pass through the `observe` machinery. This should now be fixed on edge.

That was a nasty one to reproduce. Thanks wading through it!
