### ISSUE TITLE
Conflict between partials and line positions, missing hasOwnProperty check

### ISSUE THREAD

**Issue by MartinKolarik** [ractivejs/ractive#3082]
First, a demo:

```js
new Ractive({
    el: 'body',
    template: Ractive.parse('<div>{{>sort}}</div>', { includeLinePositions: true }),
});

// Uncaught TypeError: Cannot read property 't' of undefined
```

https://jsfiddle.net/4cLtuk81/2/

A `p` property is used to store inline partials as well as line positions, which can lead to some hard to find bugs. [Here](https://github.com/ractivejs/ractive/blob/76e49bd6ba0ef982dd8e7fd9e3e89adf779a29f8/src/view/items/partial/getPartialTemplate.js#L92) Ractive checks for `p[name]`, but `p` can also be an array of line positions that have nothing to do with partials.

Because Ractive uses `p[name]` rather than `p.hasOwnProperty(name)`, this check returns `true` for all methods on `Object.prototype`, and when `p` contains line positions, also for `Array.prototype` methods (which causes the above bug).

To fix the demonstrated bug, adding `.hasOwnProperty()` would be enough, but I think line positions should also move to a different property, as there might be other edge cases this conflict causes.

**Comment by evs-chris** [comment]
> I think line positions should also move to a different property

I concur. I feel like `q` should be pretty safe. `i`, `n`, and `l` are already used in sections. A cursory glance shows that there are only three places that it needs to change.

**Comment by MartinKolarik** [comment]
>A cursory glance shows that there are only three places that it needs to change.

Plus all the tools that use it, which is the worse part. But better than random bugs like this.

**Comment by evs-chris** [comment]
> Plus all the tools that use it

Ahhhh. I see now that rcu uses that info to generate source maps. That is unfortunate.

It _looks_ like rcu gracefully handles `.p` not being a position array, so it would probably be safe to not break the template format now and just fix the places that look for partials in `.p` on element AST nodes.

**Comment by MartinKolarik** [comment]
Maybe but if it is going to change, it's better to do it before v1.0.0. I can update rcu just not sure what else uses it.

**Comment by evs-chris** [comment]
I was thinking break it _at_ 1.0.0 by throwing this into the 1.0.0 milestone after the immediate issue is worked around. That way 0.9.4 (hopefully) won't surprise anybody with extra tooling breakage. Does that sound reasonable?

**Comment by MartinKolarik** [comment]
Ok that sounds good. It seems the only other two places where `p` is used in Ractive are:
https://github.com/ractivejs/ractive/blob/e7317ba889760d2831c2f95af183dfe1052e0b87/src/parse/_parse.js#L128
https://github.com/ractivejs/ractive/blob/e7317ba889760d2831c2f95af183dfe1052e0b87/src/parse/_parse.js#L141

**Comment by MartinKolarik** [comment]
Would have fixed it already, but:
```
$ npm start

> ractive@1.0.0-edge start C:\Martin\Projects\~\ractive
> gobble --env=dev:browser serve

gobble: server listening on port 4567                                                                                                                                                                                                                       
gobble: livereload server running                                                                                                                                                                                                                                    
∙∙∙∙∙∙∙ 10-rollup running...                                                                                                                                                                                                                                 
gobble: 10-rollup transformation failed
                                                                                                                                                                                                                             
input:  C:\Martin\Projects\~\ractive\src
output: C:\Martin\Projects\~\ractive\.gobble\10-rollup\1
>>>
Could not load C:\Martin\Projects\~\ractive\src\utils/is (imported by C:\Martin\Projects\~\ractive\src\Ractive\static\interpolators.js): ENOENT: no such file or directory, open 'C:\Martin\Projects\~\ractive\src\utils\is'
Error: Could not load C:\Martin\Projects\~\ractive\src\utils/is (imported by C:\Martin\Projects\~\ractive\src\Ractive\static\interpolators.js): ENOENT: no such file or directory, open 'C:\Martin\Projects\~\ractive\src\utils\is'
    at C:\Martin\Projects\~\ractive\node_modules\rollup\dist\rollup.js:9461:10
    at <anonymous>
<<<
```

For some reason rollup tries to load all files without the `.js` extension.

**Comment by evs-chris** [comment]
You don't happen to have node 8, do you?

**Comment by MartinKolarik** [comment]
I sure do.

**Comment by evs-chris** [comment]
I think npm 5 has some... issues. Try dropping back to 6 with n or nvm, deleting node_modules, and reinstalling them.

**Comment by MartinKolarik** [comment]
Switched to `v6.11.3` and reinstalled, but same problem. I'll try Ubuntu instead of Windows to see if it's OS dependent.

**Comment by evs-chris** [comment]
Note to self, readjust for 1.0.0.
