### ISSUE TITLE
How to teleport a component back and forth?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3084]
## Description:

An application has the following component hierarchy: 

```html
+ c1
    + c11
    + c12
+ c2
    + c22
        + c221
    + c21
```

I need to teleport `c221` onto a mountpoint defined in `c11`. Following code: 

```js
c11RactiveInstance.attachChild(c221RactiveInstance, {target: 'myMountPoint'});
```

throws the following exception: 

```js
Error: Instance r-15 is already attached to a different instance r-11. Please detach it from the other instance using detachChild first.
```

...where I couldn't figure out how to use `detachChild`. Closest reproduction code is here: [Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutR-AAgC8A4uWp0EADzJckACmAAddkrKzWAGyKzIApSAA8AIwCu6jgD4mATwGNWHLmT3BgNigk1IMGQwHozC3ZLAxUMAEoVTgB3UVJKGkUVNS89AHIAYgZzFnN0rBT1BC0dBD0AAyK1QzAAZlDVMjU1ABUYInZcNhgyASCyDgFcMBzvATIOrp6+sjAEAUNGJAXcMhtNBCEDRk0GGD0YsApZAG5+0gBrFBgc9iQAWl39vRuiGwNLec09gOWESz9cyDdj6JotMgAM1uTAENi8eziSGoEwYAhgyAEyKo1TIAXqjQhuNxhgAhA8HgIKdSabS6fSGRSqQ9Cc08QMhhwnpoKCRLttwAgPiBLJNOt19njAsCrCTscN1psBcZ9isDgIAEwsKTDBg8pBwhEMGLnJgUdgPeYUFBgFwCACsAAZtZ9iXj+EQvkaAh7WTV-Ni-Xj5WsNlsDCqYGq9ABGbW6-Xo5Cm82WhDW216J0ukVuwyZAS2AT+IMBQNFCpYMFqDgY+4IdWQ0zscQceQRZTgkELERzCi4XFkGJo3vHXiQ81IADCzDYnG48nSHvSUS7fd4bc7RLmQr0TZblDbHbdan8-ictBWZFIYCnx288iHDAi52L-gE7AYfWHMEu5pQJ5kGeT6Xgg14kLe94KC+EJvh+X4CD+f7sABXYQheOjgZBFAPk+VbANeMBoHa6S2OkkSnG6GC4hRRTUewkQgDgZDwIY8oUEgAo5GQeTNCKZbUJYmBAA)

**Comment by ceremcem** [comment]
[ractive.insert](https://ractive.js.org/api/#ractiveinsert) might be [what I was looking for.](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutR-AAgC8A4uWp0EADzJckACmAAddkrKzWAGyKzIApSAA8AIwCu6jgD4mATwGNWHLmT3BgNigk1IMGQwHozC3ZLAxUMAEoVTgB3UVJKGkUVNS89AHIAYgZzFnN0rBT1BC0dBD0AAyK1QzAAZlDVMjU1ABUYInZcNhgyASCyDgFcMBzvATIOrp6+sjAEAUNGJAXcMhtNBCEDRk0GGD0YsApZAG5+0gBrFBgc9iQAWl39vRuiGwNLec09gOWESz9cyDdj6JotMgAM1uTAENi8eziSGoEwYAhgyAEyKo1TIAXqjQhuNxhgAhA8HgIKdSabS6fSGRSqQ9Cc08QMhhwnpoKCRLttwAgPiBLJNOt19njAsCrCTscN1psBcZ9isDgIAEwsKTDBg8pBwhEMGLnJgUdgPeYUFBgFwCACsAAZtZ9iXj+EQvkaAh7WTV-Ni-Xj5RQkALIQwGAYFRstgYVTA1XoAIza3X69HIU3my0Ia22vROl0ikkB6isipYMFqDgY+4IdWQ0zscQceQRZTg9QxNEiOYUXiQ81IADCzDYnG48nSHvSEVOuLIRBgaD6feOg+H08yEYYc4XXf7vDbnaJcyFeibLcobY7brU-n8TloKyXJDAI+O3nkZB784EAiPgI7AMH0PYwJc5ooPeZCPr+DAvggb4fl+CjzhCgH+MBoECOBkHsNBXYQvBtDmrgDZkD+y6ruhRFkBguKRAeagMewkQgDgZDwIYIZhgYORkHkzQigEgaYEAA)

**Comment by evs-chris** [comment]
Regular and anchored components aren't interchangeable as it stands right now - components are either fully managed or fully unmanaged. You _can_ detach and insert, but it might cause weird things to happen. Your best bet for jumping about the dom would be attaching and detaching external instances.

**Comment by ceremcem** [comment]
I was about to close the case as [this](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutR-AAgC8A4uWp0EADzJckACmAAddkrKzWAGyKzIApSAA8AIwCu6jgD4mATwGNWHLmT3BgNigk1IMGQwHozC3ZLAxUMAEoVTgB3UVJKGkUVNS89AHIAYgZzFnN0rBT1BC0dBD0AAyK1QzAAZlDVMjU1ABUYInZcNhgyASCyDgEYik1NATIOrp6+sjAEAUNGJAXcMhtNBCEDRk0GGD0YsApZAG5+0gBrFBgc9iQAWl39vRuiGwNLebGGAOWESz9cyDdj6JotMgAM1uTAENi8eziSGoEwYAhgyAEyKo1TIAXqjQhuNxhgAhA8HgIKdSabS6fSGRSqQ9Cc08QMhhwnpoKCRLtsQEwGDRPpNOt19njAsCrCTsQI1hstgZjPsVgcBAAmFhSBUMHlIOEIhgxc5MCjsB7zCgoMAuAQAVgADDrPsS8fwiF9jQFPayav5sf68fKKEgBZCGAwDAr1psBaqYOq9ABGHV6g3o5Bmi1WhA2u16Z2ukDBgJBooVLBgtQcDH3BAayGmdjiDjyCLKcHqGJokRzCi8SEWpAAYWYbE43Hk6U96Qip1xZCIMDQfX7xyHI5nmUjDHni+7A947a7RLIQpoembrco7c77tr3gAMgwSDoKEN+73aMvVwgyEPc81DIH8LVwRsyHkP81wXR8eAA1oKCYBAcigm823YDszzZc9QIYWhwMg+R9SQV93zvdg4O7CFsC1J0GKiGiyAwXFIiAljwgiEAcDIeBDFDcMDDQvJmlLctqEsTAgA) is what I was looking for. Should I avoid that?

**Comment by evs-chris** [comment]
Ractive assumes that any dom it creates won't be moved externally, so there are some processes that will have issues, like transitions checking to see if one node is contained within another or sections trying to use a moved node as anchor for insertion of another. That said, if it doesn't blow up in your use case, you're probably good.
