### ISSUE TITLE
How do we set the event attribute for a dynamic component?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3085]
## Description:

Like we register a `hello` handler to a component in HTML: 

```html 
<aaa on-click="hello">say hello!</aaa>
```

how do we set the attribute on a dynamic component, hopefully [easier than this way](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gIZEAEAvMQEoEDGALgJYBuCAdAgB60IB2SAFMAA63YsS4BbAA4AbAl0jEABsNGiAPACMArrVoB7EQYC01afWoBrUoJAB9U+Ys2AfLgIBPYmATTpegITEfDA8SAgwxNR6Wty0CsDAUTG0GBgAlGoA9Nq6Bs4qSlgFBiG84QoAZjF09AZ8aUIixIK6YPS4LARI-ADkSbE9aQDcBdgFSHIEldUMdQ0FLSG0WjAijaItLf1xxAAMCymjwunCwlQ1zAIFtAQwaDs9GnpI7j1FTRM38QWi4rgoCh6AAkfH4sMQAOp6GDSJD+Hqjd6iCQyOQIBTKJotTQ6fSGbgmMyWawgcR6ZguMnMYj0WhZHJ45zEHG5fGExwk+4AIRoThAznuxA0vPpuLyBzUSCYxFwtHc0gQJKeMDCMAUAGZJOwZXozEhiCEkEMvAh6CgwDsAKy7LUuH7MgDExHEnky+Sa6kyUsY7o2dO9MrlCqV0NVGq1Or1xHcoL0AHdjd4zRaFNbbfz7Wone5ohE3ZmvUxfYVitxSmHiFVuDU5o1NrRbLYyGI2rgRtx7ZlMsQAMIhNHEbgIOM07iy7g0BD27XkIgEert1TEdgsOrrVQtexEizTauzbj1Ou0eub2wsCr0EJ8HreXx6QbGjfH48e5qHV8nDvPxudXQ0MA9m0sJ8Ow4LAGItz3ICLo9J+9a0K2q4Hke9ZUuilYzLUB7zF+J4NmeYQ3NQAFAfw7DDKcz71j+chESR9DAaBxDgTcdwIA8OYrLBaSUfWYy4c+3K8ruNbYShVH4SwhH-oBDFkRRAnUWetEyaRIFgRBbEPDBcESfxeG3n4In7oevESQQCowLQ14Ie0NK4JWMB6OIxAvBO4jmJEzmSAYPC0IMZktBgZmfqIwXcOkmBAA)?

**Comment by evs-chris** [comment]
You can throw event directives on anchors to e.g. `<#anchor on-someevent="@.doThing()" />` and it [works as you'd expect](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gIZEAEAvMQEoEDGALgJYBuCAdAgB60IB2SAFMAA63YsS4BbAA4AbAl0jEABsNGiAPACMArrVoB7EQYC01afWoBrUgG0A5GATTpe2wF0AfLgIBPYg6d6AITEfDA8SAgwxNR6Wty0CsDAMXG0GBgAlGoA9Nq6Bu4qSlhFBmG8kQoAZnF09AZ8GUIixIK6YPS4LARI-LYp8bYZANxF2EVIcgTVtQwNTUVtYbRaMCLNom1tAwnEAAyLaWPCmcLCVHXMAkW0BDBou7YaekjetiUtk7eJRaLiuCgFLYABKOZxYYgAdT0MGkSECtjGH1EEhkcgQCmULTamh0+kM3BMZkspEEIHEemYZPcFOYxHotByeXx7mIuPyBKJ5isZIeACEaBZqQ9iBpBUy8QVDmokExiLhaN5pAhSSBnjAIjAFABmSTseV6MxIYhhJDDPwIegoMC7ACsez11N+bIAxMRxL5jP5nKqAAIoZxi6TdZUwWh8Wy0Dq4ekxqowPTiYivbgEcTmaKJyQGHi0YhyVrk7xkoZk4jZQotdTZWWMSubRm1+WK5Wq9WanV6g1G4jeMF6ADu5ocVptCntjpA9dUajd3liUS9-b9Ab0QZDkXDkejseI8cTye8qfT1EzUhz8XzebJ89WJYyZYrzpytenimRxDK4Uqe9m9W4jTNFstAAPogWQYjRqM3DOtk2TEAAwmE6LENwCADvS3AKqm1AIM6+rkEQBCNNBwFgd0ug0GACEdHCfDsBCwBiHcDxAh6tinDBtBtFGnQsA0QHcUJtIYr+3B1PMgnAW05ERLc1DUbR-DsCMZxCWRIEUfJin0HRDHEExtz3Agjy3jAHEPlxwHjFZQn8oKMziXMAELLZGksHJVE0bpymqW5QnkXI2neXpjHMcZjzsZx0lHLZnGiBgJwZJgQA) coming from fully-managed components.

**Comment by ceremcem** [comment]
That was easy. I'm adding [this](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gIZEAEAvMQEoEDGALgJYBuCAdAgB60IB2SAFMAA63YsS4BbAA4AbAl0jEABsNGiAPACMArrVoB7EQYC01afWoBrUoJCnzFmwD5cBAJ7EwCadL0BCYnwwPEgIMMTUelrctArAwBFRtBgYAJQB4gi4LmixwBlZBGjJKWoA9Nq6Bo4qSlg1BkG8oQoAZlF09AZ8KUIixIK6YPS4LARI-ADkCdETKQDcNdg1SHIEre0MXT01A0G0WjAivaIDA9MxxAAMO0mLwqnCwlQdzAI1tAQwaBcTGnpIrgmdT6Kw+sRqonEuBQCgmAAkvD4sMQAOp6GDSJC+CaLYGiCQyOQIBTKPoDTQ6fSGbgmMyWawgcR6ZhOJnMYj0WhlCpUxzECmVam0+wM74AIRoDhAjm+xA0ku5lKqNzUSCYxFwtFc0gQDL+MBCMAUAGZJOwNXozEhiEEkHMPAh6CgwBcAKyXM1OCH8gDExHE7mMdnpNgA2hNPN49EDiBMAxMALo2f2ZbK6mxxKEoZLJ0rVPrqUpqxj5k5c4sarU6vXow0ms0Wq3EVyIvQAd3tnidLoU7s90u9aj9rkiYSDdKsYYjrZjExHB0TyfyaYZcQATMQAFT+6E5kDEPODotMUuqNRgY2OedhZeFBAOoJlC+n9T0biSHTERgEaRadMgTNdwwXNT0UPFiAaYJmmINpuA6LZelOWgAH1kLIMQhlwBZuG9UpSmIABhIIiWIbgEDbDluE1bgaAQb1zXIIgCG6bCkNQ0ZdBoMACKGTE+HYZFgDET5vlheMHhw2gBloTCWC6RCpMUtliRgjZOm4boFKQgZ2JCD5qG43j+HYeZHkUtjkI4-TDPoPiBOIISPi+BAfmvCYJO0pJgU88VJXWODNg07ZJM83SXK4njbOM0yQvMlDLLkazIrswThOcn5xJSMykKWWKBmnKMJn8+CNLoezcFHagEGCzyBh-UJaD4GxIx8GCYD0cR+n3ABqC0Diq4heuTNtOTAFMChyLrBvCWh2BYCIpAMHhaBYb4+DjVM71mLK8tuWKJNEYDuFSTAgA) one to my list to add into the documentation.
