### ISSUE TITLE
How do we create nested dynamic components?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3086]
## Description:

How can get `<bbb />` component appear dynamically in `<aaa />` component where `<aaa />` is a dynamic component itself like [in this example](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEZEAEAvMQEoCGAxgC4CWAbggHQIAedCAdkgBTAAOjyF1uAWwAOAGyrdIxAAYAeAgFdxAex4A+IgWIMeuOlR40ExYMACeDBDKQYMKgPQbtepSIwBKEREqYLJKWkYWdi5eAWEeYmJJWXkERR94hOI1TTodYh0AWhoZBhoAa1IhEAB9YtKyqt1cKltiMEcZLQBCYn4YGIQYYhotdR46RRsRsboXP3dPXL0RTKyAYny6dqG3XRXlLH2dfr5BxQAzMfoGHX4-OISxLYZcViokAQByafHPvwBuQKiOhiNxuYhXLQSCS8Rg8FCJMAvYi4BDXPIEfpUMq4RFWYJUYZQqQ6WG9JBaBC4nhaOjEc4MfrET61ErlP77UEeACMoQMd0BGS5z1e8jMNDAAGEkU5+ARuVhrGYYGgJszadtPv5BQlsPskPIqBcroxbvdOXR+nR1DB4g9iGIxD81QAGC0YfYenj+IHUa4sQT7ZWqxSfAhaJC2T6HDIGsyTfYJCS4FChgASHS0ioA6loYE4up9PTGEkk5AplBbsl58jwimyKlUJFoWI1mywjHQFjkdLosos8oU6uVKiBVQAhWgNEC6VXEAhT7tePZCrtIZgoui2GQIUfhmBIM7EADMUg4KK0JSQxH6SH+bQQDBQYDVAFYXWfGon1sQJK1dt+7jrkwK6PGuG6mNuu5VPuh4wIop7nrgl4MNetiZgA7ve7RPi+ijvp+M6ARstijDsoGZEBzAUUoJa1iccHGhYpo8HccSOnQ1TVKEIqCt+YLEJKWLcMQPAIBhRgmHQPC0Ag37nuQBICvJrC3PaYGsvUTHoqx5rAhxYhcawDL9PwnztDInR-PemQGRkYFeqsPr6Zx1RvOItBSjKAgcIqwCJFQKoIGqnx-lqAQuSKqmsexIJxe2qT0iaNy6bFBmuawh7il5DCyhwAKBHFHFGWKnnSrlPl+QFQUhaRNrhYVHF6i5YgTlO2ksWxjVFRlWVld5-D5XxPWGW5pUSuVeVVcGwWhmFznpc16UWZ0HUpV1LVxVQO4wHQZkikYuLnDAULEJGMkSKURLSKSvwRYt3XObqvh+JgQA)?

**Comment by evs-chris** [comment]
This is an interesting little problem. The `yield` is created when the component is initialized, _but_ there's no parent instance to set up as a container for the yield so it throws. This _should_ be possible, but it will take me a little while to rearrange things such that it is.

**Comment by evs-chris** [comment]
As of edge, partials will set up component/container stuff on bind rather than at construction, which means that an instance can pick up its container when attached to an anchor when the attachment triggers a rebind.

**Comment by ceremcem** [comment]
Current Ractive@edge build in the Playground is `7d28142126f02e59cd3ac57690caaf18f4c79713`, when will it be built for `918c0f43b2e73d4089f41a9f7295860b2aaf7430` (the commit that closes this issue)?

**Comment by ceremcem** [comment]
(don't mind, it seems a caching issue :P )

**Comment by evs-chris** [comment]
Yeah, it usually takes ~20 minutes to go through Travis -> npm -> jsdelivr to get to the point that you can [evict it from the cache](https://xkcd.com/1854/).

**Comment by ceremcem** [comment]
[Works just great!](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3rgDYIIAOABALzkBmArgHYDGALgJYD2DAFALa5ZaDAJTByuBCwAqbXgg50W3Gg0H9hAbnIYAOgz0AjI1XIAlAIas2ANwQA6BAA8WCBkm7A9Oli96lC5i6Q5AAGADwGiixcAHxGBuRsDLgs5swI5MDAAJ5sCIRIGBhhAPSRPrEhehjCXgzmDSYWVrYOzq7ungzk5L7+gQjBVd095BFRXORcALRMhGxMANaUOiAA+nMLi6sxuObZ5GD5hBwAhOTcMB0IMORMCgwswVn3jCxFwqXl0QwxeqNjADEUxYR1uJT+IxCWH+UwYVzcN2C9GY7C43FEsO8oLYuDs5iQ7gA5K9HkTNHVvN4SiVyIx7rw5I8kihemBceIEFZJgYruZFrg2RkGuY7hw-FxXCwLkgOAhBQwONKaGwruQiRt5ktyV4WN4iCRSNwAEwABnNgmU9LRPEx+ml5G8BgAjCZ4hiNLqATi8YFUkwwABhdkFbguwTAVIwNBPdVKsFEmqe+3eGp2AxJdw+4S1bqw7CwpCBczI62cW1dHreK4sOgwbqVx16lik2OmrHvfPVXN6ZrsWweWFRmPBIkGDhIbJEmEjIupZ6wnr8FCjgASxw4ggA6hwYAVTkT8zOen0AkFQh3xhVujNNksViBeBxbDsn7ZEiwvhNfmNvpNb1qyyrDGABCljbCAMQxuQBjgV+16QlWn5IDY4gsNkxAPuOMBIEi5AAMykI44gcPMSDkFcSBaEcbAoGAsYAKymkROyLkC5C8AcEJsaUKHWIhTZhHxaEYQgWG7rhMDBIRxG4KRbDkdkG4AO7UQgtH0cETEsZBPHAtkCjggJPS8TYAnQrCXAIpJpaouWGJdFSLBrGsJg+smbE0uQgZ8i45AMAgymJMkLD1EwCBscR1Aih6kV2OijZIZqWy2dyFa6k53guXYKpXNwRJHIQJzklooyZSMSG6BV2g9s22V+pYQYhu4jgRr05jRpIo6cYmtXYuyeIJRlzZvoMtBluidqZXVax2Lh-pNWwoaOBSKbNlls0NQGwZLS1bXDl16oGXWvXDamM7TaB4GpTaDlnTNc2SI1O3Lat00bfiPjPc13CtZk7WdbGRI9TU90Fmt3iFScN32VN63NuYxAwEoRI+okgo0DA4rkJO9S8AsYoSgFZJ9c2VVOaDIxVTUmBAA)

**Comment by MartinKolarik** [comment]
@evs-chris jsDelivr actually caches all files for a week at CDN level. `ractive@edge` link would be a great use case for our new purge API.

Purging a cache is as simple as making a GET request to `http://purge.jsdelivr.net/npm/ractive@edge` so it's easy to make it part of the build script (take any jsDelivr URL, replace `cdn` with `purge` and `https` with `http`).

We could probably use it for the link we have on homepage too -
 `http://purge.jsdelivr.net/npm/ractive`

**Comment by evs-chris** [comment]
So just a curl to the purge url will clean out all of the relevant cache? Any auth needed? If that's all there is to it, I'll just pop the curl in after the npm edge publish.

**Comment by MartinKolarik** [comment]
@evs-chris yep, and no auth for now.
