### ISSUE TITLE
Strange behavior of dot inside #each

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#3092]
## Description:
In this sample the second column of numbers after few insertions has all numbers the same, but expected to work same as other columns
http://jsfiddle.net/Inversion/t0yf7sqx/
On v0.7 it works fine, as expected.

I do not get something about using `.` as a shortcut for `this`, or it's a bug?

## Versions affected:
At least 0.8, 0.9

**Comment by evs-chris** [comment]
There was an uncovered corner case in reference expression handling and shuffles. This should be fixed in v0.8-dev and edge and will go out with 0.8.15 and 0.9.4 when they are cut. Thanks!

**Comment by Inversion-des** [comment]
Thank you again for fast fix!
Just posted another strange case…
