### ISSUE TITLE
Merge breaks running transition

### ISSUE THREAD

**Issue by Inversion-des** [ractivejs/ractive#3095]
https://jsfiddle.net/Inversion/7vv898aq/
In this case when you hit "+ pro" button, 2 new items added with some delay and both should be added with slide transition. 

Results are:
v0.7 — all works fine
v0.8, 0.9, edge — first transition jumps to end when second starts.

There is no such issue when you push to and render same array, but in my case rendered array should be sorted, so I use merge on every array change to support transitions.

This simulates situation when 2 new items are being added with very short time interval.
But I found this issue because my observer sometimes triggered twice instead once, so for me animation was missed at all.

**Comment by evs-chris** [comment]
This appears to be resolved as of 0.10.
