### ISSUE TITLE
[Question] instance methods are accessible from template without using `@this`

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3098]
## Description:
Components methods are accessible from template without using `@this` reference. 
Is this the exepected behaviour?

## Versions affected:
- edge
- 0.9.3

## Platforms affected:
- Chrome 61 on MacOS
- Safari 11 on MacOS

## Reproduction:
https://jsfiddle.net/w2zvmvwL/

```javascript
Ractive.components.MyComp = Ractive.extend({
  template: `
    <h1>My component</h1>
    <p>Instance methods are accessible from template also when not using @this.syntax</p>
    
    <h2>Without anything</h2>
    <p>myFunction (toString) -> {{myFunction}}</p>
    <p>myFunction() -> {{myFunction()}}</p>
    
    <h2>Using @this</h2>
    <p>myFunction (toString) -> {{@this.myFunction}}</p>
    <p>myFunction() -> {{@this.myFunction()}}</p>
  `,
  data() {
    return {
      things: 'something',
    };
  },

  myFunction() {
    return 'my function output';
  },
});

const r = window.r = new Ractive({
  el: '#main',
  template: `	<h1>Hello!</h1>	<MyComp/>`,
  data: {}
});
```

**Comment by ghost** [comment]
That's expected behavior. Ractive [includes instance members in the resolution pile](https://github.com/ractivejs/ractive/pull/2720#issuecomment-258666010) as of 0.9.

To disable this, set [`resolveInstanceMembers`](https://ractive.js.org/api/#resolveinstancemembers) to `false`.

**Comment by evs-chris** [comment]
Yep. Also note that this will change to be defaulted to false for 1.0, as it does more harm than help most of the time.

**Comment by marcalexiei** [comment]
Sorry, I haven't see it in the documentation. 
Thanks for the explanation!
