### ISSUE TITLE
Question: Async/lazy/dynamic components/elements

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#3099]
I've been pondering a few different things primarily related to decorators, async loading of components, and other dynamic-ish template things. Everything relates to dynamic/lazy loading of components and also to dynamic lightweight component-like elements.

**WARNING**: What follows is a long and rambly. The TL;DR is that I think a new simple template item that is a sort of component/partial/decorator/parser transform hybrid would be tremendously useful, especially for implementing future constructs as external plugins e.g. dynamic components (`<Component component-name="{{.type}}" ... />`) and async components (`<Async async-src="some/path" ... />`).

## Async components
Loading a component that loads and caches another component to use as a pass-thru should definitely be possible. Something like `<Async async-src="some/path/or/something" mapping1="{{.foo}}" etc="you get the idea"><loading>Not loaded yet...</loading>Stuff outside of the loading tag there is going to be supplied to the actual component as content...</Async>`. I think all it would take to implement that would be to add a low-level API that allowed a component to cause its host VDOM node to unrender and render again - like maybe `this.component.reload()`.

The placeholder component would need to be supplied with a way to turn a name/path string into a Promise for a component constructor, which with webpack would just be fronting `System.imports(path')`. It could then check its internal registry upon `config` and if the component was already loaded, skip displaying the placeholder, update the component VDOM name and maybe template a little, and trigger a deferred reload. If not loaded, go ahead and set up the placeholder render, start the async load, and wait until the load finishes to trigger the reload. All-in-all not terrible, though there is some mild abuse that would need to take place at the template AST level, but for a low-level component I think that's not unreasonable.

## Dynamic element constructs/lightweight component-ish things
Pseudo-related to that - 0.9 introduced experimental parser transforms, which allow you to supply a hooks that process templates on their way out of the parser and transform them at the element/component level. This is a very convenient process for things like turning `<card><title>stuff</title>some stuff</card>` into `<div class="ractive-material-card"><div class="ractive-material-card-title">stuff</div><div class="ractive-material-card-body">some stuff</div></div>`. Using that and a context alias to `@local`, you can achieve something like a lightweight component with no performance overhead. Obviously, you don't get things like complete data isolation, full instance event support, and independent custom css on your "component", but there is a pretty large class of widget-y components that don't call for those sorts of things.

That card may not be the best of examples, but it's a tremendously powerful thing for making declarative ui easy and dry. A full component for a material card is a pretty severe bit of overkill, especially if you have more than a small handful of them to render. My last round of performance estimates came up with a limit of 1000 components on a page for a reasonable initial render on desktop-class machines - and that number would preferably stay less than 100 for mobile-ish things. Plain template is wicked fast, comparatively.

The trouble is that the parser hooks have to be in place at build time when dealing with something like the ractive bin, which all production code hopefully does at some point. Being able to run a transform taking `<card>...</card>` at bind-time and turning it into the appropriate bit of template would remove a significant barrier to convenient use of something like parser transforms.

## Tying it together
So looking at both of those, it occurs to me that there may be cause to introduce a new simple VDOM item that is a placeholder for a bit of template that can cause itself to reload. Something like a decorator for partials, where you can take advantage of the template constructs available to elements and components and get a handle to the place in the VDOM to trigger a re-render of the placeholder. That would remove the overhead of the wrapping component for the `Async` above, as it would become an inline transform that would also skip the requirement of deferred re-render of an already loaded async components. It would also cover dynamic components, as that would just be the `Async` transform without the asynchronous part.

The dynamic element side is also covered, as the transform gets to return whatever template it needs to after having processed itself and its parts.

**Comment by ghost** [comment]
I'm not too familiar with async-loaded components. What are the current implementations at the moment and how do they work? I'm thinking it's AJAX and a self-registering component or eval-on-arrival, but I'm probably wrong there (still thinking in terms of `ractive-load` for the mechanism).

**Comment by evs-chris** [comment]
There's really not an async solution at this point. If you have `<some-not-loaded-component />`, you end up with an element rather than a component. So your only way to get async is using anchors or by placing guards around all of the component use sites and triggering the load at some point that you know it needs to. My current approach loads all of the widget-y components that I need with the main bundle and defers view components until they're needed on some sort of menu event with something like

```js
const registry = {};
this.on('load-some-view', () => {
  if (registry['some-view']) this.attachChild(new registry['some-view'](), { target: 'view' });
  else {
    System.import('./some-view.ractive.html').then(view => {
      registry['some-view'] = view.default;
      this.attachChild(new registry['some-view'](), { target: 'view' });
    });
  }
});
```

**Comment by ghost** [comment]
I mean on other frameworks. What's their approach to doing this?

**Comment by evs-chris** [comment]
Ah, that would be a ¯\_(ツ)_/¯ :smile:. I think vue is already entirely async, so it can block a chunk of render on a promise. I'm not positive though. I've lost track of angular, as it's too involved for my taste. I think svelte is about like ractive is now - conditional guard with the placeholder. React may fair a bit better having executable templates, but I don't know that they coalesce into a promise or thunk anywhere - and I'd guess that they don't. Anyone else more familiar with the usual suspects?

Having a component-ish thing that can start the load when it is called to render, render a placeholder if necessary, and then replace itself with the loaded component sounds like the most sane/least surprising thing to do though, no?

**Comment by sarendipitee** [comment]
I had a solution to this back in 0.6.x. I had to make stub components that
then required() a webpack bundle with all it's separate deps. When it
finished loading, it got a ref to the component, replaced its template and
did some resetPartial() hackery to get it to rerender.

With the way React renders to the dom it's much more simple, just needing a
single lightweight wrapper component that can be generalized to render
anything you need once it has loaded.

https://reacttraining.com/react-router/web/guides/code-splitting

**Comment by sarendipitee** [comment]
> Having a component-ish thing that can start the load when it is called to
render, render a placeholder if necessary, and then replace itself with the
loaded component sounds like the most sane/least surprising thing to do
though, no?

There's quite a few React libraries to do exactly that.

Ex:

https://www.npmjs.com/package/react-async-component
