### ISSUE TITLE
Ractive 0.9.4 - Internet explorer 11 – Ractive generates an error while included in webpack bundle.

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3102]
## Description:
Ractive 0.9.4 is not working on IE 11 while included in a bundle generated by webpack.

The issue is not present with Ractive `0.9.3`.

It seems Ractive code for is not "transpiled": 
![ractive-bundle-error](https://user-images.githubusercontent.com/24919330/31217847-a2360342-a9b8-11e7-918b-53ca8b350206.png)

## Versions affected:
- 0.9.4

## Platforms affected:
- IE 11

## Reproduction:
https://github.com/marcalexiei/ractive094-webpack-ie

**Comment by ghost** [comment]
Hmm... subtle transpilation bug between [0.9.3](https://cdn.jsdelivr.net/npm/ractive@0.9.3/ractive.mjs) and [0.9.4](https://cdn.jsdelivr.net/npm/ractive@0.9.4/ractive.mjs) only for ES builds. Both UMD builds not affected.

**Comment by marcalexiei** [comment]
I have tried last edge build: `1.0.0-build-70` and the issue is not present.

**Comment by evs-chris** [comment]
I missed a minor difference when updating the build on 0.9.4 with the edge build changes. It was skipping mjs files, which are the es module build that module-aware bundlers use by default, for the transpile step. This is fixed in 0.9.5. Thanks!
