### ISSUE TITLE
*-out directive seems to be broken in Ractive 0.9.3?

### ISSUE THREAD

**Issue by alexlibby** [ractivejs/ractive#3104]
## Description:
The *-out directive seems to be broken in Ractive 0.9.3

## Versions affected:
0.9.3

## Platforms affected:
Chrome 61 on Windows 10

## Reproduction:
The error can be reproduced by visiting [this Codepen](https://codepen.io/anon/pen/PJEqgR) - this contains a version of the ractive-transitions-fly plugin, tha has been updated to work with Ractive 0.9.3. 

The element flies in OK, but does not fly out. If you replace this line: ```<div fly-in-out>```  with ```<div fly-out>```, then it simply displays the text - no fly out action takes place. If you have ```just <div fly-in>``` then the element flies in fine. I've checked console, and cannot see any errors being generated - I've also compared my code to the main docs and can't see anything that I've missed

Question: have I missed something, or is there indeed a bug in how *-out operates in 0.9.3?

**Comment by evs-chris** [comment]
That pen appears to be tied to 0.4, but I _think_ you're just missing a conditional to cause the `div` to unrender. [Here's an updated version](https://codepen.io/anon/pen/QqmpVy) that should work as you're expecting.
