### ISSUE TITLE
set locking mechanism

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#3108]
## Description:

Docs have been explicit in saying that adaptors [don't detect `ractive.set` from within an adaptor](https://ractive.js.org/plugins/#no-built-in-infinite-loop-detection). That's fine since you might have a legitimate use for a recursive call, want control of the entire set mechanism, or to keep core code simple (every `ractive.set` will pass through the adaptor). But working on the official adaptors, two of them have their own locking mechanisms. Couldn't imagine every adaptor written would have their own, that's tedious. 

It would be nice to have any one of the following:

- Detect if a `ractive.set` is from an adaptor/observer/source of recursion and either:
    - Skip adaption.
    - Stop and warn that a recursive set is happening.
- Tell `ractive.set` to not adapt on certain invocations.
- Ractive to provide a static/instance method for tracking and releasing locks.

Thoughts? It's a nice-to-have-but-yagni kind of feature.

**Comment by evs-chris** [comment]
I haven't really looked into the details, but I lean towards the second one. It might even be nice to let it specify an adaptor e.g.:

```js
r.set('foo', bar, { adapt: false }); // YOU SHALL NOT ADAPT
r.set('foo', promise, { adapt: PromiseAdaptor }); // I don't always want my promises adapted, but when I do, I request it explicitly
```
