### ISSUE TITLE
What's the right version of Ractive.js now for new project?

### ISSUE THREAD

**Issue by nhaberl** [ractivejs/ractive#3110]
When I go to [https://cdnjs.com/libraries/ractive/1.0.0-build-73](https://cdnjs.com/libraries/ractive/1.0.0-build-73) I see builds of 1.0 but in the Github repo the last release was 0.9x?

What is the release to take for new project?

**Comment by giovannipiller** [comment]
Not a dev of the project, but as far as I'm concerned, 0.9.x is the way to go.
Latest release should be 0.9.5.

The whole 1.0.0-build-XYZ is there to make it easier for you to test upcoming changes, as a new build is published automatically after a commit.

**Comment by MartinKolarik** [comment]
@giovannipiller 👍 

Versions using format `A.B.C-build-XYZ` are pre-release versions of `A.B.C` (currently 1.0.0).

**Comment by evs-chris** [comment]
Also, the latest builds of 0.9 include most of the changes in 1.0 at this point. They won't really diverge much until just before 1.0 is released - at which point a handful of breaking changes will be introduced.
