### ISSUE TITLE
Is ractive.get supposed to return the original form of the data?

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#3112]
## Description:

Instead of a long description, a picture paints a thousand words.

![capture](https://user-images.githubusercontent.com/1582932/31854777-f086b27e-b66c-11e7-82b4-db5b84d13e4d.PNG)

The adaptor specifically tells Ractive to preserve the model when reset with a POJO on the adapted keypath. Therefore, a `ractive.get()` after a `ractive.set` with a POJO on the adapted keypath should return the Backbone model.

Expected:

- `ractive.get()` returns the model (`model1`)
- `ractive.get()` with `unwrap: false` returns the POJO representation (`model2`). 
- Adaptor would still work, updating in both directions.

Actual:

- Both `ractive.get()` return the POJO after a `ractive.set()` (`model3` and `model4`)
- Adaptor still works on the same model.

Digging in, it seems that after the `ractive.set()`, the `value` (holds the POJO version) and `wrapperValue` (holds the original data) are now both holding the POJO value.
## Versions affected:

0.7.3 and newer

## Reproduction:

```html
<script src="https://cdn.jsdelivr.net/npm/underscore@1/underscore.js"></script>
<script src="https://cdn.jsdelivr.net/npm/backbone@1/backbone.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ractive@0.9.5/ractive.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ractive-adaptors-backbone@0.3.0/dist/ractive-adaptors-backbone.min.js"></script>
```

```js
const model = new Backbone.Model({ message: 'hello' })
const instance = Ractive({ adapt: [ 'Backbone' ], data: { model } })

debugger;
const model1 = instance.get('model')
const model2 = instance.get('model', { unwrap: false })
debugger;
instance.set('model', { message: 'world' })
debugger;
const model3 = instance.get('model')
const model4 = instance.get('model', { unwrap: false })
debugger;

t.strictEqual(instance.get('model'), model)
t.strictEqual(instance.get('model.message'), model.get('message'))
```

**Comment by fskreuz** [comment]
Updated the scenario and it seems that the model is correctly updated https://jsfiddle.net/1w5v12tn/1/ but shouldn't Ractive be returning an instance of model in one of the `console.log`s?

**Comment by fskreuz** [comment]
Another update. More `console.log`s https://jsfiddle.net/1w5v12tn/2/ . This one shows that with pre-set data, Ractive does return the Model at one point. But succeeding `ractive.set`s changes this behavior.
