### ISSUE TITLE
How to set context variable on render within a component

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3113]
## Description:

Is there way to set a context variable without having a context object from an event beforehand? For example, how can we set the `.key` values in [this example](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutTAngAIAvIOLlqdBAA8yXJAApgAHXbKyc1gBsicyIIDkAHgBGAVw0cAfMGDsiTBBgxGA9OcvsrBrKvUcYeQQYfQAzM3YJDgUAShU1MnVXV0EkBkFcZgQyMAp2FEEidiQM7MEchEEAAwBrBH4qwTzysErGbhkyQTM2dkFA4uC-RI1c3lxshQNaOv4fFopeNDIp+0cDGJiAbmGMVQwY1U4AdzFSSholYYQtfQMTBiQ5rEFhzRYdPWrh9SMzLSsPxGtgAxAhSGByghcDxnEDfloKICEupUWRTFZZvpbDN6s43CYrEYBII1ghhMoQDiyXCQIJXMi0b9XIjGSN1LZXOCSGA4Sj0a5-myqr4EkhdERsUC5DDcPoANrwsh2BwIO6hBgMAzYV78jlku4mIgwbUvJUqxyGogAL21QIAurt9od2JggA)?

## Rationale 

I need to set values within a component on user interaction which has no way to trigger a ractive event on at that time (it uses a jQuery stuff under the hood).

**Comment by ceremcem** [comment]
...like in [this workaround](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutTAngAIAvIOLlqdBAA8yXJAApgAHXbKyc1gBsicyIIDkAHgBGAVw0cAfMGDsiTBBgxGA9OcvsrBrKvUcYeQQYfQAzM3YJDgUAShU1MnVXV0EkBkFcZgQyMAp2FEEidiQM7MEchEEAAwBrBH4qwTzysErGbhkyQTM2dkFA4uC-RI1c3lxshQMSMxgYWjr+HxaKXjQyKftHAxiYgG5hjFUMGNVOAHcxUkoaJWGELX0DEwYkJaxBYc0WHT1q4fURjMWisAJGtgAxAhSGByghcDxnGDAVoKKCEupMWRTFZFvpbAt6s43CYrEYBIItghhMoQASqUiQIIZnMaXTgLRGa50VjAa5UTyRupbK5oSQwEiMdjXMDBVVfAkkLoiPiwXIEbh9ABtZFkOwOBBPUIMBgGbCfKXCqlPExEGBmj66-WOG1EABeZrBAF1DsdTuxMEA), without using the `curr="{{.}}"` attribute...

**Comment by evs-chris** [comment]
Your best bet would probably be to map in the whole `test` object or map in the key too and set the key from there. If you don't mind some tight coupling and happen to have an element handy in the component template, you can [get a little whacky by jumping contexts](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutTAngAIAvIOLlqdBAA8yXJAApgAHXbKyc1gBsicyIIDkAHgBGAVw0cAfMGDsiTBBgxGA9OcvsrBrKvUcYeQQYfQAzM3YJDgUAShU1MnVXV0EkBkFcZgQyMAp2FEEidiQM7MEchEEAAwBrBH4qwTzysErGbhkyQTM2dkFA4uC-RLJknIpeXGyFA1o6-h8Wido0Mhn7RwMYmIBuYfVx3lWAYQ45WRmPMg4tleyABSIBtbIYMwQY2im12fnFw7uPw2CC2u2GGFUGDB7E4AHcxKRKDQlMMEFp9AYTAwkAssIJhpoWDo9NV9mQjGYtFYyepbABiBCkMDlBC4HjOGnkrQUakJdT88kmKzzfS2Ob1ZxuIVGASCYHCZQgMXAjkgQSuXkC9Rubmaka04CuRkkMAcvnk1yUvVVXwJJC6IiislyNm4fQAbU5dgcCAxoQYDAM2Hx5tpwIxJieQbxXvDhkjAC8g2SALrgyExVSYIA). You have to tell `getParent` that you want to ascend through the component boundary in order to land in the surrounding context.

**Comment by evs-chris** [comment]
You can also read the mapping with `readLink`, adjust the keypath, and use `this.parent.set` as seen [here](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutTAngAIAvIOLlqdBAA8yXJAApgAHXbKyc1gBsicyIIDkAHgBGAVw0cAfMGDsiTBBgxGA9OcvsrBrKvUcYeQQYfQAzM3YJDgUAShU1MnVXV0EkBkFcZgQyMAp2FEEidiQM7MEchEEAAwBrBH4qwTzysErGbhkyQTM2dkFA4uC-RLJknIpeXGyFA1o6-h8Wido0Mhn7RwMYmIBuYaTXcd5VgGEOOVkZjzIOLZXsgAUiAbWyGDMEGNoptdn5xaO91+GwQW12+zI7VwXRYujAIjEpEoNG+LC0FDIAGl6rCcgpAYEiEgADJ5GrrBygr7zXFgcEJdS02hsFixPYMshMlhmXBgGb-XaCZIZADuRBYghBglCDBggnmEMBsJe32m4mRdAAVgw8tj+LxxWj+Ap1ZIsIJaTFzYDVhTNtt2eoMKoMPTOCLERIaEphggtPoDCYGEgFubhpo0boEPoqhCjGYtFYIepbABiBCkeFyaG4ZzJshGdFJjnqdSmKzzfS2Ob1ZxuExWIwCSWU4TKEDVkF5kBC4ulkZuIv52yuDMkMB5jluBN9shVXwJJC6IhVxUIHP6ADaw5BAZlDAM2EEO8pAZMz0PYZLZDsp8M54AXoeIQBdYbO9iu1SYIA). Again... very tight coupling.

**Comment by ceremcem** [comment]
[This](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutTAngAIAvIOLlqdBAA8yXJAApgAHXbKyc1gBsicyIIDkAHgBGAVw0cAfMGDsiTBBgxGA9OcvsrBrKvUcYeQQYfQAzM3YJDgUAShU1MnVXV0EkBkFcZgQyMAp2FEEidiQM7MEchEEAAwBrBH4qwTzysErGbhkyQTM2dkFA4uC-RLJknIpeXGyFA1o6-h8Wido0Mhn7RwMYmIBuYfVx3lWAYQ45WRmAKi2V7IAFIgG1shgzBBjaKbXZ+cXD2++GwQW12wwwqgwoPYnAA7mJSJQaEphggtPoDCYGEgFlhBMNNCwdHpqvsyEYzForKT1LYAMQIUhgcoIXA8ZzUslaChUhLqPlkkxWeb6WxzerONyCowCQRA4TKECioHskCCVw8-nqNxcjUjGnAVwMkhgdm8smuCm6qq+BJIXREEWkuSs3D6ADaHLsDgQ6NCDAYBmweLNNKB6JMj0DuM9YcMEYAXoHSQBdMEQmKqTBAA) seems not tightly coupled, is working (replaced `getContext('button')` with `getContext('*')`) and does what I wanted. 

How can we [use that ctx later](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutTAngAIAvIOLlqdBAA8yXJAApgAHXbKyc1gBsicyIIDkAHiTUAfEYBGAVw0czwYOyJMEGDEYD0Nu+wufTKjMDLFV1Dhh5BBh9ADNrdgkOBQBKFTUydXJpEUEyMApeNDIAYQ45WQUDACoDFNpigAUiSO4FMhhrBBSAbjDMjQLeXAQyKpYWrlKyaRDBbN6wtQz1fMKAEly13D6VzL3PTzyhwQB3BhgAa1xIfvVD7fXaWIpIqtxmUYL2FDnHhtG40m3BKMzqWGOGwBYwMzlcdUWy3U9yOPjOCEEnGQeQYgmsI2OGOygh0chidx4owAKhRXAxbAp4olKMk0hTVkMni83gYPq41j8-pzoUDWtNZikIf9ilU4QgEbtkWRsIIAEwABhS-Ww-Q40ApfK+FB+CmyELlbL2WQ4Hy0dC0DBQCmUIGytEitpo+hdELdHoYWhoqURSqyM1oIxhtEuCH4cwtioGyL2GG1oQySF0RDiCSS7FS6SVkTI1hg7EEhaTZAmYtB0n07GsWi0FNTGTbGERnFOYlIlCDlYQWn0BksDCQcYh-U0LFJCH0AAMKUYm2Z2WRHABiBCkMB5BC4HjuddGLQUNdWgZWMwx-j6RzR2PuLyWCwCTEuBDCF0PuXHkCCJ4F6hmQXhnsBVaOJ4O4kGAx57F4q79Au6bqJmZDZhWFJyIeNyCAA2uuTifiOsQMAwBgqkRcojpYLSUVOl7Ea4tFEAAXpRFIALraqonaqJgQA)?
