### ISSUE TITLE
Update missing plugin help links

### ISSUE THREAD

**Issue by ghost** [ractivejs/ractive#3117]
## Description:

> Ractive.js: Missing "fade" transition plugin. You may need to download a plugin via http://**docs.ractivejs.org**/latest/plugins#transitions

Just putting this out there before I forget about these (because I rarely use plugins in most cases). At least the redirect from the old domain is still there, so at least you're not led to nowhere.

The plan after the monorepo PR is to [document all Official Plugins™ in the docs site](https://github.com/ractivejs/ractivejs.github.io/issues/120).

## Versions affected:

0.9+

## Reproduction:

Use `fade` plugin without loading it.

**Comment by evs-chris** [comment]
I found three instance of docs.ractivejs.org and replaced them with the appropriate links to ractive.js.org.
