### ISSUE TITLE
Triple Mustache between text nodes is rendered out of order

### ISSUE THREAD

**Issue by rockerest** [ractivejs/ractive#3119]
## Description:
When a triple mustache is
 - after a normal text node
 - which are both together in a disabled section
 - which is followed by another text node

...toggling the section to be active causes the triple mustache to be rendered before its preceding text node, which is never correct based on the template source.

## Versions affected:

0.9.6, 1.0.0-build-9, 1.0.0-build-85

## Platforms affected:

Windows 10: Firefox 57.0b10, Chrome 61.0

## Reproduction:

https://codepen.io/rockerest/pen/PJrVbx

**Comment by rockerest** [comment]
Awesome turnaround, Chris. :tada:

**Comment by evs-chris** [comment]
There was an issue with rendering a triple after initial render related to finding the correct anchor for insertion. This is now fixed on edge and will go out with 0.9.7. Thanks for the report!

**Comment by rockerest** [comment]
Thank *you* for the super quick fix. I saw that it was closed and thought I had submitted a duplicate or something. Great responsiveness there. Super impressed :)
