### ISSUE TITLE
Nested {{yield}} components rendering outside of parent

### ISSUE THREAD

**Issue by avoto** [ractivejs/ractive#3121]
## Description:
Below is a link to the playground showing the issue. The demonstration consist of a nested yielding component with a {{#if}}...{{/if}} around the inner tag. Changing the condition (checkbox value) results in the nested component to be rendered outside of its parent after the first false value. I checked with earlier versions and seems that this problem doesn't exist in 0.9.4

A workaround for me is to add a `<span> ... </span>` around the IF block.

## Versions affected:
0.9.6, 0.9.7
## Reproduction:
https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAWyQEsA7APhIHoKbaQCN4A3AAgF5vqaAO7cASkgDGKSpzQAKYAB1qi9AkiKQzFW2WqJAezIAHA4OooMkbkpUpVATwQATa+Kky0AOjQAPdNTOCnr2oegmyOjWAAYkzjLcEsgYGLyazmhkBpq0wMAOlGguODiM8Zy00SGqOACUIfgh4caRaDHVKCTIAEZFtB2qAMIIlBIA1jbAEmBo42jO3AD83ADkZGgrkCtIAOZU1Csl3CQ0xgCuKNwoDsZoaSDTs2PdBr6a3JxICGd3migwP3ejzmznueWBY3mJRyHUYPT6sKczn6dlU3HR3AMFzQMA6GMmAGJKAAzRIzEHQ1GXfEYkhIlGqNE05mCLDzPHM44Mekc9F5BgkymMzrclwMlDRPAhZyoJDWYlnageMxyWo2DowNAoM4wajqqn6cmQ1xXAFoDo4BrKOpsB7wLwZLL61QvGAZGDWACMxl83AwBhGCx2mrQ1AA3Mp0cYkM54tQdtYAEwABh9Eb13HiGBaSAc1hoI0EAFpuggDON0zhcEA

**Comment by evs-chris** [comment]
Yep, there was a bug in finding an anchor node for yielders. This is now fixed in edge and will go out with 0.9.8 when it's cut. Thanks for the report!

**Comment by anatolipr** [comment]
Wow this fix was so quick and really appreciated!

Do you have a rough estimate on when is 0.9.8 coming out? I am asking because I might just revert back to 0.9.4 until then or wait if it would take long. No rush on my end, things are working fine with the workaround for now.

Thanks :)

**Comment by ghost** [comment]
Commits to dev get published to npm with versions suffixed by `-build-XXX`. I think this fix was published with version `1.0.0-build-89`. They also get tagged as `edge`. You can use either to get this commit without waiting for an official stable release (in this case, 0.9.8).

See `npm info ractive` for all available releases. 😁

**Comment by evs-chris** [comment]
> Do you have a rough estimate on when is 0.9.8 coming out?

About 3 minutes ago 😄

**Comment by avoto** [comment]
I must admit that the rate Ractive is growing and the speed with which issues are being dealt with are both quite impressive! So glad it is my long term choice UI technology. Keep up the great work 💯
