### ISSUE TITLE
Filtering a list of two-way bound checkboxes causes unexpected behavior

### ISSUE THREAD

**Issue by STLMikey** [ractivejs/ractive#3124]
## Description:
If you have a list of checkboxes with one or many selected, then change the visible set of the list, the selections to not persist as expected and do not match the output of ractive.get for the bound keypath.  Seems to match on array index vs value or something like that.
 
Trivial Example - If I have a list of 100 checkboxes representing the numbers 1-100, then select "1",  "3", and "4"....then filter/set my list of 100 checkboxes down to only show me multiples of 10...the html will show "10", "30", and "40" as selected, but ractive.get on the bound keypath will still return [1,3,4]

There's a very real possibility I am not binding things properly, but thus far I've been stumped on this one.

## Versions affected:
edge, ^0.9.0
## Platforms affected:
Chrome/Firefox OSX (probably all)
## Reproduction:
https://jsfiddle.net/stlmikey/wxc00vup/5/

**Comment by evs-chris** [comment]
You're binding things correctly, but the way the list is getting updated creates a race condition with the binding, which loses the race in this case. The default behavior for updating an array when using `set` is to simply reuse any existing DOM associated with the list regardless of the previous and add any needed new elements or throw away any leftovers at the end. The checkbox name binding should _probably_ handle this scenario a little more gracefully, but you can avoid it entirely by telling ractive not to reuse DOM for different elements with `@.set('possibleElements', [...], { shuffle: true })`. Shuffling behaves as if you performed individual `splice` operations for each change in the array. https://jsfiddle.net/wxc00vup/6/

**Comment by STLMikey** [comment]
This works like a charm! I had never noticed the shuffle option before. Thank you!

**Comment by ghost** [comment]
I'll just drop this here for future reference https://ractive.js.org/api/#ractiveset
