### ISSUE TITLE
Missing end tag (</script>)

### ISSUE THREAD

**Issue by srinivas-mallisetty** [ractivejs/ractive#3125]
## Description:
Team, 
Today, we upgraded ractive version from  v0.7.3 to v0.9.8.

After upgradation, we are seeing the **Missing end tag (</script>)** issue. Upon digging a while for the root cause, we identified that script tags inside ractive script are not able to parse.

`<script id="sidenavTemplate" type="text/ractive">`
              `                   <script type="text/javascript">`
                          `  // some code goes here`
              `  </script>`
`</script>`

Can we get the fix for this and also if there are any upgradation checklist?

## Versions affected:
 v0.9.8
## Platforms affected:
ALL

**Comment by evs-chris** [comment]
I'm not sure about the nested script tags, but there are migration notes on the [docs site]( https://ractive.js.org/support/#migrating-from-previous-versions).

**Comment by MartinKolarik** [comment]
The problem here is that HTML specs says that a `<script>` element is terminated by the first `</script>`  that follows it, so browsers parse the above code (which is, therefore, invalid) as:

```html
<script id="sidenavTemplate" type="text/ractive">
<script type="text/javascript">
// some code goes here
</script>
```

followed by an orphaned `</script>`, which is either ignored, or turned to an empty `<script></script>`

**Comment by ghost** [comment]
This question comes up every once in a while, where a template contains embedded scripts (usually containing server-rendered values) and the hope is that when an instance using that template renders, that script executes or loads the external resource.

- If that script is external, it's recommended that you load it separately (as a global) or have a module management system (i.e. SystemJS, RequireJS, etc.) load it as a dependency of your component/instance.
- If it's an embedded script that runs on render, put that script in the instance's /component's `onrender` or `oncomplete` lifecycle initialization options to run the script.
- If it contains embedded values from the server, you can stick the data into namespaced globals or hidden inputs, which you can pick up later when you initialize an instance..

**Comment by evs-chris** [comment]
This is now handled in edge and will go out with 0.9.9 when it is cut, but note that this is a pretty dangerous thing to do. The template can't contain any content beyond the end of the `script` tag, including any other closing tags, so the `script` element has to be the last child at the root of its containing `script`. Any updates to the content after the initial render will also result in a re-eval of the script, which can cause all manner of strange behavior and leakage.
