### ISSUE TITLE
Few questions about onconstruct

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#3136]
Hello!

## Description:

```
var Component = Ractive.extend({
     onconstruct: (options) => {
    	console.log('onconstruct', options, this); // onconstruct > Vu > Window
    }
});
var comp = new Component();
```
Seems, that onconstruct doesn't assept instance's initialization options as argument, but in docs we have a desription:

> onconstruct
Accepts the instance's initialization options as argument.

Is it some issue or docs just out-of-date?

And also, it's very strange when I use arrow function I've the wrong object in this - I expect "this" === "Ractive instance", but in this case, it's not. Maybe, we need to bind right object to lifecycle event functions?

## Versions affected:
Edge
## Platforms affected:
Mac
## Reproduction:
100%

**Comment by evs-chris** [comment]
There is an issue with the docs as of 0.9, and that is that all instance events get a context object as their first arg. The options should be the second arg passed in. The general event docs got updated, but it looks like we missed the special init option events.

For arrow functions, they're already bound lexically before ractive gets a chance to bind to the instance. If you use a regular function, the correct binding will be used.

[Here's an example of both](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3iDgM7wDGA9gHZG4AEpAtgA60C8tASgIam4CWANwQA6BAA9cCSkgAUwADqV5uKpFoKluZRWq4YAV14zeYrLXJNcRAJTrFyh7h1FyAGxGvyKGbjB8iwgD6KPp8SGYAUgDKAPIAcsI0MHyUKHwAZgCeMhZW1tb2WrgYhSWUGAVKlJQIAO70zHK0YAiunmoA5LXkMK5IHbQVmEA)

**Comment by PaulMaly** [comment]
> For arrow functions, they're already bound lexically before ractive gets a chance to bind to the instance. If you use a regular function, the correct binding will be used.

Oh, it's very sad, but I got it. Maybe you need to warn about it in Ractive's docs?
