### ISSUE TITLE
Children of computed properties should be unwrapped by `ractive.get()`

### ISSUE THREAD

**Issue by m-r-r** [ractivejs/ractive#3137]
Hello,

I've found another breaking change between Ractive 0.7 and the latest version.
I forked the repository and I corrected it. I plan to submit a pull request ASAP.

## Description:

With the latest version of Ractive, calling `ractive.get()` on a child of a computed property returns the wrapped value if the property is using an adaptor.

The method `ractive.get()` in Ractive 0.7 used to return the unwrapped value, even when it was called on computed properties.

Additionally, I noticed that the `unwrap` option (added in Ractive 0.9) is ignored when the method `get()` is called on computed properties.

## Versions affected:

All versions from 0.8 to 1.X.

## Reproduction:

Here is a unit test to reproduce the problem ([Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSANCAzlA2uAC6EAO2kA9BQMZIB2AVtgHTUA2A9gK5IBmbAQxgJWHALYUBDAQA8KbAJYAjbBQCOXOgsIUATMwAszAIzrN25mIV1mTEAF0AvlkLwABG4A8iugGs3wmwAvAA6OIQAnmwI2GAICIRhbmDCvKFEpORUtIws7Nx8gsKiElKy8sqqGlo6+kam1RbU2NhJFAB8IXQenkgKAG5uCkjpjYkg7Z4Uff2d3V4zQyNhYwC0vAoyhFzCYZPTA+2YOPAAigCqNcyEMYQAFAAG1GAKbEjC3Ry8btTiJFyEASEBQcbqxbhvNxKBBuTQAdxgAhIJGQbjhcW6wm2MDoqKUETcACUBNRgf0RGh7gBKB4YNx3QhUtxBdpuYBdEKEX50bCENwbLY7GFBNxIDjULhiBB0QjMSkAUWiUplACEIgBJJB3ADkawF2IQ2qpAG4OVzQby3P0BGwuMK3Nq4mxONrTXQzdzLQBBJBIwgcGDMtlmzkbNg3QN3K1uJnAAIJHbdQZBFNWm1241uZwhwgIpH0gIkskIOmDWM5zlYxPB92JOucyn02Px7FJtwAagdbgEvpINyQrqzGArdZuQjFcO6d2bjhHjjdnM5s9r845tc9fMDItxcKJRYGCDu7NrnJ7fsgbjwbh9foDbnsw5PNzYF-1Qsfi+ICDEJEENwv2rAMA2DUDaQiOM4bLAAAxAgJJgG4ii8hBQHMChwAUHBzwQdqH51r8P4AsgF7Hp+nIgWBMDTmyLbVtatoIJm2ZPpySHUjRVY4pe9F2vYTF4UuZqOCaa6crKvIwAopLyhoNp3DAcoJDqFFFEapbpiWDqEHEPx-ACQIgmCYAQkgUIwvCiLIniBJIAgvACFw4ZGguxDMBJUmEDJXByQplI6mxzAAAxqWmDF0tq2kwgR-yAsCoI-C8bwfG44KOaZ0KwnQeZWelNl2Q5TkibW4mEJJ0myWwUZvsU1i4jAAASAAqACyAAy4VOpw3a9v2dKdRw3V+sguFaTp3CkACKXGWlsLYDCkVopZKKmTxhpFcJC50BcVzchsKDMA5-q8kIfIiqVGYgI4QA)) :
```js
QUnit.test(`children of computation should be unwrapped when returned by Ractive.get()`, (t) => {
	const fixture = document.getElementById('qunit-fixture');
	const value = 'hello';

	const Adaptor = {
		filter ( v ) { return v === value; },
		wrap ( ractive, v ) {
			return {
				get () { return v + ' adapted'; },
				teardown () { }
			};
		}
	};

	const r = new Ractive({
		adapt: [ Adaptor ],
		el: fixture,
		template: '{{scalar}}, {{#each list}}{{.}}{{/each}}',
		computed: {
			scalar() { return value; },
			list() { return [value]; },
		}
	});

	t.strictEqual(r.get('scalar'), value, 'the computation should be unwrapped by default');
	t.strictEqual(r.get('list.0'), value, 'the computation children should be unwrapped by default');
	t.strictEqual( fixture.innerHTML, 'hello adapted, hello adapted', 'the output should use the wrapped value');
});
```

**Comment by ceremcem** [comment]
This is the greatest bug report I've seen ever. Reproduction + Unit test at the same time...
