### ISSUE TITLE
Can I update "adapt" option after Ractive's instance already created?

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#3147]
Question is:
```
var ractive = new Ractive();
ractive.adapt.push(MyAdaptor);

```
Or we can apply adaptors only via initialization options? Thanks!

**Comment by ghost** [comment]
I haven't seen this in practice, but a quick look in the code, it appears that you can push an adaptor into `adaptors`. The next time you use `set`, the value is adapted. In some cases, it happens lazily, on `get` (computeds?).

https://github.com/ractivejs/ractive/blob/dev/src/model/Model.js#L70

**Comment by PaulMaly** [comment]
Thanks for the answer!

But "adaptors" option is an object, not an array? Seems, adaptors in this code is some another adaptors. Maybe viewmodel adaptors.

**Comment by ghost** [comment]
Yeah. I might need to look into this later (and clarify the difference between `adapt` and `adaptors` in the docs).

**Comment by PaulMaly** [comment]
As I know, "adaptors" - adaptors definition. "adapt" - adaptors applying to the instance.

**Comment by evs-chris** [comment]
You'd have to push to `ractive.viewmodel.adaptors` to get the new adaptor to be applied. It also looks like triggering an `update` won't cause the adaptor to be reconsidered, so it would only work for new keypaths or actual value changes. I feel like the `adaptors` array in the viewmodel should be the same one as `instance.adapt`.

**Comment by PaulMaly** [comment]
> You'd have to push to ractive.viewmodel.adaptors to get the new adaptor to be applied.

Ok, thanks, seems it work.

> It also looks like triggering an update won't cause the adaptor to be reconsidered, so it would only work for new keypaths or actual value changes.

I think it's not a problem.

> I feel like the adaptors array in the viewmodel should be the same one as instance.adapt.

That would be very cool! 

I use in my projects own-written module "ractive-app" which patches Ractive with a few very-very helpful features. One of this feature helps safely extend Ractive's instance and even Ractive constructor's static things, like this:
```
ractive.assign({
        adapt: [ 
                  require('./adaptors/promise') 
        ],
	someMethod: () => {}
});
```
And yesterday I noticed that I didn't test the adapters assignment properly and it does not work ))))

Thanks, now I know how to fix it!
