### ISSUE TITLE
Wildcard computeds don't match with correct keypaths

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3150]
## Description:

[Here](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5QdgVwDbIDQgM5QNrgC74AOmkA9GQMYAm8AdAFabUCmyAlgG4x3wv5l4RALZkAAi06YAtJTAx2mMjACGlfFxZiAjHQAM+6QHd2yarID2woonwtpevduVqNnFo2wBdAL4ZskCB8RgAEAEqumgAUwAA68LF2yJAhAOQARhbUAJ6paPGJdtbIKnYpAAYF+InAwADERCowGirIIZkAHgAKMBZELM3sLJg+PlWJADwoAHzj1fi1dSxqYO0WHcOjc5Mc0ybU+GAptXRGo2ghYCzsAOZg+MfAdGDnIU3Lj3TvKq8A1izZRqHR5if6A0ovHwhCZkXbbBb1dgAMxCdHSWwS80SNWA006PT6Aw0w1R6TemDWGxGY0x2IRZGRGLpOLIyzkTPmMJmc1qZEag1aHOxtIRePWBP6g02NMS5XymOopRUxzmnWGKRw8OARhS2guRxCACYLulIJqRcyFjqQgBmfUpAAsfnhdO1KQArPaQgA2E0al1Y+ZukIAdntAA4ZYHLb4A755ZbgwBOL3aPRRuleKrOzGUKw2OzUFUi1IAKi+MGWqWLlpu-BSSMQ8HU7As8CilEQMBgAEo4hb5hQQgAJCyhagWEJGFghOv4EKggFA1ZXSsAfhCAcr+C78BCne7pxCpf3XZ4YAA3PCc5bMPWQo3mxo21FOK0LmDl32A0PR+PJ9Os78CE5TqB05QhBYMALp+EKXAMLAbgGebwJgFjIB4yAWDcUSpE0NyIMILDwPgpB5G8MAEURJGYD2V4Dhm+BRjSPg9iAPhAA), I expect the `{{.area}}` properties fetched from computed property only for the first level of indentation and others set to `''`, like so: 

```
width: 1, height: 2, area: 2, keypath: boxes.0
    width: 3, height: 4, area: , keypath: boxes.0.b.0
    width: 5, height: 6, area: , keypath: boxes.0.b.1
        width: 7, height: 8, area: , keypath: boxes.0.b.1.b.0
width: 9, height: 10, area: 90, keypath: boxes.1
```
## Versions affected:

https://github.com/ractivejs/ractive/pull/3141

## Reproduction:

(above)

**Comment by evs-chris** [comment]
There was indeed an escaping bug in the string used to make the matching regexp for computeds. It's now fixed in @evs-chris/ractive@1.0.0-wild-compute-003.

**Comment by ceremcem** [comment]
In @1.0.0-wild-compute-003, there is none of the `.area` properties calculated.

**Comment by evs-chris** [comment]
Ah, yes, there was a small bug in the original. The keypath should be [`boxes.*.area`](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5QdgVwDbIDQgM5QNrgC74AOmkA9GQMYAm8AdAFabUCmyAlgG4x3wv5l4RALZkAAi06YAtJTAx2mMjACGlfFxZiAjHQAM+6QHd2yarID2woonwtpevQGZlajZxaNsAXQC+GbEgQPiMAAgAlN00ACmAAHXg4u2RIUIByACMLagBPNLQEpLtrZBU7VIADQvwk4GAAYiIVGA0VZFCsgA8ABRgLIhYW9hZMX19qpIAeFAA+CZr8OvqWNTAOi06RsfmpjhmTanwwVLq6IzG0ULAWdgBzMHwT4DowC9Dmlae6D5U3gGsWDkmkcnmIAUCyq9fKFJmQ9jtFg12AAzUJ0DLbRILJK1YAzLq9fqDDQjNEZd6YdabUbjLE4xFkFGY+m4sgrOTMhaw2bzOpkJpDNqcnF0xH4jaEgZDLa0pIVApY6hlFQneZdEapHAI4BGVLaS7HUIAJkuGUgWtFLMWutCTgNqQALP4EfSdakAKz20IANlNmpd2IWbtCAHZ7QAOWWBq1+AN+BVW4MATi92j0Ufp3mqzqxlCsNjs1FVosyGxGdAAVN8YCs0sWrbd+KlkYh4Op2BZ4NFKIgYDAAJTxS0LCihAASFjC1AsoSMLFCjfwoTBgOBa2uNYA-KEAzX8L34KEe32zqEK0fezwwABuBE5q2YJuhFttjSd6KcNqXcFrwcB0cTlOM5zgu-ChBU6idBUoQWDAy4-pCVyDCw24Bnm8CYBYyCeMgFi3NEaTNLciDCCw8D4KQ+TvDAxGkeRmD9rew4ZvgUa0r4-YgL4QA).

**Comment by ceremcem** [comment]
Ahhah, thanks!
