### ISSUE TITLE
Decorators between {{#if true}}....{{/if}} don't get updated

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#3152]
## Description:

Adding a conditional decorator creates issues when the data passed to it gets updated.

Example:
- ```<div {{#if true}}as-myDecorator="counter"{{/if}}>``` - will **never** be updated on `counter` changes
- ```<div as-myDecorator="counter"``` - will always be updated as `counter` changes

(obviously you can put any `true` condition in the `{{#if ...}}` segment, for the same result)

## Versions affected:
0.8.x, 0.9.x

## Platforms affected:
Tested on Safari and Chrome

## Reproduction:

[JSFiddle](https://jsfiddle.net/cg78p82g/1/)

```javascript
const r = window.r = new Ractive({
  el: '#main',
  template: `
  <h1>Decorator between \{{#if true}}...\{{/if}}</h1>
  <p {{#if true}}as-myDecorator="counter" {{/if}}>
    Total number of increments: <strong>{{counter}}</strong>
    <br> Number of decorator "updates": <strong>{{decoratorCounter}}</strong>
    <br>
  </p>

  <p><strong>They should be equal.</strong></p>
  `,
  decorators: {
    myDecorator(node, content) {
      console.info('add decorator', content);
      this.add('decoratorCounter');

      return {
        teardown() {
          console.info('teardown decorator', content);
        }
      };
    }
  },
  data: {
    counter: 0,
    decoratorCounter: 0,
  },
  onrender() {
    // matches decoratorCounter at start
    this.add('counter');

    setInterval(() => {
      this.add('counter');
    }, 1000);
  }
});
```

Simply changing the template from:
`<p {{#if true}}as-myDecorator="counter" {{/if}}>`
to:
`<p as-myDecorator="counter">`
will show you [the expected behaviour](https://jsfiddle.net/cg78p82g/2/).

**Comment by ghost** [comment]
I'm curious if this was ever a thing. Conditional attributes was one thing, but conditional directives... 🤔 

If it was never that way, this could be a feature request. Otherwise, it's a bug. 😄

**Comment by evs-chris** [comment]
Twas a bug, which is now fixed in edge. Thanks for the report!
