### ISSUE TITLE
Can I somehow get computed name in handlers?

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#3156]
## Description:

Somethings like this:

```
{
   computed: {
      some: {
         get: function() {
              // need to get "some" name
         },
         set: function() {
              // need to get "some" name
         }
      }
   }
}

```

Thanks!

**Comment by ghost** [comment]
Not sure what you mean by "'some' name". If you need the word "some" as a string (the name of the computed prop), can't you just hardcode it? It's only ever going to be some's handler.

**Comment by PaulMaly** [comment]
> If you need the word "some" as a string (the name of the computed prop), can't you just hardcode it?

Because I'm writing universal "computed property" constructor for storages (local, session, in-memory), which can be used like this:

```
{
   computed: {
      modeOn: require('./computed/storage')('modeOn', false)
   }
}
```
So, I want to make improvement one of the features of this module, but I need to know exact computed property name.

**Comment by PaulMaly** [comment]
Seems, the answer to my original question is NO. Ok, it's not a problem, I've written my own function of simple search of current prop in computed props list. Thanks!

**Comment by evs-chris** [comment]
The answer is currently no, but there are some fairly large related changes in #3141. If you're a heavy computed user, we'd love some feedback on that pr or one of the related issues.

**Comment by ceremcem** [comment]
~@PaulMaly Would you explain a little bit about the "universal computed property"? How will the `./computed/storage` export be used? A playground link would be great.~ (My post is sent too late...)

**Comment by PaulMaly** [comment]
> The answer is currently no, but there are some fairly large related changes in #3141. If you're a heavy computed user, we'd love some feedback on that pr or one of the related issues.

@evs-chris, thanks, I'll review this issue soon as I can and maybe provide some additional ideas about it. Actually, I use computed props in many unusual ways, for example for lazy-loading data from the server, or, like in the case above to automatically sync storage state and UI state. 

Meanwhile, I see, instance compute() method will be very-very useful for me because I'm developing module called "Ractive-app", which patch Ractive with some additional, very useful features. One of these features - mixins, but right now I can't setup computed props in my mixins because viewmodel.compute() doesn't work properly. I really hope, that official method will be working great! Thanks!

@ceremcem, thanks for your interest. I've written some set of the pre-defined constructors of computed properties, like "storage computed". This one I usually use with client data things, like, for example, the user local settings, you can simply use it like this:

```
const storageComputed = require('./computed/storage');

const $$ = new Ractive({
   el: '#app',
   template: `
      <input value="{{ setting }}" />
   `,
   computed: {
      setting: storageComputed('setting', '', null, {store: 'local'})
   }
});
```

This code will use two-way bindings to directly save and retrieve "settings" data using localStorage. Module exports simple function with the following signature: 

`storageComputed(key, defaultVal, modifier, options);`

By default, it stores the data in-memory, but you can choose between local & session storages. Also, we able to use modifier callback to modify data before it will be saved or retrieved.

Btw, I try to find the way to somehow join Ractive's ecosystem with my modules but things like   [this one](https://github.com/rootscript/awesome-ractive) seem thrown. 
While Ractive's colleague e.g. Vue, have a very popular [ "awesome-lists"](https://github.com/vuejs/awesome-vue).

@evs-chris, how do you think, perhaps we could add something like **ractivejs/awesome-ractive** repo to curate awesome things related to Ractive. I think I could manage this repo if core maintainers don't have enough time.

**Comment by ghost** [comment]
> This code will use two-way bindings to directly save and retrieve "settings" data using localStorage. 

Hate to throw the wrench into what you're already building, but this functionality sounds like an adaptor's duty, not a computed property.

Computed properties are designed to derive data from existing data. Common example would be to get a full name value when you already have first name and last name in your data, without having to duplicate the data or write code to sync the fields whenever either changes.

Adaptors, on the other hand, translate data that Ractive can't consume to something Ractive can consume, and vice versa. This could be anything, like a third-party model, an observable, a promise, a socket connection. Anything you can turn into a POJO and back is a candidate for an adaptor. The docs [list down a fair variety of adaptor backends](https://ractive.js.org/integrations/#adaptors).

In this case, you'd have a localStorage adaptor and an object (or anything) for the adaptor to latch on to. Here's mock code to show you what I mean. It's untested, and written off the top of my head, but you get the idea.

```js
// Dummy object for the adaptor to latch on to
function LocalStorageValue(key){
  this.key = key
}

// Adaptor that translates changes on Ractive to the localStorage and vice versa
const LocalStorageValueAdaptor= {
  filter(object){
    return object instanceof LocalStorageValue
  },
  wrap(instance, object, keypath, prefix){
    const handler = function(e) {
      if(e.key !== object.key) return
      instance.set(object.key, e.newValue)
    }

    // listen to localStorage events
    window.addEventListener('storage', handler)

    return {
      get(){
        return localStorage.get(object.key)
      },
      set(key, value){
        // Return if nested values not supported
        // Do something if you actually store JSON (i.e. get, parse, update, stringify, set)
      },
      reset(value){
        // tear down this wrapper and set one up on new value
        if(value instanceof LocalStorageValue) return false

        // Otherwise, just update
        localStorage.set(object.key, value)
      },
      teardown(){
        window.removeEventListener('storage', handler)
      }
    }
  }
}

Ractive({
  adaptors: {
    LocalStorageValueAdaptor
  },
  data: {
    setting: new LocalStorageValue('setting')
  },
  template: `
    {{ setting }}
    <input type="text" value="{{ setting }}">
  `
})
```

> I try to find the way to somehow join Ractive's ecosystem with my modules but things like this one seem thrown.

The docs site rewrite was the initial effort to get everything related to Ractive into one place. That way, there's one canonical reference and you look no further. There is actually an [integrations](https://ractive.js.org/integrations/) page that documents known plugins and tools, which is sort of like the page you just linked. If you have things you like to add, just send a PR to the [docs repo](https://github.com/ractivejs/ractivejs.github.io).

As for a plugin ecosystem, that's something [I've been working on](https://github.com/ractivejs/ractive/pull/3052) for a while now, a monorepo of sorts to manage all "official" integrations in one place. It's getting there, slow and steady.

**Comment by ghost** [comment]
<s>I never knew that repo existed. But then again, having one place to look for everything is ideal. If we can get permission to get most of the content from https://github.com/rootscript/awesome-ractive over to the docs, that would be great.</s> The thing is public domain. Copy away! 😁

**Comment by PaulMaly** [comment]
@fskreuz 

> Computed properties are designed to derive data from existing data. Common example would be to get a full name value when you already have first name and last name in your data, without having to duplicate the data or write code to sync the fields whenever either changes.

Yep, that's why I said "unusual ways". I use Ractive in my work from 2013 and during this time I had many different cases. I learned that computed props can much more than just concatenate 2 strings ))) So, I use it also an as declarative way to trigger the function, it's very useful approach in spite of the fact that it wasn't meant in design. For example, this code works like a charm:

```
const axios = require('axios');
const App = require('ractive-app')();

const storageComputed = require('./computed/storage');

function fetchPosts(key, val) {
    if ( ! val) {
      val = axios.get('https://jsonplaceholder.typicode.com/posts').then(res => res.data);  
      this.wait(val);
    }
    return val;
}

const $$ = new App({
  	el: '#app',
  	template: `
      {{#if cond }}
          <ul>
          {{#posts}}
			<li>{{ .title }}</li>
          {{/posts}}
          </ul>
      {{/if}}
	`,
    computed: {
      posts: storageComputed('posts', [], fetchPosts, {store: 'session', cache: true})
    }
});
```
This code load the list of posts in a lazy manner - if or when the condition is right, and cache it in session storage for this browser tab. Very declarative and look nice.

> Adaptors, on the other hand, translate data that Ractive can't consume to something Ractive can consume, and vice versa. This could be anything, like a third-party model, an observable, a promise, a socket connection. Anything you can turn into a POJO and back is a candidate for an adaptor. The docs list down a fair variety of adaptor backends.

Yes, but no ))) In my opinion, Adaptors are designed to wrap **3rd party** lib or class instance, which you can't modify directly, but in this case you can. Your LocalStorageValue just a function which can return anything you want and actually, you don't need to create Adaptor here. You can just return ready-to-use POJO object from this function. 

Anyway, it's not my case, because I don't want to wrap whole localStorage instance using the adaptor. I need to keep "setting" value is primitive, just a string or number, etc. Adaptors are a very great feature, I don't even know as it's possible to write a good code without them. For me, it's one of the key features of Ractive, but I still think it could be even more powerful. 

I use it, for example, with DataCollection lib (https://thestorefront.github.io/DataCollection.js/):

```
const $$ = new App({
  	el: '#app',
  	template: `
          <ul>
             {{#users}}
      	        <li>{{ . name }}</li>
              {{/users}}
           </ul>
	`,
    data: {
       users: []
    },
    adapt: [require('./adaptors/dataCollection')]
});

const usersCollection = axios.get('https://jsonplaceholder.typicode.com/users')
			.then(res => new DataCollection(res.data).defineIndex('id'));

$$.set('users', usersCollection);

$$.get('users') // -> usersCollection.values()
```
Also, in my router lib -  "ractive-page" - where I adapt Page.js.

> The docs site rewrite was the initial effort to get everything related to Ractive into one place. That way, there's one canonical reference and you look no further. There is actually an integrations page that documents known plugins and tools, which is sort of like the page you just linked. If you have things you like to add, just send a PR to the docs repo.

Yea, I know, but it also looks thrown. And also I think that special github repo is the more convenient place for that. "Awesome lists" approach looks nice and all other frameworks use it:

https://github.com/vuejs/awesome-vue
https://github.com/gdi2290/awesome-angular
https://github.com/enaqx/awesome-react
https://github.com/jondot/awesome-react-native
https://github.com/nmec/awesome-ember

I could make it a repo at my own git, but I think Vue's approach the most appropriate.

> As for a plugin ecosystem, that's something I've been working on for a while now, a monorepo of sorts to manage all "official" integrations in one place. It's getting there, slow and steady.

The key word is "official", but awesome-list includes more "community" things. I believe that it's necessary to increase Ractive's community. I believe that it's not fair that Ractive  is not so popular than the others.

> The thing is public domain. Copy away!

I think we can.
