### ISSUE TITLE
Child component lifecycle event not bubbling

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#3159]
Seems that custom events are bubbling, but lifecycle is not.

[Playground](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4AdAOzIGMB7UrAAgGEwBLBAEwaoFsAHGtUijoBeOgCUkFFMwBuaAHRoAHulJsAFMDLEU6XsnSQ6AAwA8AIwCuumnRoBaCgmYUA1sOIgnL12jaeAPgZnN1MAeisbUgDjMhwASgBubVJqWiEAEgyROlI0AHdxSWk5TW10BCMAcgBiJB4eKrxy6l5+QQwjLXIUHQoWdiMmVg5uPjzBcvxyvR4DNCMzfpG6cp0HZlJmFA8QAAEAcwQqcyQEeTO0GBR1OiqAeVI6AEktlCq6eM9VnvXSRxCvjYu0Ox1O50u11uDyewR8fg+XxA5QC4WW7BicSSZBABGwkBApjYsjozGBnnqPEC4WJMgCuCAA)

**Comment by evs-chris** [comment]
Event directives were being subscribed during render, which means that anything prior to render couldn't be listened to from the template. This was a regression that looks like it appeared around 0.8 and is now fixed in edge. Thanks!

**Comment by ceremcem** [comment]
Could we use `on-LIFECYCLE` attributes? I didn't even know about that =)

**Comment by PaulMaly** [comment]
@ceremcem yep, it's very useful in some cases.
