### ISSUE TITLE
What is "POJO" - mentioned in docs but not defined?

### ISSUE THREAD

**Issue by TotallyInformation** [ractivejs/ractive#3161]
## Description:
POJO is mentioned in the documentation but doesn't appear to be defined anywhere. Normally it refers to "Plain Old Java Object" which would appear to be rather a misnomer here!

## Versions affected:
All?

## Platforms affected:
All?

## Reproduction:
Searched the docs and the WIKI, no definition found for POJO.

I assume that the acronym is a hangover from earlier in the design of ractive. It would be helpful to those of us just starting with ractive if there were a definition somewhere - at least in the WIKI.

**Comment by ghost** [comment]
POJO - Plain Old _JavaScript_ Object, just like its Java counterpart 😁 It just means plain objects and arrays. This term is usually mentioned where "complex objects" are involved, like in adaptors, or to remind the user that in most cases, you only ever need plain objects and arrays.

**Comment by evs-chris** [comment]
It's pretty much what you guessed, but JavaScript rather than Java. Instance with a null or `Object` prototype would be a more formal definition.

**Comment by TotallyInformation** [comment]
OK, thanks. You might want to add that to the list of documentation updates :)

**Comment by TotallyInformation** [comment]
Liking ractive by the way but still trying to get my head around some things. I expect I'll fire some questions into the Google group now I've discovered it.

**Comment by PaulMaly** [comment]
@TotallyInformation Please, join our Gitter: https://gitter.im/ractivejs/ractive
