### ISSUE TITLE
Strange behavior when using a map value reference inside a {{#with}} section

### ISSUE THREAD

**Issue by avoto** [ractivejs/ractive#3163]
## Description:
When trying to access a value within a `{{#with}}` section using an object reference as the value and passing that to `@context.get()` as a parameter the `@context.get()` only computes on init and never again (following a change of the value mapping)

Please see the link to the playground for more details.

## Versions affected:
Latest, Edge
## Platforms affected:
Browser (All)
## Reproduction:

https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDwC2AhgJYB2AfAQPSmVUA6FBAzgMYxkAOuABGSQBeJngREeAGxK4EY-rgCePBKPEAPXLRgkOuMgDd5IZhSa4AwmBIU0-Igkj92CKQn2KVasXK0LDEikAVx8QYGA5NlwANSDQjAwxMwsIgGIEPTAHEh4eShREggB7PjJiin5AkLCIgAEAawQlROSIgDoi2lKDCqoI2kyOMFbzXDo2Nw9cFNwWefGAIxgaZaoABRhixfciSAX0gHcyXGzSPIKAbSjY+IQAXX4SNn4AM2Li0YsCNf4I98+GH4wmELjYPFs-A4MjYbHUPC2OwkbWAdQ4FT8uHaaFwAAoAOQA-EASkS-FxADligJDsUYA0CvwKlCbHYEMSJhDqAdgLRjqcvnMxj8ViKqAB1OkMuxPF4IDSqfTIfZjI4nbJ1bEIPH4875Owk64IaJxGqPZ5vD6ClxrABiH2c-ytQJBf1R6IomK1OqJpKSqt5-JG-osLAmXF4MxAODY8AoCEO-AASnoDMZccAFm5ILryBR8VgFnJJDI5Dm0sXpLIEAWFkhZCRnK9ghR9OUKLjiX8FhYYNrgjBKpmxqHcDdTaFnABGQsjua4PUFaA9+cWKeQABMAAZZ6PRxvIAAWLcriwh+cYADcC39GGJl+jIA48HaCO2u27Y3RUjpzj7SGvCgMEwIA

**Comment by evs-chris** [comment]
Reference expressions weren't completely participating in capture, which would cause the expression not to update when the reference expression changed without the underlying models changing. This is now fixed on edge. Thanks for the report!
