### ISSUE TITLE
0.9.10 – Memory leak found while using {{@.root}}

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3164]
## Description:
While using `@.root` reference inside template it seems that component Elements are not removed from memory when the component is torndown.

## Workaround
Set on `Ractive.defaults` a key with root instance and use it in template:
https://jsfiddle.net/sLb5acgm/

## Versions affected:
0.9.10

**The issue is not present on edge version.**

## Platforms affected:
Tested on Chrome.

## Reproduction:
https://jsfiddle.net/1j6webbd/

1. Wait 2 seconds
2. Perform a memory heap snapshot
3. Search "Detached"
4. Inspect "Detached DOM tree / 2 entries"

![heap-snapshot](https://user-images.githubusercontent.com/24919330/34037553-7f853d8c-e189-11e7-86e1-1e957501abf6.png)

```javascript
Ractive.components.MyComponent = Ractive.extend({
  template: `
    <h2>My component</h2>
    <p>{{@.root.get('rootFunction')()}}</p>	
  `,
});

const r = window.r = Ractive.defaults.app = new Ractive({
  template: `
  <h1>@.root memory Leak</h1>
  {{#if showComponent}}
    <MyComponent/>
  {{/if}}
  `,
  data: {
    who: 'World',
    showComponent: true,
    rootFunction() {
      return 'rootFunctionOutput';
    },
  },
});

r.render('#main');

setTimeout(() => {
  r.set({ showComponent: false });
}, 1500);
```

**Comment by evs-chris** [comment]
The special model to handle ractive instances that can be created for any given root model wasn't being properly torn down. This is now fixed on edge. Thanks for the report!
