### ISSUE TITLE
Instance method resetTemplate is missing from docs

### ISSUE THREAD

**Issue by TotallyInformation** [ractivejs/ractive#3166]
## Description:

Instance method resetTemplate is missing from docs. 

## Versions affected:

v0.9.10

## Platforms affected:

All.

## Reproduction:

The method is available to use and works as anticipated but is not listed in the API docs.

See also https://stackoverflow.com/questions/26666408/dynamically-updating-templates-in-ractive

I would issue a PR but I'm not convinced I've quite worked out how to use it properly. I am trying to write something that dynamically adds a button to the UI. The button can be one of a few types which have different templates and the template choice is based on a data variable. But I am getting an error on first load `Uncaught TypeError: this.el.insertBefore is not a function`.

**Comment by evs-chris** [comment]
Putting aside the missing docs for a moment, for your use-case, I'd say that a dynamic partial may be more appropriate than resetting the whole template:

```js
new Ractive({
  template: `<select value=thing.type>
    <option>unknown</option>
    <option>typeOne</option>
    <option>typeTwo</option>
  </select>
  <div>{{#thing}}{{>.type}}{{/}}</div>`,
  partials: {
    unknown: '',
    typeOne: 'this is the partial that gets used when .type === typeOne',
    typeTwo: 'this is the partial that gets used when .type === typeTwo'
  }
});
```

[playground example](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOngIYxq70B8BA9CaWyDgGd4AOwQB3cgCUGAY1xkEACmC0YtYbVy4mLSOQDkAYm3MEufVlXry5XAgC2ABwA2DO3oAGBAQmcI55ABGxMJIALSkDM4ArgjUuGAhKAB0uACejghsVsI2NgQA9o7yBcJs0cIA1sIFYsJcRSVlOXnkhcXEpWzpmQDyog0dXS157U3dGQgAKmIFg+MjXD5+ctlquW08bMDAxonCKBgYO2ypk0c7nEdcWx6W6zaOTPJRAnoqD3kV1bXCevoWEY2HoIfoIf4JYgCSjQhIIchPGAvZy2MBucgsaHRHxIchiMAIXJnTLkahk2yTMGAz7AyYzAoQxLQqGo+GI5Go9GY8jY5B4glEkGk8kg+n6EYYHIYACUAG5MEA)

If you try to use resetTemplate on an instance that hasn't been rendered yet, that's probably what is causing the exception. If you're using it on a component that is rendered, I'd say you've found a definitive case for #3146.

**Comment by TotallyInformation** [comment]
I think the correct answer to the error was to add `init: false` to the observer which killed off the initial trigger. From my many re-reads of the docs and tutorials, it would seem to be the correct method.

Thanks for the alternative approach, I will take a look at that ~~though my component doesn't include a wrapper and the templates are significantly different~~: 

```js
            btnTemplate: {
                'switch': `
                    <button type="button" aria-pressed="{{ btnPressed }}" 
                            on-click="btnClicked" 
                            class-toggle="btnPressed" class-btn-on="btnPressed" class-btn-off="!btnPressed" 
                            class="{{ class }}" style="{{ style }}"
                            title="{{ btnTitle() }}"
                        >  
                        {{ btnText() }} {{> content}}
                    </button>
                `,
                'button': `
                    <button type="button" on-click="btnClicked"
                            class="{{ class }}" style="{{ style }}"
                            title="{{ title }}"
                        >  
                        {{> content}}
                    </button>
                `,
            }
```

OK, I take that back! And you are absolutely right, thanks for the steer, that's a much better approach.
https://jsfiddle.net/TotallyInformation/021bsabo/
[Playground](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANoC6AvngZCAEpIDGKAlgG5oB0dA9gLYAOnAOzQCUGNgCEArihSCABAF45tBi3ZoAHugEATABTAAOjEMC55uej7J0kOQHJgwAHwAjFAIAqAT15pSpPY4xqYWcowYnDZoOnYAZkgIGGjBJmYWdBgY8ZICqoJ6OqhIAJRyRmlhYQD01XIAcuLxjAjoMBhyOoL2KHIA7pwwANb9jChgcgCSAKJyqHMICCHpVXIwaCiSMGYABsurq67SsgJs7gIAtPLlcq70QwDmMJy5OhdcCIN2ACTARShIPT2D6DMTdMpyAA+kIcTzQwnspAA3HJSPsDmEjjJBGcPFc4nEbnc6I9nq93lEvnJfv9AcDKe02JwCfYytCHOsdIiUWjKhiLFiToQkDBGEgLrx1lkYgpDCAEkk0HLiOV0fyqnEWm07E8kN4MHREmg9DTikDNa00DAAGqJMS67ysqEwgCsAAZSABSMpq9V+1yih5gDyYDAmv5m+wWtq2pJnQPBp3s91ekpI31+uQXPpoVxDMYXaNWnUwPUGo3h2nmrVW2P20uOtmuj3euQZzMd8wBxhBkNZSuRos2u3xnuJptyFPe9N89W80IHPaz1GpBfmTIYAAixTsFTXVVqckkyWU9CYrDYWG8CDQAGUNno2E+yrI5HQwEgBA8lcuwiD2ru9jdJA9hwgiOAOMycT2CBnKIquKwajWw5JIB3a9jBcgABwuhBoENphKYIWE5C+oIu7tl2Hi3n0YzvjEOR5EwBRcCImgoGUe6IRizAircHgAApSskOiKHIACElhgBEbDfigQLnEJoYxKyyyUVUrGRDebCfA8QJSNiZg0XRYAxHIegoL4aAKBgtEoO+JRBG+gjoFoJTqWE4wyck8n2Dokh8AAjE5rGuRxHkWF5Yg+UC-l8AATE5wD2AISDcGgmFRbJD4pWlGUlHhinCSpdhFcpOikO5v4HBF5hZTF9hldKXIQU1IlVfuJHEQc5wAMIIIwJIMXIcS5PkAh6KF7GcbVzkCFp7C6fpxzyEpzXmZZfgKIKgiORBU1ubN9U5XFvDBftLnTUd0nRSdAW8IlEHJal6WZTd2W+S9+WVeppHLn9+68CKTB2hR1XmPYtkmZhS6dQcAA8O1mJt1lykjcpzKK4qSuVsogE4-ECGtImomiICzRigjvANJJ4+cxn2aZOgYxTBx0MgWQXLIDwPDedOCcVzMgG+HMYBc5xXAI-NE4LGPs0gnMS1BePiW1MQs+DHby1keME9rHQBBjV583KBPG2gpNyqzqxMCgJv48AhOeGMN56GUhvC19uuO19lvk5rGLOOY1vlI75yeOxbuk6HQdTSIhsBxY8PVEjzjqTs3WrI1K0CDDs2IznlhWXTOcY1T7ODUM0v9ZX6v+3Dnb697IsKwbZNyObzfm37IeeS7qMO5Y-d+3IXumz7eU94nqxB2209VE4seXfH87cQjKc52nmsZ76AOIbSjHjVHXEYppvTJAghJKFF6nrJs2yqvPts3nY9hBLN+uv05h6JJ8fRyEDLI4wyRBhblkDuGwmBflmubL+EEf6LE4P-QBWAwAgImN3HyUCHizXDlZV+SN35pFmoeC4FwpKYAtoIBA3gjwk0YISPBfhFBKEhnZd89gszkNqLggW5V4h2hSLwrw7FD7MQmjNeeYQ75bDMBfOIH0FJ8Oak6AA-BAy+ijs6GQjloJkucyh2HkVopGuiUBMhZB1Neqw96ZnDv3MRjACiSIbvyGRD9jFySUTLcqaiNEKK8dok4zs7bsHBHIIxaBNGBNMf3Cx0ErGZlsf6HOZjAJQRgvYYmcgACyGU8LATlJMew3A5DEzrsk9UsTQnpJZCBAA8iyApucGm50qVUVeXVlg-WIWkM+R5GBHBaDoK04gPAABlOBIFEkoIQ-8VDnmNCfCwUTX4AGIkC8F4EQ-cmy-C6DsCgGAkghHLisLwaIdhYbWLkPDAyJwnbF3Hkw-w7cx4gCRgJYGYokhymcMABm745DMDFAA75dpSCh24N4MxARk73MEEHRGMAt6uLuYXF5eMoaMwxu8pGgKwB-OAAAMUYBoMyr5sVApRpCpw0LYWkHhZvW5AZUU3PRYZUeeUS6GU3GgBIkhWhEtJeS0Sr4RkCtaOZJGJRaXAHpexOF1QEUCCRay9S8NkCuCiWyzM8MdAsGcPeG8DAKG3ELijSAycDXMF1X6eGF80CmtcIwXQFxeIIBOdtDwPg-B2s7PDTgvBxFuBzsnINIaQ6BuDU41VVKwDhpjYi-O1RHUMH9VUZOWqdUatZcijNYR9WGtmpue6gVdzAAAAK804HcBAbAABSt56n1EvEc11DwGHeEKGW2VnT142oLUnQdJb7rxQrdWz4dbG3NtbVgUUX4u09oSn2jV1QR2ayLba0dfAADME6a3TqbS2ttC7O1xG7adXdq7N3ruLcuHey5yKP1cfYFVuIBA1yGqJd99N2FM04ZNS6bkX03L-IIBaOlOB6XsJMMwQN1giH6Kgd8HbnJ8EEMIXoFcSQdBCsB8KT93oNSvUlekbE9ECE4CMtgX0YIHXMVRmjX08IMdo3lTCbGvo9Ncf28w7SD6gYxAqrQr94a3h4BbMKEDeius6MUZwOybkvIITnb+dQkYQXjepU65byjtLCKdcd+nM5VCvbudpe9Kq4BANgKgmrXUjHWAgLFlkbwYFMhsDGaD+V42DCgXg2Rah0B0AIAAVmIdmLwdBxGQOsDgPBqhIDC0gDQ1QBquAwNUXgg0BCDWqAANjYAAFjYG6bLuXBpsG4K6jgWQ-mmC3eEHQeM9l-OtcWgQNm6DwFcNR2hjtuAik7QISAgU0ClN3RNyc02pvcB5KYUwOM5CnrQ47f8JZ4QCAW6cAQAVtUwBuBt+TwxBifm-Dts4nAohoE-EdhkpVPVoEu3txY93PgwDsEN78IgkCXaGGgAbzkPt2E5Dt0wbAEy9EdmFC4iQeyjbWGOFA4OuukCAA)

As for the original issue. I wonder if it wouldn't be best to discuss possible text here? I'm happy to do a PR but I wouldn't want to mess up the docs by getting it wrong.
