### ISSUE TITLE
computed-properties docs missing some info

### ISSUE THREAD

**Issue by mikemaccana** [ractivejs/ractive#3167]
https://ractive.js.org/v0.x/0.8/computed-properties lacks some info:

 - What version of ractive did computed properties syntax change ('previous versions of ractive'). I can't find any mention of the change to `computed` in https://ractive.js.org/v0.x/0.8/migrating

 - What is the syntax for using a computed property? Is using a `computed` property the same as `data`?

**Comment by evs-chris** [comment]
* I think the only thing that changed about computeds is that they got fully lazy. There're a few proposed changes, but none of them have landed yet.

* Computeds are used just like root data, so `{{foo}}` can be computed or plain old data. They can both be used in expressions and can both have child keypaths.

**Comment by ceremcem** [comment]
Here is an example: [Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4A7NAdwAIAlJAYxQEsA3NACmAB1iP0FIKA5ACMA9gBMAngLwUuPdAFsADsnT8ABnJQAeMACYAfAFkJ1NPSTEA5gjQUAgjDRJtAen0Gt2hsSUBXFAomJAQ-NABeDhBgYDIGMRQwHBwoihQJJQio4j8FITQYVNcDbWR8hAM4hLA3MrQKrx9-QODQrOjgMDQGKzAUZNT0zMiQHLyCopK6iq6evtqkcs9uHSaAoJCwkZikJyQBkDSM9rH8wpBi0sX6g13nBaWtViQMTPp+HdfzfpwASi11DItGJUEgPloeFVEvwAKx4CGJbq9FD8ACMAAYtPgtLQRMoAmgxOCVjw7mCKJwSSgeFY0CiKAAzPzEegMETEVi-Sk8HnUlBOFB+GDENJgBgYAB0tJQrAEULAAl+FAAVKLxVK6bLZsjFQieNiqTwMHT+EyWYx2axWly9XzXK4KMbAvKKJYxBRtX0KGQxbYKABrNBoJQ+KyiuwvN6BGCoNm2ngxi0UcJqyXS2XyxUUB2JdXpgSelCKgDc8ZQpDIAH1C8mKEZUGAJRgAI4wGWtbMURNs36lw18iuVl0pjsOweFvu83m5yVOrVIvrSCjjhcoXtlmdNzVy+KJJeD+Xr-spKkG3mR778AQAEliu6SndvhZwAixXD+uCAA)

**Comment by ghost** [comment]
Computed properties, afaik, didn't change since... ever. It's still an init property that accepts a function, string or object with `get` and `set` methods. 0.9 docs should be valid.

- https://ractive.js.org/api/#computed
- https://ractive.js.org/concepts/#computed-properties

**Comment by evs-chris** [comment]
That `previous version of ractive' seems to be a holdover from when computed properties were first introduced way back when (0.4-ish?). I'mma close this, but if you need more info, please feel free to reopen.
