### ISSUE TITLE
Support promises/async at a template level

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#3168]
I found this issue: https://github.com/ractivejs/ractive/issues/1961
Seems, @Rich-Harris already changed his mind about this: https://svelte.technology/guide#await-blocks

I already tried {{#await /}} in Svelte and it's very cool. Perhaps we could add exactly same expression to Ractive?

p/s I know about Promise adaptor, moreover I make more in this direction in my "ractive-app" module, but "native" support will be very-very awesome!

**Comment by ghost** [comment]
Consider this: I happen to work with the promise adaptor while refactoring things. The code is just over a dozen lines before processing:

```js
export default {
  filter: function (object) {
    return object != null && typeof object.then === 'function'
  },
  wrap: function (instance, object, keypath, prefix) {
    let removed = false
    const get = () => null
    const set = () => {}
    const reset = () => false
    const teardown = () => { removed = true }
    const setter = result => { removed ? void 0 : instance.set(keypath, result) }
    object.then(setter, setter)
    return { get, set, reset, teardown }
  }
}
```

Usage practically requires zero modification.

```js
const instance = Ractive({
  template: '<p>{{ value }}</p>',
  data: { value: promise },
  adapt: [ Adaptor ]
})
```

Now if this were to be implemented natively, this would touch several parts of the core code. This would require updating the parser to consume the new syntax, the above logic integrated in the model code, a battery of tests. And since it's a template syntax change, templates would need a version bump which would affect tools like rcu (which is already behind in terms of maintenance, currently working on that as well).

Also, consider the fact that Svelte generates optimal JS. It only creates code when you tell it to. On the other hand, Ractive is a runtime library - all of Ractive is loaded regardless if its used or not. With an adaptor, you can just opt not to add it. But if it's native, it will be there regardless of use.

Not saying it's not possible, I'm totally cool with the idea ([async components](https://ractive.js.org/api/#components) already uses a similar mechanism) and it's just a matter of scheduling and having the other tools keep up. But the gains over the cost is very minimal in my opinion.

**Comment by PaulMaly** [comment]
@fskreuz Thank you for the code snippet, but could you please read my p/s section? ;-)

> But if it's native, it will be there regardless of use.

I believe there is not project with Ractive without async operations. That's why I think it's a major feature.

**Comment by evs-chris** [comment]
[Here's a macro that implements awaiting.](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR5MAdmJIYAxjAoAHFHUYt0AWznJ0LGigCectM0JoAHin5gUqhLzFMUJJAHckFRQCMKosgFoAZgD2MEYAfvwYAapoAHRyMJEUGGi24twOGACuUlKYGDzoWF7s0SU0wMAAxGhIUmA00Tg45Q04JdFlwPzVtY0Cmdm5Iqn2JAbeRTwIAUiUosUlAmOz7EP2I2gw8TA8APJ1ogGYAIQCG1urDvzOrihDfTLytyAEGPBSAaJYNACCLm40DBoACUaihqDFVDV4gAKaFgPA0VAoGAYACUAJ4ZTsKDA0SQCAoSAwABkAlJ8dCAOQAfWp1zclNRAG5se9Poo-ACaLi1BpUDFOQAfQU0ADaAF0WakEFwaP0chgMAilkUEWcglK1tLZSgNFy-NE-F4yNC0BiaDEzQxrTRKfLcozNWDOdDdQh0W6uW7DTRhWLJRaEEkdHrARKnfbFVzRcAdJAaAAWBGieMAViTNBg8ZpdL+KGiVHxGTQlIRfnjnpwkux2M9gINRu8pvNloBNspKrmjuxnfYXr1AH4QwgfX6JTR4+Ga6k6zQG8bmwxMa3rYDKeqYN3Uhv+wgaEPvUKRePJ9Xhqk-BlRFIwR8aBk5GR+dCkSj0cAazjokkUAAVNDqJoaDQr2zKfp+FAuq+GCGkENAAGTwYiKDIjBgQwNEOJoKI77gSg0GwRhWGiNCtBLliwxpPYuI-lSAACUzkiOhYIMWpY0FQYGUWsX4-v+gHPpGaJOjx+A0NC6LkR+3FpDRXD8Xy6CmpsQRcTx9g4GpaQ4NiOnnvYD5Pkp0FadiMBcBkMCiBRPGGfyulSmJ0n2K+FDuBkBSTpS6GUuKYiaZq14fF8MBcqIaBOMCoLgtCzkoWwnAoNmFT4RwXClrWAGKWgyW8kBGWpHEmAbFQaAAOpgG4mByDUOU6DAxZ4D2bBgviGDxrG9JJT8eY0Pg2JGUgHWfhEUTDTJcQJEk8bhZFAAK8SqIkwHQgEADWZauO65pxepKB8RQUQBB5sKSZi63QmyEQytEUzsFSZAfCW6JjgAjAiABMCIAMziqiCKvQADMDpnaain56Rp-morgQA)

It's not _quite_ as built-in feeling as a new block-level constuct, but there's also no additional parser overhead required for the special inner-block interpolators (like `{{else}}`), which aren't exactly cheap to process. There are a few questions around how this sort of thing should behave either way (and the svelte docs seem to be mia now):

1. When the promise resolves, is the success block run with the value as context?
2. Should the error object come through somehow for the error block?
3. What should happen should the promise not be then-able?
4. Should the block allow changing the promise that it is based on or should it be a one-time thing?
5. Should it try to handle already-resolved promises by scheduling the pending setup with a `setTimeout`?

Note that it looks like this exposes a bug in macros, wherein the macro is not notified on subsequent attribute updates.

**Comment by PaulMaly** [comment]
@evs-chris I think Svelte has great implementation of this.

**Comment by evs-chris** [comment]
Looks like the svelte docs now have the await block section for me, so I got curious what the ractive implementation would look like. If you check out the `await` branch you'll see it ends up adding about 100 loc after consolidating some of the else/elseif code.

I also [adjusted the await macro](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoRtIQAeAEwEsA3AAgrIF4AdQpGAczRRYD4SB6SlR5MAdmJIYAxjAoAHFHUYt0AWznJ0LGigCectM0JoAHin5gUqhLzFMUJJAHckFRQCMKosgFoAZgD2MAwYAapoAHRyMGEUGGgi4twoCAFIlKLsEdl2ySQoYGiiNFRICDzoWF5Z2TTAwADEaEhSYCVlODj1EZ3ZEXXA-M2tnbn2JFKorTQJAPJtogGYAIQDaKNJAs6uKIkC0rIKiRIH8or0Rttu2noGRuhmFlY2IMco9Q1XiqHhUTGqcXWODGKTSGRqERB9QKRXaCE6lRQ1T6AyaLTapXhXWAPRwKPqQ3RG3s9nqkxQ0yB8xoixWa2J70GXw2+xkZx4IAIGHgUgCoiwNAAgi43DQGDQAEotJFUSKqFoxAAUirAeBoqBQMAwAEoxTw6rkwBEyhQkBgADIBSYIRUAcgA+vavrbtQBuXK8-mKPximhGtQaVCRH0AHxDNAA2gBdd1JBBcGgYACuUikmAwaoM3mqarQMBiMFj9njijQCCL3CSZd9fgifi8ZEVaD1MwizYYHZotphohdNDDNGV1fFtfr3ibLci7c7tvJrRduoAZIuZggaMvB2W6-3w9HtXWGxOGPqp2KZz2FxWKD6mwhdcAQdfNwgIqp1yut6oIvHMgUz+KAEZ3xoZZPwjAAGKM621EF7GTVN019CNgB0SAaAAgBONVRDQgBWAAWNUAC80OQmk0LAyCIlENUTDQlCYDQh0nRFFAIkxJM0FtGhOijNU-DQ29twHPcDwQdAYCPE82xAmc5zAPscBjEEy3iWCUHgtMMAwX0hNDXco33etxLzKTW2bZY5KmBS3VyHBV3iRMUy0nTxWjCtcizcEazEiSzNPSzxW7Qpe2AgKrIpGyPKrNcRwPcd22k6cgvkvsBz0ndI0M+LG0S8z-y7VLbKSJ9b3vR8b0-MKXy-H92D-DtAOA0CaogqC-BgpISQkgskJQlA0Mw7C8MImgSMjFCcNXV82uo2j6JoRiu0dL423zIJuN4-jBK3fSsqMigTMkvLwqCi9dSUjz0AQNSuuSPNevFDKROy4y-JOmTAq7c6K3s1TmweoIkOU8Qkj8JNRCkJE+RoJM5DIINFQ1LVyruo14hQAAVNB1E0NBFS86piu6irB2RjA6yBjdycpmAIh7VGSZQGnAjpntFVoY8DTu7r0a4O0AAFUmtdiyk4201SoYnkl5iIMex3HEc09Npe6-AZhbB8eeSPmUEF4WyjWgsJZmTqmfsXWFcDdAm3WmBVeSHAHeBJIXZJJI4YRm3ydVpIYC4JMYGKLXus9oM7NjdWQ+ZlBNQodwk0qUjbVZ20ozEJ2i0hvkBRgX1RDQJxJWlah8ej5mOC4JiGgrzgUAl3IAzx6um6DBukmiTA81lAB1MA3EwOQWjQNDNU4vBPLYJEygwBavjQ4Udh4ieki9pB6JBH4R+5pnolieI0ILouAAV-kBZUAgAa341w7019S4K4TGKHCAJE+VXUuavxVPVCeNvwCOwO0ZA+RcV1CJACaoABMaoADMhk1QAXAsgh29gnYgjdigF2TtcBAA) to act the same way as the await branch and threw the matching template that will work in the await branch below it for comparison. I'm on the fence as to which I like more... the await block stands out a bit more, but it's also not exactly a cheap implementation. The ergonomics on the macro are about the same, and it doesn't add any weight to core.

**Comment by PaulMaly** [comment]
Thanks! 🥇
