### ISSUE TITLE
Crash Getting Linked Ractive Computed

### ISSUE THREAD

**Issue by paulie4** [ractivejs/ractive#3169]
## Description:
Getting a computed from a Ractive instance called `Store1` crashes apparently trying to re-render what seems to be a completely unrelated Ractive instance called `View1` (although, `View1` _does_ have a link to `Store2`, which in turn has a link to `Store1`). See also [my original comment](https://github.com/ractivejs/ractive/pull/3141#issuecomment-354818878), where I thought this problem was only with dynamically created computeds, but it evidently also happens with regular computeds.

## Versions affected:
0.9.4+ (specifically any version that includes [this commit](https://github.com/ractivejs/ractive/commit/4266a32a69f78e61407c3db5d8ea910893007c25#diff-eb2b86b25094f19146a6286403895bf6R126))

## Reproduction:
You can put a conditional breakpoint on line 33 of runloop.js (or line 1897 of ractive.js) with a condition of "`!batch`" to break at where the exception is thrown.
[Playground example](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSANCAzlA2gLoC+WukIAxgPYB22ALgAQDK9VMCAjIwLyM0IA7owBKAQwr0AlgDcEACmAAdGkvrUAtgAcArvWSRGy1fTWbd+pAGsth42of009QwDMdNSVNryAlEcYOeh0YGkYAcnM9ZAA1MQAbcIBuRiIVRzSTTKJfJPTPWgYWNg4AJl5+IVEJaTlFdPokMXoxOwa1BnYEUptDcM6yxhkE8Ibs3JVWLtKAOnipGit5cPCMCKmOTlWjGBrZBEMNrhy81QK6JhipIW4+AWFxLzr7fXjDJCoKHQ0EGnoZ5wAUXiCB+fwAQgBPACSSGWW18GAatGoNFcUhQbg8Xh8-heanoYCk2DmCyWKzW4SOpW2wF2TwOxWmJzGSJM+m08WajIABsBgNS8P0St0bOFiEQeSoWWcjpwAQh6MsopYxblMCB6PAADxIWSMKRIHhKECcE0APm1AHo9TJzSAiEA)

**Comment by evs-chris** [comment]
This is one of those tricky weird things that's caused by a combination of links, laziness, support for observers, and support for reference expressions. There are certain scenarios wherein all of those things converge and can cause a view to try to update outside of the normal runloop. The solution was to make sure there's a loop currently turning with notifying from a computation. Thanks for the report!

**Comment by paulie4** [comment]
Thanks for the fix!
