### ISSUE TITLE
{{#with}} alias values not visible for non-isolated component unless explicitly bound

### ISSUE THREAD

**Issue by avoto** [ractivejs/ractive#3174]
## Description:
`{{#with something as somethingElse}}` value `somethingElse` is not visible inside a non isolated component methods such as computed and oninit. But works fine if bound through an attribute or when used in the component template.  See playground for full example.

## Versions affected:
0.9, latest, edge (maybe other)

## Platforms affected:
Browser

## Reproduction:
https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4A7NAdwAIAlJAYxQEsA3NACmAB1iOUUkYA5mhSQKAcgBGAewAmATzF4uPWlIC2ABymliKDNGUoV6jaJr1maAHRoAHumIz2hnj3Sbk6UQAMAagyQKAGETAFd0GVFgYFVNcLQZADkkNTQcHAAeCRgAPn9A9w1PNCjgYhS0zOyc7yVuIwaGDCliyIAzJAQMNDqKPv6+7QZiBhRWAEoKTmIB2f7VYmaEawQpAVYxZNSKJtExCgBqChQwJqshMbFy1LFx8YBuCgB6J4oNGGG9ClDHNDbhhJcOZ9fBA4GxDTxSJTMHA+ZhCJbNiTaZwuEwYShGAzDggXGHY6nDDnYQba5oW73WFonDUga0+o8HDjQyg+qFYo+FwNDJgAAsOQA6mA0DNiFIUABaaQ-SIZJ78nLcnjRADEZFGYHEAHE0FJBBSKEgMBRyellSgBhkIc8lYyGtEnhqTub7SrgK7XA0LbyBcLRRQZY5IPLFRa1c6tWIAArCNAwfbG00VT3elDWkzJ1IAXlx0TNtJAtvDwCdmtTXp91VYiQlJQo3TQFAWSybSbIaAQCCsFAAkpaMGApGQTSdUKaJRRtAg5M2EQkdiakG02mh6AuJOEpyd4xQ2j8LNoTZKKAgGABrJtDEaWsBIRzLGAs+q1FzEZm4IA

**Comment by evs-chris** [comment]
I've tracked down the issue, but it's a little chewier than I expected. Just wanted to note that I'm working on a fix.

**Comment by avoto** [comment]
Thanks a lot @evs-chris! I really appreciate your quick response and being able to look at this so soon. Having a fix is not an emergency on my end, currently I am binding things I need which works fine.

**Comment by evs-chris** [comment]
This is now fixed in edge and v0.10-dev. Aliases, indices, and keys weren't checking to see if an implicit mapping needed to be set up during resolution. Thanks for the report!

**Comment by avoto** [comment]
@evs-chris I don't see #3174 as part of the changelog for 0.9.12 https://github.com/ractivejs/ractive/blob/dev/CHANGELOG.md 
Also, testing using the above playground URL I am not seeing the fix included in 0.9.12. Is this fix planned to go out with another version?

Thanks :)

**Comment by evs-chris** [comment]
Oops... I didn't tag this issue, so I missed it when cherry-picking for 0.9.12. I've pushed out 0.9.13, and I didn't _see_ any other resolved issues that I missed. Hopefully this is the only one. Thanks!

**Comment by avoto** [comment]
Awesome! Thank you so much.
