### ISSUE TITLE
RFC: Plugins

### ISSUE THREAD

**Issue by PaulMaly** [ractivejs/ractive#3178]
Hi guys!

I want to suggest an additional method for the Ractive's core which is very useful in the modular approach. I won't hide it's just a tracing-paper of Vue's plugins you can find [here](https://vuejs.org/v2/guide/plugins.html).

## Use

In Vue this method is basically needed to extend Vue.prorotype conveniently and transparently with new properties and methods from 3rd party modules (called plugins). And also to control that the plugin will be applied only once. But I suggest making this method available also to instances of Ractive.

In my solution, plugin is just a function which called in context of caller with additional params:

```javascript
/**
 * This callback fired when all waitings resolved.
 * @callback pluginCallback
 * @param {...(*)} args - Bunch of arguments
 * @this (Ractive|instance)
 */

/**
 * Apply external function with args to Ractive's constructor or Ractive's instance
 *
 * @param {pluginCallback} plugin - Plugin function which will be exetuted in context of coller
 * @param {...(*)} args - Bunch of arguments
 */
function use(plugin, ...args) {};

Ractive.prototype.use = use;
Ractive.use = use;
```

```javascript
// ./plugins/myplugin.js

// plugins files itself doesn't need to import Ractive or something. it's just a function.
export default function (options) {
       this.newMethod = function() {
              console.log(options.some);
       };
}
```
```javascript
import Ractive from 'ractive';
import MyPlugin from './plugins/myplugin';

// assign new method(s) or prop(s) to Ractive constructor
Ractive.use(MyPlugin, {some: 'option 1'});

// next call of the same plugin will be ignored (do nothing)
Ractive.use(MyPlugin, {some: 'option 1'});

Ractive.newMethod(); // => 'option 1'

// the same behaviour is for instances
const app = new Ractive({});

app.use(MyPlugin, {some: 'option 2'});

app.newMethod(); // => 'option 2'
```

If this suggestion will be accepted, I can provide the pull request for these features. Actually, I already have that code as a separate module.

Expect your comments, thanks!

**Comment by ghost** [comment]
I'm not exactly sure what the goal of this request is. How different is it from Ractive's registry approach? The way I see it, the proposal is just extra indirection with setters and wrapper objects (which equates to more tutorial explaining and more things to document down the road). Ractive's approach is much simpler - all plugins are assignments to their respective registries. No setters, no wrapper objects, no inconsistent syntax. Just pop it in there, done.

Taking Vue's example and turning it into Ractive (assume limited Vue knowledge, probably not apples-to-apples) but still...

```js
// New "global function" attached to Ractive
Ractive.someStaticFunction = function() {
  // some logic
}

// New custom "directive" - decorators already do that
Ractive.decorators.myDecorator = function(){
  // bind, some logic
  return { teardown(){...} }
}

// Adding a method/property to the prototype (defaults is just an alias to prototype really)
Ractive.defaults.myMethod = function(methodOptions) {
  // some logic
}

// Looks like Vue just holds onto your mixin definition -  something you can just do yourself.
// And with ES modules, it essentially becomes a module which you can import.
const someMixin = { ... }

// Ractive polyfills Object.assign.
const instance = Ractive(Object.assign({/* options */}, someMixin)) 

// Object spread which some compilers already support.
const instance = Ractive({/* options */, ...someMixin})

// I think it makes no sense doing mixins per instance. Define a component instead with Ractive.extend().
// Setup once, instantiate multiple.
const MyComponent = Ractive.extend({ ... }, someMixin)
const SomeComponent = Ractive.extend({ ... }, someMixin)
const myInstance = MyComponent(...)
const myOtherInstance = MyComponent (...)
const someOtherInstance = SomeComponent(...}
```

Preventing the next assignment of the same name is just a nicety, something that should be solved at authoring, not at runtime.

Also, assigning to the global `Ractive` is something that really doesn't jive with module systems. Module systems expect functional/compositional code. Adding to a global something is essentially a side-effect, where you have to worry about load orders and things in order to have them all present at the right time. Which is why I also favor composing components, instead of register-globally-and-hope-its-there approach.

```js
import someDecorator from 'somewhere'
import someMixin from 'somewhereelse'
import someComponent from 'somewheretoo'

export default Ractive.extend({
  decorators: { someDecorator }
  components: { someComponent },
 /* other options */
}, someMixin)

// instead of hoping this module was called to import somewhere, somewhereelse, somewheretoo
// otherwise, they'd be absent globally.
import 'somewhere'
import 'somewhereelse'
import 'somewheretoo'

export default Ractive.extend({
  mixins: ['someMixinIHopeIsAlreadyPresentAndRegisteredItselfToTheRightGlobal']
})
```

**Comment by PaulMaly** [comment]
@fskreuz 

For example, we've some 3rd party plugin, which adds some functionality to the Ractive's constructor, Ractive's prototype and/or Ractive's instance. And also we use a modular approach. Ok, you could write this plugin like this:

```javascript
// ./plugins/myPlugin.js

Ractive.someStaticFunction = function() {};

Ractive.decorators.myDecorator = function(){};

Ractive.prototype.myMethod = function(methodOptions) {};
```
But , it won't work, because we don't have Ractive in plugin file. Ok, just require it:

```javascript
// ./plugins/myPlugin.js

const Ractive = require('ractive');

Ractive.someStaticFunction = function() {};

Ractive.decorators.myDecorator = function(){};

Ractive.prototype.myMethod = function(methodOptions) {};
```
But, we don't actually know in which environment our plugin will be used. Is it right Ractive, we required? Or maybe somewhere else someone clear require.cache after plugin call? How to assign something also to concrete Ractive's instance? We don't have that instance here.

My suggestion is to give a clear and simple way to call an external function in the context of Ractive. It's almost like decorators, I think. Here how I usually write decorators:

```javascript
// ./decorators/myDecorator.js

module.exports = function() {
     ....
     return { teardown(){...} };
};
```
I know that context of this function is Ractive's instance, so I don't need to require('ractive') inside of each decorator file. So, I suggest reusing this approach out of decorators - just provide a clear and convenient way to call an external function in the context of caller. Yep, we already can do it like this:

```javascript
const app = new Ractive();

require('myPlugin').call(app, {});

// but it looks bad and doesn't support skipping next call

app.use(require('myPlugin')); // more convenient way

```
Besides, implementation of this feature adds only about 6 lines to the source code. This is the function itself:

``` javascript

function use(plugin, ...args) {
    const plugins = (this._plugins || (this._plugins = []));
    if (typeof plugin === 'function' && ! plugins.includes(plugin)) {
        plugin.apply(this, args);
        plugins.push(plugin);
    }
}

```


P/S Actually, this won't work:

``` javascript
// Ractive polyfills Object.assign.
const instance = Ractive(Object.assign({/* options */}, someMixin)) 
```
because:
``` javascript
var options = {
        data: {
            foo: 1
        },
        decorators: { 
             bar: function() {} 
         }
};
var someMixin = {
      data: {
            baz: 2
       }, 
       decorators: { 
             qux: function() {} 
        }
};
Object.assign(options, someMixin); / => {  data: { baz: 2 },  decorators: { qux: function() {}  } }
```
So, we can't use Vue's mixins per instance approach. But I agree, that perhaps it not so necessary to be implemented in core.

**Comment by evs-chris** [comment]
I think there could definitely be a more convenient story for plugins in Ractive. It's not too bad for decorators, transitions, and events, where you don't really _need_ a reference to the Ractive constructor in most cases, but it can get painful with components. So far I've worked around global vs module Ractive with build tools, but it's not exactly ideal and requires the build tools or global on both ends (doesn't play well with requirejs, etc on the consumer end).

**Comment by ghost** [comment]
@PaulMaly 

> Here how I usually write decorators

Yep, that's pretty much how I export plugins. In fact, that's how they're being exported in the monorepo work I'm doing. [Here's the rxjs adaptor](https://github.com/ractivejs/ractive/pull/3170/commits/f012781024035972a72a6e68108c1402d0a9bf31) They all don't import Ractive, they're all just definitions. The consumer imports them, supplies the Ractive, knows about the instance/component.

> But , it won't work, because we don't have Ractive in plugin file.

Sure it _won't_. Your example assumes it's written with Ractive present in the global, which means it assumes that it's written for _the browser_. If you intend to write it for node, you _will_ have to use the module system to introduce something external. With a module system, you could write it like this (translate to CJS if you use CJS).

```js
// plugins/someStaticFunction.js
export default function() {};

// plugins/myDecorator.js
export default function(){};

// plugins/myMethod.js
export default function(methodOptions) {};

// App.js
import Ractive from 'ractive'
import myDecorator from './plugins/myDecorator'
import myMethod from '.plugins/myMethod'

export default Ractive.extend({
  decorators: { myDecorator },
  myMethod
})

// main.js
import Ractive from 'ractive'
import App from 'App'
import someStaticFunction from './plugins/someStaticFunction'

// Again, module systems are not friends with globals (that's the thing modules try to solve in the 
// first place). The best you can do is define them before they're ever used by the app.
Ractive.someStaticFunction = someStaticFunction

App()
```


> So, I suggest reusing this approach out of decorators - just provide a clear and convenient way to call an external function in the context of caller.

I don't see how your 4th code example is any different from the following, which already works, without the extra API.

```js
// SomeAdaptor.js
export default SomeAdaptor = {...}

// MyComponent.js, used in component
import Ractive from 'ractive'
import SomeAdaptor from 'SomeAdaptor'

export default Ractive.extend({
  adaptors: { SomeAdaptor }
})

// App.js, used in instance
import Ractive from 'ractive'
import SomeAdaptor from 'SomeAdaptor'

var app = App({
  adaptors: { SomeAdaptor }
})
```

Also, I think modules are the future of writing JS. If you're still needing globals, you should start writing modularly. If you can't, you can write in terms of modules, and let a tool handle introducing those globals as module dependencies. That's why Rollup `globals` exist, that's why RequireJS `shim` exists, that's why SystemJS `meta` exists - they all exist so that your  module code can "import" what's effectively a global without affecting how you write modules.

**Comment by PaulMaly** [comment]
@evs-chris 
> I think there could definitely be a more convenient story for plugins in Ractive. It's not too bad for decorators, transitions, and events, where you don't really need a reference to the Ractive constructor in most cases, but it can get painful with components.

I think it's not so bad idea to provide a simple and convenient way to execute some external function in the context of Ractive. Decorators, transitions and all these stuff are built-in plugin types. They already calling in the right context. But they also have limited structure and behavior. Simple ``use()`` method will give the chance to write more complex and domain-specific plugins, than built-in.

@fskreuz 

> Yep, that's pretty much how I export plugins. In fact, that's how they're being exported in the monorepo work I'm doing. Here's the rxjs adaptor They all don't import Ractive, they're all just definitions. The consumer imports them, supplies the Ractive, knows about the instance/component.

Yes, so why you don't agree with the idea to brings this ability to custom plugins?

> Sure it won't. Your example assumes it's written with Ractive present in the global, which means it assumes that it's written for the browser. If you intend to write it for node, you will have to use the module system to introduce something external. With a module system, you could write it like this (translate to CJS if you use CJS).

Actually, I always write my code with modular systems (above, I've typed "modular approach" twice). I don't use globals at all. And ``use()`` method makes sense, especially for modular approach.

> I don't see how your 4th code example is any different from the following, which already works, without the extra API.

It's very sad. Let's play with an example? You need to write some plugin for absolutely custom behavior. This behavior supposes that you'll need to add an additional static property to Ractive constructor, also add a few methods to prototype and also subscribe to events of the specific instance. It also needs to receive some arguments, like options or something. Clear?

So, I'll write it using ``use()`` method, but I'll be very interesting if you'll provide your own solution on existing API, OK?

Plugin itself ( !!!pay attention - modules, not globals !!! ):
```javascript
// ./plugins/myPlugin.js

module.exports = function(options) {
       const Ractive = this.constructor;

       Ractive.foo = options.foo; // add an additional static property 

       // add a few methods to prototype
       Ractive.prototype.bar = function() {};
       Ractive.prototype.baz = function() {};

       this.on('update', () => {});
       this.on('teardown', () => {});
       this.observe('some.key.path', () => {});
};
```
Usage:
```javascript
const Ractive = require('ractive');

const app = new Ractive({});

app.use(require('./plugins/myPlugin'), { foo: 'some value' });
```
Also pay attention, as this plugin uses such things as ``on()`` and ``observe()`` you need to prevent double installation of a plugin. If you, of course, don't want to do things twice.

I believe my way is very convenient. So, let's look at yours, welcome!

**Comment by evs-chris** [comment]
Pondering a bit more, having a plugin system that provided some Ractive context would make it much easier to split all of the big funky transition code out of core. There'd still be all of the hooks in place for elements and queuing in core, but all of the css transition handling and timing stuff could be pulled out into a core module that, if present, would be available at transition plugin init.

Then instead of `function(transition, params) { ... }` with the `transition` having `setStyle`, `getStyle`, `processParams`, etc, those methods would be available at init time for the plugin to capture and use at will if they're available.

As a follow-on, it would offer the plugin an opportunity to say, "oh yeah, your ractive is missing some core features I need, so I'ma either not install or just install a dummy version". That might _also_ be a way to tell decorators that they are running for SSR and allow some sort of limited API to have decorators run in that environment (add attributes, maybe content, etc).

**Comment by PaulMaly** [comment]
@evs-chris That makes sense, but in long-term. In short-term could we implement my suggestion?

> That might also be a way to tell decorators that they are running for SSR and allow some sort of limited API to have decorators run in that environment (add attributes, maybe content, etc).

Hm, I suppose that it could deprive of us some good opportunities. For example, I use decorators as the safe way to use the client-specific code on server-side. Decorators aren't executed on the server, so we can use DOM etc. inside of them.

**Comment by ghost** [comment]
Starting to see the benefit now:

- Containment, keeping the plugin "inert" until `use`. Currently, there's no way to defer execution of a plugin written in a module, unless you do it yourself... or have this feature. 👍 
- As seen in my previous comments, most of the setup is done in advance with init options. There's no way to do post-instantiation augmentation with just configs. You'll have to use the methods, then you'll run into bullet point 1 for containment... or have this feature. 👍 
- Multi-plugin setups aren't really a thing at the moment (i.e. one module installing a decorator, component, and a transition). It's a plugin per module, as you saw in the monorepo PR... or have this feature. 👍 
- Ractive-independent plugins, especially for multi-tenant apps. If you hard-code the Ractive import, you're locked into whatever Ractive is available in `node_modules` or the browser global, that is... unless you have this feature. 👍 
- As @evs-chris said, this would be a good way to augment Ractive with stuff like the SSR proposal or the splitting of Ractive into bite-sized pieces. 👍 

    ```js
    import Ractive from 'ractive'
    import RactiveParse from 'ractive-parse'
    import RactiveSSR from 'ractive-ssr'
    import RactiveDOM from 'ractive-dom'
    import RactiveAnimations from 'ractive-animations'

    // Before everything, Ractive is just barebones data modelling, until...

    Ractive.use(RactiveParse ({ ... }))
    // Now you have Ractive.parse()! ^-^)b

    Ractive.use(RactiveSSR({ ... }))
    // do SSR nahw! ^-^)b

    Ractive.use(RactiveDOM({ ... }))
    // do DOM stuff nahw!  ^-^)b

    Ractive.use(RactiveAnimations ({ ... }))
    // do transitions/animations nahw!  ^-^)b
    ```

That said... I'm a bit iffy about having `this` in code. Makes tests annoying to do, especially when `this` could be _anything_ (and you'd have to read the docs to know what it is or inspect). Also, using `this` deprives you the use of arrow functions.

Suggesting that a plugin be "a function that accepts options, and returns a function, which is then called by Ractive with a supplied with the correct constructor/instance.". Under the hood, Ractive uses the returned function's identity to prevent it from being run again on that constructor/instance.

```js
// Here's the verbose, ES3 form
export function MyPlugin(options){
  return function(Ractive|instance){
    // Augment the constructor
    Ractive.defaults.something = 'foo'

    // Augment the instance
    instance.on('something', () => {})
  }
}

// Here's a cleaner way with ES6
export const MyPlugin = options => Ractive|instance => {
  // Augment the constructor
  Ractive.defaults.something = 'foo'

  // Augment the instance
  instance.on('something', () => {})
}

// Usage
import Ractive from 'ractive'
import {MyPlugin} from 'my-plugin'

// Augment Ractive itself
Ractive.use(MyPlugin({ ... }))

// Augment a subclass
const MyComponent = Ractive.extend({ ... })
MyComponent.use(MyPlugin({ ... }))

// Augment an already-created instance
const instance = Ractive({ ... })
instance.use(MyPlugin({ ... }))
```

Few questions tho:
- Looks like Vue's plugin system is more of a global `Vue` augmentor, but the proposal also includes an instance-specific `use`. Does this mean there are _two_ ways to write plugins? 
- The example [here](https://github.com/ractivejs/ractive/issues/3178#issuecomment-358752296) assumes `this` is an instance. But the example [here](https://github.com/ractivejs/ractive/issues/3178#issue-289554090) assumes this as the global `Ractive`. Again, not a fan of variable `this`. Allows too much foot-gunning.

**Comment by PaulMaly** [comment]
@fskreuz I'm glad you see the benefits now.

> Suggesting that a plugin be "a function that accepts options, and returns a function, which is then called by Ractive with a supplied with the correct constructor/instance.". Under the hood, Ractive uses the returned function's identity to prevent it from being run again on that constructor/instance.

This way is a little worse, I think, because of more composite syntax. But it more looks like Express middleware and that's a plus. I'm not afraid context/this in JS and seems that built-in plugins, eg. decorators, is also use this way to propagate right context. But in general, this part of the solution is not so principle for me.

> Looks like Vue's plugin system is more of a global Vue augmentor, but the proposal also includes an instance-specific use. Does this mean there are two ways to write plugins?
The example here assumes this is an instance. But the example here assumes this as the global Ractive. Again, not a fan of variable this. Allows too much foot-gunning.

I think each plugin should be able to choose a way of usage. If some plugin is just extending the constructor, is ok. If another plugin doing some things with instance, is also ok. I think some plugins could be acceptable for both types of usage. It isn't difficult to make:

```javascript
module.exports = function() {
      const Ractive = this.Ractive || this.constructor.Ractive;
      const isInstance = Ractive.isInstance(this);
      ....     
};
```
Probably, use() method should be acceptable in two forms: ``Ractive.use()`` and ``instance.use()`` and a plugin usage should based on it's meaning and docs.

**Comment by dagnelies** [comment]
Dunno about all this stuff. It looks complex to me and seems to add not much to the table. IMHO the issue is less about *how* to make/import plugins but more about people actually *making and maintaining* plugins. Currently, the list is tiny and half of them are outdated. Therefore, I think the best way to foster the ecosystem is to keep things stupidly simple like it currently is. My 2 cents.

**Comment by PaulMaly** [comment]
Closed!
