### ISSUE TITLE
Ractive Initialization

### ISSUE THREAD

**Issue by taranglute** [ractivejs/ractive#3181]
## Description:
As per doc we can create Ractive  instance without configuration or specifying base level configuration like **template, target and  data.** I am using first approach i.e without config. 
After initialization, i provided base values as below:

```
var _ractive = new Ractive();
_ractive.target ="#target";
_ractive.template = html;
_ractive. data=_data;

/*method name to notify ractive to render view*/
```

Now, i am not getting how to notify ractive to render template. I tried "Updatemodel" and "Render" method, but no success.  

**It is working as expected if i go with configuration approach.**

Can you please guide me on this.

Regards

**Comment by evs-chris** [comment]
Which docs are you looking at and for which version of Ractive? It sounds like there are some that need to be updated.

You _can_ start with an unconfigured instance, but you'll have to do a little more work to get to a rendered instance - specifically, some of the stuff that the configuration handles for you.

The template property should be an array of parsed template bits, however, the vdom is created from the (blank) template and bound during construction, so swapping out the template won't actually do anything without triggering a rebind by either unrendering/rerendering the instance or calling `resetTemplate` with the new template.
```js
// this will work if you force a rebind
r.template = Ractive.parse(html);
// this will work, but only if the instance is rendered
r.resetTemplate(html);
```

As of version 0.7, I think, you also can't modify data directly, and I think the `_ractive.data` property is a vestigial placeholder from that change. Instead, you'll want:
```js
r.set('', _data);
```

To trigger the instance to render, call the render method with some sort of target, which in this case is a target node selector:
```js
r.render('#target');
```

[Putting it all together](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOngIYxq70B8BA9CaWyDgGd4AYwD2AOwG5yMctXLiEAd3IAlBsNxkEACgCUAblriYAOgEJcOgOTWs5YOQBmo0ZHLWwCADbfR18gxDYzMYBHEkBBgbAGJcJhZrYJNTMItcABUEAFsAB28GXF1rFzcHYFKMDCSDTCA):
```js
const r = new Ractive();
r.set('', _data);
r.render('#target'); // this is essentially free, since there's no template yet
r.resetTemplate(template);
```
