### ISSUE TITLE
Ractive webapp examples

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3186]
Hi,

Related to #3158, I think that beyond a list of links, what would be really cool is a list of example apps. The goals would be multiple:

- to show the world some cool apps 😎 
- to "learn by example"
- to have templates to quickly get started
 
Basically, I would envision this as a list of minimalistic "all in one page" apps, that can be simply copied to get started. That way, anyone could also easely contribute examples. Anyone could also request specific example, so that most topics are covered. Do *you* need some example? 😉

**Comment by ghost** [comment]
Being tracked here https://github.com/ractivejs/ractivejs.github.io/issues/74 and still collecting dust.

That's something I'm targetting once I get everything in a monorepo and can do huge swathes of code changes if needed. I'm planning to get playground as the first app as part of that package, then the examples and presentational ones as mentioned in the docs issue next.
