### ISSUE TITLE
animationend and transitionend events do not fire in IE11

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3190]
## Description:
animationend and transitionend events do not fire in IE11

## Versions affected:
0.9.11

## Platforms affected:
IE11 / Windows

## Reproduction:
You can view the issue on this[ playground link](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSANCAzlA2gLoC+WALvADxICWAbgATVIC8AOiKQIYxqnsB8FAPQ1a-VgDtJFbAGMY1AA6lGLdqQQBbRQBtOG9vVIBPRQjYcEAD1JCYnWaToIBk1qSp16svdmwXOCWpNfWR6ACMAeyt6bB0mBABJCQAZBAAzPhB6SIkAWkDg-WpchAk1EAABFB1I8M4dADoGhBhSAAoAcgBBIJCnXPoypGQAQk6ASgFgYCirAEYiIlHhUXEpD1FvX391ewlsagGpbNy80n3D4+GLatr6ppa2roAVS6OSiSHyscnp2eiACYlisRHR1sI5AplPxMDh4LRuPR7I5nPRmPQJAgAO70ABKDictAQ7WAknoRm4vEg9E6AGIuDwEKROhhyUYtLpQjT6RptHoNKz2Uh9JwacAItF5jzekVjqzJVZATy3oErp8cl8wJFiTBOvQiJIiBMANxw2TwRpzehkjbYpikMA0+YABhdiisJrcjoQ1BQYFIkFd7s93vqsgA1igYJEAK7lPKySK1GCQOkIDNejYaGwFeIoCQ02RlDQwLPuRScJA0CQoc6RRSQAAsIfLpDmeUOAC9qLWaVEYCMYHk5lnDVJynRGhc1R9Brb3O4Qjxe-XG-RXR6sxSKfakI7nW6t+yKWBff7Axuj6Gvjvw1GY-GkDSYMhtzuc6Q837C94S613wpGcDjnX890dDdsDbCsqxrOtSAbZtWx3egT0VTtqB7PtJUHVoR2iMc3EnWhp3eY5IG1XUbTQ8CnXoABma9CInIQACp6mwBBvEiEZWKESRmj6UIkGo288mxBBwgjI4CiE448iQWN7HIyD30KfpPgUpTilyZ0oPZcTJOkr91J0-J0moHQdDyTQeIQftIkdNS5M0iyrJsuyHKco0BNMjQkEaXsLKCDRRIpQypJkvzNKOVozMTOMJEvILe1i5y5Ri0t4qTeNkokYK0p8iRBLlZBGjAXs0DC+gIuM2SMrORTlM+GlAX029osa7SVLa5i2J9ehOq+EYCuOPjJEqWqZIjBBjHSexNAQbBYniEZkjSTJqpdABSarwokyKv2A7B0kiGBNBpY6BQQeikHaPJg22jB6BdZ6XVNNDjtO87Lsua7bvux63rej7bwpWhqEOcJLKOYwaQhqGdBcW9xwpR69pqg66q+s6LqMP7QgB16XpBwD8bVb68auwm7uJumphRorKhmuaFqWlaEnWjIVFtCkdoxqajsuSnfrVf67oet0npJl7QZQmzsHOYXcdFg5xcBqXgdlsmcZ+8m1ZpjWdq196yYR6hofiEx4chi2kfZVGr353md0FpWKZV-W4kNunSbQhX3YOEWvfV33tc+5W9epjQiZNhmKXHcdGjiTnUm56q3aGvIJE4RaaRTta08ydKNLOHO845wuNr4CRxxAIggA)

Attaching the events manually works ok ([playground link](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSANCAzlA2gLoC+WALvADxICWAbgATVIC8AOiKQIYxqnsB8FAPQ1a-VgDtJFbAGMY1AA6lGLdqQQBbRQBtOG9vVIBPRQjYcEAD1JCYnWaToIBk1qSp16svdmwXOCWpNfWR6ACMAeyt6bB0mBABJCQAZBAAzPhB+YGAoqwBGIiIAQmFRcSkPUW9ff3V7CWxqJ0ipbNz8gCZispE6SuE5BWV+TBx4Wm56e0dnemZ6CQQAd3oAJQcnWgQACmBJeiNuXkh6AHIAYi4eBFJzjEOjLV1Qs6uNbT0NB6ekfU4Z2AEWiBXeAEEgiFWhIHiCrF13gAVRrNGH0Nr0MCRHYwc70EhPNqySJfO4IM7pACuEjmbV2AEoDhIju5SGBqNgAHTpagSJC7c5c-LnBlczhIJAAUR2ElIKU5GmWMEFgWC+mobQQ-Lh1NpMMZzNZfC4OgQMFIgsh6vR2qQyBKooA3E93EQGS6WfQ2Rzubz+YKuaRUS1NbCxRLpbL5YrtebBcHAmiw3bdTS6RJDa6TZwzRbBSik6HMXaHc7s+6ncankRJJXxrJ4MLovRme4Vkx2WcCgAGHuKKye9xgBDUFBgUiQXv9wduUjhBwAaxQMEiNKQAFoSTpIjBIJcEIeh6QNDYN7mxxIzrJtRoYMfFJG+SgN6RIopIAAWGfH-Ib5oAF7PmcUQwPaMAbvknq1lI-J0EGIbom2JohDwfKvu+3Y-k8RwdkgXb0NOA6ekcRwjmOE5YdhXpHAusjLqu65nDAyAkaRp6kOe8QoFe3i3uabFHImTTFrxeHsoR2DHu4j6Ss+GEft+xGkd6NHwv+1BARIKAgbu4GQdE0FuHBtAIUWMKQNiuKtjh9DiWAZwAMx9sRdbGUIABUC7YAg3iRPaHlCJI4pQqESA2V6G4rAg4SLi056hTCG5IFS9gWZJbFqtCYbJalGptN2UlPFFMVxZxWX5RIG68joOgbpo-kUiC7KZYlOU1XVDX2rpLVuRIIU2sgXJ8v6LS+Ua9AlbF8UVUlY1pTlJI0pOjASKNGitTaOXzZVW5rnKZwjXyY1Gf1s1DRy2njcV0XTeVbVtLlC0FfQXRFV6s05Slz28W9p2eeyvmfZi9rrWGgWSAAAlNZUbouCDGOk9iaAg2CxPE9rJGkmQRUcPYAKS46RMPxcJ2DpLumhnGT3wII5AobtO+MYPQPYsz2Hq2WTFMwFTRiorT9O7IzfbM6z7Oc2ptCctQ4TUPEJhnNLzThGaNZPEzRNHCTnHc5T1MC6EQts+LrOSypeu8wbSaCwKJv2wy6sSDBkPw4jyOo+jCRYxkKgTQTWuTbdsOW3zNNGwzTPsxLgmTZo2CvqiPNh4bGhCyLBPR2bseh9bTS28LUemxzsfK7L8stMYSsy6rLhejBRyaxN2vB6TSf6-zNsR7s9sx7Z9UJ7nnf593vfZ1z7dW8PcSj1nHNOzBXJxN7qS+0TOsJVtj0SJwKNnMvmOr5km3Zdvu9NQfSRH3wzuSCARBAA))

**Comment by evs-chris** [comment]
Apparently IE doesn't have HTMLElement.ontransitionend and friends, so ractive was deciding that those events aren't available. I've added a whitelist that seems to have resolved the issue, but since it's hard to test, I'm going to wait for verification before calling this resolved. If the fix is good, I'll pull it in to the changeset for 0.9.12.

**Comment by ghost** [comment]
If this becomes one of those inconsistently supported events, this might be a good candidate for a custom event plugin. For instance, the custom `tap` event plugin is actually made out of `focus` and one of 3 other events (`pointer`, `touch`, or `mouse`).

**Comment by evs-chris** [comment]
Weirdly, it's fully supported by IE11 (and even 9 an 10 for the transitions, I think). It's just another IE-ism that they don't have an `ontransitionend` property on the elements, which is how Ractive determines whether or not the event is a DOM event.

**Comment by kouts** [comment]
This worked, thanks @evs-chris once again!
