### ISSUE TITLE
Error When Setting Value Bound to a Multiple Select to Undefined

### ISSUE THREAD

**Issue by DavidTimms** [ractivejs/ractive#3194]
## Description:
If a keypath is bound to a multiple select box, and the keypath is set to undefined, then the following error is thrown:

```
Uncaught TypeError: this.binding.forceUpdate is not a function
    at Select.sync (Select.js:85)
    at Select.update (Select.js:110)
    at update (methodCallers.js:15)
    at Array.forEach (<anonymous>)
    at Fragment.update$5 [as update] (Fragment.js:265)
    at flushChanges (runloop.js:119)
    at Object.end (runloop.js:27)
    at set (set.js:52)
    at Ractive$set [as set] (set.js:9)
```

I believe this is because [Select.js](https://github.com/ractivejs/ractive/blob/e1d4a01/src/view/items/element/specials/Select.js#L85) is assuming that its binding is a `SingleSelectBinding`, as that subclass has a `forceUpdate` method, whereas the `MultipleSelectBinding` class does not.

## Versions affected:
We first encountered this in our codebase using 0.9.11, and I've reproduced it in 1.0.0 Edge.

## Reproduction:

[Here is an example on the playground.](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSANCAzlA2iCALoC+WALvADxICWABLUgLwA6IARgPYAe7AfFQD0dAG79WAO0w54AYy6Ts5egoC2AB0UJJK5vUkIA7vQBKAQznlaohAApgU1uXIJNAG3OvI9AAZPyZypsBHcEK3pRc3cAVwQ2EGBgcjBaSRRsEhJ2ejUY92sNMIlJZzLyKi4Na0V+ABVU9PoARmEqmskS8qD22lqGtJR6ACY26r7OgPLK8f7GoYBmMY6uwIqhELCrVd8MKRIASgBuJ0l1LUNdADoYHSQEGDsAcgBibh4n49OQ8jraNQQXBi5DsdgO9GY-HojlKa3O2muP2eKUG2CeGHoMUk9wAZmlkF9JGR6ABWAAMZOOIBIQA)

**Comment by evs-chris** [comment]
Your analysis is spot on. This is fixed on edge and will get pulled into 0.9.12 when it gets cut. The edge build will be available as soon as travis does his thing. Thanks for the report!
