### ISSUE TITLE
Proposal: @last special reference

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3196]
## Description:

A `@last` special reference would be handy when we want to handle the last loop specifically in an `{{#each}}` loop: [Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gDoB2ASgIYDGALgJYBuCAdEggGZkCuANlbo12VxUAklQQBbAAQBeSaw5FqNAPZEAFAA8AlJODECVGAiocYRSQHkARgCsE1RgGsEAT1yat-BERRUwkgFpJAEZJYgx9IiIEAHdJciUGNT0iAwQuSEkAcitlJBcsrH0qMXEABwExTIADYoMAHjKAPklRSRjlbiRJKwRJFCMyKkkqZUkOXD6CaYJgYEkAARoiFg0ZaVkFgSFJDAwRsZYxGHFlqdSqAwM-Pu3hmlKwi4aAema6qjmAYgRKf1ZlMo9h8Gu9npcIc4XJk5gsoXssE8rhCDMtVjDgEsVggNHskSiId8aKxFmicetZAAGBFyGgwHYPCRzF7E4Hg5FEkl3UQSNQAPxeAOUOg2mzJuOwkjukkZUmZrIi7Ko9TeTQ+zN+FDAbIM1SKFyQQzIMI+QpNSuNIURIKoVkyACZrUqKJkAMwfRUGRUYLSYIA)

**Comment by evs-chris** [comment]
I have a change in progress that moves index and key models from the model tree into the view for shuffle-y reasons, so adding in a `@last` there would be a good deal easier. I'll see if I can integrate it with the rest of that changeset.

**Comment by dagnelies** [comment]
+1 on this one, simple and handy

**Comment by ceremcem** [comment]
[This one](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gDoB2RCA7gAQBKAhgMYAuAlgG4IAUwxBDCANpAoByAEYB7JAE8hWbg14BbAA58avQQAM5PADxKAfBQDCYBHQDWFBqYp0xRXGL4IKAMzEwrNhDBgeK2gw6APQGgcDAAMQI9GBuYmIYGIG6YUQ8GQw85giSghEAAjmSSVgB6VmVPExESAgAHvnABTV19UnlmZkRkUyuFC21DRQAvGMUAAylbkwwuAwUTIoRwX1JKZU9fQOtw2MjA6rz00cLSwgKFCtryRWZIWndwMExdGDrFRqyFUhqNPmBdxiAF3Sr-CgARjKGxEggATNDQTw6IIAMyBW48W4YACUmCAA) should run with current edge version, right? (I was waiting for jsdelvr to update the edge build but as current ractive.js includes `  var last = keys[keys.length - 1];` line, I think it is built already)

**Comment by evs-chris** [comment]
The cached script in the playground is notoriously hard to evict. I should probably add a cache-buster mode. Anyways, [it does work](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5QdgVwDbIDQgM5QNogPT6LwAOA1gOYB0AxgPYC2+MAhjQC4CWAbgKYACvACYVeIALoBfDNkggAOvHi8A7gAIASmy58AFMEXz2vZJDUByAEZ0hAT3NpD7YwxLIWxswAMnRgDwkAHxqAMJgvDRkauzhavTwmHTIvGoAZnQw0bG8MDAZar7sfvhBhcDAAMS8bGBpdHSSkoX+pfBG7exGZLy2ZuX83baNaAVtneNGnPBCvAAefcD8UzOzjaMdHeUVnKlqS9NzagC8J2oADMNpnDCY7GqcLuX4O43N41s7e8uHJ0d77rdLgC7g9eAw1E8Xk0xh1iq1NsB8NUaGBXmMvI4xkIPCw+oV0nQ8TDxri1ABGEZvSxmABMlOJRhoZgAzIVoUZoZIAJQgSRAA) if you get the latest build in there 😄
