### ISSUE TITLE
Ractive & Webpack 4 – require issue

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3200]
## Description:
Creating a bundle with Ractive and **Webpack 4** results I get an error while loading the script:
`ReferenceError: require is not defined`.

Maybe there is something that should be changed in Ractive?

Disclaimers ( :D ):
* This issue doesn't appear with Vue or other libraries. 
* Webpack has been released yesterday and maybe is an issue on his side?
* In summary, consider this a low priority issue.

## Versions affected:
Tested on 0.9.13

## Platforms affected:
All

## Reproduction:
Follow instructions provided here:
https://github.com/marcalexiei/webpack-4-ractive-require-error

**Comment by ghost** [comment]
Hmm... Ractive alone has no dependencies, and therefore no import/require in code. It's most likely a Webpack issue. I've seen Rollup/Buble bugs that happen in Ractive mostly because they wrongly handle valid ES syntax (sigh, JS is now this complicated).

**Comment by marcalexiei** [comment]
A possible workaround is use `js` files instead the `mjs` file. 

For now is the best solution I've found.

**Comment by evs-chris** [comment]
That's really weird, but I've verified that no `require` has managed to slip into our ESM output. I'd guess there's probably a mysterious webpack config incantation and dance that you missed while setting it up, based on my admittedly limited experience with webpack.

I also don't see anything in the webpack 4 changes that scream "I'm going to break your build" from webpack 3. The config in your repo is almost frighteningly small compared to some of my webpack 3 projects too. I'll see if I can poke at it when I get a few spare cycles.

**Comment by ghost** [comment]
At the very tip of that webpack generated code, inside the `eval` on line 82 is...

```js
require(\"./../webpack/buildin/global.js\")
```

So yep, not Ractive. Speaking of using `.js` instead of `.mjs`, shouldn't imports be extensionless? Also, doesn't Webpack normally speak CJS and not ES? And that you need Babel and some package.json/webpack config for Webpack to understand ES?

**Comment by marcalexiei** [comment]
I'll do more test in the next and let you now.

Thanks for the quick feedback!

**Comment by marcalexiei** [comment]
Removing the extension fix the issue. (facepalm)

Closing and thanks again.
