### ISSUE TITLE
Memory leak while passing data to child component using static delimiters

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#3201]
## Description:

Similar to #3183.
Passing data to a child component using static delimiters results in a memory leak.

## Versions affected:
0.9.13

## Platforms affected:
All (tested on Chrome)

## Reproduction:

```javascript
Ractive.components.MyComponent = Ractive.extend({
	template: `
  <div>
  	<h1>My component</h1>
    <p>{{passedData}}</p>
  </div>
  `,
});

const r = window.r = new Ractive({
	el: '#main',
  template: `
  <h1>Title</h1>
  {{#if showComponent}}
  	<MyComponent passedData="[[@.get('description')]]"/>
  {{/if}}
  `,
  data: {
	  showComponent: true,
  	description: 'Root description',
  },
  
  onrender() {
    setTimeout(() => {
      this.set({ showComponent: false });
    }, 500);
  },
});
```

https://jsfiddle.net/7xbr57b8/8/

1. Using Chrome open fiddle and wait 1 second.
2. Perform a memory heap snapshot.

<img width="1251" alt="heap snapshot" src="https://user-images.githubusercontent.com/628799/36725805-ccf2a772-1bb7-11e8-8006-b490142d25f5.png">

**Comment by evs-chris** [comment]
I _think_ I have this one plugged too on edge now, but I'm going to leave this open for you to verify when you get some time. Thanks for the report!

**Comment by giovannipiller** [comment]
Looks like it's fixed on `1.0.0-build-138`.
However, it's not, on the recently published `0.9.14-build-1`.

I can't test it on my application yet, since there are a few things to be updated to run on the 1.0.0 branch. Would it be possible to port it to 0.9.x?

**Comment by evs-chris** [comment]
The fix should be available on v0.9-dev as soon as travis does his thing.

**Comment by giovannipiller** [comment]
Hmmm, I might be doing something wrong here, but it doesn't seem fixed on: `0.9.14-build-4`

https://jsfiddle.net/7xbr57b8/16/

**Comment by evs-chris** [comment]
Nope, I managed to bork porting the patch. I _think_ I got it right now.

**Comment by giovannipiller** [comment]
Fix confirmed both on JSFiddle and my own project. Thanks a lot 😃 🎉 
Build `0.9.14-build-4`.
