### ISSUE TITLE
Distinction between event handlers and helper functions

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3206]
## Description:

> Note: name "Method" is mistakenly used in place of "Helper function"

I'm trying to understand the exact distinction between events and methods. What I understand so far is: 

>Methods can be called in 2 distinct ways: 
> * Simple calls (execute and use the return value as is)
> * Event calls (passed `@context` as the first argument, executed asynchronously (with `setTimeout(..., 0)`, return value is handled as a "should I bubble?" value (boolean)

What would be the problem when I [use a method as an event handler?](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7tCANpKQDkAIwD2SAJ6CsnbjwC2AB16UeAgAazaAHgCuvAHxbuwYAGIENMKQCCMGJQksArAEoMGYzt70jXWtzc2riKlASkogQAtNQ+1ADWALzsIPISAKLMBAEgBgDCcfGk8giktKKkAGb0MKWZCNmkpgAC9ARICAAeHqT0uKQCpgB0laKiHtoA9CFhfoE6kz5zAbSmk5bUYB5aU-rLeoZephZWtvaOLu6e-kFLXkEz4ZExhcmpEgCyCLRg4izN1EiPE6tFcKXyhWKpXKVRqpS+P3ETWArXaXR6fQGyJGYwm01CBGWQUWviOwHWVm2-l2h386hk-kigy8aXq2QElV0BDo9EiLDonVcHBuKwFQ1w3xYghxomkpDFaFoUtRHU6glcrgA3F5rtxsFokKpKMyRWkEb8kByuTy+QKhfdaGKJUrpaNZVh5bROkNFcq2qr1VqHTqtNcMK4QDhqPBHk0tGIYB0YAIAIyKTqkXCiHxIUi1JDagjXHxx-zySgwFBtATOdOFjCYIA) (or [like this](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7tCANpKQDkAIwD2SAJ6CsnbjwC2AB16UeAgAazaAHgCuvAHxbuwYAGIENMKQCCMGJQksArAEoMGYzt70jXWtzc2riKlASkogQAtNQ+1ADWALzsIPISALIItGDiLAAC1JE8AB60ril+gQHVAMJx8aTyCKS0oqQAZvQwzZnZ4qSmefQESAjFHqT0uKQCpgB07aKiE2FIpADUAMyT07PAaTZIozAsm1ikC0vunv5V2gD0IWGV1Q8+LybA95bUYB5aD30L3UMn8SFUlFmXh4uFoAmcoKqaV6OSQAnaugIdHokRYdGKrg4t2quCyABV6E1RLpaCwWBisQxcYSvFV8XNSbTBJdRNJSOy0FyhiMxoJXK4ANys6qFAi4US8BBzXiiFAsbJTOaCliCGG0MWS6UYVxzYTDJDqsBTVznAAMhuJ3EYlBgpGEumEwkVpESLRgugQUsdtG6tF0MHC7s9iqDVWwXgORwQMHRmOxuMo52ELODofD4UoGzdseqN24N2NIBw1HgT3CRO4YhgxwEAEZFMVSPKfGtukgS6EjsMUAIACwdoM3HwDLTyF0oYbwiecDCYIA))

Let's assume we can call a global function: (this might be an **another proposal**)
```html
<button on-click="{{alert('hello world')}}">click me</button>
```
We can now simulate an event call with methods like so: 
```html
<button on-click="{{setTimeout((function(){myMethod(@context)}).bind(@this), 0); /*return bubbling flag */ return true}}" >click me</button>
```

(**Proposal**) Let's assume we have a sugar for `setTimeout(..., 0); return ...` (which is kind of `fire` method): 
```html
<button on-click="@@myMethod">click me</button>
```

**More examples:**
```html 
<input value="{{.foo}}" />
<widget on-click="someMethod">simple method</widget> // call like someMethod()
<widget on-click="someMethod(.foo)">method with parameters</widget> // call like someMethod(5), return value is passed to the caller
<widget on-click="@@someMethod">simple event</widget> // call like someMethod(@context)
<widget on-click="@@someOtherMethod('additional parameter', .foo)">event with parameters</widget> // call like someOtherMethod(@context, 'additional parameter', 5)
```

## Question
Would this (with or without sugar) be an option to forget about `on: {}` "events" and use data methods in place of events?

**Comment by PaulMaly** [comment]
`myMethod` from playground example is not a method. Mostly it could be called as “helper” function. 

Method is function of Ractive’s instance itself, like ‘’ractive.get()’’ (any built-in methods) or custom methods: ‘’ractive.myMethod()’’

So, you already able to call instance methods in simple way: 
`on-click=“set(‘foo’, ‘bar’)”` (built-in methods) or `on-click=“myMethod()”`. Or using `@` or `@this`

**Comment by PaulMaly** [comment]
> Distinction between event handlers and helper functions

Event handlers (or event listeners) defining in special option `on: {}` or using built-in method `ractive.on()`. We use it for custom events. Events are triggering by built-in method `ractive.fire()` and more than one listener able to handle this event.

Helpers is a simple (good practice - "pure") functions for templating purposes. For example, if we need to format a date or something. Defining in `data` and able to be used in curly brackets like this `{{ formatDate(dateCreated) }}`.

Difference just the same as between any other imperative function and any other event in programming.

**Comment by ceremcem** [comment]
>Events are triggering by built-in method ractive.fire() and more than one listener able to handle this event.

Then if we overwrite `ractive.fire()` to make it search for "events" in helper functions today, we can start using helper functions just like event handlers (or event listeners) right away?

**Comment by PaulMaly** [comment]
I don't understand a purpose of using helpers in this way, but you don't need to overwrite `fire()`. Feel free to create special method for that:

```javascript
new Ractive({
     data: {
         foo: () => {},
         bar: () => {}
     },
     emit: function(keypath, ...args) {
          const helper = this.get(keypath);
          return typeof helper === 'function' && helper.apply(this, args);
    }
});
```
```html
<button on-click="emit('foo', 'hello world')">Go</button>
```

**Comment by PaulMaly** [comment]
Btw, you can use new custom plugins method `use()` for this:

```javascript
// ./plugins/emitHelpers.js
export default function emitHelpers({ Ractive }) {
    Ractive.prototype.emit = function(keypath, ...args) {
          const helper = this.get(keypath);
          return typeof helper === 'function' && helper.apply(this, args);
    };
}

// app.js
import Ractive from 'ractive';
import emitHelpers from './plugins/emitHelpers.js';

Ractive.use(emitHelpers);

new Ractive({
     data: {
         foo: () => {},
         bar: () => {}
     }
});
```

**Comment by evs-chris** [comment]
Anything you put in an event directive is treated as an expression that is evaluated when the event fires. There are two forms of sugar `on-click="event"` and `on-click=['event', ...args]` that allow you to more easily write `on-click="@.fire('event', @context)"` and `on-click="@.fire('event', @context, ...args)"`, respectively,

If you use `fire` in an event directive, or one of the sugary forms that handles the `fire` for you, then the event listener (either DOM or Ractive depending on whether or not the target is an element or a component) will use Ractive's event system to raise an event that will trigger listeners installed by `ractive.on()`.

So, two separate but related things:
1. Event directives, which install a listener on the DOM or Ractive component, and fire whatever expression is passed to them when the event fires. This expression is implicitly an array (so you can call multiple expressions separated by commas) and can be any valid expression supported by Ractive, including instance method calls (`@.someMethod`, `@.fire`, etc) and data calls (`.doSomething()`). If the expression is just a name (`foo`, `myEvent`, etc), then it is de-sugared into an `@.fire` call.
2. Ractive events, which are emitted with `ractive.fire()` and listened to with `ractive.on()` and `ractive.once()`.

The confusion probably comes from the old terminology where there were two different types of event directives - one the would proxy the event by firing a corresponding event in Ractive's event system, and one that would call a method on the Ractive instance directly. That distinction no longer exists, as all event directives simple evaluate the expression that is passed to them.

**Comment by ceremcem** [comment]
>That distinction no longer exists, as all event directives simple evaluate the expression that is passed to them

Like `<button onclick="my; pure; javascript;"`?

I think I understand something after I asked (as always): Ractive events should be able to be defined in a different way from valid Javascript functions, because events support publish/subscribe pattern, so their name may be different from valid Javascript function names, such as `"*.click"`. That must be the exact reason why we are defining these interchangeable functions under different keys (`on` and `data`).

**Comment by evs-chris** [comment]
> Like `<button onclick="my; pure; javascript;"`?

Very similar.

For methods vs event subscriptions, the names don't _really_ matter, as you can still `.['some-weird and *funky* key']`. The functions defined in `on` are attached to a ractive instance to be called when a certain event name is fired on the instance, kinda like `HTMLElement.addEventListener` or `EventEmitter.on` - it's just a shorthand for `this.on('event', handler)`. Methods/functions in data are just that - items in the data. They can be called as part of the template rendering (`{{event('why not')}}`) or when an event fires `on-click="event('more likely')"`, whereas the _only_ way to call a listener installed with `on` is to `fire`, whether manually from the API, manually from the template, or as a sugared proxy event from the template.

So they're not exactly interchangeable, but there are two systems that can be similar depending on how you use them.

Proxy events are useful for bubbling and having one listener that can be triggered from multiple places. Expressions are useful for calling methods in data and simpler reactions to events like `<button on-click="@.add('.num')">+</button>`.

**Comment by ceremcem** [comment]
@evs-chris I've been thinking about this distinction (if it's really needed or just a design decision that is made at the beginning and it's worth to propose a simplification) since your last comment. It's better to close the issue while I'm continuing to think about it. I might post something later.

>I've learnt many valuable tips, btw. Thanks!
