### ISSUE TITLE
How can we pass decorators inside components?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3207]
## Description:

How can we make `<mybutton />` to display a tooltip: http://jsfiddle.net/9g3pB/115/
## Versions affected:

0.9.3

# Edit 

Or [is this the intended way](http://jsfiddle.net/9g3pB/118/)?

**Comment by PaulMaly** [comment]
@ceremcem you can't assign decorators to component tags, only html tags.

http://jsfiddle.net/9g3pB/124/

**Comment by ceremcem** [comment]
Fair enough.

**Comment by evs-chris** [comment]
It's actually available in edge: http://jsfiddle.net/9g3pB/127/

Since decorators and transitions can't apply to a component, it will automatically package them into extra-attributes.

**Comment by PaulMaly** [comment]
Awesome!
