### ISSUE TITLE
What's the purpose of anchors?

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3208]
I've noticed this new "thing" in ractive, the "<# mountpoint />" anchor tags https://ractive.js.org/api/#anchors. The two examples in the docs are rather contrived though.

I just don't get what their purpose is... can anyone enlighten me?

**Comment by ceremcem** [comment]
I think it's the key facility for making async component loading feature available: https://github.com/ractivejs/ractive/issues/3089#issuecomment-329965591

**Comment by PaulMaly** [comment]
Question is very interesting. I never used them, because I think there's a very narrow case when this approach really has no alternative and it could be used.

Also, I not up to the end understand that Anchors (attachChild/detachChild) differs from the usage of insert/detach.

Besides, we also have an async loading of Components. All of it blows my mind, sometimes )))

**Comment by ghost** [comment]
It allows you to attach and detach components from the template dynamically. A big use case for this is routing, or when you just want fine-grained control of what component renders when, where, and how.

Normally, in Ractive, if you want to render/unrender a certain component at a certain condition, you'd need to stick entire trees of components inside an `{{#if }}` and toggle the expression to render/unrender, or use toggling classes to hide/unhide.

```xml
{{#if something }}
  <ThisComponent />
{{ elseif somethingElse }}
  <ThatComponent />
{{ elseif ... }}
  ...and so on
{{/if}}
```

There are a few problems though:

- The components are set in stone in the markup at authoring time. You can't decide "Oh I want to attach X component here" at runtime.
- Maintaining a list of references and the components they toggle becomes a burden past a dozen.

With anchors, you just define a "mounting point" on the template during authoring time. What gets mounted is determined at runtime. This API is very low-level. You'd have to instantiate a component, manually link mappings with `ractive.link()` and attach/detach the instance at will with `ractive.attachChild()` and `ractive.detachChild()`.

**Comment by dagnelies** [comment]
Well, I guess I have another take on things.

Usually, I only use components for reusable widgets and I load them together with ractive. I never encountered the need to load them async.

What I had was an app requiring ~30 dynamically generated forms, these could simply be fetched async and placed inside the template using `resetPartial`.

For some "pseudo routing" you could simply use a partial too:

```
new Ractive({
  template: "{{>.myView}}",
  data: {myView:'homepage'},
  partials: {
    homepage: '<h1>Some fancy html</h1><button on-click="set('myView', 'details')">Show details</button>',
    details: 'Can be loaded async...'
 }})
```

**Comment by dagnelies** [comment]
And here a working example of "pseudo routing" using async partials https://dagnelies.github.io/ractive-examples/editor.html?url=partials-nav.html

**Comment by evs-chris** [comment]
The crucial difference between managing components via anchor vs with dynamic partials is that you _fully_ control the lifecycle of the component. The goal with anchors was not asynchrony, but unmanaged instances without detach and insert hackery that can lead to tears. Asynchrony was just a useful side effect.

With template managed components, when the bit of template is torn down, so is the component, along with any non-shared state it may have had. Defining views (what I call non-widget components) to attach to anchors lets you keep a stack of widgets within it, for instance a tree with some user expanded nodes, that are isolated from show/hide and render here/move there for more complex apps.

**Comment by PaulMaly** [comment]
@dagnelies 
> And here a working example of "pseudo routing" using async partials 

I use real routing in the same way. ))))
