### ISSUE TITLE
Request: ractive.observe should accept array for multiple path observations

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3210]
## Description:

Currently, if multiple paths which are unable to be be defined as wildcards are required to be observed, the syntax is a space separated paths string: 

```js
this.observe('foo.x foo.y', function(value){
  this.add('count');
})
```

I *think* it would be more sane to pass these paths as an array: 

```js
this.observe(['foo.x', 'foo.y'], function(value){
  this.add('count');
})
```
## Versions affected:

1.0.0-edge

**Comment by ceremcem** [comment]
...might the reason for a "space separated list" be the consistency between `observe()` and `on()`? Since we can not pass an array as a key of `ractive.on()` parameter object, maybe this space separated syntax is mandatory? (if this is the reason, this issue might be discarded)

**Comment by PaulMaly** [comment]
I think it's for consistency. If you need to store keypaths you want to observe in the array, you able to do that:

```javascript
ractive.observe(keypaths.join(' '), () => {});
```

**Comment by evs-chris** [comment]
I'm not sure of the original reasons, but the space-y version will definitely be staying around for init hash reasons:

```js
new Ractive({
  observe: {
    'foo.bar baz.bat bip.bop'(v) { ;;; }
  }
});
```

**Comment by ceremcem** [comment]
Reasonable... Thanks.
