### ISSUE TITLE
Access ractive instance within decorator? 

### ISSUE THREAD

**Issue by nhaberl** [ractivejs/ractive#3212]
Is there a way to access the ractive instance within a decorator to fire some event? 

I have a table and would like to open a modal window when clicked. 

The select2 decorator approach doesn't work anymore where instance is accessed by node._ractive.root 

Thanks!

**Comment by ceremcem** [comment]
Is the desired result something like [this](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSANCAzlA2uAC6EAO2kA9BQMZIB2AdAFbZIIA2AlgG4wN0JCFFGAoBrAPYBXQtgowAhtUI8EAWgC2EpAvYABbgAYGAJlMUknbEMXLVm7bua4AugF8suSCABKSldwIDNQSGiQSAnSyDFo67AAEALzxfnaBALKO7ADcADp0AgDuKf6qABTA+bmEHJDxAOQARtoAnvUYVcQIYewKNXUABp3VADxgAMwAfACiAB4KPQjxhAqN7AgjFBOTw4QjK2tLzTBsMIm5IACMFzt01fd7hGAICki3Dw-7MO+EH7+PYEmnDobFmmyePz+owhIQSl3BgN2f32gNh8RMCMh-1GFEI3yRe1xz1eWOhzSQLVJ-2AwAAxC9qGB4hoWjoVvEFNh4rC3G4CZ88fEImpqFxqGJziAWbFdDd+djHm8aXpgaDeeC3vKBUrgLC8IZ3G4NVTkYQdXrLobjVrCXiTYQaRQGWBeQTweTKbtwat1liRjKEipCOtJekWvEAGacGDWZlZC7xRqc5ARSU0iQkBB0AD6Aezl1dIFu8Xi1RLIxIkxpAYAwhEalF1RRK51yxQAz8Bh07oQInVKj3qtKsnUI1I6HYImVlLMAJQDv5PKwMbCCMr1DNZ3NZfPtZYwKQIWcEpfYFdr+q1+tZwh7+owCTFerxADU3MIswYaEI65VIIQsz1LOr6liA8RWNyYpiMgDAXMeg6EHyPYeJ0bIKP2uwsmhdR4ASuEgBGEgSBcGCgUmMAXC43Z-PhhESCYJgkWRCgwAxlHUQqtFEeM4xMRc5E8exuxUbsm45nmlyjroq6dEhbjHoQmAgNQ8CEB68STPukBgBIgQwPEC5qRIJwIDAdSXCQszxNgEhcEg8QwMgeQ9tQUgxsZdThMCNQwM51Swh5DlOfkbggG4QA)?
