### ISSUE TITLE
Event not fired inside each loop

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3213]
Reproduction: [playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSANCAzlA2uAC6EAO2kA9BQMZIB2AdAFbZIIA2AlgG4wN0JCFFGAoBrAPYBXQtgowAhtUI8EAWgC2EpAvYABbgAYGAJlMUknbEMXLVm7bua4AugF8suSCABKSldwIDNQSGiQSAnSyDFo67AAEALzxfnaBALKO7ADcADp0AgDuKf6qABTA+bmEHJDxAOQARtoAnvUYVcQIYewKNXUABp3VADxgAMwAfACiAB4KPQjxhAqN7AgjFBOTw4QjK2tLzTBsMIm5IACMFzt01fd7hGAICki3Dw-7MO+EH7+PYEmnDobFmmyePz+owhIQSl3BgN2f32gNh8RMCMh-1GFEI3yRe1xz1eWOhzSQLVJ-2AwAAxC9qGB4hoWjoVm43DTaYVOE94np2BJqLp4gpsPEAPqEMIcgmfPHxCJqahcahic4gFmxXQ3OXYx5vGl6YGgjngt56+WG4AMPCGdxuc1U5GEC13fVQwg022XB3xGkAKQAygB5AByDGsMGBKE4ADMWmUpWEYlkAJQc+KW-5O7OjbUJFSEdYanwSYomhCzOpGyuzWUgeKNMXICIamnJkipuIN52EeJZ-vxEYkSbeu0Ozaj7MDzYFvs4vF9mkUHlPDkrhlgWXuz648mU3bg1brH4DDruiI13ZarJ1ONSOh2CJlZSzNOVXf-N+RwRleqdt2ujtMsMBSAgaa7G4nQeJ0bIKNeX4svBdR4ASaEgHGEgSBcGBZiAzYwBcLgXn8GFYRIJgmLh+GEVRxGkfq5HYeM4w0RchGsQxuwuDB+RuJBhCYCA1DwIQB7xJMoGQGAEiBDA-qdMcpx1JcJCzPE2ASFwSDxDAyB5O61BSDAWkwHU4TAjUMCGdUsISOZekGfxIBuEAA)
This is actually caused by automatic event delegation, setting ```no-delegation``` on ```tbody``` or ``` delegate: false``` on the instance fixes the issue.

Is there anything that can be done to handle this automatically?

**Comment by PaulMaly** [comment]
Sorry for offtopic, but I don't think that multiple modal components approach are a good idea in any cases. 

In a real world, you'll never know how many rows you'll have. So, if each row will contain its own Modal component instance, I think it's too expensive and not necessary.

This approach is more laconic, cheaper and already works with Ractive: [playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSANCAzlA2uAC6EAO2kA9BQMZIB2AdAFbZIIA2AlgG4wN0JCFFGAoBrAPYBXQtgowAhtUI8EAWgC2EpAvYABbgAYGAJlMUknbEMXLVm7bua4AugF8suSCABKSldwIDNQSGiQSAnSyDFo67AAEALzxfnaBALKO7ADcADp0AgDuKf6qABTA+bmEHJDxAOQARtoAnvUYVcQIYewKNXUABp3VADxgAMwAfACiAB4KPQjxhAqN7AgjFBOTw4QjK2tLzTBsMIm5IACMFzt01fd7hGAICki3Dw-7MO+EH7+PYEmnDobFmmyePz+owhIQSl3BgN2f32gNh8RMCMh-1GFEI3yRe1xz1eWOhzSQLVJhGAwAAxC9qGB4hoWjoVvEFNh4jAJIU3G4CdCYPEImpqFxqGJzjhBGV6tgOAhlMh2vE9MDQQBKG6C-77N40tUahCzeL88FvXXQg3Abm8vCGFxmtwWqmfQg2u2FPCXJ38+KG9Ugk1JRLJBXrZVIZ2u3Xg-F3bHU4AUBlgfkE8Hkym7cGrdakxOjWK6eIE0XiiQK6UKwhyiNKmpIVVqS7akBlov-FSEdbSny8+LG2Z1Q0NqPOi6dv6NTnICLSseKieTZKGScgXZUkYkSaGllshR4cdNlwOv0uii73MUEvsH4DDqJw+j3Yn5B1VtPh4HvoKOp4ASeD1AAZhIEiqk0CgwPULjfkmwFgRIJgmJBs4wChsHwQ8iHgeM4xodB+FYbsLidAKdBuNqhCYCA1DwIQ2bxJMywwJAYASIEwqVImxynHUlwkKa2ASFw0YwMgeSJtQUgwCJbHxOEwI1DAUnVLCEgKRJSBSW4IBuEAA)

**Comment by ceremcem** [comment]
[*](https://gist.github.com/ceremcem/d70d501945acc35e069ebd8bec584402#gistcomment-2378821)

**Comment by PaulMaly** [comment]
@ceremcem 
> If your modals are inside row views (ie. inside {{#if }} blocks that are rendered when a row is clicked) then only one modal will be rendered at a time, regardless from row count.

Nope, because in my approach Modal component instance will be created only once, which more performant anyway. In the case, you described each row click will produce creating a new instance and each close event - destroying it. Well, think about it.

> The convenience with this multiple modal component approach is that we don't have to pass row variables around and template would remain simpler.

I don't "pass row variables around", I just use data-array in the same context using additional state property ```selected``` which just contains an index of the selected row. Modal component's body parsing in context of a parent, so actually, no variable passing anywhere. 

Hm, I don't think that my template is more complicated, let's compare:

// multi-modal
```
{{#each mydata}}
{{#with @local as _tmp}}
    <tr on-click="mymodal">
        <td>{{@index}}</td>
	<td>{{.[0]}}</td>
	<td>
	    {{.[1]}} {{JSON.stringify(_tmp.modal)}} 
	</td>
	<modal title="Row index: {{@index}}" basedon="{{_tmp.modal}}">
	    <p>{{.[0]}}</p>
	</modal>
    </tr>
{{/with}}
{{/each}}
```

// single modal

```
{{#each mydata as row}}
    <tr on-click="mymodal">
        <td>{{@index}}</td>
	<td>{{row[0]}}</td>
	<td>{{row[1]}} {{@index === selected}}</td>
    </tr>
{{/each}}
<modal title="Row index: {{selected}}" basedon="{{selected >= 0}}">
    <p>{{mydata[selected][0]}}</p>
</modal>
```

In my opinion, it became much more laconic. 

> Our working versions are more or less the same but the "not performant version" should work, no?

Yep, I'm not saying it's not an issue. That's why I wrote "off-topic" at the beginning of my comment.

**Comment by kouts** [comment]
@PaulMaly offtopic: I think that is a valid point, I haven't ever used a modal inside a loop, I always do it the way you describe.
I posted this issue here because this maybe indicates another bug in event delegation that needs to be addressed.

**Comment by ceremcem** [comment]
@PaulMaly should we move our off-topic conversation to https://github.com/kouts/ractive-modal/issues/3?

**Comment by PaulMaly** [comment]
@ceremcem I think we're done here. So, we've only waiting for @evs-chris reaction to this issue.

UPD: @ceremcem Perhaps I was too short because to write from mobile. I don't think that we need to move this off-topic conversation to somewhere. This conversation is useful also in the topic case as a workaround before issue not fixed.

**Comment by evs-chris** [comment]
There's nothing that ractive can do automatically, but setting `delegate: false` on the modal component _should_ solve the problem. There was a bug wherein the `delegate` setting for components was being ignored, but as soon as travis finishes doing his thing, that should be resolved.

Aside from that bug, the issue is that the modal is being rendered into the template, and ractive assumes that it will safely remain there. Any time managed DOM is going to be moved around, delegation should definitely be turned off.

Thanks for the report!

**Comment by evs-chris** [comment]
[Yep, that seems to do it](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5QdgVwDbIDQgM5QNogPT6LwAOA1gOYB0AxgPYC2+MAhjQC4CWAbgKYACARioAGUQFoARok7IAJuMEAWAKwgAugF8M2SCAAUAM2IdOdeAAIA7r0kk2ZAKrwevGJhbIAsnTkpeACK8hpwuXOb6MHR07GgWhmzsdDAAngCUFsAAOvBZXIb67CkkvHSGFrwAHiTJ7JgWALxNFgDkdJIAVrwcLRYAZH0WRSVlFgy+-o3NbZ3d7C1pOXl5437IvFRVNTB1jfGJySn6aQDcS+y8yJi8FpwFw6XlcsGhN00Nrcbwpua9AxbPELwDYsBhyRa5dh5QGvfQ4dRxBIcQ6nc6Xa63e7FR4Vaq1ervVrtLo9CHLC54naYHBZEAAJUSrh8ck8tPUeyRSVSxzOkPRvHOeSiMRp9MZfGZrI0HIO3NR8E0aUK2NG12Q5QAhNNiDDgXJegB+Cxq8qQIZgTiYREmcLwY6ZHIwXjsRAwSz4ABUXu9+AsRhtZjtq38mAywAshGstnsNDIACFonV2KwSDlPd6vb68pGACpgG7B9YWGhsfNpjOZix5bgsGC3eCYdiedZyZkhvbATS89MZ-DlitZ9i5-MWJ0ARxkTviAfM-d7VfYXx+lgA+iubHYHCvx5PeGv9IXeABJcEO+A9n1zn0L7O+gDC+djmLGEyLlvrxdLAvPFY9g7ydz6KEjbNrwravrw1KHie6hhlelbkkKzqupYwFNqgYFtusUEQTBmyUnU3a-v+7CaPBf43kO95OiwFwWCwFjAlYL5rDc+gsPAcgWCQiDsLcfGhEk5o3CWND5hCF4IVC7A1nWh57GhoHgaxOGsTBHbkSRAFmtBchoJplF5MgZoJFcvD6T+A6GRS2x1GanYGeSXaaY50mRgAopU3S8Tc7AjvJS62q5KwQap-h4SWqAHhB+G2VaLH+HEh6xficRrhuMZkNuvATpwTprvKkl-sFVEWAAYsgLAUMJCVFiw9TIHQLDPHIJXJcgezJogvBEQOJWRnSyFujVWz4hYox+QWEElU6LrDclo1Ur1855GRlm9i563XreuI1Bik21ZB42zBwfrpdGW6HpgBWuedm6xtluX5SuVAMHsV3LZeW1SZGo37f5EGfmJ35FYOd2ZY9u5rrQCkNuhLZYZBn2Zq5ka6jcFDOhcdaBYG8TJBYYC1uM8ApLt+K3euF0PTueV7i9XEfLjESLXUcTwKC5kWJj7DY3B30UeSgEauDW6089VB0PorPxRzDC8Gk-Og9ZADyJ3sFQ6MAApRCUOxHDL7Oc3E2QC1p0n0PAIQUK6LCSOsJmeNcFnK4h0m8Eg8usPbvBml15kleSPNmjz2OB6RhXEZRa2u6RyPFWbC6RjzQQJCg7CebZ07fLa+N1vQDD2FwkiyJwRTWGXYCMeY4hEzAJNk1dlMZWLOVQy9lhMzOQYQUrUfkrJ3NY2472A-8yVrpBiMWAa4fM5YKfBCw6f2uGs0oYdOAtICy-IPM6gnBYmgWJAc-d0P7CI5n+Kr6OQ2WIeh-OYn5KizTbd09Dcj6KHbhxC0LAWhxF-jASOVlyTr2GiA+Og5n6g1Rr6NWJINYkCiEkB4VAiaYBVlYeAOs6B6yKLQZszdqZZXFvTSWHJu76GJHMOIqCCFuCKGGO+c1LBILmFQRh6DsSYPqjgvButmEpGIVFOhHAGHCP1qcI+MCEEWDfllHi9tOA0BXEXMAa5SH3XIR-CWJA9i0lpPIl+pUAAyTUuIe2TI3QGHEuKQMsDLVyTjFFU10ZDT+K59BKK8RLAkFgRBgPnIqciv4ImRKidEmJsSvrKzhOWIJFgE49l9P6HOgZoqsTSh4iGMs1y5Jbu-J69N+ZLBAIgDEjYYBqKhCAXknCOCaxeMCfBhCjh+IKSuOItJJ6YERrSE2FgazIG6n7GA3Uj6R0JsTcwZMd7p3JjsFJvoukEWuiuUUiy95sj2PoBkpg+D4QuJxfQpsLCXKGLwQulULj2W4JAJQaB2CQBwMAV5zzDBvI+ZAAA7GgX2tI5A8CGQwH58BT4gCiOsIZ3zgWcE8HQCgQzXmCAAMzaGAJC2ktZEXiEqpIS4cKfmvIAExoBgFCrg7BYUgE0AiNFmK0DYupXbUIzxKgktpCIVFkAMVYpxSAGglVMCYBJaKGoPESDiCsCmPWVYQAsvJZSqFUrEAkBXJwVq9LGX8uZay2kjYUh0rQN80UBC2BlxSGaIZvyKVUtpJamg1raTaBMQCS0JBKo2sVcqyADqoUgswN6lgKQ3X6QaRYAAXuIDlVRbVKvtaq2k0b41cvpZGw+NBXSYGSIm-1FLKjQCpaKD2dt1giroNcNkaBMBQpXCIWeWRaQ1EEm4FttJT4tpADsqEPa3UMpefqwVbzaQirUWQWtry-kiDNVCidsY6C8UwNqgUmbWWijILwFIcg6C4Onf8ud8KQDbt3fu3Iur53vJnYCoNoKlXgveUKkV9VxVKvNa2ghGq-XJsdcK0V76h1MtHUaooprzV-qhcaulwGR0Ikg7eoFvaH1oCfYagDb7uUgHVTKml6xJC1j5QKhDpL-l3tpGAdFYKIULsA9h3D4h8PruHSR69UHaTMbdVoSNv7PnsaQ1C6QvNZyPto5x7E2HhNJEvaxg1L76MfrVd+mVkh2DwHEFWmtSqQMsshaKRdU6NDDtnfO8djVtNDs-SAAA62yIdkKVBzv-eWn2Wn10MvdSAPj5HkMgu4DR59dGsNKa-dKzT5hTn1Lk1ZsjggABsnmtDJbQI55z0GwD7tw9xu92QQCNubV+9tMBO1QFK320rXb55nWCcAJxvim1FfgGHMrval7p1pKcTQ3WLJXOLGKxN3CVOyvlSPYAe0y6BhMpwLychD5JBIGaEQh9akUDAK8oJh9JAxCSOCzbFh1iGA28tmNcbOIJosIIEQTnD50D4DAQwjUrBmmXkkQ+wbQ2+vgOYHqFhCOxgoFEHUEXGpUtHBQQj+g51BLiNDsQKgusWCG9KzIE3bRmidHc1w2a6Cg7NAAYnRUT4nh9HtNQ24d9gW2HCA+XZxEH+aLD48MCz+bBDIDopECQSoh9KdmicwAUnm6wBshhkh7eTBxTAdzeD6HEILtAwTs25sZ32w+DBQiyu1X5M0ggrvc-VywSoWu5A64sE5rnPO-t0GN5gIme7nvJJUNzy7zvKjg8h3D2HsOqAI5OMfZHGqmNlwI7WVHzUQXwAoPyt3OO8dM5J+Ne7ZPHevboFt5IzwYBSB24wXXLu83IG1Uz3gKhS+l-90jxjzHMgMFrBQTXC2A0G7GPXzX22RN7ct+9r1PqzShCL8CKQjVYyk8i+IVd0bfbCDJSoJ0DBK+B9U+pzTFmbjjYj6EaPQSXdKBd5biwe+rc5vcIzttzW3DU4B0DziS39vbZgFnpbY-muyt4JwNbM6RAnbJ7RDHH-1sX92AJ9OAp9ddfd59edXha539P9ddDcYAG8NNVt1szR5cW96A8d8caAcDF9GM1MNN3NIBMt7s4gl8pAV8iCxcc160SC3BgBMD818d4tDAWCWCM9H83AGcwdJcGx7AnRmsr9KAb8FBGCeCRcQ1awbE8DhsCDV9q1fZqCqlMgxDIB8cABOdFTQzQjgrPbgiZKXfg6Qv7GnEQ-QoYCQowwQgPRjS2KLcPOQSPaPQQN3V3F3Fw9w2PGw4bOwmxJHYwVAWuOsYAKwbXMAF7XidPa3TgsHE7B-PQpvS7AvXHYvfHXgEQdI9IhApApjdnDwq3OvRA9vXPcFfI7IzXPnRQI-co5AgA15Kog3MiJVHIPrFkJsEyGhNIC5PrK5NxYAO3LLFTR2MyOIQja4PdSFfYEYg7VwYY52eiEgEoTiJIM0FoIBYsQDVY9YmDX2NYuIZjLYhhFTLVOQP2C0TAKgFcG2bVAAahaA0RU3WNc0rTXwmW6lGPqj3DTXO2LUu2u2h2dWtSWziA+z71aG+2BHWO+M5SWzWj63dUsCuWeHWAoFol9imOdhaKuXMHsixJ6I2IUI6MyQiA4EqC6LxPxKuVJMllW1CE8G4SdD4Ga1Tl3nYB5ApMpMxEKHOKoB5n0BaGeO6DXwWHJMRM5PxL8ktCoGuDZJaDGLAl+ERCdgVl5HFKuThMpIRM5MM2XTqDXSJOXH0FJNFLVMuUAmpOSA-zpOQCoCbEQOdCmA+GpO+2eBNNNL60lIuJCCdH5Pc3WONNVNNI1PxK1MpLPQd0mPniNPYDJO6LVMHjeGLBjJpKtI5mQEDLVMAg2CsAtDEkdIsDJT+TdPdMuU9KoG9NlxaD9LiADI5M1LrPxKzKoBzLUSrkJHUOLJLMjAAHEHTzBkAyZuBLROAfYKh1h5ZmtxUxSSzB5mxOoeSgQ5AABBKKFoUIHiWIY0S4eha5SoO03gFgUY3iGTOIQBNIcs2QbGDJQ0y4Tsks3o++CwDUDUfQMcyWFnGUgAdTCIsAAB9fy3yyhDAZSAAJWA9bP8gCy4Xk50O8IvGxQaDgTAY4KgdYKPPyCweUe8y5RUDMkspsu3O4dgAAaR3TvOwqbLtJ5nzObBwBEHZH-IqFtPrwdMJDLMXP5PILlRYEWLcBFLjOwvxI2FQV4CZPYBZJXiwsEspNoubFQo9goD8kUHUHLLoBoPZOnMEuDJLM0H5AEsEsopYr4kJFktQHkvQrAGUvIukqYpErEokr3g0psvxNovotUvUqkpsu0vdO8vrM0vVIpNDMuXMEtmtgNNtGOH0quUAjLL5JaCLz4H4obJ6LLJlP5IGKsFw3WP9k8p6O0qCvGngAEKf2zkNOspGTD1wxOPnKlLiqqu1QWDwo9J5PaGuBgD4BXHlImJqouNarcD4H5K6sVNKoiqYgADVPB3jxp5AJqxkuYz1NFyq+tB4ErEzYrnR+TVrGrkq+tAJxrJq3hmgcqorMyCg90c0JyNYJw3AUgABlbc5EGATiloG4+q08f4c6xAS6qga61Ie6ytLkZ616447Vc8nYzWXvMNfMuUkfMgBYE6kspxJqoMnaykssy4HMOgMqNS5Qj4T6768UXgdycc6Q1GiUhcumQa4IZIXgFWJY7a-y+MsPUVdgAALXTR6pgvYExpIHZp+KcuwsHmhKqH2RZr5s5SmCCQyCNHWtlPlJXGFsqAWBPgO3qjZvTRuMEGRtOv0A1FWqWtNNSo2paAyqyv2MmRVLJryqtuaqlOAmYW5NquNp4qWNNzoGVqNHxpsR+u6j+oesBtlv5Jdo9jdpFJVrLOFA1lvO1vFKNrZOAG3khpSBaFWPtjUrhv-kVpTpjXTVwptquTLI4k4DrwuH5MBKKHWMEBNj8FYHRwLKc0VFtPzDtCjINrVPYo5X5JwDTyUMwHUA9vNClI4paG7siN7v7vPN7vtDOKHs7paC4tGxgAWHcqqQFpso7p9IASOzcDpo9gZq0qoBLjOU9MVhjvhL0vzrNIKA1C9uax9puv+rmGSCBreoyEYtvqut9ruv9ufvnpetfulPAw2FBKhq1A+BhvTvhsvp6KRugd8vbops3qJTFydDgoUP3uwsLpcBLsrPLuTu90yBrtoim3rpEEbsmhbs6IRvdLjvOUTpDR9WzpaAhN4HWJaCzthNyoMuvv1uocwZ5LSpNsy0yseKVLMi4ewvgZLI3srJYG3pgDQeuAwZspWrVvFpFo+Flp5vUcqDXuksAjFo5oAD4pa+H7zZzUA9gP776-aAbkgVzkBOLGNuLeKl6JGbKUG-RB5OA9gTsfGAAeeiMytCxSsAQ+TgG4m4-mZy8UwCWizgFS8G6NI8H4yWwxn4tumJiqusOsD4Q5LgY5HmO8SLKoNk+J2CKgVgI5HqaB7hyIC8s5RO7gZeuwlgYCR2i4jGrGnG0MTJrJgunkrp7Gmgle5C9x-p9Ui+xmiZ-EmABp7+EenunpiemeUceZrupZmgie0Z6etZ4ehe4OtxnZ8ZmZqRmZyQGiMgM+5ys5yR65tU3SsyMx-Cs6nG767bOQURVp9p9G5ATG4ZqpRWZ5wS35-5np45+5nS2pgK6ZzkzQQ+zuk+k5mFuFk2K2wENwN478OF3Kgq8wYgYqzFkarJcqssvq9qvcIa+AYhb4S4PRgqnmbR9NcKklhGweLkVizbZKixjqPGt572367+uxmABxpx4bFxvWZRnozx-Qbx3x8JiwQJuSkJvycJyJ6Jw2mm4y7iWsa4FJsp1AHABJwBk1DYZJjJiwExjlviI0fgvV5rdiQ141pJlJzlDIP2LVmO5+Tktxa1vCtaRUeUOcX0MJROWCbZdrXZDQXkPO3IeAfJ1wWgRgGoYESc16XwTwPYBNiUDN9MpYeAJiCwbN2XU2PIS4VO3wfB84C4W5NEs0AAA0FHYH8aoyMc8lBG9V8grV4H8fwFbabf8abFHPiLcAaFpEEFpCMabbyEHfzGainchDdkHZgAXbdnJFnaMfTV7b8lXekiXZ3cwMu23bAF3bXebYPdxwLOPdPb3ebfwGTBvZnfvbnbkEffPY+ZSDfbyGAGADSNLDGF3VohYG6x-fx1CIwv4BH0zfqkUXYELm62ndveXcKtX0nTHZAAYBSFWClC-aQ-YFfZ-f4Fzs0G3dfcQ-3YI+ACoDoq0BI-vbI8XdvfXfw9w7dh-eo8EFo8yGAAAClbqVYAA5QB2pKPO4TpODkgdNlkZANIbrKsRjs90j1j6Sfx7DjqZjdDukfdesGE7jojn4hD7zKl9Dn9lcCTqTzwQz3Dy5PIS5fxkgIx9jmj7rXthz8j6SOz-ANT5T7dld9zn9-AcDsAED4AfAA8sSBDhTu99gD9m97d7t3d+tiyPIHEs8ckTDtTllkkmM0Ut2akwRszwuCz5AbKi2skaSNaVaZL-DoD3ExjzDtolgM0GkKL0UMXOgIZRVQjErYzRDtr6IMlMlTr2kbrwb2tPr2kdronYbkAbr6b3rxj9Qc4ANxYdgJVYVKAEAGLyty1iw4gu7Mbc4EdsHQQZIovRxMCXkPIE-PNMHc-bGK79gVQu+ObHITQelIAA)

**Comment by kouts** [comment]
Thank you @evs-chris

**Comment by kouts** [comment]
@evs-chris if ```delegate: false``` is set to the modal as in your example, does this mean that this setting propagates to the children elements and/or components of the modal?

**Comment by evs-chris** [comment]
Yes, the setting propagates to children, unless the child template happens to be yielded, in which case further template should resume using delegation from within the component if possible. It's a bit muddy to explain, and there was another bug involving handling yields. I think that's sorted now and things should work as you would expect.

For instance:

```html
<div> // delegation target for outside
  {{#each things}}
    <noDelegate><div> // delegation target for inside
      {{#each others}}
        <button on-click="go">go</button> // will delegate to the inside target
      {{/each}}
    </div></noDelegate>
    <delegate>
      {{#each more}}
        <button on-click="go">go</button> // will delegate to the outside target
      {{/each}}
    </delegate>
  {{/each}}
</div>
```

**Comment by kouts** [comment]
thanks @evs-chris this is good to know, do these  ```<noDelegate>``` and ```<delegate>``` pseudo-components actually work? Never seen them before.

**Comment by evs-chris** [comment]
No :smile:. Those are just placeholders for components with delegation on and off.
