### ISSUE TITLE
context.hasListener() example/usage

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3219]
## Description:

Currently, `ractive.hasListener('foo')` [does not behave](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7tCANpKQDkAIwD2SAJ6CsnbjwC2AB16UeAgAaza3ADwAzUaNKiCAWmGUYAXnYgLAL1sA+MH16idAegOinpbgG0OgCEpqakYJS4pLz0uDxEMKRhTlq6PsZmFta2BCYIAB5x2iAubh7ehqlBoeGR0bHxCInJpqlc2kE+ZbzuXt2Bg51DurWkSKII0Xm0EZTMMcXNCEkpWuoyHdSiSvkEtLjQabQ+AlR0TAgAdIUJSGzHcghKKmqk6jrCAK60tCaZpmosWoAGsbHZLM5gMAnNt9s1aBgMF5vr8TE4No8-gQYM0kCsBHovgQLiYWABKDgdIb0PSkFi0MBxK71AAyS0SLBElkE5MpWMClF4K1oXO2uyI+zm0RM5ksViuisWTUSwV5AsRWIwxww5K02C0JiO1NoDkJxNJBBYdAK-JN3CFIq5rl6Rj0MB2pAcar1Ju1HX9uswQA) as [I expected](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHRIIBmRArgDZm61hG4CiNAHZkABAF4RjFoPIUA9oIAUCIWQByRALYIAlMAA6gkSKpEYkwQG5DxxkYlSZlBYqJ6bxkTARkWMI0S0omIhIgDsAAwiAGTRIoGCtBSCDAAeAPKMyqoa2joiAHwiALQAjNZGIhgVxt6+-iJkYBRcJHKaAA4KCMIxcU0ttG2d3cJBCJ1sRGR0mrSMyUiKdjoV1YaGgggA7iLEsjSKBoL6M2yQIgDkAEZySACel1gbZDOT0wgXAAYvpwA8jDkchECmK1zMYn0IHBAC8oQUwAg2Gw5H8APSAuRFU44sh-ACExWKIh4uBEbBaMy25iJBV+eMxIMEYIhUME3VSlPhiORqIxQLpeMJxNJ5MpPQQNOKdJOZH+mIRSJR6IVuLVco16oJRJESDkCDJ7NEPBoYtwVMlJWlLy+z1lwy6W2EuGg9MxF32lBotAQqSpS2O6reHSmM2+f2uLFeCiZxRIFJIAGtIdCzPDgMACm1hD0yBgMOjI9HBAVbfTTgpvClJRdHLIXO5ZeqKIwRIoBlxSQJc4obmZLjpG+rcUQ2JKyL2HaNjbxY+CYGJaEuzRaYPiB+WNRhN9um3mdC9sC8FK697Da9J60pyKkh5qyKPx72eSjJDB2iJYeuD3vd6ddxgOiYEAA): 

```js
new Ractive({
  el: 'body',
  template: `
    <foo on-bar="baz">hello</foo>       <!-- has listener -->
    <foo on-bar="nonexist">hello</foo>  <!-- has listener -->
    <foo>hello</foo>                    <!-- does not have listener -->
  `,
  components:{
    foo: Ractive.extend({
      template: `<button on-click="bar">{{>content}}</button>`,
      onrender: function(){
        if (this.hasListener('bar')){
          alert('component has on-bar=... listener!')
        }
      }
    })
  },
  on:{
    baz: function(ctx){
      alert('hello from baz!')
    }
  }
})

```
...gives the following exception: 

```
Uncaught TypeError: this.hasListener is not a function
    at Child.onrender (script.js:12)
    at Hook.fire (ractive.js:6923)
    at Array.<anonymous> (ractive.js:17905)
    at flushChanges (ractive.js:5792)
    at Object.end (ractive.js:5689)
    at render$1 (ractive.js:17938)
    at Ractive$render [as render] (ractive.js:17969)
    at initialise (ractive.js:17866)
    at new Ractive (ractive.js:18571)
    at script.js:1
```

## Versions affected:

Edge

**Comment by ceremcem** [comment]
("expected" link is updated, this comment will be deleted after its notfication task has been executed)

**Comment by evs-chris** [comment]
`hasListener` is only available on contexts, so you'd need to use the context passed into the render event. That context still won't look at the template for the component, but it [probably should](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7tCANpKQDkAIwD2SAJ6CsnbjwC2AB16UeAgAaza3ADwAzUaNKiCAWmGUYAXnYgLAL1sA+MH16idAegOinpbgG0OgCEpqakYJS4pLz0uDxEMKRhTlq6PsZmFta2BCYIAB5x2iAubh7ehqlBoeGR0bHxCInJpqlc2kE+ZbzuXt2Bg51DurWkSKII0Xm0EZTMMcXNCEkpWuoyHdSiSvkEtLjQabQ+AlR0TAgAdIUJSGzHcghKKmqk6jrCAK60tCaZpmosWoAGsbHZLM5gMAnNt9s1aBgMF5vr8TE4No8-gQBBwOkMYM0kCsWHQCgBKPEjTr0PSkUm0ApXeoAGSWiRYIksgnJlKxQ0ovBWtE5212RH2c2iJnMlisVwViyaiWCPP5nQw6s1+I1xww5K02C0JiOOocAj0XwIFxMDIpVOGtEFws5rl6Rj0MB2pAcqoNOu13G1+swQA).

**Comment by ceremcem** [comment]
I'm using my `hasEvent` method to decide to add some other abilities to the component (or remove some other) `onrender`. For example, if my specific component has `sync-topic="foo.bar"`, then there is an actor is created to communicate with the application/dcs network in realtime. That happens on render, anything unrelated with user interaction. That's why `hasListener` has to be available in the instance, not only the context. Would you consider this change, or should I keep `hasEvent` method for this purpose?

**Comment by evs-chris** [comment]
My only issue with adding a `hasListener` to the ractive prototype would be that I would expect it to look at events subscribed with `ractive.on` and not/not just the component template event listeners.

As of edge, I've fixed `context.hasListener` to work with ractive contexts (as opposed to just element contexts), so my example above should work as soon as travis is done doing what travis does. I've also made `ractive.getContext()` with no args return a ractive context, so you can use it outside of lifecycle events e.g. `ractive.getContext().hasListener('myevent')`. Does that get you closer to where you need to be?

**Comment by ceremcem** [comment]
As of now, `ctx.hasListener()` works well: [Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutTAno1YACALzDi5anQQAPMlyQAKYAB12qsgtYAbIgsjCABus2aAPCwB8psmbLBg-Cgh1IMGYbfuOAxBQAzYVxmBAAFGAYWD287OKUkBAVyZGEiYR0KXAVOGABKWM1HV1wEGI04+yV2BjJhROSFJDSMrJyEfMKHYAB6QPL7cx7rWyMsWw4KdgoyQwCAV3YpDiVyWTy1Cs1A4VWyWVowIlwAGTauDqUAcjBXHQYrvI2usjAs2lKya5CmcMiWK5YYRkGDzBB5ADcsQwtmwtiQ+iIc0Wy3YSmeWxBSXmMHYwk29k0Pz+UTmRB0pWhsPUGAKGnYnAA7hJSJQaCpbK5DFcAEYMJD8QG2bQsPQGYyxcwCIQsYQcAC0tx091EqhArw6CDVVgAKm9cMIjgb0plshcYENpcwRpipYJrbr9YbjsIaq0zblLfbWDYKmMvBUOIYCXENTAEMilpQVmsMYSyOSOl8bghBXT7DCKpnaZggA). 

Thanks.
