### ISSUE TITLE
[Question] Is there anyway to call Ractive event from HTML DOM

### ISSUE THREAD

**Issue by xilanhthanki** [ractivejs/ractive#3222]
We recently upgrade version from 0.7 to 0.9.13
Before the upgrade, everything works fine.

For some reason, after using document.body.appendchild then all directives on-click not working anymore. While onclick still works. Don't know why.
The document.body.appendchild is written in decorator. 

I tried in your playground but everything works fine. So maybe the problem come from old source code.

Didn't detect any problem. So do we have anyway to call Ractive event from DOM event such as onclick?

Thanks :D

**Comment by ceremcem** [comment]
Is there a reproduction code available? 

Besides, AFAIK, you shouldn't manipulate DOM by yourself, you should let Ractive do it for you. If it works in 0.7, then might be a bug with 0.7 :)

**Comment by evs-chris** [comment]
Also, are there any errors in the console?

My first guess would be that if you're manually rearranging dom, you may want to disable delegation globally with `Ractive.defaults.delegate = false` before your app instance is created.

**Comment by xilanhthanki** [comment]
You're genius. It works like a charm.

The root cause is the line code document.body.appendchild. I commented it then the code works fine. But there're many functions behind it so I have to keep this code.

So your suggestion is great. I can apply it locally without affecting many things.
