### ISSUE TITLE
Investigate allowing yield to include a context

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#3223]
This is a placeholder so that I don't forget about it. Per a gitter conversation, it would be nice to allow `{{yield ${name} with ${context}}}` in addition to allowing aliases to be passed in.

This could probably be achieved by having the yield manually wrap its body in a `with` block that tracks the context associated with the yield in a special-cased way from `resolve`. Accessing the surrounding context from the yielded content would be achieved using context pops `^^/`, which would hop over the manually managed `with` nicely. This also may not pan out.

**Comment by marcalexiei** [comment]
Hi,
according to: 
> it would be nice to allow {{yield ${name} with ${context}}} in addition to allowing aliases to be passed in.

we will be able to do:
` {{yield staticName with ${context}, ~/foo as bar, function as functionCustom}}`

Am I right? Thanks

**Comment by evs-chris** [comment]
Not as it stands right now. Partials, yields, and `{{#with}}` blocks can supply either a context or aliases but not both.
