### ISSUE TITLE
0.10.1 - context.raise() produces an error when event not found on element

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3226]
## Description:
context.raise() produces an error when event not found on element.
This used to work fine in 0.9.13.
## Versions affected:
0.10.1
## Platforms affected:
All Browsers
## Reproduction:
[Playground link](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYD2AJmgHQBWAjgK5owCeLBgFsqnHvwC0ARhZSATCwAsLIQEsAduwJ4wpCtSpYktANZlUYFgCN69FFhhIytRpuFUbdh06oBmFv4A7KIYHrb2KI5kKhpaIAC6AL542JAgADyMqgBuAASqjAC8ADogKEgwAOZoKKUAfOlUWdl1xept6Ri0MKpkKPlFpehCZMjopbkofGRoJWVoAB4oVI60KDlo9R3NuVh8CLOlAO4FKGCQigCsAAxkC1vtKJk5ubTIGBhz5upoCLnfvwkzAAZkguAh+kIrJcJkgMBIGAhkBRDvMsAB9RHIjCbECtR7FJ47N5wz6lAEICRgNBILLqSqvegjYy1PFtQkcp5gRSvd5kkAUiTrFAHV5cGAYegwCRkegadAwCb0dQIhCqUxzAACZ1UGBYKHolUqBwAFABydAYrFOHFmgCU9QAKph+gBhehIm1oRrc-GcxrNP21IkvEkfL5IH6U60oh6cwnPPJh-mCmyMPi5KHXf4oGFsgnBhPEvlzRESDBCaRyOOF2vpMh1R1gXX5DC5JCTF2Mz0oxoN9m1hNNHJB-3DloDoeBgcBkcdcf4xpdHp9Oq4fDwABKLI2LGYDEcBolgg92LQuUKuWBXHUa1UypNvzQQjQ6hQOG7Z7twDauT-uWyCpPxtVQrFFS8ABJHwOF83ztFhgQ0RhzRYQUY1teDEIlFATTtABuX9-0AmBcjASNGHA3IoKfWCUEwpCUMFYUDntBDVGw3CCPUf9gIoUCDhPHscRNH9uJ4-8DSNA5ICvJAEBxQi-0SfDFN4jB+NYB8zQwMB6COTQrD1dC0DND9r1vdYH2-VSeJ1PVqhQd030WHD0I0lgHJNa47XgxxdTQc0dL09QACEMHdISTJUsSlOsBi7J8rieNUYETWMi9L0iHhrJi8S3LA1haUYV0+XNYz7SS8S-3ygTjPNZtmAq1TEl+HFRKqv8UrS08QIKlgyPC0qzXKnz2o6niatYOrtN0o4mtyniWvktAxvGtT3KKkrSTKnqUXydR5vGxJmtUsj1Ao1hJONNAto+HbIsYUy1LQaKeJgGpxW41bxPQCpGGCmTzLvKzvvGyaWHoYFUpm4LrCM3aMMqqrjtylGUbaYjclWdZsnPS8fiOXJtzvXGRMI8oqhqGSzQAYgphzTPJ59RlQNBqbp5mxhMnBCMYVAkBksbCUtFBMQRtnJhgHhCLR-D11oeBNVUEYpX6cUEBNUpdHISgaCMUxzDOaxwm8ZxXBPERPAiKI-ACFhgloD4wi8SInBiNwPlKaLBHFSVpVleVeFyYBaF9qUZID5yYDwxIQESIA)

**Comment by kouts** [comment]
I have managed to resolve this by adding a ```ctx.hasListener``` guard to the decorator.
[Playground link](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYD2AJmgHQBWAjgK5owCeLBgFsqnHvwC0ARhZSATCwAsLIQEsAduwJ4wpCtSpYktANZlUYFgCN69FFhhIytRpuFUbdh06oBmFv4A7KIYHrb2KI5kKhpaIAC6AL542JAgADyMqgBuAASqjAC8ADogKEgwAOZoKKUAfOlUWdl1xept6Ri0MKpkKPlFpehCZMjopbkofGRoJWVoAB4oVI60KDlo9R3NuVh8CLOlAO4FKGCQigCsAAxkC1vtKJk5ubTIGBhz5upoCLnfvwkzAAZkguAh+kIrJcJkgMBIGAhkBRDvMsAB9RHIjCbECtR7FJ47N5wz6lAEICRgNBILLqSqvegjYy1PFtQkcp5gRSvd5kkAUiTrFAHV5cGAYegwCRkegadAwCb0dQIhCqUxzAACZ1UGBYKHolUqBwAFABydAYrFOHFmgCU9QAKph+gBhehIm1oRrc-GcxrNP21IkvEkfL5IH6U60oh6cwnPPJh-mCmyMPi5KHXf4oGFsgnBhPEvlzRESDBCaRyOOF2vpMh1R1gXX5DC5JCTF2Mz0oxoN9m1hNNHJB-3DloDoeBgcBkcdcf4xpdHp9Oq4fDwABKLI2LGYDEcBolgg92LQuUKuWBXHUa1UypNvzQQjQ6hQOG7Z7twDauT-uWyCpPxtVQrFFS8ABJHwOF83ztFhgQ0RhzRYQUY1teDEIlFATTtABuX9-0AmBcjASNGHA3IoKfWCUEwpCUMFYUDntBDVGw3CCPUf9gIoUCDhPHscRNH9uJ4-8DSNA5ICvJAEBxQi-0SfDFN4jB+NYB8zQwMB6COTQrD1dC0DND9r1vdYH2-VTOWI14UAWC9JmbPVqhQd030WHD0I0lg3JNa47RUsTxPyYETTWBYWDIjAABldXQH4YHNHS9PUAAhDB3SEkygtE0LQsilhHF1NAUt0-TMuys97S4grckSVTEmsBidQwIK6v-VRwuMi9L0iHhrJC8SfLA1haUYV0+XNYzatUnjRoE4zzWbZg5uGxJfhxfKCu6iLTxAsborhKbSRmg6UXtIb6oWi71KO5btIq9b6s2+S0B2m7FvGxhJums1eo0F6CsajbVLI9QKNYSTjTQU6PnOnLGFMtS0GCniYBqcVuM+8T0AqRg0pk8y7ys3H6u+lh6GBcKnrS6wjLu3LOtC0GeNB0G2js1Z1myc9Lx+I5cm3O8+ZEwjyiqGoZLNABiSW3NMiXn1GVA0Bl+WVbGEycEIxhUCQGSdsJS0UExJmZIGzYxI5-D11oeBNVUEYpX6cUEBNUpdHISgaCMUxzDOaxwm8ZxXBPERPAiKI-ACFhgloD4wi8SInBiNwPlKYLBHFSVpVleVeFyYBaFzqUZILzyYDwxIQESIA)
Nevertheless, I think that this is either a) a breaking change or b) a bug.

**Comment by evs-chris** [comment]
Definitely a bug. There was a missing test case for missing event listeners that let it slip through when adding `<component on-something="..." />` support to `raise`. This is now fixed in edge and v0.10-dev. Thanks for the report!

**Comment by kouts** [comment]
Thank you for your efforts @evs-chris for evolving and maintaining this great library.
