### ISSUE TITLE
How to...

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3231]
To put it bluntly, I'd like to make something like this:

    {{#each items}}
      <li class-active="isLinked(@keypath, 'selected')" on-click="@this.link(@keypath, 'selected')">... </li>
    {{/each}}

    {{#with selected}}
        ...
    {{/with}}

How would you advise to do this?

It's for the example here: https://dagnelies.github.io/ractive-examples/editor4panes.html?url=content/linked_item.html

**Comment by ghost** [comment]
I'd do it [like this](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSANCAzlA2uAC6EAO2kA9BQMYD2SCAdAFYCOArgjAJ6N0C2FNpx4BaAMyNJARkb8AlgDsWuALoBfLIXgAeADZKA1gAIYCPQF4AOjkLc9CbGAQJCN42DMAza0VLkqfgBDAA9qJGUAI1paQmxCGCCScOUBCmjY+MSSCklJAHYabGx0mLiEpLklPmKbAD4rRX0jU3NfePtHZ1d3TwQfGzBiMkoKYLCIxgzy7JS+WkFprKTcqUZC6mLSzIqSUUJnfiYFVNqQBqaDRRM+nwByIf9Rr1pFOMYUGJQHJPlsecEm2wAH4vEEFHpuBYAGq0PSEILyMx3VqWO4dBxOFyEFF2EgICx3QgIEKEIrYO4XRo6JDyABuxnkSF8CJgaDc5x0FFpdKpTWw1Bg8hIhEZzJsxP4JD0QWJ9UaVkINPpxmoMuKvjoelE2H4ogALPLFIrFTp2HpVersL4DPFRCgYLR2CQjSbCMBgABiBBBahgYz42jShDqdQKtwR5qWoIamy2wj2x3O0TySXuNUx7CiX2EekEmzYcwIajEpDGCwV4wAASUDBC7leojV8mohl8VYOf0YhcIAAp0UWS8g7hhq7WSQBKeoerxI+KKcEh9TGD3qwgLo6hrkGKkRj0UH1+0Ph00Uc27rk8i886OxkBanV6w3nE-ur3yLzGQsOIdlgCElaKOaejHsaEamjKkTmHUABic6ihuCDbkEUF6Lubo6EoJDsKKGZ3i8MB6nQbyOno7h0kEeicL4HqBsGeDfsWpaqIws4wPOi7HiAxgUOhkaQdBAAyMYIYuyGoXxppYTht7WjYBFEa8CRwuRlHUTYtEIEGDgMYOzGMGuiFcTxfH7h+oGnle4bKgyeFyfecKPgaroRgAKs4xhILKQSQK+OgkGYdQegAUgAygA8gAct2CRKCgH7cL2nbYKOQF6Hoo4AEwTluFABQgF7cvSFxcgKQoinymA4PAFEwKYOZ5uWxiKAgADuxgAEoNXSCC9sA4asuykDGHcnqDa4I4DQgUoysSw2jZK0qyggk1gV5CLDf1YHGDtX56cgw1pRlr50Q4w14FtbqKmxHFHMNNgAIIGNQCA2Bgr6KoZi73SAADqrwMDAMqKEg2A2K+miXeBhA3eu33GDYABCtCRG9H2EF9d0IyAACyQRAwg3Dg2BiqQ+jsOIT9ADCYD4wYr2YOjmMID9D2KGgZEgBDqjhmGijqBOADcVXUPA0RINwK7hpEvqGA6Tog02cK0DAkDei4gvhicojOPIKBDJA0gAAxGwApJrYEvG8ohghC3CQLC8KImYFt82AmVS2BWoq8Nnr5JlACcAAi4j6q7IDqEAA).

```
	<div class="col-sm-4">
		<ul class="list-group">
		{{#each people}}
			<li class="list-group-item" class-active="selected === @index" on-click="@this.set('selected', @index)">{{firstname}} {{lastname}}</li>
		{{/each}}
		</ul>
	</div>
	<div class="col-sm-4">
		{{#if selected !== null}}
			<label>First name</label>
			<input class="form-control" value="{{people[selected].firstname}}" />
			<label>Last name</label>
			<input class="form-control" value="{{people[selected].lastname}}" />
		{{/if}}
	</div>
	<div class="col-sm-4">
		The data:
		<pre>{{JSON.stringify(this, null, 2)}}</pre>
	</div>
```

```js
var ractive = new Ractive({
	target: '#target',
	template: '#template',
	data: {
		selected: null,
		people: [{
			firstname: "Alice",
			lastname: "Wonderlands"
		},{
			firstname: "Bob",
			lastname: "Marley"
		},{
			firstname: "Charlie",
			lastname: "Angel"
		}]
	}
});
```

**Comment by giovannipiller** [comment]
On a hurry and from mobile, so I might be missing something but, how about this?

```
{{#each items as item}}
  <li class-active="item === selected" on-click="@this.link(@keypath, 'selected')">... </li>
{{/each}}
```

**Comment by evs-chris** [comment]
Was about to post exactly what @giovannipiller said. If object identity won't work for you because you're not dealing with objects or you have the same object multiple times in the list, you could use `readLink`, but if identity works, that's by far the easiest route.

**Comment by dagnelies** [comment]
@fskreuz : although this possibility works for the provided example, it becomes problematic once you use structures like nested lists or trees. 

@giovannipiller @evs-chris : that's exactly what I did first. I still find it the most intuitive. Sadly, equality don't seem to work on linked objects.

**Comment by evs-chris** [comment]
It _should_ work, and does in a [simple example](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOngIYxq70B8BA9CaW7QHYCCAZwDGMYgAdclGvVwIAtpIA2DBfXK4AnpIR08CAB65OYXIpXsBtXMGABiBA1FhKCxcIwYbrXETJyAHt+AFpRFWJRAGsDAAEAOkj+aIAKOOiEXXUwLHIAcmEEFQRRBSR8gEpNCIZhYWoYIIB3clr60KKSsuQDBPJqQfIAP04u0vLrQT9bewT+IO9yOf4GRQRvX1suHj5p+05nV03p33sHYgAzcnGepG9z5uJcN1vyk+3drdxV9chyAjEfiSACuMlIDBUIP09BWaw2PhA5E4HAARjAUd9+CDFKiEDB-oDgWDyBCoTCQCtFojkXtttwyHS7MBOE8Xg8WVcTlwxBJpGwQDhhPB+AhWgAlFy4MgIVLAXy4Jgsf75ByK5gIXD5LAKpSqdQIFVqvVqBTa3xIdQMf7y07SjzCf4AbW+s3Iv0NBSCMAY-DQ2vdQX+ACYAIzkbCuuzu+EqhiSVQIAMLf4AFnDkbtbo9KqKlv4yaD5FTAFYAGwRnVZ6M5gqouoIesqFSF-4Vnx2gC6vg7GEqgpAongCSazUg-Be4TAxBUSFSwf4AGpQ5Vlr56zEUE0QfwkOEgipvf8HJcAJxns8AbgEHYEI5aCTeyDX0w30S3QR3e9EB6P5AcSCAde-AYJgQA). Is there something more involved?

**Comment by dagnelies** [comment]
Thanks. `{{. === ~/selected}}` works indeed. What I tried was `{{. === selected}}` which doesn't.

I guess I ended up again in the same trap as #3193
