### ISSUE TITLE
IFrame on-load does not work unless Adblock is running

### ISSUE THREAD

**Issue by clarkd** [ractivejs/ractive#3233]
## Description:
Yep, you read that right. We're seeing an issue where the on-load event for an iframe is not fired unless Adblock is installed & enabled in Chrome.

## Versions affected:
I've tested this was Ractive 0.9.13 as well as 1.0.0..164. 

## Platforms affected:
Google Chrome - tested on v65 and v66.

## Reproduction:
1. Visit https://jsfiddle.net/FarWn/165/
2. If you have Adblock installed & enabled, you should see "loaded" be logged into the console. If you don't, you won't see anything logged.
3. Visit chrome://extensions/ and disable Adblock/Adblock Plus
4. Refresh the fiddle, having now **disabled** Adblock, nothing will be logged to the console.

Seriously confused by this one! I presume Adblock is doing something to interfere but confused why it only works with Adblock enabled (and not the other way around)...

**Comment by MartinKolarik** [comment]
The event isn't fired because there's no `src` attribute (or maybe it's fired too soon, not sure). It works ok when you add it: https://jsfiddle.net/FarWn/166/

**Comment by clarkd** [comment]
@MartinKolarik Thanks for the quick reply, that's intriguing. For our scenario we're not using a src attribute so not sure that's a workaround, and of course it doesn't explain the interaction between Ractive & Adblock. Any thoughts?

**Comment by MartinKolarik** [comment]
So the event is fired but Ractive adds the listener too late, that's maybe something that could be fixed. Regarding Adblock, it seems it fires another `load` a little later for whatever reason.

Why do you need to wait for a `load` event when you don't use `src` ?

**Comment by clarkd** [comment]
If I recall correctly, you have to wait for the load event to then access
the document.

**Comment by clarkd** [comment]
If I recall correctly, you have to wait for the load event to then access the _document_ object.

**Comment by clarkd** [comment]
@MartinKolarik We've added in a workaround for now (use the native onload event) but it would be great if this was fixed in a later release. Thanks for your assistance so far.

CC @krityan

**Comment by evs-chris** [comment]
[As of 0.10.3](https://jsfiddle.net/FarWn/182/), load events are not deferred, and as such will fire if the frame is loaded immediately when it hits the DOM. Note that you also need to either defer rendering by not supplying a target or subscribe to the `test` event as an init option in order to have the event subscribed on the ractive side when it fires (meaning that the event fires in ractive, but there aren't any listeners yet). Thanks!

**Comment by clarkd** [comment]
That's awesome, thanks for a quick turnaround. We're on 0.9 currently but I'll check in with the team on when we are upgrading etc.

Thanks all!

**Comment by arcman77** [comment]
@clarkd  I'm actually getting this same issue for just a regular iframe and attempting to listen in on it's native onload event. I can't figure out why adblock  would allow it to fire properly and then turning off adblock results in the event no longer firing

**Comment by clarkd** [comment]
@arcman77 It's not clear to me why that happens but it's definitely something that Adblock does. I guess iframes are occasionally used to embed adverts so might be checking for something along those lines that causes it.
