### ISSUE TITLE
Proposal: Support shorthand event chaining in the template

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3237]
## Description:

Currently if we want to trigger multiple actions in the same event, we can define them in the template as follows: 

```
<button on-click="@.fire('pushHello'),@.fire('pushWorld')">push hello world</button>
```

It would be awesome if we could write the same chain as follows: 
```
<button on-click="pushHello, pushWorld">push hello world</button>
```

## Versions affected:

Current latest (0.10.3)

## Reproduction:
[Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gHYIDuABAEoCGAxgC4CWAbggBTAA6B7tCANpKQDkAIwD2SAJ6CsnbjwC2AB16UeAgAazapUgB4ArrwB8W7t2DAAxAhphS8iUlWVSlXKXoKMGU7TO1dXnojC08EeW9dAHogky4-BIsom2owb19owzj-XWF9WlpRAlIigFpqIOoAawBedhBFfVwwAAk+XlF6o0bm0jB20Wi8gqLshNz8wuKyivpquoamsAB1URheJC6eu2I1jaHJ0YzhqZKCcsra+oABADoAM3oYVkFttt4OwQBKLFI7x+eLFeS1W6yQ3y2Sz6A1IuzBBxGBDG3AmiLOFzmV0WzXeHSw21BG0hvX6H1EsL2SFIuHoSl4CARUzG6hk8SKAg48W4bwGAnu+gIdHoRRYdAAHl9Of45GB6LhbtsgQ4nLRKNIhKTPl9fNhfATKXyBUKReLJb4ZXKFUslY5nOrBHCNhCubQfPFdfEVZQOb5lc4BABter9CT1AC6Wjd0oIGC+mCAA)

**Comment by dagnelies** [comment]
IMHO, `<button on-click="pushHello, pushWorld">` would be a little too close to `<button on-click="@.pushHello(), @.pushWorld()">` which has a completely different meaning.

**Comment by ghost** [comment]
Ractive already supports 3 ways to do events: proxy (just names), expression (JS), and the special array form as a compromise for both. I'm not sure if adding another would be beneficial or if it would complicate parsing/confuse understanding of expressions even more.

**Comment by dagnelies** [comment]
Indeed, I forgot that this syntax is already occupied by https://ractive.js.org/api/#on-42

**Comment by ceremcem** [comment]
@fskreuz Confusing part for me is: Why can comma separate expressions but not the others? 

@dagnelies I couldn't see where it is occupied. Can you quote it?

**Comment by dagnelies** [comment]
The example `<button on-click="clickedproxy">` invokes the proxy event `clickedproxy`

**Comment by ceremcem** [comment]
So, how does it interfere with above proposal? 

```
<button on-click="clickedProxy">...</button>
```
will invoke `clickedProxy`, where 

```
<button on-click="clickedProxy, clickedProxy2">...</button>
```
will invoke `clickedProxy` and then `clickedProxy2`. I can't see the conflict.

**Comment by ghost** [comment]
@ceremcem In some cases, under the hood, Ractive wraps the syntax into an array and spreads it as args wherever it ends up in. One such example , iirc, is [plugin arguments](https://ractive.js.org/plugins/#using_7). The array proxy syntax is an explicit variation of this, where the `[]` are actually visible. Then  there's regular JS comma-separated expressions (evaluate each, return value of last). An example of this is the multiple `fire` in the OP. 

```xml
<button on-click="clickedProxy, clickedProxy2">...</button>
```

In this example, this can be seen in _two_ ways. It can be two proxy events or it can also be two expressions being evaluated, and only returns the second. It's like doing:

```
const a = 1
const b = 2
a, b // prints 2, but a goes nowhere
```

Sure, it's convenient to have shortened syntax. But this usually comes at the cost of confusing other syntaxes.

---

```xml
<button on-click="clickedProxy">...</button>
```

When I see this, I see `clickedProxy` as a name to some handler. However

```xml
<button on-click="clickedProxy, clickedProxy2">...</button>
```

I see this as an expression and would _expect_ it to work like one considering you can write the following already:

```xml
<button on-click="@.fire('pushHello'),@.fire('pushWorld')">push hello world</button>
```

**Comment by ceremcem** [comment]
Okay, was no big deal.
