### ISSUE TITLE
0.10 – ambiguity warnings are generated also for keypath inside alias block {{#with}}

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3238]
## Description:
In Ractive 0.9.x no warning were generated for unresolved keypath inside alias block `{{#with}}` .
In Ractive 0.10.3 warning are generated. 

This should be an error if I'm referring to the correct documentation page:
https://ractive.js.org/api/#with-sections
> {#with }} also allows aliasing of references, including special references. [...] In this mode, the context within the block is not altered.

0.9.14 – https://jsfiddle.net/8ygtkdw3/
0.10.3 – https://jsfiddle.net/8ygtkdw3/2/

## Versions affected:
0.10

## Platforms affected:
All

## Reproduction:
1. https://jsfiddle.net/8ygtkdw3/2/
2. Open the console
3. Ambiguity warning is present: `'message' resolved but is ambiguous.` 

```javascript
Ractive.defaults.warnAboutAmbiguity = true;

const r = window.r = new Ractive({
  el: '#main',
  template: `
  {{#with foo as bar}}
  	{{message}}
  {{/with}}
  `,
  data: {
    message: 'I\'m a message',
    foo: 'I\'m foo',
  }
});
```

**Comment by evs-chris** [comment]
Should be fixed in v0.10-dev and edge once travis does what travis does. Thanks for the report!
