### ISSUE TITLE
Issue when installing ractive 0.10.4-build-1 via npm

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3240]
## Description:
Error while installing build `0.10.4-build-1` via `npm`

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ractive@0.10.4-build-1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Yesterday I was able to install these version without any issue.**

With other version all works fine. I tried:
* 1.0.0-build-167
* 1.0.0-build-166
* 0.10.3
* 0.9.14

## Versions affected:
* 0.10.4-build-1
* 1.0.0-build-168

## Reproduction:
NPM version:
* 5.5.1
* 6.0.0

1. Set `0.10.4-build-1` as Ractive version in `package.json` 
2. Execute `npm i`.

**Comment by giovannipiller** [comment]
Happens to me as well.

```
$ npm -v
5.5.1
```

**Comment by marcalexiei** [comment]
Could be related to the 2 last failed [travis builds](https://travis-ci.org/ractivejs/ractive/builds)?

**Comment by ghost** [comment]
Kicking build to see if that fixes it.

**Comment by ghost** [comment]
```
npm ERR! publish Failed PUT 403
npm ERR! Linux 4.14.12-041412-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.14.2/bin/node" "/home/travis/.nvm/versions/node/v6.14.2/bin/npm" "publish" "--tag" "v1.0-dev"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code E403
npm ERR! You cannot publish over the previously published versions: 1.0.0-build-168. : ractive
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/ractivejs/ractive/.build/npm-debug.log
```

**Comment by evs-chris** [comment]
I think npm is having some sort of issue... You can see the last two builds on npmjs.org, but they're not listed in the cli `show versions`. I'll try a manual publish if I don't hear back from npm soon.

**Comment by ghost** [comment]
> We are currently investigating problems with recently published packages not showing on the npm website 

Confirmed https://status.npmjs.org/

**Comment by evs-chris** [comment]
Not sure what happened to the npm registry there, but I've done a manual build to get around whatever wackiness was saying build 168 was both published and not published. Looks like travis can do its thing again now that we're beyond Schrodinger's build.
