### ISSUE TITLE
Using `progress` goes craaaaaaaazy

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3243]
Hi,

this drove me on the fringe of craziness ...I debugged for a whole afternoon to finally came to the conclusion that using the data name `progress` is broken.

https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8AOngIYxq70B8BA9CaW7QHYCCAZwDGMYgAdclGvVwIAtpIA2DBfXK4AnpIR08CAB65OMBqNxkE7AXcH8CAIwCuuXAHt+5LwFpRKsSiANYGAAIAdJ4oKCoIABQA5JIwHigwCMLCEcTCAMouoqKZwokAlOwAKmmxCFyu7l58DgSSbABSeQDyAHLkwrgS-CjEAGbEyJDkwMCdvREDQyOj2vEpaRlZOfmFxVllGBhcbUJtACLEGZbkii4DFmAIUzPraFu5BUUlh+QoXggAQgA-ADjs17AIZgBiMbkAGvErbT57YQ-ABiAEEADJ5ACi02AnDGh0hwBho3ICPeOy+WR+lQASgBVfEzImjEkOexcMQSaRsEA4YTwTiccjGBCiNwILRgXLkUQeJAygDuxFwYFlMtUDG05Aanm8xG8GplnkkvgkKDAMkVMH4CBgPgpGvlkgYDoEpCY5HMlms5Go5AdKvIDIsVlICWAAnIWiYLCmiShuATCFwiSwsa0Sh1CiTKdzagUmezSHUDGe2doppUKg8SdNGVL3nINdem2EVdbNZrH12JSmgxcNh7uAw2Yn-AwZQA3PZRbLUi5rR43FrhGa3B4JAwVMIsFqMpRhOQPT43JJ1zxyGqNWejUhneREqnmOnEgJFx6nwwc8pixlXkpBkO9NXPKhn1fIt1AQT9+EXbQ1wVc9xn4J9TQvXArxkG8f3-PMgPEECfBNR5yAACUqABZLF4ycTAgA

...that's what I call an impressive bug! Accross all versions!

**Comment by ceremcem** [comment]
Seriously, take a nap :)

**Comment by evs-chris** [comment]
There's an `r` missing in the interpolator keypath :smile:. You have `{{progess.isSuccess}}` rather than `{{progress.isSuccess}}`. I think my personal record on typo hunting stands at about 3 and a half hours over two days.

**Comment by dagnelies** [comment]
duuuuuuuuuuuuuuuh ...feel so stupid right now 🙈 
thanks
