### ISSUE TITLE
Push and splice do not work in filtered arrays

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3247]
## Description:
Disclaimer: I don't now if this is a bug or not.
Ractive's push and splice do not seem to wok when arrays are filtered.
Check the playground link, I have a method for filtering that's called filter_list.
When I'm passing data to the component using the filtering method, then Ractive's push n splice methods do not seem to work (click 1st button).
Instead I have to use a workaround to make it work (2nd button).

This only happens when the arrays are filtered.

## Versions affected:
0.10.3

## Platforms affected:
All Browsers

## Reproduction:
[Playground link](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYD2AJmgHQBWAjgK5owCeLBgFsqnHvwC0ARhZSATCwAsLIQEsAduwJ4wpCtSpYktANZlUYFgCN69FFhhIytRpuFUbdh06oBmFv4A7KIYHrb2KI5kKhpaIAC6AL542JAgADyMqgBuAASqjAC8ADogKEgwAOZoKKUAfOlUWdl1xept6Ri0MKpkKPlFpehCZMjopbkofGRoJWVoAB4oVI60KDlo9W3FKJk5ubTIGBhzMPQA7lvttbvNB0cnpQwIEhhC0nJXO9+7ZK3XPx2AFl6Nk0Plhhhcox6Jhcuo7LlzvQYCYkWA0OpchVHHwoRVwQAzVQIdAwNCMbY3HaNP5UmlNHL-BnNZm3faHJDHU4XL43PZ5Tncp70F5vD58n7pACEEgkuQAKmBVFDkaiocT1OC5WypbKJPTqbshHxhGR6Fr1P0kNkkCSkFYEGgAPoIFUoObAYAAYQVzu9ABkAIIAVQAygBRZ1BgBqQYAkgHEokJhg0E61hTXe7PT6-YHQ5HkxMqLqbjrDd8AfyTWaLZj+pWbja7chHS63Vhc8TSbxs1gABS+-3B8NR2MJgM4XLAADkAC15wGAPIAIWd8YAIrPILlZ1JZ4kAJTFkBNnZpjPoRj9j2lL09sm3of50eR6dzxcr9dbnd7g-HqeTaloajSslSYFMh0hjdL0KDMu06idLBfQDHMtb0CM9ZWs6wyjKgmwgJM0yzEMizLKs6xgnyAr3FyjwgGclwgGWtFCgxzyvO8ACskr8nc7FzJ2KASJUZxcGQfE-F6ADEaDGGAuSXmgmY3sJxbXLkuSArsSC5GA5KEnMbAtl0PR9JAADcEyCaUwmieJZASKowwzsAi6RgGEa+hGm65AA-HuxhUWgs65Lus6HimREWhIhyqKYcwAAIoMqGAsCg9CVJUToDklJhoNMFgANSziwHkRl5Pnbke9Reoum4RmG3oAErxgACgq8bLgAcsmjRIGW0nAFQ8m0GAGk6ZBLSgYyM3VmxDxzJx4pyJM5FxQ2vBSbsVhcKQFrETMcx7Qd7REbZIBWCgWLXeoEjMISSBcKSEyxfFiWlIQs5CKCLrKaps7xPUIJgkp6YqdejSnZl6gNFYMC5KW6QI0jQ27ftsNHaRV2YxaNlLaUd25HdD1oE9L21DF90fSYczfb9YK4WAqDOmqJgYEDIN-eDV4UrkA7sxgR7Q3jcOzeBC0CYTIArTxO07LJY2KS29rtrek39NpRrpHpBnk8ZpkoSgVkE-RQnug59ASc5rn1fOnneQqvkBUFawbGFEVRW9NNup9IApWlGVZTlaB5QVRWpaV5UO5VTu+bOtUsfbjXNW1nXdX1iQDejisjcrmsslB1LXNN-yNGZcH-Lg+DwLaiPmNUzqMKgemFDObRaaUw4FmOpS7oQndacPI-AEPI8T8PpSLhGAAaCq95GG6bv3uRSAAbDg4+TxP0-zovEbtS1ABis+r6UpRb1iO+T3vq5BgGzoANIBpuq4RvO58gJumC0Gvl-bxvl3EADUmqtQ6l1XqX8f5dH-rgQBQDSgv3DPGHqABxL+UgAAMUgAHXyAVPEAyCn4RgAJq4KgNpEAWCsEAE5sE4MCFIKQig8EEJHkggMIYSGkM+JQi+8D8HsM4dwshvgv5sPYcAl+m5vTLkal-LB3EKFXykcAh+aD35oJXvwkAchGESDoYYwIkipGlA0TGCMLUwyrykKotRe9HbVVXk9BAaZ7FmJAUuNcy9MEXyEZPZICDR7BJ3nvOeC83xRi3LYwIHjhFeIPkfU+EjBFqKoYue+j8ZHv0-romBf8+HxIIXvVO4CM5QPyb-XIRTQm3yIVwsMqCMG6OwbUgJiCGmiPIYouhDCpBMJYaYhJxCyF8N3KUehNCBnyHaekkRPDxG6OGSUhpsj5ERkUYoOZDiQAaK0ToiZeiDFGKwSYtJuyLFWJsZQuxdTd5eKcc7Q5uRXHuPuRwrx35fGtP8QQoJHSQmArCV4iJB8fm7ikAADmKZ0xcSST5n2WRczxmSH7P1frk6B1SlmwpvqUsB6dIE9WxbA3FHzCHIKaegzB3EsErM6aMnpuiaFTMYcw1hKKRlcJ4eMqhbKZlSF4ly1ZTKllHIZfitZciFEst8FCyVIL9kRm0V-fRAzDG0OMYq+pVzrG2LxSCiqVVnkuKQG4tAhr6lfh8TE3RfD7kpg6fEK+3wQA9yidGOMiZV6D2vtJIeOlwnz3BXayF9ig2JKickpFEqLmRrRdkzFH9SV-05RGo0BK04QMzqm3I6bA2Zq6dSlpRzsEqMLYCLpPCKFHNZf0wZBb-VFqZXygRGaq1itSR26k0qNm9PJc2qtyrVUspoVgwxE6aGSMjXqm5u4sE9rdca+OLy3mWopcAm1P4XmlAoZWlAAKu43DHkO3tM8Q2erDTUpdVN4XRsRd2g9y75xZIxW-FNVTYHCtvVm8pxK80-ufVTKlzTME4JnS2nlZDa1UPrdMxtkHO3Qd4U+s9bqu3It-X22VdasFNuPcOgMmiVW7uoeOydk6kO9rnavRdwHHFx2cZQ9dVqHnbohVQ-dZ6j3a0Vgx0Fl7CzRJeb4bD97hMxrQ4R89r70U5M-UcgpuR17UZfWUoluav1-1U-GqDKCaWtIg3p5D3TYOlHg+yoZJne2tuk3x2zKHxVULUyB1+MrNljt09hkdZHx1ToC658xxHLH6sofR9Dd7Y4mt8mai1bHPkcevaUB1PGqTA3UE6toLVgobBYI9Z6pJ0ot3KLkdup6tKPj7MJXchIuDqHdhaAcwlpxVZgEeCrw9yQoC4DALEwkWBtYHHVhr6wmsuTQEIDroTCQogHPXXIEd8hYja9N4FI9VCEgHBNoQhAI7xDK4Udu9XHoaH5gAH3OxCSbe3CoHelO3Nrt2+DxDW+krS3XesrfNWmay63h5OpvoDnen2+uTBgDwP7I9jx-Z2E6rL6gcvuzBIITC5pLT2BUKaNH2F+jtyRyFFg5FMSMAHJ1rSKpRQEUYLVn7G6hF4TGGgCKMkMJYQx7hSb+F0CzniSVpAtX6uNfUAON7IOahfY7v9rSqs2xOlvAPF1FKAbXgV7kQgGWgdQ4B-Ei0u5ycT0Zv9CGqlBejdUE1tYCwxcEKtywFEqhKgaHNSwMg5IwRWh-hTUkovtcEIWx64TZXJhB2qCgAcs4VdZmEonP3QCA+vmE16ycwfUoqhYGHiPsuHTy5j0eOPN9ZuI3mxUfIwfA9jhYE6dQlRUq5HlFISyZe6jtywU31QcojxS-e-kQkAsK+RkIKoeIMcnm+Rtz33IA+IxD5Hyu6qwf10F-e2n9KZAuAYDAFn20atc-ul51PxPY5Z-583TvVfLAMCjASmHSPJvVcx+nKoacUhT-S4nsD-5FKi8CwWwAL3LyPyXgnETCr0xFr0UgbybwAJb1yDb1yD-07273e0237yAPHG9QDEID-zn2i1XQnx72n2T0TGwNwLHz8kezp2X3SQv3X03wjyjzUn32nCIJAKwJwLf0n2Hgvyvz9lv2z3VkfwQJf04Pe0-yAXEOh0NSN2ZlZiFjN2FwHCtwIPYTtwdyd3UBdzdzQA9xQC90K3D1EPSQTxHCD3bgv0zzvz5iYKwFjzPy0hMPBTYNT1DxqG31bBzw7H3yMLUR-xL0RlUEANMMr2rwgPrzXnb1yFgPgI7wkC7wNx71QJfGCMH2H1HyY2eRUK4On1n3SJiwoNeSoPsKAVYMwNdw3y3xyOHx8K4K0mn0v2v1oDDmfzXhqLEOKMkPYT8P-yCKcLKNCLrygIQKiNb2gKQISJQL72SL6MnFILyPwImOyPQOIPYLIIyJdkoItWoMn3qLoMqOWLYNILaKWJSIwMnAaL4IHD-xEO2KkU6K-3fxHh4LcKsMhmj2YMP1OOOKAWePD1nAEL31sJYIOMwO+Oh23gRxh22HUAW0og2GDy1HOFyAJw2DJyHnKCqBqBZwxLD153RK5yZ2xIJIIjxOvn513EbhdH5zaBhxrloHgCSlUCwhgH6F6wQAHFKF0HIEoBoCMFMHMFSmsHCG8GcFcFRxEE8AiCiD8ACBYGCFoGODCC8EiCcBiDcGOFKDf0EF6wwBRAkHNA0DJBnFoB1JRApPoENN4EskSBAESCAA)

**Comment by evs-chris** [comment]
This is one of those things that _looks_ like it should work but can't, because you're effectively operating on an ephemeral clone of the array that gets recomputed when the array changes. Even the workaround is probably not doing what you expect because of the computation - there's actually data getting initialized on the component from the computation and when you do the set, it's only affecting data in the component not at the source.

The way I usually handle this sort of thing is to let the component handle the filtering, so that it has a handle to the original array to mutate it. Any approach that lets the component know what the source array(s) should be should work.

**Comment by kouts** [comment]
I don't want to mutate the original array, maybe the ```isolated: false``` setting is confusing.
I only want it to operate on the copy. So in order to do that I have to create the filtering method on the component?

**Comment by evs-chris** [comment]
Ah! I misunderstood your intent. I think what you want then is to just pass the data in, which you can do with a [static mapping](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYD2AJmgHQBWAjgK5owCeLBgFsqnHvwC0ARhZSATCwAsLIQEsAduwJ4wpCtSpYktANZlUYFgCN69FFhhIytRpuFUbdh06oBmFv4A7KIYHrb2KI5kKhpaIAC6AL542JAgADyMqgBuAASqjAC8ADogKEgwAOZoKKUAfOlUWdl1xept6Ri0MKpkKPlFpehCZMjopbkofGRoJWVoAB4oVI60KDlo9W3FKJk5ubTIGBhzMPQA7lvttbvNB0cnpQwIEhhC0nJXO9+7ZK3XPx2AFl6Nk0Plhhhcox6Jhcuo7LlzvQYCYkWA0OpchVHHwoRVwQAzVQIdAwNCMbY3HaNP5UmlNHL-BnNZm3faHJDHU4XL43PZ5Tncp70F5vD58n7pACEEgkuQAKmBVFDkaiocT1OC5WypbKJPTqbshHxhGR6Fr1P0kNkkCSkFYEGgAPoIFUoObAYAAYQVzu9ABkAIIAVQAygBRZ1BgBqQYAkgHEokJhg0E61hTXe7PT6-YHQ5HkxMqLqbjrDd8AfyTWaLZj+pWbja7chHS63Vg5oRCMTSbxs1gABS+-3B8NR2MJgM4XLAADkAC1FwGAPIAIWd8YAIvPILl51J54kAJTxeKlJs7NMZ9CMQce0o9vtkh8j-PjyOzhfLtebnd7geR6nuel7VjspaGo0rJUtBTIdIY3S9CgzLtOonRIX0AxzLW9AjPWVrOsMoyoJsICTNMsxDIsyyrOsYJ8gK9xco8IBnJcIBlkxQqsc8rzvAArJK-J3DxcydigEiVGcXBkMJPxegAxGgxhgLkN5oJm94ScW1y5LkgK7EguRgOShJzGwLZdD0fSQAA3BMYmlBJUkyWQEiqMMc7AMukYBhGvoRtuuQAPwHsY9FoPOuT7vOx4puRFoSIcqimHMAACKDKhgLAoPQlSVE6Q7pSYaDTBYADU84sL5Eb+YFu4nvUXrLtuEZht6ABK8YAAoKvGq4AHLJo0SBlgpwBUCptBgLphlwS0UGMot1bcQ8cx8eKciTDRyUNrw8m7FYXCkBaFEzHMx2ne05FOSAVgoFiD3qBIzCEkgXCkhMSUpWlT7zkIoIuhpWnzhenEgmC6npppd6NFdeXqA0VgwLkpbpCjaPjUdJ2I+dVH3bjFqOetpTPbkz2vWg72fbUiUvb9JjdgDQNEWAqDOmqJgYGD9SQ+CIN3rkQ5cxgJ7w0TSNLTBq2iaTICbYJh07Ep01qS29rtg+c39AZRrpMZpnUxZVmYSg9kkyx4nuq59CyR5XktYufkBQqQWheFawbNFsXxd9DNun9ICZdluX5YVaDFaV5VZVVNXO3VrtBfOTWcU7bUdd1fUDcNiSjdjKuTWrOssvB1LXAt-yNNZyH-Lg+DwLaqPmNUzqMKgxmFHObT6aUo4FhOpT7oQPf6WP4-AKP4-T2PpTLhGAAaCoD5GW7bkPuRSAAbDgU8z9Pc+LivEY9Z1ABiC8b5euB7-vs8gMu65BgGzoANIBtu64RouV8gNumC0E3qUXeWI74HwfouDOXVer9SGr-f+XQgE31AWA++79wzxkGgAcV-lIAADFIYBt8wGlHQa-CMABNQhUADIgDwXggAnPgghgQpBSEUEQlBqDaFkMoZ8Gh18QHcLQQGEM5CKG+F-pw4RvcQDv23N6VcbVf54IEtQoRMjSjPywV-LB68BEgDkCwiQjCTGBGkZokA2iYwRk6mGDeUgNHCMPi7BqG93oIDTE47hh8-xr1wWBVByRiETxCfvQ+i9l6fijDuBxgRvGoMPsfU+F8pHIJkbQx+z834fy-j-AxCDAH8ISSQiBUCs6wMGvAgBuRilhJnqQ0RYZME4IMfgupXDElyNEeI6h+5Sj0KYfQqQrD2EWOcd0sRfDf5DJYfIDpGTGlTIkWkkpd9GkKKURGFRigFmWO0bo-R-TDHGNMXg8x6T9kBiwTYuxDi1nhIga4t2RzcgeK8fU8Bv4Nz+LaYEsBwTOnT0nkC9ZEDInH1+fuKQAAOB5DSIHJPPpfAx4yfEQKfi-eReTqmIMkZciZrV2rQOznAgpNT8XwvAeg5p2DcECTwWirpvCqEqMYcwkZbCOEEvRSy-hxzZmcqkEJHlzKemUPxccplpT5GKOUQYvBvgYXSrBQciMejf5GJGSYhhZiVWPOsbY+xNDHGfPHi4xObiaHvLQFS81EC-GxIMfwz5KYgXxBAd8EA-donRjjImDeI9QEKVHoZCJS9IVOuhRosNiLokpJRVKy5saslYtyd-XFgDuUxqNIfcpMCc6ZtyNm0NubJm0tacc-B6jS2Akmb0tlgrRkluDWWvlqza3UnrRKjtra62yq2WyylnavVqo1Qq+heCTFTvoRY2Nhq7k0LwTmuttV6ovPcUgTxtqzX32+f+V5pRqGdsBb3G4IKz2rsXBC31Ubakrq7cuJFqTUXJrLamnJn8M3ksQSKh9XqiWZwLWS45hTch-pHXTGlLTcEELnW28VrKJ1Nq5fB-tiH+W0LQ12llkqsNvvQ5s+Vxz6EtsvV2sdh66GTundO7Do7rm3ONfuZdkGLXrqCpu7ddq90rh+Xeo9-yfinr1irNj4KI23teb4f9dMn3xuRb28jAHFyYs-Tin9gCt70bk5A4lFTC2adyNpgjOGmkwbaXB0zXqWV9NoYMjlzadNLPEZhwR4ncNKdE2Zoj2yJ0mdk1o65hy2X0No7O6zdMF3MdyKxvtj6E4cdeTanjsj91QtoS6+LbqdgXnUDl9QnUIobBYG9D6pIcrt3KLkLuF63kklfBJfchIuDqC9haIcElZwvl4CeOr+lyQoC4DALEEkWA9ZgEOFrbX1gdc8mgIQfWwmEhREOJuuRo75CxBNpboLp6qEJEOebQhCDR3iDVwoXdWtvQ0BSXIAAfe7EIFunbKud6UXcJuvb4PEXbGSBs1GG9trdaYHJ7fHm6u+kP96DaB5MGAPAwcQ5PGDnYbqCtFa9mCQQeFzSWnsCoU0uOCL9C7pjyKLAaKYkYEOfr+QMCilIowZrIOd1cOImMNAsVFK4XwvjoiC2SLoHnN4qrSBmutfa+oIcf2YeA5G93cHY8NZtidA+YeHrd2CyzE13IhA8tQ6R2PET+kLT7jp+PQGYJnTa+Z28yXs3pdrAWLL1BzuWAolUJUDQW6WBkHJGCK0-8aakhl0b1B62fWFgjDVyYodqgoCHPOW3D4U7h7AZHj80e-XTlj1lFULAE9J5Vw6NXEk0+7pW6jNbFR8ix6jxOFgTp1CVCyrkeUUg7J17qF3PBXfVByhPIr-7+RCTCwb5GQgqh4jx2eUFV3I-cgT4jFPmfa6k7BU+6z9PI-885TIFwDAYBi+2k1mX90Iul9Z4nKvlHu67575YBgUYqVI7J5hlpVPs5VCzikHfpXM80OQSleKIws62AAXvXtfqvFOImE3piK3mpB3l3pAT3rFigYPsPv9gduPtAZOP6gGIQOAWvolhvgviPsvjnomEQSQXPpvm8tvvfvvI-gfkfkninuXrOJQbAYQcQf-ovmPI-s-oHG-iXlrJwbkOAb-vwf9kAQCmEibtPFbi6FlBzKLBLjNqoB1s7uQdwu7p7t7uoL7v7mgIHigMHuVonjIRkpnmONHnnvHjUOwR-neKntYTIrYZCjwQ4QXkXvOGIeflgBXgAdPFXmAbXqoFAXYY3s3oge3pvP3rkGgX3vkJgRbtgWPu+NEZPtPrPpai8roQIcvqvnkUlrHjajvgIVftkfgdOH7ofsfsUdPu4VUdUcfE-i-rQJHD-pvC0bIUwfpHIcImETXqjJAV3NwQQfAS3m3sgZIUkb3hgRIEPukRkjgVkV4QQTQaUWQasYvpMdONsevg1OUYwSEcIsvvUWwQcdQXwZUUUXgVQQGB0SIUOFIb0fcTIkMdwt8agkIU4e-reDrhflwXgX0X8aHGmInv4afqrh2CCW0b6jweCdPHIQVqeKjuoOtnRBsLHlqOcLkOThsLTqPOUFUDUNzmSQniLqSYLpzpSXSaRDSaAmLvuC3C6GLm0BifXLQPAOlKoPhDAP0MNggEOKULoOQJQDQEYKYOYFlNYOEN4M4K4DjiIJ4BEFEH4AECwMELQMcGEF4JEE4DEG4McKUP-oIMNgzjABIOaBoGSHOLQFaSiGyfQPabwHZIkCAIkEAA) e.g. `<mycomponent left="[[filter(...)]]" right="[[filter(...)]]" />`.

**Comment by kouts** [comment]
Thank you @evs-chris that works, but what I want to achieve is that when data changes outside of the component then the data inside the component updates too.
I understand that if I want the data passed inside the component to be filtered then I should use another way and maybe not a generic filter method I'm using right now?
How could I achieve this?

**Comment by ghost** [comment]
This feels like a data architecture exercise. In particular, removing data duplication. In this case, what I would do is have one big array of the items involved. Anything else that can be derived from this array would then just be computed properties.

For instance, the items that initially show on the left and right could be derived from this one big array and two other arrays containing the IDs of what goes to the left and right. To move them around, I just move the IDs around while the items of the big array stay put. [Here's a demo](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYD2AJmgHQBWAjgK5owCeLBgFsqnHvwC0ARhZSATCwAsLIQEsAduwJ4wpCtSpYktANZlUYFgCN69FFhhIytRpuFUbdh06oBmFv4A7KIYHrb2KI5kKhpaIAC6AL542JAgADyMqgBuAASqjAC8ADogKEgwAOZoKKUAfOlUWdl1uPjwDOpYuYyoSLmFucDF6rm5tMhcGJiQuYTDo2O5pQBaKwCiABoAKgDCADIAggCqAMrrAPoAkgAipbNSAGw4I0vLIGsHJ+cACgBKADFNvd3qUXosxqsVgAhQ77C4AaX2N2h6xWINKN0wtFyUjBryWUJu61Ouz+Vx+2yuAHkAHIYkBYjA4vG4AmQkBIs5XWkAcQZUgADKzwW9SlyEesAJqs2alQWCgCcQuFgSkUkU+Ih7wl0rkDK1Ys5+2OkqlvgNbO14uRu2pxIZgoArCL2e84bzUby7lB3nJVRIlYHAobCSAPQA1dZ-U4gqSisNrc77da7bbrH2zABmSAQ0wTHLW+2p0OumferIJySGbqhWz2RzOl1uccCBfen0bv0BwN9pVDhZhcMRyNR6L7jOxuX1VqNa2JpPJlJp9InTJxM-bNu5fIFgs3teNpulsveCuVCqkao1A51JrNM7lIAvqvkB+tR7NFont5tNztDoToKijvkaHpeuWpT+legaKsGv7hvsvJRjGcZbh8KzJqm6bljmeZoOhRYlmWAr9os1YLHOGw7F8TYkb6UgAByESstHdkClosbC8JIiiaIMuuuTfixC5khSVJ0gJU7CYeXKnDy-ITlITqCghuoyo6Soqle6qarOYbqY+7wvjpylqfe0rfk+5n-va6yOr4jEIeB6zegy0GBLB8H6RykbRrGDEsVhaYZiCeH5oeRGli2E4zlWOA1h+az1mxzblvGkWsV26z-BxP4+R2Q48aO-FrlOekiSSYnLpJZXMrkFWySa8m7kpwrmceGlAVpl7Xo1H6GZxTWdVZoIFX+AH2d1Mkfi5bndQqgaCktzlIShAWzIKQXrCmIW4bmEVJSsxbRZBICVuRCWUYm1ENt8aUgnILGpblvbWeNGHcSOfHjk+glOgh85VUuEmrn9U4Ax9ckKXuroDRZXVPue2l9R1D5DfDI0Y0avGTZp-VgUhEGaYtpOqR9fmob6W2ZcFOFhQdBGZSd9FPhdYwUZlKXZazQnPdlr3YzdX28WOUn1Y8gMrKJIMruLOKS1DzUw21cM4wjp7yj1r43krnVGf2etfkLHK43ZmmK+hc1nQqZMrRTa3+SCNNHXToW+uFTNHSzMVPnF5HxAmKD0GQsyEE8CVXoHBI2KQ9BCGH8bTvEIyJCMIydN02wAO70H89DZ6caAIGgtAoAMuR-MYKA5KwaAAB7oOojAABTXegQhkMg6CzAABm66RcAgdRumMwDAAAxGgxhgLkwdkDcqgYF3SB8LkiRp9qbzpAgqjjMgGAYBI1e1yUIAAAIoGAS8sEvhxl7XLfJTRPO3AAlKUuT0OoEgTKophn0vtfDALBpglzLk-W6qUywfxAHUceuQgaLnEiudeiRGi7xHlvIYwAqDT1oGADeA8qBDywdvKwXA46jG-r-XeADShAJvkIeg2Q0BF3ATXb+GAW6wLqAAWRYWgRoFCqFkKWIPYeo8cFTxnrkWOwchCL2XsgNeRDsFjB3nvCYSBD7HwfqwwBV8b5330WgSB3N7owM-jQv+9CL5GJAWA0uKBzEv0se-eoCCkHVVBmgjBqgxFvHHngmeajt4kMkYsXuCZaCHz7m6FgJ9WHAHGPQBA9AYCzBgGgRg68CTRIJL0cosweEDDqLkNubpVAd0oHMaO2p55h3qW8eR8cmnticWXHJTSqxvxifHMglDumJTePPJRK8+ClOum8TO5dqloCEBgCuDiWDVBcQAcnmYs9ZH9sGzLniHZZwDVk1Bbus+eOypHZJQFwGAowtkgKzKoBA6AYAtz3oUcp89b7NwbtSLM7yWDPzunRd+uRynSF2W8ZIbpWmKKXhMqZUj9kPKOTfNZZyHmXL2Vw8ucK0UgIxesuF2K3hjGubc+5NSWBPJebwd5ZS5F2AUT85g9d-mAuBdAsFEKpBQqWJvDmCYTE11Ye8xgb8RlLApXcuexyiWdPQIwHZrK-kAoKJK3l8UCSKvFZK6ZqSuhzN+fXAlJyNmKpySqjQbKOUaqqVmCpNqG7gtyJCqVozjnKP-mY9ZlrlUJWdfXSO-KOa5GLtMD1SwVmDIwGAM5-r1mBolW6QV68EzMNYew5xqguFIu1Ps+eZqiUXNDYa7o+LBgrKJSSst+z-XFtOX64uzirW7LdCs6YGyLkJU7cw+gcaW7zwSv6t+ZbO1NpJb2r1-bB1wpHS2rpErx1eqbYmhKhB4j8phYsDAs740VBgEnQ9ch9VunrTcrMWYrjqEODAI9FdD0yFpa8lueRPm5BPaq9lALsiSsKABt1fLz24tyFgLgV6b13pgHIR996FAvvpe+8pT7v0cr-QMQDkK3QytGIQFgBHwOQdvfepOBHQGXuvSRmDKdyKp3beofZhwyBkArlXUxLAG5N1btdYQZBv5oHUPYWYKSc55wLtmsu6bCl9BKf+8plSC2TGmLUzd7ZGl1PbHCnp5E+kEg7ivHuuR+7anSGJ-OhdF1zJqWfBB2ipiYDQZ-eetmUlFqISAJlcchCua8wopznmqCBNyOkMgdRtghxEykgAUqcOkFGYAaEqKoLMkz56So3o0MLA8wvQmZW0nBuRYvxYcEllLky4UZfQVQbLUT6Pp1vSxtuc8KhrNmOsie5Qqg1CTT0Po6835tFoPAc+qhO4ZPLrchALdSi6HIJQGgRhTDmCvtYcI3hnCuEEPHMIXhIg+H8EEOgh9dsRCiDENwh9ShvwANwjEELcjAGSJD8Y0K8oYtBHsZNmK9oTvAbuJBAIkIAA)

```js
const data = {
  clauses: [{
    "ZZEXTCLAUSE_ID": 16,
    "ZZCLAUSEPRFX": "",
    "ZZBAL_KLDBEZ": "Desc 1",
    "ZZDESCRIPTION": "Desc 1",
    "KLUSING": "101",
    "KLUKEY1": "00910017114",
    "KLUKEY2": "",
    "KLUKEY3": "",
    "KLDCODE": "051",
    "ALGBEGD": "2017-09-07",
    "ALGVERS": 1,
    "ZZSELECTED": false,
    "ZZLOB_ID": "1"
  }, {
    "ZZEXTCLAUSE_ID": 17,
    "ZZCLAUSEPRFX": "",
    "ZZBAL_KLDBEZ": "Desc 2",
    "ZZDESCRIPTION": "Desc 2",
    "KLUSING": "102",
    "KLUKEY1": "00910017114",
    "KLUKEY2": "910017122",
    "KLUKEY3": "",
    "KLDCODE": "042",
    "ALGBEGD": "2017-09-07",
    "ALGVERS": 1,
    "ZZSELECTED": false,
    "ZZLOB_ID": "1"
  }, {
    "ZZEXTCLAUSE_ID": 18,
    "ZZCLAUSEPRFX": "",
    "ZZBAL_KLDBEZ": "Desc 3",
    "ZZDESCRIPTION": "Desc 3",
    "KLUSING": "150",
    "KLUKEY1": "00910017114",
    "KLUKEY2": "910017115",
    "KLUKEY3": "",
    "KLDCODE": "038",
    "ALGBEGD": "2017-09-07",
    "ALGVERS": 1,
    "ZZSELECTED": false,
    "ZZLOB_ID": "2"
  }, {
    "ZZEXTCLAUSE_ID": 1,
    "ZZCLAUSEPRFX": "",
    "ZZBAL_KLDBEZ": "Desc 4",
    "ZZDESCRIPTION": "Desc 4",
    "KLUSING": "101",
    "KLUKEY1": "00910017114",
    "KLUKEY2": "",
    "KLUKEY3": "",
    "KLDCODE": "003",
    "ALGBEGD": "0000-00-00",
    "ALGVERS": 0,
    "ZZSELECTED": false,
    "ZZLOB_ID": "1"
  }, {
    "ZZEXTCLAUSE_ID": 2,
    "ZZCLAUSEPRFX": "",
    "ZZBAL_KLDBEZ": "Desc 5",
    "ZZDESCRIPTION": "Desc 5",
    "KLUSING": "101",
    "KLUKEY1": "00910017114",
    "KLUKEY2": "",
    "KLUKEY3": "",
    "KLDCODE": "004",
    "ALGBEGD": "0000-00-00",
    "ALGVERS": 0,
    "ZZSELECTED": false,
    "ZZLOB_ID": "1"
  }, {
    "ZZEXTCLAUSE_ID": 3,
    "ZZCLAUSEPRFX": "",
    "ZZBAL_KLDBEZ": "Desc 6",
    "ZZDESCRIPTION": "Desc 6",
    "KLUSING": "101",
    "KLUKEY1": "00910017114",
    "KLUKEY2": "",
    "KLUKEY3": "",
    "KLDCODE": "006",
    "ALGBEGD": "0000-00-00",
    "ALGVERS": 0,
    "ZZSELECTED": false,
    "ZZLOB_ID": "2"
  }],
  top: [16, 17],
  bottom: [1, 2]
}

const TwoRowSelect = Ractive.extend({
  template: `
    <ul>
      {{#each topDisplay }}
        <li class-active="@this.isActive(ZZEXTCLAUSE_ID)" on-click="@this.select(ZZEXTCLAUSE_ID)">{{ ZZDESCRIPTION }}</li>
      {{/each}}
    </ul>
    <button on-click="@this.moveSelections()">Move</button>
    <ul>
      {{#each bottomDisplay }}
        <li class-active="@this.isActive(ZZEXTCLAUSE_ID)" on-click="@this.select(ZZEXTCLAUSE_ID)">{{ ZZDESCRIPTION }}</li>
      {{/each}}
    </ul>
  `,
  css: `
    .active{ color: red }
  `,
  data: () => ({
    items: [],
    top: [],
    bottom: [],
    selected: []
  }),
  computed: {
    topDisplay() {
      const items = this.get('items')
      const top = this.get('top')
      return items.filter(i => top.indexOf(i.ZZEXTCLAUSE_ID) > -1)
    },
    bottomDisplay() {
      const items = this.get('items')
      const bottom = this.get('bottom')
      return items.filter(i => bottom.indexOf(i.ZZEXTCLAUSE_ID) > -1)
    }
  },
  isActive(id) {
    return this.get('selected').indexOf(id) > -1
  },
  select(id) {
    const index = this.get('selected').indexOf(id)
    if (index > -1) {
      this.splice('selected', index, 1)
    } else {
      this.push('selected', id)
    }
  },
  moveSelections() {
    const top = this.get('top')
    const bottom = this.get('bottom')
    const selected = this.get('selected')

    this.set('top', this.smoosh(top, selected))
    this.set('bottom', this.smoosh(bottom, selected))
    this.set('selected', [])
  },
  smoosh(arr1, arr2) {
    const stuffInArr1 = arr1.filter(v => arr2.indexOf(v) === -1)
    const stuffInArr2 = arr2.filter(v => arr1.indexOf(v) === -1)
    return [...stuffInArr1, ...stuffInArr2]
  }
})

const App = Ractive.extend({
  components: { TwoRowSelect },
  data: () => ({
    clauses: [],
    top: [],
    bottom: []
  }),
  template: `
    <TwoRowSelect items="{{ clauses }}" top="{{ top }}" bottom="{{ bottom }}" />
    <p>Top: {{ JSON.stringify(top) }}</p>
    <p>Bottom: {{ JSON.stringify(bottom) }}</p>
  `
})

App({ target: '#target', data })
```

**Comment by kouts** [comment]
Ok so the correct way to achieve what I want is with computed properties, got it, thank you @fskreuz .
