### ISSUE TITLE
Slow rendering for large datasets

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3248]
## Description:

The following page is a part of a relatively big single web app:

![ractive-performance](https://user-images.githubusercontent.com/6639874/41470899-aca266a8-70ba-11e8-98b6-8df658a3d37c.gif)

Rendering is considerably slow for large datasets. Note that the last result (5971 rows) takes ~12MB. 

Above actions are produced by the following handler: ([Javascript here](https://gist.github.com/ceremcem/9431e5ff8a653f5b3493d593508ebb52)) 

```ls
'runQuery': (ctx) ->
    btn = ctx.component
    btn.state \doing
    t0 = Date.now!
    err, res <~ sync.query ctx.get \_tmp.query
    if err => return btn.error err
    console.log "response is: ", res
    @set \_tmp.queryResultLength, res.length
    t1 = Date.now!
    @set \_tmp.queryDelay, (t1 - t0)
    <~ sleep 50ms
    @set \_tmp.queryResult, res
    <~ sleep 50ms
    @set \_tmp.renderDelay, (Date.now! - t1 - 100)
    btn.state \done...
```
```pug 
h4.ui.header Result:
ol
    +each('_tmp.queryResult as row')
        li {{JSON.stringify(row)}}
```
> Note: According to my opinion, this is not an exact real use case, I can't imagine when I need to render 6000 records into the same page without pagination. I was experiencing a similar performance issue with my dropdown components, and I decided to render 100 records at most. 

## Versions affected:

10.0.3

## Reproduction:

Since it's a part of a large private project, reproduction is not possible at the moment.

## Edit

I don't know why, but there are huge render time differences on consequent runs:

![ractive-performance2](https://user-images.githubusercontent.com/6639874/41474824-b0bc74e4-70c5-11e8-8883-0cdcc77903bf.gif)

## Edit2 

Here is the profiler output: https://aktos.io/cloud/f/0dfa4d93f5/

**Comment by dagnelies** [comment]
Just as a comment, this has perhaps to do with the rendering itself, and unrelated to ractive.

If you render tons of elements, it'll take time in proportion, whatever you do. And imagine your query returns millions of rows, you'll be doomed even if you optimize it to death.

Have you tried some sort of paging, virtual scrolling?
Using either leads to near zero rendering time:

http://dagnelies.github.io/ractive-dataset/dataset.html
http://dagnelies.github.io/ractive-dataset/big.html

**Comment by ceremcem** [comment]
This issue should be closed by now. Key point is rendering on request, not at once and which is totally acceptable.
