### ISSUE TITLE
Context.hasListener() not working for proxy events

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3250]
## Description:

How can we use `Context.hasListener()` method for proxy events? 

When I create a component (`mycomp`) that decides its initialization sequence by looking whether it has `foo` listener or not, I use `ctx.hasListener('foo')` and it works okay. 

When I create another component (`theothercomp`) that uses `mycomp` under the hood, the listener should have to be passed to `mycomp`, obviously. But how can `mycomp` detect if `theothercomp` has a (valid?) `on-foo=` event?

## My Workaround

I'm using another attribute as a flag, like "`async-foo="true"` with `theothercomp` and `bind-async-foo` within `theothercomp`. 

## Versions affected:

0.10.3

## Reproduction:

[Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutZYCBvwQxGrAAQBeccXLU6CAB5kuSABTAAOu01kVrADZEVkcQANtu3QB4k1cbjIBPAwkmaQAIwYwkI0wCMLIoODAYUSOIwyB4AfJZkVmTWTE5iLOIcALQCBgYM7uAIeQxxwMBOFMVIGBjWAPSp6fE6icn1dlQtuhbsGACUluyylDT0zGyc3LxNE1IypKMKyqoaCfosRibmCTaeAK56HJnsWSThJADWhbn5cbtt5ZXVteIPuuUAxBQAZqFMCAACjAGCxau82mo-CpyMhxERxOFHFwRINWklysVcAhwei2ro1OwhOJoQhYZEEUiVJwYGikh9gPVfrikg0Dkd2N0yGYsAkOBR2BQyKYfvt2HIOGpyIp+lo8b9xFKyIpaGAiLgADIUZE0tQAcluDD1-VlEP42to2LI+twzCBIJYeqw4jIMH2CH6AG4HhgEtgEkhjEQRWKJew1Ka8dEyPsYOxxHL6Tw7cDQSKiAZsT6-doBkNOAB3BZyGhrVrFUx67xIJxO9YIQzGBCmXqssAAZliAGUEAg3iAAHIAeQAKuIAMJDggEACi45HHnEAscRHFCAaHe6eJSaTm2UNhWE0TiI7A2vEatw8MR2upIgas1YXL2MHE9WfyUfLFip-Pl-ERI3jq96NLuT67NuwhCAIogTLE-6AVSKIwA0UFHs09KQQI0EiOkJw5MU+SHjBCBxP+SE0oqw5jpO05ziO-Sodh6FwZhPTOny7CmImbRHs24iiuKlCStKkZJhmIjWgaCC1nSbS+q0CkDJgQA)

**Comment by evs-chris** [comment]
I _think_ you're looking for the `bubble` arg of `hasListener` which allows parent elements to supply a listener. [Is that what you're looking for?](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutZYCBvwQxGrAAQBeccXLU6CAB5kuSABTAAOu01kVrADZEVkcQANtu3QB4k1cbjIBPAwkmaQAIwYwkI0wCMLIoODAYUSOIwyB4AfJZkVmTWTE5iLOIcALQCBgYM7uAIeQxxwMBOFMVIGBjWAPSp6fE6icn1dlQtuhbsGACUluyylDT0zGyc3LxNE1IypKMKyqoaCfosRibmCTaeAK56HJnsWSThJADWhbn5cbtt5ZXVteIPuuUAxBQAZqFMCAACjAGCxau82mo-CpyMhxERxOFHFwRINWklysVcAhwei2ro1OwhOJoQhYZEEUiVJwYGikh9gPVfrikg0Dkd2N0yGYsAkOBR2BQyKYfvt2HIOGpyIp+lo8b9xFKyIpaGAiLgADIUZE0tQAcluDD1WHEZBg+wQ-VlEP42to2LI+twzCBIJYxtN5stAG4HhgEtgEkhjEQRWKJew1Na8dEyPsYOxxHL6TwXcDQSKiAZsX6A9oBkNOAB3BZyGhrVrFUx67xIJzG9YIQzGBCmXqssAAZliAGUEAg3iAAHIAeQAKuIAMIjggEACik7HHnEAscRHFCAaXe6eJSaTm2UNhWE0TiY7A2vEatw8MR2upIgas1YXL2MHE9VfyWfLFi58v17iESd46o+jT7i+uy7sIQgCKIEyxIBwFUiiMANDBJ7NPS0ECLBIjpCcOTFPkx5wQgcSAShNKKqOE7TrOC5jv06G4ZhCHYT0Jp8uwpjJm0J6tuIoripQkrStGKZZiIjoGgg9Z0m0-qtEpAyYEAA)

**Comment by ceremcem** [comment]
Wow!
