### ISSUE TITLE
.hasListener() detects listeners erroneously 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3253]
## Description:

Even we don't supply a real listener, `ctx.hasListener('mylistener', true)` considers the `mylistener` as if it was a real listener: 

![image](https://user-images.githubusercontent.com/6639874/42117162-d96ce84e-7c03-11e8-8b26-a6a3eeb286d1.png)

## Versions affected:

0.10.4

## Reproduction:

[Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4AlJAYxQEsA3NAOjIHsBbAB0YDs0OUM7mAnkzYACALwjSFGvTQAPdBwAmACmAAdDupTo2ydJBEADTdu0AeAEYBXHZxGcAtGQSUyAazHrwaBAkbeAHymKGYowMAClL5KODgiIWERAMSUAGYiGCxoAAowjKxxiaElKkpo6BRoSiJIIq5Y3GgwAJTF2hG+GGhFWiVhKhyMKCLlleg1dQ2KzW19ScAA9Om9YeaLNnYcwX1GeCGclByUKIZp1hzSnCoUci0a81QZNyhydGBIGAAylI1cMCoAORgXz+QF4EQoGDWNAte7tHRgX50booIFZZi5fKscGQ6GwgDcxRwIXwISUqCQZwuVw4KnhjxgFWsMA4IgeYW0GKxBTOSAQ3WJpM0ODmmikVFoDBY7C4PD4ggw1lYzWErHEknIktkCm4qg5OjQelQaEMJke5iUNEyKAECDQXhAlkYMHKMEMACZWHJRp8QTVLMgPASRMwkDAAOZHQwARiNIdYSCUVo4EdjAAZvSGrRhWMgBIYjq4uI5A4wPEEEeZBGqHBxHCC-IxHY3-EEIlEYnF1jWZTs1osrdR+yhzaLTBwuAB3TXSWhqEK+QyA51KATgkK6PMms3FatCGV1hug5veFAgplBAASnxErcY9V+MxgPYPbBHFl7okCN4wIgAcgA8neJ6Pn8zSvmqH4oPuSoqjAtZOPejrns0aDXre95gc+r5waqfZ7oqyr4e+v4AcBWHTE0L6LER8FQSEewJH0nCGAa2ioUy1KXFQ1y3AynIoPyzRosCaDrmKJQkn00mirgQA)

**Comment by evs-chris** [comment]
I think I may be misunderstanding this one:

There's a component, `mycomp`, which is checking for an `on-hello` listener. This component is used in the main template both with and without an `on-hello`, and it is detected correctly. There's also a `mysupercomp` component that has a `<mycomp on-hello="hello">`, which is a `mycomp` with a hello listener, so should't _all_ `mysupercomp` instances have their `mycomp` detect an `on-hello` listener?

**Comment by ceremcem** [comment]
From the point of view of `mycomp` instances which are inside `mysupercomp`, every instance naturally would have a hardcoded `hello` handler (by definition). But if we look from the point of view of functionality, as `mycomp` decides its behaviour by looking at `hello` handler definition, we *should* be able to use same behaviour of `mycomp` while using in another component.

My current workaround is as follows: I'm checking if `context.hasListener('hello')` in the parent component (in `mysupercomp`) and pass the handler to the `mycomp` conditionally: [Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4AlJAYxQEsA3NAOjIHsBbAB0YDs0OUM7mAnkzYACALwjSFGvTQAPdBwAmACmAAdDupTo2ydJBEADTdu0AeAEYBXHZxGcAtGQSUyAazHrwaBAkbeAHymKGYowMAClL5KODgiIWERAMSUAGYiGCxoAAowjKxxiaElKkpo6BRoSiJIIq5Y3GgwAJTF2hG+GGhFWiVhKhyMKCLlleg1dQ2KzW19ScAA9Om9YeaLNnYcwX1GeCGclByUKIZp1hzSnCoUci0a81QZNyhydGBIGAAylI1cMCoAORgXz+QF4EQoGDWNAte7tHRgX50booIFZZi5fKscGQ6GwgDcxRwIXwISUqCQZwuVw4KnhjxgFWsMA4IgeYW0GKxBTOSAQ3WJpM0ODmmikVFoDBY7C4PD4ggw1lYzWErHEknIktkCm4qg5OjQelQaEMJke5iUNEyKAECDQXhAlkYMHKMEMACZWHJRp8QTVLMgPASRMwkDAAOZHQwARiNIdYSCUVo4EdjAAZvSGrRhWMgBIYjq4uI5A4wPEEEeZBGr2cBUhkAAIoJF8CMVADCnHQCnp70+Pz+zSBIL8jEBLTiTlH-kdM4CIAiyzScUCESiMTi6xrMp2a0WVuoe5Q5tFpg4XAA7prpLQ1CFfIZAc6lAJwSFdHmTWbitWhDKHA4Rx50dFtmjQIIAAlPhEed6l+GYYG3f82GPCwd1EQJoIwEQADkAHlYNBRh4KHJDFgw1g0JQP8lRVGBa2nYjQJBJkoJguDpiacjFWVVVd1-Xj6LVLCYIIoix1IxDkLo-jUJCPYEj6ThDANbQwKZalLioa5bgZTkUH5Zo0WBNA3zFEoST6KzRVwIA). 

I think this behavior should be the default one.

**Comment by evs-chris** [comment]
After pondering this for a bit, it's still a bit chewy. The inner component can't really check for an `on-hello` above it's own template, because the corresponding event is no longer `hello` beyond its own template because at that point it's `mycomp.hello`. I _think_ the best solution to this would be to add events to the set of component registered attributes in some way so that they can get yielded through correctly. That would let the `mysupercomp` pass its `on-hello` through to `mycomp`, where it could then be detected correctly, though I'm not 100% sure how that works out with crossing contexts.

**Comment by ceremcem** [comment]
So can't a component pass any listener to the child only if that listener exists? It can't be that easy, but my first attempt is using a regex for this purpose: 

```js
template.replace(/(\s+)(on-[a-z-]+)=(["'])([a-zA-Z0-9]+)(["'])/g, 
    '$1{{#if @this.getContext().hasListener(\'$4\')}}$2=$3$4$5{{/if}}')
```
[Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SAbAhgFwKYGcUgL4BoQN4AlJAYxQEsA3NAOjIHsBbAB0YDs0OUM7mAnkzYACALwjSFGvTQAPdBwAmACmAAdDupTo2ydJBEADTdu0AeAEYBXHZxGcAtGQSUyAazHrwaBAkbeAHymKGYowMAClL5KODgigcFaoSkRAMSUAGYiAAIoYJR8AOZoKADCnOgKKgCUdGBIGAAyhYpoMCoA5GC+-p01cQASAKJNTQDyEb4YaHEcjI49fowRAPRZcSFh6Vm5+YV0JeWV8ii19Y0tWNztXZmMjP1xAGLjk8DTszjzjvcrwOtMptkhZVjY7BwktojHgQpxKBxKChDJlrBxpJwVBQ5DUNCCqNksSg5Bdmq0bh1ur1HngRCgYNY0DVcVsUvs+DMzp0MCw0AAFGCMVidWn0xk1ADcrJwIXwISUqCQKLRGI4tTxYRgpWsMA4Ig1KW0POY-MFrBRSAQM2lss0OBqpg4UiotAYLHYXB4fEEGGsrHawlY4kk5BdsgU3FUBt0rH0aEMJnx5iUNBEWAECDQXhAlkYMCU7UMACZWHIRAqMD0lCJLMgPBKRMwkDAigjDABGNDMBusJBKFMcIodgAMpYbKYwsaQAkMCNcXEctcYHiCrIsgkDIh6AgcHEW1OzS383l3vwe2cszaCESiMTi5lWG-dUJSD5T1BfRjoWqnZDQKlWFR1HUDAAGoahUJwAG0kEcAAvRwAF1wLEFQoO8TpEIgmD4IAQUcAAtYdHAATmQ7CMKw1YilpNcUE6AASdsdmyPICmKUoKh4U5zgaMlri4DpgMYgAWYSBhwBiizEBiAGYGJEhiAFY1g2HB+jtB0tA4LgAHcQ2kWg1BCXxDE6XMlAEEUQhjOME1Zcwn1EJwj0YbN8naNAglA1zQIfJzWBfdchHdBJ92WRx-JCtggpQRyBF9f0YE3FyD28DytW8nzqVpRxHHmGtmyixKA2fByfT9UrnL3S8YHcnpMpAQI8oK1zaVA0DauKyrkrKpMKqSwNmvyxgtxykQWtGrrHwSnqhpCGERDhDhDANbQMvjERUXRKhMWxFl8W0S12i5bcNPxGVkku+1cCAA)

**Comment by ceremcem** [comment]
[...yeah](https://gitter.im/ractivejs/ractive?at=5b4fb6f2f046ba6aca6318cf), moreover, there is an extra complexity in the process. If we take a look at [this example](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAZ3gEoCGAxgC4CWAbggHQkD2AtgA4MB2C7ZutAZgwYACALxDi5anQQAPMlyQAKYAB12KsvNYAbIvMhCABmo0aAPACMArpo4A+E2VNlgwAMQU+QgAJkwFXhYiGEoibV4SK1wyZgwMR2cNVztI6Nj49Scs1wRwhDiErKTgAE8KXKQ4oULigHpPAsznVxLGxJd3Tx9GblkyWjAiXAAZAPlOGEUAclxchHIprCEyGCsEAEo2oqyzXCD2IWiS7QQRFRBGbQYYAxhkc7tFAHdrgGsKdhR1s1q9onYHE1ssB6nwtuZatZbADDFhHBw7uwkAgbkI+FZ2JIOIpyDJ1qogVRgkISKISWQZLQ0GQAArBLhkRQrNbrADcJNodz4FDuZOZCHZhVmZAAkr0YETtIpFOtRHYhAT2n4ArQiEglFMZFM2TVNP5eNy7tNZicFksSEtlbxqdMtesdUDsEIAIwABndDo02EcSD0RAM6MxlGx+MKdzIVhgB0V2xkBldcKBGhKBnOyL4RCs2icIEKGS9agw6xM7AklBo9GYbE43FwAG1zrgrCwUQBaAQMc4AXTJZaktD6CmUji0LF0+iMhTMHaEJTOeGbKJgMHO1STHQ8Xm8PXkcgGQ1G0S4KONczN-M2GA4rZN8zI84A+rfyOdXKDwVlAe1XG4giEKGEJJRDETAfs4UIxAcjAYmQCrADIYEdLUf6hNoH4-B2X5kLC8LsAYMYaE+Z5kAGGJYuwOIUkstA0cEKC4KG65EjAJJkriVIILS9LcEyqwbOyJCcgghoIHyfGsrqVr8DyCCnqaZCLCS1G0TA9Gelk+ZkBkRYlpwTziKQ5ayTGuQGFMFgMEgJSLCOCA6HoCAGMYQJmGAABMdgAMJ3HoHwoIci4wK2jCsBwDK4D87lYeYLDRVkACCAUtkFIXVgyJL-EIFiidYFDaEgyzCIOSJCP8DB+CiJJVmF3BZSUQgsDYlCfEIFCwZJDDUmAlVPG1YCHMwonld1LGpTVPBLEEuC4H5pVAWkTANcEqGlSVuDCBwtBru0AAq+pCAAEgA8gA6jtR1CMiuAkDAFDZbgQhgAw+kxA1MAMEEKAOcs3VCAgNC1llnFPAgXA-XZW1TshcWuQAzHYHaRfDU5ZnFxRuAgpD9fFy5ECUiiw5eurmNoFBo9s06CNt2zfu4GInNNPgfMiMiiCIYjeLo0SIe0GjXs+96NsR9y5uutO1PTCDTXEdgWGQ0bAN4zOyHEGGCPKRCtbg+HAKqPNkD8pPk2+mMkGA6ES9oMNgPDTbJe2ghIzDqO6j+pvY7j+OE-rZhG8TOx222M7+80dPsAzD1K0ishsxzXNaZpvPbPzxHzgLIsh8CEvh1LuAy3LCtRyzqu-IFDsMBrWs63ricU7UfvribWMWy76iZDhmQcPhQrC0gpFBhQ2K4kskqMe07HCtMqqKaPeaONp6yYEAA), we have to define a MITM event which would mislead the regex: 

```js
Ractive.components["super-foo"] = Ractive.extend({
  template: `
    <foo y="superrr" 
      {{#if @context.hasListener('select',true)}}on-select="_select"{{/if}}
      >
      {{#partial custom}}
        button count {{x}}
      {{/partial}}
    </foo>
  `,
  on: {
    _select: function(ctx, ...args){
      var c = ctx.getParent(true); c.refire = true;
      this.fire('select', c, ...args);
    }
  }
})
```
Here `_select` is not meant to be declared if `select` listener does not exist for `super-foo` component. Thus, my previous regex won't work for this case as it will always detect `_select` listener declared.

There are **3 different** handlers here: `select`, `select` and `_select` (yes, first two shares the same name). First `select` is what `super-foo` listens for, eg `<super-foo on-select="blahblah" ...`, second `select` is what `foo` expects to listen, third one, the `_select` is actually the first one with MITM applied to re-propagate the `foo` context. 

I accept that this is something we should handle manually. Less magic is better, that's why I'm going to close this issue.
