### ISSUE TITLE
RFC: Make Ractive check for default members on non-instances and use those automatically.

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3256]
This is basically a continuation from here: https://github.com/ractivejs/ractive-bin-loader/issues/1#issuecomment-403348494

When an ractive component is lazy loaded using the ```import()``` command then in order to access the instance you have to do ```import('./component.ractive.html').then(module => module.default)```

**Comment by evs-chris** [comment]
This is now fixed on edge because, amazingly, I got travis to publish with a new token first try. I'll pull it to 0.10 soon. Thanks!

**Comment by kouts** [comment]
Thanks @evs-chris !
