### ISSUE TITLE
Invalid return type of extendWith method

### ISSUE THREAD

**Issue by ramik91** [ractivejs/ractive#3259]
## Description:
There's an invalid signature for **Ractive.extendWith** method. It's return type is **void** but in fact returns a child of **Static<Ractive<Ractive & U>>** type.

Invalid typing causes problems when developing in TypeScript.

**Typings**
https://github.com/ractivejs/ractive/blob/dev/typings/ractive.d.ts#L1016
https://github.com/ractivejs/ractive/blob/dev/typings/ractive.d.ts#L1487

**Actual code**
https://github.com/ractivejs/ractive/blob/07627511b01e19cc31f01698ebe7afa6f88aee37/src/extend/_extend.js#L26#L28

## Versions affected:
10.0.0 and higher

## Platforms affected:
All

## Reproduction:
```typescript
// widget.ts

import {Ractive} from 'ractive';

class Widget extends Ractive {
    myFancyMethod (value: number): void {
        // Do stuff
    }
}

Ractive.components['widget'] = Ractive.extendWith(Widget, {
    template: '<div>Widget template goes here</div>'
});
```

**Comment by evs-chris** [comment]
Once travis finishes travising, this will be fixed on edge and v0.10-dev - to go out with 0.10.9 when it's cut. Thanks for the report!
