### ISSUE TITLE
Using this.set() inside a transition breaks completion

### ISSUE THREAD

**Issue by ilessiivi** [ractivejs/ractive#3260]
## Description:
When `this.set()` is called inside a transition function, the returned promise doesn't get resolved or rejected, though the new value will be set correctly.

After setting something in the transition function, calling `t.complete()` to finish the transition will not resolve or reject its promise either.

## Versions affected:
0.10.8, edge

## Reproduction:
https://jsfiddle.net/wxc00vup/117/ (no animations here, just console logs)

**Comment by dagnelies** [comment]
It's quite unusual to set variables inside transitions ...perhaps it's not intended/supported.

After all, the transition is triggered by setting a variable. If this in turn sets other variables, it could trigger some kind of complex async chain reaction.

What's the use case anyway?

Usually, you do things more like`r.set('foo', 123).then(() => r.set('bar',234))` when you want to set data before/after a transition is done.

**Comment by evs-chris** [comment]
I actually ran into this the other day with a less traditional transition, but in my case, it was fine to run it in `setTimeout`. It should probably at least not get stuff hung up when you _do_ touch data within a transition, even if it isn't meant to be done.

**Comment by ilessiivi** [comment]
This is my use case: when an object gets spliced from an array, I'm doing an outro animation for its element with a CSS class that is added using this.set() and I need the element to stick around in the DOM for the duration of its animation. It removes some duplicated code from the splices when the class is handled in the transition. I also have a bit of logic for cancelling other animations with another this.set().

If what I'm doing is not meant to work, it would be great for this.set() to be rejected with an error when called in a transition function. I can probably use the built-in t.animateStyle() here instead.

**Comment by evs-chris** [comment]
This should be fixed in 0.10.9 and edge as soon as travis finishes travising. Thanks for the report!
