### ISSUE TITLE
Inconsistent lifecycle events order (teardown before unrender)

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#3265]
## Description:
While further debugging #3263, I noticed that lifecycle `teardown` event is called **before** the `unrender` when the component is inserted via template syntax (ex. `{{#if ...}}<MyComponent>{{/if}}`.

Order is correct when instance is manually rendered via `.render('#somewhere')`.

## Versions affected:
0.10.10-build-3 (reproduced also on 0.9 and 0.8)

## Platforms affected:
All

## Reproduction:
[Inserting via template](https://jsfiddle.net/tjad589u/44/) – ❌ teardown is executed before unrender
[Inserting via manual `.render()`](https://jsfiddle.net/tjad589u/42/) – ✅ teardown is called right after unrender

```javascript
function logCallback(name) {
  console.info(name)
  window.r.push('eventsLogs', name)
}

const MyComponent = Ractive.extend({
  template: '<h1 as-myDecorator myTransition-in-out>Hello there {{label}}</h1>',

  transitions: {
    myTransition(t) {
      setTimeout(() => {
        logCallback(`transition ${t.isIntro ? 'in' : 'out'}`)
        t.complete();
      }, 500);
    }
  },

  decorators: {
    myDecorator() {
      logCallback('decorator added')

      return {
        teardown: () => {
          logCallback('decorator teardown')
        }
      }
    }
  },

  onconstruct() {
    logCallback('construct')
  },

  onconfig() {
    logCallback('config')
  },

  oninit() {
    logCallback('init')
  },

  onrender() {
    logCallback('render')
  },

  oncomplete() {
    logCallback('complete')
  },

  onupdate() {
    logCallback('update')
  },

  oninsert() {
    logCallback('insert')
  },

  ondetach() {
    logCallback('detach')
  },

  onunrender() {
    logCallback('unrender')
  },

  onteardown() {
    logCallback('teardown')
  },

  ondestruct() {
    logCallback('destruct')
  },
});

// if you change your console context to "result", you can interact with
// your Ractive instance with the glboal "r"
const r = window.r = new Ractive({
  el: '#main',
  template: `
  	<h1>Component lifecycle</h1>
    
    <p>Teardown should trigger after unrender.</p>
    
    <ol>
    	{{#each eventsLogs}}
      	<li>{{.}}</li>
      {{/each}}
    </ol>

    {{#if showComponent}}
    	<MyComponent label="{{label}}"/>
    {{/if}}
  `,

  components: {
    MyComponent,
  },

  data: {
    showComponent: false,

    eventsLogs: [],
  },

  oncomplete() {
    this.set('showComponent', true).then(() => {
      logCallback('completed setting the component visible. Now hiding.')
      this.set('showComponent', false)
    })
  },
});
```

**Comment by giovannipiller** [comment]
Also, I'm not sure if decorators and transitions should teardown/complete after the component's teardown. I think so, but it might be worth pointing out.

Edit: [from the doc, it looks like it's fine](https://ractive.js.org/legacy/0.9/api/#ondestruct), although decorators are not mentioned there.

**Comment by evs-chris** [comment]
This is some slightly weird territory. Managed instances tear down like any other vdom node, which means they unbind (teardown) and then unrender. When you manually tear down a component, it will unrender itself before tearing down. The transitions and decorators associated with a given chunk of vdom will only tear down when actually being removed from the DOM, which with a managed component is after teardown has fired.

That's one of the reasons for `destruct`. When `destruct` fires _everything_ associated with the component should be gone.

**Comment by giovannipiller** [comment]
> That's one of the reasons for destruct. When destruct fires everything associated with the component should be gone.

Ok, this clears things up 😊 Thanks

**Comment by ceremcem** [comment]
Was there lifecycle event called `destruct`? I even didn't know about it. I was thinking `teardown` was the last state. @giovannipiller thanks for the issue!
