### ISSUE TITLE
node.setAttribute() calls before node._ractive is set

### ISSUE THREAD

**Issue by paulie4** [ractivejs/ractive#3272]
## Description:
When `Element.statics` were added, there were some new calls to `node.setAttribute()` added BEFORE `defineProperty(node, '_ractive', ...)` was called. This is breaking our `attributeChangedCallback()` handler, since the handler tries to call `Ractive.getContext(this)` to get the parent `Ractive`, which is now failing.

Unless there's a good reason for it to be before the `defineProperty(node, '_ractive', ...)` call, the fix should be as easy as moving the following block of code to be after the `defineProperty(node, '_ractive', ...)` call (see [src/view/items/Element.js](https://github.com/ractivejs/ractive/blob/dev/src/view/items/Element.js#L310)):
```
    if (this.statics) {
      keys(this.statics).forEach(k => {
        node.setAttribute(k, this.statics[k]);
      });
    }
```

## Versions affected:
Everything after this commit:
[special case handling for plain text attributes](https://github.com/ractivejs/ractive/commit/1b58fe544b7fbc023cd3ffea98699363be448b60#diff-1af7602427c785a77ef5894d8bf09b7cR310)

## Platforms affected:
Google Chrome and any other browser if a custom element polyfill is used

## Reproduction:
[playground example](https://ractive.js.org/playground/#N4IgLiBcIDwCYEsBuACBcC8AdEBbAhggHY4B8MA9IkqSADQgDOUIAxgPZGNgoCmANr1y8iYACK8AZigwoA8gCMAVr1ZgAdKwBOvfGF4AKABIAVALIAZAKKDho9QAct7MC4CeD3gEoA3FhJEAkIi4lLqemBaCAoArvoAwgAW+EQA5rxw8fj8-Ar4rADWMiiSMURqCJwGEVGx+gBy+MJ0KOz8cABq2TG8LYEA7l38PV4owP4okygcXDwO+DqixWCJCIyOCyH17HC8KAA++ygASvlgyLzq6WDxnPoAHmAGK2te6lpnF+oCfkQAvr9-HB2KwYnYNDpUmt9FobMFRAYAOSg7jsXAAWgEYERLXGRCmKCcLncnkgfFsIQkkjo-j+vn8-hm3BQHwqSD2sgGJ0+7IMeKwYAFAjJiIAxARiDiJlN9LgHPw9LwRTAUa4MViULg3OiatgQAAWABMZEoqrRmP4YFIUv+vnobBY9sSUFAWhYCv03BAfz+QA)

**Comment by evs-chris** [comment]
Sorry it took a bit, but this will be fixed when the next round of releases are cut. Thanks for the report!
