### ISSUE TITLE
Anchors – @shared properties changes not propagated from attached components

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3275]
## Description:
You have a "component" tree looks like:
- root - A
  - attached component - B
    - component inside mount component - C

**A** set `@shared.sharedData`.
**B** pass `@shared.sharedData` to **C** via template syntax.
When **A** change `@shared.sharedData` it is  correctly updated only on **A** and **B**, but not in **C**.

## Versions affected:
Tested on:
- 1.0.0

## Platforms affected:
All

## Reproduction:
1. Open this [fiddle](https://jsfiddle.net/Lu7oer2x/).
2. You should see `change` on **A** and **B** paragraphs and `init` on the last one.

```javascript
Ractive.components.MyComponentInner = Ractive.extend({
  template: `
  <h3>C MyAttachedComponentInner</h3>
  <p>sharedData passed by attached component: {{sharedData}}</p>
  `,
});

const r = window.r = new Ractive({
  template: `
  <h1>A Anchrome try</h1>
 	<p>@shared.sharedData inside root component: {{@shared.sharedData}}</p>
	<# mount-point />
  `,
  data: {
    who: 'World'
  }
});

r.render('#main').then(async () => {
  await r.set('@shared.sharedData', 'init');

  const MyAttachedComponent = Ractive.extend({
    template: `
     <h2>B Attached component</h2>
     <p>@shared.sharedData inside attached component: {{@shared.sharedData}}</p>
     <MyComponentInner sharedData="{{@shared.sharedData}}"/>
    `,
  });

  await r.attachChild(new MyAttachedComponent(), { target: 'mount-point'});

  r.set('@shared.sharedData', 'change');
});
```

**Comment by evs-chris** [comment]
This one is a bit complicated, but the good news is that it's a form of #3271, so it's already fixed on edge and the dev builds and should be good once 1.0.1/0.10.11 are cut.

**Comment by marcalexiei** [comment]
Great, I forgot to test on dev / edge build...

Thank you!
