### ISSUE TITLE
Events should be triggerable from outside of component

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3279]
## Description:

When we create a component (a complex button, for example) we should be able to trigger it's events as if we physically interact with the component. Currently there are some edge cases. 

Reference: [Gitter chat](https://gitter.im/ractivejs/ractive?at=5bc8ced41c100a4f29a8618a)

## Versions affected:

1.0

## Platforms affected:

Browser 

## Reproduction:

This doesn't behave as intended: [Playground](https://ractive.js.org/playground/#N4IgLiBcIgNCBnKIBKBDAxmAlgNwKYB0GA9gLYAOJAdvtWAgNoDkZAngLSmU11jMBdAAQBeIeix4i+AB5g6AEwAUwADrUhQ+ZQA2aeZCEADdarBmAPOw4AjAK5gwNITS47sGANYjVIDO69fAD5gYCDSej4AXyiLAHpre0caINMwE2oogEpTanUJHAJicipaeiZWTiSnakFRcUxC6TlFFXVNbQo9A2M0y2rnV38Pb18AfWHAkBDgNmx8HQUYoVCAYmwAMyFcNB07fBjQnb2DqNC4zZj4gepUvPTYdpdqQzUNTSEJgM9DDbtqSQ0JRYGRZN4fD5gAAW2AQhA22AATvglMxJp5mLAhMwoQsdCRmDl3pook9SZkiepaAB3BqSAhtd4LQzMGwkBRsTFPTrdfCGDKWChBACSkXo2BohgA6vghNS0PQtCQhBRESQAOaItBkMj6Dy7HRsITorS4oQ3OFCCwICgKoQIMBsHT4Hx+Ej4xGGZEKYKhagkeRXOI2hVBeJC3KWazcUp8Z5uEaujYkEjBPpgKxVBw1ITYBSu3FsNjBAAS2FN+GRAEJ4olsyk0rXODHePQ7lGs8kNENvgXsL5c-nfCRPGhi9MwIjsOr1ZW0DZneb69Qm7Zl+2V1CAExBACiMgo+Cw+AU8W3dwsQplzAUQlkh6wSvt+FlW6Eu0rDCECO9z3fFAoIREX+LFeFzBB3wgzY5VldETyEXwywrasBxuUDoUrcDINzLZqVg754N8Sdp1nLUF3wVDl0IK04gjPJNx3FB8AQOwdAzOJz3US8ggAFVxZF3wE-132dREvx-eC0CgrZEPLDCUJAJcuywuDT1ou4jEed5JRWJ5NGRagFErX5-kBahgTAUFwQ+MwEHwMAeOwMh8BIBwlCULJRCCXTiQhU1YUIOywFRf15ExbFCEi-R-IgshyD4Qk9L86EAoRQyAEEdB0ABhEpWwYDz4RIRFd0wKF3NBLyfL8vzNiUGRCFnYLmDzQlRBEMRmBHMdCWsmqIQaiTUS+EZEt8-qhAaoLUWOfZwpaiDVLGiaSSSmq6oaprUVazyOs6wtOTBNb+sGpEUWYEavGWlbNCm+yZt2OasQW40CIUa6JvJY6SSJGqoixABGAAGEHfo+f6kphEyARwIEQSO8aRM-VE8PtMchBhKsPqECHfOTEhobMiyrOOj8xKUIiYUWhVmDAc1ZWImdK3gjY1TIFwHAQPMKJAMHVveclsjgPxkGFqEoFARFkF5B0QBiIA)

This is workaround version by @evs-chris : [Playground](https://ractive.js.org/playground/#N4IgLiBcIgNCBnKIBKBDAxmAlgNwKYB0GA9gLYAOJAdvtWAgNoDkZAngLSmU11jMBdAAQBeIeix4i+AB5g6AEwAUwADrUhQ+ZQA2aeZCEADdarBmAPOw4AjAK5gwNITS47sGANYjVIDO69fAD5gYDZsfB0FAF9oiwB6a3tHGiDTMBNqaIBKU2p1CRwCYnIqWnomVk5kp2pBUXFMIuk5RRV1TW0KPQNjdMsa51d-D29fAH0RwJAQsIio2KFQgGJsADMhXDQdO3xY0K2dvejQ+PXYhMHqNPyM2A6XakM1DU0hSYDPQzW7akkaJRYGTZF5vN5gAAW2AQhDW2AATvglMwpp5mLAhMwIZEdCRmLlXppog9iVkCepaAB3RqSAjtV6RQzMGwkBRsdEPLo9fCGTKWChBACS9D42BohgA6vghJS0PQtCQhBR4SQAObwtBkMj6DzbHRsISorTYoRXGFCCwIChyoQIMBsHT4Hx+Ei4+GGREKYKhagkeQXeJWuVBBICvKWazcMp8G5mCPVBy1ITYBTO7FsNi+R5uUbOgACsIRSOYaxIeNyMwAEthjfhEQBCBJJROpdJNzhR3j0WNgKwJlIaYafNPYLMp50kTxoTMzMDw7Cq1V1tA2R2mlvUdu2DexzcQgBMQQAojIKPgsPgFAkDzcLAKpcwFEJZGesArbfhpfuhNs6wwhHCnqPD+FAUEI8K-BivDJggP6wesMrSqil5CL41a1g2WZXFBkJ1jBcHJhslJIZ8KG+HOC5Lhqq74FhG6EBa8Rhvke6Hig+AIHYOi9vEN7qHeQQACrYoiP6ib6P6OvC-6AShaDwRsaE1rhmEgOuA74chV5MTcRj3K84pLA8miItQCh1t8vz-NQgJgMCoJvGYCD4GAgnYGQ+AkA4ShKNkohBEZhJgsa0KEM5YDIr68jopihBxfoIWwWQ5B8PixnBZCoVwmZACCOg6AAwqUXYML5sIkPCR6YBCPnAv5gXBcF6xKDIhBLhFzApviogiGIzCTtO+IOY1YKtbJyIfKMaVBSNQiteFyKHLsMWdbBWnTbNRLpY1zWte1yJdX5vV9em7IgttI1jUWE2ohtm2aPNLmLdsy0YqthqkQod2zaSF1EgSjXRBiACMAAM4MA28QPpVCll-DgAJAudM2SX+yLEba05CFC9bfUI0NBaWJBw9Ztn2Rdv7SUo5FQmtcrMGAprShRi51ihawqmQLgOAgKa0SAkNba8pI5HAfjIGLEJQKA8LINydogLEQA)

Chris' changes:

```patch
--- <unnamed>
+++ <unnamed>
@@ -1,6 +1,6 @@
 Ractive.components['my-component'] = Ractive.extend({
   template: `
-		<my-button on-click="click">{{>content}}</my-button>
+		<my-button on-click="click">{{yield}}</my-button>
 	`
 })
 
@@ -21,8 +21,8 @@
   template: `
 	<p>Intention: We want to programmatically click the buttons. <span style="color: red">{{note}}</span></p>
 
-	<my-component on-click="foo">
-		<my-button id="heyy">Hi there!</my-button>
+	<my-component>
+		<my-button id="heyy" on-click="@.fire('foo')">Hi there!</my-button>
 	</my-component>
 	<my-button on-click="hi" id="okay">triggerable button</my-button>
 ```

This is the final goal to achieve: 

```
<parent on-foo="bar">
  <child on-click="something">hello</child>
</parent>
```

Here, 

* `something` is defined in `parent`, which means `parent` uses `{{>content}}` partial for its children. `something` does something, then fires its `foo` which in turn fires the `bar`.
* we want to trigger `findSomehow('child').fire('click')` to fire the `bar`

> This issue is raised originally in `radio-buttons` component [here](https://github.com/aktos-io/scada.js/tree/dev/components/radio-buttons)

**Comment by ghost** [comment]
So... a button inside a button, why is that needed?

**Comment by ceremcem** [comment]
I've built a relatively complex button component ([`ack-button`](https://github.com/aktos-io/scada.js/tree/dev/components/ack-button)) that provides many helper functions and async callbacks within the `context`. I'm using `ack-button` whenever I need a regular `button` as a drop-in replacement.

Now I needed a group of `ack-button`s that will behave like `<input type="radio" />`. Since each button should provide the same helper functions with `ack-button`, I'm using `ack-button`s here. Those `ack-button`s have to communicate with each other because whenever one is pressed, the others should be released. This is managed by [`radio-buttons`](https://github.com/aktos-io/scada.js/blob/788c91ba1f4da59ef50808f952e62cc8c4c53013/components/radio-buttons/index.ls#L56-L74) container. 

In this case we have to have buttons inside a button.

**Comment by evs-chris** [comment]
I created a test case based on the original bug that I _thought_ I saw from that gitter chat, where `on-click="foo"` and `on-click="@.fire('foo', @context)"` were not behaving the same way. I must have done something else to the original playground, because adjusting the one from above to just use `on-click="foo"` does work.

As far as the partial vs yield issue, that's actually functioning as intended. The context for the partial will be the the immediate component and the context for the yield will be the container. This means that with a yield, the event will fire in the outermost container that is yielding, whereas the partial will be wherever the immediate content exists (at the intermediate level, in this case). So the only way to catch the event with the partial version would be to use a scoped event e.g. `on-*.click` or `on-radio\-button.click`.

**Comment by ceremcem** [comment]
Based on [your version](https://ractive.js.org/playground/#N4IgLiBcIgNCBnKIBKBDAxmAlgNwKYB0GA9gLYAOJAdvtWAgNoDkZAngLSmU11jMBdAAQBeIeix4i+AB5g6AEwAUwADrUhQ+ZQA2aeZCEADdarBmAPOw4AjAK5gwNITS47sGANYjVIDO69fAD5gYDZsfB0FAF9oiwB6a3tHGiDTMBNqaIBKU2p1CRwCYnIqWnomVk5kp2pBUXFMIuk5RRV1TW0KPQNjdMsa51d-D29fAH0RwJAQsIio2KFQgGJsADMhXDQdO3xY0K2dvejQ+PXYhMHqNPyM2A6XakM1DU0hSYDPQzW7akkaJRYGTZF5vN5gAAW2AQhDW2AATvglMwpp5mLAhMwIZEdCRmLlXppog9iVkCepaAB3RqSAjtV6RQzMGwkBRsdEPLo9fCGTKWChBACS9D42BohgA6vghJS0PQtCQhBR4SQAObwtBkMj6DzbHRsISorTYoRXGFCCwIChyoQIMBsHT4Hx+Ei4+GGREKYKhagkeQXeJWuVBBICvKWazcMp8G5mCPVBy1ITYBTO7FsNi+R5uUbOgACsIRSOYaxIeNyMwAEthjfhEQBCBJJROpdJNzhR3j0WNgKwJlIaYafNPYLMp50kTxoTMzMDw7Cq1V1tA2R2mlvUdu2DexzcQgBMQQAojIKPgsPgFAkDzcLAKpcwFEJZGesArbfhpfuhNs6wwhHCnqPD+FAUEI8K-BivDJggP6wesMrSqil5CL41a1g2WZXFBkJ1jBcHJhslJIZ8KG+HOC5Lhqq74FhG6EBa8Rhvke6Hig+AIHYOi9vEN7qHeQQACrYoiP6ib6P6OvC-6AShaDwRsaE1rhmEgOuA74chV5MTcRj3K84pLA8miItQCh1t8vz-NQgJgMCoJvGYCD4GAgnYGQ+AkA4ShKNkohBEZhJgsa0KEM5YDIr68jopihBxfoIWwWQ5B8PixnBZCoVwmZACCOg6AAwqUXYML5sIkPCR6YBCPnAv5gXBcF6xKDIhBLhFzApviogiGIzCTtO+IOY1YKtbJyIfKMaVBSNQiteFyKHLsMWdbBWnTbNRLpY1zWte1yJdX5vV9em7IgttI1jUWE2ohtm2aPNLmLdsy0YqthqkQod2zaSF1EgSjXRBiACMAAM4MA28QPpVCll-DgAJAudM2SX+yLEba05CFC9bfUI0NBaWJBw9Ztn2Rdv7SUo5FQmtcrMGAprShRi51ihawqmQLgOAgKa0SAkNba8pI5HAfjIGLEJQKA8LINydogLEQA), I made following changes: 

```patch
--- <unnamed>
+++ <unnamed>
@@ -1,7 +1,10 @@
 Ractive.components['my-component'] = Ractive.extend({
-  template: `
-		<my-button on-click="click">{{yield}}</my-button>
-	`
+  template: `{{>content}}`,
+  on: {
+    _select: function(ctx){
+      this.fire('select')
+    }
+  }
 })
 
 
@@ -21,8 +24,8 @@
   template: `
 	<p>Intention: We want to programmatically click the buttons. <span style="color: red">{{note}}</span></p>
 
-	<my-component>
-		<my-button id="heyy" on-click="@.fire('foo')">Hi there!</my-button>
+	<my-component on-select="foo">
+		<my-button id="heyy" on-click="_select">Hi there!</my-button>
 	</my-component>
 	<my-button on-click="hi" id="okay">triggerable button</my-button>
 ```

to mimic my actual use case: [Playground](https://ractive.js.org/playground/#N4IgLiBcIgNCBnKIBKBDAxmAlgNwKYB0GA9gLYAOJAdvtWAgNoDkZAngLSmU11jMBdAAQBeIeix4i+AB5g6AEwAUwADrUhQ+ZQA2aeZCEADYMAB8penwC+1o7HWaahtRs1CA+gnw78WQwBmAK7UkjRKWDIAlK7u7mAAFtgIhAHYAE74SszevljMUY7u1kUl1NaF1OrqEjgExORUtPRMrJwARkFgYDSCouKYddJyiipF2hR6BsbVYKpgADyd3TRCNFw62BgA1iKqIB4Ymzv7ZqZs2D4KtkKmAMTYAUK4aDpB+LamL28f1qYA9I9bAt-ssetQzLN7EVnLcippDsdtoEQmFqBEwNFYnEtEkUmlMtkjlttsxYEJmAkfDoSAV4UIypoyhVqtRaAB3AaSAhjNw+QzMdokBRsMnjfC6fT4QxGWYLChmACSVno2FhAHV8EJ2Wh6FoSEIKOkSABzdJoMhkfRbV46NhCYk7XFasE0FJCBYICi6oQIMBsXx7ECkGnpQyZBSnUzUEjyYH-L26swghWs+YLdhcRq8PXrXJ+MBBgIkEinWbpzOujTYBRBqlsNj7NbUDYkoMAAVSGSyzC8PgLdJAZgAEthnZkAIQgytdcGQqqLf6Z7hNPjzisdWerdaO3b7JJNmtBkjbNCNodgdLYE0m-Dm9q+IRV6eblYQ1kLBIAJjMAFEZBQBb4AoILfvO8pmJqzAKEIsiAVg+q+vgWpfkIrx3gwQgEsBzZoRQFBCOkITkrwQjJGhCBkU87JaruOH7KO474BOTZViRiR3mRlFoJRjzarRSL0eAV43neaAPvgrFbtQhAev8qZVNQn4-ig+AIEEOiLmB6gQQAKlSmRoYZMZob46SYdhME8VRQgMWOHGTlJb5cQ6gkgfJ87Qm4sLYpomTUAod4oqEODhJEMT0vM3hgLp2BkPgJBdEoShRKIZhwm4OK4skhDRdkMbyGSFKECV+jZZRZDkHwdKZTiiQ5WkAUAII6DoADC2bNAwKWpCQ6S-pgCTJdEaUZVlcSPEoMiELeYDZDWBSiCIYjMCeZ4FL542aNN2HZIiJI1VtcTTXlzDfO8RXMORdEKIdR2Mkdk3TbN823aly0rfWooRbVW07d2e27ndR1CCd+BzWdrwXeSV2UTdwPjWU9JxCyv0MuSACMAAMOOVCjDi1UkwVohiWLI6ZGHZDRvpnkISQTgj1gE3ExYkMToXouFm2aOh5lKPs9Vw7qzBgE+WqXtet4RlhxpkGsXQIDWkkgHjxSlOoFRwMGyBawkUCgOkyBTGpEC2EAA) and *it works as expected*. 

Still, somehow I can't trigger the button in my application. Let me close the issue now and re-open if I find anything. Thanks.
