### ISSUE TITLE
Helpers methods don't have the instance as context when called from an instance method

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3280]
## Description:
Helpers methods have the instance as context (```this```) when called from the templates.
The same isn't true when called from an instance method.
## Versions affected:
1.0.0
## Platforms affected:
Desktop Browsers
## Reproduction:
[Playground link](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYD2AJmgHQBWAjgK5owCeLBgFsqnHvwC0ARhZSATCwAsLIQEsAduwJ4wpCtSpYktANZlUYFgCN69FFhhIytRpuFUbdh06oBmFv4A7KIYHrb2KI5kKhpaIAC6AL542JAgADyMqgBuAASqjAC8ADogKEgwAOZoKKUAfOlUWdl1xept6Ri0MKpkKPlFpehCZMjopbkofGRoJWVoAB4oVI60KDlo9W3FKJk5ubTIGBhzW7XttZfpQnzCZPTqaOr9VK0Xjc1vjV09fW-b6k63V6-QKcxudweTxQAH1hqNUJsQJNprMhotlqt1tkkf9ds0DkcTqUYPQAO5bC47PZ5Q5IY5zBgICQYITSOSUnZclDAYBwgAUAHIABIAUQAMuKAPKCgCUiUS2yuTRyrUuSo+qrauVyNMJ9OJIFJFJAbx11IJdIZpSZLLZ8kpOvNuysXFIDxRMzmrvd7WRVsNVhQ6lyQfUEmYADMkFwELVkQ8JIdVKY5oRBQh6JUYWA0AhM4L4vUAMIIFMmSb0XKZyq5XkCkUS6VyhWNH0oB51XLap069Ltj1TL2lAd+-XWkBh0PBiNoaOx+O5RPJ1OlAACKDAqgwLBrMPU9BhMEwC4w-NlJbLpkr1azdb5KCFADkpTCAEqigDKAFVxQAVT8W0SNs3Q7dQzSdTUWh7KCvkMYE-jaXB8HgN9jGxVhcwQGYYB3OFckKXJIy4dQ1lUB5+TsGBZWAHtjxQLgYBDTdtxYUk7BYapH0FOEWEFABqKjZVyAB+SYtx3diUE4mohV4gShNySBckFPlgAUyJ+MFRIYUSQUAG42kVdp1GyCpcnMaoYUYVAkAIusezhZTaJDJ0xUlKVlJFPNM1yMl6BgBBGAAQkFHAex1F93y-X8AK8p8q2PDBTyI+gSMYQUe2M4y2jQsicUEegRihZ4dwhIr7keZ57LyjCWAxJ5GH5Fze23egxjQRhlOjBAMDQcLXJ1eEOq8gBicriqq2FhsRMKIqXdRnPm3s9ywzN+TWBYaOW3sDhQBYWAC1RKg0JAEBYMhjxxZ4ABE5xjONz0Mwbdp1Bh1AwdrWBrflao2FgsJwvDuPc5tZVlZ7Xt7d7PoQb6s35Fid0B3hgaFUGZXBnadWM3tkh7HY9wPI8TzjM9tpeoaJPq67pKOk71DOi6ruhO750eiGdphr7dwRv6CpR3CWAbKKPx-f9APByHdu5uHecqRHqcFtHBVFmKJblTmXuyrW2jMmBcixDZ7MeMlcn5tBmp7coqhqMaba4ubXJm9B7bQEYOqdnUbPKZTLLQazbKMiHkNoeA11UYqYH6RiEH5UpdHISgaCMUxzE3axwm8ZxXEKkRPAiKI-ACFhgloY4wi8SInBiNxjlKLXBEYz6YAke4NHQA3gFoZuAr9+gO94fTEhARIgA)

**Comment by ceremcem** [comment]
Pardon me, but, can't the reproduction be reduced?

**Comment by kouts** [comment]
What do you mean by "reduced" @ceremcem ?
Do you mean the title maybe?

**Comment by ceremcem** [comment]
I'm trying to understand the problem (just for the curiosity) too but it seems a little bit complex to me. I'm sure that @evs-chris or @fskreuz (and many people) will spot the intention but I'm just wondering if it might be reduced in terms of complexity or not.

**Comment by kouts** [comment]
The problem is simple, helpers methods (```Ractive.helpers```) do not get the instance context as ```this``` when called from inside instance methods.

**Comment by ghost** [comment]
So, as per usual JS rules, how the function is called determines `this`. 

      console.log(Ractive.helpers._t('NO_RESULTS'));
      console.log(this.helpers._t('NO_RESULTS'));

By just eyeballing, `this` in both cases would be `Ractive.helpers` and `this.helpers`, respectively.

Ractive does set the instance as context [if you call it inside a template](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYD2AJmgHQBWAjgK5owCeLBgFsqnHvwC0ARhZSATCwAsLIQEsAduwJ4wpCtSpYktANZlUYFgCN69FFhhIytRpuFUbdh06oBmFv4A7KIYHrb2KI5kKhpaIAC6AL542JAgADyMqgBuAASqjAC8ADogKEgwAOZoKKUAfOlUWdl1uPjw6mgA7rkASsYoOWgAFMDF6rm55VU1kLkA5ADE09Uo8zjjk+hCZMjoc-PAwFxkZLzDAGa2AJSJieubuYyoSHPAuVf0B1YV87nJjzAaAQZxglFyYwmk1yJ1BuWGuTy1whj2huQY6gw9AQrAQ9EqwxQYFUGGuqOhMBqXBgE2yLBQ9AAqqdeABhJAYEbXADc5MSj356kSPLatHgAAFVDt6DAUDCYAhhqVdORKDQjKZzETrOFvM5XIJ6CJPBEon4AixgrQMKETXqYm4baUeeNBNSsTAJGR6Bp0DAIbR3TK5t7fbxuYkQIkgA):

```
new Ractive({
  target: '#target',
  template: '{{upper(foo)}}',
  data: { foo: 'bar' },
  helpers: {
    upper ( v ) {
      console.log(this)
      return v.toUpperCase();
    }
  }
});
```

**Comment by kouts** [comment]
Yes, I know, I think it should be the same as if you called it from inside the template, no?
Or else I'll have to do e.g ```Ractive.helpers._t.call(this, 'NO_RESULTS');```

**Comment by ghost** [comment]
Nope, you're calling the function directly.

I don't think it's a good idea to "pre-bind" the context when registering functions. Imagine if you assigned a function from somewhere else (like a lodash function) to Ractive's helpers, and automagically it would have a different `this` value. That would unnecessarily complicate things.

```
const someLibFunction = function(){
  console.log(this)
}

// All you do is assign. Assuming auto-binding was a thing...
Ractive.helpers.someLibFunction = someLibFunction 

window.someLibFunction() // this === window, guuud. direct call to a global is window.
{{ someLibFunction() }} // this === instance, totally makes sense since we're in a template
this.helpers.someLibFunction() // this === this.helpers? where is this called? what's `this` in this call?
Ractive.helpers.someLibFunction() // this === ??? called directly, from anywhere, in or out of instance.
```

I'd stick with not autobinding and let the caller decide what `this` is. If it's Ractive calling (i.e. from a template), it will most likely set the right `this`. But if you manually call the function and directly, you're responsible for what `this` is.

**Comment by evs-chris** [comment]
Just confirming waht @fskreuz said. Unfortunately, there's not really a direct way around this, as once a function is bound, there's no way to bind it to anything else. That means that inherited helpers would have the wrong context. Using helpers in a template is a bit of a special case that sidesteps the issue with `call` behind the scenes.

I think the least painful solution would probably be to add a helper method to the ractive prototype to cut down on some of the `call` boilerplate for you e.g.

```js
Ractive.prototype.helper = function(name, ...args) {
  return this.helpers[name].apply(this, args);
};

// later
r.helper('_t', 'NO_RESULTS');
```

Although it looks like this specific case may be internationalization of some sort, which is probably used a good bit and could use its own method:

```js
Ractive.prototype._t = function(str) {
  return this.helpers._t.call(this, str);
};

// later
r._t('NO_RESULTS');
```

**Comment by kouts** [comment]
Thanks, @evs-chris I'll try what you suggested!
