### ISSUE TITLE
How to force update function calls in a view, even if the actual model has not changed?

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#3283]
I'm using i18next for localization of my app by adding it to all of my Ractive instances somehow like that:
`Ractive.defaults.t = i18next.t.bind(i18next)`

Rendering texts in the template looks like that:
`<div>{{@.t('menu.title')}}</div>`

How can I force to update the text if the language is changed?
Unfortunately calling `instance.update()` won't do, because Ractive doesn't see any change in the model.

Is there a more "ractive way" you can recommend for doing internationalization in Ractive apps?

**Comment by ceremcem** [comment]
Not an exact answer, but maybe related with: https://github.com/ceremcem/ractive-i18n#current-method (see @evs-chris' resolution)

**Comment by evs-chris** [comment]
Yep, [this](https://ractive.js.org/playground/?file=i18n.js#N4IgLiBcIgNCBnKN4GNlxACyqATlAHYCuANqfEpANogD0dqAJoQHQBWCTApqQJYA3PK0LcwdQgAcAtnTwBDVGEHcAAtyYBzbnMXKB3DggD8ARhABdAL7xpUU-ABmVaqELzp3ZH0I8AHqwKSiqsWGDSpJioAPaEYNxxyAA8CLzcSgAEAvKkxNwAvAA6IMDAqghY8ngarHymABxspPKEmlZWxRmxALSola0FxeWV1Uy1DU3R8kwAFKqE0Tys2bncAJTFAHyFhBkZSdGSyrFZOXlFJcDEvtyOPhrtWzMAIrfyZGBrSXSHx4Tbu32vz4sU2pgAzOCAOzfYGgnZ7A5HEH-ABi0Tw0hysOR8MBSL+mwAavJNHkcYSdt9UqR0mAAVSsKZNgAJXikaKwfYISQtTalOqNGbuTwZAA+YoyAHIAEp6FRStbtam8-4AQm+TIZhBSqDwfCOAL2fGkkgxYAygt2jjw0Wk0tYdCtRilAG4ERkPTFCAgLQBBSSSDL5DJy4IGVjcPzxXwzYAevbEVKQDLUK0zNYWWAJjLxU3NeIpgAkABUAKIAWQACgAZP3l7OAvaoBAIYsAYQAyp3G3tm62AJJMFNS+SBqUeqxrd2EL2xX0ZMdBkMAdx8TGiK9YS+DGVEK4yAckcZzYCq2jAI4ARosAJ4TwFTmfUvUG+k7Km+2+0o0ZJkZYAMhiDk8BTABiAAGCD6gaeRXQyDodToL8fx2EAbDcDwvGgZ1OCiWIYwgaBaQtDlpg0XdHByVIZx2KMzTwC0eCoj4Mkca5ghOSRck0HwZl+BA1gAj8wGqMBiDwa0OL+ONQ3lAwuR8X0WlQbgEKE+Mm0tH0z0IVTQl4SRuDwBBqH4o4EHFSVgCnEQsKs6UrSlCxdxmX08CE-JNmErTm3nUiWk0Xcw30QwKiqDQAHExBmKVnWaVpFRnPs+29BcsWXOTwzCkYopigADZ0MtYItgAStp8unHNjUcDIZgyjIADJGoydztIyDKhLEiTdgy6h3IsZKUoyXhUh84a+z4Wr6rHJqWpCkJnjLAAhABVSKhLS6JaVYFcqkIGZ8oAOWiXMFB9AsUUXbI+GaK9aTYjFpVK9yrCldrSvKqxKqGibusk1rRN+vtEJSxCcymuq1TIngmA06qMhhiiQ1EvJgcKMAFojcLRk7GK4omVgYalLlyuDbzNImvydI62aQyxnKIqYaKwEOoqxxKsrAu+qrfMm6a1U68aqZquqyfyCXpQhaFFSy0LWBxjQ8dZwrCeKz7ufyrlAIZkcZQAFlQKFTCJbgpSfBGUtGtTIZmcXJaldFMRyWXUjAEsTW4aJiFZjNyblkJFaYZW2bVjmNdab7tYDgwR07Pg8Bjs2py5cEoIg3mRb2a3LWm+2QylEkyTNoS3Y9zxvd9zzvIZhXcuDgr2ckTmvq1gCk71+TuG6PgKnNtYuVMdPM6p0G+wxi2tLHqwZysdCsxAW5vBuAIgnlsIInQoA) is how I'd do it. You install the plugin with `import i18n from 'wherever/you/put/the/code'; Ractive.use(i18n());`. To change languages, `Ractive.sharedSet('i18n.lang', 'lang-here')` and you can also reference `@shared.i18n.lang` anywhere in the template.

To answer your other question about updating a function, from 0.10 (I think), you can `instance.update('some.function', { force: true })` and it will cause all references to re-evaluate.

**Comment by LeJared** [comment]
Thanks!
The `Ractive.sharedGet('...')` did the trick. I simpliy put this as a dummy-call into my wrapper for the `t()` method without actually using its value. This way i can notify all Ractive-instances to update its text by `Ractive.sharedSet('..')`-ing this keypath whenever i18next change the active language.
