### ISSUE TITLE
Detect browsing between routing URLs?

### ISSUE THREAD

**Issue by washamdev** [ractivejs/ractive#3287]
## Description:
Is there a way to detect when ractive is used to browse between routes on a site? For instance, on a site like roncaauto [dot] com, I see that the URL is changing when I click the links in the nav menu, but after looking through the documentation, searching Google and StackOverflow, etc., I don't see any event to tap into to know when the user browses between routes or pages on a site.

I tried tapping into events like activate, deactivate, teardown, etc.:

    ractive.on({
        activate: function () {
            alert( 'Activating' );
        },
        deactivate: function () {
            alert( 'Deactivating' );
        },
        teardown: function () {
            alert('Teardown');
        }
    });

But I never saw an alert. Is there any way to do this? Thank you.

## Versions affected:
v0.7.3

**Comment by ceremcem** [comment]
I guess it's all about a webapp that uses History API. There was a [discussion](https://github.com/ractivejs/ractive/issues/3134) which covers the case.

**Comment by evs-chris** [comment]
It looks like that site is using page.js to change out the templates used in a single ractive instance. You could probably attach a listener to the page.js instance that is managing the page to get notified of navigation.

**Comment by washamdev** [comment]
Thanks very much for that valuable tidbit! I was under the impression that Ractive did routing too, so thanks for dispelling that, @evs-chris!

For anyone else needing an answer, looks like `page.exit` is what I was needing. If you add a callback to `exit` for all routes, it will run each time the user browses:

    page.exit(function (ctx, next) {
        console.log("intercept browsing to another route...");
        next();
    });
