### ISSUE TITLE
Ractive appending out of order

### ISSUE THREAD

**Issue by tmilker** [ractivejs/ractive#3289]
## Description:
I'm iterating with a .forEach over an array loaded from a JSON file that has been sorted and instantiating new Ractives that are appended(append: true) to the same element on a page.  I've verified that the .forEach is running in the correct order but the Ractive instances show up in varying order, sometimes sorted properly, sometimes out of order.  Am I doing something wrong or is there something I can do to make them show up in the same order they're iterated?

## Versions affected:
Found in 1.0.1, tested the same in 1.1.0

## Reproduction:
I can't reproduce it with a simple example on JSFiddle.  I guess it's something to do with how long it takes Ractive to setup/oragnize/render each one that is determining when it gets appended?  Any way to control this?

**Comment by evs-chris** [comment]
Everything ractive is synchronous, so I'd guess what's happening is that some async aspect of the render is causing a conditional at the root of the instance's fragment to render later than the rest. Is there an element at the root of all of the instance templates e.g. `template: '<div>...</div>'`?

As an aside, this sounds like a pretty strange way to handle this. Is there a particular reason you're not just using an overarching instance with components or anchors to manage the iterated instances?

**Comment by tmilker** [comment]
Yes, the template is a div that each of the instances is being put into.

I do recognize that it's not exactly normal.  This is one of the first projects I wrote in Ractive(that was previously AngularJS) quite a long time ago that I recently updated to 1.0(and today 1.1) for some reorganization of the data it's displaying so it's based on my limited amount of knowledge back then.  Sounds like I just need to put more work into doing it the right way now and not waste any more time on past mistakes.  Thanks.

**Comment by tmilker** [comment]
This is being caused by the asynchronous request for the 2nd JSON file that is loaded and causes the instantiation of each Ractive().  The forEach spins through all of them at once and since these can happen out of order, they get added out of order.

**Comment by evs-chris** [comment]
Legacy... say no more :grinning:. I'm glad you found the cause, and it wasn't something I broke!

**Comment by tmilker** [comment]
@evs-chris Yeah, nothing seems to be broke in Ractive and I got it moved over to using one instance instead of n*instances.  BTW: What's the point where you should use components vs. partials?  The need for local functions?  I haven't quite figured that one out yet.

**Comment by dagnelies** [comment]
> BTW: What's the point where you should use components vs. partials? The need for local functions? I haven't quite figured that one out yet.

Well, basically, a partial is a piece of template. It's perfect for such a usage and has the advantage that it can dynamically be swapped out. The components are better suited for widgets that have complex behavior, that need to maintain an internal state, rely on events, interact with third party libs, etc.

**Comment by dagnelies** [comment]
Typical usage of partials:

- https://dagnelies.github.io/ractive-examples/content/tabs.html
- https://dagnelies.github.io/ractive-examples/content/async_content.html

Typical usage of components:

- https://dagnelies.github.io/ractive-examples/widgets/color-picker.html
- https://dagnelies.github.io/ractive-examples/widgets/ace.html

**Comment by tmilker** [comment]
Thanks @dagnelies!

**Comment by evs-chris** [comment]
What @dagnelies said. Basically, for anything that you need events for or are not going to have a ton of instances, it's more convenient to have a component. There are ways give partials private data and behave a bit more like lightweight components, but they get pretty involved in low-level stuff pretty fast.
