### ISSUE TITLE
ractive.set('foo[bar]', 'test');

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#3292]
If I am not mistaken, something like `ractive.set('foo[bar]', 'test');` worked in the past.

However, it does not appear to work anymore. Did I miss something?

**Comment by evs-chris** [comment]
I believe it only works with numbers. Since bar is a variable, and set doesn't do resolution, `set('foo[bar]', 'test')` isn't supported. I did look at adding simple string support (`foo['bar']`) at one point, but it got too complex with too many failure cases too fast.

**Comment by dagnelies** [comment]
I thought I used in the past for stuff like `set('somedata[email@whatever.com]', {...})` in order to deal with "complex keys". ...I'll have to dig a bit to find back the code.

**Comment by evs-chris** [comment]
You can escape .s e.g. `set('somedata.email@whatever\\.com', { ... })`, and there's a `Ractive.escapeKey` helper for that. I'm pretty sure brackets in a set have only ever supported numbers though. The relevant code in the ractive source is in the keypath utils as the function normaliseKeypath.

**Comment by dagnelies** [comment]
That will do it. Thanks. 👍
