### ISSUE TITLE
Incorrect oldvalue when observing data bound to checkboxes via the name directive

### ISSUE THREAD

**Issue by keosion** [ractivejs/ractive#3293]
## Description:

When observing array data bound to checkboxes via the name directive, callback is called with incorrect oldValue. OldValue is equal to newValue and shouldn't.

## Versions affected:
Any version since 0.8

## Reproduction:
https://jsfiddle.net/7sxu0r2p/2/

## Fix attempt :
In [/src/view/items/element/binding/CheckboxNameBinding.js](https://github.com/ractivejs/ractive/blob/dev/src/view/items/element/binding/CheckboxNameBinding.js#L71), in method handleChange(), line 71 : we should't get value by reference in order not to modify it too early.

If we replace 
`this.group.value = this.model.get();`
by
`this.group.value = this.model.get().slice();`
we get a shallow copy of the array and it works.

I can submit a PR if this solution seems suitable.

**Comment by evs-chris** [comment]
Absolutely! You've already solved the problem, so you may as well get that git credit, right? If you don't mind, please add a test to https://github.com/ractivejs/ractive/blob/dev/tests/browser/twoway.js to make sure it doesn't get broken again in the future.

If you don't have time, I'll pick this up in a bit.
