### ISSUE TITLE
on-click event gets disconnected

### ISSUE THREAD

**Issue by donnyv** [ractivejs/ractive#3299]
## Description:
When a checkbox has a on-click event and a neighboring button also has a on-click event in a list of items. If you try to delete those items the last item can not be deleted because the button's click event is disconnected. Changing the checkbox to on-change resolves the problem. Even if on-click shouldn't be used for checkboxes, it shouldn't cause this issue. 

## Versions affected:
1.3.1

## Platforms affected:
Chrome, Firefox and Edge

## Reproduction:
https://jsfiddle.net/mcke3uas/3/

**Comment by evs-chris** [comment]
There's a bug in check bindings wherein it registers a click listener on the checkbox if IE is detected when rendering, but it _always_ unregisters a click listener when unrendering. That causes issues with delegated events. This should now be fixed on edge, and will go out with a point update on 1.3, 1.2, and 1.1 in a bit. Thanks!
