### ISSUE TITLE
Strange cursor behavior when fire() is used inside a keydown event

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3300]
## Description:
Strange cursor behavior when ```.fire()``` is used inside a keydown event

## Versions affected:
1.3.2

## Platforms affected:
All desktop Browsers

## Reproduction:
[Playground link](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYD2AJmgHQBWAjgK5owCeLBgFsqnHvwC0ARhZSATCwAsLIQEsAduwJ4wpCtSpYktANZlUYFgCN69FFhhIytRpuFUbdh06oBmFv4A7KIYHrb2KI5kKhpaIAC6AL542JAgADyMqgBuAASqjAC8ADogKEgwAOZoKKUAfOlUWdl1xept6Ri0MKpkKPlFpehCZMjopbkofGRoJWVoAB4oVI60KDlo9W3FKOlkreq5uTsACsi0aLl89FwwubS3GPR39IcoYJcAZqowWLnfaAQjFySHUwLIMEwGEmH2OIAAKkgrBMrFxSK8WOkrHcqAcjkcAHJ2VQXGGoGGXB6-Z65Rj0TDqADk-TYXBGk3oFNy6kW-Q0ZDR-1UgMYLDaR0a+3Fx3au0qPWBCA0mDmwGASp5GESiQmuI6hm6vRQBw6XR6fQGcwBQIA+sNRqhNiBJtNZkNeStjOtsk6Tbt+YKpjM5uglhNaMgMBgrc8hBIGOpIvQEBNskgEDxVcB1EghGhtRNXhITGg+HSAO7qOYlsv0Su6vG5NVPPM2tMZ-M69SNM1Gk3d3sWgpzeUFO1oEZjJ0u4PupaetYbLaytUAYjQxjAuQ1mALh3xmRy90j0dKMDrEywfAQbpAQgqlQ0Ehs6KEkFyUgADGQFgBuZf4gezTHkgUZzAwCASBgcYAGwAYBB7WsCOZ5lmKGdoW6jxmAoLVHM7Y8DatA4eo1SMA20qAY0zSNlRwERqBp4gBBUGwfBCG5OkAb9EGt6hrUzoMWBpSfLG8avEmKbOgRt5qkg1QFs6er7lRTQ5LRnFqS00pqlQG7EXuPaGn0dS4Pg8AAEpehsgj0CMrxoImGAsKOwKFLkVmLj6LC8o5jAABTANspATg66Dvoyq6ueOk6OoyODSowqBIO+nxcOoi6vP5ACUQUqbkkIoLchx5RxO6ULkhDxJRuRdkcyTSq876lfiMlESRZGpelmXqP5awLLlNVHAmTw3iwCD0JU-mMgAwh1Xw-GgjCMtl-75XVtVtIkq3bOonneqwwhkA5TksEhuTuftNm+WCgXBfaU4RauSExWFaDxYlyVdRl6xZYN+WFcVTZDbkLZoG26Y8BFjI1RtDX7k1wP5TWFbqN9PV9SgA1IxxaZ3CYF33FjLDPKoj45ggLA1jNTBoGtuMVNyuaXO5-UuTU03oSt9MITQuSIlYuSouihwQlCS0g6onz+QThRy7kACc-0cUc7yqM5GAc4yYMQx28W5IyAtC2iKCvLkYtRktuRm4yADU6G24yACE3Mg0cfMAEJoLQSBcJr1ufDC6tnYt03Ebh70sFHXJUk8dx0pg3J2LkQj0D6HJcjySxCiKbu5Hzwh5omXI7kLgJ1hnmuXKo-Tls8JgaJUedq853yQmH836-1OBNprN5rEtNo7u+bPVCgOXbTzgEbfV0o6rU6iT7teMFdZ6fuTy5YeWvaB3fu5RVDUT0H2PH376Fj0G6uD1xQl+5JeUzU1eV76ECDLUcehEUAFL0GATJ3xViCao75fBwXyvVQBCEP4IS-gbE4vsEBnyAfJNAoDFAgxnrkaq+4uyTzMrQeAAABVQ9kYD9FuAgfypRdDkEoDQIwphzDvGsOEbwzhXC2REJ4CIUQ-ABBYMEWgUYwheEiE4GIbgoylB2m4R4zwJDHQ0OgO4wBY7PHfEoxMvBfyJBAIkIAA)

**Comment by evs-chris** [comment]
I've tracked this down to component event proxying not automatically bubbling the inner event. When you pass the same context through in the fire, you're using the same mechanism that ractive uses internally to proxy custom events, which makes it take ownership of it as if it were a component event - and it consequently cancels the event after firing subscribers.

You can skip the second arg (null or {}) of `this.fire`, and it won't interfere with the event any further e.g. [`this.fire('change', null, {selected_line: ctx.get()});`](https://ractive.js.org/playground/#N4IgFiBcoE5SAbAhgFwKYGcUgDQg1ANrgooAOGkA9FQMYD2AJmgHQBWAjgK5owCeLBgFsqnHvwC0ARhZSATCwAsLIQEsAduwJ4wpCtSpYktANZlUYFgCN69FFhhIytRpuFUbdh06oBmFv4A7KIYHrb2KI5kKhpaIAC6AL542JAgADyMqgBuAASqjAC8ADogKEgwAOZoKKUAfOlUWdl1xept6Ri0MKpkKPlFpehCZMjopbkofGRoJWVoAB4oVI60KDlo9W3FKOlkreq5uTsACsi0aLl89FwwubS3GPR39IcoYJcAZqowWLnfaAQjFySHUwLIMEwGEmH2OIAAKkgrBMrFxSK8WOkrHcqAcjkcAHJ2VQXGGoGGXB6-Z65Rj0TDqADk-TYXBGk3oFNy6kW-Q0ZDR-1UgMYLDaR0a+3Fx3au0qPWBCA0mDmwGASp5GESiQmuI6hm6vRQBw6XR6fQGcwBQIA+sNRqhNiBJtNZkNeStjOtsk6Tbt+YKpjM5uglhNaMgMBgrc8hBIGOpIvQEBNskgEDxVcB1EghGhtRNXhITGg+HSAO7qOYlsv0Su6vG5NVPPM2tMZ-M69SNM1Gk3d3sWgpzeUFO1oEZjJ0u4PupaetYbLaytUAYjQxjAuQ1mALh3xmRy90j0dKMDrEywfAQbpAQgqlQ0Ehs6KEkFyUgADGQFgBuZf4gezTHkgUZzAwCASBgcYAGwAYBB7WsCOZ5lmKGdoW6jxmAoLVHM7Y8DatA4eo1SMA20qAY0zSNlRwERqBp4gBBUGwfBCG5OkAb9EGt6hrUzoMWBpSfLG8avEmKbOgRt5qkg1QFs6er7lRTQ5LRnFqS00pqlQG7EXuPaGn0dS4Pg8AAEpehsgj0CMrxoImGAsKOwKFLkVmLj6LC8o5jAABTANspATg66Dvoyq6ueOk6OoyODSowqBIO+nxcOoi6vP5ACUQUqbkkIoLchx5RxO6ULkhDxJRuRdkcyTSq876lfiMlESRZGpelmXqP5awLLlNVHAmTw3iwCD0JU-mMgAwh1Xw-GgjCMtl-75XVtVtIkq3bOonneqwwhkA5TksEhuTuftNm+WCgXBfaU4RauSExWFaDxYlyVdRl6xZYN+WFcVTZDbkLZoG26Y8BFjI1RtDX7k1wP5TWFbqN9PV9SgA1IxxaZ3CYF33FjLDPKoj45ggLA1jNTBoGtuMVNyuaXO5-UuTU03oSt9MITQuSIlYuSouihwQlCS0g6onz+QThRy7kACc-0cUc7yqM5GAc4yYMQx28W5IyAtC2iKCvLkYtRktuRm4yADU6G24yACE3Mg0cfMAEJoLQSBcJr1ufDC6tnYt03Ebh70sFHXJUk8dx0pg3J2LkQj0D6HJcjySxCiKbu5Hzwh5omXI7kLgJ1hnmuXKo-Tls8JgaJUedq853yQmH836+oXAIAgOBNprN5rEtNo7u+bPVCgOXbTzgEbfV0o6rU6gz7teMFdZ6fuTy5YeZvaB3fu5RVDUT3H5PH1H6Fj0G6uD1xQl+5JeUzU1eV76ECDLUcehEUAFL0DAEyR+KsQTVHfL4OC+V6ogIQt-BCv8DYnF9ggS+oD5JoAgYoEG89cjVX3F2GeZlaDwAAAKqHsjAfotwED+VKLocglAaBGFMOYd41hwjeGcK4WyIhPARCiH4AILBgi0CjGELwkQnAxDcFGUoO03CPGeBIY6Gh0B3GALHZ475VGJl4L+RIIBEhAA).

I'm not _entirely_ sure why proxied events cancel, but it's in the test suite.

**Comment by kouts** [comment]
Thanks @evs-chris , that solved it fine.
