### ISSUE TITLE
ractive cli fails with v1.3.4

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive#3302]
## Description:
I'm building components using ```ractive component -i```, since v.1.3.4 this now fails with error
```TypeError: Path must be a string. Received ReadStream ...```

## Versions affected:
1.3.4

## Platforms affected:
Debian Linux
node v8.15.1
npm 6.9.0
This also fails with node 10.15.3 LTS

**Comment by tolisg** [comment]
Same issue here. 
### **Platforms affected:**

Windows 10
node v8.15.1
npm 6.9.0

**Comment by evs-chris** [comment]
I really need to get a base test suite in place for the bin. Sorry. This should be fixed as of 1.3.5. Thanks for the report!

**Comment by kouts** [comment]
Thanks @evs-chris it works fine with v1.3.5
