### ISSUE TITLE
teardown not called on dynamically-added components

### ISSUE THREAD

**Issue by JohnnyFun** [ractivejs/ractive#3303]
## Description:
I'm dynamically loading in ractive components with webpack's `import(...)` and then using `Ractive.attachChild(lazyLoadedComponentInstance, 'anchor-name')`. But the dynamically-attached child component doesn't seem to get torn down.

The parent component that owns the anchor `<# anchor-name>` tears down when it's hidden, but the dynamically attached child doesn't (example code below).

Docs for [attachChild](https://ractive.js.org/legacy/0.9/api/#ractiveattachchild) indicate that the parent will manage the attached child's render/unrender cycle. Does that cycle include teardown?

## Versions affected:
1.3.6

## Reproduction:
This code demonstrates how dynamically-attached child components don't teardown, but non-dynamically-attached children _do_ teardown.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ractive Dynamic Components</title>
</head>
<body>
</body>
<script src="https://cdn.jsdelivr.net/npm/ractive"></script>
<script>
    Page1 = Ractive.extend({
        template: `Page 1 {{msg}}`,
        onteardown() {
            console.log('tearing down page 1')
        }
    })

    Page2 = Ractive.extend({
        template: `Page 2 {{something}}`,
        onteardown() {
            console.log('tearing down page 2')
        }
    })

    AppRoutesDynamic = Ractive.extend({
        template: `
        <h1>Dynamic page components</h1>
        <button on-click="@.set('active', 'page1')">Page 1</button>
        <button on-click="@.set('active', 'page2')">Page 2</button>
        <div>
            {{#if active === 'page1'}}<# page1 msg="yay" />{{/if}}
            {{#if active === 'page2'}}<# page2 something="yep" />{{/if}}
        </div>`,

        oninit() {
            console.log('AppRoutesDynamic initing')
            this.page1 = null
            this.page2 = null
            this.observe('active', active => {
                if (active == null)
                    return
                // if page component isn't yet attached, attach it
                if (active === 'page1' && this.page1 == null) {
                    this.page1 = Page1()
                    this.attach(this.page1, 'page1')
                } else if (active === 'page2' && this.page2 == null) {
                    this.page2 = Page2()
                    this.attach(this.page2, 'page2')
                }
            })
        },

        onteardown() {
            console.log('AppRoutesDynamic tearing down')
        },

        goTo (componentName) {
            if (componentName === 'page1') {
                if (this.page1 == null)
                    this.page1 = Page1()
                this.attach(this.page1, 'page1')
            } else {
                if (this.page2 == null)
                    this.page2 = Page2()
                this.attach(this.page2, 'page2')
            }
        },

        attach(pageInstance, target) {
            this.attachChild(pageInstance, { target })
        }
    })

    AppRoutes = Ractive.extend({
        template: `
        <h1>Static page components</h1>
        <button on-click="@.set('active', 'page1')">Page 1</button>
        <button on-click="@.set('active', 'page2')">Page 2</button>
        <div>
            {{#if active === 'page1'}}<Page1 msg="yay" />{{/if}}
            {{#if active === 'page2'}}<Page2 something="yep" />{{/if}}
        </div>`,

        components: {
            Page1,
            Page2
        },

        data() {
            return {
                active: null
            }
        },

        onteardown() {
            console.log('AppRoutes tearing down')
        }
    })

    Ractive({
        el: document.body,
        template: `
            <button on-click="@.toggle('show')">Toggle page components' parent</button><br/><br/>
            {{#if show}}
                <!-- <AppRoutes /> this works as expected -->
                <AppRoutesDynamic /> <!-- this one doesn't call teardown on page components -->
            {{else}}
                AppRoutes hidden, so expecting currently-shown page component to tear down
            {{/if}}
        `,
        components: {
            //AppRoutes,
            AppRoutesDynamic
        },
        data() {
            return {
                show: true
            }
        }
    })
</script>
</html>
```

**Comment by evs-chris** [comment]
Sorry, I thought I responded to this right after you posted it, but it looks like something happened that ate my response.

In short, no, teardown is not part of the render cycle for manually managed components. With anchor points, you're responsible for creating and destroying components in addition to handing them to a parent to have a place to live in the template (attachChild).

An `{{#await}}` block or simply gating the component behind an `{{#if condition}}` that isn't true until the component is fully loaded would be the best alternatives if you don't want to manually manage the full lifecycle outside of render. Another alternative would be to add a detached listener in the page components that call `this.teardown()`.

**Comment by JohnnyFun** [comment]
No worries, thanks for the response.

For the suggestion to use `{{#if`, I _think_ I'm already doing that with this:
```
{{#if active === 'page1'}}<# page1 msg="yay" />{{/if}}
{{#if active === 'page2'}}<# page2 something="yep" />{{/if}}
```
i.e., when `active` switches from page1 to page2, I'd want page1 to teardown. But it doesn't call teardown. Or am I misunderstanding where the `{{#if` needs to be?

**Comment by JohnnyFun** [comment]
I think I got it to work by handling calling teardown in each page component's `onunrender` handler like: 
```
if (active === 'page1') {
	this.page1 = Page1()
	this.page1.onunrender = () => this.page1.teardown()
	this.attach(this.page1, 'page1')
} else if (active === 'page2') {
	this.page2 = Page2()
	this.page2.onunrender = () => this.page2.teardown()
	this.attach(this.page2, 'page2')
}
```
I had originally simply called teardown on the previous page component, but that complained about calling it on an unrendered component.

You can close this if this is all expected behavior. Thanks for your tips!

**Comment by evs-chris** [comment]
Since components are looked up lazily, gating the component behind `{{#if active === 'page1'}}<page1 msg="yay" />{{elseif active === 'page2'}}<page2 something="yep" />{{else}}loading...{{/if}}` you could avoid the anchors altogether. Whatever handles your routes would need to check to see if the target component is already loaded and if it is, just swap out the `active` value on the parent instance. If it's not, start loading the component and set the `active` value when it's done, optionally setting `active` to something like `false` to show the loading branch in the interim.

**Comment by JohnnyFun** [comment]
ooooooh, I see! It works. I lazy load the component and then set it on the parent's `this.components`. Thanks!
