### ISSUE TITLE
Binding a variable to on-click causes it to not fire

### ISSUE THREAD

**Issue by donnyv** [ractivejs/ractive#3304]
## Description:
When using a string inside data and binding it to a template. The on click event does not fire. But if you hard code it it works. This used to work in version 0.8.1

## Versions affected:
Latest

## Platforms affected:
Chrome, Firefox

## Reproduction:
https://jsbin.com/holumatiyu/edit?html,js,output

**Comment by evs-chris** [comment]
Unfortunately, this is one of the cases that didn't make it through event normalization with a complete analogue. If you simply want to fire a named event on click e.g. `on-click="foo"`, there's special case handling that turns that into (more or less) `on-click="@.fire('foo')"`. To handle the dynamic event version from prior to 0.9 (`on-click="{{someRef.withAnEventName}}"`), you need to do the fire yourself e.g. `on-click="@.fire(someRef.withAnEventName)"`.
