### ISSUE TITLE
Full html not rendering

### ISSUE THREAD

**Issue by donnyv** [ractivejs/ractive#3305]
## Description:
For some reason the entire html value is not being rendered. There should be a secound `<i>` element.
## Versions affected:
latest
## Platforms affected:
Chrome
## Reproduction:
https://jsbin.com/pefixebato/edit?js,output

**Comment by p3k** [comment]
the dom element `{ el: '#container' }` ractive is supposed to add it’s magic is commented out in your html code:

```html
  <!--<div id="container"></div>-->
```

and there is single quote missing at the end of the style attribute in the `<i>` element of ractive’s data object: 

```js
{ 
  value: "<div style='position: relative;'><i style='color: #cccccc;font-size: 14px;position: absolute;'>A</i><i style='color: #cccccc;font-size: 14px;position: absolute;top: 10px; left: 2px;>A</i></div>"
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^ 
}
```

**Comment by donnyv** [comment]
> the dom element `{ el: '#container' }` ractive is supposed to add it’s magic is commented out in your html code:
> 
> ```
>   
> ```
> 
> and there is single quote missing at the end of the style attribute in the `<i>` element of ractive’s data object:
> 
> ```js
> { 
>   value: "<div style='position: relative;'><i style='color: #cccccc;font-size: 14px;position: absolute;'>A</i><i style='color: #cccccc;font-size: 14px;position: absolute;top: 10px; left: 2px;>A</i></div>"
> // --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^ 
> }
> ```

Thats my bad. I was playing around with it after I posted this. I must have changed the linked one. I'll post a new link with the issue.

**Comment by donnyv** [comment]
@p3k It was the missing quote!! Thanks!
