### ISSUE TITLE
Computed - Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by renattonl** [ractivejs/ractive#3307]
## Description:

In my component, I try to make a logic to compute a variable and I get this error: Uncaught RangeError: Maximum call stack size exceeded.
My problem is in computed variable "lastVersion". I had a similar problem when creating a computed variable called "title" and that is why I have transformed it to a method.

**My error**
![](https://i.ibb.co/PGxQdmx/Captura-de-pantalla-de-2019-07-24-17-10-41.png) 

  ```
import Ractive from 'ractive'

  export default Ractive.extend({
    template: $TEMPLATE,
    isolated: true,
    computed:{
      lastVersion(){
        const {item} = this.get()
        if(item && item.keyJson && item.registro && item.registro.json){
          const all = item.registro.json[item.keyJson] || []
          if (all.length > 0) return all[0]
        }
        return null
      }
    },
    on:{
      async render() {
        console.log(this.get())
      },
    },
    title(){
      const {isPrograma, item} = this.get()
      if(isPrograma) return item.registro.nombre

      return `${item.registro.programa} - ${item.registro.nombre} v.${item.registro.version}`
    },
  })
```

## Versions affected:
0.10.14

## Platforms affected:
Ubuntu 18.04

## Reproduction:
Chrome **75.0.3770.142**

**Comment by marcalexiei** [comment]
I think the problem is:
`this.get()`
You are telling Ractive to recompute `lastVersion` and `title` every time a data property change, which includes `lastVersion` and `title` themselves.

Try this:
`const item = this.get('item')`

Or even better perform a `get` for each property you need:
- `item.registro.json`
- `item.keyJson`
- and so on

By doing so the computed property gets recalculated only when the specific property change.

EDIT added example

E.g.
```
const keyJson = this.get('item.keyJson');
const json = this.get('item.registro.json');
if (keyJson && json) {
  const [lastVersion] = json[keyJson] || [];
  if (lastVersion) return lastVersion;
}

return null
```

**Comment by ceremcem** [comment]
@marcalexiei Is it really `const = this.get('item')` or  `const item = this.get('item')`?

**Comment by marcalexiei** [comment]
The second one. I’ve edited the comment.

Thank you and sorry for the typo.

**Comment by ceremcem** [comment]
NP. Both of my comments will destruct themselves in 10 seconds (as they are meant to be direct messages to you). "t minus 10", "9", "8"...

**Comment by renattonl** [comment]
thank's @marcalexiei , Your answer has helped me. But that means I should avoid using this.get() ??. 
I'm used to using Destructuring assignment usually.

**Comment by ceremcem** [comment]
@renattonl As Ractive tracks computed property dependencies, you should avoid using `this.get()` and fetch only what you need (`this.get('foo')). However, this might be a separate enhancement proposal. @evs-chris

**Comment by renattonl** [comment]
@ceremcem  I understand Ractive's approach, but it would be nice to work using Destructuring in this.get ()

**Comment by evs-chris** [comment]
Can confirm: what @marcalexiei said. You _can_ use `get()` and destructuring, but if you use it in certain places, like computeds, you're not letting ractive know _exactly_ which keypaths you depend on, so _any_ change to _any_ data within the model is going to trigger the computed to recompute.
