### ISSUE TITLE
semantic error TS2305: Module '"ractive"' has no exported member 'InitOpts'

### ISSUE THREAD

**Issue by ctomczyk** [ractivejs/ractive#3313]
## Description:

Trying to compile TypeScript project and getting:

`[!] (plugin rpt2) Error: example.ts(1,19): semantic error TS2305: Module '"ractive"' has no exported member 'InitOpts'.
example.ts`

`import Ractive, { InitOpts } from 'ractive';`

Installed `npm install ractive` and `npm install @typings/ractive`.

Even, when I remove type InitOpts I can't compile and getting:

`semantic error TS2709: Cannot use namespace 'Ractive' as a type.`

## Versions affected:

1. "ractive": "1.2.4"
2. "@types/ractive": "0.7.27"

## Platforms affected:

macOS Mojave, 10.14.6 (18G87).

**Comment by evs-chris** [comment]
Ractive includes typings in the module since 0.10, I believe. Try removing `@typings/ractive` and it should use the built-in typings, which should have InitOpts defined.

**Comment by ctomczyk** [comment]
@evs-chris That was the issue. Thanks.
