### ISSUE TITLE
Ractive.extendWith and "this"

### ISSUE THREAD

**Issue by kryptus36** [ractivejs/ractive#3315]
## Description:

When creating a widget, I seem unable to call methods using this.

## Versions affected:

1.2.4

## Platforms affected:

All

## Reproduction:

```
// widget.ts

import {Ractive} from 'ractive';

class Widget extends Ractive {
    method (value: number): void {
        // Do stuff
    }

    anotherMethod(): void {
        this.method(5);  //this.method is undefined???
    }
}

const myWidget = Ractive.extendWith(Widget, {
    template: '<button on-click="@this.anotherMethod()">Click</button>'
});

export default myWidget;
```

**Comment by evs-chris** [comment]
In this case, you'll want:
```ts
// widget.ts

import { Ractive, InitOpts } from 'ractive';

export default class Widget extends Ractive {
    constructor(opts?: InitOpts) { super(opts); }
    
    method (value: number): void {
        // Do stuff
    }

    anotherMethod(): void {
        this.method(5);  //this.method is undefined???
    }
}

Ractive.extendWith(Widget, {
    template: '<button on-click="@this.anotherMethod()">Click</button>'
});
```

**Comment by kryptus36** [comment]
Thanks for the reply. I realized in trying to simplify my example I figured out the problem is actually stemming from something a bit deeper in my code.

I'm actually trying to handle a drop event.

Since ractive lacks on-drag* and on-drop events as far as I can tell I had attached the event listener manually, which obviously changes the context of this.

There are some drag and drop plugins but they seem outdated. Are there plans to add events for html 5's drag and drop events?

**Comment by evs-chris** [comment]
Any html event should already be supported e.g. `<div on-drop="@.dropped(@event)">Drop here</div>` would call the `dropped` method on your instance with the drop event. Here's an [example](https://ractive.js.org/playground/#N4IgFiBcoE5SBTAJgcwSAvgGhAWygIw4BmAzlANqgB2AhrupCAJbVIIAeAdDLQMYAXZgDcEXMANwAbEDj4B7agIRL4AHjAEAfAAkEUqfKwACYMDoNjAHyvGA5ACV+Q0XYwYAhGoD0mrQB1qNSQRYyReFBRaACMpBABefxABGABXBCTjRQBacNoUUgFaGAFEkAABLjyCopKACnKEUSUASkzCgE847NTSBBhsvrjBeOpFBADqY2MAEQjjBkCfEOFJ4NCc8PkABzLKre3t5AamlQE2kCzqXIj5URg9qtv7k+bzpMnpuZ3jMH6MoLeFaTJakPgwZjbASfYwKaiFYwAQUOxnixicghEYk4yjYdWAgWm02UuG2UloykgxgAJAAVACiAFkAAoAGURDKwhKJfFIpCp1IAwgBlYVcqY8vkASSQVLstEOdm5GBaAG5Aty4QiFdtUcYAO6sJDyfVcHV66gIfVIw747nE4poARy6LyJAdOziolhGA7I5IOpNFqme08xSkeRxLiGFB1OwHf0eT3GIPqiXeppcbYwU5KGYIYi0VJSAR1NWh6aZvipGA5pS0x0IARcTpR6L8ADWKF9qTYgsj8hgersdjT3uwoeqhWKpaDIfTRMzSAptFpvHhxH6XALm8Ew9wdwQo4rKeE2+Iu4EiIMJuQw4U2w6jMPx4XlbPy6Ka9oG63fQEMwrnGygcAIyZ2KQNZHuWC4Tgu1SHjAgbCMGBJvqeVQrt+v4wOel77i+Y7ehh1a1mcDYwE6LYCF0YjtnwXY9n2A5Dmidg5kgSroZm2a5gBBZFiWZZEdMGDKjBPhghCUIgkErYTNymimLCLFUgAxAADBpAAcBDabQqrGGJEorPO3qGkgAhgFSACsCC4CJvwIMwKASLZ9mOa6MDsDAVIENsHDGBGUjMEgjm4I6rB+R5obbLQSAhNQKDRQ5ypLN48mTJgAC6OAFvARqcDwzhYuIkgyBgQA).

**Comment by kryptus36** [comment]
Thanks for the example. It showed me I'm over complicating it - the drop event does indeed work.
