### ISSUE TITLE
How dynamically add ractive partials

### ISSUE THREAD

**Issue by TanvirAlam** [ractivejs/ractive#3317]
## Description:
I am trying to show my `partials`, They are set but it not showing

The following is possible:

`{{> xxx-xxx-xxx {paths: path}}}` -- this works

but I am tring to load it dynamically: I got all my partial templates in `conceptTemplates` and would like to do the following:
```
{{#each conceptTemplates : num }}
{{#if num === conceptType}}
    {{> {{ . }} {paths: path} }}
{{/if}}
{{/each}}
```

please help, need a solution

**Comment by evs-chris** [comment]
Could you share a link to ractive.js.org/playground or jsfiddle or something like that to give us something to poke at? I think I understand what you're doing, but I'm not positive. You definitely don't need nested mustaches, but the data in concept templates would have to be pre-parsed partial arrays. There are other ways to approach it that don't require parsing up front, but an example to work with would be helpful.

**Comment by TanvirAlam** [comment]
@evs-chris  Sorry body I got no time maybe later: just to give you little more description

my objective is to load partial template from external source:

using the following:
```
let partials = {}, promises;

promises = Object.values(codeSystemTemplates[0]).map( function ( name, type ) {
                        return fetch( '/' + name + '.html' ).then( function ( response ) {
                                return response.text()
                        }).then(function(body) {
                            if (type == conceptType) {
                                partials[name] = body;
                            }
                        });
});

```
do the following:
```
Promise.all( promises ).then( function () {
                    let ractive = Ractive({
                        el: '#' + path,
                        template: mainTemplate,
                        data: init_data,
                        partials: partials
                    });
 });
```
So the Partials come as:

`partials: name: Array(1)`

But my problem is when it comes to display in the view?? how??

`{{> partials.name {paths: path}}}` ????? is not working

**Comment by dagnelies** [comment]
This example might help:

https://dagnelies.github.io/ractive-examples/content/tabs.html

**Comment by TanvirAlam** [comment]
I solved by generating new ractive instance for each template and pass it on.
