### ISSUE TITLE
Templates: "Early return" instead of nesting

### ISSUE THREAD

**Issue by monoblaine** [ractivejs/ractive#3322]
Hi,

Is there any way to "early return" inside a template? Meaning that, is there any way to change the following template

```
<h1>Hello</h1>

{{#if foo === true}}
    <p>Foo is true.</p>
{{/if}}
```

to the following one?

```
<h1>Hello</h1>

{{#if foo === false}}
    {{return???}}    
{{/if}}

<p>Foo is true.</p>
```

**Comment by evs-chris** [comment]
No, there's not a way to do early returns, as templates are purely declarative. You can, however, put your `<p>Foo is true.</p>` in a partial and render that conditionally e.g. `{{#if foo}}{{>foo-is-true}}{{/if}}`.

**Comment by monoblaine** [comment]
Thank you @evs-chris, that's indeed a good alternative.
