### ISSUE TITLE
How to get DOM node reference from @.fire()

### ISSUE THREAD

**Issue by donnyv** [ractivejs/ractive#3323]
## Description:
I have this in a template.
`<td on-dblclick="@@.fire('on-cell-dbl-click', { rowData: ~/rowData[i],  cellIndex: j })">{{~/rowData[i].row[j]}}</td>`

In javascript I would like to get a DOM node reference of the `<td>`.
```
_this._ractive.on("on-cell-dbl-click", function (ctx) {
        
       // get node reference
      // ....

        if (currently_pressed_key === "alt") {
             fire_cell_double_click_event(ctx.rowData, ctx.cellIndex);
        }
});
```

## Versions affected:
1.3.6

## Platforms affected:
Win 10, Chrome 79.0.3945.88 (Official Build) (64-bit)

**Comment by kouts** [comment]
Is ```ctx.node``` what you are looking for?
Also be sure to check out the [context object docs](https://ractive.js.org/api/#contextnode)

**Comment by donnyv** [comment]
Its not in there.
![image](https://user-images.githubusercontent.com/2224189/71730485-44fce400-2e10-11ea-926b-4976d82a7fc0.png)

**Comment by donnyv** [comment]
Also if you expand that `__proto__` node is undefined.
![image](https://user-images.githubusercontent.com/2224189/71730572-88575280-2e10-11ea-905e-3c66a1da1372.png)

**Comment by kouts** [comment]
Can you try like this;
```<td on-dblclick=['on-cell-dbl-click', ... ] ...```

**Comment by donnyv** [comment]
That worked! Is there anyway to get it using `@.fire()` ?

**Comment by kouts** [comment]
Using ```fire``` try passing the context object as a parameter like this;
```@context```
You can find all the [special references here](https://ractive.js.org/api/#special-references).
