### ISSUE TITLE
60 Seconds Setup @ Wiki, points to nowhere

### ISSUE THREAD

**Issue by AxDSan** [ractivejs/ractive#3325]
## Description:
The 60 second setup in the [Wiki](https://github.com/RactiveJS/Ractive/wiki/60-second-setup), link to where the guide is supposed to be hosted, points to nowhere when you go there, also the link seems to be not correct, as the correct path would be to point to the actual website url (https://ractive.js.org/)

## Versions affected:
N/A
## Platforms affected:
N/A
## Reproduction:
N/A

**Comment by evs-chris** [comment]
I didn't realize we still had wiki content here. There's not really a 60 second setup to point to anymore, but I've at least changed the link to ractive.js.org. I still need to go through the docs to make them a bit more coherent after the move to ractive.js.org.

Thanks for the report!
