### ISSUE TITLE
How to add external template recursively

### ISSUE THREAD

**Issue by TanvirAlam** [ractivejs/ractive#3327]
## Description:
What is the best way to add external templates: Below show image shows sample design
![sample](https://user-images.githubusercontent.com/3250040/76755479-37ef6000-6784-11ea-8898-b4e348938214.png)

Each box is external template that are added dynamically.

How do I initiate `new reactive` component that can uses the same method

I have added JFiddle work place: https://jsfiddle.net/tanvir_alam_shawn/bg27chx6/15/
## Versions affected:
Ractive.js 1.3.11

## Reproduction:
I have added JFiddle work place: https://jsfiddle.net/tanvir_alam_shawn/bg27chx6/15/

If anyone can help it would appreciated as I am new to Ractive

**Comment by evs-chris** [comment]
Sorry, I've been ill and didn't see this issue pop up.

What you typically do for recursive stuff like this is either use a partial in a single instance or a component that is self-referential. [Here's](https://jsfiddle.net/trmp41w5/) an example of a self-referential component. The partial would be similar just using a tree structure in your data e.g. `{ children: [{ children: []}, {children: [{children: []}]}] }` with `partials: { children: '{{#each children}}<div class="child">{{>children}}</div>{{/each}}' }`, where the `children` partial renders another instance of itself in the new context set up by walking down the tree with the `#each`.

**Comment by TanvirAlam** [comment]
This has been solved, thank you
