### ISSUE TITLE
Decorators not updated on Ractive.sharedSet()

### ISSUE THREAD

**Issue by LeJared** [ractivejs/ractive#3329]
## Description:
Update-Methode of decorators is not called if change was trigger by Ractive.sharedSet()

## Versions affected:
1.3.11

## Reproduction:
https://jsfiddle.net/lejared/0zatne42/31/

This is a reduced test case based on my internationalization plugin for ractive. When the selected language is changed globally through Ractive.sharedSet() this change is recognized by all instances and all components quite as expected. Only decorators don't get updated.

**Comment by evs-chris** [comment]
I believe I have a fix for this on edge now. Decorator args were just set up as a function that pulled immediate deps and capture wasn't a factor. I dropped a bit of code and just used an expression proxy, like those from regular mustache expressions, to track args, so capture came along with that for free. If you can, try out edge with your app and let me know how it goes.

**Comment by LeJared** [comment]
Edge seems to work quite well. Thanks for the quick fix.
Also updated the jsfiddle and it works too: https://jsfiddle.net/lejared/0zatne42/33/
