### ISSUE TITLE
not a bug... but something like ractive.keys() would be handy

### ISSUE THREAD

**Issue by jhiver** [ractivejs/ractive#3336]
## Description:

For the life of me i cannot iterate through whatever was set. In old version it was quite easy to get to the data but nowadays I can't find how to get it done. Any idea please?

## Versions affected:

all recent ones

## Platforms affected:

everywhere.

## Reproduction:

ractive.set('foo', 1)
ractive.set('bar', 2)
ractive.keys() # would return [ 'foo', 'bar' ]

**Comment by MartinKolarik** [comment]
What's wrong with `Object.keys(ractive.get())` ?

**Comment by jhiver** [comment]
How could I have missed this? Thanks!
