### ISSUE TITLE
Is there anyway to use only Mustache syntax in Ractive templates?

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#3346]
## Description:

Lately I'm using Ractive to generate C source code on the server side and it went well so far. 

Since every line, struct and function call counts while developing for an embedded platform (microcontroller), it becomes an crucial requirement to write the application code just as much as needed in the first place. That's why it might be an advantage to generate C source code with Ractive templates and provide a configuration data for generating necessary code for different scenarios, rather than trying to get the same thing by C preprocessor.

At this point, it would be handy to encapsulate all Ractive activities inside Mustache's, so it wouldn't likely to interfere with the target language. 

Is it possible to initialize component instances with Mustache's and restrict anything outside Mustache's?

## Versions affected:

All. 

## Platforms affected:

All. 

## Reproduction:

N/A

**Comment by evs-chris** [comment]
I'm not 100% sure what you're asking here, but it _sounds_ like text-only mode? Where the parser is supposed to read direct text between mustaches and only parse mustache content. I think there are some outstanding whitespace issues with that that may be avoided to some extent by enable preserve whitespace. Is there something beyond that that you need the parser to do?

Unrelated, have you seen [zig](https://github.com/ziglang/zig)? It bills itself as a cleaned-up C, where one of the biggest warts is the completely unrelated preprocessor language, which is replaced by compile-time evaluation. It's probably not in any shape for production and may not have a live llvm backend for your arch, but I think it's going to be interesting for the embedded space.

**Comment by ceremcem** [comment]
Yes, I'm talking about text-only mode. I never tried initializing a component in text-only mode, that's why this confusing idea came out. What I understand is there is no way to initialize a component in text-only mode? [That reproduction](https://ractive.js.org/playground/index.html?env=docs&hidemenu#N4IgLiBcIDwA4CcCmACAlgEwLwB0QHsBXMOYvAPhwDsYB6RJckAGhAGcoQAlAQwGMwaAG5IAdH3wBbOPipIqYNgG08ACyQAbDfjwBdFFhS8BwsUgAeYeRgAUwaihRXpGnlcgoABg5TqAnijAwFaWAL6hAITeVKEAlNTUaFRsYAYocgDuRvyCInY+YDwIAOZIYB4A5ADERCTEFcwFSC5uSB7GuWJwRWxINtEw6lr45HRD2uQoPtRVGEgAZkmo4-hO6shTVEFVaPO+SH7hPo6zC0u+aCgArNRBtLtHVLfAVUj8qiiSfgDyAEYAVo9HI5thk0GAPl8-v8lAABADWB30PDYKCEPA0QOB2NOizkgWA6I0onM4QJRNEh1CxwJtDBEMedzefFUj2onmYgRCYG+VA0fgAsvg5h4wAhCEhOQxeggRAB1VTgpBsbp8NpOcVIOKNKiODBuHgeey64H+UWanXYqEAyDG7GOPA8ACMeCN5g8eHm+B0LBQfg9IF+RTwoU5NJwYEdACZXYF3VNAzwAF54Tn+hMAR0I5hDNOpJvzcRYID4nGLqigoAQnFcVhSIHCQA) says the same. 

I took a look at zig. It might be a nice language for it's own domain, but I didn't quite get the benefits. If I had a chance to move to another language (for embedded applications), [DLang](https://dlang.org/) would be my choice. I'm looking forward to build my first application with DLang in a new project. 

However, my case is a little bit more unfortunate. I really don't prefer C because it's too verbose, it doesn't support some other programming paradigms (OO, functional programming) that may help (and is helping for me) to build a maintainable application with reusable code. However, C is practically the only language in embedded world. Moreover, I've been using a RTOS that helps me abstracting some difficulties. That RTOS (ChibiOS) heavily uses C preprocessor to avoid function, struct and variable declaration because, again, every abstraction counts. However, the RTOS' abstractions are not enough and prevents us from writing reusable code.

I might nearly use an object oriented approach with pure C by abusing structs ("every struct is an instance" approach) but that bloats the application size, so I can't do it either. 

Also, writing an application isn't the end of work. We may need support at any time, so we may need to share our code in the forum. If I pick another language, or some "auto generated" C code output of another language, things will get hairy. (Trust me, I'm a LiveScript user.)

So I decided to use a nice preprocessor language in in conjunction with C. Here I thought I could use Ractive. 

It might sound like re-inventing C++ (the version back in the C-with-classes days), that's okay. I may want to generate Ractive templates from Ractive templates which in turn generate C codes, so it might sound like re-inventing Lisp. Those might not be Ractive's goal, that's also okay. But I feel like Ractive will do that job just fine with a few additions, like #3338 and #3346 (this) one.

**Comment by evs-chris** [comment]
I think I understand what you're trying to do a little better now. It sounds like we would need a way to include a component as a mustache rather than a tag. There's not really a clean way to differentiate between a tag and a component at parsing, as they look the same and the component is looked up at render time.

You could work around this issue by dropping your components into partials e.g. `c source here {{>component}} more c source` and then parsing the component partial without text-only mode as `<mycomponent ... />`.

**Comment by evs-chris** [comment]
I thought about this a little more, and was wondering how much of a component tag do you need to support? Do you need to create links or just pass along plain old sets? I could put together a partial function that would create the relevant template for you to do something like `{{>component('name', { value: whatever, size: 10 + theSumOfSomeStuff })}}` pretty easily. I'm guessing you don't need to link in any data for twoway binding if you're using this to render text, so that might be enough, though I could add link mapping argument to that as well without _too_ much trouble, I think.

**Comment by ceremcem** [comment]
As you correctly guessed, there is no need to support twoway binding in such a use case and that function-like syntax would be awesome. Only maybe the count of parentheses reduced?

**Comment by evs-chris** [comment]
[Here's an example](https://ractive.js.org/playground/#N4IgLiBcIgNCBnKN4GNlxACyqATsgDYCGYApghAL7wC2UAjPAGZKQDaoAdsbWcgEsuAEzIAPAHR5iqMAIBuZCVjC1CmVAHsu5HcgA8WBgD4AEmUKFNsAATBgPPjYA+zmwHIASjLmL3VKgBCfQB6I2MAHS57Yy1aAAdtMh0ACndmTU13W2AbACNiPEgPYnzCu2ACgC8A7PzNeOKAThsAKhsGABYbKgBKAP08vBDIrn0MzTK8AF4IkFKCvArqgLn6+NmQexb2rtWQGxGoqP0EVDwBeLBRmxsBBM08MDsbOMSuZOeqG2Y8TVoPBIQoQBHl3ABuKK3byyBRKLAWeJkPAICRvJI6GzTV7-d6fSFcW5aLiUGwAMUyWJsMN8SnEumEKVy5ASJHIxXcFM0gWWhQCywaAXB7h6vQJRO0pIAgvF4lSaXCJPTkozgFDbjYWfE2WRigASAAqAFEALIABQAMlLjbB1USEAh9QBhADKLtthI1qAdAElhBziLLsnacQ8PjpHS8JsUuT11X0CeriaTA3LsQB3ITCTTpiSpqkfdM2GXxJkhsCFADmZDAHLymmEAE9g57bsJSMRimrWxrqsVOgAmDXDkc2ENUeNi9VJyXPLU6qkAAwQ-zImvp4Js1Y+F1Q+gNxk3MXR4bAaQmdVyiwDU15NSodXrjRsOw63T6AU0YARS3IYjA4KLjOJKaIQShWJWKSFtSPhwmWPbzqQuowbCigSPEhQIGQKSIeQOTrv+ADyXCEI2JoNshYB4AArmufQesOJ6fJGuTRuSlI0CG7YVl2Ia3H2L5NOOk4SGAmimAaJoWikvS9CcIRnBcVyjCclCNmBNw2EYLxaFYRQ2AAxAADEZAAcDCmcQm4TmMClgOpZCjCANDcLw-DQCCeQSAAVkgaDaLoEDQOIiRPD81FcLC2ihniqSOGQtjccQvR2OqeA1tReCEuwIbdqOtY2AA7AxI7IfFJXDrQxSEXk3lkLISo6BcFApElLhuMAfQSLQgYpGu0zGKlPaMbOmravKsFoRhKLYYuerAGQ7AMAAulQi69KJ4qjjY6VgJlhK5FwxSLUZy22AVDAAMy2MwxRgONVBbcOfTCZ6y1RFQzlnSAZDMIIIjiFIk3wqo6hUEAA) of what that component partial helper would look like. There's a console log at the end that shows that it works in textOnlyMode, though you'd still need to process `&gt;` and `&lt;`, apparently.

**Comment by ceremcem** [comment]
That is more than enough. Thanks a lot!
