### ISSUE TITLE
Decorators - conditional decorators do not work on yielded partials

### ISSUE THREAD

**Issue by marcalexiei** [ractivejs/ractive#3351]
## Description:
Today I have installed last build (`1.4.0-build-41`).
I found a Maximum call stack size error related to conditional decorators inside a yielded partial.

**NOTE:** `Ractive.defaults.isolated` must be set to `false`

These issue is not present in `1.3.12` version ([fiddle](https://jsfiddle.net/cn2hvg13/))
The issue started from build [`1.4.0-build-40`](https://travis-ci.org/github/ractivejs/ractive/builds/742567936)

## Versions affected:
* 1.4.0-build-41
* 1.4.0-build-40

## Platforms affected:
All, tested on Chrome and Safari

## Reproduction:
- Open this [fiddle](https://jsfiddle.net/otxswhf6/)
- Open console
- Run the fiddle and check the console

```javascript

Ractive.defaults.isolated = false;

Ractive.components.Dropdown = Ractive.extend({
  template: '{{yield title}}'
});

const r = window.r = new Ractive({
  el: '#main',
  template: `
  <Dropdown>
    {{#partial title}}
    <p {{#if isDecorated}}as-awesomeDec{{/if}}>
      We are ready for some bugs!
    </p>
    {{/partial}}
  </Dropdown>
  `,
  decorators: {
    awesomeDec(node) {
      node.style.color = 'red'
      return { teardown() {} };
    }  
  },
  data: {
    isDecorated: true,
  }
});
```

**Comment by evs-chris** [comment]
Interestingly, it's not the decorator, it's the `isDecorated` reference. Since a yield doesn't hold a context, it just directs the flow of context, resolving the reference within the yield crosses a component boundary, which with non-isolated components, results in an implicit mapping between components. But since it's a yield, the resolved model is the same. The link creation process would catch that if you did it manually, but it doesn't do deep checks on internal use. I think I've got this fixed in edge in build-42 once travis does its travis thing. If not, please don't hesitate to reopen this issue.

**Comment by marcalexiei** [comment]
I tested with the new build: the reported scenario is fixed, but there are 2 issues:

### 1. ambiguity warning:
Now if you set `warnAboutAmbiguity` to `true` all parent data properties used inside the yielded partial log an ambiguity warning in console (in this case `isDecorated`).

You can reproduce this issue on this [fiddle](https://jsfiddle.net/s2zo7eag/).

### 2. another maximum call stack size error
I know this is quite ugly and should be "isolated" but in the previous version was working.
I think the problem is related to the `TabList` param: `activeTab="{{activeTab}}"`.

**NOTE:** in the real app scenario `activeTab` is used inside the `TabList` component but seems not required to reproduce the issue.

You can reproduce this issue on this [fiddle](https://jsfiddle.net/jou8vwcd/).

```javascript

Ractive.defaults.isolated = false;
Ractive.defaults.warnAboutAmbiguity = true;

Ractive.components.TabList = Ractive.extend({
  template: '{{yield content}}'
});

Ractive.components.Cmp1 = Ractive.extend({ template: 'Cmp1' });
Ractive.components.Cmp2 = Ractive.extend({ template: 'Cmp2' });

const tabSet = [
  { name: 'first', label: 'first' },
  { name: 'second', label: 'second' },
]

const r = window.r = new Ractive({
  el: '#main',
  template: `
  <TabList activeTab="{{activeTab}}">
      {{#if activeTab.name === 'first'}}
        <Cmp1/>
      {{elseif activeTab.id === 'second'}}
        <Cmp2/>
      {{/if}}
  </TabList>
  `,
  data: {
    tabSet,
    activeTab: tabSet[0],
  }
});
```

### Workaround: 
- use `Ractive.defaults.isolated` to `true`
- set `isolated` to `true` on the parent component where the partial is yielded (In this case the Ractive instance)

**Comment by evs-chris** [comment]
Thought about it a bit harder and think I have a solution that is more correct now in [build-43 (fiddle)](https://jsfiddle.net/t4ry8ghv/). When walking up the fragment tree to resolve a reference, moving from a yield to its parent fragment should not consider the component, as logically, the yield shares the scope with the parent fragment rather than the containing fragment. That seems to resolve all of these issues without being hacky.

**Comment by evs-chris** [comment]
As an aside, and I'm not sure that this isn't just for the example, but you generally shouldn't set the same non-primitive value at multiple places in ractive data, as it can't track them in all the places at the same time. Linking multiple paths to the single canonical path will make things stay consistent everywhere.

**Comment by marcalexiei** [comment]
Both issues are resolved in the real app scenario.
Thanks!

**Comment by marcalexiei** [comment]
Today we discovered another, maybe, related issue:

In previous versions the`typeof .foo` was resolved correctly to `string`

```javascript
Ractive.defaults.isolated = false;
Ractive.defaults.warnAboutAmbiguity = true;

Ractive.components.Dropdown = Ractive.extend({
  template: '{{yield}}'
});

const r = window.r = new Ractive({
  el: '#main',
  template: `
  {{#with something}}
    <Dropdown>
      {{JSON.stringify(.)}}
      <br>
      {{typeof .}}
      <br>
      typeof .foo -> {{typeof .foo}}
       <br>
      '' + .foo -> {{'' + .foo}}
    </Dropdown>
  {{/with}}
  `,
  data: {
    something: {
      foo: 'bar'
    }
  }
});
```

You can reproduce the issue on this [fiddle](https://jsfiddle.net/5fq7j12w/)

### Workaround
Use `isolated` components :D

**Comment by evs-chris** [comment]
Yep, missed a possible path through. Should be good in build-44.

**Comment by marcalexiei** [comment]
Issue no longer present. Thanks!
