### ISSUE TITLE
Typescript error when accessing component's name from context

### ISSUE THREAD

**Issue by giovannipiller** [ractivejs/ractive#3361]
## Description:
There seem to be a definition error where, after getting a context, one cannot access the following property:
`context.ractive.component`

As a related note: `context.component`, as per definitions, should be of type `Ractive`. Same as `context.ractive.component`.
This however is not the case.

`context.ractive.component` is of type `Child`
`context.component` is actually of type `Component`

## Versions affected:
1.3.13, edge

## Reproduction:

```typescript
import Ractive from "ractive";

Ractive.extend({
  on: {
    'clickity-clackety': function (context) {
      // context.ractive.component exists but has no definition
      context.ractive.component.name;

      // context.ractive.name doesn't exist
      context.component?.name;

      // Based on definitions, both `context.ractive.component` and `context.component` should be instances of Ractive.
      // This is not the case.
    }
  },
})

```

**Comment by giovannipiller** [comment]
Here's a reproduction repo:
https://github.com/marcalexiei/ractive-sandbox/blob/master/main-context-component.ts

**Comment by evs-chris** [comment]
Just wanted to say that this and other typings issues are on my radar to poke at soon.

**Comment by marcalexiei** [comment]
FYI also `Ractive.tick` is missing from declarations.

**Comment by evs-chris** [comment]
I guess soon is a relative term. `component` on a context helper is actually the internal component vdom-like node that manages a component, so I added what I think is a reasonable chunk of public interface for that to the typings `{ name: string; instance: Ractive }`. It should be available on edge once travis finishes doing its thing.
