### ISSUE TITLE
Typescript issue with the provided method signatures

### ISSUE THREAD

**Issue by hexargon** [ractivejs/ractive#3368]
## Description:
Hi, actually I have a problem after importing the Ractive typings, the TypeScript compiler complains about missing parameter types. The parameters of the following exported method signatures are affected:

```
export type MacroFn = (MacroHelper) => MacroHandle;
```

```
export type PluginExtend = (PluginArgsExtend) => void;
export type PluginInstance = (PluginArgsInstance) => void;
```

```
export type Plugin = (PluginArgsBase) => void;
```

The reported Error Message is:
Typescript ErrorCode TS7051 "Parameter has a name but no type. Did you mean 'arg0: MacroHelper'?"
...

Is there a way to fix this issue.

## Versions affected:
1.3.14

**Comment by evs-chris** [comment]
I'm doing some typings work right now, but it turned out this was hiding some other typings issues too. In the meantime, it looks like you're not running into this issue with your code, so if you can turn on `skipLibCheck`, you should be able to get around it.

**Comment by evs-chris** [comment]
This should be resolved on edge now, once travis finishes doing its thing.
