### ISSUE TITLE
RFC Typings: opt-in typing for data and find methods

### ISSUE THREAD

**Issue by evs-chris** [ractivejs/ractive#3371]
The current typings leave `get` and `set` accepting/returning `any`, which is effectively what they do, however it's much more useful to be able to extract data with a type already in place e.g. `const customer = this.get<Customer>('customer')`. On it's face, that's not much of a distinction from `const customer: Customer = this.get('customer')`, but it really starts paying off when you want to do something like `const customers = this.get<Customer[]>('customers').filter(c => c.balance > 0);`, where you don't want to have to do an extra set of parens to do a cast on the `get`.

To that end, I've pushed up a typings change on edge that does this. The default type param for everything is still `any`, so not supplying it is _mostly_ the same as without the change. The one difference is expected return type inference as in the example with the customer above. With the type param, typescript will infer `Customer` as the type parameter in `const customer: Customer = this.get('customer')` because of the typing on the variable. I think this is better, as it prevents something like `const customer: Customer = this.get('customer') || {};` accidentally blowing something up (I actually found a few of these in my code trying out this change) because the `{}` doesn't have methods or whatever that `Customer` requires.

I'm opening this issue as a request for comments on this change. Obviously if you don't use typescript, you probably don't care, but for those who do, what do you think about this, or at the very least, does this negatively affect you?

**Comment by giovannipiller** [comment]
I think this is a great improvement! Will tinker with it next week and report back!

**Comment by giovannipiller** [comment]
After a few tests, this approach seems to improve Ractive's Typescriptenss considerably.
You have my vote! 😄👍
