### ISSUE TITLE
Inconsistent HTML entity decoding in attributes

### ISSUE THREAD

**Issue by ppena-LiveData** [ractivejs/ractive#3434]
## Description:
If a template has an HTML element attribute with just a static string, then HTML entities are decoded, but if there's a mustache in the attribute, then the HTML entities are not decoded. For example, `attr="&amp;"` will have `&amp;` decoded to `&`, but `attr="&amp;{{''}}"` will not have it decoded, see [that example in the Ractive Playground](https://ractive.js.org/playground/#N4IgLiBcIDwA4D4A6A7ABGgKgUwM5jWGCRADMB7ckgX2tRgHpEQAaEXKEVkAY0+4AWUUACdOAGwCGYPBGpsAtlACMbUh0gBtUCkkLsnAJYoAJtgAeAOhGSeYQwDdslgWAXjuPcihk-OMXB4RQzgwZHQ0LxR8NABBODg0AF40ACVbeydLC18TAApiCIwZBTgpGUg0AAMACUwAWQAZNGwfQzAATzQzLzMTSBgAIxEEGApyNGkwESSSADI9OABuElGGcdHhzZG6ppa2zrQAOQB5TG7sXux+oZGhyRFJsGnZkAXSpaIAci-aVcZBg8EFUWKgMBgeLhcJUACQAYQAygjQUVIlCAJL9NBfSQJL5gtDUACUKxQBKiMVxiRSAHdjCZyDTLFTkmgUNgaXEEgUCcUHgBzbBgSpfQbkEwdfERYmkjDiIVocashk8ACu+h8lgAjqrsCIOgjsPK7OQRHkvuMvkSCeNLMZ2SIcOYCCkqkqpo8HJJxEkvjDgLbBWBYs9goNVTJzR6rdQvmg6WABGh5Sh+Ymkv7A0KQ9NDOHIzjQ1bLCm0wJqFVZcmFYDHikVerWmBtbr9YbjWBTeba1aCbW7SgHU6XdVa09pmgvT6-cB+0Gc2GI9go0WibH4+0k6X0-659nQ3mlyvpsXt+XK-QGIFgqFwvR8B15eEMAJlIRIuRxKbKgBiAAMf4ABzKIBkhLISl4Pk+qAgNQAC6bDYKQRimBY1gZI4ziuO4sFAA).

## Versions affected:
Maybe all? The problem is in [src/parse/converters/element/readAttribute.js](https://github.com/ractivejs/ractive/blob/16ee82bc7b95b7789a7b61f57e9fc8c5c7e13021/src/parse/converters/element/readAttribute.js#L119), since it only calls `decodeCharacterReferences()` when `value.length === 1 && isString(value[0])`.

## Platforms affected:
All.

## Suggested fix:
Instead of this:
```javascript
  if (value.length === 1 && isString(value[0])) {
    return decodeCharacterReferences(value[0]);
  }
```

The code could decode all static strings, like this (thanks @GabeSchaffer for this suggested fix):
```javascript
  // decode HTML entities for each static string within an attribute
  for (var i in value) {
    if (isString(value[i])) {
      value[i] = decodeCharacterReferences(value[i]);
    }
  }

  if (value.length === 1 && isString(value[0])) {
    return value[0];
  }
```

**Comment by evs-chris** [comment]
Thanks for the concise bug report with a very good breakdown of the problem and resolution! This should be resolved in 1.4.4.
