### ISSUE TITLE
Custom interpolators

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#356]
RIght now, only numbers get interpolated with `ractive.animate()` (or objects/arrays containing numbers). It would be neat to be able to provide custom interpolator plugins so you could animate 'red' to 'blue', for example:

``` js
ractive.animate( 'textColor', 'blue', {
  interpolator: 'color',
  duration: 1000
});
```

Off the top of my head, best way to implement this would be something like

``` js
Ractive.interpolators.color = function ( from, to ) {
  return function ( t ) {
    var intermediateColor = /* some code happens */
    return intermediateColor;
  };
};
```

Bonus points for being able to configure the interpolators e.g.

``` js
Ractive.interpolators.color = function ( from, to, colorSpace ) {
  return function ( t ) {
    var intermediateColor = /* some code happens */
    return intermediateColor;
  };
};

ractive.animate( 'textColor', 'blue', {
  interpolator: 'color:hsl',
  duration: 1000
});
```

We could use the same mechanism to 'typewrite' text, a la the [typewriter transition plugin](http://ractivejs.github.io/Ractive-transitions-typewriter/), or do [supercool 90s TV credit sequences](http://youtu.be/DI-gsQf_F-I?t=18s).

**Comment by evs-chris** [comment]
It looks like this is implemented and documented, so I'mma close it.
