### ISSUE TITLE
Enable Ractive Components that don't control the DOM

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#363]
Since components seem to be fresh in your mind, is it possible, or should it be possible, to have Ractive components that delegate the DOM interaction? I just did a component for an ace editor:

```
    var Editor = Ractive.extend({
      template: '#editor',
      magic: true,
      twoway: false,
      init: function(){
        var self = this
        var e = ace.edit(this.fragment.items[0].node)
        e.setTheme('ace/theme/twilight')
        e.getSession().setMode('ace/mode/javascript')
        e.on('change', function(){
            self.data.js.code = e.getValue()
        })

        //this doesn't fire
        self.on('set', function(keypath, value){

        })
      }
    })
```

Works enough to do what I need, but it doesn't update from model changes back to the component.

Basically let Ractive manage the overarching template, but at a component level interface into something else controlling the binding. I could see an adapter for d3 charts for example. It would open up bringing in specialty display libraries.

Does that make sense?

**Comment by mrjoelkemp** [comment]
Sounds like this can be closed?

**Comment by zenflow** [comment]
Has this been feature request been implemented? If so I will need to update the docs and start using it!

**Comment by matthew-dean** [comment]
Wait wait, what is happening here with the binding to an ace instance?

**Comment by evs-chris** [comment]
This is a super old issue, and it _looks_ like decorators are the answer, so I'm going to close this.
