### ISSUE TITLE
New feature: import components from HTML file

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#366]
This probably isn't fully baked yet, but it's a really neat idea (suggested by @davidmoshal in #299), and I'd be interested in feedback.

The idea is to be able to fully define components in a single file that contains the template, any CSS, and custom methods/init logic. It draws inspiration from Web Components and [HTML Imports](http://www.html5rocks.com/en/tutorials/webcomponents/imports/). If we get it right, it will make it really easy to create reusable components that can be shared widely (think Ractive UI, like jQuery UI or Angular UI, except not an unloved cousin to the main project :)
## Making a component

You define a component in an HTML file (because HTML can contain `<style>` and `<script>` tags, and text editors are happy to chop and change syntax in that situation - much better than the nightmare that is multiline string templates in a .js file).

``` html
<div class='box' style='width: {{size}}px; height: {{size}}px'>
  <p>This box has a total area of {{ format(size*size) }}px.</p>
</div>

<!-- This CSS will be appended to the page when the first instance
     of this component is created, and removed when the last instance
     is torn down. It is optional. There's no scoping magic, we have to
     just be careful with class names -->
<style>
  .box {
    background-color: black;
    color: white;
  }
</style>

<!-- The script block is optional (as is the style block) -->
<script>
  module.exports = function ( Ractive ) {
    return Ractive.extend({
      init: function () {
        console.log( 'initialising box!' );
      },
      data: {
        size: 200,

        // add comma separators
        format: function ( num ) {
          var remaining = '' + num, result = '', lastThree;

          while ( remaining.length > 3 ) {
            lastThree = remaining.substr( -3 );
            result = ( ',' + lastThree + result );

            remaining = remaining.substr( 0, remaining.length - 3 );
          }

          return remaining + result;
        }
      }
    });
  };
</script>
```
## Loading the component

Then you load the external file in one of two ways:
### 1. As a globally available component

``` html
<!doctype html>
<html>
  <head>
    <title>Component imports test page</title>

    <!-- here is where we import the component. We could add a 'name'
         attribute, otherwise it will default to Ractive.components.box -->
    <link rel='ractive' href='box.html'>
  </head>

  <body>
    <div id='container'></div>

    <script src='Ractive.js'></script>
    <script>
      var box;

      Ractive.load().then( function () {
        box = new Ractive.components.box({ el: 'container' });
      });
    </script>
  </body>
</html>
```
### 2. Loading a specific component

``` html
<!doctype html>
<html>
  <head>
    <title>Component imports test page</title>
  </head>

  <body>
    <div id='container'></div>

    <script src='Ractive.js'></script>
    <script>
      var box;

      Ractive.load( 'box.html' ).then( function ( Box ) {
        box = new Box({ el: 'container' });
      });
    </script>
  </body>
</html>
```

The 'box.html' path will be resolved relative to `Ractive.baseUrl`, if it exists (so you could put all your components in a `components` or `imports` folder without having to explicitly refer to that folder each time).
## Dependencies

Some components might have dependencies on other components. One way to handle that is to have separate `<link>` tags for them all, so that all components are globally available. Another is to use the `@import` directive:

``` html
@import foo.html
@import ../bar.html
@import somethingElse.html as baz

<div class='component-zoo'>
  <h2>This is a foo</h2>
  <foo/>

  <h2>This is a bar</h2>
  <bar/>

  <h2>This is a baz</h2>
  <baz/>
</div>
```
## Cross-origin stuff

The html files have to be hosted on the same origin, or served with appropriate CORS headers.
## Optimisation

Clearly this is isn't a great way to build large apps, because you don't want to have to make a ton of requests. At some point in the future there'll be a build tool that will compile components (and their dependencies) into a JavaScript bundle, that would work with grunt et al - the [Ractive AMD loader plugin](https://github.com/RactiveJS/requirejs-ractive/) will also serve this purpose (when used with the RequireJS optimiser). Uncompiled component imports won't work with the runtime builds, as they need to be parsed.
## Promises (an aside)

Under the hood, this is using promises. (If any promises experts out there can see any ways in which [this implementation](https://github.com/RactiveJS/Ractive/blob/0.4.0/src/utils/promise.js) deviates from the [spec](http://promises-aplus.github.io/promises-spec/), let me know!) I'm tempted, now that they're in the library, to start using them in other places (e.g. returning a promise from `ractive.set()` and `ractive.animate()` etc, rather than using callbacks and making them chainable)... any thoughts?
## How to start testing them

Grab the latest dev build from https://github.com/RactiveJS/Ractive/tree/0.4.0/build.

Just to clarify - nothing is set in stone here - the `Ractive.load()` method name, the `<link>` approach, the component format, the `@import` directive - it's all just fodder for discussion at this point. If you have better ideas please share them!

**Comment by paulocoghi** [comment]
@Rich-Harris I am returning to front-end development thanks to your framework. Probably this is not the best place but: Thank you very much for your incredible work.

I have spent almost 15 years programming in classic way of PHP/MySQL and with front-ends that were completely dependent to PHP processing.

I fill that, now, I can create a full independent front-end like (or even better than) big companies. And it's a pleasure to use your creation.

I hope that, someday, I will have enough knowledge to contribute to Ractive to make it better, stronger and faster. ;)

**Comment by Rich-Harris** [comment]
@paulocoghi Thanks so much for saying so! Really glad to hear it's working for you, and your contributions will be very welcome when the time comes. Not just my framework though, I'm one of many contributors :)

**Comment by ceremcem** [comment]
Hi, 

Thank you for your hard work. RactiveUI idea is the most important one of my expectations from Ractive. It seems to be on its way. 

But, I found it a little bit hard to use. It's hard to me, because I didn't manage to use it yet :) 

First question on my mind (which draws me back while debugging) is "Why I have to write more than a line of code when I cut my partials and paste into another file"? I think I should add only one more line, which means "buddy, look that file for your partials". If I need to point more than a file, then it's OK to point these files separately. 

Second problem is, should I have to use JavaScript to code dynamic parts of the partial? For example, I prefer LiveScript. Likewise, styles could be written in any language that could be compiled to CSS, I think. 

Do I miss something?
