### ISSUE TITLE
DOM Node Count Vs. Actual Nodes

### ISSUE THREAD

**Issue by ekanna** [ractivejs/ractive#407]
Hi,

In Chrome Develper Tools at timeline, i saw below counters:

1.Document Count
2.DOM Node Count
3.Event Listener Count

I was able decrease Document Count & Event Listener Count by using below ractive methods:

.teardown()
.off()
.cancel()

But, i could not do so for DOM Node Counter. How to reduce this count?
Huge variation between actual nodes and DOM node counter. In spite of this, my application is woking smoothly. But would like to know the reason. 

Does it have anything to do with the way dom is updated by ractive?

Thanks
koti

**Comment by evs-chris** [comment]
I don't see any bonus nodes floating around, so I'm going to close this. Feel free to reopen if it crops back up.
