### ISSUE TITLE
[Feature] Add logic to all images in the template

### ISSUE THREAD

**Issue by binarykitchen** [ractivejs/ractive#416]
I would like to add a lazy loading mechanism to all images a Ractive template is holding.

The template has many conditionals so a callback method for whenever an `<img>` is about to become visible would be great. Any clues?

**Comment by matthew-dean** [comment]
@binarykitchen Did you ever publish this as a Ractive plugin?

**Comment by binarykitchen** [comment]
no

**Comment by matthew-dean** [comment]
No worries.
