### ISSUE TITLE
Proposal for a generic "LayoutManager" plugin/component

### ISSUE THREAD

**Issue by vseguip** [ractivejs/ractive#459]
## Layout manager proposal

Disclaimer: I'm a total noob when it comes to web development as well as Ractive.

First please look [here](http://stackoverflow.com/questions/22090591/how-to-move-components-around) to get some background information.

I think this use case is common enough to extract a general functionality that may serve others. Requirements I would like to see from the solution:
1. Subcomponents remain independent from the parent component. Ideally they should only concern themselves with their own data and not even know if they are in a top level component or not. In other words loose coupling.
2. Layout manager should be extensible and adaptable to different subcomponents through a common interface API
3. A declarative approach to the problem
4. No unnecessary deleting/creation of Ractive components or DOM nodes.
5. No pollution of the data model.
6. Allow for component and subcomponents encapsulated in HTML files as per the Ractive 0.4.0 branch.
## Basic objects for the example

Suppose we are displaying a situation aware map of our network of computers. We model each computer as a component. This component includes data like CPU use Memory, etc and location of the computer. In the web page we would like to display each computer in a different DOM <div> depending on the computer location field. Changing the location of the computer in the subcomponent should refresh the location of the subcomponent in the DOM. 
## Proposed solution

The layout component injects a new attribute in the data of the subcomponent (the subcomponent need not be aware of this). This data can actually be a function of the subcomponent data defined in the top component. For example we show a `topcomponent` template:

``` html
<div id="source" style="visibility:hidden">
         <h1> Section 1 </h1>
        {{# subcomponents}}
             <subcomponent cpu={{cpu}} location={{location}} parentNodeForLayout="{{getParentNode(.)}}"/>
        {{/subcomponents}}
 </div>

<div id="room1">
         <h1> Room 1 </h1>
</div>
<div id="basement">
         <h1> My basement </h1>
</div>

<div id="room101">
         <h1> Room 101 </h1>
</div>
```

Here is the `topcomponent` definition:

``` js
component.exports = {
   init: function () {
 },
   data: {
     parentNodeAttribute: "parentNodeForLayout",
     computers: [{name: "pc1", cpu: 100, location:"room1"}, {name: "pc2", cpu: 70, location:"room101"}],
     getParentNode: function(computer){return computer.room}   
   }

 }
```

Now according to my understanding of Ractive we can now listen to changes in parentNodeForLayout in the `topcomponent` like this in the component init function:

``` js
init: function() {
      this.observe("computers", function(oldval, newval, keypath){
         /**** Magic goes here to detect if parentNode has changed and to move the subcomponent accordingly ****/
      }
}
```

Now the problem with this approach is that we are calling the function everytime we change a datum of the computers, ideally we would only want to be called when `getParentNode(.)` changes for each subcomponent. I'm not sure if this is possible at all but we would want to do something like this:

``` js
this.findAllComponents().forEach(c, function(comp){
   if(comp.data.hasOwnProperty(this.data.parentNodeAttribute)){ //just observe components interesting for layout
      comp.observe(this.data.parentNodeAttribute, function(oldval, newval, keypath) {
       /*** Generic DOM foo to move the subcomponent to new destination ****/
     }
    }
}
```

Now as long as we agree on a set of interfaces (name of getParentNode and so forth) the code can be abstracted as a plugin or a component mixin, whatever fits Ractive best. This sort of code can be used to implement drag and drop lists, dynamic layouts and so forth in a clean and declarative fashion. Extra features can include wrapping the subcomponents in an html element inside the destination container (inside a li node for instance), explicit lifecycle management etc.

**Comment by evs-chris** [comment]
0.9 (alpha) has features that should handle this nicely, so I'm going to close this :smile:

**Comment by arxpoetica** [comment]
@evs-chris can you elaborate? What alpha features does 0.9 have?

**Comment by ghost** [comment]
@arxpoetica I believe this is @evs-chris 's new ["anchors" functionality](https://github.com/ractivejs/ractive/pull/2674). In really simple terms, this allows you to add special mustaches (iirc, `{{>> anchorName }}`) in specific points on the component and be able to dynamically attach/detach other instances to them at will.

**Comment by arxpoetica** [comment]
awesome! i like that the syntax is similar to partials.

**Comment by kouts** [comment]
@arxpoetica actually the syntax is more like a component i.e `<#anchorName />`

**Comment by ghost** [comment]
It changed? Awww 😞  I liked `{{>> foo }}` because it looked like a grappling hook/barbed arrow. 😁
