### ISSUE TITLE
A way to replace elements instead of using it as a container (feature request)

### ISSUE THREAD

**Issue by rstacruz** [ractivejs/ractive#472]
Ractive is awesome! I'd also love to be able to do:

```js
new Ractive({
  template: '<h2>New h2</h2>',
  el: $('h1'),
  replace: true
});
```

...and have the `<h1>` be replaced with the new `<h2>`, instead of having h2 being contained inside the h1.

(Related: #471)

**Comment by Madgvox** [comment]
I'm closing this since you can insert templates before elements, so replacing an existing element would not be too difficult using `ractive.render` and a bit of js.
