### ISSUE TITLE
Command line tool for compiling templates

### ISSUE THREAD

**Issue by monsanto** [ractivejs/ractive#485]
It would be cool if Ractive came with a CLI tool for precompiling templates.

I suggest a file format like:

```
-- template: name1

{{foo}} {{bar}}

-- template: name2

{{#stuff}}...{{/stuff}}
```

... basically, a series of Ractive templates separated by -- template and the desired name of the template (which would ultimately be registered as a partial).

The result of compiling the file would be a nodejs style module which exports an object with all of the (parsed) templates.

Another option for a file format would be to have one file per template, with the file name being the registered partial's name. This is how dust.js does it. I personally dislike this style, because 1) partials are often very short, which makes dedicating an entire file to it feel like a waste, and 2) it's nice to group related partials together.

I wrote this as a starting point.

``` javascript
#!/usr/bin/env node

var path = require('path'),
    fs = require('fs'),
    sys = require('util'),
    Ractive = require('ractive');

var parse = function (data) {
    var parts = data.split(/(?:^|[\r\n])-- template: (.*)/).slice(1);
    var template = "";
    for (var i = 0; i < parts.length; i+=2) {
        template += "module.exports.";
        template += parts[i];
        template += "=";
        template += JSON.stringify(Ractive.parse(parts[i+1]));
        template += ";";
    }
    sys.print(template);
};

process.stdin.resume();
process.stdin.setEncoding('utf8');

var buffer = '';
process.stdin.on('data', function(data) {
    buffer += data;
});

process.stdin.on('end', function() {
    parse(buffer);
});
```

You can `cat templates/*.ractive | ractivec > parsed-templates.js`, and in your application

```
partials = require('./parsed-templates.js')
new Ractive({..., template: partials[templatename], partials: partials, ...})
```

with browserify putting in the heavy lifting to make this work on client side.

Comments?

**Comment by evs-chris** [comment]
edge now has a bin included, so if you `npm i -g ractive@edge`, you can `echo "<div>hello, {{name}}</div>" | ractive parse` and get output suitable for pasting into `new Ractive({ template: ... })`. It _should_ also handle expressions for csp. You can get a list of options by calling it with no command e.g. `ractive`.
