### ISSUE TITLE
Accessing ractive object within events

### ISSUE THREAD

**Issue by jhiver** [ractivejs/ractive#505]
First and foremost thanks for this awesome library...

Seems like you can get to the ractive object using event.node._ractive, but is there a cleaner way of doing it (say, event.ractive()) ?

I have browsed the event docs but cannot find it anywhere.

This is would be useful to have a clean way of accessing the ractive object using an event, so that you can do:

```
ractive.on 'someevent', onSomeEvent
```

Thanks

**Comment by elayman** [comment]
As a comment to martypdx's example, you should always clean up your events by returning an object with a teardown like so:

events: {
    returnOrTab: function (e) {
        var returnOrTabHandler = function (e) { ... };
        ...
        return {
            teardown: function () { node.removeEventListener('keypress', returnOrTabHandler); }
        };
    }
}
