### ISSUE TITLE
Components not working when used with Webpack

### ISSUE THREAD

**Issue by rstacruz** [ractivejs/ractive#540]
The docs say this that you can fire custom programmatic events in components:

```
<widget on-activate="doSomething"/>

ractive.on( 'doSomething', function () {
  alert( 'Widget activated!' );
});
```

> (The same goes for any events that are _fired programmatically_ by the component, rather than as a result of user interaction.)

However, doing something like `on-close="xyz"` gives you:

```
[Warning] Missing "close" event. You may need to download a plugin via http://docs.ractivejs.org/latest/plugins#events (vendor.js, line 66)
```

Using Ractive 0.4.0-pre2 on iOS7.1 Safari. This works alright on my desktop browsers though.

(This issue's previously titled _Custom events for components throws an error_, now renamed to be more specific to the issue.)

**Comment by alexserver** [comment]
good call.
