### ISSUE TITLE
Question: how to deep set or extend an object

### ISSUE THREAD

**Issue by jonathantneal** [ractivejs/ractive#550]
How might I deep set or extend an object within data in Ractive?

If my data contains nested objects like so:

``` json
{
    "deep": {
        "foo": true,
        "bar": false
    }
}
```

How might I update the object without clobbering the other properties?

``` js
ractive.set('deep', {
    bar: true
});
```

**Example**: http://codepen.io/jonneal/pen/1e15853515369b6d362729fb8fe029a0

**Related**: #79

Don’t mistake my question for a complaint. I prefer that set overwrites objects, but I would also like the ability to update an object.

---

If not already available, could this be a separate method? I am looking for something, perhaps, like this:

``` js
// NOTE: identical function exists in project
function utils_isObject(value) {
    return value && Object.prototype.toString.call(value) === '[object Object]';
}

// extend first object with all remaining objects
function utils_extendObject() {
    var
    // move all objects into collection
    objects = [].slice.call(arguments),
    // separate first object
    object = objects.shift();

    // for each object in collection
    objects.forEach(function (nextObject) {
        // set or extend its keys to first object
        Object.keys(nextObject).forEach(function (key) {
            if (utils_isObject(object[key]) && utils_isObject(nextObject[key])) utils_extendObject(object[key], nextObject[key])
            else object[key] = nextObject[key];
        });
    });
}
```

**Comment by evs-chris** [comment]
edge now has `ractive.set('some.path', someComplexObject, { deep: true })` which overwrites the overlapping leaves of the model tree with `someComplexObject` aka a deep set.
