### ISSUE TITLE
Template rendering: triple mustache creates an invisible content

### ISSUE THREAD

**Issue by laszlothewiz** [ractivejs/ractive#551]
I wanted to insert a piece of code inside an SVG and nothing shows up. The code appears to be there but it looks like as if it was inserted in such a way that the browser didn't parse it.

I made a fiddle to demonstrate it: http://jsfiddle.net/DUB8K/2/

While at it, I found another bug: the attribute _xlink:href_ gets changed to _href_. Which in this case doesn't yet cause an problem but it could be an issue with other SVG elements. This is also shown on the screenshot below.

As you can see in the screenshot the code inserted with triple mustache shows as greyed out in Firebug.
![ractive-bug-svg](https://cloud.githubusercontent.com/assets/1079849/2630704/4bac38d8-be4e-11e3-9f78-dfcffee8d0bb.png)

**Comment by Ghostavio** [comment]
`getAttributeNS` is not an option on IE8 :/
