### ISSUE TITLE
concatenating variables in argument passed to event results in garbage passed to event handler

### ISSUE THREAD

**Issue by monsanto** [ractivejs/ractive#568]
http://jsfiddle.net/ezLqe/27/

See console. Clicking 'working button' should print 'success'. Clicking the other button I would expect to either print 'successdouble success', or throw an error (and stop working). 

What happens is the warning "Could not parse directive arguments (successdouble success). If you think this is a bug, please file an issue at http://github.com/RactiveJS/Ractive/issues" ractive.js:2060 is raised, and the garbage value "${fd03e1d4-cfc1-44de-8973-1b100003b340-0}${fd03e1d4-cfc1-44de-8973-1b100003b340-1}" is passed to the event handler.

**Comment by Madgvox** [comment]
Closing this one since the remaining issues surrounding these syntaxes are being discussed in #1172.
