### ISSUE TITLE
Absolute keypath reference

### ISSUE THREAD

**Issue by nijikokun** [ractivejs/ractive#570]
Traversing is nice, but at some point I just end up with things like this:

```
{{#../../../../../plans}}
```

Could we implement something so we can go from root? maybe starting with `/`

```
{{#/plans}}
```

To be honest, this is pretty high on my priority list :(

**Comment by alexserver** [comment]
now we need to have this in documentation, http://docs.ractivejs.org/latest/mustaches , thanks for this feature, is very useful.
