### ISSUE TITLE
WYSIWYG Example

### ISSUE THREAD

**Issue by jonathantneal** [ractivejs/ractive#579]
Did I miss the example for [this feature](https://github.com/ractivejs/ractive/pull/208) from six months ago? I would love to see a WYSIWYG that leverages templates.

**Comment by zaus** [comment]
Just mentioning (for those of you that got here from a search) that the fiddles are all broken because the CDN is no longer serving correctly; I updated it in http://jsfiddle.net/e89Sr/6/ to work again
