### ISSUE TITLE
Pattern Observers on Array

### ISSUE THREAD

**Issue by browniefed** [ractivejs/ractive#580]
In writing the documentation for Pattern Observers I came across a weird case. I wasn't certain of the expected behavior. 

When observing on `items.*` and a new item is pushed onto the array should it return the new object or the index. Currently it returns the index and keypath is set at `items.length` which is technically correct but my assumption would be `items.3` or `items`. (Edited since the last piece of the sentence made no sense...)

Jsfiddle: http://jsfiddle.net/S327k/2/

When setting at a specific index path you get this. Which actually gives you the new object.

Jsfiddle: http://jsfiddle.net/H5Uw7/1/

**Comment by kurdin** [comment]
With ``magic: true`` and if pushed ``newItem`` is object this issue still exists.
````javascript
var ractive = new Ractive({
    el: 'main',
    magic: true,
    template: '#template',
    data: {
        items: [ ]
    }
});

console.group( 'initial observe' );
ractive.observe( 'items.*', function ( n, o, k, index ) {
    console.log( 'changed keypath is %s. index is %s. new value is %s', k, index, n );
});
console.groupEnd();

// try difference array mutations...
console.group( 'push' );
ractive.get( 'items' ).push( {test:'test'} );
console.groupEnd();
````
output
````console
push
(index): changed keypath is items.0. index is 0. new value is Object
(index): changed keypath is items.0. index is 0. new value is Object
````
http://jsfiddle.net/tGGv9/4/ 
http://jsfiddle.net/tGGv9/3/
