### ISSUE TITLE
Ractive computed property updated on changes from other Ractive instances

### ISSUE THREAD

**Issue by seanami** [ractivejs/ractive#647]
I'm working on a prototype using Ractive JS, and I'm trying to write modular JS where each reusable element of the UI is its own Ractive instance (like from `new Ractive(...)`. I'm using `Ractive.extend(...)` to define the different components.

I'm trying to have a parent Ractive instance that contains one more more child Ractive components, and the parent needs to have computed properties that update based on changes in one or more properties (or computed properties) of the child component instances. I'm finding that this just doesn't work. A change in a property on the child component doesn't cause the parent's computed property to update, even when `child.get(...)` is used within the parent's computed property definition.

Here's a simplified example: http://jsfiddle.net/smcbride/mHLG2/1/ (The remaining time rendered by the parent should update with changes in the elapsed time in the child, but it doesn't.)

Is this not a part of the design of components and computed properties? Is there a different pattern that I should be using to accomplish this sort of thing instead?

**Comment by Madgvox** [comment]
The fiddle in the OP works as of 0.8-edge.
