### ISSUE TITLE
Binding fails when using select2

### ISSUE THREAD

**Issue by sandermarechal** [ractivejs/ractive#680]
I have a form that I render using Ractive and that uses two-way binding. The selects in the form are enhanced using [Select2](http://ivaynberg.github.io/select2/). However, the binding fails when using select2 to render the selects. I use this trivial decorator for select2:

``` js
Ractive.decorators.select2 = function (node, content) {
    $(node).select2();

    return {
        teardown: function () {}
    }
}
```

My template:

``` html
<select decorator="select2" value="{{selection}}">
  {{#options}}
    <option value="{{.}}">{{.}}</option>
  {{/options}
</select>

When I set new data in Ractive, the select2 box is not updated. Likewise, when I select an option, the data in Ractive is not updated.

I tried figuring out how Ractive binding works on the inside so I can fix the issue or work around it, but I can't figure it out. Please fix this or help me fix it myself.
```

**Comment by sochoa** [comment]
@sandermarechal - I was scrambling to find the proper method for select2 combo boxes in ractve templates with decorators.  Its not a common practice, it seems, so your having posted your code helped me squash a bug.  From a back-end systems engineer to you, thanks.
