### ISSUE TITLE
event parameters for components

### ISSUE THREAD

**Issue by alexserver** [ractivejs/ractive#694]
This issue is related to #690 

When I try to send a param to a component event it says there is yet not available.
```
<somecomponent on-somevent="dosomething:justaparam" />
```

this is a jsfiddle I developed to illustrate the problem.
http://jsfiddle.net/9StFz/9/

Is this fix comming soon ? I'm looking forward to help.
thanks !

**Comment by martypdx** [comment]
closed via #2095
