### ISSUE TITLE
Functions in expressions in lists called extra times

### ISSUE THREAD

**Issue by jrajav** [ractivejs/ractive#716]
If you have a function in an expression in a list item (e.g., ```{{# list }} {{ fn(.) }} {{/}}```), that function gets called more times than it should have to when the list itself is updated via `ractive.set()`.

Refer to this jsbin: http://jsbin.com/fapusefe/15/edit?html,js,console,output

And this gist for stacktraces of various conditions inside the 'hasname' function: https://gist.github.com/jrajav/ac1b73cdffa7ca00b22c

There are two conditions the function is being called in - the "refresh" stacktrace, and the "flushChanges" stacktrace. I can't quite figure out the rules around when the "refresh" iteration happens. Sometimes it will be all of the elements in the list, sometimes just one out of three, sometimes none. However, the "flushChanges" iteration always happens, and it always runs over the whole length of whatever the longest length is that the list has held. This happens even if the list has just been set to undefined, which usually causes the function to fail if it was expecting a list of objects.

For instance, if I start with ```{{# list }} {{ fn(.) }} {{/}}``` as a template, list starting off empty, and then set the list to be an array of length three, fn might be called six times, three in "refresh" and three in "flushChanges". If I then set it to a different array of length two, fn might be called four times, once for the last new value in the list in "refresh", and three times for 'undefined' and then the two new values list in "flushChanges". If I set the list to undefined after all this, fn will be called three times over a value of 'undefined' in "flushChanges".

I know this is just about the worst explanation possible. Just play around with the jsbin to see what I mean.

If it were just that fn was called extra times for the same elements in the list, that wouldn't be a logical issue in a declarative template, just a performance issue. The real problem is that it's being called with a value of 'undefined' for lists shorter than what the list has been before, and (surprisingly) when the list doesn't even exist anymore.

**Comment by evs-chris** [comment]
Looks like this is at the very least fixed in edge.
