### ISSUE TITLE
Dot in property key gives strange behaviour

### ISSUE THREAD

**Issue by jasny** [ractivejs/ractive#744]
I'm not able to use a dot in as the key of a (value) object within the Ractive template. While this works perfectely in JS, Ractive start to behave very strange.

```
<div id="output"></div>

<script type="text/ractive" id="template">
    <h3>v1</h3>
    <p>{{version["1"]}}</p>
    
    <h3>v1.1</h3>
    <p>{{version["1.1"]}}</p>
    
    <h3>v1.1.1</h3>
    <p>{{version["1.1.1"]}}</p>
</script>

<script type="application/javascript">
    var ractive = new Ractive({
        el: '#output',
        template: '#template',
        data: {
            version: {
                "1": "Mayor release",
                "1.1": "Minor release",
                "1.1.1": "Patch release"
            }
        }
    });
</script>
```

## Output
<div id="output"><h3>v1</h3> <p>Mayor release</p> <h3>v1.1</h3> <p>a</p> <h3>v1.1.1</h3> <p></p></div>

## Expected
<div id="output"><h3>v1</h3> <p>Mayor release</p> <h3>v1.1</h3> <p>Minor release</p> <h3>v1.1.1</h3> <p>Patch release</p></div>

[There is a jsfiddle :smile:](http://jsfiddle.net/jasny/GnyrJ/)
---

**Comment by sigod** [comment]
I strongly suggest mentioning this in the documentation.

And you need to do something with object iteration. It just [breaks][0] without any warning or message in the console.

[0]: http://jsfiddle.net/sigod/yz9n13pr/

**Comment by MartinKolarik** [comment]
Fixed in edge.
