### ISSUE TITLE
complete() not called after render() in edge build

### ISSUE THREAD

**Issue by skeptic35** [ractivejs/ractive#749]
See this fiddle: http://jsfiddle.net/6Fn6A/
My test object is rendered but the `complete` method is never called. If I change the fiddle in a way that I pass the `el`, then everything works as expected (see http://jsfiddle.net/6Fn6A/1/).

**Comment by esbhome** [comment]
Have the same problem - when I call ractiove.render() the event onrender not called - what I can do to catch this event onrender when I second and third time render my ractive instanse?
