### ISSUE TITLE
Problem with ractive.merge?

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#753]
Am I completely misunderstanding `merge`? Is it a union or intersection?

Take a look at http://jsfiddle.net/LxAG7/, it replaces the first item in the array and I would expect it to add it because `timestamp` is not equal. It doesn't work with latest either, which makes me think I'm not getting it.

``` js
var ractive = new Ractive({
    el: document.body,
    template: '#template',
    data: {
        message: []
    }
})

var i = 1;
setInterval(function(){

    var message = { 
        message: 'hello' + i++,
        timestamp: Date.now()
    }

    ractive.merge('messages', [ message ], { compare: 'timestamp' } )

}, 1000)
```

**Comment by guilhermeaiolfi** [comment]
Well, until now I've never used ```merge``` because I thought it would merge/union the data. #1947 brought me here. So, +1 from me to change this behavior for/before 1.0.
