### ISSUE TITLE
ES6 export syntax other than export default

### ISSUE THREAD

**Issue by martypdx** [ractivejs/ractive#793]
I haven't tried to track it down, but additional ES6 module syntax gets mucked by our amd clean method:

```js
export default var foo = 'bar'
```

Can't do multiple exports. 

Might also be limits of our transpiler, but haven't dug any deeper than trying to use syntax and it failed.

**Comment by evs-chris** [comment]
With the sunset of esperanto and the rise of rollup, I'm going to go with this isn't an issue anymore :)
