### ISSUE TITLE
How can I remove event handler from a specific element?

### ISSUE THREAD

**Issue by QuyHP** [ractivejs/ractive#846]
For example, I have registered a proxy event on an element

> &lt;a href="javascript:;" on-mouseover="doSomething"&gt;Do something&lt;/a&gt;

Say I have a reference to this element (from event.node inside the event handler), how can I remove/unsubscribe "doSomething" from just this specific element? (I still want to keep this event for other elements)

**Comment by evs-chris** [comment]
Delegation is now in edge, you can wrap events in conditionals, and you could have a sing-fire event decorator, so I'm going to call this one done.
