### ISSUE TITLE
Do Ractive work with jQuery UI widgets?

### ISSUE THREAD

**Issue by codler** [ractivejs/ractive#87]
Do Ractive work with jQuery UI widgets? 

http://jqueryui.com/accordion/
Lets say I have markup for accordion in template and after when Ractive renders. how can I activate the accordion with `$( "#accordion" ).accordion();` in Ractive?

**Comment by Isinlor** [comment]
Just in case someone gets here trough Google - now it can be easily done with [decorators](http://stackoverflow.com/questions/23083841/ractivejs-and-jquery-plugins).
