### ISSUE TITLE
Lifecycle hooks

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#927]
At present, lifecycle hooks are a bit of a mess - partly for historical reasons, partly a design failure (mea culpa). This is what you have to work with:

```js
MyRactive = Ractive.extend({
  beforeInit: function ( options ) {
    // this is called whenever the component is instantiated,
    // immediately before any setup/rendering happens
  },
  init: function ( options ) {
    // this will be called once the component has been rendered
    // (assuming it *is* rendered to the DOM)
  },
  complete: function () {
    // this is called asynchronously once any intro transitions
    // have completed - again, assuming it is rendered
  }
});
```

To do any cleanup on teardown, you have to do something like this:

```js
MyRactive = Ractive.extend({
  init: function () {
    this.on( 'teardown', cleanup );
  }
});
```

If you're not creating a component with `Ractive.extend()`, there's just the `complete()` method - no `beforeInit()` or `init()`. Harmless, perhaps (you can do the `beforeInit()` work before `new Ractive()`, and the `init()` work afterwards), but this has proven to be a source of confusion.

**The problem?** Firstly, these hooks are badly named. `init()` and `complete()`, in particular, offer little clue as to what they're for. Secondly, it's possible to use Ractive without targeting a DOM node - maybe you're using it on the server, maybe you have a viewless instance that you're using for managing state within your app, maybe the instance is responsible for attaching itself to a DOM node that it doesn't yet know about. In any of these cases you would probably expect the `init()` method to be called, but it isn't. It's more like an `onRender()` method (it's actually called from within the `render()` method).

And the `beforeInit()` method is pretty much redundant now that we have option functions for dynamically defining templates and partials and so on.

Fixing this isn't hard from an implementation standpoint - it's just a design question that we need to try and get right. It's also an opportunity to consider a couple of related issues.

## The hooks themselves

There's a bunch of lifecycle events we need to consider:

* Instantiation (`new Ractive(...)`)
* Rendering (before *and* after? Or just after?)
* Completion of any initial transitions (though arguably, if you need this hook, you should simply omit the `el` option and then call `ractive.render(el)`, since that returns an equivalent `Promise`)
* Detach and insert
* Unrender
* Teardown/destroy (which includes unrender but isn't the same - you can unrender and re-render without destroying the instance)

(If I've missed any, please point them out!)

**Should each of these hooks be a method?** Or should some, or all (except the instantiation hook) be events that you subscribe to? A method allows things like `this._super()`, which is potentially useful, and it means one less level of indentation:

```js
MyRactive = Ractive.extend({
  onDetach: function () {
    // do something
  }
});

// versus
MyRactive = Ractive.extend({
  onInit: function () {
    this.on( 'detach', function () {
      // do something
    });
  }
});
```

It also means we have fewer 'system' event names which can't be used for DOM proxy events (e.g. `on-click='change'` is banned, because there's a system `change` event).

On the flip side, events are a simple, well-understood mechanism, and they allow you (and other consumers of a component, not just the component itself) to attach multiple handlers. (In any case, throwing out things like the `teardown` event would break existing code, so they'd have to be deprecated gradually if at all.)

If we went with methods (or a hybrid approach), what should they be called? Is `onInit()`, `onRender()` and so on the right convention to use?

## Defining methods at the point of `new Ractive()`

It would eliminate the confusion about `beforeInit()` working with `Ractive.extend()` but not `new Ractive()` if properties of the `options` object were simply added to the instance - so if you specify an `onInit()` method, it gets called:

```js
var ractive = new Ractive({
  onInit: function () {
    // some (arguably pointless, but hey) init logic happens
  }
});

// is the same as
MyRactive = new Ractive.extend({
  onInit: function () {
    // ...
  }
});

var ractive = new MyRactive();
```

This dovetails nicely with the discussion happening around [allowing proxy event directives to call methods directly](https://github.com/ractivejs/ractive/issues/568#issuecomment-47437324) - we could do things like this without having to faff around creating components:

```js
var audio = new Audio();
audio.src = 'klaxon.wav';

var ractive = new Ractive({
  el: 'body',
  template: '<button on-click="klaxon()">click me!</button>',
  klaxon: function () {
    audio.play();
  }
});
```

## Mixins

The other thing that would potentially fall out of this is mixin support. If a mixin is defined as a set of methods that are called during the appropriate lifecycle events, you can start adding reusable chunks of functionality that are completely orthogonal to the implementation details of a particular component. I'll be honest, I don't really know what the applications of this could be (logging? persistence?) but it seems like an idea with potential. There's some discussion of it on [this issue](https://github.com/ractivejs/ractive/issues/588).

-------

So, that was another long-winded stream of consciousness. Congrats if you made it this far. Would welcome all feedback! Thanks.

**Comment by martypdx** [comment]
Going to close this as most of it has been implemented. Mixins were the one straggler item, let's raise new issues if we still want to add something. (or reopen this issue)
