### ISSUE TITLE
Appending to the DOM rather than re-rendering entire DOM?

### ISSUE THREAD

**Issue by Nijikokun** [ractivejs/ractive#957]
I have a page that can load easily, `6000` elements at once. I'm trying to lazy-load this data `on-scroll` so the dom gets updated as you scroll. However, I'm unsure whether ractive will re-render the entire dom when data is appended or whether it will simply append the elements to the dom.

Another issue is removing all of these elements and re-doing this process when changing views (performance).

**Comment by kurdin** [comment]
It would be cool if we can reuse existing DOM on first ``ractive.render() `` event. Makes ``ractive.render() `` use whats already in DOM. This way we can render HTML on server, serve it to client with ractive app and data, ractive would set all events on existing DOM and change content only if data is changed.

**Comment by Madgvox** [comment]
As progressive enhancement is coming to 0.8 (yay), I'm closing this.
