### ISSUE TITLE
How to change delimiter from {{}} to [[]] (or anything else)?

### ISSUE THREAD

**Issue by luiscvega** [ractivejs/ractive#98]
Hi, I'm using a templating system in my app that also uses curly braces. Is there a way to change Ractive's delimiters?

**Comment by evs-chris** [comment]
I didn't realize that this works with various unicode characters, at least in Chrome. So you can have, among other things, mustaches as your mustache delimiter:
```{{=🐍 🐒=}} 🐍 ref 🐒 🐍=෴ ෴=🐒 ෴ref.length෴```
 Although, I suppose those look more like eyebrows in that context.

**Comment by JonDum** [comment]
Oh god Chris, why :laughing:

**Comment by martypdx** [comment]
Reminds me of "pirate javascript": 

```js
'use ☠';


```
