### ISSUE TITLE
Allow chained transitions

### ISSUE THREAD

**Issue by emiltamas** [ractivejs/ractive#987]
It would be nice if we could create composite transitions like this:

``` html
<div intro="slide:{duration:300}, fadeBackground: #FFFFCC">
   Some notification that will slide and then produce a yellow flash
</div>
```

This way we can easily achieve various transitions effects by mixing "standard" ones.

**Comment by evs-chris** [comment]
A combined transition plugin is now possible as of 0.9 since you can use `Ractive.findPlugin` to look up the transitions and chain them. A style transition, where a hash of styles to apply is provided and the start or end values are computed from the initial position of the node is also possible.
